### ISSUE TITLE
FocusScope does not move VoiceOver virtual cursor

### ISSUE THREAD

**Issue by probablyup** [adobe/react-spectrum#1002]
# 🐛 Bug Report 

We have a modal built like:

```jsx
<FocusScope autoFocus contain restoreFocus>
  {children}
</FocusScope>
```

But while keyboard focus is moved when the modal is rendered, VoiceOver context (virtual cursor) is not.

## 🤔 Expected Behavior

The VO virtual cursor should be moved to the first focusable element.

## 😯 Current Behavior

It is not, keyboard focus is moved but VO remains on the initial button trigger that opened the modal.

## 💁 Possible Solution

Something like this perhaps:

```ts
/**
 * Programmatically move voiceover focus with Javascript.
 * https://silvantroxler.ch/2016/setting-voiceover-focus-with-javascript/
 */
export const setA11yFocus = (element: HTMLElement) => {
  const focusInterval = 10 // ms, time between function calls
  const focusTotalRepetitions = 10 // number of repetitions

  element.setAttribute('tabindex', '0')
  element.blur()

  let focusRepetitions = 0

  const interval = window.setInterval(function () {
    element.focus()
    focusRepetitions++
    if (focusRepetitions >= focusTotalRepetitions) {
      window.clearInterval(interval)
    }
  }, focusInterval)
}
```

## 🔦 Context

This is preventing us from making a robust Modal implementation, focus management is only half the story of accessibility.

## 🧢 Your Company/Team

ButcherBox

**Comment by devongovett** [comment]
Closing for now. Let us know if you have an example and we can reopen! 😄
