### ISSUE TITLE
useOverlayPosition() is buggy in a few cases when placement=top

### ISSUE THREAD

**Issue by chungwu** [adobe/react-spectrum#1004]
# 🐛 Bug Report 

`useOverlayPosition()` sets the `bottom` css prop when `placement=top`.  This currently is buggy in two cases I know of:

* If the container is not body; `computePosition()` is only computed using `boundaryDimensions`, when it should be using `containerOffsetWithBoundary` instead
* When `document.body` as the default container has `position: relative`; as a positioned offset parent, the `bottom` needs to be computed relative to the container's actual height, instead of the "visible height" computed by `getContainerDimensions`

## 🤔 Expected Behavior

placement=top would align overlay above trigger element correctly.

## 😯 Current Behavior

placement=top only works properly right now if the overlay container is `document.body`, and it has `position: static`

## 💁 Possible Solution

PR incoming :smile: 

## 🔦 Context

Noticed this when using `useSelect` when `shouldFlip` kicks in

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.2.0
| Browser          | Chrome 84
| Operating System | Ubuntu 20.04

## 🧢 Your Company/Team

[Plasmic](https://plasmic.app)

**Comment by ktabors** [comment]
Thanks for finding this and creating a PR to fix it!
