### ISSUE TITLE
useMenu without focus

### ISSUE THREAD

**Issue by zbeyens** [adobe/react-spectrum#1008]
# 🙋 Feature Request

I would like to use `useMenu` without having to focus the menu. If not possible, is there a way to reuse the existing code?

## 🤔 Expected Behavior

![CleanShot 2020-08-23 at 18 52 36](https://user-images.githubusercontent.com/19695832/90983897-dc66a100-e571-11ea-9fe1-5e007b907352.gif)

The input gets the focus but it's still possible to modify the selection of the menu.

## 🔦 Context

My use-case is an autocomplete component (input + menu) like VSCode's command palette.

**Comment by devongovett** [comment]
You're looking for a combo box. These hooks are currently a work in progress, and should be available relatively soon. The `useListBox` hook already supports an option called `shouldUseVirtualFocus` that we are using in the combo box component for this purpose, which allows keeping DOM focus on the text field.
