### ISSUE TITLE
Flex for flex-gap supported doesn't render a passed id

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#1010]
# 🐛 Bug Report 

Add an id to a Flex component in storybook
Open in a browser that supports flex-gap
id won't be there

## 💁 Possible Solution

We probably need to spread filterDomProps on this line like we do above
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/layout/src/Flex.tsx#L81

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LucianRadu** [comment]
Working on it.
