### ISSUE TITLE
Calling state.setSelectedKey with an empty string does not update state.selectedItem

### ISSUE THREAD

**Issue by kamal** [adobe/react-spectrum#1016]
# 🐛 Bug Report 

The Picker does not display the currently selected option if the option's key is an empty string.

## 🤔 Expected Behavior

The trigger button should display the selected item.

## 😯 Current Behavior

The trigger button does not display the rendered selected item. However, when you open the Picker dialog, you see that the item is correctly selected.

![image](https://user-images.githubusercontent.com/269/91215400-4e9dc980-e6c9-11ea-9cb5-82ae4986ffb0.png)

## 💁 Possible Solution

`state.selectedItem` should update when `state.setSelectionKey` is called with an empty string

## 🔦 Context

I was attempting to emulate default browser behavior where it would select the first option if none of the options are currently selected. In addition, I was attempting to provide a different placeholder value. In regular HTML, the convention is to provide a "fake" option as the first item whose value is an empty string.

```jsx
<Picker label="Foo">
  <Item key="">Select a color</Item>
  <Item key="yellow">Yellow</Item>
  <Item key="blue">Blue</Item>
</Picker>
```

## 💻 Code Sample

Here's a PR illustrating the bug https://github.com/adobe/react-spectrum/pull/1015

Although the PR focuses on selectedKey/defaultSelected key, you can trigger this bug with normal interactions as long as the Item key is an empty string.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.2.0
| Browser          | Chrome 84.0.4147.135
| Operating System | MacOS Catalina (10.15.6)

## 🧢 Your Company/Team

Polarwind, Envoy's component library

**Comment by devongovett** [comment]
I think this is probably something to do with falsey values. Had the same issue with `0`. Might be a good place to start looking.
