### ISSUE TITLE
useSearchField `ref` type is incorrect

### ISSUE THREAD

**Issue by shrugs** [adobe/react-spectrum#1017]
# 🐛 Bug Report 

The types in `useSearchField` from `@react-aria/searchfield` at https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/searchfield/src/useSearchField.ts#L40 says that the hook requires a ref to the type `HTMLInputElement & HTMLTextAreaElement` but it should probably be `HTMLInputElement | HTMLTextAreaElement` to allow the user to pass one _or_ the other, instead of a type that is the intersection of both.

With the current types, the example at https://react-spectrum.adobe.com/react-aria/useSearchField.html is invalid.
(also worth noting that for typescript to be happy, the ref must be typed like so: `const ref = useRef<HTMLInputElement>(null);`)

## 🤔 Expected Behavior

The type should accept an `HTMLInputElement` _or_ and `HTMLTextAreaElement`, not the intersection of the two types.

## 💁 Possible Solution

update the type [here](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/searchfield/src/useSearchField.ts#L40) to be the union of the two, not the intersection.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | `@react-aria/searchfield@3.1.0`

## Context

This should be an easy first issue for someone looking to contribute.

## Workaround

Just cast to any like `useSearchField(props, state, ref as any)`

**Comment by snowystinger** [comment]
Thanks! Looks like it's always been an intersection but union appears to be be more appropriate
