### ISSUE TITLE
useSelectState.isFocused is false when moving focus from the trigger element to the menu

### ISSUE THREAD

**Issue by kamal** [adobe/react-spectrum#1019]
# 🐛 Bug Report 

The `state.isFocused` returned by `useSelectState` changes from `true` to `false` when the user triggers the menu to open via keyboard or mouse interaction.

## 🤔 Expected Behavior

I expect `state.isFocused` to remain true if the Picker is still being interacted with

## 😯 Current Behavior

0. Instrument state.isFocused
1. Tab to focus on Picker
2. See state.isFocused === true
3. Press enter on keyboard to open the menu
4. See state.isFocused === false

## 💁 Possible Solution

Consider state.isOpen as another criteria for state.isFocused. This is probably not robust as you can set `defaultOpen` prop to true to have the menu be visible yet not focused. Another alternative is using `useFocusWithin` to accurately maintain `state.isFocused`

## 🔦 Context

I was trying to add onFocus and onBlur handlers to the Picker "from the outside" but it appears `Picker` doesn't expose callbacks for that. Naively, I also tried to spread `useFocus`' `focusProps` on `Picker` and that didn't work either.

## 💻 Code Sample

```js
  const state = useSelectState(props)
  useEffect(() => {
    console.log(state.isFocused)
  }, [state.isFocused])
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | master, 3.2.0
| Browser          | Chrome 84.0.4147.135
| Operating System | macOS Catalina

## 🧢 Your Company/Team

Envoy

**Comment by ktabors** [comment]
We appreciate you reaching out about your issue. This is the behavior we designed for, when the picker is open the button loses focus and focus moves to an item in the Picker. Thanks for including what you were trying to do, you can accomplish the desired behavior by watching the `isFocused` and `isOpen`. The `isFocused` state is used to determine if the picker button is focused. The `isOpen` state is used to determine if the menu is open.

**Comment by kamal** [comment]
@ktabors i followed your suggestion where my internal focused state is based on isFocused and isOpen. i do observe that there is an (minor?) inconvenience where the component will be blurred (both isFocused and isOpen is false) for a tick after you close the menu but before `FocusScope` returns the focus to the button. i can replicate this in react-spectrum's Picker component.

**Comment by ktabors** [comment]
I'm happy that it worked (mostly). Can you provide more information about what your use case and what are trying to build so we can figure out the best solution?

**Comment by kamal** [comment]
@ktabors I'm replacing a component that was previously a pure html select component with one powered by `useSelect`. Two of the props that it exposes was `onFocus` and `onBlur`. These were directly attached onto the select element and uses the default React focus and blur events. It's not a major blocker but it'd be nice to provide a similar expectation with the custom select.

**Comment by ktabors** [comment]
Thanks for the additional information. At this time we are hoping that you can improve your workaround to accomplish this behavior. We'd like to hold off on changing the API at this time.
