### ISSUE TITLE
Utilize useResizeObserver in ButtonGroup

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#1020]
# 🙋 Feature Request

ButtonGroup currently adds an event listener for window resize events (https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/buttongroup/src/ButtonGroup.tsx#L69-L79). Now that we have a useResizeObserver hook, we should use it in place of the useEffect linked above.

## 🤔 Expected Behavior

The ButtonGroup's current behavior should be maintained after the addition of useResizeObserver:
- **When ButtonGroup is in a horizontal orientation:** The ButtonGroup should switch to vertical orientation if there isn't enough room to render all the buttons in a single row. This calculation should happen on initial render and on window resize. 

- **When ButtonGroup is in a vertical orientation:**  Resizing the window should never switch the ButtonGroup to horizontal orientation even if there is enough room to render all the buttons in a single row

## 💁 Possible Solution

Example of existing useResizeObserver usage: https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx#L122. 

## 🧢 Your Company/Team

RSP

**Comment by tomsontom** [comment]
@LFDanLu looks like the #1225 PR did not close that issue probably because it is a dup of #1115?

**Comment by LFDanLu** [comment]
Ah, that is correct, thanks for the heads up!
