### ISSUE TITLE
Implement new prop "overflowMode" for ActionGroup

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum#1021]
# 🙋 Feature Request

When an ActionGroup contains too many buttons to fit in the available space, it currently overflows. This is more noticeable on mobile and other small screen browser windows. ActionGroup should support an `overflowMode` prop set to either "wrap" (default) or "collapse". The behavior should be implemented similar to Breadcrumb and use the `useResizeObserver()`, https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/utils/src/useResizeObserver.ts.

There is special behavior when the `density` prop is set to "compact" https://react-spectrum.adobe.com/react-spectrum/ActionGroup.html#density. With that state, overflowMode only works as "collapse", "wrap" wouldn't be supported.

## 💻 Examples

Examples of "wrap" and "collapse"
![image](https://user-images.githubusercontent.com/309540/91328437-d3492000-e77b-11ea-84c8-d3a145aa9221.png)

Example of how the collapsed button would behave. See https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/breadcrumbs/src/Breadcrumbs.tsx#L137 for the code could look like, with ellipse instead of the FolderBreadcrumb icon.
![image](https://user-images.githubusercontent.com/309540/91328930-67b38280-e77c-11ea-8618-6044a6ce8a3a.png)

## 💁 Possible Solution

Example of existing useResizeObserver usage: https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx#L122. 

## 🧢 Your Company/Team

RSP

## 🎁 Tracking Ticket

RSP-1657

**Comment by snowystinger** [comment]
For Contribution day this is considered a complex issue

**Comment by snowystinger** [comment]
Closed by https://github.com/adobe/react-spectrum/pull/1919
