### ISSUE TITLE
useFocusVisible yielding false positives on unrelated keyups

### ISSUE THREAD

**Issue by Andarist** [adobe/react-spectrum#1024]
# 🐛 Bug Report 

Simple scenario:
1. click a button
2. mouseleave from it
3. press any keyboard key

A more specific one which I'm pretty sure if not working correctly is going to be described in the "Expected Behavior" section.

## 🤔 Expected Behavior

I think that this focus ring should not appear in this scenario. I think there maybe might be some reasons to show the focus ring in some scenarios like this (click + keyboard interaction later) but I don't have any good examples in my mind right now - so maybe you would know something.

However, even if there are cases when this should appear I would consider a scenario with a link not working properly:
1. cmd+click a link
2. release cmd

Here I'm pretty sure that we shouldn't show the focus ring as the primary modality was pointer and not the keyboard for this interaction.

Additionally - in applications with global keyboard shortcuts those focus rings should not appear so eagerly either. Imagine:
1. click a button
2. start pressing cmd to match against a global shortcut
3. get distracted because an unrelated focus ring has appeared

## 😯 Current Behavior

This focus ring appears.

**Comment by devongovett** [comment]
We do ignore modifier keys already, but I do see the issue. https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/interactions/src/useFocusVisible.ts#L62 I think the issue is that `e.metaKey` is set on key down but not on key up. Maybe we need to also check if `e.key === 'Meta'` etc. there as well?

**Comment by Andarist** [comment]
> Maybe we need to also check if e.key === 'Meta' etc. there as well?

For the cmd+click a link issue - yeah, probably. There is still a potential issue about **any keydown** (and other events changing current modality to keyboard) following a click on an element triggering the focus visible state. This doesn't sound right either, does it? 🤔

**Comment by devongovett** [comment]
I think that is the expected behavior. How would the modality change to keyboard otherwise?

**Comment by Andarist** [comment]
You obviously have far more knowledge about how this should work as your team has researched this stuff a lot. From my layman's point of view, I only expect the focus to be visible if the focus itself was directly caused by keyboard navigation. Pressing random keys is not that in my opinion. I understand that my reasoning might be inaccurate and there might be other reasons to show the focus visible state - if you could share some more knowledge about this topic I would highly appreciate it, always eager to learn more (I know about returning to the page from another tab scenario).

Apart from "any keydown" triggering the current behavior I have also given a more concrete example: global shortcuts. I wouldn't (as a user) expect a focus ring to popup when I just use an in-app shortcut. That seems distracting, at the very least.

**Comment by devongovett** [comment]
I will cc our accessibility experts to provide their opinion. @majornista @jnurthen

**Comment by jnurthen** [comment]
Any keydown matches how chrome processes :focus-visible - while this is not officially specified I'm not sure why we would want to deviate from that.
