### ISSUE TITLE
Set custom theme to Provider component 

### ISSUE THREAD

**Issue by stk26kakarla** [adobe/react-spectrum#1030]
# ❔ Question

How do we set a theme to Provider component to follow lightest color and medium scale

## 🔦 Context

The theme prop for `<Provider>` take "Theme" object. And for every name there is a CSSModule type: [className: string]: string.
How to use this in JavaScript?

I looked into [defaultTheme](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/theme-default/src/index.ts) file, [Theme type provider](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-types/provider/src/index.d.ts), they all are in TypeScript and very difficult to produce a JavaScript custom theme with color spectrum lightest.

## 💻 Code Sample

`<Provider theme={xxxxx} colorScheme="lightest" scale="medium" isEmphasized>`

What can xxxxx be?
And colorScheme="lightest" doesn't work, anything to import?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |3.1.0
| Browser          |chrome
| Operating System |Windows 10

**Comment by snowystinger** [comment]
from the theme type provider link you shared, we can see that the only colorSchemes are `light` and `dark`, and scale is either 'medium' or 'large'
from the defaultTheme link you shared, we can see that there the values for the default theme's light and dark are light and darkest respectively, defaultTheme does not set light to the lightest Spectrum color scheme

to see what they look like you can console log out the theme object

I recommend reading https://react-spectrum.adobe.com/react-spectrum/theming.html

**Comment by stk26kakarla** [comment]
Thank you @snowystinger 
console logging was a good idea.
 i got this:
```
{
    "global":
    {
        "spectrum": "_spectrum_5be2e",
        "spectrum--medium": "_spectrum--medium_5be2e",
        "spectrum--large": "_spectrum--large_5be2e",
        "spectrum--darkest": "_spectrum--darkest_5be2e",
        "spectrum--dark": "_spectrum--dark_5be2e",
        "spectrum--light": "_spectrum--light_5be2e",
        "spectrum--lightest": "_spectrum--lightest_5be2e"
    },
    "light": { "spectrum--light": "_spectrum--light_606b7" },
    "dark": { "spectrum--darkest": "_spectrum--darkest_acf7f" },
    "medium": { "spectrum--medium": "_spectrum--medium_24f04" },
    "large": { "spectrum--large": "_spectrum--large_38267" }
}
```
By the above JSON object in the log how to modify the object to get lightest theme?

I understand the limitation of defaultTheme and colorSchemes. and I read the theming document, although i understood the available options but couldn't figure how to use/set to `<Provider>`

I only want to understand how to generate a new lightest theme object in JavaScript.

**Comment by snowystinger** [comment]
It depends, if you want your own lightest, then you'll need to create it.
If you want Spectrum Lightest, the easiest way is probably to build this project and copy the artifact out to your build.

**Comment by stk26kakarla** [comment]
I am intending for Spectrum Lightest.
OK, so it is not configurable as such and need modification to the library. 
Something like or rather use this: https://github.com/evargast/SpectrumWhiteTheme

**Comment by snowystinger** [comment]
yes, looks like you can use that one https://www.npmjs.com/package/spectrum-white-theme

**Comment by devongovett** [comment]
@evargast would you like to contribute this theme into the core react-spectrum repo? We do currently have a couple different variables in React Spectrum that aren't in Spectrum DNA yet/aren't correct, so we should ensure that the CSS is being built using the variables in the RSP repo. Plus, it would be good to officially support this. 😄

**Comment by evargast** [comment]
Oh cool someone found my theme haha sure! Do we want to call it `LightestTheme`? Lightest always confused me so I called it white 😅  , I can put something together!

**Comment by devongovett** [comment]
Cool! I think `@react-spectrum/theme-light` might make sense? Then we would have `@react-spectrum/theme-light`, `@react-spectrum/theme-default`, and `@react-spectrum/theme-dark`.

Also what should the theme do in OS dark mode? Spectrum [states](https://spectrum.adobe.com/page/color/#Device-dark-mode) that only the `darkest` theme should be used in dark mode. So we should include that in the light theme as well I think. If you wanted to always have light mode regardless of OS setting (not recommended), you could hard code the `colorScheme` prop to `"light"`.

**Comment by evargast** [comment]
Sure thing, I love the idea of lightest/darkest combo! ☯️  

Just put a PR up https://github.com/adobe/react-spectrum/pull/1046
