### ISSUE TITLE
Collapsed Breadcrumb menu items unnavigable with arrow keys

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum#1032]
# 🐛 Bug Report 

Use a Breadcrumb component with collapsed Breadcrumb items into a folder icon (menu).
Use the keyboard to select the folder icon.
Use the enter key or an arrow key to open the menu.
Navigate the menu with arrow keys and it closes the menu.

## 🤔 Expected Behavior

The keyboard arrow keys are able to navigate the overflow collapse menu items.

## 💁 Possible Solution

It might be related to the published version of the component and not a locally run version.
Maybe focus isn't being set within the menu when it is opened?

## 🔦 Context

The bug occurs in a few of the test apps, like testing Parcel building and SSR. 
This does not occur in storybook or the docs.

## 🧢 Your Company/Team

RSP

**Comment by dannify** [comment]
Unable to reproduce this in codesandbox - https://rl6zx.csb.app/
