### ISSUE TITLE
ActionGroup does not support tooltips

### ISSUE THREAD

**Issue by jluyau** [adobe/react-spectrum#1034]
# 🐛 Bug Report 

Tooltips within an ActionGroup <Item> do not trigger.

## 🤔 Expected Behavior

Support for tooltips in ActionGroup Items

## 😯 Current Behavior

No tooltip shows on hover

## 🔦 Context

Trying to place tooltips on ActionGroup items as they have no visible text

## 💻 Code Sample

```
      <ActionGroup>
        <Item>
          <TooltipTrigger delay={0}>
            <div>asdf</div>
            <Tooltip>asdf</Tooltip>
          </TooltipTrigger>
        </Item>
      </ActionGroup>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

quarry

**Comment by devongovett** [comment]
I think we need to do something like we have for DialogTrigger so tooltips can work in collection components: https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/dialog/src/DialogTrigger.tsx#L101-L114
