### ISSUE TITLE
which type definitions to place inside @react-types

### ISSUE THREAD

**Issue by xitter** [adobe/react-spectrum#1045]
# ❔ Question

Is there any convention to put certain type definitions inside @react-types while some of them exist in the source file itself? I don't see much documentation around using `@react-types`.

For eg. 
Pagination component's type definitions exist at:
- [@react-stately](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/pagination/src/usePaginationState.ts#L17)
- [@react-types](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-types/pagination/src/index.d.ts)
- [@react-aria](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/pagination/src/usePagination.ts#L17)

## 🔦 Context

Have been trying https://github.com/adobe/react-spectrum/issues/1012, and struggling with where to keep type definitions.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by xitter** [comment]
Thanks @devongovett, is there any downside if all definitions are moved to `@react-types`?

**Comment by devongovett** [comment]
I think we usually keep specific types in react aria and react stately where needed. There's not really a downside I guess other than maybe locality of the definition with the code that implements it. 🤷
