### ISSUE TITLE
runAfterTransition calls setupGlobalEvents before document is ready

### ISSUE THREAD

**Issue by HipsterBrown** [adobe/react-spectrum#1048]
# 🐛 Bug Report 

I'm using the `useButton` hook in a project and experienced an error when the bundled javascript is included in the head of the page. 

> Uncaught TypeError: can't access property "addEventListener", document.body is null

## 🤔 Expected Behavior

Event setup side-effects happen when the component / hook is used.

## 😯 Current Behavior

Including `useButton` in the bundle leads to [`setupGlobalEvents`](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/utils/src/runAfterTransition.ts#L74) being called, whether or not the component depending on `useButton` is active on the page. 

```
Uncaught TypeError: can't access property "addEventListener", document.body is null
    $b3e8d5c5f32fa26afa6df1b81f09b6b8$var$setupGlobalEvents module.js:634
    node_modules 13-19d749bd3766408a4b8d.chunk.js:123131
    Webpack 28
module.js:634
    $b3e8d5c5f32fa26afa6df1b81f09b6b8$var$setupGlobalEvents module.js:634
    js module.js:638
    Webpack 29
```

## 💁 Possible Solution

Either call [`setupGlobalEvents`](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/utils/src/runAfterTransition.ts#L74) when `runAfterTransition` is invoked, or update `setupGlobalEvents` to confirm the document is interactive (`document.readyState === 'interactive') or wait until `DOMContentLoaded` is fired. 

```ts
if (document.readyState !== 'loading') {
  setupGlobalEvents();
} else {
  document.addEventListener('DOMContentLoaded', setupGlobalEvents);
}
```

## 🔦 Context

I'm trying to building an accessible component to act like a button for an internal design system for my company. `@react-aria/button` looked like a great solution for including all the attributes and behaviors to accomplish this task.

See "Possible Solution" section. 

My current fix for the app is to defer the script for the bundle, but I still see this as a potential [footgun](https://en.wiktionary.org/wiki/footgun) for folks getting started with this project. 

## 💻 Code Sample

https://gist.github.com/HipsterBrown/6480f7cc89afd083fb4aa827d6a89699

## 🌍 Your Environment

Rails 5.1 + Webpacker 4.0.2 + React 16.9.0

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.2.1
| Browser          | Firefox Developer Edition
| Operating System | Macos 10.15.6

**Comment by devongovett** [comment]
Good point! I like your proposed solution. Would you like to submit a PR?

**Comment by HipsterBrown** [comment]
@devongovett PR opened! https://github.com/adobe/react-spectrum/pull/1052
