### ISSUE TITLE
Breaking Menu/Picker/any popup components in React 16.13 on Chrome

### ISSUE THREAD

**Issue by justin2taylor** [adobe/react-spectrum#1053]
Using a simple project with the samples from the site for menus and pickers, the popup menus appear in the wrong location on Chrome:

Picker
![image](https://user-images.githubusercontent.com/10479769/92279607-84526780-eeac-11ea-8fd8-677a39be1b1b.png)

Menu
![image](https://user-images.githubusercontent.com/10479769/92279614-887e8500-eeac-11ea-9303-a64436f6b61c.png)

This issue only Occurs in Chrome as Firefox looks alright.
![image](https://user-images.githubusercontent.com/10479769/92279662-a1873600-eeac-11ea-8046-547b68130264.png)

Downgrading React to 16.10.2 fixed the issue for now:

![image](https://user-images.githubusercontent.com/10479769/92279689-b2d04280-eeac-11ea-9c72-9f396561dbe9.png)

I didn't see a React compatibility version on the readme, this could be useful so we know when we're safe to upgrade. 

Thanks!

**Comment by LFDanLu** [comment]
@justin2taylor Hrm, I can't seem to reproduce this using React 16.13 myself with react-spectrum 3.3.0, mind sharing what version of react spectrum you are using?

**Comment by justin2taylor** [comment]
@LFDanLu I was on 16.13, but turns out it wasn't an issue with the version, since my window was small it was displaying the mobile version of popup menus which come up from the bottom instead of the selector.

This is for a CEP panel in Adobe CC apps, so it won't be used on mobile, but the window may be small depending on how it's docked. 

Is there a way to force Spectrum to always show the desktop versions of components? Thanks

**Comment by LFDanLu** [comment]
@justin2taylor Ah, you are in luck, the latest update (3.3.0) changes the isMobile calculation to use the screen width instead of the window width.

**Comment by justin2taylor** [comment]
Awesome, thank you!
