### ISSUE TITLE
`useDrag1D` should use pointer events instead of (or in addition to) mouse events

### ISSUE THREAD

**Issue by itaylor** [adobe/react-spectrum#1063]
# 🙋 Feature Request

As of now, the `useDrag1D` utility from `react-aria/utils` is implemented using mouseEvents.  This means components that use it will not work at all on touch-based devices.  I'd like to request changing this to either user pointer events exclusively, or to have a configuration option to control using mouse events or pointer events.

## 🤔 Expected Behavior

Components implemented using `useDrag1D` would work for both mouse users and touch-screen users.

## 😯 Current Behavior

Things that make use of `useDrag1D` (like the prototype Slider implementation from #809 ) do not work on touch enabled devices. 

## 💁 Possible Solution

I'm messing around with a slider-esque custom component built using some of the work that was done in #809, and I want it to work on mobile/iPad.  To make this happen, I made a hacked-up version of `useDrag1D` that uses pointer events instead of mouse events.  My version works well on modern browsers with both touch and mouse, but doesn't work with some older browsers.

Some gotchas to the pointer events api are that the slider "thumb" needs the `touch-actions: none` style applied, and unfortunately there's no direct way to do that through the current API of `useDrag1D`, it's either a separate step you have to do in the component that uses `useDrag1D`, or that API needs to change.

## 🔦 Context

I think this will become more important when the Slider component is created, as it will need a pointer events implementation of `useDrag1D` in order to work on mobile/touchscreen devices.  https://github.com/adobe/react-spectrum/projects/1#card-43908283

## 🧢 Your Company/Team

Although I work for Adobe, this isn't part of a team milestone, just me messing around with sliders to get a better handle on how react-spectrum works under the covers.

**Comment by mischnic** [comment]
This is also mentioned in this issue: https://github.com/adobe/react-spectrum/issues/1018

> For things like color area, color wheel, and dials (circular sliders), we'll need 2d movement support. The idea will be to deprecate useDrag1D and use useMove for all of these.

> The current implementation of useDrag1D does not handle touch events. We should implement this on top of pointer events where available, and then fall back to touch/mouse events when not available, just like other interaction hooks. In addition to the obvious events, we'll also need to handle onPointerCancel/onTouchCancel to ensure that we reset the dragging state when touches are canceled by the system.

**Comment by itaylor** [comment]
If it'd help, I could add feature detection and make a PR for a version of `useDrag1D` that uses pointer events if they are available.  The only real downside would be that implementers would still need to add `touch-events:none` in their draggable region's css.  However, if there's a plan to move to something with a different API than that of `useDrag1D`, then it's probably not worth the effort to make a PR.

**Comment by dannify** [comment]
Hi @itaylor, the useDrag1D hook is in early stages and touch support has not yet been added. The recent slider work was a community contribution and is currently in alpha. We have every intention to add full touch support to slider and the associated hooks but it is a little further away on the team's road map.

**Comment by dannify** [comment]
If it is still something you would like to contribute to, we can work with you on the direction we were planning on taking with this hook, but yes as you mentioned above, it is likely to have a different API.
