### ISSUE TITLE
Switch: Add property to flip the position of label and switch

### ISSUE THREAD

**Issue by sarnason** [adobe/react-spectrum#1075]
# 🙋 Feature Request

Allow the Switch label to be in front and left aligned. (and please correct me if I am wrong on this not existing)

## 🤔 Expected Behavior

A Switch can be implemented as used in Ps on iPad and Xd on desktop

Label <-flex-> (O )

## 😯 Current Behavior

It seems that the label is rendered after the switch itself. 

## 💁 Possible Solution

Add property such as labelFirst=true
Only the remaining issue is if the switch should come immediately after or be right aligned which would be more useful.
So Left aligned Label but right aligned switch.

## 🔦 Context

I am implementing Spectrum in a properties sidebar and want it to look similar to Ps and Xd in this regard.
Now I know that I can define and refer to the label as another component but it just seems to make sense to allow this. 

## 💻 Examples

<img width="311" alt="Screenshot 2020-09-17 at 01 37 20" src="https://user-images.githubusercontent.com/2607409/93410184-0c127b80-f888-11ea-958b-2ff74694aa8e.png">
<img width="242" alt="Screenshot 2020-09-17 at 01 34 09" src="https://user-images.githubusercontent.com/2607409/93410194-103e9900-f888-11ea-9c23-57ddd00f9e47.png">

## 🧢 Your Company/Team

Seems that at least Ps on iPad uses this kind of layout as well as Xd on the desktop.
If not already supported it seems like something that should be considered.
My product, Visial is an external one and aims to support the full CC workflow in a familiar UX.

**Comment by snowystinger** [comment]
While we don't support this with the label on Switch right now, you can accomplish this without too much hassle doing something like https://codesandbox.io/s/competent-kepler-35266?file=/src/App.js, you can turn those lines into a component to make it easier as well

**Comment by sarnason** [comment]
Thanks Robert!

**Comment by snowystinger** [comment]
I updated my example so that the labels will actually trigger the Switch as well

**Comment by matthewdeutsch** [comment]
Consulted with Design and decided this would not be included in the Switch component. Please use the provided workaround!
