### ISSUE TITLE
useSelect example using span instead of a label

### ISSUE THREAD

**Issue by mickaelzhang** [adobe/react-spectrum#1078]
# ❔ Question

I was looking at the [useSelect doc example](https://react-spectrum.adobe.com/react-aria/useSelect.html) and it seems like the example for the select doesn't  use a label but a span. Is there a reason for this choice?

## 🔦 Context

I thought the appropriate choice here would be to use a label (with the `forHtml` prop) so that when we click on the label, it would open the select menu.

## 💻 Code Sample

https://react-spectrum.adobe.com/react-aria/useSelect.html#example

**Comment by devongovett** [comment]
Yep! The reason is that native label elements can only label native form elements (e.g. input or select). Therefore, we use a span to label our custom elements.
