### ISSUE TITLE
IE throws error "Error occurred" when using `FocusScope`

### ISSUE THREAD

**Issue by HyunSeob** [adobe/react-spectrum#1080]
## 🤔 Expected Behavior

Error doesn't occurred.

## 😯 Current Behavior

Error occurred on IE11.

## 💁 Possible Solution

I saw FocusScope using `createTreeWalker` internally. There is [an issue](https://stackoverflow.com/questions/38245898/createnodeiterator-fails-in-ie9-when-acceptnode-is-specified) on IE when using `createNodeIterator`. I think this problem is related with that issue. So I think if you pass function not the object as third parameter to `createTreeWalker`, this issue may be fixed.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/focus   | 3.2.1
| Internet Explorer  | 11
| Windows | 10

**Comment by snowystinger** [comment]
Unfortunately, we do not support IE11 https://react-spectrum.adobe.com/react-aria/interactions.html#supported-browsers-and-platforms
