### ISSUE TITLE
Add NoSearchResults IllustratedMessage component

### ISSUE THREAD

**Issue by evargast** [adobe/react-spectrum#1085]
# 🙋 Feature Request
Add this component to the library of available IllustratedMessages

![Screen Shot 2020-09-22 at 1 42 47 PM](https://user-images.githubusercontent.com/52969178/93923844-8d7b6b00-fcd9-11ea-8af3-428d653356af.png)

I've made it locally, mimics all other IllustratedMessages, figured we can contribute it back! 

## 🤔 Expected Behavior

Works like an IllustratedMessage

## 😯 Current Behavior

The NoResults illustrated image is a bit vague - not Search specific
![Screen Shot 2020-09-22 at 1 42 25 PM](https://user-images.githubusercontent.com/52969178/93923794-776daa80-fcd9-11ea-8e2b-c9d75f7b54c7.png)

## 💁 Possible Solution

Use the svg and pass it the illustrated image props, got a working solution, PR coming soon! 

## 🔦 Context

I'm working with the Commerce Cloud Search team - we need a no results image that illustrates that the search went through but no results for it.

## 💻 Examples
Real life example: https://spectrum.adobe.com/page/icons/ already uses that icon but it's not in an IllustratedMessage format - the idea is to support it

![Screen Shot 2020-09-22 at 1 46 32 PM](https://user-images.githubusercontent.com/52969178/93924198-0a0e4980-fcda-11ea-9e87-571ceae3d76a.png)

## 🧢 Your Company/Team

Adobe / Commerce Cloud

**Comment by matthewdeutsch** [comment]
@evargast we'll be following up with the design team on new IllustratedMessages being added to Spectrum shortly

**Comment by evargast** [comment]
> @evargast we'll be following up with the design team on new IllustratedMessages being added to Spectrum shortly

Nice, thanks!
