### ISSUE TITLE
Button Double Click and Hold Disables Page Selection

### ISSUE THREAD

**Issue by pacocoursey** [adobe/react-spectrum#1088]
# 🐛 Bug Report 

Double Clicking and holding on a button using `useButton` from `@react-aria/button` eventually disables user-selection on the entire page. This is a very dangerous global side effect. Here is a gif that clearly demonstrates the issue:

![aaa](https://user-images.githubusercontent.com/34928425/93945880-0805b400-fcf5-11ea-95f7-46f39bae4f2c.gif)

## 🤔 Expected Behavior

`user-select: none` should be cleaned up from the html element after a press is completed.

## 😯 Current Behavior

`user-select: none` remains on the html element forever.

## 🔦 Context

Ran into this bug while trying to build a simple Button with the `useButton` hook.

## 💻 Code Sample

Minimal reproduction: https://codesandbox.io/s/practical-hill-99u82?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/button   | 3.2.1
| Browser          | Chrome | 85.0.4183.102 (Official Build) (64-bit)
| OS          | macOS Catalina 10.15.6
-- | --

**Comment by pacocoursey** [comment]
Updated title because it's much easier to reproduce via Double Click + Hold.

**Comment by mischnic** [comment]
Might be a duplicate of https://github.com/adobe/react-spectrum/issues/862

**Comment by pacocoursey** [comment]
Agreed, looks like the components use the same helper under the hood. Closing in favor of #862 and associated PR #926
