### ISSUE TITLE
When sidenav and header nav will be implemented?

### ISSUE THREAD

**Issue by lordsfantasy** [adobe/react-spectrum#1095]
When sidenav and header nav will be implemented?

**Comment by dannify** [comment]
It is not in our immediate plans to implement. Some work has been done on SideNav but it needs to be finalized. You can follow our roadmap to see what is coming up. https://github.com/adobe/react-spectrum/projects/1

**Comment by matthewdeutsch** [comment]
As a clarification, there is no Header component planned at this time, but you can expect a SideNav component published react-spectrum later on!

**Comment by gar1t** [comment]
The last update here was that react-spectrum would include a SideNav component - back in 2020 - but this is closed. Is there an open issue that is tracking the status of this?

**Comment by dannify** [comment]
Not currently. Side nav is not a very complicated component to create so it hasn't been high on our implementation list nor highly requested by the community. It is likely that we will at least set up a React Aria Component for it but I don't have a ticket to cover that yet.
