### ISSUE TITLE
RFC: Removing isReadOnly from @react-stately/slider and @react-aria/slider

### ISSUE THREAD

**Issue by mischnic** [adobe/react-spectrum#1096]
We are thinking about removing the `isReadOnly` prop from the slider-related hooks as having a read-only slider in addition to a disabled slider/slider handle doesn't make much sense (as opposed to a text field, which can still be focused to copy it's contents).

https://github.com/adobe/react-spectrum/blob/f5f16024617a0ce88805cf845a5db16d94cc6ace/packages/%40react-types/slider/src/index.d.ts#L4

https://github.com/adobe/react-spectrum/blob/f5f16024617a0ce88805cf845a5db16d94cc6ace/packages/%40react-types/slider/src/index.d.ts#L14

Is anyone using this/has a usecase?

cc @chungwu

**Comment by chungwu** [comment]
Makes sense to me!  Thanks :+1:
