### ISSUE TITLE
useTreeData update method causing infinite loop

### ISSUE THREAD

**Issue by drenther** [adobe/react-spectrum#1097]
# 🐛 Bug Report 

The `tree.update` method from `useTreeData` hook is causing some kind of infinite loop.

## Context

I was trying to build a tree component using the `useTreeData` hook from `@react-stately/data` package, where you can expand and collapse sections with children. I was using an expanded property on an item to track the state.

## 🤔 Expected Behavior

Expected the expand / collapse to work by updating the expand property on the value of an item in the tree using `tree.update` method provided.

## 😯 Current Behavior

When using `tree.update` to toggle the expanded state of a node. It works as expected for the first time but after that if you try to expand or collapse any node it goes into some kind of infinite loop (the UI freezes and crashes).

## 💻 Code Sample

Codesandbox that reproduces the bug - https://codesandbox.io/s/react-stately-usetreedata-fws7j

#### How to reproduce?

Click on any of the folder icon in the tree to expand / collapse a composite node, the first action will behave as expected. Then, try to expand / collapse any of the node again and the UI will freeze.

---

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-stately/data  | 3.1.0
| Browser          | Chrome Version 85.0.4183.121 (Official Build) (64-bit)
| Operating System | macOS Catalina

**Comment by LFDanLu** [comment]
I was able to reproduce this in the useTreeData test, need to dig into what is happening.

**Comment by LFDanLu** [comment]
I believe it is because of this line: https://github.com/adobe/react-spectrum/blob/main/packages/@react-stately/data/src/useTreeData.ts#L328
Should be `parentKey: oldNode.parentKey`, infinite loop was happening because of the self referential parentKey causing `updateTree` to keep looping over the same node

Gonna double check locally.

**Comment by drenther** [comment]
Hey @LFDanLu, I can give it a try. I was anyway planning to monkey-patch over the weekend for my sideproject.

Will be willing to make a PR if it's still unassigned.

**Comment by dannify** [comment]
Hey @drenther did you still want to give this a try? It has not been picked up yet.

**Comment by razvanip** [comment]
@LFDanLu i can confirm `parentKey: oldNode.parentKey` is the fix locally.

I can pick this up add some tests and do a PR if that is oki.

**Comment by LFDanLu** [comment]
@razvanip Absolutely, that would be great!
