### ISSUE TITLE
Unable to type useSelect's usage of useListBox

### ISSUE THREAD

**Issue by aweary** [adobe/react-spectrum#1100]
# 📝 Feedback

This could just be feedback on better documentation or there may be a TypeScript issue here. Following the [example for `useSelect`](https://react-spectrum.adobe.com/react-aria/useSelect.html) it seems like `useListBox` requires `children` as the input type extends `CollectionBase` but the example doesn't pass any props or property called `children` to `useListBox`. Things also seem to work fine with that too.

## 🔦 Context

Just trying to implement a component using `useSelect` with TypeScript

## 💻 Code Sample

[Here is a running example of the documentation code with some attempted typing in TypeScript](https://codesandbox.io/s/reverent-beaver-7vf6f?file=/src/App.tsx:2241-2335). 

These lines specifically are the problem:

```js
let { listBoxProps } = useListBox(
    {
      autoFocus: state.focusStrategy || true,
      disallowEmptySelection: true
    },
    state,
    ref
  );
```

```
Argument of type '{ autoFocus: FocusStrategy; disallowEmptySelection: true; }' is not
assignable to parameter of type 'AriaListBoxOptions<any>'.
Property 'children' is missing in type '{ autoFocus: FocusStrategy; disallowEmptySelection: true; }'
but required in type 'AriaListBoxOptions<any>'
```

## 🌍 Your Environment

See the CodeSandbox

## 🧢 Your Company/Team

N/A

**Comment by mischnic** [comment]
This ignore comment in the ListBox component is related to the children as well:

https://github.com/adobe/react-spectrum/blob/da1f0a8a149db773b61c8ae61a99ec0139db7b29/packages/%40react-spectrum/listbox/src/ListBoxBase.tsx#L68-L74

```
Argument of type '{ keyboardDelegate: ListLayout<T>; isVirtualized: true; defaultChecked?: boolean; defaultValue?: string | number | readonly string[]; suppressContentEditableWarning?: boolean; suppressHydrationWarning?: boolean; ... 300 more ...; isHidden?: boolean; }' is not assignable to parameter of type 'AriaListBoxOptions<T>'.
  Types of property 'children' are incompatible.
    Type 'ReactNode' is not assignable to type 'CollectionChildren<T>'.
      Type 'string' is not assignable to type 'CollectionChildren<T>'.ts(2345)
```

**Comment by aweary** [comment]
Looks like that was introduced by @devongovett in https://github.com/adobe/react-spectrum/pull/534.

**Comment by devongovett** [comment]
Ugh, I wish there was a good way of type checking the code in MDX files...

In this case, I think `useListBox` doesn't actually need the `children` prop so we should probably omit it from the type or make it optional. It's only required by the state hook.
