### ISSUE TITLE
Unable to Import CheckboxGroup from @adobe/react-spectrum

### ISSUE THREAD

**Issue by royalbhati** [adobe/react-spectrum#1101]
# 🐛 Bug Report 

According to the docs [here](https://react-spectrum.adobe.com/react-spectrum/CheckboxGroup.html) we can import CheckboxGroup from @adobe/react-spectrum but it is not exported.

## 🤔 Expected Behavior

CheckboxGroup should be imported from  @adobe/react-spectrum

## 😯 Current Behavior

CheckboxGroup can't imported from  @adobe/react-spectrum

<img width="987" alt="Screenshot 2020-09-26 at 11 36 56 AM" src="https://user-images.githubusercontent.com/11679543/94331725-a1321480-ffec-11ea-8fd3-796e8e28d4b8.png">

## 💁 Possible Solution

Export it in the package

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | nightly
| Browser          |. Chrome
| Operating System | MacOS

**Comment by LFDanLu** [comment]
Good catch, I was able verify in a codesandbox as well.
