### ISSUE TITLE
usePreventScroll breaks layout

### ISSUE THREAD

**Issue by b-b0t** [adobe/react-spectrum#1103]
# 🐛 Bug Report 

When using usePreventScroll as I understand it's meant to remove the scrollbar and prevent lock as well as add padding so that content does not move.

## 🤔 Expected Behavior

Modal pop up, remove scrollbar and prevent scrolling

## 😯 Current Behavior

My body gets padding-right: 0px applied and it stretches the entire layout.

## 💁 Possible Solution

Provide an option to stop padding being added on body element.

## 🔦 Context

Opening modals and keeping page the same. 

## 💻 Code Sample

  // Prevent scrolling while the modal is open, and hide content
  // outside the modal from screen readers.
  usePreventScroll();
  let { modalProps } = useModal();

## 🌍 Your Environment

Next.js Node.js 12

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser     | Chrome Latest
| Operating System |  MacOS 10.15

## 🧢 Your Company/Team

Adobe/Spectrum

**Comment by devongovett** [comment]
Why would setting paddingRight: 0px break the layout? Did you have a non-zero padding already? Maybe we need to add the width of the scrollbar in addition to the existing padding rather than replace the padding?

**Comment by b-b0t** [comment]
@devongovett so if you look at the page of the example and toggle the dialog you'll see the Contents menu on the right collapse in a little: https://react-spectrum.adobe.com/react-aria/useDialog.html
I know this may be as intended but it just feels unpolished IMO. 
Might submit a PR after further investigation.
