### ISSUE TITLE
Picker double typing a letter doesn't move ahead

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#1111]
# 🐛 Bug Report 

If you have a Picker with Devon, Danni, Doggo such as in our story, repeatedly typing 'd' should cycle through them.
This can be observed in a native select element.

## 💁 Possible Solution

The change is probably related to this PR https://github.com/adobe/react-spectrum/pull/425/files which was correcting for the case where
"John A", "John B", "John C" are all in a Picker and typing "j" once will move to "John A", but typing an "o" will move it to "John B" when it should stay on "John A". This fix needs to stay, there's just more left to do to support this.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by johnjacobkenny** [comment]
May I give this a try?

**Comment by snowystinger** [comment]
go for it! :)

**Comment by snowystinger** [comment]
Hey, we did some further testing around native selects and it only does this behavior when it's closed. We think it's good enough as is. I'll be closing this one, thank you for the interest though.
https://jsfiddle.net/snowystinger/6tacqu3j/3/

**Comment by johnjacobkenny** [comment]
No problem! Thanks :smile:
