### ISSUE TITLE
Toast API

### ISSUE THREAD

**Issue by dannify** [adobe/react-spectrum#1116]
Research for creating a Toast API.
See https://spectrum.adobe.com/page/toast/

Information on potential implementation details of priority queue (optional)
Timebox: 2 days

**Comment by Robbie-Cook** [comment]
Where's my Toast component bois? Es not in your react-spectrum exports or react docs.

**Comment by LFDanLu** [comment]
@Robbie-Cook This was a task to create the Toast api, the Toast component is still TBD. You can track its status via our roadmap here: https://github.com/adobe/react-spectrum/projects/1
