### ISSUE TITLE
Implement ColorSlider component

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#1119]
# 🙋 Feature Request

<img src="https://spectrum.adobe.com/static/images/color-slider_options_background@2x_6RYkHuW0ogMG2Gaq4pI1B4_1589390365715.png" height="300">

The [color slider](https://spectrum.adobe.com/page/color-slider/) component allows a user to choose a value for a single color channel. Which channel it represents is configurable and could include hue, saturation, brightness RGB values, etc.

## 💁 Possible Solution

See #973 which describes the API for the Color object we will use to represent colors. A base has already been implemented and merged, though additional color formats may need to be implemented.

The props for the ColorSlider component are as follows:

```ts
interface ColorSliderProps extends ValueBase<Color>, LabelableProps, AriaLabelingProps {
  channel: ColorChannel,
  value?: string | Color, // override to allow passing string
  defaultValue?: string | Color,
  orientation?: Orientation,
  /** Whether the value's label is displayed. True by default if there's a `label`, false by default if not. */
  showValueLabel?: boolean,
  showTextField?: boolean, // do we want this? we didn't keep it for slider....
}
```

The existing slider hooks and potentially aspects of #1083 and useMove in #1106 could be used to implement this. Some additional logic should be implemented on top to normalize numeric values into colors, and implement the relevant track background styling. The track background and color value shown in the handle/loupe for each channel shows the relevant channel in addition to the following values for other channels:

- Hue - sets saturation, value, and alpha to 1
- Saturation - sets alpha to 1
- Value - sets alpha to 1
- RGB - sets alpha to 1
- Alpha - sets value to real output color

The API for stately and aria could be as follows:

```ts
interface ColorSliderState extends SliderState {
  value: Color,
  setValue(value: string | Color): void
}

function useColorSliderState(props: ColorSliderProps): ColorSliderState;

// Using existing slider hooks. Only a single thumb allowed (?)
interface ColorSliderAria extends SliderAria, SliderThumbAria {}

function useColorSlider(props: ColorSliderProps, state: ColorSliderState): ColorSliderAria;
```

The stately package could implement `getThumbMinValue` and `getThumbMaxValue` to return the min/max values for the relevant color channel (e.g. RGB = 0-255).

These should be implemented in the `@react-spectrum/color`/`@react-aria/color`/`@react-stately/color` packages, respectively.

See the [spectrum website](https://spectrum.adobe.com/page/color-slider/) for details on the behavior. The CSS for ColorSlider is already [implemented in Spectrum CSS](https://opensource.adobe.com/spectrum-css/colorslider.html). We also have an internal prototype of this component available for reference by Adobe employees.

### ColorThumb

This component also depends on the internal `ColorThumb` component, which also includes a [color loupe](https://spectrum.adobe.com/page/color-loupe/). This component is used as the thumb the user drags, and the loupe appears when they are pressing to show a preview of the color being chosen.

The API for ColorThumb could be as follows:

```ts
interface ColorThumbProps {
  value: Color,
  isDisabled?: boolean,
  isDragging?: boolean, // shows the color loupe
  isFocused?: boolean // makes the circle larger
}
```

## 🧢 Your Company/Team

RSP

**Comment by valentinbdv** [comment]
Sooooo glad the color slider is now available: https://react-spectrum.adobe.com/react-spectrum/ColorSlider.html
This was the only missing piece for my project! Thanks for the amazing work ;)
