### ISSUE TITLE
Implement ColorWheel component

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#1120]
# 🙋 Feature Request

<img src="https://spectrum.adobe.com/static/images/color-wheel_options_background@2x_2eKSpCf06sGhX2YKECpJON_1589498745498.png" height="300">

The [color wheel](https://spectrum.adobe.com/page/color-wheel/) component allows a user to choose a color hue.

## 💁 Possible Solution

See #973 which describes the API for the Color object we will use to represent colors. A base has already been implemented and merged, though additional color formats may need to be implemented.

The props for the ColorWheel component are as follows:

```ts
interface ColorWheelProps extends ValueBase<Color>, LabelableProps, AriaLabelingProps {
  value?: string | Color, // override to allow passing string
  defaultValue?: string | Color,
  step?: number,
  isDisabled?: boolean
}
```

The `useMove` hook added in #1106 can be used to implement the drag behavior for the handle. In addition, a visually hidden `<input type="range">` element should be used to represent the value for accessibility, similar to the slider components. If it makes sense, we could reuse parts of the slider hooks, but the circular dragging behavior may make this more impractical than its worth.

The track background and color value shown in the handle/loupe shows the hue in addition to setting saturation, brightness/lightness, and alpha to 1.

The React Stately and React Aria APIs could look something like this:

```ts
interface ColorWheelState {
  readonly value: Color,
  setValue(value: string | Color): void,

  // numeric value for the hue
  readonly hue: number,
  setHue(value: number): void,
}
```

These should be implemented in the `@react-spectrum/color`/`@react-aria/color`/`@react-stately/color` packages, respectively.

See the [spectrum website](https://spectrum.adobe.com/page/color-wheel/) for details on the behavior. The CSS for ColorWheel is already [implemented in Spectrum CSS](https://opensource.adobe.com/spectrum-css/colorwheel.html). We also have an internal prototype of this component available for reference by Adobe employees.

### ColorThumb

This component also depends on the internal `ColorThumb` component, which also includes a [color loupe](https://spectrum.adobe.com/page/color-loupe/). This component is used as the thumb the user drags, and the loupe appears when they are pressing to show a preview of the color being chosen.

The API for ColorThumb could be as follows:

```ts
interface ColorThumbProps {
  value: Color,
  isDisabled?: boolean,
  isDragging?: boolean, // shows the color loupe
  isFocused?: boolean // makes the circle larger
}
```

## 🧢 Your Company/Team

RSP

**Comment by mischnic** [comment]
Changes:

- We are only supporting the hue channel.
- We don't need min/max.

**Comment by devongovett** [comment]
(updated description)
