### ISSUE TITLE
useButton not applying :active pseudo-class in Firefox

### ISSUE THREAD

**Issue by e-cooper** [adobe/react-spectrum#1122]
# 🐛 Bug Report 

When using the `useButton` hook, styling for `button:active` does not seem to work in Firefox.

## 🤔 Expected Behavior

Active styling should be applied when the button press is being held.

## 😯 Current Behavior

No styling is applied because the pseudo-class does not seem to be applied.

## 💁 Possible Solution

There may be event handling preventing expected behavior.

## 🔦 Context

Should be obvious.

## 💻 Code Sample

https://codesandbox.io/s/stupefied-agnesi-02dyf?file=/src/Button.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.2.1
| Firefox          | 79 (64-bit)
| macOS Mojave |  10.14.6

## 🧢 Your Company/Team

External company team

**Comment by devongovett** [comment]
Ah. We usually recommend applying a CSS class based on the `isPressed` state returned by `useButton` instead of the pseudo class. This will also behave better on touch devices. This blog post demonstrates why: https://react-spectrum.adobe.com/blog/building-a-button-part-1.html.

See the `useButton` docs for an example of how to apply a class based on the press state: https://react-spectrum.adobe.com/react-aria/useButton.html#custom-element-type

**Comment by e-cooper** [comment]
I was able to use `isPressed` to apply a conditional class to my Button. That allowed me to control the styling for that button state in my theme like I wanted.

Button.js
```js
import React from 'react';
import { Button as RButton } from 'rebass';
import { useButton } from '@react-aria/button';
import { useHover } from '@react-aria/interactions';
import { useFocusRing } from '@react-aria/focus';
import { mergeProps } from '@react-aria/utils';
import classnames from 'classnames';

const Button = props => {
  const {
    className,
    ...others
  } = props;
  const { isFocusVisible, focusProps } = useFocusRing();
  const { buttonProps, isPressed } = useButton(props, ref);
  const { hoverProps, isHovered } = useHover(props);

  const buttonClasses = classnames(className, {
    'is-hovered': isHovered,
    'is-pressed': isPressed,
    'is-focused': isFocusVisible,
  });

  return (
    <RButton
      className={buttonClasses}
      {...others}
      {...mergeProps(hoverProps, focusProps, buttonProps)}
    />
  );
};
```

theme/buttons.js
```js
// default variant
export const primary = {
  bg: 'red',
  '&.is-pressed': {
    bg: 'yellow',
  },
  '&.is-hovered': {
    bg: 'blue',
  },
  '&.is-focused': {
    boxShadow: '...',
  },
};
```
