### ISSUE TITLE
Allow left and right MenuTrigger options

### ISSUE THREAD

**Issue by kaiortmanns** [adobe/react-spectrum#1125]
# 🙋 Feature Request

Currently `MenuTrigger` only allows directions `bottom` and `top`. The underlying `Popover` arrow is always hidden. The request is to allow more control including the directions `left` and `right` and allow to control wether an arrow is shown or not.

## 🤔 Expected Behavior

See above.

## 😯 Current Behavior

See above.

## 💁 Possible Solution

Allow to pass `placement` option to `MenuTrigger` which will forward to `Popover`. 
Add option to show or hide arrow. Hidden should be default.

## 🔦 Context

Vertical action bars should be able to present additional entries in a menu that should show up (left or right) beside the bar.

## 💻 Examples

Will try to add some soon.

## 🧢 Your Company/Team

Adobe

## 🎁 Tracking Ticket (optional)

not available

**Comment by snowystinger** [comment]
Thanks for starting this! We've started a discussion with Spectrum and are waiting for them to answer a couple more questions. We'll get back to you once we have an answer.

**Comment by snowystinger** [comment]
Yes, this all good with design.
The type should be
`direction?: 'bottom' | 'top' | 'left' | 'right' | 'start' | 'end',`

Let's start with left and right though and we can do start and end later.

As for the popover arrow, we do not want this. We rely on alignment with the target to convey its association.
