### ISSUE TITLE
How to use Collection components with Server-Sent Events and WebSocket

### ISSUE THREAD

**Issue by matamatanot** [adobe/react-spectrum#1126]
# 🙋 Documentation Request

Maybe, Feature Request.
List data, such as chats and comments, may be sent via SSE or Websocket.
How to handle this data with some APIs for collections, such as useAsyncList and useListData?

**Comment by ktabors** [comment]
The methods are documented in https://react-spectrum.adobe.com/react-stately/useAsyncList.html and https://react-spectrum.adobe.com/react-stately/useListData.html and are what you would use to manipulate data from SSE or Websocket APIs. Insertion is explained https://react-spectrum.adobe.com/react-stately/useListData.html#inserting-items and removal is explained https://react-spectrum.adobe.com/react-stately/useListData.html#removing-items.
