### ISSUE TITLE
Tooltip should remain open when the user hovers over the Tooltip itself

### ISSUE THREAD

**Issue by majornista** [adobe/react-spectrum#1131]
## 🐛 Bug Report 

Observed on https://react-spectrum.adobe.com/react-spectrum/Tooltip.html.

Tooltip closes when the user hovers over the Tooltip itself.

## 🤔 Expected Behavior

Tooltip should remain open when the user hovers over the Tooltip itself.

## 😯 Current Behavior

Tooltip closes when the user hovers over the Tooltip itself.

## 🔦 Context

Observed on https://react-spectrum.adobe.com/react-spectrum/Tooltip.html.

This is necessary to comply with [WCAG 2.1 Success Criterion 1.4.13: Content on Hover or Focus](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html), which states:

> Where receiving and then removing pointer hover or keyboard focus triggers additional content to become visible and then hidden, the following are true:
>
> **Dismissible**
> A mechanism is available to dismiss the additional content without moving pointer hover or keyboard focus, unless the additional content communicates an input error or does not obscure or replace other content;
>
> **Hoverable**
> _**If pointer hover can trigger the additional content, then the pointer can be moved over the additional content without the additional content disappearing;**_
>
> **Persistent**
> The additional content remains visible until the hover or focus trigger is removed, the user dismisses it, or its information is no longer valid.
>
>Exception: The visual presentation of the additional content is controlled by the user agent and is not modified by the author.

## 💻 Code Sample
```jsx
<TooltipTrigger>
  <ActionButton aria-label="Edit Name">
    <Edit />
  </ActionButton>
  <Tooltip>Change Name</Tooltip>
</TooltipTrigger>
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  3.4.0
| Browser          | All
| Operating System | All

## 🧢 Your Company/Team

Adobe/Accessibility

**Comment by snowystinger** [comment]
Thanks @majornista for sharing that page, I hadn't seen it before. Looks like there's actual a direct callout to native tooltips
> Examples of additional content controlled by the user agent include browser tooltips created through use of the HTML title attribute.

Why is this an exception? It was the influence for our decision when we didn't include it https://github.com/adobe/react-spectrum/pull/843#discussion_r463894392

**Comment by majornista** [comment]
> Thanks @majornista for sharing that page, I hadn't seen it before. Looks like there's actual a direct callout to native tooltips
> 
> > Examples of additional content controlled by the user agent include browser tooltips created through use of the HTML title attribute.
> 
> Why is this an exception? It was the influence for our decision when we didn't include it [#843 (comment)](https://github.com/adobe/react-spectrum/pull/843#discussion_r463894392)

I believe this exempts content authors from being held accountable for user agent (ie browser) implementations over which they have no control, like a `title` attribute or `img[alt]` text tooltip.

**Comment by majornista** [comment]
In v2, OverlayTrigger applies same `handleDelayedShow` and `handleDelayedHide` methods for the Trigger to the Overlay on mouse enter and on mouse leave of the Tooltip.
https://git.corp.adobe.com/React/react-spectrum-v2/blob/master/src/OverlayTrigger/js/OverlayTrigger.js#L531-L532

**Comment by snowystinger** [comment]
Right, but my question is, why is the native one different than the wcag recommendation? Why aren't they in alignment? If you can answer that anyways.

**Comment by majornista** [comment]
I don't have a good answer for why the native tooltip is not in alignment with WCAG 2.1, other than that the native implementation predates WCAG 2.1 recommendation by many years, and therefore have the exemption. The Success Criterion was added for WCAG 2.1 https://www.w3.org/WAI/WCAG21/quickref/#content-on-hover-or-focus, which was released in 2018. 

Bottom line, if the author has control of the element that displays on hover, then it should not hide when the user hovers  over it.

> ## [Hoverable](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html#hoverable)
>
> The intent of this condition is to ensure that additional content which may appear on hover of a target may also be hovered itself. Content which appears on hover can be difficult or impossible to perceive if a user is required to keep their mouse pointer over the trigger. When the added content is large, magnified views may mean that the user needs to scroll or pan to completely view it, which is impossible unless the user is able to move their pointer off the trigger without the additional content disappearing.
>
> Another common situation is when large pointers have been selected via platform settings or assistive technology. Here, the pointer can obscure a significant area of the additional content. A technique to view the content fully in both situations is to move the mouse pointer directly from the trigger onto the new content. This capability also offers significant advantages for users who utilize screen reader feedback on mouse interactions. This condition generally implies that the additional content overlaps or is positioned adjacent to the target.

**Comment by snowystinger** [comment]
I think the way to accomplish this would be to pass some functions through the Tooltip context object so that the tooltip trigger state can be updated as the Tooltip is hovered.
We'll need to introduce a delay to the closing of a tooltip so that there is time for the user to move from the trigger to the tooltip without it closing.

**Comment by Andarist** [comment]
I have started looking into this. I believe that the complete solution would also have to account for focusing tooltips but right now im only after handling hoverable case
