### ISSUE TITLE
DialogTrigger type="modal" warning

### ISSUE THREAD

**Issue by polmoneys** [adobe/react-spectrum#1135]
# 🐛 Bug Report 

Warnings

## 🤔 Expected Behavior

No warnings

## 😯 Current Behavior

Only happens with type="modal":

> Warning: Legacy context API has been detected within a strict-mode tree.
> The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.
> Please update the following components: Transition

>Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

## 💻 Code Sample

[Codesandbox](https://codesandbox.io/s/overlay-7ttro?file=/src/component/index.js)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.4.0
| Browser          | Chrome
| Operating System | MacOS

🙏🏽

**Comment by snowystinger** [comment]
I believe this will be solved by https://github.com/adobe/react-spectrum/pull/1108
