### ISSUE TITLE
useMenuTrigger Item not resetting user-select none

### ISSUE THREAD

**Issue by siggirh** [adobe/react-spectrum#1137]
Before we get to the bug report I just want to say thank you for sharing this library with the world. I've been using it a few days and it's amazing. :)

# 🐛 Bug Report 

When using `useMenuTrigger`, once an action has been clicked the `user-select: none;` styling isn't removed from the html root tag thus making no text on the page selectable after the menu is closed.

## 🤔 Expected Behavior

When an item has been clicked and/or menu has been closed, `user-select: none` should be removed.

## 😯 Current Behavior

You can see this on the [`useMenuTrigger` react-spectrum docs](https://react-spectrum.adobe.com/react-aria/useMenuTrigger.html)

1. Click the `Actions` menu to open (`user-select` will switch to `none` and then removed from dom)
2. Click any option, for example `Cut` (`user-select` will switch to `none` and stay there no matter what happens after).
3. Window alert will pop up
4. Click `Ok` in the alert to close.
5. `user-select: none` remains set on the html root.

Clicking outside the menu or on the trigger itself will close the menu and no `user-select:none` will be left behind. This only seems to happen when you click a menu `Item` with a mouse.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest |
| Browser          | chrome 85 |
| Operating System | catalina 10.15.6 |

**Comment by mischnic** [comment]
Are you sure you're using the latest version? https://github.com/adobe/react-spectrum/pull/926 fixed something similar and should be part of the last release

**Comment by siggirh** [comment]
Well like I said you can see it doing this on the live react-spectrum docs site. I expect that to be running latest :)

**Comment by LFDanLu** [comment]
Reproduced in a codesandbox with latest

**Comment by LFDanLu** [comment]
@siggirh Sorry for the delay, but I did some more digging. The menu in the `useMenuTrigger` docs doesn't have a open/close transition attached to it so as soon as you click on any of the menu items it removes the menu on `pointerdown`, causing `useGlobalListeners` to clean up the `pointerup` listener responsible for removing `user-select: none`. 

If you are currently blocked by this behavior you could add a transition to your menu and it should fix it (it's why our MenuTrigger component doesn't exhibit the same issue). I'll need to discuss with the team how best to handle this long term.

**Comment by LFDanLu** [comment]
Discussed with the team, adding a useEffect to usePress that calls `restoreTextSelection` on unmount seems like the appropriate fix.
