### ISSUE TITLE
Support rendering ActionButton as anchor link similar to Button

### ISSUE THREAD

**Issue by icaraps** [adobe/react-spectrum#1139]
# 🙋 Feature Request

Support rendering ActionButton as anchor link similar to Button

## Example

`<ActionButton elementType="a" href="github.com">Edit in GitHub</ActionButton>`

## 🔦 Context

Part of designs.

## 🧢 Your Company/Team

Adobe I/O

**Comment by snowystinger** [comment]
Sounds great! This would be a pretty good contribution, you should be able to use the same logic around it from Button https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/button/src/Button.tsx#L54 and you'll need to add the type definition to the extends on action button https://github.com/adobe/react-spectrum/blob/main/packages/%40react-types/button/src/index.d.ts#L72
Everything else should already be handled by useButton

**Comment by devongovett** [comment]
I think this should be discussed more before we move forward. I think it's important to distinguish buttons and links visually and semantically (for screen reader users). There are many articles out there explaining why although it's common, we should not mix up buttons and links as they are not the same thing. Adding link support to the normal `Button` component was a mistake IMO. So I'd like to consider carefully what we add to the API here, and possibly come up with some distinct affordance to distinguish buttons and links visually.

**Comment by icaraps** [comment]
> Adding link support to the normal `Button` component was a mistake IMO

Interesting .. What was the reason for still adding link support ?

**Comment by snowystinger** [comment]
Sorry for the delay, it's not a very satisfying answer, but it came over with legacy work.

**Comment by snowystinger** [comment]
This is not something that we're going to support at this time. We suggest using a Link.
