### ISSUE TITLE
Add calc() helper function

### ISSUE THREAD

**Issue by icaraps** [adobe/react-spectrum#1140]
# 🙋 Feature Request

Add calc() helper function similar to https://react-spectrum.adobe.com/react-spectrum/Grid.html#repeat

To allow using Spectrum variables to define dimensions, and typed to allow IDE autocomplete.

## 💻 Examples

`<View width={calc('size-x - size-y')}></View>`

## 🧢 Your Company/Team

Adobe

**Comment by snowystinger** [comment]
Hey, thanks for the suggestion. I'm not super great at TS, can it actually match that kind of a signature? or would we need to have an operator field?
`calc('size-x', 'size-y', '-')` or `subtract('size-x', 'size-y')`
Both of these get a little cumbersome, one is hard to read, the other requires multiple different functions
And then what if you want to nest calc's
`calc('size-x' - calc('size-y' * 2))` || `calc('size-x', calc('size-y', 2, '*'), '-')` || `subtract('size-x', multiply('size-y', 2))`
or want to use other units
`calc(100% - 'size-x')`

I know this one can't be typed for suggestions, but maybe we allow for a string of the whole thing?
`calc(var(--size-x) - var(--size-y))` i think right now this gets discarded or incorrectly handled by https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/utils/src/styleProps.ts#L120

**Comment by icaraps** [comment]
> I know this one can't be typed for suggestions, but maybe we allow for a string of the whole thing?

+1

**Comment by devongovett** [comment]
Can you give us an example of what this would be useful for? When would you be doing arithmetic on multiple spectrum variables?

**Comment by icaraps** [comment]
For example arithmetic of spectrum variables with relative units `calc(100vh - spectrum-variable)` e.g. the toc of the react-spectrum docs page could be written using the View component so from:

```
.toc {
  position: fixed;
  top: 80px;
  right: 8px;  
  overflow-y: auto;
  max-height: calc(100vh - 80px);
}

``` 
to

```
<View 
  elementType="nav" 
  position="fixed" 
  top="size-1000" 
  right="size-100" 
  overflow="auto" 
  height={calc('100vh - size-1000')}
>
```

I also often need negative spectrum variables so `calc('-1 * size-100')` for example etc.

**Comment by snowystinger** [comment]
This is too tricky to add at this time. We haven't figured out an API that we're happy with. For now, can you use UNSAFE_classname to accomplish this?
