### ISSUE TITLE
Toast Messages not in topmost layer in v3 provider wrapped with v2

### ISSUE THREAD

**Issue by pratesha** [adobe/react-spectrum#1141]
We are using V2 spectrum provider associated/wrapped with v3 provider, after this change the toast messages are not floating on the topmost layer, custom changes to zindex also does not mitigate the issue.

**Comment by LFDanLu** [comment]
Thanks for filing this issue, would you happen to have a code snippet or a code sandbox to share? Perhaps we would be able to make a change in v2 to make sure this combo works. Perhaps` isolation: isolate` has something to do with it as well, would need to dig on my end for that.

**Comment by ktabors** [comment]
This is a know issue in v2 with workarounds like Daniel mentioned.

**Comment by pratesha** [comment]
We are using v2 modal, we had to use v3 provider only to use picker component in our website.

**Comment by LFDanLu** [comment]
@pratesha Just to make sure I have the exact setup, you have a v2 toast and a v2 modal, and your v3 provider wraps the v2 provider?

**Comment by pratesha** [comment]
@LFDanLu yes you're right !

**Comment by ktabors** [comment]
What is the order of your v2 and v3 providers at the top level? If your v3 is the topmost, can you move the v2 to be the parent?

**Comment by pratesha** [comment]
@ktabors  implemented the change following your previous post, please refer this chat link 
https://behance.slack.com/archives/C7N5BE1EW/p1597352995087300?thread_ts=1597352783.086800&cid=C7N5BE1EW

**Comment by ktabors** [comment]
Please try switching the order of the providers. As the conversation continued it looks like you weren't setting the color scheme in v3 correctly and once you did that things worked.

**Comment by pratesha** [comment]
I just did that, the result is same, no ellipsis/truncation seen.

**Comment by ktabors** [comment]
Can you share you code related to your providers and your toasts?

**Comment by ktabors** [comment]
Closed due to inactivity.
