### ISSUE TITLE
Table API Feedback

### ISSUE THREAD

**Issue by deloreyj** [adobe/react-spectrum#1144]
# 📝 Feedback

I want to have access to more of the column definition in the <Cell /> render function in addition to the column's `key`. The column width definition has implications for how cell content should be rendered. As far as I can see there's no way to get that right now.

## 🔦 Context

When content is going to overflow its column width, I want more granular control than just having it cut off with ellipses. 

## 💻 Code Sample

```js
<Table sortDescriptor={sortDescriptor} onSortChange={setSortDescriptor}>
  <TableHeader columns={currentColumns}>
    {column => <Column allowsSorting>{column.name}</Column>}
  </TableHeader>
  <TableBody items={tableItems}>
    {item => (
      <Row key={item.orderId}>
        {key => (
          <Cell>
            {renderCell(
              key,
              item,
            )}
          </Cell>
        )}
      </Row>
    )}
  </TableBody>
</Table>
```
In this specific example, I'd like to pass `column.maxWidth` to renderCell. I can lookup that column since I have the key, but I think it's more ergonomic to have it provided as the argument to that render function. 

## 🧢 Your Company/Team

Adobe/Magento

**Comment by devongovett** [comment]
In this example, what would you pass? The object that created the column (e.g. the one with `column.name`) or the props of the `<Column>` component (e.g. with `allowsSorting`)?

**Comment by deloreyj** [comment]
The first one. The object with a shape like this https://github.com/adobe/react-spectrum/blob/main/packages/@react-types/table/src/index.d.ts#L35-L44
