### ISSUE TITLE
Providers and Next.js

### ISSUE THREAD

**Issue by polmoneys** [adobe/react-spectrum#1147]
# ❔ Question

Hola 💐. which Providers should I use on a Next.js project ? 

## 🔦 Context

Related docs:

[react-spectrum SSRProvider](https://react-spectrum.adobe.com/react-spectrum/ssr.html),  [react-spectrum SSRProvider II](https://react-spectrum.adobe.com/react-spectrum/Provider.html), [react-aria SSRProvider](https://react-spectrum.adobe.com/react-aria/SSRProvider.html), [react-aria I18nProvider](https://react-spectrum.adobe.com/react-aria/I18nProvider.html).

It seems all the info is on the docs yet I'm not confident on how to use it. There is a linked repo [with next.js](https://github.com/devongovett/rsp-next) that uses only **react-aria SSRProvider** on a **page.js**. 

I guess my question is twofold:
- which **Provider** should we use ? Is there any hierarchy we should follow ? 
- can we move from **page.js** to **_app.js** ? 

## 💻 Code Sample

Is A) enough ?

````javascript

// pages/_app.js

import { Provider, defaultTheme } from '@adobe/react-spectrum'; 

function MyApp({ Component, pageProps }) {
  return <Provider theme={theme} locale={locale}>
       <Component {...pageProps} />
</Provider>
}

````

Is B) accomplishing the same as A) above ?

````javascript

// pages/_app.js

import { SSRProvider } from '@react-aria/ssr'; 
import { I18nProvider, useLocale } from '@react-aria/i18n'; 

function MyApp({ Component, pageProps }) {
  return <SSRProvider theme={theme} >
<I18nProvider locale={locale}>
<Component {...pageProps} />
</I18nProvider>
</SSRProvider>
}

````

should we C) ? 

````javascript

// pages/_app.js

import { SSRProvider } from '@react-aria/ssr';

function MyApp({ Component, pageProps }) {
  return <SSRProvider theme={theme} >
<Component {...pageProps} />
</SSRProvider>
}



// pages/_document.js

import { I18nProvider, useLocale } from '@react-aria/i18n'; 

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    return (
<I18nProvider locale={locale}>
      <Html lang={locale.lang} dir={locale.dir}>
        <Head>
          <meta charSet="utf-8" key="key-charset" />
          <title>{META.title}</title>
          <link rel="shortcut icon" href="/favicon.ico" key="key-favicon" />
          <Seo />
          </script>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html >
    );
  }
}

````

## 🧢 Your Company/Team

We are kicking off a project with Next.js at [Wide agency](https://www.wideagency.com/) and we will most definitely be using some of the packages. Thank you all for any tips and guidance.

**Comment by LFDanLu** [comment]
@polmoneys For my own information, are you using `react-spectrum` (the components) or `react-aria` (the aria hooks) in your project? [SSRProvider](https://react-spectrum.adobe.com/react-spectrum/ssr.html) has info on what you need for the former, while [SSRProvider aria](https://react-spectrum.adobe.com/react-aria/SSRProvider.html) and i18n provider is if you are making your own components but utilizing our react-aria hooks.

**Comment by polmoneys** [comment]
We are cherry picking react-aria, maybe if theming was more approachable we'd try react-spectrum components. 

Muchas gracias 🙏🏾
