### ISSUE TITLE
Flexbox "order" style prop should be added.

### ISSUE THREAD

**Issue by adamlay91** [adobe/react-spectrum#1152]
# 🐛 Bug Report 

Flexbox `order` prop does nothing when adding it to a child component of the `<Flex>` component. A workaround is to use `UNSAFE_style={{ order: 1 }}` instead. Documentation says it should be available as a prop: https://react-spectrum.adobe.com/react-spectrum/Flex.html#props

## 🤔 Expected Behavior

Adding an `order` prop to a child of `<Flex>` should allow you to change the order of the flex items.

## 😯 Current Behavior

The following code snippet renders "ABC", when I expect it to render "CBA"
```
<Flex>
          <View order={3}>
            A
          </View>
          <View order={2}>
            B
          </View>
          <View order={1}>
            C
          </View>
</Flex>
```

## 💁 Possible Solution

As suggested by @snowystinger, need to make `order` a style prop.

## 💻 Code Sample

Expected: "CBA", but renders "ABC"
```
<Flex>
          <View order={3}>
            A
          </View>
          <View order={2}>
            B
          </View>
          <View order={1}>
            C
          </View>
</Flex>
```

Workaround: Renders "CBA"
```
<Flex>
          <View UNSAFE_style={{ order: 3 }}>
            A
          </View>
          <View UNSAFE_style={{ order: 2 }}>
            B
          </View>
          <View UNSAFE_style={{ order: 1 }}>
            C
          </View>
 </Flex>
```

## 🧢 Your Company/Team

Adobe Partner Platform

**Comment by snowystinger** [comment]
I think it should be added to https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/utils/src/styleProps.ts#L23

**Comment by harshilparmar** [comment]
Can I try this?

**Comment by renancleyson-dev** [comment]
This issue didn't had activity for almost 2 months. Can i work on this?

**Comment by devongovett** [comment]
Go for it!
