### ISSUE TITLE
Table row highlight is truncated if table is displaying only 1 column 

### ISSUE THREAD

**Issue by jluyau** [adobe/react-spectrum#1153]
# 🐛 Bug Report 

When hovering a row in a table that only has 1 column displayed (after other ones have been hidden), only half the row will be highlighted when hovered.

## 🤔 Expected Behavior

Hovering a row in a table which has all but one column hidden should highlight the whole row. 

## 😯 Current Behavior

Hovering a row in this case will only highlight half of it. 
![Screen Shot 2020-10-08 at 5 03 38 PM](https://user-images.githubusercontent.com/3901877/95530614-275a3d80-0993-11eb-8dd5-3681514a820e.png)

(NOTE: highlighting works fine if table initially has 1 column. only shows when columns are changed from X->1)

## 💁 Possible Solution

Looks like the cell width is not being updated after the 2nd to last column is removed:
checkbox width: 55px
cell width: 422.5px
row width: 900px

## 💻 Code Sample

see Table > hiding columns story. uncheck all checkboxes and highlight a row.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.4.0
| Browser          | Chrome
| Operating System | macOS Catalina 10.15.2 

## 🧢 Your Company/Team

Adobe/quarry

**Comment by snowystinger** [comment]
This is potentially complex (>1 day) issue to solve
