### ISSUE TITLE
Server Side Rendering doesn't work with latest NextJS

### ISSUE THREAD

**Issue by schabluk** [adobe/react-spectrum#1156]
# 🐛 Bug Report 

The guide for setting up SSR configuration in NextJS doesn't work with its latest version.

## 🤔 Expected Behavior

No errors.

## 😯 Current Behavior

After following the guide: https://react-spectrum.adobe.com/react-spectrum/ssr.html#nextjs I'm getting an error:

```
ready - started server on http://localhost:3000
info  - automatically enabled Fast Refresh for 1 custom loader
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

info  - Using external babel configuration from /Users/my/project/.babelrc.js
error - ./src/styles/globals.css
TypeError: Invalid PostCSS Plugin found at: plugins[0]

(@/Users/my/project/postcss.config.js)
    at Array.forEach (<anonymous>)
```

Content of `postcss.config.js`:
```
module.exports = {
  plugins: ['tailwindcss', 'autoprefixer', 'postcss-import'],
}
```

The `@zeit/next-css` plugin is considered to be obsolete according to: https://err.sh/next.js/built-in-css-disabled

After removing `@zeit/next-css` plugin, I'm getting:

```
error - ./node_modules/@react-spectrum/actiongroup/dist/main.css
Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to src/pages/_app.tsx. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://err.sh/next.js/css-global
Location: node_modules/@react-spectrum/actiongroup/dist/module.js
```

## 💁 Possible Solution

The suggestion is that the maintainer should publish a compiled version of the dependency: https://github.com/vercel/next.js/blob/master/errors/css-npm.md 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.4.0
| next   | 9.5.5

**Comment by devongovett** [comment]
The error seems to be complaining about your postcss config. Are you sure it's correct and you have all of those modules installed properly?

**Comment by schabluk** [comment]
Yes, I'm pretty sure my setup is correct. Everything was working before I installed `@adobe/react-spectrum` and configured `SSRProvider` and theme `Provider`.

The first error is about the PostCSS, but the second complains about this line:
```javascript
// node_modules/@react-spectrum/actiongroup/dist/module.js
import "./main.css";
```

**Comment by devongovett** [comment]
Did you check out the example project? https://github.com/devongovett/rsp-next

**Comment by schabluk** [comment]
So, I could finally make the build work without errors after changing `postcss.config.js` like this:
```javascript
module.exports = {
  plugins: [
    require('postcss-import'),
    require('tailwindcss'),
    require('autoprefixer')],
}
```
However, it turns out that `@zeit/next-css` doesn't allow me to use CSS Modules together with regular CSS files from react-spectrum - it works only with [built-in css module support](https://nextjs.org/blog/next-9-2#built-in-css-module-support-for-component-level-styles). At this point I have to bail out on it, because most of my codebase uses CSS Modules. Though, I'm still going to use react-aria and react-stately :)

Any chance that the built-in CSS in Next will be supported by Spectrum in the near future?

**Comment by devongovett** [comment]
TBH I'm not sure what we could do about it. Next doesn't load CSS files from node_modules so I'm not sure how we're expected to distribute the styles or how that would play with other tools. The current recommendation in the docs is the best we could come up with to force Next to load our CSS. If anyone has any better ideas we'd love to hear them though. 😄

**Comment by schabluk** [comment]
@devongovett: please check related issue in tailwindcss: https://github.com/tailwindlabs/tailwindcss/issues/2547

**Comment by schabluk** [comment]
Importing css from 3rd party components is supported in Next v10: https://nextjs.org/blog/next-10#importing-css-from-third-party-react-components

**Comment by devongovett** [comment]
Hmm still can't import css from _within_ node_modules though. I don't think we want to force people to manually import the css file for each component they use...

**Comment by schabluk** [comment]
> I don't think we want to force people to manually import the css file for each component they use...

No, that would be overcomplicated. Weird that it doesn't work from within node_modules...

**Comment by travigd** [comment]
It's worth noting that asking users to import CSS for every component **is* the approach that Reach UI takes, and it's not overly complicated (though there are comparatively fewer components).

**Comment by DarkPurple141** [comment]
Using a Babel plugin may help here. Alternatively an approach like https://github.com/atlassian-labs/compiled might make sense?

**Comment by ZLevine** [comment]
> It's worth noting that asking users to import CSS for every component *_is_ the approach that Reach UI takes, and it's not overly complicated (though there are comparatively fewer components).

Agreed. Also you avoid importing CSS for components you never use.

**Comment by nhducit** [comment]
both nextjs and react spectrum are awesome but it sad they are not easy to use them together

**Comment by kennetpostigo** [comment]
Hi, I'm running into this with a bare nextjs application, and I opened a issue in the example repo, so just wanted to reference (https://github.com/devongovett/rsp-next/issues/2)[here].

Does anyone know if theres a work around?

**Comment by ryankauk** [comment]
I was thinking maybe there's a way to ignore the css imports from webpack config side and then just import the styles manually. I don't know enough about web pack, does anyone with more web pack knowledge know a way for this to be possible?

**Comment by moonrise-tk** [comment]
Hey I'm new to this, so forgive me for not completely understanding the problem but couldn't Spectrum just publish using CSS modules instead of global css? Or do the distributed version necessarily convert the modules into global css?

**Comment by Amir-Abushanab** [comment]
Starting a new Typescript + Next.js (10.2.0) project and I've hit a brick wall with this too

**Comment by abhinav-anshul** [comment]
Hi, anyone came up with a solution?

**Comment by edazpotato** [comment]
I've had this same issue. If anyone has a workaround, that would be great!

**Comment by cmawhorter** [comment]
FWIW -- i _think_ i was able to get this running.  according to [this issue in next-transpile-modules](https://github.com/martpie/next-transpile-modules/issues/146), a fix shipped in 7.2.  

to get it to run without error, i had to do the following:

- use the [explicit list of modules](https://github.com/devongovett/rsp-next/issues/2#issuecomment-773754816) instead of wildcard (it complained about not being able to find module)
- install webpack@4 (with webpack5 it was giving an error about "tap" being undefined). got the idea from [here](https://github.com/vercel/next.js/discussions/19081)
- not sure if this did anything, but i also did: node v14, `rm -fr ./node_modules; rm-fr ./.next`

after that npm run dev loads the site. no idea if it's actually working though.  i'm new to both nextjs and spectrum.

**Comment by DaveStein** [comment]
@cmawhorter did you do this in NextJS 10 or 11?

**Comment by cmawhorter** [comment]
@DaveStein pretty sure it was v10

**Comment by DaveStein** [comment]
Ah I'm on 11 so I'm scared to even try vs await what the maintainer says over at https://github.com/martpie/next-transpile-modules/issues/222

**Comment by reidbarber** [comment]
Posting here for visibility, but it seems to be working with the config posted over at https://github.com/martpie/next-transpile-modules/issues/222#issuecomment-881765169. Big thanks to @fabianishere and @DaveStein. 

next.config.js:
```
const withTM = require("next-transpile-modules")([
  "@adobe/react-spectrum",
  "@react-spectrum/actiongroup",
  "@react-spectrum/breadcrumbs",
  "@react-spectrum/button",
  "@react-spectrum/buttongroup",
  "@react-spectrum/checkbox",
  "@react-spectrum/combobox",
  "@react-spectrum/dialog",
  "@react-spectrum/divider",
  "@react-spectrum/form",
  "@react-spectrum/icon",
  "@react-spectrum/illustratedmessage",
  "@react-spectrum/image",
  "@react-spectrum/label",
  "@react-spectrum/layout",
  "@react-spectrum/link",
  "@react-spectrum/listbox",
  "@react-spectrum/menu",
  "@react-spectrum/meter",
  "@react-spectrum/numberfield",
  "@react-spectrum/overlays",
  "@react-spectrum/picker",
  "@react-spectrum/progress",
  "@react-spectrum/provider",
  "@react-spectrum/radio",
  "@react-spectrum/slider",
  "@react-spectrum/searchfield",
  "@react-spectrum/statuslight",
  "@react-spectrum/switch",
  "@react-spectrum/tabs",
  "@react-spectrum/text",
  "@react-spectrum/textfield",
  "@react-spectrum/theme-dark",
  "@react-spectrum/theme-default",
  "@react-spectrum/theme-light",
  "@react-spectrum/tooltip",
  "@react-spectrum/view",
  "@react-spectrum/well",
  "@spectrum-icons/ui",
  "@spectrum-icons/workflow"
]);

module.exports = withTM({});
```

Hopefully we can update the docs and add an example pretty soon.

**Comment by DaveStein** [comment]
A key thing for debugging in 222 was that using the error messages as normal,I was able to nail down all the `@react-spectrum` values. Fabian then described in ticket how doing an inspect mode showed him additional things like `@spectrum-icons`

**Comment by sarnason** [comment]
It's not working for me. Spent two days already trying to get a large project to build.
Made a sample with details in the readme. I am sure @devongovett will find it interesting as it is based on his original sample.
https://github.com/sarnason/rsp-next-ts

**Comment by reidbarber** [comment]
@sarnason I've got working examples at [rsp-next-ts](https://github.com/reidbarber/rsp-next-ts) and [rsp-next](https://github.com/reidbarber/rsp-next) for reference. Both fresh from create-next-app.

**Comment by sarnason** [comment]
Thanks @reidbarber! I was able to find my problem by comparing the two. Turns out that using the nightly wasn't such a good idea. Shall I file a bug for it being broken?

**Comment by reidbarber** [comment]
@sarnason Feel free to create one if you still have good details about the error you were getting
