### ISSUE TITLE
useControlledState doesn't check for Set equality

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#1158]
# 🐛 Bug Report 

Discovered in https://github.com/adobe/react-spectrum/pull/1077. `useControlledState` should do some kind of deeper equality check for Sets when determining whether or not to fire `onChange` here: https://github.com/adobe/react-spectrum/blob/main/packages/@react-stately/utils/src/useControlledState.ts#L35

Right now Table fires a `onSelectionChange` every time a user hits the `esc` key when in Table w/ selection support since it treats every `new Set` as a unique empty set

## 🧢 Your Company/Team

RSP

**Comment by devongovett** [comment]
I think we should solve this at a higher level, e.g. in the selectionmanager rather than in controlled state.

**Comment by LFDanLu** [comment]
handled by https://github.com/adobe/react-spectrum/pull/1077
