### ISSUE TITLE
Clicking a button in a table row triggers row click affordance

### ISSUE THREAD

**Issue by jluyau** [adobe/react-spectrum#1165]
# 🐛 Bug Report 

Clicking a button that lives in a table row triggers the button as well as the row's click affordance (turning a darker grey than just mousing over the row)

## 🤔 Expected Behavior

If clicking a button (which uses `usePress` that stops event propagation), the event doesn't trigger the row. However, the row click affordance should also not fire as it gives the feedback that it did get clicked.

## 😯 Current Behavior

The row will show the click affordance even though the click event doesn;t propagate.

## 🔦 Context

Action buttons in a table

## 💻 Code Sample

See react-spectrum's story Table > CRUD. Click the action button (long press if needed to see) and notice the row flashes to the darker grey.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.4.0 
| Browser          | Chrome
| Operating System | MacOS Catalina

## 🧢 Your Company/Team

Adobe/quarry

**Comment by devongovett** [comment]
Fixed in the latest release.
