### ISSUE TITLE
[Checkbox] Use `Link` with Checkbox

### ISSUE THREAD

**Issue by leesiongchan** [adobe/react-spectrum#1166]
# 🐛 Bug Report 

```jsx
<Checkbox>Please click <Link><a href="/hello">me</a></Link></Checkbox>
```

## 🤔 Expected Behavior

`me` should be clickable

## 😯 Current Behavior

`me` is not clickable, but toggled the checkbox instead.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | ^3.3.0
| Browser          | Edge 86.0.622.38
| Operating System | macOS 10.15.6

**Comment by snowystinger** [comment]
so this is problematic for accessibility, a checkbox label should, when clicked, toggle the checkbox
by putting a link in it, you’ve conflated the two actions
can you consider doing a different UI pattern or push design for something else?
For example, you could separate the two components Checkbox/label + link
`<Flex><Checkbox>Please Click</Checkbox> - <Link href="/hello">this link</Link></Flex>`

**Comment by leesiongchan** [comment]
I see. Thank you very much.
