### ISSUE TITLE
Auto-generated IDs and Jest Snapshots

### ISSUE THREAD

**Issue by strass** [adobe/react-spectrum#1167]
# 🐛 Bug Report 

The ID generation feature is preventing us from using jest to snapshot our components.

## 🤔 Expected Behavior

There should be a way to easily snapshot components that compose useId.

## 😯 Current Behavior

Snapshot changes each run since IDs are being randomly generated.

## 💁 Possible Solution

1) expand our component API to include id props for all labeled elements (we are trying to avoid this)
2) Instructions on how to mock the useId hook in Jest or a provider that provides a static seed.

**Comment by snowystinger** [comment]
You should be able to do something to this effect
```
jest.mock('@react-aria/utils', () => {
  const { useUID } = require('react-uid'); // you could use whatever you want here
 
  return {
    ...jest.requireActual('@react-aria/utils'),
    useId: () => {
      return `react-spectrum-0-${useUID()}`;
    },
  };
});
```

thanks @paulkenney

**Comment by Kikketer** [comment]
I actually had the same issue but soon discovered the answer above wasn't working for some reason.  I still haven't figured out why, but I have a suspicion that there are multiple copies of the utils coming in and the mock isn't hijacking the correct one.

So what we did to "fix" this issue was to create a sort of patch in the component we were building.  
Code from the example (https://react-spectrum.adobe.com/react-aria/useSelect.html):
```
import { useId } from '@react-aria/utils'

function Select({ id, ...props }) {
  // This will use a given ID if you provide one from the parent
  const resultingId = id || useId()

  // Create state based on the incoming props
  let state = useSelectState({id, ...props});

  // Get props for child elements from useSelect
  let ref = React.useRef();
  let {labelProps, triggerProps, valueProps, menuProps} = useSelect(
    {id, ...props},
    state,
    ref
  );

  // Get props for the button based on the trigger props from useSelect
  let {buttonProps} = useButton(triggerProps, ref);

  return (
    <div style={{position: 'relative', display: 'inline-block'}}>
      <div {...labelProps} id={resultingId}>{props.label}</div>
      <HiddenSelect
        state={state}
        triggerRef={ref}
        label={props.label}
        name={props.name}
        id={resultingId}
      />
      <button {...buttonProps} ref={ref} style={{height: 30, fontSize: 14}} aria-labelledby={`${resultingId} ${resultingId}-button ${resultingId}-value`} id={`${resultingId}-button`}>
        <span {...valueProps} id={`${resultingId}-value`}>
          {state.selectedItem
            ? state.selectedItem.rendered
            : 'Select an option'}
        </span>
        <span aria-hidden="true" style={{paddingLeft: 5}}>
          ▼
        </span>
      </button>
      {state.isOpen && <ListBoxPopup {...menuProps} state={state} />}
    </div>
  );
}
```

This is just a partial.  We are also carrying down that ID into the options as well.
With this patch, in the test you simply provide an id: `<MyDropdown id={'stable-id'} />` which will then create stable ids all the way down.  But in "real" code you can still neglect to provide an `id` and it'll be generated by `useId` similar to how it is working today.

**Comment by devongovett** [comment]
Another possibility is to wrap your application in an SSRProvider, which will ensure consistent ids just like we need to for server side rendering. That said, I'd avoid snapshot testing in general because it's very error prone.

**Comment by torgeadelin** [comment]
I think snapshot tests are a good way of catching bugs when building a design system. @devongovett Do you have another solution for this? Wrapping each components in SSRProvider while testing isn't ideal.

@snowystinger your solution doesn't work for me either.

**Comment by torgeadelin** [comment]
Ok, after hours of trial and error, I have finally found a solution to mock the `useId` function.

```js
// Create a file in `__mocks__/@react-aria/utils/index.js` with the following 
const utils = require('@react-aria/utils/dist/main');

module.exports = {
  ...utils,
  useId: () => 'test-ID',
};

```

Then in your test, add `jest.mock(`@react-aria/utils)`;

This should mock all uses of the `useId` function.
