### ISSUE TITLE
When a Dialog contains an iframe that loads a form, the fields cannot be focused because they cannot be focused.

### ISSUE THREAD

**Issue by gstan07** [adobe/react-spectrum#1168]
# 🐛 Bug Report 

When the user clicks inside a field from a form that's contained in an iframe in a Dialog component, the focus gets lost and the user cannot write any character in that field

## 🤔 Expected Behavior

fields in iframes loaded using the Dialog component should be focusable

## 😯 Current Behavior

focus gets stolen when the user focuses a field
## 🔦 Context

I'm trying to load a form from an external service (form builder). Form works fine outside the dialog. Form works fine in an iframe if I use react-modal or other modal component instead of Spectrum Dialog
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Adobe Design Prototyping

**Comment by LFDanLu** [comment]
@gstan07 Mind sharing a code snippet or a code sandbox? Just want to make sure I get the same/similar setup when trying to reproduce.

**Comment by gstan07** [comment]
Hi @LFDanLu.
Here's the code:
![image](https://user-images.githubusercontent.com/2083415/96590756-1395cc00-12ef-11eb-8e5b-59272cb04772.png)
and here's the video of how it behaves:
https://www.dropbox.com/s/m9qnldwv38d1qtp/Screen%20Recording%202020-10-20%20at%2016.09.26.mov?dl=0
Let me know if you need additional details

**Comment by LFDanLu** [comment]
@gstan07 hmm, so the reason this happens is due to FocusScope attempting to contain focus within the the dialog. Clicking on the input within the iframe yields a `e.relatedTarget` of `null` in the onBlur attached to the Dialog, which makes FocusScope believe that focus is leaving the Dialog, causing it to refocus the Dialog. 

Trying to think up of a way to handle this.
