### ISSUE TITLE
Link all references to 'spectrum dimension variables'

### ISSUE THREAD

**Issue by filmaj** [adobe/react-spectrum#1169]
# 🙋 Documentation Request

Throughout the documentation, there are references to "spectrum dimension variables". I recently returned to using react spectrum after a break, and this was a new concept for me. Unfortunately, Googling it yielded little information.

Turns out, the info is under the 'styling' section of the documentation: https://react-spectrum.adobe.com/react-spectrum/styling.html#dimension-values

However, as I was diving through the docs, it took me a while (about 15 mins) to find this.

As such, may I suggest we link all references to this term to the relevant section of the docs? Happy to put together a PR for this, let me know you thoughts.

## 🧢 Your Company/Team

filmaj Consulting Inc.

**Comment by LFDanLu** [comment]
Feels reasonable to me.
