### ISSUE TITLE
Typography support

### ISSUE THREAD

**Issue by undavide** [adobe/react-spectrum#1171]
Hi, as I'm redesigning a Gatsby website, I'd like to know more about the Spectrum Typography implementation available in React Spectrum. As a background, I've been using Spectrum Web Components in the context of UXP plugins so far, so I'm slightly more familiar with them.

Here, I get that there's `Text` and `Heading`, as far as content goes. They seem to be a bit _bare_ if I compare them to the Spectrum CSS specs or one of the available implementation of Web Components (Spectrum or Coral). 

It's not my intent to criticize, I'm just unsure how to get the assortment of Classifications (serif/sans serif), Weights and Font sizes. E.g. `Heading` has only _levels_, is there a way to access this [rich variety](https://opensource.adobe.com/spectrum-css/typography-heading.html)? The same would apply to `Body`, that I assume in React Spectrum is replaced by `Text`. I don't think there are implementation for `Detail` or `Code` yet.

Any pointer would be greatly appreciated. Thank you!

**Comment by devongovett** [comment]
Yeah the typography components just aren't implemented yet. The Heading/Text components are meant for use inside another component like Dialog/Menu that provides the styling. Eventually we'll have typography components that could be used standalone. For now, you could use spectrum CSS directly perhaps.

**Comment by undavide** [comment]
Hi @devongovett thanks for confirming it. I should directly import `@spectrum-css/typography/dist/index-vars.css"`, correct? Is there any chance that it can interfere with React Spectrum in your opinion? Thanks!

**Comment by ktabors** [comment]
To directly use SpectrumCSS there is https://opensource.adobe.com/spectrum-css/get-started.html to explain getting started. Information about Typography is found at https://opensource.adobe.com/spectrum-css/typography.html

**Comment by ktabors** [comment]
Closed due to inactivity.
