### ISSUE TITLE
[useRadioGroup, useCheckboxGroup] createContext() `An argument for 'defaultValue' was not provided.`

### ISSUE THREAD

**Issue by matamatanot** [adobe/react-spectrum#1173]
## 🙋 Documentation Request

https://reactjs.org/docs/context.html#reactcreatecontext

`useRadioGroup` and `useCheckboxGroup` docs do not pass an argument to React.createContext(). This API must take the defaultValue.

- https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/checkbox/docs/useCheckboxGroup.mdx
- https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/radio/docs/useRadioGroup.mdx

ref: #865

**Comment by devongovett** [comment]
Hmm seems like a bug in the TS definitions, not passing the arg is equivalent to passing undefined. We could probably update the docs to pass null there though. 🤷
