### ISSUE TITLE
Long text in picker menu items is not truncated

### ISSUE THREAD

**Issue by pratesha** [adobe/react-spectrum#1174]
# 🐛 Bug Report 

Long unspaced item names in picker menu are not truncated/show in new line

## 🤔 Expected Behavior

Unspaced text in picker menu should show ellipsis behaviour or carry over to new line

## 😯 Current Behavior

Long unspaced item names in picker menu are not truncated/show in new line

## 🔦 Context

Adobe color team is using picker to display libraries for a user in menu item, for different languages, the menu item can be a large text

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0
| Browser          | All browsers
| Operating System | All Os

## 🧢 Your Company/Team

Adobe Color

## 🕷 Tracking Issue (optional)

https://jira.corp.adobe.com/browse/CCMCS-3690
<img width="314" alt="Screenshot 2020-10-05 at 10 36 26 PM" src="https://user-images.githubusercontent.com/72404525/96445317-57280180-122d-11eb-928c-6b586e4e6ce4.png">

**Comment by devongovett** [comment]
This is correct according to Spectrum designs. See https://spectrum.adobe.com/page/picker/#Text-overflow.
