### ISSUE TITLE
useTooltipTrigger example code in react-aria docs not working

### ISSUE THREAD

**Issue by karlpetersson** [adobe/react-spectrum#1175]
# 🐛 Bug Report 

The example code for useTooltipTrigger in the react-aria docs (https://react-spectrum.adobe.com/react-aria/useTooltipTrigger.html) doesn't seem to work. Here's a codesandbox using the example code: https://codesandbox.io/s/awesome-matsumoto-36xnj?file=/src/App.tsx

The tooltip does not display on hover. It is possible to get the tooltip to display, by focusing the button and then tabbing back and forth to another window, as can be seen in this gif:
![Kapture 2020-10-19 at 18 06 36](https://user-images.githubusercontent.com/3764441/96476748-e6d1ae00-1235-11eb-9804-39da32b4896e.gif)

## 🔦 Context

I want to use the useTooltipTrigger hook to build a tooltip component, rather than use the React Spectrum one, and I am trying to follow the docs to accomplish this.

## 💻 Code Sample

https://codesandbox.io/s/awesome-matsumoto-36xnj?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria/tooltip   | 3.0.0
| react-aria/utils | 3.3.0
| react-stately/tooltip | 3.0.0
| Browser          | Chrome Version 86.0.4240.80 (Official Build) (x86_64)
| Operating System | macOS 10.15.2 (19C57) 

## 🧢 Your Company/Team

Visly

**Comment by LFDanLu** [comment]
@karlpetersson This is definitely strange, the same code works in my local storybook, will have to do some digging.

**Comment by LFDanLu** [comment]
@karlpetersson Looks like the example is missing a `useFocusVisible()` or `useInteractionModality()` call. Calling either of these hooks from the `@react-aria/interactions` package will setup the event listeners needed to properly track the current interaction modality. For now, you can call either one and it should resolve the hover issue.

The long term fix will probably be to add either of those hook calls to `useTooltipTrigger` itself.

**Comment by devongovett** [comment]
Ah. We should setup these events on page load rather than lazily when calling those hooks. https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/interactions/src/useFocusVisible.ts#L193

**Comment by devongovett** [comment]
Closing as this was fixed in #1286

**Comment by maksimsemenov** [comment]
Neither `useFocusVisible()` nor `useInteractionModality()` worked for me.

This is my `Tooltip` component:
```js
const Tooltip = ({
  children,
  disabled,
  target,
  tooltipClassName,
  tooltipStyle
}) => {
  useFocusVisible()
  const state = useTooltipTriggerState({ delay: DELAY, isDisabled: disabled })
  const targetRef = React.useRef()
  const overlayRef = React.useRef()

  const { triggerProps, tooltipProps: tooltipTriggerProps } = useTooltipTrigger(
    { delay: DELAY, isDisabled: disabled },
    state,
    targetRef
  )

  const { tooltipProps } = useTooltip(tooltipTriggerProps, state)
  const { overlayProps } = useOverlayPosition({
    targetRef,
    overlayRef,
    offset: 4,
    placement: 'right'
  })

  return (
    <>
      {cloneElement(target, {
        ...triggerProps,
        ref: targetRef
      })}
      {state.isOpen && (
        <OverlayContainer>
          <div
            className={cn(styles.tooltip, styles[appearance], tooltipClassName)}
            {...mergeProps(overlayProps, tooltipProps, { style: tooltipStyle })}
            ref={overlayRef}
          >
            <Text className={styles.text} size="small">
              {children}
            </Text>
          </div>
        </OverlayContainer>
      )}
    </>
  )
}
```

And this is how it is used:
```js
<Tooltip
        target={
          <div>
            <WarningIcon />
          </div>
        }
      >
        {errorMessage}
</Tooltip>
```

My workaround was to use `useHover` hook to change the tooltip `state`. It worked, but I'm still confused why `useFocusVisible` did not work for me.

**Comment by vincerubinetti** [comment]
I found that using RAC's built in Button component didn't take `onPointerEnter` or associated events, which the `useTooltipTrigger` and associated hooks provide as part of `triggerProps` and are necessary to make hover work. Using a regular button seems to work for me, but then causes other issues outside the scope of this one.
