### ISSUE TITLE
useTooltipTriggerState always uses constant TOOLTIP_DELAY as opposed to the `delay` value passed as prop

### ISSUE THREAD

**Issue by karlpetersson** [adobe/react-spectrum#1177]
# 🐛 Bug Report 

The `delay` prop in `useTooltipTriggerState` can't be used to control the delay for showing the tooltip, instead a constant is always used. Please see: https://github.com/adobe/react-spectrum/blob/423d56867ad76a320537f4e3e127ed7b26c13b58/packages/%40react-stately/tooltip/src/useTooltipTriggerState.ts#L103

However, passing a `delay` value of 0 will work, since it causes the hook to not call the `warmupTooltip` routine, thus displaying the tooltip immediately. 

## 🤔 Expected Behavior

Expected `delay` prop to be used to control the delay of showing the tooltip for other values than 0

## 😯 Current Behavior

`delay` is effectively ignored and a constant 1500ms is always used for delaying showing the tooltip

## 💁 Possible Solution

Change to use the passed in `delay` in the `setTimeout` call, e.g:

```
if (!isOpen && !globalWarmUpTimeout && !globalWarmedUp) {
  globalWarmUpTimeout = setTimeout(() => {
    globalWarmUpTimeout = null;
    globalWarmedUp = true;
    showTooltip();
  }, delay);
}
```

## 🔦 Context

I want tooltips to show with a delay of 500ms instead of 1500ms

## 💻 Code Sample

https://github.com/adobe/react-spectrum/blob/423d56867ad76a320537f4e3e127ed7b26c13b58/packages/%40react-stately/tooltip/src/useTooltipTriggerState.ts#L103

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Visly

**Comment by johnjacobkenny** [comment]
I am picking this up @snowystinger. Will add a PR soon.
