### ISSUE TITLE
Select example from docs and Warning message

### ISSUE THREAD

**Issue by polmoneys** [adobe/react-spectrum#1179]
# ❔ Question

How can i fix the warning that reads " If you do not provide a visible label, you must specify an aria-label or aria-labelledby attribute for accessibility at ListBoxPopup "

I've tried to fix it like in the useListBox example of the [docs](https://react-spectrum.adobe.com/react-aria/useListBox.html) but warning persist:

```javascript
...
...

 let {listBoxProps, labelProps} = useListBox(props, state, ref);

  return (
    <>
      <div {...labelProps}>{props.label}</div> // THIS
      <ul
        {...listBoxProps}
        ref={ref}
        style={{
          padding: 0,
          margin: '5px 0',
          listStyle: 'none',
          border: '1px solid gray',
          maxWidth: 250
        }}>
        {[...state.collection].map((item) => (
          <Option key={item.key} item={item} state={state} />
        ))}
      </ul>
    </>
  );

```

## 💻 Code Sample

[Component](https://codesandbox.io/s/formlite-v2-nyy2r?file=/src/forms/select/index.js:653-661)

[App](https://codesandbox.io/s/formlite-v2-nyy2r?file=/src/App.js:1808-1814)

UseListBox console [output](https://codesandbox.io/s/formlite-v2-nyy2r?file=/src/forms/select/index.js:2137-2144): 
<img width="1718" alt="undefined" src="https://user-images.githubusercontent.com/7026863/96579150-ad9d4a80-12d6-11eb-9efa-36739b34632f.png">

Mark up seems to be OK ? 

<img width="1119" alt="present" src="https://user-images.githubusercontent.com/7026863/96579153-aece7780-12d6-11eb-9db7-4a476c50c0ea.png">

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest
| Browser          | chrome latest
| Operating System | mac os latest

**Comment by snowystinger** [comment]
Thanks for reporting this. It actually, this looks like a bug in our documentation as well.
https://react-spectrum.adobe.com/react-aria/useSelect.html

**Comment by snowystinger** [comment]
Looks like we just needed to pass a little more information along to useListBox so that it'd know we were labelled correctly. I've created a PR to address this in our docs and you should be able to do the same @polmoneys
