### ISSUE TITLE
How to build a single component?

### ISSUE THREAD

**Issue by filmaj** [adobe/react-spectrum#1181]
# ❔ Question

Dumb question: how does one go about building a single component from `./packages/@react-spectrum/*`?

## 🔦 Context

I am interested in building and using / testing the date picker component, which is pre-alpha at the moment and is not published to npm under the `@react-spectrum` scope.

If someone could help shed light on this, I would happily create a pull request expanding on the documentation to include this information. Perhaps could be included in the project README and/or individual component package READMEs and/or the contribution documentation?

## 🧢 Your Company/Team

filmaj Consulting inc.

**Comment by mischnic** [comment]
Running `make build` in the project root would build all packages and 
`yarn parcel build packages/@react-spectrum/slider/ --no-minify` would only build build that single package.

**Comment by filmaj** [comment]
Awesome! Thank you for that.

Do the contributors/committers believe adding this to the documentation would be useful? As an outsider, I would! Happy to put together a PR for that, let me know.

**Comment by filmaj** [comment]
So I can build the datepicker component as per instructions above (`yarn parcel build packages/@react-spectrum/datepicker --no-minify), but then copying the `dist/` folder bits into my other project and trying to import `main.js` or `module.js` yields a bunch of Parcel errors for me. I see a bunch of imports in datepicker like `@react-aria/calendar`, `@react-spectrum/calendar`, `@react-spectrum/calendar`, for instance, that are not public, and so parcel is having trouble figuring out where to get those from.

I must be doing something wrong... any tips?

**Comment by mischnic** [comment]
Well, that unreleased package depends on more unreleased packages. Maybe copying all of them over and adjust to module specifiers to import with a relative specifier from the other folders?

**Comment by dannify** [comment]
Hey @filmaj, I'd prefer to encourage people to use our alphas rather than our unreleased code so we won't add this to our docs. Glad you got it working though. Hopefully we have time to finish off DatePicker soon!

**Comment by filmaj** [comment]
I actually never got it working haha

**Comment by dannify** [comment]
Oh no! I guess I am not too surprised. DatePicker hasn't been updated for a while and it has a lot of parts.
