### ISSUE TITLE
Add support for async loading to ComboBox

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#1184]
# 🐛 Bug Report 

ComboBox should support async loading of items, for example when autocompleting data from a server as the user types. This should show a loading spinner in the ComboBox while data is loading, perhaps after a short delay so that it doesn't show if data comes back quickly.

<img height="250" src="https://user-images.githubusercontent.com/19409/96663358-64182400-1305-11eb-8936-be4bbc2c9731.png" />

## 💁 Possible Solution

1. Add an `isLoading` prop to ComboBox and show a spinner when it is set. This should occupy the same space as the error icon shown in an invalid state, and if both props are true at the same time, the spinner should be shown instead of the error icon.
2. Add a `filter` method to `useAsyncList` and `useListData` to update the filter text.
3. In `useListData` a `filter` option should be supported and receive an item and the filter text and return a boolean for whether the item should be included.
4. In `useAsyncList`, the filter text should be passed to the `load` method, which can pass the text to the server to load the filtered data.

## 🧢 Your Company/Team

RSP

**Comment by espebje** [comment]
@devongovett Could one also look at adding combobox to docs? ref #1092 . Or an example somewhere of how to implement with concern to accessibility.

**Comment by snowystinger** [comment]
@espebje thanks for your interest! We'll be doing docs once the component is ready. For now, you can look at the PR's and committed code to see what we're doing. Also, the specs directory is a great place to go for accessibility https://github.com/adobe/react-spectrum/blob/main/specs/accessibility/Autocomplete.mdx

**Comment by tybenz** [comment]
One thing to callout here: it sounds like the type-ahead in the Combobox is considered to be a "filter" that just takes data from the datasource and pares it down based on the filter-term/search-term. I have a use-case where I'd want to use one API for the pages of list items (Melville), and a separate API to look-up by name (USS). Have y'all considered allowing for an interface where there can be two separate APIs for incremental load/browse vs. search term entry?

**Comment by snowystinger** [comment]
I think this should be covered by our API, you can put combobox into a controlled state for the items and once this issue is done, you'll be able to set isLoading while you wait for your results. useAsyncList should handle the rest.
