### ISSUE TITLE
Meter's progress bar doesn't grow beyond 192px wide

### ISSUE THREAD

**Issue by sarnason** [adobe/react-spectrum#1192]
# 🐛 Bug Report 

By placing a Meter within a View in a Grid and trying to make it fit the width of that column only the label and value are adjusting while the progress bar stays at a max width of 192px. 
I can make it smaller and it adjusts fine, but it seems to have an upper limit.

## 🤔 Expected Behavior

It should stretch to fill the component to its width.

## 💻 Code Sample

Create a two row grid with a width of say 100% and place this in the second View.

<Meter
    label="Space used"
    valueLabel="12 of 60GB"
    value={20}
    variant="positive"
    width="100%"
  />

![Screenshot 2020-10-25 at 17 41 36](https://user-images.githubusercontent.com/2607409/97114592-5984d280-16e9-11eb-82af-c668f225c5da.png)

![GAP](https://user-images.githubusercontent.com/2607409/97114639-9f419b00-16e9-11eb-90c8-c49729eed223.png)

![Screenshot 2020-10-25 at 17 41 19](https://user-images.githubusercontent.com/2607409/97114587-50940100-16e9-11eb-999f-ded537238a20.png)

**Comment by snowystinger** [comment]
That seems like a bug.
I'm not sure why, but the Meter seems to be laid out with Flex, I think we could solve this by using Grid instead

**Comment by snowystinger** [comment]
I'll also check with our design to make sure this isn't on purpose

**Comment by snowystinger** [comment]
Bug was in CSS, filed with spectrum-css https://github.com/adobe/spectrum-css/issues/1064

**Comment by devongovett** [comment]
We should pull this change back into our copy of the css: https://github.com/adobe/spectrum-css/commit/5b39f6788d8b4c34968d808c4ff4fd50b7c9423f

**Comment by atwright147** [comment]
This still seems to be an issue. I would expect to be able to set a `width="100%"` and make it 100% width but instead I have to override two CSS rules via UNSAFE_style

```jsx
<ProgressBar
  value={50}
  UNSAFE_style={{ 'max-inline-size': '100%', 'inline-size': '100%', }}
/>
```
