### ISSUE TITLE
TextField in controlled use loses focus on "onChange"

### ISSUE THREAD

**Issue by sarnason** [adobe/react-spectrum#1193]
When I implement a controlled TextField as per the documentation [example](https://react-spectrum.adobe.com/react-spectrum/TextField.html):

It loses focus as soon as I make a change to its value.

Now, I can work around this as using autoFocus on the TextField - however it flickers as I type as it loses and regains focus on every keystroke.

I tried both using value and defaultValue as I figured that the TextField would only inject the defaultValue on render but still it is the same

A simple way to reproduce is using the sample code and entering text.
Also try adding or removing autoFocus to the TextField to see the flicker fun.

**It is very important to note that this is buried within a    DialogContainer and Dialog triggered from a MenuTrigger**

## 💻 Code Sample
[Fully working sample is here](https://codesandbox.io/s/visial-test-flickrbug-vezyl?file=/src/App.js).
1. Click on the ... menu, choose edit, type text and see the focus being lost and reapplied

**Comment by snowystinger** [comment]
I think it's because you're constantly creating a new component `EditDialog`
If you Memo it or pull the component out into it's own module level definition, it seems to work fine
https://codesandbox.io/s/visial-test-flickrbug-forked-l9jcc?file=/src/App.js

**Comment by sarnason** [comment]
🤭
👏🏻
