### ISSUE TITLE
Is it correct to have non-existing tooltips in case they aren't active?

### ISSUE THREAD

**Issue by donaldpipowitch** [adobe/react-spectrum#1197]
# ❔ Question

When I look at the official examples of the tooltips I see markup like this:

```
<span style="position: relative;">
  <button aria-describedby="react-aria-3839221732-11">I have a tooltip</button>
</span>
```

The buttons has a `aria-describedby` field, but there is no element with such an id by default.

Let's say I'd like to show a tooltip for an image instead of a button (which already contains text) I'd get linter errors like `Ensures all ARIA attributes have valid values` or `Ensures <img> elements have alternate text or a role of none or presentation`

So my questions would be:
1. Should the tooltip content _always_ be there in the markup, but visually hidden whenever the tooltip is not active?
2. Should the tooltip content always be _additional_ content, but never the _only_ description of an element?

## 🔦 Context

I try to understand more about how ARIA works.

## 💻 Code Sample

https://react-spectrum.adobe.com/react-aria/useTooltipTrigger.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by devongovett** [comment]
Yep this was a bug, and was fixed by https://github.com/adobe/react-spectrum/pull/1150. Will go out in the next release this week.
