### ISSUE TITLE
Button state not cleared when navigating back in Safari

### ISSUE THREAD

**Issue by pwalczyszyn** [adobe/react-spectrum#1202]
# 🐛 Bug Report 

When returning back to a page using back button in Safari, the `Button` component that was initially clicked to navigate away from that page is showing as hovered.

Before navigating to another page:

![image](https://user-images.githubusercontent.com/368561/97427080-751ff100-1914-11eb-917b-3a0c8d1f3172.png)

After navigating back with back button in Safari:

![image](https://user-images.githubusercontent.com/368561/97427178-8668fd80-1914-11eb-94f4-dd5413e58bf4.png)

There is one more issue, when Safari looses focus and gets it restored (after navigating back with back button), the component get's blue outline like below:

![image](https://user-images.githubusercontent.com/368561/97448355-dfdf2580-1930-11eb-8d22-eb8849d81543.png)

## 🤔 Expected Behavior

The button should have default state.

## 😯 Current Behavior

This can be tested on [labs.adobe.com](https://labs.adobe.com)

## 💻 Code Sample

This is how the button is used:
```
<Button variant="primary" elementType="a" href={pageLink}>Learn more</Button>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.4.0
| Safari          | 14.0
| Operating System | macOS Catalina

## 🧢 Your Company/Team

Adobe

**Comment by dkario** [comment]
Hi @pwalczyszyn, this is the expected behavior for RSP3 focus management. From the [`FocusRing` docs](https://react-spectrum.adobe.com/react-aria/FocusRing.html):

> Focus rings are only visible when interacting with a keyboard so as not to distract mouse and touch screen users. When we are unable to detect if the user is using a mouse or touch screen, such as switching in from a different tab, we show the focus ring.

**Comment by snowystinger** [comment]
For the first part, is that a visited style being applied? do you have any styles that might be interfering?
Can you explain more of how to test it on labs.adobe.com? i clicked a button, was navigated away, when I came back I didn't see the dark background or the focus ring

**Comment by pwalczyszyn** [comment]
@snowystinger this is happening on Safari 14.0, one of my colleagues has older version of Safari and he can't reproduce it. Our additional style is not interfering I believe. What you can see in the screenshot below the styles `is_hovered_7a745` and `_focus-ring_7a745` are not removed when returning back to the page.

![image](https://user-images.githubusercontent.com/368561/97537586-50348800-19bf-11eb-9801-2a20aaa096c7.png)

**Comment by pwalczyszyn** [comment]
I was just able to reproduce this in Chrome. When I CMD + Click on a button and move mouse away and release CMD button.

![chrome](https://user-images.githubusercontent.com/368561/97538692-1f555280-19c1-11eb-90f0-a6f194f75299.gif)

**Comment by pwalczyszyn** [comment]
I'm also seeing similar behaviour on https://react-spectrum.adobe.com/react-spectrum/Button.html

![chrome](https://user-images.githubusercontent.com/368561/97539669-a951eb00-19c2-11eb-9016-cd95cf4391bf.gif)

**Comment by devongovett** [comment]
I believe this is expected behavior. The keyboard focus style appears when any key is pressed to indicate where focus is on the page. That said, we could potentially ignore modifier keys in particular like Cmd/Shift/Alt, but that would not match native `:focus-visible` behavior. This has already been reported in #1024, so closing as a duplicate.

**Comment by pwalczyszyn** [comment]
@devongovett I don't agree that this should be closed. Using CMD+Click was just one easy way to reproduce it. But real problem is in Safari when no modifier key is used, and when when you navigate back (using back button) the button maintains hovered state.

**Comment by devongovett** [comment]
Hovered or focused? Does the focus ring appear? If so, then that's expected too.

**Comment by pwalczyszyn** [comment]
Just hovered, like below:

![image](https://user-images.githubusercontent.com/368561/97995529-e82ed900-1de6-11eb-9eb7-b9b1b0d1a738.png)


Focus ring is another issue that appears when Safari regains focus (or you switch tab back).

**Comment by snowystinger** [comment]
I'm unable to do this with just a click in Safari. When I click "Learn more", I'm taken to a new page in same tab. When I hit the back button, I'm taken back to this card view and the button for "Learn more" looks normal (no fill and no focus ring). Is there anything else to this instruction?

I do see the CMD+Click behavior that is reported in #1024
