### ISSUE TITLE
Table visual bugs

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#1207]
# 🐛 Bug Report 

- [ ] Table is sometimes blurry on initialization, goes away on scroll, see screenshot (DL, Firefox Android Windows)
- [ ] When the select all checkbox switches from indeterminate to checked it appears un-emphasized briefly (DG)
- [x] Active state should be removed when there is no selection enabled

## 🧢 Your Company/Team

RSP

**Comment by matthewdeutsch** [comment]
closing in favor of #1834
