### ISSUE TITLE
Tooltips on ActionGroup Items mutate the key strings

### ISSUE THREAD

**Issue by jluyau** [adobe/react-spectrum#1212]
# 🐛 Bug Report 

Wrapping an `ActionGroup`'s `Item`s with `TooltipTrigger` will cause an extra ".$" to be added to the key strings, which show when an Item is selected.

## 🤔 Expected Behavior

Key strings are not mutated.

## 😯 Current Behavior

Key strings get an added ".$" (e.g. `key="add"` will result in `$.add`)

## 💻 Code Sample

https://codesandbox.io/s/mystifying-grothendieck-1jdmd?fontsize=14&hidenavigation=1&theme=dark

```
import React from "react";

import {
  ActionGroup,
  Tooltip,
  TooltipTrigger,
  defaultTheme,
  Item,
  Provider
} from "@adobe/react-spectrum";
import "./styles.css";

export default function App() {
  return (
    <Provider theme={defaultTheme}>
      <ActionGroup
        selectionMode="single"
        disallowEmptySelection
        onSelectionChange={(sel) => console.log("selected 1", sel)}
      >
        <TooltipTrigger delay={0}>
          <Item key="a">A</Item>
          <Tooltip>Alpha</Tooltip>
        </TooltipTrigger>
      </ActionGroup>

      <ActionGroup
        marginTop="20px"
        selectionMode="single"
        disallowEmptySelection
        onSelectionChange={(sel) => console.log("selected 2", sel)}
      >
          <Item key="a">A</Item>
      </ActionGroup>
    </Provider>
  );
}
```
Click the top "A" button and observe in the console that the selected value is ".$a".
Click the bottom "A" button and observe in the console that the selected value is "a".

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

quarry

**Comment by LFDanLu** [comment]
@jluyau This is probably the `React.Children.toArray(children)` call in TooltipTrigger mutating the children's keys (https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx#L76). We can probably substitute the `toArray` call with the following approach from Breadcrumbs (https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx#L42-L47).

**Comment by johnjacobkenny** [comment]
@LFDanLu I can take this up. Curious to know your thought on whether to extract the code from Breadcrumbs into `utils` before making this change?

**Comment by LFDanLu** [comment]
@johnjacobkenny Thanks for picking this up! I think for now it is fine to open a pull without extracting the `Children.forEach` into `utils`, but definitely feel free to raise that question within the pull so other reviewers can weigh in.

As for throwing an error, what did you have in mind? I think the docs should probably mention the ordering required like DialogTrigger does (https://react-spectrum.adobe.com/react-spectrum/DialogTrigger.html#content), but both of these things can be done in a separate PR/issue IMO.

**Comment by samiur98** [comment]
Hey @LFDanLu, I worked on the issue and create a PR that implements the fix along with a storybook test.

**Comment by johnjacobkenny** [comment]
@LFDanLu well it seems I'm beaten to creating the PR. However, I think may be enough to have the docs updated to mention the ordering.

**Comment by LFDanLu** [comment]
Closing since PR has been merged and separate issue made
