### ISSUE TITLE
Picker Popup not showing if it got attached in the DOM as part of a DOM-Tree with "display: hidden"

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#1213]
# 🐛 Bug Report 

Attaching an Picker who is contained in an DOM-Tree who is "display: hidden" when added to the DOM fails to open the Picker Popup.

## 🤔 Expected Behavior

It does matter if the tree is hidden or not and the Picker Popup just opens

## 😯 Current Behavior

The Popup does not open appropriately (one just sees a thin line)

![Bildschirmfoto 2020-10-30 um 12 18 03](https://user-images.githubusercontent.com/52631/97699310-3328b380-1aaa-11eb-8f3b-6314b25bb240.png)

## 💻 Code Sample

```typescript
function Bug() {
  const [state, setState] = useState(0);

  return (<div>
    <div style={{display: state % 2 === 0 ? 'block' : 'none'}}>
      <Picker label="Choose A">
        <Item key="rarely">A1</Item>
        <Item key="sometimes">A2</Item>
        <Item key="always">A3</Item>
      </Picker>
    </div>
    <div style={{display: /* state === 0 ||*/ state % 2 === 1 ? 'block' : 'none'}}>
      <Picker label="Choose B">
        <Item key="rarely">B1</Item>
        <Item key="sometimes">B2</Item>
        <Item key="always">B3</Item>
      </Picker>
    </div>
    <ActionButton onPress={() => setState(state + 1)}>Toggle</ActionButton>
  </div>);
}
```

Click Toggle and you should see something like shown in the screenshot above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | master
| Browser          | FF / Chrome
| Operating System | OS-X

**Comment by snowystinger** [comment]
Here's a codesandbox https://codesandbox.io/s/red-firefly-5975t
It seems as though it doesn't remeasure after initial render. So display none has a width of 0 when it's figuring out the overlay size. I've added a different case where the Picker size just changes to demonstrate this as well.

**Comment by snowystinger** [comment]
We might be able to add a useResizeObserver https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/utils/src/useResizeObserver.ts call in here to handle it https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/picker/src/Picker.tsx
Where we observe the trigger size.
