### ISSUE TITLE
Collection: useListState: manager.select is not a function

### ISSUE THREAD

**Issue by cedeber** [adobe/react-spectrum#1215]
Hello, 

I am wondering if the last changes here https://github.com/adobe/react-spectrum/blob/879cbbdd5031a8d6ac4e91272c8e73d7dd38b0c9/packages/%40react-aria/selection/src/useSelectableItem.ts#L72 doesn't breaks the ListBox example you can find here: https://react-spectrum.adobe.com/react-aria/useListBox.html#example

The example online is still working for the moment (is the website always at the lastest state?), but when I tried it with the last update from few days ago it breaks it with the error: `manager.select is not a function`.

As I never tried it before, I currently still have hard time to figure out what is exactly broken.
But I'll post an issue anyways, in case the problem is not only on my side 😅

Thanks.

**Comment by devongovett** [comment]
Make sure all of your node_modules are up to date. Possibly @react-aria/selection isn't on the latest version due to a lockfile or something?

**Comment by cedeber** [comment]
😣 Oh my, you saved my Friday. A fresh install fix it. Thank you. Have a nice week-end 😊
