### ISSUE TITLE
Avoid wrapping ActionGroup's Item in TooltipTrigger component by adding a prop to Item Component

### ISSUE THREAD

**Issue by aashritandon92** [adobe/react-spectrum#1221]
# 🙋 Feature Request

In order to have Tooltip appear on ActionGroup Items, we need to wrap every item in TooltipTrigger component and provide tooltip to it. If item could have a `tooltip` prop attached to it, the code can have less duplication, and will be easier to read, write and understand.

## 🤔 Expected Behavior

```
<ActionGroup isQuiet selectionMode="single">
   <Item key="a" tooltip="A" placement="bottom"> A </Item>
   <Item key="b" tooltip="B" placement="bottom"> B </Item>
   <Item key="c" tooltip="C" placement="bottom"> C </Item>
</ActionGroup>
```

## 😯 Current Behavior
```
<ActionGroup selectionMode="single">
        <TooltipTrigger delay={0}>
          <Item key="a">A</Item>
          <Tooltip>A</Tooltip>
        </TooltipTrigger>
        <TooltipTrigger delay={0}>
          <Item key="b">B</Item>
          <Tooltip>B</Tooltip>
        </TooltipTrigger>
       <TooltipTrigger delay={0}>
          <Item key="c">C</Item>
          <Tooltip>C</Tooltip>
        </TooltipTrigger>
</ActionGroup>
```

## 🧢 Your Company/Team

Adobe/CC

**Comment by snowystinger** [comment]
Thanks for the suggestion! I think it'd be best for you to create a component that joins them. If we do this in React Spectrum, then ActionGroup will have a dependency on Tooltip which means that tree shaking won't be as effective and will increase the size of packages.

**Comment by snowystinger** [comment]
We had a discussion in the team about this. Since the children must be `Item`'s you actually cannot create a component to do this. We contemplated adding Tooltip to the button, however, we'd have to then support every prop for TooltipTrigger and Tooltip and that is not a route we want to go.
For now, the best thing you can do is wrap each Item in a TooltipTrigger as you're doing.
