### ISSUE TITLE
Warning on useListBox controlled keys

### ISSUE THREAD

**Issue by jeroenwienk** [adobe/react-spectrum#1223]
# 🐛 Bug Report 

The [useListBox](https://react-spectrum.adobe.com/react-aria/useListBox.html#sections) example gives a warning when using controlled state in multiple selection mode. I've provided an example create react app repo where this can be reproduced. The warning shows on the first selection only.

![image](https://user-images.githubusercontent.com/6419150/98017494-a3636c00-1dff-11eb-9e8d-cddcd212ffd7.png)

```javascript
function App() {
  const [selectedKeys, setSelectedKeys] = React.useState([]);

  return (
    <div>
      <ListBox
        label="Choose an option"
        selectionMode="multiple"
        selectedKeys={selectedKeys}
        onSelectionChange={(selectedKeys) => {
          setSelectedKeys([...selectedKeys.values()]);
        }}
      >
        <Section title="Section 1">
          <Item key={1}>One</Item>
          <Item key={2}>Two</Item>
          <Item key={3}>Three</Item>
        </Section>
        <Section title="Section 2">
          <Item key={4}>One</Item>
          <Item key={5}>Two</Item>
          <Item key={6}>Three</Item>
        </Section>
      </ListBox>
      <pre>
        {JSON.stringify({ keys: selectedKeys }, null, 2)}
      </pre>
    </div>
  );
}
```

## 🤔 Expected Behavior
I expect to be able to keep controlled selection state in a parent component without receiving warnings.

## 😯 Current Behavior
A warning is shown on the first selection. 

## 💻 Code Sample

[https://github.com/jeroenwienk/react-aria-listbox](https://github.com/jeroenwienk/react-aria-listbox)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.1.0
| react-stately   | 3.0.1
| react   | 16,17
| Browser          | Chrome 86.0.4240.111, Firefox 82.0
| Operating System | Windows 10.0.18362 Build 18362

**Comment by snowystinger** [comment]
I believe this issue will be fixed by this change https://github.com/adobe/react-spectrum/pull/1029/files#diff-927eebaa6f590e895634eae7f762db38e91f5f30a71fb8960c620cabfa59d058R50

**Comment by snowystinger** [comment]
updating stale links as that change was broken out
This PR should fix this issue now https://github.com/adobe/react-spectrum/pull/1375

**Comment by reidbarber** [comment]
Fixed via https://github.com/adobe/react-spectrum/pull/1375
