### ISSUE TITLE
Qn: Using function in dependency array for useEffect

### ISSUE THREAD

**Issue by johnjacobkenny** [adobe/react-spectrum#1227]
# ❔ Question
https://github.com/adobe/react-spectrum/blob/3b9fc8e26bd070c1efdedcfd7240951a887826c5/packages/%40react-spectrum/utils/src/useHasChild.ts#L20

Here the local useState method `setHasChild` has been included in the dependency array. Curious to know if there is any reason for that, from what I searched, I could not find anything.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
We use https://reactjs.org/docs/hooks-rules.html#eslint-plugin `react-hooks/exhaustive-deps`
This is required because we use setHasChild inside the hook.

**Comment by johnjacobkenny** [comment]
Yes we are using the method inside the hook, but from what I understand, adding to the deps array is only for functions that may change (e.g. those passed in as props). In this case I'm not getting a clarity about whether the setState changes.

**Comment by snowystinger** [comment]
If it doesn't change it doesn't matter if it's included. In this instance it won't change. However, eslint is not smart enough to figure that out. Rather than turn off the lint rule we include it.

Are you running into a problem with it?

**Comment by johnjacobkenny** [comment]
No @snowystinger, I was just curious about it. 🙂
