### ISSUE TITLE
What happens if use both usePress and useMove

### ISSUE THREAD

**Issue by Zaynex** [adobe/react-spectrum#1228]
# ❔ Question

What happens if use both usePrecss and useMove ?

## 🔦 Context

It's not issue to me. But about API design.Maybe it will cause issue.
## 💻 Code Sample

```
function Demo() {
  const  { moveProps } = useMove();
  const { pressProps } = usePress();
  return <div {...pressProps} {...moveProps} ></div>
}
```

I read the source code, pressProps wrapper onClick ,onMouseDown, etc events handler.
But if moveProps wrapper mouseDown event, it will cover previous pressProps's mouseDown.

The pressProps hook may has no effect.

**Comment by snowystinger** [comment]
You can use the utility function `mergeProps` to join those https://react-spectrum.adobe.com/react-aria/mergeProps.html

**Comment by Zaynex** [comment]
Yes, `mergeProps` is useful. But if developer register custom mouseDown event, How to solve?
```
function Demo() {
  const  { moveProps } = useMove();
  const { pressProps } = usePress();
  const handleMouseDown = () => {};
  return <div {...pressProps} {...moveProps} onMouseDown={handleMouseDown}></div>
}
```

It should work if use `mergeProps`.What if developer doesn't aware of that.I mean we can't use react event handler directly if we use moveProps or pressProps.
```
function Demo() {
  const  { moveProps } = useMove();
  const { pressProps } = usePress();
 const handleMouseDown = () => {}
  const mergedProps = mergeProps(moveProps, pressProps, {handleMouseDown})
  return <div {...mergedProps}></div>
}
```

**Comment by snowystinger** [comment]
Well, handleMouseDown isn't the right name for that, but I'll assume it's pseudo code. Our recommendation is to use the hooks usePress or useMove as they have been normalized for many different interactions. If you must make your own onMouseDown, then you should merge it with the results of useMove and usePress as you did in that last example you wrote. We have documentation and typescript to express this. Are you running into any specific problems?

**Comment by Zaynex** [comment]
Thanks for your patient explanation. I just wnat to figure out the api design.
