### ISSUE TITLE
Support autofocus on Picker

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#1229]
# 🙋 Feature Request

We have an input form where a Picker is the first field but we can not mark it as the initial focus receiver as unlike eg TextField it has no autofocus-Property.

## 🤔 Expected Behavior

Provide an autofocus-Property like it is available on other Elements like buttons, text-inputs, ...

## 😯 Current Behavior

Property is not available

## 💁 Possible Solution

Looking at other controls they all inherit `FocusableProps` so one possibility would be to make PickerProperties extend that as well although I'm not sure whether this was left out for a reason. A simpler and more focus solution would be to just add the autoFocus-Property directly and pass it on to FieldButton.

If you think this is a valid request it would be great if you could tell me which of the 2 options I should implement.

**Comment by LFDanLu** [comment]
@tomsontom Not sure why autoFocus isn't available on Picker since it is supported on a native select element, so I think adding `FocusableProps`/`FocusableDOMProps` sound reasonable. @devongovett was it intentionally left out here?

**Comment by LFDanLu** [comment]
@tomsontom Talked with @devongovett today, go ahead and add the FocusableProps to the PickerProperties.
