### ISSUE TITLE
Support for drag & drop in react-aria

### ISSUE THREAD

**Issue by matthewdeutsch** [adobe/react-spectrum#1230]
# 🙋 Feature Request

Drag & drop support can be useful in many React Spectrum components, including Table, and upcoming Tree and List components

## 💻 Examples

![image](https://user-images.githubusercontent.com/700930/98143534-37ccdd80-1e97-11eb-8dd8-49d04e77e349.png)

## 🧢 Your Company/Team

RSP

**Comment by josharens** [comment]
@devongovett is this still being worked on? I see that drag & drop support is "in progress" on the react spectrum sprint board but it looks like maybe it hasn't been updated in awhile. I'll need drag & drop support in the near future and I'm trying to determine if I can wait for this or if I need to look for another solution. I'm happy to contribute any way I can if needed, just let me know, thanks!

**Comment by devongovett** [comment]
@josharens yes, it is still being worked on. See #1286 for the current prototype. I will be returning to it in a week or so to try to get it merged.

**Comment by igorkulka** [comment]
Hello, are there any plans to add documentation for this? We'd love to adopt drag&drop from react-aria in our team, but we're missing some documentation. Thanks a lot for your answer

**Comment by GoranRibic** [comment]
Any news regarding documentation?
