### ISSUE TITLE
 useMenuItem access key prop causes Warning:MenuItem: `key` is not a prop

### ISSUE THREAD

**Issue by Tatamethues** [adobe/react-spectrum#1234]
# 🐛 Bug Report 

[Item](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/collections/src/Item.ts) uses key  from props, but causing warning under StrictMode.
## 😯 Current Behavior

```
Warning: MenuItem: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
Umbrella issue for strict mode: https://github.com/adobe/react-spectrum/issues/779

**Comment by Tatamethues** [comment]
looks like I used it a wrong way with ts. After, checking the codes from spectrum. I fixed the problem. Thanks.
