### ISSUE TITLE
React Aria useButton mouse click triggers :focus-visible styles

### ISSUE THREAD

**Issue by cmalven** [adobe/react-spectrum#1247]
# 🐛 Bug Report 

When clicking on a `<button>` element using `useButton` that has `:focus-visible` styles, React Aria seems to apply `focus-visible` to the `<button>`.

## 🤔 Expected Behavior

Clicking on any element should not activate `focus-visible` on that element.

## 😯 Current Behavior

Clicking on a `<button>` which uses `useButton` will apply `focus-visible` to that element.

## 🔦 Context

Before implementing React Aria, we went out of our way to apply unique styles for elements that were focused using clicks/presses and elements that were focused using the keyboard. After implementing React Aria, all components based on `useButton` apply those `:focus-visible` styles on mouse click.

**CodeSandbox**
https://codesandbox.io/s/react-aria-button-focus-visible-s29dz

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | `@react-aria/button` 3.2.2
| Browser          | Google Chrome 86.0.4240.183
| Operating System | MacOS 10.14.6

**Comment by snowystinger** [comment]
Can you provide a codesandbox to demonstrate this? I'm not quite following. Also, we don't have a @adobe/react-spectrum or a react-aria version 3.2.2, what version are you using?

**Comment by cmalven** [comment]
@snowystinger Codesandbox link is below (and also added to original post). The example is using CSS modules for styling because that's what we are using in our app, but I don't think the styling method would make a difference.

https://codesandbox.io/s/react-aria-button-focus-visible-s29dz?file=/src/Btn.js

Not sure what you mean about the version - we're definitely using `@react-aria/button` at `3.2.2` (latest) as you can see in the Codesandbox. Maybe I'm just not understanding your versioning system.

**Comment by devongovett** [comment]
This is possibly because we programmatically focus the button on mouse down. I'm not sure what the heuristic Chrome uses to determine when to show focus-visible styles. Also, fwiw, `:focus-visible` doesn't have 100% browser support yet - Safari doesn't support it. In Safari, neither of your focus styles seem to be applying for me. It also doesn't appear to be working in Firefox, though possibly you need to use their non-standard `:moz-focusring` pseudo class instead? Even then, there's no guarantee that browsers implement the same heuristic to determine when to apply these - the spec doesn't say what it should be.

Have you considered using React Aria's [useFocusRing](https://react-spectrum.adobe.com/react-aria/useFocusRing.html) hook to apply your focus styles instead? This will ensure everything works consistently across browsers.

**Comment by cmalven** [comment]
> Also, fwiw, :focus-visible doesn't have 100% browser support yet - Safari doesn't support it. In Safari, neither of your focus styles seem to be applying for me.

We're aware of this. The CodeSandbox is a reduced test case that shows the issue, but our actual code uses fallback focus styles for browsers like Safari, etc.

Based on everything I've read about `focus-visible` and the [official spec](https://www.w3.org/TR/selectors-4/#the-focus-visible-pseudo) the current behavior of `@react-aria/button` and `link` do not seem to match the intent. I know it may seem like a small detail, but for people who put a lot of effort into the polish of their app design, this is an issue and we've opted to explore other options because of it.

React Aria is great, though. Thanks for your work on it.

**Comment by devongovett** [comment]
Ok, I don't think there is anything we can do about it though 🤷. The behavior is entirely dependent on what browsers decide to implement. I think I would classify this as a Chrome bug - the element receives focus during mouse down so therefore Chrome shouldn't apply the focus visible styles. But then again, the spec only suggests a heuristic and leaves it up to browser vendors to decide what to do.

Again, for consistent behavior, I would suggest using `useFocusRing`. We've put a ton of effort into testing it across every device and dealing with all the edge cases. Given that you're already having to implement fallback styles (presumably using JS?), perhaps you could use this instead and avoid re-creating it on your own?

**Comment by devongovett** [comment]
FWIW, if you're curious about *why* we preventDefault on mouse down and focus the element ourselves, you can read [this section](https://react-spectrum.adobe.com/blog/building-a-button-part-3.html#ensuring-consistent-focus-behavior) from our blog series on the complexities of building consistent buttons. If you want to read more, here's the [first post](https://react-spectrum.adobe.com/blog/building-a-button-part-1.html) in the series and you can follow the links to the rest.

**Comment by cmalven** [comment]
Thanks for the clarifications @devongovett I really appreciate it. Everything you're saying makes sense, and I do think the application of the `:focus-visible` styles when focus is applied via JS is probably a Chrome bug. It's just unfortunate that Chrome applies `:focus` and `:focus-visible` styles in a consistent way when focus is being applied via standard keyboard and mouse events and not via javascript.

We're not using JS to apply any focus styles in the app currently - that's all being handled via CSS, including fallback styles - but I definitely get why applying them via JS would be more consistent if we went all in on it.

Thanks again for your thoughtful responses.
