### ISSUE TITLE
ToolTips on Elements other than ActionButtons

### ISSUE THREAD

**Issue by mburri** [adobe/react-spectrum#1252]
# ❔ Question

Is it possible to add tooltiptriggers and tooltips on other elements than ActionButtons

## 🔦 Context

I'm trying to add a tooltip to an Icon like this:

```
<View>
    <TooltipTrigger>
         <AlertCircle />
         <Tooltip>a tooltip</Tooltip>
    </TooltipTrigger>
</View>
```

but that does not seem to work - the tooltip text does not show up. Do I have to wrap the Icon in a different Element? All examples and test cases are using ActionButton as first child of TooltipTrigger.

## 💻 Code Sample

see above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum  |  ^3.4.0   |
| Browser       | Brave, Chrome, Firefox| 
| Operating System | Linux | 

## 🧢 Your Company/Team

headwire/jsonforms-react-spectrum-renderers

**Comment by snowystinger** [comment]
Please attach tooltips only to interact-able components. Icons do not fall into that category by themselves, but you can use a Quiet ActionButton with an aria-label and an icon inside it as the visible label to achieve this look.

**Comment by mburri** [comment]
ah I see. Thanks for the reply!
