### ISSUE TITLE
useToggleButton value attribute and add native element <input type="checkbox">

### ISSUE THREAD

**Issue by AndyOGo** [adobe/react-spectrum#1264]
# 📝 Feedback

HTML already offers an element, which mirrors the semantics of a toggle, the `<input type="checkbox" />`.
It's even possible to implement a pure CSS toggle by utilising the checkbox hack (see linked code example below).

Why is this no mentioned within the docs?

In regard to the the buttons `value` attribute, why is it not utilised, e.g. `<button value="on/off">`?
https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-value

## 🔦 Context

https://react-spectrum.adobe.com/react-aria/useToggleButton.html#features

## 💻 Code Sample

https://codepen.io/mburnette/pen/LxNxNg

## 🧢 Your Company/Team

Private

**Comment by snowystinger** [comment]
`useToggleButton` is aria specific to a toggle button, vs a switch, vs a checkbox. These hooks also wrap functionality to normalize interactions across different inputs and devices.

As for why it's not mentioned in the docs, a toggle button is different than a switch, which does mention input type=checkbox https://react-spectrum.adobe.com/react-aria/useSwitch.html. It's also different than a checkbox, which is talked about here https://react-spectrum.adobe.com/react-aria/useCheckbox.html.

I’m not sure I follow button value on/off, this is a pattern I’ve not seen before and seems specific to forms. We use aria-pressed which a screen reader will recognize.

**Comment by AndyOGo** [comment]
Thank you very much for your quick feedback.

Sorry, your are right. I didn't read about the `useSwitch` hook yet.

To my understanding all of these `Checkbox`, `Switch` and `Toggle` elements mainly differ in their visual UI, but the underlying state should be always a boolean.
Or do I missunderstand something?

I searched the web and it seems the terms Switch and Toggle are used interchangeably, but guess they shouldn't.
https://ux.stackexchange.com/questions/40265/toggle-button-vs-check-box-and-toggle-switch

Regarding the `on`/`off` is just an example from me, it can be any value which indicates a boolean.

Anyway I just started to study your docs, and they are really a joy to read.

**Comment by snowystinger** [comment]
I'm glad you're enjoying them and am happy to have you question them.

Checkbox, Switch, and ToggleButton are all backed by the useToggleState from our stately package which we pass to useCheckbox, useSwitch, and useToggleButton. The props that each one allows and returns though are a little different. For example, useCheckbox can handle an indeterminate state that the other two are unaware of. The useToggleButton also returns button props that the other two do not. And useSwitch returns a `role=switch` that the other two do not.
Finally ToggleButtons use `aria-ispressed` to represent its selected state vs Checkbox and Switch which both use `checked` and `aria-checked`.

Does that clarify it?

**Comment by AndyOGo** [comment]
Thank you very much.
Yes, it clarifies the technical difference for me.
I will read more about the UI, ARIA viewpoint on these.
