### ISSUE TITLE
useMenuSection difference between headingProps/groupProps not clear

### ISSUE THREAD

**Issue by AndyOGo** [adobe/react-spectrum#1266]
# 🙋 Documentation Request

The `useMenuSection` hook returns an object of type `MenuSectionAria`.
What is the difference and purpose of `headingProps` and `groupProps`?
Why splitting them up, if both are for the heading element?

> `headingProps`
> Props for the heading element, if any.
> `groupProps`
> Props for the heading element, if any.
> https://react-spectrum.adobe.com/react-aria/useMenu.html#api

## 🧢 Your Company/Team

Private

**Comment by snowystinger** [comment]
Looks like we had copy paste there.
If you look a little further down at the example using that hook you can see they are on different elements.

**Comment by AndyOGo** [comment]
Thank you very much.
Indeed, the example makes that very clear :)
