### ISSUE TITLE
useOverlay in a nested overlay causes elements in the second overlay to not respond to mouse events correctly

### ISSUE THREAD

**Issue by karlpetersson** [adobe/react-spectrum#1274]
# 🐛 Bug Report 

calling `useOverlay` in a component that was rendered in an overlay causes some elements inside that component (the second overlay) to not be focusable by clicking them, e.g. inputs do not work. I am essentially trying to nest the example in `useOverlayTrigger` from the docs, see code here: https://codesandbox.io/s/trusting-perlman-4sho5?file=/src/App.tsx

If I don't call `useOverlay` it works as expected. Although, then I don't get the behaviour of closing the second popover when clicking outside. I'm guessing that the first call to `useOverlay` is interfering with mouse events in the second overlay, but I can't figure out why it shouldn't work from looking at the source.

I'm not sure if this is even intended to work, so please let me know if what I'm trying to do here doesn't make sense.

![Kapture 2020-11-16 at 17 11 32](https://user-images.githubusercontent.com/3764441/99279899-0a861500-2831-11eb-9df9-531ae8f080cf.gif)

## 🤔 Expected Behavior

Expected being able to open a second overlay from a trigger within the first overlay, and have an input element in the second overlay

## 😯 Current Behavior

Input element in the second overlay cannot be focused by clicking it

## 🔦 Context

I want to be able to open a popover from within another popover.

## 💻 Code Sample

https://codesandbox.io/s/trusting-perlman-4sho5?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Visly

**Comment by snowystinger** [comment]
Hey! I took a look at your codesandbox and what it is installing in the network tab. I see that it's resolving `@react-aria/interactions` to 3.3.0, that version has this bug, however, we recently released a patch fix to address it, 3.3.1. If you can convince codesandbox to install that, it should work.
I grabbed the zip copy of your codesandbox and aside from a few TS errors, it works (I verified that I had `@react-aria/interactions: 3.3.1` locally)

One last generic comment, you are missing passing triggerRef to useButton. It's not related to this issue, but may cause you other grievances.

**Comment by snowystinger** [comment]
Btw, here's the resolution of the package from the network tab in case you want to look for it yourself
<img width="1384" alt="Screen Shot 2020-11-16 at 1 36 51 PM" src="https://user-images.githubusercontent.com/698229/99311061-d26eda00-2810-11eb-86ba-1c201d7a286e.png">

**Comment by karlpetersson** [comment]
Thanks! bumping @react-aria/interactions to 3.3.1 solved this for me.

Just in case you weren't aware, the example for [useOverlayTrigger](https://react-spectrum.adobe.com/react-aria/useOverlayTrigger.html) is missing passing the `triggerRef` to `useButton`

**Comment by snowystinger** [comment]
Was not aware, thanks for pointing that out!
