### ISSUE TITLE
Firefox starts a selection when dismissing a dialog by clicking outside

### ISSUE THREAD

**Issue by hzr** [adobe/react-spectrum#1280]
# 🐛 Bug Report 

Go to https://react-spectrum.adobe.com/react-aria/useDialog.html#example in Firefox
Press "Open Dialog"
Click outside the dialog
Move mouse

## 🤔 Expected Behavior

No text selection should start

## 😯 Current Behavior

Text selection starts

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.1.2
| Browser          | Firefox 83
| Operating System | MacOS Big Sur

**Comment by stefanprobst** [comment]
is this the same issue as https://github.com/adobe/react-spectrum/issues/919? if so this should already be fixed in the `main` branch.

**Comment by hzr** [comment]
Yes, same. (I probably just searched open issues.)

Thanks!
