### ISSUE TITLE
Table - initialDescriptor prop does not sort properly

### ISSUE THREAD

**Issue by bryantabaird** [adobe/react-spectrum#1296]
# 🐛 Bug Report 

I can't seem to use the `initialSortDescriptor` prop on a Table correctly. I realize that this is in alpha too, so this may be known, but I couldn't find this issue.

## 🤔 Expected Behavior

Table should be sorted correctly on load.

## 😯 Current Behavior

Regardless of whether I pass in `ascending` or `descending`, the table doesn't sort with an async list. See the attached codesandbox.

## 💻 Code Sample

https://codesandbox.io/s/admiring-gates-v04hd

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Adobe Analytics

**Comment by LFDanLu** [comment]
@bryantabaird Thanks for filing this issue, I see the same thing locally as well. I noticed that toggling the sort order actually causes it to sort properly, so maybe we just aren't performing the sort on intiial load

**Comment by bryantabaird** [comment]
Correct... just on initial load from my experience as well

**Comment by LFDanLu** [comment]
@bryantabaird Did some digging in our `useAsyncList` function and I think this is actually working as intended. We pass the `sortDescriptor` to the `load` function that you provide to `useAsyncList` [here](https://github.com/adobe/react-spectrum/blob/main/packages/@react-stately/data/src/useAsyncList.ts#L241-L247) so you can actually leverage your `sort` function in your `load` to handle initial sorting:

```
...
    async load({ sortDescriptor }) {
      let projects = await getCollectionItems();
      let items = projects.sort((a, b) =>
        sortFn(a, b, sortDescriptor.column, sortDescriptor.direction)
      );
      return {
        items
      };
    },
    initialSortDescriptor: { column: "name", direction: "descending" },
...
```
Here is a codesandbox that I forked from yours: https://codesandbox.io/s/xenodochial-shannon-4v71o. Note that you might have to open the sandbox into a new window/hit that refresh button after you change the sort order in the code, for some reason the little preview on the right doesn't update w/o it

**Comment by bryantabaird** [comment]
Sorry just seeing this... I'll look into it shortly

**Comment by bryantabaird** [comment]
Yes, seems that utilizing the `sortDescriptor` param in the load function object resolved the issue, which the sandbox provided was not doing. Feel free to mark as resolved, thanks!
