### ISSUE TITLE
usePreventScroll + overlay + sticky navbar causes flicker on iOS

### ISSUE THREAD

**Issue by alexanderbluhm** [adobe/react-spectrum#1300]
# 🐛 Bug Report 

**(I solved this by replacing the sticky navbar with a fixed one but maybe this is interesting for someone)**
I use a sidebar transition on my page. Since I don't want to scroll the body when the sidebar is open is use `usePreventScroll ` to fix this.
I also have a sticky navbar and the combination of the overlay, the navbar and the prevent scroll causes a weird flicker on Safari (iOS). I attached a video and a codesandbox demo.

## 🤔 Expected Behavior

The overlay should fade in and out without flicker.

## 😯 Current Behavior

There is a little but noticable flicker on the top of the page.
![flicker](https://user-images.githubusercontent.com/6071634/99847124-dd5e9d00-2b77-11eb-8605-e60759e0661a.png)
In the middle image you can see the content popping over the sticky navigation.
I tested several `z-index` things but none of them seems to work.

## 💁 Possible Solution

The problem has to do with the sticky navbar. If it is not there it works.

## 🔦 Context

I am trying to make a simple layout with a navbar, content and a slideover (overlay).

## 💻 Code Sample

https://codesandbox.io/s/musing-khayyam-x0l42?file=/src/App.js#

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.1.1
| Browser          | latest Safari
| Operating System | iOS

## 🧢 Your Company/Team

Freelance project for an analytical software

**Comment by snowystinger** [comment]
I'm unable to reproduce this on Safari iOS 14.2.1
I think this is what you were doing to see the issue? https://codesandbox.io/s/magical-napier-nujlt

**Comment by alexanderbluhm** [comment]
@snowystinger Hmm weird, it is visible for me on your example on iOS 14.2 with iPhone Xs.
I will check it on another device.

**Comment by snowystinger** [comment]
I don't see it happen on a family member's iPhone XS running iOS 14.1
Let me know what you find on another device, I'll pass it around my team as well

**Comment by alexanderbluhm** [comment]
@snowystinger Also occurs on my IPad. I can attach a video tomorrow.
Just to be sure how I reproduce this:
- I scroll down a little bit to see the „open“ button.
- I click the button, I see the flicker and the sidebar opens 
- I close the sidebar, scroll a little bit and repeat the steps > I see the flicker again.

Thank you very much for your help! :)

**Comment by alexanderbluhm** [comment]
https://vimeo.com/483452163

**Comment by snowystinger** [comment]
Hey, sorry for the delay, no one on the team has been able to reproduce this issue. Could you potentially do some profiling to narrow down what's going on?

**Comment by dannify** [comment]
Unable to reproduce. Please reopen with more information.
