### ISSUE TITLE
docs: Add a note on retrieving selection state for checkbox group item

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#1302]
# 🙋 Documentation Request

The docs for `useCheckboxGroup` and `useCheckboxGroupItem` provide [an example](https://react-spectrum.adobe.com/react-aria/useCheckboxGroup.html#example) that renders a native `input` element (which visually indicates its selection state automatically). For checkbox group items with custom styling, the docs [refer to the `useCheckbox` styling section](https://react-spectrum.adobe.com/react-aria/useCheckboxGroup.html#styling).

For me, it was not immediately obvious that a checkbox group item needs to retrieve its selection state with [`state.isSelected(props.value)`](https://react-spectrum.adobe.com/react-stately/useCheckboxGroupState.html#interface) (to be able to apply styles depending on selection state) - while a standalone checkbox has direct access via `state.isSelected`.

Maybe add a quick note to the styling section, or provide a basic example for custom styling (w/ isSelected and isDisabled) to the `useCheckboxGroupItem` docs? Thanks!

**Comment by snowystinger** [comment]
clarification is great! would you like to take a go at adding to the example? The file is located here https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/checkbox/docs/useCheckboxGroup.mdx

**Comment by stefanprobst** [comment]
> would you like to take a go at adding to the example?

sure! just a quick question what approach you want to recommend in the docs:

```js
// const groupState = React.useContext(CheckboxGroupContext)
// const {inputProps} = useCheckboxGroupItem(props, state, ref)

const isSelected = groupState.isSelected(props.value)
const isDisabled = groupState.isDisabled || props.isDisabled
// *** or ***
const isSelected = inputProps.checked
const isDisabled = inputProps.disabled
```

the second approach is [from the `react-spectrum` implementation](https://github.com/adobe/react-spectrum/blob/b297fe284f29e5f387b8d4bd81f0bf3447effe1b/packages/%40react-spectrum/checkbox/src/Checkbox.tsx#L83) - but it feels a bit odd to read the state from the DOM props. the first approach effectively just copies what is already [in `useCheckboxGroupItem`](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/checkbox/src/useCheckboxGroupItem.ts#L30).

**Comment by snowystinger** [comment]
The first is probably better if it's how useCheckboxGroupItem already works. We probably do it the other way in react spectrum because the groupState was added much later.

**Comment by stefanprobst** [comment]
cool :+1: - yes i thought so - probably due to the conditional react-hooks acrobatics in `useCheckboxGroupItem`. will send pr tomorrow!
