### ISSUE TITLE
types: Make AriaBreadcrumbItemProps interface public

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#1303]
# 🙋 Feature Request

While `useBreadcrumbs` makes the `AriaBreadcrumbsProps` interface publicly available via `@react-types/breadcrumbs`, `useBreadcrumbItem` [does not export the `AriaBreadcrumbItemProps` interface](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/breadcrumbs/src/useBreadcrumbItem.ts#L18-L24), either directly or via `@react-types/breadcrumbs`

## 🤔 Expected Behavior

`AriaBreadcrumbItemProps` should be public.

## 😯 Current Behavior

`AriaBreadcrumbItemProps` is not be public.

## 💁 Possible Solution

[`AriaBreadcrumbItemProps`](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/breadcrumbs/src/useBreadcrumbItem.ts#L18-L24) should maybe be moved to the `@react-types` package.

**Comment by LFDanLu** [comment]
@stefanprobst Sounds reasonable to me, we should probably move [AriaBreadcrumbItemProps](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/breadcrumbs/src/useBreadcrumbItem.ts#L18-L24) to [here](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-types/breadcrumbs/src/index.d.ts)
