### ISSUE TITLE
React stately/Aria - isRequired

### ISSUE THREAD

**Issue by chrisphillers** [adobe/react-spectrum#1304]
## Question

I am unable to use "isRequired" or "orientation:horizontal" props using useRadioGroup -  it is not having any impact on the layout/style.

## 🔦 Context

Hi, getting a little confused between using Aria/stately/vanilla spectrum libraries. I am using all three in one project, however I would like to use Adobe Stately to manage state in my form - to do this I am using Aria for some components and Spectrum for others and having difficulty styling the 2 to match. I am unable to use "isRequired" or "orientation:horizontal" props using useRadioGroup - it is not having any impact on the layout/style.

Looking at the code below I am creating my own isRequired styling (which shouldnt be necessary I imagine) - I am passing in orientation="horizontal" and isRequired in to my RadioGroup function.

Am I using the correct library? Is the below as I should be going about it?

## 💻 Code Sample
```
import {
  useRadioGroupState,
  Item,
  Section,
  useListData,
  useCheckboxGroupState,
} from 'react-stately';

import { useRadioGroup, useRadio } from '@react-aria/radio';

  const RadioGroupChris = props => {

    const { children, label } = props;
    const state = useRadioGroupState(props);
    const { radioGroupProps, labelProps } = useRadioGroup(props, state);
    
    return (
      <div {...radioGroupProps}>
        <span {...labelProps}>
          {label}
          {/* {isRequired ? '*' : ''} */}
        </span>
        <RadioContext.Provider value={state}>
          <div style={{ display: 'flex' }}>{children}</div>
        </RadioContext.Provider>
      </div>
    );
  };

  const RadioChris = props => {
    const { children } = props;
    const state = React.useContext(RadioContext);
    const { inputProps } = useRadio(props, state);

    return (
      <label style={{ display: 'flex', alignItems: 'center' }}>
        <input {...inputProps} />
        {children}
      </label>
    );
  };

function App() {
  return (
    <RadioGroupChris
      label={label}
      orientation="horizontal"
      isRequired
      necessityIndicator="icon"
      display="flex"
    >
      <RadioChris value={option1.value}>{option1.name}</RadioChris>
      <RadioChris value={option2.value}>{option2.name}</RadioChris>
    </RadioGroupChris>
  );
}
```
## 🌍 Your Environment

Javascript/Parcel running on Docker

| Software         | Version(s) |
| ---------------- | ---------- |
adobe/react-spectrum: 3.5.0
react-stately/radio: 3.2.1
react-stately": 3.0.1
| Browser          |  Chrome
| Operating System | MacOS

## 🧢 Your Company/Team

DemDx

**Comment by snowystinger** [comment]
Hey! sorry to hear you're having an issue. I hope you don't mind, but I edited your description to make it a little more readable. Please feel free to correct any assumptions I made while doing it.
I think you're missing the props on `{props.isRequired ? '*' : ''}`.
We don't control your rendering logic, so you do need to render your own isRequired style of label if you're going to just use the hooks. The hook you are using should just concern itself with aria attributes to convey required.
This https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/radio/src/RadioGroup.tsx#L70 is our way of handling that. We created an internal Label component that knows what to do with isRequired and localizes it appropriately.
I'd suggest also reading the prop description here https://react-spectrum.adobe.com/react-spectrum/RadioGroup.html#labeling to see how we control the style of required label we use.

Hope that helps!

**Comment by chrisphillers** [comment]
Hi @snowystinger 
That is helpful thank you and of course no problem correcting my post.:)
So we do indeed need to create our own label/styling to achieve the same look/functionality as vanilla "react spectrum" components - I hoped naively that would be built in!
Your pointer very helpful thank you.
