### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by isJaakko** [adobe/react-spectrum#1305]
I don't know how to install all dependencies of the **react-spectrum** and I did't find any instructions.
So how can I run it.
Thank you.

**Comment by snowystinger** [comment]
Hey! are you trying to build react-spectrum or use it?
If using it, I'd suggest starting here https://react-spectrum.adobe.com/react-spectrum/getting-started.html
If you're trying to run it, you should be able to clone it, go to the root, `yarn install` (i use yarn 1.21, node 12.x) and that should get you going

**Comment by isJaakko** [comment]
Got it. Thank you.
