### ISSUE TITLE
Property 'children' does not exist on type 'AriaRadioGroupProps'

### ISSUE THREAD

**Issue by matamatanot** [adobe/react-spectrum#1310]
# 🐛 Bug Report 

I wrote the code in Typescript with the documentation.
https://react-spectrum.adobe.com/react-aria/useRadioGroup.html

But I got an error saying "Property 'children' does not exist on type 'AriaRadioGroupProps'".
<img width="625" alt="vscode" src="https://user-images.githubusercontent.com/39780486/100531088-7dce5480-323d-11eb-9b21-db6679a19ca0.png">

## 🤔 Expected Behavior

Property 'children' exist on type `AriaRadioGroupProps`.
`interface AriaRadioGroupProps extends RadioGroupProps, DOMProps, AriaLabelingProps, AriaValidationProps {}`

or

Change Document. #865 

## 💁 Possible Solution

Add Property `children`.

## 💻 Code Sample

```
export function RadioGroup(props: AriaRadioGroupProps) {
  const { children, label } = props;
  const state = useRadioGroupState(props);
  const { radioGroupProps, labelProps } = useRadioGroup(props, state);

  return (
    <div {...radioGroupProps}>
      <span {...labelProps}>{label}</span>
      <RadioContext.Provider value={state}>{children}</RadioContext.Provider>
    </div>
  );
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/radio   |"3.1.2" |

**Comment by stefanprobst** [comment]
similar with `AriaCheckboxGroupProps`, while `SpectrumCheckboxGroupProps` (and `SpectrumRadioGroupProps`) *does* include `children`

**Comment by LFDanLu** [comment]
@matamatanot @stefanprobst So the `AriaRadioGroupProps` and `AriaCheckboxGroupProps` don't include children because the aria hooks that they are used in aren't responsible for rendering, just for providing accessibility attributes and interaction handlers for said component. IMO you should create your own types for your components that extend from these types and that is where you can add a `children` type def.

**Comment by matamatanot** [comment]
@LFDanLu 
I'm sorry, I misunderstood.
In fact, React Spectrum extended this type.
https://github.com/adobe/react-spectrum/blob/73840f5e8697b97ca42c15b0627f10137e3c8a88/packages/%40react-types/radio/src/index.d.ts#L59-L69

Thank you for the useful advice.
