### ISSUE TITLE
useModel error after upgraded to v3.5.0 react spectrum

### ISSUE THREAD

**Issue by karthik-reddivari-dx26** [adobe/react-spectrum#1311]
# 🐛 Bug Report 

After upgraded to react spectrum v3.5.0 we are facing the issue on all the component that depends on useModel like menu, dialog. I tried updating the react-aria to 3.1.0 but no luck. 

The error message says `Modal is not contained within a provider` but i am sure that i have added Spectrum provider in my app.tsx and it works for v3.4.0

## 🤔 Expected Behavior
Components should work as expected

## 😯 Current Behavior
Breaks the component and i see a error in the console.
<img width="527" alt="Screenshot 2020-11-29 at 9 44 36 AM" src="https://user-images.githubusercontent.com/66973203/100537297-8f0c6680-3227-11eb-9a8a-183d84d8d0f5.png">

## 💻 Code Sample
It's breaking with the basic examples of menu, dialog

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
@karthik-reddivari-dx26 Do you mind adding a code snippet showing your Provider setup or a basic sandbox example reproducing this issue? We've also seen similar issues get resolved by clearing your node_modules and package lock files and doing a reinstall, might be worth a shot here

**Comment by karthik-reddivari-dx26** [comment]
@LFDanLu Sorry for getting back late. Looks like the issue is causing because of `@spectrum-icons/illustrations": "^3.2.0` but i am not really sure why they are dependent but once we updated the version to `@spectrum-icons/illustrations": "^3.2.1` it started working.
This might be useful for someone if they face the same issue. I am closing this issue thanks for your support
