### ISSUE TITLE
Is there a way to use onPress with Next.js Link child function component?

### ISSUE THREAD

**Issue by jgil-r** [adobe/react-spectrum#1314]
# ❔ Question

In Next.js, if the child of their Link component is a function component, I have to wrap it in React.forwardRef. I am trying to use React Aria's useLink hook, but in the browser I am getting `onClick is deprecated, please use onPress`. Is there a way to use onPress? 

## 💻 Code Sample
My custom link component:
```jsx
import { forwardRef } from 'react';
import { useLink } from '@react-aria/link';

const RouterLink = forwardRef((props, ref) => {
  let { linkProps } = useLink(props, ref);
  let { onClick, href, children } = props;

  return (
    <a href={href} onClick={onClick} ref={ref} {...linkProps}>
      {children}
    </a>
  );
});

export default RouterLink;
```
Then use it as a child of next/link:
```jsx
<Link href="/" passHref>
  <RouterLink>Text</RouterLink>
</Link>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/link   | 3.1.2
| Browser          | Firefox 83.0 (64-bit)
| Operating System | Linux Mint 20 Cinnamon

**Comment by LFDanLu** [comment]
@jgil-r I'm not familiar with Next.js at all, but is there anything preventing you from using `onPress` instead of `onClick` in your `RouterLink` props? That would get rid of your console error.

**Comment by jgil-r** [comment]
@LFDanLu That's what I'm confused about, because I don't need to use onPress. I just pass down href prop to my custom `<a/>` component and I can either use it with Next.js [Link](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-function-component) component for client-side route changes or just on it's own to go to a given url.

**Comment by snowystinger** [comment]
What if you did something to the effect of:
```
const RouterLink = forwardRef((props, ref) => {
  let { linkProps } = useLink({...props, onClick: undefined, onPress: props.onClick}, ref);
  let { href, children } = props;

  return (
    <a href={href} ref={ref} {...linkProps}>
      {children}
    </a>
  );
});
```

We marked onClick as deprecated within our hooks because we built usePress to handle all touch/click/keyboard interactions in the same way. If you are interested in knowing more about that normalization, I suggest reading our 3 part blog post about how not simple buttons actually are https://react-spectrum.adobe.com/blog/building-a-button-part-1.html

**Comment by jgil-r** [comment]
@snowystinger I get the following error. I'll take a look at the blog post though, thanks for the link.

```
Uncaught TypeError: Cannot read property 'nodeName' of undefined
    at linkClicked (link.js:47)
    at onClick (link.js:225)
    at triggerPressEnd (module.js:211)
    at HTMLDocument.onPointerUp (module.js:383)
```

**Comment by snowystinger** [comment]
ah, looks like Next.js Link is looking at e.currentTarget and it's not coming through onPress https://github.com/vercel/next.js/blob/canary/packages/next/client/link.tsx#L86

Good news, we're still actually sending that through https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/usePress.ts#L171

```
const RouterLink = forwardRef((props, ref) => {
  let { linkProps } = useLink({...props, onClick: undefined, onPress: (e) => props.onClick({...e, currentTarget: e.target})}, ref);
  let { href, children } = props;

  return (
    <a href={href} ref={ref} {...linkProps}>
      {children}
    </a>
  );
});
```

**Comment by jgil-r** [comment]
That worked. Thanks again for the links and help!

**Comment by snowystinger** [comment]
You can always add preventDefault, we already do that in usePress, so this is safe. And then you should be able to cast the event type
```
onPress: (e) => props.onClick({...e, currentTarget: e.target, preventDefault: () => {}} as WhateverEvent)
```
