### ISSUE TITLE
[rfc] allow checkbox group as a single tabstop, or add layout grid primitive

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#1321]
# 🙋 Feature Request

Currently, a checkbox group behaves mostly like a set of individual checkboxes inside a "fieldset" element with `role=group`, which manages selection state. This means that every individual checkbox will have a `tabIndex` and moving through a checkbox group with a keyboard means moving over every checkbox in the group. It is also the approach suggested - in passing - in the WAI-ARIA Authoring Practices 1.1 and 1.2.[^1]

With longer checkbox groups - for example in Faceted Search Interfaces - this can become quite tedious. An example would be a series of checkbox groups for Categories, Keywords etc, with each having ~10 checkbox items.

I think it would be great to have an option to make a checkbox group behave like a single tabstop, and use a roving-tabindex to move between checkboxes with arrow keys.This could be implemented either as an option to `useCheckboxGroup`, or maybe via another primitive for what in the WAI-ARIA Authoring Practices is refered to as ["Layout Grids", that sets `role=grid` on the grouping element](https://w3c.github.io/aria-practices/#grid). The WAI-ARIA Authoring Practices actually *do* mention checkbox groups here: ["A grid widget is a container that enables users to navigate the information or interactive elements it contains using directional navigation keys ... It can be used for purposes as simple as grouping a collection of checkboxes"](https://w3c.github.io/aria-practices/#grid).

A `role=grid` primitive could also be useful for UIs that e.g. map search facets to a list of *links* (continuing the example above: a section with a list of "Browse by {category}", "Browse by {keyword}" etc. links). I think [`reakit` provides a primitive for such cases](https://reakit.io/docs/composite/), and it would be awesome to have something similar in `react-aria`.

[^1]: ["If a set of checkboxes is presented as a logical group with a visible label, the checkboxes are included in an element with role group"](https://w3c.github.io/aria-practices/#wai-aria-roles-states-and-properties-5)

## 🤔 Expected Behavior

see above

## 😯 Current Behavior

see above

## 💁 Possible Solution

see above

**Comment by devongovett** [comment]
We are working on grid support right now actually. You could theoretically build this using that. I'm not sure it would be expected to treat `role=group` as a composite. @majornista @jnurthen thoughts on this?

**Comment by devongovett** [comment]
FYI, here's the ticket for the grid hooks we're working on: #1327

**Comment by stefanprobst** [comment]
awesome!

**Comment by majornista** [comment]
You may be able to use `FocusScope` and `useFocusManager` to implement the roving `tabIndex` behavior. I'm not sure that adding the layout grid design pattern to CheckboxGroup provides much added benefit.

**Comment by stefanprobst** [comment]
@majornista thanks for pointing me towards `useFocusManager`! however, it's not 100% clear to me how to make it support the above usecase. looking at the docs example [here](https://react-spectrum.adobe.com/react-aria/FocusScope.html#usefocusmanager-example), moving with arrow keys works as expected, but <kbd>Tab</kbd> also moves focus *inside* the group. i can [make it ~work by manually handling Tab/Shift+Tab](https://codesandbox.io/s/tab-wkk1z?file=/pages/index.js) in the `onKeyDown` handler, is this what you were refering to?

to clarify, this is the pattern i'm looking for:

```
                ==TAB==>               ==TAB==>
 [CheckboxGroup]        [CheckboxGroup]        [button]
↑  * Checkbox          ↑  * Checkbox
A  * Checkbox          A  * Checkbox
R  * Checkbox          R  * Checkbox
R  * Checkbox          R  * Checkbox
O  * Checkbox          O  * Checkbox
W  * Checkbox          W  * Checkbox
↓  * Checkbox          ↓  * Checkbox
```

**Comment by majornista** [comment]
@stefanprobst Here is an example using a wrapper to handle events:

```jsx
import {Checkbox, CheckboxGroup} from '@react-spectrum/checkbox';
import {getFocusableTreeWalker} from '@react-aria/focus';
import React, {cloneElement, useState} from 'react';
import {SpectrumCheckboxGroupProps} from '@react-types/checkbox';
import {useId} from '@react-aria/utils';
import {useLocale} from '@react-aria/i18n';

function CheckboxGroupWithRovingTabIndex(props: Omit<SpectrumCheckboxGroupProps, 'children'> = {}) {
  let {
    children,
    orientation = 'vertical',
    ...otherProps
  } = props;
  let {direction} = useLocale();
  let id = useId(otherProps.id);

  let [focusedCheckboxValue, setFocusedCheckboxValue] = useState(null);
  let onFocusCapture = e => setFocusedCheckboxValue((e.target as HTMLInputElement).value);

  let onKeyDown = (e) => {
    let nextDir;
    switch (e.key) {
      case 'ArrowRight':
        if (direction === 'rtl' && orientation !== 'vertical') {
          nextDir = 'prev';
        } else {
          nextDir = 'next';
        }
        break;
      case 'ArrowLeft':
        if (direction === 'rtl' && orientation !== 'vertical') {
          nextDir = 'next';
        } else {
          nextDir = 'prev';
        }
        break;
      case 'ArrowDown':
        nextDir = 'next';
        break;
      case 'ArrowUp':
        nextDir = 'prev';
        break;
      default:
        return;
    }
    e.preventDefault();
    let walker = getFocusableTreeWalker(e.currentTarget, {from: e.target});
    let nextElem;
    if (nextDir === 'next') {
      nextElem = walker.nextNode();
      if (!nextElem) {
        walker.currentNode = e.currentTarget;
        nextElem = walker.firstChild();
      }
    } else {
      nextElem = walker.previousNode();
      if (!nextElem) {
        walker.currentNode = e.currentTarget;
        nextElem = walker.lastChild();
      }
    }
    if (nextElem) {
      // Call focus on nextElem so that keyboard navigation scrolls the radio into view
      nextElem.focus();
    }
  };

  return (
    <div
      role="presentation"
      onKeyDown={onKeyDown}
      onFocusCapture={onFocusCapture}>
      <CheckboxGroup {...otherProps}>
        {
          children.map(
            (child, i) => cloneElement(child, {key: `${id}-checkbox-${i}`, excludeFromTabOrder: focusedCheckboxValue && focusedCheckboxValue !== child.props.value})
          )
        }
      </CheckboxGroup>
    </div>
  );
}
```

**Comment by stefanprobst** [comment]
@majornista thanks a lot for the example!

i'll close this then, as there's nothing really actionable.

**Comment by devongovett** [comment]
FYI, you might also be able to use useFocusManager with a FocusScope rather than the tree walker stuff. Might be easier. 🤷🏻‍♂️
