### ISSUE TITLE
useBreadcrumbItem should accept generics

### ISSUE THREAD

**Issue by matamatanot** [adobe/react-spectrum#1324]
# 🐛 Bug Report 

`useBreadcrumbItem` return `itemProps`. itemProps is not suitable for `<a>`.

## 🤔 Expected Behavior

No type error.

## 😯 Current Behavior

There is a type error.

## 💁 Possible Solution
I may be a little wrong, but the error is now gone.

`node_modules/@react-aria/breadcrumbs/dist/types.d.ts`
```
interface BreadcrumbItemAria<T> {
    itemProps: HTMLAttributes<T>;
}
export function useBreadcrumbItem<T>(props: AriaBreadcrumbItemProps, ref: RefObject<T>): BreadcrumbItemAria<T>;
```

## 💻 Code Sample

```
export const Breadcrumbs = (props: AriaBreadcrumbsProps<HTMLElement>) => {
  const { navProps } = useBreadcrumbs(props);

  return (
    <nav {...navProps}>
      <ol>{props.children}</ol>
    </nav>
  );
};

export const BreadcrumbItem = (props: AriaBreadcrumbItemProps) => {
  const ref = useRef<HTMLAnchorElement>(null);
  const { children } = props;
  const { itemProps } = useBreadcrumbItem(
    {
      children,
    },
    ref
  );

  return (
    <li>
      <a {...itemProps} ref={ref}> // error!!!
        {children}
      </a>
    </li>
  );
};

```

```
Type '{ children: ReactNode; ref: RefObject<HTMLAnchorElement>; defaultChecked?: boolean | undefined; defaultValue?: string | number | readonly string[] | undefined; ... 251 more ...; css?: InterpolationWithTheme<...>; }' is not assignable to type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.Type '{ children: ReactNode; ref: RefObject<HTMLAnchorElement>; defaultChecked?: boolean | undefined; defaultValue?: string | number | readonly string[] | undefined; ... 251 more ...; css?: InterpolationWithTheme<...>; }' is not assignable to type 'AnchorHTMLAttributes<HTMLAnchorElement>'.
    Types of property 'onKeyDown' are incompatible.
      Type '((event: KeyboardEvent<HTMLElement>) => void) | undefined' is not assignable to type '((event: KeyboardEvent<HTMLAnchorElement>) => void) | undefined'.
        Type '(event: KeyboardEvent<HTMLElement>) => void' is not assignable to type '(event: KeyboardEvent<HTMLAnchorElement>) => void'.
          Types of parameters 'event' and 'event' are incompatible.
            Property 'code' is missing in type 'KeyboardEvent<HTMLAnchorElement>' but required in type 'KeyboardEvent<HTMLElement>'.ts(2322)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
|"@react-aria/breadcrumbs" | "^3.1.1" |

**Comment by devongovett** [comment]
Same comment as on your other issue. Isn't `HTMLElement` already compatible with `HTMLAnchorElement` since it is a superclass?

**Comment by matamatanot** [comment]
After updating @react, react-dom, and @types/react to 17, the type error no longer occurs.

Before the update, it was displayed as follows.
`JSX.IntrinsicElements.a: React.DetailedHTMLProps<React.AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>`

After as follows.
`JSX.IntrinsicElements.a: DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>`

**Comment by asterikx** [comment]
I had the same problem with the `useHover` and `useFocus` hooks on div elements. TS reported incompatibilities between `HTMLElement` and `HTMLDivElement` on keyboard-related events. I was already using React 17 but forgot to upgrade `@types/react`. Upgrading `@types/react` to `^17.0.0` resolved the issues for me.

**Comment by bstro** [comment]
I ran into a similar type error while unknowingly using older types (`@types/react": "^16.9.53"`). I am posting this comment in case anyone runs into a similar error as I did while trying to spread certain props into an HTMLDivElement.
```
Types of parameters 'event' and 'event' are incompatible.
            Property 'code' is missing in type 'KeyboardEvent<HTMLDivElement>' but required in type 'KeyboardEvent<HTMLElement>'.ts(2322)
```
Upgrading `@types/react` to `^17.0.0` per @asterikx solved the issue.
