### ISSUE TITLE
Add field*Width properties for label oriented components

### ISSUE THREAD

**Issue by kcoop** [adobe/react-spectrum#1334]
# 🙋 Feature Request

Add fieldWidth, fieldMinWidth and fieldMaxWidth properties to components with labels using labelPosition="side". 

## 🤔 Expected Behavior

One should be able to specify the width of the field itself in addition to the width of the field + label. This is useful to left justifying the label while right justifying the field. Example behavior in Spectrum: https://spectrum.adobe.com/page/text-field/#Label-position

## 😯 Current Behavior
Labels and associated fields are always left justified.

**Comment by snowystinger** [comment]
should `fieldGrow` `fieldShrink` `fieldBasis` also be added? It is a flex container for the field + label

**Comment by devongovett** [comment]
Let's not get too complicated. The fact that it's flex should be considered an implementation detail, so we shouldn't expose that IMO.

**Comment by snowystinger** [comment]
Guidance is to use a <Form> element
