### ISSUE TITLE
useInteractOutside does not work when clicking on a component that utilizes usePress

### ISSUE THREAD

**Issue by josharens** [adobe/react-spectrum#1338]
# 🐛 Bug Report 

After updating to `@react-aria/interactions@3.3.2` I noticed that the `onInteractOutside` callback is not being called when I click on an outside button that uses `usePress`.

## 🤔 Expected Behavior

`onInteractOutside` is called when clicking on any element outside of the specified element.

## 😯 Current Behavior

Clicking on a button that uses `usePress` outside of an element that is using `useInteractOutside` does not call the `onInteractOutside` callback.

## 💁 Possible Solution

This is just pure speculation so take this with a grain of salt, but it looks like `useInteractOutside` is relying on mouse and touch events instead of pointer events now. My hunch is that `usePress` is calling `preventDefault` on pointer events internally which is canceling the mouse events that `useInteractOutside` is listening for.

## 💻 Code Sample

https://codesandbox.io/s/condescending-napier-4hecp?file=/src/App.js

**Comment by snowystinger** [comment]
Looks like https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/usePress.ts#L274
will stop onMouseDown https://www.w3.org/TR/pointerevents/#the-pointerdown-event. We're actually about to test without pointer events at all in usePress, reason being that they aren't fully implemented in all browsers yet to the extent that we can comfortably use them. More info will be in the Issue/PR where that work is being done.
