### ISSUE TITLE
Add SearchWithin component

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#1342]
# 🙋 Feature Request

A `SearchWithin` combines a `SearchField` and a `Picker` into a single group. This allows a user to constrain the scope of their search to a particular category, for example.

![search-within_hero-default@2x_bwiGRKFYK03jVaNw9YqQK_1583263785784](https://user-images.githubusercontent.com/19409/101099734-43451e80-3593-11eb-9015-2dc3fb44af03.png)

## 💁 Possible Solution

A `SearchWithin` acts as a container for a `SearchField` and a `Picker`. It does not implement any logic on its own, but it does provide styling for its children and support for labeling the entire search within as a whole. Therefore, to give developers full control over both pieces, it will simply accept them as children.

```tsx
<SearchWithin label="Search">
  <SearchField placeholder="Search" />
  <Picker defaultSelectedKey="all">
    <Item key="all">All</Item>
    <Item key="campaigns">Campaigns</Item>
    <Item key="audiences">Audiences</Item>
    <Item key="tags">Tags</Item>
  </Picker>
</SearchWithin>
```

The API for this is as follows:

```tsx
interface SpectrumSearchWithinProps extends SpectrumLabelableProps, DOMProps, StyleProps {
  children: ReactNode,
  /** Propagated to both children */
  isDisabled?: boolean
}
```

### Styling

The search within css classes from spectrum-css can be used to implement this. In order to apply them, we can use the [SlotProvider](https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/utils/src/Slots.tsx#L35). SearchField and Picker will need to be updated to call [useSlotProps](https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/utils/src/Slots.tsx#L22) with default slot names of `searchfield` and `picker` respectively. This way they can receive props sent from the `SearchWithin` to apply class names and other props.

In addition to classes, SearchWithin should also send a few other props to the slots:

- `isDisabled`
- `isRequired`
- `label` - set to `undefined` to override any prop that might be there. The label should be on the whole SearchWithin.
- `isQuiet` - set to false to override any prop that might be there since it is unsupported by SearchWithin.
- `aria-labelledby` - set to the id of the search within label. See below.

### Accessibility

A search within should be considered an ARIA `group`. It should support a visible label (implemented using the `<Field>` wrapper component), and use the id of this label to label both the SearchField and the Picker via `aria-labelledby` and the group itself.

Basic gist:

```tsx
<div id="label">Label</div>
<div role="group" aria-labelledby="label">
  <input type="search" aria-labelledby="label" />
  <button aria-labelledby="label">All</button>
</div>
```

### Packages

This should be implemented in the `@react-spectrum/searchwithin` package. Because it's pretty simple, mostly a spectrum concept and not an official ARIA pattern, we don't need to create any React Aria or React Stately hooks for it.

## 🧢 Your Company/Team

RSP

**Comment by so99ynoodles** [comment]
https://github.com/adobe/react-spectrum/pull/1366
It seems like there is no progress since 15 Dev 2020.
