### ISSUE TITLE
Implement Avatar component

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#1345]
# 🙋 Feature Request

An avatar is a thumbnail representation of an entity, such as a user or an organization.

![Screen Shot 2020-12-03 at 4 53 11 PM](https://user-images.githubusercontent.com/698229/101107832-0889b900-3588-11eb-8a8a-997f54f4c91c.png)

## 💁 Possible Solution

The API should be something like the following.

```ts
interface SpectrumAvatarProps extends Omit<StyleProps, 'width' | 'height'> {
  src: string,
  alt?: string,
  /**
   * This affect both height and width at the same time.
   * @default size-100
  */
  size?: DimensionValue,
  isDisabled?: boolean
}
```

Example usages:

```tsx
<Avatar src="images/daniel.jpg" alt="Daniel" />
```

### Aria/Stately hooks
There are no hooks needed.

### DOM structure
An avatar should be implemented with the `img` tag. 
```tsx
<img src="images/daniel.jpg" alt="daniel"  />
```

## 🧢 Your Company/Team

RSP

**Comment by solimant** [comment]
@snowystinger - could you please assign to me?
