### ISSUE TITLE
Implement help text support

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#1346]
# 🙋 Feature Request

Help text provides either an informative description or an error message that gives more context about what a user needs to input. It should be supported in many form components including `TextField`, `TextArea`, `Picker`, `ComboBox`, `NumberField`, `HexColorField`, `RadioGroup`, and `CheckboxGroup`.

![help-text_hero@2x_6u5Htn8ISf26fmDesW9oqk_1603232864911](https://user-images.githubusercontent.com/19409/101113475-7399b680-35ad-11eb-9490-8bcb52418d37.png)

## 💁 Possible Solution

Create the following interface in `@react-types/shared` in `inputs.d.ts`. All of the components that support help text will extend from this interface.

```tsx
interface HelpTextProps {
  /** A description for the field. Provides a hint such as specific requirements for what to choose. */
  description?: ReactNode,
  /** An error message for the field. *./
  errorMessage?: ReactNode
}

// Spectrum specific types. Extends `Validation` so that the `validationState` prop is available.
interface SpectrumHelpTextProps extends Validation {
  // causes the description to be displayed with lighter text
  isDisabled?: boolean,
  showIcon?: boolean
}
```

Next, we need the component to render this error text as well as the styling for it. This is not yet available in spectrum-css or spectrum-dna, so we will need to create our own css for the time being. Perhaps we can also contribute this back upstream. We can use the XD file available on [the spectrum site](https://spectrum.corp.adobe.com/page/help-text/) for reference. The `HelpText` component should live in the `@react-spectrum/label` package. When the `validationState` prop is set to `invalid`, the `errorMessage` should be displayed, otherwise the `description`.

The `Field` component in `@react-spectrum/label` implements a wrapper for all form components that support a label. It is currently used only by `ComboBox`, however we should refactor all of the other components listed above to use it too. This will allow us to centralize the error text and labeling support across many components. `HelpText` should be added to the `Field` component when the `description` or `errorMessage` props are provided.

`Field` is not used by `RadioGroup` and `CheckboxGroup` since those are a bit different. They should use `HelpText` directly. In addition, in these cases, Spectrum says the help text should have an error icon in addition to the actual text.

### Accessibility

For accessibility, we need to associate the description and error message element with the field. This should be done using the `aria-describedby` attribute. In order to make this easier, we should create a `useField` hook in the `@react-aria/label` package that should be analogous to the `Field` component in React Spectrum. It should combine the existing `useLabel` hook and also handle the `description` and `errorMessage` props.

```ts
interface FieldProps extends LabelableProps, HelpTextProps {}

interface FieldAria extends LabelAria {
  /** Props for the description element, if any. */
  descriptionProps: HTMLAttributes<HTMLElement>,
  /** Props for the error message element, if any. */
  errorMessageProps: HTMLAttributes<HTMLElement>
}

declare function useField(props: FieldProps): FieldAria;
```

This should generate ids for both the description and error message elements, and associate them with the field when they are available. While Spectrum swaps between the description and error message, other implementations may wish to display both at once, so we should use the `useSlotId` util to generate the ids. This will ensure that no broken references are added to `aria-describedby` if the element is not actually rendered.

Once we have this hook, it should replace the call to `useLabel` in the hooks for all components where help text is supported. These are: `useTextField`, `useSelect`, `useComboBox`, `useRadioGroup`, and `useCheckboxGroup`. `descriptionProps` and `errorMessageProps` will need to be added to the return types for all of these hooks, and passed through to the `Field` component in Spectrum.

### Layout

We've gotten a request from the community to provide guidance on how to (or why not to) preserve centered horizontal alignment between an input with help text and other UI elements. Once help text appears, the vertical height of a flex-styled row will expand, and a centered alignment will bring surrounding elements down with it. As part of this implementation, we should provide explicit documentation on either how to style this correctly or alternative recommendations if we advise against doing this.

## 🧢 Your Company/Team

RSP

**Comment by majornista** [comment]
`aria-errormessage` is unsupported using VoiceOver or NVDA, we should probably favor aria-describedby for the time being. https://a11ysupport.io/tech/aria/aria-errormessage_attribute

**Comment by devongovett** [comment]
Ah ok, thanks. Updated the ticket.
