### ISSUE TITLE
Picker not showing popover when container is position fixed.

### ISSUE THREAD

**Issue by guiyep** [adobe/react-spectrum#1355]
# 🐛 Bug Report 

Picker not showing popover with items when container is position fixed.

example:

```
<div style={{ width: '100%', height: '100%', postion: 'fixed' }}>
    <Picker>
      <Item key="test">test</Item>
    </Picker>
</div>
```

I'm asuming that it is because the popover is being injected in the body and there is no way we can move this to another component.

## 🤔 Expected Behavior

Picker should be smart and know how to position the popover. or provide a way of doing so.

## 😯 Current Behavior

Popover is not shown, no error.

**Comment by LFDanLu** [comment]
@guiyep Thanks for filing this issue, I tried to reproduce with your example but wasn't able to: https://codesandbox.io/s/heuristic-brown-yvizr?file=/src/App.js. What version of RSP are you using? Do you have some more example code or a sandbox where you can reproduce this issue?

**Comment by guiyep** [comment]
I see that is working in your example. Will try to update the version in my app and if it still persists I will create an exact example in codesandbox.

thanks for the quick reply!
