### ISSUE TITLE
useSingleSelectListState should support having no selected key

### ISSUE THREAD

**Issue by chungwu** [adobe/react-spectrum#1363]
# 🙋 Feature Request

Right now, `SingleSelectListState.selectedKey` is a required field, and `useSingleSelectListState` interprets an undefined selectedKey as "uncontrolled" (vs controlled with an undefined value).  `useSingleSelectListState` also calls `useListState` with `disallowEmptySelection`.

Workaround right now is to use `null` as the selectedKey, but there seems to be no official way to clear a selection.

## 🤔 Expected Behavior

Can have a SingleSelectListState with no selectedKey

## 😯 Current Behavior

SingleSelectListState.selectedKey, once set, cannot be unset

## 💁 Possible Solution

There is some ambiguity here on how `useControlledState` interprets value and defaultValue; `undefined` could both mean "no prop passed in" or "undefined passed in".  Could switch to using, say, `null`, or some other defined sentinel / symbol to indicate "no prop passed in" instead:

```
function keyOrNone(props, key) {
  return key in props ? props[key] : NONE;
}

function useSingleSelectListaState() {  
  useControlledState(keyOrNone(props, "selectedKey"), keyOrNone(props, "defaultSelectedKey"), ...);
}
```

## 🔦 Context

Trying to implement a Select / Picker that can be deselected.

## 💻 Examples

In this example: https://codesandbox.io/s/clever-dirac-vtrd6?file=/src/App.tsx

Using Spectrum Picker, selecting an option and then selecting the "Unset" option (which sets the selectedKey to `undefined`) results in unexpected behavior (Picker still shows a selected value).

## 🧢 Your Company/Team

Plasmic

**Comment by LFDanLu** [comment]
@chungwu Yep, we suggest that you use `null` to clear key selection (its the approach we used in the ComboBox [stories](https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx#L464)) This could definitely be better documented though, perhaps something in the docs/prop description.

**Comment by i-like-robots** [comment]
Whilst my team found it was possible to set the `selectedKey` to `null` in order to clear the current selection this has given us problems with our types.

If `null` is a valid value should [this declaration](https://github.com/adobe/react-spectrum/blob/1e2b7f280a04ead83e21b27fa580eb189e5f4186/packages/%40react-types/shared/src/selection.d.ts#L19) also allow `null`?

**Comment by khoad** [comment]
I can take a look at this issue.
