### ISSUE TITLE
Need help with collection/node interface example

### ISSUE THREAD

**Issue by MuhammadSaadQadeer** [adobe/react-spectrum#1365]
# 🙋 Documentation Request

I was trying to use the level prop mentioned here for Item interface from `@react-stately/collections` but I am not sure where to pass the level prop or as how to use it exactly because there no example specified for more reference I am attaching a screen shot below so that you guys get exact idea what I am talking about here

![image](https://user-images.githubusercontent.com/40329686/101734287-daedc400-3ae1-11eb-882a-15d5bd6ca8c9.png)

Here's the link to the specific documentation as well https://react-spectrum.adobe.com/react-stately/Collection.html

**Comment by MuhammadSaadQadeer** [comment]
Here's a bit more detail about the problem that I am facing 

```
function Example(props) {
  return (
    <Menu onAction={alert}>
      {({ MenuButton, Items, Item }) => (
        <>
          <MenuButton>
            <button className="p-4 bg-gray-400">Open</button>
          </MenuButton>
          <Items>
            <div>
              <Item>First</Item>
            </div>
          </Items>
        </>
      )}
    </Menu>
  );
}
```

Now when I wrap <Item> in any element it gives 
![image](https://user-images.githubusercontent.com/40329686/101734638-6f582680-3ae2-11eb-827f-6fb396de287e.png)

So I thought may be I can use level prop to fix this one but I am not sure how to fix it exactly because I couldn't find any references , so if you guys can guide me regarding this that would be great

Thanks

**Comment by snowystinger** [comment]
What is the purpose of the div? could it be moved inside the <Item>? Also, what are <Items> plural? 
I'm assuming you're using the hooks to create your own Menu?

Levels is just a property, you would use it internal to creating your Menu, maybe do something like indent the item. Internal to Menu you'd have access to it. From outside I don't think you should.

**Comment by MuhammadSaadQadeer** [comment]
Yes, I am using hooks to create my own menu , I am trying to implement a headless menu component using ARIA hooks, I need to expose isFocused props to my child <Item/> but I can't because I am not able to wrap it in some parent component to pass props below is my full code 

import React from "react";
import { useMenuTriggerState } from "@react-stately/menu";
import { useButton } from "@react-aria/button";
import { useMenu, useMenuItem, useMenuTrigger } from "@react-aria/menu";
import { useTreeState } from "@react-stately/tree";
import { mergeProps } from "@react-aria/utils";
import { useFocus } from "@react-aria/interactions";
import { Item } from "@react-stately/collections";
import MenuOverlay from "./menu-overlay";

```
const Menu = (props) => {
  // Create state based on the incoming props
  let state = useMenuTriggerState(props);
  // Get props for the menu trigger and menu elements
  let ref = React.useRef();
  let { menuTriggerProps, menuProps } = useMenuTrigger({}, state, ref);
  const { className, onAction } = props;
  // Get props for the button based on the trigger props from useMenuTrigger
  let { buttonProps } = useButton(menuTriggerProps, ref);

  function MenuButton(props) {
    return (
      <span {...buttonProps} ref={ref} {...props}>
        <span aria-hidden="true">{props.children}</span>
      </span>
    );
  }

  let Items = (props) => {
    return (
      <>
        {props.isOpen || state.isOpen ? (
          <MenuItems
            domProps={menuProps}
            autoFocus={state.focusStrategy}
            onClose={state.close}
            className={className}
            onAction={onAction}
            {...props}
          >
            {props.children}
          </MenuItems>
        ) : null}
      </>
    );
  };

  // Props available at Menu Level
  return props.children({
    MenuButton,
    Items,
    open: state.isOpen,
    onClose: state.close,
    ...props,
  });
};

function MenuItems(props) {
  // Create menu state based on the incoming props
  let state = useTreeState({ ...props, selectionMode: "none" });

  // Get props for the menu element
  let ref = React.useRef();
  let { menuProps } = useMenu(props, state, ref);
  let { className } = props;

  return (
    <MenuOverlay onClose={props.onClose}>
      <ul
        {...mergeProps(menuProps, props.domProps)}
        ref={ref}
        style={{
          position: "absolute",
          listStyle: "none",
        }}
        className={className}
      >
        {[...state.collection].map((item) => (
            <MenuItem
              key={item.key}
              item={item}
              state={state}
              onAction={props.onAction}
              onClose={props.onClose}
              className={item.props.className}
            />
        ))}
      </ul>
    </MenuOverlay>
  );
}

function MenuItem({ item, state, onAction, onClose, className }) {
  // Get props for the menu item element
  let ref = React.useRef();
  let { menuItemProps } = useMenuItem(
    {
      key: item.key,
      isDisabled: item.props.isDisabled,
      onAction,
      onClose,
    },
    state,
    ref
  );

  // Handle focus events so we can apply highlighted
  // style to the focused menu item
  let [isFocused, setFocused] = React.useState(false);
  let { focusProps } = useFocus({ onFocusChange: setFocused });
  return (
    <li
      {...mergeProps(menuItemProps, focusProps)}
      ref={ref}
      className={className}
    >
      {item.rendered}
    </li>
  );
}

function Example(props) {
  return (
    <Menu onAction={alert}>
      {({ MenuButton, Items, }) => (
        <>
          <MenuButton>
            <button className="p-4 bg-gray-400">Open</button>
          </MenuButton>
          <Items>
            {/** for custom controlling the state use prop isOpen */}      
              <Item
              className="p-2 hover:bg-blue-500 hover:text-white"
              key={"longKey"}
              textValue={"Some text value"}
              isDisabled={true}
            >
            </Item>
          </Items>
        </>
      )}
    </Menu>
  );
}

export default Example;
```

I need to do something like this in the <Item> children 

```
<Item>
(isFocused)=> (
<span></span>
)
</Item>
```

**Comment by snowystinger** [comment]
It looks like you're almost there, did you need to apply a classname based on the isFocused state? or did you try that and something didn't work?
```
  // Handle focus events so we can apply highlighted
  // style to the focused menu item
  let [isFocused, setFocused] = React.useState(false);
  let { focusProps } = useFocus({ onFocusChange: setFocused });
  return (
    <li
      {...mergeProps(menuItemProps, focusProps)}
      ref={ref}
      className={classNames(className, {isFocused})}
    >
      {item.rendered}
    </li>
  );
```

**Comment by MuhammadSaadQadeer** [comment]
isFocused works perfectly fine, what I want to do is I want to make it a reusable component and I want to expose isFocused props to the user so that user can apply styles onFocus or even on hover

**Comment by snowystinger** [comment]
Can you move what you have defined in Item right now
```
  let [isFocused, setFocused] = React.useState(false);
  let { focusProps } = useFocus({ onFocusChange: setFocused });
  return (
    <li
      {...mergeProps(menuItemProps, focusProps)}
      ref={ref}
      className={classNames(className, {isFocused})}
    >
```
and put it into your reusable component, we can call it Foo
then you'd render it like:
```
<Item><Foo /></Item>
```
Now you should have access to everything you need inside Foo, Item essentially does nothing except `item.rendered`

**Comment by snowystinger** [comment]
Closing, feel free to reopen if you're still having issues
