### ISSUE TITLE
useInteractOutside should not assume document.body covers viewport

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#1367]
# 🐛 Bug Report 

When [the `useOverlayTrigger` example](https://react-spectrum.adobe.com/react-aria/useOverlayTrigger.html#example) from the docs is viewed standalone (see [this Codesandbox](https://codesandbox.io/s/overlay-trigger-dd9p1?file=/src/App.tsx)), the overlay can only be dismissed by clicking the small area covered by `document.body` (yellow background in the Codesandbox).

## 🤔 Expected Behavior

Clicking anywhere outside the overlay should close it.

## 😯 Current Behavior

Overlay not closed.

## 💁 Possible Solution

I think this happens because `useInteractOutside` has [this check](https://github.com/adobe/react-spectrum/blob/1d9905e7c8308cfbb2a1e03bfc22b2dce89cbb12/packages/%40react-aria/interactions/src/useInteractOutside.ts#L114) (added in #715) which assumes `document.body` covers the viewport. If this is not the case, `isPointerDown` is not set to `true` [here](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/useInteractOutside.ts#L44-L46), and subsequently `onInteractOutside` does not get called [here](https://github.com/adobe/react-spectrum/blob/1d9905e7c8308cfbb2a1e03bfc22b2dce89cbb12/packages/%40react-aria/interactions/src/useInteractOutside.ts#L86-L89).

When changing `document.body` to `document.documentElement` everything seems to work fine. If this makes sense, i'll send a pr.

## 💻 Code Sample

see https://codesandbox.io/s/overlay-trigger-dd9p1?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest
| Browser          | firefox 83
| Operating System | ubuntu 20.04

**Comment by snowystinger** [comment]
I see what you mean, I can't think of a reason not to use documentElement instead and all of our event listeners are registered on the document, not document.body
