### ISSUE TITLE
Media queries with Spectrum React components

### ISSUE THREAD

**Issue by undavide** [adobe/react-spectrum#1373]
# ❔ Question

I understand that you advise against the use of custom styles and classes with React Spectrum components; I was wondering what the recommended way to provide media-query-like behaviour is, with the goal e.g. to target mobile and desktop sizes. 

## 🔦 Context

I'm currently using [`gatsby-plugin-breakpoints`](https://www.gatsbyjs.com/plugins/gatsby-plugin-breakpoints/) on a Gatsby website: it provides a hook that I can use to check the current breakpoint, but doing that each time on each component looks to me a bit cumbersome.

## 💻 Code Sample

An example could be a `<Flex>` component for which I'd like to change the `marginX` depending on the screen size:

```js
import React from "react";
import { useBreakpoint } from "gatsby-plugin-breakpoints";

const Header = () => {
  const breakpoints = useBreakpoint();
  return (
    <Flex marginX={breakpoints.sm === true ? `size-100` : `size-300`}>
      // ...
    </Flex>
  )
}

export default Header;
```

Is this the best I can get or there's a more proper way? Thanks!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.x
| Browser          | Chrome
| Operating System | macOS 10.15.7

## 🧢 Your Company/Team

I'm a random guy from the Internet `¯\_(ツ)_/¯`

**Comment by snowystinger** [comment]
Hey! Thanks for the interest! I think you'll find this issue answers your question https://github.com/adobe/react-spectrum/issues/770
Let us know if you meant something else.

**Comment by undavide** [comment]
Thanks for pointing me to that, it's exactly what I meant! I've upvoted it, I'll ask there what's the current state.
