### ISSUE TITLE
How to filter v3 Table rows with useAsyncList

### ISSUE THREAD

**Issue by bryantabaird** [adobe/react-spectrum#1386]
# ❔ Question

In a v3 Table using a `useAsyncList` hook, I'm trying to filter a list of results dynamically.

## 🔦 Context

What is the best way to implement a search filter to a `useAsyncList` hook? I added a filter function to the `load` prop, but I'm not sure if this is the recommended way for something like this.

The animation for reload seems to be too long, despite a very small timeout. See sandbox

![image](https://user-images.githubusercontent.com/9795404/102379321-ff371e00-3f83-11eb-8c52-e21ff634332b.png)

## 💻 Code Sample

https://codesandbox.io/s/tender-leavitt-lqjck

## 🧢 Your Company/Team

Adobe Analytics

**Comment by LFDanLu** [comment]
@bryantabaird We are working on adding `filterText` support to `useAsyncList` as a part of [async ComboBox support](https://github.com/adobe/react-spectrum/issues/1184). I believe that would cover your use case here.

**Comment by bryantabaird** [comment]
@LFDanLu that's a great step in the right direction. Quick follow up question, though not shown in my sample sandbox, how could a user implement a custom filter function?

For our use case, pure `filterText` will not be sufficient, as we have a custom approximate string matching function (think fuzzy search) that we use in many locations throughout our app.

Can `useAsyncList` also support some kind of `filterFn` instead?

**Comment by LFDanLu** [comment]
(chatted in slack with you about this but for anyone else who is curious): Yep it will, the filterFn will be available as a option to pass to `useAsyncList`.
