### ISSUE TITLE
Resizing dialog from bottom up will leave buttons "floating" outside and below bottom dialog boundary

### ISSUE THREAD

**Issue by coftedal** [adobe/react-spectrum#1404]
# 🐛 Bug Report 

If you resize a dialog with buttons along the bottom, from the bottom up, the buttons will eventually "float" in open space below the bottom dialog border. You can continue to make the dialog smaller, but the buttons will stay behind and break containment from the dialog boundaries.

## 🤔 Expected Behavior

The button controls would stay within the boundaries of the dialog. They may become covered or obscured as the dialog shrinks in size, but they should stay a part of, and within, the dialog.

## 😯 Current Behavior

What happens now is that at a certain point in the resizing, the buttons stop moving with the dialog and just "float" on the screen while you continue to shrink the dialog. It appears, visually, that they lose containment within the dialog boundaries.

1. https://react-spectrum.adobe.com/react-spectrum/Dialog.html
2. Click the "Upload" button example to invoke the Upload dialog
3. Open the Dev Tools window for the browser - mine is orientated at the bottom of the screen
4. Grab the bottom of your browser window and start to move it up towards the top, shrinking your browser
5. This will cause the Dev Tools window to start to "push" the React dialog from the bottom, and the React dialog will begin to resize as the space gets smaller and smaller.
6. Watch the buttons on the React dialog and you'll see at some point, they'll separate themselves from the containing boundary of the bottom of the React dialog.

## 🔦 Context

Our app is using larger dialogs than the sample one in Storybook, so we didn't have to resize very far to run into this visual issue.

## 💻 Code Sample

https://react-spectrum.adobe.com/react-spectrum/Dialog.html, see steps above using Upload example.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | v.3.3.0
| Browser          | Microsoft Edge Version 87.0.664.66
| Operating System | Big Sur 11.1

## 🧢 Your Company/Team

Adobe Admin Console

**Comment by coftedal** [comment]
Here's a screenshot sample with it just starting to float.

![Screen Shot 2020-12-18 at 2 13 18 PM](https://user-images.githubusercontent.com/76232204/102673425-f17ec580-4148-11eb-9db7-e9ea7ed2b34b.png)

**Comment by snowystinger** [comment]
Hoping that the fix is to use overflow on the dialog and not on the page. I've made a PR for that but will need to run it past design

**Comment by snowystinger** [comment]
Out of curiosity, what is the actual problematic Dialog you're using? Trying to figure out what the real world problematic scenario is.

**Comment by snowystinger** [comment]
From Design:
> we spent quite some time trying to find a good UX solution for dialogs (especially with a lot of content) that would work well across platforms and states (keyboard open, etc.) We ended up with the idea that the content of the dialog should be scrolling and not the whole dialog itself (among many considerations, buttons staying visible makes the UX more accessible). That being said we had not necessarily considered a tall visual at the top in combination with a very tight vertical space.

We'll pick it up with design again in the new year

**Comment by snowystinger** [comment]
Issue author's team talked with Spectrum Design internally.

@coftedal can we close this? or what was the resolution?

**Comment by snowystinger** [comment]
Closing from inactivity and not causing a real world issue at the moment. Feel free to reopen if it does.
