### ISSUE TITLE
Implement isSelected for ActionButton

### ISSUE THREAD

**Issue by sarnason** [adobe/react-spectrum#1412]
# 🙋 Feature Request

Please add isSelected for the ActionButton.
https://spectrum.adobe.com/page/action-button/

## 🤔 Expected Behavior

An action button can have a selected state to allow for toggling — not only for taking a direct action. This can be used to disclose parts of an interface, such as for showing or hiding panels.

See
https://spectrum.adobe.com/page/action-button/

## 😯 Current Behavior

Doesn't work

## 💁 Possible Solution

My workaround is to use UNSAFE_className="is-selected"

## 🔦 Context

Doing a file browser and using ActionButtons to select list view or grid view.  

## 💻 Examples

Here I have added the class to the Grid/Thumb view button:
<img width="453" alt="Screenshot 2020-12-20 at 17 52 42" src="https://user-images.githubusercontent.com/2607409/102720447-4f97de00-42ec-11eb-8be6-19126914495b.png">

Example from assets.adobe.com
<img width="367" alt="image" src="https://user-images.githubusercontent.com/2607409/102720640-76a2df80-42ed-11eb-94e8-7fe67d1b9b42.png">

## 🧢 Your Company/Team

For my own product, Visial.

**Comment by devongovett** [comment]
Does ToggleButton work for your use case? https://react-spectrum.adobe.com/react-spectrum/ToggleButton.html

**Comment by sarnason** [comment]
Yes indeed! Thank you. Perhaps some overlap here to consider. Feels like they share so much.

**Comment by devongovett** [comment]
Yeah we intentionally broke this behavior out into a separate component because it behaves slightly different from a normal button. I don't think the design site has been updated yet.
