### ISSUE TITLE
More Slider Thumb Related Tests

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum#1417]
# 🙋 Feature Request

Please add some more tests. As we improved clicking on the slider and moving the nearest slider to that position. The coverage is good, but they don't cover all the edge cases with multiple thumbs and disabled. 

## 🔦 Context

We created a multiple thumb with disabled slider story and the tests don't cover all the cases found in this story.

## 🧢 Your Company/Team
RSP

**Comment by dannify** [comment]
To be added when we pick up Slider again
