### ISSUE TITLE
Add `waitForMouseup` option to `useFocusWithin` to evade flashing

### ISSUE THREAD

**Issue by NeekSandhu** [adobe/react-spectrum#1427]
Both CSS's `:focus-within` and the `useFocusWithin` hook will temporarily declare a "blur" when clicking on an input label of some other control within the container. This leads to the flashing of focused styles for that brief moment. While one might evade this problem by adding `tabIndex={-1}` to the `label` element, it still doesn't cover all the other holes, for example, clicking on something leading to a programmatic focus of controls.

One solution (the one we use), is to wait between mousedown and mouseup events. Mousedown will retain the pseudo focus-within state until mouseup, and when the latter event triggers, we just check if `document.activeElement` is still owned by the subject container. If so, the focus-within continues to be `true`, and is declared as `false` otherwise.

**Comment by ktabors** [comment]
Can you provide an example of this behavior via something like a sandbox?

**Comment by ktabors** [comment]
If needed, please reopen with example code.
