### ISSUE TITLE
How to check an item by default in radio button group ?

### ISSUE THREAD

**Issue by MatteoGauthier** [adobe/react-spectrum#1429]
# ❔ Question

How to check an item from a radio group by default
## 🔦 Context

With the useRadioGroupState

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | @react-aria 3
| Browser          | Chrome 87
| Operating System |Microsoft Windows [version 10.0.18363.1256]

**Comment by devongovett** [comment]
You should be able to use the `value` (controlled) or `defaultValue` (uncontrolled) prop.

**Comment by MatteoGauthier** [comment]
> You should be able to use the `value` (controlled) or `defaultValue` (uncontrolled) prop.

Thanks a lot for your reply, Can you help me to do that, or an example

**Comment by snowystinger** [comment]
See https://react-spectrum.adobe.com/react-spectrum/CheckboxGroup.html#value

**Comment by snowystinger** [comment]
@MatteoGauthier were you able to resolve your issue?
