### ISSUE TITLE
Native iOS keyboard select does not appear when tapping on useSelect example

### ISSUE THREAD

**Issue by Catchpowle** [adobe/react-spectrum#1432]
# 🐛 Bug Report 
Native iOS keyboard select does not appear when tapping on useSelect example within the docs on an iPhone https://react-spectrum.adobe.com/react-aria/useSelect.html

## 🤔 Expected Behavior

I think the native iOS keyboard select should appear.

## 😯 Current Behavior

The custom dropdown appears, but this is quite small on mobile.

## 💻 Code Sample

If you visit this page on an iPhone and tap on the Select to test https://react-spectrum.adobe.com/react-aria/useSelect.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | Docs
| Browser          | iOS Safari
| Operating System | iPhone XS iOS 14.2

**Comment by devongovett** [comment]
React Aria is designed to allow you to create your own custom styled components. While that particular example isn't mobile optimized, it should be possible to build such a layout yourself, or even switch to a native select on mobile yourself if you like.

For example, React Spectrum's [Picker](https://react-spectrum.adobe.com/react-spectrum/Picker.html) component displays a custom tray on mobile.

**Comment by Catchpowle** [comment]
Thanks for replying, I was just wondering if there was some pattern that had been missed in the example with the HiddenSelect, that would cause the native keyboard to be triggered on mobile, but makes sense that this is left to userland :)
