### ISSUE TITLE
Improve useListBox docs

### ISSUE THREAD

**Issue by kauly** [adobe/react-spectrum#1434]
# 🙋 Documentation Request

https://react-spectrum.adobe.com/react-aria/useListBox.html

The doc shows a function that creates a custom ListBox and receives the state via props. The problem is that we don't know what that props are and they are essential to understand the example. My suggestions is to create that props above the ListBox function. And yes, I tried to look at the useListState interface.

**Comment by kauly** [comment]
For anyone interest, I find a example [here](https://github.com/adobe/react-spectrum/blob/e08af810954896b95e444b5b02ab782cd1e4b759/packages/%40react-aria/combobox/test/useComboBox.test.js#L24)

**Comment by LFDanLu** [comment]
@kauly The props being passed to the `ListBox` in the `useListBox` example are `label="Choose an option"`, `selectionMode="single"`, and the children of the `ListBox` shown here in example: 
![image](https://user-images.githubusercontent.com/9661127/103564993-59851980-4e74-11eb-89b9-8a5b109c6f65.png)

Does that clarify things? Or is the ask here to explain `useListState` in the documentation some more?

**Comment by kauly** [comment]
I think that the whole documentation could be more helpful with complete code examples and codebox like in the mui page. 
The props that I was talking about: 
```let defaultProps = {items: [{id: 1, name: 'one'}], children: (props) => <Item>{props.name}</Item>};```
