### ISSUE TITLE
Change the default font size for the Medium Scale

### ISSUE THREAD

**Issue by undavide** [adobe/react-spectrum#1435]
# ❔ Question

What's the proper way to change the base `font-size` site-wise?
Tangentially related to [this issue](https://github.com/adobe/react-spectrum/issues/1171), but different.

## 🔦 Context

I'm building a Gatsby website. The default font-size for the Medium Scale is `--spectrum-global-dimension-font-size-100`, too small. Even your [Explore React Spectrum](https://react-spectrum.adobe.com/index.html) uses the bigger `--spectrum-global-dimension-font-size-200`.

I'm trying to set that as the default, but the following doesn't work:
 
```css
body,
html {
  font-size: var(--spectrum-global-dimension-font-size-200);
}
```

This is in a `global.css`, but I suppose that `<Provider>` overrides it.
Could you please advise?

Thank you!

**Comment by LFDanLu** [comment]
@undavide I believe you would have to make a custom theme, specify your new font-size there, and provide that to your Provider.

**Comment by infantito** [comment]
@undavide did you get it? How could I reset the font-size?
