### ISSUE TITLE
Where do I find useGrid?

### ISSUE THREAD

**Issue by honzatmn** [adobe/react-spectrum#1438]
Hey, first of all – thanks for doing amazing work on react-aria (and react-stately), it's a great experience to use it. 

I noticed this note in `useListBox` documentation:
```NOTE: listbox options cannot contain interactive content (e.g. buttons, checkboxes, etc.). For these cases, see useGrid instead.```

However, I search through docs and this repository, but I haven't found `useGrid` anywhere 🤔 

## Context
I'd like to use checkboxes in the list (and "only" button to the right, checking only one item in the list), but based on this note, it seems that `useListBox` isn't the right hook to go with.

Thanks a lot for any direction.

**Comment by LFDanLu** [comment]
@honzatmn Thanks for catching that, `useGrid` does not exist yet but it is being worked on in [this pull](https://github.com/adobe/react-spectrum/pull/1422). We should probably remove mention of `useGrid` from the docs until that pull is merged.

**Comment by devongovett** [comment]
useGrid is in alpha. Going to close this.
