### ISSUE TITLE
What is the intended use of `isDisabled` in @react-aria/button useButton

### ISSUE THREAD

**Issue by theetrain** [adobe/react-spectrum#1442]
Thanks for maintaining react-aria; I'm very interested in adopting this library in my project.

# ❔ Question

1. What is the intended way for consumers to render disabled buttons when using `useButton`?
2. Under what conditions should a button be allowed to render as disabled, and what is the rationale?

I see an opportunity to improve the hook itself or its documentation to help explain its treatment for `disabled` buttons.

Reference: https://react-spectrum.adobe.com/react-aria/useButton.html

## 🔦 Context

For question 1, about the intended way to use `useButton`, this is how `useButton` returns props:

https://github.com/adobe/react-spectrum/blob/c2c187606d447a6daa185e0b0507c22883ab3147/packages/%40react-aria/button/src/useButton.ts#L93-L98

The `disabled` prop is set based on the value of `isDisabled` and other conditions, such as whether or not the element is an `input`. As a personal rule, I try to avoid disabled buttons whenever possible. However, in the event where I do want to render a disabled button, along with helpful user-facing information on how to enable it again, what should the developer do to render `disabled={true}` in a component that consumes `useButton`?

## 💻 Code Sample

I want to be able to pass `disabled` as a standard attribute to a component like so:

```jsx
// react input 1
<Button disabled isSubmit>Submit form</Button>

// html output 1
<input value="Submit form" type="submit" />

// react input 2
<Button disabled>Add to cart</Button>

// html output 2
<button type="button">Add to cart</button>
```

It does not work the way I expect. However, it works if I pass `isDisabled` like so:

```jsx
// react input 1
<Button isDisabled isSubmit>Submit form</Button>

// html output 1
<input value="Submit form" type="submit" disabled="true" />

// react input 2
<Button isDisabled>Add to cart</Button>

// html output 2
<button type="button" disabled="true">Add to cart</button>
```

This may relate more to question 2, under what conditions is a button allowed to be disabled? I'm guessing it should not be possible to render a `<button>` as disabled, yet it is possible when I pass `isDisabled={true}`. I'm also guessing it's okay for an `<input type="submit" />` to render as disabled judging the `useButton` source code.

https://github.com/adobe/react-spectrum/blob/c2c187606d447a6daa185e0b0507c22883ab3147/packages/%40react-aria/button/src/useButton.ts#L72

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | @react-aria/button@3.3.0
| Browser          | Chrome 87
| Operating System | macOS 10.15.7

## 🧢 Your Company/Team

Not affiliated with Adobe, an external developer.

**Comment by ktabors** [comment]
Thanks for the question. When we came up with the API we standardized on using 'is' for boolean properties like disabled, quiet, emphasized, justified, selected, readOnly, etc. This consistent api does mean that properties don't always mirror default html element attributes. In you component using `useButton` you can use `disabled` and convert it to `isDisabled` when passing the property into `useButton`.

Can you provide more explanation or an example for your question on why disabled? If it is a design pattern being used by an app I could see a form that doesn't have all the required fields completed having a disabled form submit button.

**Comment by theetrain** [comment]
Thanks for your response. My main concern with the `useButton` API is the fact that `isDisabled` is not a documented prop on the react-aria website. My team came up with a visual design for disabled buttons, and in order to render that style I plan on using the following CSS:

```scss
.button {
  font-size: 1rem;
  padding: 0.5rem 1rem;
  border: 0;
  border-radius: 1rem;
  font-weight: 700;

  &[disabled="true"] {
    opacity: 0.3;
  }
}
```

In a plain HTML example, this would style correctly since the developer would write `<button class="button" disabled="true">Buy now</button>` and it would render correctly. However, that won't happen with the current implementation of `useButton` since I would need to listen for the `disabled` prop and write my own logic to replace it with `isDisabled` as you suggested; and since `isDisabled` is not documented, I would assume the prop is brittle and can be removed in an upcoming version without notice. Consistent name conventions such as the `is` prefix may be useful for react-aria maintainers, but does it improve the experience for react-aria consumers?

>Can you provide more explanation or an example for your question on why disabled?

I think this question is an important one, and I'm happy to respond. Small disclaimer, I am not an interaction designer, but I understand the general consensus that disabled interactive elements generally hamper the user experience for everyone, and users of assistive technology especially. My personal rule is, "if it is disabled, it is invisible to the user." The example you gave (a form is incomplete and cannot be submitted) is the most likely implementation of it. Good form validation is complex to implement. 

I've worked on projects with forms that do not have their submit buttons disabled, and when users click on it they will receive an error message with suggestions on how to complete the form. It's easier to develop, but the user won't know a form field is invalid until they submit the form, which causes friction. 

Another approach is to provide client-side validation for each form input to help guide the user into properly completing the form's required fields before submitting. The submit button at the end of the form would be disabled (and practically invisible), but in its place would be a skip-link to the first incomplete required input field along with a brief explanation on how to complete the field.

---

I hope this illustrates my situation better. If the intent of react-aria is to put guard rails on potentially bad patterns such as disabled buttons that provide no alternative context for users, then I support that, but please document this and cite sources for rationale. `isDisabled` can potentially help developers stop and think about why they're disabling buttons at all and improve the web. Alternatively, the `disabled` attribute can be supported and explained with an example. Both options are a documentation and educational opportunity for `useButton` consumers.

<details><summary>React button example that renders as an input type=submit, or regular button depending on props</summary>

```jsx
import { forwardRef } from 'react'
import PropTypes from 'prop-types'
import styled from 'styled-components'
import { useButton } from '@react-aria/button'

const StyledButton = styled.button`
  font-size: 0.875rem;
  padding: 0.5rem 1rem;
  border: 0;
  border-radius: 1rem;
  font-weight: 700;
  box-shadow: 0px 0px 2px rgba(23, 43, 77, 0.04), 0px 3px 2px rgba(23, 43, 77, 0.08);

  &[disabled] {
    opacity: 0.3;
  }
`

const PrimaryButton = styled(StyledButton)`
  background-color: #f3872f;
  color: #ffffff;

  &:hover {
    background-color: #f6a563;
  }
`

const SecondaryButton = styled(StyledButton)`
  background-color: #ffffff;
  color: #061938;
  border: 1px solid #dfe1e6;

  &:hover {
    background-color: #f4f5f7;
  }
`

const variantMap = {
  primary: PrimaryButton,
  secondary: SecondaryButton
}

const Button = forwardRef((props, ref) => {
  const { buttonProps } = useButton(props, ref)
  const { variant, isSubmit, children } = props

  const RenderButton = variantMap[variant]

  if (isSubmit) {
    return (
      <RenderButton
        {...buttonProps}
        as="input"
        type="submit"
        ref={ref}
        value={children}
      />
    )
  }

  return (
    <RenderButton type="button" {...buttonProps} as={variantMap[variant]} ref={ref}>
      {children}
    </RenderButton>
  )
})

Button.propTypes = {
  variant: PropTypes.oneOf(['primary', 'secondary']),
  isSubmit: PropTypes.bool,
  children: PropTypes.node.isRequired
}

Button.defaultProps = {
  variant: 'primary',
  isSubmit: false
}

Button.displayName = 'Button'

export default Button
```

</details>

**Comment by snowystinger** [comment]
I'm not sure where you are looking, but I see isDisabled right here https://react-spectrum.adobe.com/react-aria/useButton.html#api
![Screen Shot 2021-01-15 at 2 12 51 PM](https://user-images.githubusercontent.com/698229/104783836-c41f3a80-573b-11eb-9bbf-0c6f3ab43339.png)
Can you explain more of where you would expect to see it?

**Comment by majornista** [comment]
@theetrain, as @snowystinger The `isDisabled` prop is documented as part of the API for the `AriaButtonProps` that are passed into the `useButton` hook. The user interface for the API documentation seems somewhat to blame for your confusion, because it displays the list of supported properties in a Popover that displays when the "AriaButtonProps" link is clicked within the code sample. 

Regarding your second question where you point to the code snippet: https://github.com/adobe/react-spectrum/blob/c2c187606d447a6daa185e0b0507c22883ab3147/packages/%40react-aria/button/src/useButton.ts#L72.

This code only executes when the `elementType` passed to the  `useButton` hook is not a `button`. In which case we return a few additional properties: https://github.com/adobe/react-spectrum/blob/c2c187606d447a6daa185e0b0507c22883ab3147/packages/%40react-aria/button/src/useButton.ts#L72. For example, for an `a` `span`, or `div` behaving as a `button`, the `[disabled]` html attribute is invalid, and the hook returns `aria-disabled` instead.

I’m not sure that React-Aria can be so opinionated regarding the use of a disabled state that we either disallow it or make disabled items disappear.

**Comment by theetrain** [comment]
@snowystinger thanks for pointing that out; I had no idea the API docs had interactive popovers like that. I am more accustomed to seeing props in a table layout or collapsed in an expandable region with a clear visual interactive affordance. The `AriaButtonProps` link doesn't show an underline unless I hover or focus it. At a glance, it looks like a static code snippet.

@majornista thanks for explaining the source code, I understand it a little better now. It makes sense to make decisions on how to return props based on element type when certain attributes are not useful to elements such as `<span>`.

I am not contesting whether React-Aria should decide for the user whether or not disabling a button is allowed. More or less, I found the answers to my questions.

>What is the intended way for consumers to render disabled buttons when using useButton?

Use the `isDisabled` prop as per the documentation. It's not a huge effort to have my own button component listen to a `disabled` prop if I choose to have that experience.

>Under what conditions should a button be allowed to render as disabled, and what is the rationale?

There are no opinions or references to research articles from the React-Aria docs suggesting when it's acceptable to have disabled buttons. Hopefully my response to @ktabors can provide some inspiration to help educate consumers of `useButton` on that topic if you see value in that.

Feel free to close this issue, and thanks everyone for your time addressing my questions.
