### ISSUE TITLE
Combobox bugs

### ISSUE THREAD

**Issue by dannify** [adobe/react-spectrum#1443]
- [x] onOpenChange shouldn't be called if there are no items
- [x] Pressing enter in `allowsCustomValue` story should close menu
- [x] Read only mobile combobox shouldn't be open when focused/clicked
- [x] Menu remains open when selecting an already selected item with mouse
         To reproduce: Select an item, open it back up with the mouse, click on the selected item with the mouse, onSelectionChange is called and the dropdown stays open. 
- [x] Input not updating when reselecting after input change 
         To reproduce: Select "Item Three", then ctrl + A and type "three". Arrow down and press enter. The input text is not updated to "Item Three" again.
- [ ] Talkback on Firefox doesn't announce if a combobox option is disabled
- [ ] isOpen and defaultOpen stories have a bunch of room in between each item

**Comment by joaopaulobdac** [comment]
Hey @dannify,
I tried following the documentation PR and the ComboBox source code but I'm not getting any labelProps here:

```tsx
import { useComboBox } from '@react-aria/combobox'
import { useComboBoxState } from '@react-stately/combobox'
import type { ComboBoxStateProps } from '@react-stately/combobox'
import { useRef } from 'react'
import Overlay from './Overlay'
import ListBox from './ListBox'

type ComboBoxProps<T> = ComboBoxStateProps<T>

export default function ComboBox<T>(props: ComboBoxProps<T>) {
    const state = useComboBoxState(props)

    const inputRef = useRef<HTMLInputElement>(null)
    const buttonRef = useRef<HTMLButtonElement>(null)
    const listBoxRef = useRef<HTMLUListElement>(null)
    const popoverRef = useRef<HTMLDivElement>(null)

    const { labelProps, inputProps, buttonProps, listBoxProps } = useComboBox({
        inputRef, buttonRef, listBoxRef, popoverRef, ...props
    }, state)

    console.log(labelProps) // Empty object

    return (
        <div>
            <label {...labelProps}>
            </label>
            <input {...inputProps} ref={inputRef} />
            <button {...buttonProps} ref={buttonRef}>
            </button>
            {state.isOpen && (
                <Overlay
                    overlayRef={popoverRef}
                    isOpen={state.isOpen}
                    onClose={state.close}
                    isDismissable
                    shouldCloseOnBlur
                >
                    <ListBox
                        {...listBoxProps}
                        listBoxRef={listBoxRef}
                        state={state}
                        autoFocus={state.focusStrategy}
                        disallowEmptySelection
                    />
                </Overlay>
            )}
        </div>
    )
}
```

Can you confirm if this is a bug or an error on my part?

**Comment by joaopaulobdac** [comment]
Never mind, got it. You have to pass a `label` prop to `useComboBox`.
