### ISSUE TITLE
Combobox design fixes

### ISSUE THREAD

**Issue by dannify** [adobe/react-spectrum#1444]
- [x]  The combo box button is currently 34x32, it should be square (32x32).

- [x] The button should retain the "down" style while the menu is open. There is no DNA tokens for that but it should match ActionButton. 
    - The background of the button should be gray #200, border #400, chevron icon #700.  
    - When hovering on the button while in down state, the background stays the same, but the border goes to #500, and the chevron icon goes to #900. Refer to the action button DNA file for more details. 

- [x] The text in the menu should align to the text of the combo box.

- [ ] The label text should be 8 px closer to the value text. (check Textfield, confirm with design)

![image](https://user-images.githubusercontent.com/10407036/103731574-4ec4a480-4f9a-11eb-8411-87ed96e4b2bf.png)

**Comment by devongovett** [comment]
Closing. Remaining item is not combobox specific.
