### ISSUE TITLE
TextArea height disregarded when labelled

### ISSUE THREAD

**Issue by undavide** [adobe/react-spectrum#1453]
# 🐛 Bug Report 

The `<TextArea>` ignores the `height` prop when there's also a `label`

## 🤔 Expected Behavior

`height` should work

## 😯 Current Behavior

`<TextArea>` height is reset to default

```html
        <Form>
          <!-- right -->
          <TextArea height="size-2000" />
          <!-- wrong -->
          <TextArea label="Wrong height" height="size-2000" />
        </Form>
```

## 💻 Code Sample

See this [CodeSandbox](https://codesandbox.io/s/elated-cray-xic8x?file=/src/App.js:253-374).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.7.0
| Browser          | Chrome
| Operating System | macOS 10.15.7

## 🧢 Your Company/Team

Freelance

**Comment by snowystinger** [comment]
Yep, I see that, thanks!
For a quick glance, looks like within Field, label should have a flex of `0 0 auto` and the actual field should have a flex of `1 1 auto`
