### ISSUE TITLE
Form components validation: no "clean" initial state?

### ISSUE THREAD

**Issue by undavide** [adobe/react-spectrum#1454]
# ❔ Question

I'm trying to implement validation in a simple form. With "controlled" components either they are in the "valid" (green checkmark) or "invalid" (red warning) state. 

Unless I miss something, this means that a freshly loaded, empty Form with controlled components is presented to users the first time they open it full of red flags all over. Not very friendly. See [this CodeSandbox](https://codesandbox.io/s/sharp-davinci-56dmq?file=/src/App.js). Setting them to `undefined` first triggers a Warning message (see below).

I was wondering whether there is the possibility to activate the `validationState` check on each individual component's `onBlur`, so that the error checking appears gradually.

Alternatively, I understand that I can set `validationState` on the parent `<Form>` (e.g. on submitting), which is not much helpful either. I've tried an approach were I have, e.g.

```js
  const [email, setEmail] = useState();
  const [isEmailValid, setIsEmailValid] = useState();
  // to be called on Form submission
  const validateForm = evt => {
    // ...
    setIsEmailValid(
      /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(email)
        ? "valid"
        : "invalid"
    );
    //...
  };
  // ...
<TextField
  validationState={isEmailValid}
  value={email}
  onChange={setEmail}
  label="Email" />
```

As soon as I type in the `TextField` React is quite unhappy in the console: `"Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.` Besides, having two getters + two setters for each form element does seem a bit awkward to me.

In alternative I've also tried to implement `react-hook-form`; they sort-of work if you follow the [instruction for React Native](https://react-hook-form.com/get-started#ReactNative) with their own error messages, but I've found no way to selectively trigger a single element's `validationState` (i.e. if I `useState` on it I still get the same controlled/uncontrolled message) – so I'm back to square one. Unless I decide to ignore Warnings altogether.

Is there a proper way to deal with this? Thanks!

--- 

As a very side note, the `Form` example on the Spectrum React Components page [here](https://react-spectrum.adobe.com/react-spectrum/Dialog.html) – the "Register" dialog, last but one in the Example section before "Accessibility", is slightly misleading IMHO: the `ButtonGroup` is in the `Footer` (i.e. outside the `Form` that belongs to the `Content`) so there's no way make it work as `type="submit"`. 

Outside the context of React component, it seems that you can work around the issue adding the [`form` attribute](https://stackoverflow.com/questions/7020659/submit-form-using-a-button-outside-the-form-tag/12567605#12567605) to the button, but I haven't been able to make it work with React Spectrum.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.7.0
| Browser          | Chrome
| Operating System | macOS 10.15.7

## 🧢 Your Company/Team

Freelance

**Comment by snowystinger** [comment]
First, can we make the second concern (type=submit) a new Issue? I just don't want to keep track of two conversations in one thread.

Second, for initial validation state, could you do something like this?
https://codesandbox.io/s/wizardly-volhard-6hvmk?file=/src/App.js

**Comment by undavide** [comment]
Great, thanks! One important bit I did overlook is `useState("")` – in my code I didn't set an empty string, and I've learned that an `undefined` value makes the component uncontrolled – hence the warning when I set the value in the change handler.
Thanks again.
