### ISSUE TITLE
Question about TypeScript generics restrictions for collection nodes

### ISSUE THREAD

**Issue by joaopaulobdac** [adobe/react-spectrum#1455]
# ❔ Question

Currently, some component interfaces that make use of collections have a generic type restriction for their collection `Node` to type `object`. Can we remove this restriction since it's not required for using the `Node` type?

Some that I found:

https://github.com/adobe/react-spectrum/blob/c3db4cd3df9a69d59542721a0e99be5960fa8429/packages/%40react-stately/list/src/useListState.ts#L38

https://github.com/adobe/react-spectrum/blob/c3db4cd3df9a69d59542721a0e99be5960fa8429/packages/%40react-stately/list/src/useSingleSelectListState.ts#L38

https://github.com/adobe/react-spectrum/blob/c3db4cd3df9a69d59542721a0e99be5960fa8429/packages/%40react-stately/combobox/src/useComboBoxState.ts#L34

## 🔦 Context

This is a pain point for me because I have to also include the `extends object` in the definition of all my components using these hooks. Also I'm using the [`ban-types` typescript eslint rule](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md) which has the `object` type as one of the banned types.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/combobox    | ^3.0.0-alpha.0 |
| @react-aria/listbox     | ^3.2.3 |
| @react-stately/combobox | ^3.0.0-alpha.0 |
| @react-stately/list     | ^3.2.2 |
| Browser          | Chromium 87.0.4280.141 |
| Operating System | Linux |

**Comment by ktabors** [comment]
We would like to keep the collections as generic as possible. Do you have any thoughts or suggests on how to improve this portion of the typescript while keeping collections generic and open?

**Comment by joaopaulobdac** [comment]
What I'm doing right now is manually removing the `extends object` part from these declarations in my node_modules folder, meaning it becomes just `<T>`.

That's why I wanted to ask this question, to know if this would break anything in the codebase. I quickly went through the source code and I couldn't find a reason as to why the collection node type has to extend object.

Most of the time when you are using collections the node type will be a object anyway, but removing this would allow to not include the `extends object` part in the declaration of our own components :)

**Comment by devongovett** [comment]
I believe the reason for that restriction is that we use the object wrapped by the Node as a WeakMap key which requires that it is an object. Is there a better way to restrict this than object? Why is that a banned type?

**Comment by joaopaulobdac** [comment]
From https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md

> - Avoid the `object` type, as it is currently hard to use due to not being able to assert that keys exist.
>   - See [microsoft/TypeScript#21732](https://github.com/microsoft/TypeScript/issues/21732).

> - Avoid the `Object` and `{}` types, as they mean "any non-nullish value".
>   - This is a point of confusion for many developers, who think it means "any object type".
>   - See [this comment for more information](https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-675156492).

They recommend using `Record<string, unknown>` instead

> I believe the reason for that restriction is that we use the object wrapped by the Node as a WeakMap key which requires that it is an object.

Ah ok! Is that to prevent the user from including a object twice in an array? If not, and if you still want to allow the node to be of any type though, maybe you could wrap the value in your own object and switch to WeakSet. For example: instead of a WeakMap like `value -> data` you would use a Set of `{ value, data }` objects.

**Comment by devongovett** [comment]
I don't really see how that TS issue about `object` applies here. And we don't use `Object`.

In fact, the definition for `WeakMap` in TS itself is defined as `interface WeakMap<K extends object, V>`: https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2015.collection.d.ts#L45

> Is that to prevent the user from including a object twice in an array? If not, and if you still want to allow the node to be of any type though, maybe you could wrap the value in your own object and switch to WeakSet

It's acting as a cache. We can't wrap in our own objects because then we wouldn't be able to find them. The key needs to be the exact same object.

I don't really see anything that we're going to change here. I'd suggest dropping that lint rule as it seems to be more aggressive than necessary.
