### ISSUE TITLE
Question: Toast availability

### ISSUE THREAD

**Issue by undavide** [adobe/react-spectrum#1457]
# ❔ Question

I was looking for the Toast component, which is present on your sourcecode but it's not exported in `@adobe/react-spectrum`. Is there a way to use it, or it's still in an alpha phase?

I can try to customize a Dialog of type="tray" but a ready-made Toast would be easier :-)

Thanks!

**Comment by snowystinger** [comment]
I believe Toast is really pre-alpha even right now. See Backlog https://github.com/adobe/react-spectrum/projects/1
