### ISSUE TITLE
Support Tab Icons

### ISSUE THREAD

**Issue by kaushalyap** [adobe/react-spectrum#1458]
# 🙋 Feature Request

Allow to add icons to the tab along with the labels

## 🤔 Expected Behavior

https://material-ui.com/components/tabs/#forced-scroll-buttons

## 😯 Current Behavior

Only labels

## 💁 Possible Solution

Possibly through a prop

## 🔦 Context

Icons are easily identifiable than labels

**Comment by snowystinger** [comment]
Thanks for your interest! The Tabs api is currently in flux a little bit (denoted by the "Alpha" badge on our documentation website), so we don't officially support Icons quite yet, it is on the roadmap for them as far as I know.

On a side note about usability.
Icons are actually not always easily identifiable, someone with a visual impairment might find icons very difficult to identify and the meaning of the icon can change across cultures, please make sure to include an aria-label at the very least.

**Comment by kaushalyap** [comment]
> On a side note about usability.
> Icons are actually not always easily identifiable, someone with a visual impairment might find icons very difficult to identify and the meaning of the icon can change across cultures, please make sure to include an aria-label at the very least.

Yes there are complications but I spoke in general.

**Comment by devongovett** [comment]
Going to close this as it will be covered in #1668.
