### ISSUE TITLE
Picker items with long words is not readable

### ISSUE THREAD

**Issue by emircado** [adobe/react-spectrum#1459]
# 🐛 Bug Report 

We were using the v3 Picker in our app. We had items with long texts not separated by spaces but only by underscores. It didn't seem like we had a way to read the entire item as it doesn't break into multiple lines or have the items box horizontally scrollable.

## 🤔 Expected Behavior

Just wanted to see if there's an available workaround for these picker items. Items should be readable in some way.

## 😯 Current Behavior

I modified a story in Storybook to replicate the long item we had in our app. Recording is below
https://user-images.githubusercontent.com/5743833/104369665-a9965880-54d2-11eb-82cf-f29e2e513806.mov

I am unable to read the entire long item. Multiple items that start with the same string might be indistiguishable.

## 💁 Possible Solution

I was initially hoping for some way to horizontally scroll through items when they get long, but I realized it's supposed to be broken into multiple lines. Select v2 is able to break the long word and make it readable.

## 🔦 Context

We just wanted our long items to be readable in some way. We don't have control over what the texts will be in our picker items.

## 💻 Code Sample

RSP v3 Storybook, replace one option with a long string with no spaces

## 🧢 Your Company/Team

Adobe/AEP

**Comment by snowystinger** [comment]
Are you able to put break word on the `<Text`? I see it works with dashes, wondering if underscores are not typically allowed break points
![Screen Shot 2021-01-12 at 1 57 11 PM](https://user-images.githubusercontent.com/698229/104379840-e8321000-54de-11eb-8c1e-4a75cb5307e3.png)

**Comment by emircado** [comment]
@snowystinger I'm just guessing, but maybe text doesn't break on underscores coz they count as word characters
https://www.w3schools.com/jsref/jsref_regexp_wordchar.asp

I tried enclosing the item text in `<Text>` but it didn't fix the issue

**Comment by snowystinger** [comment]
Given this bug in Spectrum-CSS https://github.com/adobe/spectrum-css/pull/452, I think it's ok to recommend that you do something like this:
https://codesandbox.io/s/ecstatic-water-sfjek?file=/src/App.js
```
        <Item key="foo">
          <Text>
            <span style={{ wordBreak: "break-all" }}>
              your_text_here_long_long_long_long
            </span>
          </Text>
        </Item>
```

**Comment by emircado** [comment]
This works! Thank you!
