### ISSUE TITLE
Tabs - Underline transition resizes prematurely

### ISSUE THREAD

**Issue by bryantabaird** [adobe/react-spectrum#1462]
# 🐛 Bug Report 

On the very first example on the Tabs documentation page in alpha, there are three tabs which exist:

1. Founding of Rome
2. Monarchy and Republic
3. Empire

See https://react-spectrum.adobe.com/react-spectrum/Tabs.html#example

When I click between the right most tab "Empire" and another tab back and forth quickly and repetitively, you'll notice that, when the underline transitioning from the "Empire" tab to another tab happens, the underline grows prematurely.

I'm guessing this happens with the transition of any tab title of a smaller width to a different tab with a larger width.

![Jan-13-2021 11-57-13](https://user-images.githubusercontent.com/9795404/104496673-803f0080-5596-11eb-92f0-dab263a6f869.gif)

**Comment by LFDanLu** [comment]
@bryantabaird Thanks for catching this, gonna need to play around with the transform and tab line resizing.
