### ISSUE TITLE
[combobox] behavior of Home and End keys causes scrolling

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#1463]
# 🐛 Bug Report 

Started from a conversation here: https://github.com/adobe/react-spectrum/issues/1436
While focused in a combobox with the popup closed, such as hitting Esc to close it, if the Home or End key is pressed and the container or page can scroll in that direction, it will do that. On the second press of that button, the text selection will move, causing the page to scroll back to the combobox.

## 🤔 Expected Behavior

The page should not scroll, the cursor should just move.

## 💁 Possible Solution

preventDefault on those keys, we may need to manually move selection

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by matthewdeutsch** [comment]
closing issue; as stated in PR

> there are no issues reported about this and it goes against native.
> We could consider again for Grid edit mode or specifically for ComboBox
