### ISSUE TITLE
Does Provider also provide font files?

### ISSUE THREAD

**Issue by undavide** [adobe/react-spectrum#1464]
# ❔ Question

I'm developing a Gatsby site with React Spectrum and all is good as Chrome loads "Source Sans Pro" as the font-family in my local dev server (I'm not under the Adobe's umbrella so Adobe Clean is forbidden to me). To my surprise, Safari and Firefox instead show macOS default (Helvetica).

I've deployed the site to a Netlify dev server and on my machine it works the same: Chrome => Source Sans Pro, (Safari, Firefox) => Helvetica. I've asked to a friend of mine to check it, and to him it's Helvetica for every Browser, so I suppose it's my Chrome that acts kinky – probably the fonts are cached somewhere.

Could you please confirm that `<Provider>` itself doesn't load the font-family (e.g. from `woff2` files), and that's up to me? I couldn't find any mention in the docs.

If this is the case, is there a default set of families/weights in use on the default theme?

Thanks!

**Comment by snowystinger** [comment]
I think this file will answer most questions you have in regards to fallbacks https://github.com/adobe/react-spectrum/blob/main/packages/@adobe/spectrum-css-temp/components/commons/fonts.css
You should be able to use "Source Sans Pro" I believe, it's in the open fonts while Adobe Clean is not. https://fonts.google.com/specimen/Source+Sans+Pro. After those font choices are exhausted, it looks like it depends on the browser/machine you're on and what settings have been adjusted.

We do not load any fonts for you, and you can see how we do this in our docs and storybooks https://github.com/adobe/react-spectrum/search?q=typekit

**Comment by undavide** [comment]
Thanks for the information.
