### ISSUE TITLE
Tabs header grabs complete vertical space

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#1466]
# 🐛 Bug Report 

Using the Tabs-Component the complet available space is not used for the content but for the header with the tab-items. This can be reproduced with the following snippet

```typescript
function Reproducer() {
  return (<Flex minHeight={400} minWidth={400} UNSAFE_style={{borderWidth: 1, borderStyle: 'solid', borderColor: 'black'}}>
    <Tabs>
      <Item title="Tab 1">
        <Content>
          <Text>Hello World</Text>
        </Content>
      </Item>
      <Item title="Tab 2">
        <Content>
          <Text>Hello World</Text>
        </Content>
      </Item>
    </Tabs>
  </Flex>);
}
```

yielding the following result

![Bildschirmfoto 2021-01-14 um 18 09 50](https://user-images.githubusercontent.com/52631/104624332-ba41fc80-5693-11eb-9a10-a5aea5b5f55f.png)

## 🤔 Expected Behavior

I would expect that the content area takes all available space

## 😯 Current Behavior

The tab area takes all space available

## 💁 Possible Solution

The reason that the header takes the complete space is that it gets the following CSS-Selector applied

![Bildschirmfoto 2021-01-14 um 19 29 45](https://user-images.githubusercontent.com/52631/104633043-e31bbf00-569e-11eb-80a7-38cba7488083.png)

Removing the three properties "flex-grow", "flex-shrink" and "flex-basis" from the node and adding "flex-grow" to the tabpanel would fix the problem.

![Bildschirmfoto 2021-01-14 um 19 35 02](https://user-images.githubusercontent.com/52631/104633578-a1d7df00-569f-11eb-9ce1-481a21d6a114.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
@tomsontom Thanks for finding this issue and for the pull. I'm currently playing around with your fix, it looks close, just comparing it with what spectrum css has
