### ISSUE TITLE
Tabs - Content is focusable?

### ISSUE THREAD

**Issue by bryantabaird** [adobe/react-spectrum#1474]
# ❔ Question

Is content within a tab supposed to be focusable? See image and try for yourself [here](https://react-spectrum.adobe.com/react-spectrum/Tabs.html#example)

![image](https://user-images.githubusercontent.com/9795404/104773669-a5687600-5732-11eb-915d-bd3cb885fcc3.png)

## 🧢 Your Company/Team

Analytics

**Comment by snowystinger** [comment]
Yes, that is how it's supposed to behave https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role#keyboard_interaction
> When focus is outside of the tablist moves focus to the active tab. If focus is on the active tab moves focus to the next element in the keyboard focus order, ideally the active tab's associated tabpanel.
