### ISSUE TITLE
Picking an item from the Picker within a Dialog dismisses the dialog on mobile

### ISSUE THREAD

**Issue by frontsideair** [adobe/react-spectrum#1477]
# 🐛 Bug Report 

I have placed a Picker inside a Dialog. When trying to pick an item from the list, instead the whole dialog is dismissed. This happens only on mobile, works fine on desktop. 

## 🤔 Expected Behavior

The dialog should not be dismissed, the picker should have its value set to the selected option.

## 😯 Current Behavior

The dialog is dismissed. 

## 💁 Possible Solution

Going with a native `select`

## 🔦 Context

I want to present a form in a dialog with a picker.

## 💻 Code Sample

[Codesandbox](https://codesandbox.io/s/sparkling-brook-vzngy?file=/src/App.tsx)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.7.0
| Browser          | iOS Safari, Desktop browsers in responsive design mode
| Operating System | iOS, macOS

**Comment by snowystinger** [comment]
I know you have it listed in the Environments, but I'm going to write it here as well because I missed it in the description earlier. This happens when both Dialog and Picker render as a Tray.

**Comment by devongovett** [comment]
I don't think trays are really designed to have form elements inside them. Plus, with picker this will result in a nested tray which isn't ideal either. I'd suggest using a full screen dialog for your form with a picker inside instead.

**Comment by frontsideair** [comment]
As much as I liked the tray, fullscreen takeover seems like it can work for my use case.
