### ISSUE TITLE
Button with `display: none` breaks keyboard navigation in <FocusScope contain> 

### ISSUE THREAD

**Issue by augustalfredsson** [adobe/react-spectrum#1478]
# 🐛 Bug Report 

Keyboard navigation breaks in a `<FocusScope>` with `contain` set when there's a button with `display: none` inside the focus scope.

## 🤔 Expected Behavior

In a focus scope with three buttons, where the middle one is hidden with `display: none`, you should be able to navigate to the first and the last button with your keyboard (navigation with tab key).

## 😯 Current Behavior

In a focus scope with three buttons, where the middle one is hidden with `display: none`, you get stuck on the first button unable to reach the last button when navigating with keyboard (navigation with tab key).

## 🔦 Context

We noticed this issue when using a modal component we've built with react-aria where we hide a button with `display: none` based on a media query. It's not possible to navigate past the hidden button, you can only go as far as the last button in the tab order before the hidden one.

## 💻 Code Sample

I have recreated the issue [here](https://codesandbox.io/s/festive-nightingale-dd8fs) in a simpler version without the modal.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria/focus   | 3.2.3
| Browser          | Safari 14.0.2 (16610.3.7.1.9)
| Operating System | macOS 11.1

**Comment by LFDanLu** [comment]
@augustalfredsson Thanks for filing this. We have this block of [code](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/focus/src/FocusScope.tsx#L173-L183) to determine if a element is focusable, perhaps we can tweak it to avoid "display: none".

**Comment by majornista** [comment]
I think perhaps we make an assumption that with React, we would favor omitting the element from the render, over using `display: none` or `[hidden]`. We could add `:not([hidden])` to [the selectors](https://github.com/adobe/react-spectrum/blob/7326ad2ab299a05c6786c1fc8e23df652b3d630d/packages/%40react-aria/focus/src/FocusScope.tsx#L168-L171), but we try to avoid DOM methods that force layout/reflow, like `getComputedStyle()` or `element.offsetParent`.

**Comment by augustalfredsson** [comment]
@majornista That would work, and that is how we bypass this issue currently, but it would be nice to still be able to use media queries in css to hide focusable content inside `<FocusScope contain>`.
