### ISSUE TITLE
<FocusScope contain> doesn't let you blur

### ISSUE THREAD

**Issue by chungwu** [adobe/react-spectrum#1479]
# 🐛 Bug Report 

Once you have a `<FocusScope contain>`, you cannot blur elements inside the `FocusScope`.  On blur, the currently-focused node is immediately focused again (see the `onBlur` handler in `FocusScope.tsx`.

Super basic example here: https://codesandbox.io/s/react-aria-focusscope-doesnt-allow-blur-ywli8?file=/src/App.tsx

Once you focus on one of the inputs, you cannot unfocus by clicking on the yellow container.

## 🤔 Expected Behavior

While I expect focus to be contained (nothing outside `FocusScope` can be focused), I didn't expect that you cannot have nothing focused (`document.activeElement === document.body`).

## 😯 Current Behavior

Nothing in `FocusScope` can be blurred once something has been focused.

## 💁 Possible Solution

Make an exception when nothing is in focus?

```
        if (!isInAnyScope && document.activeElement !== document.body) {
          activeScope = scopeRef;
          focusedNode.current = e.target;
          focusedNode.current.focus();
        }
```

At this point, this behavior probably needs to be controlled by an additional prop...

## 🔦 Context

In a modal, this means something in the modal is always focused.  If my modal's focusable elements always displays a drop down menu on focus, then there's no way to dismiss the menu by unfocusing the element.

## 💻 Code Sample

https://codesandbox.io/s/react-aria-focusscope-doesnt-allow-blur-ywli8?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.2.3
| Browser          | Chrome
| Operating System | Linux

## 🧢 Your Company/Team
Plasmic

**Comment by snowystinger** [comment]
Backing up just a little bit

> In a modal, this means something in the modal is always focused. If my modal's focusable elements always displays a drop down menu on focus, then there's no way to dismiss the menu by unfocusing the element.

I think I need clarity on this. The way I look at this is it that the elements that display the dropdown on focus should really only display it 'onFocus'. After that, if the user 'Interacts outside' or uses the 'Esc' key or 'Tabs' away, the dropdown should hide, even though the element still has focus in some of those cases.

The general rule of thumb being that when a modal (popover/dropdown) closes, focus should be restored to the element that opened it.

In general I don't see us wanting to make an exception for 'nothing focused'. I think this could lead to jumps that the user is not expecting while keyboard/VO navigating. If the element that opened the dropdown has disappeared when you go to return focus to it, then you should figure out a logical place to the put the focus. That isn't usually on the body, especially when you're in a modal. It might be logical to put focus on the modal itself though, or on the modal's dismiss button.

I talked to our accessibility team today as well. Their recommendation for this case though is to have a click outside close the dropdown and for focus to be returned or stay on the triggering element.

**Comment by chungwu** [comment]
Thanks! For now we are taking up your suggestion -- we no longer open the menu `onFocus`, but instead `onKeyPress` or `onClick`, and then we add an `useInteractOutside` to close the menu, even when the focus is still on the input.

**Comment by snowystinger** [comment]
Closing, feel free to reopen if you find it not working and we still need to make a change

**Comment by pascalduez** [comment]
Hi,

let's reuse the codesandbox: https://codesandbox.io/s/react-aria-focusscope-doesnt-allow-blur-forked-5e2ls?file=/src/App.tsx

There's no way for a user to unfocus the input (mouse, or even keyboard). It's just a bare text input without any binded handler.
Isn't it disturbing? It is for us.

Secondly, try to select some text, it's getting a bit nuts, and select also the label, and the whole selection is out of control.
