### ISSUE TITLE
isOpen ComboBox menu items sizing is occasionally too large

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#1485]
# 🐛 Bug Report 
Pulling this out of https://github.com/adobe/react-spectrum/issues/1443. Initial investigation showed that the incorrect sizes were reflected within Virtualizer. Only happens occasionally, perhaps a race condition

![image](https://user-images.githubusercontent.com/9661127/105223872-3794c380-5b11-11eb-9642-6729275213cb.png)

## 🤔 Expected Behavior

ComboBox menu items should render with a consistent size 

## 😯 Current Behavior

ComboBox items render too large occasionally. Seems to only happen if `isOpen = true` or `defaultOpen = true` is provided

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

RSP

**Comment by razvanip** [comment]
@LFDanLu looks like `let size = getSize(ref.current)` in `useVirtualizerItem` when we update the size we get different `values`

**Comment by razvanip** [comment]
Digged a little deeper, 

We have two resizes one for the `menu` based on the `input`, and then the resize for the `items` in the `list`

Even though they seem to execute in the correct order, i am sure that we modify some stuff on `layoutInfo` by reference and `console.logs` don't reflect the reality that seems to be that in the situation when the `combobox` `isOpen` the resize of the `item` is not done really when the `menu` has finished setting the `size`.

A solution would be to not `open` the popover until we have `set` the `state` for the `menuWidth` something in the lines of
```
isOpen={state.isOpen && !!menuWidth}
```

The above seems to fix the issue.
But i am getting a an error on `AriaHideOutside`, we have a `null` node.

```
 if (![...visibleNodes, ...hiddenNodes].some(node => node.contains(change.target))) 
``` 

i guess it does not heart to filter
```
if (![...visibleNodes, ...hiddenNodes].filter(node => !!node).some(node => node.contains(change.target))) {
```

what do u think ?

**Comment by LFDanLu** [comment]
@razvanip This certainly seems to work and seems reasonable to me, thank you for taking the time to debug here! I'll include this fix in https://github.com/adobe/react-spectrum/pull/1449 and see what the team thinks.

**Comment by LFDanLu** [comment]
@razvanip Looks like https://github.com/adobe/react-spectrum/issues/1288#issuecomment-768493058 might be a more root level fix, I'd have to test it out, just wanted to let you know.

**Comment by razvanip** [comment]
@LFDanLu thanks, commented on the main PR.

I guess the million dollar question would be why we get different sizes in `useVirtualizerItem`
