### ISSUE TITLE
Checkbox does work inside a loop (map)

### ISSUE THREAD

**Issue by dev-fe-dx26** [adobe/react-spectrum#1489]
click on Checkbox does not work inside map loop. Checkboxes are not being checked or unchecked. please note that i am using checkbox inside react material table

// it does not make a difference whether the below function used or not          
const changePermission = hasIt => {
hasIt = !hasIt;
};

    {viewsPermissions.map((view, i) => (
    <TableRow key={`view-${view.info.viewName}`}>
        <TableCell align="center">{view.info.viewName}</TableCell>
        {view.info.permissionMetadata.map((p, j) => (
        <TableCell align="center" key={`permission-${p.permission.key.action}`}>
            <Checkbox
            isSelected={p.hasIt}
            onChange={changePermission}
            isEmphasized
            data-testid="activated"
            // value={p.hasIt}
            ></Checkbox>
        </TableCell>
        ))}
    </TableRow>
    ))}

**Comment by LFDanLu** [comment]
@dev-fe-dx26 Do you happen to have a codesandbox that you could share? As @razvanip mentioned, If you are trying to use controlled Checkboxes, you should have `onChange` call a `setState` to modify the selected state of your Checkbox. 

Could you share what `view.info.permissionMetadata` contains? Trying to figure out what the value of `p.hasIt` is and what controls its value.

**Comment by dannify** [comment]
Unable to reproduce
