### ISSUE TITLE
Toast-Stories "add via provider" and "add via provider with timers" are broken

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#1490]
# 🐛 Bug Report 

The stories are broken because one has to wrap them in a ToastProvider otherwise `useToastProvider` call will return nothing.

## 🤔 Expected Behavior

Sample works and Toast open when clicking a button

## 😯 Current Behavior

Exception when clicking one of the buttons because toastContext is not set

## 💁 Possible Solution

Wrap the calls in a `<ToastProvider>` - I'll provide a PR

## 🔦 Context

I was looking at the sample stories 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
Toasts are not currently implemented. Work was started on them, but it was decided that more thought needed to be put into them and they were put on hold.

**Comment by tomsontom** [comment]
this is just to make the story work and not fail with an exception
