### ISSUE TITLE
Button press missed when on-screen keyboard is open while in dialog (tray) on mobile device

### ISSUE THREAD

**Issue by frontsideair** [adobe/react-spectrum#1497]
# 🐛 Bug Report 

Sorry for confusing title. The reproduction is linked as a CSB example. The issue is, I have a form inside the dialog (tray) with a `TextField` and a `Button`. When the input is focused on a mobile device, the on-screen keyboard is opened and the viewport is shrunk. I can see the submit button and and would like to press it before dismissing the keyboard. But the press misses most of the time and I have to press the button again once the keyboard is gone. (It's a timing issue as far as I can see.)

It's a jarring experience as the user doesn't know why the tray is still open and if it's safe to press the button again.

## 🤔 Expected Behavior

The press shouldn't miss the button.

## 😯 Current Behavior

The press misses the button sometimes but not always, which makes it extra confusing.

## 💁 Possible Solution

I'm not sure how to fix it but looks like there is logic to respond to viewport size change to keep the tray where it must be and there seems to be a jump when on-screen keyboard is dismissed, which causes the button to move away. The resizing logic can be delayed just enough so the button receives the press event.

## 🔦 Context

I want to have a form inside a tray. I feel like this is not an uncommon case and should provide a smooth experience.

## 💻 Code Sample

https://codesandbox.io/s/sparkling-brook-vzngy

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.7.0
| Browser          | iOS Safari
| Operating System | iOS 14.3

**Comment by snowystinger** [comment]
That's interesting, when I follow these steps:
1) Press Open
2) focus in the textfield
The keyboard comes up, but obscures the tray completely for me. I feel like that's not what should happen either.

**Comment by frontsideair** [comment]
In my case the tray is pushed above by the keyboard but yours sounds even less usable. :/

**Comment by snowystinger** [comment]
So the issue I was facing with codesandbox was that in their iframe mode, they use `height: 100vh` which is unaffected by the software keyboard. As a result, the tray never moved up. By opening the sandbox in its own window, I do see the behavior you described.
The reason for it is that onPress happens after touch up, but the text input blurs on touch start and hides the keyboard, so you guessed right.
Unfortunately this is a hard thing to fix, we can't prevent the other elements from receiving focus (accessibility no), we can't force the keyboard to stay up and we don't want to make a bunch of blank space on the bottom of the tray.
I think the best thing to do would be to refer back to our usage guidelines https://react-spectrum.adobe.com/react-spectrum/DialogTrigger.html#tray which states "Tray Dialogs are typically used to portray information on mobile devices or smaller screens."
I would read this as, no forms in Trays. Instead, I'd suggest using the fullscreen variant of dialogs.
