### ISSUE TITLE
useOverlayPosition: is it possible to set maxHeight?

### ISSUE THREAD

**Issue by honzatmn** [adobe/react-spectrum#1500]
Hi everyone, in `useOverlayPosition`, maxHeight seems to be calculated automatically to fit the viewport. This is a great feature, and it saved me a lot of time without calculating it manually.

However, is it possible to set maximum max-height somehow? E.g. when I'd want to have a popover with a maximum height 300px, even when there is potentially more vertical space?

I'll be happy for any advice on this.

Edit: I can "hack" it in my popover component by checking ```if (style.maxHeight > 300) { style.maxHeight = 300; }```, but having it as `prop` would be way more elegant.

**Comment by LFDanLu** [comment]
@honzatmn I'm unsure what side effects would occur if we add a `maxHeight` prop to `useOverlayPosition`, will have to dig into that. In the meantime, I believe your approach of overwriting the `style.height` returned from `useOverlayPosition` is appropriate.

**Comment by LFDanLu** [comment]
@honzatmn Apologies for the delay, finally got around to digging into this. It seems to me that adding this wouldn't be too difficult and doesn't seem to break anything when I play around with it locally. It would involve adding a `maxHeight` prop to `useOverlayPosition` and propagating it through [`calculatePosition`](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/overlays/src/calculatePosition.ts#L356) to [`calculatePositionInternal`](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/overlays/src/calculatePosition.ts#L389), replacing the [maxHeight calculated](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/overlays/src/calculatePosition.ts#L326-L333) with the user provided maxHeight depending on whichever one is smaller.
I'll bring it up with the team to see if they agree and proceed from there

**Comment by honzatmn** [comment]
@LFDanLu that's okay, congrats on the recent release! 👏 A lot of nice updates there.

Thanks for getting back to this and discussing it with the team.

**Comment by LFDanLu** [comment]
@honzatmn Discussed this with the team this morning, we were curious about your use case for limiting the max height of your overlays. Is it design specific? Concerns about possible inconsistent overlay sizing between similar components were brought up.

**Comment by LFDanLu** [comment]
Gotcha, I've tagged our design team on this, will update you when they reply back.

**Comment by LFDanLu** [comment]
Apologies about the delay again, feedback from our design team is that they want to remain consistent with native `select` behavior in that overlays take up the available height so we won't be supporting a explicit prop for controlling the `maxHeight`.

**Comment by honzatmn** [comment]
@LFDanLu Thanks a lot! I may find some time to contribute it in the next few days if it's okay.
