### ISSUE TITLE
Improve performance of useFocusRing()

### ISSUE THREAD

**Issue by sedstrom** [adobe/react-spectrum#1516]
# 🙋 Feature Request
Improve performance of useFocusRing() by avoiding unnecessary state updates.

## 🤔 Expected Behavior
useFocusRing should no trigger re-renders for non-focused components when modality changes. 

## 😯 Current Behavior
useFocusRing causes re-render for when modality changes even when not focused.

## 💁 Possible Solution
Allow passing in argument to useFocusVisible that will mute updates to focusVisibleState. 

```ts
export function useFocusRing(props: FocusRingProps = {}): FocusRingAria {
  let {within} = props;
  let [isFocused, setFocused] = useState(false);
  let [isFocusWithin, setFocusWithin] = useState(false);
  const focused = within ? isFocusWithin : isFocused
  let {isFocusVisible} = useFocusVisible({ ...props, isDisabled: !focused });
  let {focusProps} = useFocus({
    isDisabled: within,
    onFocusChange: setFocused
  });
  let {focusWithinProps} = useFocusWithin({
    isDisabled: !within,
    onFocusWithinChange: setFocusWithin
  });

  return {
    isFocused: focused
    isFocusVisible: focused && isFocusVisible,
    focusProps: within ? focusWithinProps : focusProps
  };
```

```ts
export function useFocusVisible(props: FocusVisibleProps = {}): FocusVisibleResult {
  setupGlobalFocusEvents();

  let {isTextInput, autoFocus, isDisabled} = props;
  let isFirstRender = false;
  let [isFocusVisibleState, setFocusVisible] = useState(() => {
    isFirstRender = true
    return autoFocus || isFocusVisible()
  });
  useEffect(() => {
    let handler = (modality: Modality, e: HandlerEvent) => {
      // If this is a text input component, don't update the focus visible style when
      // typing except for when the Tab and Escape keys are pressed.
      if (isDisabled || (isTextInput && modality === 'keyboard' && e instanceof KeyboardEvent && !FOCUS_VISIBLE_INPUT_KEYS[e.key])) {
        return;
      }

      setFocusVisible(isFocusVisible());
    };

    if(!isFirstRender && !isDisabled) {
      setFocusVisible(isFocusVisible());
    }

    changeHandlers.add(handler);
    return () => {
      changeHandlers.delete(handler);
    };
  }, [isTextInput, isDisabled, isFirstRender]);

  return {isFocusVisible: isFocusVisibleState};
}

```

## 🔦 Context
We use space + mouse drag to pan content in our app. Pressing space then using the mouse will change modality from keyboard to pointer and each time that happens all components using the focusRing() hook will re-render for no reason. 

This causes stuttering/lag in the initial movement of the panned content. 

## 🧢 Your Company/Team
Visly https://visly.app

**Comment by devongovett** [comment]
This makes sense. If we are not always keeping `isFocusVisibleState` up to date, it may cause problems when the item *does* become focused though.

Perhaps `useFocusVisible` is the wrong API to use for `useFocusRing`. Maybe we should add a lower level API that just emits events rather than updating any React state. That way, `useFocusRing` could consume these events directly and decide whether to update its own state based on whether it's focused.

**Comment by Andarist** [comment]
@devongovett initially I've reached for `useFocusVisible` as I was migrating components away from using [`use-focus-visible`](https://github.com/dipunm/use-focus-visible/). For my use case actually, the `useFocusRing` would probably be a better suit - I'm wondering though what is actually an appropriate use case for the "raw" `useFocusVisible`? 🤔

**Comment by devongovett** [comment]
Yeah I agree. `useFocusVisible` isn't actually that useful by itself.

**Comment by Andarist** [comment]
K, gonna take a look tomorrow~ what it would take to optimize this if the plan is to simply replace `useFocusVisible` with a more optimized "tracker". It should be pretty straightforward using the `onFocusChange` of `useFocus`.
