### ISSUE TITLE
useTreeState doesn't rebuild the tree collection when a node is expanded 

### ISSUE THREAD

**Issue by rgrove** [adobe/react-spectrum#1525]
# 🐛 Bug Report 

When `useTreeState` is used in an uncontrolled component, it doesn't rebuild the tree collection after the internal `expandedKeys` state changes due to a `toggleKey()` call.

As a result, the `prevKey` and `nextKey` props of the children of the newly expanded node never get set, which prevents keyboard navigation from working on those children when a keyboard delegate is attached to the tree via `useSelectableCollection`.

## 🤔 Expected Behavior

In an uncontrolled component, an internal change to the `expandedKeys` state should cause the tree collection to be rebuilt, so that the `prevKey` and `nextKey` props of each child node are updated.

## 😯 Current Behavior

The tree collection is not rebuilt when `expandedKeys` state changes internally.

## 💁 Possible Solution

I think this can be fixed by changing this line in `useTreeState`:

https://github.com/adobe/react-spectrum/blob/c66852948e2eb7427ce24d4f3199e53c4f615919/packages/%40react-stately/tree/src/useTreeState.ts#L54

...to:

```typescript
let tree = useCollection(props, nodes => new TreeCollection(nodes, {expandedKeys}), null, [expandedKeys]);
```

Happy to send a PR if there's agreement!

## 🔦 Context

I'm building a treeview component that uses `useTreeState` to manage the state of the tree and `useSelectableCollection` to manage selection state and keyboard interactions within the tree.

## 💻 Code Sample

Reduced test case: https://codepen.io/rgrove/pen/eYBNpao

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| \@react-stately/tree   | 3.1.2
| Browser          | n/a
| Operating System | n/a

## 🧢 Your Company/Team

[SmugMug](https://www.smugmug.com/)

**Comment by LFDanLu** [comment]
@rgrove I've reproduced your issue locally and confirmed that your suggested fix seems to work, just need some time to dig around and make sure this is the approach we want to go with (IMO passing the `expandedKeys` as a invalidator for `useCollection` seems correct, just wonder if we need to add any additional invalidators)
