### ISSUE TITLE
mergeProps has side-effects if ids are not equal

### ISSUE THREAD

**Issue by AndyOGo** [adobe/react-spectrum#1535]
# 🙋 Documentation Request

We used [`mergeProps({ id: 1 }, { id: 2 })`](https://react-spectrum.adobe.com/react-aria/mergeProps.html) with two different ids.
Doing that causes a **side-effect and re-renders** related components with different ids.

The `useId()` hook stores all it's ids and `updateValue` function in a local [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) here:
https://github.com/adobe/react-spectrum/blob/cbaffb3e7e94f5000c42d9153548021907250dee/packages/%40react-aria/utils/src/useId.ts#L17

And sets the items at this line:
https://github.com/adobe/react-spectrum/blob/cbaffb3e7e94f5000c42d9153548021907250dee/packages/%40react-aria/utils/src/useId.ts#L50

The `mergeIds(a, b)` calls these `updateValue()` through the map, if they are not equal.
https://github.com/adobe/react-spectrum/blob/cbaffb3e7e94f5000c42d9153548021907250dee/packages/%40react-aria/utils/src/useId.ts#L62-L72

I think this can be clarified, by:
- mention in the docs, that `mergeProps` may have side-effects
- give more describtive names to `map` in `useId` hook, e.g. `idsMap`
- give more descriptive names to `setA` and `setB` in `mergeIds` function, like `updateIdA`, `updateIdB`

**Comment by snowystinger** [comment]
Great idea and suggestion, thank you!
