### ISSUE TITLE
Update HexColorField to match behavior of NumberField

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#1539]
# 🙋 Feature Request

Match scrolling behavior
Match onBeforeInput behavior

**Comment by ktabors** [comment]
Should this include step behavior? Currently it is based off of zero or the current value which is different.

**Comment by snowystinger** [comment]
HexColorField always has a min and max #000000 and #FFFFFF respectively, which means that steps will always start at the min

**Comment by ktabors** [comment]
it does start at the min, but it doesn't seem to snap intervals of the step, like inputing #123456 doesn't change to #123460 and stepping is becomes #123466 not #123460.
