### ISSUE TITLE
useSelectableList Error: Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by AndyOGo** [adobe/react-spectrum#1549]
# 🐛 Bug Report 

`useSelectableList` called with `isVirtualized: false` does not check if the ref is set and throws this error:

> Error: Uncaught TypeError: Cannot read property 'querySelector' of null

https://github.com/adobe/react-spectrum/blob/abcd25984bc9cf726754e4dea9a392afdc3d8afb/packages/%40react-aria/selection/src/useSelectableList.ts#L107-L116

## 🤔 Expected Behavior

Refs should always be checked to be set.

## 😯 Current Behavior

`ref.current` is not checked to be set.

## 💁 Possible Solution

Add a check for `ref.current` to the if block.

```js
if (!isVirtualized && selectionManager.focusedKey && ref.current) {}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
@AndyOGo Looks reasonable, thanks for the fix!
