### ISSUE TITLE
Complex Menu Items link 404

### ISSUE THREAD

**Issue by placegraphichere** [adobe/react-spectrum#1555]
the link to the View guidelines under the "Complex Menu Items" is a 404 here: https://react-spectrum.adobe.com/react-spectrum/Menu.html#complex-menu-items

# 🙋 Documentation Request

`Item` component docs would be great to  have!

## 🧢 Your Company/Team

Adobe Research

**Comment by dannify** [comment]
Thanks @placegraphichere. Looks like we missed an update to the Spectrum website. Unfortunately I am not sure there is a good definition on their site yet that is specific enough for Menu so we might need to add that information ourselves. I will follow up with Spectrum and in the meantime we will remove the broken link.
