### ISSUE TITLE
Spectrum Icons do not take value from color prop and are always displayed in grey

### ISSUE THREAD

**Issue by mayank-shekhar** [adobe/react-spectrum#1567]
# 🐛 Bug Report 

Spectrum icons are showing up as grey when the color prop is set. The color: var(--spectrum-semantic-negative-color-icon); part is not added as a style on the dom element. I don't understand why.

## 🤔 Expected Behavior

Semantic colors should work based on color prop

## 😯 Current Behavior

Icons show up as grey.
Codesandbox: https://codesandbox.io/s/rsp-alert-icon-colors-dp2st?file=/package.json

## 💻 Code Sample

```js
<Provider theme={defaultTheme} colorScheme="light">
      <Flex gap="size-100">
        <Alert aria-label="Default Alert" />
        <Alert aria-label="Negative Alert" color="negative" />
        <Alert aria-label="Notification Alert" color="notice" />
        <Alert aria-label="Positive Alert" color="positive" />
        <Alert aria-label="Informative Alert" color="informative" />
      </Flex>
</Provider>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.3.0
| Browser          | All browsers
| Operating System | Mac OSX

**Comment by mayank-shekhar** [comment]
Workaround I found was: 
- delete node_modules
- Delete yarn.lock / package-lock.json
- npm install / yarn

Then this works correctly

**Comment by devongovett** [comment]
You likely had an older version installed which didn't have the color icon support yet. Glad you got it working.
