### ISSUE TITLE
Contribution file states that this project is in pre-release mode, is this still true?

### ISSUE THREAD

**Issue by AndyOGo** [adobe/react-spectrum#1568]
# 🙋 Documentation Request

Is this information still correct?

> We are currently in pre-release mode and are actively working on getting to a stable version.
https://github.com/adobe/react-spectrum/blob/main/CONTRIBUTING.md

**Comment by devongovett** [comment]
Oops, that is quite old. We should update that similar to this page on the website https://react-spectrum.adobe.com/contribute.html
