### ISSUE TITLE
Somewhat poor performance of useFocusVisible

### ISSUE THREAD

**Issue by Andarist** [adobe/react-spectrum#1569]
# 🐛 Bug Report 

Every `useFocusVisible` subscribes~ to modality changes:
https://github.com/adobe/react-spectrum/blob/739d7f1eb4ea2dbb00190c31fc709164c1ca6f35/packages/%40react-aria/interactions/src/useFocusVisible.ts#L204
But only a single component at a time really needs to be notified about this change.

There is a chance that maybe `useFocusWithin` requires this knowledge as well and that would potentially require more than a single component to be notified about those changes but I'm actually unsure about this as I'm not using any patterns requiring this.

## 🤔 Expected Behavior

No performance degradation, regardless of how many consumers this hook has.

## 😯 Current Behavior

In a larger project, this can lead to a decreased performance on modality changes - with just 30 listeners Chrome warns me sometimes about a slow event listener, noting 100ms+ execution time for pointerdown/keydown listeners that lead to modality changes. The numbers are, of course, very app-specific but all applications can suffer from such slowdowns - just maybe for a different number of listeners etc.

## 💁 Possible Solution

Reorganize the composition to make `useFocusVisible` aware of `onFocus`/`onBlur`.

## 💻 Code Sample

Just an application with a lot of components using `useFocusVisible`. I could provide a repro case but it seems to me that the description is somewhat enough to understand this problem enough.

**Comment by devongovett** [comment]
Dup of #1516?

**Comment by Andarist** [comment]
Looks like this - didn't find it when searching for `useFocusVisible` as it only kinda mentions `useFocusRing`. Let's close this and keep the discussion there.
