### ISSUE TITLE
Implementing a saturation/lightness picker with useMove

### ISSUE THREAD

**Issue by gsimone** [adobe/react-spectrum#1591]
# 📝 Feedback

Hey, I'm having a blast implementing components with the library, amazing work! I'm trying to make a simple saturation/lightness picker, trying to stick as closely as possible to react-aria.

![image](https://user-images.githubusercontent.com/1862172/108195929-c7319000-7118-11eb-8c32-16b5daae2bf6.png)

## 🔦 Context

In the usual color picker UX, the user can click anywhere on the element to set the sl value, or they can click + drag to move the cursor around. I hacked this together by following the useMove example but putting the moveProps on the element instead of the cursors, allowing me to click anywhere and drag. 

Which brings me to 2 problems:
1. now the focus would be on the element, not the cursor (which is a minor problem in this case)
2. I don't have a way to know where the user initially clicked, since the hook only returns the movement delta

The solution here could be adding additional info like the position of the pointerDown event ( or even the whole event, and let details be implemented in userland )

Thanks for your time, cheers!

## 💻 Code Sample

https://codesandbox.io/s/react-aria-color-lvvzo?file=/src/App.js

**Comment by Lincerossa** [comment]
@gsimone, is your issue related to the fact that there is not any listener on the "click" or "pointerDown" event?

<img width="584" alt="Screenshot 2021-02-17 at 14 50 26" src="https://user-images.githubusercontent.com/16242899/108213593-7da06f80-712f-11eb-8735-10dd6c0f9ed9.png">

**Comment by gsimone** [comment]
And also that the user has to move 1px before the onMoveStart event is called

**Comment by devongovett** [comment]
Take a look at how it's done in useSlider, useColorSlider, and useColorWheel. You'll need to put an additional useMove handler on the background in addition to the thumb.

**Comment by devongovett** [comment]
@gsimone would you be interested in contributing this component? We have a ticket for it already (#1118) but if you're already working on it, seems silly to duplicate efforts. Let me know if the API defined there makes sense to you.

**Comment by devongovett** [comment]
Going to close this issue in favor of the existing one (#1118). Hopefully the original question is answered. 😄
