### ISSUE TITLE
Keyboard pressing does not trigger submit event for a button inside a form.

### ISSUE THREAD

**Issue by deebov** [adobe/react-spectrum#1593]
## 😯 Current Behavior

Pressing the space or enter key does not trigger a submit event for `type="submit"` button inside a form. However, it does trigger the `onPress` action on button which makes it really confusing. 

## 🤔 Expected Behavior

Pressing the space or enter key **should** trigger a submit event for `type="submit"` button inside a form.

## 💻 Code Sample

https://codesandbox.io/s/weathered-silence-eqr18?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.3.0

**Comment by snowystinger** [comment]
This may be relevant https://github.com/adobe/react-spectrum/pull/904

**Comment by deebov** [comment]
The PR seems to be stale. Is there any intention to merge and release it any soon?

**Comment by snowystinger** [comment]
it stalled because there was no one asking for it, so now it should get some tlc again

**Comment by deebov** [comment]
is there anything I can do to speed up the process?

**Comment by snowystinger** [comment]
Thank you for your offer, the team wants to go over a few options so we'll be making time for it in the next sprint.

**Comment by deebov** [comment]
thanks for the info!

**Comment by stefanprobst** [comment]
hi, what's the status of this?
