### ISSUE TITLE
NumberField blog post

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#1608]
# 🙋 Documentation Request

Add a blog mdx for creating an internationalized numberfield with formatting.

**Comment by devongovett** [comment]
Excited for this one! Some ideas I had, in no particular order:

* Why don't we use `<input type="number">`? Accessibility issues, formatting control, etc. Find that gov.uk post too.
* Problems we had with spinbutton and voiceover
* Intro to numbering systems, locale formatting differences, and how they fit together. Maybe include some examples of some of the differences we found.
* How the number parser works, how we handle different formatting options, etc.
* How we prevent input of invalid characters (before input stuff)
* Handling input method editors (e.g. pinyin), e.g. composition events
* The things we did to show mobile keyboards, deal with minus signs, etc.
* How we handle stepping, handling rounding errors, etc.
