### ISSUE TITLE
Some useResizeObservers cause an error in React 17

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#1610]
# 🐛 Bug Report 

Switch back and forth from the second tab, you should see a thrown error.
<img width="495" alt="Screen Shot 2021-02-18 at 12 01 39 PM" src="https://user-images.githubusercontent.com/698229/108414429-10e5ad80-71e1-11eb-9298-755d5a0712c3.png">

## 🤔 Expected Behavior

This should work.
It's caused by this line https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/picker/src/Picker.tsx#L144

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by tomsontom** [comment]
Is there any workaround until the next release? I've just updated our application to the current release and I'm running now into this issue

**Comment by snowystinger** [comment]
you could use the nightly or use patch-package until it's released
