### ISSUE TITLE
Missing ListData interface in react-stately package

### ISSUE THREAD

**Issue by kqito** [adobe/react-spectrum#1612]
# 🐛 Bug Report 
In `@react-stately/data`, the `DataList` interface is exported. 
But missing `ListData` interface in [react-stately package](https://www.npmjs.com/package/react-stately) now.

## 🤔 Expected Behavior

`ListData` can be imported from the react-stately package.

## 😯 Current Behavior

`ListData` is not exported in the react-stately package.

## 💁 Possible Solution

Change https://github.com/adobe/react-spectrum/blob/main/packages/react-stately/src/index.ts to export `ListData` type

```ts
export type { ListData } from "@react-stately/data";
```

## 🔦 Context

The interface that can be imported in @react-stately/data can't be imported in react-stately, so I'm having trouble.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |3.3.0
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
@kqito Hey, mind expanding on what you need the `ListData` type for? Are you running into a typescript issue where you need that type definition?

**Comment by kqito** [comment]
@LFDanLu Thank you for the reply!
For example, if I want to define ListData as a type of props, I will need this.

```
import { VFC } from "react";
import { ListData, useListData } from "@react-stately/data";

type ListDataItemsProps = {
  listData: ListData<string>;
};

const ListDataItems: VFC<ListDataItemsProps> = (props) => {
  return (
    <div>
      {props.listData.items.map((item) => (
        <span>{item}</span>
      ))}
    </div>
  );
};

const App: VFC = () => {
  const listData = useListData<string>({});

  return (
    <div className="App">
      <ListDataItems listData={listData} />
    </div>
  );
};

export default App;
```

>Are you running into a typescript issue where you need that type definition?

Of course, I think it is possible to use `ListData` by using ReturnType and other types, but I had a question about the fact that it is exported in `@react-stately/data` and not in `react-stately`.

**Comment by LFDanLu** [comment]
@kqito Oh I see, this seems accidental to me, I think that type should've been included in the react-stately export as well.

**Comment by kqito** [comment]
I will create a PR to export the ListData and fix this. ;)

By the way, I think there are some interfaces other than ListData that have not been exported yet, are you planning to export them as well?

**Comment by LFDanLu** [comment]
Which interfaces are you referring to? Ones like `ListOptions` or `AsyncListData`?

**Comment by kqito** [comment]
Yes. I'm also wondering if I should export interfaces related to hooks other than useDataList.

**Comment by LFDanLu** [comment]
Sure, if you find any others that you think should be exported you can include them as well. If you find a lot, it might be worthwhile creating a bulk tracking issue for it.
