### ISSUE TITLE
SelectionGroup component for Menu to support more than one selection modes.

### ISSUE THREAD

**Issue by intergalacticspacehighway** [adobe/react-spectrum#1621]
# 🙋 Feature Request

SelectionGroup component will allow putting selection mode on groups. 
This is a fairly common use-case. See the screenshot attached in examples - there are 2 groups, one has a "single" selection mode and the other has "none". 

## 🤔 Expected Behavior

A single menu component should support more than one selection mode.

## 😯 Current Behavior
Currently, selection mode can be specified only on the Menu component.

## 💁 Possible Solution

- Something like below. Credit - @devongovett 
```
<Menu>
  <Section title="Style">
    <SelectionGroup selectionMode="multiple" selectedKeys={selectedFormats}>
      <Item key="bold">Bold</Item>
      <Item key="italic">Italic</Item>
      <Item key="underline">Underline</Item>
    </SelectionGroup>
  </Section>
  <Section title="Align">
    <SelectionGroup selectionMode="single" selectedKeys={selectedFormats}>
      <Item key="left">Left</Item>
      <Item key="center">Center</Item>
      <Item key="right">Right</Item>
    </SelectionGroup>
  </Section>
</Menu>
```

## 🔦 Context

Have discussed this with @devongovett and we found this is a fairly common use case. 

## 💻 Examples
<img width="175" alt="Screenshot 2021-02-23 at 10 27 13 AM" src="https://user-images.githubusercontent.com/23293248/108803845-b45c0700-75c1-11eb-8081-25363a9ca3e1.png">

## 🧢 Your Company/Team
GeekyAnts

GeekyAnts/NativeBase

**Comment by cmmartti** [comment]
Here are two more examples of mixed selection modes in a single menu in the wild. The first is on the Windows desktop, the second is in the Window menu of most document-oriented desktop programs:

![mixed-selection-modes](https://user-images.githubusercontent.com/6448223/110843902-d4085600-8276-11eb-8ab3-be65506f788e.png)

![mixed-selection-modes_adobe-acrobat](https://user-images.githubusercontent.com/6448223/110843977-e5e9f900-8276-11eb-8511-bdf89c638b5b.png)

**Comment by intergalacticspacehighway** [comment]
Got something working!
If Items aren't wrapped with a SelectionGroup, it'll fallback to Menu's selectionMode

https://user-images.githubusercontent.com/23293248/112585266-7ef44480-8e1f-11eb-8ef0-5ef4cc8f2dcc.mov

**Comment by devongovett** [comment]
@intergalacticspacehighway are you still working on this? If not, is your code in a place where someone else could take it over?

**Comment by intergalacticspacehighway** [comment]
@devongovett I lost the code with my old system 😭
I can reimplement it by this weekend though.

**Comment by intergalacticspacehighway** [comment]
@devongovett created a draft PR https://github.com/adobe/react-spectrum/pull/2091. It's a bit rough right now.

**Comment by ritz078** [comment]
Is this in the roadmap in the near future?
