### ISSUE TITLE
Valid react peer dependency version ranges for @adobe/react-spectrum-ui and @react-spectrum/slider do not include React 17

### ISSUE THREAD

**Issue by joelrbrandt** [adobe/react-spectrum#1642]
# 🐛 Bug Report 

When I attempt to add `@adobe/react-spectrum@~3.8.0` to a clean project* with React 17 installed (and with pnpm’s strict peer dependencies enabled), I get the following three errors from various dependencies of react-spectrum:

```
ERROR  @adobe/react-spectrum > @react-spectrum/actiongroup > @react-spectrum/button > @spectrum-icons/ui: @adobe/react-spectrum-ui@1.0.1 requires a peer of react@^16.8.0 but version 17.0.1 was installed.
ERROR  @adobe/react-spectrum > @react-spectrum/actiongroup > @react-spectrum/button > @spectrum-icons/ui: @adobe/react-spectrum-ui@1.0.1 requires a peer of react-dom@^16.8.0 but version 17.0.1 was installed.
ERROR  @adobe/react-spectrum: @react-spectrum/slider@3.0.1 requires a peer of react@^16.8.0 but version 17.0.1 was installed.
```

Boiling that down, it appears that the following two packages declare peer dependencies on `react` or `react-dom` using a semver string that does not include v17:

* @adobe/react-spectrum-ui@1.0.1 — both `react` and `react-dom`
* @react-spectrum/slider@3.0.1 — just `react`

\* by “clean project”, I mean “a project that has never had any react-spectrum components added as dependencies, so there are not existing out-of-date versions in a lockfile”

## 🤔 Expected Behavior

peer dependencies should include v17

## 😯 Current Behavior

they don't

## 💁 Possible Solution

Solution is to update the peer dependencies version range (assuming these packages actually work in React v17) -- a discussion on Slack indicates that they should.

Workaround is to use a package manager hook to override these. Here is a PNPM hook:

```javascript
function readPackage(packageJson, context) {
  if (packageJson.peerDependencies !== undefined) {
    if (["@adobe/react-spectrum-ui", "@react-spectrum/slider"].includes(packageJson.name)) {
      packageJson.peerDependencies["react"] = "*"
    }
    if (["@adobe/react-spectrum-ui"].includes(packageJson.name)) {
      packageJson.peerDependencies["react-dom"] = "*"
    }
  }
  return packageJson;
}
```

## 🔦 Context

Trying to upgrade our team's project to React v17

## 🌍 Your Environment

Using PNPM at version 5.17.2

## 🧢 Your Company/Team

Adobe Research

**Comment by dannify** [comment]
Update react-spectrum-ui to ^1.0.2

https://github.com/adobe/react-spectrum/blob/7326ad2ab299a05c6786c1fc8e23df652b3d630d/packages/%40spectrum-icons/ui/package.json#L15

**Comment by dannify** [comment]
Slider has been updated and will be released this month. Icon packages have a ^ and should include the update already
