### ISSUE TITLE
[combobox] when async loading items, defaultSelectedKey does not set input value

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#1645]
# 🐛 Bug Report 

When loading combobox `items` async, and setting a `defaultSelectedKey` (or `selectedKey`), the value of the text input is not set to the `textValue` of the `selectedItem` once the items are loaded.

To see this behavior, add a `defaultSelectedKey` to the `AsyncLoadingExample` in the [combobox storybook here](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/combobox/stories/ComboBox.stories.tsx#L501-L535):

```diff
    <ComboBox
      label="Star Wars Character Lookup"
      items={list.items}
+     defaultSelectedKey="Luke Skywalker"
      inputValue={list.filterText}
      onInputChange={list.setFilterText}
      loadingState={list.loadingState}
      onLoadMore={list.loadMore}
      onOpenChange={action('onOpenChange')}>
      {item => <Item key={item.name}>{item.name}</Item>}
    </ComboBox>
```

## 🤔 Expected Behavior

Combobox inputValue is set to textValue of the default selected item. In the above storybook example, I'd expect the text input to show "Luke Skywalker" once the items are loaded.

## 😯 Current Behavior

see above

## 💁 Possible Solution

I *think* this is because the combobox tracks the selected key and sets the input value [here](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/combobox/src/useComboBoxState.ts#L168-L173), but in this case the input value would need to be set when `selectedItem`, not the `selectedKey`, changes. (?)

## 🔦 Context

I ran into this in an edit form where i have the id (= defaultSelectedKey) available immediately, but need to fetch the options from a server.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest
| Browser          | Firefox 85
| Operating System | Ubuntu 20.04

**Comment by LFDanLu** [comment]
Did some experimenting locally and this might be a bit tricky. My initial thoughts were that `useAysncList`'s `selectedKeys` and `filterText` could be leveraged to provide the desired "update the combobox with the selected option's text when load finishes" behavior but I ran into some snags with overriding the filterText and with stale list options being returned. Another possibility would be to call `resetInputValue` in `useComboBoxState` if we detect that `items` changed and if a `selectedKey` is provided. 

In the meantime, do you have access to the text value of your default selected option before the server fetch finishes? Maybe you could use `selectedItem` from `useComboboxState`

**Comment by devongovett** [comment]
I think this is behaving as expected. `defaultSelectedKey`, and all uncontrolled props, only affect the initial render. In this case, the item doesn't exist. Does it work if you make it controlled with `selectedKey`?

**Comment by stefanprobst** [comment]
thanks for the quick responses!

> I think this is behaving as expected

hmm, the way i understand it is that `defaultSelectedKey` and other uncontrolled props don't do anything when changed after the first render. however, here `defautSelectedKey` does not change since it's already provided initially. what *does* change is `props.items` (a controlled prop) and changing it should (i think) update the text input with the (newly available) `textValue` of the selected item (as long as the text input has not been modified by user input). but I'll admit i'm not 100% sure myself what should be expected.

> Maybe you could use selectedItem from useComboboxState

could you elaborate? not totally sure what you mean?

**Comment by stefanprobst** [comment]
> Does it work if you make it controlled with selectedKey?

checked with the same storybook example as above: same behavior when using `selectedKey` instead of `defaultSelectedKey`.

**Comment by aleclarson** [comment]
I think this might also be an issue with `Select`?

```json
"react-aria": "^3.37.0",
"react-aria-components": "^1.6.0",
```
