### ISSUE TITLE
[combobox] when nested inside a form, pressing Enter should not submit when the listbox is open

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#1646]
# 🐛 Bug Report 

When a combobox is nested inside a `<form>`, pressing Enter currently submits the form.

## 🤔 Expected Behavior

When the listbox is open, pressing Enter should select an item, but not submit the form.

## 😯 Current Behavior

see above

## 💻 Code Sample

add this example to the combobox stories:

```js
function FormSubmissionExample() {
  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        alert('submitted');
      }}
    >
      <ComboBox
        label="ComboBox"
        defaultItems={items}
      >
        {(item) => <Item>{item.name}</Item>}
      </ComboBox>
    </form>
  );
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by stefanprobst** [comment]
checked with a `datalist`: when typing and pressing enter => submit; when moving cursor into the open listbox => Enter selects but does not submit.

**Comment by LFDanLu** [comment]
@stefanprobst We could probably `preventDefault` [here](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/combobox/src/useComboBox.ts#L103-L105) if the menu is open, good catch. Maybe something like this:
```
      case 'Enter':
      case 'Tab':
        if (state.isOpen && e.key === 'Enter') {
          e.preventDefault();
        }

        state.commit();
        break;
```
