### ISSUE TITLE
[combobox] using a number id as collection item key only works when key prop is not used explicitly

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#1647]
# 🐛 Bug Report 

with dynamic collections it is possible to use a collection item's `id` as the `key`. when using a `number`, not a `string` as a collection item id, this only works correctly when *not* explicitly specifying the `key` on the collection item.

This will work correctly:

```js
function KeyExample() {
  const items = [
    { id: 1, label: "One" },
    { id: 2, label: "Two" },
    { id: 3, label: "Three" },
  ];

  return (
    <ComboBox label="ComboBox" defaultItems={items} defaultSelectedKey={3}>
      {(item) => {
        return (
          <Item>{item.label}</Item>
        )
      }}
    </ComboBox>
  );
}
```

However, this will not:

```diff
function KeyExample() {
  const items = [
    { id: 1, label: "One" },
    { id: 2, label: "Two" },
    { id: 3, label: "Three" },
  ];

  return (
    <ComboBox label="ComboBox" defaultItems={items} defaultSelectedKey={3}>
      {(item) => {
        return (
+         <Item key={item.id}>{item.label}</Item>
        )
      }}
    </ComboBox>
  );
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
@stefanprobst Thanks for catching this. This seems to be an issue with all Collection components and I believe stems in part from how we determine a [node's key](https://github.com/adobe/react-spectrum/blob/main/packages/@react-stately/collections/src/CollectionBuilder.ts#L64-L75). If the user provides a key on the `Item` specifically, `getKey` returns `item.key` which is a string regardless of what was provided to the item. If the user doesn't provide a key on the `Item`, `getKey` falls back to the id/key provided in the `items` array which could be a number or a string. I'm not sure there is a good way of handling this, will need to think on this a bit, but at the very least we could explicitly call this out in the documentation

**Comment by stefanprobst** [comment]
> I'm not sure there is a good way of handling this, will need to think on this a bit, but at the very least we could explicitly call this out in the documentation

personally i think it's ok to just mention it in the collection component docs.

**Comment by LFDanLu** [comment]
I wonder if we should maybe make `selectedKey` always expect a string for consistency across all cases (otherwise the docs mention sounds fine to me as well), lemme ask the team.
