### ISSUE TITLE
Color Component failing on typecheck 

### ISSUE THREAD

**Issue by suryaProjects** [adobe/react-spectrum#1666]
# 🐛 Bug Report 

Using "@react-spectrum/color": "^3.0.0-alpha.0".. It is failing on the typecheck for the onChange prop

## 😯 Current Behavior

Our code works fine as expected. The issue does not hinder the development but we cannot commit our changes to git.

## 🔦 Context

Interface 'ColorFieldProps' incorrectly extends interface 'ValueBase<string | Color>'.
Types of property 'onChange' are incompatible.
Type '((color: Color) => void) | undefined' is not assignable to type '((value: string | Color) => void) | undefined'.
Type '(color: Color) => void' is not assignable to type '(value: string | Color) => void'.
Types of parameters 'color' and 'value' are incompatible.
Type 'string | Color' is not assignable to type 'Color'.
Type 'string' is not assignable to type 'Color'.ts(2430)

![image](https://user-images.githubusercontent.com/72864006/110062956-43220e00-7d90-11eb-9672-44bf6f75df9a.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | "^3.6.0"
| Browser          | chrome
| Operating System | Mac OS

## 🧢 Your Company/Team

Adobe/Dynamic Chat

**Comment by LFDanLu** [comment]
@suryaProjects We could probably replace the `ValueBase` extend with `Omit<ValueBase<string | Color>, 'onChange'>` to fix this. In the mean time, is there a particular reason why your typechecker is checking types within node_modules? You can probably exclude node_modules from the typecheck which would unblock you for the time being

**Comment by kwoncharles** [comment]
@suryaProjects I think your VSCode doesn't follow the TS option in `react-spectrum`, it follows the options you configured in VSCode.

See [this article](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions)
