### ISSUE TITLE
Update Tabs API

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#1668]
# 🙋 Feature Request

We need to make the Tabs API more flexible to support custom layouts and additional options (e.g. an "Add tab" button). Applications may need to put the tab list in one container and the tab content somewhere else, without being constrained to the default layout. However, they still need to be connected for accessibility purposes. In addition, it's currently more difficult than it needs to be to include add icons to tabs.

## 💁 Possible Solution

Rather than putting `<Item>` elements directly inside `<Tabs>`, and using the `title` prop to specify the tab content and children to specify the tab panel content, we can instead separate them out. The `Tabs` component will simply be a state container and communicate to `<TabList>` and `<TabPanels>` via a context. The `TabList` and `TabPanels` components are both collection components, taking `<Item>` elements as children, which must have matching `key` props so that we can show the content for the selected tab. Because the `<Item>` for the tab and the contents are separate, this makes it easier to include more complex content like icons rather than putting it in the `title` prop.

```tsx
<Tabs>
  <TabList>
    <Item>
      <FilesIcon />
      <Text>Files</Text>
    </Item>
  </TabList>
  <TabPanels>
    <Item>
      <FilesPanel />
    </Item>
  </TabPanels>
</Tabs>
```

By default, `<Tabs>` should be a flex container in either horizontal or vertical orientation (depending on the `orientation` prop). However, this API also allows for custom layouts to be built by simply wrapping the `<TabList>` and `<TabPanels>` components in any other layout components (e.g. `<Flex>`). This allows inserting additional content between as well, e.g. an add tab button.

```tsx
<Tabs>
  <Flex direction="column">
    <Flex direction="row">
      <TabList>
        <Item key="tab1">Tab</Item>
      </TabList>
      <ActionButton>
        <AddIcon />
      </ActionButton>
    </Flex>
    <TabPanels>
      <Item key="tab1">Tab 1 content</Item>
    </TabPanels>
  </Flex>
</Tabs>
```

### API

* `useTabs` should be renamed to `useTabList`
* `useTabsState` should be renamed to `useTabListState`
* `tabPanelProps` should be removed from `useTabs` and added to a new `useTabPanel` hook

```tsx
interface TabListProps<T> extends CollectionBase<T>, SingleSelection {}
interface AriaTabListProps<T> extends TabListProps<T>, DOMProps, AriaLabelingProps {
  keyboardActivation?: 'automatic' | 'manual',
  orientation?: Orientation,
  isDisabled?: boolean
}

interface TabListState<T> extends SingleSelectListState<T> {}
declare function useTabListState<T>(props: TabListProps<T>): TabListState<T>;

interface TabListAria {
  tabListProps: HTMLAttributes<HTMLElement>
}

declare function useTabList<T>(props: AriaTabListProps<T>, state: TabListState<T>): TabListAria;

interface TabProps {
  key: Key
}
interface AriaTabProps extends TabProps, DOMProps, AriaLabelingProps {}

interface TabAria {
  tabProps: HTMLAttributes<HTMLElement>
}

declare function useTab<T>(props: AriaTabProps, state: TabListState<T>): TabAria;

interface TabPanelProps {
  key: Key
}
interface AriaTabPanelProps extends TabPanelProps, DOMProps, AriaLabelingProps {}

interface TabPanelAria {
  tabPanelProps: HTMLAttributes<HTMLElement>
}

declare function useTabPanel<T>(props: AriaTabPanelProps, state: TabListState<T>): TabPanelAria;
```

In this case, the Spectrum API and the Aria/Stately APIs are quite different. Most props should go to the top `<Tabs>` element which has no Aria equivalent. In addition the `<TabPanels>` element has no Aria equivalent, just the individual panels. It should be possible to implement this API on top of the ARIA API using context and a bit of prop mapping to send things to the right places. 

```tsx
interface SpectrumTabsProps<T> extends SingleSelection, DOMProps, StyleProps {
  items?: Iterable<T>,
  keyboardActivation?: 'automatic' | 'manual',
  orientation?: Orientation,
  isDisabled?: boolean,
  disabledKeys?: Iterable<Key>,
  isQuiet?: boolean,
  density?: 'compact' | 'regular'
}

interface SpectrumTabListProps<T> extends DOMProps, StyleProps {
  children: CollectionChildren<T>
}

interface SpectrumTabPanelsProps<T> extends DOMProps, StyleProps {
  children: CollectionChildren<T>
}
```

I believe the `<Tabs>` component may also need its own state to store the selection, and then use the `useTabListState` in controlled mode (e.g. passing `selectedKeys` in from context). The `<TabPanels>` component will also need to use the `useCollection` hook to build its own collection so that it can find the correct tab panel to display.

## 🧢 Your Company/Team

RSP

**Comment by intergalacticspacehighway** [comment]
My initial implementation. 
https://github.com/intergalacticspacehighway/react-spectrum/blob/feat/tabs-api-update/packages/%40react-spectrum/tabs/src/Tabs.tsx 
(Custom layout requirement (e.g. Flex as children in Tabs) and storybook examples+testcases are working).
This is [hacky atm](https://github.com/intergalacticspacehighway/react-spectrum/blob/feat/tabs-api-update/packages/%40react-spectrum/tabs/src/Tabs.tsx#L259). I didn't find any better way to share state between list and panel (unless we move the entire state to the Tabs)

Also, I am not sure how useful it would be to make TabPanels and TabList as collection components since useCollection already works with `<Item />` as children for TabPanels and `useTabListState` handles the same for TabList.
Also, it would be difficult to build a collection tree like `Table` as TabList and TabPanels won't always be immediate children.

I might be missing something. Let me know if I should refer to any other component for reference!

**Comment by devongovett** [comment]
Thanks for working on this so quickly @intergalacticspacehighway! I spent some time thinking about this problem and all the alternate solutions I could think of were worse than your current solution. As you said, it's not really possible to move the state to the Tabs because the collection is built based on the children of the TabList. Other options I considered were changing `useTabPanel` to take the `tabListId` and `selectedKey` as props instead of passing in the state, but I don't really like forcing users of React Aria to manage these types of things since they are easy to get wrong. It also makes the API harder to use for the simple case, which is just a single component with both the TabList and TabPanel in one component rather than the more flexible API we are implementing for Spectrum. What you've done is a bit hacky but overall not too bad, so I think it's fine to go ahead with that.

**Comment by intergalacticspacehighway** [comment]
@devongovett true, I'll take a fresh look and see if I can make any improvements. Will generate a PR soon! Thanks 😄

**Comment by intergalacticspacehighway** [comment]
@devongovett what if we do something like below and remove the dependency on state in useTabPanel. I haven't tested this yet. Might have race conditions depending upon order of useTabs and useTabPanels, but using the optional condition should do the trick.
Idea is to have the same ids for a `tab that is selected` and `tabpanel` between rerenders 😅 

Will test it as I get some time.
<img width="1083" alt="Screenshot 2021-03-12 at 2 33 37 PM" src="https://user-images.githubusercontent.com/23293248/110917456-f023fa00-833f-11eb-9320-55c04fb0ae22.png">

**Comment by intergalacticspacehighway** [comment]
@devongovett tabPanel can always have an id like *-tabPanel and the selected tab can always have an id of *-tab-selected. We just need to set them on the mount and preserve them between renders (using the tabIds Weakmap?) 
I think something like this should remove the dependency on the state in useTabPanel.

**Comment by intergalacticspacehighway** [comment]
@devongovett One more solution I can think of is to use a useControlledState or a new hook called useSingleSelectState at Tabs component and use useListState in useTabListState instead of useSingleSelectListState.

Downside of this is that it'll change the useTabList ARIA hook's API. 🙁
declare function useTabList<T>(props: AriaTabListProps<T>, state: TabListState<T>): TabListAria;
to
declare function useTabList<T>(props: AriaTabListProps<T>, state: SingleSelectState<T>, listState: TabListState<T>): TabListAria;
declare function useTabPanels<T>(props: AriaTabPanelProps<T>, state: SingleSelectState<T>);
