### ISSUE TITLE
[NumberField] onChange does not work as expected

### ISSUE THREAD

**Issue by MistaPidaus** [adobe/react-spectrum#1674]
# 🐛 Bug Report 

`onChange` event of `useNumberField` from `@react-aria/numberfield` or `NumberField` from `@react-spectrum/numberfield` does not work as expected.

## 🤔 Expected Behavior

Expecting that every time user input or type, it should trigger `onChange` event when it pass to the component prop. For controlled form, it should trigger the state changes whenever user input which can be seen in `console.log`

## 😯 Current Behavior

Currently, it only trigger like `onBlur` event. User have to click outside of the input in order to see the changes, in this case to see the updated state. doing `console.log` and see it only trigger whenever click anywhere outside of the input.

## 🔦 Context

I'm trying to use `useNumberField` from `@react-aria/numberfield` with React Hook Form by using `Controller` by RHF but turns out that `NumberField` doesn't properly doing `onChange` event as expected while `TextField` works fine. 

## 💻 Code Sample

https://codesandbox.io/s/react-spectrum-numberfield-issue-jdp5p

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.4 and 3.0-alpha for NumberField
| Browser          | Chrome
| Operating System | MacOS

**Comment by devongovett** [comment]
This is actually intentional, and is documented [here](https://react-spectrum.adobe.com/react-aria/useNumberField.html#controlled). The reason is that partial input may not be parseable to a valid number, e.g. if the user just typed a decimal point or other symbol. Therefore it doesn't really make sense to fire the onChange event as the user types. What's your usecase for an incremental value rather than waiting until the user commits their changes?

**Comment by MistaPidaus** [comment]
I have another thing that is watching and display accordingly based on user input value.

For example, I have a number field where user have to input an amount value and another function that watch the value change and display a fee based on the user input value like a "real-time" fee calculation.

**Comment by devongovett** [comment]
One other issue is that when the `value` prop changes, we need to re-format the value according to the locale and number format options. If we did this as the user was typing, this might lead to a weird experience. For example you'd type the number 2 and other characters might appear (e.g. the currency symbol, unit, etc.) and we'd need to figure out where to put the cursor. For that reason it's probably easier to keep doing it on blur. Open to suggestions though if you have ideas on how to implement this. cc. @snowystinger

**Comment by MistaPidaus** [comment]
Well, I guess I leave this issue for now. We don't have a strong preference or requirements at the moment regarding the approach so I guess I'll try make use what it is now. But again, it would be nice if we have it.

I'm closing this issue.

**Comment by snowystinger** [comment]
We started out with this feature, however, as noted above it quickly became untenable with formatting.
I think it'd have to be a different component without formatting, a smaller range (so we don't need group characters like the comma for thousands in en-US-u-nu-latn), and possibly restrictions around decimals (decimals characters also vary based on locale and numeral system and therefore keyboards)

**Comment by MistaPidaus** [comment]
I was looking something like [react-number-format](https://www.npmjs.com/package/react-number-format) but since react-aria provide accessibility out of the box, gotta go for that.

**Comment by snowystinger** [comment]
Ah, very cool project, I think there's room for improvement to this component. And it looks like they might have figured out how to deal with selection position while formatting in real time, that was one of our biggest issues as Devon noted. We should look into how they handle that and make sure it works with things like pinyin.
