### ISSUE TITLE
[RSP - NumberField] Events are not triggered

### ISSUE THREAD

**Issue by evargast** [adobe/react-spectrum#1676]
# 🐛 Bug Report 

## 🤔 Expected Behavior

General input event handlers are triggered appropriately
![Screen Shot 2021-03-09 at 1 09 55 PM](https://user-images.githubusercontent.com/52969178/110524304-d765db00-80d8-11eb-82d1-de2ac529b011.png)

## 😯 Current Behavior

**onBlur, onFocus, onFocusChange** are not being triggered correctly

[see example here](https://codesandbox.io/s/numberfield-events-cpf3d?file=/src/App.tsx)

## 🔦 Context

The NumberField input should update the page context, but there's no need to update the context onChange, ideally we update it once `onBlur`

```javascript
  const [value, setValue] = React.useState(0);

  const updateContext =() => {
    pageContext.update({number: value})
  }

  return (
      <NumberField
        label="Events example"
        minValue={0}
        value={value}
        onChange={setValue}
        onBlur={updateContext}
      />);
```

## 💻 Code Sample

[CodeSandbox](https://codesandbox.io/s/numberfield-events-cpf3d?file=/src/App.tsx)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.8.0 | 
| react-spectrum/numberfield   | 3.0.0-alpha.1 |
| Browser          | Chrome Version 89.0.4389.82 (Official Build) (x86_64) | 
| Operating System | MacOS Big Sur 11.1 | 

## 🧢 Your Company/Team

Adobe / Commerce Cloud

**Comment by ktabors** [comment]
I confirmed the this events are not being called because they aren't being passed it, the theory is useNumberField needs these, probably useFocusable similar to useTextfield.

**Comment by evargast** [comment]
**Update**: 

useNumberInput was missing useFocusable as mentioned by Kyle above, we need to call it, pass it props and inputRef, then merge it with the other props.

@ktabors has a working solution, we should have a PR ready soon 🙂
