### ISSUE TITLE
ViewStyleProps#border*Width does not allow number or custom dimension values

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#1679]
# 🐛 Bug Report 

eg "borderTopWidth" is defined as 

```typescript
/** The width of the top border. See [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-width). */
borderTopWidth?: BorderSizeValue
```
and BorderSizeValue is

```typescript
export type BorderSizeValue =
  | 'thin'
  | 'thick'
  | 'thicker'
  | 'thickest';
```
which is then translated to 

```css
border-top-width: var(--spectrum-alias-border-size-thin);
```

## 🤔 Expected Behavior

Allow the developer to specify absolute values (eg 2px) or a custom `DimensionValue` like `size-10`.

## 😯 Current Behavior

Not possible

## 💁 Possible Solution

There are 2 solutions:
* redefined BorderSizeValue to 
```typescript
export type BorderSizeValue =
  | 'thin'
  | 'thick'
  | 'thicker'
  | 'thickest'
  | DimensionValue;
```
* redefine `border*Width` to `BorderSizeValue | DimensionValue`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
@tomsontom Those border size values are from Spectrum design guidelines, hence why the definition is so strict. If you'd like to have a View with a custom border width, you can use a div instead.

**Comment by tomsontom** [comment]
But then I'd miss the other cool features like spectrum colors, ... - the alternative would be giving public API to use those in divs or just wrap View into div to get a border which feels really wrong!

**Comment by LFDanLu** [comment]
You could leverage `UNSAFE_style` to specify your border styles, would that suffice?

**Comment by tomsontom** [comment]
Right and that's what I have today but I wanted to get rid of all the warnings in my console so I started to clean up but got stuck with border 😃

**Comment by snowystinger** [comment]
There is a talk going on about making the CSS variable tokens available to JS, but that does not exist yet. View is meant to strictly adhere to Spectrum guidelines.
Can you provide the use case you're trying to implement? Maybe we can figure out a better solution with that information.

**Comment by tomsontom** [comment]
ok - I found a way to do that myself - i used `import { useStyleProps, viewStyleProps } from '@react-spectrum/utils';` and implemented a custom "View"-component where I can use the goodies from spectrum and still control the stuff I need to control

**Comment by tomsontom** [comment]
what I find a bit strange although is that the JS-Doc points to the MDN-Page but one can not set the values documented there so that's a bit strange

**Comment by dannify** [comment]
Fair point. We should specify somewhere that we use a subset according to Spectrum guidelines.
