### ISSUE TITLE
ComboBox in form submits input value rather than selected key

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#1690]
# 🐛 Bug Report 

Context: https://github.com/adobe/react-spectrum/discussions/1672

## 🤔 Expected Behavior

Not 100% sure but this is what I think might be correct:
ComboBox with `allowCustomValue=false` should probably submit its selected key on form submit. ComboBox with `allowCustomValue=true` should probably submit its input value on form submit if no selected key exists, otherwise submit its selected key.

EDIT: The above proposal has an issue since the user wouldn't be able to tell if it is a key or the input value being submitted

## 😯 Current Behavior

ComboBox always submits its input value on form submit

## 💁 Possible Solution

Possibly use HiddenSelect? Use something similar to HiddenSelect? Need to investigate

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by devongovett** [comment]
I think we could use an `<input type="hidden" name={props.name} value={selectedKey}>` rather than putting the `name` attribute on the `<input type="text">` element. I guess only when `allowsCustomValue` is false? When if it's true though? Would you want to submit the `selectedKey` or the input value in the case the user _did_ select on the of the items but custom values _are_ allowed.

**Comment by tenphi** [comment]
@devongovett I would add that `allowsCustomValue` should allow selecting any value using `defaultSelectedKey` or `selectedKey` prop.
Currently, If a form has an initial value for Combobox and it's not on the list it's impossible to set it.
There is a `defaultInputValue` prop but it doesn't look good to use it for this scenario. Maybe I don't understand something here.

IMHO Submitting the custom value is also critical.

**Comment by devongovett** [comment]
It sounds like what `defaultInputValue` is for, but feel free to open a separate discussion or issue about that if you're having trouble.
