### ISSUE TITLE
If there aren't enough items to fill the Table height, user cannot trigger a loadMore operation

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#1691]
# 🐛 Bug Report 

Right now loadMore is triggered via scrolling in the Table (from what I can tell). If there aren't enough items to fill the table body, the user can't scroll the table and thus can't trigger loadMore. 

## 🤔 Expected Behavior

Perhaps the table should loadMore automatically if there aren't enough items to fill the window?

## 😯 Current Behavior

See description

## 💁 Possible Solution

I've been playing around with adding a useEffect to the TableVirtualizer that looks something like this:
```
  useEffect(() => {
    if (!collection.body.props.isLoading && collection.body.props.onLoadMore && !state.isAnimating) {
      if (bodyRef.current?.offsetHeight > state.virtualizer.contentSize.height ) {
        collection.body.props.onLoadMore();
      }
    }

  }, [collection.body.props.isLoading, state.virtualizer, state.isAnimating, bodyRef])
```
Bit finicky cuz it is triggering loadMore one extra time than is required... Need to dig to see when exactly state.isAnimating changes. Ideally this useEffect would only trigger when `isLoading=false` and after any new items finish loading+resizing in the table. Might be a transition delay issue?   

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by devongovett** [comment]
I assume this issue is also affecting ListBox because the logic is the same there (in Virtualizer)?

**Comment by LFDanLu** [comment]
Doesn't happen in ListBox because it sets `sizeToFit="height"` I think
