### ISSUE TITLE
Allow disabled menu items to be focused

### ISSUE THREAD

**Issue by cmmartti** [adobe/react-spectrum#1696]
# Feature Request
Currently, any menu items that are disabled cannot be focused. This does not match most native implementation of menus, at least in Windows (I'm not sure what the standard behaviour is in Apple's OSs).

I propose that an option like `allowDisabledFocus = false` be added somewhere that allows this. I am willing to submit a pull request with the changes if they're agreeable.

## Expected Behavior
That disabled menu items are focus-able and not skipped when using the arrow keys, and attempting to select them will do nothing (including keeping the menu open).

## Current Behavior
Currently, as per the documentation, disabled items 
> cannot be selected, focused, or otherwise interacted with.

## Context
I'm trying to match the behaviour of native menus, which allow disabled menu items to be focus-able, but there's no way to easily add this behaviour without re-implementing parts of React Aria myself. Since there's plenty of precedent for allowing disabled items to be focus-able (see example screenshots), in my opinion it should be supported.

The [WAI-ARIA recommendations](https://www.w3.org/TR/wai-aria-1.1/#aria-disabled) leave it up to the implementation:

> Disabled elements might not receive focus from the tab order. For some disabled elements, applications might choose not to support navigation to descendants.

From a user experience point-of-view, for static menus it can confusing when disabled items change the number of keypresses it takes to reach a particular option.

## Possible Solutions
Depending on what it should affect, an option called `allowDisabledFocus` (or similar) with a default value of `false` could go in a couple of different places.

Adding it to the [`ListKeyboardDelegate`](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/selection/src/ListKeyboardDelegate.ts) class would automatically extend the `allowDisabledFocus` capability to everything that uses it (`useComboBox`, `useSelect`, and `useSelectableList`).

Alternatively, if only `SelectableList`s (listboxes and menus) should have that capability, then [`useSelectableList`](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/selection/src/useSelectableList.ts) could be modified to pass an empty Set of `disabledKeys` to the `ListKeyboardDelegate` constructor if the option `allowDisabledFocus = true`.

Testing with the above modifications shows that disabled items correctly can't be selected with the keyboard, but I'm not sure if that's always the case, and if this change would have other far-reaching effects.

## Examples

Adobe Illustrator:
![disabled-focus_adobe-illustrator](https://user-images.githubusercontent.com/6448223/110960544-dc1ad100-831c-11eb-8c6a-5c9d9e0f0dc3.png)

Adobe Acrobat:
![disabled-focus Adobe Acrobat](https://user-images.githubusercontent.com/6448223/110885305-9d513080-82b4-11eb-9c0e-4919f2a4c822.png)

Firefox:
![disabled-focus Firefox](https://user-images.githubusercontent.com/6448223/110886054-f8cfee00-82b5-11eb-891d-9695f44893f3.png)

Android:
![disabled-focus_android](https://user-images.githubusercontent.com/6448223/110962827-649a7100-831f-11eb-8138-6a2a3b5981bd.png)

**Comment by cmmartti** [comment]
> other disabled controls like inputs and buttons are not focusable

If they're disabled with the `disabled` attribute in HTML, they're not, but if the `aria-disabled` attribute is used, focus-ability is dependent on the implementation. And WAI-ARIA only states that disabled items _might_ not receive focus, not that they shouldn't. And that's just on the Web. Natively, disabled controls are often focus-able, such as in Microsoft Office's Ribbon, although form-style dialogues usually disallow focusing disabled controls.

> Is there a UX reason...?

Yes, consistency with native Windows menus where disabled options are almost always focus-able (MacOS is not the target), and muscle memory. This is dependent on individuals and the application in question, obviously, but I for one prefer it when the number of keypresses to reach an otherwise static thing doesn't change. Random example: in Adobe Illustrator, I can reach the Tile Windows command with Alt+W, ↓↓→↓, and this never changes whether the menu options above or below it are disabled. There are other ways of reaching it (Alt+W, A, T), but the method I landed on over time is with the arrow keys.

If it's not something that Adobe is interested in including in the React Aria project, that's fine, but I noticed the discrepancy and wanted to see if I could change it.

In any case, I've just discovered that I can pass in a custom `KeyboardDelegate` with the preferred behaviour directly into `useMenu`, which is good enough for me.

**Comment by ktabors** [comment]
Thanks for the examples. We will bring this up to the design and accessibility teams. This would be handled holistically for all components. It looks like you have a workaround with the KeyboardDelegate.

**Comment by snowystinger** [comment]
Update
We're moving in the direction of this design https://spectrum.adobe.com/page/menu/#Unavailable, this will be released for React Spectrum components in the near future. You will also be able to implement this with hooks, but if you're using React Aria Components, then it's still a little ways off.

**Comment by dannify** [comment]
Unavailable menu items have been released fro React Spectrum. Please open a new issue to express interest in this feature in React Aria Components.
