### ISSUE TITLE
Non selectable table updates

### ISSUE THREAD

**Issue by dannify** [adobe/react-spectrum#1706]
When row selection is not on we would like to be able to allow text selection:

- Disable the active state when clicking on a row
- Investigate the need to remove hover state as well (ask Spectrum)
- Enable text selection might also be needed

Investigate how to not disable text selection because of usePress. Is it possible to remove/disable usePress so that it does not interfere with text selection on Tables without selection enabled.

**Comment by LFDanLu** [comment]
In progress work saved in https://github.com/adobe/react-spectrum/tree/issue_1706. Crux of the text selection issue is a `preventDefault` on mouse down in `useSelectableCollection` that fixes a bug where the scroll bar will jump when clicking on it. Couple fixes attempted including blurring the collection on click to avoid this issue but all have complications with other parts of the code (Virtualizer's onBlur).
