### ISSUE TITLE
toast completion?

### ISSUE THREAD

**Issue by Luiz-N** [adobe/react-spectrum#1707]
# 🙋 Feature Request

I noticed that there seems to be an undocumented or perhaps incomplete  [react-toast component in this codebase](https://github.com/adobe/react-spectrum/tree/main/packages/@react-aria/toast). Any clue on when/if this will be completed?

**Comment by snowystinger** [comment]
Doesn't look like it has a date yet, but you can follow along here https://github.com/adobe/react-spectrum/projects/1#card-43906135
There is also this doc, https://github.com/adobe/react-spectrum/blob/main/specs/api/Toast.md which has notes on conversations about implementation
If you wanted to contribute it, we'd need to discuss the concerns in that md file.
