### ISSUE TITLE
Add XMLS attribute to illustrated message SVG artwork

### ISSUE THREAD

**Issue by placegraphichere** [adobe/react-spectrum#1708]
Without the `xmlns="http://www.w3.org/2000/svg"` the assets are not copy/paste-able in Xd. (Copy source html and paste directly in Xd) The attribute appears to be in the workflow icons, but not the illustrated message SVG artwork. 

I don't think XMLS are required for any accessibility or functional reason, but they would be nice to include. 

Example here:
https://github.com/adobe/react-spectrum/blob/fc8fda0c6902e2790cc92ab2d3f7fbb6ffc6f365/packages/%40spectrum-icons/illustrations/src/Error.tsx#L6

**Comment by placegraphichere** [comment]
and the docs where I would like to copy and paste from:

https://react-spectrum.adobe.com/react-spectrum/IllustratedMessage.html

**Comment by snowystinger** [comment]
It could go into the util https://github.com/adobe/react-spectrum/blob/main/packages/@spectrum-icons/illustrations/src/utils.ts this is an internal only function, so that'd cut down on the copy paste

**Comment by devongovett** [comment]
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg says:

> Note: The xmlns attribute is only required on the outermost svg element of SVG documents. It is unnecessary for inner svg elements or inside HTML documents.

**Comment by snowystinger** [comment]
Ok, since it's not required and this isn't an actual use case for us, I would suggest reaching out to Spectrum who controls those assets and talk to them about getting those svgs. You can reach them here: https://spectrum.adobe.com/page/contact-us/
We won't be adding xlmns at this time
