### ISSUE TITLE
Date Picker (Date Range) V3, Support for date-fns for date/time math and formatting, and isValid on onChange event

### ISSUE THREAD

**Issue by motiooon** [adobe/react-spectrum#1715]
# 🙋 Feature Request

Hello Spectrum Team, 

My team at Adobe is migrating several packages from moment.js to date-fns for the date math and formatting. We're currently using Date Picker v2 which is reliant on moment.js under the hood. We would like to be able to use the new version of Date-Picker that is using date-fns. That would help us complete the migration to date-fns for our packages. 

If you have any stable nightly version that we can use please let me know, otherwise, I'd like to understand the projected date when we would be able to use the V3. 

## 🤔 Expected Behavior

1. The Date picker, should use internally date-fns so when we bring the component as a dependency into our packages, it will use date-fns instead of moment.js. 

2. Additionally in the API surface, should return back javascript Date objects rather than strings and moment.js instances. Date-fns operates on Date instances, and that would help us parse and further format any output from the Date Picker calendar.

3. The onChange event should have an argument that will give us the status of the date-range validation. For example, v2 returns on the onChange event Object and DateRange as the first and second argument, where Object is {start, end} of type string, and DateRange is {start, end} of type moment.js instances. When the start or end dates are invalid, the DateRange is being passed as null, which is indicative that the date range is invalid. One possible API surface for the date-fns version would be:

onChange: (isValid: Boolean, {start: Date, end: Date}) 

## 😯 Current Behavior

1. Date Picker is dependant on moment.js
2. onChange event is not passing an isValid argument, and higher-order components have no programmatic way to know if the start-end pair is a valid date range, unless they check the second argument to be null, or Object.

## 💁 Possible Solution

1. Replace the date/time library with date-fns
2. Change API surface of the onChange event to always have an isValid property, and the return types of start and end should be valid Javascript Date instances.

## 🔦 Context

My team is migrating all packages from moment.js to date-fns and the Date Picker V2 is dependent on moment.js, which blocks us, because as long as we have the Date Picker in the bundle, we are going to bring moment.js into the bundle.
Additionally as explained above, the isValid date range is not coming back explicitly from the onChange event which created confusion for some of our engineers, myself included, on how can we see if the date-range is valid when someone types the dates instead of selecting them.  

## 🧢 Your Company/Team

Adobe/Commerce and Provisioning

**Comment by dannify** [comment]
Hey @motiooon 
We will be working on DatePicker in the next couple of months. The current code is old work and will likely change quite dramatically from its current form. While we will not be using moment.js for our new version, it is likely that we will swap out date-fns for something else as well. 

We will certainly take into account the ability to determine validation state of the component.

**Comment by motiooon** [comment]
Thank you @dannify for the reply here. That sounds good. Re:
> it is likely that we will swap out date-fns for something else as well
What other libraries or solutions are you eyeing for the date/time math? Are you assessing if you can just use raw javascript Date, with navigator.locale support, write your own date/time math, or something else?

**Comment by devongovett** [comment]
We ended up building the [@internationalized/date](https://github.com/adobe/react-spectrum/tree/main/packages/%40internationalized/date) package for this, which has a similar API to date-fns in some ways, but supports internationalization. Going to close.
