### ISSUE TITLE
Unnecessary char inserted by Label.tsx when required=false and necessityIndicator=icon

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#1718]
# 🐛 Bug Report 

I was wondering today why I get a line break when the label exceeds the size of the field it covers and found. The reason for this is that I've set `<TextField label='Test' required={false} />`. Inspecting the source code I found that in the label text at the end the following HTML-Entity is added `&#8203;`.

I think adding this only makes sense if something follows after it

## 🤔 Expected Behavior

That no extra character is added at the end unless something follows after it. In case of isRequired=false this only makes sense if the necessityIndicator == 'label'

## 😯 Current Behavior

Added all the time no matter if some text follows or not

## 💁 Possible Solution

I've modified Label.tsx from:

```typescript
    <ElementType
      {...filterDOMProps(otherProps)}
      {...styleProps}
      onClick={onClick}
      ref={domRef}
      className={labelClassNames}
      htmlFor={ElementType === 'label' ? labelFor || htmlFor : undefined}>
      {children}
      {necessityIndicator && ' \u200b'}
      {/* necessityLabel is hidden to screen readers if the field is required because
        * aria-required is set on the field in that case. That will already be announced,
        * so no need to duplicate it here. If optional, we do want it to be announced here. */}
      {necessityIndicator === 'label' && <span aria-hidden={!includeNecessityIndicatorInAccessibilityName ? isRequired : undefined}>{necessityLabel}</span>}
      {necessityIndicator === 'icon' && isRequired && icon}
    </ElementType>

```

to this

```typescript
    <ElementType
      {...filterDOMProps(otherProps)}
      {...styleProps}
      onClick={onClick}
      ref={domRef}
      className={labelClassNames}
      htmlFor={ElementType === 'label' ? labelFor || htmlFor : undefined}>
      {children}
      {(necessityIndicator === 'label' || (necessityIndicator === 'icon' && isRequired)) && ' \u200b'}
      {/* necessityLabel is hidden to screen readers if the field is required because
        * aria-required is set on the field in that case. That will already be announced,
        * so no need to duplicate it here. If optional, we do want it to be announced here. */}
      {necessityIndicator === 'label' && <span aria-hidden={!includeNecessityIndicatorInAccessibilityName ? isRequired : undefined}>{necessityLabel}</span>}
      {necessityIndicator === 'icon' && isRequired && icon}
    </ElementType>
```

## 💻 Code Sample

```typescript
<View maxWidth="30px"><TextField width="100%" label="TestenTestenTesten" isRequired={false} /></View>
```

Results in:
<img width="305" alt="Bildschirmfoto 2021-03-19 um 22 42 58" src="https://user-images.githubusercontent.com/52631/111845096-81790a80-8904-11eb-893d-f0e519cd119b.png">

With the above changes described above it looks like this:
<img width="305" alt="Bildschirmfoto 2021-03-19 um 22 44 51" src="https://user-images.githubusercontent.com/52631/111845240-c13ff200-8904-11eb-9961-faf0d841277f.png">

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
Yep, I can see it in a codesandbox and seems like a good fix
https://codesandbox.io/s/wild-browser-hjbrz?file=/src/App.js
