### ISSUE TITLE
Fix issues reported by lgtm

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#1734]
# 🐛 Bug Report 

I came by https://lgtm.com/projects/g/adobe/react-spectrum/alerts/?mode=list&severity= who reports that problem which is indeed correct as the as the value computed is not used in the otuer block

## 🤔 Expected Behavior

narrow the variable scope and don't do unnecessary work

## 😯 Current Behavior

Useless assignment

## 💁 Possible Solution

Move the variable-declaration into the `if()`-block 

```typescript
function addColorValue(color: Color, step: number) {
  let newColor = color ? color : MIN_COLOR;
  let colorInt = newColor.toHexInt();
  
  let clampInt = Math.min(Math.max(colorInt + step, MIN_COLOR_INT), MAX_COLOR_INT);
  if (clampInt !== colorInt) {
    let newColorString = `#${clampInt.toString(16).padStart(6, '0').toUpperCase()}`;
    newColor = parseColor(newColorString);
  }
  return newColor;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by tomsontom** [comment]
I could provided fixes for other issues covered in the report above

**Comment by snowystinger** [comment]
what a cool tool, very picky :)
I don't see anything from that report that suggests the wrong fix, I'm actually surprised we have that few alerts
I see no reason not to do most of those, I don't think i'd worry about the shell command ones though in merge-spectrum-css.js, that's just internal tooling

**Comment by tomsontom** [comment]
If you agree I would make Issues/PRs one by one but I could naturally address more in one issue/PR as well.

On the number of issues - I've not yet looked how many rules/queries this tool currently uses and what's not there yet but could be added/improved

**Comment by snowystinger** [comment]
I think they look pretty benign, I'd just do it in one unless you run into something complicated. Thanks!
