### ISSUE TITLE
Upgrade Parcel

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#1743]
# 🙋 Feature Request

We need to upgrade parcel, to do so though we would need to upgrade postcss. Since we likely can't upgrade postcss, we may need to grab the older parcel plugin (hopefully only one, but maybe 2) to support the older postcss
https://v2.parceljs.org/languages/postcss/
https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/css/package.json

**Comment by krisnye** [comment]
@krisnye following this so I can remove my @react-spectrum-uxp/parcel-resolver-alias-fix workaround.
