### ISSUE TITLE
v3 Table - toggle transitions on/off

### ISSUE THREAD

**Issue by eduardn** [adobe/react-spectrum#1747]
# 🙋 Feature Request

A way for the table component transitions to be disabled/enabled.

## 🤔 Expected Behavior

Table should have a prop that can be used to toggle transitions on/off.

## 😯 Current Behavior

There is no way to do that currently.

## 💁 Possible Solution

Had a look through the code and it seems that the `Table` renders a `TableVirtualizer` that accepts a `transitionDuration`

https://github.com/adobe/react-spectrum/blob/6521a98b5cc56ac0d93109e31ffcf0a9b75cee62/packages/%40react-spectrum/table/src/Table.tsx#L292

and this is used in the `Virtualizer` to decide if the data should be animated when set

https://github.com/adobe/react-spectrum/blob/6521a98b5cc56ac0d93109e31ffcf0a9b75cee62/packages/%40react-stately/virtualizer/src/Virtualizer.ts#L208-L211

Setting that to 0 seems to disable the animations.

## 🧢 Your Company/Team

Adobe/Identity Mars

**Comment by dannify** [comment]
Hey @eduardn
We will be working on Table in the next few months and updating the transitions will be one of the changes we will be tackling. Currently we are revising this with the Spectrum design team.

**Comment by eduardn** [comment]
Hey @dannify, thanks for the details. I'll patiently await updates 😄

**Comment by viswesh** [comment]
V3 looks great, thanks to all the contributors. About transitions, when there are many rows, animations stagger and look janky. With transitions turned off, interactions are snappier (sort, search). 
```
.table * {
  transition: none !important;
}
```
