### ISSUE TITLE
required is missing in return value of useTextField

### ISSUE THREAD

**Issue by kqito** [adobe/react-spectrum#1750]
# 🐛 Bug Report 

`useTextFiled` receives `isRequired` as an argument. 
However, the argument is only used for `aria-required`, which does not affect whether the input is actually `required` or not, which may be different from the actual behavior.

please see: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required

So I suggest to include `required` in the return value

## 🤔 Expected Behavior

The return value contain `required`

## 😯 Current Behavior

The return value does not contain `required` 

## 💁 Possible Solution

I suggest to add `required` to  return value of `useTextField` as following

```ts
return {
  required: isRequired || undefined, 
  'aria-required': isRequired || undefined, 
}
```

## 🔦 Context

The problem is that even if `isRequired` is true, it is possible to send even if there is no value in input.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/textfield | 3.2.2
| Browser          | Chrome (Version 89.0.4389.90 (Official Build) (x86_64))
| Operating System | Mac OS

**Comment by snowystinger** [comment]
Closing, here's relevant conversation from PR
>We should not rely on browser validation as it will be inconsistent. Validation is up to the application. That’s why we use aria-required and not required.
If you are using our hooks, you can just pass required directly to the element you want it on.
If you are using the Spectrum components, then you should use the validationState prop.
