### ISSUE TITLE
Add trimTextWithEllipsis prop

### ISSUE THREAD

**Issue by kcoop** [adobe/react-spectrum#1759]
We have a requirement in our text fields for displaying overflowing text as truncated with a trailing ellipsis when the text field does not have the focus. 

Would be great to have a `unfocusedTextOverflow` prop or some such thing, e.g. 
```
unfocusedTextOverflow: "Clip" | "Ellipsis" |  string;
```
where "Clip" is the default.

**Comment by snowystinger** [comment]
It looks like we already do this? https://react-spectrum.adobe.com/react-spectrum/TextField.html
I tried it in chrome, when I'm typing there is no ellipsis and when I blur, there are.
Do you mean TextArea? That one should never have an ellipsis https://spectrum.adobe.com/page/text-area/

**Comment by kcoop** [comment]
Well, should have mentioned, we also (at least currently) have the requirement that sometimes it's clipped. :-)

**Comment by kcoop** [comment]
So maybe have "Ellipsis" be the default?

**Comment by dannify** [comment]
Spectrum guidelines specify that overflow behavior for TextFields should be truncated with ellipsis. May be an idea to bring up your use case of clip with them?
https://spectrum.adobe.com/page/text-field/#Text-overflow

**Comment by snowystinger** [comment]
Closing as we're following current Spectrum guidelines. If they decide to change, we'll update with them.

**Comment by kcoop** [comment]
Fair enough. In our situation, we have a mishmash of Spectrum and not, but that's not your problem.
