### ISSUE TITLE
useTextField TypeScript defintion provides unsatisfiable union for inputProps

### ISSUE THREAD

**Issue by chrishoage** [adobe/react-spectrum#1760]
# 📝 Feedback

https://github.com/adobe/react-spectrum/blob/e066b675c123776d4cac96595143b6d3a96f8fc6/packages/%40react-aria/textfield/src/useTextField.ts#L20-L25

The `inputProps` union is unsatisfiable by typescript when applied to an input or a textarea because the onChange handler contains an argument defined as a explicit HTML element

```
 Type '{ ref: (e: HTMLInputElement) => void; accept?: string | undefined; alt?: string | undefined; autoComplete?: string | undefined; autoFocus?: boolean | undefined; ... 282 more ...; css?: InterpolationWithTheme<...>; } | { ...; }' is not assignable to type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.
  Type '{ ref: (e: HTMLInputElement) => void; autoComplete?: string | undefined; autoFocus?: boolean | undefined; cols?: number | undefined; dirName?: string | undefined; ... 264 more ...; css?: InterpolationWithTheme<...>; }' is not assignable to type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.
    Type '{ ref: (e: HTMLInputElement) => void; autoComplete?: string | undefined; autoFocus?: boolean | undefined; cols?: number | undefined; dirName?: string | undefined; ... 264 more ...; css?: InterpolationWithTheme<...>; }' is not assignable to type 'InputHTMLAttributes<HTMLInputElement>'.
      Types of property 'onChange' are incompatible.
        Type 'ChangeEventHandler<HTMLTextAreaElement> | undefined' is not assignable to type 'ChangeEventHandler<HTMLInputElement> | undefined'.
          Type 'ChangeEventHandler<HTMLTextAreaElement>' is not assignable to type 'ChangeEventHandler<HTMLInputElement>'.
            Type 'HTMLTextAreaElement' is missing the following properties from type 'HTMLInputElement': accept, align, alt, checked, and 23 more.

57     return <input {...inputProps} ref={ref} />;
```

It appears that in at least one of the components in react-spectrum sidestep this issue because it is passing a chained callback which does not break the type signature

https://github.com/adobe/react-spectrum/blob/28ceccbf05637e9fb256794a16c0152e52be179e/packages/%40react-spectrum/textfield/src/TextArea.tsx#L52-L54

I recommend using a generic in `useTextField` that will apply the correct attributes depending on the ref object passed in. 

## 🔦 Context

I am unable to apply the inputProps with out casing inputProps first

## 💻 Code Sample

I have provided a minimal repo case here https://codesandbox.io/s/affectionate-bardeen-rtfmw

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| [Package name]   |
| Browser          |
| Operating System |

**Comment by torgeadelin** [comment]
I'm having the same issue.

**Comment by devongovett** [comment]
Perhaps we should make `useTextField` generic based on the `elementType` prop? i.e. it could return `InputHTMLAttributes` if `elementType="input"` (by default), and `TextAreaHTMLAttributes` if `elementType="textarea"`?

**Comment by chrishoage** [comment]
That is roughly the solution I came up with in my now closed PR https://github.com/adobe/react-spectrum/pull/1761

However the hooks that compose this (`useCombobox` and `useSearchField`) also needed to be updated. 

I was unable to complete the PR due to being unable to test the resulting typescript definition files due to this bug https://github.com/adobe/react-spectrum/issues/1388

**Comment by torgeadelin** [comment]
I managed to make the error go away by casting the `inputProps` as follows:
```
<input
  {...(inputProps as React.InputHTMLAttributes<HTMLInputElement>)}
  ref={ref}
/>
```

Ideally this should be fixed in the package.

**Comment by bstro** [comment]
Any plans to address this issue relatively soon? As-is, this hook is effectively broken when used in a typescript codebase.
