### ISSUE TITLE
useButton generated types.d.ts missing imports causing incorrect buttonProps type

### ISSUE THREAD

**Issue by chrishoage** [adobe/react-spectrum#1764]
# 🐛 Bug Report 

```
InputHTMLAttributes, ButtonHTMLAttributes, AnchorHTMLAttributes
```

These imports are missing from react in `@react-aria/button/useButton`. It appears that parcel does not properly extract the function overloads for useButton. 

This makes the return type from useButton and useToggleButton return `any` since typescript can't properly resolve the types

## 🤔 Expected Behavior

![image](https://user-images.githubusercontent.com/1056886/113451148-39eb8780-93b6-11eb-98da-678a23c72733.png)

## 😯 Current Behavior

https://codesandbox.io/s/frosty-jones-6lw40

![image](https://user-images.githubusercontent.com/1056886/113451120-2cce9880-93b6-11eb-933b-d2d9f2a4204d.png)

## 💁 Possible Solution

It's not clear if it's a bug in parcel, but the imports used in the overloads are not being picked up. 

`tsc useButton.ts -d` correctly picks up the types imported for the overloads

Adding 

```ts
export type UsedForParcel<T> =
  | AnchorHTMLAttributes<T>
  | ButtonHTMLAttributes<T>
  | InputHTMLAttributes<T>
  | HTMLAttributes<T>;
```

to `useButton.ts` allows parcel to properly detect the types and import them. 

This is far from ideal, but would make the output correct at least. 

I have never used parcel so I don't have a good solution for this problem. 

## 🔦 Context

the `useButton` return type is unreliable and the current types that are output in the package are broken.  

## 💻 Code Sample

https://codesandbox.io/s/frosty-jones-6lw40

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
Does https://github.com/adobe/react-spectrum/issues/1388 cover what you are encountering here?

**Comment by chrishoage** [comment]
Yes, this does appear to be the same issue. Apologies for the noise! 

Closing as duplicate of #1388
