### ISSUE TITLE
Nightlies fail if there were no changes

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#1769]
# 🐛 Bug Report 

Nightly builds of RSP will fail (sending a failure e-mail) if there were no changes since the last nightly. It'd be better if we just didn't run that workflow if there were no changes.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by dannify** [comment]
Used to it now. One day we will revisit this.
