### ISSUE TITLE
Add ActionBar component

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#1790]
![image](https://user-images.githubusercontent.com/19409/114802315-5b535880-9d52-11eb-9405-830d47cdfcf4.png)

# 🙋 Feature Request

An ActionBar allows users to perform bulk actions on the selected items in collection components like TableView, GridView, ColumnView, etc. It composes an [ActionGroup](https://react-spectrum.adobe.com/react-spectrum/ActionGroup.html) with a count of selected items and a button to clear the selection.

## 💁 API

The action bar will be split into two components: the `ActionBar` itself, and an `ActionBarContainer` (name TBD), which provides the layout for a collection component (e.g. Table) and the bar.

The `ActionBar` is a collection component. It accepts `<Item>` elements as children just like an `ActionGroup`. It should be implemented with `ActionGroup` internally, but only expose a subset of options.

```ts
interface ActionBarProps extends CollectionBase {
  // Required. When zero, the ActionBar is hidden.
  selectedItemCount: number,
  // Also required. When clicked, the selection should be cleared.
  onClearSelection: () => void,
  isEmphasized?: boolean,
  onAction?: (key: Key) => void
}
```

The `ActionBarContainer` adjusts the size of the collection component when it becomes visible to reduce the size such that the ActionBar does not cover the content and the user can still scroll to the last row. This can likely be implemented using [slots](https://react-spectrum.adobe.com/react-spectrum/layout.html#slots).

```ts
interface ActionBarContainer {
  children: ReactNode
}
```

### Example

```jsx

<ActionBarContainer>
  <Table selectedKeys={selectedKeys}>
    {...}
  </Table>
  <ActionBar
    selectedItemCount={selectedKeys.size}
    onClearSelection={...}
    isEmphasized>
    <Item>Edit</Item>
    <Item>Delete</Item>
  </ActionBar>
</ActionBarContainer>
```

### Questions for design
- What ActionGroup properties should be supported?
    - ~~Justified?~~ not for now
    - ~~Density?~~ not for now
    - Is it always quiet?
    - I assume not emphasized because the bar also has a different emphasis?
    - Not orientation
    - Probably not selection?

## 🧢 Your Company/Team

RSP

**Comment by bhellema** [comment]
@matthewdeutsch - do you have an idea of the timeline for this component?  This is something that we would greatly benefit from on the AEM Odin project.

**Comment by matthewdeutsch** [comment]
@bhellema we have another Adobe team interested in contributing this to RSP, and we'll be kicking off discussions with them next week — we understand this component is being requested by many teams looking to enable bulk actions, and I'll follow up with you soon on status. Thanks!
