### ISSUE TITLE
<Image> prevents flex layout from using img aspect ratio

### ISSUE THREAD

**Issue by kcoop** [adobe/react-spectrum#1791]
Because `<Image>` wraps the `<img>` tag in a div with width & height = "100%", a flex container is unable to use the aspect ratio of the image to calculate unspecified dimensions, so one has to rely on explicit widths and heights.

See this example showing an `<Image>` and an `<img>`: https://codesandbox.io/s/hungry-mclaren-tgqt0?file=/src/App.js

**Comment by snowystinger** [comment]
Image is only meant to be used in situations where a parent is providing styles to it such as Dialog. You can read more about these components here https://react-spectrum.adobe.com/react-spectrum/layout.html#slots. You should use a plain `img` tag.
We'll probably move those components to a different section in the docs in the near future, we realize where they are now is a bit misleading for what can be used standalone vs inside one of these contexts.

**Comment by kcoop** [comment]
I see. Thanks for the clarification.
