### ISSUE TITLE
only handle vertical wheel on NumberField

### ISSUE THREAD

**Issue by bung87** [adobe/react-spectrum#1792]
# 🙋 Feature Request
only handle vertical wheel on number field, for Mac user's touch pad.

## 🤔 Expected Behavior
only handle vertical wheel on number field

## 😯 Current Behavior
unexpectedly horizontal wheel changes the value

**Comment by snowystinger** [comment]
This should be fixed in https://github.com/adobe/react-spectrum/pull/1530 which has been released, can you try a newer version and let us know if it's still happening?

**Comment by bung87** [comment]
I think need compare deltaX and deltaY absolute value to determine which direction , when two fingers swipe on touch pad, there are deltaX and deltaY two values changes, can't relys only `deltaY`.

**Comment by snowystinger** [comment]
Ah, I see this. The issue being that if you drag at anything that is slightly diagonal it'll register as stepping the value.
