### ISSUE TITLE
Button's onPress callback not fired on iOS.

### ISSUE THREAD

**Issue by stpnvntn** [adobe/react-spectrum#1807]
# 🐛 Bug Report 

I faced an issue using `useButton` from `@react-aria/button` . I have a pretty simple form (input + submit button) alongside with an additional content. When user clicks on the input the native keyboard are showed. After that any click on the button won't fire any event.
The issue exists only when use `useButton().buttonProps` (seems the root cause is `onPointerDown`). Without `useButton` everything works fine. Also, if there is no additional content on the page everything works fine as well.

## 🤔 Expected Behavior

`onPress` callback should be called.

## 😯 Current Behavior

`onPress` callback not be called.

recording:
https://user-images.githubusercontent.com/15350011/115405509-f935a000-a1f6-11eb-909a-cff9b4780ffa.mp4

## 💁 Possible Solution

https://github.com/adobe/react-spectrum/pull/1809

## 🔦 Context

Want to reduce among on click user need to do. 

## 💻 Code Sample

I build a simple demo stand to reproduce the issue: https://codesandbox.io/s/react-ariabutton-issue-xikke?file=/src/App.js.

https://xikke.csb.app/ 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/button   | 3.3.1
| Browser          | Safari 14  or Google Chrome on iOS 87.0.4280.163
| Operating System | iOS 14.4

## 🧢 Your Company/Team

n/a

## 🕷 Tracking Issue (optional)

n/a

**Comment by snowystinger** [comment]
I can't quite tell, are you running into the same thing as this issue? https://github.com/adobe/react-spectrum/issues/1061 & PR

**Comment by stpnvntn** [comment]
No, unfortunately they are not the same

**Comment by ktabors** [comment]
I adjusted the codesandbox examples and these two issues appear different. Looking at the PRs their solutions might be similar or related.

**Comment by aaliakseyenka** [comment]
hey @ktabors is it smth we can get forward with the PR created by @stpnvntn?

**Comment by ktabors** [comment]
Were Devon's comments on the PR helpful in resolving this? I haven't seen any updates since that conversation.

**Comment by aaliakseyenka** [comment]
Hey @ktabors, yes, we decided to go using the workaround for now. Verified it is working as expected

**Comment by ktabors** [comment]
Closing this issue because there is a workaround. Please reopen if there is additional need.
