### ISSUE TITLE
NumberField: [ Violation ] non-passive event listener

### ISSUE THREAD

**Issue by ashalogic** [adobe/react-spectrum#1853]
# 🐛 Bug Report 

[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.

## 🤔 Expected Behavior

no warning.

## 🔦 Context

![image](https://user-images.githubusercontent.com/42332369/116715578-22b0b180-a9d7-11eb-9ea1-d1844407a46c.png)

## 💻 Code Sample

`<NumberField onChange={setValue} label="Days" />`

## 🌍 Your Environment

even on the official website

**Comment by LFDanLu** [comment]
@ashalogic I can't seem to reproduce this on the docs on my end, what were your reproduction steps?

**Comment by ktabors** [comment]
Closing and we can reopen if it's still a problem.
