### ISSUE TITLE
Table View should have ability for users to resize columns 

### ISSUE THREAD

**Issue by jesca** [adobe/react-spectrum#1855]
# 🙋 Feature Request
Requesting the ability for the table view to have a feature to allow users to resize the columns. Users have different needs for screen real estate.

## 😯 Current Behavior
Fixed table column sizes

## 🔦 Context
The Adobe Sign Manage page has many customers requesting the ability to change column sizes.
 
## 🧢 Your Team
Adobe Sign - Document Cloud

## 🎁 Tracking Ticket
DCCR-2323

**Comment by devongovett** [comment]
Superseded by https://github.com/adobe/react-spectrum/issues/2555. Please track there. Going to close this one.
