### ISSUE TITLE
Users unable to scroll on certain devices

### ISSUE THREAD

**Issue by jesca** [adobe/react-spectrum#1856]
# 🐛 Bug Report 
Desktop users of mice without a scroll bar/touchpad cannot initiate scrolling on the table view.  

## 🤔 Expected Behavior
Scroll bar should always be present if there is overflowing content in the table view

## 😯 Current Behavior
Users of Adobe Sign's old manage page cannot scroll as the scroll bar doesn't show until a scroll is initiated on the touch pad  
https://share.getcloudapp.com/z8u6dR65

## 💁 Possible Solution
https://stackoverflow.com/questions/35663653/make-a-scrollbar-always-visible-in-a-div-chrome
  

## 🌍 Your Environment
Chrome / MacOS, but not sure if it's affecting other OSs.

## 🧢 Your Company/Team
Adobe Sign

## 🕷 Tracking Issue (optional)
DCCR-3108

**Comment by snowystinger** [comment]
Wouldn't this be a problem with every div that could scroll?
I think the solution would be to use the system preferences to show the scrollbars.
![Screen Shot 2021-04-30 at 5 51 09 PM](https://user-images.githubusercontent.com/698229/116765956-d7010680-a9dc-11eb-9229-8d5e338eda70.png)

I'm actually using this with my mouse right now and this is how my table looks.
![Screen Shot 2021-04-30 at 5 53 27 PM](https://user-images.githubusercontent.com/698229/116765989-fc8e1000-a9dc-11eb-9fde-552b6b8d3a31.png)
By default it's on automatic detection, which I've noticed does show the scrollbars when I plug in my mouse.

**Comment by jesca** [comment]
See gmail's scrollbar in the email list and chat -- 
<img width="940" alt="Screen Shot 2021-05-05 at 8 37 51 AM" src="https://user-images.githubusercontent.com/3870011/117168780-5431d000-ad7d-11eb-9b5e-109ac1dd8bb2.png">

Our page: 
<img width="934" alt="Screen Shot 2021-05-05 at 8 38 10 AM" src="https://user-images.githubusercontent.com/3870011/117168813-5c8a0b00-ad7d-11eb-90db-dbafe0689aad.png">

**Comment by snowystinger** [comment]
I hope you don't mind, I just want to clarify, you have a mouse connected right now, and you do not see the scrollbars? And you have that setting turned on for 'Automatically'?

**Comment by snowystinger** [comment]
Talked offline, closing because this is not a V3 issue. We are following up in V2
