### ISSUE TITLE
[react-stately][useControlledState] value param should be optional

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [adobe/react-spectrum#1859]
# 🐛 Bug Report 
In the `useControlledState` function, the first prop, `value`, can be optional. However, the typescript doesn't allow the `value` param to be optional.

## 🤔 Expected Behavior
The example below doesn't have any type errors, assuming that `validDefaultValue` and `validOnChange` have the right types.
```ts
useControlledState(undefined, validDefaultValue, validOnChange)
```

## 😯 Current Behavior
The first param has the typescript error: `Argument of type 'SomeType | undefined' is not assignable to parameter of type 'Value'.
  Type 'undefined' is not assignable to type 'Value'.ts(2345)`
```ts
useControlledState(undefined, validDefaultValue, validOnChange)
```

## 💁 Possible Solution
Solution is simple: change the current https://github.com/adobe/react-spectrum/blob/a71a0a7/packages/%40react-stately/utils/src/useControlledState.ts, which has param `value: T` to be `value: T | undefined`.

I can make a pull request fixing.

## 🔦 Context
I was trying to use the `useControlledState` to make a component optionally controlled (written in typescript), but then I got the typescript error.

## 💻 Code Sample
```ts
useControlledState(undefined, true, () => {})
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | `@react-stately/utils@3.2.0`
| Browser          | Not applicable
| Operating System | Windows

## 🧢 Your Company/Team
*None*

**Comment by LFDanLu** [comment]
@ChocolateLoverRaj Mind making a sandbox to reproduce the issue? I tried here but I don't get a typescript error: https://codesandbox.io/s/distracted-minsky-ufupl?file=/src/App.tsx

**Comment by ChocolateLoverRaj** [comment]
@LFDanLu The reason why your sandbox did not have a typescript error is because the value type implicitly because `number | undefined`. But when calling `useControlledState<number>()`, there is a typescript error. In this sandbox: https://codesandbox.io/s/use-controlled-state-bug-kwy9q?file=/src/App.tsx, `useControlledState<number>()` is used so that `blah` will be `number`, and not `number | undefined`, so that `add()` can be called without any typescript errors or needing to use `blah as number`. If you remove the `<number>` part, there will be a typescript error when doing `add(blah)` because `blah` could be `undefined`.

**Comment by snowystinger** [comment]
Interesting, we do exactly this here
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/numberfield/src/useNumberFieldState.ts#L86
where value is defined https://github.com/adobe/react-spectrum/blob/main/packages/@react-types/numberfield/src/index.d.ts#L25
is optional https://github.com/adobe/react-spectrum/blob/main/packages/@react-types/shared/src/inputs.d.ts#L34

But I'm not seeing a TS error for our repo and I am for codesandbox, which means either newer TS is less forgiving or we have some option set that is allowing this.

**Comment by ChocolateLoverRaj** [comment]
I think it's because of the `strictNullChecks` option. When set to `false`, it lets you use `undefined` as values I think. In the codesandbox, the `strict` option was set to `true` in `tsconfig.json`, which includes the `strictNullChecks` option. You can try turning it on and off to see the error appear / go away in the sandbox.

**Comment by ChocolateLoverRaj** [comment]
The [`tsconfig.json`](https://github.com/adobe/react-spectrum/blob/ac27232f81bc0b9430efbedb154131b7f0d26352/tsconfig.json) file in the packages you linked doesn't have a `strict` or `strictNullChecks` option.

**Comment by LFDanLu** [comment]
@ChocolateLoverRaj thanks for the info, IMO this should be a ok change to make then since it would fix this issue for users w/ `strict` set to true but wouldn't break it for users who don't have `strictNullChecks` enabled. @snowystinger thoughts?

**Comment by snowystinger** [comment]
seems reasonable, thanks for checking on that, with the extra info it sounds like it would be non-breaking

**Comment by ChocolateLoverRaj** [comment]
It's not just the value param that should be optional. The default value and onChange function should also be optional.

Use 1: Not controlled.
```ts
useControlledState(undefined, 10, undefined) // Should be fine
```

Use 2: Controlled.
```ts
useControlledState(5, undefined, () => {}) // Should be fine
```

So in a normal optionally controlled / default value component, the props would be similar to this

```tsx
import { FC, Dispatch } from 'react'

interface Props {
  value?: number
  onChange?: Dispatch<number>
  defaultValue?: number
}

const OptionallyControlledComponent: FC<Props> = props => {
  const { value: propsValue, onChange, defaultValue } = props
  
  // propsValue, defaultValue, and onChange could all be undefined
  const [value, setValue] = useControlledState(propsValue, defaultValue, onChange)

  return <>Something</>
}
```

**Comment by snowystinger** [comment]
yep, default should be able to be undefined, and should just be TS to handle it
the callback however will likely need a check in useControlledState in addition to typings so we don't try to invoke undefined as a function

**Comment by ChocolateLoverRaj** [comment]
@snowystinger It already checks if `onChange` is undefined or not: https://github.com/adobe/react-spectrum/blob/a71a0a7/packages/%40react-stately/utils/src/useControlledState.ts#L34.

**Comment by DaniGuardiola** [comment]
I have this issue too, and I also found this line of code which I believe could be problematic: https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/utils/src/useControlledState.ts#L20

I think `??` is better here to avoid ignoring a perfectly valid `false` or `0` value with the `defaultValue`. Just a heads up in case it was an oversight.

**Comment by DaniGuardiola** [comment]
A workaround in case it's useful to anyone!

In a declaration file, put this:

```typescript
declare module "@react-stately/utils" {
  function useControlledState<T>(
    value?: T,
    defaultValue?: T,
    onChange?: (val: T, ...args: any[]) => void
  ): [T, (val: T | ((prevState: T) => T), ...args: any[]) => void];
}
```
