### ISSUE TITLE
select state.toggle() not working

### ISSUE THREAD

**Issue by deebov** [adobe/react-spectrum#1871]
# 🐛 Bug Report 

`state.toggle()`  doesn't toggle the popover open state if used inside `onClick` of trigger

## 🤔 Expected Behavior

`state.toggle()` should toggle the popover open state

## 😯 Current Behavior

`state.toggle()`  doesn't toggle the popover open state if used inside `onClick` of trigger

## 🔦 Context

We wanted to fix #1870 by not using the press props because we couldn't wait until the react-aria team resolved the issue. But it seems that react-aria's api tied to its ecosystem and not very easy to use one of the apis standalone. And would block us from moving on.

## 💻 Code Sample

https://codesandbox.io/s/suspicious-kepler-gkhtv?file=/src/Select.tsx:1280-1306

**Comment by ktabors** [comment]
Thank you for the codesandbox example. If you add `shouldCloseOnInteractOutside()` to the useOverlay on line 75 that should resolve your issue. I tested this with just a simple return false. It should check if the trigger is the target.
