### ISSUE TITLE
TextField select all text

### ISSUE THREAD

**Issue by aharui** [adobe/react-spectrum#1873]
# 🐛 Bug Report 

Would like a way to programmatically have TextField select all text.

## 🤔 Expected Behavior

Need a way to get a TextField to select all text when it gets focus 

## 😯 Current Behavior

I can use the autoFocus to give the TextField focus, but I can't find a way to get the text to be selected.

## 💁 Possible Solution

I would like a select() method like for HTMLInputElements.

## 🔦 Context

If a UI displays a plain label with an option to rename it.  Upon choosing to rename it, the UI should display a TextField with the label's contents fully selected to make it easier to rename it.

## 💻 Code Sample

See example project.  The node_modules folder was deleted to save space.  Yarn install --force should rebuild node_modules.

[spectrum-textfield.zip](https://github.com/adobe/react-spectrum/files/6429487/spectrum-textfield.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.10.0 |
| Browser          | Chrome |
| Operating System | Mac OSX 10.15.7 Catalina |

## 🧢 Your Company/Team

Adobe/Creative Cloud

**Comment by devongovett** [comment]
I believe this is already possible via refs.

```tsx
function Example() {
  let ref = useRef();
  useLayoutEffect(() => {
    ref.current.select();
  }, []);
  return <TextField ref={ref} />
}
```

Here's an example: https://codesandbox.io/s/nostalgic-architecture-8wo4e?file=/src/App.js
