### ISSUE TITLE
RS3 Table [Alpha] - Cannot set property 'estimatedSize' of undefined

### ISSUE THREAD

**Issue by bhellema** [adobe/react-spectrum#1885]
# 🐛 Bug Report 
Toggling the selectionMode of the Table component causes an TypeError "Cannot set property 'estimatedSize' of undefined.  This issue seems to occur when one of the table rows is selected.

## 🤔 Expected Behavior
After having selected a row, changing the selectionMode should not cause an exception.

## 😯 Current Behavior
I have generated a sample that can reproduce the error.  https://codesandbox.io/s/determined-wilbur-ozcif?file=/src/App2.tsx Once the application loads:
1. select the "show" radio button
2. select the checkbox in the first row
3. click the "hide" radio button

## 💁 Possible Solution
🤷‍♂️

## 🔦 Context
Unable to drive the table dynamically causes our use case to not usable. 

## 💻 Code Sample
https://codesandbox.io/s/determined-wilbur-ozcif?file=/src/App2.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.9.0 |
| react-spectrum/table   | 3.0.0-alpha.11 |
| Browser          | Chrome |
| Operating System | Mac |

## 🧢 Your Company/Team
AEM

**Comment by LFDanLu** [comment]
Just an update, but it seems to be something to do with `overflowMode="wrap"`, digging to see what makes this case special
