### ISSUE TITLE
useMenuTrigger is ignoring `isDisabled` prop?

### ISSUE THREAD

**Issue by chungwu** [adobe/react-spectrum#1887]
# 🐛 Bug Report 

`useMenuTrigger()` does take in an `isDisabled` prop, but it's only used in the returned `onKeyDown()` handler.  The `onPress()` handler seems to ignore it entirely:

```
      onPress(e) {
        if (e.pointerType === 'touch') {
          state.toggle();
        }
      },
```

Should this be ignoring the press when disabled?

## 🤔 Expected Behavior

When isDisabled is passed, menu cannot be triggered.

## 😯 Current Behavior

Menu is always triggered even when disabled.

## 💁 Possible Solution

Don't toggle state when disabled 😛

## 🧢 Your Company/Team

Plasmic

**Comment by LFDanLu** [comment]
🤦 makes sense. Looking at the code, it seems like we've been relying on the user to pass `disabled` to the button? And on the spectrum component side we've been passing `isDisabled` to the trigger button directly, not entirely sure why we don't have `disabled: isDisabled` as a part of `useOverlayTrigger/useMenuTrigger`'s triggerProps...

**Comment by chungwu** [comment]
Oh!  It looks like `onPointerDown` event still gets triggered even when `<button disabled/>` (so even though the button is disabled, the menu still gets shown on click).  I now realize that I should have passed `isDisabled` onto `usePress()` before spreading that onto the `button`, which probably would've prevented the triggering of the overlay... :sweat_smile:

**Comment by pasDamola** [comment]
Hi @chungwu, is this still open?

**Comment by pasDamola** [comment]
Hi @chungwu, I'll like to work on this, has the issue been fixed?

**Comment by chungwu** [comment]
Ah mm I figured out why my overlay was still triggering even when disabled (didn't pass isDisabled on to `usePress()`), but...  I do still think it makes sense for `useMenuTrigger()` to observe / respect the `isDisabled` prop passed to it as well...

**Comment by dannify** [comment]
Closed by https://github.com/adobe/react-spectrum/pull/2479
