### ISSUE TITLE
typescript configuration should be more strict

### ISSUE THREAD

**Issue by alirezamirian** [adobe/react-spectrum#1890]
# 📝 Feedback
[Current typescript configuration](https://github.com/adobe/react-spectrum/blob/master/tsconfig.json) doesn't have any of the `strict` flags. While it might not be the biggest problem for users of @react-spectrum packages, for users of @react-aria and @react-stately, it can cause problems which are mostly related to `strictNullCheck` flag. 
A couple of examples of these problems:
- Return value of [`KeyboardDelegate` methods](https://github.com/adobe/react-spectrum/blob/master/packages/@react-types/shared/src/collections.d.ts#L92-L92) should be nullable.
- In [useControlledState](https://github.com/adobe/react-spectrum/blob/master/packages/@react-stately/utils/src/useControlledState.ts#L16-L16), arguments don't allow `undefined` value while they should #1859

## 🔦 Context

We are using @react-aria and @react-stately to implement our own design system, and we have `strict` flag turned on in our tsconfig.

## Suggestion
I suggest turning `strict` flag on. Or at least `strictNullCheck`. I would be happy to contribute by fixing current errors that would appear by `strict` flag. 
It might be hard to fix all errors at once, because of conflict, PR size, etc. It can be split into a few PRs where the change to strict flag is committed in the last one.

**Comment by LFDanLu** [comment]
This sounds reasonable to me, I'd be interested to see how much would need to be fixed.

**Comment by alirezamirian** [comment]
@LFDanLu 
1673 errors with `strict` set to true. 
1593 errors with only `strictNullCheck` set to true.

**Comment by dannify** [comment]
Having to add `| undefined` (and even `null`?) to pretty much every type (based on the number of errors reported for strictNullCheck) can't be the only way to solve this issue right? This seems a little over the top. Are there no other options for this in typescript?

**Comment by ChocolateLoverRaj** [comment]
@dannify One possible method could be to bulk modify every function and add ` | undefined` to all the parameters. This wouldn't change any internal behavior, but would decrease errors in packages that use the packages.

**Comment by dannify** [comment]
This is something I would be interested in doing. We would need it on all props as well. An option I'd like to explore is to handle this at build time instead of in the source code.

**Comment by ChocolateLoverRaj** [comment]
@dannify I made [a babel plugin that adds `| undefined` to all parameters of exported functions](https://www.npmjs.com/package/babel-plugin-ts-not-strict). Can you try that and see it it can be used during build time?

**Comment by dannify** [comment]
I think this is something we would be able to build on and use. It would also need to include all types, including Object properties, within the component packages and the shared types as well (not just function parameters).

**Comment by ChocolateLoverRaj** [comment]
K I will add object values of functions parameters too.

@dannify What do you mean by
> shared types

**Comment by dannify** [comment]
A lot of our packages use the @react-types package for their types (mostly in React Aria and React Spectrum)
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/textfield/src/useTextField.ts#L13 so we would want to include those as well.

**Comment by ChocolateLoverRaj** [comment]
@dannify So I looked at https://github.com/adobe/react-spectrum/blob/main/packages/%40react-types/textfield/src/index.d.ts and it exports interfaces. So I will make the babel plugin make every property in the interface optional.

**Comment by ChocolateLoverRaj** [comment]
@dannify I released [`v1.2.0`](https://github.com/ChocolateLoverRaj/babel-plugin-ts-not-strict/releases/tag/v1.2.0) of the babel plugin. Can you try it out? Let me know what other modifications the plugin needs to do.

**Comment by dannify** [comment]
Ok great! Next week we have a break but I can take a look when we are back. Thanks for the update

**Comment by unional** [comment]
Another thing to consider is enabling `exactOptionalPropertyTypes`.

**Comment by psirenny** [comment]
> i.e. all optional types should have `| undefined`.

This would make it **much** easier to use the library in projects with `exactOptionalPropertyTypes` enabled. Otherwise, all `undefined` props passed into React Aria Components throw a type error. Workarounds are ugly. e.g.

```tsx
<Checkbox
  {...(isIndeterminate === undefined ? {} : { isIndeterminate })}
>
  …
</Checkbox>
```

**Comment by snowystinger** [comment]
We can consider this after https://github.com/adobe/react-spectrum/issues/3183

Things that would help, a plugin to do it incrementally and a count of how many things exactOptionalPropertyTypes is affecting so we know the effort.

We also accept contributions.

**Comment by unional** [comment]
Essentially it's finding all optional parameters and slapping `undefined` to them. 

If you don't mind putting `undefined` in front, it can be a find and replace of `?: ` => `?: undefined | `

Personally, I would do a find `?: ` and add `| undefined` to the end of the type one by one. 😁

**Comment by snowystinger** [comment]
We have completed turning on strict for TS https://github.com/adobe/react-spectrum/pull/7368
