### ISSUE TITLE
Follow up to selectOnFocus + multiple selection changes in useSelectableCollection

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#1905]
# 🐛 Bug Report 

Followup work after https://github.com/adobe/react-spectrum/pull/1843 is merged/added:

- implement similar behavior for mouse interactions, current pull handles keyboard interactions only (see below bugs for details)
- With selectOnFocus I can tab into the list, but it won't select the item, shift+down arrow then selects "Cut" but "Copy" is left unselected. In order to select it, I'd need to tab in, then down arrow, then up arrow, then shift down arrow
    - Up for debate, perhaps this is desired behavior
- clicking on a selected item (single selection) doesn't unselect the item
     - for multi-select it properly unselects the item
- for multiselect w/ selectOnFocus:
   - clicking on a unselected item w/o shift doesn't unselect previously selected items
- how to support multiselect on mobile? no modifier keys so do we switch modes away from selectOnFocus=true?

## 🧢 Your Company/Team

RSP

**Comment by dannify** [comment]
Needed for highlight functionality in components such as TableView

**Comment by snowystinger** [comment]
> clicking on a selected item (single selection) doesn't unselect the item

I can't reproduce this without disallowEmpty. And of course with disallowEmpty it makes perfect sense.

will update this comment as i work the rest

**Comment by majornista** [comment]
With these new selection modes, there does not appear to be a way to select/deselect multiple non-contiguous items. 

I tend to agree with the sentiment expressed in this Twitter thread: https://twitter.com/codingchaos/status/1383583716623065089
> Also selection following focus is a pretty shitty pattern in general.
>
>“Oh, you selected some items and want to keep them? WELL TOO BAD, SHOULDN’T HAVE USED THE ARROW KEY, THEN”

Why do we have to reproduce UI choices that OSX made twenty years ago, if they suck and exclude keyboard-only users from certain tasks?

Windows 10's File Explorer uses Ctrl+Alt+ArrowUp/ArrowDown to allow a user to navigate between items in the Explorer without losing selection.

**Comment by snowystinger** [comment]
I assume you're only talking about selectOnFocus.
Ctrl+Alt+Up seems reasonable, but I can't tell if that's what you're recommending doing or if you're upset with Windows as well.
