### ISSUE TITLE
Write tests for ListBox/Table to cover selection behavior

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#1906]
# 🙋 Feature Request

We have some gaps in our tests for checking all the various interaction flows for single/multi selection for ListBoxes/Tables. We'll want to write them so that we can make sure nothing breaks when we merge https://github.com/adobe/react-spectrum/pull/1843.

Some tests to write (TODO brainstorm some more/look through current existing tests):
ListBox:
- multi selection with shift key modifier

## 🧢 Your Company/Team

RSP

**Comment by snowystinger** [comment]
This will be closed by https://github.com/adobe/react-spectrum/pull/2026 and https://github.com/adobe/react-spectrum/pull/2013
