### ISSUE TITLE
Wrong maxLength issue between safari and other browsers

### ISSUE THREAD

**Issue by asvny** [adobe/react-spectrum#1907]
# 🐛 Bug Report 
When I provide `maxLength` for Textarea component like 10 ... I am not able to enter more than 10 characters in safari. I think it does double count ( \r \n ). But works perfectly fine in other browsers.
```
        <TextArea
          placeholder="Enter some text"
          onChange={() => {}}
          label="Your text"
          maxLength={10}
        />
```

## 🤔 Expected Behavior

Should allow to enter 10 characters.

## 😯 Current Behavior

Can enter only like 7 characters.

## 💁 Possible Solution

There are some jquery plugins which normalize the behaviour.

## 🔦 Context

Pretty much every Textarea component that depends on maxLength.

## 💻 Code Sample

Observe the behaviour between Chrome and Safari ..

- Keep on pressing enter key.
On Chrome - you can enter 10 times
On Safari.   - only 7 times.

https://codesandbox.io/s/empty-fire-kcwyk?file=/src/App.js 
```
        <TextArea
          placeholder="Enter some text"
          onChange={() => {}}
          label="Your text"
          maxLength={10}
        />
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
Seems like this happens for native textareas as well, there is this webkit bug filed for it: https://bugs.webkit.org/show_bug.cgi?id=154342. Will need to see what possible solutions exist

**Comment by bhavinzwt** [comment]
Is this issue fixed or not?

**Comment by snowystinger** [comment]
From looking at the safari bug, it looks like the answer is no. You're welcome to contribute a PR to address it. Otherwise, you could put the field into a controlled state and count the length of the string in your input yourself.

**Comment by quocvuong2000** [comment]
Has anyone found a solution yet? I'm encountering the same bug.

**Comment by Ahmad-S792** [comment]
Just to comment - Safari 17.1 allows you to enter 10 character, the bug has been fixed in WebKit and released as Safari.

**Comment by snowystinger** [comment]
Thanks for the update, I'll go ahead and close this issue
