### ISSUE TITLE
useSelect example not working on firefox mobile (developer mode)

### ISSUE THREAD

**Issue by lodisy** [adobe/react-spectrum#1930]
# 🐛 Bug Report 

The following example does not work on firefox mobile, it keeps closing the ListBoxPopup.

https://react-spectrum.adobe.com/react-aria/useSelect.html

## 🤔 Expected Behavior

Works normally like on firefox desktop or other browsers

## 😯 Current Behavior

Keeps closing the dropdown.

No errors in console.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.6.0
| Browser          | Firefox Nightly 90.0a1 2021-05-01 / Firefox Developer Edition 84.0b8
| Operating System | macOS Big Sur

**Comment by stefanprobst** [comment]
might be related to https://github.com/adobe/react-spectrum/issues/816

**Comment by LFDanLu** [comment]
yep this looks like the same as #816 as mentioned above, closing this as a dupe as it will be the same core issue.
