### ISSUE TITLE
Remove isReadOnly from Picker

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#1931]
# 🙋 Documentation Request

Remove isReadOnly from Picker since it doesn't do anything right now and the behavior is still being discussed by design

## 🧢 Your Company/Team

RSP

**Comment by LFDanLu** [comment]
This would entail removing isReadOnly from the Picker types. As for behavior if `isReadOnly` is provided by a wrapping Form, perhaps we should disable the Picker and make sure the HiddenSelect isn't disabled so the value is still submitted

**Comment by Patil2099** [comment]
@LFDanLu I would love to work on this issue. Can you guide me a little on this issue ?

**Comment by LFDanLu** [comment]
@Patil2099 Sure! You would need to take a look at https://github.com/adobe/react-spectrum/blob/main/packages/%40react-types/select/src/index.d.ts#L31 and add replace the InputBase extend with a `Omit<InputBase, 'isReadOnly'>`. I think that will suffice for now, you can build the docs locally with `yarn start:docs` to make sure `isReadOnly` is no longer in the Picker doc props

**Comment by Patil2099** [comment]
Thanks @LFDanLu  I will submit a patch soon.
