### ISSUE TITLE
Add `data-test-id` for Table Components to use for Cypress Testing

### ISSUE THREAD

**Issue by fhschan** [adobe/react-spectrum#1943]
# 🙋 Feature Request
In e2e Cypress testing, it suggests to use `data-` for the elements we want to query for as best practices. https://docs.cypress.io/guides/references/best-practices#How-It-Works

It would be great if the Spectrum components allows us to pass in a prop, like `data-test-id` to define the elements we want to test, or automatically add this for us in the base elements with the row/cell key,  so we can run the e2e test with this query anchor.

## 🤔 Expected Behavior
- When running cypress e2e, we can search for a table element through the usage of `data-test-id`

## 😯 Current Behavior
- There is no way for developers to pass in this value manually for Cypress testing purposes through props. 
- I have a sandbox demo running a quick check to make sure the prop passed in is not being addressed to the table elements

Codesandbox demo:
https://codesandbox.io/s/inspiring-thunder-j04l6?file=/src/App.js

Image Example:
![image](https://user-images.githubusercontent.com/22137751/119049518-7fb7db80-b975-11eb-8861-0e324d76443c.png)

From the image, the expected behaviour is that if we have `data-test-id` passed in to the corresponding element (in this case the column header `FOO`, then there should be an attribute in the `div`, which has `data-test-id="cypress-columnHeader-foo"` in it.

## 💁 Possible Solution
- Allow user to pass this prop in to populate this value themselves
- Automatically add a `data-test-id` attribute to the column headers, rows and values based on it's corresponding key passed in/

## 🔦 Context
- In AEP platform library, the current table that is implemented there has this anchor point. 

## 💻 Examples
![image](https://user-images.githubusercontent.com/22137751/119053477-f5727600-b97a-11eb-93f0-d3295277de54.png)

## 🧢 Your Company/Team
AEP - Saruman

**Comment by fhschan** [comment]
CC: @jluyau @matthewdeutsch

**Comment by dannify** [comment]
Hi @fhschan 
We support passing `data-test-id` to the top level element of a component. From there you can use semantics to find the elements needed in your tests. Hopefully this page on testing will help you https://react-spectrum.adobe.com/react-spectrum/testing.html

**Comment by fhschan** [comment]
Hi @dannify - Thanks for the response!

Yes, I found that we can pass in at the `Table` component level, but our existing Cypress cases also has the ability to define it at the row and cell level.  Was wondering if this implementation is possible as well?

Understand that we can query for a cell by string, (eg. `getByLabelText` in the case of testing library, or `get` for cypress).  In the event where we want to ensure a specific value is in a specific row, which is what we have for the test cases, having the ability to have `data-test-id` prop to the row element would help significantly to find the exact row we are looking for.

eg. A dataset with unique ids, if we can map the row to that id (given that this unique id is hidden visually on the table), we can simply confirm that the row has this data, and then we can query the cells within the row.

**Comment by fhschan** [comment]
Please disregard! Understand that RS will only support parent level prop for this `data-test-id`. Thanks all!
