### ISSUE TITLE
Strings "am" and "pm" are not localized in date and time fields

### ISSUE THREAD

**Issue by scpiper22** [adobe/react-spectrum#1947]
# 🐛 Bug Report 

[FRA/DEU] Strings "am" and "pm" are not localized in date and time fields 

## 🤔 Expected Behavior

These strings should be localized.

## 😯 Current Behavior

Steps To Reproduce:

## 💁 Possible Solution

Strings to be externalized so that they can be localized

## 🔦 Context

Note:
1. This issue occurs on FRA/DEU, not on JPN.
2. This issue occurs on following scenarios:

## 🧢 Your Company/Team

Dx Globalization Team

**Comment by LFDanLu** [comment]
I took a look at the link you provided and followed the jira repro steps, looks like this is v2 Datepicker. Could you file a issue here: https://git.corp.adobe.com/React/react-spectrum-v2/issues?
