### ISSUE TITLE
Event bubbling with dnd

### ISSUE THREAD

**Issue by pra7eek** [adobe/react-spectrum#1952]
# 🐛 Bug Report 

When there are nested droppable elements with spectrum dnd, only the child element event should be propagated and the parent elements' events should be stopped by default.

## 🤔 Expected Behavior

`onDrop` should get executed only for the element where it is dropped.

## 😯 Current Behavior

`onDrop` is being executed for all the parent/droppable elements.

## 💁 Possible Solution

Stopping the event propagation by default

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.10.0
| Browser          | Chrome 90.0.4430.212 
| Operating System | MacOS

**Comment by dannify** [comment]
Hey @pra7eek 
Thanks for adding this, I think it makes sense to stop propagation by default as suggested. We will probably have a look at it next week sometime.
