### ISSUE TITLE
Add more chromatic stories

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#1957]
# 🙋 Feature Request

- See what components are missing chromatic stories
  - Compile a list for posterity:
  - Pick up a couple to write stories for (choose ones that have a bunch of different styles?)

EDIT: 
List of packages that don't have chromatic stories at all:
- Color components
- Combobox
- Form (maybe this one doesn’t need chromatic?)
- Icon (maybe this one doesn’t need chromatic?)
- Label
- Listbox
- Listview
- Menu
- Overlay
- Table

## 🧢 Your Company/Team

RSP

**Comment by snowystinger** [comment]
Make sure to write them in CSF :)
