### ISSUE TITLE
Manage focus in docs popover breadcrumbs

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#1961]
# 🐛 Bug Report 

When a link within a popover changes the contents of the popover, focus will be lost to the document.body, because the element that had focus will be removed from the DOM and replaced with new content.
There was prior work done on this, but we had to change some CSS to do it, we should figure out a way that doesn't require any CSS changes to the component. So this is really about managing the focus in our docs, not necessarily about Breadcrumbs themselves.
https://github.com/adobe/react-spectrum/pull/728

## 🤔 Expected Behavior

Focus should not go to the body.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
Perhaps related to https://github.com/facebook/react/issues/12363 as well, FocusScope might not be containing focus since onBlur isn't being fired on unmount
