### ISSUE TITLE
Table header alignment is 1px off from column contents

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#1995]
# 🐛 Bug Report 

<img width="459" alt="image" src="https://user-images.githubusercontent.com/19409/121276524-adf94e80-c883-11eb-80a0-47f08b1fcb84.png">

## 🤔 Expected Behavior

Either the table header should move 1px to the right or the contents should move 1px to the left.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
Reasonably sure this is due to the border on the table body but no border around the header, maybe we can add a transparent border to it?
