### ISSUE TITLE
Add originalEvent to usePress and useHover event handlers

### ISSUE THREAD

**Issue by DeyLak** [adobe/react-spectrum#1998]
# 🙋 Feature Request

It would be great to have access to `originalEvent` in `HoverEvent`, returned by `useHover` and `PressEvent` from `usePress`

## 🤔 Expected Behavior
 
For some press events, I want to have access to more detailed info about, where and how they happened.

## 😯 Current Behavior

I discovered, that now there is no way, I can access mouse coordinates from `usePress` or `useFocus` hook, even if they exist.

## 💁 Possible Solution

I think, the best way to solve this is to give the user access to the originalEvent, that you already have in your codebase, so the user can decide himself, what to do with it and, potentially, make use of your `PointerType` enum. This looks like a minor and also a powerful change to me.

## 🔦 Context

I was trying to make a material ui like ripple behaviour, using your great library. Ripples can be in 2 forms: 
1. Fixed position to their container
![image](https://user-images.githubusercontent.com/1286563/121389307-f03e9080-c954-11eb-9f84-1d7c7e563d62.png)

2. Position of the mouse click
![image](https://user-images.githubusercontent.com/1286563/121389195-d3a25880-c954-11eb-8a58-560b0b1c536d.png)

I think, that your `usePress` + `useHover` hook are great abstractions for this case, it even covers different ripple scenarios: keyboard press, mouse, etc. Having access to mouse coordinates (if they exist) will work like a charm for this task.

**Comment by snowystinger** [comment]
Hey! so this is very much related to https://github.com/adobe/react-spectrum/issues/1860
passing the entire event object through is not something we intend to do, however, maybe we could talk about adding position data to usePress/useHover
or maybe we make a different hook to track that

assuming you're using our hooks and not our components, you could possibly also add your own handlers (through mergeProps) to handle position tracking

**Comment by DeyLak** [comment]
@snowystinger Thanks for a quick response! I see your concerns, so I closed my PR. I still think, though, it would be very useful at least to proxy coords info from events, or maybe even something else, like mouse buttons, etc. I believe, a compromise, based on specs can be made here.

For those, who may come here later, I leave my simplified workaround, proposed by @snowystinger here:

```ts
type ContainerElementProps = React.HTMLProps<HTMLDivElement>

interface PointerCoords {
  clientX: number;
  clientY: number;
}

export const useRipples = () => {
  // useRef to store coords between events
  const pointerCoordsRef = useRef<PointerCoords>();

  ...

  const { pressProps } = usePress({
    ...
    onPressEnd: () => {
      // Clear coords on press end, so other events won't receive them next time
      pointerCoordsRef.current = undefined;
      ...
    },
  })
  const { hoverProps } = useHover({...})
  
  const rippleContainerProps: ContainerElementProps = mergeProps(
    // Pass additional handler to save coords on target events
    {
      onPointerDown = e => {
        pointerCoordsRef.current = {
        clientX: e.clientX,
        clientY: e.clientY,
      };
    },
    hoverProps,
    pressProps,
  );
  
  return {
    rippleContainerProps,
  };
})
```

**Comment by snowystinger** [comment]
closing in favor of this https://github.com/adobe/react-spectrum/issues/2031
we've discussed it in the team and think this is a valid issue to solve by adding position data to our hooks
