### ISSUE TITLE
Data attributes on Tabs don't get passed through to DOM element

### ISSUE THREAD

**Issue by Aaronius** [adobe/react-spectrum#2002]
# 🐛 Bug Report 
If you add a data attribute as a prop on the Tabs component, the attribute doesn't flow through to any DOM element.

## 🤔 Expected Behavior
The data attribute would show up on the primary DOM element for Tabs.

## 😯 Current Behavior
The data attribute does not show up on the primary DOM element for Tabs.

## 💁 Possible Solution
I assume pass through certain props to the DOM element like is [done with other elements](https://github.com/adobe/react-spectrum/blob/4b75cbe84157bcd735f7097a41f397d2c5c58543/packages/%40react-spectrum/well/src/Well.tsx#L35).

## 🔦 Context
We have a functional test that finds a particular tab and clicks it. We use `[role="tab"]` as part of our selector to identify a particular tab, but we also want to incorporate a `data` attribute that's been added to the ancestor Tabs DOM element so we can make sure we're searching for the tab within a specific Tabs instance. This is particularly useful in the case that there are multiple Tabs instances on the page. In our case, there's only one instance of Tabs, so it's easy for us to work around this particular issue, but I figured Tabs should be consistent with other components which seem to support data attributes.

## 💻 Code Sample
Open https://codesandbox.io/s/tabs-with-data-attribute-ni4di?file=/src/App.js
In the codesandbox console, run `document.querySelector("[data-foo]")` and notice that no DOM elements are found when there should be a DOM element found.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | Tabs component 3.0.0-rc.0
| Browser          | Chrome
| Operating System | Mac Catalina

## 🧢 Your Company/Team
Adobe Experience Platform Data Collection

**Comment by snowystinger** [comment]
Related https://github.com/adobe/react-spectrum/issues/1943
I think Tabs will always have a root element, so this should be ok

**Comment by LFDanLu** [comment]
Yep, looks like we just need to `filterDOMProps(otherProps)` and pass it to the Tabs wrapper div
