### ISSUE TITLE
`useModal()` usage doesn't apply `aria-hidden` to elements

### ISSUE THREAD

**Issue by MoistCode** [adobe/react-spectrum#2003]
# 🐛 Bug Report 

Following the example shown in the [`useDialog()` example](https://react-spectrum.adobe.com/react-aria/useDialog.html#example) and the [`useOverlayTrigger()` example](https://react-spectrum.adobe.com/react-aria/useOverlayTrigger.html), I noticed that the `aria-hidden` attributes are not being applied to elements outside of the dialog/overlay as they do on the aforementioned example pages.

## 🤔 Expected Behavior

Using `useModal()` in combination with `<OverlayContainer>` should apply `aria-hidden` to the correct elements to hide them from screen readers on mount.

## 😯 Current Behavior

`aria-hidden` attributes are not being applied to elements outside of the dialog/overlay as they do on the aforementioned example pages.

This [code sandbox](https://codesandbox.io/s/suspicious-pare-uv2qo?file=/src/Popover.js) applies the [`useOverlayTrigger()`](https://react-spectrum.adobe.com/react-aria/useOverlayTrigger.html) example. 

## 💁 Possible Solution

Not sure quite yet but will update this issue if I come across anything,.

## 🔦 Context

I'm using the combination of the examples from `useModal()` and `useOverlayTrigger()` to create a `usePopoverDialog()` that returns a bunch of props to spread into a `<PopoverDialog>` component as well as trigger props to spread onto the triggering element. The rest of the functionality seems to work so far except for this. 

## 💻 Code Sample

[Code Sandbox](https://codesandbox.io/s/suspicious-pare-uv2qo?file=/src/Popover.js) applies the [`useOverlayTrigger()`](https://react-spectrum.adobe.com/react-aria/useOverlayTrigger.html) example. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/dialog  | 3.1.3 |
| @react-aria/overlays  | 3.6.3 |
| react | 17.0.2 |
| react-dom | 17.0.2 |
| Browser | Chrome 91.0.4472.77 (Official Build) (x86_64) |
| Operating System | macOS Big Sur 11.3.1 |

**Comment by snowystinger** [comment]
I'm looking at the docs for useDialog that you linked to. I'm seeing everything get `aria-hidden` 
![Screen Shot 2021-06-09 at 4 28 06 PM](https://user-images.githubusercontent.com/698229/121442076-c169ef80-c93f-11eb-8b3a-c45141fa73a6.png)

did you try the note? last paragraph right before the example itself
Note: useModal only hides content within parent OverlayProvider components. However, if you have additional content in your application outside any OverlayProvider, then you should use the @react-aria/aria-modal-polyfill package to ensure that this content is hidden while modals are open as well. See the watchModals docs for more information.

**Comment by MoistCode** [comment]
Looks like I actually missed where the `aria-hidden` was suppose to be added to. I'll close this. Thanks!
