### ISSUE TITLE
Heavy line under selected tab doesn't update when tab label is changing

### ISSUE THREAD

**Issue by Aaronius** [adobe/react-spectrum#2004]
# 🐛 Bug Report 
If you change the label of tab, the heavy line underneath the selected tab doesn't update in position or width to accommodate the new label.

## 🤔 Expected Behavior
The heavy line under the selected tab would always be the same width of selected tab and always the correct position.

## 😯 Current Behavior
The width and position of the heavy line doesn't change.

## 🔦 Context
We have tabs whose labels can dynamically change.

## 💻 Code Sample
https://codesandbox.io/s/tabs-with-changing-label-w41cc?file=/src/App.js
Change the value in the text field. Notice the width of the heavy line doesn't change. Select the Empire tab. Change the value in the text field some more. Notice the position of the heavy line doesn't change.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0.0-rc.0 of Tabs
| Browser          | Chrome
| Operating System | Mac

## 🧢 Your Company/Team
Adobe Experience Platform Data Collection

**Comment by snowystinger** [comment]
Yep, looks like a bug

**Comment by snowystinger** [comment]
For now it's enough to add the missing dependency to the the right useEffect by passing through the children to https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/tabs/src/Tabs.tsx#L290

**Comment by ktabors** [comment]
This is probably related. If there is a font loading issue it seems that the tabs don't update where there should be a resize. See this story where the component loads, font loading is delayed, and once the font loads and is applied to the page, the selected tab indicator doesn't line up. https://git.corp.adobe.com/pages/taborski/rsp-storybook/?path=/story/v3-components-tabs--font-change
![image](https://user-images.githubusercontent.com/309540/123843213-81ef4d00-d8c6-11eb-9272-b7c204310172.png)

**Comment by yanandcoffee** [comment]
I would like to take a look at this.
