### ISSUE TITLE
Tooltip click and long hover interaction 

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum#2008]
# 🐛 Bug Report 

While testing ActionGroup, the `with tooltip` story I noticed that clicking on a button a leaving the hover seems to keep the timer running because I move the mouse pointer away from hover and back over the button quickly and the tooltip immediately pops up.

## 🤔 Expected Behavior

After clicking the tooltip doesn't open.
Quickly mousing away and hovering again should start the tooltip show timer.

## 😯 Current Behavior

Tooltip immediately shows up if there was a long hover after clicking.

## 💁 Possible Solution

Wondering if the timer is running even when the tooltip shouldn't show.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | master branch pr build |
| Browser          | Firefox |
| Operating System | OSX |

## 🧢 Your Company/Team
RSP

**Comment by Tris-909** [comment]
Can I start working on this as my first PR ?

**Comment by snowystinger** [comment]
Please do! Here's the guide for contributions https://react-spectrum.adobe.com/contribute.html

**Comment by pavolmarc** [comment]
Hi, is anybody working on this right now? I would be interested.

**Comment by snowystinger** [comment]
I cannot reproduce on the latest, appears to have been fixed. https://codesandbox.io/p/sandbox/awesome-liskov-h3x38k
