### ISSUE TITLE
ComboBox - Menu direction does not flip correctly

### ISSUE THREAD

**Issue by eyao06** [adobe/react-spectrum#2024]
### Expected Behaviour
- ComboBox menu will appear on top when attempting to open it while having it very low in the browser

### Actual Behaviour

1. ComboBox menu appears on bottom when attempting to open it while having it very low in the browser
2. While the ComboBox is low on the browser and menu is still open on the bottom, when the Chevron is double clicked, the menu will go up

#### Steps to Reproduce
1. Goto [https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#example](https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#example)
2. Locate the first example 
3. Scroll down or up on ur browser till the ComboBox is near the bottom of the browser
4. Click the ComboBox's Chevron to open the menu
5. You will notice that the menu opens at the bottom
6. While the menu is opened, double click the Chevron in the ComboBox again
7. You will notice the menu going on top of the ComboBox now

#### Sample Code that illustrates the problem
- See the example here [https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#example](https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#example)

**Comment by LFDanLu** [comment]
Confirmed on my end, think we can do something similar to Picker: https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/picker/src/Picker.tsx#L105-L111 to handle it. I have distant recollection that this was attempted in the past, but I'm not 100% sure will have to dig
