### ISSUE TITLE
pasting into text inputs contained within modals/dialogs with usePreventScroll isn't working on iOS/Safari

### ISSUE THREAD

**Issue by sheldonj** [adobe/react-spectrum#2030]
# 🐛 Bug Report 

The following versions I've been able to determined are effected:

- Issue confirmed using safari on iOS 14.6
- Issue confirmed using Chrome on iOS 14.6

[I've provided a short loom demo here demonstrating the issue:](https://www.loom.com/share/778d525f458a4d739873355ad888390a)

Essentially iOS users can't past text into inputs that are contained within Modals/Dialogs when the usePreventScroll hook is activated.

## 🤔 Expected Behavior

Users should be able to copy and paste text into text inputs contained in Modals when using the built in iOS tools.

## 😯 Current Behavior

Users can't paste text into inputs when usePreventScroll is active.

## 💁 Possible Solution

[I've identified the following lines as the culprit!](https://github.com/adobe/react-spectrum/blob/6924b49d773d8d276ded1bf21dcb0af37e700cfb/packages/%40react-aria/overlays/src/usePreventScroll.ts#L135)

## 🔦 Context

It looks like this issue was introduced in the following pull request:
[https://github.com/adobe/react-spectrum/pull/1290](https://github.com/adobe/react-spectrum/pull/1290)

@devongovett - Maybe you have some insight on this.

## 💻 Code Sample

I have created a small working example of the issue using an example posted on your documentation pages:

[https://codesandbox.io/s/condescending-leavitt-sosbp?file=/public/index.html](https://codesandbox.io/s/condescending-leavitt-sosbp?file=/public/index.html)

You can test this on your iOS device here:
[https://sosbp.csb.app/](https://sosbp.csb.app/)

**Comment by sheldonj** [comment]
What would be helpful in the short term would be to further understand the context of why these lines were added when they were.  In our case we need users to be able to paste some critical information into a modal.

I don't mind working on a resolution for this and submit a PR, I just need to better understand what regressions I need to track if I work on this.

Any thoughts or guidance would be appreciated.

**Comment by LFDanLu** [comment]
@sheldonj  If I remember correctly, that line was to stop iOS Safari from scrolling the whole page when tapping on an input within a Modal or Tray. More specifically, I believe that previously this would cause our mobile ComboBox tray to scroll partially off screen when the input within it was tapped. As an aside, this also doesn't seem to be a problem in our Spectrum Dialogs which is kinda weird.

Incidentally, I can't seem to reproduce the behavior above locally on a test iPhone hence my reliance on memory here heh. If you do pick this up and work on a fix, you can also look at the "long content" story in our Storybook for regression testing. It's there that I see some behavioral changes with the iOS 14 (like how I am unable to navigate from the Dialog's top input to the bottom input via the iOS's virtual keyboard next/previous buttons)

**Comment by LFDanLu** [comment]
suggestion from @devongovett: only trigger that touch end code if the input is not focused
