### ISSUE TITLE
ComboBox - menuTrigger="focus" prop keeps the menu open when clicking the ComboBox label

### ISSUE THREAD

**Issue by eyao06** [adobe/react-spectrum#2033]
# 🐛 Bug Report 

- When using the menuTrigger="focus" prop for the ComboBox and while having the menu open, when we click on the label of the ComboBox, the menu will close and re-open immediately 
- This can be seen in the storybook example [https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#trigger-options](https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#trigger-options)

## 🤔 Expected Behavior

- While having the using the prop and having the menu open, when we click on the label the menu should close and not re-open

## 😯 Current Behavior

- While having the using the prop and having the menu open, when we click on the label the menu close and immediately re-opens

- [https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#trigger-options](https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#trigger-options)

## 💻 Code Sample

- Found the issue in storybook [https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#trigger-options](https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#trigger-options)

**Comment by LFDanLu** [comment]
Might be a bit tricky since clicking on the label will blur the combobox and refocus it (native behavior of label + input), but may be able to suppress this if we detect that the menu is open and the blur target is the label

**Comment by LFDanLu** [comment]
Talked with team, deemed this as expected behavior.
