### ISSUE TITLE
Table stories with async loading will continue to load more

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#2035]
# 🐛 Bug Report 

The API fails after it's loaded everything possible, then it continues to try to load more even though the API call failed.
There is also an interesting case when showing scrollbars. When the load more spinner appears, it increases the size bringing up scrollbars which take up space which causes a recalculation which causes the scrollbars to go away and it starts all over again. See in Chrome in https://reactspectrum.blob.core.windows.net/reactspectrum/01e0504f3182021dfe146204704448abbe955336/storybook/index.html?path=/story/tableview--loads-more-on-scroll-when-contentsize-height-rect-height-2

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
The scroll bar behavior stuff comes from https://github.com/adobe/react-spectrum/commit/4ffc6447a8f8b22e316383997e1d0b31d8602a56. 

The loadMore spam is probably something we should handle (perhaps in useAsyncList? or maybe something in TableView)

**Comment by snowystinger** [comment]
Fixed in latest on main
