### ISSUE TITLE
FocusScope: containment broken when active & last focusable element becomes disabled

### ISSUE THREAD

**Issue by RubenStoesser** [adobe/react-spectrum#2038]
# 🐛 Bug Report 

This is quite the edge-case but I noticed the focus can move outside of a FocusScope containment of when the last focusable element in that scope is the active element and then becomes disabled which automatically removes its focus.

## 🤔 Expected Behavior

Focus should stay contained within the scope when pressing <kbd>Tab</kbd> after the active element becomes disabled.

## 😯 Current Behavior

Pressing <kbd>Tab</kbd> after the last focusable element in a scope becomes disabled (the item must be the focused element at that point) will move focus outside of the containment to the first focusable element in the document.

Once focus moves back into the FocusScope containment will work correctly again.

When first pressing <kbd>Shift</kbd> + <kbd>Tab</kbd> and then tabbing past the disabled item also works as usual.

## 💻 Code Sample

Codepen showing the issue: https://codesandbox.io/s/affectionate-black-j2jg0?file=/src/App.js

To reproduce:
1. Open dialog
2. Set focus on "Click to disable" button
3. Press <kbd>Enter</kbd> to disable the button
4. Press <kbd>Tab</kbd>, focus will move outside of the modal to the "some other button" button.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria/focus   |  3.4.0
| Browser          | 91.0.4472.77
| Operating System | Windows 10

**Comment by LFDanLu** [comment]
I believe this is similar/related to https://github.com/adobe/react-spectrum/issues/874. As mentioned in that issue, there are some open questions regarding where focus should move exactly when the last focused element is unmounted (or disabled in this case).
