### ISSUE TITLE
FocusScope and Tippy.js do not love each other

### ISSUE THREAD

**Issue by j-lefloch** [adobe/react-spectrum#2052]
# 🐛 Bug Report 

FocusScope stops working as expected if there is a Tippy tooltip triggered somewhere else in the page.

## 🤔 Expected Behavior

FocusScope should work as expected 

## 😯 Current Behavior

https://user-images.githubusercontent.com/86349269/123075306-68f32180-d418-11eb-89c4-12b408188977.mp4

## 💻 Code Sample

https://codesandbox.io/s/xenodochial-pine-ht2cs?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.7.1
| @tippyjs/react   | 4.2.5
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
Hey there! Thanks for opening an issue, unfortunately we're not familiar with Tippy. Would you be willing to debug this a bit further and provide some more information to help us fix it?

**Comment by snowystinger** [comment]
Closing stale
