### ISSUE TITLE
unable to resolve dependency tree while using react@17.0.2

### ISSUE THREAD

**Issue by Newbie012** [adobe/react-spectrum#2054]
# 🐛 Bug Report 

Getting an ERESOLVE error on node 15 (due to incompatible peer deps):

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-aria/checkbox@3.2.2
npm ERR!   node_modules/@react-aria/checkbox
npm ERR!     @react-aria/checkbox@"3.2.2" from the root project
npm ERR!   47 more (@react-aria/focus, @react-aria/radio, ...)
```

## 🤔 Expected Behavior

The packages should support react 17.0.2 as well

## 😯 Current Behavior

It doesn't (see logs above).

## 💁 Possible Solution

use `--legacy-peer-deps` (not recommended).

## 🔦 Context

Trying to npm install

**Comment by snowystinger** [comment]
According to npm's semver calculator, that range should match 17.0.2 https://semver.npmjs.com/
I think you've found a bug in node 15

**Comment by Newbie012** [comment]
@snowystinger I think the bug is in the calculator and not in node 15. see [node-semver](https://github.com/npm/node-semver#prerelease-tags):

> If a version has a prerelease tag (for example, 1.2.3-alpha.3) then it will only be allowed to satisfy comparator sets if at least one comparator with the same [major, minor, patch] tuple also has a prerelease tag.
>
> For example, the range >1.2.3-alpha.3 would be allowed to match the version 1.2.3-alpha.7, but it would not be satisfied by 3.4.5-alpha.9, even though 3.4.5-alpha.9 is technically "greater than" 1.2.3-alpha.3 according to the SemVer sort rules. The version range only accepts prerelease tags on the 1.2.3 version. The version 3.4.5 would satisfy the range, because it does not have a prerelease flag, and 3.4.5 is greater than 1.2.3-alpha.7.

**Comment by snowystinger** [comment]
Here's an issue that discusses it https://github.com/npm/node-semver/issues/297, and https://semver.npmjs.com/ uses node-semver to run. It's doing the extra matching because it's running in loose mode.
I'm not sure if you can set that for your install, I didn't look that far. To be more compliant, we should be able to just add `|| ^17.0.0` to every `react` and `react-dom` dependency, but hopefully that thread gets you through this faster than waiting an entire release cycle. I'll see if anyone on the team has any other ideas, it's odd that this hasn't come up before, 17 has been out of alpha for a while now. Though most people probably skipped Node 15 and just went to 16, have you tried it on 16? https://nodejs.org/en/about/releases/ and I recommend checking out `nvm` if you haven't already for easy node version management https://github.com/nvm-sh/nvm

**Comment by Newbie012** [comment]
It doesn't seem to work on Node 16 (npm 7.18.1)  as well

**Comment by snowystinger** [comment]
Hey, I'm unable to reproduce this in node 14 or 16. The steps I followed were:
1. nvm use 16
2. npx create-react-app my-app
3. cd my-app
4. npm install "@adobe/react-spectrum"

I see no errors from the install

Could you provide more about your steps and settings?

**Comment by Newbie012** [comment]
Try to `npm install @react-aria/checkbox`

**Comment by snowystinger** [comment]
I changed step 4 to be `npm install @react-aria/checkbox` and I'm still installing everything just fine with React 17.0.2
Is there any other information you can provide?
I also tried deleting node_modules and the package-lock after cd'ing into my-app

Did you try with the steps above out of curiosity? or are you just relying on your project? I'm curious if a clean slate doesn't work on your machine.

**Comment by Newbie012** [comment]
Can you share your package.json deps? I'm not sure cra comes with react 17.0.2 by default. I will try to do the steps you made when I'll arrive home

**Comment by snowystinger** [comment]
this is what CRA generates
```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.8.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.1.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by Newbie012** [comment]
I have no idea why suddently it started working.... 😅 closing it for now. If it will occur again, I will let you know
