### ISSUE TITLE
`NumberParser` tries to build invalid regexes and throws at runtime

### ISSUE THREAD

**Issue by dubzzz** [adobe/react-spectrum#2065]
# 🐛 Bug Report 

`NumberParser` can create invalid regexes leading to runtime crashes.

## 🤔 Expected Behavior

`NumberParser` should properly generate its internal regexes.

## 😯 Current Behavior

Regex seems invalid.

## 🔦 Context

I initially was trying to suggest a Pull Request to add property based tests on the algorithm dealing with reversing `Intl.NumberFormat`. So I did a first iteration of it on [runkit](https://runkit.com/dubzzz/60da17b1fb733a001cd93508) then [commited it on my fork](https://github.com/dubzzz/react-spectrum/commit/e2043a932d6a65dd7192705a1bf7fdf44e8b1db5#diff-7bf83599612e94f27f7a4a9ce5457ccc8c68b7ea557c05b16b02e2ea6515e426).

_This first property based test is pretty promising as it found this bug plus some others were the parsing fails and produces NaN while the string is fully valid._

## 💻 Code Sample

```js
const { NumberParser } = require("@internationalized/number");
const parser = new NumberParser("fr-FR",{"style":"currency","currency":"USD","currencyDisplay":"name"});
parser.parse('') // throws:
// SyntaxError: Invalid regular expression: /dollars des États\-Unis|dollar des États\-Unis| |[\p{White_Space}]/: Invalid escape
```
See it on runkit: https://runkit.com/dubzzz/60da5678a56323001a06dfac

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          | node 14.17.0 |
| Operating System | Windows |

## 🧢 Your Company/Team

N.A.

**Comment by snowystinger** [comment]
thanks so much for reporting this! it would appear that our `escapeRegex` is to blame, maybe this would be a better `return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');`
https://github.com/adobe/react-spectrum/blob/main/packages/%40internationalized/number/src/NumberParser.ts#L239
Property based testing sounds great, look forward to your PR!

**Comment by dubzzz** [comment]
> Property based testing sounds great, look forward to your PR!

I'll definitely open a PR to suggest it as a way to find bugs earlier in the development process. For the moment, the tests would be red as they fall into the issue described in this PR. But I can, at least for the moment, update the test to avoid this case.

**Comment by dubzzz** [comment]
I just opened a first PR to suggest the idea of Property Based Testing.
