### ISSUE TITLE
New component: ActionMenu

### ISSUE THREAD

**Issue by dannify** [adobe/react-spectrum#2079]
The ActionMenu is a combination of an ActionButton and a Menu/MenuTrigger.  It is designed to be a convenience component and therefore will only offer a subset of the props available if someone was to build their own. 

The icon for the ActionButton will be hardcoded to the More icon (3 dots). `aria-label` on the ActionButton should have a default translated string “More actions” but also the ability to provide a custom `aria-label` via props.

### Example
``` jsx
<ActionMenu aria-label="More editing options" onAction={(key) => alert(key)}>
  <Item key="view">View</Item>
  <Item key="copy">Copy</Item>
  <Item key="delete">Delete</Item>
</ActionMenu>
```
### Content
Here is a codesandbox of the basic internals of the component
https://codesandbox.io/s/action-menu-lpifm

``` jsx
<MenuTrigger>
  <ActionButton>
    <More />
  </ActionButton>
  <Menu>
    // children
  </Menu>
</MenuTrigger> 
```

### API
``` tsx
interface ActionMenuProps<T> extends AriaLabelingProps {
  children: ItemElement<T> | ItemElement<T>[] | ItemRenderer<T>
  align?: Alignment,  // from shared types
  direction?: 'bottom' | 'top' | 'left' | 'right' | 'start' | 'end',
  shouldFlip?: boolean,
  isDisabled?: boolean,
  isQuiet?: boolean,
  autoFocus?: boolean,
  onAction?: (key: Key) => void 
}
```
Tests and stories to be included.

## 🧢 Your Company/Team

RSP

**Comment by tomsontom** [comment]
Is there a timeline until when this needs to be implemented? I would like to give it a try unless someone is already working on it.

**Comment by devongovett** [comment]
Feel free! We are on a company summer break this week but I'll be around if you have any questions.

**Comment by tomsontom** [comment]
@devongovett  @dannify  in what package should the ActionMenu live? One could argue for `button` and `menu` although I more lean towards `button` but before starting my journey we should clarify where to put it.

**Comment by devongovett** [comment]
Good question. I'm thinking menu, mainly because I don't want the button package to depend on the menu package. The other way around somehow seems better, I guess because menu already depends on so many things.
