### ISSUE TITLE
Standard card component

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#2080]
# 🙋 Feature Request

Cards are containers for information about an item in a collection. They usually appear in a `CardView`, but can also appear standalone. There are many different card types in Spectrum. This ticket is for the implementation of [standard cards](https://spectrum.adobe.com/page/cards/) (vertical orientation only).

![image](https://user-images.githubusercontent.com/19409/124190604-68d9ce00-da77-11eb-97e2-a9c886257392.png)

## Slots

Quiet cards accept children in several different slots, to which the appropriate styling is automatically applied.

- `image` = preview → applied by the `<Image>` component
- `illustration` = preview → e.g. for generic file/folder icons
- `avatar` → applied by the `<Avatar>` component, or via `<Image slot="avatar">` for custom non-avatar images (e.g. product logo in this position. See #1345
- `heading` = title → Required. Applied by the `<Heading>` component
- `content` = description → Required. Applied by the `<Content>` component
- `detail` → `<Text slot="detail">`
- `actionmenu` → applied by the `<ActionMenu>` component. See #2079
- `footer` → applied by the `<Footer>` component

All slots are optional except a title and description.

## Example

This is an example of a card using every possible slot.

```tsx
<Card>
  <Image src="preview.png" />
  <Avatar src="avatar.png" />
  <Heading>Title</Heading>
  <Text slot="detail">PNG</Text>
  <Content>Description</Content>
  <ActionMenu>
    <Item>Action 1</Item>
    <Item>Action 2</Item>
  </ActionMenu>
  <Footer>
    <Badge>Badge</Badge>
    <Button>Something</Button>
  </Footer>
</Card>
```

## API

```ts
interface SpectrumCardProps extends AriaLabelingProps {
  children: ReactNode,
  isQuiet?: boolean,
  // standard cards are not applicable in gallery layout
  layout?: 'grid' | 'waterfall' | 'gallery',
  size?: 'S' | 'M' | 'L',
  // to be implemented later
  orientation?: 'horizontal' | 'vertical'
}
```

## Accessibility and DOM structure

The `<article>` element should be used as the container for cards. When used within a CardView, the card will become a `gridcell`, but that does not need to be handled here.

- The `aria-labelledby` attribute of the article element should point to the id of the `<Heading>` element.
- The `aria-describedby` attribute of the article element should point to the id of the `<Content>` element.

This can be implemented with the `useSlotId()` hook.

In addition, the img element used for the preview should have `alt=""` by default to mark it as decorative. Users can override this by setting the `alt` prop of the `<Image>` component themselves.

```html
<article aria-labelledby="title-id" aria-describedby="description-id">
  <img src="preview.png" alt="" />
  <img src="avatar.png" alt="" />
  <h3 id="title-id">Title</h3>
  <span>Detail</span>
  <section id="description-id">
    Content / description
  </section>
  <footer>
    footer
  </footer>
</article>
```

## 🧢 Your Company/Team

RSP

**Comment by snowystinger** [comment]
Closed in https://github.com/adobe/react-spectrum/pull/2209
