### ISSUE TITLE
Horizontal card component

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#2081]
# 🙋 Feature Request

Cards are containers for information about an item in a collection. They usually appear in a `CardView`, but can also appear standalone. There are many different card types in Spectrum. This ticket is for the implementation of [standard cards](https://spectrum.adobe.com/page/cards/) (horizontal orientation only).

<img width="469" alt="image" src="https://user-images.githubusercontent.com/19409/124191332-80658680-da78-11eb-9597-0a2fd1919d1a.png">

## Slots

Quiet cards accept children in several different slots, to which the appropriate styling is automatically applied.

- `image` = preview → applied by the `<Image>` component
- `illustration` = preview → e.g. for generic file/folder icons
- `heading` = title → Required. Applied by the `<Heading>` component
- `content` = description → Required. Applied by the `<Content>` component
- `actionmenu` → applied by the `<ActionMenu>` component. See #2079

All slots are optional except a title and description.

## Example

This is an example of a card using every possible slot.

```tsx
<Card>
  <Image src="preview.png" />
  <Heading>Title</Heading>
  <Content>Description</Content>
  <ActionMenu>
    <Item>Action 1</Item>
    <Item>Action 2</Item>
  </ActionMenu>
</Card>
```

## API

```ts
interface SpectrumCardProps extends AriaLabelingProps {
  children: ReactNode,
  isQuiet?: boolean,
  // horizontal cards are only applicable to grid layout
  layout?: 'grid' | 'waterfall' | 'gallery',
  size?: 'S' | 'M' | 'L',
  orientation?: 'horizontal' | 'vertical'
}
```

## Accessibility and DOM structure

The `<article>` element should be used as the container for cards. When used within a CardView, the card will become a `gridcell`, but that does not need to be handled here.

- The `aria-labelledby` attribute of the article element should point to the id of the `<Heading>` element.
- The `aria-describedby` attribute of the article element should point to the id of the `<Content>` element.

This can be implemented with the `useSlotId()` hook.

In addition, the img element used for the preview should have `alt=""` by default to mark it as decorative. Users can override this by setting the `alt` prop of the `<Image>` component themselves.

```html
<article aria-labelledby="title-id" aria-describedby="description-id">
  <img src="preview.png" alt="" />
  <h3 id="title-id">Title</h3>
  <section id="description-id">
    Content / description
  </section>
</article>
```

## 🧢 Your Company/Team

RSP

**Comment by tomsontom** [comment]
After having successfully completed #2079 who is has been the prereq for that component I'd like to give this more complex one a try unless someone else already works on it.

**Comment by snowystinger** [comment]
Sure, thanks for volunteering. Fair warning, we will be working on the other card types this sprint and some changes may come your way as a result. We will add any additional information to this issue as it comes up. You'll probably have to add slots to `ActionMenu`. If you haven't already, I'd read https://react-spectrum.adobe.com/react-spectrum/layout.html#slots and you can take a lot at components that make use of this and the RFC https://github.com/adobe/react-spectrum/search?q=Slots as they aren't heavily documented for outside use.

**Comment by tomsontom** [comment]
@snowystinger you mean you work on #2080 ? If that is the case then I don't think it makes a lot of sense for me to work on that because the work will overlap. This leads to the question: Why is there #2081 and #2080 at all?

**Comment by dannify** [comment]
Hey @tomsontom, sorry, I created this confusion. You are correct, there is significant overlap in all of the Card component tickets as they are all variants of the same component. The different tickets were created to mostly track the different design and types of Cards. The team is just about to start working on creating this new component (only happened today!) but I am sure there will be plenty of work to come out of our initial implementation.
We love having you contribute so please let us know if you see anything else you are interested in working on. Sorry again for the mix up.

**Comment by tomsontom** [comment]
No worries - i find some other issue/component I can contribute to

**Comment by snowystinger** [comment]
closed in https://github.com/adobe/react-spectrum/pull/2209
