### ISSUE TITLE
CardView component

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#2083]
# 🙋 Feature Request

`CardView` is a collection component that displays a list of Cards in various layouts including grid, waterfall (vertical masonry), and gallery (horizontal masonry). It supports selection, keyboard navigation, and async loading / infinite scrolling

## Example

This is a basic example showing a dynamic collection of cards. Static collections with Card as children should also be supported.

```tsx
import {CardView, WaterfallLayout} from '@adobe/react-spectrum';

<CardView layout={WaterfallLayout} items={items}>
  {item => 
    <Card>
      ...
    </Card>
  }
</CardView>
```

## Layouts

The `@react-spectrum/card` package should export classes for each of the layouts. These can be passed to the `CardView` `layout` prop which will handle instantiating it with the default options, or an instance can be constructed with custom options and passed in by the user.

```tsx
let layout = useMemo(() => new WaterfallLayout({...}), []);
<CardView layout={layout} items={items}>
  {item => 
    <Card>
      ...
    </Card>
  }
</CardView>
```

The implementations of these layouts should be mostly copied from v2 and modified to match the new Virtualizer and KeyboardDelegate API.

## Stately 

`CardView` should reuse the `useListState` and `useGridState` hooks similar to how `ListView` works. The `Card` component should implement the `getCollectionNode` API similar to `Item` or `Row` so that it can be used inside a collection component.

This should result in a grid state object that can be used with the ARIA grid hooks.

## Aria

`CardView` should use `useGrid` and associated hooks to implement the ARIA grid pattern. Each card is represented as a row in the grid with a single cell inside. The keyboard delegate will need to be overridden and passed into `useGrid`. Each layout object should implement the keyboard delegate interface to provide spatial navigation via the arrow keys.

## Spectrum

`CardView` will need to coordinate several props with the layout. For instance, the `cardSize` and `cardOrientation` props will affect the layout, and the layout may also affect the card type (e.g. gallery layout only supports quiet cards). A context should be used to pass the props that affect the cards (e.g. `cardSize`  and `isQuiet`) to each `Card` component.

Selection should be managed by `useListState`. The state should be passed through a context to the `Card` components. If present (i.e. the `Card` is inside a `CardView`), and selection is enabled, then the `Card` should display a selection checkbox.

In addition, when inside a `CardView`, some of the ARIA semantics of the cards need to be overridden. It should become a `row` with a `gridcell` inside. In order to do this, we can map each item in the collection to an internal `Card` component that accepts additional DOM props that the public Card API does not. Essentially, the exported `Card` component would accept props for a standalone card and render one of the internal cards, and `getCollectionNode` would map the card to an item which later would be mapped to an internal card by `CardView`.

## API

```ts
interface LayoutConstructor {
  new (): Layout;
}

interface CardViewProps<T> extends CollectionBase<T>, MultipleSelectionProps, AsyncLoadable {
  layout: LayoutConstructor | Layout,
  cardSize?: 'S' | 'M' | 'L',
  cardOrientation?: 'horizontal' | 'vertical',
  isQuiet?: boolean,
  renderEmptyState?: () => ReactNode
}
```

## 🧢 Your Company/Team

RSP

**Comment by sargismarkosyan** [comment]
Hey team, is this in the near-time roadmap for this?

**Comment by devongovett** [comment]
Done in S2.
