### ISSUE TITLE
TableView: if selection, too much whitespace between checkbox and first cell

### ISSUE THREAD

**Issue by carolframpton** [adobe/react-spectrum#2089]
# 🐛 Bug Report 

If using the v3 TableView with selection there seems to be excess whitespace between the checkbox and the first cell. More than I am seeing in https://spectrum.corp.adobe.com/page/table/#Selection.

## 🤔 Expected Behavior

less white space around checkbox particularly between checkbox and first cell

## 😯 Current Behavior

 Here is one of our many tables which illustrates my point.

![image](https://user-images.githubusercontent.com/71789937/124321116-271a5780-db4b-11eb-8500-fa756389c227.png)

## 🔦 Context

Our app uses tables extensively. While this example doesn't show it they tend to be packed with columns and we don't have whitespace to spare.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Adobe Admin Console

**Comment by LFDanLu** [comment]
Compared the current TableView with the XD files on Spectrum/Spectrum contribution site, confirmed that the current TableView has more whitespace between the checkbox and the first cell. In the XD file the spacing is 24 px, but ours has a extra 8 px of spacing
