### ISSUE TITLE
Picker on mobile Firefox opens list of options only on long press

### ISSUE THREAD

**Issue by PacoSoftwerft** [adobe/react-spectrum#2098]
# 🐛 Bug Report 

The Picker component **opens** the collapsible list of options **only on long click/touch**.

Example: https://react-spectrum.adobe.com/react-spectrum/Picker.html

Firefox on mobile device or desktop **with enabled touch simulation**
width must be 700px or less

## 🤔 Expected Behavior

When I touch or click the list should open.
I should not need to hold down.

## 😯 Current Behavior

On a normal click one just sees a flicker.
For a millisecond `aria-hidden="true"` is added to the div and `_is-actice-xyz` to the button but both are directly removed.

The long click/touch opens the dialog box of the browser, too (very annoying).

## 🔦 Context

I would like to select an option from a list.

## 💻 Code Sample

https://react-spectrum.adobe.com/react-spectrum/Picker.html

all of them

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum/utils   |  3.6.1
| Browser          | Firefox 89.0.2 (64-Bit) / 89.1.
| Operating System | Kubuntu 20.04 / Android 10

**Comment by stefanprobst** [comment]
this might be related: #816

**Comment by PacoSoftwerft** [comment]
yes, thank you this is a duplicate of #816
