### ISSUE TITLE
Support a whiteSpace prop on View

### ISSUE THREAD

**Issue by Aaronius** [adobe/react-spectrum#2105]
# 🙋 Feature Request
I have View instances where I'd like to use `white-space: nowrap` so that text doesn't wrap. Currently I have to either assign a class to the View using `UNSAFE_className` or create a child div that has a class that applies the style. It would be nice to have a `whiteSpace` prop to forego this need.

## 🤔 Expected Behavior
Prop doesn't exist.

## 😯 Current Behavior
Prop exists.

## 💁 Possible Solution
Add a `whiteSpace` prop to View.

## 🔦 Context
Currently I have to either assign a class to the View using `UNSAFE_className` or create a child div that has a class that applies the style. It would be nice to have a `whiteSpace` prop to forego this need.

## 🧢 Your Company/Team
Adobe/Adobe Experience Platform Data Collection

**Comment by Aaronius** [comment]
BTW, I don't feel strongly about this and I realize it may be part of a slippery slope of endless properties, but I'm just expressing my desire just so you're aware and in case it fits the general strategy.

**Comment by devongovett** [comment]
I think this would make more sense on `<Text>` and the other typography components, once we have them.

**Comment by dannify** [comment]
This work will not be introduced in this version but will be possible in Spectrum 2 components since you wil be able to sue normal html elements. Closing for now.
