### ISSUE TITLE
TypeError: Cannot destructure property 'scale' of 'Object(...)(...)' as it is null.

### ISSUE THREAD

**Issue by Sanan4li** [adobe/react-spectrum#2110]
# 🐛 Bug Report 

I just installed the package using NPM. I copied the code from the docs and run the project. It says `TypeError: Cannot destructure property 'scale' of 'Object(...)(...)' as it is null.`
## 🤔 Expected Behavior
The example should work fine with no error.

## 😯 Current Behavior
getting this error on the screen
![image](https://user-images.githubusercontent.com/45590156/125797645-44cdfcd4-62e0-4478-914a-a3e0ab24cf54.png)

## 💻 Code Sample
![image](https://user-images.githubusercontent.com/45590156/125798257-5cf27596-1ed1-4c4b-9ff2-25bf9062d9a7.png)

## 🌍 Your Environment
Windows 10

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
Ah, you're missing a Provider wrapping that https://react-spectrum.adobe.com/react-spectrum/Provider.html
you can import it in the same line as the others

**Comment by Sanan4li** [comment]
> Ah, you're missing a Provider wrapping that https://react-spectrum.adobe.com/react-spectrum/Provider.html
> you can import it in the same line as the others
> I can see that might be confusing as we didn't reference it in that doc, nor do we in other pages

Thank you for your quick reply. As you said it is not mentioned in the docs, I think this [Provider](https://react-spectrum.adobe.com/react-spectrum/Provider.html) page should be referred in every component like [Combobox](https://react-spectrum.adobe.com/react-spectrum/ComboBox.html) so that beginners always know what's the very first step to use these awesome components.
