### ISSUE TITLE
Esc on modal with open ComboBox should close ComboBox, not modal

### ISSUE THREAD

**Issue by MBernardAdobe** [adobe/react-spectrum#2111]
# 🐛 Bug Report 

When using ComboBox on a DialogContainer fullscreen modal, when the ComboBox is open and I press the Esc key, the entire modal closes instead of the ComboBox menu closing.

## 🤔 Expected Behavior

I'd expect, if there's an open ComboBox menu, the first press of Esc should close only that, not the whole modal

## 💁 Possible Solution

You'd suggested the fix would be to "stop propagation on the keyboard event within combobox itself"

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.4.0
| Browser          | Chrome 
| Operating System | Mac

## 🧢 Your Company/Team

AEP

**Comment by LFDanLu** [comment]
@MBernardAdobe I can't seem to reproduce this with this sandbox: https://codesandbox.io/s/sweet-bas-rf54o?file=/src/App.js. Mind sharing a code snippet?

**Comment by MBernardAdobe** [comment]
My apologies: I hadn't realized React-Spectrum V2 also had a Combobox component and this codebase is using the V2 version. I'd forgotten to close this ticket but it's likely not a real issue.
