### ISSUE TITLE
ActionGroup component errors out

### ISSUE THREAD

**Issue by conormdowney** [adobe/react-spectrum#2116]
So Im just trying to get a simple ActionGroup (https://react-spectrum.adobe.com/react-spectrum/ActionGroup.html) with overflow enabled to work.

So I added the following code to my component: 

```const menu = (<ActionGroup overflowMode="collapse" maxWidth={250}>
    <Item key="edit">
      <Draw />
      <Text>Edit</Text>
    </Item>
    <Item key="copy">
      <Copy />
      <Text>Copy</Text>
    </Item>
    <Item key="delete">
      <Delete />
      <Text>Delete</Text>
    </Item>
    <Item key="move">
      <Move />
      <Text>Move</Text>
    </Item>
    <Item key="duplicate">
      <Duplicate />
      <Text>Duplicate</Text>
    </Item>
  </ActionGroup>)
```
Then i added menu to my jsx. But it is giving me an error when it tries to render. The error happens in the actiongroup code. it is expecting there to be a theme but there its not finding one. The prevContext below is null
```
let prevContext = useProvider();
  let prevColorScheme = prevContext && prevContext.colorScheme;
  let prevBreakpoints = prevContext && prevContext.breakpoints;
  let {
    theme = prevContext && prevContext.theme,
    defaultColorScheme
  } = props; // Hooks must always be called.

  let autoColorScheme = $ae471163e3fb08c2a281b1d3e1120f94$export$useColorScheme(theme, defaultColorScheme);
```

The code is in 

`node_modules/@react-spectrum/actiongroup/node_modules/@react-spectrum/provider/dist/main.js`

Now that im typing it out i dont know why thereis a node modules inside the actiogroup node module....??
I used the install command from here: https://www.npmjs.com/package/@react-spectrum/actiongroup
`npm i @react-spectrum/actiongroup`

**Comment by snowystinger** [comment]
Linking to discussion https://github.com/adobe/react-spectrum/discussions/2115 and closing to be handled there. Reopen if we determine a bug exists
