### ISSUE TITLE
Broken navigation for nested `FocusScope`s

### ISSUE THREAD

**Issue by Rafal2228** [adobe/react-spectrum#2120]
# 🐛 Bug Report 

Tab navigation doesn't work as expected when we nest `FocusScope` component, the workaround for this issue seems to be using `Portal` to place elements in different subtrees, but ideally there should be a way of nesting `FocusScope` components within each other.

## 🤔 Expected Behavior

When I display `FocusScope` based component with `contain` property inside another `FocusScope` I would expect the internal one to be the only one active at a time

## 😯 Current Behavior

Currently two nested `FocusScope`s fight each other and cause focus jumping behavior

## 💁 Possible Solution

We could modify how `useFocusContainment` callback checks if element is in scope, to not take certain subtree's into account. It would probably require us checking this with `TreeWalker` instead of simple `contains`

## 🔦 Context

It breaks ability to nest dialogs within each other without usage of `Portal`

## 💻 Code Sample

https://codesandbox.io/s/sharp-fast-8q7wj?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  3.5
| Browser          | any
| Operating System | any

**Comment by lukerhoads** [comment]
Hello @Rafal2228 , new to the codebase but would like to help.

This happens for example, in the sandbox, you remove the MaybePortal and then add a couple rows. When tabbing through the rows it skips inputs. 

I think this would involve re calling `useLayoutEffect` to continue adding the nested elements to the active scope. Maybe a modified version. Everything in `useFocusContainment` looks pretty good to my untrained eye, modifications would be in initializing `scopeRef` correctly. Will continue looking into this

**Comment by Rafal2228** [comment]
@lukerhoads thanks for taking a look 👍 

I'm not entirely sure if you got my intent here correctly. I'm not trying to put more elements into the same `FocusScope`. The issue I'm facing comes from the fact that currently it's not possible to nest them (or nest any element that uses `useFocusContainment` for that matter).

The workaround which I found for this is to place `FocusScope`s next to each other with `Portal`, but I believe it should be possible to nest them without any additional actions. Take a look at this diagram - when I display nested `FocusScope` I would expect to be only able to focus between the `green` elements:

![intent (1)](https://user-images.githubusercontent.com/9198051/126315682-eb71b20d-52d9-4195-82c8-2c091f527d5a.png)

**Comment by lukerhoads** [comment]
Definitely had some trouble understanding. Thanks for clarifying. 

Alright. I think looping through the scopeRef.current in useFocusContainment and popping FocusScopes would be good if we knew how to identify FocusScopes as HTMLElements. Trying to figure that out right now.

Going to mention this issue in a PR
