### ISSUE TITLE
Use `aria-required` instead of `required` on form components that support the `isRequired` prop

### ISSUE THREAD

**Issue by paulkenney** [adobe/react-spectrum#2123]
# 🙋 Feature Request
All form field components should use `aria-required="true"` instead of `required`.

## 🤔 Expected Behavior
The `Checkbox`, `Radio`, and `RadioGroup` components, when provided a truthy `isRequired` prop value, should add `aria-required="true"` to their rendered form field DOM elements.

## 😯 Current Behavior
These components add `required` to their DOM elements if `isRequired` is truthy. When submitting a form using one of these components and it does not have a value (leaving the 'required' validation rule unsatisfied) the browser provides it own popup error message indicating a field needs a value. Additionally, the browser does not fire the `onSubmit` event that is used to trigger custom form validation.

## 💁 Possible Solution
Since the logic for handling `isRequired` is already in place for these components, and there are other components that correctly use `aria-required`, it seems that the solution is to replace one attribute with another.

## 🔦 Context
When implementing custom validation logic and error messages, we make use of the `onSubmit` event to trigger custom validation logic. We also make use of the `isRequired` prop to ensure that the required indicator (asterisk following provided label) is displayed. Since we are providing our own custom validation and error messages the native 'required field' tooltips create a distinct user experience that differs from that we wish to present.

## 💻 Examples
Here is an example of native validation on Checkbox after clicking submit button:

```
<Checkbox isRequired>I agree</Checkbox>
```

![image](https://user-images.githubusercontent.com/2644630/126215617-b3f7ee29-e70b-4f4b-ac6c-418231397bb5.png)

## 🧢 Your Company/Team
Adobe/Quarry

**Comment by dannify** [comment]
I think we should remove required from Radio and have RadioGroup manage it. Also should Switch be in this list?

**Comment by stefanprobst** [comment]
can this be solved with [`<form novalidate>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-novalidate)?

**Comment by dannify** [comment]
> can this be solved with [`<form novalidate>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-novalidate)?

Yes it definitely could but I think it would be nice to fix the inconsistencies in form components.

**Comment by paulkenney** [comment]
`Radio` does not have an `isRequired` prop of its own, and instead gets its value from its parent `RadioGroup`. The fix is for the `RadioGroup` to no longer provide this value to its children so that the `useRadio` hook (invoked inside `Radio`) does not include it in the props it returns.
