### ISSUE TITLE
Table column sort icon gets cut off when the column width is too narrow

### ISSUE THREAD

**Issue by richiepreece** [adobe/react-spectrum#2133]
# 🐛 Bug Report 

When a column gets to be too small, the sort arrow gets cut off.

## 🤔 Expected Behavior

Sort arrow should not be hidden

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/1470437/126390297-655a484c-f43a-49cc-a990-982050988880.png)

As you can see, the arrow is only half visible

## 💁 Possible Solution

We have solved this with the following client-side css, which seems to fix it:

```
[role='columnheader'] {
	min-width: 115px;
}
```
## 🌍 Your Environment

We are using the table through `@quarry/inventory beta.1`

## 🧢 Your Company/Team

Adobe Analysis Workspace

**Comment by LFDanLu** [comment]
What version of RSP TableView are you using? Does the [`minWidth` prop](https://react-spectrum.adobe.com/react-spectrum/TableView.html#column-widths) work for you?

**Comment by richiepreece** [comment]
It looks like `@quarry/inventory` is using `"@react-spectrum/table": "3.0.0-beta.0",` in my package-lock. I can try the minWidth prop, but I can only assume this issue would require every user of spectrum table to use the same min-width prop to avoid having the arrow hide.
