### ISSUE TITLE
Word wrap in picker menu

### ISSUE THREAD

**Issue by michayou** [adobe/react-spectrum#2144]
# 🙋 Feature Request

Items in the picker menu currently do not wrap well, breaking up words in the middle.  It would look much better if they word wrapped correctly.

## 🤔 Expected Behavior

Instead of breaking up "a very long pick
er item like this", it should break up "a very long
picker item like this"

## 😯 Current Behavior

Picker menus wrap by breaking up words in the middle

## 💻 Examples

You can see this by creating a picker with a very long menu item

<img width="221" alt="Screen Shot 2021-07-26 at 9 43 54 AM" src="https://user-images.githubusercontent.com/698229/127026968-66438346-9bc4-43f6-a294-6b4ad697945a.png">

## 🧢 Your Company/Team

Adobe Report Builder for CJA

**Comment by michayou** [comment]
I've been asked to leave a codesandbox tat shows this issue:  https://codesandbox.io/s/lingering-violet-fy5i0?file=/src/App.js

Just in case, here is the picker code:
```
      <Picker label="Choose frequency">
        <Item key="rarely">Short</Item>
        <Item key="sometimes">Normal</Item>
        <Item key="always">This item is very long and word wraps poorly</Item>
      </Picker>
```

**Comment by LFDanLu** [comment]
We should use wordbreak normal, overflow-wrap: break-word
