### ISSUE TITLE
Unmounting ComboBox within 1/2 second when in loading state doesn't properly clean up timers

### ISSUE THREAD

**Issue by Aaronius** [adobe/react-spectrum#2154]
# 🐛 Bug Report 
The ComboBox sets state after a half second when `loadingState` is `loading` or `filtering`. Even if the ComboBox unmounts before the half second is over, the half second timers will continue running and try to set state when they're done.

## 🤔 Expected Behavior
Proper cleanup of timers on unmount. No warning.

## 😯 Current Behavior
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at ComboBoxInput (https://9xevj.csb.app/node_modules/@react-spectrum/combobox/dist/module.js:662:17)
    at div
    at $fbef05647f50ff84b1b0bb6029f8e$var$Field (https://9xevj.csb.app/node_modules/@react-spectrum/label/dist/module.js:173:15)
    at ComboBoxBase (https://9xevj.csb.app/node_modules/@react-spectrum/combobox/dist/module.js:569:8)
    at $a1e2444f979a947af6adfa139e4b9220$var$ComboBox (https://9xevj.csb.app/node_modules/@react-spectrum/combobox/dist/module.js:556:51)
```

## 💁 Possible Solution
Clear the timers on unmount in [this useEffect](https://github.com/adobe/react-spectrum/blob/b5b930fab4e7b61ab227a749ac00749a77a18ec8/packages/%40react-spectrum/combobox/src/ComboBox.tsx#L251-L274).

## 💻 Code Sample
https://codesandbox.io/s/combobox-with-default-based-on-first-loaded-item-forked-9xevj?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | ComboBox@3.0.0-rc.0
| Browser          | Chrome
| Operating System | Mac

## 🧢 Your Company/Team
Adobe Experience Platform Data Collection

**Comment by LFDanLu** [comment]
Thanks for catching this, verified locally.
