### ISSUE TITLE
Avoid useMemo when it's no needed

### ISSUE THREAD

**Issue by viniciusdacal** [adobe/react-spectrum#2157]
# 🙋 Documentation Request

Congrats on this lib, just found out about it and it's really nice.

I just noticed there's an useMemo in the docs, when it's actually not needed. I know it doesn't seem like a big thing, but it spreads a miss use of that hook.

The example I'm referring to:

```jsx
function Example() {
  let [value, setValue] = React.useState(parseColor('#e73623'));
  let isValid = React.useMemo(() => {
    return value && value.red && value.red > value.green && value.red > value.blue;
  }, [value]);

  return (
    <ColorField
      validationState={isValid ? 'valid' : 'invalid'}
      value={value}
      onChange={setValue}
      label="Red colors"
    />
  );
}
```

In the case above, the result of the useMemo, is a boolean, so it doesn't matter if we recreate that value or not. If it was a dependency of a useEffect or a useCallback for example, it wouldn't impact.

Also, the validation done inside the function is trivial, and just the allocation of an useMemo, would cost more to performance, than the actual validation.

Additionally, it would be interesting to use optional chaining, to simplify the logic.

```jsx
function Example() {
  let [value, setValue] = React.useState(parseColor('#e73623'));
  let isValid = value?.red && value.red > value.green && value.red > value.blue;

  return (
    <ColorField
      validationState={isValid ? 'valid' : 'invalid'}
      value={value}
      onChange={setValue}
      label="Red colors"
    />
  );
}
```

ps. I don't know how complex parseColor logic is supposed to be, but when using a function to calculate the initial state, it could give a preference to the callback syntax, to avoid calling that function over and over.

```jsx
  let [value, setValue] = React.useState(() => parseColor('#e73623'));
```

Let me know what you think. If you agree, I can open a PR.

Best!

**Comment by snowystinger** [comment]
Both seem reasonable to me.
I'm not sure the isValid logic is right anyways, it looks like it should really be
```
let isValid = value?.red && value.red > value.green && value.green > value.blue;
```
transitive property would say red > blue and we'd also be asserting that green > blue which we don't currently check

**Comment by ryo-manba** [comment]
hey @snowystinger ,
Seems to be resolved by this [PR](https://github.com/adobe/react-spectrum/pull/5343/files#diff-111e044a501bdd1e42bfad288cd715a5acedc851220788d6105469a4161084f0L115-L118).
This code does not exist in [docs](https://react-spectrum.adobe.com/react-spectrum/ColorField.html#validation).

**Comment by snowystinger** [comment]
Thanks @ryo-manba i'll close it out
