### ISSUE TITLE
useSelect selecting with spacebar buggy in firefox

### ISSUE THREAD

**Issue by hayes** [adobe/react-spectrum#2171]
# 🐛 Bug Report 

Using the examples in the official documentation, if you use the keyboard to focus the select box, and use the down arrow key to open an option, hitting space will select the item, and close the dialog, but will also immediately re-open the select menu. 

## 🤔 Expected Behavior

The option menu should stay closed after making a selection using the space bar

## 😯 Current Behavior

This video was taken on OSX in firefox 89.0.2, and the same behavior does NOT happen in chrome.

https://user-images.githubusercontent.com/816527/127543125-42b9a017-7ceb-497b-af58-1daec8baa246.mov

## 🔦 Context

Building out a simple select box

## 💻 Code Sample

Examples on https://react-spectrum.adobe.com/react-aria/useSelect.html all reproduce this issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | @react-aria/select": "^3.4.0"
| Browser          | Firefox 89.0.27 
| Operating System | osx 10.15.7

**Comment by LFDanLu** [comment]
Reproduced locally, looks like we are receiving a virtual click event after selecting the option via space that triggers the following `onClick` in [usePress](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/interactions/src/usePress.ts#L236). For some reason, `state.ignoreClickAfterPress` is occasionally `false` [here](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/interactions/src/usePress.ts#L249), specifically only when the menu is opened via the arrow keys or click but not by space...

Will need to figure out where this virtual click is coming from and if we can stop it, or if we can make `state.ignoreClickAfterPress` more statble

**Comment by devongovett** [comment]
I can't reproduce in the current version.
