### ISSUE TITLE
Chrome warning about window.navigator.userAgent and window.navigator.platform access

### ISSUE THREAD

**Issue by curran** [adobe/react-spectrum#2189]
# 🐛 Bug Report 

After adopting `react-aria` (specifically `"@react-aria/button": "^3.3.2"`) in my codebase, I notice that Chrome shows a warning about accessing `window.navigator.userAgent` and `window.navigator.platform`.

## 🤔 Expected Behavior

The warning should not appear.

## 😯 Current Behavior

Chrome (Version 92.0.4515.107 (Official Build) (64-bit)) shows the following warning:

![image](https://user-images.githubusercontent.com/68416/127885874-640e3cc3-a7cb-4b00-ad16-10153ee17b1f.png)

Full text:

Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced. To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData. Note that for performance reasons, only the first access to one of the properties is shown. 1 source client.js:1 Learn more: [User-Agent String Reduction](https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html)

## 💁 Possible Solution

Research options described in [Update on User-Agent String Reduction in Chrome](https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html). One viable options may be to migrate to [`navigator.userAgentData`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData).

Access of the offending fields appears localized to https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/utils/src/platform.ts.

## 🌍 Your Environment

`"@react-aria/button": "^3.3.2"`

Chrome (Version 92.0.4515.107 (Official Build) (64-bit)) 

Ubuntu Linux

**Comment by LFDanLu** [comment]
Thanks for bringing this up, definitely something we should address.

**Comment by curran** [comment]
Just wondering, are there any automated tests that cover the functionality around user agent and platform detection? If someone were to take a stab at a solution for this issue, how to verify correctness? Thanks!

**Comment by snowystinger** [comment]
There are definitely some tests that mock it, so you'd have some coverage. How much and how extensive those particular tests are, I'm not sure, but you can always add more if you find some missing.
I'd maybe start with a GitHub search of the repo for "navigator" to see the scope of what this would entail.
