### ISSUE TITLE
Documentation for ActionMenu

### ISSUE THREAD

**Issue by dannify** [adobe/react-spectrum#2199]
ActionMenu is a new component that needs documentation

**Comment by tomsontom** [comment]
As I've contributed that component I could write that doc but I'm not a native speaker so not sure if it causes more work for you to correct my texts than to write it yourself

**Comment by dannify** [comment]
Thank you so much for the offer. Normally this would be great community addition however because this component is pretty much ready to go, it is likely we will not need a prerelease. Because of that, someone from the team will be working on these docs this week so that they can be ready in time.
