### ISSUE TITLE
[NumberField] Setting null to value does not reset to blank state

### ISSUE THREAD

**Issue by fhschan** [adobe/react-spectrum#2216]
# 🐛 Bug Report 
When using the `NumberField` component, if the implementor wants to use a controlled state to control the value of `NumberField`, passing in `null` does not reset this component to the initial state.

## 🤔 Expected Behavior
- Passing null should reset to the empty state for this component

## 😯 Current Behavior
- Passing null sets the value to 0.

## 💁 Possible Solution
Update https://github.com/adobe/react-spectrum/blob/main/packages/@react-stately/numberfield/src/useNumberFieldState.ts#L91 so it retains the empty state if the component is used in a controlled state.

## 🔦 Context
- If we have external logic using react-hook-form to control this component, we want to be able to reset the `NumberField` component to its initial case. A use case for example, for form validation. If user resets the form and we have a parent `Form` component that holds all the values of the form components, we want to reset it to the original empty value. 
- Currently, by passing in `null` to `value` prop would result in 0, which can be a valid value and does not tell the implementor that user has not filled this form from looking at the value. If we pass in `undefined`, it looks like the `NumberField` retains the previous value. (eg. user enters 5, then hits reset button which results in passing `undefined` to the `value` prop, the value shown is 5 still) 

## 💻 Code Sample
https://codesandbox.io/s/nice-moore-ochpe?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.13.0
| Browser          | Chrome Version 92.0.4515.107
| Operating System | macOS BigSur v11.4

## 🧢 Your Company/Team

Adobe/quarry

**Comment by fhschan** [comment]
@LFDanLu  - sorry I couldn't directly assign to you. Pinging you in comment and leaving a comment in our Slack thread as well. Thanks again!

**Comment by LFDanLu** [comment]
Another line of interest: https://github.com/adobe/react-spectrum/blob/main/packages/@react-stately/numberfield/src/useNumberFieldState.ts#L108
IMO we should check if `numberValue == null` and call `setInputValue` with to "" in that case perhaps

**Comment by LFDanLu** [comment]
We'll also need to check for other areas where we do a similar NaN check and account for those as well.

**Comment by hennessyevan** [comment]
Is there a workaround for this?

**Comment by LFDanLu** [comment]
At the moment none that I know of, short of using something like [patch package](https://www.npmjs.com/package/patch-package) to patch the bug locally.

**Comment by msdrigg** [comment]
This is also an issue with the datePicker component see https://github.com/adobe/react-spectrum/issues/3187. I don't think there is an equivalent `NaN` workaround for this component either.

**Comment by lishichengyan** [comment]
I noticed the previous way to update a controlled value is via a useEffect hook but now it's changed to
`
  if (!Object.is(numberValue, prevValue.current) || locale !== prevLocale.current || formatOptions !== prevFormatOptions.current) {
    setInputValue(format(numberValue));
    // ...
  }
`
Looks like we can solve the problem by simply adding a sanity check in [L97](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/numberfield/src/useNumberFieldState.ts#:~:text=let%20format%20%3D%20useCallback((value%3A%20number)%20%3D%3E%20isNaN(value)%20%3F%20%27%27%20%3A%20formatter.format(value)%2C%20%5Bformatter%5D)%3B)
`
let format = useCallback((value: number) => isNaN(value) ? '' : formatter.format(value), [formatter]);
`
===>
`
let format = useCallback((value: number) => (isNaN(value) || value === null) ? '' : formatter.format(value), [formatter]);
`
