### ISSUE TITLE
Combobox: Change 'No results' dropdown message based on the loading state

### ISSUE THREAD

**Issue by pra7eek** [adobe/react-spectrum#2226]
# 🙋 Feature Request

Currently 'No results' dropdown message is not customizable even when there is an API call in progress. If the API call is taking more time, it can confuse the end user. 

## 🤔 Expected Behavior

Should show different messages based on the loading state. "No results" when there is no API call or API returns empty data. "Please wait/Loading/etc." when there is an API call in progress.

## 😯 Current Behavior

Shows 'No results' every time when component receives an empty item list.

## 💁 Possible Solution

There can be 2 approaches to solve this, either allow component to receive a message prop so that developer can maintain it conditionally. Or, as these strings are localised, component itself can update the message to something else while it is loading.

## 💻 Examples

https://user-images.githubusercontent.com/4252162/129669621-be0e2f78-baf1-401f-8efb-bb3a1054cde4.mov

**Comment by dannify** [comment]
The loading indicator is there to show that results are loading. It is visible without opening the menu to make it obvious that loading is happening.

**Comment by pra7eek** [comment]
Yes it shows the loader, but it would be better if the message is changed along with the loading/searching state.
