### ISSUE TITLE
TableView with hideColumn as last column triggers horizontal scrollbar (Firefox)

### ISSUE THREAD

**Issue by jluyau** [adobe/react-spectrum#2229]
# 🐛 Bug Report 

## 🤔 Expected Behavior

No horizontal scroll bar if enough space to render columns/cells

## 😯 Current Behavior

If the last column in TableView is configured with `hideHeader`, a horizontal scrollbar will display and enable scrolling for a few pixels, even though there's enough space to render the cells. Only happens in Firefox. 

## 🔦 Context

Table with a hideHeader column as the last column (for action buttons).

## 💻 Code Sample

https://codesandbox.io/s/crazy-perlman-b84vt?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.13
| @react-spectrum/table | 3.0.0-rc.1
| Browser          | Firefox 91.0.1
| Operating System | MacOS Catalina 10.15.7

## 🧢 Your Company/Team

Adobe/Quarry

**Comment by snowystinger** [comment]
I believe this has been addressed, @jluyau can you verify again? Here's the updated codesandbox https://codesandbox.io/s/infallible-meitner-nn6wdm

**Comment by jluyau** [comment]
Looks good to me, thanks!
