### ISSUE TITLE
SSR – Mismatched server / client ids when running in `StrictMode`

### ISSUE THREAD

**Issue by csantos1113** [adobe/react-spectrum#2231]
# 🐛 Bug Report 

Ids mismatch during SSR running in StrictMode (this example is with Next.js, but I believe it does happen with all SSR approaches)

## 🤔 Expected Behavior
Ids to match in Server and Client

## 😯 Current Behavior

Ids don't match between Server and Client during SSR.

```
Warning: Prop `id` did not match. Server: "react-aria-0-1" Client: "react-aria-0-3"
    in input (at pages/index.js:15)
    in IndexPage (at _app.js:6)
    in SSRProvider (at _app.js:5)
    in App
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in StrictMode
    in Root
```

## 🔦 Context

I'm trying to have react-aria hooks working with Next.js in SSR.

This seems to happen in other libraries like https://github.com/radix-ui/primitives/issues/811

## 💻 Code Sample

https://codesandbox.io/s/react-spectrum-nextjs-wp58t?file=/pages/index.js
Open the console tab and see the warning there

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/ssr   | 3.0.3 |
| @react-aria/textfield   | 3.3.1 |
| Browser          | all |
| Operating System | all |

**Comment by tmoschou** [comment]
FYI React 18 beta has `useId`

- https://github.com/reactwg/react-18/discussions/111
- https://github.com/reactwg/react-18/discussions/112

**Comment by snowystinger** [comment]
Thanks, @devongovett has been keeping an eye on it https://github.com/reactwg/react-18/discussions/111#discussioncomment-1514935
we'll likely be picking up the work we started on react 18 in the near future https://github.com/adobe/react-spectrum/pull/2142

**Comment by lveillard** [comment]
Hello there! Any news on this now that React 18 has been released?
Thanks!

**Comment by devongovett** [comment]
#779 is the umbrella issue for strict mode support. For React 18 support, see https://github.com/adobe/react-spectrum/issues/2800.

**Comment by LFDanLu** [comment]
Closing in favor of the umbrella strict mode issue https://github.com/adobe/react-spectrum/issues/779
