### ISSUE TITLE
Button in (disabled) link causes navigation.

### ISSUE THREAD

**Issue by jeroenwienk** [adobe/react-spectrum#2234]
# 🐛 Bug Report 

## 🤔 Expected Behavior

When a button is pressed inside an anchor only the button should fire and not the surrounding link.

## 😯 Current Behavior

When a button is pressed inside an anchor tag it causes the browser to navigate to the provided href. Even when this anchor is disabled. This seems like default browser behavior for which I dont understand the use case.

It's rather easy to circumvent this behavior by preventing default in onClick on the nested button but this gives a deprecation warning.

`onClick is deprecated, please use onPress`

Another solution is to wrap the onClick handler prop from useButton and prevent default there. Problem is that every button needs some context aware code (am I in a anchor tag wrap with....).

```javascript
function tweakClick(onClick) {
  const prevClick = onClick;

  // almost the same as in usePress onClick
  return function (event) {
    if (event && !event.currentTarget.contains(event.target)) {
      return;
    }

    if (event && event.button === 0) {
      event.preventDefault();
      prevClick(event);
    }
  };
}
```

## 💁 Possible Solution

usePress only prevents default for onClick on isDisabled right now. Why is this not the default? Since onMouseDown also does this.

## 🔦 Context

Maybe it's a big nono to put buttons in anchors but in this use case it's a list item that navigates to a specific route and it also has a button that pops out a context menu with some actions. So now when a user clicks the context menu button they are routed away instead of only opening the menu.

## 💻 Code Sample

https://codesandbox.io/s/react-aria-linking-u0kdb?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | -
| react-aria   | 3.9.0
| Browser          | Chrome (92.0.4515.159 (64-bit)), Firefox (91.0.1 (64-bit))
| Operating System | Windows

**Comment by snowystinger** [comment]
You are correct, a link with a button inside is a big accessibility no-no.
Depending on the list implementation it's also a big no no to put an interactive element such as a button inside any list item.
You could use a table?

**Comment by jeroenwienk** [comment]
> You are correct, a link with a button inside is a big accessibility no-no. It's also not valid html.
> Depending on the list implementation it's also a big no no to put an interactive element such as a button inside any list item.
> You could use a table?

Ah indeed it's not even valid html 🤦‍♂️ . I will try to find some other solution. Thank you for the fast response.
