### ISSUE TITLE
usePress event missing altKey modifier

### ISSUE THREAD

**Issue by jeroenwienk** [adobe/react-spectrum#2235]
# 🐛 Bug Report 

## 🤔 Expected Behavior

I expect to be able to find out if alt was held down during a press.

## 😯 Current Behavior

There is no way to check for the `altKey` modifier. Only `ctrlKey`, `metaKey` and `shiftKey` are available. Also there is no way to access the event. So there is no way to check for `altKey` yourself.

## 💁 Possible Solution

Provide acces to the actual event or add `altKey` modifier to event.

## 🔦 Context

I'm not sure why the `altKey` modifier is whitheld on purpose. At least I expect that would be the case since the other modifiers are available. Would be curious why this specific modifier isn't passed.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| react-aria | 3.9.0
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
Yeah, not sure why that's not included, this is the PR commit that introduced the others if anyone wants to add it, can probably follow what this did
https://github.com/adobe/react-spectrum/commit/f749393c05ed39fdfdd9fb84a9f975ea83650fcd

**Comment by devongovett** [comment]
Yeah not sure why I missed it. Want to send a PR, @jeroenwienk?

**Comment by jeroenwienk** [comment]
> Yeah not sure why I missed it. Want to send a PR, @jeroenwienk?

Will do.
