### ISSUE TITLE
TabList's initial selected tab line not always styled correctly

### ISSUE THREAD

**Issue by reidbarber** [adobe/react-spectrum#2244]
# 🐛 Bug Report 

Occasionally, when rendering Tabs with a default selectedKey, the line below might be aligned incorrectly as seen here:

<img width="258" alt="screen-shot-20210824-142140" src="https://user-images.githubusercontent.com/8961049/130646591-9f3891f3-7507-4c4b-bf06-9f3d87c77ab5.png">

When clicking other tabs and clicking back, the style is fixed. 

This is likely due to the font loading after the style for the line has been set.

## 🤔 Expected Behavior

Selected tab line should always be aligned initially, even if font loading is delayed.

## 😯 Current Behavior

See above. Occurs inconsistently.

## 💁 Possible Solution

A resize observer should be added and TabLine's style should be recalculated if needed.

## 💻 Code Sample

Use `Tabs` with a `selectedKey`.

More likely to reproduce if cache is disabled and connection is throttled, so font loading occurs after the selected tab's line style has been set.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
related https://github.com/adobe/react-spectrum/issues/2004

**Comment by reidbarber** [comment]
Good catch, closing because #2004 should fix this
