### ISSUE TITLE
Custom plop action "renameMany" is not required

### ISSUE THREAD

**Issue by neeraj3029** [adobe/react-spectrum#2248]
# 📝 Feedback

Creating a custom plop action "renameMany" to have dynamic filenames is not required.  Dynamic file-naming can be done by renaming template filenames appropriately. Please refer to the code sample for an example.

This can significantly reduce the amount of code.

## 🔦 Context

To my understanding, the plop action renameMany is being used to rename the generated files to include the component's name in the filename. This can be handled with only handlebars and plop, and without the overhead of using a custom action.

In this way, we can totally remove a custom plop action simple change in template filenames.

## 💻 Code Sample/Alternative
For example, if the filename `Component.tsx.hbs` is changed to `{{componentName}}.tsx.hbs`, the generated file will automatically have the variable componentName within the filename.

```
<!-- If you have an example are seeing an error, please provide a code repository, gist or sample files to reproduce the issue -->

## 🌍 Your Environment

<!--- Include as many relevant details about the environment you experienced the issue in -->

| Software         | Version(s) |
| ---------------- | ---------- |
| [Package name]   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

<!--- Which product team is requesting this feedback? (i.e. Adobe/Photoshop) -->

**Comment by neeraj3029** [comment]
@dannify 
Please check out this issue 📄

**Comment by LFDanLu** [comment]
@neeraj3029 Oh interesting we'll have to give this a try, thank you for the suggestion!

**Comment by neeraj3029** [comment]
> @neeraj3029 Oh interesting we'll have to give this a try, thank you for the suggestion!

Sure, I'd love to send a PR with changes if you give it a go.

**Comment by LFDanLu** [comment]
Absolutely, we'd be happy to accept a PR.
