### ISSUE TITLE
ColorWheel onChangeEnd fires twice in StrictMode

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#2250]
# 🐛 Bug Report 

onChangeEnd fires twice when moving/clicking the thumb in a ColorWheel in StrictMode.

## 🤔 Expected Behavior

onChangeEnd should only fire once

## 😯 Current Behavior

onChangeEnd fires twice in strict mode.

## 💻 Code Sample

https://codesandbox.io/s/thirsty-shadow-0du04?file=/src/index.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | color beta 3
| Browser          |. Chrome
| Operating System | MacOS
 
## 🧢 Your Company/Team

RSP

**Comment by reidbarber** [comment]
Looks like this got handled by https://github.com/adobe/react-spectrum/pull/2448. After updating `@react-spectrum/color` to `3.0.0-beta.5` in the provided codesandbox, the issue is no longer present. Feel free to confirm and close this @LFDanLu

**Comment by LFDanLu** [comment]
Yep, looks like a dupe of https://github.com/adobe/react-spectrum/issues/2247
