### ISSUE TITLE
[SearchField] onKeyDown event handler never called

### ISSUE THREAD

**Issue by joelrbrandt** [adobe/react-spectrum#2253]
The [documentation for SearchField](https://react-spectrum.adobe.com/react-spectrum/SearchField.html) indicates that it supports an `onKeyDown` event handler. However, if a handler is registered, it is never called.

I believe the cause is that this code overrides the `onKeyDown` prop from the spread:

https://github.com/adobe/react-spectrum/blob/562b4006e27f2c479d3498df44c4ea689ff37c3a/packages/%40react-aria/searchfield/src/useSearchField.ts#L87-L93

### Expected Behaviour

If I register a handler, it is called.

### Actual Behaviour

It isn't.

### Reproduce Scenario (including but not limited to)

Add an event handler, generate an event, and observe that the handler isn't called.

#### Steps to Reproduce

1. Register a handler
2. Press a key

#### Platform and Version

Platform: Mac, but I can't imagine this matters.
Version: 3.8.0, but the problem looks to be still present in `main`.

#### Sample Code that illustrates the problem

```jsx
<SearchField
  aria-label="Search"
  placeholder="Enter text"
  onSubmit={(value: string) => {
    console.log("submitted", value);
  }}
  onClear={() => {
    console.log("cleared");
  }}
  onKeyDown={(event) => {
    console.log("you'll never see me", event);
  }}
  onKeyUp={(event) => {
    console.log("I work correctly", event);
  }}
/>
```

**Comment by LFDanLu** [comment]
Note for the team/whoever picks this up: check if textfield/textarea call the user provided onKeyDown as well.
