### ISSUE TITLE
Issue with scrollbar behavior in TableView

### ISSUE THREAD

**Issue by PlanckTimeGames** [adobe/react-spectrum#2257]
# 🐛 Bug Report 

When using a TableView inside a Flex box, the behavior of the scrollbars has different issues on different browsers.
Code sandbox link with snippet: https://codesandbox.io/s/romantic-rgb-sl9fq?file=/src/App.js

On Chrome:
When going from a small number of rows to a large number of rows, the horizontal scrollbar appears for a fraction of a second and then disappears.

On Firefox:
When going from a large number of rows to a smaller number of rows, the scrollbar disappears but leaves an empty area behind. The table doesn't expand to fill the area left behind by the scrollbar. See the image below:
![TableView on Firefox](https://user-images.githubusercontent.com/70004727/131305714-402fbd14-a24c-4899-b7d6-28a42f221d3f.png)

## 🤔 Expected Behavior

On Chrome: The horizontal scrollbar should not appear if the rows change.

On Firefox: There should be no empty space left when the scrollbar disappears.

## 😯 Current Behavior

See Bug Report section 

## 💁 Possible Solution

Seems like the Chrome issue has to do with the CSS transitions applied on rows.

## 💻 Code Sample

https://codesandbox.io/s/romantic-rgb-sl9fq?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum/table  |  3.0.0.rc.1 |
| Browser          |  Chrome and Firefox |
| Operating System | All |

## 🧢 Your Company/Team

Adobe Acrobat

**Comment by LFDanLu** [comment]
Note: "show scroll bars" need to be turned on to reproduce the Firefox issue. May be in a similar vein to #2229?

**Comment by snowystinger** [comment]
The Firefox issue has been addressed at some point, I can no longer reproduce it with our latest version https://codesandbox.io/s/competent-voice-6h8wrp?file=/src/App.js

I'm not sure we can really do anything about the Chrome case. What happens is that we add rows such that the collection must vertically scroll to accommodate all the items. That then makes the view area slightly narrower meaning that items extend beyond the visible boundary (by the vertical scrollbar width). The collection notices the view port size change and remeasures to layout within the visible boundary, which means no items will extend beyond the view port and eliminate the need for the horizontal scrollbar.

I'm going to close this. If it's really a big problem, we can reopen for just that.
