### ISSUE TITLE
Popover arrow missplaced in certain conditions

### ISSUE THREAD

**Issue by rohijai** [adobe/react-spectrum#2258]
# 🐛 Bug Report 

When the trigger button is close to the bottom edge of the page, the popup will not render correctly. It starts collapsing and also tip gets miss-aligned 

## 🤔 Expected Behavior

Tip should not be miss-aligned and should be stick to popover dialog

## 😯 Current Behavior

Getting miss-aligned

## 🌍 Your Environment

https://codesandbox.io/s/dawn-breeze-3d6er

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.10.0
| Browser          | Chrome, Safari, Firefox
| Operating System | Mac

## 🧢 Your Company/Team

Working with Adobe Color Team

**Comment by LFDanLu** [comment]
Mind adding some screenshots of what you are seeing? Is this the issue you are talking about?
![image](https://user-images.githubusercontent.com/9661127/131380445-e055e8e6-6d77-4441-8d83-65697f4d23bb.png)

**Comment by rohijai** [comment]
Yes. Adding screenshot of actual scenario

<img width="442" alt="Screenshot 2021-08-03 at 14 31 25" src="https://user-images.githubusercontent.com/89633686/131382571-ba540158-c99f-4742-83ba-47547554ebcc.png">

**Comment by LFDanLu** [comment]
In that screenshot, what is the trigger button fro the popover?

**Comment by rohijai** [comment]
Rectangle area with green border is a trigger button (also tip is pointing to it only).

**Comment by LFDanLu** [comment]
I see, I'm not sure how much we can do here since we need the tip to be positioned next to the button but at the same time we don't want the popover to partially render out of view. I'll bring it up with the team.

**Comment by LFDanLu** [comment]
Talked with the team, perhaps we could add some additional logic for changing the popover positioning when this happens or adjust the boundary of the popover, will need some investigation.

**Comment by rohijai** [comment]
Sure.

**Comment by LFDanLu** [comment]
We will investigate shifting the popover arrow automatically in cases like this and look into refining the overlay positioning code.

**Comment by ktabors** [comment]
After reviewing the two exploration PRs above and a third party solution with Spectrum we've decided to reduce padding to 6px when the trigger is at a boundary. For the extreme cases when the trigger is at the boundary and the arrow can not point at the trigger and remain nicely connected to the popover, the arrow will be removed.

**Comment by LFDanLu** [comment]
Reopening since there is some additional refinement required, PR for tracking: https://github.com/adobe/react-spectrum/pull/3454

**Comment by LFDanLu** [comment]
Fixed by https://github.com/adobe/react-spectrum/pull/4220
