### ISSUE TITLE
If the maxWidth of the last column of a TableView is specified, then the table does not layout correctly.

### ISSUE THREAD

**Issue by PlanckTimeGames** [adobe/react-spectrum#2259]
# 🐛 Bug Report 

If I specify the maxWidth of the last column of a TableView, then the table does not fill its container.
If I specify the maxWidth of any other column except the last one, then the table expands correctly.
See codesandbox snippet: https://codesandbox.io/s/unruffled-keldysh-d28rz?file=/src/App.js
See image:
![image](https://user-images.githubusercontent.com/70004727/131385590-0686d11d-8cc2-448d-96b8-57fd570e6928.png)

## 🤔 Expected Behavior

If the maxWidth of the last column is set, then the remaining columns should expand such that the table fills its container properly.

## 😯 Current Behavior

If the maxWidth of the last column of a TableView is specified, then the table does not fill its container.

## 💁 Possible Solution

Needs some fixes in layout calculation.

## 🔦 Context

I am making a table that needs to have smaller columns on the right side. This bug makes my table look ugly.

## 💻 Code Sample

https://codesandbox.io/s/unruffled-keldysh-d28rz?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum/table   | 3.0.0.rc.1 |
| Browser          | All |
| Operating System | All |

## 🧢 Your Company/Team

Adobe Acrobat

**Comment by LFDanLu** [comment]
Point of investigation: https://github.com/adobe/react-spectrum/blob/840ef4fc8fd1dd896a37b581829e954dfa5d3392/packages/%40react-stately/layout/src/TableLayout.ts#L66-L108

**Comment by snowystinger** [comment]
Looks like this was fixed at some point, I can't reproduce anymore https://codesandbox.io/s/immutable-feather-kstxgz?file=/src/App.js
