### ISSUE TITLE
@react-aria/utils useId is not deterministic, which breaks snapshot tests depending on it

### ISSUE THREAD

**Issue by jimisaacs** [adobe/react-spectrum#2272]
# 🐛 Bug Report 

@react-aria/utils useId is not deterministic, which breaks snapshot tests depending on it

The issue is caused by this line:
https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/ssr/src/SSRProvider.tsx#L32

## 🤔 Expected Behavior

The useId hook (and the useSSRSafeId) hook should be deterministic.

## 💁 Possible Solution

Allow prefix to be set by consumers.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
Can you provide more information? I don't see how specifying a prefix helps if it's nondeterministic.
If you can reproduce it, that is most helpful.

**Comment by snowystinger** [comment]
According to the comment on that line, it won't be a random number in ssr, it'll be set to zero. Can you provide more information or examples?

**Comment by jimisaacs** [comment]
It's a random number when running jest snapshot testing in jsdom environment.

**Comment by LFDanLu** [comment]
Does wrapping your test components in a SSRProvider help? Otherwise maybe you could try [mocking useId](https://github.com/adobe/react-spectrum/issues/1167#issuecomment-899753521) as a work around

**Comment by LFDanLu** [comment]
Closing for now, feel free to reopen if the above doesn't work.
