### ISSUE TITLE
Not able to drag Dialog on given view/canvas

### ISSUE THREAD

**Issue by rohijai** [adobe/react-spectrum#2273]
# 🐛 Bug Report 

When Dialog is in open state via DialogTrigger, then there should be ability to drag Dialog and dock it somewhere else on given view/canvas.

## 🤔 Expected Behavior

Should be able to drag Dialog

## 😯 Current Behavior

Not able to drag Dialog

## 🔦 Context

When user is working on canvas (Fred) and opens a color-picker to select color and part of canvas where Dialog renders is not accessible to user to perform any action, so user should have ability to drag the dialog and place/dock somewhere else on view.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.10.0
| Browser          | Chrome, Safari, Firefox
| Operating System | Mac

## 🧢 Your Company/Team

Working with Adobe Color Team

**Comment by LFDanLu** [comment]
This feels like an enhancement, will need to discuss with design to see if this is something we can support.

**Comment by rohijai** [comment]
Ok Sure.

**Comment by LFDanLu** [comment]
Similar to the reasons mentioned [here](https://github.com/adobe/react-spectrum/issues/2274#issuecomment-925173569), will be closing this as we won't be supporting this for our Popovers.
