### ISSUE TITLE
Not able to disable dismiss behaviour of Dialog

### ISSUE THREAD

**Issue by rohijai** [adobe/react-spectrum#2274]
# 🐛 Bug Report 

When Dialog is dragged (using DOM manipulation) on given view, then Dialog should not be dismissed if clicked outside Dialog area.

## 🤔 Expected Behavior

Dialog should not be dismissed if clicked outside Dialog area.

## 😯 Current Behavior

Dialog gets dismmised.

## 🔦 Context

This is a brief view of what I am trying to achieve, hope it explains the requirement (attached video in comments)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.10.0
| Browser          | Chrome, Safari, Firefox
| Operating System | Mac

## 🧢 Your Company/Team

Working with Adobe Color Team (For Fred)

## 🕷 Tracking Issue (optional)

https://github.com/adobe/react-spectrum/issues/2273

**Comment by rohijai** [comment]
https://user-images.githubusercontent.com/89633686/131801398-e53ee42c-2006-4899-9746-6683fac0258f.mov

**Comment by rohijai** [comment]
Accessibility/focus will not be concern in dragged state. As drag behaviour will not be enabled/possible via. keyboard.

**Comment by LFDanLu** [comment]
Well disallowing drag behavior on the Dialog is an accessibility concern and the focus trap in the Dialog will still give you problems. For example, what would happen if someone opened the Dialog, then clicked on an input field outside the dialog?

**Comment by rohijai** [comment]
I guess it will put focus on input field with Dialog still in open state.

**Comment by LFDanLu** [comment]
So that is the problem. The focus trap inside the popover would prevent focus from leaving the Dialog as long as it is open. The UX here is probably more suited for a different component other than Dialog that we haven't implemented yet, would be good to bring this up with Spectrum design

**Comment by LFDanLu** [comment]
Closing this since we won't be adding this behavior to the Popover due to the concerns above. You'll have to build your own Popover component to support this unfortunately, feel free to reach out to the team if you need any assistance using our hooks/existing components to do so.
