### ISSUE TITLE
CardView and v2 GridView parity 

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#2283]
# 🐛 Bug Report 

The remaining items to reach v2 parity:
- drag and drop support
- small card support (to be updated to S/M/L card support)
- placeholder images in the cards + handling item size updates in layout when that happens (not entirely sure if needed?)
- section handling (was in some of the v2 layouts but don't think we actually supported it)

**Comment by dannify** [comment]
Moved to S2
