### ISSUE TITLE
Update GridLayout logic

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#2284]
# 🐛 Bug Report 

Possible GridLayout updates:
- right now GridLayout uses static numbers for determining the vertical height of the card container, resulting in the row height being 300px (arbitrary value) even if the card doesn't have a footer + details and could fit in a 250px height
  -  Since v3 cards can have a variety of things in the card that weren't in the v2 card, perhaps we should investigate making the layout do a second measurement to see what the true size of the row is
     - set the row height to be the height of the largest card in the row
  - ~~scale support~~ roughly handed via eyeballed values but requires spectrum feedback/actual values

**Comment by dannify** [comment]
Moved to s2
