### ISSUE TITLE
CardView UX issues

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#2285]
# 🐛 Bug Report 

List of UX issues:
- the item scrolls into view when you click/tap it. Perhaps only do this when keyboard navigating, clicking/tapping the item should preserve the scroll position
  -  This is a larger issue that affects Menu/Table/collection components that use virtualizer
- ~~Removing an item doesn't show an animation~~ Fixed in previous PR
- disabled keys story, arrow key navigate to a disabled card, press space to select, it scrolls the view

## 🧢 Your Company/Team

RSP

**Comment by devongovett** [comment]
We reverted the scrolling fix in release. Will need to find a new approach.
