### ISSUE TITLE
Outdated react peer-dependency

### ISSUE THREAD

**Issue by dimitrisnl** [adobe/react-spectrum#2337]
# 📝 Feedback

I've noticed that @react-aria is using a `rc` version of React, causing terminal warnings

```ts
  "peerDependencies": {
    "react": "^16.8.0 || ^17.0.0-rc.1",
    "react-dom": "^16.8.0 || ^17.0.0-rc.1"
  },
```

for example
```ts
 @react-aria/select > @react-aria/menu > @react-stately/tree@3.2.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0-rc.1".
```

Is there a blocker updating the peerDependency to the latest ^17 version?

## 💻 Code Sample

https://github.com/adobe/react-spectrum/blob/9204e1b8cb61dac767e91087fb16203611dc67c5/packages/%40react-aria/overlays/package.json#L30-L33

**Comment by snowystinger** [comment]
updating to the latest would invalidate anyone still using the earlier versions, we technically do support exactly what that range says
I think you're looking at a similar issue to https://github.com/adobe/react-spectrum/issues/2054
This persons started working, please let us know if you are unable to get yours working, we can look into it more together. For more information, this comment probably has the most relevant information on semver https://github.com/adobe/react-spectrum/issues/2054#issuecomment-868188590

**Comment by dimitrisnl** [comment]
@snowystinger I have no issues with the current version as I'm using yarn and it doesn't seem to break. It's just that the terminal throws unnecessary warnings. 

I looked at the server calculator you posted and indeed it should include the latest react version. Very strange, it's probably a Node issue.

Closing, thank you!
