### ISSUE TITLE
Landmark navigation hook

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#2353]
# 🙋 Feature Request

Landmarks are sometimes needed to help a user navigate major sections of an application. Landmark regions add document-level keyboard shortcuts used to navigate between them. By default F6 navigates to the next landmark region, Shift+F6 navigates to the previous landmark region, and Alt+F6 navigates to the main landmark. Each region, while focused, displays a focus ring.

## 🤔 Expected Behavior

Developers would use the `useLandmark` hook, which receives a `role` and a `ref` to an element. The returned props would be passed to the element.

```js
let {landmarkProps} = useLandmark({
  role: 'main'
}, ref);

<main {...landmarkProps}>
  {/* your app here */}
</main>
```

Calling `useLandmark` would register the ref with a global singleton `LandmarkManager` (TBD). When landmarks are registered, this would have global event listeners on the page to handle F6 navigation. Navigating would either focus the landmark itself or a focusable child within it if any using the registered ref.

API:

```js
interface LandmarkProps extends AriaLabelingProps {
  role: 'main' | 'region' | 'search' | 'navigation' | 'form' | 'banner' | 'contentinfo' | 'complementary'  
}
```

## 🧢 Your Company/Team

RSP

**Comment by snowystinger** [comment]
We're going to need a way to change the order of the LandmarkRegions, relying on rendered order may not always be correct, especially with CSS Grid.
