### ISSUE TITLE
Using h1/h2/h3 HTML elements inside Item in picker, does't change the height of Item in Picker

### ISSUE THREAD

**Issue by armalik459** [adobe/react-spectrum#2381]
# 🐛 Bug Report 

When we try to use h1, h2, or other HTML elements inside Item in [Picker](https://react-spectrum.adobe.com/react-spectrum/Picker.html), the height of that item doesn't adjust to the HTML element. 

<img width="506" alt="Screenshot 2021-09-28 at 10 42 55 AM" src="https://user-images.githubusercontent.com/30997929/135031238-f988db3a-4c5d-4dca-ab9f-6de2b0ca63b4.png">

## 🤔 Expected Behavior

 Each Item should take the height of the child HTML elements.

## 😯 Current Behavior

Current behavior same as bug report.

## 🔦 Context

https://xd.adobe.com/view/b1e36c7e-f44f-4066-8fed-b065f7f96836-e4b0/screen/a876eb63-b7d8-4c47-b65a-f5a359ad9016
This is what we are trying to achieve, a spectrum dropdown / picker with multiple options, having differently styled HTML texts.

## 💻 Code Sample

https://react-spectrum.adobe.com/react-spectrum/Picker.html#example
In the above examples, if I wrap the Item children inside HTML elements like - 
```
<Picker label="Choose frequency">
  <Item key="rarely"><h1>Rarely</h1></Item>
  <Item key="sometimes"><h2>Sometimes</h2></Item>
  <Item key="always"><h3>Always</h3></Item>
</Picker>
```

The expected behaviour is that the Item will take the height of the children, but this doesn't happen and gives a buggy behaviour to the user.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | "@adobe/react-spectrum": "^3.9.0"
| Browser          | CHrome
| Operating System | Mac OS

## 🧢 Your Company/Team

 Adobe CC Libraries

##

**Comment by snowystinger** [comment]
If you wrap each of those in a `<Text>` it should do the right thing, see https://react-spectrum.adobe.com/react-spectrum/Picker.html#complex-items

**Comment by armalik459** [comment]
Thanks a lot @snowystinger
