### ISSUE TITLE
onchange event listener not working on useTextField

### ISSUE THREAD

**Issue by emiljamel** [adobe/react-spectrum#2382]
Hi everyone, sorry if I'm wrong. I have tried to create an input field using useTextField everything works as expected, but when I add the onchange event listener as a prop the input box cannot be changed. Even though the documentation says "Change, clipboard, composition, selection, and input event support".

Here is my code snippet:

```
const [value, setValue] = React.useState("my value");

<TextField label="Document" name="document" value={value} onChange={(event) => setValue(event.target.value)} />
```

And this is my TextField.js component:

```
function TextField(props) {
  const textFieldRef = React.useRef(null);

  const [isFocusWithin, setFocusWithin] = React.useState(false);

  const { labelProps, inputProps, errorMessageProps } = useTextField({ ...props }, textFieldRef);
  const { focusWithinProps } = useFocusWithin({
    onFocusWithinChange: () => setFocusWithin(prevState => !prevState)
  });

  returns (
    <div className={classes.TextField}>
      <label className={classes.TextField_Label} {...labelProps}>{props.label}</label>
      <div className={clsx(classes.TextField_Field, {
        [classes.TextField_Field__focus]: isFocusWithin
      })} {...focusWithinProps}>
        <input className={classes.TextField_Input} {...inputProps} autoComplete="off" autoCapitalize="off" ref={textFieldRef} />
      </div>
    </div>
  );
}

export default TextField;
```

have i missed something?

**Comment by snowystinger** [comment]
I see you closed it, so I'm assuming you've figured it out. So anyone who stumbles across it, onChange receives a value, not the event object. I'm assuming that's what went wrong.
One other note, you don't need to spread into a new object in the useTextField hook, you can just pass props directly in
