### ISSUE TITLE
Add T-Shirt Sizing to Button Component

### ISSUE THREAD

**Issue by dmskinner** [adobe/react-spectrum#2384]
# 🙋 Feature Request

Add t-shirt sizing to the [Button](https://spectrum.adobe.com/page/button/) component to align with the [Spectrum button design](https://spectrum.adobe.com/page/button/#Size)

## 🤔 Expected Behavior

Passing a t-shirt value in a `size` prop would change the size of the button, like other components that have size props (ex Dialog)

## 😯 Current Behavior

Button size cannot be manipulated using the standard `size` prop

## 💁 Possible Solution

Updating to main Spectrum CSS should make the change simple as it has [button size classes](https://opensource.adobe.com/spectrum-css/button-cta.html#sizing). I'm not sure if there is a good solution prior to that change, or if a work-around would be supported.

## 🔦 Context

We have a very data heavy UI and the feedback we've been given from UX is the buttons should be smaller. They believe the larger buttons are contributing to the overwhelming visual and that smaller buttons would help.

## 💻 Examples

This has already been [designed](https://spectrum.adobe.com/page/button/#Size) within Spectrum

## 🧢 Your Company/Team

Adobe/Cloud Enablement Services - Management Tooling

## 🎁 Tracking Ticket (optional)

N/A

**Comment by evargast** [comment]
@matthewdeutsch Do you know if this issue has been prioritized? Wondering if it's in the roadmap or not

**Comment by dannify** [comment]
Not on the roadmap yet. Looking forward to your pull request 😃

**Comment by andrewchough** [comment]
Mind if I take a crack at this?

**Comment by snowystinger** [comment]
For anyone looking to work on this, code exists in the Spectrum-CSS repo, which we forked a while back. You can see it here. https://github.com/adobe/spectrum-css/blob/main/components/button/index.css#L30

We'd want to stay as close as possible to that code in our implementation of size as well.

We may need to rethink the name of the prop, I think we've used 'size' for a different purpose in some other components.

**Comment by snowystinger** [comment]
Closing as not doing in RSP v3. This will be available in our Spectrum 2 implementation.
