### ISSUE TITLE
Trays are a little broken in iOS 15

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#2388]
# 🐛 Bug Report 

With the bottom toolbar in iOS 15 Safari trays sometimes extend behind them. Not sure if the visual viewport is resizing correctly. See the ComboBox docs.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.14.0
| Browser          | Safari
| Operating System | iOS

## 🧢 Your Company/Team

RSP

**Comment by reidbarber** [comment]
May be related to https://github.com/adobe/react-spectrum/issues/2343.

**Comment by devongovett** [comment]
Should be fixed in #3005
