### ISSUE TITLE
useDialog autofocus doesn't work for long-lived components

### ISSUE THREAD

**Issue by kherock** [adobe/react-spectrum#2397]
# 🐛 Bug Report 
The `useDialog` hook only attempts to autofocus when the passed in ref changes. Refs generally don't change for the lifetime of a component, so the autofocus only works during the initial component render.

## 🤔 Expected Behavior
Autofocusing should happen when the ref's current value changes. The existing implementation does have a safeguard to prevent stealing focus when focus is already inside the overlay, so it should be safe to run every time the ref changes. This would even handle unusual edge cases where the focus context is lost due to the entire overlay element being replaced in the DOM (e.g. in a multi-screen modal).

## 😯 Current Behavior
When `useDialog` is called for the first time with an empty ref object, it won't autofocus when the content mounts and the ref is hydrated. 

## 💁 Possible Solution
Modifying the deps list in its `useEffect` hook to be `[ref.current]` instead of`[ref]` solves the issue on my end.

## 🔦 Context
I have a dialog component that manages its own presence (the reason for this is to support exit animations, though I can imagine other use cases). It creates a ref to pass to `useDialog` that lives for the duration of the component, which is at least as long as its trigger element.

## 💻 Code Sample
See PR for a test case reproducing the issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | `@react-aria/dialog` v3.1.4
| Browser          | tested in Chrome/Edge, Firefox
| Operating System | Linux, macOS

**Comment by kherock** [comment]
@LFDanLu that's somewhat correct, though the callback function will at least rerun the next time the component renders. I'll see if I can make a codesandbox soon.

I'd argue that the real issue here is that `useDialog` should support using the raw element as an argument instead of a RefObject. The `@react-hook/*` hooks do this and it works well - [example here](https://github.com/jaredLunde/react-hook/tree/master/packages/size#usesizetarget-options). Regardless, the `useEffect` in the `useDialog` hook must rerun when the element change, so it should declare `ref.current` as a dependency.

Building on this, if I want a component to rerender as soon as a ref is hydrated, they way I'd prefer the `useDialog` hook to work would be something like this:

```tsx
const [dialogElement, dialogRef] = useState<HTMLElement | null>(null);
const { dialogProps } = useDialog(props, dialogElement);

return isOpen && <div ref={dialogRef} {...dialogProps}>...</div>;
```

This is useful in several other places within `react-aria`'s hooks - another major one that came up for me is with `useOverlayPosition`. I usually need the position recalculated as soon as a popup mounts. Creating a RefCallback with `useState` allows me to do this and works well in this case. However, there are other parts of `react-aria`'s hooks API that either act strangely or uncooperatively when the RefObject changes every render.

**Comment by snowystinger** [comment]
I think this entire issue can be avoided by using `autoFocus` on your FocusScope in that codesandbox's `Dialog` component or on a specific component inside the `Dialog`.

I'm going to close this issue. If it's still an issue, feel free to reopen.
