### ISSUE TITLE
FocusScope restoreFocus doesn't work when its immediate children change

### ISSUE THREAD

**Issue by kherock** [adobe/react-spectrum#2415]
# 🐛 Bug Report 

https://github.com/adobe/react-spectrum/blob/0e528a50fa1ba33df295ce12f03001d970e80504/packages/@react-aria/focus/src/FocusScope.tsx#L460

This line doesn't work effectively when the children of a FocusScope change due to a layout effect that runs when children change:
https://github.com/adobe/react-spectrum/blob/0e528a50fa1ba33df295ce12f03001d970e80504/packages/@react-aria/focus/src/FocusScope.tsx#L92-L102

When it's time for the component to unmount, the array value dereferenced at the beginning of the effect is outdated, and the cleanup function won't find the active element in the scope as a new scope has been created with a new set of children. This is especially problematic when the children are a virtual list.

## 🤔 Expected Behavior

The component should restore focus regardless of when children are added, removed, or replaced.

## 😯 Current Behavior

A simple scenario where this breaks down is opening a popover and focusing a child that doesn't render until after the FocusScope is created. When the FocusScope child is unmounted, focus is moved to `<body>`. 

## 💁 Possible Solution

`useRestoreFocus`'s layout effect cleanup function needs to use the current value of scopeRef. This creates a warning about the value being different than the one used earlier in the effect, but this is necessary behavior.

A cleaner alternative is to make scopeRef immutable altogether and ensure that the value of `scope` doesn't change for the the lifecycle of `FocusScope`.

## 🔦 Context

I have a select component that requires an extra initial render cycle while an ideal placement is being computed. The parent component orchestrating the animation contains and rerenders a FocusScope with a single child with the mount animation. Since the child present when the FocusScope initializes is different than the one present when the FocusScope unmounts, it fails to schedule the focus restoration based on the behavior described above.

![image](https://user-images.githubusercontent.com/4993980/135726714-96c1d0e9-4db3-48b7-8398-d2f7d975b8c4.png)

## 💻 Code Sample

WIP, I'll have a PR that should isolate this issue in a unit test shortly.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `@react-aria/focus`   | 3.5.0
| Browser          | N/A
| Operating System | N/A

## 🧢 Your Company/Team

N/A

**Comment by kherock** [comment]
You're welcome and no worries! That timeline should work.

**Comment by beamery-tomht** [comment]
Has there been any movement on this?
