### ISSUE TITLE
React "bad setState" error when using the an input build with useNumberField

### ISSUE THREAD

**Issue by armandabric** [adobe/react-spectrum#2418]
# 🐛 Bug Report 

I've created a [stepped number input component](https://codesandbox.io/s/usenumberfield-update-bug-rk16h?file=/src/SteppedNumberField.jsx) that is almost the same as in the doc but I'm getting a React error [when using it in another component](https://codesandbox.io/s/usenumberfield-update-bug-rk16h?file=/src/GuestsSelector.jsx). The error is trigger when clicking on the decrement/increment button 

```
Warning: Cannot update a component (`GuestsSelector`) while rendering a different component (`SteppedNumberField`). To locate the bad setState() call inside `SteppedNumberField`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at SteppedNumberField (https://rk16h.csb.app/src/SteppedNumberField.jsx:32:55)
    at GuestsSelector (https://rk16h.csb.app/src/GuestsSelector.jsx:24:3)
    at div
    at App
```

After some tests I could not find any clue on what happens here. Given the example in the docs it seems to be a legit usage but I could not make it works.

## 🔦 Context

I'm trying to create a component to select the number of the adults, children, and babies.

## 💻 Code Sample

Here a simplified example that reproduce the issue: https://codesandbox.io/s/usenumberfield-update-bug-rk16h

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/button |  3.3.4 | 
| @react-aria/numberfield  | 3.1.0 |
| react | 17.0.2 |
| react-dom | 17.0.2 |

**Comment by armandabric** [comment]
You right it's seems to be the same root issue as #2320. 

I could give a try to an on the edge version of the library to confirm the fix. Let me know when ready

**Comment by snowystinger** [comment]
You can try it any time. The team is in the middle of a few things, so it'll still be at least a week or so before we really get that PR in shape to get in.

**Comment by snowystinger** [comment]
We've finally merged this, https://github.com/adobe/react-spectrum/pull/2304 It'll be available starting in the nightlies. Let us know if you find anything wrong with it.
