### ISSUE TITLE
Update sorting docs to use Intl collator

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#2423]
# 🙋 Documentation Request

https://react-spectrum.adobe.com/react-stately/useAsyncList.html#server-side-sorting just does a simple sort that makes sense in English, but not necessarily anywhere else.
Same in Table https://react-spectrum.adobe.com/react-spectrum/TableView.html#sorting

**Comment by LFDanLu** [comment]
For those interested in picking this up, we have a [useCollator](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/i18n/src/useCollator.ts) hook that will help provide localized string collation for this
