### ISSUE TITLE
ComboBox and SearchField don't filter dynamic items.

### ISSUE THREAD

**Issue by tk-bitio** [adobe/react-spectrum#2424]
# 🐛 Bug Report 

When I use dynamic items:
```tsx
<SearchAutocomplete label="Search" allowsCustomValue items={animals}>
        {(item) => <Item key={item.id}>{item.name}</Item>}
</SearchAutocomplete>
```
the search/filter functions don't seem to work properly.

This might be intentional? I'm not sure. A quick search for "combobox dynamic" and "search dynamic" didn't pull any search results.

## 🤔 Expected Behavior

Input text should correctly filter the items.

## 😯 Current Behavior

The items do not get filtered by the input's value.

## 🔦 Context

My items load dynamically, and I need a way to also search through them. This behavior would make sense if the items were loading async, but my example uses statically set items passed in via the `items` prop. The seems to disable the searchable behavior. 

## 💻 Code Sample

https://codesandbox.io/s/immutable-darkness-gu813?file=/src/App.tsx:1862-2018

## 🌍 Your Environment

Bug is exhibited in Code Sandbox, so my computer env is not the issue.

## 🧢 Your Company/Team

🤔

**Comment by reidbarber** [comment]
Hi @tk-bitio, for that scenario you would use `defaultItems={animals}` instead of `items={animals}`. You would use the `items` prop if you wanted to make it fully controlled and use your own filter function.

**Comment by tk-bitio** [comment]
*sigh* Thank you, reidbarber. I have spent a while debugging this. I think some docs about it would belong here: https://react-spectrum.adobe.com/react-stately/collections.html#static-collections.

**Comment by tk-bitio** [comment]
Oh nvm, you edited w/ examples from the docs. Should've thought to check the React Spectrum docs.

**Comment by reidbarber** [comment]
Glad you found what you needed. Yeah, `defaultItems` is specific to useCombobox and not a part of Collections, so I could see how that could be confusing. See [this section](https://react-spectrum.adobe.com/react-aria/useComboBox.html#dynamic-collections) of the useCombobox docs to read more.
