### ISSUE TITLE
Tabs: Item: data attributes not passed to DOM

### ISSUE THREAD

**Issue by rvillescas** [adobe/react-spectrum#2429]
# 🐛 Bug Report 
We are trying to pass data-instance-id prop to our Tabs Item components. The Item components are showing "data-key" but not our custom data prop.

For example, this is what we are trying:

## 🤔 Expected Behavior
The Test documentation says the data props should render at attributes for React-Spectrum components.
https://react-spectrum.adobe.com/react-spectrum/testing.html

## 😯 Current Behavior
The custom data attribute is not present in the DOM for rendered Item components.

## 🔦 Context
We are in process of upgrading our React Spectrum components from V2 to V3 and our E2E tests are breaking.

## 💻 Code Sample
```
import React from "react";
import { Provider, defaultTheme, Tabs, TabList, Item } from "@adobe/react-spectrum";
import "./styles.css";

export default function App() {
  return (
    <Provider theme={defaultTheme}>
      <Tabs isQuiet={true}>
        <TabList>
          <Item key={'test'} data-instance-id={'test'}>
              test
          </Item>
        </TabList>
      </Tabs>
    </Provider>
  );
}
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.13.0 |
| Browser          | Chrome |
| Operating System | Mac |

## 🧢 Your Company/Team

Adobe/Asset Essentials

**Comment by mqnguyen5** [comment]
Great! I'll definitely check it out

**Comment by mqnguyen5** [comment]
Thanks for the help! Another question, though. Do I make the changes directly in the code or do I have to do it through Storybook?

**Comment by mqnguyen5** [comment]
Hi @reidbarber , I try to add the code based on [#2429 (comment)](https://github.com/adobe/react-spectrum/issues/2429#issuecomment-947016342) and #2047 but still didn't understand how I should write the test. Do you mind helping me out?
