### ISSUE TITLE
Uncaught RangeError: invalid language tag: "C"

### ISSUE THREAD

**Issue by jzarca01** [adobe/react-spectrum#2436]
# 🐛 Bug Report 

`Uncaught RangeError: invalid language tag: "C"`

## 🤔 Expected Behavior

It should use a default language if the one provided isn't valid

## 😯 Current Behavior

function `isRTL` crashes when trying to instantiate new Intl.Locale with bogus language "C"

## 💁 Possible Solution

It should check if `locale` provided is valid

## 🔦 Context

Open Firefox and browse to `about:config`
Change `intl.accept_languages` to `C`

Browse to `https://shop.gandi.net` and look in the console

```
Uncaught RangeError: invalid language tag: "C"
    ht utils.ts:26
    gt useDefaultLocale.ts:33
    <anonymous> useDefaultLocale.ts:37
    Webpack 15
utils.ts:26:17
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | @react-aria/i18n@^3.3.2 |
| Browser          | Firefox 92.0.1 |
| Operating System | Arch Linux Manjaro, Gnome 40.4.0 |

## 🧢 Your Company/Team

Gandi

**Comment by snowystinger** [comment]
Hey! Thanks for the issue. I have to say, this seems like FF shouldn't accept invalid languages? What is the actual use case here?
I'm asking because deciding on what 'default language' to use is non-obvious.

**Comment by BartoszGamza** [comment]
I've also experienced this problem. I have logs for `navigator.language` returning `en-US@posix` and it is also not accepted by `supportedLocalesOf` so best option would be to actually try-catch on Intl.Locale(locale) and fallback to en-US in case of error

**Comment by snowystinger** [comment]
Thanks for the extra info @BartoszGamza, this clarifies a lot that I was unaware of.
Do you know what the steps are to get the navigator.language to return that string?

**Comment by BartoszGamza** [comment]
@snowystinger Im not sure whether we can do anything here, this is just risky property. We got very weird outputs in the logs, such as:

![image](https://user-images.githubusercontent.com/26162660/162921614-e484405a-ca63-4894-a22e-756cafa7c293.png)

I can create a PR with try-catch approach later that should cover all the weird scenarios 😉

**Comment by BartoszGamza** [comment]
@snowystinger in general, we cannot write to `navigator.language`, I wasn't able to reproduce the error on my own. Maybe @jzarca01 will be able to confirm whether it works?

**Comment by snowystinger** [comment]
If we can figure out how to get some of these other values, it might be worth seeing if there is a browser bug here. For instance, I'm not seeing any part of the syntax allowing for the "@" character in the specification https://datatracker.ietf.org/doc/html/rfc5646 which I found through MDN https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language
