### ISSUE TITLE
Our keys in Picker stories don't always match the value

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#2437]
# 🐛 Bug Report 

https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/picker/stories/Picker.stories.tsx#L60
The story should be easy to test, and so the keys should at least resemble their value.

**Comment by khoad** [comment]
This issue can be closed

**Comment by LFDanLu** [comment]
@khoad thanks for the heads up!
