### ISSUE TITLE
useLink with React Router V6

### ISSUE THREAD

**Issue by Tatamethues** [adobe/react-spectrum#2439]
# 🐛 Bug Report 

useLink doesn't work React Router V6. 
[( please see this)](https://github.com/remix-run/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md#remove-link-component-prop)
Since the onClick function is deprecated( I saw some issues discussed this), in router V6, the useLinkClickHandler needs to use onClick function.

## 🤔 Expected Behavior

I think useLink should work with react router v6 on browser. 

## 😯 Current Behavior

warning : onClick is deprecated, please use onPress

## 💻 Code Sample
The DefaultLink is a wrapper for useLink.

```
const Link = React.forwardRef<HTMLAnchorElement, LinkProps>(function Link(
  props: LinkProps,
  ref
) {
  const { to, target, replace = false, onClick, ...others } = props;
  const href = useHref(to);
  const handleClick = useLinkClickHandler(to, {
    target,
    replace,
  });
  return (
    <DefaultLink
      href={href}
      ref={ref}
      {...others}
      onClick={(event) => {
        onClick?.(event as React.MouseEvent<HTMLAnchorElement>);
        if (!event.defaultPrevented) {
          handleClick(event as React.MouseEvent<HTMLAnchorElement>);
        }
      }}
    />
  );
});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Chrome

**Comment by Tatamethues** [comment]
Yes. Since the different event type, I'm unable to call handleClink within the onPress handler, even with your solution. The callback calles the `preventDefault()`, which doesn't on the onPress event.
`useLinkClickHandler ` ([code](https://github.com/remix-run/react-router/blob/8567b33d05a2cd62530a6c3dad29ae1d43f1856e/packages/react-router-dom/index.tsx#L342)) is used to create a custom Link component to replace the default Link component in React Router.

**Comment by zauni** [comment]
With the help of other comments on react-spectrum issues, I could come up with a `<NavLink>` component, that has most of the props of the original `<NavLink>` from React Router, but uses the `useLink` hook under the hood. maybe it is helpful for others that want to integrate React Router and React Aria.

Essentially in the `useLink` hook we provide a `onPress` function which calls the function that is returned from the `useLinkClickHandler` and fakes a mouse event so that React Router is happy.
With this trick the routing is already working fine, but it reloads the page... Because of that it is needed to use the `mergeProps` function on the `<a>` tag to include a `onClick` event handler that is doing the `preventDefault` on the original mouse click.

```tsx
import cn from 'classnames';
import type { FC, ReactNode } from 'react';
import { useRef } from 'react';
import type { AriaLinkOptions } from 'react-aria';
import { mergeProps, useLink } from 'react-aria';
import type { To } from 'react-router-dom';
import {
  useHref,
  useLinkClickHandler,
  useLocation,
  useResolvedPath,
} from 'react-router-dom';

interface Props extends AriaLinkOptions {
  to: To;
  children?: ReactNode;
  className?: string | ((props: { isActive: boolean }) => string | undefined);
}

const NavLink: FC<Props> = ({
  children,
  to,
  className: classNameProp = '',
  ...props
}) => {
  const path = useResolvedPath(to);
  const location = useLocation();
  const href = useHref(to);
  const handleClick = useLinkClickHandler(to);
  const ref = useRef(null);
  const { linkProps } = useLink(
    {
      ...props,
      onPress: (e) => {
        // call the click handler from react router on press of the link
        handleClick({
          ...e,
          button: 0, // @see https://github.com/remix-run/react-router/blob/edf1dfc3327f721045ed672870b4f99825aa8fb8/packages/react-router-dom/dom.ts#L41
          // eslint-disable-next-line @typescript-eslint/no-empty-function
          preventDefault: () => {}, // noop because react-router wants to call this function, but react-aria is not providing it on the PressEvent
        } as unknown as React.MouseEvent<HTMLAnchorElement>);
      },
    },
    ref
  );

  const toPathname = path.pathname;
  const locationPathname = location.pathname;

  const isActive =
    locationPathname === toPathname ||
    (locationPathname.startsWith(toPathname) &&
      locationPathname.charAt(toPathname.length) === '/');

  const ariaCurrent = isActive ? 'page' : undefined;

  let className: string | undefined;
  if (typeof classNameProp === 'function') {
    className = classNameProp({ isActive });
  } else {
    // If the className prop is not a function, we use a default `active` class
    className = cn(classNameProp, { active: isActive });
  }

  return (
    <a
      {...mergeProps(linkProps, {
        // react-aria is not doing a preventDefault on links
        // @see https://github.com/adobe/react-spectrum/issues/2525#issuecomment-1371391041
        onClick: (event: MouseEvent) => event.preventDefault(),
      })}
      aria-current={ariaCurrent}
      href={href}
      className={className}
      ref={ref}
    >
      {children}
    </a>
  );
};

export default NavLink;

```
