### ISSUE TITLE
isDisabled does not work as expected with useComboBox/useComboboxState

### ISSUE THREAD

**Issue by hayes** [adobe/react-spectrum#2467]
# 🐛 Bug Report 

isDisabled only prevents opening combobox when clicking on the input element.
Clicking on the label or button parts of a combobox that is disabled still opens the combobox.

This is probably related to https://github.com/adobe/react-spectrum/issues/1887

## 🤔 Expected Behavior

`disabled` should be set on both inputProps and buttonProps
when `isDisabled` is `true`, clicking on label, input, or button of a combobox should not open the combobox

## 😯 Current Behavior

`disabled` is only passed to `inputProps`.  The button remains enabled, and interacting with the label opens the combo box even when disabled.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
I assume you mean for something like this? https://codesandbox.io/s/floral-brook-ftg56
I'm not seeing an issue with click on the label, but I do see that the button opens when it shouldn't.
Looks like we need to pass isDisabled to useMenuTrigger here https://github.com/adobe/react-spectrum/blob/2c09f1e7de805f9de084c9eae24fb7c6468b3152/packages/%40react-aria/combobox/src/useComboBox.ts#L78
then we should be able to remove it from our own implementation here https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/combobox/src/ComboBox.tsx#L343

**Comment by hayes** [comment]
thanks for adding an example! yes, that is what I meant.  Looks like you are correct.  I had something weird on my end that was causing the same behavior with the label, and assumed it was the same issue.  My bad.
