### ISSUE TITLE
onKeyDown not working on ComboBox.

### ISSUE THREAD

**Issue by shomitta** [adobe/react-spectrum#2468]
I need to use combobox for "allowsCustomValue", So I need to trigger event whenever a ENTER key is pressed (not on input change/ selection change) & check the TextEdit value at the time of enter & run command accordingly.

OnSelectionChange/ OnInputChange wont be helpful in this case as we have a requirement to trigger event with custom TextEditValue on pressing Enter.

**Comment by LFDanLu** [comment]
To be further discussed with the team, initial discussion is leaning towards the approach mentioned above provided that it doesn't break useComboBox's current interactions

**Comment by reidbarber** [comment]
Here is a PR for a similar issue that might be helpful for whoever picks up this issue: https://github.com/adobe/react-spectrum/pull/2617
