### ISSUE TITLE
Expose `useProvider` hook in RSP's public API 

### ISSUE THREAD

**Issue by emensch** [adobe/react-spectrum#2488]
# 🙋 Feature Request

Expose the current color scheme/matched breakpoint as part of the RSP public API 🎉 

## 🤔 Expected Behavior

```javascript
const { colorScheme, breakpoints } = useProvider();

// go nuts
```

## 😯 Current Behavior

N/A

## 💁 Possible Solution

Export the `useProvider` hook or `useBreakpoint`/`useColorScheme` hooks :) 

## 🔦 Context

There are some situations when working w/ more complex layouts that access to the same context RSP uses under the hood would be useful. A real-world example would be rendering a different icon or changing an SVG `fill` based on the current color scheme.

**Comment by LFDanLu** [comment]
Talked with the team, instead of exposing `useProvider` in the mono-package it might be an idea to create some additional hooks just to expose things like the current color scheme, breakpoints, etc.

**Comment by LFDanLu** [comment]
What we'd be looking for would hooks that are similar to `useProvider` https://github.com/adobe/react-spectrum/blob/34717616f3a6555d3f4d6739635d3ac347b50a58/packages/%40react-spectrum/provider/src/Provider.tsx#L188-L190
but would each return only the context's color scheme or breakpoints (e.g. `return useContext(Context).colorScheme`)
