### ISSUE TITLE
Disabled checkbox has an inaccessible label text

### ISSUE THREAD

**Issue by NeilWix** [adobe/react-spectrum#2527]
# 🐛 Bug Report 

I encountered this with the checkbox but it might apply to all disabled components: 
Instead of only having the input disabled, the corresponding label text is also designed as "disabled". This results in a less than 1:4.5 contrast ratio. As far as I understand WCAG, only the input itself is excepted from the minimum contrast requirement, not its text label.
## 🤔 Expected Behavior
The disabled input's label should maintain a contrast ratio of at least 4.5:1

## 😯 Current Behavior
Currently, the disabled input's label text does not meet the WCAG requirement for color contrast

https://react-spectrum.adobe.com/react-spectrum/Checkbox.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 
| Browser          | Edge chromium latest
| Operating System | Windows 10

**Comment by snowystinger** [comment]
Hey! Thanks for opening this issue. It's working as intended, disabled text is not required to meet contrast requirements, see https://webaim.org/articles/contrast/#incidental

**Comment by NeilWix** [comment]
Thanks for the prompt reply. Please note there is no such thing as a disabled text. only inputs can be disabled, hence, it doesn't meet one of the four criteria in WEBAIM's explanation you shared with me.

**Comment by snowystinger** [comment]
Hey, so I still think it's working as intended, see this definition as well https://www.w3.org/TR/WCAG21/#contrast-minimum
> Text or images of text that are part of an inactive user interface component

The checkbox label is part of the inactive component.

This is the stance that other libraries have taken as well
https://github.com/uswds/uswds/issues/757
Here's an example from Material UI
https://codesandbox.io/s/material-ui-checkbox-forked-nbt8l?file=/src/App.tsx which inspecting the text is `rgb(0, 0, 0, 0.38)` and the background is white, which gives a contrast ratio of 2.67 https://contrast-ratio.com/#rgb%280%2C%200%2C%200%2C%20.38-on-white

Is there a problem that you're facing because of this?

**Comment by NeilWix** [comment]
Also in IBM's carbon...
As far as I understand, "Text or images of text that are part of an inactive user interface component" should only refer to a button's text node or nested image. 
Styling text to look disabled, simply makes it too hard to read.
BTW, looking at browsers implementation, including the case of a disabled fieldset that hosts inputs and labels, only dims the inputs, not the text/label.

-

**Comment by snowystinger** [comment]
Thanks for a counterexample. I've talked with our accessibility team and, @jnurthen, co-chair of the ARIA WG, who provided an extra definition to help clarify. https://www.w3.org/TR/WCAG21/#dfn-user-interface-components specifically
| a part of the content that is perceived by users as a single control for a distinct function

Checkboxes and their labels are perceived as a single control, clicking the label is no different from clicking the input element in terms of functionality.

**Comment by NeilWix** [comment]
Interesting, 
in that case, I believe it would also make sense to set pointers-event to none on the "disabled" label. 
thanks!

**Comment by snowystinger** [comment]
I'm not sure I follow, what would `pointer-events: none` contribute? Is there an issue you're running into using the React Spectrum Checkbox?

**Comment by NeilWix** [comment]
No, I am just saying it from a technical perspective
Neil Osman
Accessibility engineer @ accessibility team
