### ISSUE TITLE
ListView and TableView Keyboard focus issue

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum#2528]
# 🐛 Bug Report 

In ListView, when keyboard selecting, there is a visual artifact between the rounded corners and the thin top line.

In TableView, when keyboard selecting, goto the top row and there is no top selection border. All other tops and bottom row have both a top and bottom border.

## 🔦 Context

https://reactspectrum.blob.core.windows.net/reactspectrum/9ca62f94405cb8b930bd155f6e44c4854f0a20f3/storybook/index.html?path=/story/listview--selectionstyle-highlight
https://reactspectrum.blob.core.windows.net/reactspectrum/9ca62f94405cb8b930bd155f6e44c4854f0a20f3/storybook/index.html?path=/story/tableview--selectionstyle-highlight

## 💻 Images

![image](https://user-images.githubusercontent.com/309540/140798539-e15d2d78-e879-4847-b9b2-30667f616b26.png)
![image](https://user-images.githubusercontent.com/309540/140791107-05af2ddd-a475-4ac0-893f-d31dc853decc.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | main |
| Browser          | chrome |
| Operating System | OSX |

## 🧢 Your Company/Team
RSP

**Comment by reidbarber** [comment]
First image should be fixed in: 
- https://github.com/adobe/react-spectrum/pull/2517 
- https://reactspectrum.blob.core.windows.net/reactspectrum/a85a767486a6971e2ddcf7eeaf8be8a0116c1b44/storybook/index.html?path=/story/listview--selectionstyle-highlight

**Comment by ktabors** [comment]
Both issues have been fixed.
