### ISSUE TITLE
Support for Windows High Contrast Themes

### ISSUE THREAD

**Issue by PreetiNagal** [adobe/react-spectrum#2529]
# 🙋 Feature Request

We need to Support Windows High Contrast Mode in our web PDF viewer. Currently UI elements don't adapt Windows High Contrast Mode, which is a blocker in completing support for High Contrast Mode. 
As most of our UI elements use react-spectrum CSS classes for styling, Please help to add support for High Contrast in react-spectrum CSS classes.

## 🤔 Expected Behavior
UI elements should adapt as per Windows High Contrast Mode.

There are 8 colors available in a High Contrast theme. So, UI elements should adapt colors according to the theme 

## 😯 Current Behavior

UI elements don't adapt as per High Contrast themes

## 💁 Possible Solution

Add support for high contrast mode in existing CSS classes of react-spectrum

## 🔦 Context

We need to Support Windows High Contrast Mode in our web PDF viewer. Currently UI elements don't adapt Windows High Contrast Mode, which is a blocker in completing support for High Contrast Mode. 

## 💻 Examples

Design mocks for High Contrast mode are already present in React-spectrum documentation.

## 🧢 Your Company/Team

Adobe/DocumentCloud

**Comment by devongovett** [comment]
I think this is partially fixed? Not sure which components are left. @jnurthen?

**Comment by jnurthen** [comment]
> I think this is partially fixed? Not sure which components are left. @jnurthen?

Sorry - missed this over shutdown. Still all the input components to do. Have a PR ready soon but having a few problems on pickers.
