### ISSUE TITLE
Change onSelectionChange to optionally call when value is not the same

### ISSUE THREAD

**Issue by dannify** [adobe/react-spectrum#2536]
# 🙋 Feature Request

onSelectionChange currently fires even if the value is the same. This is needed for some components however it is unwanted functionality for TableView. Add an option to turn this ON. This will mean the default is **OFF** and existing code will need to be updated accordingly. When off and the value is the same, the onSelectionChange will not fire. 

## 🔦 Context

In Table selectionStyle highlight, onAction using "space" will continually fire onSelectionChange with the same selection. Using "enter" will fire both onSelectionChange with the same selection PLUS onAction. The correct behavior should only fire onAction if the value is the same.
## 🧢 Your Company/Team

RSP

**Comment by LFDanLu** [comment]
Add tests for components that don't have onSelectionChange toggling of the same item. Tabs will need this option on, figure out if any other one will need this option on
