### ISSUE TITLE
Arbitrary Colorspace and conversion support

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#2539]
# 🙋 Feature Request

We want some way for users to bring their own color space conversions to React Spectrum's color picking type components.
The first step will be to define some API's to show how we'd like to handle this.

## 😯 Current Behavior

Users are locked into using RGB/HSL/HSB, if they want another color space supported they have to add it to React Spectrum, they have no say on how many decimal places we carry certain values out to, and they have no say on how we convert between color spaces.

## 💁 Possible Solution

A Plugin architecture is probably the way to go.

## 🔦 Context

We don't want to be in the business of performing color conversions. Applications have vastly different needs, be it precision, accuracy, or which color spaces they handle, and we don't want to force a large bundle size to fit everyone's needs.

**Comment by dannify** [comment]
Stale
