### ISSUE TITLE
Build failure with Next.js in Electron renderer.

### ISSUE THREAD

**Issue by ln-north** [adobe/react-spectrum#2564]
# 🐛 Bug Report 

Build failure with Next.js (including `next-transpile-modules` settings) **in Electron renderer**.

## 🤔 Expected Behavior

Successful build

## 😯 Current Behavior

I created an Electron app with next.js and added react-spectrum and built it according to [adobe-spectrum's SSR document](https://react-spectrum.adobe.com/react-spectrum/ssr.html). Repository is below.

https://github.com/ln-north/react-spectrum-next-electron

and failed to build with this message.

```
../node_modules/@react-spectrum/table/dist/main.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: ../node_modules/@react-spectrum/table/dist/module.js
```

## 💻 Code Sample

https://github.com/ln-north/react-spectrum-next-electron

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest |
| Browser          | Chromium(Electron) |
| Operating System | Ubuntu 20.04 |

**Comment by reidbarber** [comment]
I'll admit that I've never seen the use case of Electron + Next.js (I guess it is dependent on using static export?), but I gave it a try.

Adding `"@react-spectrum/table"` to the `next-transpile-modules` config in `next.config.js` seemed to fix the problem (this package was recently released).

<img width="441" alt="Screen Shot 2021-11-19 at 10 36 27 AM" src="https://user-images.githubusercontent.com/8961049/142658619-d8a8dbe3-96db-45cc-95b8-42d3b4361a63.png">

Feel free to re-open if you still have issues!

**Comment by ln-north** [comment]
Thanks! I made it work.
I'll try to examine in pure Next.js whether we need to add `"@react-spectrum/table"` to the docs, if we need, I'll send PR.

**Comment by reidbarber** [comment]
Sounds good, and hopefully if https://github.com/vercel/next.js/discussions/27953 gets implemented, we won't need any extra configuration at all.
