### ISSUE TITLE
Dialog zoom 400% hero image and buttons

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum#2571]
# 🐛 Bug Report 

With hero banner in 400% zoom Dialogs' the buttons are off screen. There are also off screen with the vertical buttons. 

## 🤔 Expected Behavior

Buttons are always visible and accessible.

## 😯 Current Behavior

There are a couple cases (hero, vertical buttons, etc,) with zoom where the buttons overflow out of the dialog.

## 💁 Possible Solution

Work with Spectrum for a solution. Discussed at this level zoom we move the scroll from the content to the container.

## 🧢 Your Company/Team
RSP

**Comment by majornista** [comment]
At higher zoom levels, where the content currently scrolls, and we have difficulty rendering the header, content and footer buttons, we may want to not scroll the content at all, and instead scroll the entire dialog, as if it were a long web page.
