### ISSUE TITLE
ListView needs to support PageUp, PageDown, End and Home key events

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum#2572]
# 🐛 Bug Report 

- The fn+up arrow (page up) doesn't work in ListView. fn+down arrow (page down) does work.
- Home and end keys don't do anything (regression? check what it should do)
- cannot shift select the first item, probably because the key is 0

## 🤔 Expected Behavior

The above keyboard interactions should work

## 😯 Current Behavior

The above keyboard interactions don't work
Goto a ListView, use the page up, page down, end, and home keys (fn-arrow keys on Mac), only page down works.

## 🧢 Your Company/Team
RSP

**Comment by LFDanLu** [comment]
Fixed by https://github.com/adobe/react-spectrum/pull/3000
