### ISSUE TITLE
Investigate ListView and TableView command-return key event selections are grey

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum#2595]
# 🐛 Bug Report 

The command-return key event selections are grey instead of blue. Investigate to see what is happening.

## 🤔 Expected Behavior

The command-return key event selections should be blue similar to command-click event.

## 😯 Current Behavior

The command-return key event selections are grey which is different than every other selection key, touch and click event.

![image](https://user-images.githubusercontent.com/309540/143152503-170bbe28-d137-4156-8ac4-0f69bc60862d.png)

## 🔦 Context

Found during testing

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | master |
| Browser          | chrome and firefox (probably all) |
| Operating System | osx |

## 🧢 Your Company/Team
RSP

**Comment by devongovett** [comment]
I think this is a macOS bug. There is no keyup event fired while the Command key is pressed, only a keydown. It is present in every browser.

* https://bugs.chromium.org/p/chromium/issues/detail?id=1393524
* https://bugs.webkit.org/show_bug.cgi?id=55291
* https://bugzilla.mozilla.org/show_bug.cgi?id=1299553

We could perhaps keep track of all the keydown events that occur while the Command (e.g. Meta) key is pressed, and fire corresponding keyup events for them ourselves when the Command key itself is released (there is a keyup event for that).
