### ISSUE TITLE
ActionGroup button is missing its right border if next to a disabled button

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#2609]
# 🐛 Bug Report 

- See "overflowMode: collapse disabledKeys" story, right border is missing when un-collapsed
![image](https://user-images.githubusercontent.com/9661127/143933078-a5887883-0078-4588-ba2f-c62114dc06d0.png)

## 🤔 Expected Behavior

right border of the Move button should exist

## 😯 Current Behavior

right border of the Move button doesn't exist

## 🧢 Your Company/Team

RSP

**Comment by paulgpeterson** [comment]
I'm happy to work on this issue!

**Comment by dannify** [comment]
I think https://github.com/another-maverick is taking this one already @paulgpeterson. Anything else you'd like to work on?

**Comment by paulgpeterson** [comment]
I just joined the slack channel and saw the discussion! Sure, I'll find something else.

**Comment by tomsontom** [comment]
this one go fixed with #2710

**Comment by snowystinger** [comment]
Yes it did, thank you for the comment
