### ISSUE TITLE
Firefox: Checkbox + label undraggable when nested in draggable row

### ISSUE THREAD

**Issue by damenking** [adobe/react-spectrum#2613]
# 🐛 Bug Report 

I have a grid row with a draggable element whose attributes are derived from the useDraggableItem hook.  Within that element I have a checkbox and associated label.  When using firefox I cannot initiate a drag by mousing down on the checkbox or it's label.  This issue is not reproducible in firefox when using a simple draggable div with a nested html checkbox input.  Tested with spectrum Textfield and ActionButton but those seem to be working.

## 🤔 Expected Behavior

I should be able to iniate a row drag by holding mouse down on any element within a draggable row on all browsers.

## 😯 Current Behavior

When trying to drag a row in firefox, if the checkbox or it's label was the element you clicked down on, no drag events occur.

## 💁 Possible Solution

Having the label not be a child of the checkbox works for the text but the checkbox itself continues to exhibit the same behavior.

## 🔦 Context

I have a grid collection list with multiple items that can be selected.  The checkbox is an indicator of which items in the list are selected and the checkbox label provide text for the row.  The list is reorderable via drag and drop using the Spectrum dnd implementation.

## 💻 Code Sample

Spectrum implementation: https://codesandbox.io/s/firefox-checkbox-pyg93
Basic html implementation: https://codesandbox.io/s/confident-pare-g5oym

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 13.12
| Browser          | Firefox
| Operating System | MacOs

## 🧢 Your Company/Team

Adobe/Marketo

**Comment by reidbarber** [comment]
We might want to handle this issue in https://github.com/adobe/react-spectrum/pull/2593. I noticed a related checkbox issue in https://github.com/adobe/react-spectrum/pull/2593#discussion_r759459751, so a fix for that could potentially fix this issue as well.

**Comment by devongovett** [comment]
I think this is working as intended. Interactive elements such as buttons or checkboxes within a draggable row should not cause dragging. ListView solves this by making the text a separate element from the checkbox.

**Comment by damenking** [comment]
Since you can drag these elements in chrome/safari I guess it would still be a bug but for the other browsers then?

**Comment by devongovett** [comment]
Updated your sandbox to the latest version of React Aria and it is consistent across browsers. If you want to have the label not be part of the checkbox and therefore allow dragging, you can render the text as a separate element. https://codesandbox.io/s/firefox-checkbox-forked-xkdkqm?file=/src/reorderablelist/Grid.js:2087-2094
