### ISSUE TITLE
useGrid scrollRef not working with accessible dnd drop indicator

### ISSUE THREAD

**Issue by damenking** [adobe/react-spectrum#2614]
# 🐛 Bug Report 

An overflowing grid container whose props are derived from the useGrid hook (with a scrollRef prop passed to it) will scroll when keying over items but not when moving a drop indicator out of view.

## 🤔 Expected Behavior

After starting accessible dnd by hitting enter on an item, a drop indicator is observable in the grid container.  When that drop indicator is moved to a point in the grid that is not visible due to overflow, the container should scroll to keep the drop indicator in view.

## 😯 Current Behavior

The drop indicator will no longer be visible when moved into the overflow space of the grid container.  It is only visible again if you manually scroll.

## 🔦 Context

I have a grid collection list with many items. The list is reorderable via drag and drop using the Spectrum dnd implementation.  Using accessible drag and drop I want to be able to move an item above/below another item that is in the overflowing content of the list.

## 💻 Code Sample

https://codesandbox.io/s/dnd-base-cy15o

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 13.12
| Browser          | Chrome
| Operating System | MacOs

## 🧢 Your Company/Team

Adobe/Marketo

**Comment by LFDanLu** [comment]
Did some digging in your sandbox, looks like you are missing `{...dropIndicatorProps}` here: https://codesandbox.io/s/dnd-base-cy15o?file=/src/reorderablelist/InsertionIndicator.js:1058-1123. The `useGrid` -> `useSelectableCollection` scrollIntoView code isn't actually the code that handles scrolling when in dragging mode, `useDropIndicator` -> `useDroppableItem`'s [useEffect](https://github.com/adobe/react-spectrum/blob/b826620011d000f8cd5551c898e405c9b90be14c/packages/%40react-aria/dnd/src/useDroppableItem.ts#L55-L59) brings the drop indicator into view via a direct focus call.

**Comment by damenking** [comment]
THANK YOU!
Sorry I missed that appreciate you taking a look
