### ISSUE TITLE
Move aria specific combobox props out of base type

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#2624]
There are some props that aren't used by stately in ComboBoxProps, which can be confusing for users to know where to pass props: to `useComboBoxState` or `useComboBox`.

For example:

https://github.com/adobe/react-spectrum/blob/34717616f3a6555d3f4d6739635d3ac347b50a58/packages/%40react-types/combobox/src/index.d.ts#L41-L43

should move to Aria specific props (and also be included in the Spectrum types). We will need to create a new `AriaComboBoxProps` in that file with those props and extend in `SpectrumComboBoxProps`.

cc @arackaf

**Comment by frdclav** [comment]
I am taking a look at this issue!
