### ISSUE TITLE
StatusLight in TableView column looks misaligned because of padding

### ISSUE THREAD

**Issue by carolframpton** [adobe/react-spectrum#2629]
### Expected Behaviour
A  StatusLight in a Cell in a TableView Column, which is by default left-aligned, should be capable of being aligned with its header. I should be able to remove the left padding without resorting to `UNSAFE_style`. (Likewise for a right-aligned column I might want to remove the right padding).

### Actual Behaviour
StatusLight has padding-left so it isn't aligned correctly. Setting paddingStart="0" is not supported.

### Reproduce Scenario (including but not limited to)
![image](https://user-images.githubusercontent.com/71789937/144456778-5e7f1b93-d3b1-44a6-9065-405e2e98f04c.png)

#### Platform and Version
"@adobe/react-spectrum": "3.14.0"

#### Sample Code that illustrates the problem
`<Cell>
    <StatusLight variant="negative">
       Error
    </StatusLight>
</Cell>`

**Comment by LFDanLu** [comment]
Looks like the front padding was removed from the StatusLight in spectrum-css: https://github.com/adobe/spectrum-css/pull/1332, we'll explore ways to do this in RSP.

**Comment by snowystinger** [comment]
Closing for the same reason as https://github.com/adobe/react-spectrum/issues/2212#issuecomment-2272586026
