### ISSUE TITLE
Next.js Typescript Compilation Warning

### ISSUE THREAD

**Issue by hamidihekmat** [adobe/react-spectrum#2646]
# 🐛 Bug Report 

I got a postcss error while using `react-spectrum` with Next.js 12 & Typescript.

## 🤔 Expected Behavior

There shouldn't be any warning or errors.

## 😯 Current Behavior

Error prevents the UI from re-rendering with new styles.

```shell
wait  - compiling / (client and server)...
warn  - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[7].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[7].use[2]!./node_modules/@react-spectrum/breadcrumbs/dist/main.css
Warning

(1:83) postcss-preset-env: start value has mixed support, consider using flex-start instead

```

## 🔦 Context

Trying to test out react spectrum components with Next.js 12 and typescript.

### `_app.tsx` 

```ts
function MyApp({ Component, pageProps }: AppProps) {
  const { locale } = useLocale();
  return (
    <SSRProvider>
      <Provider theme={lightTheme} locale={locale}>
        <Component {...pageProps} />
      </Provider>
    </SSRProvider>
  );
}
```

### `next.config.js`

```js
const withTM = require('next-transpile-modules')([
  '@adobe/react-spectrum',
  ...
]);

module.exports = withTM({
  reactStrictMode: true,
});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | ^3.15.0
| Browser          | Chrome@latest
| Operating System | MacOs M1

**Comment by snowystinger** [comment]
That's a warning, it shouldn't prevent anything from working.

**Comment by hamidihekmat** [comment]
> That's a warning, it shouldn't prevent anything from working. Did you follow the guides here? https://react-spectrum.adobe.com/react-spectrum/ssr.html Are there any errors?

```shell
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/Users/hekmathamidi/Desktop/Github/adobe-ui/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[7].use[1]!/Users/hekmathamidi/Desktop/Github/adobe-ui/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[7].use[2]!/Users/hekmathamidi/Desktop/Github/adobe-ui/node_modules/@react-spectrum/breadcrumbs/dist/main.css': No serializer registered for Warning
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 2 items } -> webpack/lib/ModuleWarning -> Warning
```

It is actually, it's not re-rendering when changing from `defaultTheme` to `lightTheme`.

**Comment by snowystinger** [comment]
O, interesting. Does nextjs have anything for ignoring warnings? It seems to be treating it as something it needs a loader for. Apologies for being a bit vague. I'm on my phone. If you can provide a reproduction, someone will look soon, not from a phone, and being able to play with an example will help a lot, be it codesandbox or a small GitHub repo.

**Comment by hamidihekmat** [comment]
> O, interesting. Does nextjs have anything for ignoring warnings? It seems to be treating it as something it needs a loader for. Apologies for being a bit vague. I'm on my phone. If you can provide a reproduction, someone will look soon, not from a phone, and being able to play with an example will help a lot, be it codesandbox or a small GitHub repo.

I think it has something to do with either Next.js 12 or `SSRProvider`. If I remove the `SSRProvider` from `_app.tsx`, I can apply different themes `defaultTheme | darkTheme | lightTheme`. But, wrapping the application with `SSRProvider` triggers this bug. I will try running this on older version of Next.js. I will keep you posted.

**Comment by reidbarber** [comment]
@hamidihekmat I updated an example at https://github.com/reidbarber/rsp-next-ts to use Next.js 12 and added a theme switcher. Everything seems to be working fine. Let me know if you are still running into issues. My only other suggestion would just be deleting `node_modules` and re-installing.

**Comment by hamidihekmat** [comment]
> @hamidihekmat I updated an example at https://github.com/reidbarber/rsp-next-ts to use Next.js 12 and added a theme switcher. Everything seems to be working fine. I am seeing the same warnings that you mentioned, but no errors. Let me know if you are still running into issues. My only other suggestion would just be deleting `node_modules` and re-installing.

Yeah same issue, here I created a code sandbox you can test it out for yourself. [https://codesandbox.io/s/cocky-bose-orel4](url)

**Comment by reidbarber** [comment]
@hamidihekmat the sandbox is working for me. Is it not building for you? Or is the theme not switching?

**Comment by hamidihekmat** [comment]
> @hamidihekmat the sandbox is working for me. Is it not building for you? Or is the theme not switching?

Did you check the code sand box?

**Comment by reidbarber** [comment]
@hamidihekmat Yes, it is working for me:
<img width="793" alt="Screen Shot 2021-12-07 at 4 05 35 PM" src="https://user-images.githubusercontent.com/8961049/145113389-e2b0a82e-1f03-4df1-b936-e5bf22dff7ad.png">
<img width="793" alt="Screen Shot 2021-12-07 at 4 05 27 PM" src="https://user-images.githubusercontent.com/8961049/145113398-d1375604-9694-4dd6-b726-1a4a721fb5fa.png">

Are you still seeing any issues?

**Comment by hamidihekmat** [comment]
> https://codesandbox.io/s/cocky-bose-orel4

Weird, I'm still seeing issues. I can't seem to toggle between dark and light mode...
<img width="740" alt="Screen Shot 2021-12-08 at 12 24 05 AM" src="https://user-images.githubusercontent.com/47622106/145153129-419bcf40-1fd3-4aa8-bace-ffe9eb0ed8bc.png">

**Comment by snowystinger** [comment]
would you be willing to pull the example that @reidbarber wrote in https://github.com/adobe/react-spectrum/issues/2646#issuecomment-988257082 and see if that works for you? you could compare between that and your codesandbox to maybe see the issue

**Comment by hamidihekmat** [comment]
> would you be willing to pull the example that @reidbarber wrote in [#2646 (comment)](https://github.com/adobe/react-spectrum/issues/2646#issuecomment-988257082) and see if that works for you? you could compare between that and your codesandbox to maybe see the issue

Yes I cloned the repo on `codesandbox` and I'm getting the same error and issue.... https://codesandbox.io/s/cocky-bose-orel4

**Comment by reidbarber** [comment]
@hamidihekmat your screenshot is in dark mode, and the example defaults to light mode. So it still looks like it worked, unless I'm missing something.

**Comment by snowystinger** [comment]
ok, I took a look, here it is working
https://codesandbox.io/s/relaxed-hoover-45cut?file=/pages/_app.tsx

you've conflated colorScheme and theme for your provider props, see https://react-spectrum.adobe.com/react-spectrum/Provider.html#themes

**Comment by hamidihekmat** [comment]
> @hamidihekmat your screenshot is in dark mode, and the example defaults to light mode. So it still looks like it worked, unless I'm missing something.

https://user-images.githubusercontent.com/47622106/145284517-7776f0ee-e11c-4b8b-9d50-9c691950d6fc.mov

**Comment by hamidihekmat** [comment]
> ok, I took a look, here it is working https://codesandbox.io/s/relaxed-hoover-45cut?file=/pages/_app.tsx
> 
> you've conflated colorScheme and theme for your provider props, see https://react-spectrum.adobe.com/react-spectrum/Provider.html#themes

Oh I see, I cloned the repo that @reidbarber provided. I hope they fix the warning issues in the next update regarding `postcss-preset-env`

```shell
./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[7].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[7].use[2]!./node_modules/@react-spectrum/breadcrumbs/dist/main.css
Warning

(1:745) postcss-preset-env: start value has mixed support, consider using flex-start instead 
```
