### ISSUE TITLE
Cursor Pointer on ActionButton

### ISSUE THREAD

**Issue by pratesha** [adobe/react-spectrum#2657]
### Expected Behaviour

Need the ability to have cursor pointer to <ActionButton> component

### Actual Behaviour

inline style added to have cursor : pointer is overridden 

### Reproduce Scenario (including but not limited to)

We are using Sampler icon inside action button and want cursor pointer style

#### Steps to Reproduce

Use sampler icon inside action button component

#### Platform and Version

React spectrum V3, macos, chrome v95.x

#### Sample Code that illustrates the problem

```
<ActionButton
        right="0px"
        top="0px"
        position="absolute"
        onPress={handleClick}
        isQuiet
    >
        <Sampler aria-label={props.buttonAriaLabel} size="S"/>
    </ActionButton>
```

#### Logs taken while reproducing problem
N/A

**Comment by reidbarber** [comment]
Not using a pointer cursor for buttons is intentional. Check out the discussion as to why in https://github.com/adobe/react-spectrum/pull/449.
