### ISSUE TITLE
select-all option in listbox

### ISSUE THREAD

**Issue by hayes** [adobe/react-spectrum#2663]
# 🙋 Feature Request

It would be great if there was a well documented way to add select-all behavior to a listbox.  We have a working implementation, but it requires some overly complex workarounds, and it's unclear if there is a better way to do this.

## 🔦 Context

Our use-case for the select-all listbox is for a multi-select dropdown, and also includes a searchable variant.

Our current hacky solution involves the following workarounds:

 1. We wrote a useSelectAllList hook that wraps useListState and injects a select-all item into children/items (this could be removed if the consumer manually added a select-all item)
 2. We added logic to our ListBox component, that checks for a special select-all key in the items its rendering and renders that item using a SelectAllOption component
 3. The SelectAllOption component uses a modified copy of useOption and useSelectableItem that handles the select all behavior, and determines the isSelected state based on the selection state of the other items.

All 3 of these pieces feel like hacks that are doing things outside the current expected usage of react-aria.  

Some of the requirements for our select-all:

* The select-all button should be checked/unchecked automatically if all items in a filtered collection are also selected
* The select-all button selects/deselects all items in the filtered collection (not all items in the selection)
* Disabled keys should not be affected by the select-all, and should not be factored in when determining if the select-all should be in a selected state
* For navigation/focus purposes, the select-all option should behave like any other option in the list
* Select-all should work with both controlled/uncontrolled versions

## 💁 Possible Solution

The simplest improvement for us would be making the useOption hook more customizable.  Specifically we would need to add custom handling for the onSelect behavior, and we would need to customize how the isSelected state is determined.

isSelected can currently be set via a deprecated prop in the useOption hook, but we don't want to rely on a deprecated feature.
useOption calls `useSelectableItem` which supports an onAction prop, but this is treated as a secondary action unless the list has a selection mode of `none`.  We would ideally want a way to overwrite the primary action without setting the selection mode of the whole list state to none.

The above changes would remove the need to copy/paste + modify those hooks.  If there was a more wholistic solution for select-all that would be awesome, I just don't have a good enough understanding of react-aria to know how that might be implemented.  We did find that the useTable hook has select-all behavior, but haven't spent the time to figure out how that is implemented and if there are parts of that solution that would work well for our use-case.

## 🧢 Your Company/Team

The Trade Desk

**Comment by LFDanLu** [comment]
Apologies for the delayed response. Would it be possible to see your changes to the various hooks that you mentioned above in a codesandbox or something? Another idea would be to perhaps ditch the listbox and replace it with a checkbox group in the dropdown instead.

**Comment by hayes** [comment]
I tried to create a somewhat stripped down version of our implementation here: https://codesandbox.io/s/elastic-grass-67fgc?file=/src/App.tsx

Had to take out the styling because the way we style stuff isn't easily portable to codesandbox.  There are also lots of other things I had to strip out, or replace with simpler placeholders, so there are probably a lot of places that look weird, bad, out of place, or poorly implemented because of that, but the useSelectAllState and useSelectAllOption hooks are pretty close to the versions we are using and show the workarounds we come up with for making this all work.

**Comment by LFDanLu** [comment]
At a quick glance, I think the implementation is on the right track, didn't see much that should be changed. Initially I was going to suggest looking at how we did the TableView select all checkbox (https://github.com/adobe/react-spectrum/blob/4e3b234c593f418cc3794213e0bd6e15ba684422/packages/%40react-aria/table/src/useTableSelectionCheckbox.ts#L59-L71) but that is a bit different in how that key is treated within the collection/selection manager.

Injecting the select all option into the children seems accurate (needed so the selection manager can track when the select all becomes the virtually focused key), thus requiring the additional filtering logic in useSelectAllState. I'll need to revisit the `useSelectAllOption` logic, perhaps there is a way to accomplish the select all behavior within the onSelectionChange passed to useListState.
