### ISSUE TITLE
Touch events propagate behind the modal/dialog

### ISSUE THREAD

**Issue by manelsanz** [adobe/react-spectrum#2682]
### Expected Behaviour
When I use useDialog as documentation explains (https://react-spectrum.adobe.com/react-aria/useDialog.html), I expect that, when I click interactive elements (button, link..) inside or outside the mdoal, the touch event was not propagate anymore, just close modal if is dismissisable or do nothing if not.

### Actual Behaviour
When I click outside the content of open modal the touch event is going down so clicks what it's behind, for example a link. If link it's a React Router link, it goes to the new route, and that's annoying. 

If behind there is a normal button with onClick, it gets triggered. If the button uses "useButton" or "usePress", it gets highlighted but not triggered. Even that, I think it's not the solution and I continue thinking that's a bug.

#### Steps to Reproduce
1. Open this snippet with chrome: https://e29xs.csb.app/#
2. Put dev tools in responsive mode
3. Touch "Open Dialog" button
4. After it opens: click Submit or click the link outside modal. The touch event is propagated behind modal, and that's not the expected behavior.
5. If you try to click the outside button while modal is opened, the modal will close and the buton won't be triggered (just highlighted for a moment), and that's because it is using "useButton". But, definitely that's not a solution from my point of view.
#### Platform and Version
Latest library versions

**Comment by snowystinger** [comment]
I'm pretty sure you're reporting this bug https://github.com/adobe/react-spectrum/issues/1513
please star the browser bug to help it get more traction https://bugs.chromium.org/p/chromium/issues/detail?id=1150073
we haven't had any ideas for preventing this currently, open to suggestions, though lets keep the discussion on the original issue

**Comment by manelsanz** [comment]
> I'm pretty sure you're reporting this bug #1513 please star the browser bug to help it get more traction https://bugs.chromium.org/p/chromium/issues/detail?id=1150073 we haven't had any ideas for preventing this currently, open to suggestions, though lets keep the discussion on the original issue

That could be but, since it happens in Firefox too (last version), I think it could be solved by the library itself.

**Comment by equinusocio** [comment]
I think it's a library issue. Here we don't have that issue on responsive mode using another lib  (we are using react-focus-on to solve this bug)

**Comment by snowystinger** [comment]
I'm closing this one as a duplicate and moving the discussion to the original issue
