### ISSUE TITLE
Tabs onSelectionChange not called when doing a second selecting via Picker dropdown

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum#2684]
# 🐛 Bug Report 

When testing selection changes, Tabs should call onSelectionChange when the current tab is selected, even if it is the current selection. Using the "resizable" story, convert the tabs into a Picker by shrinking the width. Selecting the currently selected tabs from the Picker does not call onSelectionChange.

## 🤔 Expected Behavior

onSelectionChange is called when using the picker to select the current tab, even when it is already the current tab.

## 😯 Current Behavior

onSelectionChange is not called when selecting the current tab via the Picker.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | release testing ~3.15.x |
| Browser          | Chrome (OSX) Safari (iOS) |
| Operating System | OSX, iOS) |

## 🧢 Your Company/Team
RSP

**Comment by snowystinger** [comment]
Why did we want this behavior. The way it's currently behaving makes sense to me. Can we close this?

**Comment by ktabors** [comment]
Stale issue, closing.
