### ISSUE TITLE
TableView documentation uses swapi.dev, which has gone dowm

### ISSUE THREAD

**Issue by majornista** [adobe/react-spectrum#2691]
# 🐛 Bug Report 

[TableView Asynchronous loading example](https://react-spectrum.adobe.com/react-spectrum/TableView.html#asynchronous-loading) no longer works because https://swapi.dev/api/people/?search= is down.

## 🤔 Expected Behavior

The API returns valid results that can be returned asynchronously.

## 😯 Current Behavior

The [TableView Asynchronous loading example](https://react-spectrum.adobe.com/react-spectrum/TableView.html#asynchronous-loading) never populates with items.

## 💁 Possible Solution

We need to replace the API from which results are returned for the TableView Asynchronous loading example. Seems like a new mirror has appeared at: https://swapi.py4e.com/api/people/?search=

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
relevant https://github.com/phalt/swapi/issues/149#issuecomment-994711761
