### ISSUE TITLE
An error in @react-aria/datepicker 3.0.0-alpha.2

### ISSUE THREAD

**Issue by giangha08** [adobe/react-spectrum#2703]
# 🐛 Bug Report 

We got this error when we are implementing DatePicker of react-specttrum.

## 🤔 Expected Behavior

N/A

## 😯 Current Behavior

There is an error in the hook of @react-aria/datepicker. 
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/datepicker/src/utils.ts
![image](https://user-images.githubusercontent.com/45277074/147070876-e95f6ace-c894-415d-9288-95e67dd9e2c8.png)

![image](https://user-images.githubusercontent.com/45277074/147071348-e72e0527-2cb2-4844-943d-f51615d666ff.png)

## 💁 Possible Solution

N/A
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | react ts |
| Browser          | Chrome |
| Operating System | Win 10 |

**Comment by phantuantu24** [comment]
I rewrite my code as below
![image](https://user-images.githubusercontent.com/61622431/147182344-f864717e-0d8d-423b-a714-803d081ad743.png)
Then I get new error
![image](https://user-images.githubusercontent.com/61622431/147182409-c8d1255a-2266-4660-944c-cead318fed27.png)

**Comment by reidbarber** [comment]
@phantuantu24 try `theme={defaultTheme}` instead of `defaultTheme={defaultTheme}`

**Comment by phantuantu24** [comment]
> @phantuantu24 try `theme={defaultTheme}` instead of `defaultTheme={defaultTheme}`

Thank you so much, my problem is fixed.

**Comment by phantuantu24** [comment]
@reidbarber I couldn't find any documentation about @react-aria/datepicker, do you have anything useful to use it

**Comment by reidbarber** [comment]
@phantuantu24 This package is still in alpha so there is no documentation yet. You could look at React Spectrum's DatePicker as an example though: https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/datepicker/src/DatePicker.tsx

**Comment by phantuantu24** [comment]
Thank you a lot.

**Comment by reidbarber** [comment]
Closing this out, feel free to re-open or create an issue if there are any other problems!
