### ISSUE TITLE
yarn start:docs leads to 404 page not found without full path

### ISSUE THREAD

**Issue by isaiahtaylor** [adobe/react-spectrum#2715]
# 🙋 Documentation Request

Following the guide [here](https://react-spectrum.adobe.com/contribute.html) on MacOS:

```bash
yarn install
yarn start:docs
```

This ends with "Built in XX.XXs". If you navigate to http://localhost:1234/ like the guide recommends, you get a "404: Page not found" error. Even appending react-spectrum on the end with get you a 404; the only thing that works is the full path:

http://localhost:1234/react-spectrum/index.html

I would recommend adding that full path the the Contribution guide to save some folks a few minutes. Thanks!

## 🧢 Your Company/Team

External

**Comment by devongovett** [comment]
It was probably broken when we updated the dev dependencies recently.
