### ISSUE TITLE
TreeView Story is broken

### ISSUE THREAD

**Issue by isaiahtaylor** [adobe/react-spectrum#2716]
# 🙋 Documentation Request

The TreeView story (just called "Tree" in the Storybook menu) does not work.

Here's the default example:
![image](https://user-images.githubusercontent.com/12981251/147513732-f75d7cf1-3693-49e7-99f8-1017af093e8f.png)
It appears to render the root nodes correctly, but it is non-interactive. Clicking the labels or arrows does not reveal children.

The "Sections" example shows no children: 
![image](https://user-images.githubusercontent.com/12981251/147513781-d74f2c49-abc0-4705-8814-1c500b6525cf.png)

"Static" and "Static Sections" display the same issues.

This can reproduced by following the [Contribute](https://react-spectrum.adobe.com/contribute.html) guide on MacOS.

```bash
➜  ~ yarn --version
1.22.10
➜  ~ node --version
v14.15.5
```

## 🧢 Your Company/Team

External

**Comment by devongovett** [comment]
This component is unfinished. Actually, it's barely started. I would not expect it to work. There are several components like this in the storybook. Basically, if it's not documented on our website then it's not ready yet. 😊

**Comment by isaiahtaylor** [comment]
Makes sense, thank you!
