### ISSUE TITLE
Cannot read properties of undefined (reading 'focusNext')

### ISSUE THREAD

**Issue by phantuantu24** [adobe/react-spectrum#2717]
# 🐛 Bug Report 

## 🤔 Expected Behavior

Type month and it will be auto focus to the next, after literal ("/")

## 😯 Current Behavior

I met the error as below
![image](https://user-images.githubusercontent.com/61622431/147561999-3ee77a75-3796-4bea-bc1b-023f05e61267.png)

I think it maybe relate to this
![image](https://user-images.githubusercontent.com/61622431/147562121-878ad40f-7d26-4db7-bbb4-2e2b3593b782.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          | Chrome
| Operating System | Win10

**Comment by reidbarber** [comment]
Are you using this within a [FocusScope](https://react-spectrum.adobe.com/react-aria/FocusScope.html)?

> To get a focus manager, call the useFocusManager hook from a component within the FocusScope.

**Comment by phantuantu24** [comment]
> Are you using this within a [FocusScope](https://react-spectrum.adobe.com/react-aria/FocusScope.html)?
> 
> > To get a focus manager, call the useFocusManager hook from a component within the FocusScope.

I using focusScope in DatePickerInput as wrapper
![image](https://user-images.githubusercontent.com/61622431/148157626-3ade7b84-1a4a-465b-bc6e-2073e406882d.png)
And DatePickerField is as children
![image](https://user-images.githubusercontent.com/61622431/148157732-423daa0a-6d4b-4372-95dc-c050e0873e93.png)

**Comment by reidbarber** [comment]
Don't see anything wrong at first glance. Would you be able to reproduce this in a codesandbox, where we can have a closer look?

**Comment by phantuantu24** [comment]
my code in code sandbox here https://codesandbox.io/s/cocky-haibt-i8u1o?file=/src/App.tsx

**Comment by phantuantu24** [comment]
@reidbarber I found the problem. It relates to my yarn.lock. Everything ok after I delete it and re-install yarn. Thank you for your support. So I will close it issue.
