### ISSUE TITLE
An error in @react-aria/datepicker 3.0.0-alpha.2 with focusNext()

### ISSUE THREAD

**Issue by phantuantu24** [adobe/react-spectrum#2719]
# 🐛 Bug Report 

We got this error when we are implementing DatePicker of react-specttrum. when I finish type month then we get the errror

## 🤔 Expected Behavior

N/A

## 😯 Current Behavior

I press the right arrow on keyboard or I finish type month when I get the error
![image](https://user-images.githubusercontent.com/61622431/147720822-ae490157-2329-4123-82f8-2879420e71bd.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0.0-alpha.2
| Browser          | Chrome
| Operating System | Win10

**Comment by snowystinger** [comment]
I see you're the author of both this and https://github.com/adobe/react-spectrum/issues/2717
What is different about them? or can I close this one as a duplicate?

**Comment by phantuantu24** [comment]
yes, then we can discuss on an issue #2717
