### ISSUE TITLE
defaultOpen should not be respected if disabled or readonly

### ISSUE THREAD

**Issue by Alphy11** [adobe/react-spectrum#2736]
# 🐛 Bug Report 

If you call `useSelectState({ isDisabled: true, defaultOpen: true })` the menu will default to open.

## 🤔 Expected Behavior

disabled should override the defaultOpen since disabled selects cannot be opened.

## 😯 Current Behavior

If you call `useSelectState({ isDisabled: true, defaultOpen: true })` the menu will default to open.

## 💁 Possible Solution

We can check this before passing to MEnuTrigger here: https://github.com/adobe/react-spectrum/blob/main/packages/@react-stately/select/src/useSelectState.ts#L32

## 🔦 Context

It's a pretty minor bug, and rarely comes into play.  But seems legitimately incorrect behavior.

## 💻 Code Sample

useSelectState({ isDisabled: true, defaultOpen: true })

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🕷 Tracking Issue (optional)

This is totally a minor bug, I am happy to submit an MR if the maintainers are amenable to the solution

**Comment by LFDanLu** [comment]
IMO the user specified open state feels like it should be unaffected from the disabled state of the select button but I do agree that it does feel buggy. I'll bring this up with the team

**Comment by LFDanLu** [comment]
The team was a bit unsure either, but seeing as the select popover can still be closed via Escape or by clicking outside of the popover even with `isDisabled` being provided I'm leaning towards keeping the current behavior. By accepting what the user provides to the hook at face value, we make no assumptions of their use case.

**Comment by Alphy11** [comment]
Hrrrm.  At first I think I agreed that it's better to not break current behavior since it can't create a broken user experience.  But thinking more, I think the fact it can be closed makes it MORE broken.  Since now a user can see it as opened, then close it, and be unable to open it again, which feels pretty broken.

That said, this is a pretty tiny piece of user experience 🤷 and matters pretty little, especially since it's more of a bug-case.

**Comment by LFDanLu** [comment]
Closing this for now since as discussed previously we want to give the implementor full control over the state of the select.
