### ISSUE TITLE
useSelect implements FocusEvents but does not call onFocusChange

### ISSUE THREAD

**Issue by Alphy11** [adobe/react-spectrum#2744]
# 🐛 Bug Report 

The [useSelect](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/select/src/useSelect.ts) hook takes in props that implement FocusEvents, which exposes [onFocusChange](https://github.com/adobe/react-spectrum/blob/885b5e6b84253925b2ac9f7f2766417c63b654b5/packages/%40react-types/shared/src/events.d.ts#L75).  It puts the rest of the focus events onto the `triggerProps` return value [here](https://github.com/adobe/react-spectrum/blob/885b5e6b84253925b2ac9f7f2766417c63b654b5/packages/@react-aria/select/src/useSelect.ts#L147).  But does not use `useFocus` to do so, and so loses the `onFocusChange` event by doing so.  

## 🤔 Expected Behavior

onFocusChange should be called on focus.

## 😯 Current Behavior

onFocusChanged is not called on focus.

## 💁 Possible Solution

In useSelect, we can begin using `useFocus` to chain focus handlers together.  I am not sure the effects of this though, since the focus handlers are short circuited if the state is already focused.   We could also theoretically just call onFocusChanged manually as well, but that seems like we will cause another bug from lack of abstraction down the line.  🤷 

If someone has an idea, I am happy to submit and MR.  But I definitely am still getting my bearings on the library, and don't know what effects changing something like this would have.

## 🔦 Context

Honestly, just uncovered on a unit test we run on all of our interactible components to see if onFocus/onBlur happen, I am working around by just not testing that specific method, since it's just a convenience method on top of onFocus/onBlur.

## 💻 Code Sample

Quick repro of it not being called: https://codesandbox.io/s/silly-panka-vfmb2?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

TheTradeDesk

**Comment by snowystinger** [comment]
Thanks for the issue and codesandbox to repro it! I do see that it's not being called, and I see we list it in our useSelect props https://react-spectrum.adobe.com/react-aria/useSelect.html seems like a bug
Looks like we manually call onFocus and onBlur for certain aspects, menu vs trigger https://github.com/adobe/react-spectrum/blob/3366ae36b3ddefbf67bfd084caaf58bb89ed345b/packages/%40react-aria/select/src/useSelect.ts#L154

In the three places we do that, I think we'd need to call onFocusChange as well

**Comment by lishichengyan** [comment]
I can work on this one!

**Comment by lishichengyan** [comment]
could we close the issue since the pr has been merged? thanks!
