### ISSUE TITLE
useNumberField ignores name prop

### ISSUE THREAD

**Issue by Alphy11** [adobe/react-spectrum#2745]
# 🐛 Bug Report 

useNumberField swallows `name` prop.  

## 🤔 Expected Behavior

`name` should be added into inputProps.

## 😯 Current Behavior

name is ignored completely.

## 💁 Possible Solution

Adding it here:
https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/numberfield/src/useNumberField.ts#L179

Or, potentially adding it as a DOMprop?

## 🔦 Context

I have to manually re-apply name when using this hook.

## 💻 Code Sample

https://codesandbox.io/s/amazing-zeh-9lu60?file=/src/App.js
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

TheTradeDesk

**Comment by Alphy11** [comment]
It's also SLIGHTLY worse, in that because of [this line](https://github.com/adobe/react-spectrum/blob/c8381816b644e0a495106e3404637bc9e8aad084/packages/%40react-aria/textfield/src/useTextField.ts#L145) it will return { name: undefined } so if you spread it like:
```ts
<input name={name} {...inputProps} />
```
name will be overwritten with undefined.

**Comment by Alphy11** [comment]
this is also true of placeholder, and likely others.  Should we pass all of props into usetextField, then merge others over top?

**Comment by snowystinger** [comment]
Thanks for the codesandbox! I see the issue you're describing, it does seem like it should make it through to the input.
You're welcome to make a PR to handle it, seems like you have an idea of how to do it. We're happy to help if you run into any difficulties.

**Comment by Alphy11** [comment]
Will do sometime next week!
