### ISSUE TITLE
TableView fails to render on server side

### ISSUE THREAD

**Issue by solimant** [adobe/react-spectrum#2747]
# 🐛 Bug Report 

`TableView` seems to fail during server-side rendering (SSR).

## 🤔 Expected Behavior

`TableView` should not fail to render on server side.

## 😯 Current Behavior

`TableView` seems to fail during server-side rendering and throws the following error:
```
window is not defined
```

## 💁 Possible Solution

Surround the render with a conditional:
```tsx
{typeof window !== 'undefined' && <TableView />}
```

## 🔦 Context

We're using NextJS, so SSR is pretty common.

## 💻 Code Sample

Any `TableView` excerpt from the online docs will fail during SSR.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.15.1
| Browser          | All
| Operating System | All

## 🧢 Your Company/Team

Adobe/RSP

## 🕷 Tracking Issue (optional)

N/A

**Comment by reidbarber** [comment]
Looks like this line is the culprit:

https://github.com/adobe/react-spectrum/blob/3366ae36b3ddefbf67bfd084caaf58bb89ed345b/packages/%40react-aria/grid/src/useHighlightSelectionDescription.ts#L35

**Comment by snowystinger** [comment]
yeah, after discussing with @solimant , i think we just need to check if window exists before checking if ontouchstart is in it

**Comment by reidbarber** [comment]
Sounds good. There may be a few more we want to handle while we're at it:

https://github.com/adobe/react-spectrum/blob/3366ae36b3ddefbf67bfd084caaf58bb89ed345b/packages/%40react-aria/dnd/src/utils.ts#L56

https://github.com/adobe/react-spectrum/blob/9ba765f71bdde97d1545d91f76326e61bd35ae30/packages/%40react-aria/datepicker/src/useDateSegment.ts#L251

**Comment by snowystinger** [comment]
Sure, ones that happen during events like onFocus probably wont' be an issue, just FYI, since you can't focus something during SSR.

**Comment by solimant** [comment]
Thanks @reidbarber, @snowystinger - I've opened #2754 to fix this.
