### ISSUE TITLE
Conflicting "Intl" TS version definitions between @internationalized date & number

### ISSUE THREAD

**Issue by LucasUnplugged** [adobe/react-spectrum#2751]
# 🐛 Bug Report 

- `@internationalized/date` depends on TS lib `es2021.intl` to avoid build errors related to the `hourCycle` prop, which did not exist in earlier versions.
- `@internationalized/number` picks up the definition of `NumberFormat` from TS lib `es2021.intl`, which requires the implementation of these methods, neither of which are currently implemented: `formatRange` and `formatRangeToParts`.
- Therefore, if `es2121.intl` is excluded from tsconfig, then `@internationalized/date` throws errors; when it's included, `@internationalized/number` throws errors.

## 🤔 Expected Behavior

Building projects using both `@internationalized/date` and `@internationalized/number` should work without forcing conflicting versions.

## 😯 Current Behavior

With tsconfig libs and target matching this repo...
```json
{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "es6",
      "dom",
      "dom.iterable",
      "es2016.array.include",
      "es2017.object",
      "es2017.intl",
      "es2019.array",
      "esnext.intl",
    ]
  }
}
```
...I get the following build errors:
```
../../node_modules/@formatjs/ecma402-abstract/types/relative-time.d.ts(28,67): error TS2694: Namespace 'Intl' has no exported member 'RelativeTimeFormatUnit'.
../../node_modules/@formatjs/ecma402-abstract/types/relative-time.d.ts(35,17): error TS2694: Namespace 'Intl' has no exported member 'ResolvedRelativeTimeFormatOptions'.
../../node_modules/@formatjs/ecma402-abstract/types/relative-time.d.ts(36,19): error TS2694: Namespace 'Intl' has no exported member 'ResolvedRelativeTimeFormatOptions'.
../../node_modules/@internationalized/date/dist/types.d.ts(341,44): error TS2339: Property 'hourCycle' does not exist on type 'DateTimeFormatOptions'.
```

---

With tsconfig libs and target updated to a more recent standard...
```json
{
  "compilerOptions": {
    "target": "esnext",
    "lib": [
      "dom",
      "dom.iterable",
      "es2016.array.include",
      "es2017.object",
      "es2017.intl",
      "es2019.array",
      "esnext",
    ]
  }
}
```
...I get the following build errors:
```
../../node_modules/@internationalized/number/dist/types.d.ts(8,14): error TS2420: Class 'NumberFormatter' incorrectly implements interface 'NumberFormat'.
  Type 'NumberFormatter' is missing the following properties from type 'NumberFormat': formatRange, formatRangeToParts
```

## 💁 Possible Solution

Implementing the methods `formatRange` and `formatRangeToParts`, as per this interface from `es2021`:
```TS
    formatRange(startDate: number | bigint, endDate: number | bigint): string;
    formatRangeToParts(startDate: number | bigint, endDate: number | bigint): Intl.NumberFormatPart[];
```

## 🔦 Context

I'm using various @react-aria packages to help me build a component lib and design system. So far, I'm using these packages, specifically:
```
    "@react-aria/button": "3.2.2",
    "@react-aria/checkbox": "^3.2.3",
    "@react-aria/focus": "^3.5.0",
    "@react-aria/interactions": "3.7.0",
    "@react-aria/numberfield": "^3.1.1",
    "@react-aria/radio": "^3.1.6",
    "@react-aria/searchfield": "^3.2.2",
    "@react-aria/select": "^3.6.0",
    "@react-aria/ssr": "^3.1.0",
    "@react-aria/switch": "^3.1.3",
    "@react-aria/tabs": "^3.1.0",
    "@react-aria/textfield": "^3.5.0",
    "@react-aria/utils": "3.11.0",
    "@react-stately/numberfield": "^3.0.2",
    "@react-stately/searchfield": "^3.1.3",
    "@react-types/shared": "3.10.1",
```

## 💻 Code Sample

I don't believe codesanbox would capture this issue, as a TS build issue — the runtime is unaffected. If the above context is insufficient, I can create a repo with a minimal version of my setup.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | See above
| react-stately   | See above
| Typescript          |  4.5.4
| Node          |  16.5.0
| Operating System | MacOS 12.0.1

## 🧢 Your Company/Team

N/A

**Comment by justintaylor-dev** [comment]
+1 React-Spectrum no longer working on new projects due to this issue.

**Comment by LFDanLu** [comment]
Verified the TS errors with the new config, saw some other errors come up when running the check that we'll need to investigate as well
