### ISSUE TITLE
Missing SideNav NPM Package

### ISSUE THREAD

**Issue by care4** [adobe/react-spectrum#2752]
I noticed the SideNav package within the @react-spectrum storybook project. Yet, I'm unable to find the package within [react-spectrum NPM](https://www.npmjs.com/org/react-spectrum). It looks like this package has been in development and closed for a while (refer to #1095). 

What is the best way to access this package and is there a way to import from NPM/Yarn?

**Comment by conao3** [comment]
Just reference, this issue moved to discussions (https://github.com/adobe/react-spectrum/discussions/2753)
