### ISSUE TITLE
useMove: Using preventDefault will make the input element unusable

### ISSUE THREAD

**Issue by mcdu11** [adobe/react-spectrum#2778]
# 🐛 Bug Report 

Using preventDefault will make the input element unusable

## 🤔 Expected Behavior

useMove acts on the parent element, the child element input should be able to enter

## 😯 Current Behavior

input element cannot be used

## 💁 Possible Solution

remove e.preventDefault() statement

## 💻 Code Sample

https://codesandbox.io/s/domevent-o5fmn?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  3.7.0   |
| Browser          |    Chrome     |
| Operating System | MacOS |

**Comment by devongovett** [comment]
The preventDefault is necessary to prevent e.g. text selection from occurring while dragging, and other undesired behaviors. I think one way to solve this would be to place mouse handlers on the input as well and stopPropagation on them so they don't reach the parent. That way, when you also try to text select within the input, it doesn't try to drag the parent element also.

**Comment by mcdu11** [comment]
> The preventDefault is necessary to prevent e.g. text selection from occurring while dragging, and other undesired behaviors. I think one way to solve this would be to place mouse handlers on the input as well and stopPropagation on them so they don't reach the parent. That way, when you also try to text select within the input, it doesn't try to drag the parent element also.

Thank you so much! My problem is solved. But I don't quite understand the strange behavior brought by preventDefault
