### ISSUE TITLE
Can't select/highlight text within an overlay using `useOverlay` and `FocusScope`

### ISSUE THREAD

**Issue by ashharrison90** [adobe/react-spectrum#2798]
# 🐛 Bug Report 

Can't select text using the mouse when using `useOverlay` + `FocusScope`

## 🤔 Expected Behavior

I should be able to click and drag to highlight text within an overlay

## 😯 Current Behavior

No highlighting is shown

## 💁 Possible Solution

Could be way off here, but there's this comment from another issue that seems relevant: https://github.com/adobe/react-spectrum/issues/1604#issuecomment-781574668

The recommended solution here is to set `tabindex=-1` on a containing div. That works, but it feels like something that the `useOverlay` hook should handle. The `useDialog` hook already sets this [here](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/dialog/src/useDialog.ts#L65), so I'm wondering whether `tabindex=-1` should be added to the `overlayProps` in the `useOverlay` hook [here](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/overlays/src/useOverlay.ts#L139)?

## 🔦 Context

An example is we have a side drawer component that slides out over everything. We want focus to be contained, so `useOverlay` + `FocusScope` seems like the appropriate tools to use(?), but this drawer can also contain debug information etc so it is useful to be able to copy/paste text from it.

## 💻 Code Sample

see e.g. https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker.tsx#L121

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/focus | 3.5.0 |
| @react-aria/overlays | 3.7.3 | 
| Browser          | Chrome 97.0.4692.99 |
| Operating System | macOS Monterey 12.0.1 |

**Comment by reidbarber** [comment]
Here's a [codesandbox](https://codesandbox.io/s/useoverlay-focusscope-0h9uv?file=/src/ModalDialog.js) showing the issue. I think the solution you suggested would fix that. Seems correct, as long as it's okay to remove all overlays from navigation flow, which I'm not sure about.

**Comment by devongovett** [comment]
You mentioned it already, but I think this is handled by `useDialog`. You should be using that hook in addition to `useOverlay` for this use case, as it also handles other aspects like adding the `dialog` ARIA role.

**Comment by ashharrison90** [comment]
ahhh ok, i think in my head i was associating `useDialog` only with modals, when actually the [docs page](https://react-spectrum.adobe.com/react-aria/useDialog.html) states:
> A dialog is an overlay shown above other content in an application.

in that case i think you're right and we should be using `useDialog` as well. thanks for the clarification!

**Comment by devongovett** [comment]
Yeah. We are thinking of ways to simplify our overlay API a bit so it's more clear and easier to use. Sorry for the confusion!
