### ISSUE TITLE
Combobox auto selects hovered item on blur

### ISSUE THREAD

**Issue by Brandawg93** [adobe/react-spectrum#2809]
### Expected Behaviour
Item not explicitly selected should not be selected

### Actual Behaviour
Item selected when you tab off of combobox and are hovering over an option

### Reproduce Scenario (including but not limited to)
Playground

#### Steps to Reproduce
1. Go to [playground](https://codesandbox.io/s/y8if9?file=/src/App.js)
2. Open combobox
3. Hover over option
4. Hit tab
5. Option is selected

#### Platform and Version
Latest Chrome on latest Mac OS

#### Sample Code that illustrates the problem
View in playground

#### Logs taken while reproducing problem
View in playground

**Comment by reidbarber** [comment]
I think this is the desired behavior. We basically want hovering over an item to be the equivalent of keyboard focusing an item. And using a keyboard during a hover should do the same action as if the user was already using the keyboard (i.e. arrow up/down to focus item above or blow, or tab/enter to select.)

**Comment by Brandawg93** [comment]
That makes sense. Just wanted to double check that this is expected behavior.

**Comment by reidbarber** [comment]
Definitely, it does feel strange at first, but a user might want to switch modalities while navigating.
