### ISSUE TITLE
Cards in WaterfallLayout aren't always brought into view

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#2810]
# 🐛 Bug Report 

Found in testing:
- Sometimes the cards in Waterfall layout don't scroll completely into view. Not the tall ones, but the shorter ones that should be able to fit. It's only reproducible intermittently. I've done it mostly in 'Waterfall layout - quiet cards'. Tab to the cardview, press down until cards only partially scroll into view. (RS)

## 🤔 Expected Behavior

Cards that can fit into the current viewport should be brought completely into view

## 😯 Current Behavior

Cards sometimes aren't brought into view completely

## 💁 Possible Solution

I've reproduced this myself, will need to look into improving the scrollToItem func in CardView

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

RSP

**Comment by dannify** [comment]
See S2 version
