### ISSUE TITLE
DatePicker and DateRangePicker Overlay opens too far above label

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum#2816]
# 🐛 Bug Report 

On iPad when DateRangePicker and DatePicker opens the calendar above the picker's input field, there is extra padding, like 75x instead of being just above the label. DatePicker does this too. Sometimes it opens above with ~20px, but closing, scrolling, and reopening will cause it more in the 75px range.

## 🤔 Expected Behavior

When the calendar selector overlay opens above the input field it should be about 15px above it, just above the label. See a desktop browser like Chrome on OSX for the correct positioning.

## 😯 Current Behavior

When the calendar selector overlay opens above the input field it is positioned more in the 40px to 100px range on an iPad. 

<img width="318" alt="image" src="https://user-images.githubusercontent.com/309540/152885595-d0e151d3-1984-4108-964a-5b67c9ef99fa.png">

## 🔦 Context

Found while testing the new DateRangePicker docs. There was concern that it was related to a width and scrolling issues, but it isn't because there is no horizontal scroll on iPad. I also tested this with the first draft of the horizontal scrolling fix and the issue persisted.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | master |
| Browser          | Safari |
| Operating System | iOS iPad |

## 🧢 Your Company/Team
RSP

**Comment by devongovett** [comment]
Appears to actually be an issue with popover positioning code. I can reproduce on the DialogTrigger docs as well. Seems to be related to whether the Safari address bar is visible or collapsed. When collapsed, positioning is wrong. If you tap on it to show it again, then it is correct. Guessing we need to do something with the visual viewport there.

**Comment by ktabors** [comment]
No longer able to reproduce.
