### ISSUE TITLE
Nested `FocusScope` breaks parent `FocusScope`'s containment

### ISSUE THREAD

**Issue by rgrove** [adobe/react-spectrum#2817]
# 🐛 Bug Report 

When a `<FocusScope>` that doesn't contain focus is rendered as a child of a `<FocusScope>` that does contain focus, the <kbd>Tab</kbd> and <kbd>Shift+Tab</kbd> keys can be used to move focus outside the parent scope, breaking containment.

## 🤔 Expected Behavior

When multiple focus scopes are nested, focus should be contained within the nearest scope that has containment enabled even if an inner scope doesn't have containment enabled.

## 😯 Current Behavior

When multiple focus scopes are nested and an inner scope doesn't have containment enabled, focus is no longer contained within an outer scope that does have containment enabled. 

## 💁 Possible Solution

I'm not familiar with `<FocusScope>`'s implementation and haven't dug in yet, but I'll update this when I do unless someone beats me to it!

## 🔦 Context

We're displaying an image lightbox as a modal, with `<FocusScope autoFocus contain returnFocus>`.

Within the lightbox, the user can use a toolbar button to expand an "image details" sidebar. The sidebar uses `<FocusScope autoFocus returnFocus>` because we want it to receive focus when expanded and return focus to the toolbar when collapsed, but we don't want to prevent the user from tabbing back to other controls within the lightbox while the sidebar is open.

However, the user should never be able to tab outside of the lightbox itself, because the lightbox is a modal that obscures and should prevent interacting with the rest of the document.

## 💻 Code Sample

Reduced test case demonstrating the issue:

https://codesandbox.io/s/react-aria-focus-nested-focusscope-breaks-parent-scopes-containment-2e8m7?file=/src/App.js

https://user-images.githubusercontent.com/1465/152889308-d19306a7-b303-4be6-9ef0-018606ffcfb4.mp4

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `@react-aria/focus` | 3.5.0 |
| Browser          | Tested in Firefox 96.0.3, Chrome 98.0.4758.80, Safari 15.2 |
| Operating System | macOS 12.1 |

This issue does not appear to be browser- or OS-dependent.

## 🧢 Your Company/Team

[SmugMug](https://www.smugmug.com)

**Comment by snowystinger** [comment]
Thanks for the codesandbox, very helpful, I can see the issue and I understand your use case. Definitely seems like a bug to me. Probably the inner one is stopping the Tab event from reaching the outer one, maybe in the useRestoreFocus hook, around here https://github.com/adobe/react-spectrum/blob/dfe72ee076f7ca27728d0b6b4c1ef86e11191ece/packages/%40react-aria/focus/src/FocusScope.tsx#L436

**Comment by rgrove** [comment]
Thanks for the pointer, @snowystinger!

I've poked at this a bit today but haven't yet gotten anywhere useful. It doesn't seem to be as simple as allowing inner <kbd>Tab</kbd> events to propagate, but I haven't yet fully wrapped my head around the various ways `useFocusContainment()` and `useRestoreFocus()` can interact when dealing with nested scopes.

Here's a failing `FocusScope` test that reproduces the issue, in case anyone else wants to play with this:

```js
it.only('should lock tab navigation inside an outer focus scope with contain when a nested focus scope does not have contain', function () {
  function Test() {
    let [isOpen, setOpen] = React.useState(false);
    return (
      <div>
        <input data-testid="outsideBefore" />
        <FocusScope autoFocus contain restoreFocus>
          <button data-testid="open" onClick={() => setOpen(true)} />
          {isOpen &&
            <div>
              <div>
                <FocusScope autoFocus restoreFocus>
                  <input data-testid="child1" />
                  <input data-testid="child2" />
                  <input data-testid="child3" />
                </FocusScope>
              </div>
            </div>
          }
        </FocusScope>
        <input data-testid="outsideAfter" />
      </div>
    );
  }

  let {getByTestId} = render(<Test />);
  let open = getByTestId('open');

  expect(document.activeElement).toBe(open);
  userEvent.click(open);

  let child1 = getByTestId('child1');
  let child2 = getByTestId('child2');
  let child3 = getByTestId('child3');

  expect(document.activeElement).toBe(child1);
  userEvent.tab({shift: true});
  expect(document.activeElement).toBe(open);
  userEvent.tab();
  expect(document.activeElement).toBe(child1);
  userEvent.tab();
  expect(document.activeElement).toBe(child2);
  userEvent.tab();
  expect(document.activeElement).toBe(child3);
  userEvent.tab();
  expect(document.activeElement).toBe(open);
  userEvent.tab({shift: true});
  expect(document.activeElement).toBe(child3);
});
```

**Comment by snowystinger** [comment]
So I just found an interesting comment in our code

https://github.com/adobe/react-spectrum/blob/dfe72ee076f7ca27728d0b6b4c1ef86e11191ece/packages/%40react-aria/focus/src/FocusScope.tsx#L268

This may be a difficult problem to solve, but I'll bring it up in the team meeting tomorrow and try to determine what we want to do about it. As is, I can definitely see the frustration.

**Comment by snowystinger** [comment]
Thanks for the test, I'll bring it up in our weekly team meeting to see if anyone has any ideas.

**Comment by snowystinger** [comment]
I can no longer reproduce on the latest release. The codesandbox can be updated to test it, however, I have run out of codesandboxes, so I can't link one here.
Closing, but let us know if you are still facing issues with it.
