### ISSUE TITLE
Buttons with `type="reset"` don't reset the Form properly

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#2825]
# 🐛 Bug Report 

Some issues regarding Form reseting via buttons with type="reset":
- Enter/Space don't trigger the form reset
- Controlled components in React don't play well with native reset. Resolve this by adding `onReset` so user can reset their controlled components properly
- Check components that are controlled under the hood by default (e.g. NumberField)

Add docs when the above are fixed

## 🤔 Expected Behavior

Forms should be reset if a button w/ type="reset" is pressed

## 😯 Current Behavior

Forms work with buttons of type="reset". `onReset` should be a supported callback

## 💁 Possible Solution

PR in progress: https://github.com/adobe/react-spectrum/pull/2824

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

RSP

**Comment by snowystinger** [comment]
One other thing to keep in mind, setting a components value, such as checked or unchecked may not have aligned with what the browser considers a reset, so it might be that you default a checkbox to true and it's currently true.
Reset is called, checkbox is "unchecked" natively but because the react value was already true, it won't cause a re-render and the checkbox may be out of sync with react

**Comment by LFDanLu** [comment]
Hrm, can't seem to reproduce the above, tried making the checkbox in the "form with submit" story uncontrolled and it exhibit that behavior (prob cuz the Checkbox is inherently controlled right?)

**Comment by snowystinger** [comment]
possibly, I'll need to spend a bit of time trying to remember why this is coming up in my head as a worry.

**Comment by LFDanLu** [comment]
Actually I think I reproduced it with Switch, hrm

**Comment by snowystinger** [comment]
yeah, so a thought I'd had was to use Form context to send a function that gets invoked during onReset. RSP components subscribed to it could reset to actual default and force a re-render, but I'm not sure we want to do that, it's a bit against React and ties some implementation details together, for instance, it'd only work for React Spectrum not react-aria
