### ISSUE TITLE
useMenuTrigger doesn't set "disabled" attribute on button when isDisabled is true

### ISSUE THREAD

**Issue by mciastek** [adobe/react-spectrum#2844]
# 🐛 Bug Report 

When using `useMenuTrigger()` and when `isDisabled` is passed to the component, trigger props doesn't include `disabled` property for `button` element. This results in `button` trigger being still active (able to interact with) when list revealing is expanding.

## 🤔 Expected Behavior

Props for button received from `useMenuTrigger()` hook include `disabled` attribute, which can be passed directly to `<button/>`.

## 😯 Current Behavior

Props for button received from `useMenuTrigger()` hook doesn't include `disabled` attribute. It results in `<button/>` being active despite that trigger is blocked. It feel odd, when using `isDisabled` property on select component.

## 💁 Possible Solution

Just add `disabled` property in object returned from `useMenuTrigger()` hook:
https://github.com/adobe/react-spectrum/blob/40d086a558b5a2b77e0816c0820e449edfa36b5f/packages/%40react-aria/menu/src/useMenuTrigger.ts#L122-L126

Of course `disabled` should be true only when `isDisabled` is true.

## 🔦 Context

I'm using `useSelect()` hook and passing `isDisabled` to my select component doesn't lock `<button/>`. It's a bit confusing.

## 💻 Code Sample

Code sample - https://codesandbox.io/s/focused-spence-rggqo?file=/src/App.tsx

Props preview
![Screenshot 2022-02-11 at 15 48 09](https://user-images.githubusercontent.com/3169629/153613063-3071e888-1719-47d6-b068-787b43a643be.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.12.0
| react-stately   | 3.11.0
| Browser          | Chrome (latest stable)
| Operating System | macOS

**Comment by snowystinger** [comment]
I'm going to close this. If anyone finds it confusing enough to warrant additional description, we accept contributions. Thank you for understanding.
