### ISSUE TITLE
Focus inconsistency between Select and Combobox when using ListBox -- focus not working.

### ISSUE THREAD

**Issue by torgeadelin** [adobe/react-spectrum#2853]
# 🐛 Bug Report 

I'm building a combo-box, and I'm reusing the ListBox implementation (according to docs). I'm also using `ListBox` for my `Select` component. My Options components are wrapped inside `<FocusRing>` and I'm not manually applying inline styling on the `li` elements by taking advantage of the `isFocused` prop returned by the `useOption` hook, but rather I rely on the `useListBox` doing it's job and let it handle it for me. This works correctly when I render a plain `ListBox` or a `Select` component (which is based on `ListBox`). When I try to render a `ComboBox` component which also relies on the same `ListBox` it will not handle keyboard focus correctly. I'm not able to focus between the options when the listbox is open. This works correctly on the previous 2 examples.

Here's a codesandbox which illustrates all examples https://codesandbox.io/s/gallant-chatelet-u68itq?file=/src/App.tsx

## 🤔 Expected Behavior

I'm expecting `useComboBox` to handle the keyboard focus the same way `useListState` or `useSelectState` does.

## 😯 Current Behavior

Keyboard navigation not working inside the listbox in Combobox unless I use inline styling based on `isFocused` returned by `useOption`.

## 🔦 Context

Building an accessible combobox without applying inline style for focus.

## 💻 Code Sample

https://codesandbox.io/s/gallant-chatelet-u68itq?file=/src/App.tsx

## 🌍 Your Environment

See package.json in codesandbox.

**Comment by torgeadelin** [comment]
It's worth mentioning that the changing options while using up/down arrows functionality actually works but the focus is not visible.

**Comment by LFDanLu** [comment]
So the difference between a select and a combobox is that a combobox will keep DOM focus in its input at all times so focus never actually makes it to the options within the listbox, hence why the FocusRing approach doesn't work. This is actually why we have a `shouldUseVirtualFocus` prop in our own ListBoxOption: https://github.com/adobe/react-spectrum/blob/902a1fc5f3fd4b0aa5626d12561fafdd1e2bddf5/packages/%40react-spectrum/listbox/src/ListBoxOption.tsx#L83-L84. Is there a particular reason why you don't want to apply the inline styles here?

**Comment by torgeadelin** [comment]
Hey! Thanks for the prompt response!

Hmm, I think the focus on the combobox will not always be on the input. If the user types something, and if there are more than one option he/she might press arrow down and manually select the option. The focus therefore should change accordingly to the potential options.

The reason I would like to rely on the FocusRing is consistency. It seems hacky to me that I need to inline the focus style in certain cases. Maybe I'm miss understanding how list box actually works. We're using ListBox and it's corresponding Option/Section components in a few places and I thought I'll be able to get the keyboard functionality/style done once and just reuse it.

Are you suggesting I should customise my listbox component to support this virtual focus the same way it's handled in spectrum?

**Comment by LFDanLu** [comment]
I see, that is indeed one approach for a combobox's focus management but I'd argue that seems more appropriate for a select element, especially since typeahead is supported within a select. IMO it feels more arduous for the user to have to shift focus to the combobox's listbox just to navigate through the list and then shift focus back to the input if they wanna further filter the list of options.

Our combobox hooks assume that focus will remain on the input at all times since we use `aria-activedescendant` in lieu of actually moving focus to the listbox options as described in the latter part of the WAI-ARIA 1.2 combobox docs: https://www.w3.org/TR/wai-aria-1.2/#combobox. Unfortunately that means you'll have to customize your listbox component to support virtual focus in the same way.

**Comment by LFDanLu** [comment]
Closing for now, feel free to reopen if you have any other concerns.
