### ISSUE TITLE
Issue with @react-aria/aria-modal-polyfill@3.4.1 distributed files

### ISSUE THREAD

**Issue by JasonKaz** [adobe/react-spectrum#2855]
# 🐛 Bug Report 
The most recent update (3.4.1) to @react-aria/aria-modal-polyfill broke our local build process.

In version 3.4.0 [this line](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/aria-modal-polyfill/src/index.ts#L39) was distributed as:
`let addNode = Array.from(mutation.addedNodes).find(node => node.querySelector == null ? void 0 : node.querySelector('[aria-modal="true"], [data-ismodal="true"]'));`

In 3.4.1 it is:
`let addNode = Array.from(mutation.addedNodes).find((node)=>node.querySelector?.('[aria-modal="true"], [data-ismodal="true"]')`

Our build broke because we are not transpiling the `?.` operator for external modules. We _could_ make it support that, but clearly something changed with the build process in this repo to change the output like that.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Adobe/Admin Console team

**Comment by snowystinger** [comment]
We updated our list of supported browsers. So my guess is that's no longer being transpiled since the major browsers can handle this and have for a while now.

I'm surprised it broke your build process though, what part did it break? test environment? node environment?

**Comment by JasonKaz** [comment]
Local development environment, using Storybook. Our system was able to build and publish the module though. So there must be some mis-match between the build webpack vs the Storybook webpack.

**Comment by snowystinger** [comment]
might be related? https://github.com/storybookjs/storybook/issues/14292

**Comment by exlame** [comment]
Chaining operator should now be removed after the last release.
https://github.com/adobe/react-spectrum/pull/2860

From the discussion here : 
https://github.com/adobe/react-spectrum/issues/2857
