### ISSUE TITLE
3.8.0 - error on ?? (nullish coalescing operator)

### ISSUE THREAD

**Issue by KutnerUri** [adobe/react-spectrum#2857]
# 🐛 Bug Report 

Version 3.8.0 just got released, including a _nullish coalescing operator_ (`??`). This breaks in certain environment, like Jest.

```
  ● Test suite failed to run

    Jest encountered an unexpected token
    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    [...]

    Details:

    /github/home/Library/Caches/Bit/capsules/44d80e1c05a5191ec871aec76c25c66afd3b0734/node_modules/.pnpm/registry.npmjs.org+@react-aria+interactions@3.8.0_react@17.0.2/node_modules/@react-aria/interactions/dist/main.js:558
        ref = ref ?? newRef;
                   ^

    SyntaxError: Unexpected token '?'

      1 | import React, { ReactNode, useRef } from 'react';
    > 2 | import { useButton } from '@react-aria/button';
        | ^
      3 | import { Link } from '@teambit/base-react.navigation.link';
```

## 🤔 Expected Behavior

code should have been compiled down to:
```ts
ref = (_ref = ref) !== null && _ref !== void 0 ? _ref : newRef;
```
Usually, typescript handles that.

## 😯 Current Behavior

Code remains with the original `??` operator:

```ts
const $103a536ab6395e4d$export$27c701ed9e449e99 = /*#__PURE__*/ ($parcel$interopDefault($hZjuk$react)).forwardRef(({ children: children , ...props }, ref)=>{
    let newRef = $hZjuk$react.useRef();
    ref = ref ?? newRef; // <---------------------
    let { pressProps: pressProps  } = $213abf3f34aca140$export$45712eceda6fad21({
        ...props,
        ref: ref
    });
    let child = ($parcel$interopDefault($hZjuk$react)).Children.only(children);
    return(/*#__PURE__*/ ($parcel$interopDefault($hZjuk$react)).cloneElement(child, // @ts-ignore
    {
        ref: ref,
        ...$hZjuk$reactariautils.mergeProps(child.props, pressProps)
    }));
});
```

**Comment by JoshK2** [comment]
I solved it with a temporary solution using the transformIgnorePatterns option in Jest.
https://jestjs.io/docs/configuration#transformignorepatterns-arraystring
```
transformIgnorePatterns: ["node_modules/(?!(@react-aria|.pnpm/.*[+/]@react-aria.*|.pnpm/@react-aria.*)/)"]
```

**Comment by 0ctothorp** [comment]
I also had problems with nullish coalescence and optional chaining in storybook.

**Comment by spahnke** [comment]
Same problem here with `@internationalized/number` version `3.0.4` and Webpack (which I can't update atm). Version `3.0.3` worked fine; version `3.0.4` has optional chaining in `dist/module.js`. I worked around that by pinning the version for now.

**Comment by yaroslav-qlicks** [comment]
> Same problem here with `@internationalized/number` version `3.0.4` and Webpack (which I can't update atm). Version `3.0.3` worked fine; version `3.0.4` has optional chaining in `dist/module.js`. I worked around that by pinning the version for now.

when any solution - please share
have exactly the same(

**Comment by devongovett** [comment]
Nullish coalescing is supported natively in all browsers we support, representing over 92% of users globally. If you are using an old version of a build tool without support, I would recommend upgrading that. https://caniuse.com/mdn-javascript_operators_nullish_coalescing

**Comment by exlame** [comment]
Having the same problem with multiple files, using Webpack 4. 

On what I understand by reading on optional-chaining with Webpack, we need to upgrade to Webpack 5 to support new versions of react-aria. https://stackoverflow.com/questions/59972341/how-to-make-webpack-accept-optional-chaining-without-babel

## Solution : Webpack 5
Webpack rely on Acorn as JavaScript parser. Acorn is supporting optional chaining from version 7.1.0 (2020-06-11) https://github.com/acornjs/acorn/blob/master/acorn-loose/CHANGELOG.md#710-2020-06-11
Webpack 

Accoring to https://webpack.js.org/blog/2020-10-10-webpack-5-release/ Webpack updated Acorn from 5 to 8 on Webpack 5.0.0

## Solution : Babel - @babel/plugin-proposal-optional-chaining
I didn't played a lot with Babel parsing node_modules, but maybe there is a way to load react-aria with babel and @babel/plugin-proposal-optional-chaining.

```
ERROR in ./node_modules/@react-aria/focus/dist/module.js 95:24
Module parse failed: Unexpected token (95:24)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   let scopeRef = $bmn4K$useRef([]);
|   let ctx = $bmn4K$useContext($0238e4b796d1715f$var$FocusContext);
>   let parentScope = ctx?.scopeRef;
|   $bmn4K$useLayoutEffect(() => {
|     // Find all rendered nodes between the sentinels and add them to the scope.
 @ ./node_modules/@react-aria/radio/dist/module.js 2:0-129 45:6-25 130:17-46
 @ ./node_modules/react-aria/dist/module.js

ERROR in ./node_modules/@react-aria/listbox/dist/module.js 90:37
Module parse failed: Unexpected token (90:37)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   } = props;
|   let data = $d786742a15de2e64$export$3585ede4d035bf14.get(state);
>   let isDisabled = props.isDisabled ?? state.disabledKeys.has(key);
|   let isSelected = props.isSelected ?? state.selectionManager.isSelected(key);
|   let isFocused = state.selectionManager.focusedKey === key;
 @ ./node_modules/react-aria/dist/module.js 22:0-79 22:0-79 22:0-79 22:0-79

ERROR in ./node_modules/@internationalized/date/dist/module.js 847:98
Module parse failed: Unexpected token (847:98)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|         let eraIndex = eras.indexOf(value.era);
|         if (eraIndex < 0) throw new Error('Invalid era: ' + value.era);
>         eraIndex = $6384333fb108a063$var$cycleValue(eraIndex, amount, 0, eras.length - 1, options?.round);
|         mutable.era = eras[eraIndex]; // Constrain the year and other fields within the era, so the era doesn't change when we balance below.
|
 @ ./node_modules/@react-aria/i18n/dist/module.js 4:0-80 146:34-54
 @ ./node_modules/react-aria/dist/module.js
```

**Comment by devongovett** [comment]
Ah, looks like the latest version of storybook is still on webpack 4. Unbelievable!

Not sure about jest. The latest version worked for me.

**Comment by devongovett** [comment]
Apparently webpack 5 is opt in with storybook. Has anyone tried this? https://storybook.js.org/blog/storybook-for-webpack-5/

**Comment by orrgottlieb** [comment]
we have the same issue

**Comment by McFoggy** [comment]
We faced the issue starting from last night on CI without any code change.
Currently trying to update to webpack5 in our storybook based component library.

**Comment by snowystinger** [comment]
If you're using yarn, you may also reduce the number of things you need to update using resolutions.
https://github.com/adobe/react-spectrum/issues/2855#issuecomment-1040946387
```
"resolutions": {
    "acorn": "8.0.1"
},
```

**Comment by pascalduez** [comment]
It's not just about nullish coalescing or optional chaining, but private class methods as well.

```
ERROR in ../node_modules/@internationalized/date/dist/module.js 1120:4                          
Module parse failed: Unexpected character '#' (1120:4)                                                  
You may need an appropriate loader to handle this file type, currently no loaders are configured to proc
s this file. See https://webpack.js.org/concepts#loaders                                                
|     // i.e. a ZonedDateTime should not be be passable to a parameter that expects CalendarDate.       
|     // If that behavior is desired, use the AnyCalendarDate interface instead.                        
>     #type;                                                                                            
|     constructor(...args){                                                                             
|         let [calendar, era, year, month, day] = $de531a00a7b9094c$var$shiftArgs(args);                
```

**Comment by devongovett** [comment]
Browser support is documented here: https://react-spectrum.adobe.com/react-aria/interactions.html#supported-browsers-and-platforms

Private class properties are also pretty widely supported, but it looks like they should be compiled (due to safari). Looking into it. https://caniuse.com/mdn-javascript_classes_private_class_fields

However, webpack being a lower support target than browsers is a new one we hadn't considered. I would definitely recommend upgrading if you can, but we are discussing what to do about it now and will have an update soon. Sorry for the inconvenience and thanks for your patience.

**Comment by chrisBite** [comment]
Can confirm switching to webpack5 builder in Storybook fixed the issue.

[Latest migration docs for Storybook + Webpack5](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5)

**Comment by devongovett** [comment]
We have temporarily reverted our browserslist config to a lower browser target such that optional chaining and nullish coalescing are now transpiled in our published packages. That should keep things working for the time being.

However, we would like to update this again in the future so that we can avoid transpiling syntax that is supported by our browser targets in order to reduce bundle sizes and improve runtime performance. Please upgrade to webpack 5 (or parcel? 😉😉) and/or the latest version of jest as soon as you can. **We plan to re-introduce this change in July 2022.** Given that webpack 5 has already been available for over a year (released in October 2020), we hope this gives everyone ample time to upgrade their dev dependencies.

Sorry again for the unexpected inconvenience.

**Comment by KutnerUri** [comment]
I recommend you keep an older browser support for longer. The ?? operator is available for only about half a year, I usually keep browser support for at least 3 if not 5 years. I can't really tell users to update their browsers, and sometimes even upgrading Webpack is not possible.

As an accessibility tool, I'd expect it not to leave out 8% of the world population, more than the population of screen reader users 😉

**Comment by devongovett** [comment]
According to [caniuse](https://caniuse.com/mdn-javascript_operators_nullish_coalescing), most browsers released nullish coalescing support around Feb-March 2020. That's just about 2 full years ago, if you can believe it!

Most browsers are evergreen these days, so if you specifically choose not to update, you're making some kind of statement. I'm not sure waiting much longer would make a difference to that number. At some point, things are gonna start breaking for them.

**Comment by 0ctothorp** [comment]
> Most browsers are evergreen these days, so if you specifically choose not to update, you're making some kind of statement.

Yes and no 😛  Some people are just locked on the browser version, because of their OS/hardware: https://blog.jim-nielsen.com/2022/a-web-for-all/. 

On a side note: to be honest I'm not really sure if this should be a library author's concern 🤔

**Comment by devongovett** [comment]
Yeah exactly. If you choose you can compile your node_modules according to your browser targets. This was more of an unfortunate case of build tools themselves being outdated more than browsers.
