### ISSUE TITLE
popover can end up wrongly positioned after window resize

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#2858]
# 🐛 Bug Report 

a combobox popover can end up wrongly positioned (i.e. not aligned with the input+button) after resizing the browser window.

## 🤔 Expected Behavior

popover should always update its position correctly after window resize

## 😯 Current Behavior

with the codesandbox example linked below, after resizing the browser window a couple of times, the popover can end up looking like this:

![Screenshot_20220216_153524](https://user-images.githubusercontent.com/20753323/154288299-7105b2cb-2660-4616-a41c-4f12edef87f0.png)

## 💻 Code Sample

codesandbox: https://codesandbox.io/s/stupefied-noyce-kywmhk?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest (feb 2022 release)
| Browser          | firefox
| Operating System | linux

**Comment by LFDanLu** [comment]
Verified the behavior, seems to only happen in Firefox and rather intermittently. Will need to do some digging into the overlay positioning code to see if anything can be pinned down

**Comment by stefanprobst** [comment]
might be related to `StrictMode` - at least when *not* wrapping in strict mode like in [this codesandbox](https://codesandbox.io/s/pensive-water-jgdbuv?file=/src/index.js) it seems to work better.

**Comment by LFDanLu** [comment]
I had initially thought the same thing, but was able to reproduce the same issue after removing `StrictMode` via https://xbfgkp.csb.app/. Definitely seems to reproduce it less frequently, so perhaps another thing to investigate

**Comment by B0und** [comment]
I am having the same issue. I was able to reproduce it in chrome (open the codesandbox, press on the calendar button, then increase the browser area towards the left side of the screen. After resizing the position of the popover is incorrect).

It appears to be related to width: 100%. (If you delete `w-full` in `DateRangePicker.js` , the popover repositions correctly)

Code link: https://codesandbox.io/s/hopeful-sinoussi-pvixl8?file=/src/DateRangePicker.js:1159-1165

**Comment by snowystinger** [comment]
I tried out that codesandbox. Looks like regardless of `w-full` it readjusts its position after a window resize to the correct place. There's a bit of padding between the edge of the screen and the popover, that's intentional. Am I missing something? Maybe a browser/OS combination?
I tried it out in Chrome 106 on MacOS 12.6

**Comment by B0und** [comment]
> I tried out that codesandbox. Looks like regardless of `w-full` it readjusts its position after a window resize to the correct place. There's a bit of padding between the edge of the screen and the popover, that's intentional. Am I missing something? Maybe a browser/OS combination? I tried it out in Chrome 106 on MacOS 12.6

I am currently on linux, but I think it should't really matter. I've just tested it on chrome 105 and firefox 105.
Here is how it looks like on my side: https://www.youtube.com/watch?v=PGo2udjgcmg

**Comment by snowystinger** [comment]
I see, thank you for the video, that helps, I was doing something different.

**Comment by snowystinger** [comment]
I cannot load the codesandbox anymore for some reason. It'd be great if someone could verify if this is still happening with the latest release. We've had some improvements made to overlay positioning over the last year.
I'm going to close for now. If there's still an issue, we can reopen.
