### ISSUE TITLE
Docs for useGrid?

### ISSUE THREAD

**Issue by bstro** [adobe/react-spectrum#2859]
# 🙋 Documentation Request
I see a hook called `useGrid` and it looks like what I need. I'm wondering if this is intended for public use, and if so, if there are any plans to document this hook. I'm gonna try to get as far as I can by following [this example story](https://github.com/adobe/react-spectrum/blob/d04e70b27e40d0a04312d8c5e40127eceeefcd22/packages/%40react-aria/grid/stories/example.tsx)

**Comment by snowystinger** [comment]
If it's not documented, then it's not quite ready for prime time usage yet. You're welcome to try it out, and if you have issues or improvements, that is welcome.
I've pinged my colleagues to see if they have anything else to add to that.

**Comment by snowystinger** [comment]
Hey! The team had a good chat about this. We may eventually publish useGrid with docs, but we feel that it's so flexible people could easily misuse it. Our shorter term goal therefore is to create more specific hooks that make use of useGrid such as useList or something along those lines.

Out of curiosity, what are you hoping to use it for?

**Comment by bstro** [comment]
Hey @snowystinger, thanks for the reply, that makes sense to me. I'm trying to create a simple 8x8 grid that I would like to augment with arrow-key navigation (up/down to navigate rows, left/right to navigate cells). useTable does this, but it seems like it is really geared towards tables. I may end up just going this route, but my grid has no concept of rows/headers. You can see what I'm talking about at https://hexagrams2.vercel.app/ — on the left column, notice the 8x8 grid. One can hit tab a bunch of times to get to the desired selection (each item in that grid uses useButton), but I think it'd be nicer to support arrow-key navigation.

<img width="299" alt="image" src="https://user-images.githubusercontent.com/627290/155836458-8acfd8a8-8264-4722-af07-9a1d745abcee.png">


Thanks!

**Comment by bstro** [comment]
Hey @snowystinger, thanks for the reply, that makes sense to me. I'm trying to create a simple 8x8 grid that I would like to augment with arrow-key navigation (up/down to navigate rows, left/right to navigate cells). useTable does this, but it seems like it is really geared towards tables. I may end up just going this route, but my grid has no concept of rows/headers.

<img width="299" alt="image" src="https://user-images.githubusercontent.com/627290/155836458-8acfd8a8-8264-4722-af07-9a1d745abcee.png">

One can hit tab a bunch of times to get to the desired selection (each item in that grid uses useButton), but I think it'd be nicer to support arrow-key navigation.

**Comment by snowystinger** [comment]
Sorry for brevity, I'm on my phone. You could probably get away with using focusscope + focus manager for that.

**Comment by bstro** [comment]
Thanks, @snowystinger — `FocusManager` looks very close, but upon reading the docs, it looks like its more suited towards 1d navigation. There is `focusNext` and `focusPrevious` which would handle left/right, but I'm not sure how I would implement up/down navigation for navigating rows without a method like `focusNth`. Wdyt?

**Comment by snowystinger** [comment]
Glad that worked pretty well.

Should you run into issues with it, you could take inspiration from our Calendars, which look to be a fairly similar experience/usecase. I wouldn't blindly copy it, I'd try to go for the general idea. Which is cells and rows are in state and provides functions to set the state to a given cell. When focus is set to a cell, when that cell re-renders, it'll call focus on itself (so we don't need to pass refs around). I've added links to the relevant code in order that I mentioned it in this overview.

https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/calendar/src/useCalendarState.ts
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/calendar/src/useCalendarGrid.ts#L37
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/calendar/src/useCalendarCell.ts#L201

**Comment by bstro** [comment]
I came across this text in the docs today and was reminded of this old issue.
https://react-spectrum.adobe.com/react-aria/useListBox.html#complex-options
It says `NOTE: listbox options cannot contain interactive content (e.g. buttons, checkboxes, etc.). For these cases, see useGrid instead.`, but it looks like there are still no public-facing docs for `useGrid`?

**Comment by devongovett** [comment]
We just released an RC of [useGridList](https://react-spectrum.adobe.com/react-aria/useGridList.html), which you could use in this case. Updated the listbox docs to link to that.

**Comment by bstro** [comment]
Thanks @devongovett! Also looks like an **awesome** release. Very excited to dig in to the changes. Thanks a bunch!
