### ISSUE TITLE
Allow setting the text content of a DismissButton

### ISSUE THREAD

**Issue by Vinnl** [adobe/react-spectrum#2866]
# 🙋 Feature Request

Currently a `<DismissButton>` renders a `<button>` with its `aria-label` set to "Dismiss". Possibly this will get localised automatically when using react-aria's internationalisation support, but it doesn't seem to be otherwise customisable. (If it is, this is a request for documentation :) )

## 🤔 Expected Behavior

Be able to pass a custom string to give to the user. If no string is passed, current behaviour is preserved.

## 😯 Current Behavior

It just automatically renders "Dismiss".

## 💁 Possible Solution

One possible approach is just re-using the `aria-label` attribute set on `<DismissButton>` directly. Another approach might be using its children, though that might imply that it's possible to set it to more than a string.

## 🔦 Context

We're using other l10n tooling ([Fluent](https://projectfluent.org/), to be specific), so now we can't localise this specific element.

**Comment by snowystinger** [comment]
You are correct, the string is localized if you use react-aria's intl support. See https://github.com/adobe/react-spectrum/blob/7a5e585acc5ca538fb6e9e40f369f01394bded8a/packages/%40react-aria/overlays/src/DismissButton.tsx#L42

We actually do have some docs for the component https://react-spectrum.adobe.com/react-aria/DismissButton.html that show it doesn't take any props.

What string do you need to change it to? I can see if we want to support a prop to change it, but need a bit more information about the use case first.

**Comment by Vinnl** [comment]
The string I need to change it to depends on the locale. In the l10n library we use, we'd obtain it with a call like `l10n.getString("dismiss-button-string-id")`, which would automatically provide the string in the correct locale. Hence, ideally I'd be able to use it something like

```jsx
<DismissButton aria-label={l10n.getString("dismiss-button-string-id")}/>
```

Without knowing the codebase, it might be as simple as replacing the line you linked as such:

```diff
     <VisuallyHidden>
       <button
         tabIndex={-1}
-        aria-label={formatMessage('dismiss')}
+        aria-label={props["aria-label"] ?? formatMessage('dismiss')}
         onClick={onClick} />
     </VisuallyHidden>
```

**Comment by snowystinger** [comment]
So this brings up a couple questions, we have a lot of localized strings that ship with react-aria. How many and which ones will we need to expose to this? And if you're providing one because we don't support a given locale, how can we tell you all of the strings you'd need to provide so you have a completely localized component? I will take this to the team as we've started talking about "bring your own locale", maybe in the simple cases we just support direct label control though.

In the meantime, what is stopping you from using the translations that React Aria already has?

**Comment by snowystinger** [comment]
Team is fine with this simple case, I've opened a PR to address it

**Comment by Vinnl** [comment]
Thanks @snowystinger! And in case it's useful for understanding use cases:

> what is stopping you from using the translations that React Aria already has?

I'm not sure if react-aria's language detection resolves to the same languages we have, whether it has the same locales available as we do, and perhaps vice versa, that it _doesn't_ translate the strings we don't either. Which, writing it out like this, can be partially resolved by adding react-aria's `I18nProvider` and passing it the locale we detected, I suppose.
