### ISSUE TITLE
useSlider does not work without pointer events

### ISSUE THREAD

**Issue by jeroenwienk** [adobe/react-spectrum#2871]
# 🐛 Bug Report 

When PointerEvent is undefined the slider is not draggable.

## 🤔 Expected Behavior

I expect the fallback behavior to work because MouseEvents would be used.

## 😯 Current Behavior

The handle/thumb slightly moves but when the pointer is held down it is not draggable. I am only able to click on a absolute position to move the handle.

## 🔦 Context

Disabled pointer events in Safari because of https://github.com/adobe/react-spectrum/issues/2322

## 💻 Code Sample

https://codesandbox.io/s/useslider-4gp7qw

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.13.2
| react-aria   | 3.12.1
| Browser          | Chrome, Safari
| Operating System | Windows, MacOS

**Comment by LFDanLu** [comment]
Looks to be due to https://github.com/adobe/react-spectrum/blob/1aa66e6e75e2da014f44177686c3332cd625fb9f/packages/%40react-aria/slider/src/useSlider.ts#L201-L206, it seems to block the `onMouseDown` listeners from firing. We should probably only return the `onPointerDown` event handler if pointerEvents is defined

**Comment by LFDanLu** [comment]
Talked with the team and decided that it would be hard for us to know when it would be appropriate to remove specific listeners in a variety of case so in the meantime you can go ahead and delete onPointerDown yourself for the Safari case.

**Comment by jeroenwienk** [comment]
> Talked with the team and decided that it would be hard for us to know when it would be appropriate to remove specific listeners in a variety of case so in the meantime you can go ahead and delete onPointerDown yourself for the Safari case.

That works thank you.
