### ISSUE TITLE
@react-aria/useButton with TypeScript: Types of property 'type' are incompatible

### ISSUE THREAD

**Issue by karlhorky** [adobe/react-spectrum#2875]
# 🐛 Bug Report 

When using [the example from the `@react-aria/button` docs](https://react-spectrum.adobe.com/react-aria/useButton.html#example), the types for `useButton` in `@react-aria/button@3.4.1` don't match with the React types for the `type` prop on `<button>` elements:

```
Type '{ children: string; ref: MutableRefObject<undefined>; download?: any; href?: string; hrefLang?: string; media?: string; ping?: string; rel?: string; target?: HTMLAttributeAnchorTarget; ... 254 more ...; onTransitionEndCapture?: TransitionEventHandler<...>; }' is not assignable to type 'DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>'.
  Type '{ children: string; ref: MutableRefObject<undefined>; download?: any; href?: string; hrefLang?: string; media?: string; ping?: string; rel?: string; target?: HTMLAttributeAnchorTarget; ... 254 more ...; onTransitionEndCapture?: TransitionEventHandler<...>; }' is not assignable to type 'ButtonHTMLAttributes<HTMLButtonElement>'.
    Types of property 'type' are incompatible.
      Type 'string' is not assignable to type '"button" | "submit" | "reset"'.
```

Downgrading to version `@react-aria/button@3.3.4` makes the error go away.

The bug is still present in `@react-aria/button@3.4.0`

## 🤔 Expected Behavior

No type error

## 😯 Current Behavior

Type error (see above)

## 💁 Possible Solution

Match types with `@types/react` types: use `string | undefined` instead of the `"button" | "submit" | "reset"` literal union.

## 🔦 Context

Use [the example from the `@react-aria/button` docs](https://react-spectrum.adobe.com/react-aria/useButton.html#example)

## 💻 Code Sample

Check out `App.tsx` in this StackBlitz:

https://stackblitz.com/edit/react-ts-ybosd2?file=App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/button   | 3.4.1 |
| Browser          | - |
| Operating System | - |

**Comment by reidbarber** [comment]
I think this may be environment or typescript config specific. Using the same example and package versions in CodeSandbox shows no issues:
https://codesandbox.io/s/typescript-react-aria-button-rsgbyy?file=/src/App.js

**Comment by reidbarber** [comment]
Looks like in the example you shared, `buttonProps`'s is shown as:

<img width="608" alt="Screen Shot 2022-02-23 at 2 24 05 PM" src="https://user-images.githubusercontent.com/8961049/155408098-b9125b7b-9372-4abb-9320-625e6a602da5.png">

whereas, in the version you mentioned where this no issue, it is `any`. I think we might need to take a second look at the changes made in https://github.com/adobe/react-spectrum/commit/53fdc713be511d07d8abd805f37b4754cb761367.

**Comment by karlhorky** [comment]
Opened #2925 as a simple, naïve fix for this (I am not familiar with the codebase), @reidbarber @LFDanLu thoughts?
