### ISSUE TITLE
useButton has unexpected behaviour 

### ISSUE THREAD

**Issue by pontageorge** [adobe/react-spectrum#2877]
# 🐛 Bug Report 

We implemented the `useButton` hook on our button component that we use globaly in one of our microservices. We have had problems with implementing it largely due to the fact that:

1. The `Event` object is not exposed at all. I understand there is a `PressEvent` object returned but we can't do the `e.preventDefault()` and `e.stopPropagation()` when we need to. Furthermore, `e.preventDefault()` is not called at all on the `onClick` hook but is called on the other hooks which brings inconsistencies for users when they use click or button press.
2. In some hooks `e.stopPropagation()` is always called like the `onKeyUp` hook. We may not want to do that always and I am pretty sure it introduces some bugs.

Below there is an **CodeSandbox** example of one of the bugs which have sorted but just because we have stripped the `onClick, onPointerDown, onPointerUp, onKeyDown` hooks. We are using the `RouteLeavingGuard` to Prompt a Dialog that will ask the user if they are sure they want to leave the page with unsaved changes.

## 🤔 Expected Behavior

When pressing on the **Leave Page** button the **Confirm** button pops up. Clicking the **Confirm** button should push the new url to the browser and the **Confirm** button should dissapear

## 😯 Current Behavior

When doing the press to the **Confirm** button nothing happens. Neither the new URL is pushed nor the button dissapears

## 💁 Possible Solution

The solution is that:

1. For `onClick` -> strip `onClick, onPointerDown, onPointerUp' from the props passed to the button and pass `onPress` manually like so `onClick={onPress} `
2.  For key events -> strip `onKeyDown`

I have commented out the stripped version of the props in the `Button` component. Currently the functionality in the Sandbox ain't working. Don't forget to add `onClick={onPress}` to the button element when debugging it and also to replace `buttonProps` with `restOfProps` when you uncomment the stripped version.

## 🔦 Context

Because we are implementing the `react-aria` hooks to an already existing library of components and that is used in different projects these inconsistencies with the `Event` object causes a lot of problems and results us in stripping accessability functionality from the hook.

## 💻 Code Sample

https://codesandbox.io/s/loving-danny-uhgk7t?file=/src/Button.jsx

## 🌍 Your Environment

You can see the versions we use in the versions from the CodeSandbox

**Comment by snowystinger** [comment]
I'm not sure I know enough about React Router, however, I put a log statement in the handleNavigate function you defined, and it is called when you press the Confirm button.

I tried changing the `history.push` to `history.go` and it appropriately hides the button. What I don't know is why neither of those functions change the URL, but I suspect it isn't ReactAria's problem.

**Comment by LFDanLu** [comment]
Just to chime in, I also noticed that flipping the order of calls within the `handleNavigate` (aka doing `history.push` before the `setDisplayComponent` in your `RouteLeavingGuard` makes the url change and the close button disappear as expected. Digging further, I noticed that your `handleBlockedNavigation` calls `setDisplayComponent(true)` immediately after `handleNavigate` calls `setDisplayComponent(false)` in your current sandbox which is probably why the close button doesn't go away. I'm not sure how exactly `Prompt` works and when it fires `handeBlockedNavigation` but this seems like something to fix first

**Comment by pontageorge** [comment]
Understandable, however just as a question. Why are the `buttonProps` hooks such as `onClick, onKeyDown, onKeyUp` not exposing the `Event` object.?

We had a few bugs before with it as well we solved them now and won't spend anymore time trying to create a CodeSandbox for them but just to know if this may be added in the future?

**Comment by reidbarber** [comment]
Check out the [Building a Button Part 1: Press Events](https://react-spectrum.adobe.com/blog/building-a-button-part-1.html) blog post.

**Comment by snowystinger** [comment]
closing, i don't think there's anything left on this one. Can reopen if there anything comes up again
