### ISSUE TITLE
Typescript: Include name prop for ComboBox

### ISSUE THREAD

**Issue by malanirishi** [adobe/react-spectrum#2879]
# 🐛 Bug Report 

`name` prop is not included in typescript definition of `ComboBox`.  This gives typescript error for clients which are using `ComboBox` and passing `name` property to it.

## 🤔 Expected Behavior

`name` should be included in prop type for `ComboBox`.

## 😯 Current Behavior
Passing `name` property to `ComboBox` gives TS error.

```
Type '{ children: ({ icon, index, key, val, }: { key: string; val: string; icon?: Icons | undefined; index?: number | undefined; }) => Element; defaultItems: Iterable<{ key: string; val: string; icon?: Icons | undefined; index?: number | undefined; }> | { ...; }[] | undefined; ... 30 more ...; name: string; }' is not assignable to type 'IntrinsicAttributes & SpectrumComboBoxProps<{ key: string; val: string; icon?: Icons | undefined; index?: number | undefined; }> & { ...; }'.
  Property 'name' does not exist on type 'IntrinsicAttributes & SpectrumComboBoxProps<{ key: string; val: string; icon?: Icons | undefined; index?: number | undefined; }> & { ...; }'.ts(2322)
```

## 🔦 Context
We are trying to use `final-form-focus` library for moving focus to first field with error in react final form. For this library, we need to pass `name` prop to `ComboBox`. Even though `name` prop gets successfully applied to `ComboBox` but TS type for `SpectrumComboBoxProps` doesn't support `name`. This gives TS error for clients.

## 💻 Code Sample

https://codesandbox.io/s/combobox-standalone-ruhw5p?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.15.0
| Browser          | Chrome
| Operating System | macOS Monterey 12.2.1

## 🧢 Your Company/Team

Adobe Marketo Engage Unified Experience

**Comment by LFDanLu** [comment]
Good catch, we should probably be adding the `name` type to the ComboBoxProps [here](https://github.com/adobe/react-spectrum/blob/a936263b487f59451634a27c97ccfa90614656d5/packages/%40react-types/combobox/src/index.d.ts#L17-L42) like we do for our radio and checkbox props types
