### ISSUE TITLE
Safari not displaying double underline for focus on links

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#2885]
# 🐛 Bug Report 

Following setup for Safari Keyboard navigation https://www.scottohara.me/blog/2014/10/03/link-tabbing-firefox-osx.html
Try to navigate https://react-spectrum.adobe.com/react-spectrum/Link.html

## 🤔 Expected Behavior

It's obvious when we have focus on a link.

## 😯 Current Behavior

It's not obvious.

## 💁 Possible Solution

This is working https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          | Safari Version 15.3 (17612.4.9.1.8)
| Operating System | Mac OS 12.2.1 (21D62)

**Comment by snowystinger** [comment]
I'm suspicious that this is a new version of Safari problem.

**Comment by LFDanLu** [comment]
Followup: bring up with Spectrum, maybe have a focus ring around links instead of double underline

**Comment by snowystinger** [comment]
I see double underlines now. Closing.
In addition S2 styles have changed a number of links to focus rings
