### ISSUE TITLE
ColorArea followup

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#2901]
# 🐛 Bug Report 

Testing followup:
-  Screen reader announcement is extremely verbose and unclear that it is referring to a color. "2d slider" is used as a role description rather than "color area". It reads the full color, and then some of the channels again, every single time you press an arrow key. 
- adjust color in color area, then color in slider. the z-index of the slider thumb is wrong, and appears behind the color area
  -  To reproduce, you must click on the colorarea/colorslider itself, not the thumb
- Aria-label "foo" story isn't overriding the default aria-label which is set on the input fields.
- There isn't a color announcement made when the ColorSlider value is changed. in NVDA 

Story improvements:
- Should the ColorSlider in the ColorArea stories have the same step value applied to it? Right now it doesn't.  (UPDATE STORY)
- stories might make more sense if the third channel (slider) defaulted to zero rather than 100% 

## 🧢 Your Company/Team

RSP

**Comment by majornista** [comment]
> Screen reader announcement is extremely verbose and unclear that it is referring to a color. "2d slider" is used as a role description rather than "color area". It reads the full color, and then some of the channels again, every single time you press an arrow key.

MS Windows labels the control a "Color Picker" and uses "2d slider" as a custom, localized role description. The value text is currently meant to express the values for the 2 channels that the Color Picker controls, prioritizing the channel value that changed most recently. I currently use the `title` attribute to include all three channel values for the selected color and in an earlier version, this string also included a color name. Perhaps, on desktop, each slider should just have "Color Picker" as the accessibility name, with the `aria-valuetext` set to include all three channel values, prioritizing the channel value that changed most recently, followed by the channel value for the opposing axis, followed by the "zChannel" value set externally using a ColorSlider or ColorWheel. 

I think we should always include the "Color Picker" for color area or the channel name for the ColorSlider or ColorWheel when setting `aria-label` or `aria-labelledby`, for example, "foo Color Picker" or "foo Red."

**Comment by majornista** [comment]
> There isn't a color announcement made when the ColorSlider value is changed. in NVDA

I now wonder, and I think @devongovett may have suggested this at one time, if the full color announcement of all channels or the color name should be handled outside of the announcement of the value change for a particular channel. For this, I could remove the `title` attribute from color area, and listen to `onChange` events within the ColorArea or ColorSlider examples to update a live region with the color value as it changes. The other option would be to add the `title` attribute to announce all the color channels to the ColorSlider, which may make sense given that ColorSlider is interactive and the thumb  and loupe render the RGB or HSL Color for a given channel, based on the values of the two other channels.
