### ISSUE TITLE
Changing locale on ColorArea doesn't change direction thumb moves with home/end key

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum#2921]
# 🐛 Bug Report 

Changing the locale doesn't change the direction that home/end keys move the thumb.

## 😯 Current Behavior

Selecting a language that is RTL or LTR, and home/end keys both move the same direction. For other components like slider, color slider, most other things the direction changes.

## 🔦 Context

Noticed this while testing #2888 

## 🧢 Your Company/Team
RSP

**Comment by LFDanLu** [comment]
Note: will need to discuss w/ internationalization team and accessibility to see what the expected behavior is here.
