### ISSUE TITLE
`@react-spectrum/avatar` isn't included in `@adobe/react-spectrum`

### ISSUE THREAD

**Issue by TheMcMurder** [adobe/react-spectrum#2931]
# 🐛 Bug Report 

`@adobe/react-spectrum` doesn't include `@react-spectrum/avatar`. It's not clear to me if that exclusion is intentional or not.

## 🤔 Expected Behavior

[This file](https://github.com/adobe/react-spectrum/blob/main/packages/%40adobe/react-spectrum/src/index.ts) would include `@react-spectrum/avatar`

## 😯 Current Behavior

[This file](https://github.com/adobe/react-spectrum/blob/main/packages/%40adobe/react-spectrum/src/index.ts) does not include `@react-spectrum/avatar`

## 💁 Possible Solution

Include and re-export the package.

## 🧢 Your Company/Team

Adobe Workfront

**Comment by reidbarber** [comment]
Avatar is currently in alpha. We'll export it from the monopackage once it gets a full release. You can follow its progress on the [roadmap](https://github.com/adobe/react-spectrum/projects/1#card-67516110) until then.
