### ISSUE TITLE
Getting a random hash for FocusRing in snaphots

### ISSUE THREAD

**Issue by dermyhughes** [adobe/react-spectrum#2938]
# 🐛 Bug Report 

I am using the FocusRing component to wrap around a button like so:

```
import { FocusRing } from '@react-aria/focus';

<FocusRing focusRingClass={`foo`}>
      <button
        {...props}
      >
        {children}
      </button>
    </FocusRing>
  ```

But recently our Jest snapshots tests have been rendering these with a random hashed string rather than the element name.

## 🤔 Expected Behavior

Previously these tests rendered the component name, just like the DOM:

```
<FocusRing focusRingClass=\\"foo\\" >
    // Button element
</FocusRing>
```

## 😯 Current Behavior

```
<$dfd8c70b928eb1b3$export$1a38b4ad7f578e1d
  focusRingClass=\\"foo\\" >
    // Button element
</$dfd8c70b928eb1b3$export$1a38b4ad7f578e1d>
```

Is this expected or has something changed?

**Comment by reidbarber** [comment]
Did this start happening after updating React Spectrum to a specific version? Or updating Jest?

**Comment by snowystinger** [comment]
Looks related to the Parcel upgrade, might be linked to this issue as well https://github.com/adobe/react-spectrum/issues/2881

**Comment by dermyhughes** [comment]
I noticed this crop up around the same time as https://github.com/adobe/react-spectrum/issues/2857
I tried bumping Jest but getting the same result.

I locked to `"@react-aria/focus": "3.4.0"` and the tests are snapping as expected:

``` <FocusRing
               focusRingClass=\\"foo\\"
              >
```

**Comment by LFDanLu** [comment]
Closing for now. @dermyhughes feel free to let us know if the mock approach described above doesn't work.

**Comment by AndyOGo** [comment]
Same here.

@devongovett 
@snowystinger 
Hashing exports this way is an anti-pattern.
It's obfuscates the stack trace, snapshots, enverything that relies on `displayName`.

**Comment by devongovett** [comment]
https://github.com/parcel-bundler/parcel/issues/6092
