### ISSUE TITLE
Background color in a `Tray` messes up its `border-radius`

### ISSUE THREAD

**Issue by Sorgrum** [adobe/react-spectrum#2951]
# 🐛 Bug Report 

When the `background-color` attribute is set, the `border-radius` is no longer respected.

## 🤔 Expected Behavior

Corners of the `Tray` should be rounded
<img width="397" alt="image" src="https://user-images.githubusercontent.com/3497076/158030693-80813ae8-1a4b-41fc-bda2-c251d297c5da.png">

## 😯 Current Behavior

Corners of the `Tray` are not rounded
<img width="397" alt="image" src="https://user-images.githubusercontent.com/3497076/158030678-731858af-524a-420e-9087-3157cf98425d.png">

## 💁 Possible Solution
Adding `overflow: hidden` to the `Tray` component seems to fix this.

## 🔦 Context

When using a Popover, on small widths, the `Tray` component is used. In my use case, the background color of the items change on hover. 

## 💻 Code Sample

```tsx
<DialogTrigger type="popover" mobileType="tray" placement="top right">
  <Button variant="primary">Open</Button>
  <div style={{ backgroundColor: "red" }}>content</div>
</DialogTrigger>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  3.16.3
| Browser          | Firefox 98.0
| Operating System | macOS 11.4

**Comment by LFDanLu** [comment]
@Sorgrum Just to clarify, are you using a `DialogTrigger` with a `Dialog` or is the code sample you provided roughly accurate to your own implementation?

**Comment by ktabors** [comment]
Closing and if it's still a problem or you provide additional information we can reopen.
