### ISSUE TITLE
React Aria Slider Doest Detect Clicks on an Iframe

### ISSUE THREAD

**Issue by rizikolik** [adobe/react-spectrum#2952]
# 🐛 Bug Report 

React Aria slider doesnt stop dragging or doesnt detect mouse clicks.
## 🤔 Expected Behavior

Releasing mouse on any part of the screen must trigger onUp function.

## 😯 Current Behavior

When I drag the slider towards to an iframe and I a release my mouse when I hover to the slider again,dragging still happening.

## 💁 Possible Solution

from the  @react-aria/slider/src/useSlider.ts , while exporting trackProps, maybe should export another method .
`      onMouseLeave(e: React.PointerEvent<HTMLElement>) {
        if (e.pointerType === 'mouse' && (e.button !== 0 || e.altKey || e.ctrlKey || e.metaKey)) {
          return;
        }
        onUpTrack(e);
      },
`
So while we are calling :
`const {groupProps,trackProps}=useSlider({...})
`
and 
`
const {oNMouseLeave}=trackProps;
`
We can add another event listener to an element we want to stop dragging like that:

<div onMouseLeave?{onMouseLave}> ,
<Slider />
</div>`
`
## 🌍 Your Environment

React,Scss and spectrum-css

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
Closing as a dupe, @rizikolik feel free to reopen if that isn't the case.
