### ISSUE TITLE
`ContextualHelp` is not compatible with next.js

### ISSUE THREAD

**Issue by flyinghail** [adobe/react-spectrum#2963]
# 🐛 Bug Report 

## 🤔 Expected Behavior

Use `import { ... } from '@adobe/react-spectrum'` with `next.js`

## 😯 Current Behavior

```js
import { defaultTheme, Provider } from '@adobe/react-spectrum';
```
The code will fail to compile when used with next.js.

```
../node_modules/@react-spectrum/contextualhelp/dist/main.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: ..\node_modules\@react-spectrum\contextualhelp\dist\module.js
```

So I had to change it like this:
```js
import { theme as defaultTheme } from '@react-spectrum/theme-default';
import { Provider } from '@react-spectrum/provider';
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.16.4
| next.js          | 12.1.0

**Comment by reidbarber** [comment]
You'll need to add the following to your `next-transpile-modules` config in `next.config.js`:

```js
"@react-spectrum/contextualhelp",
```

We've got a PR to update the docs to include this newly released component at https://github.com/adobe/react-spectrum/pull/2937
