### ISSUE TITLE
Link to W3C table spec is wrong

### ISSUE THREAD

**Issue by raisiqueira** [adobe/react-spectrum#2972]
The link to the W3C spec for table component is wrong at `useTable` docs (at `@react-aria/table`).

Wrong link: https://www.w3.org/TR/wai-aria-practices/#grid

Correct link: https://www.w3.org/TR/wai-aria-practices/#table

**Comment by devongovett** [comment]
Grid is the correct one. Aria tables are non-interactive. Grids are interactive.
