### ISSUE TITLE
Tooltip crossOffset example visual issue

### ISSUE THREAD

**Issue by sparecycles** [adobe/react-spectrum#3001]
# 🐛 Bug Report 

Tooltip `crossOffset` triangle is centered on the left border of the tooltip, over the rounded corner.

## 🤔 Expected Behavior

Example(s) should all look good.

## 😯 Current Behavior

https://react-spectrum.adobe.com/react-spectrum/Tooltip.html

<img width="497" alt="image" src="https://user-images.githubusercontent.com/719818/161463178-68ee1353-e774-4f64-aa59-1c60810e6112.png">

Consistent in both Safari and Firefox.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Firefox & Safari |
| Operating System | OSX 12.3.1 |

**Comment by reidbarber** [comment]
I think this might get fixed by https://github.com/adobe/react-spectrum/pull/2842. Not seeing the issue in the latest build of that PR.

**Comment by LFDanLu** [comment]
Duplicate of https://github.com/adobe/react-spectrum/issues/2258
