### ISSUE TITLE
Define types in storybook stories

### ISSUE THREAD

**Issue by cornedor** [adobe/react-spectrum#3002]
# 📝 Feedback

Storybook items currently use a lot of any types, this makes it hard to check what types to use for what components. It would be nice if types defined for component properties so they can be used as a reference.

## 🔦 Context

I'm trying to use useMenuTrigger, the storybook stories have implementations which I can use as a reference, but they miss TypeScript types.

## 💻 Code Sample

-

## 🌍 Your Environment

-
## 🧢 Your Company/Team

-

**Comment by devongovett** [comment]
Storybook is mainly our development/testing environment, it's not really intended for use outside of that. The docs are a better place for reference.

**Comment by cornedor** [comment]
Thanks for the reply, I was trying to implement https://react-spectrum.adobe.com/react-aria/useMenuTrigger.html. The props for the seperate sub-components are composed of multiple types it seems, but I couldn't find all types in the docs.

For example MenuPopup, the props are used in useTreeState and useMenu, and also parts of it are used across the component (onClose, domProps and onAction)

**Comment by snowystinger** [comment]
I think this is experience is better now, either by using RAC directly which takes care of joining the appropriate types, or using RAC as an example of what types to use.
I'm going to close this for now. We can reopen if there is more to discuss here.
