### ISSUE TITLE
ListView borders disappear at 110% zoom

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#3017]
# 🐛 Bug Report 

ListView rows share border with each side contributing .5px. This can cause rounding errors depending on the zoom level and monitoring being used.

My combination is a non-high-dpi monitor at 110% zoom

## 😯 Current Behavior

![Screen Shot 2022-04-08 at 11 31 39 AM](https://user-images.githubusercontent.com/698229/162501937-29d376e2-1e5a-418a-823d-c401a6c5d405.png)

## 💁 Possible Solution

TableView doesn't have this issue, each rows instead share a bottom border only, using a full 1px. If we make ListView's like TableView, this should be resolved.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
Note: happens specifically in https://github.com/adobe/react-spectrum/pull/2804

**Comment by snowystinger** [comment]
I updated the description with my device that is displaying this issue

**Comment by LFDanLu** [comment]
For background, resolved by https://github.com/adobe/react-spectrum/pull/2804/commits/5ed63b59e992d3d398d4693871e67ac3a4e5edd5
