### ISSUE TITLE
Focus within fields is broken within a TableView

### ISSUE THREAD

**Issue by apoco** [adobe/react-spectrum#3022]
# 🐛 Bug Report 

Interaction with fields/inputs/selects in a `<TableView/>` is broken. For example, you cannot place focus within a `<NumberField/>` in a `<Cell/>`.

## 🤔 Expected Behavior

Fields/inputs/selects in a `<TableView/>` should be interactive. 

## 😯 Current Behavior

The `<TableView/>` seems to be intercepting events in a way that interferes with interactivity.

## 💁 Possible Solution

This is just speculation, but I suspect the row selection mechanism is interfering with child interactivity. I base this on the fact that when putting focus into an input fails upon click, the `<Row/>` becomes selected when selection is enabled. Sadly, turning off selection does not fix the problem.

## 🔦 Context

I'm looking into updating my app so it's implemented with Spectrum components since the work y'all have done with a11y is _amazing_. As part of the effort, I'm trying to convert my hand-crafted data grid into a `<TableView/>`. One feature the grid has is the ability to toggle inline editing within a row after clicking on an "Edit" button in an "Actions" button column. Unfortunately, the inputs I render cannot gain focus, and selects don't open. I did try replacing one of my inputs with a `<NumberField/>` to see if Spectrum components work around this issue somehow, and while that field can get focus if you click the stepper buttons, it does not gain focus when you click within the input area.

I realize I could replace the inline editing paradigm with, say, an edit modal, but I feel like if there's a mass editing effort going on, that would be a tedious UX.

## 💻 Code Sample

I was able to reproduce with this simple next.js page.

```typescript
export default function BugRepro() {
  return (
    <TableView>
      <TableHeader>
        <Column>Value</Column>
      </TableHeader>
      <TableBody>
        <Row>
          <Cell>
            <NumberField />
          </Cell>
        </Row>
      </TableBody>
    </TableView>
  );
}
```

I've removed everything but the essentials from my `/pages/_app.tsx`:

```typescript
export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <SSRProvider>
      <SpectrumProvider theme={defaultTheme}>
        <Component {...pageProps} />
      </SpectrumProvider>
    </SSRProvider>
  );
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.16.5
| Browser          | Firefox 99.0 (64-bit), Chromium 100.0.4896.75 (Official Build) snap (64-bit)
| Operating System | Linux

## 🧢 Your Company/Team

New app development for https://ifareahumanitariancenter.org/

**Comment by LFDanLu** [comment]
You are correct, the grid navigation/row selection behavior of the TableView can interfere when you try to interact with certain elements inside the TableView itself. We have considered adding an [edit mode](https://github.com/adobe/react-spectrum/issues/2328) that would give users a way to stop this highjacking of events but there are still some issues that have to be ironed out (aka didn't feel intuitive, how to communicate to users that edit mode even a thing, etc) .

Related issue: https://github.com/adobe/react-spectrum/issues/1214

**Comment by LFDanLu** [comment]
Closing since this is covered by https://github.com/adobe/react-spectrum/issues/2328.
