### ISSUE TITLE
Column resizing followup - task: try another method of feature flagging

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#3025]
# 🙋 Feature Request

Followup issue https://github.com/adobe/react-spectrum/issues/3007 item:
> Figure out the smallest way to feature flag the resizing portion of the TableView component

We want to be able to release TableView but not increase the code size for everyone drastically.

## 💁 Possible Solution

- Approach 1: pare down the existing resizing code so it is more granular (aka layout level instead of two whole components)
- Approach 2: Get rid of the deprecated TableView component and test to make sure there aren't breaks to existing logic

**Comment by dannify** [comment]
Let's just release the feature without flagging since it is already blocked
