### ISSUE TITLE
Dialog modal on mobile stack footer and button group

### ISSUE THREAD

**Issue by ktabors** [adobe/react-spectrum#3029]
# 🙋 Feature Request

Improve the footer and buttongroup layout of modals on mobile devices. 

## 🤔 Expected Behavior

Footer and button labels aren't squashed next to each other.

## 😯 Current Behavior

The footer and buttongroup sections of modals on mobile views are next to each other which squashes the footer and button labels can render outside of the button.

<img width="278" alt="image" src="https://user-images.githubusercontent.com/309540/162869711-69474075-0eee-4928-a520-f41ec9eacf73.png">

## 💁 Possible Solution

Do vertical stacking of footer and buttongroup like how all the parts of fullscreen and fullscreenTakeover are stacked in mobile.

## 💻 Examples

Open browser dev tools, select devices, and choose responsive view with width "320px."
Goto the DialogTrigger "adjustable dialog" story and check "show footer" and "show long button labels".
Open the modal by clicking the "Trigger" button.

https://reactspectrum.blob.core.windows.net/reactspectrum/65107923a26b8048d8704ab39f5247ed7816eb1f/storybook/index.html?path=/story/dialogtrigger--adjustable-dialog

## 🧢 Your Company/Team
RSP

**Comment by AvidDabbler** [comment]
I am seeing issues with combobox on modals as well
![image](https://user-images.githubusercontent.com/8471756/185553424-fe0c4bf9-15b6-493c-9318-400cd9a8aa06.png)

**Comment by snowystinger** [comment]
Any chance you can reproduce in a codesandbox? Also, this looks unrelated to the states issue.

**Comment by AvidDabbler** [comment]
> Any chance you can reproduce in a codesandbox? Also, this looks unrelated to the states issue.

Yup! I'm happy to open up another issue if this is not currently logged

https://codesandbox.io/s/laughing-pare-tyig0v?file=/src/index.js

**Comment by snowystinger** [comment]
Yeah, that's not related, here it is fixed https://codesandbox.io/s/damp-worker-rdzh9h?file=/src/App.js. The React-modal portalled everything to a new place in the dom where it couldn't get the CSS variables it expected. If you make a provider with a style, it'll render a new element. Or there are a few other ways to get that to happen. I suggest using our DialogTrigger https://react-spectrum.adobe.com/react-spectrum/DialogTrigger.html or DialogContainer instead though.

**Comment by ktabors** [comment]
Reverifying. There is still overlap, but the buttons no longer display with wrap.
<img width="353" alt="image" src="https://github.com/adobe/react-spectrum/assets/309540/e746a0cc-0f28-4b06-be19-57902832d82d">

**Comment by ktabors** [comment]
Current behavior does not overlap and the buttons text wrap. The wrapped text remains within the button. Closing as resolved.
