### ISSUE TITLE
Add "size" support for StatusLight component

### ISSUE THREAD

**Issue by GrantRussell** [adobe/react-spectrum#3031]
# 🙋 Feature Request
As a user, I would like to have control over the size of the StatusLight component.  As of January 19, 2022, Spectrum design supports a size configuration for the StatusLight component - https://spectrum.adobe.com/page/status-light/#Changelog.  It would be nice to have this in the React Spectrum implementation.

## 🤔 Expected Behavior
Passing a `size` prop with values like `"small"`, `"medium"`, `"large"`, etc... would alter the size of the StatusLight dot and label to match supported Spectrum design sizes.

## 😯 Current Behavior
No `size` prop is supported.

## 🧢 Your Company/Team
Adobe/Assets Essentials

**Comment by LFDanLu** [comment]
Will bring this up in grooming for discussion/prioritization

**Comment by LFDanLu** [comment]
Discussed with the team regarding prioritization, it probably won't be worked on in the near term (relies on a dna vars update). How important is controlling the size of the status lights in your app? If you need this support soon you may need to create your own StatusLight component based off of ours or override the specific spectrum status light sizing variables

**Comment by GrantRussell** [comment]
@LFDanLu It's not critical, this would mostly just be a nice-to-have feature so we can more accurately match our UX designers' XD designs. 👍

**Comment by yihuiliao** [comment]
Closing since this will be available in S2.
