### ISSUE TITLE
Safari 15 TableView selection checkboxes aren't sticky

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#3035]
# 🐛 Bug Report 

If I horizontally scroll a TableView in Safari 15.4, the checkboxes disappear off to the left. This was working in Safari 14.

## 🤔 Expected Behavior

Checkboxes for selection should always be visible.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          | Safari 15.4
| Operating System |

**Comment by LFDanLu** [comment]
https://bugs.webkit.org/show_bug.cgi?id=238016

**Comment by LFDanLu** [comment]
Also patched in https://github.com/adobe/react-spectrum/pull/2804 by removing `contain: paint`

**Comment by snowystinger** [comment]
This was completed
