### ISSUE TITLE
ListBox does not render items when testing

### ISSUE THREAD

**Issue by cameronmcefee** [adobe/react-spectrum#3036]
# 🐛 Bug Report 

I'm working on writing tests with react-testing-library for a component using `ListBox`. However, when it renders, none of the items are present. This issue only exists in the tests. Rendering in a browser works fine.

## 🤔 Expected Behavior

When rendered, I expect to a ListBox with multiple items within it.

## 😯 Current Behavior

When rendered, I get a ListBox with an empty presentation div inside it.

## 💁 Possible Solution

 It works fine in a live example, so I'm wondering if this is just pebkac on my end.

## 🔦 Context

I'm currently unable to write tests for a vital component of my plugin since the testing behavior differs from the real world behavior.

## 💻 Code Sample

In the following test case, the test will fail.

```jsx
import { defaultTheme, Item, ListBox, Provider } from '@adobe/react-spectrum'
import { render } from '@testing-library/react'

test('Should render provided items', () => {
  const items = [{ name: 'Item 1' }, { name: 'Item 2' }]
  const component = render(
    <Provider theme={defaultTheme}>
      <ListBox aria-label="Testing" selectionMode="single" items={items}>
        {(item: any) => {
          return <Item key={item.name}>{item.name}</Item>
        }}
      </ListBox>
    </Provider>
  )
  component.debug()
  expect(component.queryByText('Item 1')).toBeInTheDocument()
})
```

The logged debug output is:

```html
<body>
  <div>
    <div
      class="spectrum_b37d53 spectrum_2a241c spectrum--light_a40724 spectrum--large_c40598 spectrum_9e130c spectrum--medium_9e130c spectrum--large_9e130c spectrum--darkest_9e130c spectrum--dark_9e130c spectrum--light_9e130c spectrum--lightest_9e130c"
      dir="ltr"
      lang="en-US"
      style="isolation: isolate; color-scheme: light;"
    >
      <div
        aria-label="Testing"
        class="spectrum-Menu_7ea47c"
        id="react-aria7424150742-1"
        role="listbox"
        style="padding: 0px; overflow-y: auto; overflow-x: hidden;"
        tabindex="0"
      >
        <div
          role="presentation"
          style="width: 0px; height: 0px; pointer-events: auto; position: relative;"
        />
      </div>
    </div>
  </div>
</body>
```

Note the lack of items inside the `ListBox` div.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  `3.16.5` |
| Browser          | Node (testing via Jest) |
| Operating System | MacOS |

**Comment by snowystinger** [comment]
Hey! Thanks for the issue. Definitely frustrating that you can't get your tests working. Have you looked at the tests we've written? https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/listbox/test/ListBox.test.js
That may shed light on what you need to do.

My guess is you need to mock/return some widths/heights. This is a virtualized component, so it needs to know the space it has available to render in. Unfortunately, most testing doms actually skip all of the layout calculations in order to make faster tests, so you need to "pretend" as though layout did happen and provide appropriate values for anything that needs it.

**Comment by cameronmcefee** [comment]
That does indeed make my items show up as expected. Pebkac it is. Thanks for the quick reply and the help, @snowystinger.
