### ISSUE TITLE
Collections: gracefully handle focus if focused item is removed from collection

### ISSUE THREAD

**Issue by chuckdries** [adobe/react-spectrum#3039]
# 🙋 Feature Request

When an item in a collection component (in our case a `useGrid` grid, but I imagine this change could be made to a number of components) has focus, then that item is removed from the collection, focus should be moved to an adjacent item in the collection for convenience.

## 🤔 Expected Behavior

When focused item is removed from collection, the next item in the collection receives focus, or the final item in the collection if the item that was removed was previously the final item.

## 😯 Current Behavior

The whole component loses focus. `selectionManager.focusedKey` retains the value of the removed item's key, even though that item is no longer in the collection (which sounds like a bug, but we're actually relying on this behavior - see next section)

## 💁 Possible Solution

We're working around this problem in our current codebase by keeping track of the previous collection, then in a useEffect we diff the collection against the previous, build a Set of keys that were just removed, and check if `selectionManager.focusedKey` is in the set. If it is, we figure out the next or final item in the current collection and call `selectionManager.setFocusedKey`

## 🔦 Context /  💻 Example

We currently have a `useGrid` grid that looks something like this
![deletable grid](https://user-images.githubusercontent.com/1351436/163471833-37ebcc42-5b9c-4168-a04f-a44b86857319.png)

where the user can focus the whole row, or the drag handle on the far left or the trash can in the middle. Clicking (or activating with focus) the row itself or the trash can removes the row from the collection.

## 🧢 Your Company/Team

Adobe Marketo Engage

**Comment by LFDanLu** [comment]
This sounds like a good idea, so far we've been relying on our Virtualizer code to handle focusing the collection itself when the node associated with the `focusedKey` is removed from the DOM. Thinking out loud, but perhaps we would support a user specified callback in `useGrid`/`useSelectableCollection` that is fired when the focused item is no longer in the DOM that would allow the user to customize where focus should be moved? Not entirely sure how prescriptive we should make this behavior. I'll bring this up in our next grooming session to see what the team thinks.

**Comment by LFDanLu** [comment]
Fixed by https://github.com/adobe/react-spectrum/pull/3885
