### ISSUE TITLE
Improve handling of nulls in mergeProps

### ISSUE THREAD

**Issue by rostero1** [adobe/react-spectrum#3042]
### Discussed in https://github.com/adobe/react-spectrum/discussions/3041

<div type='discussions-op-text'>

<sup>Originally posted by **rostero1** April 14, 2022</sup>
**Requested:**

`mergeProps({onBlur: () => {}}, {onBlur: null })`

**Expected:**

`{onBlur: () => {}}`

**Got:**

`{onBlur: null}`</div>

**Comment by snowystinger** [comment]
Hey! So talked with the team some more about this. We would actually like to keep the behavior as is, so there is a way to clear fields.

I think you can accomplish what you want by using `undefined` instead.

Examples of merging non-chained properties:
```
mergeProps({a: 1, b: 2}, {a: null, b: undefined}) // => {a: null, b: 2}
```

This is also how we want to treat our function chaining as well. This way you don't need to do something like:
```
let result = mergeProps({onFoo: () => {}}, {onFoo: null}) // => {onFoo: () => {}}
delete result.onFoo;
```

You can try this out here https://codesandbox.io/s/gallant-sun-szz49h?file=/src/App.js
The console should show it working in the way we would like it to.

**Comment by rostero1** [comment]
Thanks for running this by with your team.  I think the problem is that useButton returns null for onBlur, which is causing everything to get removed when I merge them with useFocusRing focusProps.

Here's a demo showing onBlur evaluating to null.

https://codesandbox.io/s/sleepy-meitner-xkc3v1?file=/src/App.js

**Comment by snowystinger** [comment]
I think you forgot to save. Sounds like our hook is returning null when it should be returning undefined though. I think that's probably a mistake we should correct.

Potentially coming from here https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/useFocus.ts#L53
