### ISSUE TITLE
Unknown type in useSelect menu props

### ISSUE THREAD

**Issue by nkalpak** [adobe/react-spectrum#3061]
# 🐛 Bug Report 

The return type of `useSelect<T>` doesn't use the generic argument passed to it, instead using `unknown` for its `menuProps` and forcing a type cast.

## 🤔 Expected Behavior

The return type of `useSelect<T>` should use the generic argument `T` to fill in the `menuProps` generic argument.

## 😯 Current Behavior

The return type of `useSelect<T>` doesn't use the generic argument `T`. Instead, the `menuProps` returned from it is typed as `AriaListBoxOptions<unknown>`.

## 💁 Possible Solution

Use the generic argument `T` passed to `useSelect` inside the `SelectAria` interface. This would cause `SelectAria['menuProps']` to have a type of `AriaListBoxOptions<T>`.

## 🔦 Context

I am trying to spread the props of `useSelect<T>` into a `ListBox` component which has prop `items` defined as `Iterable<T>`. This `items` definition inside the `ListBox` component comes from `@react-types/listbox`'s `ListBoxProps`.

When the `menuProps` returned by `useSelect<T>` are spread into the `ListBox` component, the `items` property contained within the `menuProps` has a type of `Iterable<unknown>`, while the `items` property contained within the `ListBoxProps<T>` has a type of `Iterable<T>`.

I expect here that the `menuProps` returned by `useSelect<T>` should fit into a `ListBoxProps<T>`, if`<T>` is the same.

## 💻 Code Sample

https://codesandbox.io/s/gifted-pine-if2czq?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-types/listbox   | 3.2.4
| @react-aria/select  | 3.5.4
| Browser          | X
| Operating System | X

**Comment by LFDanLu** [comment]
This makes sense, mirrors what we do in the `useComboBox` hook. Thanks for catching this!
