### ISSUE TITLE
TagGroup story cleanup

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#3073]
# 🐛 Bug Report 
- "not-removable" class is applied to Tags, it doesn't seem to be a real class https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/tag/src/Tag.tsx#L65 and it should be removed from our code (RS)
- using items prop' is a duplicate story, we already have one using the items prop above, the "icons" story (RS)
- remove withAnnouncing story

## 🧢 Your Company/Team

RSP

**Comment by reidbarber** [comment]
Closing, these items have been completed in https://github.com/adobe/react-spectrum/pull/3692
