### ISSUE TITLE
isVirtualized not working as expected

### ISSUE THREAD

**Issue by ctoph13** [adobe/react-spectrum#3084]
# 🐛 Bug Report 

Hi there. I use react-spectrum quite a bit, so just wanna start off with a thanks for the great library!

I'm recently trying to use the `isVirtualized` feature for `useMenu()`, as I have a list with tons of options that is quite sluggish if they're all on rendered/on the dom. I'm having some trouble getting it working, I've read through some of the source code for any hints, scoured the internet for documentation and examples of using this feature, but I can't seem to find anything to help me out, so unfortunately an issue is my last resort!

## 🤔 Expected Behavior

I have a menu list, using `useMenu()` and `useMenuItem()`, both passing in the `isVirtualized: true` in the options object. I have set a height on the `<ul>`, the `<div>` wrapping my menu, and on each `<li>` nested in the `<ul>`. I was expecting that, with these heights and the option being set to true for `isVirtualized`, react-aria would have what it needs to only render/mount a small subset of the list on the dom, which would update as I scroll up and down. For example, for a list of 1000 items, with heights of 50, and containers with a height of 500, i'd expect 11-20 or so items "loaded" since only 11 could be (partially) visible at once, and maybe a buffer for scrolling or someting.

It does seem a little strange though that I don't have to pass the height into the hook somehow, perhaps I'm missing something here, but I can't find any documentation or working examples. 

## 😯 Current Behavior

What happens is, I can see the 10-11 items in the list, but if I inspect the page with dev tools, all of the items are loaded. I have a sample application reproing the "issue" here: https://codesandbox.io/s/react-typescript-forked-4dyjqr?file=/src/App.tsx

In this example, I have `<ul>` and  surrounding`<div>` with heights of 500, and the `<li>`s have a height of 50. however, the list has 1000 items in it, and in the dev tools I can see all 1000 are in the document.

## 💁 Possible Solution

Just looking for a working example or some documentation, I'd say there's a pretty good chance I'm missing something in my implementation to get it working, but I have come up short on trying to find a solution. Hopefully any resolution here can be found by others in the future!

## 🔦 Context

I'm trying to load a large list of selectable options in a menu. The menu is searchable, however it is sluggish to trigger open and scroll around if there is no search criteria to limit down the options. I've tried to get the render performance of each option down as much as I can, but unfortunately it's still quite slow, not a fault of react-aria, it's just too many items at once. If I limit the number of items, it's nice and snappy and responsive, which is great, so I was hoping virtualization could solve my problem as it would only load a small subset of items at one time. 

## 💻 Code Sample

https://codesandbox.io/s/react-typescript-forked-4dyjqr?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.14.1
| react-stately  | 3.12.2
| react | 17.0.2
| Browser          | Chrome
| Operating System | macOS

## 🧢 Your Company/Team

react-aria, react-stately

**Comment by devongovett** [comment]
The `isVirtualized` option just tells react aria that you are using a virtualizer, which adjusts some things with the Aria attributes we produce. Virtualization itself will need to be done by a separate library. We use @react-aria/virtualizer for that, but we haven't written docs for it yet. You could also use another library like react-window instead.

**Comment by ctoph13** [comment]
Ah I see, well don’t I look foolish hahaha. Thanks for the quick response! I’ll give it a crack with a virtualizer.
