### ISSUE TITLE
numberfield ignores inc/dec

### ISSUE THREAD

**Issue by andelkocvjetkovic** [adobe/react-spectrum#3088]
# 🐛 Bug Report 

NumberField buttons for increment and decrement ignore onClick

## 🤔 Expected Behavior

Every click on buttons increment and decrement should trigger corresponding action.

## 😯 Current Behavior

For some reason buttons increment and decrement ignores first onClick action, and trigger corresponding actions after second onClick.

## 💁 Possible Solution

I rolled back to  @react-stately/numberfield: 3.0.4, and that fixed the bug

## 💻 Code Sample
https://stackblitz.com/edit/vitejs-vite-rk94ju?file=package.json

## 🌍 Your Environment
MacOS Big Sur

**Comment by reidbarber** [comment]
Seems like it's related to using Strict Mode. We have an umbrella issue for strict mode support at https://github.com/adobe/react-spectrum/issues/779.

**Comment by LFDanLu** [comment]
Closing in favor of the umbrella strict mode issue https://github.com/adobe/react-spectrum/issues/779
