### ISSUE TITLE
Create React Application project fails to build when React Spectrum is used 

### ISSUE THREAD

**Issue by vdua** [adobe/react-spectrum#3115]
# 🐛 Bug Report 

We have a project with create-react-app which uses react-scripts v4. We are planning to add adobe react-spectrum to it and the build is failing. We are able to create a simple create-react-app (without our code) where the issue is reproducible [0] 

[0] https://github.com/vdua/react-spectrum-issue

## 🤔 Expected Behavior

The project should build successfully

## 😯 Current Behavior

The project fails to build with the following error

```
Failed to compile.

./node_modules/@react-spectrum/meter/dist/main.css
ParserError: Syntax Error at line: 1, column 116
```

Tried to debug react-scripts build and found the culprit to be "postcss-values-parser": 2.0.1.  The following css rule
```
calc(var(--spectrum-global-dimension-size-2400)*-1))
```
is causing the parser to fail as it assumes that `-1` must be preceded by a space or a comma [1]. 

The issue is happening for other css files where -1 is being used in calc function as well, namely

* table
* form
* label
* overlays
* tooltip
* radio
* checkbox
* slider
* tabs
* button
* combobox
* numberfield
* switch
* picker
* meter
* layout
* dialog
* progress
* actiongroup

[1] https://github.com/shellscape/postcss-values-parser/blob/v2.0.1/lib/parser.js#L162

## 💁 Possible Solution

The latest react-scripts (v5) uses postcss-values-parser: 6.0.1. I tried using that but it caused errors with other libraries.

I looked at react-spectrum code to find out when this space was removed from the css files as it was working for us earlier in one of our projects and found out that overriding the above modules to following versions to be working fine.

```
"overrides": {
    "@react-spectrum/table": "3.1.1",
    "@react-spectrum/form": "3.2.4",
    "@react-spectrum/label": "3.3.4",
    "@react-spectrum/overlays": "3.4.4",
    "@react-spectrum/tooltip": "3.1.4",
    "@react-spectrum/radio": "3.1.5",
    "@react-spectrum/checkbox": "3.2.4",
    "@react-spectrum/slider": "3.0.4",
    "@react-spectrum/tabs": "3.1.1",
    "@react-spectrum/button": "3.6.0",
    "@react-spectrum/combobox": "3.2.0",
    "@react-spectrum/numberfield": "3.1.1",
    "@react-spectrum/switch": "3.1.3",
    "@react-spectrum/picker": "3.5.0",
    "@react-spectrum/meter": "3.1.3",
    "@react-spectrum/layout": "3.2.1",
    "@react-spectrum/dialog": "3.3.4",
    "@react-spectrum/progress": "3.1.3",
    "@react-spectrum/actiongroup": "3.3.1"
  },
  ```

The fix is in the `fix` branch[2]

[2] https://github.com/vdua/react-spectrum-issue/tree/fix

## 🔦 Context

We were using lerna monorepo for our packages and hoisting node_modules. Due to some constraints we needed to break the repos or remove hoisting. Since everything was working fine, we just tried the same package versions (no package-lock.json) and the build started to fail.

Now we think react-spectrum with the react-scripts v4 is not working as we were able to create a sample app without any of our code at all. 

## 💻 Code Sample

The reproducible code is hosted at https://github.com/vdua/react-spectrum-issue for

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | ^3.15.1 |
| Browser          | Not Related to Browser |
| Operating System | Mac OS 12.2.1 |

## 🧢 Your Company/Team

Adobe/AEM Forms

**Comment by snowystinger** [comment]
I do not see the resolution/override suggested in https://github.com/adobe/react-spectrum/issues/3044#issuecomment-1104567462
did that not work?

**Comment by vdua** [comment]
@snowystinger I will try with a fresh setup and see. Maybe I forgot to delete the package-lock.json/node_modules when trying that fix.

**Comment by vdua** [comment]
Not a bug since it works as suggested in #3044. The problem is with monorepos where overrides are not supported. (https://github.com/npm/cli/issues/4232). Closing the issue.
