### ISSUE TITLE
Time Field doesn't appear to support "millisecond" granularity

### ISSUE THREAD

**Issue by charliematters** [adobe/react-spectrum#3117]
# 🐛 Bug Report 

The "hour", "minute", and "second" granularities all work as expected, but setting "millisecond" in any of the examples causes all the time fields to disappear. You can see this in the code sandboxes e.g. https://codesandbox.io/s/naughty-jasper-u0feqc?file=/src/App.js

The AriaTimeFieldProps include "millisecond" in the granularity union

## 🤔 Expected Behavior

A segment should appear for milliseconds

## 😯 Current Behavior

The time segments do not get displayed:
https://codesandbox.io/s/naughty-jasper-u0feqc?file=/src/App.js

**Comment by devongovett** [comment]
Ah, it shouldn't be in the types since it isn't supported right now.

Do you have a use case for this?

**Comment by charliematters** [comment]
Ah ok, that makes sense. We don't have a particularly strong use case, but our system stores timestamps in "milliseconds since the epoch", so it would be nice to be able to edit with the same granularity as the data
