### ISSUE TITLE
aria-checked is not valid on an input type="checkbox"

### ISSUE THREAD

**Issue by jnurthen** [adobe/react-spectrum#3130]
# 🐛 Bug Report 

Using aria-checked on a checkbox is now a MUST NOT in ARIA-in-HTML
https://w3c.github.io/html-aria/#att-checked

## 😯 Current Behavior

spectrum/blob/main/packages/%40react-aria/checkbox/src/useCheckbox.ts#L48)

## 💁 Possible Solution

Remove all references to aria-checked. If spreading these props on an input type=checkbox they are not necessary

## 💻 Code Sample

https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/checkbox/src/useCheckbox.ts#L48

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by devongovett** [comment]
@jnurthen I assume we should also remove it from switch?
