### ISSUE TITLE
@react-aria/ssr@3.1.2 not updated in npm registry

### ISSUE THREAD

**Issue by tukotech** [adobe/react-spectrum#3156]
# 🐛 Bug Report 

In [packages/react-aria/ssr](https://github.com/adobe/react-spectrum/tree/main/packages/%40react-aria/ssr), observed that the package.json was updated to say that peer dependency now supports React 18, see line below: 
https://github.com/adobe/react-spectrum/blob/2b4abbc7c0bb10120056696a8ece65bf3efcf74a/packages/%40react-aria/ssr/package.json#L23

This is good news but unfortunately, the npm package is not updated. Npm registry still shows it was updated 3 months ago. 

## 🤔 Expected Behavior

Either replace package in npm or bump the version to 3.1.3 and push a new version to npm

## 😯 Current Behavior

Packages that has transitive dependencies to react-aria/ssr will warn user that the package does not support React 18.
`warning "react-bootstrap > @restart/ui > @react-aria/ssr@3.1.2" has incorrect peer dependency "react@^16.8.0 || ^17.0.0-rc.1".`

## 🔦 Context

I am using react-bootstrap with transitive dependency to react-aria/ssr. Also, just trying to clean-up warning in my system.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-bootstrap   | 2.4.0
| Browser          | Edge 101.0.1210.39 (Official build) (64-bit)
| Operating System | Windows 10

**Comment by devongovett** [comment]
We merged React 18 support only a couple days ago. We are testing and it will be released soon. https://github.com/adobe/react-spectrum/pull/3108
