### ISSUE TITLE
ActionMenu unable to infer item type and types to object

### ISSUE THREAD

**Issue by jluyau** [adobe/react-spectrum#3178]
# 🐛 Bug Report 

ActionMenu is not correctly typing the item parameter in the function as a child scenario

## 🤔 Expected Behavior

ActionMenu should be able to infer the item type (akin to what ActionGroup does):
![Screen Shot 2022-05-31 at 10 03 30 AM](https://user-images.githubusercontent.com/3901877/171232337-3776c4ce-10ee-48c8-a44e-d5cf0afdd399.png)

## 😯 Current Behavior

If providing a function as a child to ActionMenu, the `item` parameter is typed to a generic `object` rather than inferring the type from the `items` array:
![Screen Shot 2022-05-31 at 10 01 30 AM](https://user-images.githubusercontent.com/3901877/171232064-86d166f5-1b5c-4083-991e-66749785463a.png)

## 💻 Code Sample

https://codesandbox.io/s/nice-water-3tq2qv?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.18.0
| Browser          | Chrome 101.0.4951.64 
| Operating System | MacOS Catalina 10.15.7 

## 🧢 Your Company/Team

Adobe/Quarry

**Comment by LFDanLu** [comment]
Looks like we missed updating the export to something like:
```
const _ActionMenu = forwardRef(ActionMenu) as <T>(props: SpectrumActionMenuProps<T> & {ref?: FocusableRef<HTMLButtonElement>}) => ReactElement;
```
