### ISSUE TITLE
Tab through highlights both Add comment and add attachment buttons in SupportTicketAddDiscussionItemFormSection

### ISSUE THREAD

**Issue by tek85747** [adobe/react-spectrum#3180]
🐛 Bug Report

### Expected Behaviour
Only the current enabled button 'Add attachment' should be highlighted

### Actual Behaviour
Both 'Add attachment' and 'Add comment' buttons are highlighted
[removed]

#### Steps to Reproduce
[removed]

#### Platform and Version

Software | Version(s)
-- | --
react-spectrum | 3.15.1
Browser | Chrome 94.0.4606.81
Operating System | MacBook Pro

#### Sample Code that illustrates the problem
I'm using Spectrum [Button](https://react-spectrum.adobe.com/react-spectrum/Button.html) and [ButtonGroup](https://react-spectrum.adobe.com/react-spectrum/ButtonGroup.html), and observed that pressing any key through keyboard anywhere in screen highlights both 'Add comment' and 'Add attachment' buttons. 

My findings:  I tried to fix the issue by using View , Flex  and even  div
but still the issue is reproducible. I tried to replicate the issue using html buttons and they are working as intended. Looks like the problem is with the Spectrum Button . I've attached the screenshots for reference.

[removed]

**Comment by snowystinger** [comment]
Please do not include internal Adobe links and make sure your screen shots/videos can be shared publicly.

**Comment by tek85747** [comment]
https://codesandbox.io/s/reverent-snowflake-gfs5gz?file=/src/App.js

**Comment by tek85747** [comment]
Thank you for fixing this issue @snowystinger @devongovett.
