### ISSUE TITLE
Incorrect types for useMenuTriggerState argument

### ISSUE THREAD

**Issue by alirezamirian** [adobe/react-spectrum#3194]
`MenuTriggerProps` is used to type the options of `useMenuTriggerState`:
https://github.com/adobe/react-spectrum/blob/a0a88da217db1cff67be1bdc94490b3a7002b6f3/packages/%40react-stately/menu/src/useMenuTriggerState.ts#L33

It includes fields such as `align` or `shouldFlip` that are irrelevant to `useMenuTriggerState`.

**Comment by LFDanLu** [comment]
Makes sense, those should be present in SpectrumMenuTriggerProps only, thanks for catching this

**Comment by lishichengyan** [comment]
following up on this issue - is it OK to change 
`export function useMenuTriggerState(props: MenuTriggerProps): MenuTriggerState  { `
to
`export function useMenuTriggerState(props: OverlayTriggerProps): MenuTriggerState  {`
since the type `MenuTriggerProps` is too "broad" in this case?

**Comment by iamwillpowell** [comment]
Closing. Fixed in [#4150](https://github.com/adobe/react-spectrum/pull/4150)
