### ISSUE TITLE
Drop label in HiddenSelect

### ISSUE THREAD

**Issue by donaldpipowitch** [adobe/react-spectrum#3198]
# 🙋 Feature Request

If I understood correctly `<HiddenSelect/>` only needs a `label` so FireFox can "identify the `<select>`". Correct? That means it doesn't need be the _actual_ label, but it could be a generated one? If yes this could help in adopting react-aria as tests like `expect(result.getByText('Some Actual Label')).toBeInTheDocument();` don't need to be rewritten (this would currently fail with "You queried for ..., but two elements were found. Please use getAllByText().").

## 🤔 Expected Behavior

`<HiddenSelect/>` creates some randomized label for Firefox. Existing tests which query the actual label visible to the user will not be affected by adopting react-aria.

## 😯 Current Behavior

`<HiddenSelect/>` uses the same label which is also used for the frontend. This will likely create _two_ `<label/>`'s with the same text content which might break tests which rely on just one label with that text content.

## 💁 Possible Solution

Create a randomized label.

Maybe there are other ways to easily hide the label during tests. (Or is it even save to _not_ render `<HiddenSelect/>` in tests at all as it is just needed for browser form autofill, mobile form navigation, and native HTML form submission? This would at least help with unit tests, but E2E tests.)

## 🔦 Context

Adopting react-aria in an existing code base.

**Comment by donaldpipowitch** [comment]
Thank you very much for looking into it.

**Comment by devongovett** [comment]
The label usually does matter I think because it affects the behavior of autofill. Some browsers look for common labels like "email", "name", etc. and use this to inform how autofill behaves.
