### ISSUE TITLE
intl-messageformat resolves to broken release

### ISSUE THREAD

**Issue by sanyabas** [adobe/react-spectrum#3201]
# 🐛 Bug Report 

package.json in `@internationalized/message` has [dependency](https://github.com/adobe/react-spectrum/blob/1187fa3bfea1aed7b49d39a22b26944c7d017a82/packages/%40internationalized/message/package.json#L21) of `intl-messageformat: "^9.12.0"`, which may be resolved to version `9.13.0`. This release is broken, it crashes on lots of rather old browsers, because it doesn't check for availability of `Intl.Locale`. Bug was fixed in version `10.0.0`, breaking changes from changelog don't seem important for react-aria.
Issue in intl-messageformat repo: https://github.com/formatjs/formatjs/issues/3588#event-6612532878
Changelog for version 10.0.0:  https://github.com/formatjs/formatjs/releases/tag/intl-messageformat%4010.0.0

## 🤔 Expected Behavior

No crashes

## 😯 Current Behavior

Crashes when using `useSelect` on browser not supporting `Intl.Locale`

## 💁 Possible Solution

Bump dependency version to `^10.0.0`.

## 🔦 Context

Affects any usage of `useSelect`.

## 💻 Code Sample

Open this sandbox in Safari 13 or below (or any browser not supporting Intl.Locale): https://codesandbox.io/s/wandering-leftpad-wfn4hi?file=/src/App.js
There will be an error in console: `TypeError: undefined is not a constructor (evaluating 'new Intl.Locale(supportedLocales[0])')`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.18.0
| Browser          | Safari 12
| Operating System | MacOS 10.12.6

**Comment by mantagen** [comment]
Do we know when the fix will be released in the `react-aria` package? We're on `3.17.0` and experiencing this issue.

**Comment by snowystinger** [comment]
Sorry for the longer delay between last release and our upcoming one, our company had a summer shut down. We're aiming for end of the month.
