### ISSUE TITLE
Allow to maintain the Item state on tab change

### ISSUE THREAD

**Issue by yesil** [adobe/react-spectrum#3225]
# 🙋 Feature Request

I would like to be able to keep the tab content state between tab changes.

Given:
A component with a RadioGroup as a tab content
Set the defaultValue of the RadioGroup  from the context (useContext)
Change the selected radio option in the group above
Change tab
Change tab back to the radio group one

## 🤔 Expected Behavior
RadioGroup state is maintained, and the default option is not selected

## 😯 Current Behavior
RadioGroup state is NOT maintained, and the default option IS selected

## 💁 Possible Solution

Add an option the keep the state of a tab item even when it is not displayed

## 🔦 Context

We are developing a UI component that can be opened with a context defined by the consumer.
The UI component state falls back to the context values on tab changes, whereas from UX point of view, UI state must be maintained.

## 🧢 Your Company/Team

Adobe

**Comment by reidbarber** [comment]
Seems like a good use case, but we can't change the current default behavior. We could look at adding a new optional prop that determines this behavior. 

Maybe something like this:

`tabMountBehavior?: 'active' | 'immediate' | 'lazy'`

- **active** (default): Mounts a tab when it is selected, then unmounts it when another tab gets selected. State inside a tab will not persist when switching tabs. 

- **immediate**: Immediately mounts all tabs. State inside a tab will persist when switching tabs.

- **lazy**: Mounts a tab when it is selected, and doesn't unmount it when another tab gets selected. State inside a tab will persist when switching tabs.

**Comment by yesil** [comment]
I think the option should be given to the developer. Hoisting the state of a form with a lot of fields in a tab is a lot of work and we are not using a state manager unfortunately.

**Comment by devongovett** [comment]
Hoisting shouldn't be that difficult if you use React context. And anyway, "a lot of work" is not a good enough reason for us to support this. There are many considerations and side effects of such a change as well, such as accessibility, keyboard focus behavior, memory usage, performance, etc. The future React [Offscreen](https://reactjs.org/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.html#offscreen) feature might help at some point.

**Comment by snowystinger** [comment]
Closing as not doing for React Spectrum v3. If you're using RAC, you should be able to use https://react-spectrum.adobe.com/react-aria/Tabs.html#tabpanel
