### ISSUE TITLE
Explicit types for interaction returns

### ISSUE THREAD

**Issue by maxmezzomo** [adobe/react-spectrum#3232]
# 🙋 Feature Request

I think it would be an improvement to explicitly type the returns for hooks such as useHover, usePress...etc

## 🤔 Expected Behavior

To return a more precise type representing what the hooks return.

## 😯 Current Behavior

The hooks currently return an accurate but extensive type: `HTMLAttributes<HTMLElement>`.

## 💁 Possible Solution

Hover Result Could for example be implemented as such:

Currently
```
interface HoverResult {
  /** Props to spread on the target element. */
  hoverProps: HTMLAttributes<HTMLElement>,
  isHovered: boolean
}
```
Could be
```
interface HoverResult {
  /** Props to spread on the target element. */
  hoverProps: Pick<
    HTMLAttributes<HTMLElement>,
    | "onPointerLeave"
    | "onPointerLeave"
    | "onPointerLeave"
    | "onPointerLeave"
    | "onMouseLeave"
    | "onTouchStart"
  >;
  isHovered: boolean;
}
```

## 🔦 Context

A while ago I ran into this issue whilst using framer-motion which provides its motion wrapper for html elements. For example, youc can use motion.div rather than div so the animated styles can be updated directly. Motion will provide different types for certain attributes (onAnimationStart.. etc). Spreading hover props on an animated component is then problematic for the ts compiler.

## 💻 Examples

Below is a link to a simple codesandbox example

https://codesandbox.io/s/flamboyant-mcclintock-5mqige?file=/src/App.tsx

[![Edit flamboyant-mcclintock-5mqige](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/flamboyant-mcclintock-5mqige?fontsize=14&hidenavigation=1&theme=dark)

**Comment by devongovett** [comment]
See this discussion for an explanation: https://github.com/adobe/react-spectrum/discussions/1618#discussioncomment-396010

We'd like to keep our types equivalent to the DOM API so that we can add or remove props returned from our hooks without breaking changes. It's unfortunate that framer-motion has props with the same names as DOM props but different types - that seems like the real issue here.

**Comment by maxmezzomo** [comment]
I see, I was thinking also along those lines that it may be for that reason and I think its a sensible way to go.
Perhaps this would also be solved if the return type were based off a generic. 
This was a separate issue I was consering opening. If useHover, for example, took a generic, the return type for the hoverProps could be `HTMLAttributes<T>` where T extends either HTMLElement or something else. The use case I had in mind was for SVG elements.
All of this might become a little of topic and may introduce unexpected complexities; but I'm happy make an issue or discussion if anyone thinks having a look at the generic option is interesting.

**Comment by devongovett** [comment]
Yeah that seems like an interesting option to explore
