### ISSUE TITLE
react-aria and react-stately should re-export all types

### ISSUE THREAD

**Issue by donaldpipowitch** [adobe/react-spectrum#3240]
# 🙋 Feature Request

If you use `react-aria` and/or `react-stately` with TypeScript you still have to manage other dependencies  to be able to access all needed types (e.g. `import type { AriaListBoxOptions } from '@react-aria/listbox';` or `import type { Node } from '@react-types/shared';`). For a better developer experience both libs should re-export all the types which are used.

## 🤔 Expected Behavior

```
import type { AriaListBoxOptions , Node } from 'react-aria';
```

## 😯 Current Behavior

```
import type { AriaListBoxOptions } from '@react-aria/listbox';
import type { Node } from '@react-types/shared';
```

## 🔦 Context

I use pnpm and want to enforce people to only import direct dependencies (and not dependencies of dependencies). That's why I need to manage libs like `@react-aria/listbox` _on top of_ `react-aria`.

**Comment by LFDanLu** [comment]
This sounds reasonable to me, will bring this up with the team in our next grooming session.
