### ISSUE TITLE
WHCM / forced-colors support missing in useDatePicker, RangeCalendar

### ISSUE THREAD

**Issue by aardrian** [adobe/react-spectrum#3260]
# 🐛 Bug Report 

The useDatePicker component and RangeCalendar use colors to indicate selected, unavailable, restricted, and spanning dates. There is a two-fold risk/bug here:

1. When Windows High Contrast Mode / Contrast Themes / forced-colors mode is activated, the colors are all lost;
2. This is a potential [WCAG Success Criterion 1.4.1 Use of Color](https://www.w3.org/WAI/WCAG21/quickref/#use-of-color) failure.

I encountered this in two date picker controls, which appear to be related:

- useDatePicker unavailable dates:
https://react-spectrum.adobe.com/react-aria/useDatePicker.html#unavailable-dates
- RangeCalendar:
https://react-spectrum.adobe.com/react-spectrum/RangeCalendar.html

## 🤔 Expected Behavior

When I switch into High Contrast Mode, the operating system assigns [pre-defined system colors](https://adrianroselli.com/2021/02/whcm-and-system-colors.html#CSS4) to certain types of content. Buttons get a specific border color, links get a specific link color, and so on. _If_ the native controls are used (so `<button>` versus `<div role="button">`, for example). Custom styles such as background colors, shadows, and even gradients will go away.

However, the interface should still make it possible for me to visually distinguish the different states of a control. I should be able to visually identify each state while in High Contrast Mode.

## 😯 Current Behavior

All dates are exposed as white text on black (or system color text on system color background), as expected. But no icons, marks, shapes, or other indicators are added to compensate for the loss of color.

Here is the useDatePicker calendar showing disabled, unavailable, available and selected days using red, gray, white, and blue:
<img width="246" alt="The dark gray month grid. Days in the past that are disabled are gray text. Days you cannot select are red text. Days available for selection are white text. The selected day is white on a blue square." src="https://user-images.githubusercontent.com/1376607/175346391-3b6a3ee2-afd3-4c53-abae-36804a17522d.png">

Here is the useDatePicker calendar with Windows 11 Contrast Themes active demonstrating how the disabled, unavailable, available and selected days use white (default) for all:
<img width="251" alt="The month grid as white text on black. All days are white text. Days in the past that are disabled are white. Days you cannot select are white. Days available for selection are white. The selected day is white with no other indicator." src="https://user-images.githubusercontent.com/1376607/175346608-ecff7cbb-90b3-4844-b6c3-fb0559e22450.png">

Here is the RangeCalendar showing available, weekend and the selected start, selected end, and spanning day using light gray, light gray with a slash, blue with a ring, blue, and subdued blue:
<img width="253" alt="The dark gray month grid. Days available for selection are light gray text. Weekend days are light gray text with a light gray slash through the text. The selected start day is light gray text on a blue circle with a separated blue ring. The selected end day is light gray text on a blue circle. The days covered in the spanning time are light gray text on a subdued blue background." src="https://user-images.githubusercontent.com/1376607/175347661-855c21ab-d918-4693-9094-52a360145d4c.png">

Here is the RangeCalendar demonstrating how the available, weekend and the selected start, selected end, and spanning days use white (default) text, with a black slash for weekends:
<img width="253" alt="The month grid as white text on black. All days are white text. Weekend days are white text with a black slash through the text. The selected start day is white text with no other indicator. The selected end day is white text with no other indicator. The days covered in the spanning time are white text with no other indicator." src="https://user-images.githubusercontent.com/1376607/175347751-9c4c7367-db87-47f5-be9a-3bfe0b55bac3.png">

In those screen shots, the second image of each pair is in exactly the same state as the first — same selection, same everything.

I cannot visually tell which is available, which is selected, and so on.

## 💁 Possible Solution

Use methods other than solely color. Icons, shapes, borders, etc. can help and potentially satisfy the WCAG concern as well.

Do not rely on [`forced-color-adjust`](https://caniuse.com/?search=forced-color-adjust), partially because of support and partially because people who rely on WHCM can be adversely affected by the colors you might force.

## 🔦 Context

If I want to use this in a context where WCAG conformance is a requirement, this bug prevents it.

If I want to support any users of WHCM, they will be unable to use this control, so I cannot use it nor recommend it.

Sadly, I encounter this gap frequently. As a result, I have reference material linked from this post: [WHCM and System Colors](https://adrianroselli.com/2021/02/whcm-and-system-colors.html)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0.0
| Browser          | Chrome 102, Edge 102, Firefox 101
| Operating System | Windows 10/11

**Comment by devongovett** [comment]
Thanks for the report! We are currently working on an overhaul to WCHM across all of our React Spectrum components: #2830.

Handling this in the react-aria docs as well is something we need to figure out, as most of the examples are very lightly styled (styling is not really the point of the examples). But would be good to demonstrate somehow as well for devs to integrate into their own components using our library.

**Comment by aardrian** [comment]
Ah, I only checked open issues, not PRs. Thanks for the reference.

I cannot tell from the activity what the timeline is for that to land. Can you guesstimate?

**Comment by devongovett** [comment]
I think it should be soon (1-2 weeks I'd guess). Once it lands we'll do some testing, and then fix any issues that we discover before it is released.
