### ISSUE TITLE
Hidden field getting focus with Tab during Add attachments

### ISSUE THREAD

**Issue by tek85747** [adobe/react-spectrum#3271]
# 🐛 Bug Report 

Unknown field getting focus while pressing Tab during Add attachments

## 🤔 Expected Behavior

After Select files, next visible button is 'Cancel' button and should be highlighted 

## 😯 Current Behavior

After Select files, user has to press 'Tab' two times to get focus to cancel button

## 🔦 Context

Step 1: Click on 'Add attachment' button
Step 2: Click on Discussion header with mouse
Step 3: Now press 'Tab' on keyboard (2 times)
Step 4: After 'Select files' is highlighted, press 'Tab'

## 🌍 Your Environment

react-spectrum | 3.15.1
-- | --
Browser | Chrome 94.0.4606.81
Operating System | MacBook Pro

**Comment by snowystinger** [comment]
Hey! thanks for the issue. Did you mean to attach a codesandbox or link to an example where we can reproduce your steps?

**Comment by tek85747** [comment]
As there are inter dependencies I cannot reproduce this issue in codesandbox. You can check this issue here: https://stage.adminconsole.adobe.com/F1AB5BD45908E2FD0A494121@AdobeOrg/support

**Steps to reproduce the issue:**
Step 1: Login to [Admin Console](https://stage.adminconsole.adobe.com/F1AB5BD45908E2FD0A494121@AdobeOrg/support) and enable FF 'temp_react_port_support_ticket_add_discussion_item'
Step 2: Open any support case
Step 3: Click on 'Add attachment' button
Step 4: Click on Discussion header with mouse
Step 5: Now press 'Tab' on keyboard (2 times)
Step 6: After 'Select files' is highlighted, press 'Tab'

Expected result: After Select files, next visible button is 'Cancel' button and should be highlighted

Actual result: After Select files, user has to press 'Tab' two times to get focus to cancel button

**Comment by snowystinger** [comment]
Please do not post any links to adobe in this issue as it is public. If you need more help, please reach out in Slack.

**Comment by ktabors** [comment]
Is there codesandbox to demonstrate this issue with pure React Spectrum outside of an application?

**Comment by snowystinger** [comment]
Closing. We can reopen if a reproduction is shared.
