### ISSUE TITLE
DatePicker focus and blur events are not being triggered

### ISSUE THREAD

**Issue by pavithra-ramaswamy** [adobe/react-spectrum#3272]
# 🐛 Bug Report 

Tried to invoke a few event based functions except for onChange the rest are not being invoked.

For example the on focus and blur functions: 
let elemAttrs = {
  onFocusChange:(e) => this.onFocusChange(e),
  onFocus:(e) => this.onFocus(e),
  onBlur:(e) => this.onBlur(e)
};

## 🤔 Expected Behavior

Focus and blur related event handlers should be triggered
 
![image](https://user-images.githubusercontent.com/92180288/176269871-4428a2cc-0fbc-4fa6-a084-6ddfe18e8918.png)

## 😯 Current Behavior

onBlur, onFocus, onFocusChange are not being triggered correctly

## 💻 Code Sample

const onFocusChange =() => {
    console.log("onFocusChange called");
}

const onFocus =() => {
    console.log("onFocus called");
}

const onBlur =() => {
    console.log("onBlur called");
}

let elemAttrs = {
  ....,
  onFocusChange:(e) => this.onFocusChange(e),
  onFocus:(e) => this.onFocus(e),
  onBlur:(e) => this.onBlur(e)
};

<DatePicker {...elemAttrs} />

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.19.0
| Browser          | Chrome
| Operating System | MacOS

**Comment by makarandkeer** [comment]
I am also facing same problem of `onBlur` not getting invoked. Any ETA on fix?

**Comment by joshuajaco** [comment]
We are facing the same problem using the `useTimeField` hook.

**Comment by ktabors** [comment]
@joshuajaco thanks for the info. The draft pr linked to should fix this for the react-aria date hooks and the React Spectrum date components.
