### ISSUE TITLE
DatePicker is not localizing “Time” text as per user’s locale

### ISSUE THREAD

**Issue by makarandkeer** [adobe/react-spectrum#3297]
### Expected Behavior 
`DatePicker` should localize `Time` text as per user’s locale

### Actual Behavior

`DatePicker` is not not localizing `Time` text as per user’s locale (refer screenshot below)
![image](https://user-images.githubusercontent.com/32228809/178536366-3f46449b-aa72-465c-ac5b-c3b93820a8b3.png)

**Comment by LFDanLu** [comment]
Thanks for reporting this, looks like we missed localizing the TimeField label in general.
