### ISSUE TITLE
TableBody contents at some views will infinitely resize, causing the scrollbars to flicker on/off

### ISSUE THREAD

**Issue by jluyau** [adobe/react-spectrum#3329]
# 🐛 Bug Report 

## 🤔 Expected Behavior

Scrollbars should not show at all when displaying the loading spinner or empty state

## 😯 Current Behavior

At some views of table view (via resizing and zooming in/out) with a height of 100%, the contents of the table body (either loading spinner or empty view) will infinitely shift due to the container resizing. If scrollbars are always displayed (either on Windows or as a Mac option), the scrollbars will flicker on and off.

## 🔦 Context

Poor user experience for anyone using the tables

## 💻 Code Sample

https://codesandbox.io/s/focused-brattain-2eqlsh?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.19
| Browser          | Chrome 103.0.5060.114
| Operating System | MacOS Monterey 12.4, Windows 11
## 🧢 Your Company/Team

Adobe/Quarry

**Comment by tiffany-sy-lin** [comment]
video of the flickering due to the scroll bars

https://user-images.githubusercontent.com/20674023/180329697-fb0ecbf7-525e-412c-a409-34105f154c83.mov

**Comment by jluyau** [comment]
Here's the bug on a Windows 11 tablet, Chrome 103.0.5060.134
https://user-images.githubusercontent.com/3901877/180330501-ae0bd0d9-c314-4ab7-a09c-fdcc479772f8.mp4

**Comment by reidbarber** [comment]
Did an initial investigation, and it looks like the offending commit is https://github.com/adobe/react-spectrum/commit/418e59ba5be2418cb52ea5087162a6faeeb1cc5a
