### ISSUE TITLE
Unable to focus elements when multiple FocusScope used

### ISSUE THREAD

**Issue by surajahmed** [adobe/react-spectrum#3330]
# 🐛 Bug Report 

When we use `FocusScope` more than one time with `contain={true}`. We are unable to focus on elements inside the rest of the `FocusScope`.  This was working fine in the earlier version `@react-aria/focus@3.2.2`

## 🤔 Expected Behavior

Should be able to focus/click elements.

## 😯 Current Behavior

`@react-aria/focus@3.2.2`
Unable to focus inside FocusScope when used multiple times.
 
## 🔦 Context

We are using multiple modal components. All the modal contents are wrapped with FocusScope with `contain={true}`. Focus is contained in the first modal and is unable to focus on the rest of the modal contents.

## 💻 Code Sample

CodeSandbox Link https://codesandbox.io/s/silly-snyder-kj8tu3

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Chrome
| Operating System | MacOS 12.2.1
| @react-aria/focus | 3.6.1

## 🧢 Your Company/Team

React Native Aria

**Comment by snowystinger** [comment]
Hey, thanks for the issue. This is working as intended, you can't have two sibling scopes that both contain, each one will try to make sure focus is within itself and that the focus never leaves.

Can you explain a bit more about your use case?

I think what you're trying to implement, and I could be wrong, is a roving tabIndex, essentially like a RadioGroup. In that case, you should stop using contains and follow along with an implementation I did for a AxeCon talk this year where I implemented a RadioGroup's roving tabIndex https://www.youtube.com/watch?v=HpSYnoPh6aE&t=589s

**Comment by surajahmed** [comment]
Thanks, @snowystinger.
We're trying to open a modal from another modal.
Both the modals are wrapped in `FocusModal` with `contain={visible}`.
When both the modals are visible, we have two modals with `contain={true}`.

We need to set `contain={false}` manually when a new modal pops up. Thanks for your help, we'll do it by wrapping all the modals in a Provider and keeping track of the current active modal.

**Comment by snowystinger** [comment]
I see. Some extra information then, we only allow one modal to be visible at a time. If a new one opens, the previous one closes. It offers a bit nicer UX as well, you don't have to back track through numerous modals to get back to the page.
That said, our FocusScope should be able to handle this. You can move from a containing focus scope parent down into a nested contain focus scope, however, you cannot move up from a child to a parent.

The codesandbox you shared isn't quite a representation of the issue I don't think?

Something more like this https://codesandbox.io/s/reverent-colden-6u7hve?file=/src/App.js it's a partial example, I'd expect an underlay to prevent mouse users from interacting with the buttons in the first scope. But you can see if you tab to "1 One", press space, then tab twice more, you'll move from the first scope to the second scope, and then via keyboard you cannot leave the second scope. Again, you'd need something to move focus to the second scope, maybe autofocus or something and you'd need to prevent mouse interactions with the first scope, but it shows that our FocusScopes can handle this flow.

**Comment by surajahmed** [comment]
Thanks for the example @snowystinger . I've made a few changes to your example and introduced a third scope. Can you please tell me how can I focus on the third scope?

**Comment by snowystinger** [comment]
The third dialog you have isn't part of the second dialog, it's incidental that it opened it. The second dialog should close when it opens the third. Keyboard navigation works again here https://codesandbox.io/s/peaceful-montalcini-5pk6wz

**Comment by surajahmed** [comment]
Okay, got it. Thanks for your help.
