### ISSUE TITLE
ListBox is not working inside Tabs

### ISSUE THREAD

**Issue by collegewap** [adobe/react-spectrum#3339]
# 🐛 Bug Report 

When I use ListBox inside the tabs, list items are not displayed.

## 🤔 Expected Behavior

Items should be displayed

## 😯 Current Behavior

Items are not displayed

## 💁 Possible Solution

NA

## 💻 Code Sample

https://stackblitz.com/edit/react-ts-bhnpas

Repo: https://github.com/collegewap/react-spectum-listbox-tab-issue 
## 🌍 Your Environment

Local

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.19.0
| Browser          | Chrome
| Operating System | Windows

## 🧢 Your Company/Team

Adobe/Sales Platform

**Comment by snowystinger** [comment]
Issue is with React StrictMode, please remove that and check that it works.
This will be covered by https://github.com/adobe/react-spectrum/issues/779
