### ISSUE TITLE
useTable ignores provided id prop and generates a new one

### ISSUE THREAD

**Issue by moelmaghraby** [adobe/react-spectrum#3349]
# 🐛 Bug Report 

When using UseTable and passing an id with the props, this id is ignored and a new one is generated

## 🤔 Expected Behavior

it should use the provided id and generate a new one if an id isn't provided

## 😯 Current Behavior
the provided id is ignored and a new one is generated

## 💁 Possible Solution

passing props.id when using useId here: https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/table/src/useTable.ts#L60
I don't think this is intentional/needed, would be happy to provide a PR if this is not indeed intentional

## 💻 Code Sample
https://codesandbox.io/s/react-spectrum-template-forked-5kkzxl?file=/src/App.js

**Comment by snowystinger** [comment]
looks unintentional if you don't mind creating a PR that would be much appreciated
