### ISSUE TITLE
Empty TableView does not focus select all checkbox on tab

### ISSUE THREAD

**Issue by jluyau** [adobe/react-spectrum#3377]
# 🐛 Bug Report 

Tabbing through an empty table view does not focus the select all checkbox on Tab, but will focus on Shift+Tab

## 🤔 Expected Behavior

Select all checkbox focused both ways

## 😯 Current Behavior

Select all checkbox focused on Shift+Tab

## 🔦 Context

Reported by a team using inventory

## 💻 Code Sample

https://codesandbox.io/s/magical-banzai-6xzkh5?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.19.0
| Browser          | Chrome
| Operating System | MacOS

## 🧢 Your Company/Team

Adobe/Quarry

**Comment by LFDanLu** [comment]
Thanks @jluyau, we've added a ticket to our project board for tracking called "TableView interactive empty state support", will need to finish discussing w/ Spectrum Design and Accessibility about the desired behavior. Will close this issue, feel free to track the new ticket via https://github.com/orgs/adobe/projects/19/views/4
