### ISSUE TITLE
Add (back) support for custom icons sizes in buttons

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#3381]
# 🐛 Bug Report 

Since #2073 has been merged it is impossible set a custom icon-size for icons inside eg an `ActionButton` like this

```typescript
        <ActionButton height="size-600" width="size-600">
          <Add size='M' />
        </ActionButton>
```

## 🤔 Expected Behavior

The icon size is `M`

## 😯 Current Behavior

The icon is rendered as size `S` as the slot-provided value now wins

## 💁 Possible Solution

A possible solution would be to add an additional parameter to `useSlotProps`

```typescript
export function useSlotProps<T>(props: T & {id?: string}, defaultSlot?: string, priorityProps?: Partial<T>): T {
  let slot = (props as SlotProps).slot || defaultSlot;
  let {[slot]: slotProps = {}} = useContext(SlotContext) || {};
  let prioProps = priorityProps ? {id: props.id, ...priorityProps} : {id: props.id};

  return mergeProps(props, mergeProps(slotProps, prioProps));
}
```

and change `Icon.tsx` to

```typescript
export function Icon(props: IconProps) {
  props = useSlotProps(props, 'icon', {'size': props.size});
...
```

Another solution would be to extend `SpectrumActionButtonProps`, ... allowing me to control the icon size there.

## 🔦 Context

I use `ActionButton` to implement a navigation panel where I use larger buttons (controling their width/height) hence I'd like to use there buttons of size M/L.

## 💻 Code Sample

```typescript
        <ActionButton height="size-600" width="size-600">
          <Add size='M' />
        </ActionButton>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
Thanks for the issue! However, this is working as intended, you aren't meant to change the size of an icon inside an action button. The size is as the Spectrum Design system intends

**Comment by tomsontom** [comment]
well but why do I then have to possibility to define height/width?

**Comment by snowystinger** [comment]
Valid question, maybe those should not be allowed props on the ActionButton and we overlooked them. I'll bring it up with the team to make sure. However, if you do anything crazy with them, it'll probably look bad, and that should be at least a mild deterrent.

**Comment by tomsontom** [comment]
May I also add that https://spectrum.adobe.com/page/action-button/#Size shows buttons in different sizes (my use case could be covered by `extra-large`)

**Comment by snowystinger** [comment]
Yes, I can see the confusion, that is known as t-shirt sizing, and we have not implemented it yet. It's on our roadmap, but we have a few other things to do before we can implement it. Specifically, we're waiting for our token system to finish a breaking change, then we should be able to take it on.

**Comment by ToyWalrus** [comment]
> Specifically, we're waiting for our token system to finish a breaking change, then we should be able to take it on.

@snowystinger Is there any ETA on this yet?

**Comment by snowystinger** [comment]
I'm unfortunately not the one to give ETA's. @matthewdeutsch ?
