### ISSUE TITLE
DatePicker `onClose` called immediately after opening using React 18's Strict Mode during development

### ISSUE THREAD

**Issue by EddyVinck** [adobe/react-spectrum#3395]
# 🐛 Bug Report 

I was looking at the date picker examples here https://react-spectrum.adobe.com/react-aria/useDatePicker.html and I then checked out the styled Tailwind CSS example.

I downloaded the code from the CodeSandbox, and tried running it in my project, but the calendar kept closing when I tried to open it.

## 🤔 Expected Behavior

The datepicker should work the same during development mode with or without strict mode enabled.

## 😯 Current Behavior

The calendar closes immediately, but only in development mode with strict mode.

Turning off strict mode or running in production does not have the problem.

## 💁 Possible Solution

I think this may have to do with `useEffect` running twice in strict mode, but that is an assumption.

## 🔦 Context

I am trying to use a code example, tried copying it 1:1 into my project, yet it doesn't work and it's not very apparent as to why that is.

## 💻 Code Sample

I copied the original CodeSandbox and just added `React.StrictMode` around the `<App>`

https://codesandbox.io/s/practical-wind-d5gxlp?file=/src/index.js

## 🌍 Your Environment

The exact same as the [CodeSandbox](https://codesandbox.io/s/white-breeze-rer8g2?file=/src/DatePicker.js) but I was also using NextJS

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | Same as in Codesandbox above |
| Browser          | Chrome (latest)
| Operating System | MacOS |

**Comment by reidbarber** [comment]
Thanks for reporting! We have an umbrella issue for strict mode issues at https://github.com/adobe/react-spectrum/issues/779, so I'll close this in favor of that.

**Comment by EddyVinck** [comment]
Thanks @reidbarber!
