### ISSUE TITLE
[useButton]: useButton not extracting `className` from props as DOMProps

### ISSUE THREAD

**Issue by sachinsom93** [adobe/react-spectrum#3397]
# 🐛 Bug Report 

When passing `className` to a Button component which is created using useButton props, `className` is not passing from Button component to underlying button component.
Here, `button` is the HTML tag, inside which we spread `useButton` props,
And, `Button` referencing to a react Component that contain the `button ` tag. 

According to my Understanding,  `buttonProps` didn't contain `className` as it is not extracted from `props` via `useButton`.

## 🤔 Expected Behavior
When passing `className` inside `props`, `useButton` should insert it inside `buttonProps.`

## 😯 Current Behavior

Currently, `useButton` is not extracting 'id' as DOMProps from given `props` argument.

Suppose, we have a Button Component inside `Button.jsx`, which return a button element having spreaded buttonProps.
I'm logging 'props' and 'buttonProps'.
```
import React from 'react';
import { useButton } from 'react-aria';

function Button(props) {
  const { buttonProps } = useButton(props);
  const btnRef = React.createRef(null);
  console.log({ props });
  console.log({ buttonProps });
  return (
    <button ref={btnRef} {...buttonProps}>
      {props.children}
    </button>
  );
}

export default Button;
````
Here, is my `App.js` where I'm using Button component, currently I am passing Id and className to it.
```
import React from 'react';
import './style.css';
import Button from './Button';

export default function App() {
  return (
    <div>
      <Button className="exampleBtn" id="btn">
        Example Button
      </Button>
    </div>
  );
}
```
And, here is the logging result.
![image](https://user-images.githubusercontent.com/64790109/184326446-f58e0a7b-9d4e-4590-b7eb-75eab522bfe9.png)

As, you can notice, `props` object has `id` and `className` both, but `buttonProps` only have 'id'.

## 🔦 Context
I have created a custom Button component using `react-aria` and when integrating this `Button`  component inside other component, I passed bootstrap classes to style the Button. But, the styles are not working as underlying `button` element is not getting className from `buttonProps`.

## 💻 Code Sample
Demo Link - https://react-e6ufdp.stackblitz.io

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.18.0 |
| Browser          | Microsoft Edge |
| Operating System | Windows 11 |

Note - I'm Working on solving this issue, will soon raise PR.

**Comment by reidbarber** [comment]
From https://github.com/adobe/react-spectrum/issues/3037#issuecomment-1098601117:
> @devongovett:  It's not so much that we filter them, it's just that we don't do anything at all with props that aren't defined by us. We return DOM props based on the props in our API. It's your job to add any additional props you want passed through. You could use the mergeProps utility for that.

**Comment by sachinsom93** [comment]
Thanks for quick response.
