### ISSUE TITLE
ComboBox: left/right arrow keys do not work after inputing a value while dropdown menu is down

### ISSUE THREAD

**Issue by eyao06** [adobe/react-spectrum#3400]
# 🐛 Bug Report 

1. Have a ComboBox with options in it
2. Typing in a valid value in the input box of a ComboBox
3. The dropdown menu opens
4. When attempting to press the left or right arrow key on the keyboard, the text cursor does not move
5. While the menu is still open, if you move the text cursor anywhere on the string and press the left or right keys, it still does not move
6. when the menu closes (via selecting a option, inputing a invalid text, or manually closing it) the text cursor is movable again with the left and right keys

## 🤔 Expected Behavior

- user is able to move the text cursor left and right with the left and right keyboard keys

## 😯 Current Behavior

- user is **not** able to move the text cursor left and right with the left and right keyboard keys

## 💻 Code Sample

This issue was found in the Spectrum v3 storybook
https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#example

https://user-images.githubusercontent.com/12926470/184436517-c51fefe6-0069-4519-be5b-a45ea6d92a62.mov

**Comment by devongovett** [comment]
Traced this back to this PR: https://github.com/adobe/react-spectrum/pull/3000, likely implementing `getKeyLeftOf` and `getKeyRightOf` in ListLayout.
