### ISSUE TITLE
Menu key.currentKey undefined when deselecting

### ISSUE THREAD

**Issue by melcherry98** [adobe/react-spectrum#3434]
# 🐛 Bug Report 

When deselecting a menu item initially set as selected using `defaultSelectedKeys` the `key.currentKey` value is `undefined` but if you deselect the same item after it is selected manually it returns the correct key.

## 🤔 Expected Behavior

I would expect `key.currentKey` value to be the key of the deselected item.

## 😯 Current Behavior

https://codesandbox.io/s/menu-deselection-currentkey-undefined-2fffrl?file=/src/App.js

repro: 

- deselect any menu item and view the value logged to the console.

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.19.0
| Browser          | chrome
| Operating System | Mac OS BigSur

## 🧢 Your Company/Team

Adobe Marketo Engage

**Comment by reidbarber** [comment]
This seems to be working as expected. `onSelectionChange` passes in `keys: Selection` which is type `'all' | Set<Key>`, so there is no `currentKey` property available.

**Comment by reidbarber** [comment]
Going to close this since it appears to be working as expected, but feel free re-open if you're still having any issues.
