### ISSUE TITLE
Type error in useMenu example from docs

### ISSUE THREAD

**Issue by bstro** [adobe/react-spectrum#3437]
# 🙋 Documentation Request

I'm trying to do my best approximation of the `useMenuItem` example [from the docs](https://react-spectrum.adobe.com/react-aria/useMenu.html#menuitem), using Typescript.

The only type I added was for the props for the `MenuItem` component:
```
type MenuItemProps = { item: AriaMenuItemProps; state: TreeState<object> };

export function MenuItem({ item, state }: MenuItemProps) { … }
```

You can see in the following codesandbox that there is a type error when trying to render `{item.rendered}`:
```
Property 'rendered' does not exist on type 'AriaMenuItemProps'.ts(2339)
```

Here's [my codesandbox](https://codesandbox.io/s/bold-sara-s92omw?file=/src/MenuItem.tsx:825-847) demonstrating the type error.

Would love some guidance about how to correctly type this so that I don't encounter a type error when using the component as-instructed.

**Comment by snowystinger** [comment]
Looks like you're looking for this https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/menu/src/MenuItem.tsx#L27 ?
MenuItem is internal to us, so we don't export this. But you should be able to recreate it pretty easily.
Sorry that's not a little easier to find. We're working on some improvements to our hook docs and TS.

**Comment by bstro** [comment]
@snowystinger many thanks! that helps a lot. :)

**Comment by bstro** [comment]
@snowystinger wondering if you could help me with one more hiccup. I'm running into another type error, but this one  seems harder to figure out what to do by copying spectrum components... getting `Type 'unknown' is not assignable to type 'object'` when trying to render `<Menu>` component

https://codesandbox.io/s/frosty-hofstadter-n7rf4w?file=/src/components/MenuButton.tsx:952-1005
