### ISSUE TITLE
Description and error message props for useCheckbox, useCheckboxGroup, and useRadioGroup

### ISSUE THREAD

**Issue by vbudovski** [adobe/react-spectrum#3439]
# 🙋 Feature Request

Provide `descriptionProps` and `errorMessageProps` for `useCheckbox`, `useCheckboxGroup`, and `useRadioGroup`. This would make them consisten with every other field in react-aria.

## 🤔 Expected Behavior

This should behave exactly the same as in the `useTextField` implementation.

## 😯 Current Behavior

No support for `descriptionProps` or `errorMessageProps` is currently provided for checkboxes or radio groups. 

## 💁 Possible Solution

Implement in a similar manner to `useTextField`.

## 🔦 Context

Not providing description and error message props makes it more difficult to provide a consistent experience when implementing error messaging in forms.

## 💻 Examples

`const { groupProps, labelProps, descriptionProps, errorMessageProps } = useCheckboxGroup(props, state);`

**Comment by LFDanLu** [comment]
This should also be supported by their React Spectrum component counterparts as well
