### ISSUE TITLE
FocusScope broken in React 18 StrictMode

### ISSUE THREAD

**Issue by RubenStoesser** [adobe/react-spectrum#3458]
# 🐛 Bug Report 

The last update (`v3.8.0`) to `@react-aria/focus` has introduced code that breaks `FocusScope` when running in React 18 `StrictMode`.

Rendering a `<FocusScope` throws this error:

```ts
Cannot set properties of undefined (setting 'nodeToRestore')
```

The issue does not occur when StrictMode is not enabled or `v3.7.0` of `@react-aria/focus` is used.

## 🤔 Expected Behavior

FocusScope should not throw an error when rendering.

## 😯 Current Behavior

Whenever a FocusScope is rendered in StrictMode an error is thrown:

```ts
Cannot set properties of undefined (setting 'nodeToRestore')
```

The error seems to be thrown when trying to assign `focusScopeTree.getTreeNode(scopeRef).nodeToRestore` in this `useLayoutEffect`:
https://github.com/adobe/react-spectrum/blob/241101290bc6a009510e1d888cac8ca63e70b5d4/packages/%40react-aria/focus/src/FocusScope.tsx#L456

## 💻 Code Sample

Example Code Sandbox using the [example code from react-aria docs](https://react-spectrum.adobe.com/react-aria/FocusScope.html#example):

https://codesandbox.io/s/react-spectrum-template-forked-88lk5n?file=/src/App.js

To reproduce just click on the "open" button. 

Note that when `<StrictMode>` is removed in the `index.js` file the error does not occur. 
When the version of `@react-aria/focus` is changed to `3.7.0` the error also does not occur.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/focus   | 3.8.0
| Browser          | Chrome 104.0.5112.101
| Operating System | MacOS 12.5.1

**Comment by reidbarber** [comment]
Thanks for finding! We have an umbrella issue for strict mode issues at https://github.com/adobe/react-spectrum/issues/779, so I'll close this in favor of that.
