### ISSUE TITLE
Server Side Rendering doesn't work with latest Next.js (12.2.5)

### ISSUE THREAD

**Issue by bboy114crew** [adobe/react-spectrum#3462]
# 🐛 Bug Report 
The guide for setting up SSR configuration in Next.js doesn't work with its latest version - 12.2.5

## 🤔 Expected Behavior
No errors.

## 😯 Current Behavior
After following the guide: https://react-spectrum.adobe.com/react-spectrum/ssr.html#nextjs, I'm getting an error:
```
(node:89564) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
error - ./node_modules/@react-spectrum/list/dist/main.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@react-spectrum/list/dist/module.js
```

![Screenshot 2022-08-31 at 14 51 32](https://user-images.githubusercontent.com/13061304/187626387-407bcff9-2ba3-4778-8c0b-d78077e37009.png)

## 💁 Possible Solution
The suggestion is that the maintainer should publish a compiled version of the dependency: https://github.com/vercel/next.js/blob/master/errors/css-npm.md

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  ^3.21.1 |
| next   |  12.2.5 |
| next-transpile-modules   |  ^9.0.0 |
| react  |  18.2.0 |
| react-dom   |  18.2.0 |

**Comment by reidbarber** [comment]
Add `'@react-spectrum/list'` to the `next-transpile-modules` config in `next.config.js`. You'll need to do this when any new components are released with a new version for now. The error should always show you which package to add to that config.

**Comment by reidbarber** [comment]
The docs should get updated soon to include this via https://github.com/adobe/react-spectrum/pull/3465
