### ISSUE TITLE
`useOverlayPosition` no longer seems to position the overlay

### ISSUE THREAD

**Issue by Vinnl** [adobe/react-spectrum#3464]
# 🐛 Bug Report 

Using the `useOverlayTrigger` example code from https://react-spectrum.adobe.com/react-aria/useOverlayTrigger.html#example, the popover is no longer positioned next to the trigger in react-aria 3.19.0.

## 🤔 Expected Behavior

The popover should be positioned on top of the trigger, like on the docs website.

## 😯 Current Behavior

The popover instead is located at the end of the page. See [the CodeSandbox](https://codesandbox.io/s/react-spectrum-template-forked-05t37s?file=/src/App.js), including the console log I added there.

## 💁 Possible Solution

I'm not exactly sure what the fix would be, but I believe that the return value of `useOverlayPosition` used to at least include `.overlayProps.style.left` and `.overlayProps.style.top`. Those no longer seem to be present. When it comes to suspicious PRs, the title an description suggest that https://github.com/adobe/react-spectrum/pull/597 might possibly be related.

## 🔦 Context

I'm looking at [upgrading from 3.17.0 to 3.19.0](https://github.com/mozilla/fx-private-relay/pull/2420), but after the upgrade, two of our drop down menus no longer work.

You can try it out yourself by opening the filter button next to the "Search masks" field:

After the upgrade (with bug): https://deploy-preview-2420--fx-relay-demo.netlify.app/?mockId=some
Before the upgrade: https://fx-relay-demo.netlify.app/?mockId=some

![image](https://user-images.githubusercontent.com/4251/187690326-d35060d9-725b-4067-a303-7b8fae7b4ea7.png)

(Source code for that component is [here](https://github.com/mozilla/fx-private-relay/blob/main/frontend/src/components/dashboard/aliases/CategoryFilter.tsx).)

## 💻 Code Sample

https://codesandbox.io/s/react-spectrum-template-forked-05t37s?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.19.0 |
| Browser          | Firefox 104 and Chromium 104 |
| Operating System | Fedora Workstation 36 |

## 🧢 Your Company/Team

Mozilla/Firefox Relay

## 🕷 Tracking Issue (optional)

https://github.com/mozilla/fx-private-relay/pull/2420#issuecomment-1232936959

**Comment by devongovett** [comment]
Your sandbox is using the `Button` component from `@adobe/react-spectrum`, but passes a prop named `buttonRef` which doesn't exist. You could use `ref` but it involves some additional steps to unwrap the custom object. If you want a native button element, you need to pass the trigger props through `useButton` and provide the ref to the element. Here's a forked version of your sandbox that appears to work: https://codesandbox.io/s/react-spectrum-template-forked-7oc67b?file=/src/App.js

**Comment by Vinnl** [comment]
Aargh, I'm using a native `<button>` in my own code, but indeed, seems like with that I'm unable to reproduce it in a Codesandbox. Will re-open if I can reproduce in an isolated Codesandbox.
