### ISSUE TITLE
ActionMenu Not Working With Current Release: 'Cannot set properties of undefined'

### ISSUE THREAD

**Issue by greenpixels** [adobe/react-spectrum#3469]
# 🐛 Bug Report 

I reinstalled my dependencies and encountered ActionMenu throwing an error when trying to open the menu.

## 🤔 Expected Behavior

The menu should open and show its children/items.

## 😯 Current Behavior

The application crashes, showing the following error:

```
Error in /turbo_modules/@react-aria/focus@3.8.0/dist/main.js (409:87)
Cannot set properties of undefined (setting 'nodeToRestore')
```

## 💻 Code Sample

[Stackblitz Example](https://stackblitz.com/edit/react-ts-qjlhr7?file=App.tsx) using the default example [shown in the documentation](https://react-spectrum.adobe.com/react-spectrum/ActionMenu.html#events).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.21.1
| react | 18.2.0
| react-dom | 18.2.0
| @types/react-dom | 18.0.6
| @types/react| 18.0.18

**Comment by reidbarber** [comment]
Looks like this is related to using React Strict Mode. React Spectrum doesn't currently support strict mode, but work is being done for it at https://github.com/adobe/react-spectrum/issues/779
