### ISSUE TITLE
 useDateSegment not working as expected

### ISSUE THREAD

**Issue by rdangol1** [adobe/react-spectrum#3472]
# 🐛 Bug Report 

When trying to use useDateSegment from [useDateField](https://react-spectrum.adobe.com/react-aria/useDateField.html) an error pop up that doesn't allow destructuring.

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/65328698/187952908-b5d04472-6790-42c7-9632-fc5bbe6ab6e2.png)

## 🔦 Context

 Trying to create a date picker component using the date field.

## 💻 Code Sample

https://codesandbox.io/s/datefield-test-yqvjbl?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | chrome
| Operating System | macOS

**Comment by snowystinger** [comment]
Fixed it https://codesandbox.io/s/nifty-keldysh-yehquv?file=/src/App.js
based off https://react-spectrum.adobe.com/react-aria/useDateField.html#example

Looks like you weren't using 'useDateField'
