### ISSUE TITLE
@react-stately/numberfield Controlled Value Bug

### ISSUE THREAD

**Issue by callen1994** [adobe/react-spectrum#3480]
# 🐛 Bug Report 

When using a controlled value on a component that uses a "useNumberFieldState" hook, the component will hold a state value that is out of sync with the parent. On blur the emitted value will be different from the stored value. Also the value will toggle between two previous values when you focus and un-focus the element.

## 🤔 Expected Behavior

The State within the component should reflect what's displayed on the input element. The value shouldn't revert back to a previous value when on-blur.

## 😯 Current Behavior

This code sandbox displays the bug effectively.
https://codesandbox.io/s/8iddiw

## 💁 Possible Solution

When I installed @react-stately/numberfield @3.0.0 the bug stopped showing up

## 🔦 Context

I'm trying to use React ARIA to build a library of styled input components.

## 💻 Code Sample

This code sandbox displays the bug effectively.
https://codesandbox.io/s/8iddiw

**Comment by LFDanLu** [comment]
I think this is a strict mode issue, seems to work as expected after removing that from your [sandbox](https://codesandbox.io/s/react-stately-numberfield-broken-forked-t5yz6m?file=/src/index.js). Closing in favor of the umbrella issue: https://github.com/adobe/react-spectrum/issues/779

**Comment by Kunz-David** [comment]
This bugged me for a long time till I found this post. It still doesn't work the way it should in strict mode.

**Comment by snowystinger** [comment]
Have you tried it on this branch? https://github.com/adobe/react-spectrum/pull/4564

Any extra eyes on it are very helpful before it gets merged. Thank you!
