### ISSUE TITLE
`SSRProvider` creates issues with conditionally-rendered `OverlayContainer`s

### ISSUE THREAD

**Issue by brandonpittman** [adobe/react-spectrum#3490]
# 🐛 Bug Report 

When wrapping an app with `SSRProvider`, conditionally-rendered overlays don't display correctly on the first display. If you show one based on `state.isOpen` from a trigger, the rendering is odd the first go. In my app's case, the tooltip that should be rendered stays offscreen until mousing away, then the overlay flashes on and off in a second. Hovering over the same element again, the overlay displays correctly.

I created a sandbox that shows a similar problem. In the sandbox, the overlay shows, but the offset is being ignored.

These issues only show up when the app is wrapped in an `SSRProvider`. If the provider is removed, the overlays display as expected, but then the app complains about SSR and IDs. 

I can side-step the issue by conditionally rendering the content inside the `OverlayContainer`s, but this results in hundreds of portals sitting at the bottom of `body`.

## 🤔 Expected Behavior

I expect overlays to display correctly even when the app is wrapped in an `SSRProvider`.

## 😯 Current Behavior

Overlays exhibit odd behavior, sometimes not showing at all, or having odd `positionProps.style` values when wrapped with `SSRProvider`.

## 🔦 Context

I'm building a Remix app that would seemingly require `SSRProvider` and I have lots of menus and tooltips that need to be in `OverlayContainer`s because of overflowing/scrolling parents.

## 💻 Code Sample

https://codesandbox.io/s/react-spectrum-template-forked-9io4uj?file=/src/index.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.19.0
| react-stately   | 3.17.0
| Chrome          | 103
| macOS | 12.5.1

**Comment by rk-lunar** [comment]
👍

**Comment by rk-lunar** [comment]
We have the same problem, and i found this issue which i think is directly related to the problem.

https://github.com/adobe/react-spectrum/issues/3293

**Comment by brandonpittman** [comment]
*Update: 2022-09-09.* After playing around today a bit more, I was able to get an OverlayContainer to conditionally render when triggered off of `useMenuTrigger` by moving the OverlayContainer inside the Popover component and then conditionally rendering the Popover. Works as expected.

Tried the same with my Tooltip, but no matter what I do, the Tooltip (using OverlayContainer) won't position itself when conditionally rendered and the OverlayContainer is inside the conditionally rendered component. If I conditionally render inside the OverlayContainer, things look fine, but there are a hundred OverlayContainers in the body. Also, if I remove the SSRProvider, everything works as expected, but React Aria yells at me about IDs not matching.

**Comment by rk-lunar** [comment]
I've made it work but manually handling the ref in a callback.

```
    const popoverRefCallback = useCallback(
      (ref: HTMLDivElement) => {
        popoverRef.current = ref;
        updatePosition();
      },
      [popoverRef, updatePosition]
    );
```

**Comment by rk-lunar** [comment]
> _Update: 2022-09-09._ After playing around today a bit more, I was able to get an OverlayContainer to conditionally render when triggered off of `useMenuTrigger` by moving the OverlayContainer inside the Popover component and then conditionally rendering the Popover. Works as expected.
> 
> Tried the same with my Tooltip, but no matter what I do, the Tooltip (using OverlayContainer) won't position itself when conditionally rendered and the OverlayContainer is inside the conditionally rendered component. If I conditionally render inside the OverlayContainer, things look fine, but there are a hundred OverlayContainers in the body. Also, if I remove the SSRProvider, everything works as expected, but React Aria yells at me about IDs not matching.

I've made it work by manually handling the ref in a callback.

```
    const popoverRefCallback = useCallback(
      (ref: HTMLDivElement) => {
        popoverRef.current = ref;
        updatePosition();
      },
      [popoverRef, updatePosition]
    );
```

**Comment by brandonpittman** [comment]
> > _Update: 2022-09-09._ After playing around today a bit more, I was able to get an OverlayContainer to conditionally render when triggered off of `useMenuTrigger` by moving the OverlayContainer inside the Popover component and then conditionally rendering the Popover. Works as expected.
> > Tried the same with my Tooltip, but no matter what I do, the Tooltip (using OverlayContainer) won't position itself when conditionally rendered and the OverlayContainer is inside the conditionally rendered component. If I conditionally render inside the OverlayContainer, things look fine, but there are a hundred OverlayContainers in the body. Also, if I remove the SSRProvider, everything works as expected, but React Aria yells at me about IDs not matching.
> 
> I've made it work by manually handling the ref in a callback, and then calling `updatePostion` which is returned from the `useOverlayPosition` hook.
> 
> ```
>     const popoverRefCallback = useCallback(
>       (ref: HTMLDivElement) => {
>         popoverRef.current = ref;
>         updatePosition();
>       },
>       [popoverRef, updatePosition]
>     );
> ```

@rk-lunar 

Ah, that took care of it! Thank you very much for the workaround. 

I don't know if the above workaround is the solution to this problem or if it should work without the callbackRef. Will leave this open for now.

**Comment by eramdam** [comment]
Did anyone figure out a workaround when using `useMenu`? I'm running into the same issue when trying to incorporate the [styled example](https://codesandbox.io/s/awesome-boyd-c0gbv5?file=/src/Menu.tsx) inside a Next.JS project and SSRProvider breaks it 😅

**Comment by eramdam** [comment]
@brandonpittman sorry if I'm missing context but why did you close the issue?

**Comment by brandonpittman** [comment]
https://github.com/adobe/react-spectrum/issues/3490#issuecomment-1241670866

**Comment by Vinnl** [comment]
@eramdam I expect that [our workaround](https://github.com/mozilla/fx-private-relay/pull/2612/commits/e26f79a85f2fe11ba08408cac7d8e8c50b9e23ce#diff-edbffc39ec80534abfe406392e700ab7da225db46156fe9898a7ad34675b5e50) should work there as well, but passing the menu trigger state instead of the overlay trigger state.

@brandonpittman I don't think that the existence of a workaround means that the bug is no longer present? Ideally, that (or our) workaround wouldn't be necessary.

**Comment by eramdam** [comment]
> @eramdam I expect that [our workaround](https://github.com/mozilla/fx-private-relay/pull/2612/commits/e26f79a85f2fe11ba08408cac7d8e8c50b9e23ce#diff-edbffc39ec80534abfe406392e700ab7da225db46156fe9898a7ad34675b5e50) should work there as well, but passing the menu trigger state instead of the overlay trigger state.
> 
> @brandonpittman I don't think that the existence of a workaround means that the bug is no longer present? Ideally, that (or our) workaround wouldn't be necessary.

Yep, your work around works!

**Comment by VapidLinus** [comment]
> I've made it work by manually handling the ref in a callback, and then calling `updatePostion` which is returned from the `useOverlayPosition` hook.

I'm using `usePopover()` which doesn't return an `updatePosition()` method... how would I work around the issue when using `usePopover()`?

I don't understand why this issue was closed. This is still a bug... :/

**Comment by huw** [comment]
Mine was broken with the examples for `useSelect`, but [this workaround](https://github.com/adobe/react-spectrum/issues/3787#issuecomment-1421083421) from #3787 fixed it fine:

```tsx
<Overlay portalContainer={document.body}>
     ...
</Overlay>
```

This is in a Remix app where we hydrate the entire `<html>` element; I think it was getting confused about where to send the portal perhaps?
