### ISSUE TITLE
Add support for configuring `useTypeSelect()`'s timeout interval

### ISSUE THREAD

**Issue by ctotheameron** [adobe/react-spectrum#3500]
# 🙋 Feature Request

We would like to be able to configure the "reset" time for components using `useSelectState()`, `useListState()` (anything that leverages typeahead support). The current 500ms interval is a bit tight for our usecase.

## 🤔 Expected Behavior

Ideally there could be a prop passed to these hooks like `typeSelectTimeout` that could allow configuring the typeahead behavior.

## 😯 Current Behavior

Currently it looks like there is a hardcoded 500ms timeout before the `useTypeSelect()` hook resets the search value.

https://github.com/adobe/react-spectrum/blob/49026315c499852d6ab5d2bf5b9907ac7e0c2850/packages/%40react-aria/selection/src/useTypeSelect.ts#L87

## 💁 Possible Solution

Expose a prop on `useTypeSelect()` and its consumers so that top-level apis of Select, ListBox etc could provide their own.

## 🔦 Context

Feedback from our users and internal testers is that the typeahead timeout is too tight and causes annoyance and confusion when trying to filter for a row in a long list (think list of all countries).

## 💻 Examples

In the attached GIF, when trying to type to Malaysia - I was a tiny bit slow and ended up on Laos
![Sep-09-2022 14-42-21](https://user-images.githubusercontent.com/3002968/189291440-48b20340-263e-4bd4-9b38-7b5138556aa0.gif)

## 🧢 Your Company/Team

AngelList

**Comment by devongovett** [comment]
Thanks for the feedback. We could also consider raising the timeout in general. Adding a prop would work, but it would need to be added in a lot of places, so if we can make the experience better for everyone without requiring customization that would be better. Do you have an idea of what value you think would be good?

**Comment by ctotheameron** [comment]
Anecdotally for us, any value between 750-1000ms feels much better than what is there currently

**Comment by devongovett** [comment]
Thanks. I think it's ok to raise it. Would you like to open a PR to adjust the value? Then we can test it and see how it feels.
