### ISSUE TITLE
react18 CollectionBuilder incompatible

### ISSUE THREAD

**Issue by sun0day** [adobe/react-spectrum#3502]
# 🐛 Bug Report 

<img width="737" alt="image" src="https://user-images.githubusercontent.com/102238922/189381575-3c754e8d-26f8-4f09-84c0-1f269a79b445.png">

## 🤔 Expected Behavior

`CollectionBuilder` work in React18

## 😯 Current Behavior

`CollectionBuilder` does not work in React18

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |   @react-stately/table@3.3.0 <br /> @react-stately/collections@3.4.2
| Browser          |
| Operating System |

## 🕷 Tracking Issue (optional)

Full description and reproduction see https://github.com/nextui-org/nextui/issues/729

**Comment by devongovett** [comment]
The problem here isn't React 18 specific. The `TableBody` component only supports `Row` elements as children, but you have a `CountersListItem` child.

**Comment by jrgarciadev** [comment]
Hey @devongovett this issue can be closed 👍🏻
