### ISSUE TITLE
Cannot fully configure autoFocus in useDateRangePicker

### ISSUE THREAD

**Issue by joshsalverda** [adobe/react-spectrum#3505]
# 🐛 Bug Report 

The autoFocus value within calendarProps cannot be overridden currently.

## 🤔 Expected Behavior

The autoFocus value should be configurable.

## 😯 Current Behavior

The prop is hardcoded to true.

## 💁 Possible Solution

I can workaround the issue by overriding the prop outside of the library itself, but ideally there should be some built-in way to handle it.

Could another prop be added, possibly? autoFocusCalendar? I'm not too sure of the naming.

## 🔦 Context

I have a slightly more complex calendar popup ui with a set of buttons allowing you to quickly select date ranges, e.g.:

<img width="400" alt="calendar_example" src="https://user-images.githubusercontent.com/3029989/189537915-f3ba2684-5d99-4dc0-9fc9-2ab2bf139a12.png">

I don't want the calendar to receive focus directly, since that bypasses a lot of the ui. Just focusing on the overall modal dialog is more ideal, then users can navigate through all of the appropriate options.

## 💻 Code Sample

The relevant code is:

https://github.com/adobe/react-spectrum/blob/5f16c3ff51c2c657b4560119b7b811ceed726bc5/packages/%40react-aria/datepicker/src/useDateRangePicker.ts#L149

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria | 3.18.0 |

**Comment by LFDanLu** [comment]
Talked with the team, overriding the props like you mentioned would be our suggested approach.
