### ISSUE TITLE
AriaBaseButtonProps and AriaAttributes types are incompatible.

### ISSUE THREAD

**Issue by torgeadelin** [adobe/react-spectrum#3509]
# 🐛 Bug Report 
AriaBaseButtonProps and AriaAttributes types are incompatible.

## 🤔 Expected Behavior
Aria attributes returned by useButton or useButtonToggle are not compatible with the ones on the prop types of the component types for those components (button, and button toggle respectively).

Imagine you try to create a button-simple component with some very basic functionality and no styling which you use as a base for other button variants you might create in your design system. This button-simple component uses the `useButton` hook.

If you try to create another button based on button-simple, i.e. button toggle, the aria props returned by the useButtonToggle, are not compatible with the ones button-simple can receive. 

```js
import { AriaButtonProps, AriaToggleButtonProps } from '@react-types/button';

// ButtonSimple
export interface ButtonSimpleProps extends AriaButtonProps {
  ... custom props
}

const ButtonSimple forwardRef(props: ButtonSimpleProps, ref: RefObject<HTMLButtonElement>) => {
  const internalRef = useRef();
  const ref = ref || internalRef;
  const {buttonProps} = useButton(props, ref);

  return <button ref={ref} {...buttonProps}>{props.children}</button>
});

// ButtonToggle
export interface ButtonToggleProps extends AriaToggleButtonProps {
  ... custom props
}

const ButtonSimple (props: ButtonToggleProps) => {
  const ref = useRef();
  const state = useToggleState(props);
  const { buttonProps } = useToggleButton(props, state, ref);

  // aria-pressed, aria-haspopup and aria-expanded returned by useToggleButton are incompatible with the ones ButtonSimple can receive.
  return <ButtonSimple ref={ref} {...buttonProps}>{props.children}</button>
}

```

## 😯 Current Behavior
I expect the props to be compatible.

## 💁 Possible Solution
`node_modules/@react-types/button/src/index.d.ts`
```diff
interface AriaBaseButtonProps extends FocusableDOMProps, AriaLabelingProps {
  /** Indicates whether the element, or another grouping element it controls, is currently expanded or collapsed. */
-  'aria-expanded'?: boolean,
+  'aria-expanded'?: boolean | 'false' | 'true' | undefined,
  /** Indicates the availability and type of interactive popup element, such as menu or dialog, that can be triggered by an element. */
-  'aria-haspopup'?: boolean | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog',
+  'aria-haspopup'?: boolean | 'false' | 'true' | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog' | undefined,
  /** Identifies the element (or elements) whose contents or presence are controlled by the current element. */
  'aria-controls'?: string,
  /** Indicates the current "pressed" state of toggle buttons. */
-  'aria-pressed'?: boolean,
+  'aria-pressed'?: boolean | 'false' | 'mixed' | 'true' | undefined,
  /**
   * The behavior of the button when used in an HTML form.
   * @default 'button'
   */
  type?: 'button' | 'submit' | 'reset'
}
```
## 🔦 Context
Typescript

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  "@react-aria/button": "3.4.3"  "@react-types/button": "^3.4.0" |
| Browser          | Chrome Version 105.0.5195.52 (Official Build) (arm64) |
| Operating System | MacOS 12.5.1 (21G83) |

**Comment by LFDanLu** [comment]
I've got some slightly different errors than what your are getting, probably due to the react-types version perhaps: https://codesandbox.io/s/distracted-firefly-9bv2tm?file=/src/App.tsx. The sandbox errors since our `FocusEvents` doesn't take a element type which is something we could look into fixing.

**Comment by torgeadelin** [comment]
Actually the example code I provided doesn't really work well. It kind of illustrates the difference in the aria types, but I'm realising the problem is much bigger, that is, we can't compose the components like this.

The `useToggleButton ` props returned are supposed to be applied to a native DOM `button` element. It doesn't contain `onPress` (which is what ButtonSimple expects).

Because of way the `useToggleButton` is designed, it cannot be used create a component that is based on another aria-based button (something that uses `useButton` hook)(apart from the native HTML button), which seems a bit limiting.

I'm not sure if this was intended anyway, so maybe the incompatibility of the types is not the issue here.

But my team do uses this pattern of composing more complex components on top of base ones (like button simple).

**Comment by snowystinger** [comment]
`useToggleButton` already uses `useButton`. It doesn't need to be applied to a native button, it can be spread onto any element as the TS shows through the prop `ElementType`. You are correct, it should not be spread onto a Component that was created with `useButton`, then you'd be doubling up on `useButton`.

The reason for two hooks is that Buttons do not have a state, but ToggleButtons do. We could have implemented it such that `useToggleButton` could be spread onto a Component that was created using `useButton`, but that would be an extra step that people using our library would have to do to build a ToggleButton and if you spread it on any native element it wouldn't work.

**Comment by torgeadelin** [comment]
I see. We ended up not using the hook anymore, and just chain the state.toggle and add the aria-pressed prop directly in the implementation of the button toggle component, to avoid using useButton twice.

I'm not sure if the initial types issue it's still an issue, so feel free to close this if that's the case.
