### ISSUE TITLE
I run the sample code of useMenu, it is not working

### ISSUE THREAD

**Issue by Coala1010** [adobe/react-spectrum#3513]
# 🐛 Bug Report 

My React version is v18.2.0

## 🤔 Expected Behavior

useMenu sample code should work

## 😯 Current Behavior

I checked the Menu.js file of sample code from useMenu
there is code like `[...state.collection]`
it cannot get correct array

I tried it on other project (React version is 17.0.2)
It worked well

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-stately   | 3.15.0 |
| react-aria | 3.19.0|
| Browser          | Chrome |
| Operating System |  Windows |

**Comment by LFDanLu** [comment]
Seems to work for me using the code from the docs directly: https://codesandbox.io/s/kind-goldberg-6oq3ki?file=/src/App.js. Mind attaching your own codesandbox that reproducing the issue?

**Comment by reidbarber** [comment]
This may be a typescript issue that is fixed by setting `downlevelIteration` to `true` in your `.tsconfig` file.

**Comment by Coala1010** [comment]
Yes, I'm using typescript
I added like below, is it correct?

![image](https://user-images.githubusercontent.com/28304925/190220522-c8b7d9cf-6f7c-4b2a-8ed7-29094b07e5a5.png)

**Comment by reidbarber** [comment]
That looks correct. Are you still seeing the issue? If so, what is the exact error message?

**Comment by Coala1010** [comment]
![image](https://user-images.githubusercontent.com/28304925/190231345-a96d8201-6b9b-498e-8359-95c441778f85.png)

it still cannot get correct array @reidbarber

**Comment by snowystinger** [comment]
Can you make sure you aren't using React StrictMode?

**Comment by Coala1010** [comment]
Do you have skype? Can you guide me to fix it? @reidbarber

**Comment by reidbarber** [comment]
If you want to create a codesandbox like the one linked above, the team can get back to you in this thread.

**Comment by Coala1010** [comment]
`Array.from(state.collection)`

I resolve the problem like above

Thank you

**Comment by reidbarber** [comment]
I just noticed you were targeting ES5, and spread syntax is ES6. Glad you found the solution!
