### ISSUE TITLE
`useOverlayPosition` position the overlay in Next.js

### ISSUE THREAD

**Issue by Vinnl** [adobe/react-spectrum#3517]
# 🐛 Bug Report 

This might be an issue with Next.js, but the most minimal reproduction I can currently make happens using React Aria, so I can't quite report it there yet. Feel free to close if this is considered out of scope for React Aria.

I'm using `useOverlayTrigger` much like in the documentation, based on [this comment's sandbox](https://github.com/adobe/react-spectrum/issues/3464#issuecomment-1233208643). And [in a CodeSandbox](https://codesandbox.io/s/react-spectrum-template-forked-j9ef84) it appears to work fine, but [in a minimal, freshly-created Next.js app](https://github.com/Vinnl/nexts-react-aria-overlay-repro/blob/main/pages/index.js), the popover does not get anchored to the trigger.

## 🤔 Expected Behavior

The popover should be anchored to the trigger, like this:

![image](https://user-images.githubusercontent.com/4251/190120086-995171b5-bfc1-4dbb-8d9c-b4bc8009b471.png)

## 😯 Current Behavior

In a Next.js app, the `top` and `left` attribute for the style attribute are not set in the initial render, nor updated by themselves:

![image](https://user-images.githubusercontent.com/4251/190120298-8a17ee42-60bd-494c-9df9-0e050bbf25a8.png)

Live demo: https://vinnl.github.io/nexts-react-aria-overlay-repro/
Source code: https://github.com/Vinnl/nexts-react-aria-overlay-repro/blob/main/pages/index.js

## 💁 Possible Solution

If the popover is re-rendered for another reason, the `top` and `left` properties seem to be set properly. To see this, in [the reproduction](https://vinnl.github.io/nexts-react-aria-overlay-repro/), click the green area, then within two seconds, open the popover. It will initially be incorrect positioned, but after the two seconds pass, the component will re-render and the popover will snap into place:

https://user-images.githubusercontent.com/4251/190120923-886d7f9c-2453-4a86-a776-c5ecbba3ddfc.mp4

## 🔦 Context

I'm looking at [upgrading from 3.17.0 to 3.19.0](https://github.com/mozilla/fx-private-relay/pull/2420), but after the upgrade, two of our drop down menus no longer work.

You can try it out yourself by opening the filter button next to the "Search masks" field:

After the upgrade (with bug): https://deploy-preview-2420--fx-relay-demo.netlify.app/?mockId=some
Before the upgrade: https://fx-relay-demo.netlify.app/?mockId=some

![image](https://user-images.githubusercontent.com/4251/187690326-d35060d9-725b-4067-a303-7b8fae7b4ea7.png)

(Source code for that component is [here](https://github.com/mozilla/fx-private-relay/blob/main/frontend/src/components/dashboard/aliases/CategoryFilter.tsx).)

## 💻 Code Sample

CodeSandbox without the bug: https://codesandbox.io/s/react-spectrum-template-forked-j9ef84
Similar code in a Next.js app, demonstrating the bug: https://github.com/Vinnl/nexts-react-aria-overlay-repro/blob/main/pages/index.js
Live demo of the bug: https://vinnl.github.io/nexts-react-aria-overlay-repro/

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.19.0 |
| Browser          | Firefox 104 and Chromium 104 |
| Operating System | Fedora Workstation 36 |

## 🧢 Your Company/Team

Mozilla/Firefox Relay

## 🕷 Tracking Issue (optional)

https://github.com/mozilla/fx-private-relay/pull/2420#issuecomment-1232936959

**Comment by devongovett** [comment]
First thing I would try would be turning off the React StrictMode setting in next.config.js

**Comment by Vinnl** [comment]
Thanks @devongovett, [just did that](https://github.com/Vinnl/nexts-react-aria-overlay-repro/commit/189ecfd0a116ca268fcf3deb8b7134424dbaef96), but no luck; the bug still occurs. (And the Codesandbox also works _with_ StrictMode.)

**Comment by rk-lunar** [comment]
is this possibly related to https://github.com/adobe/react-spectrum/issues/3490?

**Comment by Vinnl** [comment]
Thanks @rk-lunar - yes, by adding the `<SSRProvider>`, I can reproduce the issue [in the Codesandbox](https://codesandbox.io/s/react-spectrum-template-forked-yyxi8v) as well! I'll close this issue and subscribe to that one.
