### ISSUE TITLE
Narrow down "focusProps" return type

### ISSUE THREAD

**Issue by masad-frost** [adobe/react-spectrum#3534]
[useFocus](https://github.com/adobe/react-spectrum/blob/17287539f7fc8574c6c6236424f6da44f8dc2b19/packages/%40react-aria/interactions/src/useFocus.ts#L29) and other focus hooks return `onBlur` and `onFocus` functions, yet the return type is `DOMAttributes` which includes things like `children`, it makes the hook hard to re-use since components may not accept certain props.

**Comment by snowystinger** [comment]
Please see https://github.com/adobe/react-spectrum/discussions/1618
