### ISSUE TITLE
useRadioGroup arrow keys should only affect radio inputs in the group

### ISSUE THREAD

**Issue by masad-frost** [adobe/react-spectrum#3536]
# 🐛 Bug Report 

If you have a focusable element (e.g. `<object>`) inside the radio group parent, then arrow keys will select that item and try to use its "value".

## 🤔 Expected Behavior

Arrow keys only switch between radio elements

As cursed as the following code looks (button inside fieldset), the default browser behavior makes sense and does exactly what I'd expect

https://user-images.githubusercontent.com/1994028/191152545-2a54636c-de12-4aad-91b4-0d1d5843f9fa.mp4

```
<fieldset>
    <legend>Select a maintenance drone:</legend>

    <div>
      <input type="radio" id="huey" name="drone" value="huey"
             checked>
      <label for="huey">Huey</label>
      <button>wow</button>
    </div>

    <div>
      <input type="radio" id="dewey" name="drone" value="dewey">
      <label for="dewey">Dewey</label>
    </div>

    <div>
      <input type="radio" id="louie" name="drone" value="louie">
      <label for="louie">Louie</label>
    </div>
</fieldset>
```

## 😯 Current Behavior
It focuses any element and grabs its "value" attribute to set it.

## 💁 Possible Solution

Only consider inputs of type radio inside the fieldset.

## 🌍 Your Environment

Any

## 🧢 Your Company/Team

Replit

**Comment by devongovett** [comment]
Note that the `radiogroup` ARIA role only allows `radio` children, so that button isn't really allowed. See https://github.com/adobe/react-spectrum/issues/2379#issuecomment-936893447.

**Comment by masad-frost** [comment]
Dang my GitHub issue search has been failing me quite a bit. This makes sense.

Maybe we should console.warn when the walked-to element isn't a radio input.

Feel free to close the PR, though matching default browser behavior might be desirable regardless.

Closing this issue as a duplicate.
