### ISSUE TITLE
Calendar state does not update when prev/next month button is clicked

### ISSUE THREAD

**Issue by bobywoodwarrior** [adobe/react-spectrum#3538]
![chrome-capture-2022-8-20 (1)](https://user-images.githubusercontent.com/6125119/191299316-338413f6-2a01-4725-aec9-22fae348c321.gif)

# 🐛 Bug Report 

When the button next or previous is clicked, the calendar doesn't update and stay on the current selected month.

## 🤔 Expected Behavior

The UI should update and the month must be incremented/decremented.

## 💁 Possible Solution

I don't know if there's a relation but the documentation of [useCalendar](https://react-spectrum.adobe.com/react-aria/useCalendar.html#example) suggests to add a `ref` parameter to `useCalendar` in their exemple: 
<img width="671" alt="image" src="https://user-images.githubusercontent.com/6125119/191297322-dbc3c5c2-24ed-42e2-83eb-805a73be8fa1.png">

But the [ definition of useCalendar](https://react-spectrum.adobe.com/react-aria/useCalendar.html#api) is: 
<img width="864" alt="image" src="https://user-images.githubusercontent.com/6125119/191297859-dbfd576f-c4fb-4507-844f-3fa50fb74ec7.png">
(As well as the definition in typescript)

## 💻 Code Sample

See the [codesandbox](https://codesandbox.io/s/epic-sid-ze63bh?file=/src/Calendar.tsx)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.19.0
| react-stately   | 3.17.0
| Browser          | Chrome 105.0.5195.125
| Operating System | macOS Monterey

## 🧢 Your Company/Team

[Dokey](https://dokey.io/)

**Comment by LFDanLu** [comment]
You need to pass the `prevButtonProps` and `nextButtonProps` to `useButton`, here is an updated version of the sandbox: https://codesandbox.io/s/angry-cookies-tojdvt?file=/src/Calendar.tsx
