### ISSUE TITLE
virtualizer is not working on Strict mode

### ISSUE THREAD

**Issue by digvijoymohapatra11** [adobe/react-spectrum#3539]
We are using @react-aria/virtualizer@3.5.0. virtualizer is working fine in normal mode but in strict mode it is always blank.
Please refer the below sandbox for the reference.
[https://codesandbox.io/s/listbox-example-react-spectrum-forked-5zwt8i?file=/Example.js](url)

**Comment by reidbarber** [comment]
React Spectrum doesn't fully support React Strict Mode yet, however work is in progress. I'll close this in favor of the umbrella issue for strict mode issues at https://github.com/adobe/react-spectrum/issues/779
