### ISSUE TITLE
VisuallyHidden not showing children when isFocusable is true

### ISSUE THREAD

**Issue by briluu** [adobe/react-spectrum#3571]
# 🐛 Bug Report 

`VisuallyHidden`'s `isFocusable` prop is not working - i.e. focused children are not shown.

## 🤔 Expected Behavior

When `isFocusable` is true, the children of `VisuallyHidden` should be visible. 

## 😯 Current Behavior

The children remain hidden when they receive focus.

## 🔦 Context

We want to implement a skip link.

## 💻 Code Sample

https://codesandbox.io/s/nifty-silence-ynqdxw?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.18.0 |
| Browser          | Chrome | 
| Operating System | MacOS |

## 🧢 Your Company/Team

Adobe Administration UIs

**Comment by LFDanLu** [comment]
Was able to reproduce locally, for some reason the styles aren't being recomputed [here](https://github.com/adobe/react-spectrum/blob/08103810989f354d9c7d578a84b1e88378a94d20/packages/%40react-aria/visually-hidden/src/VisuallyHidden.tsx#L66-L74) when the hidden button is focused, but I confirmed that `useFocus`'s `onFocusChange` handler is firing which should cause a rerender and update `isFocused`... Will need to dig more

**Comment by snowystinger** [comment]
We'd need to change useVisuallyHidden's onFocus to an onFocusWithin I think. Looks like we are technically listening for focus changes on the wrapping element right now, which shouldn't be focusable I don't think.
