### ISSUE TITLE
Allow hidden select to take a className prop

### ISSUE THREAD

**Issue by mantagen** [adobe/react-spectrum#3578]
# 🙋 Feature Request

Allow `<HiddenSelect />` to take a className prop, so that it can be excluded from axe or pa11y etc. 

## 🤔 Expected Behavior

`<HiddenSelect />` doesn't show as a false positive

## 😯 Current Behavior

`<HiddenSelect />` currently shows a false positive in Axe (not listed but equivalent to https://github.com/adobe/react-spectrum/wiki/Known-accessibility-false-positives#picker). 

E.g.

![ARIA hidden element must not be focusable or contain focusable elements](https://user-images.githubusercontent.com/12934669/193304708-4aa105b3-1b4c-422a-96ea-be56153aeab7.png)

## 💁 Possible Solution

Allow `<HiddenSelect />` to take a className prop, so that it can be excluded from axe or pa11y etc. 

## 💻 Examples

```ts
<HiddenSelect
  className="pa11y-ignore"
/>
// pa11y no longer complains
```

**Comment by snowystinger** [comment]
Hey! Thanks for the issue. This is a pretty good idea, we've seen a fair number of complaints about this topic. I don't think a className is quite the approach we want. We'd like to build this into our component, and it appears both libraries can accept a selector of any variety to exclude an element from the report. We think solving this inside our `<HiddenSelect>` is the best approach as it then minimizes the work that users need to do and it means our React Spectrum users can easily use it as well. Instead, we'd like to introduce a documentable and recognizable data attribute, `data-rsp-a11yIgnore`, or something to that effect.

For reference
https://github.com/pa11y/pa11y#hideelements-string
https://www.deque.com/axe/core-documentation/api-documentation/#context-parameter-examples

**Comment by mantagen** [comment]
Thanks for the response!
Yep, using a `data-` attribute sounds more sensible, good thinking! How likely would something like this be to get added to a roadmap some time soon?

**Comment by snowystinger** [comment]
you can just make a PR if you'd like, thanks! otherwise, I can't say when it would be picked up

**Comment by LFDanLu** [comment]
@abitbetterthanyesterday go for it! See https://github.com/adobe/react-spectrum/issues/3578#issuecomment-1268775411 for the approach we'd like to take here, let us know if you have any questions.

**Comment by abitbetterthanyesterday** [comment]
I have put a PR out, let me know if you have any remarks.
