### ISSUE TITLE
Table height being set shorter than the content of the table

### ISSUE THREAD

**Issue by tsgeorgi** [adobe/react-spectrum#3586]
# 🐛 Bug Report 

The table height is being set to a fixed pixel size upon loading of the DOM and this size is less than height of the combined rows within the table.
div role="presentation" and div role="rowgroup" appear to automatically calculate their height on page load but somehow fall short of the overall height of the content within them.
There appears to be no way to override this height using CSS as all styles are being set inline for these elements and our app.css stylesheet does not seem to affect these elements or even be considered for use by them. Because of this we can't even target the class of the elements and set an !important override.

## 🤔 Expected Behavior

The table height should be equal to the content of the table

## 💁 Possible Solution

Either calculate the height correctly or use auto height which calculates it based on the size of the children elements.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
Can you provide a codesandbox demonstrating the issue what you're seeing? I'm having a hard time following.

**Comment by reidbarber** [comment]
Closing due to discussion in slack. Issue was not related to RSP v3.
