### ISSUE TITLE
Large CSS Size

### ISSUE THREAD

**Issue by yogeshapps** [adobe/react-spectrum#3625]
# 🐛 Bug Report 
I am trying to use ActionButton. While analysing the bundle size, noticed that ActionButton is taking up ~120KB minified size(including both JS and CSS).
Major portion of 120KB is taken up by the button.css i.e. ~95KB.
`<ActionButton isQuiet onPress={handleCopyClick}>
      <Copy aria-label={props.formatMessage('colorpicker.textField.copy.ariaLabel')} size="S"/>
 </ActionButton>`

## 🤔 Expected Behavior
CSS size should be lower.

## 😯 Current Behavior
<img width="1772" alt="Screenshot 2022-10-11 at 11 21 43 AM" src="https://user-images.githubusercontent.com/47735723/195010701-b51c8339-3f46-4434-a14f-9e3359c603b9.png">

## 🔦 Context
This is increasing overall bundle size. 

## 💻 Code Sample
```
<ActionButton isQuiet onPress={handleCopyClick}>
      <Copy aria-label={props.formatMessage('colorpicker.textField.copy.ariaLabel')} size="S"/>
 </ActionButton>
```

## 🌍 Your Environment
I tried it with both create react app and bundle with webpack@5. Found same css in both cases.

**Comment by reidbarber** [comment]
There are some active PRs by @devongovett that should cut down the size pretty significantly (#3650, #3651). We could also potentially look at splitting styles for different types of buttons into separate files.

**Comment by Rados51** [comment]
@yogeshapps @reidbarber 
I guess this can be closed

<img width="966" alt="image" src="https://github.com/adobe/react-spectrum/assets/47051193/44731c37-dde2-4ce2-9112-6429f0bd971c">

**Comment by snowystinger** [comment]
Thanks for the comment, closing
