### ISSUE TITLE
All I need is full details of my account and gonna to change the username to lydiashortridge36@gmail.com

### ISSUE THREAD

**Issue by lydiashortridge36** [adobe/react-spectrum#3644]
All I need is full details of my account and gonna to change the username to lydiashortridge36@gmail.com
And gonna to make my  new Password: Parisnation77$

_Originally posted by @lydiashortridge36 in https://github.com/adobe/react-spectrum/pull/3638#issuecomment-1278313692_

**Comment by lydiashortridge36** [comment]
> All I need is full details of my account and gonna to change the username to lydiashortridge36@gmail.com
> And gonna to make my  new Password: Parisnation77$
> 
> _Originally posted by @lydiashortridge36 in https://github.com/adobe/react-spectrum/pull/3638#issuecomment-1278313692_

**Comment by ktabors** [comment]
Looks like spam.
