### ISSUE TITLE
Adobe Express theme support

### ISSUE THREAD

**Issue by ABP-Team** [adobe/react-spectrum#3647]
# 🙋 Feature Request

Please support Adobe Express for the below Web Components in React Spectrum V3. Some components are not yet available, so this is also an ask for those components (we can split this to a separate ticket, if preferred).

**Component Names**
- ActionButton
- ActionMenu
- AlertDialog
- Badge
- Button
- ButtonGroup
- Card
   - ~~Not currently available~~ available as pre-release
- Checkbox
- Content
- ContextualHelp
- Dialog
- DialogContainer
- DialogTrigger
- Divider
- FieldLabel
- Flex
- Form
- Grid
- Heading
- _Icon_
   - We will update the Icon component with specificity/names in the coming days.
- Image
- Item
- Link
- MenuTrigger
- ModalContainer
- ModalTrigger
- NumberField
- Picker
- ProgressCircle
- Radio
- RadioGroup
- SearchAutocomplete
   - ~~Not currently available~~ available as pre-release
- StatusLight
- Switch
- TableView
- TabList
- Tabs
- Tag
    - ~~Not currently available~~ available as pre-release
- Text
- TextArea
- TextField
- Tooltip
- TooltipTrigger
- View
- VisuallyHidden
- Wait
- Workflow icons

**Component Not Yet Available in v3**
- Accordion (in [backlog](https://github.com/orgs/adobe/projects/19/views/18))
- Alert Banner (not yet planned)
- In-line Alert (in [backlog](https://github.com/orgs/adobe/projects/19/views/18))
- Toast (in [backlog](https://github.com/orgs/adobe/projects/19/views/18))

## 🤔 Expected Behavior

1. Adobe Express Theming support for the above component list.
2. Accordion, Alert, Alert Banner, Autocomplete, Card, Tag, and Toast components are supported in RS v3.

## 😯 Current Behavior
1. No Adobe Express Theming support for the above listed components.
2. Accordion, Alert, Alert Banner, Autocomplete, Card, Tag, and Toast components are not supported in RS v3.

## 💁 Possible Solution

N/A

## 🔦 Context

We support multiple verticals and this has affected our engineering teams to design/develop interim ad-hoc workarounds. More particularly, we are trying to institute Theming for company wide priorities. Gaining this support would help us to use scalable systems across all verticals and achieve efficient allocation of resources that compounds as Adobe's product/offer portfolio expands. 

## 🧢 Your Company/Team

Adobe/Digital Media/Adobe Business Platform

**Comment by snowystinger** [comment]
Closing as we support Express in a theme. Energy is focused on Spectrum 2 support now.
