### ISSUE TITLE
TagItem: Add states (invalid)

### ISSUE THREAD

**Issue by holblin** [adobe/react-spectrum#3658]
# 🙋 Feature Request

The current `TagItem` doesn't have a state like describe here: https://opensource.adobe.com/spectrum-css/tag.html
This would be useful to represent a previous selection that is invalid to the current user (permission error)

## 🤔 Expected Behavior

To be able to have an invalid state and pass it per TagItem.

## 😯 Current Behavior

There is no state and it's not possible to change the style of the TagItem with CSS.

## 💁 Possible Solution

Adding a state parameter and making the CSS match the documentation shared earlier.

## 🔦 Context

We need to show the selection of objects but some of them could have RBAC issues for the current user.

## 💻 Examples

![image-2022-09-13-17-54-16-213 (1)](https://user-images.githubusercontent.com/1541524/196505293-09d0e5c9-a4a3-4074-9edb-a5f0a1fb138a.png)

## 🧢 Your Company/Team

Adobe/CJM

**Comment by reidbarber** [comment]
I've updated the issue to remove an internal link. Please avoid posting internal links on this repo since it is public.

**Comment by dannify** [comment]
Individual invalid tags are not a currently support state for TagGroup. This would need to be a design discussion. Most likely with DX
