### ISSUE TITLE
TagGroup/TagItem: Invalid margin

### ISSUE THREAD

**Issue by holblin** [adobe/react-spectrum#3659]
# 🐛 Bug Report 

It seems that the margin between the V3 Tag is not correct.
The margin should be 4px

## 🤔 Expected Behavior

The margin between tags should be 4px

## 😯 Current Behavior
The margin between tags is twice 4px making a gap of 8px.

## 💁 Possible Solution

Make sure the margin doesn't stack or that the total is 4px.

## 🔦 Context

XD review points out the margin error.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Adobe/CJM

**Comment by snowystinger** [comment]
No internal links, this is a public project

**Comment by reidbarber** [comment]
Just confirmed that the current margins are correct and match the latest designs.
