### ISSUE TITLE
TagGroup: Limit the number of tags/size that tag takes to render

### ISSUE THREAD

**Issue by holblin** [adobe/react-spectrum#3660]
# 🙋 Feature Request

It would be amazing if TagGroup could have the option to limit the number of Tags to show or to limit the viewable size that the tag will take (3 lines for example). Then it could automatically have a tag (show more / +4 tags ....) and on click, it will expend all the tags.

## 🤔 Expected Behavior

We could limit the number of tags shown by default and have the option to extend the tags that are shown.

## 😯 Current Behavior

We can't limit the number of tags shown automatically.

## 🔦 Context

This was brought up during a UX review

## 🧢 Your Company/Team

Adobe/CJM

**Comment by snowystinger** [comment]
No internal links, this is a public project

**Comment by reidbarber** [comment]
I think you can achieve this with the current setup by placing an action button inline with the tag group and showing more when it's pressed. Not sure if there would be benefits to adding this as a feature handled by the TagGroup component itself, unless it had to do with the screen reader experience.
