### ISSUE TITLE
useMenu focus strategy sometimes doesn't focus a menu item

### ISSUE THREAD

**Issue by andelkocvjetkovic** [adobe/react-spectrum#3668]
🐛 Bug Report 
FocusStrategy doesn't always work when the menu is opened

🤔 Expected Behavior
Should always focus first item in the menu list

## 😯 Current Behavior
First item sometime get focused but sometime not.

https://user-images.githubusercontent.com/56834937/196887844-3be1f981-bbb2-4719-bd8a-817cf70f65dd.mov

**Comment by snowystinger** [comment]
Thanks for the issue and sorry for the delay. Looks like this one slipped through the cracks.

I assume this was the first example in the useMenu docs?
https://react-spectrum.adobe.com/react-aria/useMenu.htm

I tried it just now and I'm not seeing it focus anything. Focus strategy for mouse should be menu, not the first item. This differs from keyboard, where the first or last item will get focus.

I'm going to close as working as intended for now. Feel free to reopen if there's still an issue.

**Comment by oliviertassinari** [comment]
> Focus strategy for mouse should be menu, not the first item. This differs from keyboard, where the first or last item will get focus.

@snowystinger is there a reason for this? 

<img width="817" height="222" alt="Image" src="https://github.com/user-attachments/assets/c50de5d0-541b-439f-8d55-bd97663b2cde" />

https://www.w3.org/WAI/ARIA/apg/patterns/menubar/

or 

<img width="798" height="151" alt="Image" src="https://github.com/user-attachments/assets/40085763-1295-4163-af47-ee69c1f2f34d" />

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/menu_role

With [Material UI](https://mui.com/material-ui/react-menu/#basic-menu) the focus move to the first role="menuitem". In [Base UI](https://base-ui.com/react/components/menu), it's the other way around the focus move to role="menu". So I'm curious to understand you guys logic for this.

**Comment by devongovett** [comment]
Looks like it changed here: https://github.com/adobe/react-spectrum/pull/400

> The reason was that especially on touch devices, it's strange to tap on a picker and see an item already highlighted, even though there's no keyboard attached to your device. This also matches native behavior of menus opened with a mouse on desktop better.
