### ISSUE TITLE
Dropdown moves around when zooming in

### ISSUE THREAD

**Issue by mischnic** [adobe/react-spectrum#3678]
# 🐛 Bug Report 

When zooming in (using the Mac touchpad, not via Cmd+), the Combobox dropdown moves around unexpectedly.

## 😯 Current Behavior

https://user-images.githubusercontent.com/4586894/197382526-6ef34179-cf0e-48ba-af14-49778f9fa9f9.mov

## 🤔 Expected Behavior

Zooming shouldn't affect the position of the dropdown?

**Comment by snowystinger** [comment]
related, possibly duplicate https://github.com/adobe/react-spectrum/issues/2700

**Comment by LFDanLu** [comment]
I believe this is handled now via https://github.com/adobe/react-spectrum/pull/5612 as well which has just been released. I can no longer reproduce the issue in the docs so closing this out. Feel free to reopen if you see any other issues!
