### ISSUE TITLE
Controlled useNumberField shows previous value on input blur in Vite development

### ISSUE THREAD

**Issue by langarus** [adobe/react-spectrum#3754]
# 🐛 Bug Report 

Using react-aria react-stately (more precicesly `useNumberFieldState` and `useNumberField`)  in a react vite ts project results in buggy behavior in development mode.

This is only happening when we have the input as controlled. Meaning we pass both value and onChange to `useNumberField`.  
If we do not pass value as a prop it works just fine.

The tests are done in a Vite React TS env using exactly the example provided at:
https://react-spectrum.adobe.com/react-aria/useNumberField.html#example

**!!! This is only happening in development. After building (in prod) it does not happen.**

Created a stackblitz replicating the bug - but this is also happening locally.
https://stackblitz.com/edit/node-hmcypn?file=src/App.tsx

![vite_bug](https://user-images.githubusercontent.com/45520746/202169221-dcdb934f-667a-45e6-b64a-7f8adb65bf7d.gif)

## 🤔 Expected Behavior

The number in input should not change to previous one after onBlur.

## 😯 Current Behavior

onBlur in the input we have the previous value instead of the current one.

## 💁 Possible Solution

Maybe a hacky way would be to not pass the value, but this is not ideal. Any suggestions are welcome.

## 💻 Code Sample

https://stackblitz.com/edit/node-hmcypn?file=src/App.tsx

## 🔦 Context

This bug makes it close to impossible to develop in Vite using these hooks.

**Comment by snowystinger** [comment]
The reason this presents a problem in development mode is due to React.StrictMode. If you disable that, it should work as expected. We have an umbrella issue for strict mode, so I'll be closing this one.
https://github.com/adobe/react-spectrum/issues/779
