### ISSUE TITLE
`usePreventScroll` interferes with horizontal scrolling in IOS

### ISSUE THREAD

**Issue by jhyj0521** [adobe/react-spectrum#3779]
# 🐛 Bug Report 

`usePreventScroll` interferes with horizontal scrolling in ios.
Within a pop-up using usePreventScroll, I want to use an element with horizontal scrolling, but horizontal scrolling is interrupted.

## 🤔 Expected Behavior

`usePreventScroll` must not interfere with the horizontal scrolling of the internal element.

## 😯 Current Behavior

`usePreventScroll` is interfering with horizontal scrolling of internal elements.

## 💁 Possible Solution

If `scrollable.scrollHeight` and `scrollable.clientHeight` are the same, I think we can solve the problem by not executing unnecessary code that prevents screen touch movement.

## 💻 Code Sample

https://codesandbox.io/s/xenodochial-grass-3onoeo?file=/src/index.js

Click the open-popup button to display a pop-up using usePreventScroll.
Running url provided by the code sandbox on the iOS device shows that the vertical scroll works well, but the horizontal scroll works intermittently.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.11 |
| Browser          | safari |
| Operating System | IOS 16.1 |

**Comment by jhyj0521** [comment]
I put it on the Code Sample of the issue.

**Comment by dmitryshelomanov** [comment]
@jhyj0521 any solution for fix it ? Not working on ios safari and chrome browsers

**Comment by LFDanLu** [comment]
Resolved via https://github.com/adobe/react-spectrum/pull/3780
