### ISSUE TITLE
Table select all with custom checkbox misbehaving

### ISSUE THREAD

**Issue by vbudovski-alliance** [adobe/react-spectrum#3789]
# 🐛 Bug Report 

When using a custom styled checkbox for the TableSelectAllCell, it is not possible to toggle the state using a mouse click. Space works. Using the default checkbox input behaves as expected. Additionally, Enter does not toggle the select all checkbox, but it does work for row checkboxes.

```
function TableSelectAllCell({ column, state }) {
    const ref = useRef<HTMLTableHeaderCellElement>(null);
    const isSingleSelectionMode = state.selectionManager.selectionMode === 'single';
    const { columnHeaderProps } = useTableColumnHeader({ node: column }, state, ref);
    const { checkboxProps } = useTableSelectAllCheckbox(state);

    const inputRef = useRef(null);
    const checkboxState = useToggleState(checkboxProps);
    const { inputProps } = useCheckbox(checkboxProps, checkboxState, inputRef);

    return (
        <StyledTableSelectAllCell {...columnHeaderProps} ref={ref}>
            {isSingleSelectionMode ? (
                <VisuallyHidden>{inputProps['aria-label']}</VisuallyHidden>
            ) : (
                // FIXME: For some reason the custom checkbox cannot be toggled using a click in the select all cell.
                //  Find a proper fix later.
                <div onClick={() => checkboxState.toggle()} style={{ lineHeight: 1 }}>
                    <CheckboxBase
                        isSelected={checkboxProps.isSelected}
                        isDisabled={checkboxProps.isDisabled}
                        isIndeterminate={checkboxProps.isIndeterminate}
                        {...inputProps}
                        ref={inputRef}
                    />
                </div>
            )}
        </StyledTableSelectAllCell>
    );
}

const CheckboxBase = forwardRef<HTMLInputElement, CheckboxBaseProps>((props, ref) => {
    const { isSelected, isDisabled, isIndeterminate, ...inputProps } = props;
    const { focusProps, isFocusVisible } = useFocusRing();

    return (
        <>
            <VisuallyHidden>
                <input {...mergeProps(inputProps, focusProps)} ref={ref} />
            </VisuallyHidden>
            <StyledCheckbox
                isSelected={isSelected}
                isIndeterminate={isIndeterminate}
                isDisabled={isDisabled}
                isFocusVisible={isFocusVisible}
                aria-hidden
            >
                {isSelected ? <CheckIcon /> : isIndeterminate ? <MinusIcon /> : null}
            </StyledCheckbox>
        </>
    );
});
```

## 🤔 Expected Behavior

It is possible to click on the checkbox to toggle it.

## 😯 Current Behavior

It is not possible to click on the checkbox to toggle it, but space press works.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.21.0
| Browser          | Chrome 107
| Operating System | Mac OS

**Comment by snowystinger** [comment]
I know it's possible to get it working. We use our own custom styled checkbox in our implementation. You could refer to our source to try and find the difference https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/table/src/TableView.tsx#L769

Let us know if you're still having trouble after comparing those. We're all on break right now, but we'll be back at the start of the week.

**Comment by vbudovski-alliance** [comment]
I've had a look at the Spectrum source, and I can't spot any critical differences with what I've written. Any firther tips on debugging/fixing would be greatly appreciated.

**Comment by snowystinger** [comment]
Any chance you could put this into a codesandbox? would be easier to debug for us like that
Here's a starter template https://codesandbox.io/s/late-sun-k8dlvc, you can swap out RSP for the react-aria/react-stately packages

**Comment by vbudovski-alliance** [comment]
Here's an example of the styled checkbox issue: https://codesandbox.io/s/unruffled-chihiro-yi34et

**Comment by snowystinger** [comment]
Thanks, it sparked a memory that we have an open issue for this https://github.com/adobe/react-spectrum/issues/2383 along with a workaround. Can you see if that works for you?

**Comment by vbudovski-alliance** [comment]
Unfortunately adding `pressProps` to the custom checkbox doesn't seem to help, and breaks the hit box a bit.

**Comment by snowystinger** [comment]
I just tried it out in your codesandbox. It starts to behave if you have both the usePress and you make the React Fragment around it a `label` instead
https://codesandbox.io/s/awesome-kate-rrd70p?file=/src/Checkbox.tsx:586-600

**Comment by vbudovski-alliance** [comment]
Can confirm the click now works. Probably safe to close this as as duplicate of #2383.
