### ISSUE TITLE
[React Aria] Focusing issues with useSelect when using a controlled component pattern and initial value is empty string

### ISSUE THREAD

**Issue by mryechkin** [adobe/react-spectrum#3793]
# 🐛 Bug Report 

I'm running into an issue with a controlled component pattern, where setting the `selectedKey` of a component built with [useSelect](https://react-spectrum.adobe.com/react-aria/useSelect.html) to an empty string results in focusing issues.

```jsx
const [animal, setAnimal] = React.useState('');

<Select selectedKey={animal} onSelectionChange={(value) => setAnimal(value)}>
```

When navigating with a keyboard and pressing the DOWN key, the Popover / ListBox opens, but instead of navigating up and down through the items it just keeps closing and opening.

![react-aria-select](https://user-images.githubusercontent.com/5657181/204385196-66cf14ca-a31a-4be4-a679-43aa726ad983.gif)

This issue doesn't happen if setting the initial state to `null` - however that results in a React warning about component changing from uncontrolled to controlled as soon as a selection is made, which isn't desired. This was the recommendation in a similar issue #1580, but it doesn't seem to account for the warning.

## 🤔 Expected Behavior

Navigating to the component with a TAB key and then pressing DOWN should open the Popover / ListBox and go through the selection

## 😯 Current Behavior

Navigating to the component with a TAB key and then pressing DOWN repeatedly opens and closes the Popover / ListBox

## 💁 Possible Solution

N/A

## 🔦 Context

I'm trying to build a custom Select using one of the provided examples in the docs, and make sure that it can be used as a controlled component.

## 💻 Code Sample

https://codesandbox.io/s/react-aria-select-vgl4n9?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria  | 3.21.0
| Browser          | Chrome 107
| Operating System | MacOS 13.0.1

## 🧢 Your Company/Team

External

## 🕷 Tracking Issue (optional)

N/A

**Comment by LFDanLu** [comment]
I'm not seeing the "uncontrolled to controlled" error when initializing `animal` to null: https://codesandbox.io/s/react-aria-select-forked-846tnk?file=/src/App.tsx, do you have another sandbox demonstrating that? As a side note, I've turned off the Typescript strict null check in that sandbox, the null Typescript issues is something we are aware of and incrementally fixing via https://github.com/adobe/react-spectrum/issues/3183.

**Comment by mryechkin** [comment]
Hi @LFDanLu - thanks for the quick response!

Turns out it was my own wrongdoing after a long day of looking at the same code 🤦‍♂️ I was seeing the warning only when initializing to `undefined` instead of `null` - which makes sense.

Thanks again! Closing the issue now.
