### ISSUE TITLE
useComboBox/useComboBoxState ignores selectedKey when rendering on server

### ISSUE THREAD

**Issue by joshuajaco** [adobe/react-spectrum#3796]
# 🐛 Bug Report 

When passing `selectedKey` to `useComboBox` and  `useComboBoxState` when server-side rendering I expect the value of the selected item will be displayed. Instead the value remains empty and the place holder is shown instead. Hydrating on the client results in the correct value being show, however the user will still experience a content shift as the server rendered something different.

## 🤔 Expected Behavior

The same value will be shown in SSR and CSR.

## 😯 Current Behavior

SSR shows no value, CSR shows correct one

## 💻 Code Sample

https://codesandbox.io/s/zen-bas-dof5xx?file=/src/index.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.21.0
| react-stately   | 3.19.0
| Browser          | Chrome/107.0
| Operating System | macOS Monterey 12.6.1

**Comment by snowystinger** [comment]
One quick note, you're using both `items` as well as passing in actual `Items`, these are mutually exclusive options. Use `Item` for small data sets you don't really need to manage. Use `items` for a controlled state, usually used for async or large data sets that change a lot.

**Comment by joshuajaco** [comment]
> One quick note, you're using both `items` as well as passing in actual `Items`, these are mutually exclusive options.

Yeah my bad, I was testing something. Should have forked the sandbox beforehand. I've reverted it to the state it was before.

**Comment by snowystinger** [comment]
Looks like you forgot to save? I still see both. Don't worry, I do it all the time too.

**Comment by joshuajaco** [comment]
I had a look at the implementation and from what I can tell it extracts the input value from the actual dom element of the selected item, which won't work on the server. A possible work around could be to controll the input value entriely by passing `inputValue` to `useComboBoxState` .

**Comment by joshuajaco** [comment]
> Looks like you forgot to save? I still see both. Don't worry, I do it all the time too.

now...

**Comment by joshuajaco** [comment]
I just did maintenance and it turns out it has been solved.
