### ISSUE TITLE
@react-aria/useTextField with TypeScript: Types of property 'value' are incompatible

### ISSUE THREAD

**Issue by cperilla318** [adobe/react-spectrum#3805]
# 🐛 Bug Report 

When using `useTextField`, the types  in `@react-aria/texfield@3.21.0` don't match with the React types for the "value" prop on <input> elements:
```
"Argument of type '{ ref?: LegacyRef<HTMLInputElement>; key?: Key; accept?: string; alt?: string; autoComplete?: string; autoFocus?: boolean; capture?: boolean | \"user\" | \"environment\"; ... 281 more ...; onTransitionEndCapture?: TransitionEventHandler<...>; }' is not assignable to parameter of type 'AriaTextFieldOptions<\"input\">'.
Types of property 'value' are incompatible.
Type 'string | number | readonly string[]' is not assignable to type 'string'. 
Type 'number' is not assignable to type 'string'.",
```

## 🤔 Expected Behavior

no type error
## 😯 Current Behavior
Type error
![image](https://user-images.githubusercontent.com/116305169/204861669-96a98739-383b-42dc-8d39-db2a8f29f32c.png)

## 🔦 Context

Use [the docs example](https://react-spectrum.adobe.com/react-aria/useTextField.html#example)

## 💻 Code Sample

https://codesandbox.io/s/patient-sky-5k8qky?file=/src/Input.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/textfield| 3.21.0
| Browser          |
| Operating System |

**Comment by cperilla318** [comment]
Just realized if I add value type to my interface, now "defaultValue" has the same issue
![image](https://user-images.githubusercontent.com/116305169/204870598-e132bd05-ecea-444b-8342-4b399c9c446e.png)

If I keep doing this, more props have the same issue
![image](https://user-images.githubusercontent.com/116305169/204871178-ee9168e1-44ed-48c3-a50f-a619b71d46b5.png)

**Comment by LFDanLu** [comment]
You can actually use our [`AriaTextFieldProps` type](https://github.com/adobe/react-spectrum/blob/b35d5c02fe900badccd0cf1a8f23bb593419f238/packages/%40react-types/textfield/src/index.d.ts#L34) for your props like so: https://codesandbox.io/s/white-river-fl4elh. @devongovett has been working on making our docs examples TS compatible via https://github.com/adobe/react-spectrum/pull/3710 so hopefully that will make using our examples much easier.
