### ISSUE TITLE
font-family is incorrect when lang="zh-Hant"

### ISSUE THREAD

**Issue by carolframpton** [adobe/react-spectrum#3834]
# 🐛 Bug Report 

When <html lang="zh-Hant" ... /> the font-family is simplified Chinese not traditional Chinese as expected.

## 🤔 Expected Behavior
zh-Hant = traditional Chinese

## 😯 Current Behavior

Spectrum-CSS and RS's copy of Spectrum-CSS do not have an entry for `lang:(zh-Hant)` so the font family defaults to the one for `zh` which is the same as `zh-Hans` which is the wrong font-family.

Currently `font-family: 'adobe-clean-han-simplified-c', 'SimSun', 'Heiti SC Light', 'sans-serif';`

See https://github.com/adobe/react-spectrum/blob/main/packages/%40adobe/spectrum-css-temp/components/commons/fonts.css#L56

and

https://github.com/adobe/spectrum-css/blob/43a159f9fcc1a5114ea59fd61f5e63ecf6e7b1fa/components/typography/font.css#L29

Note `zh-Hant` maps to RS's `I18nProvider` `locale="zh-TW"`.

## 💁 Possible Solution

Add entry in the above files for `zh-Hant`.

## 🔦 Context

Our loc QE spotted this issue and filed a bug against our product. They expect
`font-family: 'adobe-clean-han-traditional', 'MingLiu', 'Heiti TC Light','sans-serif'; `

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | "3.23.0"
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Adobe Admin Console

**Comment by LFDanLu** [comment]
TODO: check that this font is in the typekit
