### ISSUE TITLE
[react-aria] useTextField returns onBlur null instead of undefined

### ISSUE THREAD

**Issue by DeLm0re** [adobe/react-spectrum#3861]
# 🐛 Bug Report 

I do not know if this is intentional or not, but I think there is an issue with the `useTextField` hook in `react-aria`.
All event handlers returned are set to `undefined` when not defined except `onBlur` which is returned as `null`.

At first, it does not seem worrying, but when it comes to `mergeProps` things become a little more spicy.
In fact, when you try to merge props coming from `react-aria` with props coming for on another library (`react-number-format` in my case) then `mergeProps` results in `onBlur` defined as `null` so when activated, it prompts an error in console.

`onBlur is not a function`

I do not know if it is a constraint in the library code but it would be great if `onBlur` was returned as `undefined`. Plus it makes more sense considering all other handlers work like that.

## 💻 Code Sample

https://codesandbox.io/s/condescending-parm-s6wufv?file=/src/App.tsx

## 🌍 Your Environment

MacOs
React 18.2
With and without Vite 4.0.1

**Comment by reidbarber** [comment]
Looks like something we can fix here:

https://github.com/adobe/react-spectrum/blob/3155e4db7eba07cf06525747ce0adb54c1e2a086/packages/%40react-aria/interactions/src/useFocus.ts#L77-L78

We are incrementally updating our files to support typescript strict mode, so I think we would have caught this in the process eventually. Feel free to open a PR if you'd like, otherwise it should get fixed eventually.

**Comment by DeLm0re** [comment]
@reidbarber Thanks for the reply & the explanation.

For the moment it is not an emergency as we found multiple workarounds. However in order to keep the code clear and concise, it would be great if this is fixed as soon as possible.

I will look into opening a PR

**Comment by snowystinger** [comment]
I've actually made this change here https://github.com/adobe/react-spectrum/pull/3801
It was causing an issue with mergeProps for us as well https://github.com/adobe/react-spectrum/pull/3801?notification_referrer_id=NT_kwDOAAqndbE0OTU2MDkxOTg2OjY5ODIyOQ#discussion_r1052734195

**Comment by DeLm0re** [comment]
@snowystinger Awesome 👍
