### ISSUE TITLE
useDateField does not accept onChange, value, defaultValue  in typescript

### ISSUE THREAD

**Issue by dev-seahouse** [adobe/react-spectrum#3873]
# 🐛 Bug Report 

## 🤔 Expected Behavior

AriaDateFieldProps should accept onChange

## 😯 Current Behavior

when passing prop with  onChange, value, defaultValue to useDateField, typescript error is thrown 

Type '{ value: CalendarDate; }' is not assignable to type 'IntrinsicAttributes & AriaDateFieldProps<CalendarDate>'.
  Property 'value' does not exist on type 'IntrinsicAttributes & AriaDateFieldProps<CalendarDate>'.ts(2322)

## 💻 Code Sample

https://codesandbox.io/s/compassionate-firefly-cgw2k3?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
That's just the props for the Aria hook, it doesn't know anything about values or onChange for those values. You need to combine the aria props with the stately props.
You can see how we did it here https://github.com/adobe/react-spectrum/blob/main/packages/%40react-types/datepicker/src/index.d.ts#L98
And here's the type for the stately hook https://github.com/adobe/react-spectrum/blob/86b9d3d0564244215a73c3bd18edad53078c4f3b/packages/%40react-stately/datepicker/src/useDateFieldState.ts#L118
