### ISSUE TITLE
`getDatesInWeek` from `useCalendarState` throws TypeError about `Intl.Locale` constructor

### ISSUE THREAD

**Issue by gregoralbrecht** [adobe/react-spectrum#3881]
# 🐛 Bug Report 

I'm trying to build a date picker using [this example](https://codesandbox.io/s/objective-shape-8r4utm?file=/src/Calendar.js) as a blueprint. The example works but it isn't using TypeScript, which I'm trying to do.

The example contains this:
```jsx
import { useCalendarState } from "react-stately";
import { createCalendar } from "@internationalized/date";
[...]
const state = useCalendarState({ ...props, createCalendar });
```

Which seems to work fine. But we I try to extract the dates to use in a grid from `state`, TypeScript throws an error:
```jsx
import { useCalendarGrid } from "react-aria";
import { getWeeksInMonth } from "@internationalized/date";
[...]
const { weekDays } = useCalendarGrid({}, state)
const weeksInMonth = getWeeksInMonth(state.visibleRange.start, "de-DE")
const weeks = [...new Array(weeksInMonth)].map((weekIndex) => {
    // This throws 💥 a TypeError: "First argument to Intl.Locale constructor can't be empty or missing"
    const datesInThisWeek = state.getDatesInWeek(weekIndex); // 

    [...]
  });

```

## 🤔 Expected Behavior

I'd expect `state.getDatesInWeek(weekIndex: number)` to return an array of dates. [The docs](https://react-spectrum.adobe.com/react-aria/useCalendar.html):
>The `state.getDatesInWeek` function returns the dates in each week of the month. 

## 😯 Current Behavior

Throws an error: 
>TypeError
>First argument to Intl.Locale constructor can't be empty or missing

I found [this issue](https://github.com/microsoft/TypeScript/issues/47169) that describes similar behavior but I'm not sure if that's very helpful.

## 🔦 Context

I'm trying to recreate the example linked above in TypeScript so that I can build my own `<DatePicker>`.

## 💻 Code Sample

[Here's a CodeSandbox with all of my code.](https://codesandbox.io/s/finn-datepicker-d2e146?file=/src/CalendarGrid.tsx) There's line `15` in the file `CalendarGrid.tsx` that throws.

## 🌍 Your Environment

I'm working in the linked CodeSandbox

**Comment by LFDanLu** [comment]
Looks like you need to provide a locale to `useCalendarState` like so: https://codesandbox.io/s/finn-datepicker-forked-4m8nhi?file=/src/App.tsx:162-196. [This line](https://github.com/adobe/react-spectrum/blob/080488a859be32a1ee30f4f9fdcc4d5e8331a144/packages/%40react-stately/calendar/src/useCalendarState.ts#L316) calls [Intl.Locale(locale)](https://github.com/adobe/react-spectrum/blob/080488a859be32a1ee30f4f9fdcc4d5e8331a144/packages/%40internationalized/date/src/queries.ts#L211) and if `locale` is undefined causes the type error you saw
