### ISSUE TITLE
button story: user-select:none on press test does not work in High Contrast mode

### ISSUE THREAD

**Issue by jnurthen** [adobe/react-spectrum#3894]
# 🐛 Bug Report 

user-select:none on press test story does not work in high contrast mode

## 🤔 Expected Behavior

All stories should meet accessibility guidelines

## 😯 Current Behavior

The button appears in red which isn't a colour which should appear in high contrast mode

## 💁 Possible Solution

Do not use UNSAFE_style to set background colours for items unless they have been tested in High Contrast mode.
Alternatively change the high contrast implementation to not use forced-color-adjust: none on the base element.

## 🔦 Context

Performing an accessibility audit of all react spectrum components.

## 💻 Code Sample

(https://reactspectrum.blob.core.windows.net/reactspectrum/41e26fa0f01ee9ab6e5c21edf6f7bb5d498bf40f/storybook/index.html?path=/story/button--user-select-none-on-press-test)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 
| Browser          | Edge
| Operating System | Windows (or using forced-colors in dev tools)

## 🧢 Your Company/Team

Accessibility

**Comment by dannify** [comment]
These stories are for internal testing only and are not real world examples.  Accessibility testing can be carried out on the documentation website or the more standard stories if more examples are needed.
