### ISSUE TITLE
Clicking outside combobox selects the last focused item

### ISSUE THREAD

**Issue by alirezamirian** [adobe/react-spectrum#3900]
# 🐛 Bug Report 

Due to a recent change in @react-stately/combobox, combobox calls `onSelectionChange` when clicking outside.
NOTE: **This is a different issue than #2181.**

## 🤔 Expected Behavior
Clicking outside should not select last focused option.

## 😯 Current Behavior
Depending on the implementation of the combobox's popover, clicking outside may select a value.

In react-spectrum's implementation, it doesn't happen, because of how `Popover` is implemented. But here is an example copied from react-aria docs: https://codesandbox.io/s/react-stately-combobox-issue-v54cui?file=/src/App.js
The only difference with [the example in the documentation](https://react-spectrum.adobe.com/react-aria/usePopover.html#example) is that the Popover is made modal (by not passing `isNonModal` to Popover).

## 💁 Context and Possible Solution
This seems to be a regression caused 168ca5a. Previous to this change `close` function returned from `useComboboxState` was coming from `triggerState`, and with this change, it's overwritten to `commit`:
https://github.com/adobe/react-spectrum/blob/73d8be4dd7ff1713084cfe3f602f11aef1cecb07/packages/%40react-stately/combobox/src/useComboBoxState.ts#L304-L308
I'd guess the intention of this change was to not just close the menu, but to make sure the necessary cleanup is done as well, whenever the combobox menu is closed for whatever reason (such as outside click). But in that case it should be `commitSelection` or `commitCustomValue` being called instead of `commit`. 

## 💻 Code Sample

https://react-spectrum.adobe.com/react-aria/usePopover.html#example

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.22.0
| react-stately          | 3.20.0 (no issue with 3.18.0)
| browser     | Chrome
| Operating System | MacOS

**Comment by LFDanLu** [comment]
Curious that the setting for `isNonModal` changes the behavior, still digging why. That option is necessary for the ComboBox so that the input isn't aria hidden when the popover is open

**Comment by LFDanLu** [comment]
Mind expanding on why you are removing `isNonModal` from your implementation of ComboBox?

**Comment by alirezamirian** [comment]
> Curious that the setting for isNonModal changes the behavior, still digging why

I've traced it through:
When `isNonModal` is false, in  `useOverlay` is called with `isDismissable: false`:
https://github.com/adobe/react-spectrum/blob/dc035b2f5878c6883d92567e089209d105d8c04b/packages/%40react-aria/overlays/src/usePopover.ts#L81
When `isDismissable` is false, `useInteractOutside` is called with `onInteractOutside` set to `null`.
https://github.com/adobe/react-spectrum/blob/dc035b2f5878c6883d92567e089209d105d8c04b/packages/%40react-aria/overlays/src/useOverlay.ts#L123
That in turn means in `useInteractOutside`, the pointerDown handler on `document` won't call `onInteractStart` callback passed from `useOverlay`:
https://github.com/adobe/react-spectrum/blob/dc035b2f5878c6883d92567e089209d105d8c04b/packages/%40react-aria/interactions/src/useInteractOutside.ts#L49-L56
And that's important because in `onInteractStart` callback in `useOverlay`, `preventDefault` and `stopPropagation` is called on the pointer down event:
https://github.com/adobe/react-spectrum/blob/dc035b2f5878c6883d92567e089209d105d8c04b/packages/%40react-aria/overlays/src/useOverlay.ts#L94-L101
Which means the `onBlur` handler in `useCombobox` won't get called:
https://github.com/adobe/react-spectrum/blob/dc035b2f5878c6883d92567e089209d105d8c04b/packages/%40react-aria/combobox/src/useComboBox.ts#L144
Which otherwise would call `setFocused` In `useComboboxState`, with `false`:
https://github.com/adobe/react-spectrum/blob/dc035b2f5878c6883d92567e089209d105d8c04b/packages/%40react-stately/combobox/src/useComboBoxState.ts#L287-L302
And that would call `commitSelection`, which clears the input and closes the menu.

**Comment by LFDanLu** [comment]
Thank you for the detailed tracing! From a quick pass of the logic, I believe this change makes sense. It would also mean that we then wouldn't commit the focused value when using the visually hidden dismiss buttons, but that feels like the correct behavior.

**Comment by alirezamirian** [comment]
Yeah, good point with the visually hidden dismiss button. I guess I can open a PR tomorrow.
