### ISSUE TITLE
Re-export Node type in react-aria

### ISSUE THREAD

**Issue by donaldpipowitch** [adobe/react-spectrum#3902]
# 🐛 Bug Report 

Not a "bug" in the traditional sense, but it falls under _"Did something not work as expected?"_. I once had this feature request (https://github.com/adobe/react-spectrum/issues/3240) to export all types in `react-aria` and `react-stately` and your wonderful team added this.

But I just noted that there is at least one type which is not exported by `react-aria` and `react-stately`: `Node`. For that type we still need to use `@react-types/shared` as a direct dependency. Is this type missing an export or is this intended?

## 🤔 Expected Behavior

`import type { Node } from 'react-aria';` works.

## 😯 Current Behavior

`import type { Node } from 'react-aria';` errors, because of `Module '"react-aria"' has no exported member 'Node'.`.

## 💁 Possible Solution

Export all missing types from `@react-types/shared` in `react-aria` and `react-stately`.

## 🔦 Context

"How has this issue affected you?" We need to manage more dependencies that should stay in-sync.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | "react-aria": "^3.22.0" |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
You could import them from the `@react-types/...` packages. We could definitely look into a combined package like `react-stately`or `react-aria` for the types or maybe some of these should be exported by those combined packages as well.

**Comment by LFDanLu** [comment]
Discussed this in our grooming session today. We'd like to look into exporting more types from our monopackages, specifically types that are actually reachable from other publicly available types.

**Comment by AndyOGo** [comment]
+1

**Comment by devongovett** [comment]
`Node` is exported from the `react-stately` monopackage. https://github.com/adobe/react-spectrum/blob/3b390fd3758aa21a8b0e933b68fbf7ac5728cae8/packages/react-stately/src/index.ts#L33

I think this issue is probably outdated since we did add a lot of type definitions to both `react-aria` and `react-stately`. Which one a type is in depends on what level it is used/defined in.

**Comment by AndyOGo** [comment]
Hmh, I couldn’t import the Item type from the collection interface via react-aria mono package.

I will try it via react-stately mono package, mayve it was my fault.

**Comment by AndyOGo** [comment]
I just update [`react-aria`](https://react-spectrum.adobe.com/react-aria/getting-started.html#installation) and [`react-stately`](https://react-spectrum.adobe.com/react-stately/getting-started.html#installation) mono package.

Some types imports aren't working, like:

```ts
import { type CollectionChildren } from "react-aria";
// > Module '"react-aria"' has no exported member 'CollectionChildren'.ts(2305)

import { type CollectionChildren } from "react-stately";
// > Module '"react-stately"' has no exported member 'CollectionChildren'.ts(2305)
```

Only this works:
```ts
import { type CollectionChildren } from "@react-types/shared";
```

**Comment by devongovett** [comment]
Not all types are exported from the monopackage. This issue was about `Node`. What are you doing with `CollectionChildren`? That's more of an internal type.

**Comment by AndyOGo** [comment]
We itilizse the useListState hook, which takes a children prop of tagt type.
