### ISSUE TITLE
NumberField width 100% break in RSP 3.24.1

### ISSUE THREAD

**Issue by holblin** [adobe/react-spectrum#3906]
# 🐛 Bug Report 

After upgrading RSP from 3.23.0 to 3.24.1, our NumberField with width=100% are broken and doesn't properly takes the correct space.

## 🤔 Expected Behavior

The NuberField is properly shown

![Screen Shot 2023-01-11 at 1 41 40 PM](https://user-images.githubusercontent.com/1541524/211924002-76c2db51-825a-42a6-8bf5-7d0539de3f51.png)

## 😯 Current Behavior

The NumberField has a big empty space.

![Screen Shot 2023-01-11 at 1 41 58 PM](https://user-images.githubusercontent.com/1541524/211924020-c3758b5e-99d8-49c7-8f20-d02d5ffd63cf.png)

## 💁 Possible Solution

We fix temporary the problem with:

```
body
  [class*='spectrum-Field'][class*='spectrum-Stepper-container']
  [class*='spectrum-Stepper-field'] {
  width: 100%;
}
```

## 💻 Code Sample

```
    <NumberField
      width="100%"
      ...
    />
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.24.1 |

## 🧢 Your Company/Team

Adobe/CJM/AO

**Comment by snowystinger** [comment]
I don't see this an issue in codesandbox, https://codesandbox.io/s/angry-hamilton-p6h9kl?file=/src/App.js
can you reproduce it outside of your app?

**Comment by LFDanLu** [comment]
Please reopen with a minimal reproduction
