### ISSUE TITLE
HiddenSelect does not provide a value for collections with size > 300, throwing console error

### ISSUE THREAD

**Issue by omacranger** [adobe/react-spectrum#3917]
# 🐛 Bug Report 

When rendering collections with a size of 300 or more, HiddenSelect does not provide a fallback value for the rendered input field which logs a console error for value of null, then uncontrolled -> controlled switch when a value is then set / provided onSelectionChange.

## 🤔 Expected Behavior

No console errors, probably needs the same `state.selectedKey ?? ''` that `useHiddenSelect` uses for the `selectProps`.

## 😯 Current Behavior

Console error for invalid value, then error for uncontrolled -> controlled state switch. 

## 💁 Possible Solution

`state.selectedKey ?? ''` on [L137](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/select/src/HiddenSelect.tsx#L137)

## 💻 Code Sample

https://codesandbox.io/s/epic-swirles-2ho1my?file=/src/index.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.24.1
| Browser          | Chrome
| Operating System |

**Comment by snowystinger** [comment]
I see, you mean this one?
> Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.

followed by 
> Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen.

I think your diagnosis seems correct. Would you like to open a PR?

**Comment by omacranger** [comment]
@snowystinger Created, let me know how it looks. Thanks.
