### ISSUE TITLE
Truncated text is not visible on ellipsis in table view's cells

### ISSUE THREAD

**Issue by vishalsehgal11** [adobe/react-spectrum#3922]
# 🐛 Bug Report 

Truncated text is not visible on ellipsis in table view's cells
<img width="80" alt="image" src="https://user-images.githubusercontent.com/10407036/212996248-78b99ec9-4dca-44c1-8509-ee1cbeab4bc7.png">

## 🤔 Expected Behavior

Show tooltip with truncated text when ellipsis is visible in the cells

## 😯 Current Behavior

Text gets truncated and ellipsis is visible but there is now way to read whole text, it is just lost

## 💁 Possible Solution

Showing whole text in the tooltip which should be visible when ellipsis is there

## 🔦 Context

This component is used in acc project where we consume inventory 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

ACC Web UI

**Comment by dannify** [comment]
Resizable columns can be used to solve this issue.
https://react-spectrum.adobe.com/react-spectrum/TableView.html#column-resizing
