### ISSUE TITLE
Invalid date conversion for old dates in local tz

### ISSUE THREAD

**Issue by tomfa** [adobe/react-spectrum#3924]
# 🐛 Bug Report 

When using `parseAbsolute(value, "Europe/Oslo")` as a value in `useDateFieldState`, an odd bug occurs.
The minutes/seconds/dates are being updated on update to year.

See [minimal example](https://codesandbox.io/s/funny-brattain-i87tq4?file=/src/DateInput.js)

## 🤔 Expected Behavior

Changing the year does not affect other fields.

## 😯 Current Behavior

Updating year also changes minute/second/day (depending on granularity).

## 💁 Possible Solution

It seems to me that `parseAbsolute` returns wrong timezoneOffset for old dates, in certain timezones
```ts
parseAbsolute('0002-01-01T00:00:00Z', 'Europe/Oslo')
// returns { ... , offset :3180000 }}, but should maybe be 3212000?
```

### Workaround

Using a `CalendarDateTime` rather than `ZonedDateTime`. See method `workaroundParseDate` in [`DateInput.js`](https://codesandbox.io/s/funny-brattain-i87tq4?file=/src/DateInput.js)

## 🔦 Context

Trying to use @react-aria/datepicker, with timezone `Europe/Oslo`.

## 💻 Code Sample

See [minimal example](https://codesandbox.io/s/funny-brattain-i87tq4?file=/src/DateInput.js)

## 🌍 Your Environment

I suppose @internationalized/date is the culprit.

| Software         | Version(s) |
| ---------------- | ---------- |
| [@internationalized/date](https://codesandbox.io/examples/package/@internationalized/date) | 3.0.2 |
| [@react-aria/datepicker](https://codesandbox.io/examples/package/@react-aria/datepicker) | 3.2.1 |
| [@react-aria/i18n](https://codesandbox.io/examples/package/@react-aria/i18n) | 3.6.3 |
| Browser          | Chrome, Firefox, Safari
| Operating System | Mac OSX 12.1

**Comment by devongovett** [comment]
hmm, it's not happening for me in your example. Any other steps needed to reproduce?

**Comment by tomfa** [comment]
Seems it takes my browser timezone into consideration. 


https://user-images.githubusercontent.com/1502702/212965862-cbc09d36-13df-4cf2-8e8c-0143ef3eaf33.mov

**Comment by tomfa** [comment]
The issue seem to be that `Date.getTimezoneOffset` returns offset in minutes, while old dates in several timezones have offsets in seconds. 

Firefox handles this by returning a floating number in these cases (which creates a potentially different behaviour for Firefox users - I haven't checked). 

The solution here is anyway not to rely on `getTimezoneOffset`, or only use it when the date is "newer".

Related:
- DayJS fixing a _related_ issue: iamkun/dayjs#2016
- Related issue in Moment: https://github.com/moment/moment/issues/5515

I can make a PR

**Comment by devongovett** [comment]
Great catch! Thanks for doing the research on it.
