### ISSUE TITLE
Support long-form date names in `weekDays` return value in useCalendarGrid

### ISSUE THREAD

**Issue by egdelwonk** [adobe/react-spectrum#3925]
# 🙋 Feature Request

Currently, `useCalendarGrid` returns single-letter dates on the GregorianCalendar. We would like to use `Sun`, `Mon`, etc. in order to better differentiate between Saturday and Sunday.

## 🤔 Expected Behavior

We should be able to customize the `weekDays` return value while preserving i18n

## 😯 Current Behavior

We cannot change the week day headings from their default behavior for `GregorianCalendar`

## 💁 Possible Solution

If we could add props to `GregorianCalendar` to change the heading abbreviation length.

## 🔦 Context

Our UX designers requested that week days be identified with three letters instead of one. We would like to use `react-aria`'s default behavior as much as possible, but cannot meet the designers' requests as-is.

## 💻 Examples

![image](https://user-images.githubusercontent.com/512548/212996901-0c8f9e9b-4d94-40ae-a228-c790aca0f264.png)

## 🧢 Your Company/Team

A group of devs who really like working with react-aria ❤️

**Comment by devongovett** [comment]
Added a weekdayStyle prop in #4519.
