### ISSUE TITLE
Dismissible dialog drag in+drag out dismisses 

### ISSUE THREAD

**Issue by jamiebuilds** [adobe/react-spectrum#3933]
# 🐛 Bug Report 

You can reproduce this in the docs: https://react-spectrum.adobe.com/react-aria/useModalOverlay.html#dismissable

In the dismissible example:

- Open Dialog
- Press start on inside of dialog, drag outside of dialog, press end
- _Dialog does not close_
- Press start on outside of dialog, drag inside of dialog, press end
- _Dialog does not close_

Then try this:

- Press start on outside of dialog, drag inside of dialog, press end
- Press start on inside of dialog, drag outside of dialog, press end
- _Dialog closes_ (wrong)

## 🤔 Expected Behavior

- Press start on outside of dialog, drag inside of dialog, press end
- Press start on inside of dialog, drag outside of dialog, press end
- **Dialog does not close**

## 😯 Current Behavior

See above

## 💁 Possible Solution

It seems to be holding onto some state between the two interactions that make it think the drag started and ended outside of the dialog.

## 🔦 Context

Discovered when fixing unrelated bug.

## 💻 Code Sample

The dismissible example in the docs: https://react-spectrum.adobe.com/react-aria/useModalOverlay.html#dismissable

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.22.0
| Browser          | Safari, Chrome
| Operating System | macOS

## 🧢 Your Company/Team

Signal

## 🕷 Tracking Issue (optional)

N/A

**Comment by snowystinger** [comment]
Yep, I see it too, probably because of this line
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/useInteractOutside.ts#L62
we should probably always set the pointerDown to false regardless of where the pointer up came from
