### ISSUE TITLE
Cannot set properties of undefined (setting 'nodeToRestore') 

### ISSUE THREAD

**Issue by Lingareddyvinitha** [adobe/react-spectrum#3954]
# 🐛 Bug Report 

When we try to open useOverlays from @react-aria packages

    

## 🤔 Expected Behavior

When upgrading to React version 18 with strict mode enabled, some UI elements such as pickers and Overlays may display all items

## 😯 Current Behavior
When upgrading to React version 18 with strict mode enabled, some UI elements such as pickers and Overlays may experience crashes and errors.
 
![image](https://user-images.githubusercontent.com/47639732/214493634-8ee94e31-0da5-4fe4-a6b2-32cea027f62a.png)

### Our packages
```
    "@react-aria/button": "3.6.1",
    "@react-aria/checkbox": "3.5.1",
    "@react-aria/combobox": "3.4.1",
    "@react-aria/dialog": "3.3.1",
    "@react-aria/focus": "3.8.0",
    "@react-aria/i18n": "3.6.0",
    "@react-aria/interactions": "3.12.0",
    "@react-aria/link": "3.3.3",
    "@react-aria/listbox": "3.6.1",
    "@react-aria/menu": "3.6.1",
    "@react-aria/overlays": "3.10.1",
    "@react-aria/radio": "3.3.1",
    "@react-aria/select": "3.8.1",
    "@react-aria/separator": "3.2.3",
    "@react-aria/table": "3.4.1",
    "@react-aria/tabs": "3.3.1",
    "@react-aria/textfield": "3.7.1",
    "@react-aria/tooltip": "3.3.1",
    "@react-aria/utils": "3.13.3",
    "@react-aria/virtualizer": "3.5.0",
    "@react-spectrum/progress": "3.3.1",
    "@react-spectrum/provider": "3.5.1",
    "@react-spectrum/text": "3.3.1",
    "@react-spectrum/theme-default": "3.3.3",
    "@react-spectrum/utils": "3.7.3",
    "@react-stately/collections": "3.4.3",
    "@react-stately/data": "^3.6.1",
    "@react-stately/menu": "3.4.1",
    "@react-stately/overlays": "3.4.1",
    "@react-stately/radio": "3.6.0",
    "@react-stately/select": "3.3.2",
    "@react-stately/table": "3.4.0",
    "@react-stately/tabs": "3.2.1",
    "@react-stately/tooltip": "3.2.1",
    "@react-stately/tree": "3.3.3"
    
 ```
 [devongovett](https://github.com/devongovett) 
 [Tom Schindl](https://github.com/tomsontom)
[Aaron Hardy](https://github.com/Aaronius)

**Comment by RajaTheKing826** [comment]
Yah, i'm also facing the same issue, is there any solution for this @devongovett

**Comment by devongovett** [comment]
Strict mode is not yet supported but we are working on it.

**Comment by Lingareddyvinitha** [comment]
[devongovett](https://github.com/devongovett) 
 
When will the final release of this issue be available?

Currently, we have removed the strict mode from our application, but some members of the community suggest it would be beneficial to reinstate it.

Could you provide suggestions for disabling strict mode for specific components or alternative solutions?

**Comment by snowystinger** [comment]
We don't have a date yet for our next release, but we are in the midst of prepping for it. So likely next week or the one after.
