### ISSUE TITLE
Numberfield does not support name props, it is required for formvalidation

### ISSUE THREAD

**Issue by samyakjain333** [adobe/react-spectrum#3956]
# 🐛 Bug Report 

Numberfield does not support name props, it is required for formvalidation

## 🤔 Expected Behavior

name field should be supported for Numberfield

## 😯 Current Behavior

Type '{ "aria-describedby": string; "data-id": string; onChange: (value: any) => void; name: string; value: number; isRequired: true; }' is not assignable to type 'IntrinsicAttributes & SpectrumNumberFieldProps & RefAttributes<FocusableRefValue<HTMLElement, HTMLElement>>'.
  Property 'name' does not exist on type 'IntrinsicAttributes & SpectrumNumberFieldProps & RefAttributes<FocusableRefValue<HTMLElement, HTMLElement>>'.ts(2322)

## 🔦 Context

We are trying to use final-form-focus library for moving focus to first field with error in react final form. For this library, we need to pass name prop to NumberField.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
Please see the discussion on https://github.com/adobe/react-spectrum/pull/2884
Closing as a duplicate
