### ISSUE TITLE
Dialog in Table closes when typing

### ISSUE THREAD

**Issue by mathieu-lessard** [adobe/react-spectrum#3957]
### Expected Behaviour
You can type in a Dialog in a Table.

### Actual Behaviour
Table's Row with the typed value is focused.

### Reproduce Scenario (including but not limited to)

1. Create a Table with Height value
2. Add Rows until the table has a scroll bar
3. Add a Dialog to Rows
4. Open a Dialog and type a letter which would focus outside of the currently viewable rows

#### Steps to Reproduce
https://codesandbox.io/s/react-spectrum-table-focus-yk8kq2?file=/src/App.tsx

Using the above link:
1. Make the window's height small enough so only "John Doe" rows are visible.
2. Click "Add" button"
3. Type any letter (Not "J").

#### Platform and Version
Tested in @adobe/react-spectrum 3.20 - 3.24.1
On Mac - Safari, Chome, Firefox
On Windows 10 - Edge, Chrome, Firefox

#### Sample Code that illustrates the problem
https://codesandbox.io/s/react-spectrum-table-focus-yk8kq2?file=/src/App.tsx

#### Logs taken while reproducing problem
N/A

**Comment by LFDanLu** [comment]
Thanks for catching this, looks like our [typeSelect](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/selection/src/useTypeSelect.ts#L83) is triggering while that dialog is open.

**Comment by jnurthen** [comment]
Note - I can reproduce this the following steps:
* run testcase
* click the + button on any of the rows to open the dialog
* shift+tab 2 times to get to the text field
* start typing
