### ISSUE TITLE
[useOverlay] Click Outside in Shadow-DOM context

### ISSUE THREAD

**Issue by tnovas** [adobe/react-spectrum#3970]
The callback `shouldCloseOnInteractOutside` in [useOverlay](https://github.com/adobe/react-spectrum/blob/f32367ad4a4639ccb8738b9daefe42d0d870affd/packages/%40react-aria/overlays/src/useOverlay.ts#L95) sends `event.target`, in Shadow-DOM context the `event.target` is Shadow-DOM and not the real point click, so, in this context the result is always click outside.
Could be changed to sends the `event` and not `event.target`?
This way we have more information like `event.composedPath()` and we check the real point click.

I look forward to your feedback.
Regards!

**Comment by LFDanLu** [comment]
Closing as dupe

**Comment by theomessin** [comment]
@LFDanLu instead of closing every Shadow DOM related ticket in favour of #1472 I think it might be best work incrementally and tackle issues one-by-one. #1472 has been around for 2 years and no progress has been made. #4526 addresses this particular issue.
