### ISSUE TITLE
TextField issue with diacritics not fully visible

### ISSUE THREAD

**Issue by enortonAtAdobe** [adobe/react-spectrum#3983]
# 🐛 Bug Report 

full diacritics not visible in TextField for some characters depending on the browser

## 🤔 Expected Behavior

full diacritics should be visible

## 😯 Current Behavior

<img width="294" alt="Screen Shot 2023-01-30 at 5 50 34 PM" src="https://user-images.githubusercontent.com/26984108/215640625-e90b0155-bfb4-4247-a942-29001069bf25.png">

## 💻 Code Sample

https://32w4px.csb.app/

## 🌍 Your Environment

this happens in some browsers but not others - mainly Firefox seems to be the only one to handle correctly

## 🧢 Your Company/Team

AEP

**Comment by snowystinger** [comment]
Looks like this might be font related.

I tried a TextField inside a Provider with the arabic locale, it's closer but the third line under that letter still seems cut off. https://codesandbox.io/s/broken-dust-8fscze?file=/src/App.js

It looks like this happens in native as well https://jsfiddle.net/pbw3L0kv/2/

Will bring up with our design, I tried changing the line-height and padding with partial luck. Changing the line-height rendered all the diacritic in the vertical space, but was still cut off in the horizontal.

<img width="199" alt="Screenshot 2023-01-31 at 10 29 04 AM" src="https://user-images.githubusercontent.com/698229/215821072-3b1838e5-dd96-4b1c-a32e-a901958045a6.png">

**Comment by snowystinger** [comment]
After a discussion with the team. We've realized that codesandbox is not part of our typekit provisioning, nor possibly is chromatic. As a result, the images we've been dealing with and example apps are not actually correct. We need to use an environment where we actually resolve to the correct font and see if this is still a problem there.

We have another issue, neither our docs site nor localhost appears to be provisioned for the Arabic Adobe font face

We also need to verify this against other accent marks that hang below the text baseline, such as the French `Ç`

**Comment by ktabors** [comment]
Adobe Arabic is sans-serif and we want a serif font for consistency, so we're using Myriad Arabic. The same for Hebrew. Spectrum CSS has made this change as well.

**Comment by snowystinger** [comment]
Here is a textfield in an Arabic locale provider with Arabic text, using Myriad Arabic. These screen shots were all generated from https://reactspectrum.blob.core.windows.net/reactspectrum/4a41f3b71c62796056043e36972fa7118f2a0e3e/storybook/index.html?path=/story/textfield--default&providerSwitcher-express=false
Steps:
1. Change locale in top bar
2. inspect dom element for input
3. replace label with text from this ticket
4. paste text from this ticket into field

FireFox - everything handled correctly
<img width="784" alt="Screenshot 2023-04-27 at 5 54 40 PM" src="https://user-images.githubusercontent.com/698229/235029162-6caec817-0daf-46d3-8b44-bf85315f3005.png">
<img width="1559" alt="Screenshot 2023-04-27 at 6 01 18 PM" src="https://user-images.githubusercontent.com/698229/235029710-057b8c96-af68-4388-9f68-b6d72628dab3.png">

Safari - field looks fine, but label arabic diacritic is cut off
<img width="454" alt="Screenshot 2023-04-27 at 6 04 50 PM" src="https://user-images.githubusercontent.com/698229/235030146-1130a0c2-b9e0-4156-ac5e-95b012fff4d7.png">
<img width="475" alt="Screenshot 2023-04-27 at 6 07 09 PM" src="https://user-images.githubusercontent.com/698229/235030263-13b9a792-b79b-4b17-b82d-ba04cd29587d.png">

Chrome - Arabic diacritic cut off in field
<img width="292" alt="Screenshot 2023-04-27 at 6 10 05 PM" src="https://user-images.githubusercontent.com/698229/235030620-7d086525-ede1-4850-adc0-6b7dbb4c88ca.png">
<img width="299" alt="Screenshot 2023-04-27 at 6 11 13 PM" src="https://user-images.githubusercontent.com/698229/235030725-71e00445-101e-4175-a18c-1243b4c147f9.png">
