### ISSUE TITLE
Fullscreen Dialog dismissable modal doesn't display close button in header

### ISSUE THREAD

**Issue by maslennikov** [adobe/react-spectrum#3984]
# 🐛 Bug Report 

Rendering a Dialog inside DialogContainer with `isDismissable` prop combined with `type="fullscreen" (or "fullscreenTakeover")` doesn't show a close button in header.

## 🤔 Expected Behavior
Dismiss button is visible when modal is fullscreen

## 😯 Current Behavior

Button element is being rendered in DOM (first screenshot) but its css prop `gridArea: closeButton` doesn't correspond to dialog content style (second screenshot). Close button appears when `type` prop is removed.

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/2033295/215721189-3cd7edf9-6b67-4fcb-b0ca-8bd1f9ea9f91.png">

<img width="418" alt="image" src="https://user-images.githubusercontent.com/2033295/215721633-7923e813-031e-4c40-9f44-7afb7e9510eb.png">

## 💻 Code Sample

```tsx
      <DialogContainer
        isDismissable
        type="fullscreen" // or type="fullscreenTakeover"
        onDismiss={() => setDisplayPreview(false)}
      >
        <Dialog isDismissable>
          <Heading>Dialog Title</Heading>
          <Content>
            <Text>Close Button not showing</Text>
          </Content>
        </Dialog>
      </DialogContainer>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.24.1
| Browser          | chrome Version 109.0.5414.87 (Official Build) (x86_64)
| Operating System | macOS 11.7.1

**Comment by snowystinger** [comment]
Thanks for the issue, in Spectrum's design system that isn't a valid combination. Instead, please use a `ButtonGroup` and provide your own close button.
See https://react-spectrum.adobe.com/react-spectrum/DialogTrigger.html#fullscreen and https://react-spectrum.adobe.com/react-spectrum/DialogContainer.html#dialog-triggered-by-a-menu-item for examples with this.
