### ISSUE TITLE
ColorField component in some cases is taking more than six characters on Android devices.

### ISSUE THREAD

**Issue by atakiyar** [adobe/react-spectrum#3985]
# 🐛 Bug Report 

In Android devices, the Color Field takes more than six characters in some cases. Like if the the color is #FFFFFF, we can add any number of characters after it. This is one such scenario.

## 🤔 Expected Behavior

The input box of color field should not accept more than six characters in any case.

## 😯 Current Behavior

![Screenshot_20230124-153059](https://user-images.githubusercontent.com/124043092/215735385-b8d6353f-1c47-484d-9b74-3520d4ba017e.png)

## 🔦 Context

This issue is causing problem for users as they can add non-hex color values as well which makes the website buggy.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | Latest
| Browser          | Chrome
| Operating System | Android

## 🧢 Your Company/Team

Adobe CC

**Comment by reidbarber** [comment]
Updated this to remove reference to an internal project. Reminder not to include internal links or screenshots on public Github.
