### ISSUE TITLE
link has no focus style on Safari on MacOS

### ISSUE THREAD

**Issue by jnurthen** [adobe/react-spectrum#3991]
# 🐛 Bug Report 

There is no focus style for links on Safari

## 🤔 Expected Behavior

It should be possible to tell which element has focus

## 😯 Current Behavior

Using https://react-spectrum.adobe.com/react-spectrum/Link.html tabbing to the links in the page shows no focus style.

https://user-images.githubusercontent.com/1724479/215899029-cb26abd2-9ca9-4001-9dd4-f99baf11d224.mov

## 💁 Possible Solution

Safari doesn't seem to support
```
text-decoration: underline double;
```

It does seem to support 
```
text-decoration-line: underline;
text-decoration-style: double;
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3
| Browser          | Safari 16.3
| Operating System | MacOS 13.2

**Comment by devongovett** [comment]
Appears Safari doesn't support the `text-decoration: double underline` shorthand, but does support `text-decoration-line: double`

**Comment by jnurthen** [comment]
I can resolve this by switching 
```
  &:focus-ring {
    text-decoration: underline;
    text-decoration-style: double;
  }
```
to
```
  &:focus-ring {
    text-decoration-line: underline;
    text-decoration-style: double;
  }
```
but I don't think we should have to as the base CSS seems like it should work to me. 
Is this a a parcel bug @devongovett ?

**Comment by devongovett** [comment]
Appears so. Filed https://github.com/parcel-bundler/lightningcss/issues/411

**Comment by LFDanLu** [comment]
Will need to do some followup work here when https://github.com/parcel-bundler/lightningcss/issues/411 is fixed

**Comment by dannify** [comment]
Need to update parcel lightning-css now that it is released.
