### ISSUE TITLE
Checkbox doc for Validation needs accessibility information adding

### ISSUE THREAD

**Issue by jnurthen** [adobe/react-spectrum#4002]
# 🙋 Documentation Request

Validation needs to make it clear that the error must also be indicated in text. The color change is not sufficient for certain color blind users or high contrast users.

**Comment by LFDanLu** [comment]
We will need to expose the HelpText component (or something like it) so users can add it to the Checkbox + update the api since the current one isn't what we wanna expose.

**Comment by snowystinger** [comment]
Guidance from Spectrum Design is that we should expose helptext to checkboxes similar to checkbox groups

**Comment by snowystinger** [comment]
What part of help text do we not want to expose?
