### ISSUE TITLE
make 'Key' type generic (eg. TKey) to enable branded-types preservation

### ISSUE THREAD

**Issue by dev-m1-macbook** [adobe/react-spectrum#4009]
# 🙋 Feature Request

## 🤔 Wanted Behavior
item branded-type to be preserved throughout automatically, without manual type-casting.

[some blogpost about branded types](https://dev.to/andercodes/typescript-tip-safer-functions-with-branded-types-14o4)
```
type CityIdType = string & { __CityIdType: null };
export type CityType = {
  id: CityIdType,
  ...
}

const cities = await getCities(...) // citys: of type CityType

const { ... } = useComboBox({
  items: cities,
  onSelectionChange(cityId) {
    // cityId's type is 'CityIdType' without casting
  }
}) 
```

## 😯 Current Behavior
```
const cities = await getCities(...) // citys: of type CityType from above

const { ... } = useComboBox({
  items: cities,
  onSelectionChange(cityId) {
    // cityId's type is React.Key type
    //   manual casting is do-able, but may introduce bugs
  }
}) 
```

## 💁 Possible Solution
Make 'Key' generic:

eg). 
```
export interface SingleSelectionState<TKey extends Key> extends FocusState<TKey> {
  /** Whether the collection allows empty selection. */
  readonly disallowEmptySelection?: boolean,
  /** The currently selected key in the collection. */
  readonly selectedKey: TKey,
  /** Sets the selected key in the collection. */
  setSelectedKey(key: TKey): void
}
```

btw, I just started working on this -- but it's quite a big work. This may result in big git-diffs, which can cause a lot of git conflicts for other contributers currently working on this project.

(and I'm welcome if someone else can do this instead 😪 )

## 🔦 Context

manual casting / non-branded-types can introduce bugs. On the other hand, with branded types, I can code confidently without worrying about passing around wrong stuff (eg. getCity( someVar.id ) where someVar is ScheduleType instead of CityType)

## 🧢 Your Company/Team
my github id for this work: [rencarKTR](https://github.com/rencarKTR)

**Comment by LFDanLu** [comment]
@dev-m1-macbook Thank you for looking into this! Since this seems to be quite the undertaking, would you like to open a pull applying this change to a single component/smaller scope if possible? That way we can evaluate the change and bring it into our own backlog

**Comment by dev-m1-macbook** [comment]
@LFDanLu sorry I gave up on this and moved on (no longer using react-aria)
 -- it seems that 'Key' is used everywhere, and I couldn't separate it out into smaller scope or introducing typescript-hacks into this project (which could be a big breaking change for older ts users)

minor issue: some 'keys' are actually constant-values (can be avoided by using literal-values as type)
bigger issue: some 'keys' are actually string-concatenation with user-given key value

the changes were like 2000+ lines, and I had other deadlines to meet 😢 

anyway, one easier way would be providing a wrapper d.ts file with correct generics, and ignoring all the internals of this lib
