### ISSUE TITLE
isFocusVisible should be false after the mouse moves

### ISSUE THREAD

**Issue by mitchellwarr** [adobe/react-spectrum#4031]
# 📝 Feedback

The isFocusVisible should be false if the user moves their mouse

## 🔦 Context

If a mouse using user types in an input, and then moves their mouse over something that shouldFocusOnHover, that item shows the focus ring. The focus ring can be confusing to primarily mouse using users since they don't normally see it.

**Comment by LFDanLu** [comment]
Mind sharing a codesandbox of your setup here? Our Spectrum components use `FocusRing`/`useFocusRing` to determine whether or not to display the focus style (`focusClass`/`isFocused`) vs the keyboard focus style (aka `focusRingClass`/`isFocusVisible`), maybe you could do something similar?

**Comment by yihuiliao** [comment]
Closing since stale. Feel free to reopen if you are still encountering issues.
