### ISSUE TITLE
DatePicker is setting time to default after selecting time for the first time

### ISSUE THREAD

**Issue by ishikagoel5628** [adobe/react-spectrum#4033]
# 🐛 Bug Report 

DatePicker is setting time to default after selecting time for the first time

## 🤔 Expected Behavior

Should set it to the time we selected using the DatePicker

## 😯 Current Behavior

After inserting the time and leaving the DatePicker, the time is set to the default one.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | "^3.19.0"
| Browser          | Chrome
| Operating System | Mac

## 🧢 Your Company/Team

 Adobe/Campaign

**Comment by ishikagoel5628** [comment]
![datepicker-bug](https://user-images.githubusercontent.com/47469060/217790617-c1353dac-f227-4fe3-a5d1-b78ecd74aac4.gif)

**Comment by devongovett** [comment]
To be clear this is specifically because you did not enter the AM/PM segment and left it as the placeholder.

**Comment by ishikagoel5628** [comment]
But it is little confusing right?

**Comment by devongovett** [comment]
Looks like it is already supposed to be the case that if the am/pm field is the only one not filled in, that we accept the placeholder. Maybe there is a bug causing that not to happen.

https://github.com/adobe/react-spectrum/blob/1f3dbd56b87c9f5adcdab63e81a6ee64b33314e6/packages/%40react-stately/datepicker/src/useDateFieldState.ts#L336-L343
