### ISSUE TITLE
ToggleButton: staticColor variant does not show change of state on hover in HCM 

### ISSUE THREAD

**Issue by dineshy87** [adobe/react-spectrum#4052]
# 🐛 Bug Report 

All variants of Togglebutton show Highlight color as border to reflect change of state from default state to hover state in high contrast mode. But the staticColor variants do not show any visible change of state in HCM.

## 🤔 Expected Behavior

The border for the staticColor variants of ToggleButton component should also use HighLight color in HCM to reflect change of state like other variants.

## 🔦 Context

https://user-images.githubusercontent.com/16927765/218561135-db52a8f2-e70a-4f65-9619-c73a358da187.mov

## 💻 Example
Issue can be observed on [Storybook](https://reactspectrum.blob.core.windows.net/reactspectrum/41e26fa0f01ee9ab6e5c21edf6f7bb5d498bf40f/storybook/index.html?path=/story/button-togglebutton--staticcolor-white&providerSwitcher-express=false&providerSwitcher-theme=darkest&providerSwitcher-toastPosition=bottom) and [react-spectrum docs](https://react-spectrum.adobe.com/react-spectrum/ToggleButton.html#static-color)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          | Edge 109 |
| Operating System | Windows |

If react-spectrum team needs access to https://assistivlabs.com/ to test WHCM, please let Adobe Accessibility team know. We can get you access.

**Comment by dannify** [comment]
Fixed in https://github.com/adobe/react-spectrum/pull/4803
