### ISSUE TITLE
ToggleButton: In light and lightest themes, on hover, text color is same as background color in HCM

### ISSUE THREAD

**Issue by dineshy87** [adobe/react-spectrum#4054]
# 🐛 Bug Report 

When the theme is set to light/lightest, and in High Contrast Mode, text color is changing to background color (becomes invisible) on mouse hover. This issue originates from ActionButton component and is therefore seen wherever ActionButton is used. (Like ToggleButton, ActionGroup etc).

## 🤔 Expected Behavior

On hover, text should still have the same 'ButtonText' color and only the border color should change to Highlight.

## 😯 Current Behavior

Text color is changing to background color on hover and therefore becomes invisible. 

https://user-images.githubusercontent.com/16927765/218563436-5dd27590-0887-4443-8f2f-242c8771cdb7.mov

## 💻 Example
Issue can be observed on [Storybook](https://reactspectrum.blob.core.windows.net/reactspectrum/41e26fa0f01ee9ab6e5c21edf6f7bb5d498bf40f/storybook/index.html?path=/story/button-togglebutton--default) and [react-spectrum docs](https://react-spectrum.adobe.com/react-spectrum/ToggleButton.html)

## 🌍 Your Environment

If react-spectrum team needs access to https://assistivlabs.com/ to test WHCM, please let Adobe Accessibility team know. We can get you access.

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          | Edge 109 |
| Operating System | Windows |

**Comment by LFDanLu** [comment]
@dineshy87 thank you for letting us know about https://assistivlabs.com/. Definitely interested in learning more, seems like a handy tool, should I reach out to you or the accessibility team directly?

**Comment by dineshy87** [comment]
This issue originates from ActionButton component and is therefore seen wherever ActionButton is used. (Like ToggleButton, ActionGroup etc)
