### ISSUE TITLE
Landmark: Inconsistent focus indicator styling between themes in HCM

### ISSUE THREAD

**Issue by dineshy87** [adobe/react-spectrum#4059]
# 🐛 Bug Report 

'Highlight' color must be used for outline to indicate focus across all themes in HCM. It seems like it is properly being used for light and lightest themes, but the dark and darkest themes are not using the Highlight color.

## 🤔 Expected Behavior

Focus styling is consistent across themes in HCM

## 😯 Current Behavior

https://user-images.githubusercontent.com/16927765/218604945-426cffcb-f5c8-4375-9620-542f0d33ad53.mov

## 💻 Example
Issue can be observed on [Storybook](https://reactspectrum.blob.core.windows.net/reactspectrum/41e26fa0f01ee9ab6e5c21edf6f7bb5d498bf40f/storybook/index.html?path=/story/landmark--flat-landmarks) using [Assistivlabs.com ](https://assistivlabs.com/) in Windows HCM. 

## 🌍 Your Environment

If react-spectrum team needs access to https://assistivlabs.com/ to test WHCM, please let Adobe Accessibility team know. We can get you access.

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          | Edge 109 |
| Operating System | Windows |

**Comment by snowystinger** [comment]
These stories are purely for testing movement, they aren't real landmarks.
Closing
