### ISSUE TITLE
Cannot dismiss an overlay using `Overlay` and `useModalOverlay` with `escape` key. 

### ISSUE THREAD

**Issue by benderham** [adobe/react-spectrum#4066]
# 🐛 Bug Report 

If following the documented example for [useModalOverlay](https://react-spectrum.adobe.com/react-aria/useModalOverlay.html), `escape` key dismiss only works if the child element of the Modal uses `useDialog`.
 
## 🤔 Expected Behavior

I should be able to dismiss a modal overlay using the `escape` key if `isDismissable` is `true`, and `isKeyboardDismissDisabled` is `false`.

## 😯 Current Behavior

Escape key dismiss works if the child element of the overlay (Modal) uses `useDialog`. If child element of the overlay is any other element the `escape` key dismiss is not respected. 

## 💻 Code Sample

[Code Sandbox](https://codesandbox.io/s/react-aria-usemodaloverlay-escape-key-bug-jrgm3m)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.22.0
| react-stately | 3.20.0
| Chrome | 109.0.5414.119
| Firefox Developer Edition | 111.0b1 (64-bit)
| MacOS | 13.1 (22C65)

**Comment by snowystinger** [comment]
This is expected. You should have a dialog as the child. Anything else would have a number of accessibility issues. The first sentence of the docs for useModalOverlay talks about how these hooks help cover the issues present with native dialogs.

**Comment by benderham** [comment]
Thank you for the quick response @snowystinger. Understood 🙃
