### ISSUE TITLE
useTreeData move does not allow moving into or within root

### ISSUE THREAD

**Issue by michaeldfoley** [adobe/react-spectrum#4074]
# 🐛 Bug Report 

The `move()` function from `useTreeData` can only move items to/within a parent item. The `insert()`, `append()`, and `prepend()` functions allow the user to specify `null` as the `parentKey` if they want to add an item to the root so I believe `move()` should follow that same pattern

## 🤔 Expected Behavior

There should be a way to move an item to or within the root of a tree created with `useTreeData`

## 😯 Current Behavior

There is no way to move an item to or within the root of a tree created with `useTreeData`

## 💁 Possible Solution

Passing `null` as the second argument to `move()` should move the item to the root, following the pattern established by `insert()`, `append()`, and `prepend()`. I'd be happy to submit a PR to fix this.

## 🔦 Context

Using this to create a nested drag-and-drop canvas and I need to be able to move items between the root and children

## 💻 Code Sample

```javascript
const tree = useTreeData({
  initialItems: [
    { 
      name: 'a', 
      items: [
        { name: 'b', items: [] }
      ] 
    },
    { 
      name: 'c', 
      items: [] 
    },
    { 
      name: 'd', 
      items: [
        { name: 'e', 
          items: [
            { name: 'f', items: [] }
          ] 
        }
      ] 
    }
  ],
  getKey: (item) => item.name,
  getChildren: (item) => item.items
});

tree.move('e', 'a', 0) // works as expected: moves item 'e' to the items array of item 'a'
tree.move('e', null, 0) // does not works as expected: I would expect this to move item 'e' to the root items array. instead the item is removed entirely. 
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-stately   | 3.20.0

**Comment by snowystinger** [comment]
Seems reasonable, would love a PR
