### ISSUE TITLE
live-announcer causing width overflow in mobile while using calendar hooks

### ISSUE THREAD

**Issue by wildcant** [adobe/react-spectrum#4086]
# 🐛 Bug Report 

Hi guys, first of all thank your work on this amazing library,
I've being working on a custom calendar component using the hooks from stately and aria packages and found this problem when interacting with the calendar grid cells the message in the live announcer would update and cause overflow in the page, this is mostly noticeable in mobile view. It seems this is similar to https://github.com/adobe/react-spectrum/issues/3791

## 🤔 Expected Behavior

The data-live-announcer should be completely invisible and should not affect the overflow behavior.

## 😯 Current Behavior

The data-live-announcer will grow in width till it pushes the width out of the body.

## 💁 Possible Solution

Seems to be a style fix similar to #3791 

## 🔦 Context

Here's an example of the current behavior

Range calendar initial state             |  Range calendar while state changes
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/48843517/219878767-e0052769-11aa-4e29-a7dc-5afd76845ab0.png)  |  ![image](https://user-images.githubusercontent.com/48843517/219878778-7bcefc2f-8aed-4284-aa7f-5803dbc0fa2c.png)

## 💻 Code Sample

Here's a code sandbox, it has the example from the [documentation](https://react-spectrum.adobe.com/react-aria/useRangeCalendar.html) on how to use the useRangeCalendar hook from react aria:
https://codesandbox.io/s/calendar-range-live-announcer-issue-seokij
<img width="1433" alt="Screenshot 2023-02-18 at 12 03 09 PM" src="https://user-images.githubusercontent.com/48843517/219879064-2f0bb087-9649-4b56-8d0a-9776b5845290.png">

**Comment by snowystinger** [comment]
is it causing horizontal scrolling for you? It's not doing anything for me in terms of page layout. I can see it extend out past the width, but it isn't causing any issues for me.

The possible solution cited was applied to both height and width, so I think something else will be needed.

**Comment by wildcant** [comment]
Yes it's affecting my layout, not a 100% sure why yet, my app is using next js 13 and tailwind, I'm guessing somewhere one of the two is applying some style making the problem more noticeable, here's a codesandbox with next js and tailwind where you can see this effect:
https://codesandbox.io/p/sandbox/calendar-range-live-announcer-issue-next-js-tailwind-5ilibw

In order to see the problem you'll have to open the preview in a new tab and toggle device toolbar, l like this:

|  Range calendar initial state  |   Range calendar while state changes   |
| ---------------- | ---------- |
| <img width="1440" alt="Screenshot 2023-02-19 at 12 21 22 PM" src="https://user-images.githubusercontent.com/48843517/219964004-6d720fc1-e8a1-4183-9aa5-003977618601.png"> | <img width="1440" alt="Screenshot 2023-02-19 at 12 19 34 PM" src="https://user-images.githubusercontent.com/48843517/219963985-0256671b-3bec-42b0-a3dc-c88dc72f315a.png">

I was able to fix the issue in my project with the following css
``` css
div[data-live-announcer='true'] {
  display: none;
}
```

but not sure if that would be an issue for accessibility or SEO?
just curious, what is the main purpose of the live announcer?
in terms of UI it seems to be working just fine for now

**Comment by snowystinger** [comment]
I think display none will negatively impact the iPhone VoiceOver or the Android TalkBack experience. Instead, maybe you can just set the width of the live-announcer or it's children to 1px for now? I'll try to find some time to try it out this week, but we are headed into a release, so I apologize if I'm a little slow getting back. If you want to try those out and make a PR, that'd be very helpful.

**Comment by filipw01** [comment]
Looks like it's fixed in react-aria 3.23.1. @wildcant can you try it out?
