### ISSUE TITLE
Unable to correct value in day segment on useDateField

### ISSUE THREAD

**Issue by lightwave** [adobe/react-spectrum#4087]
# 🐛 Bug Report 

useDateField broke on day segment. When first entered into the yyyy/mm/dd segment and type in 2023 12 31, it works. Now press backspace to delete 31 on the day segment. The dd placeholder should show. (Don't unfocus from the segment.) Enter 2, and 02 is displayed in the day segment.  Then type e.g., the digit 5, to finish entering day 25 of the month.  Expect 25 to be entered but instead, 05 is shown.  

## 🤔 Expected Behavior

Expect to be able to edit/correct day entered in the day segment.  e.g., enter 30, backspace backspace and enter 25.  25 should be the day but it's 05. 

## 😯 Current Behavior

When first entered into the yyyy/mm/dd segment and type in 2023 12 31, it works. Now press backspace to delete 31 on the day segment. The dd placeholder should show. (Don't unfocus from the segment.) Enter 2, and 02 is displayed in the day segment.  Then type e.g., the digit 5, to finish entering day 25 of the month.  Expect 25 to be entered but instead, 05 is shown.  

## 💁 Possible Solution

the problem is that the day segment as zero leading text in it.  A possible solution is not to normalized the text with leading zero until blur out of that segment.

## 🔦 Context

Use is expecting to be able to backspace to correct typo but it's currently impossible to do that.  If user move the focus to another control on the page and click back into the segment, then the user can enter the day again, but this "work-around" is discovered by accident and not how it's expected to behave.

## 💻 Code Sample

No need for a separate codesandbox.  The documentation page of useDateField has a datefield and you can reproduce the problem there.  https://react-spectrum.adobe.com/react-aria/useDateField.html#example

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/datepicker   | 3.2.1

**Comment by LFDanLu** [comment]
Is there a particular locale required to reproduce this? The docs for me are `mm/dd/yyyy` and don't reproduce the issue you describe here.

**Comment by lightwave** [comment]
The doc shows `yyyy-mm-dd` for me.  My Mac is set to Canada region which defaults to yyyy-mm-dd date format. For United States region, you can override the default date format to yyyy-mm-dd in MacOS system preferences Region setting.

Thanks

**Comment by LFDanLu** [comment]
Verified this locally with the Canada locale set in our storybook. Most likely something with this [onInput](https://github.com/adobe/react-spectrum/blob/3f3e83fdf970b3ca1ce57dbd15087d4985d3687e/packages/%40react-aria/datepicker/src/useDateSegment.ts#L176) is my initial thought, thanks for reporting!

**Comment by ryo-manba** [comment]
@snowystinger
Now that PR #5715 has been merged, this issue may be closed.

**Comment by LFDanLu** [comment]
ah good call, closing!
