### ISSUE TITLE
useComboBox incorrect popover positioning with virtual keyboards 

### ISSUE THREAD

**Issue by veiico** [adobe/react-spectrum#4088]
# 🐛 Bug Report 

When using useComboBox component on android phone, pressing the arrow icon opens up a popover dialog. But it also focuses the input, which brings up the native keyboard. This messes up the positioning of popover: content scrolls up, while popover stays in place, leaving it behind the keyboard.

Tried to find this bug in issues tab, but couldn't. If this is a duplicate - let me know. 

Affects iPad as well, see https://github.com/adobe/react-spectrum/issues/4283

## 🤔 Expected Behavior

Popover positioning should be updated after keyboard stops moving up

## 😯 Current Behavior

On useComboBox component arrow (to open popover) click - android keyboard shows up. But popover hides bellow it.

https://user-images.githubusercontent.com/10235669/220064240-f8e7f998-6da5-4cce-9394-908afd5a1bbc.mp4

## 💁 Possible Solution

Didn't find one

## 💻 Code Sample

Can be replicated on the documentation page. Snippet from there:
```
import {useButton, useComboBox, useFilter} from 'react-aria';
import {Item, useComboBoxState} from 'react-stately';

// Reuse the ListBox, Popover, and Button from your component library. See below for details.
import {Button, ListBox, Popover} from 'your-component-library';

function ComboBox(props) {
  // Setup filter function and state.
  let { contains } = useFilter({ sensitivity: 'base' });
  let state = useComboBoxState({ ...props, defaultFilter: contains });

  // Setup refs and get props for child elements.
  let buttonRef = React.useRef(null);
  let inputRef = React.useRef(null);
  let listBoxRef = React.useRef(null);
  let popoverRef = React.useRef(null);

  let { buttonProps, inputProps, listBoxProps, labelProps } = useComboBox(
    {
      ...props,
      inputRef,
      buttonRef,
      listBoxRef,
      popoverRef
    },
    state
  );

  return (
    <div style={{ display: 'inline-flex', flexDirection: 'column' }}>
      <label {...labelProps}>{props.label}</label>
      <div>
        <input
          {...inputProps}
          ref={inputRef}
          style={{
            height: 24,
            boxSizing: 'border-box',
            marginRight: 0,
            fontSize: 16
          }}
        />
        <Button
          {...buttonProps}
          buttonRef={buttonRef}
          style={{
            height: 24,
            marginLeft: 0
          }}
        >
          <span
            aria-hidden="true"
            style={{ padding: '0 2px' }}
          >
            ▼
          </span>
        </Button>
        {state.isOpen &&
          (
            <Popover
              state={state}
              triggerRef={inputRef}
              popoverRef={popoverRef}
              isNonModal
              placement="bottom start"
            >
              <ListBox
                {...listBoxProps}
                listBoxRef={listBoxRef}
                state={state}
              />
            </Popover>
          )}
      </div>
    </div>
  );
}

<ComboBox label="Favorite Animal">
  <Item key="red panda">Red Panda</Item>
  <Item key="cat">Cat</Item>
  <Item key="dog">Dog</Item>
  <Item key="aardvark">Aardvark</Item>
  <Item key="kangaroo">Kangaroo</Item>
  <Item key="snake">Snake</Item>
</ComboBox>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.22.0
| Browser | Android Chrome 110.0.5481.65
| Operating System | Android 13
| Android UI | One UI 5.0

**Comment by LFDanLu** [comment]
Reproduced locally. Seems to have started happening with https://github.com/adobe/react-spectrum/pull/3347, previously the popover positioned itself properly even after the virtual keyboard opened. Issue isn't resolved on the lasted changes on main with the updates to how we propagate the overlay styles in useOverlayPosition

**Comment by LFDanLu** [comment]
Note: occurs on iPad as well, see https://github.com/adobe/react-spectrum/issues/4283 for more details

**Comment by LFDanLu** [comment]
Fixed by https://github.com/adobe/react-spectrum/pull/4330
