### ISSUE TITLE
< TableBody /> top border being cut-off by <TableHeader />

### ISSUE THREAD

**Issue by rkdmen** [adobe/react-spectrum#4094]
# 🐛 Bug Report 

on `3.24.1` version, `.spectrum-Table-headWrapper_d0fc74 { margin-bottom: 1px } ` is causing TableHeader being shifted down and top-border is hidden. 

## 🤔 Expected Behavior
- Should show border on top
<img width="606" alt="image" src="https://user-images.githubusercontent.com/16869691/220485321-bd4b7f42-ac0b-470e-9205-0a37d8a31503.png">

## 😯 Current Behavior
- Border being cut-off
<img width="603" alt="image" src="https://user-images.githubusercontent.com/16869691/220485232-0def15ae-3b48-4c83-8a92-d68c507d725b.png">

## 💁 Possible Solution

Temporary solution suggested.
Using unsafe_classname,  on the tableview `.my-class-name * { box-sizing: unset; } `

## 💻 Code Sample

same issue can be viewed on `reactspectrum.blob...net/.../.../index.html` 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.24.1 |
| Browser          | Chrome stable (latest v.) |
| Operating System | MacOS Ventura 13.2 |

## 🧢 Your Company/Team

Adobe Commerce / Search & Merch

## 🕷 Tracking Issue (optional)

n/a

**Comment by snowystinger** [comment]
Clarifying a little, the margin causes an issue in conflict with a common CSS reset
```
* {
  box-sizing: border-box;
}
```

solution is for us to set the box-sizing we expect on the appropriate element. that way a CSS reset can't set it to something we don't expect
