### ISSUE TITLE
LogicButton: Disabled or variant is not using proper system colors in HCM

### ISSUE THREAD

**Issue by dineshy87** [adobe/react-spectrum#4099]
# 🐛 Bug Report 

Or variant when disabled, doesn't seem to use systems colors when in High Contrast Mode. See screenshot below. 

## 🤔 Expected Behavior

When disabled (across themes) :

Background color must use 'ButtonFace'
Border color must use 'GrayText'
Text color must use ''GrayText'

## 😯 Current Behavior

![LogicButton or variant when disabled isn't using the right high contrast colors ](https://user-images.githubusercontent.com/16927765/220717938-42fa8c71-f10a-4c9b-9cb7-095776a73063.png)

## 💁 Possible Solution

Needs following applied to appropriate selector:   

``` CSS
 --spectrum-logicbutton-or-background-color-disabled:ButtonFace;
 --spectrum-logicbutton-or-border-color-disabled: GrayText;
 --spectrum-logicbutton-or-text-color-disabled: GrayText;
```

## 🔦 Context

Issue can be observed on [Storybook](https://reactspectrum.blob.core.windows.net/reactspectrum/41e26fa0f01ee9ab6e5c21edf6f7bb5d498bf40f/storybook/index.html?path=/story/button-logicbutton--logic-variant-or&providerSwitcher-express=false&providerSwitcher-toastPosition=bottom) or [react-spectrum docs](https://react-spectrum.adobe.com/react-spectrum/LogicButton.html) or [chromatic](https://www.chromatic.com/component?appId=5f0dd5ad2b5fc10022a2e320&csfId=button-logicbutton--logic-variant-or&buildNumber=454&k=63f50211c92ed3657d97b4c5-1200-interactive-true&h=27&b=-5) while using Windows high contrast mode.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3|
| Browser          | Edge 109 |
| Operating System | Windows |

**Comment by ktabors** [comment]
It looks like #4092 fixed this except in dark and darkest modes.
