### ISSUE TITLE
ProgressBar/Meter: In HCM, fill color is not being picked from forced-colors media query

### ISSUE THREAD

**Issue by dineshy87** [adobe/react-spectrum#4105]
# 🐛 Bug Report 

System colors defined in forced-colors media query are not consistently applied for track and fill colors on ProgressBar across variants. Same is the case with Meter component. 

## 🤔 Expected Behavior

Following variables are present in the CSS but not consistently used. Make sure that for all variants including overBackground, track color is ButtonFace and fill color is ButtonText. 

```
--spectrum-barloader-large-track-fill-color: ButtonText;
--spectrum-barloader-large-track-color: ButtonFace;
```

![ProgressBar expected behavior](https://user-images.githubusercontent.com/16927765/220799154-3aa88c56-785f-482e-ba2a-de28db1403d5.png)

## 😯 Current Behavior

https://user-images.githubusercontent.com/16927765/220799134-616f41a2-92e8-4ce5-ab38-2eb7eacb2f98.mov

## 🔦 Context

Issue can be observed on the [docs](https://react-spectrum.adobe.com/react-spectrum/ProgressBar.html) and [storybook](https://reactspectrum.blob.core.windows.net/reactspectrum/41e26fa0f01ee9ab6e5c21edf6f7bb5d498bf40f/storybook/index.html?path=/story/progress-progressbar--default&providerSwitcher-express=false&providerSwitcher-toastPosition=bottom) while using Windows high contrast mode.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3|
| Browser          | Edge 109 |
| Operating System | Windows |

**Comment by LFDanLu** [comment]
In addition, Spectrum Design is making the value text required, we will need to update our docs and deprecate the showValueLabelProp. Maybe add a warning letting people know a label is required as well
