### ISSUE TITLE
Required to have `id` present on items passed to TableBody but not documented

### ISSUE THREAD

**Issue by JoachimKoenigslieb** [adobe/react-spectrum#4119]
# 🙋 Documentation Request
Hi, I'm trying to build some table components in Typescript. It seems that for rendering dynamic collections, I need to include an `id` on the items prop assed to `<TableBody>`. This is not described explicitly in the docs. I expected it to be around here: https://react-spectrum.adobe.com/react-aria/useTable.html#dynamic-collections.  

I also figure that the generic on `TableBody` should be something like 

```
export let TableBody: <T extends { id: number | string, }>(props: TableBodyProps<T>) => JSX.Element;
```

To make sure that Id is passed. Not passing Ids lead to a runtime crash, so this would be very nice to catch in the types instead. 

## 🧢 Joachim from Climaider

**Comment by LFDanLu** [comment]
Just to clarify, it isn't specifically that an `id` is required but more that you need a [unique key](https://react-spectrum.adobe.com/react-stately/collections.html#unique-keys). We link to those docs in the state management section of useTable, but we certainly can make that callout more clear. Open to any types updates to catch this as well, probably should be on all our collection components if possible.

**Comment by devongovett** [comment]
Hmm, not sure we can make type updates because it isn't required on the object itself. You can also set a `key` prop on the `<Row>`.

```jsx
<TableBody items={rows}>
  {(item) => <Row key={item.name}>{(columnKey) => <Cell>{item[columnKey]}</Cell>}</Row>}
</TableBody>
```

[Example](https://codesandbox.io/s/epic-jennings-uq5flm?file=/src/App.js)

**Comment by JoachimKoenigslieb** [comment]
> Just to clarify, it isn't specifically that an `id` is required but more that you need a [unique key](https://react-spectrum.adobe.com/react-stately/collections.html#unique-keys). We link to those docs in the state management section of useTable, but we certainly can make that callout more clear. Open to any types updates to catch this as well, probably should be on all our collection components if possible.

I see now! I guess I'm used to ignoring linters shouting at me for missing keys and never figured that this could be an issue causing the crash. I think adding this warning on "dynamic content" sections would make it a lot more beginner friendly.

> Hmm, not sure we can make type updates because it isn't required on the object itself. You can also set a `key` prop on the `<Row>`.
> 
> ```js
> <TableBody items={rows}>
>   {(item) => <Row key={item.name}>{(columnKey) => <Cell>{item[columnKey]}</Cell>}</Row>}
> </TableBody>
> ```
> 
> [Example](https://codesandbox.io/s/epic-jennings-uq5flm?file=/src/App.js)

I see. I think I'm still a little confused. 

Which components actually need a key/id? In the above the `<Cell>` component manages without one? I guess the problem is that if you enforced a requirement of `key` (or `id`) on `<Cell>` this would worsen ergonomics in the non-dynamic case as we would then not just depend on whatever React does for generating the key?

I think I can work around this by overriding types on my components which are then based on React-aria primitives.
