### ISSUE TITLE
Dialog popover loses focus when switching tabs in Chrome/FF

### ISSUE THREAD

**Issue by stepgould** [adobe/react-spectrum#4130]
# 🐛 Bug Report 

In Chrome, when clicking on another browser tab with https://react-spectrum.adobe.com/react-spectrum/DialogTrigger.html open, dialog closes. This is being used in Unified Shell for the Help Center.

## 🤔 Expected Behavior
When clicking on another browser tab then returning to the original tab, the dialog should remain open. 

## 😯 Current Behavior

The popover dialog is closed when returning to the original tab, losing any info that was in there.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
Either change https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/overlays/src/usePopover.ts#L80 so it isn't always true for specific cases (we'll want to preserve closeOnBlur for Menus/ComboBox/Picker) or detect this window changing scenario specifically
