### ISSUE TITLE
Grid/Flex: Add Accessibility section to inform users about things to take note of if they're using order property

### ISSUE THREAD

**Issue by dineshy87** [adobe/react-spectrum#4131]
# 🙋 Documentation Request

Can we add following text to Grid and Flex documentations. There is a link to [order property's MDN page](https://developer.mozilla.org/en-US/docs/Web/CSS/order) in the documentation but surfacing the accessibility concerns in react-spectrum documentation will be helpful.

### Accessibility 

Using the order property will create a disconnect between the visual presentation of content and DOM order. This will adversely affect users experiencing low vision navigating with the aid of assistive technology such as a screen reader. So, the key is to always begin with a DOM order that reflects the correct or intended reading order, and then to ensure that visual presentations  also convey that order.

**Comment by snowystinger** [comment]
I think this is covered by the official HTML docs about display grid/flex and we won't have these components in s2 anymore. So I'm going to close this.
