### ISSUE TITLE
TooltipTrigger. Add information to Accessibility documentation about users who will not be able to access Tooltip information.

### ISSUE THREAD

**Issue by jnurthen** [adobe/react-spectrum#4137]
# 🙋 Documentation Request

Add information to Accessibility documentation about users who will not be able to access Tooltip information. As tooltips are only triggered by focus or hover users who never focus/hover content will not have access to the tooltip. Screen reader users using the virtual cursor style navigation and Voice recognition users never focus the elements. Touch users on many devices also do not trigger tooltips.

**Comment by snowystinger** [comment]
I think we can consider this closed? https://react-spectrum.adobe.com/react-aria/Tooltip.html#accessibility Or if someone wants to copy that paragraph over to the RSP page?

**Comment by snowystinger** [comment]
closing, can reopen if there's more to do
