### ISSUE TITLE
Tabs: screen reader users perceive no distinction between horizontal and vertical orientation

### ISSUE THREAD

**Issue by majornista** [adobe/react-spectrum#4140]
# 🐛 Bug Report 

## 🤔 Expected Behavior

Since we can't rely on screen readers announcing the tablist orientation to determine whether to use ArrowUp/ArrowDown instead of ArrowLeft/ArrowRight. Both ArrowUp and ArrowLeft should work to navigate to the previous tab, and both ArrowDown and ArrowRight should work to navigate to the next tab.

## 😯 Current Behavior

With focus on a Tab, a screen reader user would have to guess the orientation to figure out which arrow keys will work to navigate to the next or previous Tab.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | [@adobe/react-spectrum@3.25.0](https://github.com/adobe/react-spectrum/releases/tag/%40adobe%2Freact-spectrum%403.25.0)
| Browser          | Chrome Version 110.0.5481.177 (Official Build) (arm64)
| Operating System | macOS Ventura 13.2.1 (22D68)

## 🧢 Your Company/Team

Adobe/Accessibility

**Comment by LFDanLu** [comment]
For whoever picks up this issue, see [here](https://github.com/adobe/react-spectrum/blob/101fd8f29dd031d84234060aecae3da718292eb7/packages/%40react-aria/tabs/src/TabsKeyboardDelegate.ts#L29-L63) for how we handle horizontal/vertical tab navigation. We'd want to change it so we'd return keys for Left/Right even if orientation is vertical and for Up/Down even if orientation is horizontal. Behavior would be similar to TagGroup which uses [ListKeyboardDelegate](https://github.com/adobe/react-spectrum/blob/101fd8f29dd031d84234060aecae3da718292eb7/packages/%40react-aria/selection/src/ListKeyboardDelegate.ts#L119-L133)

**Comment by LFDanLu** [comment]
Thanks, let us know if you have any questions!
