### ISSUE TITLE
SearchField ContextualHelp not appearing inline.

### ISSUE THREAD

**Issue by dsmmcken** [adobe/react-spectrum#4144]
# 🐛 Bug Report 

Appears in docs:
![image](https://user-images.githubusercontent.com/1576283/222473899-610d6e1e-5130-4212-8bc4-9542cfac1f42.png)

## 🤔 Expected Behavior

contextual help is rendered next to the label.

## 😯 Current Behavior

See docs for SearchField, and screenshot above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0
| Browser          | Chrome/Firefox
| Operating System | Windows

**Comment by reidbarber** [comment]
Looks like we should remove `display: inline-block` here so the field's `grid-template` gets applied:
https://github.com/adobe/react-spectrum/blob/cb1fc23c8f9efce828f774858aaf3a06a19b49a2/packages/%40adobe/spectrum-css-temp/components/search/index.css#L23-L24

**Comment by dsmmcken** [comment]
@reidbarber I opened a PR for this, not sure who is supposed to review it.

What I found odd was that it works fine in storybook as is, but not in any final build or in docs. Does storybook have a different asset import order?

**Comment by snowystinger** [comment]
Yes, docs load things incrementally. So it may have a different import order than storybook. Any website building with RSP could end up with a different order, so we need to approach this as a specificity issue in the CSS selector and resolve which rules should be applied such that this is deterministic and doesn't depend on order

**Comment by dsmmcken** [comment]
Got it, don't assume ordering. Removing `inline-block` to fix this such that it becomes `inline-grid` instead is still the correct fix I think though.
