### ISSUE TITLE
useOverlayTriggerState implementation prevents fulfillment of exhaustive dependencies.

### ISSUE THREAD

**Issue by aam051102** [adobe/react-spectrum#4153]
# 🐛 Bug Report 

The hook `useOverlayTriggerState` returns a new object (not controlled via state) every re-render, which means that the return value cannot be used as a dependency in `useEffect` hooks or similar, preventing the fulfillment of the recommended `react-hooks/eshaustive-deps` ESLint rule.

## 🤔 Expected Behavior

I expect `useOverlayTriggerState` to return a controlled object, so it can be used as a dependency without triggering an infinite loop.

## 😯 Current Behavior

As described, `useOverlayTriggerState` returns an uncontrolled object which, when used as a dependency in an effect, triggers an infinite loop upon re-render.

## 💁 Possible Solution

Modifying the implementation of `useOverlayTriggerState` to use a controlled object seems a reasonable solution, though I have no knowledge of the internals.

## 🔦 Context

I have a `useEffect`, which runs on component creation. It checks some cookies, runs `state.open()` conditionally, and finally sets a state. The state update causes a re-render, which causes `state` to update and since `state` is a dependency, it causes an infinite loop.

## 💻 Code Sample

```jsx
const MyComponent = () => {
  const state = useOverlayTriggerState({});
  const [myState, setMyState] = useState({});
  
  useEffect(() => {
    if(false) {
      state.open();
    }
    
    setMyState({ });
  }, [state]); // Fulfilling react-hooks/exhaustive-deps
  
  return <></>;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.23.1
| react-stately | 3.21.0
| Browser          | Chrome
| Operating System | Windows 11
| NextJS | 12.2.3

**Comment by snowystinger** [comment]
That would still have the potential to change more than you'd like. Instead, use state.open and state.isOpen etc in your dependency array. If that's still changing too frequently, we can check if we're memoing those properties.

**Comment by aam051102** [comment]
From what I can tell from [the implementation](https://github.com/adobe/react-spectrum/blob/cc158b410d11894fb2f14cc2732165dd91786036/packages/%40react-stately/overlays/src/useOverlayTriggerState.ts), `open()` is also defined on every re-render. As an aside, using `state.open` in the dependency array doesn't fulfill exhaustive-deps, though that may be a different, unrelated bug.

**Comment by snowystinger** [comment]
yeah, does look like it's redefined every render (was on my phone when I typed my reply earlier), but that's easy to fix if you wanted to submit a PR

```
  open: useCallback(() => {setOpen(true)}, [setOpen])
```

**Comment by snowystinger** [comment]
wrt using state.open, you'd need to pull it off the object, they can't do analysis of complex objects, so you'd really be doing something like this
```
  let open = state.open;
  
  useEffect(() => {
    if(false) {
      open();
    }
  }, [open]);
```

**Comment by aam051102** [comment]
In that case, I suppose all the functions should be memorized and not just open(). I will look at the other state hooks and see if I can come up with a performant solution.

**Comment by snowystinger** [comment]
Many of them are going to have the same issue. I think we're just going to address them as the need arises. So if you'd like to submit a PR for useOverlayTriggerState, that'd be great.

**Comment by aam051102** [comment]
I have created a pull request now. #4155. It should cover the discussion of this issue.
