### ISSUE TITLE
Regenerate CSS hashes when css file contents change to support micro-frontend envs that can have multiple versions of ReactSpectrum on the page

### ISSUE THREAD

**Issue by bkfarnsworth** [adobe/react-spectrum#4158]
# 🙋 Feature Request

It would be great if css classname hashes were regenerated when css file contents change. This would allow different versions of react spectrum to exist on the same page, which is a common occurrence for teams using a micro-frontend architecture.

See this video for more context on the issue:

https://drive.google.com/file/d/1ZyP_kG7euECAiXVHP_IAtDb0YJ4jNn9D/view?usp=sharing

## 🤔 Expected Behavior

If ever a css file is modified, all the classname hashes should be regenerated.  For example spectrum-InputGroup_a0942f should become spectrum-InputGroup_43def6

## 😯 Current Behavior

Currently, css hashes are only regenerated if the filename of the css file changes.

## 🔦 Context

See the video for a screen recording of how this issue manifested in our app:

https://drive.google.com/file/d/1ZyP_kG7euECAiXVHP_IAtDb0YJ4jNn9D/view?usp=sharing

## 🧢 Your Company/Team

Adobe Analytics

**Comment by devongovett** [comment]
Assigning myself to do the work in lightningcss.
