### ISSUE TITLE
IllustratedMessage uses Italics font-style for CCJK 

### ISSUE THREAD

**Issue by lreis** [adobe/react-spectrum#4165]
# 🐛 Bug Report 

The IllustratedMessage component applies Italics to its body text when using a Content child component, for all locales.

## 🤔 Expected Behavior

The Italics font-style is not used for CCJK, since that style is not appropriate in those languages.

## 😯 Current Behavior

The Italics font-style is used for CCJK.

![rspv3-illustrated-message-italics](https://user-images.githubusercontent.com/509658/223239863-40b23374-7189-46d9-982b-7987b3c0d2b9.png)

## 💁 Possible Solution

Investigate font handling for CCJK locales.

## 🔦 Context
See also https://github.com/adobe/react-spectrum/issues/4125

## 💻 Code Sample

[React-Spectrum v3 Storybook](https://reactspectrum.blob.core.windows.net/reactspectrum/641eeab6091ea9355e251b1535513f61cde09c76/storybook/index.html?path=/story/illustratedmessage--not-found&providerSwitcher-express=false&providerSwitcher-locale=ja-JP&providerSwitcher-toastPosition=bottom)

## 🧢 Your Company/Team

Adobe Localization

**Comment by LFDanLu** [comment]
Look into applying `font-synthesis: none` to get rid of the italics

**Comment by devongovett** [comment]
Maybe in here: https://github.com/adobe/react-spectrum/blob/main/packages/%40adobe/spectrum-css-temp/components/commons/fonts.css
