### ISSUE TITLE
Date range picker popover doesn't flip and disappears when not enough space

### ISSUE THREAD

**Issue by agusterodin** [adobe/react-spectrum#4172]
# 🐛 Bug Report 

The popover in date range picker implementation as shown in [these official examples](https://react-spectrum.adobe.com/react-aria/useDateRangePicker.html#styled-examples) disappears. This is despite having the popover `shouldFlip` property set to `true`.

## 🤔 Expected Behavior

When the popover no longer fits on the screen, the dialog should flip to above the input. If there is no space in either direction, the dialog should at least remain scrollable so application is usable.

## 😯 Current Behavior

Popover completely disappears when there isn't enough room on the screen despite the `shouldFlip` property set to `true`

https://user-images.githubusercontent.com/10248395/223537863-52989ad4-544a-458e-a4ee-c9d95e7133c6.mov

## 🔦 Context

Date picker popover doesn't show up on short desktop browser windows. Date picker popover also doesn't appear whatsoever on mobile devices due to screen size (tested on Google Pixel 6). 

## 💻 Code Sample

Present in official examples here https://react-spectrum.adobe.com/react-aria/useDateRangePicker.html#styled-examples

I can confirm that these issues are present even in the latest version of React ARIA (version number below).

## 🌍 Your Environment

react-aria: 3.23.1
Browser: Google Chrome 110.0.5481.177 (Official Build) (arm64)
Operating System: MacOS 13.2.1 (22D68)

## 🧢 Your Company/Team

CarbonReach

## 🕷 Tracking Issue (optional)

N/A

**Comment by THMKAE** [comment]
The custom Popover component, in both Tailwind or Chakra UI examples, uses a `top="100%"` or `top-full`, if you remove that, the positioning will work as expected.
