### ISSUE TITLE
Unexpected behavior with DateField auto tabbing

### ISSUE THREAD

**Issue by brynshanahan** [adobe/react-spectrum#4174]
# 🐛 Bug Report 

Cursors automatically tabs from Day -> Month before the user is "definitely" finished with the day segment.
Currently typing "1" into an empty Day segment will tab into the Month field when there is no month entered.

 I feel like I might be misunderstanding how the auto-tabbing works but this is not how I would imagine it working

## 🤔 Expected Behavior

For entry in Day Segment:
if empty and char <= "3" => cursor remains in Day segment
if empty char <= "2" and Month segment === Feb => cursor remains in Day segment
else tabs to Month segment

For entry in Month Segment
if empty and char <= "1" => cursor remains in Month segment
else tabs to Year segment

## 😯 Current Behavior

Cursor automatically tabs you into the next field if you have previously entered *any* content in the day segment
Resets after focusing on another segment of the DateField

eg. 
1. type "1" into Day segment  -> focus remains in Day
2. Backspace 
3. type "1" into Day segment again -> tabs to Month segment

If you tab to the Month segment and back to Day segment manually after step 2., step 3 will keep the users focused in the Day segment 

How it's currently setup if you delete what you had entered in the Day segment and then try and enter the Day "12" it will focus you all the way to the Year segment

Upon further inspection, the same issue happens when clearing the Month segment and typing "1" into the field (it will also tab you to the Year segment making it hard for users to enter months 10-12)

<details>
  <summary>Screen recording</summary>
<br/>

https://user-images.githubusercontent.com/37826020/223613481-1354c792-6145-4e89-b1ad-7ffb7ceb7ddc.mov
</details>

## 💁 Possible Solution

None given currently

## 🔦 Context

I'm looking to integrate the useDateField hook into our component library

## 💻 Code Sample

https://codesandbox.io/s/date-picker-comparisons-04c5ew?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
|   @adobe/react-spectrum  | 3.25.1
| Chrome          | 110.0.5481.177
| MacOS | 12.6.1 

## 🧢 Your Company/Team

NSW Gov (not using library yet)

**Comment by LFDanLu** [comment]
Looks like in certain locales (Canada (French), English (GB), etc), the `newValue` calculated [here](https://github.com/adobe/react-spectrum/blob/d6adfebbbf29339df5722778d2a81579a2622580/packages/%40react-aria/datepicker/src/useDateSegment.ts#L181) is `01` when the user types in `1`, passing [this check](https://github.com/adobe/react-spectrum/blob/d6adfebbbf29339df5722778d2a81579a2622580/packages/%40react-aria/datepicker/src/useDateSegment.ts#L246-L249) and thus focusing the next segment.

**Comment by danyo-moe** [comment]
Im from New Zealand where date format is dd/mm/yyyy. For me day only accepts one char when you clear it with backspace first. It should accept two chars when you clear using backspace before jumping to month 

![CleanShot 2023-06-20 at 15 19 35](https://github.com/adobe/react-spectrum/assets/132923714/4bac6fdb-3363-4ef5-8a88-3475f27aee9a)

**Comment by ryo-manba** [comment]
Hey @LFDanLu,

PR https://github.com/adobe/react-spectrum/pull/5715 has been merged. It seems like this issue should be resolved now. 
You can verify the behavior in the PR's [Storybook](https://reactspectrum.blob.core.windows.net/reactspectrum/b3cdfcf5127ebb8beaecc8b3b0248e9ac289a298/storybook/index.html?path=/story/date-and-time-datefield--default&providerSwitcher-express=false).


Cc: @danyo-moe @brynshanahan

**Comment by LFDanLu** [comment]
@ryo-manba Yup, thanks for letting me know, I'll close this out! @danyo-moe @brynshanahan keep in mind that this hasn't been released yet but will be in the next release (exact date still TBD unfortunately). Feel free to reopen if you run into any issues
