### ISSUE TITLE
DateField/useDateField doesn't accept leap day on initial input

### ISSUE THREAD

**Issue by josephnle** [adobe/react-spectrum#4181]
# 🐛 Bug Report 

`DateField`/`useDateField` does not accept "29" as a valid day value with month "02" when starting at an empty default value. This is only possible when the year is set to a leap year. 

## 🤔 Expected Behavior

For date format `mm/dd/yyyy`, user should be able to enter in `02` for `mm` then `29` for `dd` without having to set `yyyy` first.  e.g. `02/29/2008`.

## 😯 Current Behavior

1. Type in `02` for `mm`.
2. Press `2` then `9` and observe that the day gets set to `9` instead.
3. If `yyyy` is set to `2008` (or any leap year) then `29` is accepted. However, the user has to first enter the year which can be confusing.

## 💁 Possible Solution

Accept 2/29 as day on initial input. If a non-leap year is entered then set day to 2/28.

## 🔦 Context

I am currently building a date field within our design system using `useDateField`.

This is particularly annoying/confusing for those who have a leap birthday 😅

## 💻 Code Sample

Observable on the [React Spectrum docs](https://react-spectrum.adobe.com/react-spectrum/DateField.html).

![Recording 2023-03-08 at 14 59 03](https://user-images.githubusercontent.com/2822954/223870669-6be499aa-adf4-4c62-a719-d26107655b7e.gif)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-spectrum/datepicker   | 3.4.0 |
| Browser          | Chrome 110.0.5481.177 |
| Operating System | macOS 13.2.1

## 🧢 Your Company/Team

Persona

**Comment by devongovett** [comment]
I think this is the same issue as https://github.com/adobe/react-spectrum/issues/3256?

**Comment by danyo-moe** [comment]
Example from New Zealand with dd/mm/yy format using it at Ministry of Education.

![image](https://github.com/adobe/react-spectrum/assets/132923714/24d27b83-289c-4df3-ae02-a4357b5f3920)

**Comment by danyo-moe** [comment]
Example in New Zealand date format dd/mm/yyyy. Day changes from 29 to 28 when entering month. 

Using at Ministry of Education

![ezgif com-video-to-gif](https://github.com/adobe/react-spectrum/assets/132923714/7a645b32-fad7-465d-b938-3b503265cf45)

**Comment by devongovett** [comment]
closing as dup of #3256
