### ISSUE TITLE
useNumberField doesn't work in StrictMode

### ISSUE THREAD

**Issue by ibnumusyaffa** [adobe/react-spectrum#4193]
# 🐛 Bug Report 
`useNumberField` doesn't work in strictmode

## 💻 Code Sample

[https://stackblitz.com/edit/vitejs-vite-xc5npn?file=package.json](https://stackblitz.com/edit/vitejs-vite-xc5npn?file=package.json)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria |  3.23.1 
| react-stately |  3.21.0
| react     | 18.2.0
| react-dom     | 18.2.0

**Comment by reidbarber** [comment]
Thanks for filing! We have an open PR for this at https://github.com/adobe/react-spectrum/pull/4005.

I'm going to close this we have an umbrella issue for strict mode support at https://github.com/adobe/react-spectrum/issues/779
