### ISSUE TITLE
Wheel scroll behavior for NumberField is inverted on Windows

### ISSUE THREAD

**Issue by asyncore** [adobe/react-spectrum#4196]
# 🐛 Bug Report 

When a `NumberField` is active, scrolling down via the mouse wheel triggers the `increment` behavior, and scrolling up via the mouse wheel triggers the `decrement` behavior on Windows. On MacOS this could make sense as the scroll direction is inverted, but it's pretty counter-intuitive on Windows.

## 🤔 Expected Behavior

Scrolling up via the mouse wheel should increment the value, and scrolling down via the should decrement the value in the `NumberField` on Windows.

## 😯 Current Behavior

Scrolling up via the mouse wheel decrements the value, and scrolling down via the increments the value in the `NumberField` on Windows.

## 💁 Possible Solution

The behavior is defined in https://github.com/adobe/react-spectrum/blob/4a7576870d4dbe80cdbebba2043f593474ad6cb4/packages/%40react-aria/numberfield/src/useNumberField.ts#L142.

Perhaps, based on the `window.navigator.userAgent`,
For Mac platforms, the current behavior could be kept (`e.deltaY > 0` => `increment()`)
and for the other platforms (`e.deltaY < 0` => `increment()`)

Alternatively, the behavior can be inverted based on a flag in the `NumberField` or `NumberFieldState` props, so the caller would be in control.

## 🔦 Context

As a Windows user, I'm used to things going down when I scroll down, and going up when I scroll up.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.17 |
| Browser          | Chrome |
| Operating System | Windows |

**Comment by devongovett** [comment]
On my Mac, scrolling up increments, and scrolling down decrements (the opposite of scrolling). I just checked and the same thing happens on my Windows machine when using the trackpad. I don't have a hardware mouse to test with.

That said, in both cases it depends on an operating system setting that changes the scroll direction (in the Touchpad settings on Windows). We tried to match the default for this I believe. Unfortunately, browsers don't expose this setting so we cannot easily change our behavior based on it. You can find a Chromium bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=156551 and a spec bug here: https://github.com/w3c/uievents/issues/57
