### ISSUE TITLE
Picker component has focus trap on focusable label

### ISSUE THREAD

**Issue by holblin** [adobe/react-spectrum#4199]
# 🐛 Bug Report 

When using reversal focus on the Picker component, the focus is trapped on the picker if the picker label contains a focusable component.

## 🤔 Expected Behavior

The focus jumps to the focusable label.

## 😯 Current Behavior

The focus is lost and next reversal focus will move back to the picker

## 💁 Possible Solution

`TextArea` seems to not be impacted by that.

## 🔦 Context

The issue is affecting me because I have inside the label a tooltip for contextual help that need to be focusable.

## 💻 Code Sample

```
<TextArea label={<ActionButton>ABC</ActionButton>} />
<Picker label={<ActionButton>ABC</ActionButton>}>
  <Item>ABC</Item>
  <Item>DEF</Item>
</Picker> 
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Adobe/CJM/AO

**Comment by devongovett** [comment]
Can you use https://react-spectrum.adobe.com/react-spectrum/Picker.html#contextual-help? Ideally the label itself would not include focusable elements. The builtin contextual help support handles this already

**Comment by holblin** [comment]
This works for me using the built-in contextual help. Sorry that I missed that in the documentation.
Thanks a lot!
