### ISSUE TITLE
`isRequired` prop on `useCheckbox()` does not set the input `required` prop

### ISSUE THREAD

**Issue by jvzaniolo** [adobe/react-spectrum#4223]
# 🐛 Bug Report 

I'm writing a checkbox component for my company's Design System, and I noticed that when setting the `isRequired` prop to `true` does not set the input `required` property. It only sets `aria-required` to `"true"`

## 🤔 Expected Behavior

The checkbox input `required` prop should be set to the component `isRequired` prop value

## 😯 Current Behavior

The checkbox input only receives `aria-required="true"`

## 💁 Possible Solution

`function useCheckbox() { return { inputProps: { ...inputProps, required: props.isRequired }}}`

## 💻 Code Sample

```tsx
function Checkbox(props: AriaCheckboxProps) {
  const ref = React.useRef<HTMLInputElement>(null)
  const state = useToggleState(props)
  const { inputProps } = useCheckbox(props, state, ref)

  return (
    <label>
      <input
        ref={ref}
        {...inputProps}
      />
      {props.children}
    </label>
  )
}

<Checkbox isRequired>Label</Checkbox>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria | 3.23.1 |

**Comment by snowystinger** [comment]
Dupe: see https://github.com/adobe/react-spectrum/issues/2123
