### ISSUE TITLE
TagGroup loses focus to document.body after removing only visible Tag with other collapsed Tags remaining 

### ISSUE THREAD

**Issue by majornista** [adobe/react-spectrum#4224]
# 🐛 Bug Report 
[TagGroup: maxRows + onRemove Storybook example](https://reactspectrum.blob.core.windows.net/reactspectrum/6f3de95401691820e26d05cc6243b325f91079d3/storybook/index.html?path=/story/taggroup--max-rows-on-remove&providerSwitcher-express=false) initializes with one visible Tag, reading "Cool Tag 1" and a button reading "Show All (6)." If a user moves keyboard focus to the Tag and presses delete to remove that Tag, the TagGroup redraws to show two of the previously hidden Tags, "Another cool tag" and "This tag", and the "Show All (5)" button.

## 🤔 Expected Behavior

After removing the first Tag, focus should restore to the first Tag in the TagGroup.

## 😯 Current Behavior

Focus is lost to the `document.body`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | @adobe/react-spectrum@3.25.1
| Browser          | Google Chrome Version 111.0.5563.64 (Official Build) (arm64)
| Operating System | macOS Ventura 13.2.1 (22D68)

## 🧢 Your Company/Team

Adobe/Accessibility

## 🕷 Tracking Issue (optional)

A11Y-5870

**Comment by LFDanLu** [comment]
Just a fyi, this work is being handled this sprint by @reidbarber. cc @reidbarber so you can link your PR to this when ready.

**Comment by reidbarber** [comment]
This was fixed by https://github.com/adobe/react-spectrum/pull/4358
