### ISSUE TITLE
The Picker and ComboBox example in the document doesn't work

### ISSUE THREAD

**Issue by vimcaw** [adobe/react-spectrum#4228]
# 🐛 Bug Report 

I just paste code from documents, and it doesn't work, the items don't show.

![CleanShot 2023-03-19 at 00 17 12@2x](https://user-images.githubusercontent.com/21964227/226118743-681463f1-c67f-4a0c-be52-dd05c51957a0.png)

![CleanShot 2023-03-19 at 00 17 30@2x](https://user-images.githubusercontent.com/21964227/226118755-a08b3411-419b-473e-a86a-c43c793df76e.png)

![CleanShot 2023-03-19 at 00 15 52@2x](https://user-images.githubusercontent.com/21964227/226118714-84fb8bef-e0d2-4e8a-a0cb-3395f65c8d0e.png)

## 🤔 Expected Behavior

The items of `Picker` and `ComboBox` display normally as same as the document.

## 😯 Current Behavior

The items of `Picker` and `ComboBox` are gone.

## 💁 Possible Solution

None.

## 🔦 Context

I just want both components work normally.

## 💻 Code Sample

https://codesandbox.io/s/react-spectrum-bug-io42gg?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.25.1 |
| Browser          | Chrome 111.0.5563.64 |
| Operating System | macOS 13.2.1 (22D68) |

## 🧢 Your Company/Team

It's my personal project.

## 🕷 Tracking Issue (optional)

None.

**Comment by devongovett** [comment]
For now, remove `<StrictMode>` from index.js. We are working on support for it: #779.
