### ISSUE TITLE
[Toast] exiting attribute should apply to the target on close

### ISSUE THREAD

**Issue by siriwatknp** [adobe/react-spectrum#4244]
# 🐛 Bug Report 

The `exiting` does not apply to the target on close

## 🤔 Expected Behavior

The `exiting` always applies to the first element of the region

## 😯 Current Behavior

When remove any element, the first element always get the `exiting` attribute.

https://user-images.githubusercontent.com/18292247/227089618-07cb9cdb-bf88-4ea0-bc63-6b3b1f6e1b24.mov

https://codesandbox.io/s/snackbar-joy-ui-feat-react-aria-gme1rg?file=/JoySnackbar.tsx

## 🔦 Context

I'm integrating `useToast` from React Aria with [Joy UI Alert](https://mui.com/joy-ui/react-alert/). All of the code I got from the official React Aria website.

## 💻 Code Sample

Take a look at the CodeSandbox above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by marinalazarova** [comment]
I'm experiencing this as well. I believe it's because of the way the toasts are being sorted by priority here:
https://github.com/adobe/react-spectrum/blob/d677c31d7b4dd34641c1b8f809863ee1a735607c/packages/%40react-stately/toast/src/useToastState.ts#L172-L176

**Comment by marinalazarova** [comment]
**UPDATE:**

I was able to "fix" this by extending the `ToastQueue` class and overriding the `add` method to always set the highest priority for newly added toasts. I'm posting the workaround here for anyone who needs this:

```typescript
class CustomToastQueue<T> extends ToastQueue<T> {
  add(content: T, options?: any) {
    return super.add(content, {
      ...options,
      // We need to access the private `queue` property to get the length
      // of the queue, which is used as the priority of the newly added toast.
      // We could use the `visibleToasts` property, but that would only give
      // us the length of the visible toasts, not the total length of the queue.
      // This is only a workaround until the following bug is fixed:
      // @see https://github.com/adobe/react-spectrum/issues/4244
      // @ts-ignore
      priority: (this.queue as QueuedToast<T>[]).length,
    });
  }
}
``` 

Then, you can instantiate your toast queue like this:
```typescript
const toastQueue = new CustomToastQueue<ToastContent>({
  maxVisibleToasts: 3,
  hasExitAnimation: true,
});
```

**Comment by LFDanLu** [comment]
Will have to discuss this use case with the team. As noted, we sort via priority as defined [here](https://spectrum.adobe.com/page/toast/#Priority-queue) but this is Spectrum specific logic and the hooks should probably have a way to opt out of this logic IMO.
