### ISSUE TITLE
Toast doesn't disappears sometimes even if persist is set to false

### ISSUE THREAD

**Issue by janvis1** [adobe/react-spectrum#4277]
# 🐛 Bug Report 

Toast doesn't disappears sometimes even if persist is set to false

## 🤔 Expected Behavior

The toast should disappear automatically if the persist is set to false.

## 😯 Current Behavior

When i click on the start/stop button under CC then two toasts pop up on the screen. If i wait them to disappear and then click again on start/stop button then it works fine but if i continuously click on start/stop button without waiting for earlier toasts to disappear then some of them remains on the screen i.e. doesn't disappears.

## 🔦 Context

An end user can click on start/stop button multiple times so the toasts should disappear automatically otherwise it will stack up on the screen disturbing the UI.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 
| Browser          |  Chrome
| Operating System | MacOS

## 🧢 Your Company/Team

Adobe/Connect

**Comment by reidbarber** [comment]
This appears to be for React Spectrum v2. This repo is v3, please refer internally for information on v2. Toast v3 docs can be found here: https://react-spectrum.adobe.com/react-spectrum/Toast.html
