### ISSUE TITLE
[useDateField] [react-aria] not selecting correct locale 

### ISSUE THREAD

**Issue by PixeledCode** [adobe/react-spectrum#4280]
# 🐛 Bug Report 

`useDateField` in Mozilla Firefox keeps using the Gregorian calendar, displaying the field in `mm/dd/yyyy` where it should be `dd/mm/yyyy` based on my locale.

## 🤔 Expected Behavior

According to this: https://react-spectrum.adobe.com/react-aria/useDateField.html#international-calendars, it should show it automatically, but I have to specifically use `I18nProvider locale="hi-IN-u-ca-indian"` to make it work

## 😯 Current Behavior

I am unsure how to show it since it is based on the user's location, but it is showing the wrong locale for the date field. It's working properly in Chrome and Safari but not in Firefox

## 🔦 Context

I am based in India, and people are familiar with date fields in the `dd/mm/yyyy` format. 

## 💻 Code Sample

https://codesandbox.io/s/modern-hooks-9nlyud?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   |  3.22.0
| Browser          | Firefox
| Operating System | MacOS

**Comment by devongovett** [comment]
By default we use `navigator.language` to determine the locale. What does that return for you? If it is returning `hi-IN`, then the formatting should be as you expect:

```js
new Intl.DateTimeFormat('hi-IN').format(new Date())
// => "29/3/2023"
```

In addition, the default calendar system for `hi-IN` appears to be Gregorian:

```js
new Intl.DateTimeFormat('hi-IN').resolvedOptions().calendar === 'gregory'
```

You can see in Unicode CLDR [here](https://github.com/unicode-org/cldr/blob/22af90ae3bb04263f651323ce3d9a71747a75ffb/common/supplemental/supplementalData.xml#L4649-L4664) where that is defined. So that would explain why you needed to add `-u-ca-indian` to get the Indian calendar system as well.

**Comment by PixeledCode** [comment]
I guess its a browser issue. `navigator.language` has different returns on different browsers:
Firefox - `en-US`
Chrome - `en-GB`
Safari - `en-IN`

**Comment by Tyris** [comment]
I don't think using `navigator.language` is correct. I'm on a Mac in Australia, and Firefox is defaulting to `en-US` despite my OS locale being set to `en-AU`. Firefox doesn't even have an option for `en-AU`, at best I can choose `en-GB`. It shouldn't be up to the end-user to figure out that they need to set Firefox to `en-GB` (or something else) to make a date input work correctly (note that other date field libraries seem to use the correct locale, including the build in `<input type="date" />` one in Firefox).

Instead I we should use the `locale` value from `Intl` using `Intl.DateTimeFormat().resolvedOptions().locale`
<img width="1092" height="89" alt="Image" src="https://github.com/user-attachments/assets/a05f85f0-b345-4f27-8dff-8c14086ca706" />
