### ISSUE TITLE
Combobox menu on iPad is not displayed

### ISSUE THREAD

**Issue by bdow** [adobe/react-spectrum#4283]
# 🐛 Bug Report 
Combobox's menu on iPad is not displayed. Maybe just incorrectly positioned?

## 🤔 Expected Behavior
The Menu/Popover should still be available for the user to see the options.

## 😯 Current Behavior
On an iPad, the Menu/Popover for a Combobox is missing (or misplaced) when the keyboard is displayed at full screen. 
See video for example:
https://user-images.githubusercontent.com/1143861/228600903-e11ca5dc-34cd-41e7-b1b8-c89ae11e5dc8.mov

## 🔦 Context

Our users are having issues with the combobox component on their ipads, making it not usable. I have directed them to try not to use the full screen keyboard on their iPad in hopes that it will position itself correctly then.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  latest (or whichever is used on the website)
| Browser          | Safari 16
| Operating System | iOS 16

## 🧢 Your Company/Team

[Homebound](https://www.homebound.com/) (we use React-Aria / Stately for building our own Design system)

**Comment by LFDanLu** [comment]
Seems like the same issue as https://github.com/adobe/react-spectrum/issues/4088, gonna close this one and change 4088 to cover both issues
