### ISSUE TITLE
useOverlayPosition enforces styles directly 

### ISSUE THREAD

**Issue by dnaploszek** [adobe/react-spectrum#4304]
# 🐛 Bug Report 
`useOverlayPosition` started to enforce styles directly on the ref [here](https://github.com/adobe/react-spectrum/blob/83677f94489fdfa535fd511157f5292ad80b7b09/packages/%40react-aria/overlays/src/useOverlayPosition.ts#L147-L150). Is there any way to prevent this from happening? 

## 🤔 Expected Behavior
Being able to apply the styles conditionally depending on the variant of the popover.

## 😯 Current Behavior
Previously we had an ability to set the position styles on any node we wanted, now we're forced to have the styles applied directly to the node that ref we pass into `usePopover` (which then goes to the `useOverlayPosition`

## 💁 Possible Solution
Easiest way would be to add a prop that allows to omit the direct application of styles in `useOverlayPosition` [applied here](https://github.com/adobe/react-spectrum/blob/83677f94489fdfa535fd511157f5292ad80b7b09/packages/%40react-aria/overlays/src/useOverlayPosition.ts#L147-L150). But I'm sure there could be an easier / better solution?

## 🔦 Context
We're using `usePopover` to create our popover which comes in a couple of different shapes. Our dropdown changes from a regular popover into an action sheet on mobile, so we were applying the popover styles conditionally depending on the screen width. Now the styles are applied directly without any way to omit/override them.

## 💻 Code Sample
https://github.com/adobe/react-spectrum/blob/83677f94489fdfa535fd511157f5292ad80b7b09/packages/%40react-aria/overlays/src/useOverlayPosition.ts#L147-L150
These set of lines are problematic for us

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria | 3.23.1 |
| Browser          | Chrome |
| Operating System | MacOS |

## 🧢 Your Company/Team
Not affiliated with Adobe

**Comment by LFDanLu** [comment]
Unfortunately, there isn't a way to prevent this from happening at the moment. Could you instead render a different component for mobile instead of reusing the same Popover? For some of our components (Dialogs, ComboBox, etc) we render a Tray that uses `useModalOverlay` instead for these cases.

**Comment by dnaploszek** [comment]
We've quite a strong rule of not using javascript to change DOM nodes for responsiveness - we want to handle these via media queries (which we were able to do with the previous approach). I'll not bump the version for now, but I would love to hear back if it could be avoided in the future 🙏🏻
