### ISSUE TITLE
onBlur / onFocus usage with useDateField

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#4324]
### Discussed in https://github.com/adobe/react-spectrum/discussions/4292

<div type='discussions-op-text'>

<sup>Originally posted by **jake-chapman-mark43** March 30, 2023</sup>
We have someone using our DateInput and DateRate which uses the associated spectrum hooks. Spreading `{...fieldProps}` onto `DateField` which is passing all props into appropriate hooks. We've noticed that majority of default event handlers like `onBlur` `onFocus` etc all get stripped. At first I thought it was a prop spreading issue. But after some logical thinking and working on it I realized it kind of made sense since there are no "text inputs" per say, but we do have editable segments that do receive `onFocus` and `onBlur` events. I can add these manually to `<segment>` but they are fired off for each individual segment of the component being showed based on props.

They're needing to save the value to the database when the user has selected a date, what's an appropriate way to handle `onBlur` for something like DateInput/DateRange since there isn't a 'single' event for those but will be firing off multiple times?</div>

**Comment by LFDanLu** [comment]
No longer reproduces with the latest version
