### ISSUE TITLE
Shift+Tab focuses last radio in group

### ISSUE THREAD

**Issue by robphoenix** [adobe/react-spectrum#4329]
# 🐛 Bug Report 

According to [WAI-ARIA](https://www.w3.org/WAI/ARIA/apg/patterns/radio/)  Shift+Tab should focus the first radio button in a group.

> If none of the radio buttons are checked, focus is set on the first radio button in the group.

However, when using `useRadioGroup`, it is the last Radio button which is focused. The ARIA docs above do make note of this possibility;

> The initial focus behavior described above differs slightly from the behavior provided by some browsers for native HTML radio groups. In some browsers, if none of the radio buttons are selected, moving focus into the radio group with Shift+Tab will place focus on the last radio button instead of the first radio button.

I believe it is because when all radio buttons are unchecked they all have `tabindex="0"`. Should it be that in this circumstance the first radio button should have `tabindex="-1"`?

## 🤔 Expected Behavior

Shift+Tab should focus the first radio button in a group if all radio buttons are unchecked.

## 😯 Current Behavior

Shift+Tab focuses the last radio button in a group if all radio buttons are unchecked.

## 💁 Possible Solution

Set `tabindex="-1"` on the first radio button in a group if all radio buttons are unchecked.

## 🔦 Context

I think this causes the radio group to not be as accessible as it should be?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by devongovett** [comment]
Shift tab going to the last radio seems to be how native radio buttons work. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

**Comment by robphoenix** [comment]
Yes, the ARIA docs acknowledge that this is how some native browsers work, but that the ARIA expectations are different.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/9257284/229830711-b9349792-1f7c-455e-835a-0fc58f750ee8.png">

<img width="912" alt="image" src="https://user-images.githubusercontent.com/9257284/229830869-e61507ec-6c83-4247-9503-fb0f739c0449.png">

**Comment by devongovett** [comment]
Hmm, I'm not sure that one is more correct than another. Keep in mind that ARIA Authoring Practices Guide is not a spec that must be adhered to, just a set of examples. Is there a strong reason for overriding the native behavior? Users may have come to expect it.

**Comment by robphoenix** [comment]
Ok, thanks @devongovett 
There's no strong reason to override the native behaviour, I just came across this conflicting information and wanted to clarify the behaviour was as expected.
