### ISSUE TITLE
Tooltip arrow placement not correct

### ISSUE THREAD

**Issue by MartinDawson** [adobe/react-spectrum#4343]
Tooltip placement accepts these props:

```ts
  /**
   * The placement of the element with respect to its anchor element.
   * @default 'top'
   */
  placement?: 'start' | 'end' | 'right' | 'left' | 'top' | 'bottom',
```

Modify Tooltip.stories.ts to have these args:

```ts
  placement: {
    control: 'radio',
    options: [
      'start', 'end', 'right', 'left', 'top', 'bottom'
    ]
  },
```

Arrow icon is not correct:

![Screenshot from 2023-04-06 13-37-05](https://user-images.githubusercontent.com/15030491/230380669-575dce6f-02d7-4515-95bf-1c7b08d8c993.png)

Also, react-aria supports these placements:

```ts
export type Placement = 'bottom' | 'bottom left' | 'bottom right' | 'bottom start' | 'bottom end' |
    'top' | 'top left' | 'top right' | 'top start' | 'top end' |
    'left' | 'left top' | 'left bottom' | 'start' | 'start top' | 'start bottom' |
    'right' | 'right top' | 'right bottom' | 'end' | 'end top' | 'end bottom';
```

And I see it's in the css of react-spectrum but none of the css is correct apart from for `bottom`, `top`, `right`, `left`.

**Comment by LFDanLu** [comment]
The tooltip's arrow's cross positioning is typically set by TooltipTrigger so those extra placement values are handled there. What use case do you have where you are using Tooltip on its own?
