### ISSUE TITLE
Button `onPress` doesn't work using keyboard if `onKeyUp` is passed

### ISSUE THREAD

**Issue by ritz078** [adobe/react-spectrum#4350]
# 🐛 Bug Report 

While using `useButton`, if you pass `onKeyUp` as props, `onPress` callback doesn't fire on clicking `Enter` or `Space` keys

## 🤔 Expected Behavior

`onPress` should work independent of `onKeyUp`
## 😯 Current Behavior

Accessibility breaks when keyboard event callbacks are passed. Here is a codesandbox. https://codesandbox.io/s/hopeful-gagarin-up2fc4?file=/src/App.js

## 🔦 Context

I am building a design system on storybook. Storybook automatically detects props that accept callbacks and passes one so that it can log all the callback responses. So this way the component broke as `onPress` never worked with keyboard. This is how I found out about this bug. 

## 💻 Code Sample

https://codesandbox.io/s/hopeful-gagarin-up2fc4?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.24.0
| Browser  | Chrome
| Operating System | MacOS

**Comment by LFDanLu** [comment]
Looks like onPress and onKeyDown are being called on Enter/Space in your attached code sandbox. What version are you running with locally?

**Comment by ritz078** [comment]
@LFDanLu Sorry. I have updated the issue. This only happens when we use `onKeyUp`.

**Comment by KelvinOm** [comment]
Also, if `onKeyUp` is passed, then `is-active` class stops working.
