### ISSUE TITLE
Very large size bundle size (80KB+) with only Button element (react-aria-components)

### ISSUE THREAD

**Issue by eashish93** [adobe/react-spectrum#4356]
# 📝 Feedback

I'm just tried react-aria-components on a fresh next.js app and by just importing only the button component, bundle size increased by 80KB+. This is not the case with react-aria hooks version.
- 
<img width="533" alt="Screenshot 2023-04-10 at 7 10 03 PM" src="https://user-images.githubusercontent.com/13780952/230912287-e6ec66fd-6624-43e8-83d0-bb121de27ffd.png">

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| [Package name]   | react-aria-components
| Browser          | Chrome 111
| Operating System | Mac OS 12.6.3

**Comment by devongovett** [comment]
Appears to be something wrong with the tree shaking. In the build output some of the components get their forwardRef compiled like this:

```js
const $778035c5624f61e7$export$2dc68d50d56fbbd = (0, $dGqE5$forwardRef)($778035c5624f61e7$var$Breadcrumbs);
```

This should have a PURE annotation so the minifier can remove it:

```js
const $778035c5624f61e7$export$2dc68d50d56fbbd = /*#__PURE__*/ (0, $dGqE5$forwardRef)($778035c5624f61e7$var$Breadcrumbs);
```

Some of them have this and some don't. I tried manually adding them and it reduced the bundle size a lot.

**Comment by devongovett** [comment]
Appears to be something wrong with the tree shaking. In the build output some of the components get their forwardRef compiled like this:

```js
const $778035c5624f61e7$export$2dc68d50d56fbbd = (0, $dGqE5$forwardRef)($778035c5624f61e7$var$Breadcrumbs);
```

This should have a PURE annotation so the minifier can remove it:

```js
const $778035c5624f61e7$export$2dc68d50d56fbbd = /*#__PURE__*/ (0, $dGqE5$forwardRef)($778035c5624f61e7$var$Breadcrumbs);
```

Some of them have this and some don't. I tried manually adding them and it reduced the bundle size a lot.

**Comment by devongovett** [comment]
After fixing that, there is another bug in the SWC minifier used by Next.js, where PURE annotations on forwardRef calls with a sequence expression (e.g. `(0, $dGqE5$forwardRef)`) are not removed properly. Disabling the `swcMinify` option in `next.config.js` seems to fix that one. I filed an issue here: https://github.com/swc-project/swc/issues/7241

**Comment by eashish93** [comment]
I tried with `swcMinify` disabled in fresh next.js app and without `app` folder. Getting almost same result.
<img width="609" alt="Screenshot 2023-04-10 at 11 22 00 PM" src="https://user-images.githubusercontent.com/13780952/230961261-af28705d-1f59-4424-a87b-6b736f2b2ced.png">

**Comment by devongovett** [comment]
Yeah you'll need the other fix first - inserting the PURE annotations in the react-aria-components build. See #4357. That brings the size down a lot for me, and then the `swcMinify` option fully optimizes it.

**Comment by eashish93** [comment]
This is barebone VITE build (esbuild version)

<img width="442" alt="Screenshot 2023-04-10 at 11 43 12 PM" src="https://user-images.githubusercontent.com/13780952/230965099-8d98baad-ea06-4973-b131-938bccb18b2e.png">

With react-only
<img width="482" alt="Screenshot 2023-04-10 at 11 42 40 PM" src="https://user-images.githubusercontent.com/13780952/230965000-235ef9dc-d1d2-4329-9685-72b0208a32f3.png">
With react + button

**Comment by devongovett** [comment]
I think #4357 should also fix that. esbuild seems to already support PURE annotations properly, so once they are there it should be fine.

**Comment by devongovett** [comment]
Just released v1.0.0-alpha.3 with this fix, and tested in a next.js project. It should be much improved. SWC also just improved the minifier, so in the next version of Next.js it should be even better.

**Comment by leerob** [comment]
Appreciate the deep diver here @devongovett!

**Comment by IonelLupu** [comment]
Still not fixed as described here: https://github.com/vercel/next.js/discussions/60206

**Comment by windmaomao** [comment]
the problem is not the `next`, if i use `rollup`, and import button only, it generates a 1.3M file.

<img width="954" alt="Screen Shot 2024-02-02 at 10 42 22" src="https://github.com/adobe/react-spectrum/assets/1700809/09572867-8aaa-4ca7-90d1-a4b0a439334a">
