### ISSUE TITLE
AlertDialog has no pending state support for primary button

### ISSUE THREAD

**Issue by sargismarkosyan** [adobe/react-spectrum#4362]
# 🙋 Feature Request

AlertDialog is designed to be used for confirmation actions. But some of these actions can take time to execute.
For that, it will be helpful to show some loading processes that will indicate the process is taking place.
For example, I would expect the primary button to show a loading indicator.
I could implement that in my component but cannot pass `React.Element` to the `primaryActionLabel` as it only accepts a string as a value.

`<AlertDialog
            primaryActionLabel={
              <ProgressCircle
                aria-label="Loading..."
                variant="overBackground"
                isIndeterminate
                size="S"
              />
            }
          >`

## 🤔 Expected Behavior

I am expecting to be able to pass React.Elements to primaryActionLabel property as a value

## 😯 Current Behavior

primaryActionLabel property accepts only string objects as a value

## 💁 Possible Solution

Change the type of primaryActionLabel property from string to React.Element

## 🔦 Context

This will help us to add a loading indicator on the primary button when the job takes time to execute

## 🧢 Your Company/Team

Adobe/Workfront

**Comment by LFDanLu** [comment]
Spectrum Design has a design for the loading button [here](https://spectrum.corp.adobe.com/page/button/#Pending), we are tracking this in our milestone backlog at the moment so keep an eye out for any updates in status [here](https://github.com/orgs/adobe/projects/19/views/18).
