### ISSUE TITLE
React Aria Components Popover children render props error

### ISSUE THREAD

**Issue by VlasenkoStanislav** [adobe/react-spectrum#4369]
# 🐛 Bug Report 

I copied [example code](https://react-spectrum.adobe.com/react-aria/Popover.html#example) and tried to access children render props, but popup doesn't show up, and I see an error in console.

## 🤔 Expected Behavior

Access to popup children render props.

## 😯 Current Behavior

The popup doesn't show up, and I see this error in console:
Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

## 💻 Code Sample

[Codesandbox](https://codesandbox.io/p/sandbox/quiet-cloud-1816m0?file=%2Fsrc%2FApp.tsx)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria-components   | 1.0.0-alpha.2
| Browser          |  Chrome 112.0.5615.50
| Operating System | Windows 11

**Comment by devongovett** [comment]
I think this line should be `renderProps.children` https://github.com/adobe/react-spectrum/blob/a8903d3b8c462b85cc34e8565e1a1084827d0a29/packages/react-aria-components/src/Popover.tsx#L119

**Comment by VlasenkoStanislav** [comment]
@devongovett, seems to have the same issue in these components: ComboBox, Select, NumberField, DateField, DatePicker, Tabs.
