### ISSUE TITLE
Dynamic TableView + ActionButton = Flickering on Mouseover

### ISSUE THREAD

**Issue by repli-a** [adobe/react-spectrum#4374]
# 🐛 Bug Report 

Dynamically generated TableView rows flicker/jump on fast mouseover or click when a button is added to a cell

## 🤔 Expected Behavior

Rows should not flicker/jump on UI interaction if they are not being re-rendered

## 😯 Current Behavior

When the mouse is quickly passed over dynamically generated rows or if they are clicked the row text shifts upward slightly for a moment as though the row "jumped". This does not happen with static table content. It looks like a glitch, not intentional UI behavior.

Adding a button to the row with conditional logic seems to be what triggered the issue.

No errors corresponding to this issue are in the logs. Each item is confirmed to have unique IDs.

## 💁 Possible Solution

No idea. I do not see this issue reported elsewhere.

## 🔦 Context

This is possibly user error but if not I wanted to bring it to your attention.

## 💻 Code Sample

I plan to rewrite this to replace the button elements here with a component instead, but here is how it stands as of now. Prior to adding the buttons the table did not exhibit this behavior.

```
<TableHeader>
  <Column key='name' align='center'>Seq. Name</Column>
  <Column key='origStatus' align='center'>Status</Column>
  <Column key='origSize' align='center'>Size</Column>
  <Column key='proxyStatus' align='center'>Proxy Status</Column>
  <Column key='proxySize' align='center'>Proxy Size</Column>
  <Column key='totalSize' align='center'>Total Size</Column>
</TableHeader>
<TableBody items={seqArray}>
  {item => (
    <Row>
      {columnKey => columnKey.includes("Status") ? <Cell><MenuTrigger>
  <ActionButton>
  {item[columnKey]}
  </ActionButton>
  <Menu onAction={(key) => alert(key)}>
    <Item key="cut">Pin</Item>
    <Item key="copy">Unpin</Item>
    <Item key="paste">Open</Item>
  </Menu>
</MenuTrigger></Cell> : <Cell>{item[columnKey]}</Cell>}
    </Row>
  )}
</TableBody>
</TableView>
  );
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.25.1
| Browser          | Chromium 88
| Operating System | Windows 10

**Comment by repli-a** [comment]
I have also confirmed by removing the conditional operator that adds the button that this is the cause. Without the button, the table does not jump when moused-over or clicked.

**Comment by snowystinger** [comment]
Hey, thanks for bringing this up, would you mind adding a codesandbox to demonstrate as well?
Here's one to get you started https://codesandbox.io/s/pensive-field-of0b6s?file=/src/App.js

**Comment by repli-a** [comment]
Sure thing.

In the meantime I've further narrowed this down to the ternary operator I'm using to conditionally render this element. With the conditional expression gone, the flicker is no longer present even with the buttons dynamically rendered. 

Is it possible to forego the iterator in the cell renderer and just explicitly list the cell elements and the item/key pairs that should be in each element, since I know exactly how many cells will be in a row? Like this:

```
  {item => (
    <Row>
<Cell>item1.key1</Cell>
<Cell>item1.key2</Cell>
<Cell><Component/></Cell>
<Cell><Component/></Cell>
<Cell>item1.key5</Cell>
    </Row>
    ```

**Comment by repli-a** [comment]
Alright, the example is up in codesandbox but I wasn't able to reproduce. I'm also unable to reproduce it in my browser. I specified Chrome in the description (I've since corrected), but realized I'm encountering it in [Adobe CEP](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md), which [uses CEF/Chromium 88](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#chromium-embedded-framework-cef). So not apples-to-apples and not something I would expect you to fix.

That said, can I take the alternate approach mentioned above to work around this issue for this particular platform?

**Comment by snowystinger** [comment]
Ah, unfortunately, we do not use CEP/CEF. I suggest asking in their support channels.

If it works when you write it that way, I don't see a problem. Though it might point to React not reusing certain dom elements, so maybe all you need to do to your original implementation is provide some keys?

**Comment by repli-a** [comment]
I did run into issues with refresh funkiness initially, but I've since modified and now provide an `id` in each object as specified [here](https://react-spectrum.adobe.com/react-spectrum/TableView.html#content). Don't the `id`s in this case correspond to React's keys?

**Comment by snowystinger** [comment]
Yes and no, we automatically use id's like keys would be used to do our caching in virtualized components such as TableView.

Is it ok if we close this issue? if something comes back from CEP, we can reopen it

**Comment by repli-a** [comment]
Sure thing. Thanks for your help.
