### ISSUE TITLE
RAC - Select and SelectValue do not honor `placeholder` prop

### ISSUE THREAD

**Issue by auskast** [adobe/react-spectrum#4398]
# 🐛 Bug Report 

For the `react-aria-components` `Select` and `SelectValue` components, setting the `placeholder` prop on either one does not affect the rendered HTML. Looking at the source code, it seems that the placeholder is hard-coded to `Select an item`.

Secondarily, it is a bit confusing as to which component the placeholder should be set on. It seems that the intent is that the `Select` component receives the `placeholder` prop rather than `SelectValue`.

## 🤔 Expected Behavior

Setting the `placeholder` prop on `Select` should display a placeholder when no item is selected.

The `SelectValue` component should not accept a `placeholder` prop.

## 😯 Current Behavior

Neither the `Select` nor `SelectValue` `placeholder` prop have any effect.

## 💁 Possible Solution

Change the `defaultChildren` render prop in `SelectValue` to accept the `placeholder` prop, if defined. It's possible that this needs to somehow come from the `SelectContext` if the intent is for the prop to be set on the `Select` component.

https://github.com/adobe/react-spectrum/blob/b92f6029e71aa29a9f7b35e403586856a90004ad/packages/react-aria-components/src/Select.tsx#L154

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria-components  | 1.0.0-alpha.3 |
| Browser          | Chrome 112.0.5615.49 (Official Build) (arm64) |
| Operating System | macOS 13.3.1 |

**Comment by LFDanLu** [comment]
We should definitely make the `placeholder` prop for `Select` propagate its value to the `SelectValue`. Probably should be added to the [InternalSelectContext](https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/Select.tsx#L84). For now you could use the renderProps on `SelectValue` to render a placeholder when an item isn't selected like [so](https://codesandbox.io/s/trusting-keller-y65pr6?file=/src/App.js).
