### ISSUE TITLE
Popover (react-aria-components) : add portalContainer prop

### ISSUE THREAD

**Issue by rlebosse** [adobe/react-spectrum#4404]
# 🙋 Feature Request

Since the `Popover` component uses the `Overlay` component which takes an optional `portalContainer` prop, it would be very useful to be able to use `portalContainer` with `Popover` too.

It would allow to "portalize" the overlay content somewhere else than in `document.body`.

## 🤔 Expected Behavior

The following code :

```js
<Popover portalContainer={document.querySelector('#overlay-container')}>List</Popover>
```

Would "portalize" the `Popover` content to the dom node returned by `document.querySelector('#overlay-container')`.

## 😯 Current Behavior

The following code :

```js
<Popover portalContainer={document.querySelector('#overlay-container')}>List</Popover>
```

"Portalizes" the `Popover` content to `document.body`.

## 🔦 Context

I'm building a selector using the `Select`, `Button`, `Item`, `Label`, `ListBox`, `Popover` and `SelectValue` components.
This selector is used in tooltip that closes automatically when blurred.
Since the selector options are appended to `document.body`, when I open it with my keyboard (`SPACE` or `ENTER` keys), it is consider a blur because the blur goes outside the tooltip.
I would like to be able to append the selector options in the tooltip in order to prevent this from happening, thanks to the `portalContainer` prop.

**Comment by LFDanLu** [comment]
Mind expanding on why you have your selector in a tooltip? https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/ indicates that "Tooltip widgets do not receive focus", could you instead make this experience open a popover dialog and expose the selector in that dialog instead?

**Comment by rlebosse** [comment]
Hi, I was mistaken by using the word "tooltip". It's more of a "popover" that is displayed by clicking on a button present in the page. This popover is handled by another lib than those provided by `react-spectrum` (with the lib [tippyjs-react](https://github.com/atomiks/tippyjs-react)).

To be more correct :

I'm building a selector using the `Select`, `Button`, `Item`, `Label`, `ListBox`, `Popover` and `SelectValue` components.
This selector is displayed in a popover (built with the lib [tippyjs-react](https://github.com/atomiks/tippyjs-react)) that closes automatically when blurred.
Since the selector options are appended to `document.body`, when I open it with my keyboard (SPACE or ENTER keys), it is consider a blur because the blur goes outside the popover.
I would like to be able to append the selector options in the popover in order to prevent this from happening, thanks to the portalContainer prop.

**Comment by LFDanLu** [comment]
Apologies, I'm not very familiar with tippyjs so I'm having a hard time following the resulting DOM structure here, is it possible to include a codesandbox showing the minimal reproduction here?  If I'm following you correctly, you want to be able to make the React Aria Component's Popover portalled to the tippyjs Popover instead of to document.body?

**Comment by rlebosse** [comment]
Hi @LFDanLu , here is another use case that could illustrate the need to get a `portalContainer` prop for `Popover` :

I use the 'focus-trap-react' lib to "trap" the focus in a modal (I don't use `FocusScope` since it's code that has been written long before I use `react-aria-components`).

In this modal, I use the `Select` provided by `react-aria-components`, but since the items displayed (within `Popover`) are appended to `document.body`, they are considered outside of the "focus trap", and I can't set the focus on one of these items (using the keyboard arrows for example).

Being able to pass `portalContainer` with a prop to `Popover` would allow me to specify to append the items displayed to the modal container (inside the "focus trap"), and allow the focus on them.

Here is a CodeSandbox I made to illustrate my problematic : https://codesandbox.io/s/react-aria-components-select-focus-trap-react-jrq5z5?file=/src/App.tsx

**Comment by armandabric** [comment]
I'm working with the `Modal` component and I also need to configure the Overlay `portalContainer` props. 

Having the modal in the body element cause some issue for us. We need to move it in our application _root container element_.

**Comment by mryechkin** [comment]
Casting another vote for this suggestion 👍 It would help with scenarios where we can't always control _all_ the overlays being used.

**Comment by LFDanLu** [comment]
Copy pasting my comment from a related issue:
The team talked about this some more yesterday. We are entertaining the idea of allowing users to specify the portalContainer for RAC/aria hooks like its done in https://github.com/adobe/react-spectrum/pull/5381, but we would want to make it clear in the prop description/naming that it is largely unknown what cases may fail if the overlay is portalled somewhere unexpected (e.g. portalled to a third party FocusScope, etc).

We'd like to collect some more information about the use cases here so we can make a more informed decision or suggest alternatives.
@armandabric could you share some more info as to the requirement for the modal needing to be in the root container element? 
@mryechkin just to clarify, you are alluding to a scenario with other third party overlays/components in your app/project?
