### ISSUE TITLE
CMD+A keyboard shortcut triggers error when all rows in table are already selected

### ISSUE THREAD

**Issue by tianenpang** [adobe/react-spectrum#4406]
# 🐛 Bug Report 

When all rows of a Table component are already selected and `CMD`+`A` keyboard shortcut is used, it triggers a `setB.has is not a function` error.

## 🤔 Expected Behavior

The `CMD`+`A` keyboard shortcut should toggle the selection state of all rows in the Table component.

## 😯 Current Behavior

It triggers the [`setB.has is not a function`](https://github.com/adobe/react-spectrum/blob/b92f6029e71aa29a9f7b35e403586856a90004ad/packages/%40react-stately/selection/src/useMultipleSelectionState.ts#L25) error.

## 💻 Code Sample

https://codesandbox.io/s/react-aria-table-select-all-via-kbd-tu9jkl

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | Latest
| Browser          | Chrome
| Operating System | Windows

**Comment by reidbarber** [comment]
I think we could probably get better behavior for this by updating the following line to `manager.toggleSelectAll()`:
https://github.com/adobe/react-spectrum/blob/b92f6029e71aa29a9f7b35e403586856a90004ad/packages/%40react-aria/selection/src/useSelectableCollection.ts#L221

But also add a `keys === 'all' && selectedKeys === 'all'` condition here to fix the actual issue shown:

https://github.com/adobe/react-spectrum/blob/b92f6029e71aa29a9f7b35e403586856a90004ad/packages/%40react-stately/selection/src/useMultipleSelectionState.ts#L112-L116
