### ISSUE TITLE
TableHeader(react-aria-components): Type does not support `className`

### ISSUE THREAD

**Issue by jaknas** [adobe/react-spectrum#4420]
# 🐛 Bug Report 

When using `TableHeader` component from `react-aria-components` and trying to pass `className` prop ([as in docs](https://react-spectrum.adobe.com/react-aria/Table.html#tableheader-1)), TypeScript says that `TableHeaderProps` does not support `className` property.

## 🤔 Expected Behavior

User should be able to pass `className` without any type warnings

## 😯 Current Behavior

```ts
Type '{ children: Element[]; className: string; }' is not assignable to type 'IntrinsicAttributes & TableHeaderProps<object>'.
  Property 'className' does not exist on type 'IntrinsicAttributes & TableHeaderProps<object>'
```

## 💁 Possible Solution

Extend `TableHeaderProps` with `RenderProps` or `StyleRenderProps` interface.

## 💻 Code Sample

https://codesandbox.io/s/goofy-marco-r8c6dx?file=/src/App.tsx

**Comment by LFDanLu** [comment]
Extending StyleRenderProps seems reasonable enough.

**Comment by AmirAhmadzadeh** [comment]
I can take a look at this issue.
