### ISSUE TITLE
Expose weekday data in `<CalendarGridHeader/>` render props, so you can format weekdays

### ISSUE THREAD

**Issue by arzatskis** [adobe/react-spectrum#4421]
# 🙋 Feature Request

Expose date data in `<CalendarGridHeader/>` render props, so you can format weekdays

## 🤔 Expected Behavior

Having more data available in children render function, from which you can format weekday would solve the issue.

## 😯 Current Behavior

At the moment render props [exposes](https://react-spectrum.adobe.com/react-aria/Calendar.html#calendargridheader) day as string, but you can't  format weekday (e.g. rendering `Mo` instead of `M`)

## 💁 Possible Solution

1. Exposing more render props / data for weekday could be one
2. Prop for how you want weekdays formatted may be another one

## 💻 Examples

Here's calendar mock with longer weekdays to illustrate what I'm trying to achieve:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/687133/233579348-67165220-c2ea-4d19-9c75-9d7260c4349e.png">

**Comment by LFDanLu** [comment]
This sounds reasonable enough, perhaps we could preserve the original [Date](https://github.com/adobe/react-spectrum/blob/ba727bdc0c4a57626131e84d9c9b661d0b65b754/packages/%40react-aria/calendar/src/useCalendarGrid.ts#L137) when generating the `weekDays` and provide that info to the `CalendarHeaderCell`. Alternatively, we could add a prop for customizing the [weekday](https://github.com/adobe/react-spectrum/blob/ba727bdc0c4a57626131e84d9c9b661d0b65b754/packages/%40react-aria/calendar/src/useCalendarGrid.ts#L131) option maybe.
