### ISSUE TITLE
Bundling issue with @internationalized/date?

### ISSUE THREAD

**Issue by plasmicops** [adobe/react-spectrum#4425]
# 🐛 Bug Report 

Loading `./node_modules/@internationalized/date/dist/import.mjs` results in this error:

```
error - ./node_modules/@internationalized/date/dist/import.mjs:1:0
Module not found: Can't resolve '@swc/helpers/src/_class_private_field_init.mjs'
```
`import.mjs` looks like this:

```
import $cUVuN$swchelperssrc_class_private_field_initmjs from "@swc/helpers/src/_class_private_field_init.mjs";
import $cUVuN$swchelperssrc_define_propertymjs from "@swc/helpers/src/_define_property.mjs";
```

so it appears to be importing from `@swc/helpers/src/`, which seems wrong (and also, isn't included in the distribution).

## 🤔 Expected Behavior

Should work

## 😯 Current Behavior

Import error as above

## 💻 Code Sample

Reproduce by:
1. `npx create-next-app@latest`
2. `npm i @internationalized/date`
3. Import into your `index.tsx`

## 🌍 Your Environment

Latest `@internationalized/date` (3.2.0) and next (13.3.1)

## 🧢 Your Company/Team

Plasmic

**Comment by chungwu** [comment]
Ah issue appears to be more widespread than that; also affected: 

```
./node_modules/@react-aria/focus/dist/import.mjs:1:0
Module not found: Can't resolve '@swc/helpers/src/_define_property.mjs'
```

I suspect many more...

**Comment by chungwu** [comment]
Actually looks like it's related to this... https://github.com/vercel/next.js/issues/48593

**Comment by chungwu** [comment]
Confirmed that this is a nextjs issue; things work fine with nextjs version 13.2.* but breaks in 13.3.  Sorry for the noise!

**Comment by salamaashoush** [comment]
it is not a nextjs issue only, I have the same issue with webpack and rspack when I upgrade `@swc/helpers` to `0.5.0`

**Comment by fraincs** [comment]
This does not look like it's fixed.

**Comment by icopp** [comment]
Same problem here. Doesn't work with Next v12 at all for whatever reason.

**Comment by devongovett** [comment]
I don't think there is anything we can do about this. We have to upgrade to `@swc/helpers` to fix newer versions of Next and some other build tools, but that breaks older Next. So I think you have to either upgrade Next to the latest 13.x release, or ask the Next.js team to backport the fix to an older version. Sorry about that!

**Comment by devongovett** [comment]
For reference, the fix was this: https://github.com/vercel/next.js/pull/48980. You could potentially use something like [patch-package](https://github.com/ds300/patch-package) to patch the version of Next that you are using yourself, or maybe somehow override the webpack config.

**Comment by devongovett** [comment]
FYI, I reached out to the Vercel folks and they were nice enough to backport a fix to `@swc/helpers` that you can use with Next v12! See https://github.com/vercel/next.js/issues/48593#issuecomment-1681930868 for how to override the version with your package manager.
