### ISSUE TITLE
How to set `borderStyle: "dashed"`?

### ISSUE THREAD

**Issue by conao3** [adobe/react-spectrum#4428]
# 🙋 Feature Request

If I specify `borderStyle: "dashed"` for `UNSAFE_style` with `borderWidth="thin"`, render border with `"solid"`.

## 🤔 Expected Behavior

render border with `"dashed"` style.

## 😯 Current Behavior

render border always `"solid"` style.

## 💁 Possible Solution

This issue comes from this line. 
https://github.com/adobe/react-spectrum/blob/ba727bdc0c4a57626131e84d9c9b661d0b65b754/packages/%40react-spectrum/utils/src/styleProps.ts#L246

Since `UNSAFE_style` is overridden by react-spectrum's, I suggest that `UNSAFE_style` be preferred over react-spectrum's style.
Users who use `UNSAFE_style` should know that this feature could shoot itself in the foot.

## 🔦 Context

No

## 💻 Examples

```tsx
  return (
    <View
      borderWidth="thin"
      padding="size-500"
      borderRadius="regular"
      UNSAFE_style={{
        borderStyle: "dashed",
      }}
    >
      DropZone
    </View>
  )
```
![image](https://user-images.githubusercontent.com/4703128/233813657-4abc7f5f-5292-416c-8872-ec630c14b14d.png)

## 🧢 Your Company/Team

No

## 🎁 Tracking Ticket (optional)

No

**Comment by snowystinger** [comment]
React spectrum is specifically designed for the Spectrum design system. There are too many foot guns with regards to just the design system itself that this isn't something we want to open up. One of the goals of the react spectrum components is to enforce the design system. Instead, if you're an Adobe employee, I suggest reaching out to the Design team to see if there is a missing use case. And if you're not an Adobe employee, I think this is the perfect place to use React Aria Components, https://react-spectrum.adobe.com/react-aria/react-aria-components.html

**Comment by conao3** [comment]
I'm not Adobe employee.

I found `Drop Zone` component at [Spectrum CSS](https://opensource.adobe.com/spectrum-css/dropzone.html) and I want to implement this with react-spectrum. it has a dashed border to indicate "drop zone".
I think `UNSAFE_style` should be a priority for the last resort to achieve the look users want.

Note: There is a request directly for implementing DropZone (#3034)

**Comment by snowystinger** [comment]
So you can implement any component you want using our hooks, including one's that aren't in React Aria Components or React Spectrum. And when you do that, you can use any CSS you like, including Spectrum-CSS. This is how we allow people to customize their components if they need something we haven't implemented or is outside what Spectrum has designed.

The DropZone over at Spectrum CSS was created a while ago, I do not know how up to date it is with current designs. Eventually we'll implement one in React Spectrum as you've noted. When we do, we'll work with design to make sure that it matches the current direction of the design system. We'll also update that issue when we work on it.

Here is a link to the docs for the hook. 
https://react-spectrum.adobe.com/react-aria/useDrop.html#example

One more option you have is you can use the CSS variables and style a plain div. This comes with mostly the same foot-gun warnings until Spectrum-CSS can maintain a stable API, which is something on their roadmap.

I'm going to close this for now. If you have issues using the hooks to create the Dropzone, feel free to open a new Issue.
