### ISSUE TITLE
@react-aria/datepicker does not export RangeCalendarProps type

### ISSUE THREAD

**Issue by syropian** [adobe/react-spectrum#4441]
# 🐛 Bug Report 

Since the datepicker's `calendarProps` is generally passed wholesale to a custom calendar component, we need to be able to import the `RangeCalendarProps` type into that custom component to type its props. 

## 🤔 Expected Behavior

I should be able to import `RangeCalendarProps` from `@react-aria/datepicker`

## 😯 Current Behavior

There is no import for `RangeCalendarProps`

## 💁 Possible Solution

Export the `RangeCalendarProps` type

## 🔦 Context

Just trying to build a basic date range picker

## 💻 Code Sample

N/A
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria/datepicker   | latest
| Browser          | any
| Operating System | macOS

## 🧢 Your Company/Team

Combo

**Comment by snowystinger** [comment]
Should be able to import it from any of these places depending on the packages you're using. We strongly encourage people to use either the first or second option from this list, it helps with package version management.
```
import {RangeCalendarProps} from 'react-aria';
import {RangeCalendarProps} from 'react-aria-components';
import {RangeCalendarProps} from '@react-types/calendar';
```
