### ISSUE TITLE
React Aria Components: Expose `DropIndicatorProps` type

### ISSUE THREAD

**Issue by jaknas** [adobe/react-spectrum#4446]
# 🐛 Bug Report 

`DropIndicatorProps` type is not exported from `react-aria-components`

## 🤔 Expected Behavior

it should be exported to allow creating custom `<DropIndicator/>` components

## 💁 Possible Solution

re-export it from `react-aria`

## 💻 Code Sample

https://codesandbox.io/s/winter-sun-rcjjvf?file=/src/App.tsx

**Comment by snowystinger** [comment]
Looks like we have two different DropIndicatorProps types, one for react-aria, and one for react-aria-components. Respectively

https://github.com/adobe/react-spectrum/blob/bd89c6aba9dd1bf763a5166d37524ab6fb612509/packages/%40react-aria/dnd/src/useDropIndicator.ts#L24

and 

https://github.com/adobe/react-spectrum/blob/bd89c6aba9dd1bf763a5166d37524ab6fb612509/packages/react-aria-components/src/useDragAndDrop.tsx#L157


I'll bring it up with the team and see how we want to go about resolving this. It might be confusing to have them both named the same thing.

**Comment by snowystinger** [comment]
Talked to my colleague, we have sufficient examples of two interfaces sharing the same name that we don't feel this is an issue.
For example, combobox props, [react-types](https://github.com/adobe/react-spectrum/blob/bd89c6aba9dd1bf763a5166d37524ab6fb612509/packages/%40react-types/combobox/src/index.d.ts#L17)
vs the [react-aria-component](https://github.com/adobe/react-spectrum/blob/bd89c6aba9dd1bf763a5166d37524ab6fb612509/packages/react-aria-components/src/ComboBox.tsx#L25)
