### ISSUE TITLE
useFocusable triggers keyboard interaction use case when only using mouse

### ISSUE THREAD

**Issue by Inkvii** [adobe/react-spectrum#4457]
# 🐛 Bug Report 

`useFocusable` hook triggers keyboard interaction use case when it should not.

Given blank page with a button, clicking on it should not trigger keyboard interaction (as if hitting tab). 

Also there is something odd going on when switching focus from textfield that uses `useTextfield` hook to the button - that shouldnt trigger keyboard interaction either.

## 🤔 Expected Behavior

Keyboard interaction should be triggered only when user uses tab.

Expected focus-visible css pseudoclass to work as intended when using mouse only interaction

## 😯 Current Behavior

When reloading page and clicking on button, focus-visible psedudoclass is applied to the element. 

When typing text to textfield and then mouse clicking on button, focus-visible pseudoclass is applied to the element.

Tested it against button without `useButton` hook with same css classes applied and this button works as intended.

When first clicking on button that doesnt use `useButton` hook and then on any other button, it behaves correctly (focus-visible pseudoclass is not applied)

## 💁 Possible Solution

This article helped me to pinpoint the issue https://discourse.wicg.io/t/ability-to-explicitly-set-focus-visible-from-focus/5695/2 

## 🔦 Context

Goal of this issue is to use focus-visible as intended. Currently it behaves more like only focus pseudoclass, applying the css rules even when no keyboard interaction is happening. 

https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

## 💻 Code Sample

https://codesandbox.io/s/frosty-mopsa-1i8is3?file=/src/App.jsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |3.23.1
| Browser          | Chrome 112
| Operating System | Windows 10

**Comment by snowystinger** [comment]
Hey there, from what I can see, you're not using React Aria to style anything. Instead, you're just getting the native psuedo selectors and therefore native browser behaviors. You'll want to read our blog post which talks about some of these pitfalls https://react-spectrum.adobe.com/blog/building-a-button-part-3.html#focus-rings

I suggest using our new React Aria Components instead https://react-spectrum.adobe.com/react-aria/Button.html. They offer data attributes that Tailwind can easily target for styling and we normalize the focus visible behaviors across browsers.
Here's a great demo building a switch with React Aria Components and Tailwind https://www.youtube.com/watch?v=T-pr-rZgMlQ

You can also still use the hooks directly, you'll just want to use https://react-spectrum.adobe.com/react-aria/useFocusRing.html to determine if you should show the focus-ring here's your example with that implemented https://codesandbox.io/p/sandbox/old-wildflower-72pd6l?file=%2Fsrc%2FApp.jsx

**Comment by Inkvii** [comment]
I see, so in order to normalise behavior across multiple browsers and OS javascript has to be used, since each browser implements css rules slightly differently. 

Thanks for the explanation, closing the issue
