### ISSUE TITLE
SelectStateOptions is not exported in .d.ts

### ISSUE THREAD

**Issue by donaldpipowitch** [adobe/react-spectrum#4460]
# 🐛 Bug Report 

~~After updating React Aria/Stately TypeScript was complaining that I'm passing `children` to `useSelectState`. The props are defined as this (notice the `Omit<SelectProps<T>, 'children'>` part):~~

```ts
interface SelectStateOptions<T> extends Omit<SelectProps<T>, 'children'>, CollectionStateBase<T> {
}
```

~~However when I look at the official example https://react-spectrum.adobe.com/react-aria/useSelect.html and the through the source code I see that `children` are passed to `useSelectState` then `useSingleSelectListState` then `useListState` and then `useCollection` which uses `children`.~~

`SelectStateOptions` is not exported in the .d.ts file.

## 🤔 Expected Behavior

~~`useSelectState({ children })` should be fine.~~

`import { SelectStateOptions } from 'react-stately';` works.

## 😯 Current Behavior

~~`useSelectState({ children })` errors in TypeScript.~~

`import { SelectStateOptions } from 'react-stately';` errors.

## 💻 Code Sample

https://codesandbox.io/s/dreamy-taussig-netudj?file=/src/Select.tsx:132-199

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by donaldpipowitch** [comment]
You're right. My bad. It looks like the underlying type changed from `AriaSelectOptions` (that had `children` in the past, but not anymore...?) to `SelectStateOptions` which _does_ support `children` from `CollectionStateBase` like you said. 

But for some reason it is not exported and can't be used directly.

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/1152805/235762306-d6772885-3967-4adf-a940-cd84afef5ac6.png">

But according to the source code it should be exported.

**Comment by LFDanLu** [comment]
Yep, we should definitely export it from `react-stately`, oversight on our part.
