### ISSUE TITLE
disallowSelectAll from useSelectableList is not passed to useSelectableCollection

### ISSUE THREAD

**Issue by simenbrekken-visma** [adobe/react-spectrum#4462]
# 🐛 Bug Report 

`disallowSelectAll` is not able to be forwarded from `useSelectableList` to `useSelectableCollection`

## 🤔 Expected Behavior

I should be able to forward `disallowSelectAll` from `useSelectableList` to `useSelectableCollection`

## 😯 Current Behavior

`disallowSelectAll` cannot be forwarded from `useSelectableList` to `useSelectableCollection`

## 🔦 Context

I'm making a listbox that uses `useAsyncList` in which case "Select all" isn't really selecting all items but merely the ones that have been loaded so far. We might add a separate "Select all" button/hotkey that does this on the backend but we need to disable the default behavior first.

**Comment by LFDanLu** [comment]
Just to clarify, the listbox that you are implementing wants all keys (loaded and unloaded) to be selected upon pressing CMD+A correct? This should already be supported since [select all](https://github.com/adobe/react-spectrum/blob/5a3315f560071087cacf846bd2a86d8f47692446/packages/%40react-stately/selection/src/SelectionManager.ts#L404-L408) sets `selectedKeys` to the "all" keyword rather than looking at the items currently loaded.

**Comment by simenbrekken-visma** [comment]
We would like to disable the shortcut as it conflicts with another shortcut on the page.

**Comment by LFDanLu** [comment]
I see, thanks for the additional info. I think this change should be fine then.

**Comment by snowystinger** [comment]
Just curious, what is the other shortcut on the page? I ask because Ctrl+A is the Aria command for select all, see https://www.w3.org/WAI/ARIA/apg/patterns/listbox/
But if that conflicts with something else that is common, maybe we should be reporting a bug.

**Comment by simenbrekken-visma** [comment]
@snowystinger It's definitely not a common shortcut. In addition in our `Select` and `MultiSelect` we have a search input inside the popover that when someone attempts to "Select all" inside the input field but it doesn't have focus for some reason all items are suddenly selected. We would like to control this behavior ourselves.
