### ISSUE TITLE
`.nvmrc` points to Node v12 which conflicts with eslint-plugin-jest

### ISSUE THREAD

**Issue by simenbrekken-visma** [adobe/react-spectrum#4463]
# 🐛 Bug Report 

`.nvmrc` appears to be out of date. [`CONTRIBUTING.md`](https://github.com/adobe/react-spectrum/blob/main/CONTRIBUTING.md#developing) specifies Node v14 but the `.nvmrc` contains `12.*`.

## 🤔 Expected Behavior

`.nvmrc` should have `14.*`

## 😯 Current Behavior

`.nvmrc` contains `12.*`

Running `yarn` after switching to 12 results in the following error:

```
error eslint-plugin-jest@27.1.1: The engine "node" is incompatible with this module. Expected version "^14.15.0 || ^16.10.0 || >=18.0.0". Got "12.22.12"
```

**Comment by snowystinger** [comment]
It should be 14 or 16, both will work and the .nvmrc should be updated.
