### ISSUE TITLE
ChevronLeft and ChevronRight have ids on the path elements

### ISSUE THREAD

**Issue by jluyau** [adobe/react-spectrum#4465]
# 🐛 Bug Report 

The `<ChevronLeft>` and `<ChevronRight>` icons from `@spectrum-icons/workflow` have an `id` prop set on the path. The `<ChevronRight>` path id is also incorrect.

## 🤔 Expected Behavior

The `id` props should probably not be set.

## 😯 Current Behavior

Since the `id` prop is set on the path, it cannot be overridden by passing an `id` prop into the icon. Therefore, having multiple instances of these icons on a page would result in an accessibility issue because of duplicate ids. Also, because the ChevronRight id is incorrect (S_MillerColumnsChevronPrevious), it collides with the ChevronLeft path id (which also has this value).

## 💁 Possible Solution

Remove the `id` props from the underlying `<path>` element.

## 🔦 Context

This is an accessibility issue to have duplicate IDs on the same page since we're using both ChevronLeft and ChevronRight for a pagination component

## 💻 Code Sample

https://codesandbox.io/s/elegant-curran-cu7os2?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.26
| Browser          | Chrome 112.0.5615.137
| Operating System | MacOS Ventura 13.2.1

## 🧢 Your Company/Team

Adobe/Quarry

**Comment by reidbarber** [comment]
I wonder if we could use [svgo](https://github.com/svg/svgo) in [buildIcons.js](https://github.com/adobe/react-spectrum/blob/main/scripts/buildIcons.js). We would probably get some other improvements as well.

**Comment by snowystinger** [comment]
That compile SVG is only used for Express workflow icons. The others are all generated in a different repo. We would need to submit against that. It's internal @jluyau , I'll reach out to you.
