### ISSUE TITLE
React Aria Components: Combobox opening doesnt add html{overflow: hidden}

### ISSUE THREAD

**Issue by IHIutch** [adobe/react-spectrum#4515]
# 🐛 Bug Report 

You'll see in [this example](https://draft-ui-storybook.vercel.app/?path=/story/datepicker--default) using `Datepicker` that when the date picker is opened `html` gets the style `overflow: hidden`. This is true for the `Select` component as well.

However, the `Combobox` component ([example](https://draft-ui-storybook.vercel.app/?path=/story/combobox--default)) does not do this when opening.

Im not sure if this is intentional. Or what the suggested approach is for styling overflow flow behavior. I suppose, typically, that the popover would correctly open with the available space. You can see an example of how this might be handled below:

https://github.com/adobe/react-spectrum/assets/20825047/2c9c3e8f-38f8-413e-b001-656da2f6282f

https://github.com/adobe/react-spectrum/assets/20825047/6c67e805-5959-4d55-a7a0-5bd9824dc683

However, I did notice that the popovers receive an automatic `max-height` based on the space available, so perhaps the suggested approach is to scroll within the popover?

## 🤔 Expected Behavior

All of the popover components add `overflow: hidden` to `html`. Or none of them do.

## 💁 Possible Solution

If this behavior is expected, it would be nice to know a suggested approach regarding scrolling inside or outside the popover

## 💻 Code Sample

Repo: https://github.com/IHIutch/draft-ui

## 🕷 Tracking Issue (optional)

Related: https://github.com/IHIutch/draft-ui/issues/1

**Comment by LFDanLu** [comment]
Background:
Unlike other popovers, ComboBox actually allows users to interact with elements outside the popover when its popover is open for accessibility purposes (aka screen readers need to be able to move back and forth between the input element and the popover). This classifies its popover as [isNonModal](https://github.com/adobe/react-spectrum/blob/3f91517ec3f64dead637f6ea7a9fb85190f9c872/packages/%40react-aria/overlays/src/usePopover.ts#L33-L40) in usePopover which disables [scroll prevention](https://github.com/adobe/react-spectrum/blob/3f91517ec3f64dead637f6ea7a9fb85190f9c872/packages/%40react-aria/overlays/src/usePopover.ts#L95-L97), hence the lack of the `overflow: hidden` unlike other popovers. This mimics the behavior of the native [datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist).

> However, I did notice that the popovers receive an automatic max-height based on the space available, so perhaps the suggested approach is to scroll within the popover?

Yes, limiting the popover to fit within the space available and making its contents scrollable would be our suggested approach.

**Comment by IHIutch** [comment]
Thanks for the thorough explanation!
