### ISSUE TITLE
Render prop for the RAC DatePicker results in error

### ISSUE THREAD

**Issue by brandonpittman** [adobe/react-spectrum#4521]
### Discussed in https://github.com/adobe/react-spectrum/discussions/4516

<div type='discussions-op-text'>

<sup>Originally posted by **brandonpittman** May 13, 2023</sup>
I'm trying to use the render prop on the DatePicker, but I keep getting this error:

```
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
```

I assumed this would work:

```tsx
export function Datepicker<T extends DateValue>({
  className,
  ...props
}: MyDatePickerProps<T>) {
  return (
    <DatePicker {...props} className={datepickerStyle}>
      {(values) => <div>{/* other elements /*}</div>}
    </DatePicker>
  );
}
```

But it's not working. Am I using it incorrectly?
</div>

**Comment by brandonpittman** [comment]
Spent hours trying to figure this out to no avail. The example from the docs, but using a render prop produces the error mentioned above. But I pulled the repo down, ran the tests, and the test for render props passes. 😭 

```tsx
                  <DatePicker>
                    {(values) => (
                      <>
                        <Label>Date</Label>
                        <Group>
                          <DateInput>
                            {(segment) => <DateSegment segment={segment} />}
                          </DateInput>
                          <Button>▼</Button>
                        </Group>
                        <Popover>
                          <Dialog>
                            <Calendar>
                              <header>
                                <Button slot="previous">◀</Button>
                                <Heading />
                                <Button slot="next">▶</Button>
                              </header>
                              <CalendarGrid>
                                {(date) => <CalendarCell date={date} />}
                              </CalendarGrid>
                            </Calendar>
                          </Dialog>
                        </Popover>
                      </>
                    )}
                  </DatePicker>
```

**Comment by brandonpittman** [comment]
I tried the latest nightly, but and the render prop errors go away, but then I get some weird type errors in the editor.
 
<img width="1019" alt="CleanShot 2023-05-15 at 5 03 30@2x" src="https://github.com/adobe/react-spectrum/assets/967145/c7c60b7c-aa34-4715-b95f-6cb3618ac58f">

<img width="870" alt="image" src="https://github.com/adobe/react-spectrum/assets/967145/2639fd57-9643-4a16-a358-b596664c28fe">

**Comment by brandonpittman** [comment]
Also getting hydration mismatches on the DateSegment ids on the nightly.

<img width="697" alt="image" src="https://github.com/adobe/react-spectrum/assets/967145/4b56a4f1-d5c8-422b-b198-1046ad6a016c">

**Comment by brandonpittman** [comment]
Lastly, the locale from the I18nProvider is being ignored…

**Comment by devongovett** [comment]
btw I'd guess that the type errors you saw with `@internationalized/date` are because somehow your package manager installed multiple different versions of that library. You might have to bump that one to nightly as well to make them match up.

**Comment by brandonpittman** [comment]
Nightly had a working DatePicker, but since I was running into others errors, I just patched the DatePicker locally after comparing the nightly to the latest release.
