### ISSUE TITLE
Blank rendering of Item component inside Menu (RAC)

### ISSUE THREAD

**Issue by eashish93** [adobe/react-spectrum#4523]
# 🐛 Bug Report 

Following the doc, I'm trying to use Dropdown Menu using the following code:
```jsx
import {MenuTrigger, Button, Popover, Menu, Item} from 'react-aria-components';

<MenuTrigger>
  <Button aria-label="Menu">☰</Button>
  <Popover>
    <Menu onAction={alert}>
      <Item id="open">Open</Item>
      <Item id="rename">Rename…</Item>
      <Item id="duplicate">Duplicate</Item>
      <Item id="share">Share…</Item>
      <Item id="delete">Delete…</Item>
    </Menu>
  </Popover>
</MenuTrigger>
```
<img width="622" alt="Screenshot 2023-05-15 at 12 33 11 AM" src="https://github.com/adobe/react-spectrum/assets/13780952/944ef721-feba-40d8-a9fe-47edd8d828d4">

## 🤔 Expected Behavior

Should render the item data.

## 😯 Current Behavior
`Item` element showing blank data. Even using with dynamic collection (from doc), the result is same.

## 💻 Code Sample

 https://codesandbox.io/p/sandbox/heuristic-pike-hsizwj?file=%2Fapp%2Fpage.tsx%3A8%2C32

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | (RAC - 1.0.0-alpha.3)
| Browser          | Chrome 113
| Operating System | Mac

**Comment by snowystinger** [comment]
My initial thought was that you were seeing this https://github.com/adobe/react-spectrum/issues/4390

However, I see it with our nightly as well https://codesandbox.io/p/sandbox/romantic-shockley-vje51b?file=%2Fpackage.json%3A1%2C1

**Comment by Agile-fox** [comment]
@snowystinger It also happens for the combobox, here is a quick link in for the [codesandbox](https://codesandbox.io/s/nostalgic-tereshkova-mlb6f9?file=/src/App.tsx). Fun thing is that as it appears blank you can still select options with the keyboard.

**Comment by ducan-ne** [comment]
I got this too, and spent 4 hours figuring out that it was because of Next.js. I'm running the same code with Webpack/Vite and have had no problems.

**Comment by snowystinger** [comment]
> @snowystinger It also happens for the combobox, here is a quick link in for the [codesandbox](https://codesandbox.io/s/nostalgic-tereshkova-mlb6f9?file=/src/App.tsx). Fun thing is that as it appears blank you can still select options with the keyboard. It also happns on the 3.26.0 spectrum version 😢

@Agile-fox Your codesandbox is showing the problem because of ReactStrict Mode

**Comment by eashish93** [comment]
This is now fixed with latest release (alpha.4)
