### ISSUE TITLE
React-Aria Popover position is incorrect when rendered inside of a native dialog

### ISSUE THREAD

**Issue by ashleyryan** [adobe/react-spectrum#4539]
# 🐛 Bug Report 
 When a popover is used inside of a native dialog with a position of left or right, the `top` CSS attribute is calculated incorrectly

To render a popover inside/on top of a native dialog, `portalContainer` must be used on the Overlay with an element inside of the dialog. However, when the dialog is opened after scrolling down the page, the popover isn't positioned correctly when using the left or right positions. It's seems that the `top` CSS attribute gets calculated from the top of the page, but absolutely positioning an item inside of the dialog with a top position greater than the viewport's height renders it off the screen. For some reason this isn't an issue with the top or bottom position.

## 🤔 Expected Behavior

The popover should appear to the left or right of the trigger element. Interestingly, the arrow of the popover does appear in the correct position

## 😯 Current Behavior

The popover doesn't display because it's `top` position places it off the screen

https://codesandbox.io/s/distracted-zhukovsky-t6ooly?file=/src/App.tsx

## 🔦 Context

We're moving to react-aria from a different library and moving to the native dialog now that our browser supports it.

The native dialog element uses the special top-layer that is not a public API (yet) so the only way to render things above it is with an element inside of it and an `overflow: visible` CSS attribute. You can't use z-index shenanigans with it. 

## 💻 Code Sample

https://codesandbox.io/s/distracted-zhukovsky-t6ooly?file=/src/App.tsx

## 🌍 Your Environment

React 17 (and 18)
react-aria 3.21.0

**Comment by usetheplatform** [comment]
Hi, I've encountered a similar issue and looked at your example.

If I provide the boundaryRef to the PopoverTrigger element, only the left position is rendered on the right side.

<img width="1259" alt="image" src="https://github.com/adobe/react-spectrum/assets/58340039/ffe8c4a4-2823-454b-81d8-802ec6edbc1f">

**Comment by usetheplatform** [comment]
Btw, I was able to fix the issue by providing a ref to the dialog in `boundaryElement` in `useOverlayPosition`

**Comment by snowystinger** [comment]
Closing as it seems this is working. We can reopen if there is more. Thank you!
