### ISSUE TITLE
Description/ErrorMessageProps from useTextField (useField) returning undefined

### ISSUE THREAD

**Issue by binaryartifex** [adobe/react-spectrum#4541]
# 🐛 Bug Report 

## 🤔 Expected Behavior
Description and error message props from useField (using useTextField as an example) should return ID's associated with those props.

## 😯 Current Behavior
There is some re-rendering wierdness occuring with the hooks that provide the error/description props. a simple console log shows values are indeed provided, however immediately, sometimes several more re-renders occur and the values are suddenly undefined.

## 🔦 Context
Any error or description based fields are no longer associated with my input fields because no id's are generated connecting the two.

## 💻 Code Sample

[codesandbox](https://codesandbox.io/s/serene-night-ojxdsp?file=/src/text-field.tsx:228-244)

open console and see where values are provided then immediately undefined.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.23.1 
| Browser          | chrome v113.0.5672.93
| Operating System | windows 11

**Comment by LFDanLu** [comment]
useField uses [useSlotId](https://github.com/adobe/react-spectrum/blob/82c55f937128580e3459f038e8ec01dfa9db947e/packages/%40react-aria/label/src/useField.ts#L35-L36) to generate the ids for the description/error message, which checks to see if the id is being used in the DOM and will return undefined if not. The thought process here is that if you don't actually have an description/error message then you don't need those ids for your field's `aria-labelledby` attribute. 

If you attach those description/error props to a element, they [won't return undefined](https://codesandbox.io/s/recursing-voice-uqnbhf).

**Comment by binaryartifex** [comment]
cheers mate, makes sense now.
