### ISSUE TITLE
Cannot convert ECMASCRIPT_2018 feature "RegExp named groups" to targeted output language.

### ISSUE THREAD

**Issue by RambabuPatina** [adobe/react-spectrum#4542]
# 🐛 Bug Report 
Hi Team, We are using @internationalized/date library and facing a compile issue in a fulcro app (clojurescript based) which is compiling with [shadow-cljs](https://shadow-cljs.github.io/docs/UsersGuide.html#_introduction). There is a configuration (`:compiler-options {:output-feature-set :es5}`) in shaadow-cljs.edn there we need the output feature to be 'es5' in order to compatible with our internal react libraries. I have checked with shadow-cljs author and there is no way to skip the error. The compilation error getting as,
```
Closure compilation failed with 1 errors
--- node_modules/@internationalized/date/dist/main.js:1169
Cannot convert ECMASCRIPT_2018 feature "RegExp named groups" to targeted output language.
```
If we set the output feature to :es8 the error is going away but our components are not working. Could you please fix if it can be compatible to es5

## 🤔 Expected Behavior

Should not throw compilation error

## 😯 Current Behavior

The compilation error getting as,
```
Closure compilation failed with 1 errors
--- node_modules/@internationalized/date/dist/main.js:1169
Cannot convert ECMASCRIPT_2018 feature "RegExp named groups" to targeted output language.
```

## 🔦 Context
It's impacting our app to consume our internal design systems

## 💻 Code Sample
If we comment below line in the source code in node_modules, it is working
```
const $4c32e2d98e5a5134$var$ABSOLUTE_RE = /^(\d{4})-(\d{2})-(\d{2})(?:T(\d{2}))?(?::(\d{2}))?(?::(\d{2}))?(\.\d+)?(?:(?:([+-]\d{2})(?::(\d{2}))?)|Z)$/;
const $4c32e2d98e5a5134$var$DATE_TIME_DURATION_RE = /^$/;
//const $4c32e2d98e5a5134$var$DATE_TIME_DURATION_RE = /^((?<negative>-)|\+)?P((?<years>\d*)Y)?((?<months>\d*)M)?((?<weeks>\d*)W)?((?<days>\d*)D)?((?<time>T)((?<hours>\d*[.,]?\d{1,9})H)?((?<minutes>\d*[.,]?\d{1,9})M)?((?<seconds>\d*[.,]?\d{1,9})S)?)?$/;
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @internationalized/date  | 3.2.0 |
| Browser          | Chrome Version 112.0.5615.137 |
| shadow-cljs | 2.14.5 |
| react | 17.0.1 |
| org.clojure/clojurescript | 1.10.914 |
| com.fulcrologic/fulcro | 3.4.14 |

## 🧢 Your Company/Team

Appfire/Publishing team

**Comment by snowystinger** [comment]
Closing as our tsconfig is now correct in stating we rely on this syntax.
