### ISSUE TITLE
Doesn't return anchorKey :  undefined currentKey :  undefined

### ISSUE THREAD

**Issue by Kristaps006** [adobe/react-spectrum#4543]
# 🐛 Bug Report 

 

Bellow I have a async list where I fetch a data and set selectedKeys on `checkbox` 

`  let list = useAsyncList({
    async load() {
      const myUser = await getMyUser({ bearerToken });
      const customerId = myUser?.customerRelations[0]?.customerId;
      const data = await getFavListsOverview({ bearerToken, customerId });
      const items =
        data?.map((item) => ({
          name: item.name ?? '',
          id: item.id ?? '',
          items: item.items ?? undefined,
        })) ?? [];
      const selected = items.filter((item) => item.items);
      return {
        items,
        selectedKeys: selected.map((item) => item.id),
      };
    },
    getKey: (item) => item.id ?? '',
  });`
  
Here is my async list, that I am trying to pass into `GridList`  that uses `useGridList` hooks.
`    <GridList
          items={list.items} 
          selectionMode="multiple"
          aria-label="Select a favorite list"
          selectedKeys={list.selectedKeys}
          onSelectionChange={list.setSelectedKeys}
        >
          {(item) => (
            <Item aria-label="grid-item" key={item.id}>
              {item.name}
            </Item>
          )}
        </GridList>`
        

## 🤔 Expected Behavior

when item is  `list.selectedKey` it will return `anchorKey `and `currentKey` with current.target.id  on the item. 

When item is unselected from `list.selectedKey`  it returns `anchorKey `and `currentKey` as `undefined`

`anchorKey `and `currentKey`  should always return an  `id` of the item you have selected or unselected 
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
I'm having trouble following your issue. Would you be willing to put it into a codesandbox with steps on how to reproduce the issue?

**Comment by Kristaps006** [comment]
I have made a quick example [https://codesandbox.io/s/ecstatic-noyce-utlowq?file=/src/App.js](url)
 
where I console.log `list.selectedKey.currentKey`. as you notice it returns `undefined`. when you unselect the chekcbox. 
So there is no way of sending a request on toggle, since I don't know what item I have unselected.

**Comment by snowystinger** [comment]
I see, on first render + interaction, it returns undefined. Once you interact a second time, it does have the correct key. Is that what you mean?
Seems like a bug. Thank you for providing the codesandbox.

**Comment by Kristaps006** [comment]
Yes, that is correct.
Thank you for looking into it

**Comment by devongovett** [comment]
`anchorKey` and `currentKey` are internal implementation details, not public API. What are you trying to achieve?

**Comment by Kristaps006** [comment]
I am trying to make a call when key is unselected. I need to know `id` to make a call.

**Comment by devongovett** [comment]
Neither of those properties represent the key that was last unselected. You'd need to diff the previous selectedKeys with the new one in the onSelectionChange to determine that. Note that there may be multiple keys selected or unselected at a time.

**Comment by Kristaps006** [comment]
In my case I am getting set of `selectedKeys` that can be multiple `selectedKeys` as mentioned. However, when I `uncheck` ( my case I am using ` useGridLis`)  , I don't have any way to determine what `key` I have `uncheked` . On regular checkField I would use `current.target`. However I can see that` onSelectionChange((key)=> console.log(key) ) `
key returns `currentTarget`  with the key correct  id I need to make make a call. 
Hope that clarifies.
Feels a heavy walk around to diff the previous selectedKeys with the new one in onSelectionChange if `currentKey` actually holds the value I need

**Comment by devongovett** [comment]
As I mentioned, multiple keys can be selected or deselected at the same time. For example, the user may select and deselect ranges of items. Therefore a single key is not enough to determine what changed. You'd need to compare the sets.

**Comment by LFDanLu** [comment]
Closing for now, let us know if the above doesn't work for you.
