### ISSUE TITLE
React Aria useSelect docs hidden select of disabled select unexpectedly focused by keyboard navigation

### ISSUE THREAD

**Issue by danvim** [adobe/react-spectrum#4546]
# 🐛 Bug Report 

On the useSelect page, hidden textboxes of disabled select can be focused using tab-navigation with no visual feedback.

## 🤔 Expected Behavior

Hidden textbox should not be focused if button is not focusable.

## 😯 Current Behavior

Disabled button is not focused and hidden textbox is focused.

**Expected focus**

![image](https://github.com/adobe/react-spectrum/assets/5255292/b05729ee-07f4-4894-8d21-b5f45314defc)

**Expected blur**

![image](https://github.com/adobe/react-spectrum/assets/5255292/6094dc17-437c-428d-8c7b-72342036a317)

**Unexpected focus on textbox when select `isDisabled`**

Notice `focused=true` in the following screenshot.

![image](https://github.com/adobe/react-spectrum/assets/5255292/868d2899-49f3-48aa-ae3b-2bec1ec92c33)

## 💁 Possible Solution

Not sure.

## 🔦 Context

While tab navigating a select component built like one in docs, tab navigating over disabled selects provide no visual feedback.

## 💻 Code Sample

https://react-spectrum.adobe.com/react-aria/useSelect.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria | 3.24.0 |
| Browser          | Edge/Firefox |
| Operating System | Windows |

**Comment by LFDanLu** [comment]
Thanks for catching this. I believe we just need to propagate Select's `isDisabled` to the HiddenSelect, I'll open a PR shortly.

**Comment by danvim** [comment]
@LFDanLu Thanks Daniel :)
