### ISSUE TITLE
[useColorSliderState] Unknown color channel: hue

### ISSUE THREAD

**Issue by dbrxnds** [adobe/react-spectrum#4561]
# 🐛 Bug Report 

`useColorSliderState` throws an error that `hue` is not a valid color channel. This also happens in react-spectrums own UI library

## 🤔 Expected Behavior

It shouldn't throw an error for that as described in the docs.

## 🔦 Context

Unable to use ColorSlider now.

## 💻 Code Sample

https://codesandbox.io/s/wizardly-tree-xr3yrh?file=/src/App.tsx

**Comment by devongovett** [comment]
You need to use an `hsl` color if you want to use the hue channel. In your example, you've provided an RGB color. Something like this should work.

```js
useColorSliderState({ channel: "hue", defaultValue: "hsl(0, 100%, 50%)" });
```

**Comment by dbrxnds** [comment]
That makes sense, got it to work. Thanks @devongovett
