### ISSUE TITLE
DateRangePicker(react-aria-components) Render prop passes function to div's children

### ISSUE THREAD

**Issue by aspirisen** [adobe/react-spectrum#4572]
# 🐛 Bug Report 

For some reason when you use render prop in DateRangePicker the function then goes into children prop

## 🤔 Expected Behavior

Render props content should be used as children

## 😯 Current Behavior

The render prop function goes into children prop and nothing is displayed

## 🔦 Context

In the source code there is a self-closing tag, assuming that children will be taken from `renderProps` object
<img width="541" alt="image" src="https://github.com/adobe/react-spectrum/assets/3620639/54253944-98c0-495a-99e5-32b5ae562098">

However in transpiled code we can see explicit `props.children` usage and thus the children from `renderProps` are not used
<img width="471" alt="image" src="https://github.com/adobe/react-spectrum/assets/3620639/53520355-752d-4e5b-bfaa-8d1ba3c066d1">
<img width="794" alt="Pasted Graphic" src="https://github.com/adobe/react-spectrum/assets/3620639/48b38528-02f9-4886-a668-968b3491fd17">

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria-components   | 1.0.0-alpha.3

**Comment by snowystinger** [comment]
I think this is a duplicate of https://github.com/adobe/react-spectrum/issues/4369, which was fixed by https://github.com/adobe/react-spectrum/pull/4385. Could you try the nightly version?

**Comment by aspirisen** [comment]
@snowystinger yes, it works in nightly version, thanks 👍
