### ISSUE TITLE
add range component for react-aria-components Slider

### ISSUE THREAD

**Issue by meesvandongen** [adobe/react-spectrum#4578]
# 🙋 Feature Request

Add a Range component, similar to radix ui's Slider Range https://www.radix-ui.com/docs/primitives/components/slider#range. This would allow users to apply different stylings to what is and what is not "selected".

i.e. the white part in this image overlaying the track.
![image](https://github.com/adobe/react-spectrum/assets/35409045/e65b805e-b620-4202-a280-206d1cf6966e)

**Comment by snowystinger** [comment]
I think that would be purely visual and therefore expected that the component implementor would handle that. You could do something like this:
https://codesandbox.io/s/stoic-joana-wh80yw?file=/src/App.js

We could consider exposing some other data to make it so you don't need to do the calculation, but I think you can work around that for now.

**Comment by meesvandongen** [comment]
That does make sense. So in general the direction for react aria components is that it should only implement the strict necessities? 

Anyway, I will take your suggestion, thanks.

**Comment by devongovett** [comment]
There's an example here that shows how to do this with render props as well: https://github.com/adobe/react-spectrum/blob/main/examples/rac-tailwind/src/App.js#L368
