### ISSUE TITLE
Calendar: Wrong first day of week for Australian Locale

### ISSUE THREAD

**Issue by shobokshy** [adobe/react-spectrum#4585]
# 🐛 Bug Report 

Viewing the [`Calendar` component](https://react-spectrum.adobe.com/react-spectrum/Calendar.html) or using any of the underlying Stately hooks returns Sunday as first day of the week for `en-AU` where as it should be Monday.

## 🤔 Expected Behavior

To show Monday as first day of week

## 😯 Current Behavior

Its showing Sunday as first day of week

## 💁 Possible Solution

A possible fix is to include `AU` in this list https://github.com/adobe/react-spectrum/blob/main/packages/%40internationalized/date/src/weekStartData.ts

Or get an updated version of the list from:
https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-core/supplemental/weekData.json

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @internationalized/date   | 3.2.0
| Browser          | Safari 16.4
| Operating System | macOS Ventura 13.3.1 (a)

**Comment by LFDanLu** [comment]
Thanks for the heads up!

**Comment by rvramesh** [comment]
Can I work on this?
