### ISSUE TITLE
Select component fails to open when the items array is empty

### ISSUE THREAD

**Issue by AinaVendrell** [adobe/react-spectrum#4589]
# 🐛 Bug Report 

I have created a select component using the `useSelectState` and the `useSelect` hook following [this example](https://react-spectrum.adobe.com/react-aria/useSelect.html#usage). This component includes a popover with a header that dynamically adjusts based on the number of items present. However, the select component fails to open when the items array is empty.

## 🤔 Expected Behavior

I would expect that when the user clicks the button to open the select, the `isOpen` state should transition to true regardless of whether the items array is empty.

## 😯 Current Behavior

The `isOpen` property of the state keeps being false if there are no items

## 💻 Code Sample

https://codesandbox.io/s/dry-shape-svjys6?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
We have an explicit condition [here](https://github.com/adobe/react-spectrum/blob/61d241ebbb09d169dbf79d166646dd9fcedbfb97/packages/%40react-stately/select/src/useSelectState.ts#L52-L61) that prevents the open state from changing if the select doesn't have any items to display. Mind sharing your use case for wanting to open the dropdown when there aren't any items to show?

**Comment by snowystinger** [comment]
Maybe if the select doesn't have any options it should be disabled?

**Comment by AinaVendrell** [comment]
In the component, I have included an information section that appears at the top of the dropdown list. This section is designed to provide the user with an understanding of how selecting a particular value would affect the behavior of the application.

In cases where there are no items available to display in the dropdown, instead of simply disabling the select component, I would like to provide feedback to the user about why the list is empty and how they can add items to it. To offer guidance to the users, rather than leaving them confused or unsure about the next steps.

**Comment by snowystinger** [comment]
That makes sense and it's good to explain why something might be empty or disabled. What if, instead of the select, which I don't think can have that kind of extra markup inside of its options list, you replaced the empty select with a button? It could even look like the select, and when opened, it displayed a popover with the info? If that info should still be there when the select has options, then it might be better to look into a pattern such as our ContextualHelp https://spectrum.adobe.com/page/contextual-help/

**Comment by AinaVendrell** [comment]
Thanks for the suggestion! I will try implementing your idea of replacing the empty select with a button.
