### ISSUE TITLE
Add AppShell layout

### ISSUE THREAD

**Issue by prabirshrestha** [adobe/react-spectrum#4604]
# 🙋 Feature Request

Add an `<AppShell />` component similar to the ones found in mantine.

## 🤔 Expected Behavior

* Should support header, left bar, right bar, footer with main content.
* Everything should be optional.
* Should support responsive design.
* Allow to resize left bar and right bar. (ex: file explorer for tree view on left and preview on right).

## 😯 Current Behavior

Not available

## 💁 Possible Solution

Write your own.

## 🔦 Context

Almost every app starts with a layout whether it has header, nav bar, main content, aside or footer. While it is possible to do it with `<Flex/>` or `<Grid/>` component we still need to write extra code to make it responsive.

## 💻 Examples

https://mantine.dev/core/app-shell/

**Comment by snowystinger** [comment]
This isn't an Aria pattern. If you're from Adobe, please reach out internally for some solutions. If you aren't from Adobe, you can build this utilizing components built on React Aria and React Aria Components.
