### ISSUE TITLE
Using <Suspense/> inside <SSRProvider/> causes hydration error

### ISSUE THREAD

**Issue by chungwu** [adobe/react-spectrum#4607]
# 🐛 Bug Report 

Using `<Suspense/>` inside `<SSRProvider/>` cases this error:

```
Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.
```
AFAICT, this is caused by the `setState()` [in SSRProvider](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/ssr/src/SSRProvider.tsx#L71) in the layout effect which updates the value of the `SSRContext`; since `<Suspense/>` is a descendant and the context just changed, React has to re-render the content inside `<Suspense/>` as it can't rely on the server-generated html.

Here's a quick repro using Next.js: https://codesandbox.io/p/sandbox/affectionate-cache-01vp9h?file=%2Fpages%2Findex.tsx%3A8%2C20

## 🤔 Expected Behavior

No errors

## 😯 Current Behavior

```
Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.
```

## 💁 Possible Solution

Maybe use `startTransition` for the `setIsSsr()` call?  But not sure if that messes anything else up.

## 💻 Code Sample

https://codesandbox.io/p/sandbox/affectionate-cache-01vp9h?file=%2Fpages%2Findex.tsx%3A8%2C20

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.25.0
| Next          | 13.4.1

## 🧢 Your Company/Team

Plasmic

**Comment by devongovett** [comment]
I have a PR to switch to React's builtin useId, which should remove the need for SSRProvider entirely if you're using React 18. Seems like that's the best way forward. #4347
