### ISSUE TITLE
[useDatePickerState]: Cannot use 'in' operator to search for 'timeZone' in null

### ISSUE THREAD

**Issue by artaommahe** [adobe/react-spectrum#4619]
# 🐛 Bug Report 

- open an example fora date picker https://codesandbox.io/s/white-breeze-rer8g2?file=/src/DatePicker.js
- open first date picker
- select a hour segment
- clear it (press backspace 2 times)
- see an error `Cannot use 'in' operator to search for 'timeZone' in null`

Also type for `DatePickerState.timeValue` is wrong - field can be null, but the type is `DatePickerState.timeValue: TimeValue`. Same with `DateRangePickerState.timeRange`.

## 🤔 Expected Behavior

no error and proper type of the field `DatePickerState.timeValue: TimeValue | null`

## 😯 Current Behavior

```
TypeError
Cannot use 'in' operator to search for 'timeZone' in null
    at commitValue (https://rer8g2.csb.app/node_modules/
react-stately/datepicker/dist/module.js:122:26
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.21.0/3.25.0 | 
| Browser          | Chrome |
| Operating System | MacOS |

**Comment by LFDanLu** [comment]
Reproduced in the Spectrum DatePicker as well. Looks like the TimeField [onChange](https://github.com/adobe/react-spectrum/blob/06e63d3ae7898b8cd81fdb6fa87b763faf2054bf/packages/%40react-stately/datepicker/src/useTimeFieldState.ts#L51) is calling [selectTime](https://github.com/adobe/react-spectrum/blob/06e63d3ae7898b8cd81fdb6fa87b763faf2054bf/packages/%40react-stately/datepicker/src/useDatePickerState.ts#L118) with null, resulting the observed break [here](https://github.com/adobe/react-spectrum/blob/06e63d3ae7898b8cd81fdb6fa87b763faf2054bf/packages/%40react-stately/datepicker/src/useDatePickerState.ts#L93). Will have to handle the null case in that line but also make sure not to clear the timezone in the TimePicker
