### ISSUE TITLE
Picker: In windows OS, menu border is getting overlapped by scrollbar edges

### ISSUE THREAD

**Issue by minaseem** [adobe/react-spectrum#4632]
# 🐛 Bug Report 
If the picker menu has a scroll, border on the top right, and bottom right corners are getting hidden.

# 📺 Screenshot

![dropdown screenshot](https://github.com/adobe/react-spectrum/assets/5484032/bc9add90-e7a4-498e-8389-2c969ea5dcca)

## 🤔 Expected Behavior
The border should be clearly visible on all sides

## 😯 Current Behavior
The border is discontinued on corners.

## 💁 Possible Solution
One of the possible solution could be to add some padding a top and bottom of the menu.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.27
| Browser          | Chrome 114
| Operating System | Windows

## 🧢 Your Company/Team
Adobe

AJO Reporting Team

**Comment by reidbarber** [comment]
I think this is expected behavior Windows + Chrome. I think any changes might have unwanted side effects, or affect other platforms.

**Comment by minaseem** [comment]
@reidbarber Thanks for your input. Please close this ticket if you feel that it is the expected behaviour.

**Comment by matthewdeutsch** [comment]
@minaseem I don't anticipate this issue to be investigated further anytime soon - we'll keep this item open until we get a chance to determine if there's any action we can take

**Comment by devongovett** [comment]
Wasn't this fixed in the latest release? I think part of #4050.
