### ISSUE TITLE
Modals not working in Next 13

### ISSUE THREAD

**Issue by reinierkaper-carewell** [adobe/react-spectrum#4654]
# 🐛 Bug Report 

I'm trying the modals example implementation, but when I press the button to show the modal, React throws hot reload errors:
```
Warning: Cannot update a component (`HotReload`) while rendering a different component (`ModalExample`). To locate the bad setState() call inside `ModalExample`:
```

## 🤔 Expected Behavior

Modals to work

## 😯 Current Behavior

Modal doesn't show up but throws a Hot Reload error instead.

## 💁 Possible Solution

No clue :)

## 🔦 Context

N/A

## 💻 Code Sample

Followed this: https://react-spectrum.adobe.com/react-aria/useModalOverlay.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.24.0
| Browser          | Chrome
| Operating System | MacOs

**Comment by reinierkaper-carewell** [comment]
I think the main issue is this line: `{React.cloneElement(children(state.close), overlayProps)}`
I'm pretty sure `children` is not a function.

**Comment by snowystinger** [comment]
Children is a function if you wrote the same example. Could you provide a codesandbox or some way of reproducing?

```
<ModalTrigger label="Open Dialog">
  {close => // this is the children as a function
    <Dialog title="Enter your name">
      <form style={{display: 'flex', flexDirection: 'column'}}>
```

**Comment by reinierkaper-carewell** [comment]
Ohhh I see, I must've missed that part, thanks!
Will close for now!
