### ISSUE TITLE
Leading zero is truncated for day in New Zealand region where it shouldnt be.

### ISSUE THREAD

**Issue by danyo-moe** [adobe/react-spectrum#4668]
# 🐛 Bug Report 

Leading zero's in day component for regions such as New Zealand should not be truncated

https://share.cleanshot.com/RLcHSYq9

## 🤔 Expected Behavior
Leading zero should not be truncated

It is truncated when typed or selected from date picker
## 😯 Current Behavior
It truncates the leading zero

It shouldnt truncate the leading zero.

I can replicate on the top date picker on example site
https://react-spectrum.adobe.com/react-spectrum/DatePicker.html

## 🔦 Context

Enter a date. UX look / feel issue

## 💻 Code Sample

https://react-spectrum.adobe.com/react-spectrum/DatePicker.html

## 🌍 Your Environment
Incognito window. 
https://react-spectrum.adobe.com/react-spectrum/DatePicker.html

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | [Latest on demo site.](https://react-spectrum.adobe.com/react-spectrum/DatePicker.html)
| Browser          | Chrome Version 114.0.5735.106 (Official Build) (arm64)
| Operating System | MacOS 13.4

## 🧢 Your Company/Team
Ministry of Education

Web

**Comment by devongovett** [comment]
This is how the browser's date formatter formats dates by default in the `en-NZ` locale:

```js
new Intl.DateTimeFormat('en-NZ').format(new Date(2023, 0, 1))
// => "1/01/2023"
```

These formats come from the Unicode CLDR. You can see the format definition here: https://github.com/unicode-org/cldr/blob/main/common/main/en_NZ.xml#L39

**Comment by devongovett** [comment]
Digging through this further, this seems like a bug in CLDR to me. It's weird that it has a leading zero for the month but not the day. I couldn't reproduce this in other locales like `en-AU` either. Going through the git blame in that xml file linked above seems to show that this has been the same format for over 20 years though. I'll see about filing an issue over there to get it fixed. But that might take some time to make its way into browsers and operating systems.

In the meantime, we could consider adding a prop to override the format to always include leading zeros. A similar prop was requested in #4247. The danger is that hard coding this in an app may override locale-specific preferences, so I think using unicode's defined formats by default and only overriding as a last resort would be our recommendation.

**Comment by danyo-moe** [comment]
Hmm apologies for the confusion. Is there a way to configure it to add the leading zero. Rightly of wrongly for the time being we have standardised on short date format dd/mm/yyyy

**Comment by danyo-moe** [comment]
oops you reply too fast. yeah our use case is an internal ish web application that is only intended for use in NZ so having a way to override the format (against standards) is probably not a big issue for us atm.
