### ISSUE TITLE
[Toast] Behaviour with multiple toasts in a queue is confusing

### ISSUE THREAD

**Issue by dsmmcken** [adobe/react-spectrum#4673]
# 🙋 Feature Request

Are there any plans to improve the toast spectrum component experience around having multiple toasts in a queue at once? I find it confusing as user if more than one toast is triggered at once. There's no visual indication/animation when a new toast enters, it just appears directly on top, and there is no visible change when it is dismissed on click (fades out overtop of an underlying toast that could look the same).  

## 🤔 Expected Behavior

Additional toasts visibly animate in and visibly animate out.

## 😯 Current Behavior

Toasts appear directly on top of each other, one at time, with no visually distinct animation. It is not at all clear if you click to dismiss a toast, that it has actually been dismissed if there is another similar toast below it.

## 💁 Possible Solution

Expose maxVisibleToasts/ToastQueue options as a prop on <ToastContainer> or maybe allow a global ToastQueue constructor to be passed in directly to toastcontainer? Or even changing the dismiss animation from fade to slide down might help, so the user can tell a dismiss actually happened if it's the same message underneath.

https://github.com/adobe/react-spectrum/blob/e892f4b5a2a94044c09eb8a9c232268b31344e87/packages/%40react-spectrum/toast/src/ToastContainer.tsx#L38

## 🔦 Context

I can't guarantee that only one toast will occur at a time, a user could perform an action that triggers a toast faster than the previous toast is dismissed.

## 💻 Examples

Click to trigger the same toast [toast](https://react-spectrum.adobe.com/react-spectrum/Toast.html) multiple times, note the lack of change on enter. Click the dismiss multiple times, note the lack of perceptible exit animation.

**Comment by dsmmcken** [comment]
I guess the guidelines are against multiple toasts being visible at once, so my issue is probably more with the lack of visible animation occurring between toasts appearing/dismissing when multiple are in queue.

https://spectrum.adobe.com/page/toast/#Multiple-toasts

**Comment by reidbarber** [comment]
Closed by https://github.com/adobe/react-spectrum/pull/5933
