### ISSUE TITLE
[useViewportSize] `window is not defined` in a Remix application

### ISSUE THREAD

**Issue by marg0l** [adobe/react-spectrum#4676]
# 🐛 Bug Report 

In this file: `https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/useViewportSize.ts` there is a check to make sure the `window` is defined before using browser API's, however [Remix](https://remix.run/docs/en/1.17.1/pages/gotchas#typeof-window-checks) supports Deno which supports `window` on the server and therefore this check is not sufficient and the Remix docs suggest using `typeof document === "undefined"`.

## 🤔 Expected Behavior

Should not break in SSR

## 😯 Current Behavior

Breaks in SSR

## 💁 Possible Solution

Use `typeof document === "undefined"` instead of `typeof window !== 'undefined'`.

## 🔦 Context

Trying to render the `ModalOverlay`, `Modal` and `Dialog` components in the context of a Remix application

## 💻 Code Sample

```tsx
type DrawerProps = {
  children: React.ReactNode;
};

export default function Drawer({ children }: DrawerProps) {
  return (
    <ModalOverlay
      isOpen
      isDismissable
      className="data-[entering]:animate-background-fade-out data-[exiting]:animate-background-fade-in fixed inset-0 backdrop-brightness-50">
      <Modal className="data-[entering]:animate-slide-in data-[exiting]:animate-slide-out fixed top-0 bottom-0 right-0 w-2/5 bg-white p-8">
        <Dialog>
          {({ close }) => (
            <div className="text-black">
              {children}
              <Button onPress={close}>Close</Button>
            </div>
          )}
        </Dialog>
      </Modal>
    </ModalOverlay>
  );
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria-components   | 1.0.0-alpha.4
| Browser          | Chrome 
| Operating System | MacOS

**Comment by snowystinger** [comment]
Thanks for the issue. I'm actually surprised this hasn't come up before, we use that check in a few places, including in our SSR Provider. I assume you can use ClientOnly in order to work around this for now? Much like this example has done https://github.com/DanielSmith/remix-tailwind-aria ?

Would you be willing to put together a PR?

**Comment by marg0l** [comment]
Hi, yes we are using ClientOnly for now and it works great. I'll create a PR no problem

**Comment by reidbarber** [comment]
Closed by https://github.com/adobe/react-spectrum/pull/4688
