### ISSUE TITLE
useTablistState not working in React Storybook

### ISSUE THREAD

**Issue by jhowell-droit** [adobe/react-spectrum#4708]
# 🐛 Bug Report 

Hi, I am currently building a component library in React written in Typescript.
I'm working on a Tabs component and am trying to make use of the `useTabListState()` hook from 'react-stately'. 
The component works as expected in a test Vite React application I have in my project, but in Storybook v6.5.16 the tabs don't render and in the console is the following error:

"import.mjs:207 Uncaught Error: Unknown element <[object Object]> in collection.
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (import.mjs:207:1)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (import.mjs:163:1)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (import.mjs:291:1)
    at Generator.next (<anonymous>)
    at new $a02d57049d202695$export$d085fb9e920b5ca7 (import.mjs:84:1)
    at factory (import.mjs:114:1)
    at import.mjs:315:1
    at mountMemo (react-dom.development.js:17225:1)"

Any ideas?

## 💻 Code Sample

Here's my TSX file:

```
import { AriaTabListProps, AriaTabProps, useTab } from 'react-aria';
import { TabListState, useTabListState } from 'react-stately';
import { Orientation, Node } from '@react-types/shared';
import styles from './index.module.css';

export interface TabProps {
  item: Node<AriaTabProps>;
  state: TabListState<AriaTabProps>;
  orientation?: Orientation;
}

const Tab = ({ item, state }: TabProps) => {
  const { key, rendered } = item;
  const ref = useRef(null);
  const { tabProps } = useTab({ key }, state, ref);
  return (
    <div className={styles['c-tabs__tab']} ref={ref} {...tabProps}>
      {rendered}
    </div>
  );
};

const Tabs = (props: AriaTabListProps<AriaTabProps>) => {
  const state = useTabListState<AriaTabProps>(props);
  console.log(state);
  return (
    <div className={styles['c-tabs']}>
      <div className={styles['c-tabs__list']}>
        {[...state.collection].map((item) => (
          <Tab key={item.key} item={item} state={state} />
        ))}
      </div>
    </div>
  );
};

export default Tabs;

```

and here's the `tabs.stories.mdx` file:

```
import { ArgsTable, Canvas, Meta, Story } from '@storybook/addon-docs';
import { Item } from '@react-stately/collections';
import Tabs from '../tabs';

<Meta title="Droit/Components/Tabs" component={Tabs} />

export const Template = (args) => (
  <Tabs {...args}>
    <Item key="FoR" title="Founding of Rome">
      Arma virumque cano, Troiae qui primus ab oris.
    </Item>
    <Item key="MaR" title="Monarchy and Republic">
      Senatus Populusque Romanus.
    </Item>
  </Tabs>
);

# Tabs

<ArgsTable story="Playground" />

## Default

<Canvas>
  <Story name="Playground">
    {Template.bind({})}
  </Story>
</Canvas>

```
 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
React Aria - v3.23.1
React Stately v.322.0
react-types v3.18.1
Mac OS 
Google Chrome Version 114.0.5735.133 (Official Build) (arm64)

**Comment by snowystinger** [comment]
That looks a bit different from our example https://react-spectrum.adobe.com/react-aria/useTabList.html (no tab panel for one thing) have you checked if something just got copied funny? Might be useful to put together a minimum reproduction either on codesandbox or a small github repo reproducing it or even a PR demonstrating it in our own storybook.

Our issue template has a codesandbox template you could get started with https://codesandbox.io/s/react-spectrum-template-syueo

**Comment by jhowell-droit** [comment]
I've tested it outside of Storybook as I put in the original post and the lack of tabpanel doesn't matter too much. With the TSX as it is above it just renders the tabs without any content (as you'd expect).

I've done a bit of extra debugging today though and have noticed that it works ok if I create the story as a TSX file. When inspecting the VirtualDom using React DevTools you can often see extra nodes added when the stories are MDX. I'm therefore wondering whether the MDX version has something in between the Tabs component and the Tab component whereas`useTabListState` is expecting these to be parent > child.

Having to write the story in TSX is not ideal as I use the `args` and `argTypes` a fair bit to demo the components. But in short, it seems to be a Storybook issue rather than something at your end.

**Comment by snowystinger** [comment]
`useTabListState` is just a hook, shouldn't care at all about how deeply the children are nested. However, if something got between Tabs and Item, that could be a problem. I'm not sure why an mdx file would add anything there.
I'm glad you have a workaround and am sorry it's not working with the mdx. If you should find anything else or begin thinking it's on our end again, a small github repo with a storybook with the mdx files turned on would be very helpful to us.
