### ISSUE TITLE
Provide `fromDate` or `fromEpoch` to create `ZonedDateTime`

### ISSUE THREAD

**Issue by jokull** [adobe/react-spectrum#4725]
# 🙋 Feature Request

I would love to be able to either `fromDate(date: Date, timeZone: string)` or `fromEpoch(value: number, timeZone: string)`. Unless I'm missing some way to do this in the current `@internationalized/dates` library?

Currently I'm doing `parseAbsolute(new Date(epoch).toISOString(), tz)`

**Comment by LFDanLu** [comment]
We'd be happy to expose those, would need to export them from [here](https://github.com/adobe/react-spectrum/blob/main/packages/%40internationalized/date/src/index.ts#L41) and add it to the docs.

**Comment by naveen2593kumar** [comment]
Hey @LFDanLu  and @jokull 

Do you guys mind if I can contribute on this ?

Please confirm so that I can continue with the changes and purpose a PR.
