### ISSUE TITLE
ZonedDateTime doesn't handle forward timezone transition correctly for some durations

### ISSUE THREAD

**Issue by longzheng** [adobe/react-spectrum#4733]
# 🐛 Bug Report 

While trying to fix https://github.com/adobe/react-spectrum/issues/4701 in PR https://github.com/adobe/react-spectrum/pull/4702 I discovered a bug with `ZoneDateTime` froward timezone transitions when trying to add a new test.

`ZonedDateTime` is designed to handle timezone transitions when adding duration https://react-spectrum.adobe.com/internationalized/date/ZonedDateTime.html#adding-and-subtracting-durations
> Adding and subtracting is time zone aware. When adjusting a date around a daylight saving time transition, the hour may be adjusted accordingly. For example, in the United States, adding one hour during a "spring forward" transition skips the 2 AM hour, and adding an hour in a "fall back" transition repeats the 1 AM hour. Under the hood, the UTC offset is changing instead.

The documentation example shows an example of adding a day which adjusts the hours

```ts
// A "spring forward" transition
let date = parseZonedDateTime('2020-03-07T02:00-08:00[America/Los_Angeles]');
date.add({days: 1}); // 2020-03-08T03:00-07:00[America/Los_Angeles]

```

This seems to work for some duration values, but not others.

Adding 1 day and 24 hours result in the same output.

Adding 2 days and 48 hours does not result in the same output. Adding "48 hours" adjusts the hour for the transition. Adding "2 days" does not adjust the hour.

<img width="644" alt="image" src="https://github.com/adobe/react-spectrum/assets/484912/09041a55-a64d-4100-a5f2-543e0bfb4d4f">

Similarly, adding "168 hours" adjusts the hour. Adding "7 days" does not.

## 🤔 Expected Behavior

Adding 2 days should adjust the spring forward transition the same as adding 48 hours.

```ts
// A "spring forward" transition
let date = parseZonedDateTime('2020-03-07T02:00-08:00[America/Los_Angeles]');
date.add({days: 2}); 
```

```ts
// A "spring forward" transition
let date = parseZonedDateTime('2020-03-07T02:00-08:00[America/Los_Angeles]');
date.add({hours: 48}); 
```

## 😯 Current Behavior

```ts
// A "spring forward" transition
let date = parseZonedDateTime('2020-03-07T02:00-08:00[America/Los_Angeles]');
date.add({days: 2}); 
// 2020-03-09T02:00:00-07:00[America/Los_Angeles]
// hour is not adjusted
```

```ts
// A "spring forward" transition
let date = parseZonedDateTime('2020-03-07T02:00-08:00[America/Los_Angeles]');
date.add({hours: 48}); 
// 2020-03-09T03:00:00-07:00[America/Los_Angeles]
// hour is adjusted
```

## 💁 Possible Solution

Not sure

## 🔦 Context

Trying to add a test to `ZonedDateTime.test.js` https://github.com/adobe/react-spectrum/blob/e783f0bb5df33425c26cc80aa20f292fbca24672/packages/%40internationalized/date/tests/ZonedDateTime.test.js#L17

## 💻 Code Sample

https://codesandbox.io/p/sandbox/eager-christian-76ltpw?file=%2Fsrc%2FApp.tsx%3A20%2C1-22%2C11

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.3.0
| Browser          | Chrome 114.0.5735.133 (Official Build) (arm64)
| Operating System | macOS 13.4.1

**Comment by devongovett** [comment]
You are correct that adding two days and adding 48 hours are difference, and I believe this is expected behavior. When adding days, the behavior is to preserve the hour so if it was at 8am before it'll still be 8am after even if the timezone offset changed. This would make sense if you were rescheduling an appointment to be one day later, for example. However, if you add 48 hours, we add exactly 48 hours from the starting time, which may mean that the resulting hour field changes. This matches the behavior in the upcoming [TC39 Temporal spec](https://tc39.es/proposal-temporal/docs/zoneddatetime.html#add) as well.

**Comment by longzheng** [comment]
@devongovett Ah thanks for the explanation. TIL about TC39.

For clarity, the original example of adding 1 day changes the hour because 02:00-07:00 would be invalid.

```ts
// A "spring forward" transition
let date = parseZonedDateTime('2020-03-07T02:00-08:00[America/Los_Angeles]');
date.add({days: 1}); // 2020-03-08T03:00-07:00[America/Los_Angeles]
```

The Temporal API produces the same result

```ts
Temporal.ZonedDateTime.from('2020-03-07T02:00-08:00[America/Los_Angeles]').add({days:1})
// 2020-03-08T03:00:00-07:00[America/Los_Angeles]
```
