### ISSUE TITLE
useNumberField: AriaNumberFieldProps type has no `name` property 

### ISSUE THREAD

**Issue by omarkhatibco** [adobe/react-spectrum#4744]
# 🐛 Bug Report 

I'm trying to use the `useNumberField` and I was passing name as props  but i got typescript warning

```ts
Argument of type '{ name: string; }' is not assignable to parameter of type 'AriaNumberFieldProps'.
  Object literal may only specify known properties, and 'name' does not exist in type 'AriaNumberFieldProps'.ts(2345)
```

btw, using `name` is being reflected in `inputProps`
## 🤔 Expected Behavior

to have `name` exported in types

## 😯 Current Behavior

`name` is not exported 

## 💁 Possible Solution

export  `name` to types

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria | 3.26.0 |
| Browser| latest.|
| Operating System | MacOS  |

**Comment by devongovett** [comment]
At the moment this is intentional because usually you'd want to submit an actual number value rather than a formatted string that depends on the user's locale. You could use an `<input type=hidden>` to do that. #4640 is a work in progress to make that built in.

**Comment by omarkhatibco** [comment]
thank you @devongovett, should I close this issue? and follow yours?
