### ISSUE TITLE
TypeError: Cannot destructure property 'scale' of '

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [adobe/react-spectrum#4751]
```
 error ..\..\node_modules\@react-spectrum\datepicker\dist\import.mjs (824:10) @ $04e96200274b03de$export$12ce2869ce471b1f
- error TypeError: Cannot destructure property 'scale' of '(0 , _react_spectrum_provider__WEBPACK_IMPORTED_MODULE_12__.useProvider)(...)' as it is null.
null
- error ..\..\node_modules\@react-spectrum\datepicker\dist\import.mjs (824:10) @ $04e96200274b03de$export$12ce2869ce471b1f
- error TypeError: Cannot destructure property 'scale' of '(0 , _react_spectrum_provider__WEBPACK_IMPORTED_MODULE_12__.useProvider)(...)' as it is null.
null```

**Comment by Tushar1729-k** [comment]
How did you fix this @hp8wvvvgnj6asjm7 ??

**Comment by snowystinger** [comment]
Usually this happens due to multiple copies of a package being installed, or a provider not being wrapped around your app.

**Comment by snowystinger** [comment]
@Tushar1729-k let us know if that fixed it or if you need more help. It may be helpful to reproduce the problem in a codesandbox or stackblitz so we can see what's going on as well and know if it's related to your setup or a bug on our end.

**Comment by vjchildress** [comment]
I experienced this and then fixed it. I had previously tried to install the @react-spectrum/datepicker as a stand-alone component and then realized I needed to install react-spectrum. I installed react-spectrum and ran into the error. It stopped giving me the error after I uninstalled the first @react-spectrum/datepicker package.
