### ISSUE TITLE
TableView with Zoom 150% on Windows crashes with Error: Maximum update depth exceeded

### ISSUE THREAD

**Issue by synox** [adobe/react-spectrum#4761]
# 🐛 Bug Report 

Our Adobe product uses `TableView` in a React Application. Our customers reported that the React application crashes when using Google Chrome with 150% zoom, only on Windows. We had to rollback the feature. 

## Reproduce

 - use a Windows 11 (VM). 
 - in System settings, open `Display`, set `Scale` to 150%, 
- Open Google Chrome, 
- open https://reactspectrum.blob.core.windows.net/reactspectrum/b57b3af44c345d456658e2895bb9244c65f0e7d3/storybook/index.html?path=/story/tableview--resizing-uncontrolled-static-widths
- if the error does not happen, resize the window a few times. 

The error happens sometimes on macOS, with Scrollbars always enabled, and 150% zoom in Chrome. 

also happens on 
 - https://reactspectrum.blob.core.windows.net/reactspectrum/b57b3af44c345d456658e2895bb9244c65f0e7d3/storybook/index.html?path=/story/tableview--resizing-uncontrolled-column-divider&providerSwitcher-express=false
 - https://reactspectrum.blob.core.windows.net/reactspectrum/b57b3af44c345d456658e2895bb9244c65f0e7d3/storybook/index.html?path=/story/tableview--resizing-uncontrolled-min-max&providerSwitcher-express=false
 - https://reactspectrum.blob.core.windows.net/reactspectrum/b57b3af44c345d456658e2895bb9244c65f0e7d3/storybook/index.html?path=/story/tableview--resizing-uncontrolled-some-not-allowed&providerSwitcher-express=false
 - https://reactspectrum.blob.core.windows.net/reactspectrum/b57b3af44c345d456658e2895bb9244c65f0e7d3/storybook/index.html?path=/story/tableview--resizing-uncontrolled-some-not-allowed&providerSwitcher-express=false
 - 

## 🤔 Expected Behavior

Zoom level should not influence component behavior. 

## 😯 Current Behavior

Crashes with Error message: 
> Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

<img width="1351" alt="Screenshot 2023-07-12 at 16 21 00" src="https://github.com/adobe/react-spectrum/assets/2250964/6b75b445-a490-454a-b7da-eff5d29bf609">

## 🔦 Context

This blocks an Adobe product feature. 

## 💻 Code Sample

https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/table/stories/Table.stories.tsx#L1467-L1494

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.22.0 |
| Browser          | Google Chrome Version 115.0.5790.13 (Official Build) (64-bit) |
| Operating System | Windows 11 |

## 🧢 Your Company/Team

Adobe/AEM

## 🕷 Tracking Issue (optional)

(Adobe internal)

**Comment by LFDanLu** [comment]
I'm unable to reproduce this on my own Windows 11 machine in 150% zoom after switching between the stories back and forth 30+ times. How frequently did this reproduce for you? Does this happen only in 3.22.0 or on latest (I assume latest since you were running the storybook locally?)

**Comment by synox** [comment]
I was able to reproduce this consistently after 2 clicks. I tested on browserstack.com with local network extension.

**Comment by synox** [comment]
Resizing the window seems to help, see attached video. I open the story outside of Storybook (iframe) in a new window. 

https://github.com/adobe/react-spectrum/assets/2250964/f5c4dd1e-fac0-45c0-9c97-b707018300fa

**Comment by LFDanLu** [comment]
Gotcha, got it to reproduce via resizing

**Comment by LFDanLu** [comment]
Looks to be the browser scrollbars flickering in and out causing the table to infinitely resize itself: https://www.loom.com/share/cd90c4ca54ca49248006939b0e2784c6. Feels similar to https://github.com/adobe/react-spectrum/issues/3329.

**Comment by synox** [comment]
Here is another example of a TableView that fails to render: 
```html
 <TableView width="size-3000" height="size-3600">
            <TableHeader>
                <Column key="name" allowsSorting={true}>
                    Name
                </Column>
            </TableHeader>
            <TableBody>
                <Row>
                    <Cell>2021406_Proposal</Cell>
                </Row>
                <Row>
                    <Cell>Budget Template</Cell>
                </Row>
                <Row>
                    <Cell>Onboarding</Cell>
                </Row>
                <Row>
                    <Cell>Welcome</Cell>
                </Row>
            </TableBody>
        </TableView>
```

**Comment by synox** [comment]
I confirm, the fixed version does not crash on windows.

**Comment by LFDanLu** [comment]
@synox Thanks for confirming that! The fix should go out with the upcoming release next week.

**Comment by LFDanLu** [comment]
@synox Just a fyi the fix was shipped with the release last week (8/9, version 3.29), let us know if you run into any issues!
