### ISSUE TITLE
Date Picker is not working for chinies locale as it is working for other language locale

### ISSUE THREAD

**Issue by 19akashsharma** [adobe/react-spectrum#4765]
# 🐛 Bug Report 

I was using DatePicker Component of adobe/react-spectrum. there is a issue in this date picker with **locale={"zh-CN"}** with chinese language only what happening is. when we are selecting date then we go for selecting time in chinese locale. when you enter hours then when you enter minute. it will and **GMT 5:30**  automatically  and focus come on hours . but this is not happening in other language locale.

https://github.com/adobe/react-spectrum/assets/127079016/4424684a-2b25-43c8-abb0-bb8e75a84a13

https://github.com/adobe/react-spectrum/assets/127079016/e6047f25-2f60-491a-9c20-43ff0b91f176

## 🤔 Expected Behavior

As it is working with other language locale, it should work with chinies locale as well.

## 😯 Current Behavior

I was using DatePicker Component of adobe/react-spectrum. there is a issue in this date picker with **locale={"zh-CN"}** with chinese language only what happening is. when we are selecting date then we go for selecting time in chinese locale. when you enter hours then when you enter minute. it will and **GMT 5:30**  automatically  and focus come on hours . but this is not happening in other language locale.

## 💻 Code Sample

```
import React, { useState } from "react";
import { Provider, defaultTheme } from "@adobe/react-spectrum";
import "./styles.css";
import { parseAbsoluteToLocal } from "@internationalized/date";
import { DatePicker } from "@adobe/react-spectrum";

export default function App() {
  const [date, setDate] = useState(undefined);
  const OnDateChange = (value) => {
    const iso = parseAbsoluteToLocal(new Date(value).toISOString());
    return setDate(iso);
  };

  const getValue = () => {
    if (date) {
      return date;
    }
    return undefined;
  };

  return (
    <Provider theme={defaultTheme}>
      <DatePicker
        label="Event date"
        value={getValue()}
        onChange={OnDateChange}
        granularity="minute"
      />
    </Provider>
  );
}
```

## 🧢 Your Company/Team

Adobe Life, ACC

**Comment by LFDanLu** [comment]
This is probably happening because the DatePicker goes from a base CalendarDateTime format to a ZonedDateTime once the user begins setting an actual time value. I'd suggest that you set a placeholder value with a ZonedDateTime so that the user can see what date format the DatePicker is accepting ahead of time like so: https://codesandbox.io/s/keen-volhard-p54tst?file=/src/App.js

**Comment by dannify** [comment]
Feel free to reopen with more information if this solution does not work for you.
