### ISSUE TITLE
Package Registry 404ing

### ISSUE THREAD

**Issue by alexmlee** [adobe/react-spectrum#4772]
# 🐛 Bug Report 

Trying to use the @react-stately package in CICD is failing due to a 404 
"https://registry.yarnpkg.com/@react-stately/table/-/table-3.9.0.tgz: Request failed \"404 Not Found\""

## 🤔 Expected Behavior

Hitting this endpoint should respond with a status code 200 and the package.

## 😯 Current Behavior

It has a 404 response

"https://registry.yarnpkg.com/@react-stately/table/-/table-3.9.0.tgz: Request failed \"404 Not Found\""

## 💁 Possible Solution

Check if something is wrong with package registry pipeline, or if versions were deprecated

## 🔦 Context

Can't install the package

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by alex-pominov** [comment]
Having exact same issue building react-native expo app.

```
error Couldn't find package "@react-stately/table@^3.10.0" required by "@react-stately/layout@^3.12.2" on the "npm" registry.
```

**Comment by reidbarber** [comment]
It looks like an active NPM incident: https://status.npmjs.org/incidents/jglnklhspsnm

**Comment by reidbarber** [comment]
Closing since it looks like this has been resolved.
