### ISSUE TITLE
perf: generators are 20x slower than forEach

### ISSUE THREAD

**Issue by qweered** [adobe/react-spectrum#4776]
Link to class method - [FocuseScope.tsx](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/focus/src/FocusScope.tsx#L860-L869) 

Bench link - [jsbench](https://jsbench.me/y4lj3wo9rt/1)

![IMG_20230717_173353_071](https://github.com/adobe/react-spectrum/assets/41731334/1397e80e-f227-4bc1-936f-3571e14081b1)

**Comment by AlexGalays** [comment]
also reading a codebase that uses generators for no good reason (I think?) 😭

**Comment by devongovett** [comment]
Is this affecting a real world application? I'm not sure how useful micro benchmarks are here. The number of focus scopes on a page at a time will typically be quite small (< 10) so I'd be surprised if this had any perceivable impact.
