### ISSUE TITLE
Nested column bug when column nodes are cached

### ISSUE THREAD

**Issue by fionawhim** [adobe/react-spectrum#4786]
# 🐛 Bug Report 

The `Column` class has a “bit of a hack” to call `updateContext` to add a column to the `context`’s list of columns:

https://github.com/adobe/react-spectrum/blob/f2a118718d0a807d4a852af046c45811afab9578/packages/%40react-stately/table/src/Column.ts#L56

Unfortunately, if a parent column is cached, this ends up not being run on its child columns, since `CollectionBuilder` doesn’t iterate on child nodes when `shouldInvalidate` returns false:

https://github.com/adobe/react-spectrum/blob/b57b3af44c345d456658e2895bb9244c65f0e7d3/packages/%40react-stately/collections/src/CollectionBuilder.ts#L98

This means that those nested columns do not get added into `context.columns`, so the check for `Row`s that they have the same number of cells as there are columns fails. (E.g. “Cell count must match column count. Found 3 cells and 0 columns.”)

I’m not sure what the right fix is around what to cache or not cache… it may be that `shouldInvalidate` should always return `true` for columns with child nodes?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
Mind sharing a codesandbox reproducing the caching issue?

**Comment by ktabors** [comment]
Closing and we can reopen if it's still a problem.

**Comment by crazko** [comment]
We're probably just facing this bug.

Reproduction: https://codesandbox.io/p/sandbox/32y9vy

https://github.com/user-attachments/assets/0fc34f02-2004-4256-810d-0a9b01d2cd0b

Can this be re-opened? 🙏

**Comment by snowystinger** [comment]
Thanks for the sandbox, reopening
