### ISSUE TITLE
AriaNumberFieldProps do not have a name attribute

### ISSUE THREAD

**Issue by mxp-qk** [adobe/react-spectrum#4788]
# 🐛 Bug Report 

`AriaNumberFieldProps` ([here](https://github.com/adobe/react-spectrum/blob/84a1f0fc20d4494430e8acda8e244ff087e1e5e0/packages/%40react-types/numberfield/src/index.d.ts#L35)) do not accept a name property for the `<input>` children. Aria type for form related component as `AriaTextFieldProps`, `AriaCheckboxProps`, etc. all accept a `name` attribute.

This is only typescript related as the name attribute is pass down to the input if added as prop (see sandbox test)

## 🤔 Expected Behavior

AriaNumberFieldProps should have an optional name property

## 😯 Current Behavior

Adding a name property raised a typescript error
<img width="658" alt="Screenshot 2023-07-19 at 15 17 00" src="https://github.com/adobe/react-spectrum/assets/56259084/737424e0-888b-433b-aaaa-63b0b4981910">

## 💁 Possible Solution

Extends an interface similar to `TextInputDOMProps` for `AriaTextFieldProps`

## 🔦 Context

This is related to similar issue concerning form attribute (name, form, etc.) for integration with HTML form.

## 💻 Code Sample

https://codesandbox.io/s/sweet-rhodes-m4crmw?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria | 3.23.1  |
| react-stately | 3.23.0 |

## 🧢 Your Company/Team

Quick Agency / Dev team

**Comment by reidbarber** [comment]
You could extend `AriaNumberFieldProps` and pass it down to the input yourself for now yourself for now. It seems reasonable to add `name` to the props, but we probably don't need to go as far as extending `TextInputDOMProps`.

**Comment by devongovett** [comment]
See https://github.com/adobe/react-spectrum/issues/4744#issuecomment-1620884471

**Comment by mxp-qk** [comment]
Thank you @devongovett, I've missed this one. I'm closing the issue then
