### ISSUE TITLE
DatePicker component gets focused when clicking outside of DOM elements

### ISSUE THREAD

**Issue by gmwill934** [adobe/react-spectrum#4807]
# 🐛 Bug Report 

The `DatePicker` component for some reason gets on a focus state when DOM elements outside of it are clicked, this happens on both implementations, using `react-aria-components` and `react aria hooks`

## 🤔 Expected Behavior

The `DatePicker` component should not get set in a focus state when clicked outside of it.

## 😯 Current Behavior

You can take a look at your [own example](https://react-spectrum.adobe.com/react-aria/DatePicker.html#example) and see it gets on a focused state when clicked outside of it.

## 💁 Possible Solution

I was thinking about event bubbling, but that only goes up, right?

## 🔦 Context

A form in a modal, it's annoying to click randomly to get out of the "focused" state of the `Datepicker`.

## 💻 Code Sample

Your own example, you can look at it [here](https://react-spectrum.adobe.com/react-aria/DatePicker.html#example).

## 🌍 Your Environment

Mac OS Monterey 12.6
Node 16.15.1
Storybook 7.1

**Comment by LFDanLu** [comment]
Looks like this is covered in https://github.com/adobe/react-spectrum/issues/3164, see the thread there for some initial investigations/possible fixes. Closing out as a dupe, feel free to reopen if I'm mistaken
