### ISSUE TITLE
Remove unheeded t-shirt icon size from menu example

### ISSUE THREAD

**Issue by MBernardAdobe** [adobe/react-spectrum#4814]
In the Menu example for items that have icons, the icon has a tshirt size. However, changing the size does not do anything. 

This is likely because of https://react-spectrum.adobe.com/react-spectrum/workflow-icons.html#sizing "When used inside another React Spectrum component, they'll generally be sized automatically"

Perhaps the example could be edited so that no user expects size to be a relevant icon attribute?

https://github.com/adobe/react-spectrum/blob/e4bc3269fa41aa096700445c6bfa9c8620545e6a/packages/%40react-spectrum/menu/docs/Menu.mdx#L272

**Comment by LFDanLu** [comment]
Good catch, I believe those user defined sizes are a hold over from when we didn't have the SlotProvider logic to control the icon size via the component. Definitely can be removed from the Menu docs.

**Comment by RobertoSimonini** [comment]
I would like to solve this issue

**Comment by LFDanLu** [comment]
@RobertoSimonini Sounds good, let us know if you have any questions!
