### ISSUE TITLE
Jest tests for useCalendar returning earlier month for title 

### ISSUE THREAD

**Issue by LisaHao** [adobe/react-spectrum#4818]
# 🐛 Bug Report 

I'm using Jest to test a component with the `useCalendarState` and `useCalendar` hook. The title keeps describing the month before the one I expect (based off the visible range & the focused value).

## 🤔 Expected Behavior
The title should match the month of the visible range & the focused value.

## 😯 Current Behavior

When I console log the `state.visibleRange`, I get:
```
    {
      start: $625ad1e1f4c43bc1$export$99faa760c7908e4f {
        calendar: $af14c9812fdceb33$export$80ee6245ec4f29ec { identifier: 'gregory' },
        era: 'AD',
        year: 2023,
        month: 7,
        day: 1
      },
      end: $625ad1e1f4c43bc1$export$99faa760c7908e4f {
        calendar: $af14c9812fdceb33$export$80ee6245ec4f29ec { identifier: 'gregory' },
        era: 'AD',
        year: 2023,
        month: 7,
        day: 31
      }
    }
```
However, when I console.log the title, I get `June 2023`. I've tried this with different dates and the title keeps returning as the month before the visible range. This only impacts my Jest tests. It renders correctly otherwise!

## 🔦 Context

I cannot test my components.

## 💻 Code Sample
Component:
```
export function StandaloneCalendar({
  minDate,
  maxDate,
  availableDates,
  selectedDate,
  changeDate,
}: StandaloneProps): JSX.Element {
  const selectedCalendarDate = dateTimeToCalendarDate(selectedDate);
  const [focusedDate, setFocusedDate] = useState(selectedCalendarDate);

  useEffect(() => {
    setFocusedDate(dateTimeToCalendarDate(selectedDate));
  }, [selectedDate]);

  const memoizedAvailability = useMemo(() => {
    return Object.fromEntries(availableDates.map((date) => [date, true]));
  }, [availableDates]);

  const state = useCalendarState({
    locale: DateTime.now().locale,
    value: selectedCalendarDate,
    focusedValue: focusedDate,
    onFocusChange: setFocusedDate,
    onChange: (date: DateValue): void => changeDate(date.toString()),
    minValue: dateTimeToCalendarDate(minDate),
    maxValue: dateTimeToCalendarDate(maxDate),
    isDateUnavailable: (date: DateValue): boolean => !memoizedAvailability[date.toString()],
    createCalendar,
  });

  const { calendarProps, prevButtonProps, nextButtonProps, title } = useCalendar(CALENDAR_ARIA_PROPS, state);

  return (
    <div {...calendarProps} className='flex-1'>
        <Text>{title}</Text>
  );
}
```

Test:
```
describe('StandaloneCalendar', () => {
  const dates = [
    DateTime.fromObject({ year: 2023, month: 7, day: 2, hour: 15 }),
    DateTime.fromObject({ year: 2023, month: 7, day: 28, hour: 15 }),
    DateTime.fromObject({ year: 2023, month: 8, day: 8, hour: 10 }),
    DateTime.fromObject({ year: 2023, month: 8, day: 28, hour: 13 }),
    DateTime.fromObject({ year: 2023, month: 9, day: 1, hour: 16 }),
    DateTime.fromObject({ year: 2023, month: 9, day: 15, hour: 8 }),
  ];
  it('shows selected date, shows all of the available dates within the selected date`s month and disables all other dates', async () => {
    render(
      <StandaloneCalendar
        minDate={dates[0]}
        maxDate={dates[dates.length - 1]}
        availableDates={dates.map((date) => date.toISODate())}
        selectedDate={DateTime.fromObject({ year: 2023, month: 7, day: 31 })}
        changeDate={() => {}}
      />,
    );
    expect(await screen.getByText('July 2023')).toBeVisible();
  });
});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
Hard for me to say what exactly is going on without poking around in your implementation/having a minimal reproduction to try out locally. Could you log out what [this line](https://github.com/adobe/react-spectrum/blob/d4613f219d7dc92ee9f2438572a9e92b1534b47c/packages/%40react-aria/calendar/src/useCalendarBase.ts#L42) inputs are? Does this reproduce if you use the [React Aria Components Calendar](https://react-spectrum.adobe.com/react-aria/Calendar.html#calendar)?

**Comment by LisaHao** [comment]
@LFDanLu thanks for commenting (totally missed this! Sorry about that!)

I get the following when I log the inputs:
```
state.visibleRange.start: $625ad1e1f4c43bc1$export$99faa760c7908e4f {
      calendar: $af14c9812fdceb33$export$80ee6245ec4f29ec { identifier: 'gregory' },
      era: 'AD',
      year: 2023,
      month: 7,
      day: 1
    }
 state.visibleRange.end: $625ad1e1f4c43bc1$export$99faa760c7908e4f {
    calendar: $af14c9812fdceb33$export$80ee6245ec4f29ec { identifier: 'gregory' },
    era: 'AD',
    year: 2023,
    month: 7,
    day: 31
  }
state.timezone: America/Los_Angeles
```

**Comment by LisaHao** [comment]
I also noticed that the `useCalendarCell` hook does something weird. It seems to return a formatted date that's one day earlier than I expect.

My implementation:
```
  const ref = useRef(null);
  const {
    cellProps,
    buttonProps,
    isSelected,
    isDisabled,
    isOutsideVisibleRange,
    isUnavailable,
    formattedDate,
  } = useCalendarCell({ date }, state, ref);

  console.log(`date: ${date} formattedDate: ${formattedDate}`);
```

And I get back examples like:
```
    date $625ad1e1f4c43bc1$export$99faa760c7908e4f {
      calendar: $af14c9812fdceb33$export$80ee6245ec4f29ec { identifier: 'gregory' },
      era: 'AD',
      year: 2023,
      month: 7,
      day: 6
    }
formattedDate: 5
```
&
```
    date $625ad1e1f4c43bc1$export$99faa760c7908e4f {
      calendar: $af14c9812fdceb33$export$80ee6245ec4f29ec { identifier: 'gregory' },
      era: 'AD',
      year: 2023,
      month: 8,
      day: 1
    }
formattedDate: 31
```

It looks like it's doing the same behavior where it's formatting it as the month before or the date before.

**Comment by LFDanLu** [comment]
Definitely odd, never seen this behavior before. Were you able to try running the same kind of test against a base [React Aria Components Calendar](https://react-spectrum.adobe.com/react-aria/Calendar.html#calendar) or a pared down [useCalendar](https://react-spectrum.adobe.com/react-aria/useCalendar.html#example) implementation? 

If it reproduces with those, then it may be something with the test environment. If it doesn't reproduce, then there might be something with your implementation.

**Comment by LisaHao** [comment]
@LFDanLu thanks for the help, Daniel! I assume it's something wrong with the test environment because this only happens when I run jest tests. When I run the app locally, everything looks as I expect.

Do you have any ideas about how the conversion from date --> formattedDate happens? What might've gone funky there?

**Comment by LFDanLu** [comment]
So useCalendarCell takes the provided CalendarDate and [converts it to a native Date object](https://github.com/adobe/react-spectrum/blob/07f673acb2d68144156df3aa0db6e91810b12c67/packages/%40react-aria/calendar/src/useCalendarCell.ts#L104-L105), then [grabs the day value](https://github.com/adobe/react-spectrum/blob/07f673acb2d68144156df3aa0db6e91810b12c67/packages/%40react-aria/calendar/src/useCalendarCell.ts#L295-L301) of the Date via a DateFormatter. Can to do some logging around those lines to see when the date changes unexpectedly?

**Comment by LisaHao** [comment]
Thanks for all of the help @LFDanLu — we've narrowed it down more. I found that when `useCalendarCell` hook converts the date to a native Date object within Jest, it seems to add the expected timezone but doesn't add the offset to the date. 

When I `console.log` the stringified version, I get `Sat Aug 05 2023 00:00:00 GMT+0000 (Pacific Standard Time)` (our jest global-setup has PST as the set timezone). However, when I run the app locally and console log the same information, I see that the stringified native date is `Sat Aug 05 2023 00:00:00 GMT-0700 (Pacific Daylight Time)` for me (I'm in California) and `Sat Aug 05 2023 00:00:00 GMT-0400 (Eastern Daylight Time)` for a coworker who is in the East Coast. Do you have any ideas why it wouldn't calculate the offset even though it seems to have properly recognized the timezone?

**Comment by LFDanLu** [comment]
Oh interesting, what is your jest setup here for the tests? I assume you aren't using fake timers since you are setting up the timezone globally?

**Comment by LisaHao** [comment]
We just have 
```
module.exports = async () => {
  process.env.TZ = 'PST';
};
```
in our `global-setup.js` !

**Comment by LFDanLu** [comment]
Thanks for the code snippet. I reproduced this locally, not entirely sure why setting it to `PST` doesn't set the offset, but it should be noted that this extends to calls to the native Date object and not just our useCalendarCell code (aka logging out `new Date.toString()` returns `Wed Aug 09 2023 21:09:08 GMT+0000 (Pacific Standard Time)`). Changing your `process.env.TZ` to ` process.env.TZ = 'America/Los_Angeles'` actually provides the proper offset (aka ` Wed Aug 09 2023 14:11:35 GMT-0700 (Pacific Daylight Time)`. Does that work for you instead? You could also just use `"UTC"` as the timezone since I think that is the only required value that `Intl.DateTimeFormat` is required to recognize.

**Comment by LisaHao** [comment]
Thank you so much @LFDanLu !!! Really appreciate the investigation. Going to close this out :)
