### ISSUE TITLE
RAC bug: <Section/> does not receive restProps when used in a <ListBox/>

### ISSUE THREAD

**Issue by jrmyio** [adobe/react-spectrum#4828]
# 🐛 Bug Report 

When using additional props in a Section (`<Section {...props}/>`) inside a `<ListBox/>`, the props are not correctly passed to the generated `<section/>` dom element. This behavior does work for `<Header/>` , <`ListBox/>` and `<Item/>.`

## 🤔 Expected Behavior

Section should get the dom attributes passed to it, for example a data attributes.

## 😯 Current Behavior

In the below sandbox you can inspect the dom and see how `[data-something]` is not passed to the `<section/>`.
https://codesandbox.io/s/festive-bose-cdx75d?file=/src/App.tsx

## 💁 Possible Solution
Fixing this should be most likely be a double check at this line where the section props are not passed to ListBoxSection:

https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/ListBox.tsx#L151

However, doing so would `<Header/>` to also get those props, which is not what we want:
https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/ListBox.tsx#L285

So maybe the fix should be in passing `section.props` instead of `otherProps` at line :
https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/ListBox.tsx#L301

**Comment by LFDanLu** [comment]
Sounds reasonable to have the data-attributes propagated to the section.

> So maybe the fix should be in passing section.props instead of otherProps at line :
https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/ListBox.tsx#L301

Yep, I think that is the right change, the ListBox item does something similar to that effect [here](https://github.com/adobe/react-spectrum/blob/07f673acb2d68144156df3aa0db6e91810b12c67/packages/react-aria-components/src/ListBox.tsx#L345).
