### ISSUE TITLE
@react-aria/toast causing Dynamic require of "react" is not supported

### ISSUE THREAD

**Issue by kysley** [adobe/react-spectrum#4829]
# 🐛 Bug Report 

When instantiating a new `ToastQueue`, or using the `useToastState` hook, I get a runtime error `Dynamic require of "react" is not supported`.

## 🤔 Expected Behavior

There should be no runtime error when using Toasts.

## 😯 Current Behavior

![image](https://github.com/adobe/react-spectrum/assets/14065780/1ed7d6b1-9ef0-4ee1-af32-e4a6c2a5bbcd)

## 💁 Possible Solution

I tried to externalize `react`, which initially removed the Dynamic require error, but it led to having 2 versions of react in the DOM. 

## 🔦 Context

We are trying to make use of @react-aria/toast to handle Toasts for our design system. 

I feel as if this could be related to using esbuild/tsup? Here is our config if that may alude to anything:

```ts
export default defineConfig({
	outDir: "dist",
	format: ["esm", "cjs"],
	dts: true,
	platform: "browser",
	external: ["react"],
	clean: true,
	splitting: true,
	treeshake: true,
	entry: ["src/**/*.ts"],
	esbuildPlugins: [svgrPlugin(), dynamicImport()],
});
```

## 💻 Code Sample
This is enough to cause the runtime error.
```ts
const toastQueue = new ToastQueue<ReactNode>({
	maxVisibleToasts: 5,
});
```
Another way is:
```ts
const state = useToastState<ReactNode>({
    maxVisibleToasts: 5,
});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria | 3.26.0
| react-stately | 3.24.0
| Browser          | Firefox Dev 116
| Operating System | Windows 10
| @react-aria/toast | 3.0.0-beta.2
## 🧢 Your Company/Team

Lightspeed HQ

## 🕷 Tracking Issue (optional)
n/a

**Comment by devongovett** [comment]
I don't think anything in our code is doing a dynamic require, but maybe related to the `external: ["react"]` in your config? Not really familiar with esbuild though.

**Comment by kysley** [comment]
Appreciate you getting back! I haven't had a chance to debug further :( Marking react as external here means that esbuild assumes the module is available at runtime. So react doesn't need to be bundled _with_ our package. This is why without external, our tests resulted in 2 versions of React in the dom.

I'd be happy to try any ideas, otherwise I think its safe to call this a build tooling issue and you can close 🙂

**Comment by steveg152** [comment]
> Appreciate you getting back! I haven't had a chance to debug further :( Marking react as external here means that esbuild assumes the module is available at runtime. So react doesn't need to be bundled _with_ our package. This is why without external, our tests resulted in 2 versions of React in the dom.
> 
> I'd be happy to try any ideas, otherwise I think its safe to call this a build tooling issue and you can close 🙂

@kysley  Did you ever figure out a solution for this?  It seems like these components are meant for building component libraries, but they do not seem to be compatible with bundling tools like esbuild or tsup.  I am finding it very difficult to build a reusable component.
