### ISSUE TITLE
TextField should support setting captialization

### ISSUE THREAD

**Issue by prabirshrestha** [adobe/react-spectrum#4832]
I like to disable `autocapitalize="off"` for username/emails `TextField` but seems like it is currently not possible. TextField should allow us to override this behavior.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize

**Comment by reidbarber** [comment]
Seems like a reasonable addition to me. I think if we do this, we should also make this apply to other input fields as well (SearchField, Combobox, SearchAutocomplete, etc.)
