### ISSUE TITLE
BorderSizeValue should support 'none' to hide the border

### ISSUE THREAD

**Issue by prabirshrestha** [adobe/react-spectrum#4833]
BorderSizeValue should support `none` such that one can conditional remove the border based on responsive value.

```typescript
export type BorderSizeValue =
  | 'thin'
  | 'thick'
  | 'thicker'
  | 'thickest';
```

```typescript
<View borderEndWidth={{ base: 'none', M: 'thin' }}>...</View>
```

**Comment by LFDanLu** [comment]
Perhaps we could modify [this function](https://github.com/adobe/react-spectrum/blob/07f673acb2d68144156df3aa0db6e91810b12c67/packages/%40react-spectrum/utils/src/styleProps.ts#L168-L170) so it handles cases where the value is undefined like so
```
function borderSizeValue(value: BorderSizeValue) {
  return value ? `var(--spectrum-alias-border-size-${value})` :  undefined;
}
```
Then you could omit the `base` (or whichever responsive break point) definition entirely:
```
<View borderEndWidth={{M: 'thin' }}>...</View>
``` 
Thoughts?

**Comment by reidbarber** [comment]
Seems reasonable, and that seems like a good solution.

**Comment by pr7prashant** [comment]
Hi, can I pick this one ?

Also, can we give support for both options so that the users can choose to omit or add `none` for more readability as per their need. What do you think ?
```
function borderSizeValue(value: BorderSizeValue) {
  return value && value !== "none"
    ? `var(--spectrum-alias-border-size-${value})`
    : undefined;
}
```

**Comment by reidbarber** [comment]
@pr7prashant Go for it! And that seems like a good solution.

**Comment by pr7prashant** [comment]
I noticed that [styleProps.test.js](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/utils/test/styleProps.test.js) has tests for only one function `dimensionValue`. May I add tests for other exported functions in a separate issue if you think it would be helpful ?

**Comment by snowystinger** [comment]
Tests are always good to add. Thanks!
