### ISSUE TITLE
size property is not working for ComboBox

### ISSUE THREAD

**Issue by Levik931** [adobe/react-spectrum#4843]
### Provide a general summary of the issue here

```
  <ComboBox
        size="large"
        label="Pick an engineering major"
        defaultItems={options}
        onSelectionChange={setMajor}>
        {item => <Item>{item.name}</Item>}
      </ComboBox>
```

### 🤔 Expected Behavior?

ComboBox must get larger but it's not, only width is working but only increased the width.

### 😯 Current Behavior

No changes in the size of the component. 

### 🖥️ Steps to Reproduce

```
import React from "react";
import {
  Provider,
  defaultTheme,
  Button,
  ComboBox,
  Item
} from "@adobe/react-spectrum";
import "./styles.css";

export default function App() {
  return (
    <Provider theme={defaultTheme} height="100%">
      <Button variant={"primary"}>Click Me</Button>
      <ComboBox size="large" />
    </Provider>
  );
}
```

### Version

9.8.1

### What browsers are you seeing the problem on?

Microsoft Edge

### What operating system are you using?

Windows 

### 🧢 Your Company/Team

Adobe Spectrum

**Comment by yihuiliao** [comment]
Closing since t-shirt sizing will be supported in the Spectrum 2 implementation. There aren't any plans to add this to RSP v3.
