### ISSUE TITLE
useDateFieldState accepts `isDateUnavailable` prop but makes no use of it

### ISSUE THREAD

**Issue by Darmun** [adobe/react-spectrum#4848]
### Provide a general summary of the issue here

`useDateFieldState` types allow to pass `isDateUnavailable` prop, however it's not used in the hook, and has no effect on `validationState`.

### 🤔 Expected Behavior?

`validationState` is determined taking into account `isDateUnavailable`.

### 😯 Current Behavior

`validationState` is [determined](https://github.com/adobe/react-spectrum/blob/main/packages/@react-stately/datepicker/src/useDateFieldState.ts#L312) with `minValue` and `maxValue` constraints.

### 💁 Possible Solution

Include function passed in `isDateUnavailable` in `validationState` result.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/charming-panka-ny2y3m?file=/src/App.js

You can try inputing "today", which mark date segments as "aria-invalid". That won't be the case if date corresponding to weekend is passed.

### Version

react-stately@3.24.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

MacOS Ventura 13.5

**Comment by LFDanLu** [comment]
Makes sense to me, perhaps something like `(isInvalid(calendarValue, props.minValue, props.maxValue) || (calendarValue && isDateUnavailable && isDateUnavailable(calendarValue))` at this [line](https://github.com/adobe/react-spectrum/blob/8e6cefdb5f13aa61eab9fcf5c91f2eaac1d807b5/packages/%40react-stately/datepicker/src/useDateFieldState.ts#L312-L313) like you suggested.
