### ISSUE TITLE
[React-Aria] Snapshot Test Ids change everytime after 2023-06-27 release

### ISSUE THREAD

**Issue by ashleyryan** [adobe/react-spectrum#4851]
### Provide a general summary of the issue here

After the latest release, ids in my snapshot tests are changing every run. I see the comments on the release notes and on the MR (#4347) but that seems to imply that the id format will only change once - which is fixable - but for me its changing every time.

I'm using React 18 and it seems like the [`didSSR` check seems to be false](https://github.com/adobe/react-spectrum/blob/22ded332388098ca54227afb7d1c4d0ae270e875/packages/%40react-aria/ssr/src/SSRProvider.tsx#L161) (which makes sense, Jest isn't doing SSR) and so `defaultContext.prefix` is being used in the id.

In React 17, the SSRProvider set `isSSR` to true, before switching to false in useLayoutEffect (which I assume ran after snapshots were generated)

old and new:
```
- aria-controls="react-aria-4"
+ aria-controls="react-aria9516198744-:r9a:"
```

I would expect it to be `react-aria-:r9a:`

### 🤔 Expected Behavior?

Snapshot test ids should be stable between snapshot runs

### 😯 Current Behavior

the ids change everytime in jest, so snapshot tests don't work

### 💁 Possible Solution

Re-purpose the SSRProvider (or something similar?) to be used in tests so that the prefix isn't included?

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/naughty-fermi-4zlqv2?welcome=true

The terminal tab at the bottom should be running jest watch mode and will show the snapshot differences between runs

(if it's not showing anything in the terminal you may need to fork and run npm run test)

### Version

react-aria 3.21.1

### What browsers are you seeing the problem on?

Other

### If other, please specify.

jest/jsdom

### What operating system are you using?

MacOS ventura

**Comment by devongovett** [comment]
Thanks for reporting this. I think we can detect if `NODE_ENV` is `"test"` and automatically disable the extra random prefix in test environments like we do for SSR.
