### ISSUE TITLE
useTextField's onChange isn't firing with useFormik's formik change handler

### ISSUE THREAD

**Issue by jenmak-tangelo** [adobe/react-spectrum#4854]
### Provide a general summary of the issue here

The controlled component controlled with formik's hook, for example:
```
      <TextInputField
        type="tel"
        id="phone"
        name="phone"
        prefix="phone"
        label="Mobile Phone"
        value={formik.values.phone}
        onChange={formik.handleChange}
      />
```
Does not allow the user to input a value because of the onChange function. I suspect it is because it returns a string instead of an event. 

### 🤔 Expected Behavior?

The onChange should return an event instead of just the target value

### 😯 Current Behavior

The onChange returns just the target value and is incompatible with other libraries

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/naughty-water-87jkcy?file=/src/App.js

### Version

3.26.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you using?

Mac OS

**Comment by devongovett** [comment]
See #1860 and #3247 for previous discussions about this. In your case, could you do something like this?

```js
<TextInputField
  // ...
  value={formik.values.phone}
  onChange={value => formik.setFieldValue('phone', value)} />
```

**Comment by jenmak-tangelo** [comment]
Yes that is exactly what I ended up doing. Thanks
