### ISSUE TITLE
Table component does not render any rows on server

### ISSUE THREAD

**Issue by mkdynamic** [adobe/react-spectrum#4870]
### Provide a general summary of the issue here

When server side rendering a basic Table component the thead and tbody are empty until the component loads on the client.

### 🤔 Expected Behavior?

The table should render all rows on the server.

### 😯 Current Behavior

The table does not render rows on the server.

### 💁 Possible Solution

Unsure.

### 🖥️ Steps to Reproduce

```js
function () {
  return (
    <Table aria-label="Files">
      <TableHeader>
        <Column isRowHeader>Name</Column>
        <Column>Type</Column>
        <Column>Date Modified</Column>
      </TableHeader>
      <TableBody>
        <Row>
          <Cell>Games</Cell>
          <Cell>File folder</Cell>
          <Cell>6/7/2020</Cell>
        </Row>
      </TableBody>
    </Table>
  );
}
```

Output when rendering on the server:

```html
<table
  class="react-aria-Table"
  aria-label="Files"
  id="react-aria-:R6kl:"
  role="grid"
  tabindex="0"
  aria-describedby=""
>
  <thead role="rowgroup" class="react-aria-TableHeader"></thead>
  <tbody
    role="rowgroup"
    class="react-aria-TableBody"
    data-empty="true"
  ></tbody>
</table>
```

### Version

1.0.0-alpha.5

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by devongovett** [comment]
At the moment, our collection implementation does not work during SSR because it relies on a portal. Therefore, we simply delay rendering of rows until after hydration. This is not ideal and I'm hoping to find a solution to it some day. https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/Collection.tsx#L716

**Comment by mkdynamic** [comment]
@devongovett Thanks – I see, so this impacts all the collection components. Do you have a sense of how hard it would be to solve this? Is it something major that would require significant refactoring, or is your sense it is a smaller change? SSR is critical for my particular use case so just want to understand the level of difficulty in making this work and whether it'd be something feasible for me to look into.

**Comment by devongovett** [comment]
I think it can be done. I have a working prototype but need to test it further.
