### ISSUE TITLE
Warnings when integrating Button usePress with TooltipButton

### ISSUE THREAD

**Issue by courtneylinder** [adobe/react-spectrum#4873]
### Provide a general summary of the issue here

When building a `TooltipButton` from react-aria, it documents using onClick ([link](https://react-spectrum.adobe.com/react-aria/useTooltipTrigger.html)) even though our react-aria `Button` component uses `onPress`. Trying to integrate the `TooltipButton` into our `Button` component causes console warnings and logs. The logs say `onPress` is not recognized but also say `onClick` is deprecated and to use `onPress`. Is there a way to use these components together without all the console warnings?

### 🤔 Expected Behavior?

To be able to use a Button built from react-aria as part of TooltipButton.

### 😯 Current Behavior

When using Button in a TooltipButton, various warning and console logs appear.

### 🖥️ Steps to Reproduce

Code sandbox with TooltipButton using internal built Button: https://codesandbox.io/s/tender-frost-r5yzd9?file=/src/App.js

### Version

3.24.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS Ventura 13.3.1

**Comment by reidbarber** [comment]
Going to close this, but feel free to post any follow-up questions here, or as a discussion. There are similar discussions at https://github.com/adobe/react-spectrum/discussions/4748 and https://github.com/adobe/react-spectrum/discussions/3666

**Comment by courtneylinder** [comment]
@reidbarber If we don't pass rest down to the native button, then it doesn't recognize the onMouseEnter and whatnot for the tooltip so that stops working. If I add `filterDomProps` on buttonProps, then onPress isn't recognized and it breaks for our other components that use onPress in their buttons.

**Comment by reidbarber** [comment]
@courtneylinder in that case, you would want to manually pass `onMouseEnter` from the component's props down to the element. Here is one way:

```tsx
import {useButton} from 'react-aria';
import {useRef} from 'react';

function Button(props) {
  let { onMouseEnter, onMouseLeave } = props;
  let ref = useRef();
  let { buttonProps } = useButton(props, ref);
  let { children } = props;

  return (
    <button {...buttonProps} ref={ref} onMouseEnter={onMouseEnter} onMouseLeave={onMouseLeave}>
      {children}
    </button>
  );
}
```

or you can use [useHover](https://react-spectrum.adobe.com/react-aria/useHover.html) / [useTooltipTrigger](https://react-spectrum.adobe.com/react-aria/useTooltipTrigger.html).

**Comment by courtneylinder** [comment]
Gotcha. So I am using this `Button` as the Trigger for my TooltipTrigger. So I can pass in the `triggerProps` at the TooltipTrigger level (from useTooltipTrigger) but pull out the Dom functions individually at the `Button` level so that I can still use my button with its styling. Thank you!
