### ISSUE TITLE
Unable to style the `Breadcrumbs` component with Tailwind.

### ISSUE THREAD

**Issue by polc** [adobe/react-spectrum#4885]
Hi ! The `Breadcrumbs` component creates a `nav` element containing an `ol` element as its children. Unfortunately, we can't assign a class name to the `ol` element, even though it's quite important !

```
<Breadcrumbs className="flex items-center">
</Breadcrumbs>
```

I'm not sure how it's done in other components, is there any precedent ?

**Comment by reidbarber** [comment]
We have a TODO for this here:

https://github.com/adobe/react-spectrum/blob/8e6cefdb5f13aa61eab9fcf5c91f2eaac1d807b5/packages/react-aria-components/src/Breadcrumbs.tsx#L41-L42

I think the concern was balancing having too many containers, but also allowing easy customization of every element. 

Specific to Tailwind, but for now you could use `[&> ol]:` on the parent.

**Comment by polc** [comment]
Oh I was not aware that these selectors had been added to Tailwind. This looks good enough to me. Thank you!
