### ISSUE TITLE
TableView DnD DragPreview does not render text

### ISSUE THREAD

**Issue by tiffany-sy-lin** [adobe/react-spectrum#4895]
### Provide a general summary of the issue here

TableView drag and drop's `DragPreview` doesn't render the text in the preview when `selectionStyle='highlight`.

### 🤔 Expected Behavior?

Should render default preview correctly

### 😯 Current Behavior

An empty rectangle is rendered (ie. text is missing)

### 💁 Possible Solution

https://github.com/adobe/react-spectrum/blob/1775ff2a331be32c3b27417acc2705ad11019b37/packages/%40react-stately/table/src/TableCollection.ts#L275-L285

Set second column as rowHeader since the first column is the drag handle.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/patient-firefly-54vfwr?file=/src/App.js

### Version

3.27.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

DXUE Quarry

**Comment by LFDanLu** [comment]
We should just iterate through `this.columns` and find the first one that doesn't have `props.isSelectionCell` or `props.isDragButtonCell`.
```
if (this.rowHeaderColumnKeys.size === 0) {
    this.rowHeaderColumnKeys.add(this.columns.find(column => !column.props?.isDragButtonCell && !column.props?.isSelectionCell).key);
}
```
