### ISSUE TITLE
Id from from combobox items not returned from onSelectionChange

### ISSUE THREAD

**Issue by DATADEER** [adobe/react-spectrum#4901]
### Provide a general summary of the issue here

According to the docs on https://react-spectrum.adobe.com/react-aria/ComboBox.html#dynamic-collections.
The `id` provided in the array of objects (`items`) passed to the ComboBox as `defaultItems` should be returned as the `key` from `onSelectionChange`. In the current implementation is returns an internal id instead of the id from the items.

Quote from https://react-spectrum.adobe.com/react-aria/ComboBox.html#dynamic-collections
"As seen below, an iterable list of options is passed to the ComboBox using the defaultItems prop. Each item accepts an id prop, which is passed to the onSelectionChange handler to identify the selected item. Alternatively, **if the item objects contain an id property**, as shown in the example below, **then this is used automatically** and an id prop is not required."

### 🤔 Expected Behavior?

The `id` provided in the array of objects (`items`) passed to the ComboBox as `defaultItems` should be returned as the `key` from `onSelectionChange`.

### 😯 Current Behavior

The key returned from  `onSelectionChange` is an internal id such as `react-aria-2`.
Only if you explicitly pass the id to `<Item id={item.id}>{item.label}</Item>` does it actually return the id.

### 🖥️ Steps to Reproduce

I've reproduced the error on Codesandbox: https://codesandbox.io/p/sandbox/tender-sun-mtrh8f

### Version

"react-aria-components": "^1.0.0-alpha.6",

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by LFDanLu** [comment]
This is because you are passing `key={item.id}` to your Item. If you [omit that entirely](https://codesandbox.io/p/sandbox/romantic-rubin-8ymztg?file=/app/page.tsx:46,27) or do `id={item.id}` (as you mentioned earlier), then you receive the proper value in your onSelectionChange. This is a change from our React Spectrum collection implementation noted in @devongovett's RFC as follows:
```
Our current implementation heavily uses the React key prop to identify items in collections. However, this will not work with the new implementation because key is not passed through from the <Item> element to the implementation of the Item component. Therefore, we will need to use a different prop name such as id that is passed through. This would be a breaking change to switch to by default, but for React Aria Components this is ok since it is a new library. We will need to think through how to release this in our existing React Aria hooks and React Spectrum components separately.
```

**Comment by ktabors** [comment]
Closing and we can reopen if it's still a problem.
