### ISSUE TITLE
RAC Calendar missing 'weekdayStyle' prop

### ISSUE THREAD

**Issue by binaryartifex** [adobe/react-spectrum#4907]
### Provide a general summary of the issue here

cannot alter the format of the weekday's due to no exposed weekdayStyle prop

### 🤔 Expected Behavior?

a weekdayStyle prop should be exposed.

### 😯 Current Behavior

The CalendarGridHeader's children props exposes the day as a renderprop string but it seems redundant to have to create logic that already exists to parse the weekday style

### 🖥️ Steps to Reproduce

Create RAC calendar and check for exposed props that indicate the ability to change the weekdayStyle.

### Version

1.0.0-alpha.6 (RAC)

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 11

**Comment by devongovett** [comment]
It is on CalendarGrid I think?

**Comment by binaryartifex** [comment]
yep. there it is. cheers mate.
