### ISSUE TITLE
Spacing is off if a Picker isQuiet and does not have a label

### ISSUE THREAD

**Issue by michayou** [adobe/react-spectrum#4912]
### Provide a general summary of the issue here

If you create a picker that is `isQuiet`and does not have a label, there will be a large space between the text and the caret.

You can easily see this in v3.25.0

### 🤔 Expected Behavior?

The space between the text and caret in an isQuiet picker without a label should be the same as one with a label.

### 😯 Current Behavior

The top picker has a label and displays properly.  The bottom one does not and displays improperly.

![Screenshot 2023-08-14 at 11 30 23 AM](https://github.com/adobe/react-spectrum/assets/69984832/43bb17b1-eaab-4bce-9f02-3eeb8df26583)

### 💁 Possible Solution

Fix the picker without labels

### 🔦 Context

We have a picker without a label and the spacing is weird.

### 🖥️ Steps to Reproduce

     //the top picker will display correctly.  The bottom one will have too much space between the text and the caret
     
      <div>
        <Picker label="Choose frequency" isQuiet>
          <Item key="rarely">Rarely</Item>
          <Item key="sometimes">Sometimes</Item>
          <Item key="always">Always</Item>
        </Picker>
      </div>
      
      <div>
        <Picker aria-label="Choose frequency" isQuiet>
          <Item key="rarely">Rarely</Item>
          <Item key="sometimes">Sometimes</Item>
          <Item key="always">Always</Item>
        </Picker>
      </div>

### Version

3.25.0

### What browsers are you seeing the problem on?

Chrome, Safari

### If other, please specify.

I haven't tested other browsers

### What operating system are you using?

mac ventura 13.5

### 🧢 Your Company/Team

Client Apps (Adobe)

**Comment by reidbarber** [comment]
Looks like the quiet variant gets `width: auto`, but this is applied to the field wrapper (which isn't used if there isn't a visual label). Looks like we should add `width: auto` here:

https://github.com/adobe/react-spectrum/blob/be501251a2012b2c1401e79940cbb39151c84d9d/packages/%40adobe/spectrum-css-temp/components/dropdown/index.css#L140-L142

We should also make sure we have chromatic stories covering this combination, and any missing combinations.

**Comment by pr7prashant** [comment]
Hi @reidbarber, I was also facing this issue and noticed that we are not adding the classes to the Field wrapper when label is not present. Adding these classes to the field wrapper fixes this issue. I have raised a small PR #5592 for the changes and storybook. Thanks

https://github.com/adobe/react-spectrum/blob/be501251a2012b2c1401e79940cbb39151c84d9d/packages/%40react-spectrum/picker/src/Picker.tsx#L226
