### ISSUE TITLE
Button needs onPress manually passing

### ISSUE THREAD

**Issue by lloydjatkinson** [adobe/react-spectrum#4919]
### Provide a general summary of the issue here

The `react-aria-components` button needs `onPress`, (edit: discovered same problem for `isDisabled)` manually passing to it despite being spread. Take this example of a wrapper button component. The `onPress` is not called unless I manually pass it.

```diff
export const Button = ({
    value,
    onPress,
    isDisabled,
    ...props
}: ButtonProps) => {
    const buttonVariants = clsx(
        'rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm',
        {
            'hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600': !isDisabled,
            'bg-gray-500 focus:ring-0 focus:ring-offset-0': isDisabled,
        }
    );

    return (
        <ReactAriaButton
            {...props}
            className={buttonVariants}
+++         onPress={onPress}>
            {value}
        </ReactAriaButton>
    );
};
```

### 🤔 Expected Behavior?

I would expect passing `onPress` would not be manually necessary. The `TextField` component does not require `onChange` to be manually passed, so I would expect the API's to be follow the same conventions.

For example:

```tsx
export const TextField = ({
    label,
    description,
    errorMessage,
    isDisabled,
    validationState,
    ...props
}: TextFieldProps) => {
    return (
        <ReactAriaTextField {...props}>
            <div className="flex flex-col gap-2">
                <Label className={labelVariants}>{label}</Label>
                <Input
                    className={inputVariants}
                    readOnly={isDisabled}
                    disabled={isDisabled}
                />
            </div>
            {errorMessage && (
                <Text className={errorMessageVariants} slot="errorMessage">
                    {errorMessage}
                </Text>
            )}
        </ReactAriaTextField>
    );
};
```

### 😯 Current Behavior

If `onPress` is not supplied, despite the previous spread `{...props}`, then the function is not called.

### 💁 Possible Solution

Align the API of all components so that either all of them can have their callbacks spread `{...props}` or make it so none of them support this and make it explicit in the docs that wrapper components must supply every prop.

### 🔦 Context

Writing wrapper components for consistent design system styling and interaction reasons.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/stoic-edison-r6gy7g?file=/src/Button.jsx

Comment and uncomment the two code blocks to observe the different (and inconsistent with `TextField`) behaviour.

```tsx
    // <ReactAriaButton {...props}>
    //   {value}
    // </ReactAriaButton>
    <ReactAriaButton {...props} onPress={onPress}>
      {value}
    </ReactAriaButton>
```

### Version

NA

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows

### 🧢 Your Company/Team

NA

**Comment by reidbarber** [comment]
Going to close this since it doesn't seem to be an issue, but feel free to leave further discussion/questions here.
