### ISSUE TITLE
RAC Modal doesn't check for SSR when using useViewportSize

### ISSUE THREAD

**Issue by MarekBodingerBA** [adobe/react-spectrum#4921]
### Provide a general summary of the issue here

As mentioned in one of the [discussions](https://github.com/adobe/react-spectrum/discussions/4892#discussioncomment-6734538), the user needs to hide RAC Modal in SSR environment because it uses `useViewportSize` hook that accesses `window`. 

https://github.com/adobe/react-spectrum/blob/be501251a2012b2c1401e79940cbb39151c84d9d/packages/react-aria-components/src/Modal.tsx#L144

### 🤔 Expected Behavior?

Modal should check if it is in SSR environment and use appropriate hook.

### 😯 Current Behavior

Modal fails when in SSR environment.

```
ReferenceError: window is not defined
    at $5df64b3807dc15ee$var$getViewportSize (file:///C:/Projects/konto.bratislava.sk/next/node_modules/@react-aria/utils/dist/import.mjs:811:172)
    at file:///C:/Projects/konto.bratislava.sk/next/node_modules/@react-aria/utils/dist/import.mjs:790:52
    at useReducer (C:\Projects\konto.bratislava.sk\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5079:57)
    at Object.useState (C:\Projects\konto.bratislava.sk\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5017:10)
...
```

### 💁 Possible Solution

> We should either change Modal so that hook call + the div it renders is in a child component of ModalOverlayInner so that Overlay wouldn't render it server side and/or make useViewportSize have a useIsSSR check within it as well. Mind filing an issue for that? Ideally, we would handle is useIsSSR check in as many places as necessary so you wouldn't have to do so.

### 🖥️ Steps to Reproduce

1. Use RAC Modal in SSR environment.
2. Fail

### Version

react-aria-components@1.0.0-alpha.6

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows

**Comment by LFDanLu** [comment]
Thanks for filing this! A quick fix that I hadn't considered in my original comment is just simply adding a `useIsSSR` check to this [if statement](https://github.com/adobe/react-spectrum/blob/09a258f098147f7e67a0430b593b08168220ec4a/packages/react-aria-components/src/Modal.tsx#L109) so that we don't render the ModalOverlay on the server.
