### ISSUE TITLE
Slider: Should have a name prop that is passed to the input element

### ISSUE THREAD

**Issue by NRodriguezcuellar** [adobe/react-spectrum#4924]
### Provide a general summary of the feature here

Currently the `<Slider>` component in React-Aria-Components does not allow to set the `name` property for the underlying input element, which means it can not be used with a native form to send form data.  

### 🤔 Expected Behavior?

allow for a `name` prop and pass it to the underlying `<input type="range"/>` element. 

### 😯 Current Behavior

no `name` prop

### 💁 Possible Solution

explained in the `expected behaviour` section 

### 🔦 Context

I am trying to use the `<Slider>` component but i am relying on the `name` property on input elements to send form data to my API endpoint, currently it is not possible to set the name property on the underlying input element, making it impossible to use the Slider component in my form without the values being ignored.

**Comment by devongovett** [comment]
Since a Slider can have multiple thumbs, the `name` prop is on the SliderThumb instead. See https://react-spectrum.adobe.com/react-aria/Slider.html#html-forms

**Comment by NRodriguezcuellar** [comment]
oh wow, no idea how i missed that, thanks!
