### ISSUE TITLE
Datepicker is focused on clicking anywhere below input

### ISSUE THREAD

**Issue by Darmun** [adobe/react-spectrum#4926]
### Provide a general summary of the issue here

Datepicker can be focused by clicking parent container, anywhere below input. See example from docs: from https://react-spectrum.adobe.com/react-aria/DatePicker.html#example 

### 🤔 Expected Behavior?

Datepicker is focused by clicking on the label or input.

### 😯 Current Behavior

Datepicker is focused by clicking on the label, input, or anywhere below input.

### 🔦 Context

Builiding Datepicker using component available in `react-aria-components`. This focus behaviour might be unexpected when filling for example form.

### 🖥️ Steps to Reproduce

1. Go to example from docs: https://react-spectrum.adobe.com/react-aria/DatePicker.html#example
2. Click on the grey area below input.

 Click will focus one of the segments within input.

### Version

react-aria-components: 1.0.0-alpha.5

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

MacOS Ventura 13.5

**Comment by snowystinger** [comment]
Closing as a duplicate https://github.com/adobe/react-spectrum/issues/3164
