### ISSUE TITLE
GridList: interactive children stopPropagation not considered

### ISSUE THREAD

**Issue by boreens** [adobe/react-spectrum#4928]
### Provide a general summary of the issue here

When an item is selected and you click on the interactive child that prevents the event from bubbling up, the item gets deselected. 

### 🤔 Expected Behavior?

stopPropagation should be taken into account. So we could click on the Button without Item deselection

### 😯 Current Behavior

When an item is selected and you click on the interactive child that prevents the event from bubbling up, the item gets deselected.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/react-aria-grid-list-pjpgrf

### Version

1.0.0-alpha.6

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

macOS 12.6 (21G115)

**Comment by devongovett** [comment]
`onClick` is too late because the selection/deselection occurs during `onPointerDown`. Here's an example: https://codesandbox.io/s/react-aria-grid-list-forked-9wc883
