### ISSUE TITLE
I don't understand the insistence on pixel layouts

### ISSUE THREAD

**Issue by michael-lloyd-morris** [adobe/react-spectrum#4929]
### Provide your feedback here.

Across a wide variety of devices expressing the size of elements in terms of pixels or other absolute units is inflexible. Relative view units such as view width in combination with ems are vastly superior. So I don't understand why React Spectrum insists on using antiquated pixel layouts with all the problems they incur.

If relative view units are used the whole page can adjust to a fine degree impossible to achieve with pixel layouts. This is dont by setting the html element's font-size - this defines the rem unit, and the em unit remains proportional to its parent. Here's an example I use in Sass:

```
html {
  font-size: 1vw;

  @media (max-width: 999px) { font-size: 1.125vw; }
  @media (max-width: 899px) { font-size: 1.25vw; }
  @media (max-width: 799px) { font-size: 1.43vw; }
  @media (max-width: 699px) { font-size: 1.675vw; }
  @media (max-width: 599px) { font-size: 2vw; }
  @media (max-width: 499px) { font-size: 2.5vw; }
  @media (max-width: 399px) { font-size: 3.35vw; }
  @media (max-width: 299px) { font-size: 5vw; }
}

body { font-size: 1.6em }
```

Note the body font size setting to insure text remains at minimum size of 16px for accessibility.

I'm not asking that Spectrum adopt this - but I want it to get out of the way of sizing the pages this way. 

### 🔦 Context

My eyesight is starting to fail (I'm nearly 50).  I use this approach because if I want the text to be larger I can resize the window and text is larger. It's intuitive.  CTRL + mouse wheel works too, but it's not as intuitive and many sites don't like being scaled. If I do full screen a web page I can read it across the room.

From a dev experience standpoint I've found that this basic skeleton makes the rest of the CSS much easier to work with and reduces the need for media queries elsewhere significantly.

### Version

3.29

### What browsers are you seeing the problem on?

Other

### If other, please specify

All

### What operating system are you using?

Not applicable

**Comment by snowystinger** [comment]
Hey, thanks for the issue. I'm sorry you're experiencing some difficulties. In Spectrum, we're actually working on this right now in the token system. Eventually, it'll make its way into our React implementation.

In the meantime, you said you're not asking Spectrum to adopt this, which would indicate to me you're using either our hooks or the new React Aria Components. You should have full control over the styles in both of those cases. Are you saying you're running into an issue there?

**Comment by michael-lloyd-morris** [comment]
I'm still learning the system and I'm not familiar with the hooks nor with React Aria.  When I filed this I was sorta hoping I'd overlooked something. And if this approach is something you think would be useful then by all means include it - I just didn't want to come across as demanding.

**Comment by snowystinger** [comment]
If you're just learning and are unfamiliar with React Aria, I'd have a look here to get started https://react-spectrum.adobe.com/react-aria/react-aria-components.html

**Comment by michael-lloyd-morris** [comment]
Thank you. I'll close this for now, I was frustrated when I wrote it and to be honest I need to learn more before I can make useful suggestions.
