### ISSUE TITLE
RAC: `Tabs` is renders late

### ISSUE THREAD

**Issue by eckoln** [adobe/react-spectrum#4938]
### Provide a general summary of the issue here

I am using `Combobox` and `Tabs` components from react-aria-components with `"use client"` in `Next.js v13.4.18`. When the page loads, `Combobox` renders instantly but `Tabs` renders slower/later than other components.

### 🤔 Expected Behavior?

`Tabs` component needs to be rendered instantly because other components are rendered when the page loads. If `Tabs` is renders late, the layout is empty. It makes the UI look bad.

### 😯 Current Behavior

`Tabs` renders later/slower than other components.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/react-aria-components-issue-54vk42

### Version

1.0.0-nightly.4081

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 10 19045.3324

**Comment by devongovett** [comment]
I believe this will be fixed by #4913, which add support for server rendering collection components including Tabs.
