### ISSUE TITLE
`onPressUp` and `onPressDown` are listed as props, but they are not used in useButton

### ISSUE THREAD

**Issue by Itherael** [adobe/react-spectrum#4954]
### Provide a general summary of the issue here

The [`Button`](https://react-spectrum.adobe.com/react-spectrum/Button.html#props) component from React Spectrum and [`useButton`](https://react-spectrum.adobe.com/react-aria/useButton.html) are both listing `onPressUp` and `onPressDown` props. 

Both properties are not used inside the `useButton` if we [take a look at the code](https://github.com/adobe/react-spectrum/blob/8987f9283871b1bda0acc4637096966275f82167/packages/%40react-aria/button/src/useButton.ts#L87-L95)

### 🤔 Expected Behavior?

Accept the props `onPressUp` and `onPressDown` or remove the props from the documentation/typings.

### 😯 Current Behavior

`onPressUp` and `onPressDown` are ignored in `Button` and `useButton`.

### 🖥️ Steps to Reproduce

1. Press the Button from the following example: https://codesandbox.io/s/cranky-bassi-hk2gxj?file=/src/App.js

### Version

@react-aria/button@3.8.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

macOS

**Comment by devongovett** [comment]
I don't see `onPressDown` listed in the docs, but looks like `onPressUp` not being passed through to `usePress` is indeed a bug.
