### ISSUE TITLE
useNumberField stuck when trying to validate a form

### ISSUE THREAD

**Issue by lauritzsh** [adobe/react-spectrum#4955]
### Provide a general summary of the issue here

More details can be found at this issue https://github.com/edmundhung/conform/issues/202. The TL;DR is that when typing the library submits the form, but for some reason this means the NumberField gets stuck. @edmundhung made a nice demo to showcase this issue https://codesandbox.io/s/react-aria-components-number-not-updated-y4s5g6?file=/src/App.js. This is using the `react-aria-components` library but it's basically the same using the hooks https://codesandbox.io/s/react-aria-components-number-not-updated-forked-yzg3yq?file=/src/App.js.

Funny enough, it seems to work fine in Firefox. Other browsers are not working.

### 🤔 Expected Behavior?

The number input should be updating when writing.

### 😯 Current Behavior

The number input is not updating when writing.

### 🔦 Context

We are using Remix at work to validate the form. This means we need validation on both front-end and back-end. https://github.com/edmundhung/conform is a nice library to handle this case. However, we require to have some number inputs, currency inputs as well. What we do now is that after submit, we start validating each field on input, but this is not working as intended.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/react-aria-components-number-not-updated-y4s5g6?file=/src/App.js
https://codesandbox.io/s/react-aria-components-number-not-updated-forked-yzg3yq?file=/src/App.js

### Version

"react-aria-components": "1.0.0-alpha.6"

### What browsers are you seeing the problem on?

Chrome, Safari

### What operating system are you using?

macOS Ventura

### 🕷 Tracking Issue

https://github.com/edmundhung/conform/issues/202

**Comment by snowystinger** [comment]
I suspect that https://github.com/adobe/react-spectrum/pull/4300 and https://github.com/adobe/react-spectrum/pull/4640 may help with this issue.

**Comment by snowystinger** [comment]
I finally got a chance to look at this a little.

I don't think this is our issue. This won't work with any controlled input. See https://codesandbox.io/s/react-aria-components-number-not-updated-forked-69v5kq?file=/src/App.js with no code from us.

Controlling components is extremely common and I'm willing to be most design system implementations control their components even if you can use them in a controlled or uncontrolled way.

On a different note, our `Input` should not be used standalone. It should be used inside of our other high level components. If you put it inside a `TextField`, then it will exhibit the same behavior.

**Comment by ktabors** [comment]
Closing and we can reopen if it's still a problem.
