### ISSUE TITLE
Add directory support for FileTrigger

### ISSUE THREAD

**Issue by prabirshrestha** [adobe/react-spectrum#4963]
### Provide a general summary of the feature here

Upload selecting directories when using FileTrigger.

### 🤔 Expected Behavior?

Add support for `<FileTrigger directory>` to allow selecting directories.

### 😯 Current Behavior

Not supported

### 💁 Possible Solution

Although the property is called webkitdirectory and not directory, it is supported by Chrome, Firefox, Edge 14+, and Safari 11.1+.

https://caniuse.com/?search=webkitdirectory

Could prefix with `UNSAFE_`.

```jsx
<FileTrigger UNSAFE_directory>
```

### 🔦 Context

This allows nested folders to be supported.

**Comment by reidbarber** [comment]
Seems like a reasonable request, although I noticed `webkitdirectory` isn't even in the React types for input, so I think we would need to `ts-ignore` it. I tried locally and it passed the directory contents as the `FileList` in `onChange`, as expected.
