### ISSUE TITLE
Button `onPress` is not called when "clicking" the button via Storybook play function

### ISSUE THREAD

**Issue by csantos-nydig** [adobe/react-spectrum#4964]
### Provide a general summary of the issue here

`onPress` is not called when I write a storybook story using the `play` function executing `userEvent.click(button)`

```
export const PlayButton: ButtonStory = {
  render: (args) => render(args),
  play: async ({canvasElement}) => {
    let canvas = within(canvasElement);
    let button = await canvas.findByRole('button');
    await userEvent.click(button);
  }
};
```

### 🤔 Expected Behavior?

`onPress` to be called when using `await userEvent.click(button);` from stories

### 😯 Current Behavior

`onPress` isn't called

### 🖥️ Steps to Reproduce

- clone this repository
- add `"@storybook/testing-library": "^0.0.13",` as a dev dependency in https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/button/package.json
- add the following story to https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/button/stories/Button.stories.tsx
  ```tsx
  import {userEvent, within} from '@storybook/testing-library';

  export const PlayButton: ButtonStory = {
    render: (args) => (<Button {...args}>Default</Button>),
    play: async ({canvasElement}) => {
      let canvas = within(canvasElement);
      let button = await canvas.findByRole('button');
      console.log('button found', button);
      await userEvent.click(button);
      console.log('button clicked!');
    }
  };
  ```
  - this code is similar to https://github.com/adobe/react-spectrum/blob/4ce4d1d25ff8f89e648559c07bd7bd8d894a9492/packages/@react-spectrum/picker/stories/Picker.stories.tsx#L173
- start storybook
- go to the Button PlayButton story
- notice the `onPress` action isn't called

<img width="1429" alt="image" src="https://github.com/adobe/react-spectrum/assets/87080313/c0c0be41-451a-45a0-a69c-4e8a5d69421e">

### Version

latest `main`

### What browsers are you seeing the problem on?

N/A - issue happens in Storybook

### What operating system are you using?

N/A - issue happens in Storybook

**Comment by snowystinger** [comment]
`userEvent.click` in user-eventv12 has some issues, you could try upgrading the userEvent 14 (though it's a lot of work potentially) or you could look at our `triggerPress` https://github.com/adobe/react-spectrum/blob/main/packages/dev/test-utils/src/events.ts#L18 which we use to work around `userEvent.click` because we haven't done the upgrade either.

**Comment by snowystinger** [comment]
Closing as I think we found the solution. If not, we can reopen. Thanks!
