### ISSUE TITLE
`useCalendarState` does not allow to reset the value

### ISSUE THREAD

**Issue by sarneeh** [adobe/react-spectrum#4969]
### Provide your feedback here.

You're allowed to pass `undefined` to the `value` option to `useCalendarState` which results in an **initial** "unselected" state of the calendar, but if you select a value later, you can't come back to the default, unselected state - passing `undefined` again does not result in an empty `state.value`.

`selectDate` or `setValue` does not accept `undefined | null`, so there's no way to unset it.

### 🔦 Context

I'd like to be able to reset the calendar state.

### 💻 Code Sample

```tsx
const state = useCalendarState({
    value: undefined,
    locale,
    createCalendar: () => calendar,
})

// state.value = null

const state = useCalendarState({
    value: SOME_DATE,
    locale,
    createCalendar: () => calendar,
})

// state.value = SOME_DATE

const state = useCalendarState({
    value: undefined,
    locale,
    createCalendar: () => calendar,
})

// state.value = SOME_DATE
```

### Version

@react-stately/calendar@3.0.4

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by snowystinger** [comment]
I'm not quite sure what you're doing, but I'm able to unset the value in this codesandbox https://codesandbox.io/s/zen-liskov-vxlwgn?file=/src/App.js

If that doesn't solve it for you, could you provide a codesandbox replicating the problem along with steps?

**Comment by snowystinger** [comment]
No worries, you might want to read https://goshacmd.com/controlled-vs-uncontrolled-inputs-react/ for more information. The key being that `undefined` and `null` are different in react. `undefined` implies that the prop wasn't provided at all, while `null` says the prop was provided but purposely is empty
