### ISSUE TITLE
useSelect not scrolling to selected element when popdown opens

### ISSUE THREAD

**Issue by ashleyryan** [adobe/react-spectrum#4974]
### Provide a general summary of the issue here

I have a custom listbox component that doesn't use `useSelect` because I need multiple selection, but is implemented quite similarly to the useSelect hook. Starting with @react-aria/selection v3.16.0, the selected item no longer scrolls into focus. It works if I pin the version of react-aria/selection to v3.15.0 (I don't use react-aria/selection directly, but it's a dependency of other dependencies that I use).

I noticed I can reproduce the behavior on the `useSelect` [example on the website](https://react-spectrum.adobe.com/react-aria/useSelect.html#example). If you select Fuschia at the bottom, close the select, and then reopen it, you'll notice that Fuschia is not in focus within the visible area of the popover. If I go back to an older version of the site on the way back machine (Jun 9), it does scroll into focus: https://web.archive.org/web/20230609162236/https://react-spectrum.adobe.com/react-aria/useSelect.html#example

### 🤔 Expected Behavior?

The selected item in a listbox should scroll into focus when the popover opens

https://web.archive.org/web/20230609162236/https://react-spectrum.adobe.com/react-aria/useSelect.html#example

### 😯 Current Behavior

The selected item does not scroll into focus when the popover opens.

https://react-spectrum.adobe.com/react-aria/useSelect.html#example

### 🔦 Context

I believe this broke in the June 27 release, possibly with the React 18 strict mode update? There are some other selection-related changes from around that time too though.

https://github.com/adobe/react-spectrum/commit/06e63d3ae7898b8cd81fdb6fa87b763faf2054bf#diff-e356ae602508922357fd9cd1aa7896f74e24f87bcb2ee86a7bb4a486ea87a2f2

These are the versions of react-aria we're currently using

```json
"@react-aria/button": "^3.8.1",
"@react-aria/combobox": "^3.6.3",
"@react-aria/dialog": "^3.5.4",
"@react-aria/i18n": "^3.8.1",
"@react-aria/listbox": "^3.10.1",
"@react-aria/menu": "^3.10.1",
"@react-aria/overlays": "^3.16.0",
"@react-aria/separator": "^3.3.4",
"@react-aria/ssr": "^3.7.1",
"@react-stately/collections": "^3.10.0",
"@react-stately/combobox": "^3.6.0",
"@react-stately/list": "^3.9.1",
"@react-stately/menu": "^3.5.4",
"@react-stately/overlays": "^3.6.1",
```

And again, this makes it work, if I add the override: 

```
 "overrides": {
    "@react-aria/selection": "3.15.0"
  }
```

### 🖥️ Steps to Reproduce

I do not currently have a codesandbox with the issue (I will try and add one) but the website links above show the issue.

### Version

August 9, 2023

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS Ventura 13.5

**Comment by LFDanLu** [comment]
Looks like this was the change that caused it: https://github.com/adobe/react-spectrum/pull/4669/files#r1230347558. We wanted to align with our virtualized collection experience, but it actually seems like we do scroll the focused item in Picker even in pointer modality via https://github.com/adobe/react-spectrum/blob/3b390fd3758aa21a8b0e933b68fbf7ac5728cae8/packages/%40react-spectrum/picker/src/Picker.tsx#L94 which resolves to `autoFocus=true` here: https://github.com/adobe/react-spectrum/blob/3b390fd3758aa21a8b0e933b68fbf7ac5728cae8/packages/%40react-aria/virtualizer/src/Virtualizer.tsx#L124. Will bring this up with the team to make sure what behavior we actually want here, but I think we'll actually want to scroll these items into view as per https://github.com/adobe/react-spectrum/issues/3910 and https://github.com/adobe/react-spectrum/issues/3944

**Comment by ashleyryan** [comment]
Well, TIL that `overrides` only works for the root package.json of the running app, so the override doesn't get bundled into our library. Instead I'm trying to workaround it by manually scrolling the option into focus. I'm putting this useEffect into my ListboxPopover:

```
  useEffect(() => {
    if (overlayState.isOpen && selectedItems.length > 0) {
      const option = popoverRef.current?.querySelector(`li[aria-selected="true"][data-key="${selectedItems[0]?.key}"]`)
      
      // the issue only effects mouse users, not keyboard ones
      if (getInteractionModality() === 'pointer') {
        option?.scrollIntoView({ block: 'nearest' })
      }
    }
  }, [selectedItems, overlayState.isOpen])
  ```
  
  Is there a better way? selectedItems comes from the `collection` within the list state and `getInteractionModality` comes from `@react-aria/interactions`

**Comment by LFDanLu** [comment]
I believe that is the best way to access the selected DOM element at a glance, the `aria-selected` and `data-key` should both be fairly stable.
