### ISSUE TITLE
useId returns duplicated id

### ISSUE THREAD

**Issue by ohazda** [adobe/react-spectrum#4982]
### Provide a general summary of the issue here

After updating react-aria packages, many of my a11y tests got flagged because of a duplicated id attribute. 

```
-    "@react-aria/i18n": "^3.5.0",
-    "@react-aria/ssr": "^3.3.0",
-    "@react-aria/utils": "^3.13.2",
+    "@react-aria/i18n": "^3.8.1",
+    "@react-aria/ssr": "^3.7.1",
+    "@react-aria/utils": "^3.19.0",
```

For some reason when I click the button, it renders a new component with the id attribute which counter starts from 0 again and ignores the fact that on the server the counter was increased by 1 already.

### 🤔 Expected Behavior?

useId takes into account previously generated ids on the server.

So after I click the button the ID counter should be 2.

### 😯 Current Behavior

The counter starts from 0 for components that have been only rendered on the client side.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/simple-ssr-85zwc4

### Version

3.27

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac OS

**Comment by LFDanLu** [comment]
I think this was fixed in this PR: https://github.com/adobe/react-spectrum/pull/4913#discussion_r1295105257, can you try the latest `react-aria` nightly to see if that fixes it for you?

**Comment by ohazda** [comment]
@LFDanLu Hey, tried [3.27.1-nightly.4096](https://www.npmjs.com/package/react-aria/v/3.27.1-nightly.4096). Still seems broken. Updated the codesandbox to use the nightly version.

**Comment by LFDanLu** [comment]
No problem, thanks for verifying. I'll close this out, the above fix should go out with our next release but for now feel free to use the nightly!
