### ISSUE TITLE
<Next.PagesRouter />

### ISSUE THREAD

**Issue by kaitoukid-1412** [adobe/react-spectrum#4991]
### Provide a general summary of the issue here

Cannot be used with the `pages` directory, but the `app` is still working

https://nextjs.org/docs

### 🤔 Expected Behavior?

![image](https://github.com/adobe/react-spectrum/assets/15698245/85e2d83e-2978-419e-95ea-ee3f2bb1cb91)

![image](https://github.com/adobe/react-spectrum/assets/15698245/2eaa8950-fd7f-455f-9f1e-3870ef918449)

### 😯 Current Behavior

Failed to compile

```
./node_modules/@react-spectrum/actionbar/dist/main.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\@react-spectrum\actionbar\dist\import.mjs
```

### 🖥️ Steps to Reproduce

next `13.4.19`
react `18.2.0`
@adobe/react-spectrum `3.29.0`

### Version

3.29.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Window11

**Comment by snowystinger** [comment]
Hey! thanks for the issue, sorry you're experiencing some difficulty. Did you try following the instructions here https://react-spectrum.adobe.com/react-spectrum/ssr.html#nextjs ?
Can you provide a reproduction?

**Comment by snowystinger** [comment]
You'll forgive me for being a little wary of downloading a random rar file. Would you mind making a public git repo that has the project instead?
