### ISSUE TITLE
[RAC] `className` autocopletes to a `{}` by default

### ISSUE THREAD

**Issue by thevipinmishra** [adobe/react-spectrum#4992]
### Provide a general summary of the issue here

First of all, I'm not really sure if it belongs here, please feel free to move it to discussions otherwise.

The issue I'm facing is quite annoying, I'm using VS Code, and upon typing the class..., I get the suggestion/autocompletion of `className` like almost all other components and libraries, but upon clicking it, I get a curly bracket, instead of the usual string to add my classes.

Here you can check that in action.

![className](https://github.com/adobe/react-spectrum/assets/52159805/1bd69b26-8b8e-45e0-adf0-f723586d8ca1)

The reason I'm reporting it here is pretty obvious, that people DO NOT want a cury bracket, but a string every single time in their className autocompletion.

### 🤔 Expected Behavior?

Like almost all the component libraries and native classname's behaviour, we want it to be a `""` by default.

### 😯 Current Behavior

![className](https://github.com/adobe/react-spectrum/assets/52159805/1bd69b26-8b8e-45e0-adf0-f723586d8ca1)

### 🖥️ Steps to Reproduce

I tried reproducing it on Codesandbox, but this particular issue, doesn't apply there.

### Version

  "react-aria-components": "1.0.0-alpha.6",

### What browsers are you seeing the problem on?

Other

### What operating system are you using?

Windows (WSL)

**Comment by thevipinmishra** [comment]
Sorry, the gif's quality is pretty bad, but you get the idea.

**Comment by devongovett** [comment]
Probably because it also accepts a function, not only a string. Not sure there's anything we can do about that. Seems like a vscode/typescript issue?
