### ISSUE TITLE
React Aria Table Component Not Rounding With Tailwind Styles

### ISSUE THREAD

**Issue by u1x30** [adobe/react-spectrum#5007]
### Provide a general summary of the issue here

Cannot create table with rounded edges.  To exhaust all the possibilities, added rounded styles to each below element. Only header is rounding as expected.

### 🤔 Expected Behavior?

The table elements with rounded styles should render as rounded.  

### 😯 Current Behavior

Table and elements are rendered as squares with exception of header.  Need to render table with rounded edges.  

Here is the rendered HTML:

<table class="w-full border border-solid rounded" data-rac="" id="react-aria6703416219-:r3c:" role="grid" tabindex="0" aria-describedby="">
    <thead role="rowgroup" class="w-full">
    <tr role="row">
        <th tabindex="-1" data-key="react-aria-1" role="columnheader" id="react-aria6703416219-:r3c:-react-aria-1" class="w-40 table-header rounded-tl-xl"
            data-rac="">Name
        </th>
        <th tabindex="-1" data-key="react-aria-2" role="columnheader" id="react-aria6703416219-:r3c:-react-aria-2" class="table-header rounded-tr-xl"
            data-rac="">Value
        </th>
    </tr>
    </thead>
    <tbody role="rowgroup" class="w-full border border-solid rounded" data-rac="">
    <tr role="row" tabindex="-1" data-key="react-aria-6" aria-labelledby="react-aria6703416219-:r3c:-react-aria-6-react-aria-1"
        class="table-row overscroll-none border border-solid rounded" data-rac="">
        <td tabindex="-1" data-key="react-aria-4" role="rowheader" id="react-aria6703416219-:r3c:-react-aria-6-react-aria-1" class="p-4 border border-solid rounded"
            data-rac="">Test Name
        </td>
        <td tabindex="-1" data-key="react-aria-5" role="gridcell" class="p-4 border border-solid rounded" data-rac="">1</td>
    </tr>
    <tr role="row" tabindex="-1" data-key="react-aria-9" aria-labelledby="react-aria6703416219-:r3c:-react-aria-9-react-aria-1"
        class="table-row overscroll-none border border-solid rounded" data-rac="">
        <td tabindex="-1" data-key="react-aria-7" role="rowheader" id="react-aria6703416219-:r3c:-react-aria-9-react-aria-1" class="p-4 border border-solid rounded"
            data-rac="">Test Value
        </td>
        <td tabindex="-1" data-key="react-aria-8" role="gridcell" class="p-4 border border-solid rounded" data-rac="">20000000000000</td>
    </tr>
    </tbody>
</table>

### 💁 Possible Solution

Perhaps the style is overwritten by the component styles? 

Can please let us know how we can create a table with rounded edges? Any work around would be greatly appreciated.  

### 🔦 Context

Our website has rounded everything for rendered components so the tables do not match because react-aria table component renders table elements as squares (with exception of header elements).

### 🖥️ Steps to Reproduce

1. Create a page with below table 
import React from "react";
import {Cell, Column, Row, Table, TableBody, TableHeader} from 'react-aria-components'

export default function App() {
  return (
    <Table className="w-full border border-solid rounded"> {/*ROUNDED IGNORED, TABLE RENDERED as SQUARE*/}
    <TableHeader className="w-full">
      <Column isRowHeader={true} className="w-40 border border-solid rounded-tl-xl"> {/*WORKS as EXPECTED*/}
        Name
      </Column>
      <Column className="border border-solid rounded"> {/*WORKS as EXPECTED*/}
        Value
      </Column>
    </TableHeader>
    <TableBody className={'w-full border-solid rounded'}>{/*ROUNDED IGNORED, RENDERED as SQUARE*/}
      {
        <Row className="overscroll-none border-solid rounded">
          <Cell className={`p-4 border border-solid rounded`}> {/*ROUNDED IGNORED, RENDERED as SQUARE*/}
            Test Name
          </Cell>
          <Cell className={`p-4 border border-solid rounded`}> {/*IGNORED,  RENDERED as SQUARE*/}
            Test Value
          </Cell>
        </Row>
      })
    </TableBody>
  </Table>
)
}

2. Open page in Browser (using Brave/Chrome)

### Version

1.0.0-alpha.6

### What browsers are you seeing the problem on?

Other

### If other, please specify.

Brave (Based off Chrome)

### What operating system are you using?

Ubuntu

**Comment by reidbarber** [comment]
This is unrelated to the React Aria's Table implementation, but is more to do with Tailwind's default styling for tables. Use border-separate in order to force cells to display their own borders: https://tailwindcss.com/docs/border-collapse#separate
