### ISSUE TITLE
usePreventScroll behaves differently between usePopover and useModalOverlay

### ISSUE THREAD

**Issue by cedeber** [adobe/react-spectrum#5019]
### Provide a general summary of the issue here

If you create a Popover component that calls `usePopover` and this component takes care itself of `state.isOpen` to mount or not the html, the call of `usePopover` will automatically blocks the scroll on mount.

The same way of working is possible with a Modal component and doesn't have this bug.

The reason is that `usePopover` has
https://github.com/adobe/react-spectrum/blob/2600c965036eb66e9f4af90a8925b1f7fd165b24/packages/%40react-aria/overlays/src/usePopover.ts#L96C25-L96C25
while `useModalOverlay` stops the scroll only when opened
https://github.com/adobe/react-spectrum/blob/2600c965036eb66e9f4af90a8925b1f7fd165b24/packages/%40react-aria/overlays/src/useModalOverlay.ts#L54 

### 🤔 Expected Behavior?

calling `usePopover` should not block the scroll as long as `state.isOpen` is not `true`.

### 😯 Current Behavior

The scrolling is block as long as you mount a component that calls `usePopover`

### 💁 Possible Solution

in `usePopover`:
```js
usePreventScroll({
    isDisabled: isNonModal || !state.isOpen
});
```

### 🖥️ Steps to Reproduce

Works as expected: (imagine the triggersProps, etc...)

```jsx
<button>open</button>
<Modal><Dialog /><Modal>
```

Blocks the scroll
```jsx
<button>open</button>
<PopOver><Dialog /><Popover>
```

In both `Modal` and `Popover` we have
```jsp
return state.isOpen ? <content /> : null
```
No need to do
```jsp
<button>open</button>
{state.isOpen && <Popover><Dialog /></Popover>}
```
which is more convenient for the devs and works well with `Modal`

### Version

latest

### What browsers are you seeing the problem on?

Safari

### What operating system are you using?

macOS

**Comment by LFDanLu** [comment]
This sound reasonable to me, was poking around to see if there was a reason we hadn't added that `!state.isOpen` previously but couldn't find anything from my work in https://github.com/adobe/react-spectrum/pull/3899/ that would indicate otherwise. Further logic may need to be implemented (aka we would perhaps wait for `isOpen` to be true AND for the popover to be positioned before preventing scroll) if we revert the change where we modify the popover's node's style directly for its positioning as alluded to [here](https://github.com/adobe/react-spectrum/issues/1924#issuecomment-1524127447) but for now I think adding `!state.isOpen` is fine for now.

**Comment by nstanard** [comment]
Posted over on [a different issue](https://github.com/adobe/react-spectrum/issues/4213#issuecomment-1734476660) and then found this one. I seem to be running into something similiar to this (or maybe the same). However, setting `isNonModal` to `true|false` makes no difference to me and my popover containers are scroll locked when I use them inside `<Dialog` components.

**Comment by devongovett** [comment]
Unfortunately, this change caused some issues with animations on iOS. See #5144.

Is there a reason you are not unmounting your popover when it is not open? That seems like the easiest way to solve the issue while also waiting for exit animations.

**Comment by cedeber** [comment]
How do I make animation work then? Because
```jsx
{state.isOpen  && <Popover state={state} />}
```
will unmount the popover even before the exit animation starts.

I also can't fake a state in the parent component because then how do I know it will close soon? Or do I really have to pass 2 states and do something like
```jsx
{animatedState.isOpen  && <Popover state={state} animatedState={animatedState} />}
```

That feels like an overkill to me.

And in addition, it is not consistent with the Modal.

**Comment by devongovett** [comment]
Yeah you need two states. The state that we provide only tracks whether the user has opened or closed it, but typically you'd use an animation library like react-transition-group or Framer Motion's AnimatePresence which would handle unmounting after the animation is complete. You can also do it yourself with a second state like you mentioned, but that's what those libraries would do for you internally.
