### ISSUE TITLE
onChange doesn't behave the same way between useTextField and useNumberField

### ISSUE THREAD

**Issue by cedeber** [adobe/react-spectrum#5022]
### Provide a general summary of the issue here

While `useTextField` and `useNumberField` use both inputs of type text, the `onChange` callback for `useTextField` is fired on every key stroke (like `onInput`) whereas for `useNumberField` it is fired on on focus loss (which is the default behavior of `onChange` in the standard API)

### 🤔 Expected Behavior?

Although I prefer that the non-standard `onChange` from react-aria behaves more like `onInput`, it would be nice to have both hooks behaving the same way.

### 😯 Current Behavior

`useNumberField` calls `onChange` only on focus loss.

### 💁 Possible Solution

So for me, `useNumberField` should call `onChange` on every new input (which is how up and down keys and the buttons behaves by the way)

### 🖥️ Steps to Reproduce

Just use the hooks to any input field or use the doc to see how they behave.

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows

**Comment by devongovett** [comment]
See #1674, and the description [in the documentation](https://react-spectrum.adobe.com/react-aria/useNumberField.html#controlled) about why this is.

**Comment by cedeber** [comment]
Ok, got it for the useNumberField, makes sense, but why to keep inconsistencies between them then?
Why not having onTextField.onChange to behave like the standard onChange behaviour (only called on focus loss), and so like the useNumberField?
Or, the other way, why not trigger onChange of number field only when the value can be correctly parsed? After that's all we need in most cases.

**Comment by devongovett** [comment]
> Why not having onTextField.onChange to behave like the standard onChange behaviour (only called on focus loss), and so like the useNumberField?

Actually, number field is the exception. Other components follow React's `onChange` behavior, which is more like the `input` DOM event.

> Or, the other way, why not trigger onChange of number field only when the value can be correctly parsed?

This could cause strange behavior if the input is controlled using the `value` prop, where the input reformats as the user is typing. See https://github.com/adobe/react-spectrum/issues/1674#issuecomment-794369846

**Comment by cedeber** [comment]
I did some more tests here. The issue I have is that when the input field is in a tab (for instance, but not only) and this tab is unmounted, then the number input is not blurred, and so the value is not reported.
We are using this tabs as parameter panels you can find in lots of software like Figma, and of course users set a value and switch tab directly.
I tried not keeping those tabs mounted for perf reasons.

But I think I found a trick. By doing so, in the NumberField component:
```js
useLayoutEffect(
  () => () => {
    inputRef.current?.blur();
  },
  [],
);
```
it looks like it works as wished. The onChange callback is called as expected - only with new value, taking min/max into account, etc... - and before unmount.

Is it something react-aria hooks could consider having into useNumberField or something?

PS: For the other inputs it's never a problem as onChange is called on input, unlike the number field.

**Comment by cedeber** [comment]
I also realized that the type `AriaNumberFieldProps` is missing `InputDOMProps` (name attribute)

Imported by `TextInputDOMProps` for the `AriaTextFieldProps`.
