### ISSUE TITLE
useDateField: Press Enter key on the field tabs back a date segment

### ISSUE THREAD

**Issue by rodrigoschweitzer** [adobe/react-spectrum#5032]
### Provide a general summary of the issue here

Using the component inside of a form, pressing the Enter key tabs back a date segment instead of submitting it.

### 🤔 Expected Behavior?

Should submit the form instead of tabbing back a segment.

### 😯 Current Behavior

it tabs back a date segment.

### 🔦 Context

You can test on the useDateField docs page: 

https://react-spectrum.adobe.com/react-aria/useDateField.html#usedatefield

### 🖥️ Steps to Reproduce

1. Create a form with a DateField component
2. Fill up the field
3. Press enter

### Version

3.27.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS Ventura 13.5

**Comment by LFDanLu** [comment]
Closing in favor of https://github.com/adobe/react-spectrum/issues/5102 which has comments describing the relevant code context.
