### ISSUE TITLE
RAC - Custom Popover doesn't work

### ISSUE THREAD

**Issue by jezikk** [adobe/react-spectrum#5043]
### Provide a general summary of the issue here

I pick up `Select` example from docs:

```typescript
<Select>
        <Label>Favorite Animal</Label>
        <Button>
          <SelectValue />
          <span aria-hidden="true">▼</span>
        </Button>
        <Popover>
          <ListBox>
            <Item>Aardvark</Item>
            <Item>Cat</Item>
            <Item>Dog</Item>
            <Item>Kangaroo</Item>
            <Item>Panda</Item>
            <Item>Snake</Item>
          </ListBox>
        </Popover>
      </Select>
```

Only different is that I have created a custom Popover
```typescript
export const Popover = React.forwardRef(
  (
    { className, children, ...props }: PopoverProps,
    ref: ForwardedRef<HTMLElement>,
  ) => {
    [props, ref] = useContextProps(props, ref, PopoverContext);
    const ctx = props as PopoverContextValue;

    return ctx.state.isOpen && <span>Rendered</span>;
  },
);
```

Popover doesn't work.

### 🤔 Expected Behavior?

`state` works correctly

### 😯 Current Behavior

`state` doesn't do anything

### 🔦 Context

I want to use custom Popover to use `framer-motion` library for animation.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/rac-modal-forked-krf2mz?file=/src/components/Popover.tsx

### Version

latest

### What browsers are you seeing the problem on?

Safari

### What operating system are you using?

macOS

**Comment by binaryartifex** [comment]
@jezikk did you manage to get this working?
