### ISSUE TITLE
Date won't select the day

### ISSUE THREAD

**Issue by sinafath** [adobe/react-spectrum#5062]
### Provide a general summary of the issue here

day selection won't work correct for Persian calendar

### 🤔 Expected Behavior?

If I select the  fifth to seventh day of Mehr 1402 that range to be selected not another day

### 😯 Current Behavior

please select the fifth to seventh day of Mehr 1402 in this[ Codesandbox example](https://codesandbox.io/s/clever-rubin-gcmkkg?file=/src/App.js:0-595) that I used to replicate the bug. to do this you have to go next month and select fifth and seventh day of the next month. but what you see now is another range date has been selected

### 💁 Possible Solution

```
        function toPersianCalendar<T extends AnyCalendarDate>(date: T) {
       return toCalendar(date, new PersianCalendar());
      }
const [value,setValue] = useState()
    <DateRangePickerBase
     onChange{setValue}
        value={value?.start && value?.end &&{
          start: toPersianCalendar(field.value.start),
          end: toPersianCalendar(field.value.end),
        }} 
      />
```

### 🖥️ Steps to Reproduce

[ Codesandbox example](https://codesandbox.io/s/clever-rubin-gcmkkg?file=/src/App.js:0-595)

### Version
    "@internationalized/date": "3.0.0",
    "react-aria": "3.21.0",
    "react-stately": "3.19.0"

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

windows

**Comment by LFDanLu** [comment]
Looks like the issue is specifically with any of the months ahead of the current date, any of the months before the current date don't exhibit this issue. Possibly related to https://github.com/adobe/react-spectrum/issues/3757#issuecomment-1446846517, where it was noted that the `isSameDay` helper util has problems comparing the persian dates with gregorian ones
