### ISSUE TITLE
Issues with Safari

### ISSUE THREAD

**Issue by ccorcos** [adobe/react-spectrum#5068]
### Provide a general summary of the issue here

Has anyone else noticed that the documentation website is really buggy in MacOS Safari?

When I go [here](https://react-spectrum.adobe.com/react-aria/) the first time in an incognito window, it loads quickly, but then none of the buttons or links work.

When I create a new tab (in the same incognito window), and go to the same link, the page never loads...

### 🤔 Expected Behavior?

I expected this library to work in Safari

### 😯 Current Behavior

It's unusable.

### 💁 Possible Solution

No idea, I'm new to this and evaluating whether I should use it.

### 🖥️ Steps to Reproduce

Open up Safari and go it https://react-spectrum.adobe.com/react-aria/

### Version

Whatever the documentation website is using

### What browsers are you seeing the problem on?

Safari

### What operating system are you using?

MacOS 13.5.1

**Comment by devongovett** [comment]
I can't reproduce it on Safari 16.6.

**Comment by snowystinger** [comment]
I can't reproduce it either. I'm also on Safari 16.6

**Comment by yihuiliao** [comment]
I'm also unable to reproduce; Safari 16.6, MacOS 13.5.2, M1

**Comment by dannify** [comment]
Cannot reproduce on 16.3 MacOS 13.2

**Comment by ccorcos** [comment]
Here's a video for those who haven't been able to reproduce: https://www.loom.com/share/de4daab04c2348088b24b1cf7d0d83d5

**Comment by reidbarber** [comment]
I've been investigating, and haven't found anything noteworthy yet. Since the profiler in dev tools crashes, it's difficult to debug. I've been looking for crash logs but haven't found anything useful yet.

**Comment by ccorcos** [comment]
@LFDanLu this one works for me: https://reactspectrum.blob.core.windows.net/reactspectrum/f6239e3581d22f4d093525202d7d1afc160bff42/verdaccio/docs/react-aria/index.html

**Comment by LFDanLu** [comment]
Gotcha, thank you for the quick reply, we'll keep digging. @reidbarber I can try updating my OS since we both have Intel machines and see if I can reproduce

**Comment by ccorcos** [comment]
I'm on on M1 Mac btw.

**Comment by reidbarber** [comment]
Upgraded to Safari 17.0 and I'm still having issues unfortunately.

**Comment by theMosaad** [comment]
Had the same issue for a while. Tracked it down now to Safari's page zoom. I have Safari's Page Zoom set to 150% by default which causes this unresponsiveness.

Was able to fix by increasing or decreasing the Page Zoom via Safari -> settings for react-spectrum.adobe.com -> Page Zoom

**Comment by snowystinger** [comment]
I'm still unable to reproduce, went through Safari -> settings -> website -> page zoom 150% and I can still interact with the page.

Just making sure, but I noticed some of the animations only partially play through when at 150% zoom on my laptop screen which makes them hard to see/discover, are you positive the buttons etc that you are having trouble interacting with are not part of one of the animation examples?

Maybe some more specific steps to reproduce on a specific example would help?

**Comment by theMosaad** [comment]
I couldn't reproduce on a macbook air either. Might have to do with the screen dimensions cause that's the main difference between the 2 machines.

If it's of any help, here's more details about the machine with the issue:
- Device: Mac mini m1
- OS: Sonoma 14.5 
- Display: 27-inch (2560 × 1440)
- Page Zoom: 150% making the html's width 1697px (resizing the browser to the same width didn't cause the issue)

Happy to hop on a call or provide any further info if needed.

**Comment by theMosaad** [comment]
> It loads if I disable JavaScript, so that's at least something.

Can confirm it's the case for me as well.

The exact file causing the issue is https://react-spectrum.adobe.com/getting-started.0a08bbbc.js, the site works when I block this URL from loading.

**Comment by snowystinger** [comment]
@yihuiliao and I can reproduce now.

**Comment by snowystinger** [comment]
I believe I've fixed it, PR linked https://github.com/adobe/react-spectrum/pull/6930
