### ISSUE TITLE
'usePopover' position renders incorrectly for placement 'left | right'

### ISSUE THREAD

**Issue by kim-fransson** [adobe/react-spectrum#5079]
### Provide a general summary of the issue here

Popover is not placed correctly for left / right side.

### 🤔 Expected Behavior?

Would see a popover renders either to the left side or the right side

### 😯 Current Behavior

Page is locked, but can't see the rendered popover

### 🖥️ Steps to Reproduce

https://react-spectrum.adobe.com/react-aria/usePopover.html#placement

Click on 'button with left arrow' or 'button with right arrow'

### Version

3.28.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

Ubuntu 20.04 LTS (ubuntu on windows)

**Comment by snowystinger** [comment]
I can reproduce in Chrome 116 on MacOS. Thanks for opening an issue!

**Comment by kim-fransson** [comment]
I have not had time to look into it in more detail, but my gut feeling says that its probably related to browser version update. I will try and run some visual tests on chromatic (think they use some older browser versions)

**Comment by yihuiliao** [comment]
Looks like it broke in [this PR](https://github.com/adobe/react-spectrum/pull/4917)
