### ISSUE TITLE
cannot navigate tabs with Tab key

### ISSUE THREAD

**Issue by fredericrous** [adobe/react-spectrum#5092]
### Provide a general summary of the issue here

I cannot navigate the tabs from the Tabs component with keyboard's Tab key

### 🤔 Expected Behavior?

I believe I should be able to navigate the tabs with the Tab key, like I do on Github 

<img width="488" alt="image" src="https://github.com/adobe/react-spectrum/assets/702227/89990972-0ba7-4adc-94ef-9ba83f2dd839">

### 😯 Current Behavior

only the current tab can be selected, the other tabs cannot be selected with Tab

<img width="409" alt="image" src="https://github.com/adobe/react-spectrum/assets/702227/1bb22547-a7f9-40bd-a6ac-1eb8a872974a">

### 💁 Possible Solution

tabindex should be 0, not -1 for the non selected tabs

### 🖥️ Steps to Reproduce

go to https://react-spectrum.adobe.com/react-spectrum/Tabs.html#tabs try to navigate the tabs with Tab key, you cannot select other tabs than the current tab

### Version

2.21.0-beta.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macos 12.5

**Comment by LFDanLu** [comment]
We follow the interaction pattern outlined [here](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/).  This allows the user to quickly tab to the TabPanel content related to the currently selected Tab, and still allows the user to shift focus between the Tabs via the arrow keys.

**Comment by fredericrous** [comment]
That's interesting. thank you for linking the exact wai-aria doc. arrows indeed work to navigate the tabs.

Notice the tab menu of this website can be navigated with Tab key tho 🤣

<img width="780" alt="image" src="https://github.com/adobe/react-spectrum/assets/702227/61821eba-3505-433a-9706-1a73aa715c82">
