### ISSUE TITLE
Behavior of Aria Attributes in the Latest Version of @react-aria/slider

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#5103]
### Provide a general summary of the issue here

blank aria attributes are added to slider thumb inputs
See https://github.com/adobe/react-spectrum/discussions/5098

### 🤔 Expected Behavior?

These attributes should not be on the input

### 😯 Current Behavior

There are empty aria labelling attributes on the input

### 🔦 Context

It broke in this PR https://github.com/adobe/react-spectrum/pull/4960

### 🖥️ Steps to Reproduce

Go to https://react-spectrum.adobe.com/react-aria/useSlider.html#single-thumb
inspect the hidden thumb input

### Version

prod docs

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by LFDanLu** [comment]
Unable to reproduce any long on said docs page, the aria attributes on the hidden input are properly populated
