### ISSUE TITLE
Tooltip position near the edge

### ISSUE THREAD

**Issue by crazko** [adobe/react-spectrum#5105]
### Provide a general summary of the issue here

During the implementation of our custom Tooltip component with `useTooltipTriggerState()`, `useTooltipTrigger()` and `useTooltip()` that is positioned with `useOverlayPosition()` (similarly to [`@react-spectrum/tooltip`](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/tooltip/src/TooltipTrigger.tsx)) I noticed that the position is not calculated properly near the edge of the viewport.

When there's just enough space for a tooltip to fit in its position flips on subsequent renders. I was able to simulate this behavior also with `@react-spectrum/tooltip` itself in the Storybook:

![tooltip-position](https://github.com/adobe/react-spectrum/assets/1255989/b3a441e4-41df-49f0-831d-6d5a33a22058)

Another issues connected to this is that when tooltip element does not have minimal height set (similar to [what @react-spectrum/tooltip has](https://github.com/adobe/react-spectrum/blob/a399db1e314243a023f7b5c95e319eba4496604c/packages/%40adobe/spectrum-css-temp/components/tooltip/index.css#L37)) it may happen that it is not rendered properly in Firefox:

![tooltip-position-height](https://github.com/adobe/react-spectrum/assets/1255989/5e79be5c-2d11-4194-81c9-e8460616d708)

I think that in this case the `top` and `bottom` values are used at the same time, but `bottom` has a higher value than `top`.

### 🤔 Expected Behavior?

Position of the tooltip should not flip on subsequent renders when the available space has not changed.

It should also not depend on the minimal height of the element set with CSS. 

### 😯 Current Behavior

Tooltip's position changes when there's just enough space for it.

### 💁 Possible Solution

I assume the problem is connected with [`calculatePosition()` function](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/overlays/src/calculatePosition.ts) and `PARSED_PLACEMENT_CACHE` , but I'm not really sure.

### 🖥️ Steps to Reproduce

- [open Storybook](https://reactspectrum.blob.core.windows.net/reactspectrum/3671c22a521bfd011a8921cd006033a4fb35edca/storybook/index.html?path=/story/tooltiptrigger--multiple-tooltips&args=placement:top&providerSwitcher-express=false)
- be sure `placement` is set to `top`
- change the window size so there's a space for one tooltip at the top of the viewport

### Version

react-aria@3.26.0, react-stately@3.24.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Windows 11

**Comment by snowystinger** [comment]
This appears to have been fixed at some point, I can not reproduce in our most recent builds. I'm going to close, if it's still an issue, we can reopen.
