### ISSUE TITLE
Expose `clientX` and `clientY` in `onPress` event.

### ISSUE THREAD

**Issue by GermanJablo** [adobe/react-spectrum#5115]
### Provide a general summary of the feature here

I'm trying to implement a ripple effect on a button, similar to what [NextUI](https://nextui.org/docs/components/button) has.
I'm basing it on this hook: https://github.com/cbadger85/react-use-ripple/

However, for the wave to start in the PressEvent place I need to access clientX and clientY.

### 🤔 Expected Behavior?

.

### 😯 Current Behavior

.

### 💁 Possible Solution

.

### 🔦 Context

.

### 💻 Examples

.

**Comment by reidbarber** [comment]
There is an existing issue for this at https://github.com/adobe/react-spectrum/issues/5115 and WIP PR at https://github.com/adobe/react-spectrum/pull/4267.

**Comment by reidbarber** [comment]
Closing as duplicate
