### ISSUE TITLE
[RAC] ComboBox stays open after selection

### ISSUE THREAD

**Issue by emlai** [adobe/react-spectrum#5120]
### Provide a general summary of the issue here

https://github.com/adobe/react-spectrum/assets/7543552/eb7f698f-d16e-4356-8593-3139fcd23e59

### 🤔 Expected Behavior?

ComboBox popover closes after selecting an item.

### 😯 Current Behavior

ComboBox popover stays open after selecting an item.

### 💁 Possible Solution

Workaround: control the input value via `inputValue` and `onInputChange`, then this bug doesn't happen.

### 🖥️ Steps to Reproduce

I haven't been able to reproduce the issue in [this CodeSandbox](https://codesandbox.io/s/bitter-morning-nchy6t?file=/src/App.js) yet, so any pointers on where to look for the bug would be appreciated. But the code in the sandbox matches what we have, minus the styling related code.

### Version

Reproduced in 1.0.0-beta.0 and 1.0.0-nightly.4153

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by LFDanLu** [comment]
I've reproduced this locally, seems to be that tracked internal input value state isn't updated to the newly selected value after [the following](https://github.com/adobe/react-spectrum/blob/f65c181868be342a9238e5c26c12a1a0d346ca2f/packages/%40react-stately/combobox/src/useComboBoxState.ts#L169-L171) is called, messing up our tracked [lastValue](https://github.com/adobe/react-spectrum/blob/f65c181868be342a9238e5c26c12a1a0d346ca2f/packages/%40react-stately/combobox/src/useComboBoxState.ts#L231) and causing the next run of our useEffect logic to think we are in the case where the [input value was modified by the user](https://github.com/adobe/react-spectrum/blob/f65c181868be342a9238e5c26c12a1a0d346ca2f/packages/%40react-stately/combobox/src/useComboBoxState.ts#L181-L189) and thus reopens the menu. Curiously enough, it doesn't happen in our [docs](https://react-spectrum.adobe.com/react-aria/ComboBox.html#selection) with the same configuration, still digging as to why
