### ISSUE TITLE
The typing of DatePickerState.setValue does not accept null values, despite the function itself having the ability to handling null values 

### ISSUE THREAD

**Issue by sghmk12** [adobe/react-spectrum#5122]
### Provide a general summary of the issue here

Despite `null` being a valid state value for the state produced by the `react-stately` `useDatePickerState` hook. The `setValue` function returned from the hook itself does not accept null as a valid parameter in the TypeScript types.

The hook automatically sets its own state to `null` when dates are deleted so this should be part of the typing for `setValue`.

<img width="624" alt="image" src="https://github.com/adobe/react-spectrum/assets/13241633/909403f7-9857-45d9-9757-b9ac0bbe292b">

### 🤔 Expected Behavior?

the types for state setting in the `DatePickerState` class should accept null as a valid input

### 😯 Current Behavior

The types of `setValue` and `setDateValue` in `DatePickerState` do not accept null in the types

### 🖥️ Steps to Reproduce

Open the generated types.d.ts file from `react-aria/datepicker`

### Version

@react-aria/datepicker@3.5.0

### What browsers are you seeing the problem on?

Chrome, Other

### If other, please specify.

This is a code problem

### What operating system are you using?

Mac OS 13

**Comment by LFDanLu** [comment]
This has been fixed in https://github.com/adobe/react-spectrum/pull/5052, will be going out in the next release tentatively scheduled for early October.
