### ISSUE TITLE
TableView RangeError: Maximum call stack size exceeded during page redirections

### ISSUE THREAD

**Issue by jay09prakash** [adobe/react-spectrum#5127]
### Provide a general summary of the issue here

In a TableView component with a collapsible rows feature, navigating back to the TableView after redirecting back from a navigated page causing the RangeError: Maximum call stack size exceeded

To reproduce the problem, click on the expandable row, which (in my case) will navigate to another page,  clicking the back button and then clicking on the expand row again to see the collapsed rows. It errors out. ( Screen shot of the error attached). Also, sometimes, clicking on the row does not properly does not listen to the handlers.  
![image](https://github.com/adobe/react-spectrum/assets/106740324/8577f18e-5297-4ba9-9c86-1bfdfc69daf8)

### 🤔 Expected Behavior?

Expected behavior is to still see the collapsed rows irrespective of any page navigationsThe expected

### 😯 Current Behavior

Maximum call stack error.

### 🖥️ Steps to Reproduce

To reproduce the problem, click on the expandable row, which (in my case) will navigate to another page,  clicking the back button would navigate back to the page where the TableView component renders,  and then clicking on the expand row again to see the collapsed rows. It errors out.

### Version

3

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac

### 🧢 Your Company/Team

Adobe

**Comment by LFDanLu** [comment]
Thanks for filing this! I know we chatted on slack about seeing if your were able to reproduce in a [codesandbox](https://codesandbox.io/s/react-spectrum-template-syueo), were you able to do so or did it not reproduce?

**Comment by LFDanLu** [comment]
@jay09prakash Does this still happen after the fix you applied that we chatted in Slack about?

**Comment by jay09prakash** [comment]
@LFDanLu, This ticket can be closed as the issue couldn't be recreated.  The most probable cause for this issue could be not having the data in the nested row format with duplicate entries/cells.  I will file the ticket if I come across this issue in the future.

**Comment by LFDanLu** [comment]
Sounds good, thanks!
