### ISSUE TITLE
Popover does not work inside scrollable div

### ISSUE THREAD

**Issue by tuananhlai** [adobe/react-spectrum#5139]
### Provide a general summary of the issue here

Popover component stays open and doesn't update its position when it's put inside a scrollable div.

The video below demonstrate what I meant. I'm using ComboBox element here, which uses Popover under the hood. Here's the [CodeSandBox](https://codesandbox.io/s/bold-hodgkin-g7324l?file=/src/App.js) link.

https://github.com/adobe/react-spectrum/assets/42168740/94b0369a-ff41-4fa7-bcd3-78a45dd5bb85

### 🤔 Expected Behavior?

The Popover should close, or its position should be updated when the parent div is scrolled.

### 😯 Current Behavior

The Popover neither close, nor update its position when the parent div is scrolled.

### 💁 Possible Solution

LFDanLu suggested updating this line to achieve the desired behavior.

https://github.com/adobe/react-spectrum/discussions/5132#discussioncomment-7117165

### 🖥️ Steps to Reproduce

1. Put React Spectrum's ComboBox within a scrollable div.
2. Open the ComboBox's Popover.
3. Scroll the parent div.

[CodeSandBox](https://codesandbox.io/s/bold-hodgkin-g7324l?file=/src/App.js)

### Version

latest

### What browsers are you seeing the problem on?

Firefox

### What operating system are you using?

MacOS

**Comment by boutahlilsoufiane** [comment]
Hi @LFDanLu, I faced this issue  before and I solved it by passing a `portalContainer` to `Overlay` component.
In this case, I think we should add a new prop `portalContainer` to the component `ComboBox`.

**Comment by boutahlilsoufiane** [comment]
Hi @LFDanLu, I proposed a fix, can you please check the PR.

**Comment by LFDanLu** [comment]
Apologies for not getting back to you sooner, I must've missed this when I was on break. We've had similar requests in the past for the RAC side but the team isn't sure of all the places where we may inadvertently rely on the `document.body` being where the popover is portalled (see https://github.com/adobe/react-spectrum/pull/4573#issuecomment-1581689337). I can bring this up to the team to see if we can get some time to prioritize digging into overlay positioning but the timeline for it is largely unknown unfortunately.

**Comment by boutahlilsoufiane** [comment]
Hi LFDanLu, I think it's an important issue, otherwise could you suggest any issue to fix?

**Comment by LFDanLu** [comment]
The team talked about this some more yesterday. We are entertaining the idea of allowing users to specify the `portalContainer` for RAC/aria hooks like its done in https://github.com/adobe/react-spectrum/pull/5381, but we would want to make it clear in the prop description/naming that it is largely unknown what cases may fail if the overlay is portalled somewhere unexpected (e.g. portalled to a third party FocusScope, etc). As for React Spectrum ComboBox, we'd like to make it close on scroll like it used to. https://github.com/adobe/react-spectrum/discussions/5132#discussioncomment-7117165 outlines a possible code change to make this happen but it is untested still.

**Comment by boutahlilsoufiane** [comment]
Hi @LFDanLu, do we close the popover on scroll ? Do I change the hook usePopover?

**Comment by LFDanLu** [comment]
@boutahlilsoufiane yep, the team would like the combobox's popover to close on scroll, theoretically applying the change to usePopover mentioned [here](https://github.com/adobe/react-spectrum/discussions/5132#discussioncomment-7117165) would make that happen.

**Comment by boutahlilsoufiane** [comment]
Hi @LFDanLu, the PR is ready!

**Comment by LFDanLu** [comment]
Thank you, I'll take a look!
