### ISSUE TITLE
TextField validity icons are clipped; could be missing css variable

### ISSUE THREAD

**Issue by donaldr** [adobe/react-spectrum#5149]
### Provide a general summary of the issue here

The textfield validity icons have erroneous padding. Looking at the source I see that an undefined css var exists: `--spectrum-icon-alert-medium-width`. I can't seem to find it in either the react-spectrum codebase or the spectrum-css codebase. 
<img width="144" alt="Screenshot 2023-09-27 145034" src="https://github.com/adobe/react-spectrum/assets/327828/e896d2e0-5cd1-4ed5-8fab-d9d33a7f40cc">
<img width="149" alt="Screenshot 2023-09-27 145042" src="https://github.com/adobe/react-spectrum/assets/327828/6d854ed6-6dad-4965-9b4c-cdab987e8d10">

### 🤔 Expected Behavior?

Icons should be properly spaced

### 😯 Current Behavior

Icon is clipped

### 🖥️ Steps to Reproduce

Just include this: 

<TextField validationState={invalid}/>

### Version

3.30

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 11

**Comment by donaldr** [comment]
False alarm. This is actually a side effect of something horribly egregious. Tailwind applies box-sizing border box **to all html elements**! Although you may want to decide whether to document somewhere that react-spectrum and tailwind don't play nice together, OR add some css to have all react spectrum elements set to content-box.

**Comment by donaldr** [comment]
I fixed it by undoing tailwind's specific boilerplate by adding the following css after:

```
::before, ::after {
  box-sizing: content-box;
}

*, ::before, ::after {
  box-sizing: content-box;
}
```

**Comment by snowystinger** [comment]
CSS resets like that are so very difficult to deal with. We've been trying to add the box-sizing explicitly to components, but we haven't gotten all of them. We'd be open to a PR adjusting ones you found.

I am going to close this as I wouldn't consider this to be an issue on our end. I think it's unrealistic to apply this to every element in the entire codebase.
