### ISSUE TITLE
[RAC] `'React' has no exported member 'JSX'`

### ISSUE THREAD

**Issue by alanhajo-ui** [adobe/react-spectrum#5157]
### Provide a general summary of the issue here

When using Aria components and running `tsc --noEmit`, we get a ton of errors almost concerning the entire package.

The main issue being the `Namespace 'React' has no exported member 'JSX'`,
but there is also `Namespace 'Intl' has no exported member 'ListFormatOptions'`

TS version: 5.2.2 (latest)

```zsh
node_modules/@react-aria/focus/dist/types.d.ts:51:59 - error TS2694: Namespace 'React' has no exported member 'JSX'.

51 export function FocusScope(props: FocusScopeProps): React.JSX.Element;
                                                             ~~~

node_modules/@react-aria/i18n/dist/types.d.ts:22:63 - error TS2694: Namespace 'React' has no exported member 'JSX'.

22 export function I18nProvider(props: I18nProviderProps): React.JSX.Element;
                                                                 ~~~

node_modules/@react-aria/i18n/dist/types.d.ts:48:49 - error TS2694: Namespace 'Intl' has no exported member 'ListFormatOptions'.

48 export function useListFormatter(options?: Intl.ListFormatOptions): Intl.ListFormat;
                                                   ~~~~~~~~~~~~~~~~~

node_modules/@react-aria/i18n/dist/types.d.ts:48:74 - error TS2694: Namespace 'Intl' has no exported member 'ListFormat'.

48 export function useListFormatter(options?: Intl.ListFormatOptions): Intl.ListFormat;
                                                                            ~~~~~~~~~~

node_modules/@react-aria/overlays/dist/types.d.ts:136:65 - error TS2694: Namespace 'React' has no exported member 'JSX'.

136 export function ModalProvider(props: ModalProviderProps): React.JSX.Element;
                                                                    ~~~

node_modules/@react-aria/overlays/dist/types.d.ts:156:67 - error TS2694: Namespace 'React' has no exported member 'JSX'.

156 export function OverlayProvider(props: ModalProviderProps): React.JSX.Element;
                                                                      ~~~

node_modules/@react-aria/overlays/dist/types.d.ts:199:65 - error TS2694: Namespace 'React' has no exported member 'JSX'.

199 export function DismissButton(props: DismissButtonProps): React.JSX.Element;
                                                                    ~~~

node_modules/@react-aria/select/dist/types.d.ts:308:69 - error TS2694: Namespace 'React' has no exported member 'JSX'.

308 export function HiddenSelect<T>(props: HiddenSelectProps<T>): React.JSX.Element;
                                                                        ~~~

node_modules/@react-aria/visually-hidden/dist/types.d.ts:26:67 - error TS2694: Namespace 'React' has no exported member 'JSX'.

26 export function VisuallyHidden(props: VisuallyHiddenProps): React.JSX.Element;
                                                                     ~~~

node_modules/react-aria-components/dist/types.d.ts:1034:65 - error TS2694: Namespace 'React' has no exported member 'JSX'.

1034 export function DialogTrigger(props: DialogTriggerProps): React.JSX.Element;
                                                                     ~~~

node_modules/react-aria-components/dist/types.d.ts:1215:61 - error TS2694: Namespace 'React' has no exported member 'JSX'.

1215 export function MenuTrigger(props: MenuTriggerProps): React.JSX.Element;
                                                                 ~~~

node_modules/react-aria-components/dist/types.d.ts:2076:76 - error TS2694: Namespace 'React' has no exported member 'JSX'.

2076 export function TooltipTrigger(props: TooltipTriggerComponentProps): React.JSX.Element;
                                                                                ~~~
```

### 🤔 Expected Behavior?

No errors.

### 😯 Current Behavior

Unusable due to errors.

### 💁 Possible Solution

Perhaps changing `React.JSX.Element` to just `JSX.Element`?

### 🖥️ Steps to Reproduce

1. Install `react 16.14.0` & `react-aria-components 1.0.0-beta.0`
2. Use an aria component somewhere in the app
3. Run `tsc --noEmit`

### Version

RAC 1.0.0-beta.0

### What browsers are you seeing the problem on?

Other

### If other, please specify.

Before compilation

### What operating system are you using?

macOS Ventura

**Comment by LFDanLu** [comment]
What version of `react-types` are you on? Also what does your tsconfig look like (specifically the target)?

**Comment by mtpetros** [comment]
I ran into this as well a few days ago when installing the latest version of some Spectrum packages. The dist includes the breaking type `React.JSX.Element` which is specific to React v18 (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L3306-L3323), so I had to downgrade a few minors in order to avoid the break and use dependency resolutions to pin the Spectrum packages transitive dependencies at the desired minor version.

I downloaded the tarball of `@react-aria/overlays@3.17.0` to verify (https://registry.npmjs.org/@react-aria/overlays/-/overlays-3.17.0.tgz) and that type is definitely being used.

**Comment by snowystinger** [comment]
Just crossing t's and dotting i's, can you try deleting your lock file and re-installing?

if there's too many other things going on, can you check for duplicate packages of react's types and if you have any, resolve it down to one version?
I hope this will resolve the React namespace one, though it's a bit odd to be on react 16 but using types for 18, I don't know if that will cause an issue.

As for the Intl namespace, it's in TS ^5, but you might need to adjust your target, see https://www.typescriptlang.org/play?target=9&ts=5.2.2#code/FAGwpgLgBAhgXFAkgOwiAdAGQJYGcIBiA9gE4C2MEA8gA4TZHK4DcwQA

**Comment by torgeadelin** [comment]
Does react-aria support react 16 still? If yes, would it makes sense to make sure the types are also backwards compatible?

**Comment by snowystinger** [comment]
I believe React 16 supports accessing JSX from the React namespace? https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fa8e0fff1e5be797ebf5bd4e597bfa99f0a1b8b5/types/react/v16/index.d.ts#L3132

What issue are you running into?
