### ISSUE TITLE
`useColorFieldState` doesn't trigger onChange if alpha changes

### ISSUE THREAD

**Issue by ritz078** [adobe/react-spectrum#5168]
### Provide a general summary of the issue here

If I just change the alpha value of hex and set it to `ColorFieldState`, `onChange` is not triggered. Basically, `useColorFieldState` assumes that there is no difference between `#FFFFFF00` and `#FFFFFFFF`. 

### 🤔 Expected Behavior?

If the alpha value changes, they should be treated as different values.

### 😯 Current Behavior

Alpha value in hex is ignored during comparison

### 🖥️ Steps to Reproduce

In the below example, if you click on white after transparent or vice versa, `onChange` is not triggered.

https://codesandbox.io/s/quirky-dhawan-twtk62?file=/src/App.js:314-323

### Version

3.28.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by LFDanLu** [comment]
I believe the work in https://github.com/adobe/react-spectrum/pull/3302 will cover this, cc @snowystinger.
