### ISSUE TITLE
`SelectState.selectedItem` incorrectly typed? 

### ISSUE THREAD

**Issue by DavidAmmeraal** [adobe/react-spectrum#5169]
### Provide a general summary of the issue here

When using `useSelect` as described in https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/list/src/useSingleSelectListState.ts the type of `selectedItem` is `Node<T>` (so not `Node<T> | undefined`).

This causes issues when turning on `@typescript-eslint/no-unnecessary-condition` and checking if `selectedItem` exists, because according to the type it can't be undefined. 

### 🤔 Expected Behavior?

I would expect `SelectState.selectedItem`  to be typed as `Node<T> | undefined`. 

### 😯 Current Behavior

When using `useSelect` as described in https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/list/src/useSingleSelectListState.ts the type of `selectedItem` is `Node<T>` (so not `Node<T> | undefined`).

### 💁 Possible Solution

Type `SelectState.selectedItem` to be `Node<T> | undefined`.

### 🔦 Context

This is causing issues because from types it's not clear the value could possibly be undefined. 

### 🖥️ Steps to Reproduce

Can reproduce it here, at least you can inspect selectedItem and see that the type is `Node<T>`, eslint rule isn't complaining, I guess because it needs typing and isn't being run on codesandbox. 

### Version

3.28.0

### What browsers are you seeing the problem on?

Other

### What operating system are you using?

Mac OS 14.0 (23A344)

**Comment by reidbarber** [comment]
We are incrementally adding support for Typescript's Strict Mode, so this should get handled here: https://github.com/adobe/react-spectrum/issues/3183. We plan on tackling more of these soon. I'll close this as a duplicate.
