### ISSUE TITLE
Not possible to listen to `onBlur` for custom-styled checkboxes 

### ISSUE THREAD

**Issue by doytch** [adobe/react-spectrum#5183]
### Provide a general summary of the feature here

When rendering a custom-styled checkbox, [the suggested approach in the docs](https://react-spectrum.adobe.com/react-aria/useCheckbox.html#styling) is to render a `VisuallyHidden` `input` which listens to focus events and render the focus visibility via `useFocusRing`.

The problem is that if you build out a `Checkbox` component like this, you can't support an `onBlur` prop for your component. Even though `useCheckbox` takes an `onBlur` argument in its props, there's no simple way of passing that to your `focusProps` via `useFocusRing`.

Instead, you end up cobbling something together like this:
```
      <VisuallyHidden>
        <input
          {...inputProps}
          {...focusProps}
          onBlur={(e) => {
            inputProps.onBlur?.(e);
            focusProps.onBlur?.(e);
          }}
          ref={ref}
        />
      </VisuallyHidden>
```

Ideally, we could do something as below:
```
const { inputProps } = useCheckbox({ onBlur: props.onBlur, ... }, state, ref);
const { focusProps } = useFocusRing(inputProps);
// focusProps.onBlur now calls the internal focusRing logic and the original `props.onBlur`
```

FWIW, I'd actually side-eye that DX a bit, but I offer it since it seems like the prevailing style in the library. I'd probably prefer using it a bit more directly like:
```
const { inputProps } = useCheckbox(props, state, ref);
const { focusProps } = useFocusRing({ onBlur: props.onBlur );
```

### 🤔 Expected Behavior?

  See description

### 😯 Current Behavior

See description

### 🔦 Context

I'd like to be able to create a component that uses `useCheckbox` and provides an `onBlur` prop for users.

**Comment by snowystinger** [comment]
I think you want to use `mergeProps` https://react-spectrum.adobe.com/react-aria/mergeProps.html#mergeprops
```
      <VisuallyHidden>
        <input
          {...mergeProps(inputProps, focusProps)}
          ref={ref}
        />
      </VisuallyHidden>
```

and I think we should update that example to do the same, looks like a bug

**Comment by doytch** [comment]
Ahhh, yes that makes sense - and works! 

Appreciate the quick response.
