### ISSUE TITLE
Add `isRootDropTarget` parameter to `renderEmptyState` in `GridList` component

### ISSUE THREAD

**Issue by gennadiipel** [adobe/react-spectrum#5210]
### Provide a general summary of the feature here

Add `isRootDropTarget` parameter to `renderEmptyState` in `GridList` component.

This might be useful when you want to change the content of a placeholder depending on whether there is a dragging element over the grid list root or not similar to `DropIndicator` where the flag `isDropTarget` returned in a `className`.

```
<DropIndicator target={target} className={({ isDropTarget }) => ...} />
```

Currently as far as I understand there is no way to check it using `GridList` from `react-aria-components` although it is possible using low-level hooks.

### 🤔 Expected Behavior?

I would expect `isRootDropTarget` boolean to be returned as a param for `renderEmptyState` in a `GridList`.

Something like that:

```
<GridList
      ...
      renderEmptyState={(isRootDropTarget) => {
        return (
          <span style={{ color: isRootDropTarget ? "red" : "black" }}>
            Drop items here
          </span>
        );
      }}
      dragAndDropHooks={dragAndDropHooks}
      ...
```

### 😯 Current Behavior

Currently I couldn't find any solution to check if the root is a drop target or not with `react-aria-components`. So we've been using CSS for that accessing grid list with `data-drop-target` attribute:

```
.gridList[data-drop-target] .rootDrop ...
```

### 💁 Possible Solution

WIP version here: #5211

### 🔦 Context

It becomes an issue when we needed to check whether the root is currently a drop target or not and just using CSS selectors is not enough.

**Comment by reidbarber** [comment]
I think this is a good idea. Went ahead and left a review at https://github.com/adobe/react-spectrum/pull/5211. Maybe others can chime on whether this is how we want to handle this.
