### ISSUE TITLE
Export Color classes

### ISSUE THREAD

**Issue by tpict** [adobe/react-spectrum#5213]
### Provide a general summary of the feature here

Please export the Color classes from https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/color/src/Color.ts so that they can be used for `instanceof` checks etc

### 🤔 Expected Behavior?

Color classes should be importable

### 😯 Current Behavior

Color classes are not importable

### 💁 Possible Solution

You can do something like

```js
const Hsl = parseColor("hsl(0, 0%, 0%)").constructor;
const Color = parseColor("hsl(0, 0%, 0%)").__proto__.__proto__.constructor;
```

but that's nasty.

### 🔦 Context

I can't use the Color classes for `instanceof` checks etc

**Comment by snowystinger** [comment]
Instead of instanceof, you could use `getColorSpace`? were there other reasons for needing access to the class itself?

**Comment by tpict** [comment]
I’m using [zod](https://github.com/colinhacks/zod) for form validation. It would be useful to be able to represent colors directly with the class instead of parsing/formatting to string etc

**Comment by snowystinger** [comment]
Ah, i see, for this? https://github.com/colinhacks/zod#instanceof
Could we just export the abstract Color class? then we still wouldn't be exposing anything new in terms of API, and because all of the actual instances of RGBColor, HSLColor etc all extend Color, instanceof should still pass. Do we need to be more fine-grained than that?

**Comment by tpict** [comment]
@snowystinger that would be perfect!

**Comment by snowystinger** [comment]
Closing see https://github.com/adobe/react-spectrum/pull/5214#issuecomment-1760401195

**Comment by tpict** [comment]
would it be possible to have the color classes inherit from an empty class then, for the use case I described? That way, it wouldn't expose any implementation details
