### ISSUE TITLE
Second digit not working on time field after previous data is cleared

### ISSUE THREAD

**Issue by akzhy** [adobe/react-spectrum#5223]
### Provide a general summary of the issue here

If we fill the minutes field in timepicker and then clear everything using backspace, and then try to fill the date again, the first digit is replaced with the second digit.

### 🤔 Expected Behavior?

The fields should get updated properly based on the key pressed after clearing.

### 😯 Current Behavior

After clearing, the first digit of the time picker is replaced by the second digit.

### 🖥️ Steps to Reproduce

Goto https://codesandbox.io/s/small-water-y5dgj4?file=/src/TimeField.js
Fill hours and minutes in TimeField
Clear everything in the minutes section using backspace
Refill the minutes section, eg 23
The field will display 3 instead of 23

### Version

3.0.0

### What browsers are you seeing the problem on?

Chrome, Other

### If other, please specify.

Brave

### What operating system are you using?

Mac OS Ventura

**Comment by devongovett** [comment]
Interesting. Seems to work if you first focus the hour field and then re-fill the minutes, but not if you backspace and immediately fill out the minutes. 🤔

**Comment by akzhy** [comment]
Seems to be an issue with updating  `enteredKeys.current` in `backspace` function of `packages/@react-aria/datepicker/src/useDateSegment.ts`. 

Adding this statement after line 97 seems to be fixing the issue

```typescript
newValue = newValue === '0' ? '' : newValue;
```

<img width="802" alt="image" src="https://github.com/adobe/react-spectrum/assets/20243910/a8552f70-a576-4048-a3c3-9db5f65d17a9">

@devongovett

**Comment by reidbarber** [comment]
Maybe related to https://github.com/adobe/react-spectrum/issues/5261

**Comment by akzhy** [comment]
Hi, any updates on this @reidbarber @devongovett?

**Comment by snowystinger** [comment]
I'm actually still seeing this one reproduce in the storybook on main in the React Spectrum component and the RAC component
