### ISSUE TITLE
[RAC] Select: support `menuTrigger`

### ISSUE THREAD

**Issue by emlai** [adobe/react-spectrum#5236]
### Provide a general summary of the feature here

ComboBox supports the [`menuTrigger` prop](https://react-spectrum.adobe.com/react-aria/ComboBox.html#menu-trigger-behavior), but Select doesn't.

### 🤔 Expected Behavior?

Both Select and ComboBox support `menuTrigger`.

### 😯 Current Behavior

Select doesn't support `menuTrigger`, only ComboBox does.

### 🔦 Context

We use `menuTrigger="focus"` for ComboBox to enable "open menu on focus" behavior.

We'd like our Select and ComboBox to behave consistently.

**Comment by snowystinger** [comment]
Combobox doesn't have controlled open. However, Select does, and you can use that to implement this. We don't want to introduce this to Select at this point in time.
