### ISSUE TITLE
[react-aria-components] Row component's `children` render function gets called with unexpected argument

### ISSUE THREAD

**Issue by chungwu** [adobe/react-spectrum#5241]
### Provide a general summary of the issue here

When using `Row` with a render-prop `children`, we expect `children` to be called with a column as the argument. Instead, it is sometimes called with row state (?)

### 🤔 Expected Behavior?

`children` render function passed to `Row` is only called with a column

### 😯 Current Behavior

It is sometimes called with row state

### 🖥️ Steps to Reproduce

Reproducing sandbox: https://codesandbox.io/s/bitter-morning-86l9vh?file=/src/App.tsx

You can see in the console what arguments are called on `Row`'s `children` function.

### Version

react-aria 1.0.0-beta.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Ubuntu

### 🧢 Your Company/Team

Plasmic

**Comment by reidbarber** [comment]
Can you double check that the codesandbox saved? I'm still seeing any empty template. Thanks!

**Comment by chungwu** [comment]
oops! should be saved now 😅

**Comment by devongovett** [comment]
Yeah looks like we should omit `children` from this call: https://github.com/adobe/react-spectrum/blob/d334cde64e35cfeb1482dd396ab58652bef01022/packages/react-aria-components/src/Table.tsx#L1043-L1058

The type of `props` should be `RowProps<T>` not `RowProps<unknown>` and then TS will catch this.
