### ISSUE TITLE
RAC: Calendar keyboard navigation triggers multiple focused cells

### ISSUE THREAD

**Issue by binaryartifex** [adobe/react-spectrum#5246]
### Provide a general summary of the issue here

after navigating through several months on just the RAC calendar, the focus-visible style starts applying to multiple cells, sometimes up to three cells at once.

### 🤔 Expected Behavior?

The calendar should maintain focus on only a single cell in the context of the calendar

### 😯 Current Behavior

its hit and miss and hard to predict, but when navigating between months, the focus-visible style will begin applying itself to multiple cells, i imagine this also will have an effect on screen readers as well. 

### 🖥️ Steps to Reproduce

This can easily be tested from the docs [here](https://react-spectrum.adobe.com/react-aria/Calendar.html#reusable-wrappers). just go to the first calendar example at the reusable wrappers section, and with the keyboard focus any cell. then start navigating between months and eventually multiple cells will start having focus instead of just the target one.

### Version

docs version

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 11

**Comment by reidbarber** [comment]
Looks like a duplicate of https://github.com/adobe/react-spectrum/issues/3975, related to https://github.com/adobe/react-spectrum/issues/2015. You may be able to work around this by using the focused and focus-visible states together, as mentioned in https://github.com/adobe/react-spectrum/issues/3975#issuecomment-1601728224

**Comment by binaryartifex** [comment]
@reidbarber cheers mate, yep, can confirm that was it. setting both focus and focus-visible fixes it for now. closing.
