### ISSUE TITLE
[Docs] Accordion

### ISSUE THREAD

**Issue by SaadBazaz** [adobe/react-spectrum#5253]
### 🙋 Documentation Request

Hey,
I see that [@react-spectrum has Accordion](https://www.npmjs.com/package/@react-spectrum/accordion) but the production docs haven't been filled yet.

(I can assist in this if needed)

### 🧢 Your Company/Team

Omni (third-party)

**Comment by yihuiliao** [comment]
Although we appreciate the help, because accordion and its hooks are still early in development, we do not want to document them until they become a bit more stable. You are welcome to report any issues or improvements if you do use it though.
