### ISSUE TITLE
Support for `data-focus-within` in RAC

### ISSUE THREAD

**Issue by jaknas** [adobe/react-spectrum#5258]
### Provide a general summary of the feature here

Originally opened in the discussion: https://github.com/adobe/react-spectrum/discussions/4849#discussion-5463826

For all grid components that support interactive children, I'd like to have possibility to style the `<Item/>` component based on whether the focus is contained in the descendant of this `<Item/>`. 

For example:
My solution requires to style a `<Row/>` component when it's being interacted with. Currently, this can be done with using `data-hovered` or `data-focus-visible` selectors. However, when my focus moves to one of the interactive children, there's no attribute on the `<Row/>` component I could use, that I could use to apply the same styles as e.g `data-hovered` (that'd signify that this row is being interacted with)

### 🤔 Expected Behavior?

Additional prop/data-attribute that would be enabled once the focus is on the element's descendants. Best candidate seems to be using focus-within selector, but I'm open to hear about drawbacks of this or some other ideas.			

### 😯 Current Behavior

No way of knowing that focus is contained in the element's descendants.

### 💁 Possible Solution

Possibly adding the `useFocusWithin` hook to the [TableRow](https://github.com/adobe/react-spectrum/blob/7120dd375ca6e1db4315a2940ad15c62791e9489/packages/react-aria-components/src/Table.tsx#L996) component.

### 🔦 Context

I'd like to style a grid `role="row"` element based on whether any of the descendants is currently focused.

**Comment by LFDanLu** [comment]
Just to add to @reidbarber comment, we'd also want to add `focus-within` tracking to Cell as well

**Comment by sookmax** [comment]
Hello guys, do we want to add a separate `data-focus-within` and leave the existing `data-focused` intact, or is it okay to just enhance `data-focused` to remain activated even when the focus shifts to one of its children?

I might be missing some details here, but if the latter is okay then I think this can be solved as simple as changing `useFocusRing()` in `TableRow` to `useFocusRing({ within: true })`, and in the case of `GridList`, it seems this is already handled by `useGridListItem()` and `useSelectableItem()` within it:
https://github.com/adobe/react-spectrum/blob/d2049a5831e57fcad7a2d489fa0eacbe155a6db9/packages/%40react-aria/gridlist/src/useGridListItem.ts#L62-L71

If what we want is the former.. then a little more guidance would be of great help 🙏
