### ISSUE TITLE
Memory leak in useId

### ISSUE THREAD

**Issue by velialiev** [adobe/react-spectrum#5260]
### Provide a general summary of the issue here

useId uses global variable `idsUpdaterMap` for storing id updaters and cleans it only in useLayoutEffect that doesn't run in a server environment thus leading to memory leak in SSR.

Probably cleanup doesn't work on client either because memory leak is reproducing on client (see "steps to reproduce")

https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/useId.ts#L30-L34C3

```ts
let idsUpdaterMap: Map<string, (v: string) => void> = new Map();
```

```ts
let updateValue = useCallback((val) => {
  nextId.current = val;
}, []);

idsUpdaterMap.set(res, updateValue);

useLayoutEffect(() => {
  let r = res;
  return () => {
    idsUpdaterMap.delete(r);
  };
}, [res]);
```

### 🤔 Expected Behavior?

1. useId should not use global object and should cleanup memory on the server side too
2. Cleanup should work on client

### 😯 Current Behavior

1. useId uses global object and doesn't cleanup memory on the server side
2. Cleanup doesn't work on client

### 🔦 Context

This issue leads to memory overflow in a server environment

### 🖥️ Steps to Reproduce

At first I thought the problem is reproducing only on server but tests show that the same problem is appearing on client. Despite the problem much more dangerous on server I will show how to reproduce it on client since it easier to do.

The simplest client example provided here: https://stackblitz.com/edit/stackblitz-starters-127s5h?description=React%20%20%20TypeScript%20starter%20project&file=src/leak.tsx,src/App.tsx&title=React%20Starter

1. Take a memory snapshot of the application
2. Press "Add items" button several times
3. Press "Remove items" button (in this step we are unmounting all components that use useId. `idsUpdaterMap` should be cleaned up at this step)
4. 4.0. Optionally force garbage collection to make sure there really is a leak
4.1. Take a memory snapshot and check the objects allocated between `Snapshot 1 (step 1)` and `Snapshot 2 (step 4.1)`. 

There will be alot of small objects allocated in closure by useId. If you will log one of them you will ensure that it is exactly that id updater callback we've set in the idsUpdaterMap in useId

![telegram-cloud-photo-size-2-5294424534335738265-y](https://github.com/adobe/react-spectrum/assets/55160134/eedd6228-1b50-4176-a45e-70c20bdba7d0)
![telegram-cloud-photo-size-2-5294424534335738268-y](https://github.com/adobe/react-spectrum/assets/55160134/f07d5926-487d-4f8a-8f7b-e605d7626501)

### Version

3.29.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by snowystinger** [comment]
I am not sure this is us, at least on the client. I ran jest with the same steps and exposed our map via export to the test. After adding elements and removing them, the map is empty. Can you try running this with just react's `useId`?

**Comment by velialiev** [comment]
> I am not sure this is us, at least on the client. I ran jest with the same steps and exposed our map via export to the test. After adding elements and removing them, the map is empty. Can you try running this with just react's `useId`?

I tried this with react's useId and of course there is no any such callback in memory snapshots in this case. In snapshot we can see that this callback created at useId.ts:30. After logging this callback I see the exact signature of this updateValue callback. Maybe somehow these callbacks still available from another part of code and thats why GC can't delete them? Or maybe forcing garbage collection doesn't work as I expect.

Anyway we can say confidently that there is a leak in the server environment just by seeing at this code. It uses global variable that is never cleared. We can focus specifically on the server side.
