### ISSUE TITLE
Dropzone with FileTrigger doesn't work in Safari

### ISSUE THREAD

**Issue by jezikk** [adobe/react-spectrum#5262]
### Provide a general summary of the issue here

If I drop any file into [DropZone](https://react-spectrum.adobe.com/react-aria/DropZone.html) using Safari browser, It simply do nothing.

```
import {FileTrigger, Button} from 'react-aria-components';

function Example() {
  let [file, setFile] = React.useState(null);

  return(
    <DropZone>
      <FileTrigger
        onSelect={(e) => {
          let files = Array.from(e);
          let urls = files.map((file) => file.name);
          setFile(urls);
        }}>
        <Button>Select a file</Button>
      </FileTrigger>
      {file && file}
    </DropZone>
  );
}
```

### 🤔 Expected Behavior?

DropZone works as expected in combination with FileTrigger. File name is presented under FileTrigger.

### 😯 Current Behavior

File name of dropped file is not presented in GUI.

### 🖥️ Steps to Reproduce

1. Open [this](https://react-spectrum.adobe.com/react-aria/DropZone.html) page in Safari browser.
2. Go to the following example:
```
import {FileTrigger, Button} from 'react-aria-components';

function Example() {
  let [file, setFile] = React.useState(null);

  return(
    <DropZone>
      <FileTrigger
        onSelect={(e) => {
          let files = Array.from(e);
          let urls = files.map((file) => file.name);
          setFile(urls);
        }}>
        <Button>Select a file</Button>
      </FileTrigger>
      {file && file}
    </DropZone>
  );
}
```
3. Drop any file into the Dropzone.

### Version

"react-aria-components": "^1.0.0-beta.1"

### What browsers are you seeing the problem on?

Safari

### What operating system are you using?

macos

**Comment by yihuiliao** [comment]
Hi thanks for reporting this! Seems like we forgot to add `onDrop` to the example which is why the file name is not appearing when you drop a file.
