### ISSUE TITLE
useComboBox throws an error when custom popover is used

### ISSUE THREAD

**Issue by orest22** [adobe/react-spectrum#5274]
### Provide a general summary of the issue here

I am trying to use `useCombobox` with custom Popover and it throws an error when running this [ariaHideOutside](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/combobox/src/useComboBox.ts#L316). The Popover ref becomes available later, so it make sense to validate if all refs are available. 

When enabling strict mode in TS it definitely hints that ariaHideOutside wants all elements to be available
<img width="859" alt="Screenshot 2023-10-19 at 11 29 25 AM" src="https://github.com/adobe/react-spectrum/assets/1497502/638cbcc2-9745-4cb4-995e-8b0a62c03d97">

### 🤔 Expected Behavior?

useCombobox don't throw an error and runs `ariaHideOutside` once refs become available.

### 😯 Current Behavior

It throws an error:

![Screenshot 2023-10-19 at 12 53 07 PM](https://github.com/adobe/react-spectrum/assets/1497502/ae355c90-78ad-4199-92b1-1064ccad102e)

### 💁 Possible Solution

Validate if refs together with the state.open.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/aria-mui-popover-forked-cyh3xq?file=/src/MuiAutocomplete.tsx

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac OS

**Comment by snowystinger** [comment]
Possibly fixed in https://github.com/adobe/react-spectrum/pull/6761 will check after merge

**Comment by snowystinger** [comment]
fix verified https://codesandbox.io/p/sandbox/aria-mui-popover-forked-sq7mlz?file=%2Fpackage.json
