### ISSUE TITLE
SassError: expected selector.

### ISSUE THREAD

**Issue by johibkhan2** [adobe/react-spectrum#5283]
### Provide a general summary of the issue here

I am getting below error when i removed node_module and installed it back

ERROR in ./node_modules/@react-spectrum/combobox/dist/main.css
 (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!
 ./node_modules/sass-loader/dist/cjs.js??ref--8-3!.
 /node_modules/@react-spectrum/combobox/dist/main.css)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

i am using following versions in my project "https://github.com/DX26-io/data-studio-react/tree/master"
  "@adobe/react-spectrum": "3.22.0",
    "sass": "1.26.5",
    "sass-loader": "8.0.2",
    "css-loader": "3.5.3",
    "style-loader": "1.2.0",
     "webpack": "4.43.0",
    "webpack-cli": "3.3.11",
    "webpack-dev-server": "3.11.3",

i have upgraded and downgraded the spectrum libarary. still getting the same eror. 

### 🤔 Expected Behavior?

npm start should work

### 😯 Current Behavior

i get below error while running npm start

ERROR in ./node_modules/@react-spectrum/combobox/dist/main.css
 (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!
 ./node_modules/sass-loader/dist/cjs.js??ref--8-3!.
 /node_modules/@react-spectrum/combobox/dist/main.css)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

### 💁 Possible Solution

fix the main.css in all component 

### 🖥️ Steps to Reproduce

chekout code base https://github.com/DX26-io/data-studio-react/tree/master
run npm install and npm start
node >=12.16.1

### Version

3.22.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

ubantu 18

**Comment by snowystinger** [comment]
Hey, thanks for the issue. Could you try excluding node_modules from your sass loader and only running the css-loader over node_modules?

**Comment by johibkhan2** [comment]
you can reproduce following steps
chekout code base https://github.com/DX26-io/data-studio-react/tree/master
run npm install and npm run
node >=12.16.1

**Comment by johibkhan2** [comment]
excluding node_modules from sass loader worked..Thanks

**Comment by snowystinger** [comment]
Glad you got it working, closing out
