### ISSUE TITLE
Lack of `data-hovered`  on Table column headers

### ISSUE THREAD

**Issue by jaknas** [adobe/react-spectrum#5284]
### Provide a general summary of the feature here

Hi, I'm not sure whether this is a bug or feature request, but I'm not seeing `data-hovered` added to column headers, especially if they're sortable, which would point to the user about possible interactivity possibility.

Not sure if related to https://github.com/adobe/react-spectrum/issues/4411

### 🤔 Expected Behavior?

Ability to style Table Column headers using RAC patterns, with `data-hovered` selector.

### 😯 Current Behavior

Need to reach for `:hover` selector

### 🔦 Context

I have a use-case where I'm using sortable column headers. To make it more clear to the user about interactivity behind it, I'd like to apply additional styles once the column header is hovered.

### 💻 Examples

Any RAC table example – by looking at devtools we can see that `data-hovered` is not added.

**Comment by snowystinger** [comment]
Possibly related, it doesn't have the data-hovered for sortable columns either, which are interactive.
