### ISSUE TITLE
I having some trouble to import Selection on my React component

### ISSUE THREAD

**Issue by guhesse** [adobe/react-spectrum#5289]
### Provide a general summary of the issue here

My React component crashing because the Selection function not importing corrrectly in my HeaderButton() component. 

Console keep giving me this issue, when no give this issue keep me saying something like "selecion is not defined"

I already try to install the typescript library to fix this, but without sucess unfortunely. 

I already tried to remove the "type" before the import, but no sucess.

Ps: I'm a beginner on Js and React languages. 

**This is the issue for now:**

import type { Selection } from '@react-types/shared';
                   ^
**This is my code:**

```
import React from "react";
import { Provider, darkTheme } from '@adobe/react-spectrum';
import type { Selection } from '@react-types/shared';

export function HeaderButton() {
    let [selected, setSelected] = useState < Selection > (new Set(['middle']));

    return (
        <>
            <Provider theme={darkTheme}>
                <MenuTrigger>
                    <ActionButton>
                        Align
                    </ActionButton>
                    <Menu
                        selectionMode="single"
                        selectedKeys={selected}
                        onSelectionChange={setSelected}
                    >
                        <Item key="left">Left</Item>
                        <Item key="middle">Middle</Item>
                        <Item key="right">Right</Item>
                    </Menu>
                </MenuTrigger>
                <p>Current selection (controlled): {[...selected]}</p>
            </Provider>
        </>
    );
}
```

### 🤔 Expected Behavior?

 To render properly the React Component.

### 😯 Current Behavior

Not importing

### 💁 Possible Solution

I realy dont know, i tried everything. 

### 🖥️ Steps to Reproduce

This is my link from codesandbox:
https://codesandbox.io/s/muddy-frost-ss3tmn?file=/src/App.js

### Version

^3.31.1

### What browsers are you seeing the problem on?

Other

### If other, please specify.

Adobe Photoshop

### What operating system are you using?

Windows

**Comment by snowystinger** [comment]
Looks like you aren't working in a typescript file `.js -> .tsx`
Here you go https://codesandbox.io/s/reverent-pateu-gtkrjg?file=/src/App.tsx
There were also a couple syntax errors, so I've corrected those as well.

Let us know if that solves it for you

**Comment by snowystinger** [comment]
I'm going to close this as solved. We can reopen if it's still needed.
