### ISSUE TITLE
[react-aria-components] - Table ColumnResizer does not accept children

### ISSUE THREAD

**Issue by jkirkpatrick24** [adobe/react-spectrum#5304]
### Provide a general summary of the issue here

Hey there, thanks for the amazing library! 

Based on the [documentation](https://react-spectrum.adobe.com/react-aria/Table.html#columnresizer) (and types), it looks as though the ColumnResizer should accept `children` or a render prop to add custom elements to the column resizer. I had a look at the [implementation](https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/Table.tsx#L907) and it seems as though this isn't actually possible yet. 

Just wondering if the docs need updating, or if this is a feature the component should actually support. 

Thanks again!

### 🤔 Expected Behavior?

ColumnResizer should accept and render `children`

### 😯 Current Behavior

Passing children to ColumnResizer doesn't show any warnings, but the child is not actually rendered

### 🖥️ Steps to Reproduce

Heres a sandbox showing children, and render props both failing to render a child div inside the ColumnResizer

https://codesandbox.io/s/bold-zeh-8xx9z3

### Version

1.0.0-beta.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by LFDanLu** [comment]
Discussed with the team, looks to be something we missed when implementing the resizer. Thanks @reidbarber for the quick fix!
