### ISSUE TITLE
aria-* attributes applied to `<Tab>`s getting filtered out

### ISSUE THREAD

**Issue by jessicamarcus** [adobe/react-spectrum#5312]
### Provide a general summary of the issue here

My team is using react-aria-components to build an internal component library, which will include an icon-only tabbed interface. Despite following the [props documentation](https://react-spectrum.adobe.com/react-aria/Tabs.html#tab), adding `aria-label`s to each `Tab` component seems to have no effect, rendering a group of tabs without accessible labels.

<img width="1665" alt="Screen Shot 2023-10-26 at 13 56 32" src="https://github.com/adobe/react-spectrum/assets/5561280/c4139430-d408-47e4-bcc7-6903cb021ad5">

### 🤔 Expected Behavior?

A `Tab` component with a value passed to the `aria-label` prop should render a DOM element with `role="tab"` and the aria-label attribute applied.

### 😯 Current Behavior

The aria-label provided to `Tab` is getting dropped somewhere along the way to the rendered element. I also tested this out locally using Spectrum Tabs/TabList/Item components, but had the same result...

A bit of digging led me to the `useTabs` hook and the `filterDOMProps` function, which seems to filter it unless the `labelable` option is included.

### 💁 Possible Solution

On line 61 of packages/@react-aria/tabs/src/useTab.ts, add the `labelable` option: 

```typescript
  let domProps = filterDOMProps(item?.props, {isLink: !!item?.props?.href, labelable: true});
```

### 🔦 Context

Although we _could_ add text wrapped in the `VisuallyHidden` component to get around this issue, it’s so much cleaner + more explicit to use aria-label to, well, provide accessible labels 🙃 

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/purple-brook-djgdyx?file=/src/App.tsx

The first `Tabs` group is copied from the react-aria-components documentation as-is and is present for comparison. The second is the modified version with `Tab` text replaced by icons, and aria-labels added. The screenshot attached in the summary is of this codesandbox w/ firefox devtools visible.

### Version

react-aria-components 1.0.0-beta.2

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

MacOS

**Comment by LFDanLu** [comment]
That suggested fix seems sound to me, probably something we overlooked in initial implementation.
