### ISSUE TITLE
[Toast] Screen readers read title twice

### ISSUE THREAD

**Issue by plushdohn** [adobe/react-spectrum#5329]
### Provide a general summary of the issue here

`useAriaToast` returns `toastProps` that have the same linked element in `aria-labelledby` and `aria-describedby`, making screen readers read the title twice, instead of title first, then description.

### 🤔 Expected Behavior?

`aria-labelledby` should link the `title` element, while `aria-describedby` should link to the description element

### 😯 Current Behavior

Both `aria-labelledby` and `aria-describedby` use the `title` ID

### 💁 Possible Solution

I'm not familiar with the codebase but I think `useSlotId` is generating the same ID as `useId` in the title. I would be happy to help with a PR for this!

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/stoic-mccarthy-v3spgh?file=/src/App.js:0-1353

### Version

3.0.0-beta.6

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

OSX

**Comment by LFDanLu** [comment]
I'm not sure I'm seeing the same issue, it sounds like you were getting the same id as `aria-labelledby` and `aria-describedby`?
<img width="443" alt="image" src="https://github.com/adobe/react-spectrum/assets/9661127/4ece709e-6403-4483-a0fd-d2b1d5553276">

**Comment by plushdohn** [comment]
> I'm not sure I'm seeing the same issue, it sounds like you were getting the same id as `aria-labelledby` and `aria-describedby`?

Yes, and I'm actually not able to reproduce it again 😵‍💫 I was certain I saw that behaviour in my CodeSandbox, so I don't know it might've been my browser. Closing until I find a way to repro, sorry for taking your time!
