### ISSUE TITLE
tailwindcss-react-aria-components focus-within doesnt get applied

### ISSUE THREAD

**Issue by constantin-badan** [adobe/react-spectrum#5333]
### Provide a general summary of the issue here

using focus-within with the [tailwindcss-react-aria-components](https://react-spectrum.adobe.com/react-aria/styling.html#plugin) plugin doesnt seem to work

### 🤔 Expected Behavior?

the element with focus-within class should apply styles

### 😯 Current Behavior

the element with focus-within class is not getting those styles

### 💁 Possible Solution

-

### 🖥️ Steps to Reproduce

https://stackblitz.com/edit/stackblitz-starters-mwhy2r?file=tailwind.config.ts

### Version

1.0.0-beta.2

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

mac

**Comment by reidbarber** [comment]
This is just happening because `TextField` doesn't have a `data-focus-within` state. You can wrap your `TextField` in a `Group` to achieve this though: https://stackblitz.com/edit/stackblitz-starters-ddurzt?file=app%2Fpage.tsx

**Comment by constantin-badan** [comment]
> This is just happening because `TextField` doesn't have a `data-focus-within` state. You can wrap your `TextField` in a `Group` to achieve this though: https://stackblitz.com/edit/stackblitz-starters-ddurzt?file=app%2Fpage.tsx

This works, thank you.

Some questions I still have:
1. Why is `TextField` missing that state? 
2. If I have a form with multiple inputs, should I wrap each one in a group? that seems wrong, but otherwise it will trigger the focus-within for all of them.

**Comment by reidbarber** [comment]
1. Mostly because focus is actually on the `Input`. However, I think it would be reasonable to have `focus-within` here. I know we wanted to avoid putting hover states on everything to avoid excessive re-renders everywhere, but I don't think this would be as bad.
2. To get this focus-within state for now, you would need to.
