### ISSUE TITLE
[RAC Examples - Gesture Driven Modal Sheet] undefined CSS variable '--page-background'

### ISSUE THREAD

**Issue by sookmax** [adobe/react-spectrum#5342]
### Provide a general summary of the issue here

Hello, the code snippet in [Gesture Driven Modal Sheet](https://github.com/adobe/react-spectrum/issues/new?assignees=&labels=&projects=&template=Bug_Report.yml) contains a CSS class that references an undefined CSS variable '--page-background' (`bg-[--page-background]`) so the class doesn't set the modal's background color properly when the code is copied and pasted.

It looks like `--page-background`, in turn, makes a reference to `--spectrum-global-color-gray-50` in the docs, both of which I don't get by just installing `react-aria-components` package.

### Screenshot
<img width="1922" alt="Screenshot 2023-11-01 at 10 39 21 PM" src="https://github.com/adobe/react-spectrum/assets/71210554/053a820a-ea3a-4e21-9881-f402a98b873e">

### 🤔 Expected Behavior?

the class `bg-[--page-background]` should be removed, or changed to something like `bg-white`.

### 😯 Current Behavior

the class `bg-[--page-background]` references an undefined CSS variable `--page-background`.

### 🖥️ Steps to Reproduce

Visit [here](https://codesandbox.io/p/sandbox/clever-dubinsky-y5tctj?file=%2Fsrc%2FApp.tsx%3A40%2C34&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clofsm671000a3b6ihi5yxhiu%2522%252C%2522sizes%2522%253A%255B61.69211973121564%252C38.30788026878436%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clofsm67100033b6i71zdy3ms%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clofsm67100073b6i8jzzu1tm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clofsm67100093b6isiijmrrz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clofsm67100033b6i71zdy3ms%2522%253A%257B%2522id%2522%253A%2522clofsm67100033b6i71zdy3ms%2522%252C%2522activeTabId%2522%253A%2522cloftevtk01gv3b6i8tznkueo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clofsm67100023b6ih8ukf8r2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftailwind.config.js%2522%252C%2522id%2522%253A%2522clofsnqrm00c23b6i7tmzfs0e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522id%2522%253A%2522clofsq10900ll3b6ibjnro36d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.css%2522%252C%2522id%2522%253A%2522clofssn6c013t3b6if4o8gh50%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522id%2522%253A%2522clofsu48401b93b6ikpq8s7b9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522cloftevtk01gv3b6i8tznkueo%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clofsm67100093b6isiijmrrz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clofsm67100083b6i6ppfm6hb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clofsm67100093b6isiijmrrz%2522%252C%2522activeTabId%2522%253A%2522clofsm67100083b6i6ppfm6hb%2522%257D%252C%2522clofsm67100073b6i8jzzu1tm%2522%253A%257B%2522id%2522%253A%2522clofsm67100073b6i8jzzu1tm%2522%252C%2522activeTabId%2522%253A%2522clofsm67100043b6i4m0sy99e%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clofsm67100043b6i4m0sy99e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clofsm67100053b6ipcz4fhu1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clofsm67100063b6i8rxgbwwc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522preview%2522%257D%252C%257B%2522id%2522%253A%2522clofsn08d009e3b6ibarksr3w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clofsn0fy004iecipbecgft8a%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Version

^1.0.0-beta.2

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS Sonoma 14.0

**Comment by snowystinger** [comment]
Thanks for the issue. We'd like to move all those variables out to a separate file and make it easier to get them into codesandbox

**Comment by devongovett** [comment]
That's just so it integrates into our doc site. Not sure how we could get rid of that one. You'll need to change it in the code to match whatever you're placing it into.
