### ISSUE TITLE
useCombobox: add shouldKeepInputValueOnBlur option

### ISSUE THREAD

**Issue by ashleyryan** [adobe/react-spectrum#5352]
### Provide a general summary of the feature here

by default, when the combobox input loses focus, the popover closes and the input loses its value. onInputChanged will fire with an empty string.

There's a `shouldCloseOnBlur` option for useComboboxState that will keep the text when set to false, but it also keeps the popover open when blurred, which I don't want.

Could we add another option, to keep the text, but still close the popover?

### 🤔 Expected Behavior?

I want to be able to keep the input text when the comobobox loses focus, but have the popover close

### 😯 Current Behavior

You can only keep the text by keeping the popover open with shouldCloseOnBlur: false

### 🔦 Context

I can see why it behaves the way it does, but I've got a bug report from a user wondering why their text disappears

**Comment by LFDanLu** [comment]
Would setting `allowsCustomValue: true` work for you? If your combobox doesn't truly accept any arbitrary value a user inputs then it feels more correct to have the input field be cleared, otherwise the user may expect their value to be included on form submission even though it wasn't a valid value.

**Comment by ashleyryan** [comment]
I think most of our consumers are using it as a controlled component and getting the value from `onSelectionChange` so custom text isn't a concern for them and `allowsCustomValue: true` will work for them. Thanks!
