### ISSUE TITLE
[RAC] Fix virtualization of `ListBox` component

### ISSUE THREAD

**Issue by clemensheithecker** [adobe/react-spectrum#5356]
### Provide a general summary of the issue here

The `ComboBox` component from React Aria Components, when populated with a large number of items (exceeding 1,000), exhibits a significant delay upon opening the `ListBox`. This behavior suggests a lack of efficient virtualization, despite the `useListBox` hook indicating support for "Virtualized scrolling for performance with long lists" as a feature ([see useListBox documentation](https://react-spectrum.adobe.com/react-aria/useListBox.html)). However, this feature does not seem to further be documented.

### 🤔 Expected Behavior?

The `ListBox` should open promptly and handle a large set of items efficiently, leveraging the virtualized scrolling support that is expected from the `useListBox` hook. This should ensure a smooth and responsive user interface.

### 😯 Current Behavior

The `ListBox` component opens slowly when dealing with a large dataset, which is not in line with the expected virtualized behavior. This issue is replicable in the provided CodeSandBox example and is reminiscent of a similar issue previously reported here: https://github.com/adobe/react-spectrum/issues/998.

### 💁 Possible Solution

Clarification and documentation on the virtualization feature of the `useListBox` hook could provide insight into the correct implementation. If the feature is not working as intended, a fix to properly enable virtualized scrolling within the `ListBox` component would be necessary.

### 🔦 Context

We highly value the `ComboBox` component from React Aria Components as it plays a detrimental role in our app. However, the delay in interaction has unfortunately already led to user dissatisfaction.

To address this, we've temporarily implemented a custom solution by integrating React Aria's `useComboBox` hook with TanStack Virtual for list virtualization. While this approach has been a suitable interim fix, we believe that utilizing the `ComboBox` directly from React Aria Components would be the ideal scenario, both for maintaining consistency with the library's ecosystem and for leveraging its comprehensive features.

### 🖥️ Steps to Reproduce

[Link to minimal reproducible example on CodeSandBox](https://codesandbox.io/s/naughty-napier-8s5899?file=/src/App.tsx)

### Version

1.0.0-beta.2

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by reidbarber** [comment]
Related discussions: #4393, #5056, #4575
