### ISSUE TITLE
Select on click event does not stop event propagation

### ISSUE THREAD

**Issue by alexkneis** [adobe/react-spectrum#5376]
### Provide a general summary of the issue here

Creating a select component using the `useSelectState()` hook even together with an `Overlay` from `@react-aria/overlays` does not prevent the event propagation.

Example on current docs page where the event is also being triggered on the `#` link.
https://github.com/adobe/react-spectrum/assets/29652953/83404621-766e-488d-9423-6d9e183aa2be

Tested on ios/mac on chrome and firefox

### 🤔 Expected Behavior?

The click event on an list-item using the `useSelectState` should stop the event propagation.

### 😯 Current Behavior

Clicking an element inside the list of options also triggers the click event on whatever is behind the list.

### 🖥️ Steps to Reproduce

1. Go to [useSelect](https://react-spectrum.adobe.com/react-aria/useSelect.html#popover) in the react-aria docs
2. Open a version of the page
3. Scroll up to the select example above and click the option just in front of the `#` link next to "Popover"
4. See the content jumping to the corresponding id

### Version

3.29.1

### What browsers are you seeing the problem on?

Chrome, Safari

### What operating system are you using?

ios/mac

**Comment by reidbarber** [comment]
Potentially a duplicate of https://github.com/adobe/react-spectrum/issues/1513

**Comment by alexkneis** [comment]
It is indeed 👍
