### ISSUE TITLE
[React-Aria-Components] Suggestion regarding the `Selection` type

### ISSUE THREAD

**Issue by fl-y** [adobe/react-spectrum#5420]
### Provide your feedback here.

Hi, just want to say amazing package that I've started using for a new app and loving the experience.
Took a while to figure out how to use the `ListBox` component and any component where you can't add a `onClick` handler to the children or the parent, but once I figured out there was a separate `Selection` type, things started to make much more sense.

One little nit I have while working with the components profusely is that the `Selection` type includes the 'all' string.
Due to keeping as little context in my components as possible,  this makes code like the example in the `Code Sample` section necessary.

I feel removing the `all` type entirely makes more sense in an implementation perspective - but also understand how legacy types can make this notoriously difficult, so understandable if this is left on purpose

thanks 🙏

### 🔦 Context

Context is trying to use any react-aria-component that uses the `Selection` type

### 💻 Code Sample

```typescript
const ClaimButton = ({ selected }: { selected: Selection }) => {
	const indexes = selected === 'all' ? ['0', '1', '2'] : Array.from(selected)
        // logic
}
```

### Version

"react-aria-components": "1.0.0-rc.0". I don't use spectrum

### If other, please specify

Irrelevant to browser

### What operating system are you using?

Irrelevant

**Comment by snowystinger** [comment]
Thanks for the issue! We have 'all' in order to account for the async case where all the keys may not have been loaded yet. I'm going to close this for now as we do not intend to remove it. Please let us know if you have more questions about it.

**Comment by devongovett** [comment]
There's also more information in the docs about it https://react-spectrum.adobe.com/react-stately/selection.html#select-all

**Comment by fl-y** [comment]
That makes sense 👍 - appreciate the explanation @devongovett & @snowystinger
