### ISSUE TITLE
React spectrum not building/running in a react app.

### ISSUE THREAD

**Issue by nagidev** [adobe/react-spectrum#5421]
### Provide a general summary of the issue here

Creating a fresh react app using `npx create-react-app my-app` and installing `@adobe/react-spectrum` works. However, importing any react-spectrum components results in an error when running/building the application.

```
Failed to compile.

Module not found: Error: Can't resolve '@adobe/react-spectrum' in '/path/to/project/src'
ERROR in ./src/App.js 4:0-71
Module not found: Error: Can't resolve '@adobe/react-spectrum' in '/path/to/project/src'

webpack compiled with 1 error
```

My code is the same as the one in the documentation:

```javascript
import { Button, defaultTheme, Provider } from '@adobe/react-spectrum';

function App() {
  return (
    <Provider theme={defaultTheme}>
      <Button
        variant="accent"
        onPress={() => alert('Hey there!')}
      >
        Hello React Spectrum!
      </Button>
    </Provider>
  );
}

export default App;
```

### 🤔 Expected Behavior?

Normally, the project builds and runs on the browsers.

### 😯 Current Behavior

On running `npm start` or `npm build`, I get this error:
```
Failed to compile.

Module not found: Error: Can't resolve '@adobe/react-spectrum' in '/Users/labuser/Documents/temp/adobe-spectrum-test/src'
ERROR in ./src/App.js 4:0-71
Module not found: Error: Can't resolve '@adobe/react-spectrum' in '/Users/labuser/Documents/temp/adobe-spectrum-test/src'

webpack compiled with 1 error
```

### 🖥️ Steps to Reproduce

1. Create a react project using `npx create-react-app my-app`
2. Run `cd my-app` to go to the project folder
3. Run `npm install @adobe/react-spectrum` to install react-spectrum
4. In your App.js file replace everything with the following code:
```javascript
import { Button, defaultTheme, Provider } from '@adobe/react-spectrum';

function App() {
  return (
    <Provider theme={defaultTheme}>
      <Button
        variant="accent"
        onPress={() => alert('Hey there!')}
      >
        Hello React Spectrum!
      </Button>
    </Provider>
  );
}

export default App;
```
5. Run the application using `npm start`

### Version

3.32.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by LFDanLu** [comment]
Reproduced, thanks for letting us know! We'll be fixing this asap.

**Comment by LFDanLu** [comment]
[3.32.2](https://www.npmjs.com/package/@adobe/react-spectrum/v/3.32.2) is out now, let us know if you run into any issues. Thanks @devongovett for the speedy turnaround!

**Comment by nagidev** [comment]
Thank you so much! It works perfectly now.
