### ISSUE TITLE
[tailwindcss-react-aria-components] invalid native variant not working

### ISSUE THREAD

**Issue by Ecksters** [adobe/react-spectrum#5423]
### Provide a general summary of the issue here

With `tailwindcss-react-aria-components` installed, I would expect [native variants](https://github.com/adobe/react-spectrum/blob/6b59634fc7e574cb2c6b989cd688a25bbe04f7bf/packages/tailwindcss-react-aria-components/src/index.js#L53) to work as long as the data-rac is present on the component, even without the prefix.

However, when I try to apply something like `invalid:border-error`, it doesn't take effect, although `[&[data-invalid=true]]:border-error` works without issue.

### 🤔 Expected Behavior?

Should be able to use `invalid` as a boolean modifier.

### 😯 Current Behavior

`invalid` doesn't apply styles as expected.

### 🖥️ Steps to Reproduce

CodePen:
https://codesandbox.io/s/tailwind-css-and-react-forked-lvdpvd?file=/src/components/Homepage.js:200-375

```
<TextField isInvalid>
        <Input
          className="bg-black text-white invalid:bg-red-500"
        />
      </TextField>
```

### Version

1.0.0-rc.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac OS X

### 🧢 Your Company/Team

External

**Comment by snowystinger** [comment]
Thanks for the issue! This is a great question and topic. We actually tried to do this for a little while. However, it became difficult to determine which things were native and which required our `data-*` property. In addition, if any of the native properties change, either in meaning or name, that would result in breaking changes for anyone using our library. As a result, we decided to be very explicit and uniform with our API for this and use only the `data-*` attributes.

See PR https://github.com/adobe/react-spectrum/pull/4891

Let us know if you have further questions

**Comment by Ecksters** [comment]
I'm fairly certain I have it set up correctly, as the `placeholder-shown` shorthand is working, but `invalid` does not.

**Comment by snowystinger** [comment]
Our test would suggest that this should be working https://github.com/adobe/react-spectrum/blob/3688f079ce064b8187242a4a92cec66dea455dc1/packages/tailwindcss-react-aria-components/src/index.test.js#L205

but I do not see it in the sandbox you shared

**Comment by reidbarber** [comment]
It looks like in the linked codesandbox, the tailwind config isn't being used, so it may just be an issue with configuration. Here is an example with invalid working: https://codesandbox.io/p/sandbox/winter-worker-dwpqvf?file=%2Fsrc%2FApp.js%3A26%2C11

**Comment by Ecksters** [comment]
I think you're correct, I'll try to better recreate the bug we're seeing on our environment on Monday, it appears I didn't get a working Tailwind configuration in the sandbox I made.

**Comment by reidbarber** [comment]
@Ecksters Thanks for the update!
