### ISSUE TITLE
Avatar support in Listbox

### ISSUE THREAD

**Issue by astghikk-adobe** [adobe/react-spectrum#5428]
### Provide a general summary of the issue here

The potential use case of using Listbox is the user selector. To not implement a custom Listbox everywhere, is it possible to support Avatars in addition to icons in Item?

<img width="536" alt="Screenshot 2023-11-16 at 13 30 52" src="https://github.com/adobe/react-spectrum/assets/151055193/7808c036-89ce-4d3b-855f-4445a65a01ca">

### 🤔 Expected Behavior?

Add Avatar support in Listbox. Use the icon slot. 

<img width="429" alt="Screenshot 2023-11-16 at 20 09 16" src="https://github.com/adobe/react-spectrum/assets/151055193/22d9f49d-1af4-4c78-a574-6a8c6e821fa1">

### 😯 Current Behavior

Without custom implementation, there is no good way to create a user list box. However, the current support of the icon slot is very similar to the user picker's avatar position.

### 💁 Possible Solution

Apply icon slot to Avatar component.

### 🖥️ Steps to Reproduce

[CodeSandBox](https://codesandbox.io/s/spectrum-mxsmcv?file=/src/Example.js)

### Version

3.31.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac

### 🧢 Your Company/Team

Adobe/DX

**Comment by reidbarber** [comment]
Seems like a reasonable request. We can use slots to set the placement, and use the correct size.
