### ISSUE TITLE
Wrapping a spectrum icon with rsp3 Icon spams console with warnings

### ISSUE THREAD

**Issue by snow893** [adobe/react-spectrum#5433]
### Provide a general summary of the issue here

If you import an icon from spectrum-icons and wrap it with Icon, it spams the console with warnings.
```
      <Icon>
        <ChevronRight />
      </Icon>
```
I'm aware that the spectrum-icons is already wrapped with an Icon internally, but if this is intended to be unsupported, I'd expect it to not render at all (or just allow Icon to be nested without warning spam).

### 🤔 Expected Behavior?

Less console spam :)

### 😯 Current Behavior

The className prop is unsafe and is unsupported in React Spectrum v3. Please use style props with Spectrum variables, or UNSAFE_className if you absolutely must do something custom. Note that this may break in future versions due to DOM structure changes.
The style prop is unsafe and is unsupported in React Spectrum v3. Please use style props with Spectrum variables, or UNSAFE_style if you absolutely must do something custom. Note that this may break in future versions due to DOM structure changes. 
...ad infinitum

### 💁 Possible Solution

Either make it so the icon doesn't render at all if it's an icon within an icon, or allow it without the warnings.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/practical-lichterman-449396?file=/src/App.js

### Version

3.32

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

OSX

**Comment by reidbarber** [comment]
The [Icon](https://react-spectrum.adobe.com/react-spectrum/custom-icons.html) wrapper is only meant to wrap `svg` elements so this combination isn't supported. Maybe we can enforce this via typescript, but we haven't been in the business of checking child types at runtime too much.

In the future, we may look into showing some warnings only at dev-time, so there is an argument for including these types of checks there: https://github.com/adobe/react-spectrum/issues/2944

**Comment by davidcoleman007** [comment]
as a consumer of the spectrum icon i don't know that it is internally wrapped with an Icon of it's own self, and as a container, that can consume any client icon i don't know that this wrapper exists. I should be able to place any child that ultimately boils down to an svg as a child of an icon.

**Comment by snow893** [comment]
@reidbarber Yeah, I'm aware that the combination isn't supported... but not everyone knows the implementation detail of the spectrum icons. A lot of people are used to writing combination of rs3 icon + svg. When we import SomeIcon, we expect it to be an svg to be wrapped in Icon. Having an unsupported combination that works but spews warnings is just annoying. And if you have cases where you have an icon prop, then have <Button><Icon>{props.icon}</Icon></Button>, how do we guarantee that all developers are aware that they must _not_ use spectrum icons because we use a wrapper? It adds a lot of overhead mental load for every developer using rs3, since they'll need to check every single icon to ensure it's wrapped correctly.

The warnings also give no indication of where it's actually coming from. The way I found it was looking in storybook for where got those warnings, then comment out random elements until the warnings stopped showing up. Eventually realized that we had wrapped a spectrum icon in an Icon. It's a frustrating experience.

If an Icon receives a className prop that matches what it'd be passing down anyway... it shouldn't throw warnings. Icons should be able to be nested, similar to how Provider can be.

I don't think typescript is really the right option unfortunately - as in above example, user could accept icon prop, and there's no guarantee that typescript would be able to guarantee the type, especially if the user lists it as type "any".

**Comment by snowystinger** [comment]
I think I'd prefer to push for this package to be made public and for teams at Adobe to use it. https://github.com/adobe/react-spectrum/tree/main/packages/%40spectrum-icons/build-tools#generating-icon-packages It would automatically wrap icons. This would prevent most of the need to use Icon for custom icons directly.

I do not know the current state of that package, it's been a long time since I worked on it, but we use it to do this with all of our workflow icons. This was also always the intent behind this package. In the meantime you could just copy it, it hasn't changed in a long time and it'd be good to know what is missing before publishing it.

In addition, I think we could pretty easily add a single context inside the Icon component (don't need to export it). Then we'd know if we had an Icon as the child of an Icon and be able to tailor the warning to that.
