### ISSUE TITLE
[RAC] Add `elementType: 'label' | 'div'` property to `Radio`, `Switch`, and `Checkbox`

### ISSUE THREAD

**Issue by GreenTea124** [adobe/react-spectrum#5448]
### Provide a general summary of the feature here

Currently Switch and a few other components are always rendered as HTML `<label/>` tag. I would like to be able to render it as `<div/>` tag without relying on lower level hooks API.

### 🤔 Expected Behavior?

This should render a `<label/>` HTML markup:
```tsx
<Checkbox />
<Radio />
<Switch />
<Checkbox elementType="label" />
<Radio elementType="label" />
<Switch elementType="label" />
```

This should render a `<div/>` HTML markup:
```tsx
<Checkbox elementType="div" />
<Radio elementType="div" />
<Switch elementType="div" />
```

### 😯 Current Behavior

Only this is valid:
```tsx
<Checkbox />
<Radio />
<Switch />
```

### 💁 Possible Solution

 Adding an `elementType: 'label' | 'div'` property (inspired by one used in `Separator`) could solve that. 

### 🔦 Context

I would like to use my components like this:
```tsx
<label>
   <Radio />
   <span>Some label</span>
</label>
```

Currently it wouldn't produce valid HTML since `label` would be in a `label`.

**Comment by devongovett** [comment]
It would also break the behavior of the component to not be wrapped in a label at the moment. The label is what makes clicking on the actual checkbox toggle the selection since it forwards the click to the underlying hidden native input. If we got rid of the label we'd have to manually handle clicks to toggle it.

**Comment by GreenTea124** [comment]
> It would also break the behavior of the component to not be wrapped in a label at the moment. The label is what makes clicking on the actual checkbox toggle the selection since it forwards the click to the underlying hidden native input. If we got rid of the label we'd have to manually handle clicks to toggle it.

It's a pretty straight forward fix, that's how I handle it. But I'd rather use official RAC to benefit from future API updates.

```tsx
"use client";

import React, { useRef } from "react";
import {
  useFocusRing,
  useCheckbox,
  VisuallyHidden,
  AriaCheckboxProps,
} from "react-aria";
import { useToggleState } from "react-stately";
import mergeRefs from "merge-refs";
import { cn } from "@/lib/utils";
import styles from "./Checkbox.module.scss";

function isInsideLabelNode(inputNode: HTMLElement) {
  let parentNode = inputNode.parentNode;

  while (parentNode !== null) {
    if (parentNode.nodeName === "LABEL") {
      return true;
    } else {
      parentNode = parentNode.parentNode;
    }
  }

  return false;
}

type CheckboxProps = Omit<AriaCheckboxProps, "children" | "validationState"> &
  Pick<React.HTMLAttributes<HTMLDivElement>, "className"> & {};

export const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>(
  (props, ref) => {
    const inputRef = useRef<HTMLInputElement>(null);

    // Uses hooks instead of `react-aria-components` to render root as `div` instead of as `label`.
    const toggleState = useToggleState(props);
    const checkboxData = useCheckbox(props, toggleState, inputRef);
    const focusRingData = useFocusRing(props);

    const isIndeterminate = props.isIndeterminate;
    const isSelected = checkboxData.isSelected && !isIndeterminate;

    return (
      <div
        className={cn(styles.root, props.className)}
        data-selected={isSelected || undefined}
        data-indeterminate={isIndeterminate || undefined}
        data-disabled={checkboxData.isDisabled || undefined}
        data-readonly={checkboxData.isReadOnly || undefined}
        data-focus-visible={focusRingData.isFocusVisible || undefined}
        onClick={() => {
          if (
            inputRef.current &&
            // Prevents duplicated toggle events when switch is in a label
            !isInsideLabelNode(inputRef.current)
          ) {
            inputRef.current.click();
          }
        }}
      >
        <VisuallyHidden>
          <input
            ref={mergeRefs(ref, inputRef)}
            {...checkboxData.inputProps}
            {...focusRingData.focusProps}
          />
        </VisuallyHidden>
        <span className={styles.check} />
      </div>
    );
  }
);
```

**Comment by GreenTea124** [comment]
> It would also break the behavior of the component to not be wrapped in a label at the moment. The label is what makes clicking on the actual checkbox toggle the selection since it forwards the click to the underlying hidden native input. If we got rid of the label we'd have to manually handle clicks to toggle it.

I'm migrating from Radix (which for example implements checkbox as a `button`), and it would be more aligned with my existing codebase and wrapper components. That being said, using `<input type="radio"/>` inside a label is somerhing that is defined by web standards, so I was used to it even before I've used Radix.

**Comment by snowystinger** [comment]
Closing for now as we don't plan to change this. Can reopen if a new use case comes up.
Thanks for the issue!
