### ISSUE TITLE
`onSelectionChange` on `<Tab>` component is triggered by nested tabs

### ISSUE THREAD

**Issue by adauleuklaxoon** [adobe/react-spectrum#5469]
### Provide a general summary of the issue here

When there is a nested `<Tab>` component inside another `<Tab>` component, the selection change event is triggered by any of the nested tabs. This can cause an infinite render loop when the tab is controlled and the nested tab is the default one that is selected because onSelectionChange is triggered alternatively by the parent and the child `<Tab>` component (see logs in Sandbox below)

### 🤔 Expected Behavior?

In my opinion, the event `onSelectionChange` on the parent should be triggered only if the selection of a parent tab changes

### 😯 Current Behavior

The event `onSelectionChange` on the parent is triggered also by the nested tabs components

### 🖥️ Steps to Reproduce

https://stackblitz.com/edit/stackblitz-starters-pu2gbh?devToolsHeight=33&file=src%2FApp.tsx

### Version

react-aria-components 1.0.0-rc.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Linux

**Comment by snowystinger** [comment]
Thanks for the issue!
I think our Collection implementation is rendering a little too far. We should probably make use of useShallowRender or something along those lines for the TabPanel so that the nested collection isn't rendered as part of the initial one.

https://github.com/search?q=repo%3Aadobe%2Freact-spectrum%20useShallowRender&type=code

I tried this out, and unfortunately it caused an issue with the order of react hooks being called, so it may require a bit more work.

**Comment by shivamtracxn** [comment]
+1 , started migrating to react aria at work & hit the first roadblock

**Comment by adauleuklaxoon** [comment]
Thanks @shivamtracxn for sharing a workaround. I found another one which is to ignore keys corresponding to nested tabs in `onSelectionChange` event. In pseudo code, it would be something like this:
```
if(key is from parentTab){
    doSomething()
} else {
    // ignore
}
```

**Comment by shivamtracxn** [comment]
@adauleuklaxoon Nice, For me there could be same keys in the nested tabs so couldn't use this
There is another sol. that i wont use but it is to set just the `onSelectionChange` as undefined in the Tabs slot, so it is not passed down

**Comment by P233** [comment]
I found that the `className` is also shared between the parent and nested `<Tabs />` components. 

v1.0.0

**Comment by snowystinger** [comment]
This appears to be fixed in the latest release. https://stackblitz.com/edit/stackblitz-starters-7wjeh5?devToolsHeight=33&file=package.json,src%2FApp.tsx
