### ISSUE TITLE
<ListBoxItem> in hovered state when interacting with keyboard

### ISSUE THREAD

**Issue by andrew-pledge-io** [adobe/react-spectrum#5488]
### Provide a general summary of the issue here

When using the keyboard to select a `<ListBoxItem>` inside of a `<ListBox>`, the `<ListBoxItem>` state is considered to be "hovered", despite selection not being made using a pointer.

The hover state should only apply when using a mouse. This is how other components behave (e.g. `<Button>`).

### 🤔 Expected Behavior?

When selecting a `<ListBoxItem>` with the keyboard the state should be 

```ts
{
  isHovered: false,
  isFocusVisible: true,
}
```

### 😯 Current Behavior

When selecting a `<ListBoxItem>` with the keyboard the state is 

```ts
{
  isHovered: true,
  isFocusVisible: true,
}
```

### 🔦 Context

I'm building a custom `<Select>` element and styling the `<ListBoxItem>` using the `isHovered` and `isFocusVisible` states.

When both are applied when using the keyboard, the styles look incorrect to the user.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/gifted-jennings-yd33xq

In the example a red border is applied to elements with `data-focus-visible=true` and a grey background is applied to elements with `data-hovered=true`.

The example includes a `<Select>` component with `<ListBoxItem>`s and a `<Button>` for comparison.

When selecting `<ListBoxItem>`s inside the `<Select>` using a keyboard, both the red border and grey background are applied.

When selecting the `<Button>` with the keyboard, only the red border is applied.

Using the mouse behaves as expected, focus visible styles are not applied.

### Version

react-aria-components@1.0.0-rc.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

MacOS

**Comment by reidbarber** [comment]
Looks like this is happening due to this section:

https://github.com/adobe/react-spectrum/blob/5e4dfb0c403a3698e6e3da6eae89c7e65ed0b520/packages/react-aria-components/src/ListBox.tsx#L370-L377
