### ISSUE TITLE
Combobox: setting inputValue in onSelectionChange when controlled

### ISSUE THREAD

**Issue by ashleyryan** [adobe/react-spectrum#5490]
### Provide a general summary of the issue here

I'm not sure if this is a bug, or if there's a better way to do it. I have a controlled combobox used for selecting an address. Because of the nature of the form, I want to display the full address in the combobox dropdown, but only the street address when an option is selected (and populate other input fields with city, state, etc). However, if I attempt to set the inputValue to the street address in onSelectionChange, it doesn't work and displays the full address. I have to do a setTimeout with 0ms and a second setState to get the text to display

### 🤔 Expected Behavior?

setting inputValue in onSelectionChange should override the value in the input

### 😯 Current Behavior

the input will display the text of the selected option

### 🔦 Context

There's an example here, though the behavior is slight different in my own implementation of combobox (for some reason)

note: you'll notice I don't store or control the selectedKey - I don't particularly care what the key is, I just use it to populate other text inputs. I found the same behavior (at least in my own implementation) when controlling the selectedKey as well.

Related issue: https://github.com/adobe/react-spectrum/issues/5352

https://codesandbox.io/p/sandbox/nervous-dust-g3xsk3?file=%2Fsrc%2FApp.tsx%3A72%2C17

https://vista.design/swan/preview/?language=jsx-preview&code=H4sIAAAAAAACA7VUXW%2FaMBR976%2B44oVEysLa7mFrCRKLxDQJtmmg7aHiwSSXYtXEyHHoKpT%2FPtv5cAKhXVWNB5Tccz9Ojo%2Bv40IwgsMFQMSTVALfSaoeIIA7FQOD6N8DPt1A77Lnle8kjgWm6aUOXl3DjNAE5rKGIyp1%2Fjh5kvwxqcOpJBJvoD8b96vQOmNsXDRr94Ky2IPZuGeSc6%2BD0tWrKXG5QQGLLl7h4p942Q4ehItnyF13kfsE82jDOesg95mnkr9CrkYrKGpfUOtDF6GP8I0LuYHxHo8JzUkCE0GSiKYRP5XrHK9GR2i1UHpV9NT%2F8lb91da7o8kuk78Iy9CDFOXX%2BnWp7PgTSST9LMW5Hu70%2B%2B6trdRsTU2oHl7MNvRNukE78lW2vRHJHBlG%2BlqEG5LcYzM9JIytSPTgKHmri1QUcoY%2B4%2FdOnydqUtkAoqJD39Pn4ZpkugZd7dYnVZ1A4z6qkeXF9Nc0iZ0qOirDvhkfBLZr3Yauy2w7ACqlSsTX8hmBarSQoYSNXm18QbfIM%2Bk4Zn20DquqqgzmevC%2BLs7rs889uFu6TZlNi2ck3uvup%2BNM2C26Ndy0pkyiwPh7vdDqjjPccscQMfRLalZgXehwiyjMb%2Fhb6yFk%2BpvKjWMt60s%2B5RFhOOWPKEKSKhe51e0oHxoOX%2BqI%2BXyBMhMJFISGSvgkJiKecLGt5g%2F1y4Qiiy0jE5uSFbJRSWs4sKF2mhHri%2BDZzgIKCvl2xVf8TyMGp24PDiehvFUR05SsGI4zySdGuhZKBCXvmCYV9EqiMKUJwmXvaG7j%2BIODOlTj7mZUn7Tbnm31DA72%2BShH4jYNDkd%2BaOcoi%2FHHNMzUBt2aFg101MqsVTPEYMdIhBvOYhRBTz7tENS2K53fg8GZ2h98x%2Fco2mgDn9JUHoNqk2tLlj45U1h8nN4C6tj0UshHh5Z38%2BGgnXs65khi1X1wnpfFOr7Jgg1DDrodWcRbJn%2FB9nqBvdrzC%2FxT7A7YF67Rqy8fDQc18D%2Bomm36dq5mD7%2BdbLFoBsebxr3I%2FwIs1li%2FDQoAAA%3D%3D&renderMultipleComponents=false

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/nervous-dust-g3xsk3?file=%2Fsrc%2FApp.tsx%3A72%2C17

Note that the text in the input when you select an option is the full text, instead of just address1, which is being set in onSelectionChange.

There's commented out code below it that will (kind of) make it work

### Version

react-aria/combobox 3.6.3

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

OSX Venture

**Comment by LFDanLu** [comment]
One way to can accomplish this is by tracking/providing a `selectedKey` as well to make your ComboBox completely controlled: https://codesandbox.io/p/sandbox/pedantic-scott-clkcx4?file=%2Fsrc%2FApp.tsx%3A96%2C5. This will bypass the [logic we have that is overwriting the value you set in onSelectionChange](https://github.com/adobe/react-spectrum/blob/5e4dfb0c403a3698e6e3da6eae89c7e65ed0b520/packages/%40react-stately/combobox/src/useComboBoxState.ts#L223-L230) (aka we assume that a user who is only controlling `inputValue` will want their input text to match their selected item text on selection). Alternatively, you could pass a `textValue` to your `Item` that matches the shorter string but I think that will affect the screenreader announcements on selection.

**Comment by ashleyryan** [comment]
Oops, I had a comment in my original post that said I wasn't controlling selectedKey because in my combobox implementation, it didn't seem to matter or change the behavior. So now I have to figure out why that worked in yours, but not mine. Thanks for link, will dig in more.

https://vista.design/swan/preview/?language=jsx-preview&code=H4sIAAAAAAACA51V30%2FbMBB%2B719x4qUJypIBe9hQ06mrxIRWtmlF2wPqg5tcaYQbV45TQJD%2FfbaTOnYbBl1fGt%2FP7%2B6%2Bsz0f4iE89QASlhcC2Fpk8gNiuJEy0Br1u8PHc%2Bif9IPmTNKUY1GcKOHpGVyRLIepMOokE8p%2BlD8Kdp8bcSGIQCm%2FGhnRoqR0VAdzY0HjHICxroIOTKcHY2JiiRyuu4CNr98ErI0QgHHpRHfWhe4TTJMlY7QD3RdWCHZAw6xQUPu%2B1q8PXYg%2BwnfGxRJGG9xFNCU5XHCSJ1mRsP2GvQTMighOCNkxB9%2BsZ8h3s8iQplMVOoACxYU5ziQhfyFJRFgWqCVeXVWBFBOB6TdVWy4R1JGzfF2K34SWCmOTralHnyq%2FzcryqQ4ieT9ekvwW7VxjQumcJHeebN52U2pHRjGk7Nbrs7xBIQNAUkfoB6rbfo1lAcrbN3Oo026RXwpcyYzN4oWLLE%2B9%2BqDy1V%2Bhzh7HbVBw%2B%2BNtY%2B90RNqHgk0Fz%2FJbzw%2BMkd0fG0i45URrWrfNMVKirYHsZHTcQrrOVshK4Xl%2B2619tGuOG%2F2ljCzsAGEYGmVgyQ8AXPnbFlUBvN9%2BH0c15XpafDNzCHCpov9j%2BBuV%2BOXxa3DW6LW533tr3V012%2FXqcGbx7PE2uCQx%2Bn34rPkP52CChZZxs3G6N7sNWGRUIMf0h7n8TQuucMU87aon2oBoyaocPdZqpE6RNZT3AxfFn0wsvXapw7YqycoJSwjFCbtHPiYFer7hZ%2FNx0%2Bk5U0oNnqMoeQ41vIG0y1PC0wvGV1s0A3XQ%2FW%2FxadmEzJEOm9tqELUi10zz4itn5XpocXEwZqs5m7MHS%2BYMJn6ykFtyeH6GMk9R7jimleO9dwnFT3si1yPNCjKnOCoFu9BjcLSEZ%2BQdVSXFR02ZMJFp4eRoJ6%2FF%2FfhJEkrfOrZUsd93c7fTcEptxTvmclELZenQzLWRq8bui3Epn7CVDmFph46lab%2FGCGtKElwymiKPj8TjGkG%2BNs2tcATRC74%2F2ZptkLtaSz%2FJCrGrlC8p04u7J7cc6%2BLUxSsnqFahGsp%2F622sBpFru59mp9syevQyrlbXUVOrtJgddVO7ljvb8sr%2BjOU7cPDyXOODqCe32SOQeliq4SAyNv%2BBehDt3gR%2Br%2FoLkhldnucKAAA%3D&renderMultipleComponents=false

**Comment by LFDanLu** [comment]
Sounds good, I'll close this for now but definitely feel free to followup if you run into something new or can't get it to behave the same way as the sandbox.
