### ISSUE TITLE
 Received NaN for the `max` attribute. If this is expected, cast the value to a string.

### ISSUE THREAD

**Issue by clearly-outsane** [adobe/react-spectrum#5499]
### Provide a general summary of the issue here

``` 
Warning: Received NaN for the `max` attribute. If this is expected, cast the value to a string.
web-starter:dev:     at input
web-starter:dev:     at div
web-starter:dev:     at $1910c06f0ca9905e$var$ColumnResizer (webpack-internal:///(ssr)/../../node_modules/.pnpm/react-aria-components@1.0.0-rc.0_react-dom@18.2.0_react@18.2.0/node_modules/react-aria-components/dist/import.mjs:5813:73)
```

I get this error when I use `<ColumnResizer />` in Nextjs 14 in a server component.

### 🤔 Expected Behavior?

No warnings 

### 😯 Current Behavior

I get the above warning on every render and it's annoying ^

### 🖥️ Steps to Reproduce

Just use `<ColumnResizer />` in a Table from react-aria-components in a React server component ( define your Table in a React Client component and import it in another RSC ) 

### Version

"react-aria-components": "1.0.0-rc.0"

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows

**Comment by snowystinger** [comment]
Thanks, looks like we missed a check here https://github.com/adobe/react-spectrum/blob/5e487532e3ca4714513fb6ab64f7a78d9d1ca281/packages/%40react-stately/table/src/TableColumnLayout.ts#L72 and for max as well
It should be `?? 0` for both probably, it'll get resolved to real values after the first render

**Comment by clearly-outsane** [comment]
Thank you! Hope you merge it soon :)
