### ISSUE TITLE
Allow null value in react-aria-component NumberField

### ISSUE THREAD

**Issue by slowselfip** [adobe/react-spectrum#5524]
### 📝 Feedback
When using the NumberField with controlled state, (setting default value and value) it would be nice to have an option to support a non `undefined` default value that still results in an empty field. If I use `null` the field will have `0`. The only supported value / defaultValue type currently is number.

### 🔦 Context
We are using the useController-hook from react-hook-form which accepts a defaultValue but do not support `undefined`.

The reason that `undefined` is not an option in this case is that this would cause the field to change from being uncontrolled to controlled when a value is entered into the field.

### 💻 Code Sample
```tsx
const {
  field,
  fieldState: { invalid, error },
} = useController({
  name,
  defaultValue: null,
});

return (
  <NumberField
    validationBehavior="aria"
    isInvalid={invalid}
    {...field}
  >
    <Label>{label}</Label>
    <Input />
    <FieldError>
      {error?.message}
    </FieldError>
  </NumberField>
);
``` 

### Version

"react-aria-components": "^1.0.0-rc.0"

**Comment by snowystinger** [comment]
You should be able to use `NaN` which is type number.

**Comment by slowselfip** [comment]
Thanks @snowystinger, that worked. Did not think of using `NaN`, and this is probably the first time I've ever had an actual use for it, except for maybe trying to avoid it.

**Comment by jj-ivx** [comment]
I think using `NaN` to reset back to the empty state is confusing. I would expect to be able to use `null`.
At the very least this should be added to the documentation.

**Comment by psirenny** [comment]
> I think using `NaN` to reset back to the empty state is confusing.

@jj-ivx agreed. Created #6971 to see if we could alter the behavior.

**Comment by nathan-harrower-cayuse** [comment]
Thank you for making this post @jj-ivx - I was hitting this issue as well but reading this and using Number.NaN solved it for me: 

`value={field.value ? field.value : Number.NaN}`

**Comment by snowystinger** [comment]
> value={field.value ? field.value : Number.NaN}

this will be wrong for the value `0`, better to do `value={field.value != null ? field.value : Number.NaN}`
