### ISSUE TITLE
Breadcrumbs tail element cannot be selected

### ISSUE THREAD

**Issue by ryo-manba** [adobe/react-spectrum#5549]
### Provide a general summary of the issue here

In the current implementation, as seen in the example at [useBreadcrumbs](https://react-spectrum.adobe.com/react-aria/useBreadcrumbs.html#example), the tail element of breadcrumbs becomes unselectable. This occurs due to `user-select: none;` being applied when the element is clicked.

### 🤔 Expected Behavior?

Users should be able to select and copy the text of the breadcrumb's tail element.

### 😯 Current Behavior

Currently, when attempting to select the tail element of the breadcrumbs in the react-aria-components library, as demonstrated in the [example](https://react-spectrum.adobe.com/react-aria/useBreadcrumbs.html#example), the text cannot be selected. This is due to the application of `user-select: none`.

### 💁 Possible Solution

The issue seems to stem from the use of useLink in useBreadcrumbItem, as seen in the [GitHub code here](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/breadcrumbs/src/useBreadcrumbItem.ts#L36). Specifically, `disableTextSelection(state.target);` is executed in usePress's onPointerDown handler ([source code](https://github.com/adobe/react-spectrum/blob/bdd37cd188bad79baf4911cd97fa582a7af343b0/packages/%40react-aria/interactions/src/usePress.ts#L407-L409)). A potential solution could involve adjusting this behavior to allow text selection for the tail breadcrumb element.

### 🔦 Context

This unselectability may inconvenience users who wish to copy the text from the tail element of the breadcrumb.

### 🖥️ Steps to Reproduce

Go to the [Breadcrumbs example page](https://react-spectrum.adobe.com/react-aria/useBreadcrumbs.html#example).
Try selecting the text of the last breadcrumb item.
Notice that the text cannot be selected due to `user-select: none` being applied.

### Version

react-aria@3.30.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by LFDanLu** [comment]
@sookmax that seems like the right fix, would you like to submit a PR for it? Happy to open one if you'd like also.

**Comment by sookmax** [comment]
@LFDanLu thanks for confirmation. I'll go ahead and open a PR.
