### ISSUE TITLE
NumberField: formatOptions are "visually" applied on mount on the default value, unlike the other props (like min, max, step, etc)

### ISSUE THREAD

**Issue by cedeber** [adobe/react-spectrum#5556]
### Provide a general summary of the issue here

When you set some `formatOptions` like
```js
{
  minimumFractionDigits: 1,
  maximumFractionDigits: 2,
}
```
and also set `defaultValue` to `0.00001` then you see `0.0` as value on the text field.
Although no `onChange` is triggered, it may be confusing to see a different value that the one entered.

On the other hand, if you have `defaultValue` set to `10` and `minValue` set to `15`, then you see `10`. The value is not corrected on this case. The most confusing is maybe by using `step` which also controls the fraction digits in some ways.

---

In order to validate the `defaultValue` you can do in the NumberField component
```js
  useEffect(() => {
    state.commit();
  }, []);
```
and then for the last example, the value will be set to `15` and `onChange` will be triggered.

But, in the case of you use only `formatOptions`, calling `commit()` will never trigger the `onChange` event.

### 🤔 Expected Behavior?

Hard to tell what's the best practice here, I would probably keep the wrong `defaultValue` in all cases and let the dev call `commit` in a `useEffect` in the NumberField if really wanted. Which is, maybe, probably things we will all do by default?

But it should always trigger an `onChange`, even with only `formatOptions`?

### 😯 Current Behavior

See above

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/number-field-j6lk5k

### Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

Windows

**Comment by snowystinger** [comment]
I think I've addressed this in this PR https://github.com/adobe/react-spectrum/pull/5543
