### ISSUE TITLE
React Aria Components: expose `disableFocusManagement` prop on `ModalOverlay`

### ISSUE THREAD

**Issue by danphilibin** [adobe/react-spectrum#5582]
### Provide a general summary of the feature here

In my app I have a few elements that use nested portals, like a custom ComboBox inside a Dialog. I effectively need to be able to focus an element in a second portal while the Dialog portal is open.

I've been using the `disableFocusManagement` prop on `<Overlay>` to prevent focus-trapping, otherwise the input in the second portal can't be focused. 

I'm looking to switch to React Aria Components but the `<ModalOverlay>` component that wraps `<Overlay>` doesn't expose that `disableFocusManagement` prop. Could we add that prop to `ModalOverlay` and pass it along to `<Overlay>`?

### 🤔 Expected Behavior?

I'd like to be able to disable focus management when using `ModalOverlay` from React Aria Components.

### 😯 Current Behavior

Explained in description

### 💁 Possible Solution

I'd like to be able to pass the `disableFocusManagement` prop to `Overlay` here: https://github.com/adobe/react-spectrum/blob/a8fc9ee3ff46a1f8edb96846c0777502a4ac7cfa/packages/react-aria-components/src/Modal.tsx#L169

### 🔦 Context

In my app I have nested elements that use portals, like a custom ComboBox inside a Dialog, and I use the `disableFocusManagement` prop on `<Overlay>` to prevent focus-trapping. 

(my "custom ComboBox" has a text input inside the dropdown, but since the focus is trapped inside the `Dialog` the input can't be focused.)

**Comment by snowystinger** [comment]
A combobox inside a dialog should be supported.
Here's an example, please ignore my messy styles.
https://codesandbox.io/p/sandbox/cool-phoebe-h66s6q?file=%2Fsrc%2Fstyles.css%3A240%2C16

Or are you saying your combobox isn't built from RAC or our hooks?

**Comment by danphilibin** [comment]
My version of ComboBox is built from your hooks, but I've moved the text input inside the dropdown. So I have an element outside of the dialog that needs to allow focus while the dialog is open, and the focus trapping is preventing that.

Here's an illustration:

![CleanShot 2023-12-14 at 19 34 17@2x](https://github.com/adobe/react-spectrum/assets/180350/2d9fb7f7-59b2-4041-a0cf-1d70b2e93497)

**Comment by snowystinger** [comment]
Ok, so closer to this setup
https://codesandbox.io/p/sandbox/eager-scooby-rzdm3d?file=%2Fsrc%2Fstyles.css%3A390%2C32
where focus does move into the second portal, which we still support without needing to use `disableFocusManagement`

do you have a focus scope that contains in both the dialog and the popover?

**Comment by danphilibin** [comment]
Yeah that's right. Our ComboBox does not implement RAC yet, Dialog is the first thing we've tried porting over. Our ComboBox implements `OverlayContainer`, `usePopover`, and `useComboBox`.

If moving focus into the second portal without `disableFocusManagement` is officially supported I'll do that, perhaps using RAC for both components is the missing link. Apologies for not being able to share an example, it's tough to separate out the relevant parts but knowing multiple portals are officially supported is helpful. 

> do you have a focus scope that contains in both the dialog and the popover?

I have one inside the dialog that wraps the form, including the element that opens the second dialog, but removing that doesn't fix it.

**Comment by snowystinger** [comment]
Yeah, I get that it's hard with the hooks to create examples. That's where RAC components have come from. If you can, I do recommend switching to them. Otherwise, you could probably narrow down the differences between your implementation and the RAC implementation to see what might be going wrong, though I realize that's a fair amount of code.

**Comment by danphilibin** [comment]
I replaced our own popover implementation with RAC's `Popover` in `ComboBox` and that fixed the focus issues for the most part. There are a few more issues to work out but I see a path to solving this. I appreciate the help, thank you!
