### ISSUE TITLE
TimeField: Warning: Prop `autoCapitalize` did not match. Server: "none" Client: "off"

### ISSUE THREAD

**Issue by liamb13** [adobe/react-spectrum#5599]
### Provide a general summary of the issue here

In NextJS, TimeField is having an issue with autoCapitalize.

This then leads to Error: Text content does not match server-rendered HTML.

### 🤔 Expected Behavior?

autoCapitalize isn't even a prop for TimeField so unsure how this is occuring?

### 😯 Current Behavior

```
Warning: Prop `autoCapitalize` did not match. Server: "none" Client: "off"
div
$cfa347761f172638$var$EditableSegment@webpack-internal:///(app-pages-browser)/./node_modules/@react-spectrum/datepicker/dist/import.mjs:195:46
$cfa347761f172638$export$6388987c5223b54e@webpack-internal:///(app-pages-browser)/./node_modules/@react-spectrum/datepicker/dist/import.mjs:170:61
div
$d2bb88c82604b25f$export$34dc4cfa15ead1@webpack-internal:///(app-pages-browser)/./node_modules/@react-spectrum/datepicker/dist/import.mjs:216:118
div
div
div
$79348162c55d687f$var$Input@webpack-internal:///(app-pages-browser)/./node_modules/@react-spectrum/datepicker/dist/import.mjs:324:66
div
div
$b7ca5b4454a2009d$var$Field@webpack-internal:///(app-pages-browser)/./node_modules/@react-spectrum/label/dist/import.mjs:460:88
$beaeefa091999363$var$DatePicker@webpack-internal:///(app-pages-browser)/./node_modules/@react-spectrum/datepicker/dist/import.mjs:849:89
div
ProviderWrapper@webpack-internal:///(app-pages-browser)/./node_modules/@react-spectrum/provider/dist/import.mjs:211:49
$f57aed4a881a3485$export$178405afcd8c5eb@webpack-internal:///(app-pages-browser)/./node_modules/@react-aria/overlays/dist/import.mjs:893:34
$1051245f87c5981d$export$8214320346cf5104@webpack-internal:///(app-pages-browser)/./node_modules/@react-spectrum/utils/dist/import.mjs:211:74
$18f2051aff69b9bf$export$a54013f0d02a8f82@webpack-internal:///(app-pages-browser)/./node_modules/@react-aria/i18n/dist/real-module.mjs:164:50
$7167f8da3cce35e4$var$Provider@webpack-internal:///(app-pages-browser)/./node_modules/@react-spectrum/provider/dist/import.mjs:147:23
Date
```

### 🖥️ Steps to Reproduce

```
"use client"

import { Provider, defaultTheme, TimeField } from "@adobe/react-spectrum"

export default function Page() {
  return (
    <Provider theme={defaultTheme} locale="en">
      <TimeField label="Date" />
    </Provider>
  )
}
```

[codesandbox link](https://codesandbox.io/p/devbox/react-spectrum-timefield-f3sygq?file=%2Fapp%2Fpage.tsx&embed=1&showConsole=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqcgz4i100072e67oan9nqzb%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqcgz4i100022e67n4cxhhv2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqcgz4i100042e67jhxpzwar%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqcgz4i100062e67nxjmm8ec%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqcgz4i100022e67n4cxhhv2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqcgz4i100012e67bhjzpnb3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqchb2ft00022e679k13ntrh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A20%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqcgz4i100022e67n4cxhhv2%2522%252C%2522activeTabId%2522%253A%2522clqchb2ft00022e679k13ntrh%2522%257D%252C%2522clqcgz4i100062e67nxjmm8ec%2522%253A%257B%2522id%2522%253A%2522clqcgz4i100062e67nxjmm8ec%2522%252C%2522activeTabId%2522%253A%2522clqchaanl00jp2e67a32jhkse%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clqchaanl00jp2e67a32jhkse%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clqcgz4i100042e67jhxpzwar%2522%253A%257B%2522id%2522%253A%2522clqcgz4i100042e67jhxpzwar%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqch2ma900eu2e67fnhq47eo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqch2mvm00a7effm8idk6r4b%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqch2ma900eu2e67fnhq47eo%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Version

3.32.2

### What browsers are you seeing the problem on?

Firefox

### What operating system are you using?

Mac

**Comment by reidbarber** [comment]
This is happening here:

https://github.com/adobe/react-spectrum/blob/8ad0c43026ca7e42f78c4e354652af828bf5a586/packages/%40react-spectrum/datepicker/src/DatePickerSegment.tsx#L54-L57

https://github.com/adobe/react-spectrum/blob/8ad0c43026ca7e42f78c4e354652af828bf5a586/packages/%40react-aria/datepicker/src/useDateSegment.ts#L374

but I'm not sure why it would be `"none"` on the server.

**Comment by liamb13** [comment]
I believe it should be set to none, went all around the web looking for answers.

Latest doc I could find: https://developer.apple.com/documentation/uikit/uitextautocapitalizationtype

> [Constants](https://developer.apple.com/documentation/uikit/uitextautocapitalizationtype#1627013)
> [case none](https://developer.apple.com/documentation/uikit/uitextautocapitalizationtype/none)
> Specifies that there is no automatic text capitalization.
> [case words](https://developer.apple.com/documentation/uikit/uitextautocapitalizationtype/words)
> Specifies automatic capitalization of the first letter of each word.
> [case sentences](https://developer.apple.com/documentation/uikit/uitextautocapitalizationtype/sentences)
> Specifies automatic capitalization of the first letter of each sentence.
> [case allCharacters](https://developer.apple.com/documentation/uikit/uitextautocapitalizationtype/allcharacters)
> Specifies automatic capitalization of all characters, such as for entry of two-character state abbreviations for the United States.

Additional resources:
https://stackoverflow.com/questions/13284323/how-can-i-stop-auto-capitalization-in-a-html-text-input-field-on-an-android-sams

Although, now I'm even more confused:
<img width="981" alt="image" src="https://github.com/adobe/react-spectrum/assets/69778531/0996a332-30c3-4924-9e00-b7cb61ed2ef6">

- Safari has "off"
- Chrome has "off"
- Firefox has "none"

I don't even think the prop should exist on a Time Field, with numeric inputs, autocapitalisation doesn't do anything anyway

**Comment by PixeledCode** [comment]
so was anyone able to fix this?

**Comment by snowystinger** [comment]
FYI, created a bug against FF here https://bugzilla.mozilla.org/show_bug.cgi?id=1906555

> I don't even think the prop should exist on a Time Field, with numeric inputs, autocapitalization doesn't do anything anyway

This isn't quite true, the editable segments can include non-numeric fields such as AM/PM. I don't recall if there are any others which are editable.

Since we still control the capitalization for that field though, we should still be ok to remove it unless someone thinks of another field like AM/PM where we don't.

**Comment by liamb13** [comment]
> This isn't quite true, the editable segments can include non-numeric fields such as AM/PM. I don't recall if there are any others which are editable.

Oh of course! My bad.
