### ISSUE TITLE
Select/ListBox/ListBoxItem can't have empty item

### ISSUE THREAD

**Issue by lukejagodzinski** [adobe/react-spectrum#5623]
### Provide a general summary of the issue here

It's common to have the Select component where one of the options is just empty without any label and value. In regular HTML you would go with something like:
```html
<select>
  <option value=""></option>
  <option value="option1">Option 1</option>
  <option value="option2">Option 2</option>
  <option value="option3">Option 3</option>
</select>
```
And as it's possible to create Select/ListBox/ListBoxItem like that in React Aria, it keeps complaining about this option being empty with the warning:
```
ListBox.tsx:410 A `textValue` prop is required for <ListBoxItem> elements with non-plain text children in order to support accessibility features such as type to select.
```
I've tried to provide some other textValue just for this item but the error seems to originate from somewhere else.

### 🤔 Expected Behavior?

No warning on empty option

### 😯 Current Behavior

Warning: ListBox.tsx:410 A `textValue` prop is required for <ListBoxItem> elements with non-plain text children in order to support accessibility features such as type to select.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/charming-proskuriakova-c4jwrv

### Version

1.0.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS 14.1.2 (23B92)

**Comment by snowystinger** [comment]
An empty item seems like a poor accessibility experience as nothing is announced in VoiceOver. I think it'd be better to provide a visible label which says something like "Nothing selected".

**Comment by lukejagodzinski** [comment]
> An empty item seems like a poor accessibility experience as nothing is announced in VoiceOver. I think it'd be better to provide a visible label which says something like "Nothing selected".

I get it, but it's possible in a regular select. I think it should be up to developer how to handle an empty option.

**Comment by snowystinger** [comment]
I'll bring it up with the team this week.

**Comment by snowystinger** [comment]
Update: I've discussed it with the team. We do not want to support this as it is not a good accessibility experience as mentioned before. However, we did discuss something which may be closer to your intention than my previous suggestion. Following https://react-spectrum.adobe.com/react-aria/Select.html#state you could create a clear button which would return you to an empty state. Negating the need for an empty value, but allowing the Select to return to an unselected state. I'm going to close this issue now. If you run into any issues implementing that, let us know either here or in a new issue.

**Comment by jketcham** [comment]
Is it possible to have a ListBoxItem itself act as a clear button? I'm facing a similar issue where I essentially want an empty item to clear the value, but I don't have a great place in my UI to place a separate clear button.
