### ISSUE TITLE
Table does not support isLoading and fetch more

### ISSUE THREAD

**Issue by lxcid** [adobe/react-spectrum#5631]
### Provide a general summary of the feature here

In the docs, it did mention it supports `useAsyncList()` but it doesn't support fetch more and isLoading.

Looking at old PRs it did seems there was once support for them but seems to be removed.

### 🤔 Expected Behavior?

Have API for `isLoading` and `fetchMore()`

### 😯 Current Behavior

Limited API for async list only support for empty list.

### 🔦 Context

https://react-spectrum.adobe.com/react-aria/Table.html

**Comment by reidbarber** [comment]
Related to https://github.com/adobe/react-spectrum/issues/5493. We may want to use `loadingState` instead of `isLoading`. And we'll want to do this to all collection components that support async loading.

**Comment by lxcid** [comment]
Thanks! @reidbarber! Noted, feel free to merge the ticket if it make sense for you guys! :)

**Comment by lxcid** [comment]
@reidbarber how would you handle loading and error states for table, would u recommend for initial loading to use `renderEmptyState` first?

Would you also recommend using a special item in collection for intersection checks and error status when we load more in an infinite scroll pattern?

**Comment by reidbarber** [comment]
Yes, I would use `renderEmptyState`, and have that be dynamic based on the case (collection still loading, or error).

I don't think I would use a special item to implement infinite scrolling. I think for now, you could use `onScroll` and check the container's `scrollTop`, as described here: https://github.com/adobe/react-spectrum/issues/5493#issuecomment-1836689789. Sorry for the delayed response; the team is on break this week so responses may not be as fast as usual.

**Comment by snowystinger** [comment]
Just a heads up that the RAC components don't support virtualization (infinite scrolling) yet. You can use virtualization with the hooks, but it's a bring-your-own virtualization. For RAC, though, it's probably better to use pagination for now.

**Comment by hwb15** [comment]
> Just a heads up that the RAC components don't support virtualization (infinite scrolling) yet. You can use virtualization with the hooks, but it's a bring-your-own virtualization. For RAC, though, it's probably better to use pagination for now.

Thanks for clarifying, I was looking to refactor a few components over from Headless UI but might leave it out for the moment, RAC is a great library so I look forward to the point when I virtualization is supported directly in RAC.
