### ISSUE TITLE
The Link component is missing props for lang, hrefLang and title

### ISSUE THREAD

**Issue by cbodin** [adobe/react-spectrum#5633]
### Provide a general summary of the feature here

Adding lang, hrefLang and title to the `<Link>` component, it's possible that more components would need this as it's pretty common to present a language dialog if the current site language is not in the users Accept-Language header.

### 🤔 Expected Behavior?

I should be able to add these attributes to the `<Link>` component to specify that the contents is in another language than the rest of the site.

### 😯 Current Behavior

Neither lang, hrefLang or title is available as props to the `<Link>` component.

### 💁 Possible Solution

Add lang, hrefLang and title to the `<Link>` component.

### 🔦 Context

I'm trying to create a language selector with links to other languages. The text on the link is in the target language, so that if speakers end up on a language they do not know, they will find a link with the text "English".

### 💻 Examples

```html
<nav>
  <h3>Select language</h3>
  <a href="/sida" lang="sv-SE" hreflang="sv-SE" title="Byt till Svenska">Svenska</a>
  <a href="/en/page" lang="en-SE" hreflang="en-SE" title="Switch to English">English</a>
</nav>
```

**Comment by snowystinger** [comment]
`lang` and `hreflang` both seem reasonable

Not sure about title, we typically discourage that in favor of `aria-label`

**Comment by cbodin** [comment]
> `lang` and `hreflang` both seem reasonable
> 
> Not sure about title, we typically discourage that in favor of `aria-label`

Title is not as necessary, however it will show a tooltip when hovered which will increase accessibility for non-screen reader users. Afaik aria-title will not show a tooltip.

**Comment by snowystinger** [comment]
That is correct, however, the 'title' tooltip is not styleable. So if you need a tooltip, we'd encourage using the `Tooltip` and `TooltipTrigger` components in React Aria Components.

All tooltips though are not accessible to Touch users, so we still discourage any sort of tooltip usage.

**Comment by stefanprobst** [comment]
similar usecase:

i am using [`next-intl`](https://github.com/amannn/next-intl) for i18n, which provides their own `<Link>` component wrapper around `next/link`, which

1. automatically adds a locale prefix to the `href`, and 
2. allows passing a `locale` prop to switch to a different locale

is it correct that (1) can currently be achieved by passing a wrapped `router.push` function to the `RouterProvider`, but (2) is currently not possible with RACs Link component?

**Comment by ryo-manba** [comment]
I don't think it is necessary to give the `lang` attribute to the link. If needed, a span can be used within the link to specify the language. This approach is discussed in the following article:

[Declaring language in HTML](https://www.w3.org/International/questions/qa-html-language-declarations#contentvsattribute)

It's a tough call, but allowing the title attribute as recommended by the W3C might be worth considering.

[H33: Supplementing link text with the title attribute | Techniques for WCAG 2.0](https://www.w3.org/TR/WCAG-TECHS/H33.html)

**Comment by reidbarber** [comment]
@ryo-manba Thanks for linking that. This passage does make me lean towards not allowing it:

> Because of the extensive user agent limitations in supporting access to the title attribute, authors should use caution in applying this technique. For this reason, it is preferred that the author use technique [C7: Using CSS to hide a portion of the link text](https://www.w3.org/WAI/WCAG21/Techniques/css/C7) or [H30: Providing link text that describes the purpose of a link for anchor elements](https://www.w3.org/WAI/WCAG21/Techniques/techniques/H30).
