### ISSUE TITLE
Support hover events on the ListBox Option component

### ISSUE THREAD

**Issue by bmwoodall** [adobe/react-spectrum#5638]
### Provide a general summary of the feature here

Current we have no way to pass in hover events into the `Option` component within the `ListBox` component in react-aria-components. It would be nice to be able to trigger events on item hover, I imagine this could be extended to focus events as well.

### 🤔 Expected Behavior?

I would expect that a consumer could pass in the `onHoverStart` event or the other events supported within the `useHover` hook being utilized in the `Option` component within the `ListBox` 

### 😯 Current Behavior

Hover events are not passed into the `useHover` hook within in the `Option` component.

### 💁 Possible Solution

Add `HoverProps` to the `ListBoxItem` component and pass them through to the `useHover` within the `Option` in the `ListBox` component.

### 🔦 Context

I have a use case to where I need to change the content of a div on hover of a listbox option. To preserve accessibility I want to avoid passing in additional interactive elements into `ListBoxItem`, but I have no way of executing a callback on hover of the `ListBoxItem`.

**Comment by reidbarber** [comment]
Seems reasonable to me. I don't think we are doing this for any other collection items at the moment, so we probably want to be consistent with this if we decide to add it.

**Comment by snowystinger** [comment]
Could you always render the element and just apply display: none vs whatever based on `data-hovered`? https://react-spectrum.adobe.com/react-aria/ListBox.html#listboxitem-1

I also see isHovered in the renderProps for ListBoxItem https://react-spectrum.adobe.com/react-aria/ListBox.html#listboxitem

Could you provide a codesandbox to clarify what you're trying to accomplish? Maybe I've misunderstood.

**Comment by reidbarber** [comment]
@snowystinger The solution you mentioned seems like a better solution for this use case. I think the ask is for `onHoverStart`, `onHover`, `onHoverEnd` to be added to the item's props, which seems like something we could do anyway, and may be useful in other scenarios.

**Comment by bmwoodall** [comment]
@snowystinger the rendering logic based on hover is fine, what I need is the ability to execute a callback on hover of a list item. 

The work around I have now is to use the `useHover` hook on a child wrapper within the `ListBoxItem` component. This is definitely not ideal as there could be issues for keyboard users and properly triggering events on the child. 

To @reidbarber point, exposing the `onHoverStart`, `onHoverEnd`, and `onHoverChange` events could be nice on collection items. 

I don't mind opening a PR for this functionality, I just wanted to verify that there wasn't a specific reason for not making these event available.

**Comment by bmwoodall** [comment]
For clarification the use case I need is changing the rendering of an element outside of the `ListBox` based on which `ListBoxItem` is currently hovered, not an element within the `ListBoxItem` itself.

**Comment by reidbarber** [comment]
Feel free to open a PR (it will definitely make it in sooner if so). You'll just need to spread the props into the `useHover` props, update the item props' interface to extend `HoverEvents`, and include a test that verifies the handlers get called.
