### ISSUE TITLE
Multiple thumbs slider with controlled value doesn't update correctly thumb state

### ISSUE THREAD

**Issue by junseinagao** [adobe/react-spectrum#5644]
### Provide a general summary of the issue here

When using multiple thumbs with the `<Slider />` component imported from `react-aria-components`, updating the controlled value causes non-updated thumbs to revert to their original values upon the next slider interaction.

https://github.com/adobe/react-spectrum/assets/54606780/ea2a152b-c529-4a2d-a04e-95a1432113aa

### 🤔 Expected Behavior?

The expected behavior is that when the value prop of the slider `<Slider value={MULTIPLE_NUMBER} />` is updated programmatically, all thumbs should reflect the new values accurately and maintain these values during subsequent interactions with the slider.

### 😯 Current Behavior

Currently, when the slider's controlled value is updated, and the slider is interacted with again, the non-updated thumbs revert to their original values instead of maintaining the updated state.

### 💁 Possible Solution

I guess Slider thumbs state that control in the component doesn't update correctly state with using `state.setThumbValue()` because this behavior will be fixed to catch updated value and use `state.setThumbValue()` .

This behavior can be fixed by this hack implementation.

```tsx
export default function App() {
  const [value, setValue] = React.useState([0, 100]);

  return (
    <>
      <Slider value={value} onChange={setValue} minValue={0} maxValue={100}>
        <SliderOutput
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-end",
          }}
        >
          {({ state }) => (
            <>
              <p>Current values: {state.values.join(" – ")}</p>
              <Button
                onClick={() => {
                  // 👇 update thumb value directly.
                  state.setThumbValue(0, 0);
                  state.setThumbValue(1, 100);
                }}
              >
                Reset
              </Button>
            </>
          )}
        </SliderOutput>
        <SliderTrack>
          <SliderThumb index={0} />
          <SliderThumb index={1} />
        </SliderTrack>
      </Slider>
    </>
  );
}
```

### 🔦 Context

I'm trying to update values to reset value. 

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/react-aria-components-slider-multiple-thumb-issue-xlvxmg?file=%2Fsrc%2FApp.js

### Version

react-aria-components@1.0.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac OS 14.1.1

**Comment by reidbarber** [comment]
Interesting, I wasn't able to reproduce this in the provided codesandbox:

https://github.com/adobe/react-spectrum/assets/8961049/30fdf126-3953-4a01-b46e-75f0c6fef8c8

**Comment by junseinagao** [comment]
@reidbarber 

My bad. I had changed the codesandbox to show possible solution code. Now, I updated the codesandbox to show the bug.

**Comment by sookmax** [comment]
@reidbarber 

Looks like the problem is that `valuesRef.current` in `useSliderState()`, which is used to derive the new `state.values` becomes _out of sync_ when `props.value` is updated by something other than `<SliderThumb />` interactions (i.e., the reset button in the example). 

In other words, if a user uses the same setter that they provided to `props.onChange` to change the value somewhere outside `<Slider />`, then `<Slider />` doesn't know this currently, and so `valuesRef.current` becomes stale, resulting in the behavior described in this issue.

(state updater functions such as `state.setThumbValue` and `state.setThumbPercent` work properly because they update `valuesRef.current` in `setValues()` internally)

In my local environment, adding the following effect in `useSliderState()` seems to fix the issue.
```js
useEffect(() => {
  valuesRef.current = values;
}, [values]);
```

If this looks like the right fix, then I'll submit a PR.

**Comment by snowystinger** [comment]
Thanks @sookmax for having a look. Doing it that way I think might cause some other issues as it'll update every render cycle when the ref isn't really meant to be tied to renders and instead should be updated only by events.

I think we could update it when dragging starts?

Absolutely feel free to open a PR to discuss over there though. Again, thanks so much for looking into it!

**Comment by sookmax** [comment]
@snowystinger Got it. I'll see what I can do without resorting to using an effect.
