### ISSUE TITLE
`PressResponder` warning in `<Popover>` when importing individual `@react-aria` packages instead of `react-aria` monopackage

### ISSUE THREAD

**Issue by catherine** [adobe/react-spectrum#5647]
### Provide a general summary of the issue here

After introducing `react-aria-components` to my project, I am finding that I can no longer import all individual packages for the hooks I want to access (specifically, `@react-aria/interactions` and `@react-aria/button`), but instead need to use the full `react-aria` package directly now.

### 🤔 Expected Behavior?

Continued ability to incrementally import individual `react-aria` packages alongside `react-aria-components` when specific hooks are needed instead of requiring the full package.

### 😯 Current Behavior

My application previously utilized `useLongPress` from `@react-aria/interactions`. In building a popover with the `react-aria-components` `<Popover/>`, I have the need to drop down into the `useButton()` hook in order to use my design system's styled buttons. I planned to similarly add `@react-aria/button` instead of switching to requiring the full `react-aria` monopackage.  

```
"@react-aria/button": "3.9.0",
"@react-aria/interactions": "3.20.0",
"react-aria-components": "1.0.0",
```
The `<Popover/>` is not rendering when the trigger is pressed and the console reflects the following warning (from [here](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/PressResponder.tsx#L43)):

```
A PressResponder was rendered without a pressable child. Either call the usePress hook, or wrap your DOM node with <Pressable> component. 
    at eval (webpack-internal:///./node_modules/react-aria-components/node_modules/@react-aria/interactions/dist/import.mjs:722:129)
    at $64fa3d84918910a7$export$2881499e37b75b9a (webpack-internal:///./node_modules/react-aria-components/dist/import.mjs:983:62)
    at $de32f1b87079253c$export$2e1e1122cf0cba88 (webpack-internal:///./node_modules/react-aria-components/dist/import.mjs:2778:88)
    at PermissionGate (webpack-internal:///./src/product/permissions/PermissionGate.tsx:73:5)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at div
    at Loader (webpack-internal:///./node_modules/@turo/ui/lib/loading-state/Loader.js:38:78)
    at TaxInformationView (webpack-internal:///./src/pages/tax-information/TaxInformationView.tsx:53:5)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connect.js:240:114)
    at ProtectedView (webpack-internal:///./src/routing/ProtectedView.js:34:7)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connect.js:240:114)
    at ModuleLoader (webpack-internal:///./src/routing/ModuleLoader.tsx:31:5)
    at LazyRoute (webpack-internal:///./src/routing/LazyRoute.tsx:33:5)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:465:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:671:29)
    at ClientSwitch (webpack-internal:///./src/ClientSwitch.js:27:5)
```

When I switch over to using `"react-aria": "3.31.0",` instead of the individual packages or remove `@react-aria/interactions`, the error does not persist; the trigger opens the `<Popover/>` and there is no PressResponder warning. 

### 🖥️ Steps to Reproduce

Sandbox: https://codesandbox.io/p/sandbox/react-aria-components-s6slvx-s6slvx

In it, both `@react-aria/interactions` and `@react-aria/button` are in `package.json`.

1. View console and see the warning logging. Press the button and see that it does not trigger the Popover.
2. Remove `@react-aria/interactions` from `package.json`
3. See the warning no longer logs and the Popover successfully triggers.

### Version

3.33.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS Venture 13.5.2

**Comment by snowystinger** [comment]
Most likely when installing the individual ones you've introduced duplicate copies, it's unfortunately very easy to do because the package managers are optimized for node instead of browsers. Could you check your lockfile?

**Comment by catherine** [comment]
```
react-aria-components@1.0.0:
  version "1.0.0"
  dependencies:
    react-aria "^3.31.0"

react-aria@^3.31.0:
  version "3.31.0"
  dependencies:
    "@react-aria/button" "^3.9.1"
    "@react-aria/interactions" "^3.20.1"
```

Ah... a patch version number became the minimum for both. I was working with the latest minors.

**Comment by ozguruysal** [comment]
I have the same issue too. We are using `react-aria-components` and also building some custom components using hooks. `react-aria` doesn't seem to export everything that individual packages do. 

For example, we need to use `useSelectableCollection` and that's only exported in `@react-aria/selection`. Similarly `ListCollection` is not exported in `react-stately` but in `@react-stately/list`.

@snowystinger can you recommend a solution or a direction we should be going? Also is there any reason why full packages do not export everything as the individual packages?

**Comment by snowystinger** [comment]
Usually, the things that aren't exported are things that we haven't documented or that we use internally but don't expect people outside to use.

Can you describe a bit more as to why you need to use some of these? That will give us more information as to how people use our modules and will allow us to better assess what we export and what we document.

**Comment by ozguruysal** [comment]
Thanks for asking. Our design system has some components that requires implementing a custom solution. I'm currently building a component that pretty much behaves like [this example](https://ej2.syncfusion.com/vue/demos/#/tailwind/multi-select/checkbox.html). Using all the hidden utilities React Aria offers, it looks like it's mostly possible to do a lot more than the default RACs when needed. Honesty I'd really like them to be in the docs rather then finding them in the source code and trying to understand how I can utilize them.

On another design system I used React Aria hooks (RAC didn't exist back then) and now I'd like to use RAC, since it really simplifies things for me but like I explained above I need to build additional components or customize them which requires those hidden utilities.

Would be really nice to find a solution for this duplicate copies in the lock file. Using PNPM, I see they are added sometimes but sometimes all seem to work just fine. As the project grows it might be really tricky for us.

**Comment by snowystinger** [comment]
How are you going about building this? It looks like it should be something along these lines (untested and pseudocode)
```
let filterText = useState('');
let items = [...].filter(filterText);
let [selectedKeys, setSelectedKeys] = useState([])
...
  <div>
  <span>{getLabels(items, selectedKeys)}</span>
  <Button>x</Button>
  <DialogTrigger> // control the open state to also open for a click on the whole thing, use width controls to match the group width
    <Button>v</Button>
    <Popover>
      <Dialog>
        <TextField autoFocus />
        <Checkbox>...Select All</Checkbox>
        <ListBox items selectedKeys setSelectedKeys>
          // render function
        </ListBox>
      </Dialog>
    </Popover>
  </DialogTrigger>
</div>
```

Granted, there wouldn't be virtual focus management between the textfield and the listbox. But maybe that's something we need to look into supporting, in the meantime this would still be keyboard accessible.

**Comment by ozguruysal** [comment]
Implementation is very similar to `useComboBox`. Instead of `useComboBoxState` I used `useListState` with `selectionMode: "multiple"`. So it's like:

```tsx
const state = useListState();
const { listBoxProps } = useListBox({});

// Text field and filtering 
const { contains } = useFilter({});

// filter collection with `filterCollection` from `useComboBoxState`
const filteredCollection = React.useMemo(() => filterCollection());

const { collectionProps } = useSelectableCollection({})
const { inputProps } = useTextField({
  ...
  onKeyDown: chain(collectionProps.onKeyDown, ...),
})

// Finally render like you have above, although I haven't been able to use ListBox from RAC.
<DialogTrigger>
  <Button>{state.selectionManager.selectedKeys.size} items</Button>
  <Popover>
    <Dialog>
      <Input { ...inputProps } autoFocus />  // This currently causes a page jump though

      <ul {...listBoxProps} ref={listBoxRef}>
        {[...filteredCollection].map((item) => (
          <Option key={item.key} item={item} state={state} />
        ))}
      </ul>
    </Dialog>
  </Popover>
</DialogTrigger>
```
Virtual focus is also working while you're focused on the text input. I can try to share a Codesandbox later if you want.
