### ISSUE TITLE
[React Aria Components] `isInvalid` is missing in `DateInputRenderProps`

### ISSUE THREAD

**Issue by alex-mcgovern** [adobe/react-spectrum#5662]
### Provide a general summary of the issue here

Exported type:

```ts

// [...]/react-aria-components/src/DateField.tsx

export interface DateInputRenderProps {
    /**
     * Whether the date input is currently hovered with a mouse.
     * @selector [data-hovered]
     */
    isHovered: boolean;
    /**
     * Whether an element within the date input is focused, either via a mouse or keyboard.
     * @selector [data-focus-within]
     */
    isFocusWithin: boolean;
    /**
     * Whether an element within the date input is keyboard focused.
     * @selector [data-focus-visible]
     */
    isFocusVisible: boolean;
    /**
     * Whether the date input is disabled.
     * @selector [data-disabled]
     */
    isDisabled: boolean;
}
```

Logged render props from console:

```ts
{
    "isHovered": false,
    "isFocusWithin": false,
    "isFocusVisible": false,
    "isDisabled": false,
    "isInvalid": false
}
```

### 🤔 Expected Behavior?

`isInvalid` should be exported from `DateInputRenderProps`

### 😯 Current Behavior

`isInvalid` not exported from `DateInputRenderProps`

### 💁 Possible Solution

Add it to the type declaration, happy to open a PR for this, but would also need to touch docs, presumably.

### 🖥️ Steps to Reproduce

Log render props for `DateInput` component

### Version

1.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

MacOS

**Comment by LFDanLu** [comment]
Good catch, I don't recall any particular reason `isInvalid` shouldn't be in those render props. Feel free to open a PR for this, I don't think you'll have to add anything other than the type declaration, the docs should pick that extra type automatically with its associated description.

**Comment by alex-mcgovern** [comment]
@LFDanLu opened this [PR](https://github.com/adobe/react-spectrum/pull/5670) to fix this
