### ISSUE TITLE
Tooltip positioning incorrect when containing a focusable element

### ISSUE THREAD

**Issue by andrew-pledge-io** [adobe/react-spectrum#5665]
### Provide a general summary of the issue here

Given a `<TooltipTrigger>` containing a focusable trigger element like a `<Button>`, and a `<Tooltip>` which contains a focusable element like a `<Link>`, the overlay position of the tooltip is incorrect.

### 🤔 Expected Behavior?

The tooltip overlay is positioned relative to the trigger element.

<img width="276" alt="image" src="https://github.com/adobe/react-spectrum/assets/125917457/7e5e2b69-8c9d-49bc-a1fd-9bc944d65680">

### 😯 Current Behavior

The tooltip overlay is positioned incorrectly.

<img width="463" alt="image" src="https://github.com/adobe/react-spectrum/assets/125917457/c4506b1c-8de9-4d92-b908-f20dea43564c">

### 💁 Possible Solution

Manually specifying `triggerRef` might be a workaround for this case. If that's intended, it might be worth noting in the docs.

### 🔦 Context

My interface has an information icon that uses a tooltip to show instructions on hover. The information includes a link to more detailed instructions.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/rac-tooltip-reproduction-vl4x8h?file=%2Fsrc%2FApp.tsx%3A28%2C56

### Version

react-aria-components@1.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you using?

MacOS

**Comment by snowystinger** [comment]
Tooltips cannot contain a focusable element. That would break accessibility. See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role#description
> Because the tooltip itself never receives focus and is not in the tabbing order, a tooltip can not contain interactive elements like links, inputs, or buttons.

**Comment by andrew-pledge-io** [comment]
Thanks for the response, I'll look into doing that instead.
