### ISSUE TITLE
ComboBox with `useAsyncList` doesn't open the menu again when a search hit occurs AFTER a search miss.

### ISSUE THREAD

**Issue by sookmax** [adobe/react-spectrum#5690]
### Menu open/close behavior of a normal ComboBox

A search miss -> the menu is closed -> a search hit -> the menu is reopen to show the (non-empty) filtered items.

https://github.com/adobe/react-spectrum/assets/71210554/cdaa5e8e-ccca-4818-ae0e-5ead626ca295

### Menu open/close behavior of a ComboBox with `useAsyncList`

A search miss -> the menu is closed -> a search hit -> the menu doesn't reopen.

https://github.com/adobe/react-spectrum/assets/71210554/8910ed51-de52-41bc-a282-fcbb035698fe

---

It look like this issue has something to do with [this effect](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/combobox/src/useComboBoxState.ts#L188-L258) in `useComboBoxState()`. 

In particular, it seems like the update timing of `filteredCollection.size` lags behind that of `inputValue` and `lastValue` when the filtering is async, so the following conditional statement inside the effect never evaluates to `true` and thus the menu doesn't reopen:
https://github.com/adobe/react-spectrum/blob/d330a9dc13dd8376f5d2f8cdffcd7bce53a8fbf4/packages/%40react-stately/combobox/src/useComboBoxState.ts#L189-L199

For example, let's say we have a menu item named 'foo' and we type 'f' -> 'fd' -> 'f' in a sequence.
- in a normal combobox when the input is going from 'fd' to 'f' we have:
  - `filteredCollection.size = 1`, `inputValue = 'f'`, `lastValue = 'fd'`, with which the above condition is evaluated to `true`, opening the menu.
- in a combobox with `useAsyncList()` when the input is going from 'fd' to 'f' we have:
  - `filteredCollection.size = 0`, `inputValue = 'f'`, `lastValue = 'fd'` (waiting for the async filter to return the value)
  - `filteredCollection.size = 1`, `inputValue = 'f'`, `lastValue = 'f'` (filtering is done but `lastValue` has already been updated to the same value as `inputValue`)
  - So none of the above value combinations triggers the menu to open.

### 🤔 Expected Behavior?

A combobox with `useAsyncList` to behave the same way as a normal combobox.

### 😯 Current Behavior

A combobox with `useAsyncList` does not behave the same way as a normal combobox.

## Normal combobox
https://react-spectrum.adobe.com/react-aria/ComboBox.html#menu-trigger-behavior

## Async combobox
https://react-spectrum.adobe.com/react-aria/ComboBox.html#asynchronous-loading

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Sonoma 14.2.1

**Comment by richardbann** [comment]
This seems to be the same as #5234

**Comment by sookmax** [comment]
@richardbann Thanks for the issue link!

It indeed seems to work when `allowsEmptyCollection: true` is specified for `useComboBoxState()` as https://github.com/adobe/react-spectrum/issues/5234#issuecomment-1809482551 mentions. 

The menu seems to be open at all time (whether search is hit or miss) while input value is changing when `allowsEmptyCollection` is `true`, which I think could be a decent workaround for this issue.

Unfortunately it looks like `allowsEmptyCollection` is not exposed as a Combobox prop [currently](https://react-spectrum.adobe.com/react-aria/ComboBox.html#props).

So.. @snowystinger do you think it's okay to expose `allowsEmptyCollection` as a Combobox prop? If so, I'll submit a PR for that.


https://github.com/adobe/react-spectrum/assets/71210554/1336ab7c-b42a-437e-a145-e3f4bcaeeeda

**Comment by LFDanLu** [comment]
`allowsEmptyCollection` is now exposed in RAC ComboBox via https://github.com/adobe/react-spectrum/pull/5842, just waiting on the build to check the docs

**Comment by silviu-at** [comment]
@LFDanLu Do you have any information on when the next release is going to be? Currently evaluating if we should just wait for the next release in order to get access to the `allowsEmptyCollection` prop on the react aria `ComboBox` (https://github.com/adobe/react-spectrum/pull/5842), or just implement our own combobox using `useComboBoxState` and `useComboBox`.

**Comment by sookmax** [comment]
@silviu-at 

Not sure about the exact date of the next release, but looks like it's going to be before May, judging from https://github.com/adobe/react-spectrum/pull/6247, which includes [the fix](https://github.com/adobe/react-spectrum/pull/6247/files#diff-0817015ef0279c06ff8a8a0d6f60d04ae8d4609665c6c7f25e8279b038773034R26) as well. 

If you want to use it right now, you could install [the nightly version](https://www.npmjs.com/package/react-aria-components?activeTab=versions), which already contains the fix.

**Comment by silviu-at** [comment]
@sookmax thanks for the quick reply 🙌
