### ISSUE TITLE
[Windows High contrast Mode] Border is getting drawn around quiet button in disabled state

### ISSUE THREAD

**Issue by PreetiNagal** [adobe/react-spectrum#5691]
### Provide a general summary of the issue here

[Windows High contrast Mode] Border is getting drawn around quiet button in disabled state

### 🤔 Expected Behavior?

Border should not be drawn around quiet button in disabled state

### 😯 Current Behavior

Border is drawn around quiet button in disabled state

### 💁 Possible Solution

border color in disabled state should be set to --spectrum-high-contrast-button-face

### 🖥️ Steps to Reproduce

[code](https://codesandbox.io/p/sandbox/angry-lalande-d7hx4n?file=%2Fsrc%2FApp.js%3A1%2C1-57%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqxh2b9j00063b6h6vzm2y4v%2522%252C%2522sizes%2522%253A%255B89.96527777777777%252C10.034722222222229%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqxh2b9j00023b6hmdih9bm7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqxh2b9j00033b6hjovsvwa9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqxh2b9j00053b6hv07aloab%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqxh2b9j00023b6hmdih9bm7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxh2b9i00013b6hiltpezvd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr4wcykt00023b6hn1ch3voq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A57%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqxh2b9j00023b6hmdih9bm7%2522%252C%2522activeTabId%2522%253A%2522clr4wcykt00023b6hn1ch3voq%2522%257D%252C%2522clqxh2b9j00053b6hv07aloab%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxh2b9j00043b6hruta5ck7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqxh2b9j00053b6hv07aloab%2522%252C%2522activeTabId%2522%253A%2522clqxh2b9j00043b6hruta5ck7%2522%257D%252C%2522clqxh2b9j00033b6hjovsvwa9%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqxh2b9j00033b6hjovsvwa9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

check this in windows high contrast enabled state

### Version

latest

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What operating system are you using?

Mac, windows

### 🧢 Your Company/Team
Adobe

**Comment by majornista** [comment]
I think quiet action buttons are meant to have a border in high contrast mode. The issue may actually be that the enabled button does not have a border in high contrast mode. You can see this in the Spectrum Web Components implementation   https://opensource.adobe.com/spectrum-web-components/components/action-button/#quiet

**Comment by snowystinger** [comment]
Correct, border should be drawn always for the HCM version.

**Comment by PreetiNagal** [comment]
If border should be present in default state also, then how we will distinguish it from hover state?
Currently in react-spectrum, border is not drawn in default state, but it's drawn when button is hovered.

**Comment by majornista** [comment]
As a point of reference, here are screen shots of the MS Word toolbar in Office 365 showing border being added to icon buttons when `forced-colors: active`:

With high contrast mode OFF:
<img width="731" alt="MS Word toolbar with high contrast mode OFF, showing icon-only buttons without a border" src="https://github.com/adobe/react-spectrum/assets/154077/70150a73-492d-44ce-9b19-66829951d7af" />

With high contrast mode ON:
<img width="731" alt="MS Word toolbar in dark mode with high contrast mode ON, showing icon-only buttons with an added border" src="https://github.com/adobe/react-spectrum/assets/154077/e57ede05-79c4-401c-9ea8-0f1dc32bbcb0" />

**Comment by PreetiNagal** [comment]
Hello Team
Could someone please provide information on the expected release date for these changes?

**Comment by snowystinger** [comment]
It'll be in our next release, likely in February.
