### ISSUE TITLE
[MENU]Issue in navigating to menu items using arrow keys when items are rendered in a menu section

### ISSUE THREAD

**Issue by PreetiNagal** [adobe/react-spectrum#5696]
### Provide a general summary of the issue here

  Render menu items inside section with selection mode set as single and try to navigate menu items using arrow keys. Issue appears when menu items are more than 12 and scrollbar is shown. 

### 🤔 Expected Behavior?

menu items should be accessible using up down arrow keys

### 😯 Current Behavior

On using arrow keys, scroll bar is getting scrolled and hence user is not able to access the menu items

### 🖥️ Steps to Reproduce

render a single selection menu with items more than 12ish and such that scroll bar is also shown Decrease browser height for scroll with 12ish items. 

### Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

Mac, windows

**Comment by ktabors** [comment]
Reproduced this in a code sandbox using single selection. This works correctly with multiple selection.  Needs additional investigation into why selection mode seems to case this.

**Comment by LFDanLu** [comment]
We've been tracking this issue internally actually, but you are correct in your analysis @sookmax. Ideally `scrollIntoViewport` would scroll the target into view within its nearest scrollable parent, then for each parent within a scrollable parent we'd need to scroll them in such a way that the target is still in view, repeating until we hit the document root/top most scrollable parent. This will take some calculation to determine the target's relative position in each scrollable parent's scroll region.

**Comment by PreetiNagal** [comment]
what's the status of this issue fixation?

**Comment by LFDanLu** [comment]
No updates as of now, the team hasn't had the bandwidth to pick this up unfortunately.

**Comment by PreetiNagal** [comment]
we need to migrate our component having this use case to RSPV3 asap. Please help in prioritising this issue fixation.

**Comment by snowystinger** [comment]
The fastest way to get this prioritized is to submit a PR for it. There is a suggestion for a fix above.
