### ISSUE TITLE
Clicking below the DateField activates the segment above the cursor.

### ISSUE THREAD

**Issue by RafalFilipek** [adobe/react-spectrum#5719]
### Provide a general summary of the issue here

Clicking below the DateField activates the segment above the cursor.

### 🤔 Expected Behavior?

Segments should be activated only with interactions inside DateField.

### 😯 Current Behavior

Clicking on the field activates the segment above the cursor.

### 🖥️ Steps to Reproduce

You can reproduce here https://react-spectrum.adobe.com/react-aria/DateField.html

![CleanShot 2024-01-19 at 16 11 56](https://github.com/adobe/react-spectrum/assets/80960/71274527-2696-41aa-b406-455311b19380)

### Version

1.0.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOs

**Comment by LFDanLu** [comment]
This is covered by https://github.com/adobe/react-spectrum/issues/3164, there are some possible workarounds/notes in that tickets that may of be of use. Closing this out in favor of that issue
