### ISSUE TITLE
Modal not working in iOS 14

### ISSUE THREAD

**Issue by jordant97** [adobe/react-spectrum#5720]
### Provide a general summary of the issue here

Got this error when opening Modal in iPhone on iOS 14.

Unhandled Runtime Error 
TypeError: undefined is not a constructor (evaluating 'new Intl.ListFormat()')

### 🤔 Expected Behavior?

Should open the modal

### 😯 Current Behavior

Throw the error above instead

### 🖥️ Steps to Reproduce

Just try it on iOS 14

### Version

^1.0.0-rc.0

### What browsers are you seeing the problem on?

Safari

### What operating system are you using?

iOS 14

**Comment by reidbarber** [comment]
Intl.ListFormat is only supported in iOS 14.5 and newer, so that version may not be supported: https://caniuse.com/mdn-javascript_builtins_intl_listformat_format
