### ISSUE TITLE
Accordion typeahead conflicts with typing inside

### ISSUE THREAD

**Issue by FosterSamuel** [adobe/react-spectrum#5745]
### Provide a general summary of the issue here

When typing inside an input in an `Accordion`, typeahead search begins, which blocks empty spaces from going to the input.

### 🤔 Expected Behavior?

Typing inside an input in an `Accordion` should not conflict with typeahead search. 

### 😯 Current Behavior

Typing inside an input in an `Accordion` starts a typeahead search, blocking empty spaces until the search is cleared.

### 💁 Possible Solution

`useTypeSelect` stops event propagation on empty spaces in this block: https://github.com/adobe/react-spectrum/blob/5a0690fe911ee3041b4bb3014273e19c79b5224e/packages/%40react-aria/selection/src/useTypeSelect.ts#L64

Before starting a typeahead search, `useTypeSelect` could check if `event.target` is an input. `event.target.tagName` or `'value' in event.target` could reveal if typing is happening inside an element that should not trigger `Accordion` typeahead.

If this sounds reasonable, I'm happy to write a PR.

### 🔦 Context

No further context. Just want to say thank you for the continued work on `react-aria`! We're loving it here so far.

### 🖥️ Steps to Reproduce

Minimal repro: https://codesandbox.io/p/sandbox/broken-tdd-2v8z7q

- Type "test"
- Type an empty space
- Observe empty space not added
- Wait 1 second, typeahead clears, and new empty spaces can be added
  - Typeahead is cleared [here](https://github.com/adobe/react-spectrum/blob/5a0690fe911ee3041b4bb3014273e19c79b5224e/packages/%40react-aria/selection/src/useTypeSelect.ts#L90)

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS, latest

**Comment by reidbarber** [comment]
Just as a heads up:

> Accordion and its hooks are in a very early state and we've not had the time to prioritize finishing them. As a result, we do not document them, and they are use at your own risk if you happen to discover it. See https://react-spectrum.adobe.com/Support.html#pre-releases for more information about our versioning.

From https://github.com/adobe/react-spectrum/pull/1659#issuecomment-1763492398 via @snowystinger 

I think the preferable solution would be to either disabled typeahead for this component by passing `disallowTypeAhead: true` into `useSelectableList`, or figure out a way to do so if focus is within an accordion item region.

**Comment by FosterSamuel** [comment]
@reidbarber thanks, heard on expectations. I checked ARIA practices and did not find typeahead. #5752 goes forward with your suggestion for `disalloweTypeAhead: true`.

**Comment by FosterSamuel** [comment]
Signed Adobe CLA and re-opened PR.
