### ISSUE TITLE
Wrong Italian translation for the placeholder attribute of the Picker component

### ISSUE THREAD

**Issue by Giordano-Novomatic** [adobe/react-spectrum#5749]
### Provide a general summary of the issue here

The placeholder attribute for the Picker component now uses the wrong language for the Italian localization.

### 🤔 Expected Behavior?

The correct translation should be "Seleziona una opzione..."

### 😯 Current Behavior

Now uses the string "Seleccione una opción…" (wich is spanish i think)

### 💁 Possible Solution

Replace the wrong language with the one suggested in the expected behaviour. (can be reverted to an older version as it was working before updating)

### 🖥️ Steps to Reproduce

Create a Picker component, set the locale to it and check for the placeholder text.

### Version

3.32.2

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

Windows

**Comment by devongovett** [comment]
@rgeraghty

**Comment by rgeraghty** [comment]
Thanks @Giordano-Novomatic for reporting, we are fixing this issue
cc: @devongovett
