### ISSUE TITLE
Strange behaviors in `useColorField` input when value starts with `#`

### ISSUE THREAD

**Issue by cssinate** [adobe/react-spectrum#5759]
### Provide a general summary of the issue here

The current state of the `useColorField` input (hereafter referred to as the Input) leads to some very strange and awkward user experience.

### 🤔 Expected Behavior?

- I should be able to backspace to erase all data in the Input, no matter what's in there already
- I should be able to type more than 3 valid characters after a # sign before it tries to parse

### 😯 Current Behavior

If the Input already has a `#` at the start, whether because there was a previously good known value or because the user typed it in manually, the behavior is very strange. You can't erase the value via backspace, and there's no good way to manually type more than 3 characters.

### 💁 Possible Solution

There's clearly an action that tries to happen on every change to format the color value. The formatting of the text inside the input should not take place until the input is blurred. You can still send out the `onChange` for the Input, but the actual formatting of the text shouldn't happen while the Input is in focus. 

### 🔦 Context

1. I tried to erase the value of my color field and couldn't
2. I tried to enter a color manually and couldn't

### 🖥️ Steps to Reproduce

You can test this in your own documentation: https://react-spectrum.adobe.com/react-aria/useColorField.html#controlled

1. Try first to backspace the value that's there already
2. Erase the entire value and try typing in `#c0ffee`

### Version

useColorField 3.0.0-beta.29

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 11

**Comment by reidbarber** [comment]
I believe this is a duplicate of https://github.com/adobe/react-spectrum/issues/5484

**Comment by cssinate** [comment]
You're right. I did try to search ahead of time, but I guess I didn't search for the right things.
