### ISSUE TITLE
`Form` component from `react-aria-components` doesn't accept all <form> props

### ISSUE THREAD

**Issue by Yovach** [adobe/react-spectrum#5764]
### Provide a general summary of the issue here

The `<Form>` component doesn't accept `id` from `<form>` (and many other props)

### 🤔 Expected Behavior?

The `<Form>` should accept `<form>` props (https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement)

### 😯 Current Behavior

TypeScript is showing an error if we're using `id` attribute because we don't have an extends of `HTMLFormElement` on the following type: https://github.com/adobe/react-spectrum/blob/87dbb748cbfd9bd6f53183221b8e2ef96defbfc3/packages/%40react-types/form/src/index.d.ts#L16-L68

https://github.com/adobe/react-spectrum/blob/87dbb748cbfd9bd6f53183221b8e2ef96defbfc3/packages/react-aria-components/src/Form.tsx#L23-L27

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/agitated-artem-km8c5t-km8c5t

### Version

1.0.1

### What browsers are you seeing the problem on?

Other

### If other, please specify.

TypeScript types

### What operating system are you using?

Ubuntu 23.10

**Comment by LFDanLu** [comment]
For `id` looks like we just forgot to extend from https://github.com/adobe/react-spectrum/blob/87dbb748cbfd9bd6f53183221b8e2ef96defbfc3/packages/%40react-types/shared/src/dom.d.ts#L58-L63.

**Comment by LFDanLu** [comment]
@Akshithpottigari not sure if this is a question directed to myself or @Yovach :sweat_smile:. Are you asking for clarification on what the fix should be?

**Comment by LFDanLu** [comment]
Go for it! https://github.com/adobe/react-spectrum/blob/b5974ad1ccf2abc984c5cc6664b3c2d03de36768/packages/react-aria-components/src/utils.tsx#L72-L75 could probably just extend `SharedDOMProps`

**Comment by Yovach** [comment]
> Hey @Yovach, the issue is resolved!

Hey, thanks to both of you! :)
