### ISSUE TITLE
Button inside MenuTrigger keeps data-pressed="true"

### ISSUE THREAD

**Issue by janvorwerk** [adobe/react-spectrum#5770]
### Provide a general summary of the issue here

When I use a button as menu trigger of a controlled popover: the button state keeps the `data-pressed="true"` after I stop pressing the button.

If the popover is not being controlled, the state of the button remains pressed while the popover is open, but it vanishes as soon as I click outside of the menu to have it close. This can be seen by removing these two lines from the sandbox.
```jsx
        isOpen={isMenuOpen}
        onOpenChange={setMenuOpen}
``` 

### 🤔 Expected Behavior?

The button state should clear `data-pressed="true"` after I stop pressing the button.

### 😯 Current Behavior

The button state keeps `data-pressed="true"` after I stop pressing the button.

### 🔦 Context

I have a search box with a menu allowing to add filters (ie search conditions).

The last item is a "clear all" that removes all filters (which is a hack BTW because the "multiple" selection only applies to the whole menu at this point - see #1621)
But that's why it's a controlled popover: when I add filters, the menu remains open, but when I clear them, I want the popover to close.

Follow up of discussion #5765

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/rac-button-pressed-issue-8nk7z3

### Version

react-aria-components 1.0.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

macOS 14.2.1

**Comment by devongovett** [comment]
You should move the `isOpen` and `onOpenChange` from the `Popover` to the `MenuTrigger`. What's happening is that the MenuTrigger has its own state about whether the menu is open, but you're overriding it further down the tree so there is a mismatch. Moving these props to the MenuTrigger should fix the issue.

**Comment by janvorwerk** [comment]
Indeed!! This works as a charm! 🚀

My bad... Thanks a lot for your support 🙏

I guess I can close this issue now?
