### ISSUE TITLE
include enterKeyHint to 

### ISSUE THREAD

**Issue by wigsnes** [adobe/react-spectrum#5771]
### Provide a general summary of the feature here

include enterKeyHint to the AriaTextFieldOptions<'input'>

### 🤔 Expected Behavior?

Want to be able to use enterKeyHint on my inputs

### 😯 Current Behavior

I am not able to use enterKeyHint on my inputs.

### 🔦 Context

I feel like this is self explanatory so I do not need to go into any more details. This is probably a easy fix.

**Comment by LFDanLu** [comment]
You could add that attribute to your input after spreading the props from `useTextField` right? Typically we've only added these kind of pass through attributes to `useTextField` via https://github.com/adobe/react-spectrum/blob/b5974ad1ccf2abc984c5cc6664b3c2d03de36768/packages/%40react-types/shared/src/dom.d.ts#L133-L135 if they were used in other input aria hooks (useNumberField, useDateSegement, etc)

**Comment by wigsnes** [comment]
Yes that was what I ended up doing, I just assumed react-aria would include this. If this is not something that will be supported then we can close this issue.

**Comment by LFDanLu** [comment]
For now I'm inclined to close this until we need it in our hooks, but will reopen it then thanks!
