### ISSUE TITLE
Button inside of Select open few popovers at the same time

### ISSUE THREAD

**Issue by dvasyliev** [adobe/react-spectrum#5784]
### Provide a general summary of the issue here

I need to have a contextual hint with a popover near the label for the select field. When I implement it and click on a hint button, I see 2 popovers opened, one for the hint, the second for select.

### 🤔 Expected Behavior?

- When I click on a hint button, I see only a hint popover opened
- The hint button has a different id from the select button
- The hint button doesn't have aria-labeledby and aria-describedby attributes or have the correct ones (I'm not an expert in accessibility)

### 😯 Current Behavior

- When I click on a hint button, I see 2 popovers opened, one for the hint, the second for select
- The hint button has the same id as the select button
- The hint button has wrong id's in the aria-labeledby and aria-describedby

- The same behaviour I noticed for the DatePicker
- Also when I use a hint with a DateField, after clicking on a hint button and closing a popover, the focus moves into DateField and I see the first segment active

### 💁 Possible Solution

Wrap Button for select and Popover into DialogTrigger, then the issue is gone, but the CSS variable `var(--trigger-width)` was reset for select Popover, and it has a bigger width than the select Button.

### 🔦 Context

I need to have a contextual hint with a popover near the label for the select field. 

### 🖥️ Steps to Reproduce

I created the Select component following the [example](https://react-spectrum.adobe.com/react-aria/Select.html#example) in the documentation of react-aria-components. Then added DialogTrigger with a Button and a Popover inside of the Label component.

Repo: https://github.com/dvasyliev/react-aria-components-popover-issue
GitHub page with demo: https://dvasyliev.github.io/react-aria-components-popover-issue/?path=/story/selectwithhint--default

### Version

react-aria-components@1.0.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

Doccle

**Comment by dvasyliev** [comment]
The issue was gone when I used `useButton` hook from `react-aria` instead of `Button` component from `react-aria-components`. So the problem in the `Button` component.

**Comment by snowystinger** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#interactive_content
We are working as expected. Please move the button outside of the control.

**Comment by dvasyliev** [comment]
Even if I move it outside of `label` it has the same behaviour

**Comment by snowystinger** [comment]
Ah, I see, I suspect that the context is leaking where it shouldn't. You could try clearing the context. See possible context values here https://react-spectrum.adobe.com/react-aria/Select.html#custom-children
Should be able to just wrap your DialogTrigger in the same Provider from https://github.com/adobe/react-spectrum/blob/560f05005aa5dbc67f765573a52c5d4665b90f05/packages/react-aria-components/src/Select.tsx#L142
and pass it a blank values.

Let us know if that works

**Comment by henkkasoft** [comment]
I just encountered the same problem with react-aria-components 1.4.0.
I am not understand the suggestions here, what should be done?

My component structure is like:
```
<Select>
  <Label>
    <span>{label}</span>
    <DialogTrigger>
      <Button>
        ...my info icon
      <Button>
      <Popover>
        <OverlayArrow />
        <Dialog />
      </Popover>
    </DialogTrigger>
  </Label>
  <Button>
    <SelectValue />
  </Button>
  <Popover>
    <ListBox />
  </Popover>
</Select>

```
After label-text I need to have info-icon button to trigger info dialog popover.
Should I not use this kind of component structure?
And can I do something to prevent the ListBox popover to open when info-icon button is pressed?

**Comment by snowystinger** [comment]
This is an invalid structure. You cannot have a button inside your label. Please move it to a structure like this:
```
<Select>
  <div class="label-wrapper">
  <Label>
    <span>{label}</span>
  </Label>
  <Provider clear the button context, possibly the Popover context, and any others that the Select uses, see https://react-spectrum.adobe.com/react-aria/Select.html#custom-children so that they don't leak into the DialogTrigger>
    <DialogTrigger>
      <Button>
        ...my info icon
      <Button>
      <Popover>
        <OverlayArrow />
        <Dialog />
      </Popover>
    </DialogTrigger>
  </Provider>
  </div>
  <Button>
    <SelectValue />
  </Button>
  <Popover>
    <ListBox />
  </Popover>
</Select>
```
Which is also demonstrated in the original authors github link.

I'm going to close this Issue as things are working as expected. You need to clear out the conflicting contexts.
If you have further questions, let us know. We can reopen if there is a bug present, but I don't see one right now.

**Comment by henkkasoft** [comment]
Now I understand better. Thank you @snowystinger  very much for helping me out.
I can confirm that it was enough to fix this problem by setting blank values for ButtonContext.Provider.

like this:

```
<Select>
  <div class="label-wrapper">
  <Label>
    <span>{label}</span>
  </Label>
  <ButtonContext.Provider value={{}}>
    <DialogTrigger>
      <Button>
        ...my info icon
      <Button>
      <Popover>
        <OverlayArrow />
        <Dialog />
      </Popover>
    </DialogTrigger>
  </ButtonContext.Provider>
  </div>
  <Button>
    <SelectValue />
  </Button>
  <Popover>
    <ListBox />
  </Popover>
</Select>
```

Actually my linter was moaning with value={{}} 

> The object passed as the value prop to the Context provider (at line 21) changes every render. To fix this consider wrapping it in a useMemo hook

But using variable it was happy
```
const buttonContextProviderEmptyValue = {};

...value={buttonContextProviderEmptyValue} 
```
