### ISSUE TITLE
TableView Resize Does not Recompute Width

### ISSUE THREAD

**Issue by MrDesjardins** [adobe/react-spectrum#5786]
### Provide a general summary of the issue here

There is an unwanted behavior where the TableView does not resize with the browser. The problem is limited when the browser reduces in width. When the browser increases in width the TableView is responsive and grows.

Looking at the generated HTML, it looks like widths are dynamically applied to some DOM. However, it does not happen when reducing the browser.

Here is a full [CodeSandbox](https://codesandbox.io/p/sandbox/spectrumtableviewwidthissue-h5xzrg?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls2clvv90006396gx52aejgs%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls2clvv90002396gws7f1xqk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls2clvv90003396geiz5rr4j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls2clvv90005396g8l66tvsf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B46.104801264368945%252C53.895198735631055%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls2clvv90002396gws7f1xqk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls2clvv90001396goslih7a9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftsconfig.json%2522%257D%255D%252C%2522id%2522%253A%2522cls2clvv90002396gws7f1xqk%2522%252C%2522activeTabId%2522%253A%2522cls2clvv90001396goslih7a9%2522%257D%252C%2522cls2clvv90005396g8l66tvsf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls2clvv90004396gpf5u8kck%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls2clvv90005396g8l66tvsf%2522%252C%2522activeTabId%2522%253A%2522cls2clvv90004396gpf5u8kck%2522%257D%252C%2522cls2clvv90003396geiz5rr4j%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls2clvv90003396geiz5rr4j%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A23.40248962655602%257D)

But in a nutshell, the issue appears when you have flex display:

```
<Provider theme={defaultTheme}>
      <div className="App">
        <div className="side">Menu Side</div>
        <div className="content">
          <div classname="content-top">Content Top</div>
          <div classname="content-bottom">
            Content Bottom
            <TableView overflowMode="wrap" selectionMode="none">
              <TableHeader>
                <Column>Date</Column>
                <Column>Name</Column>
                <Column>Region</Column>
                <Column align="end">Status</Column>
              </TableHeader>
              <TableBody>
                <Row>
                  <Cell>todo</Cell>
                  <Cell>todo</Cell>
                  <Cell>todo</Cell>
                  <Cell>todo</Cell>
                </Row>
                <Row>
                  <Cell>todo</Cell>
                  <Cell>todo</Cell>
                  <Cell>todo</Cell>
                  <Cell>todo</Cell>
                </Row>
                <Row>
                  <Cell>todo</Cell>
                  <Cell>todo</Cell>
                  <Cell>todo</Cell>
                  <Cell>todo</Cell>
                </Row>
                <Row>
                  <Cell>todo</Cell>
                  <Cell>todo</Cell>
                  <Cell>todo</Cell>
                  <Cell>todo</Cell>
                </Row>
              </TableBody>
            </TableView>
          </div>
        </div>
      </div>
    </Provider>
```

With the css:
```
.App {
  background-color: aqua;
  display: flex;
  height: 100vh;
  width: 100vw;
}

body {
  padding: 0;
  margin: 0;
}
.side {
  background-color: blue;
  width: 200px;
  flex: 0 0 200px;
}

.content {
  flex: 1;
  display: flex;
  flex-direction: column;
}

.content-top {
}

.content-bottom {
  flex: 1 0 auto;
}

```

You can fix the issue by adding to the content `overflow: hidden;`

Issue:
[Video](https://github.com/adobe/react-spectrum/assets/1014796/a2690aa7-4f82-4769-a290-ac496e5d5d26)

### 🤔 Expected Behavior?

I expect the TableView to be responsive inside a div with flex without needing to apply any custom css to fix the responsiveness when reducing the width of the browser.

### 😯 Current Behavior

It does not reduce the size of the grid when the browser is reduced in width.

### 💁 Possible Solution

Currently, adding to the parent container `overflow: hidden;` fix the issue. 

### 🖥️ Steps to Reproduce

Here is a [CodeSandbox](https://codesandbox.io/p/sandbox/spectrumtableviewwidthissue-h5xzrg?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls2clvv90006396gx52aejgs%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls2clvv90002396gws7f1xqk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls2clvv90003396geiz5rr4j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls2clvv90005396g8l66tvsf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B46.104801264368945%252C53.895198735631055%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls2clvv90002396gws7f1xqk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls2clvv90001396goslih7a9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftsconfig.json%2522%257D%255D%252C%2522id%2522%253A%2522cls2clvv90002396gws7f1xqk%2522%252C%2522activeTabId%2522%253A%2522cls2clvv90001396goslih7a9%2522%257D%252C%2522cls2clvv90005396g8l66tvsf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls2clvv90004396gpf5u8kck%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls2clvv90005396g8l66tvsf%2522%252C%2522activeTabId%2522%253A%2522cls2clvv90004396gpf5u8kck%2522%257D%252C%2522cls2clvv90003396geiz5rr4j%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls2clvv90003396geiz5rr4j%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A23.40248962655602%257D)

### Version

3.33.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

Adobe Express

**Comment by snowystinger** [comment]
This actually has to do with how flex works, you just need to change content's CSS to have
```
min-width: 0;
```
This will allow it to shrink and then the table will resize to fit. I'll close this as it's working when the CSS is changed.

The internet can explain why flex works this way better than I can. https://stackoverflow.com/questions/36247140/why-dont-flex-items-shrink-past-content-size
