### ISSUE TITLE
Checkbox and CheckboxGroup have no blur event support.

### ISSUE THREAD

**Issue by adriantrunzo** [adobe/react-spectrum#5794]
### Provide a general summary of the issue here

The Checkbox and CheckboxGroup components from react-aria-components do not fire a blur event or do not support an onBlur handler. onBlur works as expected with RadioGroup.

### 🤔 Expected Behavior?

An `onBlur` handler to Checkbox or CheckboxGroup is fired when the components lose focus, just like for RadioGroup.

### 😯 Current Behavior

The onBlur handler is never fired.

### 🔦 Context

I am trying to integrate Checkbox and CheckboxGroup with React Hook Form (via Controller), but the onBlur handlers are never called, which messes with RHF form validation.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/awesome-orla-6hrtw9-6hrtw9

Tab through all of the form elements and notice that only the blur count for the radio group will increase as expected. Alternatively, click a radio button and then a checkbox, you'll see the radio group blur count increase. Click a checkbox and then a radio button, you'll see that the checkbox blur count never increases.

Probably related, the onFocusChange method of Checkbox doesn't seem to work either.

https://github.com/adobe/react-spectrum/assets/1218900/110c7133-9b3f-443f-90ee-c6b4951c02b5

### Version

1.0.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

mac OS 14.3

**Comment by LFDanLu** [comment]
Thanks for catching this. I think it is perfectly reasonable to add `onBlur` support to CheckboxGroup, similar to how it was included via https://github.com/adobe/react-spectrum/issues/5332. As for `onBlur`/`onFocusChange` not being called for the Checkbox, I believe this is an oversight by us, https://github.com/adobe/react-spectrum/blob/d766af60ce5252ecd95c62645ae881c7fb9174ab/packages/react-aria-components/src/Checkbox.tsx#L229 should probably have `mergeProps` to merge the blur handlers
