### ISSUE TITLE
`<Switch />` does not trigger focus events when focused

### ISSUE THREAD

**Issue by alexcarpenter** [adobe/react-spectrum#5822]
### Provide a general summary of the issue here

The `<Switch/>` component from 'react-aria-component' does not trigger `onFocus` or `onFocusChange` events.

It also seems as though the input does not receive focus even when the data-focused attribute changes. This is problematic because when placed in a scrollable container, the focused switch does not scroll into view.

### 🤔 Expected Behavior?

The input receives focus and calls `onFocus` and `onFocusChange` events as well as scroll into view when focused, this seems to be the native behavior of input type checkboxes

### 😯 Current Behavior

focus events are not triggered https://codesandbox.io/p/sandbox/nameless-shape-s6j365?file=%2Fsrc%2FApp.js%3A8%2C49

and when placed within a scrollable container the switch that is focused does not scroll into view https://codesandbox.io/p/sandbox/nameless-shape-s6j365?file=%2Fsrc%2Fstyles.css%3A24%2C22

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/goofy-dhawan-wzlv73?file=%2Fsrc%2FApp.js%3A8%2C1

### Version

1.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you using?

Mac

**Comment by snowystinger** [comment]
Looks like we accidentally overwrite the event handlers here
https://github.com/adobe/react-spectrum/blob/d75ba60c8a4de2e1396c9808785a92f8c6e049c6/packages/react-aria-components/src/Switch.tsx#L113
we should probably be merging those two spreads
