### ISSUE TITLE
Month displayed in DatePicker and DateRangePicker has the placeholder text still taking space when valorized

### ISSUE THREAD

**Issue by Giordano-Novomatic** [adobe/react-spectrum#5831]
### Provide a general summary of the issue here

The Segment containing the month placeholder text still takes space when the date field is not empty.

![image](https://github.com/adobe/react-spectrum/assets/151722932/b39b73a9-0c57-4c70-ba35-2e11fd1dbc53)

### 🤔 Expected Behavior?

The correct display of that field should look like this:

![image](https://github.com/adobe/react-spectrum/assets/151722932/8ef825fa-5503-4392-812a-9f7bf25f81dd)

### 😯 Current Behavior

There's a white space (marked in red in the screenshot below):

![image](https://github.com/adobe/react-spectrum/assets/151722932/b39b73a9-0c57-4c70-ba35-2e11fd1dbc53)

### 💁 Possible Solution

Maybe said element should get a display: none; when the filed is not empty.

### 🖥️ Steps to Reproduce

Create a DatePicker or a DateRangePicker and select a date to fill it's value.

### Version

3.32.2

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

it's not a browser specific issue

### What operating system are you using?

Windows 11

**Comment by reidbarber** [comment]
Does the discussion in https://github.com/adobe/react-spectrum/issues/3355 offer an explanation for what you're seeing?

**Comment by Giordano-Novomatic** [comment]
> Does the discussion in #3355 offer an explanation for what you're seeing?

Yes I'd say it's the same issue.
