### ISSUE TITLE
Checkbox mouse click does not clear invalid state

### ISSUE THREAD

**Issue by smozely** [adobe/react-spectrum#5836]
### Provide a general summary of the issue here

When the Checkbox in in Invalid state, using the mouse to select the checkbox will not clear the invalid state, while using the keyboard will.

This then prevents the form being re-submitted.

### 🤔 Expected Behavior?

The invalid state from the checkbox should be cleared when selected with the mouse

### 😯 Current Behavior

The invalid state is not being cleared which looks wrong. Also because of the way we are using custom validation its preventing the form submit.

### 💁 Possible Solution

It should work the same as with the keyboard

### 🔦 Context

Using a checkbox for a "Accept Terms of use" field on a registration form. So wanting to force the Checkbox to be checked before proceeding. 

### 🖥️ Steps to Reproduce

Can see it here,

[Sandbox](https://codesandbox.io/p/sandbox/tender-violet-68x378?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clscg0n1200062e65xy29fmzw%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clscg0n1200022e65pqssww0z%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clscg0n1200032e65vmy18eao%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clscg0n1200052e656mwyilo7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clscg0n1200022e65pqssww0z%2522%253A%257B%2522id%2522%253A%2522clscg0n1200022e65pqssww0z%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clscg0n1200052e656mwyilo7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clscg0n1200042e655iziiuqh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%253F%2522%257D%255D%252C%2522id%2522%253A%2522clscg0n1200052e656mwyilo7%2522%252C%2522activeTabId%2522%253A%2522clscg0n1200042e655iziiuqh%2522%257D%252C%2522clscg0n1200032e65vmy18eao%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clscg0n1200032e65vmy18eao%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Styles are a bit iffy but
1, Click Submit - Will show that the checkbox unselected and isInvalid
2, Click the "Click Me" with the mouse - Will show that the checkbox selected and isInvalid
3, Use the keybord to change the "Click Me" - Will show the checkbox select and valid

In this example, you'll be able to submit the form even at step 2. In our case we can't because we are using custom validation ... but pretty sure resolving this issue will also fix our case

### Version

1.0.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Mac

**Comment by snowystinger** [comment]
I think this is a dupe of https://github.com/adobe/react-spectrum/issues/5693

**Comment by smozely** [comment]
Ah thanks @snowystinger yeah I guess I my searching-fu failed there (looking for Checkbox rather than Checkbox group)

closing as dup
