### ISSUE TITLE
Documentation of "useTextField" from React-Aria is not up to date

### ISSUE THREAD

**Issue by MaxAuMax** [adobe/react-spectrum#5838]
### Provide a general summary of the issue here

[Sorry for english mistakes, i'm french]

I am currently doing React components using React-Aria. I was doing a TextField with the [useTextField](https://github.com/adobe/react-spectrum/tree/main/packages/@react-aria/textfield) hook but it seems that his [documentation](https://react-spectrum.adobe.com/react-aria/useTextField.html) is not up to date ! In the code example, "isInvalid" and "validationErrors" are two props that can be used but appears to not exist anymore !

### 🤔 Expected Behavior?

I should be able to get those props to handle the error cases when a query is sent.
If i'm just doing something wrong, please let me know.
![image](https://github.com/adobe/react-spectrum/assets/91740535/38bded62-6046-4806-b950-d78b62f85ac8)

### 😯 Current Behavior

I am getting two errors, the same, for "isInvalid" and "validationErrors"
> Property 'isInvalid' does not exist on type 'TextFieldAria<"input">'.

> Property 'validationErrors' does not exist on type 'TextFieldAria<"input">'

![image](https://github.com/adobe/react-spectrum/assets/91740535/d26c5e02-c0f7-4347-a832-5554672e4d51)

### 💁 Possible Solution

Update the documentation 😅 

### 🔦 Context

No specific context.

### 🖥️ Steps to Reproduce

- Install react aria
- Create a file.tsx
- Paste the example code from the documentation
- ERROR 🟥 

### Version

react-aria: ^3.28.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### What operating system are you using?

Linux, Xubuntu

**Comment by yihuiliao** [comment]
Hmm interesting...I’m not sure what’s going on since `isInvalid` and `validationErrors` are getting returned by `useTextField` in the source code
https://github.com/adobe/react-spectrum/blob/3973a772cbc82ae0c25ab41fd75c3dba57794a6e/packages/%40react-aria/textfield/src/useTextField.ts#L212-L213

I believe `isInvalid` and `validationError` were added in v3.30 in this PR(https://github.com/adobe/react-spectrum/pull/5288) so I’d make sure the package is up to date but otherwise that’s strange

**Comment by MaxAuMax** [comment]
> Hmm interesting...I’m not sure what’s going on since `isInvalid` and `validationErrors` are getting returned by `useTextField` in the source code
> 
> https://github.com/adobe/react-spectrum/blob/3973a772cbc82ae0c25ab41fd75c3dba57794a6e/packages/%40react-aria/textfield/src/useTextField.ts#L212-L213
> 
> I believe `isInvalid` and `validationError` were added in v3.30 in this PR(#5288) so I’d make sure the package is up to date but otherwise that’s strange

God damn it, the easiest thing to do is check the version and update if needed, and i didn't do it !
In fact, i was in 3.28 and just needed to go to the latest version of Aria .....
Thanks @yihuiliao 🙄
