### ISSUE TITLE
DateInput splits up two digit numbers

### ISSUE THREAD

**Issue by thorbde** [adobe/react-spectrum#5846]
### Provide a general summary of the issue here

There's an edge case where the Days segment treats valid, double digit values as two separate values, and thus splits it into days and months. 

### 🤔 Expected Behavior?

Should input 12 in the days segment

### 😯 Current Behavior

 Currently splits into 01 in the days segment and 02 in the months segment

### 💁 Possible Solution

Haven't had the time to check the source code

### 🔦 Context

https://github.com/adobe/react-spectrum/assets/13640875/2df03995-ccf1-45b2-b517-78975b9086c2

### 🖥️ Steps to Reproduce

1. Pick a date, either in the popover or with the dateinput field
2. Focus the Day segment
3. Delete the currently selected day
4. Type in a two-digit, valid day, like 12 in the example

### Version

1.0.0-rc.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS Sonoma 14.3

**Comment by ryo-manba** [comment]
@thorbde 
This should be fixed once the [PR](https://github.com/adobe/react-spectrum/pull/5715) is merged!
For the cause, check here: https://github.com/adobe/react-spectrum/issues/5223#issuecomment-1898674803

**Comment by ryo-manba** [comment]
Hey @snowystinger,
The PR https://github.com/adobe/react-spectrum/pull/5715 is merged, so we might close this issue too!

**Comment by snowystinger** [comment]
@ryo-manba thanks, I can't reproduce in the docs. Closing

**Comment by ilbrando** [comment]
Is the documentation also updated with this? I can reproduce it in the [examples in the documentation](https://react-spectrum.adobe.com/react-aria/DateField.html). My `Intl.DateTimeFormat().resolvedOptions().locale` is `"da"`.

**Comment by snowystinger** [comment]
@ilbrando I've changed my computer (MacOS) and chrome browser to "da", but I'm unable to reproduce. What browser/OS are you on? are the steps the same as outlined in the description?

**Comment by ilbrando** [comment]
I'm on MacOS and Chrome. You can see this little [video](https://app.screencast.com/PXCsWA20G6Aks) where I first enter "22" which works and then "31" which becomes "1".

**Comment by yihuiliao** [comment]
@ilbrando I think what you're encountering is a separate issue https://github.com/adobe/react-spectrum/issues/3256
