### ISSUE TITLE
Picker component doesn't effectively use the id or name attribute

### ISSUE THREAD

**Issue by Giordano-Novomatic** [adobe/react-spectrum#5853]
### Provide a general summary of the issue here

When using a Picker component you get a warning in the Chrome dev tools saying that said element doesn't have a corresponding id or name attribute.

![image](https://github.com/adobe/react-spectrum/assets/151722932/51c25e33-f0e8-452d-a8f6-61a92efa9dbe)

### 🤔 Expected Behavior?

The picker should pass the input element a name attribute.

### 😯 Current Behavior

Currently you get a warning cause the element does not have a name or id.

### 🖥️ Steps to Reproduce

Create a Picker and check the Chrome dev tools (Issues balloon on the top-right).

### Version

3.32.2

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 11

**Comment by reidbarber** [comment]
Picker supports both the `id` and `name` props. Are you passing these in? I think the warning is just because you're using these within a `<form>` and not including at least one of them. These won't get added automatically.

**Comment by Giordano-Novomatic** [comment]
> Picker supports both the `id` and `name` props. Are you passing these in? I think the warning is just because you're using Picker within a `<form>` and not including at least one of those props. These won't get added automatically.

Yes I'm passing a name (and I also tried to pass an id but it doesn't change the outcome):
![image](https://github.com/adobe/react-spectrum/assets/151722932/630ceb65-56a1-4b89-9842-81d0fa9e7462)

**Comment by reidbarber** [comment]
I'm seeing both of them here: https://codesandbox.io/p/devbox/rsp-picker-glmpm5

`id` is added to the outer-most element, and `name` is added to the hidden `select` element.

**Comment by reidbarber** [comment]
Update it, should be public now.

**Comment by Giordano-Novomatic** [comment]
> Update it, should be public now.

Yeah i can see it now but it has the same warning i was reporting, the input is missing the name attribute. The component doesn't pass the attribute to the actual html element apparently:
`<input type="text" tabindex="0" style="font-size: 16px;">`

**Comment by reidbarber** [comment]
Oh, that is referring to an input element that is used in addition to the hidden select. It is used to marshal focus to the button. You can read more about why it is needed here:

https://github.com/adobe/react-spectrum/blob/c11afb257a8bc409ed23272a167372005adf4bcc/packages/%40react-aria/select/src/HiddenSelect.tsx#L69-L86

You can ignore that message since the input isn't actually part of the form.
