### ISSUE TITLE
MenuItem key is not set as provided

### ISSUE THREAD

**Issue by nicosammito** [adobe/react-spectrum#5854]
### Provide a general summary of the issue here

If I provide a key to the Item component inside a menu the key is for whatever reason extended by a slash and the repeated index.

Key provided inside code
![Bildschirmfoto 2024-02-12 um 16 21 57](https://github.com/adobe/react-spectrum/assets/60352747/2f4a6022-b5a1-4a71-bd8a-6dd843f001d7)

Key generated by aria:
![Bildschirmfoto 2024-02-12 um 16 22 17](https://github.com/adobe/react-spectrum/assets/60352747/89411c86-8d4b-4384-ab18-8142b18f91e8)

### 🤔 Expected Behavior?

The same key as provided

### 😯 Current Behavior

Key is extended by a slash and the index of menu item

### 🖥️ Steps to Reproduce

Followed the documentation from Aria:

https://react-spectrum.adobe.com/react-aria/useMenu.html

### Version

3.31.1

### What browsers are you seeing the problem on?

Safari

### What operating system are you using?

MacOS

**Comment by reidbarber** [comment]
The `data-key` attribute is used internally and isn't meant to be a public or documented API (it could change across versions). It won't necessarily match the id/key passed in. I would recommend adding a new data attribute that you could map your id to in a more predictable manner if you need to.

**Comment by nicosammito** [comment]
> The `data-key` attribute is used internally and isn't meant to be a public or documented API (it could change across versions). It won't necessarily match the id/key passed in. I would recommend adding a new data attribute that you could map your id to in a more predictable manner if you need to.

The problem here is that not only the `data-key` attributed matches this weird pattern, also the returned key if I add the onSelectionChange handler.

**Comment by nicosammito** [comment]
> The `data-key` attribute is used internally and isn't meant to be a public or documented API (it could change across versions). It won't necessarily match the id/key passed in. I would recommend adding a new data attribute that you could map your id to in a more predictable manner if you need to.

![Bildschirmfoto 2024-02-12 um 20 25 00](https://github.com/adobe/react-spectrum/assets/60352747/91bb990c-f30d-40f7-a06c-e84bc77f47f0)

As you see the key itself gets extended inside the Item component

**Comment by nicosammito** [comment]
Solved this issue by removing the `React.Children.map` over all menu Items. For whatever reason is React manipulating the key prop if you use `React.Children.anything`
