### ISSUE TITLE
useTextField hook in react-aria causes TypeError when ref is not provided when using forwardRef

### ISSUE THREAD

**Issue by MarekBodingerBA** [adobe/react-spectrum#5855]
### Provide a general summary of the issue here

After an update of react-aria from `3.29.0` to `3.31.0` a runtime error occurs, when component that forwards its ref uses useTextField but ref is not provided to the component that forwards it. Previously it worked. 

It is very probably caused by this change which accesses the `current` property of undefined `ref`:
https://github.com/adobe/react-spectrum/commit/0ee6a00d9d5485f644526b191faa97036a554563#diff-d45d481a028632c7e3b8d7238d268bd29e01a39e39f2a2bbcbd481991de6f46c

### 🤔 Expected Behavior?

Components utilizing the `useTextField` hook from react-aria should not require a ref to be passed in. They should render without errors even when no ref is provided by the parent component.

### 😯 Current Behavior

When a component that uses the useTextField hook from react-aria is rendered without a provided ref, a TypeError is thrown:

TypeError
Cannot read properties of null (reading 'current')

This occurs because the useTextField hook expects a non-null ref object but does not handle the case where it is not provided.

### 💁 Possible Solution

Use `ref?.current` in `useTextField`.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/react-aria-forwardref-usetextfield-bug-jhcnxl

### Version

react-aria@3.31.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### What operating system are you using?

Windows

**Comment by snowystinger** [comment]
`useTextfield` has always required a ref https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/textfield/src/useTextField.ts#L115

Note, this ref should always be for the input element https://github.com/adobe/react-spectrum/blob/ed6fb79f9a413d68bbc8821c1d7bc4b6311e45a3/packages/react-aria-components/src/TextField.tsx#L45

You can either merge the forwarded ref from your component with the input ref, or you can put the forwarded ref on the outer div or wherever else you'd like.
See previous link for an example of the two going to different places
Or you could merge them like this https://github.com/adobe/react-spectrum/blob/ed6fb79f9a413d68bbc8821c1d7bc4b6311e45a3/packages/%40react-aria/utils/src/mergeRefs.ts#L18
Or you can just use it as a fallback
```
const ForwardedInput = forwardRef<HTMLInputElement, AriaTextFieldProps>(
  (props, ref) => {
    let fallbackRef = useRef();
    ref = ref ?? fallbackRef;
    let { ...textFieldProps } = props;
    let { inputProps } = useTextField(props, ref);

    return (
      <div>
        <input {...inputProps} ref={ref} />
      </div>
    );
  }
);
```

**Comment by MarekBodingerBA** [comment]
Thank you, it seems that `useObjectRef` is the right solution?
https://github.com/adobe/react-spectrum/pull/2293

Then I propose, wouldn't it make sense to check for `ref` if it's defined in all hooks (like checks [here](https://github.com/adobe/react-spectrum/blob/5dac6d296cfcc3d69ed8290ceffa973506d19a1a/packages/%40react-stately/datepicker/src/useDateFieldState.ts#L165) or [here](https://github.com/adobe/react-spectrum/blob/5dac6d296cfcc3d69ed8290ceffa973506d19a1a/packages/%40react-spectrum/dialog/src/DialogContainer.tsx#L35))? The current behavior is inconsistent, the `useTextField` hook only fails because there's an effect that is called immediately after hook mount, which is not true for other hooks. Of course, that's up for discussion when to throw an error or when to rely on type safety, and honestly I don't know what's the best and what are the guidelines for this repository.

**Comment by snowystinger** [comment]
Yep, `useObjectRef` is a good way to go.

We do rely on types in most cases in order to avoid extra code which would increase the size of our package. Sometimes we do have checks, but those tend to be cases where the resulting error would be "hard" to figure out otherwise. This one is fairly straightforward, I feel like, with the default error.

I'll go ahead and close this issue for the time being.
