### ISSUE TITLE
[RAC] `SubmenuTrigger` throws inside a `Section`

### ISSUE THREAD

**Issue by amitdahan** [adobe/react-spectrum#5858]
### Provide a general summary of the issue here

I've been following progress of `Submenu` support in RAC (#5648) and excited it was very recently merged! 🎉 

After trying it, I noticed though it's not yet supported when used together within `Section`s.

### 🤔 Expected Behavior?

`SubmenuTrigger` can be a direct child of `Section`.

### 😯 Current Behavior

An error is thrown:

```
Unsupported element type in Section: submenutrigger
```

![image](https://github.com/adobe/react-spectrum/assets/9748762/7f3de932-4463-42b4-865e-a9d518c6d908)

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/great-goldstine-rzj4sq

Button on the left opens fine (no `Section` is used)
Button on the right throws immediately (`SubmenuTrigger` is nested within a `Section`)

### Version

1.0.2-nightly.4451

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS 14.3

**Comment by reidbarber** [comment]
Thanks for catching this! Should be fixed now.
