### ISSUE TITLE
[Slider]: Warning: Received NaN for the `max` attribute. If this is expected, cast the value to a string.

### ISSUE THREAD

**Issue by konsalex** [adobe/react-spectrum#5859]
### Provide a general summary of the issue here

I receive this while testing with RTL. Received it for multiple attributes like `value`.

Tried to patch the value like:
```ts
const value =
    mergedProps.value || mergedProps.value === 0 ? mergedProps.value : '';
```

But then `max` attribute is `NaN`.

The input is like the one provided in the docs:

```jsx
<VisuallyHidden>
    <input ref={inputRef} {...mergedProps} value={value} />
</VisuallyHidden>
```

### 🤔 Expected Behavior?

No warnings raised

### 😯 Current Behavior

Some error messages:

`Warning: Received NaN for the `max` attribute. If this is expected, cast the value to a string.`
`Warning: Received NaN for the `value` attribute. If this is expected, cast the value to a string.`

### 💁 Possible Solution

Cast this value inside the `useSliderThumb` or when is appropriate. Found a similar issue here: https://github.com/adobe/react-spectrum/issues/5499

### 🔦 Context

Create a custom slider component for Neo4j's component library based on the Slider primitives (`useSlider`, `useSliderThumb`, `useSliderState`).

### 🖥️ Steps to Reproduce

The example from the docs page is sufficient for this

### Version

3.31.0

### What browsers are you seeing the problem on?

Other

### If other, please specify.

JS-dom

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

Neo4j - Design System

**Comment by snowystinger** [comment]
Closing as https://github.com/adobe/react-spectrum/pull/5861#issuecomment-2172109984
