### ISSUE TITLE
Areas not visible due to `clip-path` are not handled correctly when moving pressed pointer off of, or back onto, element

### ISSUE THREAD

**Issue by jeyj0** [adobe/react-spectrum#5870]
### Provide a general summary of the issue here

When using `clip-path` on an element enhanced using `usePress`, the non-visible parts of the element still result in press events from react-aria, when moving off of the element while continuing to press, and moving back onto the element while continuing to press.

Another way to word it (closer to the cause of the issue, I think):

When using `usePress` for an element with `clip-path`, once the first press on the element is registered, the element's bounding box is used to determine events instead of the area visible after applying the `clip-path`.

The spec (https://www.w3.org/TR/css-masking-1/#clipping-paths) says the following:

> By default, [pointer-events](https://drafts.csswg.org/css-ui-4/#propdef-pointer-events) must not be dispatched on the clipped-out (non-visible) regions of a shape. For example, an element with a dimension of 10px to 10px which is clipped to a circle with a radius of 5px will not receive click events outside the [clipping region](https://drafts.fxtf.org/css-masking/#clipping-region).

### 🤔 Expected Behavior?

When moving a pressed curser off the visible area of an element into the non-visible, clipped area of the element, react-aria considers the element to be pressed.

### 😯 Current Behavior

When moving a pressed curser off the visible area of an element into the non-visible, clipped area of the element, react-aria considers the element to **not** be pressed.

### 💁 Possible Solution

I think the only possible solution is avoid doing any [bounding box calculations](https://github.com/adobe/react-spectrum/blob/5b9e89eeaa52c5203003eecf3c59a66a0c73e2d9/packages/%40react-aria/interactions/src/usePress.ts#L865), and instead solely rely on browser events. I don't know how feasible this is though, unfortunately.

### 🔦 Context

I am currently building a button in the shape of an "elongated hexagon" (the corners are clipped). I use `clip-path` to clip the corners for interactions.

Luckily, since the issue only occurs in the move off / back on case, the issue isn't too bad for me, because the clipped areas are minimal enough for it to be barely noticeable.

### 🖥️ Steps to Reproduce

[Follow the steps in this codesandbox](https://codesandbox.io/p/sandbox/proud-shape-k882zt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clslj5uct00062066e3tazerq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clslj5uct00022066jaithzd7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clslj5uct00032066r6oe43so%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clslj5uct00052066wi49tkuj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clslj5uct00022066jaithzd7%2522%253A%257B%2522id%2522%253A%2522clslj5uct00022066jaithzd7%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clslj5uct00052066wi49tkuj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clslj5uct00042066nsbzys8t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clslj5uct00052066wi49tkuj%2522%252C%2522activeTabId%2522%253A%2522clslj5uct00042066nsbzys8t%2522%257D%252C%2522clslj5uct00032066r6oe43so%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clslj5uct00032066r6oe43so%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Version

react-aria 3.32.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Linux

**Comment by LFDanLu** [comment]
This is a tricky one since usePress does hit target testing for some old browser bugs if I remember correctly: https://github.com/adobe/react-spectrum/issues/1720. I'll talk to the team about picking this work back up potentially but we'll need to be extra careful that removing the hit detection doesn't break anything since this press code is used extensively in the repo.

**Comment by LFDanLu** [comment]
Closing this out in favor of https://github.com/adobe/react-spectrum/issues/2506, will link
