### ISSUE TITLE
Typescript: RadioGroupProps['value'] does not allow null

### ISSUE THREAD

**Issue by GeorgEchterling** [adobe/react-spectrum#5871]
### Provide a general summary of the issue here

#5755 fixed tab selection for the [controlled RadioGroup example](https://react-spectrum.adobe.com/react-aria/RadioGroup.html#controlled-value) by using `null` as the "none selected" value. This works, but is not supported by the typescript definition of `RadioGroupProps`.

### 🤔 Expected Behavior?

`<RadioGroup {...props} value={null}>` should not cause a typescript error.

### 😯 Current Behavior

`<RadioGroup {...props} value={null}>` causes a typescript error: 
```
Type 'null' is not assignable to type 'string | undefined'.ts (2322)
inputs.d.ts(67, 3): The expected type comes from property 'value' which is declared here on type 'IntrinsicAttributes & RadioGroupProps & RefAttributes<HTMLDivElement>'
```

### 💁 Possible Solution

Have `RadioGroupProps` extend `ValueBase<string | null>` instead of `ValueBase<string>`.

### 🖥️ Steps to Reproduce

Recreate the [controlled RadioGroup example](https://react-spectrum.adobe.com/react-aria/RadioGroup.html#controlled-value) in a Typescript project.

### Version

react-aria-components 1.1.0

### What browsers are you seeing the problem on?

Other

### If other, please specify.

not a browser issue

### What operating system are you using?

Linux

**Comment by snowystinger** [comment]
Probably would be fixed by TS strict, I see radio hasn't been done yet https://github.com/adobe/react-spectrum/issues/3183

**Comment by sookmax** [comment]
@snowystinger is it really related to TS strict though? I don't see any error output when I run `yarn tsc-strict` after adding `./packages/@react-types/radio` to `tsconfig.json`.

Maybe I'm missing something here, but the following change as @GeorgEchterling suggested would do the job, I suppose?
```diff
- export interface RadioGroupProps extends ValueBase<string>, InputBase, InputDOMProps, Validation<string | null>, LabelableProps, HelpTextProps, FocusEvents {
+ export interface RadioGroupProps extends ValueBase<string|null>, InputBase, InputDOMProps, Validation<string | null>, LabelableProps, HelpTextProps, FocusEvents {
  /**
   * The axis the Radio Button(s) should align with.
   * @default 'vertical'
   */
  orientation?: Orientation
}
```

### Update
Well the above change actually introduces the following type errors in some story files under `packages/@react-spectrum/` 😅:

```
packages/@react-spectrum/form/stories/Form.stories.tsx(518,99): error TS2322: Type 'Dispatch<SetStateAction<string>>' is not assignable to type '(value: string | null) => void'.
packages/@react-spectrum/label/stories/HelpText.stories.tsx(143,9): error TS2322: Type 'Dispatch<SetStateAction<string | undefined>>' is not assignable to type '(value: string | null) => void'.
packages/@react-spectrum/radio/stories/Radio.stories.tsx(268,9): error TS2322: Type 'Dispatch<SetStateAction<string>>' is not assignable to type '(value: string | null) => void'.
```

I guess it has to do with the generic type variable `C` being the same as `T` below:
```ts
export interface ValueBase<T, C = T> {
  /** The current value (controlled). */
  value?: T,
  /** The default value (uncontrolled). */
  defaultValue?: T,
  /** Handler that is called when the value changes. */
  onChange?: (value: C) => void
}
```

Maybe we can introduce the following change in addition to the above change?
```diff
- export interface ValueBase<T, C = T> {
+ export interface ValueBase<T, C = NonNullable<T>> {
  /** The current value (controlled). */
  value?: T,
  /** The default value (uncontrolled). */
  defaultValue?: T,
  /** Handler that is called when the value changes. */
  onChange?: (value: C) => void
}
```

With this change, all files seem to pass when I run `yarn tsc-strict`. 

But I'm not sure whether there's a case where `onChange()` is actually called with the value `undefined` or `null`.

**Comment by GeorgEchterling** [comment]
> But I'm not sure whether there's a case where `onChange()` is actually called with the value `undefined` or `null`.

I don't think `RadioGroup` can currently call `onChange`with `null`. This issue is potentially related: #4971

To avoid changing the types of other components extending `ValueBase`, maybe `RadioGroupProps` can simply extend `ValueBase<string | null, string>`.

**Comment by sookmax** [comment]
> To avoid changing the types of other components extending ValueBase, maybe RadioGroupProps can simply extend ValueBase<string | null, string>.

Haha you're right! This is much better.

I'll just go ahead and create a PR for this then. I was going to wait an answer from @snowystinger regarding TS strict stuff, but maybe we can talk about that in the PR comment section.

Thanks for the suggestion @GeorgEchterling!
