### ISSUE TITLE
Click on popover makes scrollbar disappear

### ISSUE THREAD

**Issue by sina-ss** [adobe/react-spectrum#5881]
### 🙋 Documentation Request

When favorite animal is clicked to select an option, the scrollbar is removed from the page.
Before selection:
![image](https://github.com/adobe/react-spectrum/assets/64675666/f78e8b1d-553c-4182-b6e4-41e6838fba38)
after selection:
![image](https://github.com/adobe/react-spectrum/assets/64675666/77549574-4edf-46f2-8edd-bc1dd688f690)

**Comment by reidbarber** [comment]
Closing as a duplicate of https://github.com/adobe/react-spectrum/issues/5309, and related to https://github.com/adobe/react-spectrum/issues/5470.
