### ISSUE TITLE
useFocusRing not working inside iframe

### ISSUE THREAD

**Issue by ritz078** [adobe/react-spectrum#5882]
### Provide a general summary of the issue here

In the latest release 3.32.0, react-aria added support for iframe tracking but it is not working correctly.

### 🤔 Expected Behavior?

useFocusRing should work inside a dynamically created iframe.

### 😯 Current Behavior

useFocusRing doesn't works. It never assumes that the element is focused.

### 🖥️ Steps to Reproduce

Here is a reproduction

https://codesandbox.io/p/sandbox/keen-julien-55yhq6?file=%2Fsrc%2FApp.js%3A33%2C9

### Version

3.32.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by ritz078** [comment]
@slye-stripe You mentioned somewhere that you have been using this code internally. Does this require any special handling to make this work ?

**Comment by slye-stripe** [comment]
@ritz078 We only call `addWindowFocusTracking`, will look into this as well 👀
