### ISSUE TITLE
Regression in terms of localization strings/i18n bundling in the latest release

### ISSUE THREAD

**Issue by pawelblaszczyk5** [adobe/react-spectrum#5887]
### Provide a general summary of the issue here

In the December release, the possibility of optimizing and removing unused localization strings that are included with react-aria packages was added. It seems like there was some regression in the February release.

Beforehand, strings were extracted to separate files so the bundler plugins can remove them (I've used @react-aria/calendar as an example, but it seems to be the case with every @react-aria/* package that I verified).

3.54.0 release:

![image](https://github.com/adobe/react-spectrum/assets/54995479/e11e84ab-a5b8-4e28-bc95-ab8bbeb32369)

3.55.0 release:

![image](https://github.com/adobe/react-spectrum/assets/54995479/90dc0201-c216-4501-a57f-cd6c83226754)

### 🤔 Expected Behavior?

The i18n strings are extracted to separate files so these can be removed by bundler plugins

### 😯 Current Behavior

The i18n strings are bundled into the rest of the code again

### 💁 Possible Solution

I've tried to found the source of the probem and it seems [like this PR](https://github.com/adobe/react-spectrum/pull/5826/files) reverted not only the "use client" but also some stuff around parcel resolving intl during build. 

### 🔦 Context

I'm using `react-aria-component` and `react-aria` packages in a few different apps and utilizing "en-US" only. I've noticed bundle size spikes since the update happend. Even sticking to the previous version in the `package.json` is hard, because I need to manually override all the `@react-aria/*` stuff to force it to previous versions.

### 🖥️ Steps to Reproduce

I've made a small app where you can observe, the `optimize-locales-plugin` having no effect and all languages for calendar are included in the build output

![image](https://github.com/adobe/react-spectrum/assets/54995479/b246e5d9-8ff2-4df6-9550-22adc472fcfe)

https://github.com/pawelblaszczyk5/react-aria-i18n-bug-reproduction

### Version

N/A

### What browsers are you seeing the problem on?

Other

### If other, please specify.

N/A

### What operating system are you using?

N/A

**Comment by devongovett** [comment]
Oops, good catch! Didn't mean to remove that. 🙈

**Comment by devongovett** [comment]
Released a fix as a patch version to all of our packages. Thanks again for catching this!

**Comment by pawelblaszczyk5** [comment]
That was so quick, thank you very much!
