### ISSUE TITLE
CardView - Add support for placeholder Image

### ISSUE THREAD

**Issue by skathuria29** [adobe/react-spectrum#5905]
### Provide a general summary of the feature here

In Card view on Image resource fetch fail, can we have a support for a placeholder/default image ?

PS. Would love to contribute! :)

### 🤔 Expected Behavior?

something like this. 

<img width="269" alt="Screenshot 2024-02-19 at 3 48 36 PM" src="https://github.com/adobe/react-spectrum/assets/41925518/40530eec-20c7-4963-bcfa-9738fb3287a9">

### 😯 Current Behavior

Doesn't support it as of now.

### 🔦 Context

 On Image resource fetch fail, there currently no support to set placeholder image. The UI will look more presentable with this feature.

**Comment by snowystinger** [comment]
I think we could add this directly to `Image` and handle it there. Then it's not card specific. Maybe we'd come up with a default later when we work on CardView again, but this would allow you to at least handle it.
A PR is always much appreciated! <3 https://react-spectrum.adobe.com/contribute.html#pull-requests

**Comment by skathuria29** [comment]
Yeah sure, makes sense! So should I create a new issue for adding onError callback in Image and take it forward from there ? @snowystinger

**Comment by snowystinger** [comment]
This issue is fine, thanks!

**Comment by skathuria29** [comment]
Hey @snowystinger , does this feature requires an RFC ? or I can straightaway create a PR ?

**Comment by LFDanLu** [comment]
For this I think you can just create a PR and we can discuss the API from there.

**Comment by LFDanLu** [comment]
Added via https://github.com/adobe/react-spectrum/pull/5945
