### ISSUE TITLE
`CheckboxGroup` keyboard navigation is different from `RadioGroup`

### ISSUE THREAD

**Issue by polc** [adobe/react-spectrum#5907]
### Provide your feedback here.

`RadioGroup` provides one tab stop, and we can then navigate between `Radio` components using arrow keys. With `CheckboxGroup`, the behavior is different as there is one tab stop per `Checkbox` and no navigation using arrow keys.

Do you know if it's the intended behavior ? I was surprised as in our huge form, depending of the type of input, the navigation is different.

Thanks you !

### Version

`react-aria-components`: `1.1.1`

**Comment by reidbarber** [comment]
This is the expected behavior, although I can see how it seems strange that they are different. 

Here are the ARIA APG references:
https://www.w3.org/WAI/ARIA/apg/patterns/radio/#keyboardinteraction
https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/examples/checkbox/#kbd_label

**Comment by polc** [comment]
Alright, thank you for the references !
