### ISSUE TITLE
Tooltip: OverlayArrow placed too far on the edges

### ISSUE THREAD

**Issue by thorbde** [adobe/react-spectrum#5917]
### Provide a general summary of the issue here

![Screenshot 2024-02-21 at 14 21 17](https://github.com/adobe/react-spectrum/assets/13640875/9397db32-7610-42bc-8566-d2cee7ca6493)

### 🤔 Expected Behavior?

The OverlayArrow shouldn't go too far to the edges of the tooltip.

### 😯 Current Behavior

The OverlayArrow goes all the way to the edge when the trigger is wider than double the width of the tooltip. This is an issue when there's border radius applied to the tooltip. The positioning is set internally, not sure if it's from the TooltipTrigger or the Tooltip. 

### 💁 Possible Solution

Could you provide a prop to clamp the positioning of the OverlayArrow, so that it does not go further to the edge than allowed?

### 🖥️ Steps to Reproduce

1. Go to your [storybook example, with placement: top right](https://react-spectrum.adobe.com/react-aria-starter/index.html?path=/story/tooltip--example&args=placement:top+right)
2. Set the width of the trigger/button to a width wider than double the width of the tooltip (100px for example).

### Version

1.1.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Macos Sonoma

**Comment by thorbde** [comment]
@snowystinger Is there anything I can do to help here? There's an open PR that seems to address the issue

**Comment by snowystinger** [comment]
We will be giving that PR an API review soon, we just haven't had time yet. We'll update on there when we do. Thanks for the offer.
