### ISSUE TITLE
[RAC] DropZone isDisabled prop

### ISSUE THREAD

**Issue by vbudovski** [adobe/react-spectrum#5938]
### Provide a general summary of the feature here

There is no way at present to disable a DropZone component. This would be a useful feature to have, particularly in the context of using it for a FileTrigger. The trigger button can be disabled on its own, but that still leaves drag events and tab navigation to be handled. 

### 🤔 Expected Behavior?

The DropZone should accept an isDisabled prop which ensures that drop events are not processed. Ideally it would also propagate the disabled status down to the FileTrigger, if included. 

### 😯 Current Behavior

Not possible to disable the drop events or tabbing. The current workaround is to add a conditional inside the drop handler, but tabIndex is not passed through. 

### 💁 Possible Solution

As in summary. 

### 🔦 Context

Would be handy to allow disabling of drop zones in general, but particularly for a FileTrigger child.

**Comment by snowystinger** [comment]
Looks like we just missed adding it. Thank you for bringing it up.
