### ISSUE TITLE
Some months in the Persian Calendar show the 30th as the first day of the month

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#5960]
### Provide a general summary of the issue here

<img width="368" alt="image" src="https://github.com/adobe/react-spectrum/assets/9661127/e524a6cb-a765-426d-b0aa-9d2ba52aea44">

As can be seen in the image above, the month shows the 30th as the first day of said month. The month before this month is also shown as "Esfand 1403 AP" and the following months (Farvardin, Ordibehesht, etc) of the new year (1404 AP) all have this issue until the year after that (1405 AP)

### 🤔 Expected Behavior?

The months should always start with the first I believe

### 😯 Current Behavior

See summary

### 🖥️ Steps to Reproduce

Go to https://reactspectrum.blob.core.windows.net/reactspectrum/a0f0604e6dc461cc50dd923b494b7ad9b9e5bd0c/storybook/index.html?path=/story/date-and-time-calendar--default&providerSwitcher-express=false. Change the Calendar to Persian via the dropdown and navigate to the year 1404 AP. Note that the months have their start date as 31/30/29 depending on which month you are on.

### Version

3.34.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

MacOS 14.1.1

### 🧢 Your Company/Team

RSP

**Comment by sadeghbarati** [comment]
This source might be helpful


[Jalaliday (Persian)](https://github.com/alibaba-aero/jalaliday/blob/master/src/calendar.js)
