### ISSUE TITLE
Cursor shows as text instead of pointer on useTab

### ISSUE THREAD

**Issue by ryo-manba** [adobe/react-spectrum#5972]
### Provide a general summary of the issue here

The cursor on a tab created with useTab appears as text, not as a pointer.

### 🤔 Expected Behavior?

Tabs are displayed with `cursor: pointer`.

### 😯 Current Behavior

Tabs are displayed with `cursor: text`.

### 🔦 Context

According to the WAI-ARIA Authoring Practices Guide (APG), the cursor over tab elements should be displayed as a pointer to intuitively indicate to users that the tabs are interactive elements. This practice ensures that the tabs are clearly recognized as clickable by users. Reference: [WAI-ARIA Authoring Practices Guide Tabs Example](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/).

### 🖥️ Steps to Reproduce

1. Visit [useTabList example – React Aria](https://react-spectrum.adobe.com/react-aria/useTabList.html#example).
2. Hover over a tab.
3. Displayed with `cursor: text`.

### Version

react-aria@3.32.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS Sonoma

**Comment by reidbarber** [comment]
I couldn't find anything in the APG about this, but feel free to include a specific excerpt if there is one. This has been discussed pretty extensively for other interactive elements (i.e. https://github.com/adobe/react-spectrum/pull/449) and we arrived at this stance:

> ## Why don't Buttons use a pointer cursor?
> This matches Spectrum's cursor guidelines, which specify that most clickable elements (with the exception of links), should use an arrow cursor for all states, including hover and down.
The intent is to better match native browser <button> behavior, the [CSS spec](https://www.w3.org/TR/CSS2/ui.html), [Microsoft interface guidelines](https://docs.microsoft.com/en-us/windows/apps/design/input/mouse-interactions#cursors) and [Apple interface guidelines](https://developer.apple.com/design/human-interface-guidelines/inputs/pointing-devices/).

from the [FAQ](https://github.com/adobe/react-spectrum/wiki/Frequently-Asked-Questions-(FAQs)#why-dont-buttons-use-a-pointer-cursor).

Authors can always add this feature via styles, but it seems too opinionated to include this by default.

**Comment by snowystinger** [comment]
I think we could change our styles in our docs so it's not the`text` cursor and it's the`default` cursor instead.

**Comment by ryo-manba** [comment]
Thanks for the link, it was very informative! While it's not explicitly stated in the APG, looking at the CSS for the examples, it seems they intentionally use `cursor: pointer` for tabs.
https://www.w3.org/WAI/content-assets/wai-aria-practices/patterns/tabs/examples/css/tabs.css

However, after reading through the [link Devon shared](https://github.com/adobe/react-spectrum/pull/449#issuecomment-625948251) , I've come to believe that not using cursor: pointer is more appropriate. Therefore, I think the behavior as it stands is fine!
