### ISSUE TITLE
[RAC] data-focused attribute not working in Tabs

### ISSUE THREAD

**Issue by ryo-manba** [adobe/react-spectrum#5973]
### Provide a general summary of the issue here

Clicking or using the keyboard to focus on tabs doesn't add `data-focused`. 
However, `data-focus-visible` works with keyboard focus.

### 🤔 Expected Behavior?

Clicking or focusing on tabs with the keyboard should add `data-focused`.

### 😯 Current Behavior

Tabs do not receive `data-focused` when clicked or keyboard-focused,

### 🖥️ Steps to Reproduce

1. Visit [Tabs example – React Aria](https://react-spectrum.adobe.com/react-aria/Tabs.html#example)
2. Click on a tab or use the keyboard to focus on it.
3. Check that `data-focused` is not added to the tab element.

### Version

react-aria-components@1.1.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS Sonoma

**Comment by snowystinger** [comment]
Looks like it was overlooked, I've created a PR to add it. Thanks for the issue
