### ISSUE TITLE
Select menu closes unexpectedly while holding mouse button and cursor leaving then returning

### ISSUE THREAD

**Issue by subvertallchris** [adobe/react-spectrum#5988]
### Provide a general summary of the issue here

Hello!

My users report that the behavior of the `Select` is surprising, some think it is broken. I was originally going to open this as Feedback but the more I look at it, the less I think this is intentional and the more I think it is a bug.

The summary: if you press a `Button` to open a `Select`, hold the mouse button down, and move the cursor out of the `Button` and then back in, the menu will close.

### 🤔 Expected Behavior?

The Select menu should not close in this scenario. A user should be able to hold the original press without having to avoid the button.

### 😯 Current Behavior

As you'll see in the [example](https://react-spectrum.adobe.com/react-aria/Select.html#example):

* Click the menu and hold the mouse button down
* Without releasing the button, move the cursor over the menu and then move it back over the button
* The menu will close immediately
* Still holding the button, move the cursor out of the button and then back over top
* The menu will open again on its own

This is a strange experience that differs significantly from the HTML select element, as seen [here](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select).

Users are reporting that they think the Select is broken because it closes on its own before they can select. This will happen if someone is used to the HTML select behavior: pressDown to open menu, release over your option. If they happen to move their hand just right (or wrong, I guess) the menu closes.

### 💁 Possible Solution

What appears to happen is this:

* On first press, the `onPressStart` and `onPressChange (true)` events fire.
* While holding the button down, the `onPressEnd` and `onPressChange (false)` events both fire as soon as the cursor leaves the button.
* The `onPressStart` and `onPressChange (true)` fire again as soon as the cursor returns -- it sees it as a new click, which toggles the menu closed. It does not have the context to know that the menu is still 

When someone clicks and releases on the button, you get all four events in one go: `onPressStart`, `onPressChange (true)`, `onPressEnd`, `onPressChange (false)`. This does not close the menu. I have not looked at the code but the behavior suggests that `onPressStart` or `onPressChange (true)` toggles the menu state through `!currentState`; instead, it should probably use `setOpen(true)` to make it explicitly open.

### 🔦 Context

This disrupts users and hurts their confidence in my product because it deviates from their expectations. It's especially harmful on a product checkout page, where selecting a country or state is more difficult than it needs to be.

### 🖥️ Steps to Reproduce

Visit the docs [example](https://react-spectrum.adobe.com/react-aria/Select.html#example).

* Click the menu and hold the mouse button down
* Without releasing the button, move the cursor over the menu and then move it back over the button
* The menu will close immediately
* Still holding the button, move the cursor out of the button and then back over top
* The menu will open again on its own

### Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you using?

Mac OS 14.3.1

**Comment by LFDanLu** [comment]
I think your suggestion of changing the toggle call to a open call could work, essentially changing https://github.com/adobe/react-spectrum/blob/a8ec9667a2b70b88b45e329bf44918f0f93d54f9/packages/%40react-aria/menu/src/useMenuTrigger.ts#L117
to
```
state.open(e.pointerType === 'virtual' ? 'first' : null);
```
From what I can tell, there shouldn't be any ill effects to this since `useInteractOutside` will handle closing the dropdown when clicking on the trigger anyways. Note it will close on press up instead of press start now but I think that is fine. Mind opening a PR for this?

**Comment by subvertallchris** [comment]
Sure thing, PR incoming momentarily.

**Comment by subvertallchris** [comment]
Thank you! What is the release schedule like?

**Comment by subvertallchris** [comment]
Thanks so much for your quick movement on this, @LFDanLu @reidbarber! I just updated my project to nightly. Feels good.
