### ISSUE TITLE
@react-aria/overlays ssr error, ReferenceError: document is not defined, @react-aria\\overlays\\dist\\main.js:1381:61

### ISSUE THREAD

**Issue by AmelloAster** [adobe/react-spectrum#5993]
### Provide a general summary of the issue here

in react 16/17 the useIsSSR always return false
```js
export function useIsSSR(): boolean {
  // In React 18, we can use useSyncExternalStore to detect if we're server rendering or hydrating.
  if (typeof React['useSyncExternalStore'] === 'function') {
    return React['useSyncExternalStore'](subscribe, getSnapshot, getServerSnapshot);
  }

  // eslint-disable-next-line react-hooks/rules-of-hooks
  return useContext(IsSSRContext);
}
```
so the portalContainer = isSSR ? null : document.body always run the document.body
```js
export function Overlay(props: OverlayProps) {
  let isSSR = useIsSSR();
  let {portalContainer = isSSR ? null : document.body, isExiting} = props;
```
and I'm use the SSRProvider, but still not working

deps:
```js
"react": "^16.12.0",
"react-dom": "^16.12.0",
"@react-aria/overlays": "^3.20.0",
"@react-aria/ssr": "^3.8.0",
```

### 🤔 Expected Behavior?

@react-aria/overlays can works fine in react 16/17 SSR environments

### 😯 Current Behavior

ReferenceError: document is not defined, @react-aria\\overlays\\dist\\main.js:1381:61

### 💁 Possible Solution

```
export function useIsSSR(): boolean {
  // In React 18, we can use useSyncExternalStore to detect if we're server rendering or hydrating.
  if (typeof React['useSyncExternalStore'] === 'function') {
    return React['useSyncExternalStore'](subscribe, getSnapshot, getServerSnapshot);
  }

  // eslint-disable-next-line react-hooks/rules-of-hooks
  return type document === undefined;
}
```

### 🖥️ Steps to Reproduce

run in react 16/17 SSR env

### Version

3.20.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

windows, mac

**Comment by LFDanLu** [comment]
Mind including a codesandbox or stackblitz? What version is your installed `@react-aria/ssr` package? Does upgrading to latest fix the issue for you?

**Comment by AmelloAster** [comment]
> Mind including a codesandbox or stackblitz? What version is your installed `@react-aria/ssr` package (3.20.0 is the monopackage version)? Does upgrading to latest fix the issue for you?

I found out what the problem was. Thank you for your reply.

**Comment by snowystinger** [comment]
Hey! Would you mind giving the cause/solution here so that anyone else coming across this can try the same thing? Thank you so much!

**Comment by AmelloAster** [comment]
> Hey! Would you mind giving the cause/solution here so that anyone else coming across this can try the same thing? Thank you so much!

If you are using react version 16-17, please make sure you use the SSRPrivoder in @react-aria/srr to wrap your render root app when rendering SSR
