### ISSUE TITLE
"useTabList" hook keyboard navigation with arrow keys not considering orientation

### ISSUE THREAD

**Issue by Cuuki** [adobe/react-spectrum#5996]
### Provide a general summary of the issue here

We are using the `useTabList` hook to build a tab component that only uses the `horizontal` orientation. By the definition of [W3 regarding keyboard navigation](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/#keyboardinteraction) for tabs, the `horizontal` orientation should only be navigated by using `Left Arrow` & `Right Arrow` keys while using `Down Arrow` & `Up Arrow` should scroll the page.

We have currently implemented a workaround by overriding the `onKeyDown` with a custom callback that is blocking the `Down Arrow` & `Up Arrow` key navigation.

### 🤔 Expected Behavior?

When using `orientation="horizontal"` for `useTabList` from `'@react-aria/tabs'` users should only be able to switch the tabs with `Left Arrow` & `Right Arrow` keys. `Down Arrow` & `Up Arrow` keys should scroll the page.

### 😯 Current Behavior

When using `orientation="horizontal"` for `useTabList` from `'@react-aria/tabs'` users will switch the tab by either using `Left Arrow` & `Right Arrow` or `Down Arrow` & `Up Arrow` keys.

### 💁 Possible Solution

We are currently using a workaround to override the returned event handler `onKeyDown` with our own custom solution:

```ts
const { tabListProps } = useTabListReactAria({}, state, tabListRef);

const handleKeyDown = (e: KeyboardEvent<FocusableElement>) => {
    if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
        return;
    }

    tabListProps.onKeyDown?.(e);
};

const boxProps = {
    tabList: {
        ...tabListProps,
        onKeyDown: handleKeyDown,
    }
}
```

### 🔦 Context

https://www.w3.org/WAI/ARIA/apg/patterns/tabs/#keyboardinteraction

### 🖥️ Steps to Reproduce

* Create a tab with the available hooks (or use `react-spectrum` tabs component)
* Open the [sandbox link](https://codesandbox.io/p/sandbox/frosty-newton-fjj4m2?file=%2Fsrc%2FApp.js%3A2%2C69&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltct3lpj00063b7xshv366yh%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltct3lpj00023b7xcncxvaxr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltct3lpj00033b7xfsg2ayow%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltct3lpj00053b7x16w3vfv8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltct3lpj00023b7xcncxvaxr%2522%253A%257B%2522id%2522%253A%2522cltct3lpj00023b7xcncxvaxr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltctc70p00023b7zkk2z5lam%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A23%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cltctkl4100023b7zte8hkp6t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A69%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A69%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltctkl4100023b7zte8hkp6t%2522%257D%252C%2522cltct3lpj00053b7x16w3vfv8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltct3lpj00043b7xb9fs0rpq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltct3lpj00053b7x16w3vfv8%2522%252C%2522activeTabId%2522%253A%2522cltct3lpj00043b7xb9fs0rpq%2522%257D%252C%2522cltct3lpj00033b7xfsg2ayow%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltct3lpj00033b7xfsg2ayow%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) and navigate to the tab list via keyboard (`Tab` key)
* Navigate the tab list with the arrow keys

### Version

`"@react-aria/tabs": "^3.8.5"` is currently used but the version does not matter.

### What browsers are you seeing the problem on?

Other

### If other, please specify.

Browser is not relevant, issue happens everywhere.

### What operating system are you using?

macOS

**Comment by snowystinger** [comment]
Could either make a new KeyboardDelegate which doesn't have getKey(direction) depending on the orientation. https://github.com/adobe/react-spectrum/blob/361d47080c79e4d52ee287078b9e3c27ed312f2e/packages/%40react-aria/tabs/src/useTabList.ts#L45

Or we could add some logic to to useSelectableCollection https://github.com/adobe/react-spectrum/blob/361d47080c79e4d52ee287078b9e3c27ed312f2e/packages/%40react-aria/selection/src/useSelectableCollection.ts#L163

**Comment by mdhmaiti** [comment]
Hello, I am medhashis and I am new here. I made a solution for this issue and it is working. I am new to open source so I am unable to clearly understand what are the checkpoints to this open source repo.  I have some naive questions like how to pass the test-canary, test-16,  ts build fork points checks etc  and it is also my first time contributing to adobe (https://opensource.adobe.com/cla.html). In the form there is something like GitHub Login, I am confused If the github login and github username are same. Can anyone please help me ?, I liked this repo and want to be an active contributor

**Comment by LFDanLu** [comment]
@majornista just wanna check if you have an opinion here on this behavior. I think previously we had changed this behavior since we couldn't rely on the screenreader from announcing the orientation of the Tabs hence the fallback to having both pairs of arrow keys move focus through the Tabs regardless of orientation?

**Comment by majornista** [comment]
> @majornista just wanna check if you have an opinion here on this behavior. I think previously we had changed this behavior since we couldn't rely on the screenreader from announcing the orientation of the Tabs hence the fallback to having both pairs of arrow keys move focus through the Tabs regardless of orientation?

I think the solution may be to only use ArrowLeft/ArrowRight with `orientation="horizontal"`, and use both ArrowLeft/ArrowRight and ArrowUp/ArrowDown for `orientation="vertical"`.
