### ISSUE TITLE
Support `<ListBox>` as a standalone form field component

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#5997]
### Provide a general summary of the feature here

Currently, the RAC `<ListBox>` component cannot be used as a standalone form field, because it

- does not forward the `name` prop
- does not render a hidden form input (`<select>`, `<select multiple>` or `<input type="hidden">`)
- is not connected to `useField` for label, help text and validation state

what do you think about adding a new `ListBoxField` for that?

### 🤔 Expected Behavior?

i would like to be able to do something like the following:

```tsx
"use client";

import { Button, FieldError, Form, Label, ListBox, ListBoxField, ListBoxItem } from "react-aria-components";
import { useFormState } from "react-dom";

export function MyForm() {
  const fruits = [
    { id: "banana", label: "Banana" },
    { id: "kiwi", label: "Kiwi" },
    { id: "orange", label: "Orange" },
    { id: "tomato", label: "Tomato" },
  ];

  function action(formData: FormData) {
    const selectedFruits = formData.getAll("fruits");

    console.log({ selectedFruits });

    if (selectedFruits.includes("tomato")) {
      return { fieldErrors: { fruits: "No tomatoes!" } };
    }

    return undefined;
  }

  const [formState, formAction] = useFormState(action, undefined);

  return (
    <Form action={formAction} validationErrors={formState?.fieldErrors}>
      <ListBoxField name="fruits" selectionMode="multiple">
        <Label>Fruits</Label>
        <ListBox items={fruits}>
          {(item) => {
            return <ListBoxItem>{item.label}</ListBoxItem>;
          }}
        </ListBox>
        <FieldError />
      </ListBoxField>

      <Button type="submit">Submit</Button>
    </Form>
  );
}
```

### 😯 Current Behavior

see above

### 🔦 Context

see above

**Comment by LFDanLu** [comment]
Apologies for the delay, discussed this with the team today. We aren't opposed to the idea but it feels like this functionality could be handled with a radiogroup that was styled to look similar to a listbox. If that doesn't work for your use case, you could potentially build this ListBoxField already with `useField` and pass the applicable props down via the public ListBox contexts + render the visually hidden select. We'd be happy to help with any questions if you go that route!

**Comment by stefanprobst** [comment]
thanks, and sorry for the late response - i think a differently styled radio/checkbox-group might actually work!

feel free to close this issue, or convert it into a discussion.

**Comment by snowystinger** [comment]
Thank you!
