### ISSUE TITLE
Date pickers lose time zone when using the calendar after values are cleared

### ISSUE THREAD

**Issue by Stanaland-Michael-bah** [adobe/react-spectrum#6005]
### Provide a general summary of the issue here

When a date picker is supplied a ZonedDateTime as a value or defaultValue, if the user clears out the date and/or time value (by either backspacing over the field values or by clicking a "clear dates" button), then choses a new date from the popup calendar, the internal state value looses the time zone information and becomes a CalendarDateTime. 

https://github.com/adobe/react-spectrum/assets/157808128/9f586135-17ca-4920-97e9-40f1aeec16f5

https://github.com/adobe/react-spectrum/assets/157808128/e887b9fc-0ca7-476f-a9b9-b0ea4f416835

### 🤔 Expected Behavior?

The internal state value type should persist regardless of editing (If it starts out as a ZonedDateTime, it should stay a ZonedDateTime)

### 😯 Current Behavior

See general summary. There is a work-around: If you provide a placeholderValue, the time zone will persist

https://github.com/adobe/react-spectrum/assets/157808128/e1d4adbb-0eba-4e61-a412-9482f81df230

### 💁 Possible Solution

Maybe a similar issue that was fixed in useTimeFieldState here: 
https://github.com/adobe/react-spectrum/pull/4715/files

### 🖥️ Steps to Reproduce

You can use this fork of the useDatePicker Tailwind CSS example:
https://codesandbox.io/p/sandbox/gifted-vaughan-9n2wfm?file=%2Fsrc%2FApp.js

The only thing that was changed was to swap the DatePicker's defaultValue for an absolute date

1) Backspace over the hours and minutes
2) Open the calendar dialog and choose a new date
_time zone is lost, value becomes a CalendarDateTime_

1) Backspace over the year, month and day
2) Open the calendar dialog and choose a new date
_time zone is lost, value becomes a CalendarDateTime_

Workaround:
1) Add a placeholderValue that is a ZonedDateTime
2) Repeat the steps above
_time zone persists as expected_

### Version

"react-stately": "^3.30.1", "react-aria": "^3.32.1",

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

MacOS 14.3.1

**Comment by LFDanLu** [comment]
Thanks for reporting this, reproduced locally. This was partially fixed via https://github.com/adobe/react-spectrum/pull/4715, that PR might help point to where we would want to investigate further.

**Comment by boutahlilsoufiane** [comment]
Hi @LFDanLu I will work on this.

**Comment by LFDanLu** [comment]
Sure, thanks! Let us know if you need any help or guidance.

**Comment by boutahlilsoufiane** [comment]
@LFDanLu Could you please check https://github.com/adobe/react-spectrum/pull/7069
