### ISSUE TITLE
Calendar's controlled value prop (in onChange) and setValue() from CalendarStateContext can't be set to null

### ISSUE THREAD

**Issue by psywalker** [adobe/react-spectrum#6006]
### Provide a general summary of the issue here

I get the `setValue` method from `CalendarStateContext` and try to set `null` as the value for `setValue()` but an error immediately occurs and nothing is set. Prop of `value` and `onChange` and `setValue(null)` with the wrong type and TS swears at `null`. 

### 🤔 Expected Behavior?

Calendar's controlled `value` prop and `state.setValue()` from `CalendarStateContext` and in `onChange` prop can be set to `null`

### 😯 Current Behavior

Calendar controlled `value` and `setValue()` from `CalendarStateContext` can't be set to `null`, judging by `value?:T`, but for some reason it allows you to set `null`.
And the same goes for method `setValue()` from `CalendarStateContext`. You cannot set `null` in `setValue()`

### 💁 Possible Solution

1. Add to the interface `ValueBase<T, C = T>`:

`value?: T | null`,
`onChange?: (value: C (and null))`

```
export interface ValueBase<T, C = T> {
  /** The current value (controlled). */
  value?: T,
  /** The default value (uncontrolled). */
  default Value?: T,
  /** Handler that is called when the value changes. */
  onChange?: (value: C) => void
}
```
 
2. Add to the interface `CalendarState extends CalendarStateBase`:

`setValue(value: CalendarDate | null): void;`
```
export interface CalendarState extends CalendarStateBase {
    /** The currently selected date. */
    readonly value: CalendarDate;
    /** Sets the currently selected date. */
    setValue(value: CalendarDate): void;
}
```

3. Give the option (fix) to set `null` so that you can, for example, reset the date in the calendar.

### 🖥️ Steps to Reproduce

[Here you can see an example](https://codesandbox.io/p/sandbox/calendar-from-react-aria-components-67xhm4?file=%2Fsrc%2FApp.tsx%3A21%2C45). You can see that `onChange` and `setValue(null)` with the wrong type and TS swears at null. And if you press the "Clear" button and try to set `state.setValue(null);` and the value in value is not reset

### Version

1.1.1 react-aria-components

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS 13.3

**Comment by LFDanLu** [comment]
Looks like the same issue as mentioned here: https://github.com/adobe/react-spectrum/issues/3187#issuecomment-1710452003. I believe that we can just add a if statement before here: https://github.com/adobe/react-spectrum/blob/a8ec9667a2b70b88b45e329bf44918f0f93d54f9/packages/%40react-stately/calendar/src/useCalendarState.ts#L141
to be something like
```
      if (newValue === null) {
        setControlledValue(null);
        return;
      }
```
Mind opening a PR?

**Comment by psywalker** [comment]
> Looks like the same issue as mentioned here: [#3187 (comment)](https://github.com/adobe/react-spectrum/issues/3187#issuecomment-1710452003). I believe that we can just add a if statement before here:
> 
> https://github.com/adobe/react-spectrum/blob/a8ec9667a2b70b88b45e329bf44918f0f93d54f9/packages/%40react-stately/calendar/src/useCalendarState.ts#L141
> 
> 
> to be something like
> ```
>       if (newValue === null) {
>         setControlledValue(null);
>         return;
>       }
> ```
> 
> Mind opening a PR?

OK, I'll try to do this task.
But could you give me a link to a document describing the approach to contributing to your project? And also, a document that describes the steps on how to fix the code in your project and make you a PR.

**Comment by psywalker** [comment]
@LFDanLu Please help me understand in which interfaces to add `... | null`

**Comment by LFDanLu** [comment]
I imagine https://github.com/adobe/react-spectrum/blob/a8ec9667a2b70b88b45e329bf44918f0f93d54f9/packages/%40react-stately/calendar/src/types.ts#L106 would be an area to add the `| null` to.

**Comment by psywalker** [comment]
@LFDanLu, done! https://github.com/adobe/react-spectrum/pull/6030

**Comment by psywalker** [comment]
@LFDanLu Well, thank you! I've put my PR in the draft for now, just in case.

**Comment by andredewaard** [comment]
Any news when this will be merged? it looks like this is still an issue.
