### ISSUE TITLE
ComboBox: onBlur doesn't work when no Button provided

### ISSUE THREAD

**Issue by tomekancu** [adobe/react-spectrum#6007]
### Provide a general summary of the issue here

`onBlur` is not triggered for blur event, when `buttonRef` is empty in `useComboBox` hook

### 🤔 Expected Behavior?

`onBlur` should be triggered, even when there is no button inside. 

### 😯 Current Behavior

You must use `Button` inside of `ComboBox` to onBlur work correctly. 

### 💁 Possible Solution

Check if the `buttonRef` is filled
https://github.com/adobe/react-spectrum/blob/361d47080c79e4d52ee287078b9e3c27ed312f2e/packages/%40react-aria/combobox/src/useComboBox.ts#L161

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/exciting-river-rfnxhh

### Version

1.1.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac

**Comment by tomekancu** [comment]
here is PR with the solution #6008 #6008

**Comment by snowystinger** [comment]
Thanks for the issue and PR!
