### ISSUE TITLE
"Maximum call stack size exceeded" at focus @ [native code]

### ISSUE THREAD

**Issue by IonelLupu** [adobe/react-spectrum#6050]
### Provide a general summary of the issue here

Our Datadog service got tens of thousands of daily errors like this in production:
![image](https://github.com/adobe/react-spectrum/assets/4083652/11ccc4c7-1b44-4be8-9a88-28bc4692fbd0)

Following the minified code, I found that it might be related (but not 100% sure) to this piece of code from react-aria (`@react-aria/interactions/src/useFocusVisible.ts:144`):

```ts
// Register focus events on the window so they are sure to happen
// before React's event listeners (registered on the document).
windowObject.addEventListener('focus', handleFocusEvent, true);
```

We are not able to replicate. It seems it happens Chrome, Safari or Instagram browser on iOS only. What can we do to provide more information? Did you ever encounter such an error before?

### 🤔 Expected Behavior?

To not get an error

### 😯 Current Behavior

Getting an error in console

### 💁 Possible Solution

-

### 🔦 Context

-

### 🖥️ Steps to Reproduce

Cannot replicate

### Version

react-aria-components: ^1.0.2-nightly.4451

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

iOS

### 🧢 Your Company/Team

athotel.com

**Comment by reidbarber** [comment]
Also, do you have any indicators on what version was deployed when these errors showed up? I see you mentioned `^1.0.2-nightly.4451`. This could help us track down if this is from a recent change or not, or if it happened after an upgrade.

**Comment by IonelLupu** [comment]
@snowystinger Here is the stack trace from Datadog (image and text):
![image](https://github.com/adobe/react-spectrum/assets/4083652/c39a2eef-67cf-4820-8053-c02bda5ed729)
```
RangeError: Maximum call stack size exceeded.
at focus @ [native code]
at <anonymous> @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:77938
at tryFocus @ https://athotel.com/_next/static/chunks/9479.cc8275e867c5a72b.js:4:4269
at checkFocusIn @ https://athotel.com/_next/static/chunks/9479.cc8275e867c5a72b.js:4:4979
at focus @ [native code]
at <anonymous> @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:77938
at onFocus @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:38662
at focus @ [native code]
at <anonymous> @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:77938
at tryFocus @ https://athotel.com/_next/static/chunks/9479.cc8275e867c5a72b.js:4:4269
at checkFocusIn @ https://athotel.com/_next/static/chunks/9479.cc8275e867c5a72b.js:4:4979
at focus @ [native code]
at <anonymous> @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:77938
at onFocus @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:38662
at focus @ [native code]
at <anonymous> @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:77938
at tryFocus @ https://athotel.com/_next/static/chunks/9479.cc8275e867c5a72b.js:4:4269
at checkFocusIn @ https://athotel.com/_next/static/chunks/9479.cc8275e867c5a72b.js:4:4979
at focus @ [native code]
at <anonymous> @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:77938
at onFocus @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:38662
at focus @ [native code]
at <anonymous> @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:77938
at tryFocus @ https://athotel.com/_next/static/chunks/9479.cc8275e867c5a72b.js:4:4269
at checkFocusIn @ https://athotel.com/_next/static/chunks/9479.cc8275e867c5a72b.js:4:4979
at focus @ [native code]
at <anonymous> @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:77938
at onFocus @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:38662
at focus @ [native code]
at <anonymous> @ https://athotel.com/_next/static/chunks/8800-5982b3801bc71b66.js:1:77938
```
You can go to these links to see the minified code. Hopefully you can find something. I did it and I ended up to the code I shared above.

@reidbarber this is the exact version: `1.0.2-nightly.4451+c11afb257`. Not sure 100%, but I think these errors showed up even on version `1.0.0`

**Comment by reidbarber** [comment]
Are you using the [focus-trap](https://github.com/focus-trap/focus-trap) library? That stack trace looks like it's coming from there.

**Comment by reidbarber** [comment]
The `checkFocusIn` and `tryFocus` functions from the stack track exist in that codebase.

**Comment by IonelLupu** [comment]
> The checkFocusIn and tryFocus functions from the stack trace exist in that codebase.

@reidbarber I am amazed you know that code base 😅

**Comment by reidbarber** [comment]
Not quite, Github's code search is just really good!

**Comment by IonelLupu** [comment]
@reidbarber @snowystinger, we removed the package and monitored the error. It seems the package mentioned above, that was used by `react-spring-bottom-sheet` (from some old code of ours), was the issue for the error. 

All good now. Thank you very much! Closing the issue
