### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'isStopped')

### ISSUE THREAD

**Issue by jay-s-p-vi** [adobe/react-spectrum#6052]
### Provide a general summary of the issue here

when i open the datepicker by clicking on the arrow, it shows this arrow shown in error that I pasted in title.

### 🤔 Expected Behavior?

show calender

### 😯 Current Behavior

it shows ${title} error

### 💁 Possible Solution

just replace the funtion code of AnimatedCalender.tsx
located at line 114
with this code:
```js
 const animateToPage = useCallback(
    (index: number) => {
      // Animate to the new page. Use inertia if the velocity is not zero (e.g. when swiping),
      // otherwise use a static transition (e.g. when next/previous buttons are clicked).
      let pos = -index * ref.current!.clientWidth ?? 0;
      return animate(
        x,
        pos,
        x.getVelocity() !== 0
          ? {
            ...inertiaTransition,
            min: pos,
            max: pos
          }
          : staticTransition
      );
    },
    [x]
  );
also 
FIX the TYPESCRIPT errors in that file
```
 
### 🖥️ Steps to Reproduce

click on the arrow button

### Version

latest

### What browsers are you seeing the problem on?

all

### What operating system are you using?

ubnatu

**Comment by reidbarber** [comment]
Is this something you can reproduce in stackblitz/codesandbox? The code you mentioned is exactly the code in the example, so you may have forgotten to include your custom code. Also, isStopped isn't a string in our repo, so that may be coming from framer-motion.

**Comment by jay-s-p-vi** [comment]
Sorry, I attached the wrong code snippets.

here is the stackblitz link : https://stackblitz.com/edit/twtsreact-xsmmqw?file=src%2Fmain.tsx,src%2FAnimatedCalendar.tsx
- you can check the code in AnimatedCalender.tsx located at line 143 is the solution, you can comment on that code and uncomment library code to preview the error.

Thank you.

**Comment by sookmax** [comment]
You're accessing `CalendarState` incorrectly. Use destructuring assignment from the render prop to get the `CalendarState`.


```diff
<Calendar aria-label="Appointment date" className="w-fit pt-4">
-      {(state) => (
+     {({ state }) => (
```

https://stackblitz.com/edit/twtsreact-kpfzpj?file=src%2FAnimatedCalendar.tsx

**Comment by sookmax** [comment]
Interesting.. when I made the following change, [the original code](https://github.com/adobe/react-spectrum/blob/main/examples/rac-tailwind/src/AnimatedCalendar.tsx#L114-L132) works:

```diff
useEffect(() => {
  x.stop();
  const controls = animateToPage(pageOffset);
-  return controls?.stop;
+ return () => controls?.stop();
}, [pageOffset, animateToPage, x]);
```

Not sure why this affects the `this` reference when `controls?.stop()` is called.

In addition, there is a bug in the original code that [CalendarState](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/calendar/src/types.ts#L102-L107) is incorrectly referenced:

```diff
<Calendar aria-label="Appointment date" className="w-fit pt-4">
-      {(state) => (
+     {({ state }) => (
```

See this sandbox: https://stackblitz.com/edit/twtsreact-kpfzpj?file=src%2FAnimatedCalendar.tsx
