### ISSUE TITLE
add forwarded focusable ref on RadioGroup (rac)

### ISSUE THREAD

**Issue by Mrtly** [adobe/react-spectrum#6054]
### Provide a general summary of the feature here

`RadioGroup` does not currently expose a focuseable ref, the radios cannot be accessed programmatically.

### 🤔 Expected Behavior?

With a forwarded ref non-native form handling will be able to `focus()` and `scrollIntoView()` when a form field requires user attention.
When the group is programmatically called to `focus` via the ref, the first radio item in the field should be focused.

### 😯 Current Behavior

The RadioGroup does not forward a ref so it is not possible to `focus` on its radio children programmatically.

### 💁 Possible Solution

[discussion](https://github.com/adobe/react-spectrum/discussions/6049#discussioncomment-8766282)

### 🔦 Context

Other RAC input/field components expose a ref and can be focused through non-native form handling. 
Adding a forwardRef to the RadioGroup would result in behavior consistency across form fields.

**Comment by snowystinger** [comment]
Related work recently on switch and checkbox https://github.com/adobe/react-spectrum/pull/5967

Relevant comment from discussion about path forward and question to the team:
>RadioGroup doesn't expose a focusable ref, we could consider doing that.
It looks like we don't expose the inputRef to the Radio ref either. So that could also be an option.
I think using useImperitiveHandle on the RadioGroup though makes the most sense since it's aware of the roving tab index already

**Comment by sookmax** [comment]
@snowystinger, I have a question.

> I think using useImperitiveHandle on the RadioGroup though makes the most sense since it's aware of the roving tab index already

So for the usage of `useImperativeHandle()` on `<RadioGroup />` in the comment above, I imagined something like this:
```tsx
useImperativeHandle(ref, () => {
  return {
    ...domRef.current,
    focus: () => {
      let walker = getFocusableTreeWalker(domRef.current);
      (walker.firstChild() as HTMLElement).focus();
    }
  };
});
```

And when you said 'roving tab', you meant this I suppose? [Managing Focus Within Components Using a Roving tabindex](https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_roving_tabindex)

The question is, I'm not so sure how to put 'roving tab index' and the usage of the `useImperativeHandle()` that I envisioned above together? 

Of course unless you meant something completely different haha. In that case, could you clarify a little more about what we're trying to achieve here? Thanks!

**Comment by snowystinger** [comment]
I think you're on the right track, only the currently selected radio should be focusable, so the focusabletreewalker should only find that one. There is the case where none of them have been selected yet, in which case, it should find the very first radio as all of them will be technically focusable.

<img width="744" alt="Screenshot 2024-03-16 at 9 13 03 AM" src="https://github.com/adobe/react-spectrum/assets/698229/fd4202d1-003d-45ee-8c27-bbacfa62e6bb">
<img width="658" alt="Screenshot 2024-03-16 at 9 13 13 AM" src="https://github.com/adobe/react-spectrum/assets/698229/b61a7aa0-6365-42aa-9470-22765b27f8e5">
<img width="786" alt="Screenshot 2024-03-16 at 9 13 31 AM" src="https://github.com/adobe/react-spectrum/assets/698229/2bd29f80-2978-4cf3-b2de-a9d840d1771e">

**Comment by nwidynski** [comment]
Following along here as well as #5967. 

Was there a reason behind exposing the ref as a prop instead of dogfooding `<Input />` and utilizing its `<InputContext.Provider />`?

I kind of feel like `<RadioGroup />` especially could have benefitted from a more composable approach.

**Comment by snowystinger** [comment]
Hi @nwidynski thanks for the feedback.
I'm not entirely sure what you're proposing, so please forgive me if I go in a different direction with my thoughts.

I don't think we want people to use the context to attach a ref to the input for these components. That seems like a lot of extra work.
```
<Provider values={[[InputContext, {ref: inputRef}]]}>
  <Switch />

// vs
<Switch inputRef={inputRef}>
```
and I feel like this would become even more work in the case of RadioGroup wrapping each individual Radio.

I think RadioGroup and CheckboxGroup are pretty different in terms of focus behavior. One acts as a single focus stop, the other is a set of focus stops. As a result, we don't want people to call focus on a single Radio, I think it makes more sense at the RadioGroup. This, I feel, is different than the behavior for a CheckboxGroup where any of them could receive focus and calling it on the Group is meaningless.

I don't see how the context helps us solve the issue for RadioGroup, if we tried to attach with context, we'd end up sending the ref to every radio.

Again, I may be missing something. It might help to sketch out what you think the API would look like.
Thanks again for the input.

**Comment by nwidynski** [comment]
> Hi @nwidynski thanks for the feedback. I'm not entirely sure what you're proposing, so please forgive me if I go in a different direction with my thoughts.
> 
> I don't think we want people to use the context to attach a ref to the input for these components. That seems like a lot of extra work.
> 
> ```
> <Provider values={[[InputContext, {ref: inputRef}]]}>
>   <Switch />
> 
> // vs
> <Switch inputRef={inputRef}>
> ```
> 
> and I feel like this would become even more work in the case of RadioGroup wrapping each individual Radio.
> 
> I think RadioGroup and CheckboxGroup are pretty different in terms of focus behavior. One acts as a single focus stop, the other is a set of focus stops. As a result, we don't want people to call focus on a single Radio, I think it makes more sense at the RadioGroup. This, I feel, is different than the behavior for a CheckboxGroup where any of them could receive focus and calling it on the Group is meaningless.
> 
> I don't see how the context helps us solve the issue for RadioGroup, if we tried to attach with context, we'd end up sending the ref to every radio.
> 
> Again, I may be missing something. It might help to sketch out what you think the API would look like. Thanks again for the input.

That answered the question, thank you!

**Comment by snowystinger** [comment]
Well, that isn't quite the requirement for RadioGroup, the requirement there is to be able to call 'focus'.
 
This is so focus can be moved to the first invalid field in a form after validation. This is how we handle it internally https://github.com/adobe/react-spectrum/blob/81e672fda7dc023e650f5d9f471512556a8865c4/packages/%40react-aria/form/src/useFormValidation.ts#L59

If we need to give access to the individual input's per radio, then those would be done the same as we did switch and checkbox, on each individual control. But if we can I think we should hold off on that, due to the roving tabIndex, it could get you into unexpected situations. For instance you could focus an unselected one when a selection already exists.
<img width="226" alt="Screenshot 2024-03-18 at 8 09 51 AM" src="https://github.com/adobe/react-spectrum/assets/698229/e5877a0d-a606-46fa-bb03-43eb9c1764b0">
So I want to be more careful in considering exposing Radio input refs

**Comment by snowystinger** [comment]
@Mrtly can you check the PR submitted and make sure this fits your needs. I tried looking at Zod, they don't appear to move focus at all, so I think you're actually the one handling this?

If so, you could also consider handling it the same way as I mentioned in my previous comment.

**Comment by Mrtly** [comment]
> @Mrtly can you check the PR submitted and make sure this fits your needs. I tried looking at Zod, they don't appear to move focus at all, so I think you're actually the one handling this?

Thanks for the follow ups here! In my example in the discussion thread it is react-hook-form that handles the focus on invalid fields, so it generally requires [access to the ref](https://www.react-hook-form.com/faqs/#Howtosharerefusage).
 If using imperative handle for `focus()`, might you also consider adding the `scrollIntoView()` function as well?
 I'll note this on the PR too.
