### ISSUE TITLE
Date picker Popover isn't collapsing during click outside the popover 

### ISSUE THREAD

**Issue by Mohamed02** [adobe/react-spectrum#6070]
### Provide a general summary of the issue here

Date picker Popover isn't collapsing during click onside the popover when "isNonModal" is set to true

### 🤔 Expected Behavior?

Even when "isNonModal" is true, the Calendar Popover must close/collapse when the user clicks outside the calendar .

### 😯 Current Behavior

when "isNonModal" is true, the Calendar Popover isnt closing when the user clicks outside the calendar . Alternatively user has to scroll the page or select a date in order to collapse the popover. 

In addtiion to this , even the function shouldCloseOnInteractOutside is also not getting triggered when the user click outside the calendar

### 💁 Possible Solution

Option1: Allow page scrolling when - isNonModal not set,
Option 2: if Option #1 is not feasible, calendar has to be collapsed when clicked outside the Calendar. and not during scroll ( when isNonModal is true)
Option 3: If Option #1 & #2 are not feasible then trigger shouldCloseOnInteractOutside when user clicks outside the calendare( when isNonModal is true)

### 🖥️ Steps to Reproduce

Try examples on https://react-spectrum.adobe.com/react-aria/DateField.html

### Version

1.1.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac

**Comment by LFDanLu** [comment]
https://github.com/adobe/react-spectrum/issues/5338 is related. However, can you go into more detail as to why you are applying `isNonModal` to your DatePicker's Popover? That is used for ComboBox since focus remains on the input when the dropdown is opened but shouldn't be the case for DatePicker.

**Comment by Mohamed02** [comment]
without setting the property - isNonModal, the page is frozen (unable to scroll) when Popover is in expanded mode.

**Comment by LFDanLu** [comment]
The popover's not scrolling when open is intentional (see https://github.com/adobe/react-spectrum/issues/2926 and https://github.com/adobe/react-spectrum/issues/5126#issuecomment-1732793307). You shouldn't apply `isNonModal` just to get around this restriction since that prop has changes to accessibility behavior that isn't suitable in many cases.
