### ISSUE TITLE
ListView and useAsyncList fails with TypeError: Cannot read properties of undefined (reading 'key')

### ISSUE THREAD

**Issue by synox** [adobe/react-spectrum#6074]
### Provide a general summary of the issue here

When using AsyncListData with ListView, and setting the ListView.height=100%, and I scroll quickly down and up, I get the following error: 
```
TypeError: Cannot read properties of undefined (reading 'key')
    at $4e8b0456ef72939f$export$9610e69494fadfd2 (https://.../vendors-node_modules_..._esm_index_js-node_modules_...-fd91c693251bcbbc8d02113289.js:125258:19)
```

https://github.com/adobe/react-spectrum/assets/2250964/e85670b1-8a11-4827-9b92-2f3a1d1127ee

### 🤔 Expected Behavior?

It should not show an error

### 😯 Current Behavior

It shows an error on scroll. 

### 🖥️ Steps to Reproduce

reproduce in react-spectrum-v3-playground: 

```js
function Component() {
  const list = useAsyncList({
    async load({ cursor, filterText, signal }) {
      const res = await fetch(cursor || 'https://pokeapi.co/api/v2/pokemon?limit=10', {
        signal,
      });
      const json = await res.json();
      return {
        items: json.results,
        cursor: json.next,  
      };
    },
  });

  return (
    <View>
      <ListView height="300px"
        items={list.items}
        loadingState={list.loadingState}
        onLoadMore={list.loadMore}
      >
        {(item) => {
          return <Item key={item.name}>{item.name}</Item>;
        }}
      </ListView>
    </View>
  );
}
```

### Version

3.33.2

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macos

### 🧢 Your Company/Team

Adobe AEM

**Comment by snowystinger** [comment]
I tried in Chrome and used the provided code in the playground, but I am unable to reproduce.
Could you provide an already built codesandbox or stackblitz which reproduces it? Just to make sure I didn't accidentally do something silly when I copy pasted

**Comment by synox** [comment]
I am able to reproduce on https://j7v3sy.csb.app/ with Chrome and Firefox. 
-> [Editor](https://codesandbox.io/p/sandbox/upbeat-silence-j7v3sy?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltxjjhi500063b6hfkleiqwn%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltxjjhi500023b6heyh24sel%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltxjjhi500033b6h9wl9qrni%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltxjjhi500053b6h4hhvp9bw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltxjjhi500023b6heyh24sel%2522%253A%257B%2522id%2522%253A%2522cltxjjhi500023b6heyh24sel%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltxx1dv4003r3b6glwqc3scv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A32%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltxx1dv4003r3b6glwqc3scv%2522%257D%252C%2522cltxjjhi500053b6h4hhvp9bw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltxjjhi500043b6hlgnodo16%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltxjjhi500053b6h4hhvp9bw%2522%252C%2522activeTabId%2522%253A%2522cltxjjhi500043b6hlgnodo16%2522%257D%252C%2522cltxjjhi500033b6h9wl9qrni%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltxjjhi500033b6h9wl9qrni%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by snowystinger** [comment]
Thank you very much, I can reproduce now.

**Comment by synox** [comment]
@snowystinger are there any news on this?

**Comment by mitrank** [comment]
@synox I'm using Microsoft Edge browser to check the sandbox and link you mentioned above but to me it's working fine on scrolling up and down quickly, it isn't showing the null error you mentioned. 
However, when trying the code you mentioned in the Steps to Reproduce section, I encountered the error which mentioned the destructured element 'scale' is null while extracting it using useProvider hook. 
So, I tried just logging the scale extracting it from the useProvider hook, and it shows null.

**Comment by snowystinger** [comment]
No updates from my end. I've had competing priorities.

**Comment by upender7270** [comment]
I am also facing this issue, is there any update on this? It's a blocker to us.

**Comment by upender7270** [comment]
I am also getting this error frequently, any update on this issue?

**Comment by richardbann** [comment]
This seems to be the same as #6181. The virtualizer wants to render an item (based on the layout, which is computed from the actual collection), but the internal collection is lagged behind (the collection update is waiting in a transaction for the animation to complete).
I have a fix for that but it's rather hacky... I have ruled out these cases in the Virtualizer by adding a check in `getReusableView`, `_correctItemOrder` and `updateSubviews` methods: [`Virtualizer.ts`](<https://github.com/adobe/react-spectrum/compare/main...richardbann:react-spectrum:virtualizer-collection-lag#diff-f9405406c2dc605226f231a1af6ab2a05f64a6c2f83ab9eaf3f2b8c7dd8b7ae2>)
@snowystinger What do you think?

**Comment by bmingles** [comment]
In case it helps, the codesandbox attached to #6181 will automatically reproduce this issue 100% of the time.

https://codesandbox.io/p/sandbox/frosty-shtern-k9hv39
