### ISSUE TITLE
Localize show All & show Less button in  @adobe/react-spectrum/TagGroup component

### ISSUE THREAD

**Issue by dhavkuma** [adobe/react-spectrum#6084]
### Provide a general summary of the issue here

Consuming tag group in another unified shell app leaves these button unlocalized.

### 🤔 Expected Behavior?

Test should follow localization

### 😯 Current Behavior

english text always shown.

### 🖥️ Steps to Reproduce

set maxRows to 1 and enable show/hide overflowing tags.
Btn is not localized

### Version

2.28.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by devongovett** [comment]
It is localized automatically. It will use your browser's language by default, unless you override the locale set on the Provider. https://react-spectrum.adobe.com/react-spectrum/Provider.html#locales If this is already being set, then you need to check for duplicate node_modules (perhaps tag group is using a different version from provider).
