### ISSUE TITLE
ComboBox Popover doesn't stay open when selected list item overflows input width

### ISSUE THREAD

**Issue by staticshock** [adobe/react-spectrum#6087]
### Provide a general summary of the issue here

After you select this ListBoxItem, the Popover can't be successfully opened a second time:

```jsx
<ComboBox>
  <Group>
    <Input />
    <Button>Open</Button>
  </Group>
  <Popover>
    <ListBox>
      <ListBoxItem>
        Something long enough that it overflows the input box when selected
      </ListBoxItem>
    </ListBox>
  </Popover>
</ComboBox>
```

### 🤔 Expected Behavior?

The Popover should open the same way every time, regardless of the current state of the Input box.

### 😯 Current Behavior

After the long item is selected, the caret is placed at the end of the text in the input box, and through some mechanism I don't fully understand this disrupts the Popover.

https://github.com/adobe/react-spectrum/assets/13100/3055b420-e652-4025-9475-f065d14d9d60

### 💁 Possible Solution

I haven't dug deep enough to have any clue here. Frankly, I'd even be perfectly happy with a workaround, but haven't stumbled into anything good yet.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/mystifying-moon-srzl5g

### Version

```json
"react-aria": "^3.32.1",
"react-aria-components": "^1.1.1",
"tailwindcss-react-aria-components": "^1.1.1"
```

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

Arc

### What operating system are you using?

macOS

**Comment by snowystinger** [comment]
Which chrome version is this in? I'm not able to reproduce in 122.
I suspect that the cursor moving is causing a scroll event, but I'm not sure why it's causing the issue repeatedly. If it was that, i'd expect it to open fine after the cursor was already positioned at the end.

**Comment by snowystinger** [comment]
Related thread https://github.com/adobe/react-spectrum/issues/5653

**Comment by staticshock** [comment]
Originally on Arc, but I just reproduced just fine on Chrome (and somewhat on Firefox) using [this demo](https://codesandbox.io/p/sandbox/mystifying-moon-srzl5g).

- On Chrome (123.0.6312.59) it keeps happening on every click.
- On Firefox (123.0.1) it's only reproducible on the first click after selection.
- On Safari it is not reproducible.

**Comment by staticshock** [comment]
Yeah, I think this is the same issue as #5653
