### ISSUE TITLE
React-Aria Popover underlay does not cover elements with a positive z-index

### ISSUE THREAD

**Issue by cypherfunc** [adobe/react-spectrum#6095]
### Provide a general summary of the issue here

Popover uses an "underlay" element to block interaction (e.g. scrolling) with outside elements. However, elements with a z-index greater than zero are sometimes still interactable. (Something to do with stacking contexts? 🤷‍♀️)
This is difficult to work around, since the className and styling for the underlay are not customizable.

### 🤔 Expected Behavior?

The underlay should cover everything except the Popover, meaning nothing else should be interactable.

### 😯 Current Behavior

In my specific case, the Popover is rendered by UI inside a flyout, and the flyout has a positive z-index to overlay the main page. when the Popover is open, I can still scroll the flyout. This is especially noticeable because the trigger scrolls away from the Popover.

### 💁 Possible Solution

Set the z-index on the underlay like on the Popover, or at least provide a way for the caller to apply styles to the underlay so they can set it as needed. (Manually setting a high z-index on the element in the DevTools fixes the problem.)

### 🖥️ Steps to Reproduce

Open https://codesandbox.io/p/sandbox/agitated-violet-5v33kh
Scroll down in any of the divs and click to open a Popover. With that open, try scrolling each of the divs. The bottom one is always scrollable.

### Version

1.1.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 10

**Comment by cypherfunc** [comment]
Since we use vanilla CSS,  until there's a better option `[data-testid="underlay"] { z-index: 100000; }` is an ok work-around.

**Comment by snowystinger** [comment]
You could apply `isolation: isolate` to the `id="root"` element. That should take care of it.

**Comment by cypherfunc** [comment]
> You could apply `isolation: isolate` to the `id="root"` element. That should take care of it.
Yup, that works in the example. I'll have to test whether I can use it for our actual app. It still feels like a work-around to me though; compared to if the underlay z-index was set to match the popover. 🤷‍♀️ Thanks!

**Comment by snowystinger** [comment]
Glad it's working for you in the example!

I think there are a number of issues with relying on zIndex, for instance, your workaround set it to 10000, which is a random number and might conflict with some other zIndex in another library. Isolation is a good way to know you're starting a new stacking context and make all of the collisions you might have with zIndex impossible.

I feel like isolation is the best way to address this, and should be used more.

**Comment by QzCurious** [comment]
I'm facing this issue, too. I'd like to share some thought about the hard part on RAC:
I'm a Radix UI user. Radix UI is more verbose, as a component would usually only wrap a single html element, but it also make is pretty easy to customize any html element. It's really a great trade off IMO.
It's very hard for me to do switch to RAC. Even on a new, small side project, I frequently had situation that I can't style a html element that I know I need to, and it cause a lot of workaround. It cost me 5x to 10x time compare to Radix UI.

I'm not complain on it but wish to have a more flexible api for us to use RAC. As RAC is now on a stable version. I understand splitting components to more granular level would not be preferable. But hopefully we can at least have a more reliable way to style those html element. Either by props or a `[data-underlay]` attribute would be fine.

**Comment by snowystinger** [comment]
Hi @QzCurious, I think your comment is more in line with https://github.com/adobe/react-spectrum/issues/5231 ?
I'm going to close this one, we can continue your discussion over there.

@cypherfunc we can reopen this one if you are still running into issues.

**Comment by eranimo** [comment]
This is still a problem.

**Comment by snowystinger** [comment]
@eranimo thanks for your comment, were you able to follow https://github.com/adobe/react-spectrum/issues/6095#issuecomment-2019189475 to get it working?
