### ISSUE TITLE
[RAC] Access to `selectionManager.setFocusedKey` in `Menu`

### ISSUE THREAD

**Issue by somebody1234** [adobe/react-spectrum#6098]
### Provide a general summary of the feature here

I want to be able to focus certain keys on certain keypresses (e.g. focus first on `ArrowDown`; focus last on `ArrowUp`; focus selected on `ArrowLeft`)

### 🤔 Expected Behavior?

Focus API is exposed

### 😯 Current Behavior

No way to get the focus API without smuggling it out via an invisible `MenuItem`

### 💁 Possible Solution

Not sure. Exposing `selectionManager.setFocusedKey` as-is may work, but I'm not sure it's the ideal solution

### 🔦 Context

I have a 2D navigator that uses arrow keys to navigate between sections of a page based on how they are visually laid out

**Comment by somebody1234** [comment]
actually, it *is* kinda convenient to access more of the API - e.g. `getFirstKey()`/`getLastKey()`/`firstSelectedKey` would be useful in this specific usecase, although a union of `'first' | 'last' | 'first-selected'` or similar would probably be sufficient

**Comment by snowystinger** [comment]
Looks like this issues fell through the cracks. I don't think we want to support this, Menu navigation is implemented as described here https://www.w3.org/WAI/ARIA/apg/patterns/menubar/

I'm not quite sure what a 2D navigator is. Maybe if you can provide a codesandbox or a stackblitz or just some mock ups, maybe we can help with some alternate suggestions.

**Comment by somebody1234** [comment]
it's more or less like this https://www.w3.org/TR/css-nav/
although, to be fair, the idea does seem quite flawed... <https://wicg.github.io/spatial-navigation/demo/>

**Comment by snowystinger** [comment]
I see. That looks pretty different from Menu and seems more like an overall system for navigating something like a TV? Or maybe some other navigation component entirely?
I think for now you'd need to implement it yourself. It's unlikely to be compatible with our hooks and I think trying to force it via setFocusedKey could lead to some non-accessible interactions.

I'm going to close this issue for now. We can revisit in an issue dedicated to the feature later if it makes sense.
