### ISSUE TITLE
CommonJS - Server client mismatch / `SSRProvider` not working properly

### ISSUE THREAD

**Issue by ixTec** [adobe/react-spectrum#6102]
### Provide a general summary of the issue here

Using `@react-aria/datepicker` for a custom DatePicker / DateField Component and I receive server/client mismatches when rendering the component in a NextJS app and using `SSRProvider`

### 🤔 Expected Behavior?

I should be able to use the custom component in both SSR and non-SSR situations, without any errors/mismatches.

### 😯 Current Behavior

IDE console is spammed with `When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.` warnings.

Browser console  hydration errors with client and server mis match for properties coming from the react aria hooks
<img width="713" alt="Screenshot 2024-03-26 at 14 22 36" src="https://github.com/adobe/react-spectrum/assets/9938773/bdab4c9b-0eff-462f-ad3a-5fa95cad6752">

### 💁 Possible Solution

I believe this is something to do with the `locale` changes, given the default is `en-US` whereas my local locale is `en-GB` and so this causes the component to rerender with switched values? (as in, month and day are switched and so are their attributes)

### 🔦 Context

- App is wrapped in `SSRProvider` in `workbench/pages/_app.tsx`
- Using Next 12 and React 17

### 🖥️ Steps to Reproduce

Reproduction repo - https://github.com/ixTec/react-aria-datefield

- Run `yarn`
- Run `yarn workbench`

### Version

``` json 
"@internationalized/date": "3.5.2",
"@react-aria/button": "3.9.3",
"@react-aria/calendar": "3.5.6",
"@react-aria/datepicker": "3.9.3",
"@react-aria/focus": "3.12.1",
"@react-aria/i18n": "3.10.2",
"@react-aria/ssr": "3.9.2",
"@react-aria/utils": "^3.23.2",
"react-stately": "3.30.1"
```
### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

Mac OS

**Comment by reidbarber** [comment]
When rendering on the server, you'll need to use an I18nProvider with an explicit `locale` prop: https://react-spectrum.adobe.com/react-aria/ssr.html#internationalization

> When using server side rendering, the application should be wrapped in an [I18nProvider](https://react-spectrum.adobe.com/react-aria/I18nProvider.html) with an explicit locale prop, rather than relying on automatic locale selection. This ensures that the locale of the content rendered on the server matches the locale expected by the browser. The Accept-Language HTTP header, which the browser sends to the server with the user’s desired language, could be used to implement this. You could also use an in-application setting for this if available, or locale-specific URLs, for example. In addition to passing the locale prop to the I18nProvider, you should also ensure the lang and dir attributes are set on the <html> element for your page.

**Comment by ixTec** [comment]
> When rendering on the server, you'll need to use an I18nProvider with an explicit locale prop

Unfortunately this does not work either - I've updated the linked reproduction repo to show this. I still experience the SSRProvider error and server/client mismatches.

**Comment by ixTec** [comment]
@reidbarber Do you have any other suggestions for this? It's the one thing holding us back releasing our component, due to the awkward SSR issue

**Comment by reidbarber** [comment]
I'm not sure why this is happening. We have a Next.js 12 + React 17 example [here](https://github.com/adobe/react-spectrum/tree/main/examples/rsp-next-ts-17) that renders without this issue, so I'm inclined to think it's a configuration or setup discrepancy. I also don't think this is related to I18nProvider, and I don't think this is due to mixing package versions, based on the yarn.lock included.

**Comment by snowystinger** [comment]
I don't know much about Next unfortunately, but it looks to me like you aren't using `_app.tsx` which is where the SSR and I18n providers are defined. Instead, index.tsx is just directly calling the `../workbench.tsx` file. This one doesn't use either provider.
Is there some Next.js magic at work here which means that the providers actually are in play?

**Comment by ixTec** [comment]
@snowystinger The `_app.tsx` is a custom App page, to override how the pages are initialised in NextJS - see https://nextjs.org/docs/pages/building-your-application/routing/custom-app. It's similar to the custom one provided in the example @reidbarber linked [here](https://github.com/adobe/react-spectrum/blob/main/examples/rsp-next-ts-17/pages/_app.tsx)


I've updated [my repro ](https://github.com/ixTec/react-aria-datefield) to show a comparison between a local component (like you have in your example) and a transpiled component.

- The local one works fine, as expected
- The transpiled one has the problem, pointing towards an issue with how it's transpiled.

I will continue investigating this as well

**Comment by ixTec** [comment]
I've been able to confirm that this is a problem when transpiling our custom DatePicker component (using `@react-aria`) to CommonJS - does `@react-aria` not play well with it?

**Comment by snowystinger** [comment]
It looks like you're loading two different copies of our `node_modules/@react-aria/utils`
```
[1] loading module.mjs
[1] loading main.js
```

You'll need to consolidate that, through whatever config (that I'm unfamiliar with)

**Comment by reidbarber** [comment]
Maybe worth trying adding `type: "module"` to `package.json`. Or maybe double check the node version.

**Comment by ixTec** [comment]
@snowystinger Managed to resolve it thanks to this, thank you!
