### ISSUE TITLE
[RAC] Calendar: cells who are unavailable get aria-disabled, but not data-disabled

### ISSUE THREAD

**Issue by Wanchalermhonghom** [adobe/react-spectrum#6108]
### Provide a general summary of the issue here

CalendarCells that are filtered by isDateUnavailable only get aria-disabled, but not data-disabled.

### 🤔 Expected Behavior?

data-disabled should also be true.

### 😯 Current Behavior

states.isDisabled from useCalendarCell is false

### 💁 Possible Solution

`  isDisabled = isDisabled || state.isCellDisabled(date);`

this line seems to be the culprit from useCalendarCell

### 🖥️ Steps to Reproduce

1. Visit Calendar/RangeCalendar
2. Go to Unavailable dates section and inspect unavailable dates cell

Note:
Somehow the unavailable weekend dates in calendar get data-disabled.
The unavailable dates in the weekday do not

### Version

1.1.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by devongovett** [comment]
Unavailable and disabled are distinct states, so they use different data attributes (data-unavailable and data-disabled). Aria-disabled is an implementation detail for screen readers and shouldn't be used for styling.
