### ISSUE TITLE
[RAC] Radio - pass ref to input element

### ISSUE THREAD

**Issue by aspirisen** [adobe/react-spectrum#6123]
### Provide a general summary of the issue here

Looks like ref in radio is passed to label, not to the input element

### 🤔 Expected Behavior?

Ref should be forwarded to input element

### 😯 Current Behavior

Ref forwarded to label

### 💁 Possible Solution

Change forward ref logic, or add `inputRef` prop if passing default `ref` is not possible.

### 🔦 Context

I think users should have access to underlaying form element via `ref`. It is needed i.e. for [react-hook-form](https://react-hook-form.com/docs/useform/register)

### 🖥️ Steps to Reproduce

[CodeSandbox](https://codesandbox.io/p/sandbox/dark-cache-pwsn77?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clucrsl5f00063b6hmfpe8l2n%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clucrsl5f00023b6hen689r8a%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clucrsl5f00033b6hg2nqhptl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clucrsl5f00053b6h5x9ut1uj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clucrsl5f00023b6hen689r8a%2522%253A%257B%2522id%2522%253A%2522clucrsl5f00023b6hen689r8a%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clucrsl5f00053b6h5x9ut1uj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clucrsl5f00043b6hc8o726dh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clucrsl5f00053b6h5x9ut1uj%2522%252C%2522activeTabId%2522%253A%2522clucrsl5f00043b6hc8o726dh%2522%257D%252C%2522clucrsl5f00033b6hg2nqhptl%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clucrsl5f00033b6hg2nqhptl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Version

"react-aria-components": "^1.1.1"

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by devongovett** [comment]
We always forward the `ref` to the outer-most DOM element in every component. However, we recently added `inputRef` support to Checkbox/Switch in #5967, and probably should add the same thing to Radio as well.

**Comment by aspirisen** [comment]
@devongovett good, thanks. I think there is always should be ref access to form elements, just in cases like with react-hook-form.

**Comment by sookmax** [comment]
I think this issue can be closed, now that https://github.com/adobe/react-spectrum/pull/6067 is merged?

Sorry I had a typo in the PR that didn't link to this issue properly before it got merged 😅 (Closes #6054, #6123 -> should have been -> Closes #6054, closes #6123)

**Comment by yihuiliao** [comment]
@sookmax Yep, I think we can close this issue. Thanks for pointing it out!
