### ISSUE TITLE
Duplicate id prop with TextField and Input

### ISSUE THREAD

**Issue by mpalmer685** [adobe/react-spectrum#6125]
### Provide a general summary of the issue here

When providing an `id` prop to a component built with `TextField` and `Input`, the outer `div` element and the `input` element both receive the same ID.

### 🤔 Expected Behavior?

Only one element should have the given `id` prop (ideally, the `input` element).

### 😯 Current Behavior

Both the outer `div` (rendered by the `TextField` component) and the `input` element get the provided `id`.

### 💁 Possible Solution

Filter out the `id` prop before passing it to the TextField's `div` element.

### 🔦 Context

This bug is causing axe to report `duplicate-id-aria` errors because the label's `htmlFor={id}` points to two different elements.

### 🖥️ Steps to Reproduce

[CodeSandbox](https://codesandbox.io/p/sandbox/goofy-taussig-t4nywv)

### Version

"react-aria-components": "^1.1.1"

### What browsers are you seeing the problem on?

Firefox

### What operating system are you using?

macOS

**Comment by LFDanLu** [comment]
Thanks for catching this! Probably just needs to delete `id` from the filtered props before [they are spread](https://github.com/adobe/react-spectrum/blob/784737effd44b9d5e2b1316e690da44555eafd7e/packages/react-aria-components/src/TextField.tsx#L87) like its done in [SearchField](https://github.com/adobe/react-spectrum/blob/784737effd44b9d5e2b1316e690da44555eafd7e/packages/react-aria-components/src/SearchField.tsx#L78).
