### ISSUE TITLE
<Button/>'s `onPress` is not fired when using userEvent.click() from React Testing Library 

### ISSUE THREAD

**Issue by telriot** [adobe/react-spectrum#6134]
### Provide a general summary of the issue here

While testing components using React Testing Library, attempts to fire onPress using userEvent.click() fail.
It works correctly using other methods, i.e. fireEvent(...).
There was a (closed) similar issue for Storybook's userEvent, but the problem seems to persist.

### 🤔 Expected Behavior?

onPress should fire independently of the method used to click the Button component

### 😯 Current Behavior

onPress does not fire when clicking the Button component with userEvent.click().

### 🔦 Context

User event version: "@testing-library/user-event": "^14.5.2",

### 🖥️ Steps to Reproduce

Example:
```
describe('Button interaction', () => {
  test('It calls onPress when clicked', async () => {
    const onPress = jest.fn()
    const user = userEvent.setup()
    render(<View onPress={onPress} />)
    const element = screen.getByRole('button')
    await user.click(element)
    expect(onPress).toHaveBeenCalled() <= this fails (even if we were to wait for it)
  })
})
```

### Version

3.32.1

### What browsers are you seeing the problem on?

Other

### If other, please specify.

Test Environment

### What operating system are you using?

Ubuntu 22.0.4

**Comment by reidbarber** [comment]
You'll want to define a `triggerPress` utility like we have here:

https://github.com/adobe/react-spectrum/blob/bceab7b81f4925aff77ae94cefaadb032fb17442/packages/dev/test-utils/src/events.ts#L18-L22

We eventually want to publish and document some test utilities, including this. See https://github.com/adobe/react-spectrum/pull/5891 and https://github.com/adobe/react-spectrum/issues/3703

**Comment by yihuiliao** [comment]
You might need to define the pointerMap like we did and pass it to userEvent.setup():
https://github.com/adobe/react-spectrum/blob/bceab7b81f4925aff77ae94cefaadb032fb17442/packages/dev/test-utils/src/userEventMaps.ts#L3-L10
https://github.com/adobe/react-spectrum/blob/bceab7b81f4925aff77ae94cefaadb032fb17442/packages/%40react-spectrum/button/test/Button.test.js#L37

**Comment by telriot** [comment]
Thanks everyone :) I will just update my test-util setup accordingly. As mentioned above, test related docs and examples would be great (even just to know that it is something that is not going to be addressed as a bug, but needs setup no matter what).

**Comment by telriot** [comment]
As an extra note if someone stumbles on this: the solution above works right away with happy-dom, but does not with jsdom. 
Jsdom probably requires mocking the Pointer interface (See https://github.com/adobe/react-spectrum/pull/5891 and https://github.com/adobe/react-spectrum/issues/3703 for details).
