### ISSUE TITLE
[RAC] Table - TypeScript does not recognise context property types

### ISSUE THREAD

**Issue by AmProsius** [adobe/react-spectrum#6158]
### Provide a general summary of the issue here

I use React Aria Components' [Table](https://react-spectrum.adobe.com/react-aria/Table.html) with [context](https://react-spectrum.adobe.com/react-aria/Table.html#contexts) to select or deselect all the rows in the table.

However, I get a TypeScript error when accessing the `TableContext`.
```tsx
import { useContext } from "react";
import { TableContext } from "react-aria-components";

const tableContext = useContext(TableContext);
const selectedKeysCount = tableContext?.selectedKeys.size || 0;
```

```
Property 'selectedKeys' does not exist on type 'WithRef<TableProps, HTMLTableElement> | SlottedValue<WithRef<TableProps, HTMLTableElement>>'.
Property 'selectedKeys' does not exist on type 'SlottedValue<WithRef<TableProps, HTMLTableElement>>'.
```

### 🤔 Expected Behavior?

TypeScript recognises the context properties' types.

### 😯 Current Behavior

TypeScript doesn't recognise the context properties' types and throws an error.

### 💁 Possible Solution

I didn't find a solution so far, so I _expected_ the TypeScript error (because the code works) but I'd like to understand why the type isn't inferred correctly and how I can tell typescript which type to use.

```tsx
const tableContext = useContext(TableContext);
// @ts-expect-error TypeScript doesn't recognise `selectedKeys` on `tableContext`
const selectedKeysCount = tableContext?.selectedKeys.size || 0;
```

### 🔦 Context

I have an action bar that is outside the table, so I have to use the `TableContext` to control the selected keys.

### 🖥️ Steps to Reproduce

Here's a [minimal reproduction Sandbox](https://codesandbox.io/p/sandbox/rac-table-provider-typescript-p4qk54) that shows the issue.

### Version

"react-aria-components": "1.1.1"

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by yihuiliao** [comment]
Not sure why the codesandbox isn't showing me the TypeError so wasn't able to verify this myself but does using `useSlottedContext` instead of `useContext` fix the issue? https://react-spectrum.adobe.com/react-aria/advanced.html#useslottedcontext

**Comment by AmProsius** [comment]
That indeed fixes the issue. Thank you!
