### ISSUE TITLE
ListBox with layout="grid" throws exceptions when navigated out of bounds via keyboard

### ISSUE THREAD

**Issue by staticshock** [adobe/react-spectrum#6168]
### Provide a general summary of the issue here

Using the arrow keys to navigate through a ListBox (react-aria-components) configured with a grid layout throws exceptions when I reach a grid boundary via [getKeyAbove or getKeyBelow](https://github.com/adobe/react-spectrum/blob/e6923d9473264b972974513dacbcfab5a24d5616/packages/@react-aria/selection/src/ListKeyboardDelegate.ts#L129-L143).

### 🤔 Expected Behavior?

Focus stays put when I try to navigate beyond a grid boundary in any direction; no exceptions are thrown.

### 😯 Current Behavior

An exception is visible in the console. Nothing in particular is broken, but it seems untidy, and probably easily fixed with a null check somewhere in the ListKeyboardDelegate.

### 💁 Possible Solution

Maybe a null check somewhere around [here](https://github.com/adobe/react-spectrum/blob/e6923d9473264b972974513dacbcfab5a24d5616/packages/@react-aria/selection/src/ListKeyboardDelegate.ts#L111-L116)?

```js
// Find the item above or below in the same column.
let prevRect = item.getBoundingClientRect();
do {
  key = nextKey(key);
  item = this.getItem(key);
} while (item && shouldSkip(prevRect, item.getBoundingClientRect()));
```

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/crimson-sea-hddt7h

Here's what it looks like if I press the the up arrow key to navigate through this list:

https://github.com/adobe/react-spectrum/assets/13100/67b39256-ed00-4eb3-b10c-7d12cda7099d

### Version

```json
"react-aria": "^3.32.1",
"react-aria-components": "^1.1.1",
"react-stately": "^3.30.1",
"tailwindcss-react-aria-components": "^1.1.1"
```

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by snowystinger** [comment]
Thanks for the sandbox and initial digging. Looks like a bug as you've pointed out
