### ISSUE TITLE
FieldErrorContext export

### ISSUE THREAD

**Issue by rafighajili** [adobe/react-spectrum#6170]
### 🙋 Documentation Request

It would be better if FieldErrorContext can be imported from 'react-aria-components' package. (I got case which I need FieldErrorContext)

**Comment by reidbarber** [comment]
It should have been as of the latest [release](https://react-spectrum.adobe.com/releases/2024-02-13.html) via https://github.com/adobe/react-spectrum/pull/5743

Can you sure you're using the latest version? `react-aria-components@1.1.0`

**Comment by rafighajili** [comment]
> It should have been as of the latest [release](https://react-spectrum.adobe.com/releases/2024-02-13.html) via #5743
> 
> Can you sure you're using the latest version? `react-aria-components@1.1.0`

thanks, it worked after updating version
