### ISSUE TITLE
[react-aria-componets]: Checkbox imposible to visit links defined in Label

### ISSUE THREAD

**Issue by mauron85** [adobe/react-spectrum#6251]
### Provide a general summary of the issue here

Checkbox manages onClick events in a way, that prevent links used in Label to be visited.

![2024-04-23-14-53-11](https://github.com/adobe/react-spectrum/assets/359450/4c2b6e99-9cb4-4fd9-a316-92cf559bba7a)

### 🤔 Expected Behavior?

Should be able to follow (click) link from within Label.

### 😯 Current Behavior

Checkbox currently checks the checkbox instead of visiting link.

### 🔦 Context

I would like to create list of consents using checkboxes, where in label there can be links.

![image](https://github.com/adobe/react-spectrum/assets/359450/e390321c-10b1-484f-8325-209cad6becd4)

### 🖥️ Steps to Reproduce

Click on Link

https://codesandbox.io/p/sandbox/elastic-monad-c2chtf

### Version

1.1.1

### What browsers are you seeing the problem on?

Microsoft Edge

### What operating system are you using?

Windows 10

**Comment by mauron85** [comment]
I think can be related to https://github.com/adobe/react-spectrum/issues/6235

**Comment by sookmax** [comment]
> I think can be related to #6235

Maybe https://github.com/adobe/react-spectrum/issues/1166 is more relevant to your case?

**Comment by mauron85** [comment]
@sookmax I agree with conclusing made in #1166

> so this is problematic for accessibility, a checkbox label should, when clicked, toggle the checkbox
by putting a link in it, you’ve conflated the two actions

Unfortunatelly this label text (with link) is from api call, so it cannot be just splitted into two separate components.

As result, I would accept, that this use case, will not be supported. Please let me know.

In that case, I would change implementation for simple html checkbox + label.

**Comment by snowystinger** [comment]
I mean, you're just getting a string from the API, you could probably split it yourself with a regex. I'm going to close this as we won't be allowing a link in a checkbox label though, it's not accessible.
