### ISSUE TITLE
React Aria Starter Kit download (for Tailwind) is out of date with latest react-aria-components version

### ISSUE THREAD

**Issue by EricBPower** [adobe/react-spectrum#6268]
### 🙋 Documentation Request

The React Aria Starter Kit download for Tailwind is not using latest react aria components version. Latest download file from the website is react-aria-tailwind-starter.48e54b651.zip and the project package.json is using "react-aria-components": "^1.0.0-rc.0".

We are using the latest react aria version and the corresponding start components show use of properties that have changed or no longer exist in the latest version or react-aria-components.

I'm requesting an update to the documentation pages to provide an updated react aria starter kit download that uses the latest package version, and that as releases happen the starter kits should stay up to date with the latest version.

### 🧢 Your Company/Team

DHI

**Comment by reidbarber** [comment]
Looks like we need to bump the version in the starter's package.json as part of the release:

https://github.com/adobe/react-spectrum/blob/1550ccaa62363b65079eb2e36563380db0e7c043/starters/tailwind/package.json#L29 Same with the `tailwindcss-react-aria-components` version
