### ISSUE TITLE
Compatibility with React 19 types

### ISSUE THREAD

**Issue by eps1lon** [adobe/react-spectrum#6276]
### Provide a general summary of the feature here

Ensure compatibility with React 19 types

### 🤔 Expected Behavior?

no type errors		

### 😯 Current Behavior

type errors

### 🔦 Context

`npx types-react-codemod` should get you most of the way. There are also some manual changes required and 3rd party libraries to fix. An overview over all the required changes can be seen in https://github.com/eps1lon/react-spectrum/pull/1.  You can also check out https://github.com/users/eps1lon/projects/3/views/9 to get an overview what other apps/libraries need to do for migration.

**Comment by SimenB** [comment]
@snowystinger this was fixed in #6437, right?

(🎉)

**Comment by snowystinger** [comment]
Yes, thank you. I'd forgotten to attach it to this issue. <3
