### ISSUE TITLE
RSP does not install on windows

### ISSUE THREAD

**Issue by davidcoleman007** [adobe/react-spectrum#6314]
### Provide a general summary of the issue here

As a windows developer, I am unable to install RSP and contribute.

Steps to reproduce:
1) use windows
2) clone this repo
3) yarn it
4) observe the failure seen below.

I have found a number of issues, mostly around the `build-icons` step.
![image](https://github.com/adobe/react-spectrum/assets/41075/a055b788-a88f-4abd-91bd-ec8f9b21c51b)

### 🤔 Expected Behavior?

RSP repo will support windows development environments

### 😯 Current Behavior

RSP repo does not work in a windows development environment

### 💁 Possible Solution

https://github.com/adobe/react-spectrum/pull/6313

### 🖥️ Steps to Reproduce

Steps to reproduce:
1) use windows
2) clone this repo
3) yarn it
4) observe the failure

### Version

latest

### What browsers are you seeing the problem on?

Other

### If other, please specify.

can't yarn install

### What operating system are you using?

Windows 11

### 🧢 Your Company/Team

Adobe/Acrobat Web

**Comment by yihuiliao** [comment]
I believe this has been fixed in https://github.com/adobe/react-spectrum/pull/6313

**Comment by davidcoleman007** [comment]
Thank you @yihuiliao ! I will update tomorrow and verify.
