### ISSUE TITLE
User Search ComboBox, long text causes popup to immediately close when clicked

### ISSUE THREAD

**Issue by danielweck** [adobe/react-spectrum#6322]
### Provide a general summary of the issue here

In Chrome/Chromium, any overflowing text typed into the input box causes the popout to fail to display

### 🤔 Expected Behavior?

the popout should be displayed

### 😯 Current Behavior

the popout briefly shows, but immediately disappears

### 💁 Possible Solution

This bug only occurs in Chrome/Chromium (we discovered it Electron) but does not occur in Firefox and Safari (tested on MacOS) ... so probably helps narrow-down the source of the problem?

### 🔦 Context

This is a critical bug that blocks a release as the popout list of choices is not displayed

### 🖥️ Steps to Reproduce

https://react-spectrum.adobe.com/react-aria/examples/user-combobox.html

1) type any arbitrary long text that reaches the end of the input field, just enough to cause the entered text to "scroll" at least one character
2) click on the "arrows" icon button to attempt to reveal the popout list of choices

### Version

latest in official website

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by sookmax** [comment]
Might be related to https://github.com/adobe/react-spectrum/issues/5653#issuecomment-1922662612 and https://github.com/adobe/react-spectrum/issues/5653 in general.

**Comment by snowystinger** [comment]
Thank you! 
I'm able to reproduce with the example and steps you shared.
Closing as a duplicate.
