### ISSUE TITLE
Allow customizing react-spectrum DropZone's padding and border

### ISSUE THREAD

**Issue by prabirshrestha** [adobe/react-spectrum#6331]
### Provide a general summary of the feature here

There should be an option to set padding to 0 and disable the border.

### 🤔 Expected Behavior?

Should allow to set padding to 0 and disable border.

### 😯 Current Behavior

Not possible.

```typescript
<DropZone>
  <TableView>...</TableView>
</DropZone>
```

Notice the dashed border, padding and the checkbox column is after the first Name column instead of the first column and the Size column is a bit cut.

![image](https://github.com/adobe/react-spectrum/assets/287744/b28fcd08-e654-45d6-8d0f-66d62ceea01e)

When dragging I noticed there is a shift of the TableHeader which could be the issue.

![image](https://github.com/adobe/react-spectrum/assets/287744/bb6a0ef3-ee33-4432-a8f6-8e8ce0e5b1db)

Here is the Table without drop zone.

![image](https://github.com/adobe/react-spectrum/assets/287744/8d5c0c9d-4896-46f4-bf21-5087fd7d9b15)

### 🔦 Context

I'm creating a file explorer and would like to support dropping files and folders.

**Comment by snowystinger** [comment]
I don't think you should have a dropzone containing a table. There are too many conflicts with interactions. Instead, after dropping, replace the dropzone with the table and if you need to, provide a "clear" button somewhere to unload the table.

**Comment by prabirshrestha** [comment]
Thanks for the suggestion. This seems to be the exact behavior I would like to have.

```typescript
let { dragAndDropHooks } = useDragAndDrop({
  onRootDrop: (e) => console.log(e.items),
});

return <TableView dragAndDropHooks={dragAndDropHooks} />
```
