### ISSUE TITLE
Different popover underlay behaviors between mobile and desktop devices

### ISSUE THREAD

**Issue by andreslemusm** [adobe/react-spectrum#6335]
### Provide a general summary of the issue here

When you press the Popover underlay on mobile devices, the press event is 'propagating' to the interactive element below the underlay (button, anchor, input, etc).

### 🤔 Expected Behavior?

The behavior should replicate the Desktop behavior and not 'propagate' the press event to any element below the underlay

### 😯 Current Behavior

The press event is 'propagating' to the element below the underlay

### 🖥️ Steps to Reproduce

(iOS 17.4.1, Chrome latest version)

https://github.com/adobe/react-spectrum/assets/35581719/d3b764c2-656b-47c4-b79c-66cfc7d4bffd

(MacOS 14.4.1, Chrome latest version)

https://github.com/adobe/react-spectrum/assets/35581719/9e03f646-b649-4144-a6b1-24fc38b6163e

### Version

1.2.0

### What browsers are you seeing the problem on?

Chrome, Safari

### What operating system are you using?

iOS 17.4.1

**Comment by sookmax** [comment]
Looks like the same issue as https://github.com/adobe/react-spectrum/issues/1513

**Comment by andreslemusm** [comment]
> Looks like the same issue as https://github.com/adobe/react-spectrum/issues/1513

Yes, it is. Thank you!
