### ISSUE TITLE
eslint-plugin-jsdoc dependency version forces node version <=19

### ISSUE THREAD

**Issue by Renegade334** [adobe/react-spectrum#6344]
### Provide a general summary of the issue here

The current dependency version of eslint-plugin-jsdoc has an `engines` tag that forces a maximum Node version of 19, which has been out-of-support for nearly a year. In a build environment, running `yarn install` on node >=20 raises an exception and aborts.

It looks like the CircleCI tests are set to run on a Node 18 image, hence this not being picked up by the install checks.

### 💁 Possible Solution

Update the eslint-plugin-jsdoc dependency to version 43.0.8 or higher.

Additionally, Node 18 is no longer the active LTS version, so it might be worth bumping CircleCI to test on version 20.

**Comment by Renegade334** [comment]
#6344 appears to have become the primary issue for this.

**Comment by snowystinger** [comment]
Thanks, I missed this one, apologies. I'll close this one in favor of the other
