### ISSUE TITLE
Input in HiddenSelect component is not hidden from AutoFill, so it gets the value autofilled instead of the Select field below it

### ISSUE THREAD

**Issue by matthewkoenigs** [adobe/react-spectrum#6351]
### Provide a general summary of the issue here

We have a form with a state dropdown and it uses the HiddenSelect component.  That component writes in an input field above the select field and when the browser autofills in the address fields, it skips the State dropdown.  This is because the autofill is mapping the hidden field to fill in State, which doesn't update the dropdown once it's updated.  It would be greatly beneficial if the hidden value were given type="hidden".

### 🤔 Expected Behavior?

Hidden input field should have type="hidden"

### 😯 Current Behavior

Hidden input field does not have type="hidden" and is not able to be customized using props passed along to the HiddenSelect component.  Every prop I try to pass to it just goes to the select input field.

Also, why is this being added to the hidden field?  data-gtm-form-interact-field-id?

### 💁 Possible Solution

Either add type="hidden" directly to that input (because it is being built by the HiddenSelect component, so it would obviously be hidden.  Or, provide a way through props passed into the HiddenSelect component to add type="hidden" directly to that hidden field and not the select field.
You could also add something to the hidden input field to pass along that autofilled value to the select dropdown it's attached to.

### 🔦 Context

When users are trying to autofill their address into a form as they are registering or trying to check out of our site, it fills in every field except for the state dropdown because the hidden input value is taking the autofill value and not passing it along to the select field.

### 🖥️ Steps to Reproduce

Go to this site https://www.whitehouseblackmarket.com
Add any product
Then go to https://www.whitehouseblackmarket.com/store/checkout
Click on any field and let AutoFill complete the fields.  It totally skips the State dropdown because it's filling in the hidden text field.

### Version

3.11.5

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

Mac OS

### 🧢 Your Company/Team

Chicos FAS

**Comment by snowystinger** [comment]
`gtm` seems like something added by Google Tag Manager? or some other extension you might have installed?

I tried the auto fill on that site and I the state field populated with "California", which is expected for me. Is it still an issue for you? do you have another example? and what is responsible for autofilling for you? Dashlane is working for me.

**Comment by matthewkoenigs** [comment]
@snowystinger Yes.  I figured out the data being added to the hidden field by our Google Tag Manager script.
And I came up with a workaround for the autofill issue on the site I provided in the steps to reproduce.

But, I still think it's a viable request to add type="hidden" to the hidden field or allow it to be passed to the hidden field using props for the HiddenSelect component.  That would at least make it easier for future developers using that component that comes with this library.

**Comment by snowystinger** [comment]
What was the workaround?

**Comment by matthewkoenigs** [comment]
I trigger the form to do an onchange once on load and after it does that, the autofill finds the correct fields.

**Comment by snowystinger** [comment]
I'm going to close this for now until we get a reproducible example.
There may also be nothing we can do about it given this set of comments https://github.com/adobe/react-spectrum/blob/14f324fe890fcedc6e34889d9b04d5d6bfeb8380/packages/%40react-aria/select/src/HiddenSelect.tsx#L87

Thanks for the issue!

**Comment by matthewkoenigs** [comment]
Though I came up with a workaround, I still think adding "hidden" to the hidden field is a simple and important step in making your Hidden Select component easier for future users to integrate into their applications.
