### ISSUE TITLE
Source maps not included for `@react-aria` packages

### ISSUE THREAD

**Issue by short-dsb** [adobe/react-spectrum#6355]
### Provide a general summary of the issue here

Source maps are not included in the `@react-aria` packages, resulting in extensive console spam and (presumably) minified errors.

### 🤔 Expected Behavior?

Source maps are included and there’s no console spam.

### 😯 Current Behavior

Multiple warnings in the console, for example:

```
WARNING in ./node_modules/@react-aria/utils/dist/useObjectRef.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from './node_modules/@react-aria/utils/dist/useObjectRef.mjs.map' file: Error: ENOENT: no such file or directory, open './node_modules/@react-aria/utils/dist/useObjectRef.mjs.map'
```

### 💁 Possible Solution

Include the source maps in a new release.

### 🔦 Context

Console spam makes it difficult to identify actual warnings and errors.

### 🖥️ Steps to Reproduce

These are visible whenever running an app locally in development mode.

### Version

* `@react-aria/interactions` 3.21.2
* `@react-aria/ssr` 3.9.3
* `@react-aria/utils` 3.24.0

### What browsers are you seeing the problem on?

Other

### If other, please specify.

N/A

### What operating system are you using?

N/A

**Comment by snowystinger** [comment]
Looks like that map is missing for some reason https://www.unpkg.com/browse/@react-aria/utils@3.24.0/dist/
Thanks for the issue!

**Comment by frenicohansen** [comment]
Got the same warning for @internationalized/date. Source maps for .mjs are also missing.

https://unpkg.com/browse/@internationalized/date@3.5.3/dist/

**Comment by NamesMT** [comment]
+1 `@internationalized/date` console spam

**Comment by devongovett** [comment]
This is now released in a new patch update for all packages.

**Comment by smw-1211** [comment]
Experiencing the same for many other packages of @react-aria:

1. @react-aria/overlays@3.22.1
2. @react-aria/tooltip@3.7.4

Mostly for all the dist files of these 2 packages, source maps are not included.

Is there any way we can fix it other than waiting for a new release being dumped? 

Or is there any assurance of this issue getting fixed for these packages in the latter release?
