### ISSUE TITLE
Programmatically toggle Switch

### ISSUE THREAD

**Issue by guygit** [adobe/react-spectrum#6375]
### Provide a general summary of the issue here

The docs do not mention the use case how to programmatically trigger the Switch.
Since you are exposing an inputRef property, I assumed I could do it like so:

`
useEffect(() => {
   ref.current.checked = true;
}, [update]

<Switch inputRef={ref}>..</Switch>
`

However that doesn't work.

### 🤔 Expected Behavior?

Switch should toggle

### 😯 Current Behavior

Switch doesn't toggle

### 🖥️ Steps to Reproduce

`
useEffect(() => {
   ref.current.checked = true;
}, [update]

<Switch inputRef={ref}>..</Switch>
`

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

mac

**Comment by reidbarber** [comment]
You should use a [controlled value](https://react-spectrum.adobe.com/react-aria/Switch.html#controlled-value) for this use case, and update the value programmatically.

The visually hidden input is dependent on the state of the Switch component, which wouldn't get updated in that case.

**Comment by guygit** [comment]
Thx for the feedback.

I already tried that as well, but I cannot observe that the Switch is actually moving.
`
  const [value, setValue] = useState('low');
  useEffect(() => {
    setTimeout(() => {
      setValue('high');
    }, 2000);
  }, []);
              <Switch name="power" value={value}>
                Lo bro
              </Switch>
`

**Comment by reidbarber** [comment]
Try passing `isSelected={selected}`, where `selected` is a boolean. The `value` attribute is used for the form element value.

**Comment by guygit** [comment]
Reid - fantastic! (I was thinking "isSelected" was a read-only prop)

Thank you very much!
