### ISSUE TITLE
Not compatible with `@types/react@19`

### ISSUE THREAD

**Issue by SimenB** [adobe/react-spectrum#6388]
### Provide a general summary of the issue here

Following the instructions in the upgrade blog post gives errors from React Aria.

https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-deprecated-typescript-types

```
node_modules/@react-aria/textfield/dist/types.d.ts:2:10 - error TS2305: Module '"react"' has no exported member 'DOMFactory'.

2 import { DOMFactory, HTMLAttributes, LabelHTMLAttributes, ReactDOM, RefObject } from "react";
           ~~~~~~~~~~

node_modules/@react-aria/textfield/dist/types.d.ts:2:59 - error TS2305: Module '"react"' has no exported member 'ReactDOM'.

2 import { DOMFactory, HTMLAttributes, LabelHTMLAttributes, ReactDOM, RefObject } from "react";
```

### 🤔 Expected Behavior?

No TypeScript error

### 😯 Current Behavior

Errors! 😧 

### 🖥️ Steps to Reproduce

I can put one together if you really need it, but it's just imports in your code that needs to be updated.

https://github.com/adobe/react-spectrum/blob/5cacbdbf88b8c6d7f5d3fb741c2b7ccddf8def7f/packages/%40react-aria/textfield/src/useTextField.ts#L14-L22

### Version

`react-aria-components@1.2.0`

### What browsers are you seeing the problem on?

Other

### If other, please specify.

TypeScript error

### What operating system are you using?

macOS

**Comment by reidbarber** [comment]
Related https://github.com/adobe/react-spectrum/issues/6276

**Comment by SimenB** [comment]
Ah, right. That's probably a better issue to track. Thanks!
