### ISSUE TITLE
The instructions for client side routing for Tantsack Router doesn't work.

### ISSUE THREAD

**Issue by MAST1999** [adobe/react-spectrum#6413]
### 🙋 Documentation Request

Currently, if you implement it as the documentation has explained, you get this error:
![image](https://github.com/adobe/react-spectrum/assets/48868969/773f8ee7-8e5d-462e-b178-5edb898d3906)

To get rid of the error, you can change it to this:
```ts
declare module 'react-aria-components' {
  interface RouterConfig {
    href: ToPathOption<RegisteredRouter>;
    routerOptions: Omit<NavigateOptions, keyof ToOptions>;
  }
}
```

But this makes the `href` becomes just `string`, and you get no auto complete.

The way to get autocomplete is doing this:
```ts
declare module 'react-aria-components' {
	interface RouterConfig {
		href: ToPathOption<RegisteredRouter, '/', '/'> | ({} & string);
		routerOptions: Omit<NavigateOptions, 'to' | 'from'>;
	}
}
```

And change the router provider to this:
```ts
function RootComponent() {
	const router = useRouter();

	return (
		<RouterProvider
			navigate={(to, options) =>
				router.navigate({
					...options,
					to: to as ToPathOption<RegisteredRouter, '/', '/'>,
				})
			}
			useHref={(to) => {
				return router.buildLocation({ to }).href;
			}}
		>
			<Outlet />
		</RouterProvider>
	)
}
```
Now you will get auto complete in the links, and you can use any string as well:
![image](https://github.com/adobe/react-spectrum/assets/48868969/13b903ae-a6ad-4f17-b273-5352be1ae393)

This would also enable using the `params` and `search` from `tanstack/react-router` to be typesafe:
![image](https://github.com/adobe/react-spectrum/assets/48868969/00eec871-7c6f-4a8b-b69c-8e41299e54d0)

But right now since there is no way to constrict them based on the given `href` they show all the options for all the routes.

I think the way to fix this would be to give `RouterConfig` a generic string parameter and pass it to `ToPathOption` but I'm not sure.

```ts
declare module 'react-aria-components' {
	interface RouterConfig<Path extends string> {
		href: ToPathOption<RegisteredRouter, '/', Path> | ({} & string);
		routerOptions: Omit<NavigateOptions<RegisteredRouter, '/', Path>, 'to' | 'from'>;
	}
}
```

I'm not too familiar with how the types are set up for React Aria, but what I'm hoping for is this will link the `href` value to `ToPathOption` and `NavigateOptions` and show the correct values for `search` and `params` options.

**Comment by MAST1999** [comment]
I tried to create a Stackblitz for this but uses an older version of typescript and I can't exactly reproduce it:
https://stackblitz.com/edit/tanstack-router-hhpjdc?file=src%2Froutes%2F__root.tsx&preset=node

Had to remove the `| ({} & string)` since it wasn't working the typescript version Stackblitz is using.

**Comment by MAST1999** [comment]
Here's an example that is passing the params using the `routerOptions`: https://stackblitz.com/edit/tanstack-router-hhpjdc?file=src%2Froutes%2F__root.tsx,src%2Froutes%2Fposts.tsx&preset=node

**Comment by CHE1RON** [comment]
However, an "official" way to handle this would be much appreciated, so I'm bumping this .. 🙏

**Comment by levrik** [comment]
Since `useHref` also gets only the `href` passed it cannot construct a correct link with `params` which would need to get interpolated into `href`. This breaks link preview on hover in browsers as it shows something like `/projects/$id` instead of `/projects/123`.

**Comment by levrik** [comment]
I played around with the suggested solution by @MAST1999. I needed to do some changes but it's starting to work. `routerOptions` seems to be typed according to `href` now but `href` auto-completion is broken for some reason now. Still looking into it.

**Comment by devongovett** [comment]
Looks like the docs would need to be updated. This used to work but there have been some updates to TanStack Router's types that broke it. This should work instead:

```ts
import {ToOptions, NavigateOptions} from '@tanstack/react-router';

declare module 'react-aria-components' {
  interface RouterConfig {
    href: ToOptions['to'];
    routerOptions: Omit<NavigateOptions, keyof ToOptions>;
  }
}
```

You could also consider typing `href` as an object containing properties like `params` as well by making `href` take `ToOptions`. See https://github.com/adobe/react-spectrum/issues/6587#issuecomment-2224235268.

**Comment by devbytyler** [comment]
The examples differ between the Spectrum and TanStack docs, but neither works exactly right:

**Spectrum**: Extend RouterConfig to use TanStack
```tsx
import {type NavigateOptions, type ToOptions, useRouter} from '@tanstack/react-router';
import {defaultTheme, Provider} from '@adobe/react-spectrum';

declare module '@adobe/react-spectrum' {
  interface RouterConfig {
    href: ToOptions['to'];
    routerOptions: Omit<NavigateOptions, keyof ToOptions>;
  }
}

function RootRoute() {
  let router = useRouter();
  return (
    <Provider
      theme={defaultTheme}
      router={{
        navigate: (to, options) => router.navigate({ to, ...options }),
        useHref: (to) => router.buildLocation({ to }).href
      }}
    >
      {/* ...*/}
    </Provider>
  );
}
```
_Problem with above approach_: We lose out on the TanStack goodies such as `preload`, `activeProps`, and `activeOptions`. We're constrained to the props defined on RAC `<Link/>`.

**TanStack**: Use createLink to extend with RAC hooks.
```tsx
import * as React from 'react'
import { createLink, LinkComponent } from '@tanstack/react-router'
import {
  mergeProps,
  useFocusRing,
  useHover,
  useLink,
  useObjectRef,
} from 'react-aria'
import type { AriaLinkOptions } from 'react-aria'

interface RACLinkProps extends Omit<AriaLinkOptions, 'href'> {
  children?: React.ReactNode
}

const RACLinkComponent = React.forwardRef<HTMLAnchorElement, RACLinkProps>(
  (props, forwardedRef) => {
    const ref = useObjectRef(forwardedRef)

    const { isPressed, linkProps } = useLink(props, ref)
    const { isHovered, hoverProps } = useHover(props)
    const { isFocusVisible, isFocused, focusProps } = useFocusRing(props)

    return (
      <a
        {...mergeProps(linkProps, hoverProps, focusProps, props)}
        ref={ref}
        data-hovered={isHovered || undefined}
        data-pressed={isPressed || undefined}
        data-focus-visible={isFocusVisible || undefined}
        data-focused={isFocused || undefined}
      />
    )
  },
)

const CreatedLinkComponent = createLink(RACLinkComponent)

export const CustomLink: LinkComponent<typeof RACLinkComponent> = (props) => {
  return <CreatedLinkComponent preload={'intent'} {...props} />
}
```
_Problem with above approach_: AFAIK, `AriaLinkOptions` doesn't fully extend `React.AnchorHTMLAttributes<HTMLAnchorElement>` so things like `className` disappear from `CustomLink.activeProps`.

The reason I say doesn't _fully_ extend is because I tried the custom link approach and extended both `React.AnchorHTMLAttributes<HTMLAnchorElement>` and `AriaLinkOptions` but there is some overlap that causes conflicts (`onFocus`, `onBlur`, ...etc). I tried `<Omit>`ing the conflicting props, but then the RAC hooks were not satisfied. Either way, the HTMLAnchor Props still weren't available in the `CustomLink.activeProps`.

So.... any ideas?
