### ISSUE TITLE
Positioning popovers relative to a virtual element (support right-click context menus)

### ISSUE THREAD

**Issue by tryggvigy** [adobe/react-spectrum#6426]
### Provide a general summary of the feature here

Hey folks, I wanted to gauge interest in having first class support in `react-aria` / `react-aria-components` for patterns like right click context menus. 

Perhaps this should only be supported for menus, in that case it could perhaps be supported via a new trigger-type

```tsx
<MenuTrigger trigger="contextmenu">
```

### 🤔 Expected Behavior?

The first child of MenuTrigger could be any element that receives a `onContextMenu` prop to trigger it's menu on `'contextmenu'` events.

There is probably a way to describe this functionality more accurately in the lower layers of `react-aria` and `react-stately` but I'm fairly new to this library and not familiar enough with the architecture :smi

### 😯 Current Behavior

Currently right click menus can be implemented by replacing the trigger ref with a `{getBoundingClientRect: () => DOMRect }` type and continuously updating the position of that DOMRect based on the mouse click coordinates. See code sandbox below

### 💁 Possible Solution

I don't want to speculate too much on the details of how the API should be structured since I've not spent enough time thinking about it. But one way would be 

```
<MenuTrigger trigger="contextmenu">
  {/* The component that gets onContextMenu handler.
        Does not need to be interactive. */}
  <Box />
  {/* The menu to pop up */}
  <MyMenu />
</MenuTrigger>

```

### 🔦 Context

The usecase is to implement UIs similar to the native MacOS context menus
<img width="409" alt="image" src="https://github.com/adobe/react-spectrum/assets/2373958/53e508f1-db2a-4e18-a5ab-01421201a033"> 

or figmas context menus
<img width="326" alt="image" src="https://github.com/adobe/react-spectrum/assets/2373958/be5fbf3d-9b07-4728-a050-3f8cd05e66e3">

See floating-ui docs about virtual elements https://floating-ui.com/docs/virtual-elements

### 💻 Examples

They can be implemented with some effort since react-aria is so incredibly flexible (love that). 

See [code sandbox](https://codesandbox.io/p/sandbox/silent-waterfall-rm238d?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwg5f9yr00063b6lw6xtfr7p%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwg5f9yr00023b6llacnds2c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwg5f9yr00033b6lrrksdsb5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwg5f9yr00053b6le93mrlaf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwg5f9yr00023b6llacnds2c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwg5f9yq00013b6lx72m5skj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clwg5f9yr00023b6llacnds2c%2522%252C%2522activeTabId%2522%253A%2522clwg5f9yq00013b6lx72m5skj%2522%257D%252C%2522clwg5f9yr00053b6le93mrlaf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwg5f9yr00043b6l3gpgtktm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwg5f9yr00053b6le93mrlaf%2522%252C%2522activeTabId%2522%253A%2522clwg5f9yr00043b6l3gpgtktm%2522%257D%252C%2522clwg5f9yr00033b6lrrksdsb5%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwg5f9yr00033b6lrrksdsb5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by snowystinger** [comment]
I don't think we have a big interest in supporting context menus. Mostly because they are only for mouse users and are frequently (not on purpose though) used without other input methods being considered.
It's a bit of a slippery slope argument though, so I won't say never. Only that it's not a priority.

**Comment by tryggvigy** [comment]
That's fair. It's possible albeit a bit awkward to do context menus today. Feel free to close this issue 👍

**Comment by devongovett** [comment]
FWIW, this could be made easier to do, but it is possible to implement today using the offset and crossOffset props props on Popover. Basically force the placement to always bottom left, and then adjust the offset relative to that.

https://stackblitz.com/edit/rac-context-menu?file=src%2FApp.tsx
