### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by osdiab** [adobe/react-spectrum#6445]
### Provide a general summary of the feature here

Allow for react 19 as peer dependency for react aria packages, now that NextJS 15 RC is released

### 🤔 Expected Behavior?

No peer dependency errors, works with React 19

### 😯 Current Behavior

Peer dependency errors	

### 💁 Possible Solution

Loosen the dependency versions to allow 19.x for `react` and `react-dom`, test that all is still working

### 🔦 Context

Next 15 RC requires a react 19 build

**Comment by snowystinger** [comment]
Being handled in https://github.com/adobe/react-spectrum/pull/6437
