### ISSUE TITLE
Tooltip.isOpen: position not adjusted to the component within the TooltipTrigger

### ISSUE THREAD

**Issue by unional** [adobe/react-spectrum#6505]
### Provide a general summary of the issue here

When using the `isOpen` props directly, the `Tooltip` does not position correctly.

```tsx
<TooltipTrigger>
  <Butto>Top End</Button>
  <Tooltip isOpen placement="top end">
    top end tooltip
  </Tooltip>
</TooltipTrigger>
```

I try to use this `isOpen` property to make multiple tooltip to show for taking a snapshot in storybook.

In the example below, I add `isOpen` to both `top start` and `top end`.

### 🤔 Expected Behavior?

<img width="1275" alt="image" src="https://github.com/adobe/react-spectrum/assets/3254987/0056a695-1f6c-4306-b00f-eae1a254217b">

(it renders correctly after I hover over them)

### 😯 Current Behavior

<img width="1172" alt="image" src="https://github.com/adobe/react-spectrum/assets/3254987/a3a69431-8bc1-407c-95b4-65935b44a955">

### 🖥️ Steps to Reproduce

tbd

### Version

react-aria-components 1.1.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

### 🧢 Your Company/Team

Palo Alto Networks

**Comment by unional** [comment]
btw this is how it looks like when I add `isOpen` to everyone in there:
<img width="1271" alt="image" src="https://github.com/adobe/react-spectrum/assets/3254987/8fb2fc70-9bf7-4ab6-b106-b999dc0dd460">

After "kicking" them back in place:

<img width="1186" alt="image" src="https://github.com/adobe/react-spectrum/assets/3254987/d553554b-3b5e-462a-9c1d-8a73ade2c531">

**Comment by unional** [comment]
Also, the position of the tooltip does not update if I use `isOpen` and resize the window.

**Comment by snowystinger** [comment]
Looks like it's working to me https://github.com/adobe/react-spectrum/blob/6e57855257f54738418f98c37efae798bf9fb4ad/packages/react-aria-components/stories/Tooltip.stories.tsx#L116

Which can be seen here https://reactspectrum.blob.core.windows.net/reactspectrum/6e57855257f54738418f98c37efae798bf9fb4ad/storybook/index.html?path=/story/react-aria-components--tooltip-arrow-boundary-offset-example&providerSwitcher-express=false on the latest build from main

Resizing window seems to work fine as well.

Can you provide a reproduction in a codesandbox/stackblitz/equivalent?

**Comment by unional** [comment]
Hi, I updated to 1.2.1 and still observe the same issue. Will try to create a repro.

**Comment by unional** [comment]
I can see the difference.
In your example, you are setting `isOpen` on the `TooltipTrigger`.
In my example, I'm setting `isOpen` on the `Tooltip`.

It is working on `TooltipTrigger`, but not on `Tooltip`

**Comment by snowystinger** [comment]
That looks more like a bug that `TooltipProps` is extending from `OverlayTriggerProps`. You should be controlling it from `TooltipTrigger`
