### ISSUE TITLE
ListBoxItem wrapper can't access ListBox contexts

### ISSUE THREAD

**Issue by ArrayKnight** [adobe/react-spectrum#6510]
### Provide a general summary of the issue here

When establishing reusable wrappers for ListBox components, I'm expecting to be able to access the multiple contexts that ListBox implements: https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/ListBox.tsx#L244

### 🤔 Expected Behavior?

We should be able to access all provided contexts

### 😯 Current Behavior

All contexts come back as null and never become provided

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/magical-yalow-ft94s2

### Version

1.2.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac

**Comment by snowystinger** [comment]
Due to a quirk in the way we have to render things to make the Collections API possible, we can only expose that context inside the item, like so
https://codesandbox.io/p/sandbox/adoring-ully-5gjkzv

**Comment by snowystinger** [comment]
I'm going to close this as answered, feel free to ping again if there's something else

**Comment by snowystinger** [comment]
A good idea 👍🏻
