### ISSUE TITLE
Support `textarea` in `useTextField`

### ISSUE THREAD

**Issue by Andarist** [adobe/react-spectrum#652]
# 🙋 Feature Request

As text inputs & textareas are super similar it would be great to add intuitive support for textareas to `useTextField`

## 🤔 Expected Behavior

Being able to spread `inputProps` onto `<textarea/>`

## 😯 Current Behavior

Currently, `type` prop is always returned and thus it lands on the textarea node when spreading as-is.

## 💁 Possible Solution

Add `inputElementType` prop - similar to `labelElementType`.

**Comment by devongovett** [comment]
Good point. That makes sense to me. 👍

**Comment by Andarist** [comment]
Is the proposed API OK for you? A separate issue is that there are also `contenteditable` elements that could benefit from a hook like this, but getting it right for contenteditables might require significantly more thought 🤔

**Comment by devongovett** [comment]
Yeah I think the API is good.

Content editable seems like a separate challenge, and potentially a separate hook. I'd need to look into how the accessibility is meant to work for that.
