### ISSUE TITLE
Navigation through submenus (Menu/SubmenuTrigger) with key arrows are inverse when the submenu has placement="left"

### ISSUE THREAD

**Issue by tordsta** [adobe/react-spectrum#6544]
### Provide a general summary of the issue here

It is the horizontal navigation with arrow keys in the menus and submenus that is the problem. My assumption is that it has been developed and tested with the default directions, where it works fine. But when you change the side the popover is displayed on ("left" instead of default "right"), there is no change in behavior of the key arrows. It still follows the right side behavior.

### 🤔 Expected Behavior?

When opening submenus with arrow keys, the key that opens the submenu should align with the placement of the popover. If the popover is placed to the left, its the left arrow key that opens it and the right arrow key that closes it.   

### 😯 Current Behavior

The current behavior is that popovers placed to the left in a submenu, opens on press of arrow key right, and closes on press of arrow key left.  

### 💁 Possible Solution

Im guessing there are some internal key press logic that can change based on popover placements, for popovers inside a SubmenuTrigger. 

### 🔦 Context

Specifically a menu with a menu item "set status", where the submenu contains three different statuses one can select. The menu trigger is on the right side of the page (settings icon), therefore the submenus needs to expand to the left. 

### 🖥️ Steps to Reproduce

Code sandbox
https://codesandbox.io/p/sandbox/priceless-waterfall-c2hwsq

### Version

1.2.1

### What browsers are you seeing the problem on?

Other

### If other, please specify.

Arc

### What operating system are you using?

macOS Sonoma 14.1

### 🧢 Your Company/Team

Propely

**Comment by reidbarber** [comment]
I'm not sure if visual placement should have an effect on which key is used based on the [ARIA APG](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/#keyboardinteraction). I'll see if I can get some more input on this.

**Comment by reidbarber** [comment]
Discussed with @majornista:

> No, I don’t think it should change based on the positioning of the menu. The behavior should remain consistent because it is necessary for blind/low-vision users as well as keyboard only users. A good example of this consistency is in the submenus within the Customize and control Google Chrome menu in the upper right corner of the Chrome browser window.

Thanks for creating the issue, it was good to get this clarified!
