### ISSUE TITLE
Tooltip gets stuck to the screen while the user is scrolling over the screen.

### ISSUE THREAD

**Issue by GeetanshuGulati** [adobe/react-spectrum#6546]
### Provide a general summary of the issue here

We are facing an issue with the tooltip wrapped over the action button.
The tooltip gets stuck to the screen while the user is scrolling over the screen.

code sandbox https://codesandbox.io/p/sandbox/infallible-chatterjee-m6mx6j

https://github.com/adobe/react-spectrum/assets/34887112/01178f34-466b-47ae-a10b-1006652b5525

### 🤔 Expected Behavior?

tooltip should not stick to screen while scrolling

### 😯 Current Behavior

tooltip stick to screen while scrolling

### 🖥️ Steps to Reproduce

code sandbox https://codesandbox.io/p/sandbox/infallible-chatterjee-m6mx6j

### Version

3.35.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

platform independent reproducable

**Comment by snowystinger** [comment]
Thanks for reporting, looks like we need to pass 
```
onClose: () => state.close(true)
```
to useOverlayPosition in TooltipTrigger
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/tooltip/src/TooltipTrigger.tsx#L73

Would you like to contribute and write a test for it?

**Comment by rtwayland** [comment]
I'm seeing this for react-aria-components as well

**Comment by pr7prashant** [comment]
I've faced this as well before. @snowystinger can I pick this one. Seems to be open and idle for a while now. Thanks
