### ISSUE TITLE
`isDismissable` prop for `Modal` doesn't work when using a `ModalOverlay` component

### ISSUE THREAD

**Issue by daninus14** [adobe/react-spectrum#6553]
### Provide a general summary of the issue here

`isDismissable` prop for `Modal` doesn't work when using a `ModalOverlay` component.

This means that the following code doesn't function as expected, which is that a click outside the modal will dismiss the modal:
> isDismissable
> Whether to close the modal when the user interacts outside it.

```javascript
<DialogTrigger>
  <Button>Open modal</Button>
  <ModalOverlay className="my-overlay">
    <Modal isDismissable className="my-modal">
      <Dialog>
        {({close}) => <>
          <Heading slot="title">Notice</Heading>
          <p>This is a modal with a custom modal overlay.</p>
          <Button onPress={close}>Close</Button>
        </>}
      </Dialog>
    </Modal>
  </ModalOverlay>
</DialogTrigger>
```

`isDismissable` only works as expected when the is no ModalOverlay component wrapping the modal.

There is **no** workaround to have a `onPress` on the `ModalOverlay` to set the state of the `Modal` to close like in the example: https://react-spectrum.adobe.com/react-aria/Modal.html#controlled-open-state

The clicks outside the `Modal` and in the `ModalOverlay` are not registering at all.

### 🤔 Expected Behavior?

This means that the following code doesn't function as expected, which is that a click outside the modal will dismiss the modal:
> isDismissable
> Whether to close the modal when the user interacts outside it.

### 😯 Current Behavior

Nothing happens when clicking outside of the Modal.

### 💁 Possible Solution

Besides solving this bug, allowing for the ModalOverlay to generate an onPress event would've provided a simple workaround, and is something that makes sense to expect from any component we use...

### 🖥️ Steps to Reproduce

```javascript
<DialogTrigger>
  <Button>Open modal</Button>
  <ModalOverlay className="my-overlay">
    <Modal isDismissable className="my-modal">
      <Dialog>
        {({close}) => <>
          <Heading slot="title">Notice</Heading>
          <p>This is a modal with a custom modal overlay.</p>
          <Button onPress={close}>Close</Button>
        </>}
      </Dialog>
    </Modal>
  </ModalOverlay>
</DialogTrigger>
```

`isDismissable` only works as expected when the is no ModalOverlay component wrapping the modal.

### Version

1.2.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOs

**Comment by yihuiliao** [comment]
I think you'll need to place`isDismissable` on the `ModalOverlay` component instead of the `Modal` component. Someone else reported that this wasn't clear in our docs (https://github.com/adobe/react-spectrum/issues/6277). Let us know if that solves your issue.

**Comment by daninus14** [comment]
Thank you! 

It appears nowhere in the page (i found out a seemingly hidden link here https://react-spectrum.adobe.com/react-aria/Modal.html#advanced-customization which pops up props for modal overlay now that you mentioned it). It should be either in advanced customization, or really ModalOverlay should have a page for itself. 

How many other components don't have their own page? As a user I think the documentation would be much better if each component has a page for itself. This is an open source project and I am tremendously grateful for the contribution.

Thanks so much, at least now hopefully people will find this by googling this issue :D

**Comment by daninus14** [comment]
Oh by the way, I think adding that to the tailwind example may also be very helpful. I was using a workaround by using plain css and not using the modal overlay at all
