### ISSUE TITLE
Code mismatch in published packages & github repo

### ISSUE THREAD

**Issue by NarendraKuruva** [adobe/react-spectrum#6580]
### Provide a general summary of the issue here

I've cloned the repo and trying to copy the Combobox & ListBox related components as there are major UI changes in my app's combobox & ListBox

When I'm copying `ListBoxBase`, in `useListBoxLayout` hook while initialising `ListLayout`, in published package code, there is `forceSectionHeaders` key being passed.

But when I'm doing the same in my repo (copying the hook), I'm not able to pass `forceSectionHeaders` to `ListLayout`.

Attached the error screenshot 
![image](https://github.com/adobe/react-spectrum/assets/102137869/d379f2fc-c4e6-40dc-80af-4cd825b4221d)

This is the type we have in ListLayoutOptions
![image](https://github.com/adobe/react-spectrum/assets/102137869/14f69c93-538f-4c6d-8704-8ce58e30cb9a)

This is the type we are getting in your repo(react-spectrum)
![image](https://github.com/adobe/react-spectrum/assets/102137869/2223eedc-e31e-449c-a162-ae6c4d8904ef)

We are using below react-spectrum packages
     "@react-spectrum/button": "3.16.4",
     "@react-spectrum/dialog": "3.8.11",
     "@react-spectrum/label": "3.16.6",
     "@react-spectrum/provider": "3.9.7",
     "@react-stately/collections": "3.10.7",
      "@react-stately/layout": "3.13.9",
      "@react-stately/list": "3.10.5",
      "@react-stately/overlays": "3.6.7",
      "react-stately": "3.31.1",
      "@react-aria/datepicker": "3.10.1",
      "@react-aria/listbox": "3.12.1",
      "@react-aria/overlays": "3.22.1",
      "@react-aria/separator": "3.3.13",
      "@react-aria/tabs": "3.9.1",
      "@react-aria/textfield": "3.14.5",
      "@react-aria/utils": "3.24.1",
      "@react-aria/virtualizer": "3.10.1",
      "react-aria": "3.33.1",

### 🤔 Expected Behavior?

Components should work fine without any typescript errors

### 😯 Current Behavior

Getting typescript errors

### 🖥️ Steps to Reproduce

1. Clone your repo
2. In a new react app, install latest combobox dependency packages
3. Copy your combobox and Listbox code

### Version

Not using react spectrum. Using components by directly copying

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

We are using above mentioned packages

### What operating system are you using?

Ubuntu 22.04.4 LTS

**Comment by snowystinger** [comment]
This is not a bug, main was last published May 21st. The code you're looking at was added two days ago in https://github.com/adobe/react-spectrum/pull/6535. When we publish next, it'll include the change.

**Comment by NarendraKuruva** [comment]
@snowystinger 

Then how can I check the code that was published on May 21st?

**Comment by snowystinger** [comment]
You can use the github tag feature
![Screenshot 2024-06-20 at 3 00 14 PM](https://github.com/adobe/react-spectrum/assets/698229/e807df8b-464d-4e8e-9613-5bcdc45061c8)
or through here: https://github.com/adobe/react-spectrum/tags

or you can consult releases https://react-spectrum.adobe.com/releases/index.html

or if you know the githash, by looking at commits or git blame or something, you can browse the repo as it was in that state
![Screenshot 2024-06-20 at 2 58 47 PM](https://github.com/adobe/react-spectrum/assets/698229/3f269404-616c-4a4e-8695-b95b5b712d34)

**Comment by NarendraKuruva** [comment]
> You can use the github tag feature ![Screenshot 2024-06-20 at 3 00 14 PM](https://private-user-images.githubusercontent.com/698229/341275827-e807df8b-464d-4e8e-9613-5bcdc45061c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjA2MTcsIm5iZiI6MTcxODg2MDMxNywicGF0aCI6Ii82OTgyMjkvMzQxMjc1ODI3LWU4MDdkZjhiLTQ2NGQtNGU4ZS05NjEzLTViY2RjNDUwNjFjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwNTExNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTQwYThmYjA0MDcyOTVhYTk5YWU3YzYyNTZmYzkwMmYzNGU5YjI0MjE4MzMyZDI5NGRjYTc2MDQzZDNlOGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kkTvWCyzpxjy6Lrdy7ZLOnYXhyAqaQGyPcFnfME67BQ) or through here: https://github.com/adobe/react-spectrum/tags
> 
> or you can consult releases https://react-spectrum.adobe.com/releases/index.html
> 
> or if you know the githash, by looking at commits or git blame or something, you can browse the repo as it was in that state ![Screenshot 2024-06-20 at 2 58 47 PM](https://private-user-images.githubusercontent.com/698229/341275565-3f269404-616c-4a4e-8695-b95b5b712d34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjA2MTcsIm5iZiI6MTcxODg2MDMxNywicGF0aCI6Ii82OTgyMjkvMzQxMjc1NTY1LTNmMjY5NDA0LTYxNmMtNGE0ZS04Njk1LWI5NWI1YjcxMmQzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwNTExNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzMxNDJlYTRiZThhZjEwMjQ3ZGQ0ZDM0OWRhMWNlMzVmOGY4YTIxMjI1MzcxYjMzNjZlZmYzNmU5NDE4NDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OR8-5DG_nMJcV5_wvCy6-GCdI6elZiwluMMUQ4_by34)

Got It :+1: :heavy_check_mark: 
Thank you
