### ISSUE TITLE
Popover with `<input autoFocus/>` scrolls to bottom

### ISSUE THREAD

**Issue by mJarsater** [adobe/react-spectrum#6604]
### Provide a general summary of the issue here

If a Popover contains an input which is using `autoFocus` the windows scrolls to the bottom when the Popover is opened.

https://github.com/adobe/react-spectrum/assets/62651103/06f19da0-e08f-49e6-ad8c-72c862c2862d

### 🤔 Expected Behavior?

The Popover should be able to contain inputs with autoFocus.

### 😯 Current Behavior

If a Popover contains an input which is using `autoFocus` the windows scrolls to the bottom when the Popover is opened.

### 🖥️ Steps to Reproduce

[code sandbox](https://codesandbox.io/p/sandbox/recursing-flower-prydcj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxsx63xt00063b6jyuj98uuc%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxsx63xt00023b6jy04cxh6i%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxsx63xt00033b6jskb6bv3o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxsx63xt00053b6jhupdk1tr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxsx63xt00023b6jy04cxh6i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxsx63xs00013b6jal9zxq1b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxsx6o6x003g3b6jmrv59gmg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A73%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxsx63xt00023b6jy04cxh6i%2522%252C%2522activeTabId%2522%253A%2522clxsx6o6x003g3b6jmrv59gmg%2522%257D%252C%2522clxsx63xt00053b6jhupdk1tr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxsx63xt00043b6j7kqmlgqh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxsx63xt00053b6jhupdk1tr%2522%252C%2522activeTabId%2522%253A%2522clxsx63xt00043b6j7kqmlgqh%2522%257D%252C%2522clxsx63xt00033b6jskb6bv3o%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxsx63xt00033b6jskb6bv3o%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

```jsx
import { Button, DialogTrigger, Input, Popover } from "react-aria-components";

function App() {
  return (
    <div style={{ height: "200vh" }}>
      <DialogTrigger>
        <Button>Open Dialog</Button>
        <Popover>
          Popover!
          <Input autoFocus />
        </Popover>
      </DialogTrigger>
    </div>
  );
}

export default App;
```

### Version

react-aria-components: 1.2.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What operating system are you using?

macOS Sonoma: 14.4.1

**Comment by LFDanLu** [comment]
https://github.com/adobe/react-spectrum/issues/4898 is related, does that work for you?

**Comment by mJarsater** [comment]
> #4898 is related, does that work for you?

Unfortunatly neither:

```jsx
import React from "react";
import { DialogTrigger, Button, Popover, Input } from "react-aria-components";

export default function App() {
  return (
    <div style={{ height: "200vh" }}>
      <DialogTrigger>
        <Button>Open Dialog</Button>
        <Popover>
          Popover!
          <Input ref={(ref) => ref?.focus()} />
        </Popover>
      </DialogTrigger>
    </div>
  );
}
```

nor 

```jsx
function App() {
  const ref = useRef<HTMLInputElement>(null);

  useEffect(() => {
    ref.current?.focus();
  }, [ref]);

  return (
    <div style={{ height: "200vh" }}>
      <DialogTrigger>
        <Button>Open Dialog</Button>
        <Popover>
          Popover!
          <Input ref={(ref) => ref?.focus()} />
        </Popover>
      </DialogTrigger>
    </div>
  );
}
```

works as expected.

**Comment by mJarsater** [comment]
Using a ref with focus in a separate render fixes this issue.

**Comment by eranimo** [comment]
> Using a ref with focus in a separate render fixes this issue.

Can you explain what you mean by that?
