### ISSUE TITLE
Meter component: issues identified by Axe DevTools

### ISSUE THREAD

**Issue by j-lefloch** [adobe/react-spectrum#6627]
### Provide a general summary of the issue here

Due to feedback on the progressbar role (with both meter and progressbar present), Axe DevTools reports a critical issue: The ARIA attributes aria-valuenow="0", aria-valuemin="0", aria-valuemax="100", and aria-valuetext="0 %" are not allowed on this element.

### 🤔 Expected Behavior?

No issue reported

### 😯 Current Behavior

-

### 💁 Possible Solution

Maybe consider excluding the progressbar role from the feedback mechanism

### 🖥️ Steps to Reproduce

Visible on official website:
https://react-spectrum.adobe.com/react-aria/Meter.html

### Version

last version

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS Sonoma 14.4.1

**Comment by reidbarber** [comment]
Do you have a link to the axe rule that is failing? https://dequeuniversity.com/rules/axe/html/4.9

I'm curious if there is a real issue with assistive technology. If not, this may be a false positive.

**Comment by j-lefloch** [comment]
You might be correct regarding the false positive issue.
Axe DevTools did not flag any issues after I manually removed either the meter or progressbar roles (via devtools), leaving only one value.
Here is the link to the axe rule that is failing: https://dequeuniversity.com/rules/axe/4.9/aria-allowed-attr?application=AxeChrome

**Comment by snowystinger** [comment]
This is a false positive. See https://github.com/adobe/react-spectrum/blob/6288d4a3a886a52473d763dde569e0f7fb33d11e/packages/%40react-aria/meter/src/useMeter.ts#L34
It looks like the FF bug has been closed, but the Chrome one is still open. Hopefully we'll be able to remove the fallback some day
