### ISSUE TITLE
ComboBox doesn't open when `onInputChange` updates items asynchronously

### ISSUE THREAD

**Issue by bmingles** [adobe/react-spectrum#6638]
### Provide a general summary of the issue here

By default, ComboBox opens when the user types unless there are no items. In cases where the `onInputChange` event is used to filter the items array asynchronously (e.g. if a search debounce is introduced), the ComboBox doesn't always open when the items have updated. Specifically if the items array changes from empty to populated, the CombBox remains closed after the user types the last character even if there is a match to be shown.

### 🤔 Expected Behavior?

When ComboBox is configured to open as user types, it should be able to respond to async items array updates.

### 😯 Current Behavior

ComboBox remains closed after async items update.

### 💁 Possible Solution

It could be helpful if there were some way to explicitly open the ComboBox after an async change is applied to the items array. Possibly exposing an `isOpen` prop to make it controlled.

### 🔦 Context

We need this feature in order to support debounced filtering of items in response to user input.

### 🖥️ Steps to Reproduce

Instructions in the comment header of App.tsx in this codesandbox
[https://codesandbox.io/p/sandbox/spectrum-combobox-not-opening-x29g3n](https://codesandbox.io/p/sandbox/spectrum-combobox-not-opening-x29g3n?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxxpzofc00063b6q79hl8jps%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxxpzofb00023b6qq6io4b73%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxxpzofb00033b6qmh0111kv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxxpzofb00053b6q1f8afe6g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxxpzofb00023b6qq6io4b73%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxxpzofb00013b6qch9129a0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clxxpzofb00023b6qq6io4b73%2522%252C%2522activeTabId%2522%253A%2522clxxpzofb00013b6qch9129a0%2522%257D%252C%2522clxxpzofb00053b6q1f8afe6g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxxpzofb00043b6q71w6doe0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxxpzofb00053b6q1f8afe6g%2522%252C%2522activeTabId%2522%253A%2522clxxpzofb00043b6q71w6doe0%2522%257D%252C%2522clxxpzofb00033b6qmh0111kv%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxxpzofb00033b6qmh0111kv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Version

3.35.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by LFDanLu** [comment]
I believe this is similar to via https://github.com/adobe/react-spectrum/issues/5234. Ideally there would be support for a controlled isOpen prop and/or handling this case automatically in useComboBoxState, but finagling the internal open state logic has proved to be quite difficult. I'll close this in favor of the other issue, feel free to reopen if that issue doesn't sufficiently cover your case.

As an aside, I'm beginning to think exposing the combobox's state's `open` on the combobox ref might be the best intermediate fix in the short term so at least users have a way to open the combobox when needed. https://github.com/adobe/react-spectrum/blob/81abb2185cb3a9c52a8feaf76a136c64852aea13/packages/%40react-spectrum/textfield/src/TextFieldBase.tsx#L66-L76 is an example of how we've created a similar imperative interface in Textfield
