### ISSUE TITLE
RAC ComboBox logs console warnings when used in a form

### ISSUE THREAD

**Issue by joshuajaco** [adobe/react-spectrum#6651]
### Provide a general summary of the issue here

When passing a `name` to a `react-aria-components` `ComboBox` we get the following warning messages in the console:

<details>
<summary>on render</summary>

```
 Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
```

<img width="632" alt="image" src="https://github.com/adobe/react-spectrum/assets/31038284/f2a08c9c-ae08-46df-b4d8-9f4a874aa3ed">
</details>

<details>
<summary>on change</summary>

```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
```

<img width="632" alt="image" src="https://github.com/adobe/react-spectrum/assets/31038284/3fb8b124-d9f8-4d3e-b640-fc43a5e47fe6">
</details>

### 🤔 Expected Behavior?

It does not show a warning

### 😯 Current Behavior

It shows a warning

### 🖥️ Steps to Reproduce

visit the [codesandbox](https://codesandbox.io/p/sandbox/sleepy-meadow-n7hkxr?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cly2pv7nw00073b6jx22fhjxv%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cly2pv7nw00033b6j1i4dqbqd%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cly2pv7nw00043b6ju3wj55t0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cly2pv7nw00063b6j87xotfe7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B48.283119255507366%252C51.716880744492634%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cly2pv7nw00033b6j1i4dqbqd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly2pv7nw00023b6j2rcmvzdw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A9%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cly2pv7nw00033b6j1i4dqbqd%2522%252C%2522activeTabId%2522%253A%2522cly2pv7nw00023b6j2rcmvzdw%2522%257D%252C%2522cly2pv7nw00063b6j87xotfe7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly2pv7nw00053b6jkrqg8mt1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cly2pv7nw00063b6j87xotfe7%2522%252C%2522activeTabId%2522%253A%2522cly2pv7nw00053b6jkrqg8mt1%2522%257D%252C%2522cly2pv7nw00043b6ju3wj55t0%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cly2pv7nw00043b6ju3wj55t0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) and open the console

### Version

react-aria-components@1.2.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you using?

MacOS

**Comment by snowystinger** [comment]
Should be fixed by https://github.com/adobe/react-spectrum/pull/6336 when we do our next release.
