### ISSUE TITLE
Quick double space hit on Number input adds '. ' to the field

### ISSUE THREAD

**Issue by wellguimaraes** [adobe/react-spectrum#6667]
### Provide a general summary of the issue here

https://react-spectrum.adobe.com/react-aria/NumberField.html

Try quickly hitting space twice on a number field and it'll add `. ` to the field.

Does it even make sense to allow space char?

### 🤔 Expected Behavior?

Nothing

### 😯 Current Behavior

`. ` is added to the field value.

### 💁 Possible Solution

Don't know yet.

### 🖥️ Steps to Reproduce

https://react-spectrum.adobe.com/react-aria/NumberField.html

Try quickly hitting space twice on a number field and it'll add `. ` to the field.

### Version

latest

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Safari, Other

### If other, please specify.

Arc (any Chromium based)

### What operating system are you using?

Mac OS 14.5

**Comment by wellguimaraes** [comment]
It's related to this config on MacOS:

![image](https://github.com/adobe/react-spectrum/assets/4805500/0a0c2498-9727-4708-954a-98bb1ec22576)

But I think it should be somehow prevented for NumberFields.

**Comment by snowystinger** [comment]
Some locales use space for group separators, so we can't ignore it. And periods are used for both group and decimal depending on the locale.

I'm not sure there is anything we can do about it since it's an OS level thing, not browser.
