### ISSUE TITLE
[RAC] Select options with same value are not shown 

### ISSUE THREAD

**Issue by ryo-manba** [adobe/react-spectrum#6670]
### Provide a general summary of the issue here

When using Select with the same id for options, they are not displayed. This is problematic because in forms, the id is reflected as the value. For example, both Italy and Vatican have the country code 39.

### 🤔 Expected Behavior?

The same value can be specified for options.

### 😯 Current Behavior

When trying to specify the same value for options, they are not displayed.

### 💁 Possible Solution

Instead of using `selectedKey` for the input value in HiddenSelect, it might be better to use the item's `textValue`. This may diverge from the intended use of `textValue` but could resolve the issue.

https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/select/src/HiddenSelect.tsx#L156

### 🔦 Context

Handling duplicate values in select options, such as country codes, is a valid use case and should be supported. 

### 🖥️ Steps to Reproduce

1. Access the following link
https://stackblitz.com/~/github.com/ryo-manba/select-same-value?file=src/app/page.tsx
2. Italy and Vatican share the same country code, so only the latter is displayed. 

### Version

react-aria-components: 1.2.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS Sonoma

**Comment by snowystinger** [comment]
I think it's better practice to separate the two and use a map to determine the country code instead. That way you know which country the user is actually trying to reach.

Can bring up with the team when everyone is back from shutdown since it technically works for native select's.

**Comment by ryo-manba** [comment]
Thanks you for your suggestion. That approach sounds good.
However, making it work similar to a native select might enhance usability even further. It would be great to use the `value` directly in `ListboxItem`, but since it accepts an object, some adjustments will be necessary.

**Comment by snowystinger** [comment]
I was thinking about this more. I don't think this is something we should try to support. React doesn't support it for creating a controlled Select. https://codesandbox.io/p/sandbox/wispy-breeze-g7tpcl?file=%2Fsrc%2FApp.js%3A11%2C75

It goes against the fundamental way that controlled components work. You would need to pass a unique identifier in any case, and if we try to make assumptions about that, I think it becomes harder to use, not easier.

I'm going to close this now, recommendation is still to create your own look up map if you need to group certain values.
