### ISSUE TITLE
Source maps are not included in most of the packages of react-aria

### ISSUE THREAD

**Issue by smw-1211** [adobe/react-spectrum#6672]
### Provide a general summary of the issue here

Experiencing this behaviour for packages of @react-aria:

@react-aria/overlays@3.22.1
@react-aria/tooltip@3.7.4

Is there any way we can fix it other than waiting for a new release being dumped?

Or is there any assurance of this issue getting fixed for these packages in the latter release?

### 🤔 Expected Behavior?

console should be clean without any warnings of missing source maps for dist files of these 2 packages.

### 😯 Current Behavior

Console warnings are visible for most of the dist files with missing source maps of these 2 packages:

@react-aria/overlays@3.22.1
@react-aria/tooltip@3.7.4

### 🖥️ Steps to Reproduce

Include these 2 packages to the dev dependencies and try running the server you will see console errors with warnings of missing source map files.
@react-aria/overlays@3.22.1
@react-aria/tooltip@3.7.4

### Version

NA

### What browsers are you seeing the problem on?

Other

### What operating system are you using?

Windows OS

**Comment by devongovett** [comment]
They are there as far as I can tell. Are you sure you have the latest version installed? Could you give more info? https://unpkg.com/browse/@react-aria/overlays@3.22.1/dist/

**Comment by smw-1211** [comment]
Apologies, I cannot share the SS of console warnings which I get due to security compliances.

As far as I can see from the resource which you shared, source maps are only for the module files.

For eg if you see in this image:

![image](https://github.com/user-attachments/assets/633c60d6-7ddc-4ce3-9441-63870bb05ccb)

- To **lv-LV.module.js** file --> map file is present.
- But if you see **lv-LV.js** file --> map file is missing which is showing warnings in the console.

This behavior has been observed for all the similar non-module files of this package. 

For @react-aria/overlays package - Only the module files have source maps but not other files. 

This is what I understand and I think needs to be fixed to clear the console warnings.
