### ISSUE TITLE
Focus problem when onHover is called in Select / Listbox

### ISSUE THREAD

**Issue by hpigeonfiteco** [adobe/react-spectrum#6673]
### Provide a general summary of the issue here

I am developing a basic select with a search bar, but I have a focus problem.

By default, I've set autofocus on a search bar. The problem is that **when I move the mouse over the ListBoxItem, I lose the focus of the search bar **because a focus event is called (on hover is trigger the focus).

### 🤔 Expected Behavior?

I'd like the focus not to be triggered when the mouse is moved over **ListBoxItems**.

### 😯 Current Behavior

When I move the mouse over **ListBoxItems**, it triggers an unnecessary focus and unfocus the search field.

### 🖥️ Steps to Reproduce

If you try to add a text field in the select and add autofocus to it, then move the mouse over the ListBoxItems, you should get the same behavior from me.

[https://react-spectrum.adobe.com/react-aria/Select.html](url)

### Version

React aria 3.33.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows

**Comment by majornista** [comment]
It sounds like the [ComboBox](https://react-spectrum.adobe.com/react-aria/ComboBox.html) would be a better fit than [Select](https://react-spectrum.adobe.com/react-aria/Select.html) for your use case. With ComboBox, the focus will stay within the input when you hover the expanded listbox.
