### ISSUE TITLE
ComboBox.allowsEmptyCollection resets input when inputValue starts scrolling

### ISSUE THREAD

**Issue by agscala** [adobe/react-spectrum#6675]
### Provide a general summary of the issue here

Setting ComboBox `allowsEmptyCollection={true}` causes the input to reset itself as soon as the input value is long enough to start scrolling:

![Screen Cast 2024-07-09 at 9 36 55 AM](https://github.com/adobe/react-spectrum/assets/73444/be9337be-854c-48e8-8d2d-560046d4f89f)

ComboBox works correctly when `allowsEmptyCollection` is false 🤔 

### 🤔 Expected Behavior?

When the input value starts overflowing the input component, it should scroll

### 😯 Current Behavior

When the input value starts overflowing the input component, it suddenly resets itself (if `allowsEmptyCollection` is true).

### 💁 Possible Solution

https://github.com/adobe/react-spectrum/blob/2964e9aafc281888cd65da5bd77512e7f999bd84/packages/%40react-aria/overlays/src/useCloseOnScroll.ts#L29-L63

`useCloseOnScroll` is kicking off the chain of events to reset the input.  I suspect that an event handler that's supposed to close the popover on page scroll is also getting triggered when an input scrolls.

### 🖥️ Steps to Reproduce

This is an example copied directly from the the ComboBox documentation, except with `allowsEmptyCollection` added.

Type until the input starts scrolling, and you'll see that the input instead clears itself.

```tsx
<ComboBox allowsEmptyCollection>
  <Label>Favorite Animal</Label>
  <div>
    <Input />
    <Button>▼</Button>
  </div>
  <Popover>
    <ListBox>
      <ListBoxItem>Aardvark</ListBoxItem>
      <ListBoxItem>Cat</ListBoxItem>
      <ListBoxItem>Dog</ListBoxItem>
      <ListBoxItem>Kangaroo</ListBoxItem>
      <ListBoxItem>Panda</ListBoxItem>
      <ListBoxItem>Snake</ListBoxItem>
    </ListBox>
  </Popover>
</ComboBox>
```

### Version

RAC 1.2.1,  @react-aria/overlays 3.22.1, react-aria 3.33.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

OSX

**Comment by yihuiliao** [comment]
I believe this has been fixed in https://github.com/adobe/react-spectrum/pull/6461 and should be part of our next release. I've tested it out locally and the issue didn't seem to occur but I would double check after our release to make sure this still isn't an issue

**Comment by agscala** [comment]
Great, thank you! I'll close this issue
