### ISSUE TITLE
Duplicate keys in collections when rendering in tests with React 17

### ISSUE THREAD

**Issue by jabrks** [adobe/react-spectrum#6680]
### Provide a general summary of the issue here

There is no prefix on generated IDs in test environments as seen in the snippet below

https://github.com/adobe/react-spectrum/blob/b940126e4d67a11d28b7c0b098eab23205598b6c/packages/@react-aria/ssr/src/SSRProvider.tsx#L155

As a result, when rendering a collection in a test using React 17, it is possible for the keys to clash as they are structured in the same way as other generated IDs within the same tree

https://github.com/adobe/react-spectrum/blob/b940126e4d67a11d28b7c0b098eab23205598b6c/packages/%40react-aria/collections/src/Document.ts#L229

This problem is not present when using React 18 as the `useId` hook provides the generated IDs in a different format

### 🤔 Expected Behavior?

None of the components in the tree should have the same key

### 😯 Current Behavior

A message is printed to the console warning of duplicate keys

```
Warning: Encountered two children with the same key, `react-aria-5`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

### 🖥️ Steps to Reproduce

1. Visit https://stackblitz.com/edit/vitest-dev-vitest-flnhto?file=TestMenu.jsx&view=editor
2. Observe the warnings in the Terminal

### Version

react-aria-components 1.2.1

### What browsers are you seeing the problem on?

Other

### If other, please specify.

Happy DOM

### What operating system are you using?

macOS

**Comment by snowystinger** [comment]
Good news, it looks like this has been fixed since the last release. I checked and don't see this error on the nightly version https://www.npmjs.com/package/react-aria-components?activeTab=versions
https://stackblitz.com/edit/vitest-dev-vitest-flnhto-ushfie

So this will be fixed in our upcoming release
