### ISSUE TITLE
Focus Ring not disappearing in pointer input mode

### ISSUE THREAD

**Issue by RobHannay** [adobe/react-spectrum#6683]
### Provide a general summary of the issue here

Our Focus Ring is visible even when only using a mouse pointer. (primarily on menus)

The only way to get it to switch to keyboard interaction mode for focus visibility is by clicking on a link (which isn't yet using the RAC Link component, for reference).

Perhaps some way we're set up is preventing the mode detection from working correctly?

OR it's possible that clicking on that link _shouldn't_ change it to keyboard input mode?

https://github.com/adobe/react-spectrum/assets/609062/b4b1a767-8eb2-405f-9660-8b4d8e5d39d3

### 🤔 Expected Behavior?

The focus ring should only appear when using keyboard navigation, or at least disappear when using a mouse pointer to select menu items.

### 😯 Current Behavior

The focus ring stays even if menu items/other buttons are clicked with a mouse. Only clicking on links gets it to go away.

### 🔦 Context

Since migrating to use RAC, people have commented they wouldn't expect to see the focus ring until they've used keyboard navigation.

Previously, we were relying on the `:focus-visible` pseudo class which seemed to make most people happy

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/suspicious-browser-69jk5h?file=/src/App.js

I think I need to share with your email - let me know!

### Version

React Aria Components 1.2.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Mac OS

**Comment by RobHannay** [comment]
I've also tested in that sandbox using the RAC `Link` component, which also doesn't cause the interactivity mode to change to mouse/pointer. Only clicking the raw anchor tag does.

**Comment by reidbarber** [comment]
Can you check that the codesandbox is publicly accessible?

**Comment by RobHannay** [comment]
Oops, here it is

https://codesandbox.io/p/sandbox/suspicious-browser-69jk5h?file=%2Fsrc%2Findex.js%3A9%2C1&from-embed=

I also just tried on the nightly build and the issue remains as far as I can tell

**Comment by reidbarber** [comment]
This is the expected behavior. We programmatically focus menu items elements on hover, so user agents may show an outline by default in that case.

You'll notice that in our docs examples and starter kits, our focusable elements have an `outline: none` style.

**Comment by RobHannay** [comment]
> This is the expected behavior. We programmatically focus menu items on hover, so user agents may show an outline by default in that case.
> 
> You'll notice that in our docs examples and starter kits, our focusable elements have an `outline: none` default style to prevent this. You can add your own focus styles with `data-focus-visible` / `data-focused` css selectors, or inline with the `isFocusVisible` / `isFocused` render props.

Understood, thanks @reidbarber. 

Do you know why clicking on the non-React Aria link would cause that behaviour to be _disabled_ then?

**Comment by RobHannay** [comment]
Fixed using CSS to use `:focus-visible` when `[data-rac]` is not set, and `[data-focus-visible]` when `[data-rac]` is set

**Comment by aleclarson** [comment]
For anyone else coming across this, I found this CSS to work:

```css
* {
  outline: none;
}

:not([data-rac]):focus-visible,
[data-rac][data-focus-visible] {
  outline: 1px solid currentColor;
}
```
