### ISSUE TITLE
RAC Datepicker should not submit value when disabled

### ISSUE THREAD

**Issue by kennethvdberghe** [adobe/react-spectrum#6685]
### Provide a general summary of the issue here

Fields should not add their value to the form they are in when disabled.

### 🤔 Expected Behavior?

DatePicker should not add its value to the form when disabled.

### 😯 Current Behavior

DatePicker component adds his value to the form, even when `isDisabled=true`

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/billowing-browser-qxrgsm

### Version

1.2.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you using?

MacOS

**Comment by snowystinger** [comment]
Looks like we didn't add the disable property to the inputs props. I've opened a PR to address it

**Comment by kennethvdberghe** [comment]
Awesome! Thanks for the quick reply! 🎉

On 12 Jul 2024, at 07:06, Robert Snow ***@***.***> wrote:

﻿

Looks like we didn't add the disable property to the inputs props. I've opened a PR to address it
