### ISSUE TITLE
Default value for `placement` prop in RAC Tooltip docs should be `'top'` instead of `'bottom'`

### ISSUE THREAD

**Issue by chaficnajjar** [adobe/react-spectrum#6713]
### 🙋 Documentation Request

I just used the RAC Tooltip for the first time and noticed the tooltip was placed on top of the anchor element by default so I think this is supposed to say `'top'` instead of `'bottom'`:

![2024-07-16_11-21](https://github.com/user-attachments/assets/cf8f84db-aa45-4b90-9234-9a6d871d5835)

This is a screenshot of https://react-spectrum.adobe.com/react-aria/Tooltip.html#tooltip-1.

**Comment by yihuiliao** [comment]
Ah, good catch! Seems like we define the default to be 'bottom' here:
https://github.com/adobe/react-spectrum/blob/a9c39a604fd00be10d73c0c59ce2529169331ad4/packages/%40react-types/overlays/src/index.d.ts#L25-L30

But we set the placement to 'top' if it isn't defined in RAC Tooltip:
https://github.com/adobe/react-spectrum/blob/a9c39a604fd00be10d73c0c59ce2529169331ad4/packages/react-aria-components/src/Tooltip.tsx#L133

It also shares this type with RSP TooltipTrigger:
https://github.com/adobe/react-spectrum/blob/a9c39a604fd00be10d73c0c59ce2529169331ad4/packages/%40react-types/tooltip/src/index.d.ts#L41

But we also set placement to 'top' here if it isn't defined in RSP TooltipTrigger:
https://github.com/adobe/react-spectrum/blob/a9c39a604fd00be10d73c0c59ce2529169331ad4/packages/%40react-spectrum/tooltip/src/TooltipTrigger.tsx#L63-L64

So I think we just need to update the JSDoc comment to `@default top` in `PositionProps`
