### ISSUE TITLE
The code inside `<script>` element rendered by `<LocalizedStringProvider>` doesn't run on Next.js `not-found.js` page

### ISSUE THREAD

**Issue by sefakeles** [adobe/react-spectrum#6730]
### Provide your feedback here.

The code inside `<script>` element rendered by `<LocalizedStringProvider>` doesn't run on Next.js `not-found.js` page, because error boundaries doesn't support SSR.

This causes errors like `TypeError: Cannot read properties of undefined (reading 'longPressMessage')` on a `not-found.js` page, because `window[Symbol.for('react-aria.i18n.locale')]` and `window[Symbol.for('react-aria.i18n.strings')]` are `undefined`.

The following explanation has been derived from [this Github comment](https://github.com/vercel/next.js/issues/63980#issuecomment-2056307152).

If an error occurs on the server, react will skip SSR up to the nearest suspense boundary, and retry rendering on the client. But rendering a `<script>` doesn't work there like it does in SSR -- **it will get inserted, but not actually run**.

This can be fixed by adding a `loading.js` alongside the `not-found.js`, which will stop the error from "bubbling up" above the layout by creating a suspense boundary.

### Version

react-aria-components = 1.2.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

**Comment by snowystinger** [comment]
Thanks for the issue. I'm a little confused, is there still a problem? or were you able to work around it? It might be useful to include a stackblitz showing a reproduction of the issue.

**Comment by sefakeles** [comment]
Here you can find a reproduction:
https://stackblitz.com/~/github.com/sefakeles/rac-localizedstringprovider-issue

Navigate to an unknown page (e.g. /unknown) and you'll see the following error:
`TypeError: Cannot read properties of undefined (reading 'longPressMessage')`

In order to work around this error, you can create `loading.tsx` file in `app` directory with the following content:

```javascript
export default function Loading() {
  return null
}
```

**Comment by ktabors** [comment]
Thanks for including the Next.js GitHub link with the explanation of this. This is the intended behavior, and they are providing the configuration to achieve the desired app functionality and this is not something we can fix.
