### ISSUE TITLE
Buttons don't get pressed using Vimium

### ISSUE THREAD

**Issue by freisenhauer** [adobe/react-spectrum#6747]
### Provide a general summary of the issue here

If using [vimium](https://github.com/philc/vimium) in Chrome or Firefox, Buttons onPress Functions dont get called. 

### 🤔 Expected Behavior?

The Button should trigger the `onPress` function.

### 😯 Current Behavior

The Button just shortly displays the browser indication that the button was navigated (in Chrome light blue borders).

### 🔦 Context

Here you can see, which events vimium triggers to simulate a click:
https://github.com/philc/vimium/blob/master/lib/dom_utils.js#L367

```javascript
simulateClick(element, modifiers) {
    if (modifiers == null) modifiers = {};
    const eventSequence = [
      "pointerover",
      "mouseover",
      "pointerdown",
      "mousedown",
      "pointerup",
      "mouseup",
      "click",
    ];
    for (const event of eventSequence) {
      this.simulateMouseEvent(event, element, modifiers);
    }
  },
```

### 🖥️ Steps to Reproduce

* Install [Vimium](https://github.com/philc/vimium) Plugin for Chrome or Firefox

* Navigate to https://react-spectrum.adobe.com/react-aria/Button.html

* Type `f`

* Type the anchor, which is displayed at the button of the first example.

### Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

MacOS

### 🕷 Tracking Issue

https://github.com/mittwald/flow/issues/590

**Comment by snowystinger** [comment]
This might start working after https://github.com/adobe/react-spectrum/issues/1720, specifically once we remove the hitbox testing which used to be required and theoretically is removable now.

**Comment by LFDanLu** [comment]
Closing as a dupe of https://github.com/adobe/react-spectrum/issues/1720, we can reopen if it doesn't get resolved by getting rid of the hitbox testing.

**Comment by Georgegriff** [comment]
> Closing as a dupe of #1720, we can reopen if it doesn't get resolved by getting rid of the hitbox testing.

How likely is this to happen #1720  has been open since 2021?

**Comment by snowystinger** [comment]
We'd very much like to do it. We just haven't had the bandwidth yet. We accept contributions if you or anyone would be interested in pitching in.

**Comment by rsnay** [comment]
#1720 has been completed, but the latest version of react-aria-components seems to have this issue with Vimium. I recently updated a project that consumes react-aria-components that did not previously have this issue, but now it does.

This can be seen in the current docs for the "Pending" button demo: https://react-aria.adobe.com/Button#pending

https://github.com/user-attachments/assets/0cbc9997-069e-4c87-98a4-b095462400b5

Should this issue be re-opened, or should I create a new issue? Thanks!

**Comment by LFDanLu** [comment]
@rsnay I'd say open a new issue especially since you mentioned it used to work in a previous version of react-aria-components, thanks!
