### ISSUE TITLE
MenuItem with href doesn't work in Chome device toolbar

### ISSUE THREAD

**Issue by Koreil** [adobe/react-spectrum#6748]
### Provide a general summary of the issue here

Hello!
In Chrome device emulation MenuItem with href does not respond to a click.
It seems to be related with this condition: https://github.com/adobe/react-spectrum/blob/04d55eb3d6654ffcc65b48f0ea57a9a47419c1b7/packages/%40react-aria/utils/src/openLink.tsx#L108

### 🤔 Expected Behavior?

On click on MenuItem link opens in a new tab.

### 😯 Current Behavior

Nothing happens.

### 🖥️ Steps to Reproduce

1. Open Chrome devtools
2. Open device toolbar
3. Open https://react-spectrum.adobe.com/react-aria/Menu.html#menuitem-1
4. Try to use Link example

### Version

1.2.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by snowystinger** [comment]
Thanks for the issue. Is it an issue on real devices as well? or only in the emulator?

**Comment by Koreil** [comment]
We haven't catched it on real devices yet, but the behavior still doesn't seem quite expected :)

**Comment by LFDanLu** [comment]
Verified that it behaves as expected on my Android phone. Going to close this since it is possibly emulator specific, but if we find that it doesn't work on any real device we can reopen then.
