### ISSUE TITLE
No matching export for import "getSyntheticLinkProps"

### ISSUE THREAD

**Issue by IvanHoliak** [adobe/react-spectrum#6750]
### Provide a general summary of the issue here

After updating the @nextui-org/react package to 2.4.6, the @react-aria/utils dependency was updated to 3.25.0. There was a problem importing into @react-aria/utils. This is why the project is not deployed to AWS Amplify and there is no way to continue developing the project!

![image](https://github.com/user-attachments/assets/0a587d32-d2b0-44e4-af4a-db8fee9544b2)
![image](https://github.com/user-attachments/assets/e068cf66-bc4d-4230-a21c-2a3e4f0bae38)

### 🤔 Expected Behavior?

Everything should work as it did on the previous version @react-aria/utils 3.24.1

### 😯 Current Behavior

The project does not start and does not build

### 🖥️ Steps to Reproduce

1) yarn remove @nextui-org/react
2) yarn add @nextui-org/react
3) yarn dev

### Version

3.25.0 @react-aria/utils

### What browsers are you seeing the problem on?

Chrome, Other

### What operating system are you using?

MacOS

**Comment by snowystinger** [comment]
I think you possibly have multiple copies of our packages installed. Could you check that is the case? it usually manifests as a node_modules inside of a package already in your node_modules. There's also this script https://git.corp.adobe.com/gist/luyau/5033d7b6fb95deb94be24c623e0b1118 which may help you identify duplicates.

Another option is that you need to update some of the other packages, such as react-aria/menu or react-aria/gridlist

**Comment by abraira85** [comment]
I have the same error

**Comment by theonlyway** [comment]
We are all using NextUI at least with NextJS the import trace seems a bit more helpful

```
./node_modules/@react-aria/table/dist/useTableRow.mjs
Attempted import error: 'getSyntheticLinkProps' is not exported from '@react-aria/utils' (imported as '$2K6sg$getSyntheticLinkProps').

Import trace for requested module:
./node_modules/@react-aria/table/dist/useTableRow.mjs
./node_modules/@react-aria/table/dist/import.mjs
./node_modules/@nextui-org/table/dist/chunk-IZM76DYO.mjs
./node_modules/@nextui-org/table/dist/index.mjs
./components/admin/rootLayout.tsx
```

**Comment by AmazingTurtle** [comment]
I was still in 2.4.2 and got the same error without updating. Was my CI pipeline broken all the time and I didn't know it or this isn't my fault? :D

**Comment by IvanHoliak** [comment]
I was also using version 2.4.2 and did not update it, I noticed this error when I deployed an update to my app on aws amplify. Then I decided to update all versions of the packages to the latest and the error began to appear no matter what version I installed. I don't have duplicate packages, I'm sure of that!

**Comment by AmazingTurtle** [comment]
Anyone else using turbo in this setup? Is this possibly related to turbo?

**Comment by mmmmmob** [comment]
I got this same error message as well when deploying on Vercel 😰

**Comment by wingkwong** [comment]
@IvanHoliak

> After updating the @nextui-org/react package to 2.4.6, the @react-aria/utils dependency was updated to 3.25.0.

this looks weird since we use the fixed version for `@react-aria/utils@3.24.1` as well as for other RA dependencies.

**Comment by Pewtro** [comment]
I am also facing this issue (not using next-ui), it seems that `@react-aria/utils@3.25.0` in general is broken. 
The script proposed by @snowystinger reports no duplicates in package-lock.

**Comment by AmazingTurtle** [comment]
Boiled it  down to this commit.
https://github.com/adobe/react-spectrum/commit/a4dee6e127265a93c7a88d9c559c7d7fea180560

Apparently `getSyntheticLinkProps` was renamed to `useSyntheticLinkProps`.
That on it's own shouldn't cause so much trouble as nextui refers to the `3.24.1` version which was [released 2 months ago](https://www.npmjs.com/package/@react-aria/utils/v/3.24.1). Makes me wonder why `3.5.0` is used in nextui builds. More specifically in docker builds, as on my local machine with my `yarn.lock` unchanged, this problem does not occur but only in my Dockerfile.

In my specific use case, I was using `turbo` which produced a malformed `yarn.lock` which would be dirty on `yarn install --immutable`. I opted out of turbo and manually added all `packages/` and `apps/` `package.json`s.

Either way if it's broken on your local machines it helps to do `yarn why @react-aria/utils` to see why it is using `3.5.0` perhaps. On my CI machine, `turbo` was to blame.

**Comment by Pewtro** [comment]
Something like that is a breaking change, especially when combined with the usage of ^ when referring to that dependency, it means that grabbing `@react-aria/gridlist@3.8.1` will install `@react-aria/utils@3.25.0` because the dependency refers to `"@react-aria/utils": "^3.24.1",`

**Comment by SunnyHiStroke** [comment]
"After updating to Next.js 3.25, I am encountering an issue when creating a build. Please suggest how to fix it."

Errors:-
 Invalid next.config.js options detected: 
 ⚠     Unrecognized key(s) in object: 'sentry'
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
  ▲ Next.js 14.2.5
  - Environments: .env.local, .env.production

   Creating an optimized production build ...
Failed to compile.

./node_modules/@react-aria/table/dist/useTableRow.mjs
Attempted import error: 'getSyntheticLinkProps' is not exported from '@react-aria/utils' (imported as '$2K6sg$getSyntheticLinkProps').

Import trace for requested module:
./node_modules/@react-aria/table/dist/useTableRow.mjs
./node_modules/@react-aria/table/dist/import.mjs
./node_modules/@nextui-org/table/dist/chunk-IZM76DYO.mjs
./node_modules/@nextui-org/table/dist/index.mjs
./node_modules/@nextui-org/react/dist/index.mjs
./app/error.tsx

**Comment by tomd-thehistroke** [comment]
Same error getting from this morning

Failed to compile

Next.js (14.2.5)
./node_modules/@react-aria/table/dist/useTableRow.mjs
Attempted import error: 'getSyntheticLinkProps' is not exported from '@react-aria/utils' (imported as '$2K6sg$getSyntheticLinkProps').

Any solution for this.

**Comment by wingkwong** [comment]
> Something like that is a breaking change, especially when combined with the usage of ^ when referring to that dependency, it means that freshly grabbing (or deduping) packages like `@react-aria/gridlist@3.8.1` will install `@react-aria/utils@3.25.0` because the dependency refers to `"@react-aria/utils": "^3.24.1",`, and then build will be broken.

Supplement a bit. In our NextUI table component, we are using the fixed version for RA table (v3.14.1)

```ts
"dependencies": {
  "@react-aria/table": "3.14.1",
   // some other dependencies ...
}
```

In `@react-aria/table@3.14.1`, it uses `@react-aria/grid@^3.9.1`

```ts
"node_modules/@react-aria/table": {
  "version": "3.14.1",
  "dependencies": {
    "@react-aria/focus": "^3.17.1",
    "@react-aria/grid": "^3.9.1",
     // some other dependencies ...
  },
}
```

Due to the caret (`^`), `@react-aria/grid": "^3.9.1"` will resolve to `@react-aria/grid@3.10.0` which was released yesterday.

```ts
"node_modules/@react-aria/grid": {
  "version": "3.10.0",
  "dependencies": {
    "@react-aria/utils": "^3.25.0",
     // some other dependencies ...
  },
}
```

and the breaking change was introduced in `@react-aria/utils@3.25.0`

**Comment by davidbonan** [comment]
That means all previous versions of React-aria are broken due to the poor version management of the React-aria monorepo ?

**Comment by itsberkelium** [comment]
@wingkwong should we expect a fix from react-aria or NextUI?

**Comment by yuliahey** [comment]
As a temporary fix, you can specify the older version in a package.json

`
"resolutions": {
   "@react-aria/utils": "3.24.1"
 }
`

**Comment by Pewtro** [comment]
> As a temporary fix, you can specify the older version in a package.json
> 
> `"resolutions": { "@react-aria/utils": "3.24.1" }`

This will only work if you also lock other `@react-aria/*` packages (and any transitive dependencies) to install versions that do _not_ depend on the `3.25.0` version, as otherwise you'll get the inverse error.

**Comment by LiGo666** [comment]
same issue here

**Comment by neonn0d** [comment]
Any hope :D?

**Comment by devongovett** [comment]
Hmm, interesting issue. I think we were under the impression that since this is an internal/private package, breaking changes were ok, but clearly that's not the case due to pinning. Sorry about that.

I guess we could potentially bring back the old version of the function and leave it there alongside the new one. In this case the function is quite small. We will check to see if there are any more like this as well.

**Comment by 7laria** [comment]
same here

**Comment by itsberkelium** [comment]
Solved here https://github.com/nextui-org/nextui/pull/3537

**Comment by wingkwong** [comment]
> Solved here [nextui-org/nextui#3537](https://github.com/nextui-org/nextui/pull/3537)

That's not correct. We rollbacked it.

**Comment by itsberkelium** [comment]
> > Solved here [nextui-org/nextui#3537](https://github.com/nextui-org/nextui/pull/3537)
> 
> That's not correct. That PR was experimental and somehow it got merged by mistake. We've rollbacked it. We'll wait for RA team's updates and at the same time we're trying to upgrade to RA latest and resolve the build issues.

I tried it earlier once I saw this PR. Forgot I have added resolutions as a temp solution. My bad.

**Comment by 7laria** [comment]
still happening

**Comment by devongovett** [comment]
hold your horses, I'm still working on releasing the fix to npm 😅

**Comment by Visual917** [comment]
Waiting patiently.

**Comment by ImredeAngelo** [comment]
> > As a temporary fix, you can specify the older version in a package.json
> > `"resolutions": { "@react-aria/utils": "3.24.1" }`
> 
> This will only work if you also lock other `@react-aria/*` packages (and any transitive dependencies) to install versions that do _not_ depend on the `3.25.0` version, as otherwise you'll be at risk of getting the inverse error.

You can also specify versions below `3.25.0` in case some package depends on an older version:

`"resolutions": {
	"@react-aria/utils": "<3.25.0" 
}`

**Comment by Jose1i1o** [comment]
> As a temporary fix, you can specify the older version in a package.json
> 
> `"resolutions": { "@react-aria/utils": "3.24.1" }`

This worked on my end. Thanks for the heads up @yuliahey

**Comment by devongovett** [comment]
This should be fixed in v1.3.1. Sorry for the bug and thanks for your patience.

**Comment by wingkwong** [comment]
@devongovett Thanks a lot!

**Comment by tejaslende** [comment]
**Build Error Due to Import Error with @react-aria/utils - Solution Found**

**Description:**

When building my project, I encountered errors related to imports from @react-aria/utils. Specifically, the build failed due to an import error for getSyntheticLinkProps.

**Errors Encountered:**

Failed to compile.

../../node_modules/@react-aria/table/dist/useTableRow.mjs
Attempted import error: 'getSyntheticLinkProps' is not exported from '@react-aria/utils' (imported as '$2K6sg$getSyntheticLinkProps').

Import trace for requested module:
../../node_modules/@react-aria/table/dist/useTableRow.mjs
../../node_modules/@react-aria/table/dist/import.mjs
Solution:

**I resolved the issue by ensuring the following package versions:**

"@nextui-org/react": "2.2.10"
@nextui-org/react: 2.2.10
@react-aria/utils: 3.24.1

**Steps Taken:**

1:  use  nextUI version  "@nextui-org/react": "2.2.10",
2: yarn cache clean
3: yarn node_module delete
4: yarn.locak file delete
5: yarn install

Ran the build command (yarn build) successfully.
**Additional Context:**

This solution addresses the import error by using compatible versions of the involved packages. If you encounter similar issues, aligning your package versions as shown above might help resolve them.
