### ISSUE TITLE
Type errors when rendering components in React 17

### ISSUE THREAD

**Issue by jabrks** [adobe/react-spectrum#6752]
### Provide a general summary of the issue here

Attempting to render components in React 17 results in type errors

### 🤔 Expected Behavior?

The TypeScript compiler should complete successfully

### 😯 Current Behavior

The TypeScript compiler outputs an error
```
'Button' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
```

### 🖥️ Steps to Reproduce

https://stackblitz.com/edit/vitejs-vite-r5y9p6?file=src%2FApp.tsx&view=editor

### Version

react-aria-components 1.3.0

### What browsers are you seeing the problem on?

Other

### What operating system are you using?

macOS

**Comment by metalix2** [comment]
+1 when using the slider, 1.2.0 works but 1.3.0 returns the same error as above. React version 17.0.2.

**Comment by devongovett** [comment]
This should be fixed in v1.3.1.

**Comment by strogonoff** [comment]
I see this after adding `@spectrum-icons/workflow` at current version (4.2.15). 🤔

(React 18, TS 5.6.2)

**Comment by strogonoff** [comment]
The expanded message is:

```
1. JSX element type 'Search' does not have any construct or call signatures. [2604]
2. 'Search' cannot be used as a JSX component.
     Its type 'typeof import("/<snip>/.yarn/__virtual__/@spectrum-icons-workflow-virtual-2ee84ccb87/0/cache/@spectrum-icons-workflow-npm-4.2.15-701d7d7c35-5e97e771eb.zip/node_modules/@spectrum-icons/workflow/Search")' is not a valid JSX element type. [2786]
3. JSX element type 'Search' does not have any construct or call signatures. [2604]
4. 'Search' cannot be used as a JSX component.
     Its type 'typeof import("/<snip>/.yarn/__virtual__/@spectrum-icons-workflow-virtual-2ee84ccb87/0/cache/@spectrum-icons-workflow-npm-4.2.15-701d7d7c35-5e97e771eb.zip/node_modules/@spectrum-icons/workflow/Search")' is not a valid JSX element type. [2786]
```
