### ISSUE TITLE
Tabs are not getting rendered in specific scenario 

### ISSUE THREAD

**Issue by Makisuo** [adobe/react-spectrum#6753]
### Provide a general summary of the issue here

I'm using React Aria Tabs together in MDX. It used to work great but since 1.30 they stopped rendering all together.

No error is thrown, nor is any markup rendered whatsoever. 

### 🤔 Expected Behavior?

The TabList and its Panels should be rendered as normally expected.

### 😯 Current Behavior

No error is thrown and no Markup is being rendered.
Nothing inside of Tabs will get rendered.

### 💁 Possible Solution

It does still work as expected once downgrading to 1.2.2

### 🔦 Context

We are using Tabs inside of our docs to render Examples and it's Code Snippet. Our Docs are build with MDX and we insert all MDX components as seen [here](https://github.com/telekom/pixelshades/blob/main/apps/docs/src/components/mdx-content.tsx
)

This has stopped working with 1.3.0

The component in quesiton be found here:
https://github.com/telekom/pixelshades/blob/main/apps/docs/src/components/component-preview.tsx

### 🖥️ Steps to Reproduce

Not sure how to reproduce it, I tried to create a minimal production right [here](https://codesandbox.io/p/sandbox/react-aria-reproduc-tabs-g58dp5) 
But it works here so I don't know what the exact issue is here. 

Here is the broken branch of our Docs Examples being broken:
https://github.com/telekom/pixelshades/tree/react-aria-1.3.0

Docs can be started with bun run dev --filter docs

### Version

1.3.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

T-Systems

**Comment by devongovett** [comment]
This should be fixed in v1.3.1.

**Comment by Makisuo** [comment]
Thanks, works now! Completly missed I rendered Tabs in Tabs 🤦‍♂️.
Was so confused what could have broken it
