### ISSUE TITLE
Supporting table cell selection

### ISSUE THREAD

**Issue by mdegrees** [adobe/react-spectrum#6762]
### Provide a general summary of the feature here

I've tried to rebuild Notion's style table with react-aria table to find out that cell selection is not supported. Sure you can hack your way around this with react state but it would be nice if react-aria table selection manages cell selection internally.

### 🤔 Expected Behavior?

When clicking on a cell you select it. Moving right or left with keyboard or hitting tab will move selection to the next table. If the user wants to select a row it click on the row square icon.

### 😯 Current Behavior

There is no way to select a cell in the current implementation.

### 🔦 Context

I'm trying to build sophisticated tables like those of notions.so or glide https://grid.glideapps.com/

**Comment by LFDanLu** [comment]
Thank you for the feature request! At the moment Spectrum Design doesn't have a pattern for this so unfortunately it is unlikely that we can pick this up in the short term. We'd be happy to accept a contribution for this or to prioritize if there is enough community interest for it.
