### ISSUE TITLE
Cards: Waterfall view does not correctly layout on initial load, even when the size is provided

### ISSUE THREAD

**Issue by synox** [adobe/react-spectrum#6764]
### Provide a general summary of the issue here

When using waterfall layout, when disabling caching and throttle network, the card renders in the wrong size before the image is loaded. However, the sizes are provided, so I expect it to still layout correctly. 
The same happens when loading additional cards with infinite scroll. 

https://github.com/user-attachments/assets/c8bf1f2b-4d9e-4f8e-b5d1-d024ad1a9ed0

### 🤔 Expected Behavior?

When the size is provided, it should layout the cards correctly. 

### 😯 Current Behavior

Even though the size is provided, all the cards have the same size. 

### 🖥️ Steps to Reproduce

1. open https://reactspectrum.blob.core.windows.net/reactspectrum/d405547aa7a7a38ac6b05a7887702e082259cf53/storybook/index.html?path=/story/cardview-waterfall-layout--default-waterfall&providerSwitcher-express=false
2. open developer tools
3. in networking, disable caching, throttle 3g
4. reload the story with the button in the storybook
5. change the window size and see the cards change size

### Version

current HEAD

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Macos

### 🧢 Your Company/Team

Adobe/GenStudio

**Comment by LFDanLu** [comment]
Might be something with the images not loading fully by the time we measure the actual DOM nodes for the true size of the cards thus making each card the same size. Ideally we should relayout when the images fully load so we get the true aspect ratio for each card.

**Comment by LFDanLu** [comment]
We will revisit this in S2 CardView, closing out in favor of https://github.com/orgs/adobe/projects/19/views/32?sliceBy%5Bvalue%5D=%F0%9F%8C%88&pane=issue&itemId=68909718
