### ISSUE TITLE
Parent <Popover> immediately closes when nested <Input> gains focus within  <Select>

### ISSUE THREAD

**Issue by tflanagan** [adobe/react-spectrum#6775]
### Provide a general summary of the issue here

If a &lt;Input> is inside of a &lt;Select> inside of a &lt;Popover> and the user attempts to focus the &lt;Input>, the parent &lt;Popover> immediately closes.

### 🤔 Expected Behavior?

That the parent <Popover> remains open

### 😯 Current Behavior

The parent <Popover> immediately closes

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/blissful-panka-5xlxwr?file=/src/App.js

### Version

3.36.1 + 1.3.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by tflanagan** [comment]
This is a very simplified test case of what we are attempting to do.

I imagine we could use &lt;ComboBox>, but I figured I would add this incase it wasn't known or expected behavior.

**Comment by snowystinger** [comment]
Unfortunately, codesandbox appears to be having an issue right now, so apologies if I've missed the mark. Assuming that you're writing something like
```
<DialogTrigger>
  <Button>Settings</Button>
  <Popover>
    <OverlayArrow>
      <svg width={12} height={12} viewBox="0 0 12 12">
        <path d="M0 0 L6 6 L12 0" />
      </svg>
    </OverlayArrow>
    <Dialog>
      <Select>
        <Label>Favorite Animal</Label>
        <Button>
          <SelectValue />
          <span aria-hidden="true">▼</span>
        </Button>
        <SelectClearButton />
        <Popover>
          <Input /> // here?
          <ListBox>
            <Input /> // here?
            <ListBoxItem>Cat</ListBoxItem>
            <ListBoxItem>Dog</ListBoxItem>
            <ListBoxItem>Kangaroo</ListBoxItem>
          </ListBox>
        </Popover>
      </Select>
    </Dialog>
  </Popover>
</DialogTrigger>
```

Either scenario where the input is being placed is invalid. If you need a pattern like this, I suggest another DialogTrigger/Popover/Dialog with a TextField inside it and a ListBox that it filters, either with or without virtual focus. There are some other discussions in the repo about how to create something like that.

The other option is to use the Combobox component.

Again, apologises if I've missed the mark, but hopefully this helps get you unstuck. And hopefully codesandbox comes back soon.

**Comment by tflanagan** [comment]
@snowystinger Your assumption was correct. Thank you for the explanation and possible workarounds .
