### ISSUE TITLE
Regression in useControlledState signature

### ISSUE THREAD

**Issue by alirezamirian** [adobe/react-spectrum#6784]
### Provide a general summary of the issue here

It's not exactly a runtime bug, but a regression in types. The `onChange` callback is allowed to have extra parameters besides the first parameter (the changed value), which is a useful feature. While it still works at runtime, the extra parameters are removed from the retuned setter in [a recent improvement in supporting ts strict mode](https://github.com/adobe/react-spectrum/commit/54d260d736f3e24d02c4277e593f4ab34930f9bd#diff-927eebaa6f590e895634eae7f762db38e91f5f30a71fb8960c620cabfa59d058):

https://github.com/adobe/react-spectrum/blob/54d260d736f3e24d02c4277e593f4ab34930f9bd/packages/%40react-stately/utils/src/useControlledState.ts#L15-L17

### 🤔 Expected Behavior?

useControlledState should allow extra parameters to be passed to `onChange` callback.

### 😯 Current Behavior

Passing extra arguments to the returned setter function, which used to compile successfully fails now.

### 💁 Possible Solution

A quick fix would be to just add back the removed `...args: any[]` second parameter:
 
 ```diff
-export function useControlledState<T, C = T>(value: T, defaultValue: T | undefined, onChange?: (v: C, ...args: any[]) => void): [T, (value: T) => void]; 
+export function useControlledState<T, C = T>(value: T, defaultValue: T | undefined, onChange?: (v: C, ...args: any[]) => void): [T, (value: T, ...args: any[]) => void]; 
```

But with some tweaks, it should be possible to have it typed in a way that extra parameters in the returned setter are typed based on the input `onChange` type.

### 🔦 Context

I'm using the extra parameters of the onChange to provide information about the type of interaction that caused the change. the controlled state can change due to two possible types of user interactions.

### 🖥️ Steps to Reproduce

 Use the following example:
```ts
function MyComponent({
  value,
  defaultValue = 3,
  onChange,
}: {
  value?: number;
  defaultValue?: number;
  onChange: (value: number, reason: "foo" | "bar") => void;
}) {
  const [state, setState] = useControlledState<number>(
    value,
    defaultValue,
    onChange
  );
  const update = () => {
    setState(3, "foo");
  };
}
  ```

### Version

@react-stately/utils@3.10.1

### What browsers are you seeing the problem on?

Other

### If other, please specify.

N/A

### What operating system are you using?

N/A

**Comment by snowystinger** [comment]
Seems fine. While technically an undocumented hook, I don't see any harm in adding this back. It doesn't appear to break strict types or affect them otherwise.
