### ISSUE TITLE
onAction doesn't get triggered for <MenuItem>s / useMenuItem()s

### ISSUE THREAD

**Issue by Vinnl** [adobe/react-spectrum#6804]
### Provide a general summary of the issue here

After updating to React-Aria 3.34.1, the `onAction` callback for our menu items no longer get called.

### 🤔 Expected Behavior?

When clicking a MenuItem, the `onAction` callback should get called.

### 😯 Current Behavior

When clicking a MenuItem, the `onAction` callback does not get called.

### 🖥️ Steps to Reproduce

It can be reproduced using the [example from the RAC docs](https://react-spectrum.adobe.com/react-aria/Menu.html): https://codesandbox.io/p/sandbox/kind-zhukovsky-7f49q6?file=%2Fsrc%2FApp.js

In the docs, you can see that clicking a menu item (e.g. "Open") triggers an alert ("open"), but in the CodeSandbox (and our code), nothing happens.

Note that this also occurs when using the `useMenuItem` hook directly, but this was easier to create a reproduction for :)

### Version

3.34.1

### What browsers are you seeing the problem on?

Firefox

### What operating system are you using?

Fedora Silverblue 40

### 🧢 Your Company/Team

Mozilla

### 🕷 Tracking Issue

https://github.com/mozilla/fx-private-relay/pull/4911

**Comment by snowystinger** [comment]
Appears to work correctly when the codesandbox is updated to the most recent react-aria-components release https://codesandbox.io/p/sandbox/reverent-keldysh-rxz9ts

Can you check if you have duplicates of any of our packages in your node_modules?

**Comment by Vinnl** [comment]
Oh hmm, darnit. No, just the one version:

```
fx-private-relay@1.0.0 /<snip>/
└─┬ frontend@0.1.0 -> ./frontend
  └── react-aria@3.34.1
```

**Comment by Vinnl** [comment]
Ah of course :)

```
$ node lockCheck.js
-----------------------
| PACKAGE.LOCK REPORT |
-----------------------
```

Glancing at that script I think that means that there are no dupes?

**Comment by snowystinger** [comment]
Yeah, looks like that isn't the culprit.

Interestingly though, I downloaded your codesandbox, ran
```
npm i
npm start
```
and that works just fine. So codesandbox seems to be interfering a little.

Can you alter the codesandbox so it reproduces locally as well? Otherwise you'll need to do some debugging in your application.

**Comment by Vinnl** [comment]
I've been trying to reproduce it in Codesandbox for a while, but it's acting up - I was already quite happy I got the original fork working :sweat_smile: But it keeps throwing errors when I try to create a reproduction with just react-aria.

I also tried downloading a sandbox and that worked fine too :/ I did manage to reproduce on a fresh clone of our code, as described below. I guess I'll see if I can isolate that code to a minimal reproduction.

```
$ git clone --recurse-submodules --branch=dependabot/npm_and_yarn/react-aria-3.34.1 git@github.com:mozilla/fx-private-relay.git
$ cd fx-private-relay/frontend
$ npm ci
$ npm run dev:mocked
```

And then visiting http://localhost:3000/accounts/profile/?mockId=full, opening "News" at the top and switching to the "History" tab, then clicking any of the entries there doesn't do anything, and adding a log to [this callback](https://github.com/mozilla/fx-private-relay/blob/993ef818d6cac5b3223ba94fcbab478d81635ad0/frontend/src/components/layout/navigation/whatsnew/WhatsNewList.tsx#L100) passed straight to `useMenuItem`'s `onAction` shows that it doesn't get called.

**Comment by snowystinger** [comment]
I think I see the issue, looks like we accidentally stopped calling the `onAction` passed as a prop directly to the hook.
Right now we only call it if it's been passed to the Item or to the Menu as a whole.
https://github.com/adobe/react-spectrum/commit/caff84082a16b3ceec0f409a3f4d9bb982001d7c

I think that was my fault, apologies. In the meantime, you can pass it as mentioned.I'll try to look into what exactly happened there that missed any sort of regression check.

**Comment by Vinnl** [comment]
Thanks @snowystinger, I was ready to declare this a problem on our side :sweat_smile: I can confirm that the workaround you mentioned works.

**Comment by snowystinger** [comment]
Nope, I just wrote the right thing in a comment and then implemented the wrong thing https://github.com/adobe/react-spectrum/pull/6671#pullrequestreview-2170868211
and we didn't have a test for it, I've added a test in the PR I just opened for it.

I'm glad you're able to move to the other implementation, technically this code path of passing onAction directly to useMenuItem has been deprecated.
