### ISSUE TITLE
`Tooltip` positioned incorrectly when open by default and `placement` is on inline axis

### ISSUE THREAD

**Issue by TimonVS** [adobe/react-spectrum#6842]
### Provide a general summary of the issue here

When `Tooltip` has `isOpen={true}` (or `defaultOpen={true}`) and `placement="left"` (or `right`), it seems to show up instantly even when the trigger is not in view, it also doesn't reposition to attach to the trigger.

![CleanShot 2024-08-07 at 11 50 23@2x](https://github.com/user-attachments/assets/158689e0-61cd-49df-bdcd-6a8a6aca852a)

When we scroll further down:

![CleanShot 2024-08-07 at 11 50 53@2x](https://github.com/user-attachments/assets/ae5d9903-4842-42c6-925c-6d98c5e764bb)

### 🤔 Expected Behavior?

The tooltip should be attached to the trigger, and should behave similarly to `top` and `bottom` positioning.

### 😯 Current Behavior

When `placement="left"` (or `right`) is used in combination with `isOpen={true}` (or `defaultOpen={true}`), the tooltip is positioned incorrectly.

### 🖥️ Steps to Reproduce

https://stackblitz.com/edit/vitejs-vite-fh1mvs?file=src%2FApp.tsx

### Version

1.3.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by snowystinger** [comment]
I don't think this is a real use case. You shouldn't have multiple tooltips open at a time and on a non-focused element out of screen.

Do you have more information about a real life scenario where you're running into this issue? Maybe we'll have some other suggestions to handle this.

**Comment by TimonVS** [comment]
Fair enough. My use case is to show the various directions in Storybook, it acts as documentation for the consumers of our design system.

![CleanShot 2024-08-13 at 14 55 09@2x](https://github.com/user-attachments/assets/4e88850f-bf49-4c96-944d-a8dd48bcf5c5)

**Comment by snowystinger** [comment]
I see, I'd either make a drawing or use a screenshot or just leave them as the interactive component and users would need to interact with them.
You could also possibly use intersectionObserver to detect when the trigger moves into view and show them at that time.
