### ISSUE TITLE
Anchoring problem tooltip react aria (nested button)

### ISSUE THREAD

**Issue by hpigeonfiteco** [adobe/react-spectrum#6843]
### Provide a general summary of the issue here

Hello, 

I have a problem with tooltips, I have a nested button with a parent button that has a triggerRef. This parent contains a label with a button next to it. The problem is that when I move the mouse over both buttons, the tooltip anchor changes.

### 🤔 Expected Behavior?

I'd like the tooltip anchor not to change position when I move the mouse inside the nested button.

Here is the code : 

```
        <Tooltip.Trigger>
          <Button
            ref={triggerRef}
            onPress={() => setIsOpen(true)}
            className={styles.button}
          >
            <Icon name="filter_list" />

            <SelectValue className={'selectedValue'} />
            <ClearButton isClearable={!isRequired} onInfiniteSearchChange={handleInfiniteSearchChange} className={styles.clearBtn}/>

          </Button>
          {!!selectedKey && <Tooltip>{label}</Tooltip>}

        </Tooltip.Trigger>
```

### 😯 Current Behavior

The anchoring of the tooltip changes when I position the mouse over the various elements inside the button. 

When I position the mouse in the center of the button : 

![image](https://github.com/user-attachments/assets/d1d32c2b-875f-46da-91c9-b6eb0915916a)

When I position the mouse to the right of the button : 

![image](https://github.com/user-attachments/assets/c38890ef-cdaa-4eae-95b1-b9da08c1ce74)

### 💁 Possible Solution

I'm working on code that I haven't developed, otherwise I wouldn't have made a nested button, maybe if there wasn't a nested button the bug wouldn't be there.

Maybe a a possible solution would be to simply redevelop the button without nesting it.

### 🖥️ Steps to Reproduce

https://react-spectrum.adobe.com/react-aria/Tooltip.html

### Version

React aria 3.33.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows

**Comment by reidbarber** [comment]
Nested button roles is invalid ARIA, so you'll want to make them adjacent instead. You could look into adjusting the crossOffset to have it visually aligned with the overall design.

**Comment by LFDanLu** [comment]
As an aside, we'll want to support tooltips on collection items similar to what was mentioned [here](https://github.com/adobe/react-spectrum/issues/6800), upon which your experience could possibly move over to being a Tag perhaps.

**Comment by snowystinger** [comment]
Closing as work we want to do is covered in Issue linked above
