### ISSUE TITLE
usePopover: border-radius is not accounted for with Arrow Positioning

### ISSUE THREAD

**Issue by ashleyryan** [adobe/react-spectrum#6844]
### Provide a general summary of the issue here

There does not appear to be a way to provide an arrowOffset to usePopover so that the arrow doesn't attempt to align against a rounded corner of the popup. 

Sometimes, the arrow can end up positioned incorrectly on a rounded corner instead of the flat edge of a popover

### 🤔 Expected Behavior?

I'm not 100% sure I understand what arrowBoundaryOffset does, but it seems to be relative to the overlay, not the popover contents. Perhaps a new arrowOffset prop?

### 😯 Current Behavior

You can see the error here when opening the popover: https://codesandbox.io/p/sandbox/laughing-lake-ngym87?file=%2Fsrc%2Fstyles.css

Perhaps related to this: https://github.com/adobe/react-spectrum/issues/5917

### 🖥️ Steps to Reproduce

You can see the error here when opening the popover: https://codesandbox.io/p/sandbox/laughing-lake-ngym87?file=%2Fsrc%2Fstyles.css

### Version

"@react-aria/overlays": "3.19.0",

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

OSX 14.5

### 🧢 Your Company/Team

VistaPrint

**Comment by LFDanLu** [comment]
You can make use of `arrowBoundaryOffset` (use the overlay border radius for this) in combination with `arrowSize` to handle cases like these: https://codesandbox.io/p/sandbox/nervous-james-325rrf?file=%2Fsrc%2FPopover.tsx%3A23%2C14

**Comment by ashleyryan** [comment]
I'm sorry, I'm trying to reproduce your fix and I can't get it to work - I already had `arrowBoundaryOffset` and `arrowSize` set as far as I can tell. 

I removed the padding-top from your sandbox (which of course, makes plenty of room available for the popover arrow) and set the crossOffset to -200 like yours and I still can't get it to work (it doesn't look like crossOffset is being used). Did you change a prop in another file that I missed?

Yours: https://codesandbox.io/p/sandbox/quirky-field-vflj8f?file=%2Fsrc%2FPopover.tsx%3A27%2C1-28%2C1&workspaceId=2207b31a-6b61-4de0-9aa3-f53e36db68c9
Mine: https://codesandbox.io/p/sandbox/laughing-lake-ngym87?file=%2Fsrc%2FPopover.tsx%3A26%2C1-27%2C1

**Comment by LFDanLu** [comment]
Ah sorry, forgot to mention I bumped the version in the sandbox, any version of `react-aria` greater than 3.33 should work (or if you are using the `@react-aria/overlays` package then 3.22 and above)

**Comment by alif-ally** [comment]
Apply custom CSS to adjust the arrow’s position relative to the popover’s flat edges.
If modifying usePopover, add an arrowOffset prop for fine-tuning.
Experiment with arrowBoundaryOffset values to see if it improves alignment.
Use transform properties in CSS for precise arrow placement.
Example CSS: .popover-arrow { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); }
