### ISSUE TITLE
'"react-aria-components"' has no exported member named 'TextFieldProps'. 

### ISSUE THREAD

**Issue by guygit** [adobe/react-spectrum#6847]
### Provide a general summary of the issue here

The docs (https://react-spectrum.adobe.com/react-aria/TextField.html#reusable-wrappers) gives this example:

`import type {TextFieldProps, ValidationResult} from 'react-aria-components';
`

### 🤔 Expected Behavior?

Importing "TextFieldProps" should not result in the error:
'"react-aria-components"' has no exported member named 'TextFieldProps'. 

### 😯 Current Behavior

showing this error

### 🔦 Context

I cannot wrap and re-export component

### 🖥️ Steps to Reproduce

Using the below import - results in the error described above:

`import type {TextFieldProps, ValidationResult} from 'react-aria-components';

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

mac

**Comment by snowystinger** [comment]
I see it being exported here https://github.com/adobe/react-spectrum/blob/59b0762a74cfb22af10bb7fdda9d379a09e2773b/packages/react-aria-components/src/index.ts#L129 what version of RAC are you using? Can you try a newer version? Or can you reproduce in a codesandbox/stackblitz?

**Comment by guygit** [comment]
I deleted "node_modules" folder - then installed again - and problem was fixed
