### ISSUE TITLE
@react-aria/utils platform functions results are cached in test environment

### ISSUE THREAD

**Issue by boieva-maryna** [adobe/react-spectrum#6848]
### Provide a general summary of the issue here

After updating to the latest Spectrum release, my Cypress tests for mobile behaviors started failing. This problem is related to the use of the `isIPhone` function from `@react-aria/utils`.

### 🤔 Expected Behavior?

The `isIPhone()` function should return results based on the  `window.navigator['userAgentData']` set within the tests.

### 😯 Current Behavior

The result from `isIPhone()` is cached and depends on the order in which tests are run. This caching continues even when the environment is set to `test`.

### 💁 Possible Solution

The [source code](https://github.com/adobe/react-spectrum/blob/59b0762a74cfb22af10bb7fdda9d379a09e2773b/packages/%40react-aria/utils/src/platform.ts#L30C19-L30C28) includes a check for `NODE_ENV` to prevent caching during tests, but this seems to be missing in the built package modules.

### 🖥️ Steps to Reproduce

Unfortunately, I could not set up a CodeSandbox example to demonstrate this issue. Please let me know if the description is not sufficient.

### Version

@react-aria/utils 3.25.1

### What browsers are you seeing the problem on?

Other

### If other, please specify.

Cypress

### What operating system are you using?

Windows 11

**Comment by snowystinger** [comment]
I see that and understand, however I'm not sure we want to ship that in our code at this time. We have talked about some flags like this before though, so it may happen in the future.

In the meantime, we have a number of singletons across the code base, I would suggest separating your tests into separate runs as this is unlikely to be the only conflict. If you have them in separate `it` statements already, you might be able to do it like this
```
  beforeEach(() => {
    cy.visit('whatever url') // force a refresh of the page, no js state should remain across refreshes
  })
```

**Comment by boieva-maryna** [comment]
Thank you for your reply!

**Comment by snowystinger** [comment]
I'm going to close this one for now, I've linked it to the larger umbrella discussion.
