### ISSUE TITLE
Opening/closing Select causes layoutshift

### ISSUE THREAD

**Issue by oscarcarlstrom** [adobe/react-spectrum#6855]
### Provide a general summary of the issue here

When opening a `<Select/>` the `<html>`-tag gets:

``` CSS
    padding-right: 15px;
    overflow: hidden;
```

This causes layout shifts for browsers with non-floating scrollbars.

Another thing about this is that it prevents scroll on the entire page, which might be confusing to some users.

Also `<ComboBox/>` does have this behavior. And I don't really see why `Select` should have this behavior, while `ComboBox` does't

### 🤔 Expected Behavior?

The Select box should not prevent scrolling on the `html`-tag when opened. It should work just as ComboBox in this matter.

### 😯 Current Behavior

The `Select`-komponent prevents scrolling on the `html`-tag when opened, which can cause layout shifts (both horizontal and vertical). It also prevents scrolling on the entire page, which can cause confusion.

### 💁 Possible Solution

I have to suggestions:

1. Don't prevent scroll on the `html`-tag when opening a Select.
2. Make scroll prevent optional through a prop to Select (and maybe also Combobox?)

### 🖥️ Steps to Reproduce

1. Make sure you are using a browser with non-floating scrollbars (set the "Show scroll bars" option to "Always" if using a Mac)
2. Go to: https://react-spectrum.adobe.com/react-aria/Select.html
3. Keep your eyes on something to the very right (like the top search field)
4. Open a Select
5. You will notice a layout shift every time the scrollbar is appearing/disappearing

Compare to https://react-spectrum.adobe.com/react-aria/ComboBox.html, where there is no layout shift or scroll locking.

### Version

react-aria-components@1.3.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

macOS Sonoma 14.5

**Comment by devongovett** [comment]
Dup of #1216 #5470 for the padding issue.

Preventing scrolling is intentional. It matches how the native `<select>` element behaves.
