### ISSUE TITLE
[RAC] - "Select" cannot disable focus on ListBoxItem hover.

### ISSUE THREAD

**Issue by zommerberg** [adobe/react-spectrum#6859]
### Provide a general summary of the issue here

I am building a shadcn like select with an input inside.

![image](https://github.com/user-attachments/assets/01dcf0ae-2dfd-49ed-b4aa-cd9f84ab0327)

So far so good, I just added a SearchInput inside the Popover of the Select. When the Select popover opens I focus the input by using the onOpenChange

However when i hover on the ListBoxItem the focus of the input disappears because it focuses on the  ListBoxItem instead. 

https://github.com/user-attachments/assets/40f078aa-ee3a-4c7f-bf1c-8c5e0b4e7f02

If we look at normal ListBox with ListBoxItem that does not happen
https://react-spectrum.adobe.com/react-aria/ListBox.html

It happens only within a Select
https://react-spectrum.adobe.com/react-aria/Select.html

### 🤔 Expected Behavior?

Dont focus on the ListBoxItem on hover. Focus only on keyboard interactions or press.

### 😯 Current Behavior

ListBoxItem focuses on hover, making it impossible to keep the Input focused.

### 🖥️ Steps to Reproduce

This is default ListBoxItem behaviour within a select. On hover it will gain focus. 

https://react-spectrum.adobe.com/react-aria/Select.html

If we look at normal ListBox with ListBoxItem that does not happen

https://react-spectrum.adobe.com/react-aria/ListBox.html

### Version

 "react-aria-components": "^1.3.1",

### What browsers are you seeing the problem on?

Microsoft Edge

### What operating system are you using?

Windows 11

**Comment by snowystinger** [comment]
Instead of putting a search inside the Select, could you use a Combobox? That seems more in line with the pattern you're going for.

Putting a search inside a Select is not the intended interaction model for a Select and may hurt accessibility. For example, how does a keyboard user get to the search? or how do they leave the search field after they've entered their text?

**Comment by zommerberg** [comment]
@snowystinger  

I did consider it, however there are some issues with the Combobox.

When the user clicks on the Combobox he has to click again to select the text in order to write something. Or he has to click on the text and then click backspace multiple times to clear the text. That is a bit unnecessary when a common solution with a search field exists.

I want a solution that github, gitlab and every other common website has:

![image](https://github.com/user-attachments/assets/52655320-ad59-4863-888b-9e5e231434bd)

![image](https://github.com/user-attachments/assets/365459c1-11a1-4f42-85ec-baedada02828)

**Comment by snowystinger** [comment]
Ah, that looks like a Popover with a TextField inside it that filters a ListBox. No need to use Select or Combobox, because it isn't really either of those. Especially with the Tabs, extra Button at the bottom, and a Popover title at the top.

You can swap the Trigger's text based on the item you select in the ListBox, and you can control the state of the ListBox so that it still has that option selected when the Popover is opened again.

**Comment by zommerberg** [comment]
ah ok got it! Thank you very much.

Also as you were talking about the combobox i did more digging and found out i can put the cursor at the start of the text each time the user clicks on the combobox which will work for me. Like here

https://react-select.com/home

**Comment by zommerberg** [comment]
@snowystinger Sorry to ask, but should I use a MenuTrigger or a DialogTrigger for this component?

I've tried using DialogTrigger however that does not set --trigger-width. 

MenuTrigger on the other hand does set it correctly so is it fine if i go with that for this case?


Also since those components have no form intercations, i assume it is a bad idea to use such component within a form and i should fallback to using a combobox there, is that correct?

**Comment by snowystinger** [comment]
DialogTrigger would be the way to go.
MenuTrigger's `--trigger-width` is purely convenience, you can implement it yourself.
See https://github.com/adobe/react-spectrum/issues/4858#issuecomment-1671651194

You can make a hidden input that stores whatever information you need in the form. You shouldn't need us for that.
