### ISSUE TITLE
[RAC] - Ability to unselect a ListBoxItem in an uncontrolled Select

### ISSUE THREAD

**Issue by zommerberg** [adobe/react-spectrum#6860]
### Provide a general summary of the feature here

It would be nice to have the ability to unselect a ListBoxItem in an uncontrolled select.

I know i could probably do that in a controlled one with a state by calling onAction in ListBoxItem but it would be nice if there was an option i could pass to SelectListBox that allows me to do so without changing my select to a controlled one.

NOTE: I am talking about clicking on a selected ListBoxItem to unselect it rather than having an outside button to clear the state.

### 🤔 Expected Behavior?

Pass a property to Select or SelectListBox that says i can unselect an item. When that is passed when i click on a selected ListBoxItem that should unselect it in a uncontrolled mode

### 😯 Current Behavior

No way to unselect a selected item by clicking on selected item in uncontrolled mode.

### 🔦 Context

https://mantine.dev/core/select/

You can check the behavior in mantune ui.

**Comment by snowystinger** [comment]
That's not how a Select works. You can put a button next to the Select to clear it though.

But really I would say go back to my earlier suggestion https://github.com/adobe/react-spectrum/issues/6859#issuecomment-2283201083 as the thing you're building isn't a Select

**Comment by zommerberg** [comment]
@snowystinger 
I am building a differenct component from what i mentioned in #6859 , its just a normal select this time.

But you are right, there is no rule stating that a normal Select should have this option. In stead i will have a "None" option in the list.
