### ISSUE TITLE
Tooltip: crossOffset is not working

### ISSUE THREAD

**Issue by unional** [adobe/react-spectrum#6865]
### Provide a general summary of the issue here

The issue can be seen on documentation directly.

### 🤔 Expected Behavior?

shift to the right with `crossOffset(60)`

### 😯 Current Behavior

![image](https://github.com/user-attachments/assets/55b8f0cd-4794-4753-bca1-493ddda0c5e8)

### 🖥️ Steps to Reproduce

https://react-spectrum.adobe.com/react-aria/Tooltip.html

### Version

1.3.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by snowystinger** [comment]
Can you say more about what is not working? Usually it would be centered, but it looks like it's shifted over to the right in the docs and in your screen shot.

**Comment by unional** [comment]
It is not, you can take a look at the previous example of `offset`. It should go way to the right. Right now it is not doing anything.

btw, I notice other issues with placement. Will create another issue about that.

**Comment by snowystinger** [comment]
Ah, that's intentional so that the tooltip's "tip" doesn't disconnect from the body of the tooltip. In addition, it has gone right. By default the body of the tooltip would be centered on the target, but in the cross offset example, we can see it's actually hanging way off the right hand side and not much off the left.

**Comment by unional** [comment]
I see, seems like I have get confused about what they do. I thought they shift the whole element. 🍺

**Comment by mryechkin** [comment]
> I see, seems like I have get confused about what they do. I thought they shift the whole element. 🍺

Just wanted to chime in that this was my understanding as well. It's a bit misleading, since `offset` actually shifts the entire tooltip, including the tip itself.
