### ISSUE TITLE
Select and ComboBox submit value as react-aria-1, react-aria-2 etc.

### ISSUE THREAD

**Issue by jlaskie** [adobe/react-spectrum#6876]
### Provide a general summary of the issue here

When I check my form submissions, the value that user selected appears as react-aria-1 or react-aria-2 or 3 depending on the selected value. It should appear as the actual value instead. I'm using Formspark for the form submission. It's the same when using ComboBox but not TextField. This is happening with a simple form submission in Nextjs using the react aria Form component.  

```
export default function Colours() {

return (
    <>
      <Form
        action="https://submit-form.com/MyFormSparkId"
        method="post">

<Select
          name="fave-colour"
          isRequired
          placeholder="Select your fave colour"
        >
          <Label>Your Fave Colour</Label>
          <Button>
            <SelectValue />
            <span  aria-hidden="true">
              ▼
            </span>
          </Button>
          <FieldError />
          <Popover >
            <ListBox>
              <ListBoxItem >
                Blue
              </ListBoxItem>
              <ListBoxItem >
                Yellow
              </ListBoxItem>
              <ListBoxItem >
                Red
              </ListBoxItem>
            </ListBox>
          </Popover>
        </Select>

<Button type="submit">
          Submit
        </Button>
</Form>
</>
 )
}
```

### 🤔 Expected Behavior?

For example, if I select Yellow and submit the form, I should see fave-colour = Yellow in my formspark dashboard. 

### 😯 Current Behavior

I see fave-colour = react-aria-2 in my formspark dashboard. This is technically correct as it correlates to the second option but it should be displaying the actual value Yellow instead. If I pick Blue, it would be react-aria-1. If I pick Red, it shows react-aria-3.

### 💁 Possible Solution

I'm guessing that it's showing the react aria id instead of the value but I'm not sure what the solution could be. It might be something to do with formspark itself but the other TextField values are coming through without issue and the form is submitted successfully.

### 🖥️ Steps to Reproduce

Just copy and paste the code above and replace the form action with a formspark id.

### Version

react-aria-components: ^1.3.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows

**Comment by LFDanLu** [comment]
Does adding `formValue="text"` work for you: https://react-spectrum.adobe.com/react-aria/ComboBox.html#html-forms? I think you are running into the autogenerated keys for the options since you haven't provided a `id` to your options and `formValue` is `key` by default

**Comment by jlaskie** [comment]
I tried adding ``` formValue="text" ``` for the Select component but ran into this error:

```

Type '{ children: Element[]; name: string; isRequired: true; placeholder: string; formValue: string; }' is not assignable to type 'IntrinsicAttributes & SelectProps<object> & RefAttributes<HTMLDivElement>'.
  Property 'formValue' does not exist on type 'IntrinsicAttributes & SelectProps<object> & RefAttributes<HTMLDivElement>'.
  
```
  
  However, it did work for the ComboBox and using ``` id ``` works for Select so I'll just use ``` formValue="text" ``` for the ComboBox and ``` id ``` for Select for now. Thank you!
