### ISSUE TITLE
Button implemented with useButton() can't be used to open a Menu

### ISSUE THREAD

**Issue by Sxoo** [adobe/react-spectrum#6880]
### Provide a general summary of the issue here

I've created a Button using the useButton() hook, but I can't open a Menu (can't use it as a MenuTrigger) since:

```
PressResponder.mjs:33 A PressResponder was rendered without a pressable child. Either call the usePress hook, or wrap your DOM node with <Pressable> component.
```

Button taken from the docs:

```ts
import {useButton} from 'react-aria';
import {useRef} from 'react';

function Button(props) {
  let ref = useRef<HTMLButtonElement | null>(null);
  let { buttonProps } = useButton(props, ref);
  let { children } = props;

  return (
    <button {...buttonProps} ref={ref}>
      {children}
    </button>
  );
}
```

and used in a Menu also taken from the docs:

```ts
import {Menu, MenuItem, MenuTrigger, Popover} from 'react-aria-components';

<MenuTrigger>
  <Button aria-label="Menu">☰</Button>
  <Popover>
    <Menu>
      <MenuItem onAction={() => alert('open')}>Open</MenuItem>
      <MenuItem onAction={() => alert('rename')}>Rename…</MenuItem>
      <MenuItem onAction={() => alert('duplicate')}>Duplicate</MenuItem>
      <MenuItem onAction={() => alert('share')}>Share…</MenuItem>
      <MenuItem onAction={() => alert('delete')}>Delete…</MenuItem>
    </Menu>
  </Popover>
</MenuTrigger>
```

### 🤔 Expected Behavior?

The Button should implement Pressable since under the hood useButton() is using usePress(). 

### 😯 Current Behavior

PressResponder.mjs:33 A PressResponder was rendered without a pressable child. Either call the usePress hook, or wrap your DOM node with <Pressable> component.

### 💁 Possible Solution

Not sure why this is happening? What am I missing?

using a Button from `react-aria-components` works just fine.

### 🖥️ Steps to Reproduce

```ts
import React from 'react';
import { useRef } from 'react';
import { useButton } from 'react-aria';
import { Menu, MenuItem, MenuTrigger, Popover } from 'react-aria-components';


function Button(props) {
  let ref = useRef<HTMLButtonElement | null>(null);
  let { buttonProps } = useButton(props, ref);
  let { children } = props;

  return (
    <button {...buttonProps} ref={ref}>
      {children}
    </button>
  );
}

const TestMenu = () => (
  <MenuTrigger>
    <Button aria-label="Menu">☰</Button>
    <Popover>
      <Menu>
        <MenuItem onAction={() => alert('open')}>Open</MenuItem>
        <MenuItem onAction={() => alert('rename')}>Rename…</MenuItem>
        <MenuItem onAction={() => alert('duplicate')}>Duplicate</MenuItem>
        <MenuItem onAction={() => alert('share')}>Share…</MenuItem>
        <MenuItem onAction={() => alert('delete')}>Delete…</MenuItem>
      </Menu>
    </Popover>
  </MenuTrigger>
);
```

### Version

    "react-aria": "3.24.0", "react-aria-components": "1.2.0"

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by snowystinger** [comment]
Thanks for the issue, have you already gone through https://github.com/adobe/react-spectrum/issues/5647 ?
Have you checked for duplicate packages? This script can help with that check: https://gist.github.com/jluyau/9024db3527788030312332075745469b

**Comment by Sxoo** [comment]
> Thanks for the issue, have you already gone through #5647 ? Have you checked for duplicate packages? This script can help with that check: https://gist.github.com/jluyau/9024db3527788030312332075745469b

Thanks for a quick reply. I've ran through the issue, but I didn't initially connect that this was a possible approach to address the problem. I'll make an edit after I do.

**Comment by Sxoo** [comment]
Everything works as intended now, thanks!
