### ISSUE TITLE
Exception when nesting both <TabList> and <Menu> under <Tabs>

### ISSUE THREAD

**Issue by cdanielw** [adobe/react-spectrum#6885]
### Provide a general summary of the issue here

I get an exception when nesting both `<TabList>` and `<Menu>` under`<Tabs>`, unless the menu components are placed under `<Tab>` or `<TabPanel>`.

`Uncaught TypeError: state is null`. This seems to be triggered by `state.selectionManager.isDisabled(key)`

### 🤔 Expected Behavior?

I expect both a button triggering a menu and some tabs to be shown.

### 😯 Current Behavior

Currently, an exception is thrown: `Uncaught TypeError: state is null`.

### 🔦 Context

I have a page with header containing tabs and a menu button. The tabs change the contents of the page. This psudo-code should explain how I end up with the menu nested under `<Tabs>`:

```html
<Tabs>
  <Header>
    <TabList>...</TabList>
    <MenuTrigger>...</MenuTrigger>
  </Header>
  <Contents>
    <TabPanel id={pathname}>...</TabPanel>
  </Contents>
</Tabs>

```

### 🖥️ Steps to Reproduce

This reproduces the issue, using the example code from the React Aria docs:

https://stackblitz.com/edit/vitejs-vite-2pkraj?file=src%2FApp.tsx

```typescript

function App() {
  return (
    <Tabs>
      {/* Comment one of these out to make it run */}
      <DemoTabs />
      <DemoMenu />
    </Tabs>
  );
}

function DemoTabs() {
  return (
    <>
      <TabList aria-label="History of Ancient Rome">
        <Tab id="FoR">Founding of Rome</Tab>
        <Tab id="MaR">Monarchy and Republic</Tab>
        <Tab id="Emp">Empire</Tab>
      </TabList>
      <TabPanel id="FoR">
        Arma virumque cano, Troiae qui primus ab oris.
      </TabPanel>
      <TabPanel id="MaR">Senatus Populusque Romanus.</TabPanel>
      <TabPanel id="Emp">Alea jacta est.</TabPanel>
    </>
  );
}

function DemoMenu() {
  return (
    <MenuTrigger>
      <Button aria-label="Menu">☰</Button>
      <Popover>
        <Menu>
          <MenuItem onAction={() => alert('open')}>Open</MenuItem>
          <MenuItem onAction={() => alert('rename')}>Rename…</MenuItem>
          <MenuItem onAction={() => alert('duplicate')}>Duplicate</MenuItem>
          <MenuItem onAction={() => alert('share')}>Share…</MenuItem>
          <MenuItem onAction={() => alert('delete')}>Delete…</MenuItem>
        </Menu>
      </Popover>
    </MenuTrigger>
  );
}
```

### Version

react-aria-components 1.3.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

macOS Sonoma 14.5

**Comment by snowystinger** [comment]
I think this is the way to do it right now https://stackblitz.com/edit/vitejs-vite-x3bqxw?file=src%2FApp.tsx making use of `createHideableComponent` for collections. Otherwise the Tabs will try to render all the Menu items thinking they are its own.

We'll probably want to make this easier in the future. We're still working on the API's for the collections a bit.

**Comment by cdanielw** [comment]
Thanks for the prompt reply. That workaround works well. While it's a bit clunky, I don't think this issue will show up on too many other places in an application.

**Comment by snowystinger** [comment]
Closing as solved and feedback. We'll open a new Issue when we know what we want to tackle

**Comment by MrFlashAccount** [comment]
@snowystinger Unfortunately the workaround doesn't work with the latest `react-aria-components`. Any ideas how we can bypass it?

**Comment by snowystinger** [comment]
I updated the stackblitz i created earlier and it looks like it's working to me https://stackblitz.com/edit/vitejs-vite-x3bqxw?file=package.json,src%2FApp.tsx

Do you possibly have duplicate copies/multiple versions of any of our packages installed. it can happens sometimes when updating, you will want to run deduping and resolve those down to only one copy of any of our modules.

**Comment by MrFlashAccount** [comment]
Yeah, I had a bug after bumping but after some time it disappeared. One small question: 
Is it fine to wrap a menu component, like that:
`export const Menu = createHideableComponent(function Menu<T extends object>(props: MenuProps<T>) {` ?

**Comment by snowystinger** [comment]
It should be fine, let us know if you run into an issue with it.

**Comment by MrFlashAccount** [comment]
@snowystinger Thank you for the help!

**Comment by levrik** [comment]
@snowystinger When applying this workaround I get the following warning in the console:

```
A PressResponder was rendered without a pressable child. Either call the usePress hook, or wrap your DOM node with <Pressable> component.
```

Is this safe to ignore? Everything seems to work fine so far.

**Comment by snowystinger** [comment]
@levrik I don't see that in my stackblitz. I tried the latest release as well https://stackblitz.com/edit/vitejs-vite-puzjdsvu?file=package.json
Can you provide a reproduction?

**Comment by sypherznw** [comment]
@snowystinger Thanks for the fix ! And the `createHideableComponent` function.

I had a similar issue as @levrik and using `createHideableComponent` solved it : 
Within a `Tabs` component I am using a `DialogTrigger` outside of a `Tab` or `TabPanel`. And I had the same warning as @levrik. As previously said, using `createHideableComponent` made the warning disappear.
