### ISSUE TITLE
Allow passing data attributes to FieldError

### ISSUE THREAD

**Issue by omarnyte** [adobe/react-spectrum#6888]
### Provide a general summary of the feature here

Most react-aria components (e.g. `Label` and `Text`) allow data attributes to be passed to the underlying DOM element. `FieldError` does not pass any data attributes to `Text`, so the data attributes do not get passed to the underlying DOM element. I have the capacity to open an MR to implement this feature. 

### 🤔 Expected Behavior?

Data attributes passed to `FieldError` should be passed on to the underlying DOM element (e.g. `span`). 

### 😯 Current Behavior

Because `FieldError` [uses render props](https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/FieldError.tsx#L40-L45), only [these props](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/s2/src/NumberField.tsx#L434-L439) get spread into `Text`:
- `className`
- `style`
- `children`
- `data-rac`

### 💁 Possible Solution

Component props can be passed to the [`filterDOMProps`](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/filterDOMProps.ts#L57), and the props returned from the util can be spread into `Text`. 

### 🔦 Context

Our component library passes a `data-` attribute to HTML elements in order to target them for style resets. We also use data attributes (e.g. `data-size="large"`) to target components for conditional styling. We can use class names to get around this, but we use data attributes pretty extensively. 

### 💻 Examples

**React**
```jsx
 <FieldError data-size="large">An error message</FieldError>
```

**DOM Output**
```html
<span class="react-aria-FieldError" id="react-aria9938127803-:r16:" slot="errorMessage" data-rac="">
  An error message
</span>
```

### 🧢 Your Company/Team

Zapier

**Comment by snowystinger** [comment]
I think this seems reasonable if you'd like to open a PR.
Thanks!

**Comment by omarnyte** [comment]
Thanks for the quick response! I'm aiming to open a PR later today.

We use data attributes to conditionally apply styles. For example, we have a compact version of our fields, and those versions have different styles. So we want to pass `data-size="compact"` or `data-compact="true"` to `FieldError` in order to target that `span` to apply certain styles only when the attribute is present.
