### ISSUE TITLE
Not able to search in Combobox in latest version of Chrome

### ISSUE THREAD

**Issue by NarendraKuruva** [adobe/react-spectrum#6910]
### Provide a general summary of the issue here

When I hovered on a list Item & search in the input, item is getting focused and I'm not able to search anymore

**NOTE: This issue is only in the latest version of chrome, when I checked in other system where it contains older version, it works fine**

### 🤔 Expected Behavior?

I should be able to search text & navigate between items at the same time as it was provided in the previous versions

Below is a reference video of the issue in _Chrome:-  **Version 127.0.6533.119 (Official Build) (64-bit)**_
https://github.com/user-attachments/assets/9b3cbf33-4645-4fc6-89c1-698205f64982

Below is a reference video which is working in _Chrome:-  **Version 125.0.6422.60 (Official Build) (64-bit)**_
[Screencast from 20-08-24 11_09_25 AM IST.webm](https://github.com/user-attachments/assets/2a4f3567-810f-48d6-9fbc-96041d395749)

### 😯 Current Behavior

When I hovered on a list Item & search in the input, item is getting focused and I'm not able to search anymore

### 🖥️ Steps to Reproduce

1. Go to [ this story](https://reactspectrum.blob.core.windows.net/reactspectrum/873870beb0fe5c0fc823b61e17fa9d1b563f2b68/storybook/index.html?path=/story/combobox--many-sections&providerSwitcher-express=false)
2. Hover on an item 
3. Search something in the input

### Version

Latest (Was checking in the latest storybook provided)

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Ubuntu 22.04.4 LTS

**Comment by NarendraKuruva** [comment]
@devongovett @snowystinger

**Comment by NarendraKuruva** [comment]
@devongovett @snowystinger 

Can you once look into this issue?

**Comment by snowystinger** [comment]
Verified, I can reproduce

**Comment by snowystinger** [comment]
Looks like an issue with this line [https://github.com/adobe/react-spectrum/blob/faf0e18467231422cb7a06eb92a74d04e271f[…]packages/%40react-aria/selection/src/useSelectableCollection.ts](https://github.com/adobe/react-spectrum/blob/faf0e18467231422cb7a06eb92a74d04e271f1e8/packages/%40react-aria/selection/src/useSelectableCollection.ts#L428)

maybe we can alter it to something like
```
    // If the focused key becomes null (e.g. the last item is deleted), focus the whole collection.
    if (manager.isFocused && manager.focusedKey == null && lastFocusedKey.current != null) {
      if (!shouldUseVirtualFocus) {
        focusSafely(ref.current);
      } else {
        manager.setFocusedKey(delegate.getFirstKey());
      }
    }
```
though I’m not sure why the more recent version of chrome is the one to blame. In Safari, it looks like this is still called, but then focus is quickly returned to the input.

they both (safari and chrome) call focusSafely on the listbox. Both of them run in the focusSafely not for ‘virtual’ interactionModality. both supportsPreventScroll

one results in an onBlur in useFocus (chrome) and the other one does not (safari).
that’s as far as I’ve made it tonight

**Comment by NarendraKuruva** [comment]
> // If the focused key becomes null (e.g. the last item is deleted), focus the whole collection.
>     if (manager.isFocused && manager.focusedKey == null && lastFocusedKey.current != null) {
>       if (!shouldUseVirtualFocus) {
>         focusSafely(ref.current);
>       } else {
>         manager.setFocusedKey(delegate.getFirstKey());
>       }
>     }

This Worked fine for me. Thank you for ur time :+1: .

But can you check why it is an issue in the first place only in the latest chrome version?

**Comment by NarendraKuruva** [comment]
> // If the focused key becomes null (e.g. the last item is deleted), focus the whole collection.
>     if (manager.isFocused && manager.focusedKey == null && lastFocusedKey.current != null) {
>       if (!shouldUseVirtualFocus) {
>         focusSafely(ref.current);
>       } else {
>         manager.setFocusedKey(delegate.getFirstKey());
>       }
>     }

This Worked fine for me. Thank you for ur time :+1: .

But can you check why it is an issue in the first place only in the latest chrome version?
@snowystinger

**Comment by snowystinger** [comment]
That's what the second part of my comment was doing... but it is now late for me. Someone from the team, or if you're feeling adventurous, will continue when it is their work day.

**Comment by devongovett** [comment]
Should be fixed in the latest patch release.
