### ISSUE TITLE
Why does Table follow ARIA grid pattern instead of ARIA table pattern?

### ISSUE THREAD

**Issue by ihsib** [adobe/react-spectrum#6911]
### Provide your feedback here.

[React Aria Table component](https://react-spectrum.adobe.com/react-aria/Table.html#features) uses [ARIA grid pattern](https://www.w3.org/WAI/ARIA/apg/patterns/grid/) for tab focus. Why does this component not follow the [ARIA table pattern](https://www.w3.org/WAI/ARIA/apg/patterns/table/)?

### 🔦 Context

Make it easy for user to focus on checkboxes and buttons in tables using the tab keys instead of arrow keys.

### Version

React Aria Components 1.0.1

### What browsers are you seeing the problem on?

Microsoft Edge

### If other, please specify

Chrome, Firefox

### What operating system are you using?

Windows, MacOS

**Comment by reidbarber** [comment]
The Table needs to be interactive:

> Like an HTML table element, a WAI-ARIA [table](https://w3c.github.io/aria/#table) is a static tabular structure containing one or more rows that each contain one or more cells; it is not an interactive widget. Thus, its cells are not focusable or selectable. The [grid pattern](https://www.w3.org/WAI/ARIA/apg/patterns/grid/) is used to make an interactive widget that has a tabular structure.

https://www.w3.org/WAI/ARIA/apg/patterns/table/

**Comment by devongovett** [comment]
If you want a non-interactive table, there's no need to use RAC at all. Just use a regular HTML `<table>` element.
