### ISSUE TITLE
Button - onClick does not propagate in iframe

### ISSUE THREAD

**Issue by xylish7** [adobe/react-spectrum#6924]
### Provide a general summary of the issue here

It seems like the click event does not propagate when the `Button` element is used inside an iframe.

### 🤔 Expected Behavior?

The click event should propagate when `Button` component is used inside an iframe.

### 😯 Current Behavior

At this point, the click event does not propagate so it can't be caught by out elements.

### 💁 Possible Solution

If I create a custom aria button in which I delete the `onPointerDown` (`delete buttonProps.onPointerDown`), then it works. However, I find it weird to implement a solution like this because I need to create a custom component and manually add button styles. I'm also not using react-aria directly, but instead I'm using nextui `button` component which is based on react-aria.

### 🔦 Context

I'm using NextUI library (which is based on react-aria) to build a website builder. Because I'm trying to emulate mobile, tablet and desktop sizes, I need to use an iframe. However, when a `Button` component is used inside an iframe, it looks like the `click` event does not propagate so `craftjs` (the package I'm using to create the website builder) does not catch the event and the `Button` can't be selected.

Another solution is to pass `null` to `onPointerDown` (this works in NextUI Button) and it is kind of easy to do, but I'm still not sure what is the impact. `onPointerDown` seems to not be supported on a react aria `Button` component.

If the iframe is removed, everything works as expected.

### 🖥️ Steps to Reproduce

Here is a codesandbox example: https://codesandbox.io/p/devbox/craftjs-react-frame-component-forked-s9cc7t. Tha `Aria Button` is the one which does not work. `Custom Aria Button` is the one with a possible workaround. 

And a video of the issue:

https://github.com/user-attachments/assets/26959e8e-19e5-4691-b26e-ea7797c03a64

### Version

1.3.3

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What operating system are you using?

Windows 11

**Comment by snowystinger** [comment]
It sounds like the button inside the iframe is just visually representing a button? Could you just render something which looks like a button but isn't actually one. That'd probably make more sense to accessibility as well. Or, you could wrap the button in an "inert" element.

You may want to have a look through our issues for other ideas. There have been some other website builders discussing interactions like this.

**Comment by xylish7** [comment]
I see. It seems like drag and drop is also affected. I'll try to find a solution and come back if in the meantime I fix it.

**Comment by xylish7** [comment]
It seems like using `inert` attribute may do the trick. Thank you for your quick answer 👍
