### ISSUE TITLE
[RAC] Breaking change to `children` type in `BreadcrumbProps` in v1.3.2

### ISSUE THREAD

**Issue by andrew-pledge-io** [adobe/react-spectrum#6956]
### Provide a general summary of the issue here

There was a breaking change in the RAC `<Breadcrumb>` component where the type of `children` in `BreadcrumbProps` changed from `ReactNode` to `ReactNode | (props: RenderProps) => ReactNode`.

see: https://github.com/adobe/react-spectrum/commit/660e768998b253af8233419437fab863d2b8c2cd#diff-3665b56a6e79754081f2590fccd7fbfb79570f1101922c5e71fea9e2360fccb5L71

This started causing type errors where `BreadcrumbProps['children']` was being rendered in JSX as it's no longer a JSX compatible type.

There were no release notes for v1.3.2 or v1.3.3 so it was a bit tricky to track down, I'm creating this issue to document the change for others rather than expecting any kind of fix to be released.

### 😯 Current Behavior

```tsx
import type { BreadcrumbProps } from 'react-aria-components';
import { Breadcrumb } from 'react-aria-components';

export function MyBreadcrumb(props: BreadcrumbProps) {
  return (
    <Breadcrumb {...props}>
      <div className="my-style-wrapper">
        {/* ok in react-aria-components 1.3.1, type error in 1.3.2 */}
        {props.children}
      </div>
    </Breadcrumb>
  );
}

```

### 💁 Possible Solution

Users of `Breadcrumb` can fix their code by using `composeRenderProps`:

```tsx
import type { BreadcrumbProps } from 'react-aria-components';
import { Breadcrumb, composeRenderProps } from 'react-aria-components';

export function MyBreadcrumb(props: BreadcrumbProps) {
  return (
    <Breadcrumb {...props}>
      {composeRenderProps(props.children, (children) => (
        <div className="my-style-wrapper">{children}</div>
      ))}
    </Breadcrumb>
  );
}
```

### 🔦 Context

Our environment uses Renovate to automatically pick up new package versions.

When it picked up react-aria-components@1.3.2, the PR pipelines started failing due to this change in types.

### 🖥️ Steps to Reproduce

1. Install react-aria-components@1.3.1
1. Create a component that renders `BreadcrumbProps['children']` as JSX
1. Update to react-aria-components@1.3.2
1. Run TypeScript type checker

### Version

v1.3.2

### What browsers are you seeing the problem on?

Other

### What operating system are you using?

MacOS

**Comment by devongovett** [comment]
Sorry about that. This was a bug in the types. Children can be a function due to render props but the types were not reflecting reality.
