### ISSUE TITLE
Type param in SelectProps<T> is not used

### ISSUE THREAD

**Issue by unional** [adobe/react-spectrum#6960]
### Provide a general summary of the issue here

The type param `T` is used in `CollectionBase<T>` to define the `children` and `items` props.

However they are both omitted by `SelectProp`.

https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/Select.tsx#L65

So the type param is just noise and doing nothing.

### 🤔 Expected Behavior?

remove it or use it

### 😯 Current Behavior

doing nothing

### 🖥️ Steps to Reproduce

n/a

### Version

rac 1.3.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by snowystinger** [comment]
Looks like we don't require it in TagGroup https://github.com/adobe/react-spectrum/blob/32574f874fd8a8b667a409938457819ac33f8e84/packages/react-aria-components/src/TagGroup.tsx#L26

thanks for the issue

**Comment by kp047i** [comment]
@snowystinger 
May I work on this issue?

**Comment by unional** [comment]
Note that this can considered as a breaking change if we remove the type param

**Comment by snowystinger** [comment]
that's a great point, we may need to make a default in order to deprecate it instead

**Comment by kp047i** [comment]
@snowystinger 
I understand the concern about removing the type parameter `T` being a breaking change. Instead of removing the type parameter T, I'm thinking of providing a default value for it.
Would the following change be acceptable?

``` ts
export interface SelectProps<T extends object = {}> extends Omit<AriaSelectProps<T>, 'children' | 'label' | 'description' | 'errorMessage' | 'validationState' | 'validationBehavior' | 'items'>, RACValidation, RenderProps<SelectRenderProps>, SlotProps {}

function Select<T extends object = {}>(props: SelectProps<T>, ref: ForwardedRef<HTMLDivElement>) {
  // ...
}
```

**Comment by snowystinger** [comment]
I believe that will work, we'll discuss more in review. Thanks!
