### ISSUE TITLE
SelectValue shows placeholder when the selected value label is 0

### ISSUE THREAD

**Issue by unional** [adobe/react-spectrum#6961]
### Provide a general summary of the issue here

SelectValue shows placeholder when the selected value label is 0

### 🤔 Expected Behavior?

`SelectValue` should shows the label of the item 0.

### 😯 Current Behavior

SelectValue shows placeholder when the selected value label is 0

### 🖥️ Steps to Reproduce

[sandbox](https://codesandbox.io/p/sandbox/frosty-dew-2c4fdt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzrrz1o900063b6jl16zdonz%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzrrz1o900023b6j07cvxp3i%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzrrz1o900033b6j126o30a5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzrrz1o900053b6jtpeodcw9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzrrz1o900023b6j07cvxp3i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzrrz1o900013b6j3wg8foh6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0d5hzsk00023b6idq8njagt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A13%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzrrz1o900023b6j07cvxp3i%2522%252C%2522activeTabId%2522%253A%2522cm0d5hzsk00023b6idq8njagt%2522%257D%252C%2522clzrrz1o900053b6jtpeodcw9%2522%253A%257B%2522id%2522%253A%2522clzrrz1o900053b6jtpeodcw9%2522%252C%2522activeTabId%2522%253A%2522cm0crsu48002i3b6ipp3q72fl%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzrrz1o900043b6jgie0u6fc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm0crsu48002i3b6ipp3q72fl%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzrrz1o900033b6j126o30a5%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzrrz1o900033b6j126o30a5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Select the `0` item.

### Version

1.3.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

### 🧢 Your Company/Team

Palo Alto Networks

**Comment by snowystinger** [comment]
Probably missed a `key == null` check and instead just checked if the `key` is `falsy` somewhere, though I don't immediately see where

Thanks for the issue

**Comment by unional** [comment]
> Thanks for the issue, though looks like maybe you forgot to save on the codesandbox?

Yeah, somehow its not right. The good thing is that it encode the whole thing in the URL, so I can pull it from browser history. Updated.

**Comment by unional** [comment]
I think it's probably here: 

https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/Select.tsx#L260

```tsx
defaultChildren: rendered || placeholder || stringFormatter.format('selectPlaceholder')

// change to
defaultChildren: rendered ?? placeholder ?? stringFormatter.format('selectPlaceholder')
```

will probably fix it.

**Comment by snowystinger** [comment]
Thanks for finding that! would you be willing to contribute a PR + test?

**Comment by unional** [comment]
Sure. I can do that. Already have the test ready.

One question, are you using the default `TS/JS Language Features` to format your code?

There is no `.vscode/settings.json` thus the `import {x} from` is formatted to `import { x } from`, not matching your style. Can I add the setting?

**Comment by snowystinger** [comment]
We don't currently have any of those settings configured.
For now, you should be able to run
`yarn eslint packages --ext .js,.ts,.tsx --fix` to address any of those kinds of lint errors

Thank you!

**Comment by unional** [comment]
FYI, this should work for you for the most part:

```json
{
  "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false
}
```

**Comment by snowystinger** [comment]
Thanks, I am not using VSCode; some of the others on the team do, though. So I'll leave it up to them if they want to add a config.
