### ISSUE TITLE
Long tag names are not truncated to fit in parent container

### ISSUE THREAD

**Issue by mikaelasymanovich** [adobe/react-spectrum#6962]
### Provide a general summary of the issue here

Long tag names overflow the parent container

### 🤔 Expected Behavior?

They should truncate

### 😯 Current Behavior

Long tag names overflow the parent container

### 💁 Possible Solution

this was a regression when we added collapse behavior to the tag group it seems

### 🖥️ Steps to Reproduce

<img width="1060" alt="Screenshot 2024-08-27 at 3 12 23 PM" src="https://github.com/user-attachments/assets/b3c61bad-bbc6-4218-a38f-a111dd56ed08">

### Version

0.3.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac OSX Ventura 13.1 (22C65)

### 🧢 Your Company/Team

Adobe Amplify

**Comment by LFDanLu** [comment]
I believe https://github.com/adobe/react-spectrum/blob/32574f874fd8a8b667a409938457819ac33f8e84/packages/%40react-spectrum/s2/src/TagGroup.tsx#L443 needs 
```
  boxSizing: 'border-box',
  maxWidth: 'full'
```
