### ISSUE TITLE
Color area support

### ISSUE THREAD

**Issue by deebov** [adobe/react-spectrum#697]
# ❔ Question

I couldn't find the [Color Area](https://spectrum.adobe.com/page/color-area/) component in the stories. Do you guys plan to release the color components?

**Comment by snowystinger** [comment]
Hi @deebov, that is not an immediate component for us and we probably wouldn't be starting it until late in the year. If you're interested in contributing it, we would love to talk about how to do that.

**Comment by deebov** [comment]
Hey @snowystinger, I am working on a new design system. And a ColorPicker is an important part of that DS. I am working on a ColorPicker component. Would love to build the ColorPicker using something reusable like @react-aria. 
I couldn't find enough documentation/guides on how to contribute and create new packages. Do you think you may help with this?

**Comment by snowystinger** [comment]
We're in the process of creating many of those docs right now actually. For instance, the Contributing guide and this section in particular https://react-spectrum.adobe.com/contribute.html#feature-requests
As for creating new packages, the easiest way to do it is to run the `plop` command from package.json.

**Comment by devongovett** [comment]
Superseded by #1118.
