### ISSUE TITLE
Button inside label triggers dropdown to open

### ISSUE THREAD

**Issue by axelthat** [adobe/react-spectrum#6976]
### Provide a general summary of the issue here

I have a help button inside the select's label. When clicked, it should ideally show a popover. While it does show the popover, it also opens the dropdown.

Simply tapping on a mac's trackpad doesn't make the popover visible. You have to force press it.

### 🤔 Expected Behavior?

Only show popover.

### 😯 Current Behavior

Opens both popver and dropdown.

### 💁 Possible Solution

A prop to exclude the button from select tree.

### 🖥️ Steps to Reproduce

https://stackblitz.com/edit/vitejs-vite-hqst3z?file=src%2FApp.tsx

### Version

^1.3.3

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

macOS 14.6.1

**Comment by yihuiliao** [comment]
I think what's happening is that the `Select` is passing down information to the `ButtonContext` which is what you want for the button in the dropdown but not for the button inside the label. You might be able to just clear out the `ButtonContext` using the Provider like so: https://stackblitz.com/edit/vitejs-vite-roqvv2?file=src%2FApp.tsx

**Comment by snowystinger** [comment]
It's invalid to have a button inside a label.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#interactive_content
> Don't place interactive elements such as [anchors](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) or [buttons](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) inside a label. Doing so makes it difficult for people to activate the form input associated with the label.
