### ISSUE TITLE
Add `isToday` to `CalendarCellRenderProps`

### ISSUE THREAD

**Issue by musjj** [adobe/react-spectrum#6977]
### Provide a general summary of the feature here

I want to change the cell's class if it represents today's date. It looks like there's logic for it:

https://github.com/adobe/react-spectrum/blob/bb05fdc361ef3b536a63479c29cc86f90c097a10/packages/%40react-spectrum/calendar/src/CalendarCell.tsx#L64-L65

But it's not exposed in `CalendarCellRenderProps`:

https://github.com/adobe/react-spectrum/blob/bb05fdc361ef3b536a63479c29cc86f90c097a10/packages/react-aria-components/src/Calendar.tsx#L235

So I can't change the class dynamically.

### 🤔 Expected Behavior?

You should be able to change the cell's class dynamically depending if the cell represents today's date.

### 😯 Current Behavior

`isToday` is not exposed in `CalendarCellRenderProps`.

### 💁 Possible Solution

Expose `isToday` in `CalendarCellRenderProps`

### 🔦 Context

Changing the class is important for css frameworks like Tailwind.

### 💻 Examples

```tsx
<CalendarCell date={date} className={({ isToday }) => (isToday ? "bg-red-500" : "bg-blue-500")} />
```

**Comment by reidbarber** [comment]
Closing since you can call this yourself. Otherwise, we would need to call it for your for every cell, whether it got used or not.

**Comment by snowystinger** [comment]
Added here: https://github.com/adobe/react-spectrum/pull/8428/files#diff-24b8724c12f1d436228f3341b1de3c28df7891fe96a28d5750c2c039efc60514R541
