### ISSUE TITLE
useDateSegment crashes on null reference during unmount

### ISSUE THREAD

**Issue by teemuandersen** [adobe/react-spectrum#6988]
### Provide a general summary of the issue here

When running a React application on some unknown conditions and testing it using Firefox browser, the application crashes when useDateSegment is used. The exception happens during the unmount phase. First the refs are set to null and then an event is triggered on Firefox before the components are unmounted and therefore useEffect cleanup functions called. Application crashes on null reference. Chrome and Safari do not trigger these events between ref nulling and component unmount.

> ref.current is null
$32489daedd52963e$export$1315d136e6f7581/<@webpack-internal:///../../../node_modules/@react-aria/datepicker/dist/useDateSegment.mjs:263:13
$8ae05eaa5c114e9c$export$7f54fc3180508a52/<@webpack-internal:///../../../node_modules/@react-aria/utils/dist/useEffectEvent.mjs:32:54
EventListener.handleEvent*$e9faafb641e167db$export$90fc3a17d93f704c/<@webpack-internal:///../../../node_modules/@react-aria/utils/dist/useEvent.mjs:28:17
commitHookEffectListMount@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:23184:26
commitPassiveMountOnFiber@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:24960:38
commitPassiveMountEffects_complete@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:24925:34
commitPassiveMountEffects_begin@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:24912:41
commitPassiveMountEffects@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:24900:34
flushPassiveEffectsImpl@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:27073:28
flushPassiveEffects@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:27018:14
performSyncWorkOnRoot@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:26110:3
flushSyncCallbacks@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:12042:22
commitRootImpl@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:26993:3
commitRoot@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:26716:19
finishConcurrentRender@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:26015:19
performConcurrentWorkOnRoot@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:25843:29
workLoop@webpack-internal:///../../../node_modules/scheduler/cjs/scheduler.development.js:266:42
flushWork@webpack-internal:///../../../node_modules/scheduler/cjs/scheduler.development.js:239:14
performWorkUntilDeadline@webpack-internal:///../../../node_modules/scheduler/cjs/scheduler.development.js:533:21
EventHandlerNonNull*@webpack-internal:///../../../node_modules/scheduler/cjs/scheduler.development.js:571:3

### 🤔 Expected Behavior?

Application does not crash on component unmount

### 😯 Current Behavior

Application crashes.

### 💁 Possible Solution

Make commit `a9c39a6` ref handling null safe.

### 🔦 Context

This happens on all our applications. We have created a `useKludgeRef` that keeps the non-null ref until unmount as a workaround.

### 🖥️ Steps to Reproduce

Not really sure what causes this. We have tried to reproduce the issue on small sandboxes, but no luck so far.

Stack contains at least: Webpack, babel, Typescript, React 18, Reach-router, React HookForm.

### Version

react-aria 3.34.3

### What browsers are you seeing the problem on?

Firefox

### What operating system are you using?

Mac OS

**Comment by snowystinger** [comment]
Ref cleanup is called earlier than effect cleanup, so checking if the ref is still set seems appropriate.
