### ISSUE TITLE
Adjusting screen reader (VoiceOver MacOS) reading order for a react-aria-components

### ISSUE THREAD

**Issue by ihsib** [adobe/react-spectrum#6990]
### Provide your feedback here.

I've noticed that the screen reader order for react-aria-components differ from component to component.

I've done simple example with a <Button /> and a <Link /> component which both have `aria-label` set.

The button component is being read as
This is button label, button

The link component is being read as
link, This is a link label

Is there a way to control in which order the screen reader reads the component tag & aria-label?
Have I misunderstood something?

Attaching screen shots from Safari & example repo

![button-screen-reader](https://github.com/user-attachments/assets/06260b2c-85bb-4d67-81b0-74e07ad4d36b)

![link-screen-reader](https://github.com/user-attachments/assets/eaec0b2d-12c7-4e58-8212-a0f049d74a94)

### 🔦 Context

Tricky to unify how the react-aria-components are being read by the VoiceOver MacOS screen reader. Might be confusing to end user.

### 💻 Code Sample

https://github.com/ihsib/react-aria-screen-reader

```tsx
<Button aria-label="This a button label">Button text</Button>
<Link href="" aria-label="This a link label">Link text</Link>
```

### Version

1.3.3

### What browsers are you seeing the problem on?

Safari

**Comment by reidbarber** [comment]
This is how VoiceOver handles elements with link roles and button roles by default, so I think trying to override this behavior might create unexpected experiences for VoiceOver users or have other unintended consequences.
