### ISSUE TITLE
NumberField step attribute doesn't work for values with more than 3 fraction digits

### ISSUE THREAD

**Issue by laurens-in** [adobe/react-spectrum#6996]
### Provide a general summary of the issue here

The `step` attribute of the `NumberField` works as expected when setting it to `0.001` but it stops working when it is set to `0.0001`.

### 🤔 Expected Behavior?

value should increment/decrement in step size `0.0001`

### 😯 Current Behavior

value doesn't change at all.

### 🔦 Context

[Codesandbox](https://codesandbox.io/p/sandbox/confident-buck-82vs9s?workspaceId=5e814e59-f776-4f67-baaf-d35f3383593f) showcasing the problem.

### 🖥️ Steps to Reproduce

Set `step` attribute on `NumberField` to a value with 4 fraction digits.

### Version

react-aria-components 1.0.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Ubuntu 22.04

**Comment by reidbarber** [comment]
Try adding `formatOptions={{maximumFractionDigits: 4}}`

**Comment by laurens-in** [comment]
my bad, thanks!
