### ISSUE TITLE
Cannot setup dev environment

### ISSUE THREAD

**Issue by Austaras** [adobe/react-spectrum#7021]
### Provide a general summary of the issue here

after `corepack enable yarn` and `yarn install`
`yarn run start` --> `free(): corrupted unsorted chunks`
`yarn run start:docs` --> `free(): corrupted unsorted chunks`
`yarn run build` --> `[Makefile:105: build] Segmentation fault (core dumped)`

### 🤔 Expected Behavior?

Everything should work.

### 😯 Current Behavior

Nothing works

### 🖥️ Steps to Reproduce

See above

### Version

git main

### What browsers are you seeing the problem on?

Other

### What operating system are you using?

Arch Linux

**Comment by snowystinger** [comment]
Are you able to run other projects using storybook 7?
https://storybook.js.org/docs/7

is there anything more to the error?

Did the yarn install complete successfully and did it use yarn 4?

**Comment by Austaras** [comment]
> Are you able to run other projects using storybook 7? https://storybook.js.org/docs/7

Yes. I manage to run a empty vue3+vite project with storybook@7.6.20

> is there anything more to the error?

Well, sometimes it fails silently. Sometimes I got `double free or corruption (out)`

> Did the yarn install complete successfully and did it use yarn 4?
Yes and yes.

**Comment by snowystinger** [comment]
Thanks for the extra info.
Unfortunately, none of us dev on Linux. However, our CI is on CircleCI `cimg/node`, which uses Ubuntu https://circleci.com/developer/images/image/cimg/node , does work.

I don't know enough about the differences between Arch Linux and Ubuntu Linux to know if that's playing a role.

Are you able to profile any of the processes for more information?

**Comment by Austaras** [comment]
Most likely to be caused by parcel-bundler/parcel#9926

**Comment by snowystinger** [comment]
Gotcha, are you able to downgrade your node version? didn't realize you were on 22, we have only worked against 18 so far. We have it in our backlog to update that soon, but there are some dependencies blocking it at the moment.

**Comment by Austaras** [comment]
Well, I guess the difference between Arch Linux and Ubuntu is how latest their packages are. Downgrade nodejs works fine.
