### ISSUE TITLE
BST Timezone incorrectly parsing

### ISSUE THREAD

**Issue by buchananwill** [adobe/react-spectrum#7065]
### Provide a general summary of the issue here

These date/time objects should be identical. The code called is this:

```
  const currentDateTime = addHours(
    parseDate(dateOfBirth).toDate(getLocalTimeZone()),
    12
  );
  const nowFormatted = formatInTimeZone(
    currentDateTime,
    getLocalTimeZone(),
    "yyyy-MM-dd'T'HH:mm:ssXXX"
  );

  console.log(nowFormatted, new Date(nowFormatted));

  const zonedDateTime = parseAbsolute(nowFormatted, 'BST');

  console.log(currentDateTime, zonedDateTime, getTimeZone(currentDateTime));
```
![image](https://github.com/user-attachments/assets/9a8cf026-a300-4c90-a64d-a2fc0b95139c)

The parser is incorrectly outputting GMT+6 at some point in the signal chain:

![image](https://github.com/user-attachments/assets/9aacc2b1-165f-4c58-a321-75cfab3967e2)

### 🤔 Expected Behavior?

ISO8601 should be parsed correctly. BST = GMT+1 (as shown in the argument variable).

### 😯 Current Behavior

The parser adds 6 hours or misinterprets the timezone.

### 🖥️ Steps to Reproduce

Run this code :

```
import {
  CalendarDate,
  getLocalTimeZone,
  parseAbsolute,
  parseDate,
  parseZonedDateTime,
  ZonedDateTime
} from '@internationalized/date';
import { addHours } from 'date-fns';
import { formatInTimeZone } from 'date-fns-tz';

function getTimeZone(date: Date): NullableOption<string> {
  const zone = Intl.DateTimeFormat('en-GB', { timeZoneName: 'short' })
    .format(date)
    .split(', ')
    .pop();
  return zone === undefined ? null : zone;
}


const currentDateTime = addHours(
    parseDate('1985-10-21').toDate(getLocalTimeZone()),
    12
  );
  const nowFormatted = formatInTimeZone(
    currentDateTime,
    getLocalTimeZone(),
    "yyyy-MM-dd'T'HH:mm:ssXXX"
  );

  console.log(nowFormatted, new Date(nowFormatted));

  const zonedDateTime = parseAbsolute(nowFormatted, 'BST');

  console.log(currentDateTime, zonedDateTime, getTimeZone(currentDateTime));
```

### Version

3.5.5

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 10

**Comment by devongovett** [comment]
You need to use a location based timezone identifier such as "Europe/London", not an abbreviation like BST. This is because BST only applies in the summer and has different rules on when it applies depending on the date (eg before 1995), whereas "Europe/London" applies to any date.

**Comment by buchananwill** [comment]
Ok, thanks for the further explanation. I've tried that and the error is gone now. Time is such a dumpster fire. X-D :`-(
