### ISSUE TITLE
Controlled Listbox Issues

### ISSUE THREAD

**Issue by brettr91** [adobe/react-spectrum#7066]
### Provide a general summary of the issue here

These are two separate issues:

1. When a list box is fully controlled and disallowEmptySelection is equal to false, you cannot deselect the last item. 
2. When a list box is fully controlled and use the arrow keys to navigate the list it will fire onSelectionChange.

### 🤔 Expected Behavior?

1. When disallowEmptySelection is equal to false you should be able to deselect all items.
3. Arrow keys should not fire onSelectionChange

### 😯 Current Behavior

1. When disallowEmptySelection is equal to false it does not allow you to deselect the last item
2. Arrow keys fire onSelectionChange

When an input is changed back to an uncontrolled input, it goes back to normal

### 🖥️ Steps to Reproduce

[Codebox](https://codesandbox.io/p/sandbox/w4kwdz?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm1dyk4un0006356kj5ih28f3%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm1dyk4um0002356knq4p4wbx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm1dyk4um0003356ko9fq0xvn%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm1dyk4un0005356kuj9cy06d%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm1dyk4um0002356knq4p4wbx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm1dyk4um0001356k5u1eyygu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522cm1dyk4um0002356knq4p4wbx%2522%252C%2522activeTabId%2522%253A%2522cm1dyk4um0001356k5u1eyygu%2522%257D%252C%2522cm1dyk4un0005356kuj9cy06d%2522%253A%257B%2522id%2522%253A%2522cm1dyk4un0005356kuj9cy06d%2522%252C%2522activeTabId%2522%253A%2522cm1dymhb1001q356kb6aihewc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm1dyk4um0004356klp96r9uj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm1dymhb1001q356kb6aihewc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm1dyk4um0003356ko9fq0xvn%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm1dyk4um0003356ko9fq0xvn%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Version

react-aria-components 1.3.3

### What browsers are you seeing the problem on?

Chrome, Firefox, Edge

### What operating system are you using?

Windows 11

### 🧢 Your Company/Team

n/a

### 🕷 Tracking Issue

n/a

**Comment by snowystinger** [comment]
I think something about your logic is off in your onSelectionChange handler. If you CMD+click, the onSelection is fired, but you don't change the selection in response to it because of this check `if (typeof selected.currentKey !== "undefined") {`

This works https://codesandbox.io/p/sandbox/listbox-forked-pm9cjc?file=%2Fsrc%2FListBoxSelect.js and you can use CMD+left click to deselect the last one. This make sense, "replace" can only add or change. It doesn't behave as a "toggle", which is the other behavior you could choose.

Using the 'toggle' behavior will also stop it from having the selection follow the arrow key focus.

https://react-spectrum.adobe.com/react-aria/ListBox.html#selection-behavior

**Comment by brettr91** [comment]
Hi Snowystinger!

Thank you for the help. 

It works as you have said with toggle. Very much appreciated.
