### ISSUE TITLE
[react-aria-components] Popover not compatible with native popover API that became widely available in December.

### ISSUE THREAD

**Issue by mmorris8** [adobe/react-spectrum#7067]
### Provide a general summary of the issue here

There's a newly available popover API. Yay!

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover

The React Aria Popover control doesn't work with it.  If you put a Popover element inside a native element popover (say, as part of a popover form dialog) it won't work.

### 🤔 Expected Behavior?

Popover was developed as a component during a time when there was no equivalent API in the browsers. Now that one has been added any alternate implementation should be made compatible with it.

### 😯 Current Behavior

React Aria Popover uses z-index to get its popover to the top of the stack. This isn't compatible with the new popover API which uses a special top layer in the browser to place popovers, dialogs and any other elements that use the top layer in front of those that do not.  As a result React Aria components which leverage popovers like the ComboBox nested inside popover elements will cease to function. While it is possible to nest them in over Aria popovers, the native browser API is easier to work with and hooks into CSS to allow fine control of the animation of the popover.

### 💁 Possible Solution

Feature detection can be used to detect the presence of the popover API, and the Aria Popover can leverage the API when it is present and use the existing code for older browsers. However, this could present backwards compatibility challenges.

The popover API also introduces new attributes for buttons - popovertarget and popovertargetaction. These need to be relayed to the interior button element.

### 🔦 Context

I have a facet list with combo boxes. On mobile I want to slide in the facet list from the left since there isn't enough room to keep it continually visible. I composed the desktop view first.

### 🖥️ Steps to Reproduce

```
<button popovertarget="my-popover">Open Popover</button>

<div popover="auto" id="my-popover">Greetings, one and all!
<ComboBox>
  <Button>Click to open Popover</Button>
  <Popover>Alas, I cannot work in this context.</Popover>
</ComboBox>
</div>
```

### Version

react-aria 3.34.3

### What browsers are you seeing the problem on?

Other

### If other, please specify.

All browsers that support the popover api

### What operating system are you using?

Mac OSX

### 🧢 Your Company/Team

Covenant Health

**Comment by mmorris8** [comment]
Updated the description.  I'm using flex blox to position the list box directly off the list with flex-end or flex-start as appropriate. It's working very well.

**Comment by mmorris8** [comment]
Got this mostly working. Getting this error though -
```
ariaHideOutside.ts:112  Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at ariaHideOutside.ts:112:64
    at Array.some (<anonymous>)
    at MutationObserver.<anonymous> (ariaHideOutside.ts:112:46)
```
I'm guessing this is React Aria trying to enforce focus on the now missing React Popover.  Whatever it is trylng to do the Popover API is handling.

**Comment by mmorris8** [comment]
Bump

**Comment by mmorris8** [comment]
Still could use some help with the above.

**Comment by mmorris8** [comment]
The more I dig into this the more it becomes apparent that Combobox is so tightly coupled to the Aria Popover component that trying use it without that component is pointless.  Even useComboBox assumes the use of a Popover element, which renders it worthless with the Popover API.

**Comment by mmorris8** [comment]
Well, this is what I have.

```javascript
import React, { useRef } from "react"
import { useId } from "react-aria"
import { Button, ListBox, ListBoxItem } from "react-aria-components"

export default function CvComboBox({
    label, 
    items, 
    selectedKey, 
    inputValue,
    optionLabels
  }) {

  const togglePopUp = () => {
    const popOver = popoverRef.current
    const bounds = inputRef.current.getBoundingClientRect()

    if (bounds.top > window.innerHeight / 2) {
      popOver.style.top = `32px`
      popOver.style.bottom = 'auto'
      popOver.style.height = `${ Math.floor(bounds.top - 32)}px`
      popOver.classList.add('above')
    } else {
      popOver.style.top = 'auto'
      popOver.style.bottom = `32px`
      popOver.style.height = `${ Math.floor(window.innerHeight - bounds.bottom - 32) }px`
      popOver.classList.remove('above')
    }

    popOver.style.left = `${bounds.left}px`
    popOver.style.width = `${bounds.width}px`
    popOver.togglePopover()
  }

  const id = useId()
  const buttonRef = useRef(null)
  const inputRef = useRef(null)
  const listBoxRef = useRef(null)
  const popoverRef = useRef(null)

  return (
    <div className="CvComboBox">
      <label id={`${id}-lb`} htmlFor={`${id}-in`}>{label}</label>
      <div>
        <input id={`${id}-in`} ref={inputRef} defaultValue={inputValue}/>
        <Button buttonRef={buttonRef} onPress={togglePopUp} />
      </div>
      <div ref={popoverRef} popover="auto" id={id} className="menu-popover">
        <div>
            <ListBox  
              items={items}
              listBoxRef={listBoxRef} 
              selectionMode="single"
              selectionBehavior="replace"
              selectedKeys={selectedKey}
              aria-labelledby={`${id}-lb`}
              aria-label="Suggestions"
            >
              {item => <ListBoxItem id={item.label}>{
                optionLabels ? optionLabels[item.label] : item.label
              }</ListBoxItem>}
            </ListBox>
        </div>
      </div>
    </div>
  )
}
```

I've had to abandon the use of ComboBox itself because of how tightly it is coupled to the Popover element. This shows promises, but Aria behavior implementation isn't my strong suit so I would appreciate any input on what I'm missing here, if anything.

**Comment by devongovett** [comment]
Is there a reason you must use native popover rather than the React Aria Popover component? I know it's shiny and new, and maybe we'll eventually support it, but is there anything wrong with using the existing Popover that our ComboBox is designed to work with in the meantime?

> One problem - it's entirely unnecessary with the native PopOver API.

Potentially? This would require testing on various screen readers to confirm. The native popover is not modal (meaning it does not hide elements outside it), so it may have the same problem.

**Comment by mmorris8** [comment]
I tried putting in my own Popover object hoping it would be able to get the popover properties being passed down from Combobox but that doesn't work. So the internal components do not work like their custom cousins that resort to the use functions like useComboBox - interesting. They are hard wired together.

I'm just trying to figure this out.

**Comment by mmorris8** [comment]
Ok, I fixed this by just flat out hacking the offending function. 

```typescript
/**
 * Hides all elements in the DOM outside the given targets from screen readers using aria-hidden,
 * and returns a function to revert these changes. In addition, changes to the DOM are watched
 * and new elements outside the targets are automatically hidden.
 * @param targets - The elements that should remain visible.
 * @param root - Nothing will be hidden above this element.
 * @returns - A function to restore all hidden elements.
 */
export function ariaHideOutside(targets: Element[], root = document.body) {
  // This function is incompatible with the new popover api. Disable if
  // any are present with an immediate return.
  if (document.querySelector('body:has([popover])')) return

  let visibleNodes = new Set<Element>(targets);
  let hiddenNodes = new Set<Element>();

```

I really dislike applying flat out hacks like this, but I'm out of other more "go with the flow" solutions.

**Comment by mmorris8** [comment]
The above did not sit well with me. I have solved it after a week of probing. I feel like a complete and total idiot at the simplicity of the fix - nest the popover.

```javascript
<ComboBox
      onOpenChange={(isOpen) => {
        // We have to open the native popover after it is rendered. By calling setTimeout without
        // a timer we defer this call to the end of the event stack - without this wrapping we get an
        // error.  The popoverToggle method is the same one seen above as we have to recalculate
        // our position once we are promoted to the top layer.
        setTimeout(() => popoverToggle(isOpen, popoverRef.current, wrapRef.current))
      }}    
    >
      <Label>{label}</Label>
      <div ref={wrapRef}>
        <Input />
        <Button />
      </div>
      <Popover>
        <div popover="manual" ref={popoverRef} anchor="providerFacets" className="menu-popover">
          <div> 
            <ListBox 
              items={items} 
              selectionMode="single" 
            >
              {item => <ListBoxItem id={item.label}>{
                optionLabels ? optionLabels[item.label] : item.label
              }</ListBoxItem>}
            </ListBox>
          </div>
        </div>
      </Popover>
    </ComboBox>
```
