### ISSUE TITLE
Checkbox inside Modal inside Table reads from Table checkbox's context

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#7075]
### Discussed in https://github.com/adobe/react-spectrum/discussions/7062

<div type='discussions-op-text'>

<sup>Originally posted by **devlzcode** September 21, 2024</sup>
I have a table and on each row are a set of actions which open a modal. One of these modals are a form and contain a checkbox which is causing this error: `Error: A slot prop is required. Valid slot names are "selection".`
How do I fix this other than moving the modal out of the table and handling its open sate manually?

Example:
```tsx
  <Cell>
    <DialogTrigger>
    <Button/>
    <Modal>
      <Dialog>
        <Checkbox/>
      <Dialog/>
    </Modal>
  </DialogTrigger>
<Cell>
```</div>

**Comment by swheeler7** [comment]
I am also seeing this issue when using the checkbox inside a GridList. As mentioned in the discussion [#7062](https://github.com/adobe/react-spectrum/discussions/7062) setting the slot to null resolves the issue but not sure if the root cause is the same as for the table or if this is a separate bug

**Comment by snowystinger** [comment]
Seems likely that it's the same issue.

Small snafu, we don't know if our Cells if the cell is the selection cell (the one that the selection Checkbox will be in).

I don't think we can really tell which column will be the selection column either.

So we could potentially allow for a default checkbox slot. Or we'll need to figure out some way to tell if the column a cell belongs to is the selection column.

Allowing a default is probably good enough because any Checkboxes with a slot specified are expecting to be inside something providing that context and slot. That ancestor would be clearing the Table provided context, so we wouldn't have a conflict.
