### ISSUE TITLE
Disabled `Tag` can be removed with keyboard nav

### ISSUE THREAD

**Issue by abeljohn** [adobe/react-spectrum#7080]
### Provide a general summary of the issue here

When a React Aria Components `TagList` contains only disabled items, the last disabled `Tag` can be removed by tabbing backwards into the list and pressing delete.

### 🤔 Expected Behavior?

Disabled `Tag`s should not be removed using the delete key.

### 😯 Current Behavior

Disabled `Tag`s can be focused by tabbing backwards, then removed by pressing delete.

See gif and CodeSandbox below
![2024-09-24 10 02 32](https://github.com/user-attachments/assets/faed5fa2-aae9-4867-8f5d-f6cfe27bcd7b)

### 💁 Possible Solution

This seems to be caused by a combination of two issues in `useTag`:

1. disabled `Tag`s do not set `tabIndex` to -1
2. the `onKeyDown` event handler does not check if the tag is disabled before calling `onRemove`

### 🔦 Context

I can work around this by validating the removed Tag IDs in my `onRemove` event handler, but it would be nice if this worked without needing validation, like how the inner remove button automatically has `isDisabled` set to prevent removing disabled Tags via clicking.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/loving-golick-8mnndy

### Version

"react-aria-components": "1.3.3"

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS Sonoma 14.5

**Comment by snowystinger** [comment]
This appears to be fixed on main and will be in the next release.
Here's a sandbox on the nightly. https://codesandbox.io/p/sandbox/autumn-cloud-f4pk33 Please let me know if I've messed up the instructions

**Comment by abeljohn** [comment]
Thanks for looking into this. I'm still able to reproduce the issue on the nightly build. It only happens when all the remaining Tags are disabled.
I've simplified the sandbox to have all keys disabled and added clearer instructions: https://codesandbox.io/p/sandbox/compassionate-jasper-2rks9m

**Comment by snowystinger** [comment]
Awesome, thank you for providing that. I can reproduce it now.

For whoever fixes this, the focus shouldn't go to the last Tag; it should go to the group as it does for forward navigation. In addition, hitting delete should also not remove the tag, but theoretically, if we fix the first issue, the other should become not possible (though another bug could make it so, so it is better to defensively handle that if possible)

**Comment by minzzang144** [comment]
Can I try it?
