### ISSUE TITLE
 Command + A Not Working with Virtualized GridList in react-aria-components

### ISSUE THREAD

**Issue by rohitsaini1995** [adobe/react-spectrum#7083]
### Provide a general summary of the issue here

While using the Virtualized GridList component with selectionMode set to multiple and selectionBehavior set to replace, the expected behavior for Command + A (on macOS) is to select all items. However, the Command + A keyboard shortcut is not working as intended.
Selections using Cmd + Click or Shift + Arrow work fine, allowing me to select multiple items, but pressing Command + A does not trigger the selection of all items in the grid.

### 🤔 Expected Behavior?

Pressing Command + A should select all items in the GridList when the component is configured with selectionMode="multiple".

### 😯 Current Behavior

No selection occurs when pressing Command + A.

### 🖥️ Steps to Reproduce

1.	Use the Virtualized GridList component from react-aria-components with selectionMode="multiple" and selectionBehavior="replace".
2.	Attempt to select all items using the Command + A keyboard shortcut.

here is the code example I created https://codesandbox.io/p/sandbox/objective-stitch-6mcp4h?file=%2Fsrc%2FApp.js

### Version

"react-aria-components": "^1.3.0",

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac

### 🧢 Your Company/Team

Acrobat Web

**Comment by snowystinger** [comment]
Thanks for the Issue, unfortunately, your codesandbox appears to be broken. Maybe missed saving it at the end? Once it renders we can check out the behaviour.

**Comment by rohitsaini1995** [comment]
@snowystinger I fixed the sandbox, but cause was similar to this bug https://github.com/adobe/react-spectrum/issues/7076
. It was not working because I have 0 as my id. So now this seems to be fixed. So, you can close this bug.
