### ISSUE TITLE
Nesting React Aria ListBox consumes memory and crashes browser 

### ISSUE THREAD

**Issue by lecstor** [adobe/react-spectrum#7119]
### Provide a general summary of the issue here

Nesting `ListBox` from react-aria-components sends the browser into a spin running cpu at 100% and incrementally consuming more memory until the browser crashes. Tested in Chrome, Firefox, and Safari.

```
<ListBox>
  <ListBoxItem>
    <ListBox>
      <ListBoxItem>Hello</ListBoxItem>
    </ListBox>
  </ListBoxItem>
</ListBox>
```

### 🤔 Expected Behavior?

Ideally the ListBoxes render and work as expected. If that isn't possible then it probably needs to throw an error. 

### 😯 Current Behavior

The browser appears to freeze up with cpu at 100% and incrementally more memory consumed until the browser crashes.

### 💁 Possible Solution

Sorry, no clue.

### 🔦 Context

I was using ListBoxes as the drop target for a visual web editor where each node is a component and each component that can take children utilises a listbox to accept child components.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/goofy-sky-c2sygk

### Version

react-aria-components: ^1.3.3

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you using?

MacOS

**Comment by reidbarber** [comment]
The Listbox pattern support having interactive elements inside items (see [ARIA APG](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/)). You could try using a [GridList](https://react-spectrum.adobe.com/react-aria/GridList.html) instead.
