### ISSUE TITLE
FocusStrategy (autoFocus) has no effect when using the ListBox

### ISSUE THREAD

**Issue by Persists** [adobe/react-spectrum#7120]
### Provide a general summary of the issue here

When using the `ListBox` component with the autoFocus prop set to either `"first"` or `"last"`, the focus is incorrectly applied to the `ListBox` itself, rather than the first or last item in the collection. This behaviour occurs when the `ListBox` is used standalone.

### 🤔 Expected Behavior?

The expected behaviour for the `ListBox` component with `autoFocus="first"` or `"last"` is that the focus should be automatically placed on the first or last item in the collection, respectively.

### 😯 Current Behavior

The current behaviour for the `ListBox` component with `autoFocus="first"` or `"last"` is that the focus is incorrectly placed on the `ListBox` container instead of the first or last item in the collection.

### 🔦 Context

It seems the issue lies in how the first and last keys are received in the `useEffect `within useSelectableCollection. Likely, the collection is not fully populated during the initial render (when the `useEffect` is triggered.

[Relevant code lines](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/selection/src/useSelectableCollection.ts#L382-L414)

_No response_

### 🖥️ Steps to Reproduce

[Codesandbox example](https://codesandbox.io/p/sandbox/priceless-bessie-l2wnyt?file=%2Fsrc%2FApp.js&workspaceId=62ec24d5-1f87-4653-b449-fcd53e8dac80) (Reload to trigger the autofocus)

### Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you using?

MacOs

**Comment by snowystinger** [comment]
I think you may have forgotten to make the codesandbox public?

**Comment by LFDanLu** [comment]
Seems related to some of the discussion we had in this issue: https://github.com/adobe/react-spectrum/issues/4793#issuecomment-2255094953. Perhaps we could try what the linked comment suggests, aka what Menu does to ensure autofocus works.
