### ISSUE TITLE
Improve URL Structure: Remove Exposed File Names

### ISSUE THREAD

**Issue by PruthviGBhat** [adobe/react-spectrum#7125]
### Provide a general summary of the feature here

The current URL structure exposes file names (e.g., index.html), which is considered a bad practice for security, user experience, and SEO.
### Specific Issues:
Exposes file structure and technology used
Appears cluttered and less professional
Potential duplicate content issues for search engines

### 🤔 Expected Behavior?

* URLs should not expose file names (e.g., index.html)
* Directory URLs should serve the index file automatically (e.g., https://react-spectrum.adobe.com/components/alert serves index.html)

### 😯 Current Behavior

![Screenshot 2024-10-01 095637](https://github.com/user-attachments/assets/8b19f9d9-2abb-49a2-a563-587cf57794e5)

### 💁 Possible Solution

Implement URL rewriting to remove file extensions and serve directories without exposing file names.
Example:
Before: https://react-spectrum.adobe.com/blog/index.html
After: https://react-spectrum.adobe.com/blog

### 🔦 Context

* This improvement aligns with Adobe's Web Security Guidelines and SEO best practices.
* Similar URL structures have been successfully implemented in other Adobe projects (e.g., Adobe Experience League).

**Comment by reidbarber** [comment]
Not sure there is any actual security issues here. index.html always gets resolved if no page is specified.
