### ISSUE TITLE
ComboBox: `defaultOpen` & controlled open state not working 

### ISSUE THREAD

**Issue by mJarsater** [adobe/react-spectrum#7149]
### Provide a general summary of the issue here

The ComboBox cannot function using the `defaultOpen` prop or by controlled open state (using `isOpen` + `onOpenChange`).

### 🤔 Expected Behavior?

I would expect the combobox to be able to handle controlled open state aswell as the default open prop just like the Popover does.

### 😯 Current Behavior

If using either `defaultOpen` or `isOpen={true}` it renders a small popover without any content. When interacting with the input field it shows the full combobox, but this can after this not be closed. 

#### Using `defaultOpen`
https://github.com/user-attachments/assets/a20dedc3-85a0-4c90-bcc3-6da65425f1a0

#### Using controlled open state
https://github.com/user-attachments/assets/e6bc19be-ff15-4742-a887-1eb8d6e95801

### 🖥️ Steps to Reproduce

1. Checkout the [react-aria-component starter](https://react-spectrum.adobe.com/react-aria/getting-started.html#starter-kits)
2. Add either `defaultOpen` or set up a controlled open state for the ComboBox
3. Interact with it in storybook

### Version

react-aria-components 1.4.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

macOs Sonoma 14.4.1

**Comment by LFDanLu** [comment]
ComboBox doesn't actually support `defaultOpen` or controlled open due to complications with the supporting those in the combobox hooks way back in its inception (see https://github.com/adobe/react-spectrum/issues/2464). We should probably hide those Popover props from https://react-spectrum.adobe.com/react-aria/ComboBox.html#popover.

**Comment by mJarsater** [comment]
@LFDanLu is there some recommended "work around" for this? 

We are trying to build a Search component that would look and behave like a ComboBox, but the controlled open state is a feature we'd like to include.

**Comment by LFDanLu** [comment]
In the past we've considered trying to add some kind of imperative way to open the combobox, perhaps by exposing something on its ref like `open` that could be called by a user to update its internal isOpen state and thus force the combobox open. For your use case are you looking for a fully controlled open state (i.e. you need to be able to programatically open and close the combobox in a variety of situations) or more of a defaultOpen case where you want it to be open on page load?

**Comment by mJarsater** [comment]
We would need both the fully controlled open state and defaultOpen state since we are building a design system, so no real way of using how all our users would want to use the component.

**Comment by LFDanLu** [comment]
Gotcha, we'd need to revisit the combobox hooks and do some heavy refactoring (I imagine) to support controlled open state, probably unlikely for the team to pick this up in the short term to be honest. We'd welcome any help into investigating how to support it though!

**Comment by mJarsater** [comment]
@LFDanLu Cool 👍🏻 

I started looking into using the `useComboBox` hook directly instead but ran into an issue with `state.collection`. In your [examples](https://react-spectrum.adobe.com/react-aria/useComboBox.html#styled-examples) the ListBox component should use the `state.collection` and map over it, however it does not work for me without specifying `.iterable`.


#### Works
<img width="528" alt="Screenshot 2024-10-14 at 15 22 51" src="https://github.com/user-attachments/assets/d665c7ef-c46a-42bf-8613-8b14a1b08625">

#### Doesn't work
<img width="528" alt="Screenshot 2024-10-14 at 15 22 58" src="https://github.com/user-attachments/assets/f354ca6c-e2cb-4563-bcc3-4e2b9b6aba86">


Any advice on how to tackle this? 

Typescript version: 5.6.2
React: ^16.14.0
