### ISSUE TITLE
`useButton` should not pass `href` as buttonProps when elementType is other than `a`

### ISSUE THREAD

**Issue by mehm8128** [adobe/react-spectrum#7207]
### Provide a general summary of the issue here

`useButton` is receiving `href`,  `target`, `rel` for the `elementType` `a` and in the below code, not return as the `buttonProps` when `elementType` is other than `a`. But because the condition of `href` seems to be not correct, such as `input`, `span`, and other elementType can receive it as props. Is this intended behavior? If not, I'd like to fix it.
https://github.com/adobe/react-spectrum/blob/db60babaf99790e679e9f6af68399103171fb925/packages/%40react-aria/button/src/useButton.ts#L75-L84

### 🤔 Expected Behavior?

When `elementType` is `input`, `span`, and so on, `href` props is not passed to the target element and only `a` can receive.

### 😯 Current Behavior

Even though `elementType` is `input`, `span`, and so on, `href` props is passed to the target element.

### 💁 Possible Solution

rewrite as below
```ts
href: elementType === 'a' && !isDisabled ? href : undefined,
```

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/reverent-ives-hl88v2

### Version

2.21.0-beta.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

WSL2

**Comment by devongovett** [comment]
I think that sounds correct to pass "a" as the element type to the hook, even if you're rendering a router link. The hook needs to know what HTML element is going to be rendered in order to generate the correct attributes for it.
