### ISSUE TITLE
Modal Keyboard Dismissal doesn't work with Framer Motion Components

### ISSUE THREAD

**Issue by deltasierra96** [adobe/react-spectrum#7209]
### Provide a general summary of the issue here

When using Framer Motion to wrap React Aria components, keyboard dismissal doesn't work when pressing the escape key.

### 🤔 Expected Behavior?

Modal closes when user presses the escape key.

### 😯 Current Behavior

Modal doesn't listen for the escape key to dismiss modal.

### 🖥️ Steps to Reproduce

Example using Codesandbox can be seen [here](https://codesandbox.io/p/sandbox/sad-sara-xs7ypg)

I've copied and pasted the exact [example ](https://react-spectrum.adobe.com/react-aria/styling.html#plugin )in the RAC docs with the issue still persisting.

The issue still occurs with the component composition used in my other [post](https://github.com/adobe/react-spectrum/discussions/7208).

I have tried downgrading both RAC and Framer Motion to much earlier versions with no success.

### Version

1.4.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

Windows 11

**Comment by snowystinger** [comment]
I think you're just missing a `Dialog`? When I add it to your codesandbox example here, the Escape key works as expected. Is there a reason you're trying to omit that? It is needed in order to handle focus appropriately.

**Comment by deltasierra96** [comment]
> I think you're just missing a `Dialog`? When I add it to your codesandbox example here, the Escape key works as expected. Is there a reason you're trying to omit that? It is needed in order to handle focus appropriately.

Apologies, I've updated the Codesandbox with the correct version. I pasted the wrong code before heading to bed last last night.

**Comment by snowystinger** [comment]
No worries, but it does appear to be focus related. If you use a tool like NerdeFocus, you can watch where focus is in the document as it moves around. It never makes it to the dialog.
I also noticed that if I focus the button inside the dialog, the escape key works as expected.

I suspect this is due to timing, the dialog can't receive focus when we try to move it there because of the animation. Or, we move focus there and the animation causes some sort of remount. I don't know enough about how framer motion works to be able to tell.

I'd try putting some breakpoints in to narrow it down.
In here is a good place to start https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/dialog/src/useDialog.ts#L39

**Comment by deltasierra96** [comment]
As it appears, applying the visibility: hidden/visible CSS property on the Dialog was interfering with its focus ref. Appears to be working after removing, even with extended animation delays.

I feel incredibly dumb not noticing this but couldn't understand how or why a simple CSS property would cause the ref to fail.

Thanks for the recommendation on the NerdeFocus plugin - it's fantastic.

**Comment by deltasierra96** [comment]
> No worries, but it does appear to be focus related. If you use a tool like NerdeFocus, you can watch where focus is in the document as it moves around. It never makes it to the dialog. I also noticed that if I focus the button inside the dialog, the escape key works as expected.
> 
> I suspect this is due to timing, the dialog can't receive focus when we try to move it there because of the animation. Or, we move focus there and the animation causes some sort of remount. I don't know enough about how framer motion works to be able to tell.
> 
> I'd try putting some breakpoints in to narrow it down. In here is a good place to start https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/dialog/src/useDialog.ts#L39

As it appears, applying the visibility: hidden/visible CSS property on the Dialog was interfering with its focus ref. Appears to be working after removing, even with extended animation delays.

I feel incredibly dumb not noticing this but couldn't understand how or why a simple CSS property would cause the ref to fail.

Thanks for the recommendation on the NerdeFocus plugin - it's fantastic.

**Comment by snowystinger** [comment]
Glad you got it working. Don't feel dumb, we've all been tripped up by that one before.
