### ISSUE TITLE
[BUG] - Autocomplete - Text selection with Shift + Home/End isn't working

### ISSUE THREAD

**Issue by c0d3rm0n** [adobe/react-spectrum#7228]
### Provide a general summary of the issue here

I'm using Autocomplete from NextUI. They created they UI based in yours.
I created an issue there to solve one problem with text selection in that component.
[https://github.com/nextui-org/nextui/issues/3854](https://github.com/nextui-org/nextui/issues/3854)
They requested me to create a new issue upstream. 

Text selection using Shift + Home/End doesn't work in Autocomplete/Combobox input (Text Input).
For example, I can make Shift + Left/Right Arrow and it works just fine. But the other key combination no...
It happens in Firefox and Chrome browsers, in my project or even in your website...
Is it possible to make it work?

### 🤔 Expected Behavior?

1 - Click in autocomplete
2 - Type something...
3 - Click or move the cursor to the middle of the text, for example.
4 - Make Shift + Home/End
5 - Part of the text should be selected

### 😯 Current Behavior

1 - Click in autocomplete
2 - Type something...
3 - Click or move the cursor to the middle of the text, for example.
4 - Make Shift + Home/End
5 - It does nothing at all...

### 🖥️ Steps to Reproduce

1 - Click in autocomplete
2 - Type something...
3 - Click or move the cursor to the middle of the text, for example.
4 - Make Shift + Home/End

### Version

0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Linux x64

**Comment by snowystinger** [comment]
So the pattern says
> Home (Optional): Either moves focus to and selects the first option or, if the combobox is editable, returns focus to the combobox and places the cursor on the first character.
> End (Optional): Either moves focus to the last option or, if the combobox is editable, returns focus to the combobox and places the cursor after the last character.

https://www.w3.org/WAI/ARIA/apg/patterns/combobox/

Will need to consult with Accessibility. Historically for Combobox, Home/End has only controlled the Selection in the popup.

@majornista ^

**Comment by c0d3rm0n** [comment]
Are there any news related to this subject?

**Comment by majornista** [comment]
@snowystinger and @c0d3rm0n 

Shift+Home/End will work on the input when the Listbox for the Autocomplete is closed. You can test this behavior in the [RAC ComboBox example](https://react-spectrum.adobe.com/react-aria/ComboBox.html#example). If one were to type in a value that returns no results, like "Flamingo" for example, you can use ArrowLeft to move the cursor to the middle of the word, and then Shift+Home to select the first half of the word. However, with the ListBox open, Home and End move focus in the ListBox. The [usage example for the NextUI implementation](https://nextui.org/docs/components/autocomplete#usage) opens the ListBox to display "No results found." when there are no matches, so Home/End is always interpreted as being intended for the ListBox. 

Perhaps we should interpret the Shift key modifier differently for Home/End, when the ListBox is open, or when there are less than 2 results. This however could have implications for any future multiselect or TagGroup implementation.
