### ISSUE TITLE
[RAC] Introduce a delay for Menu's submenus closing.

### ISSUE THREAD

**Issue by zommerberg** [adobe/react-spectrum#7242]
### Provide a general summary of the feature here

When using the react aria components' submenus they close too quickly which causes confusion when a user accidentally hovers on another item in the menu. 

Here is an example of it, I have a dropdown menu in the top right corner which causes this conflict:

https://github.com/user-attachments/assets/950ee6b1-d735-4d45-9f16-222b9135fb6b

### 🤔 Expected Behavior?

I want to add a delay before the submenu closes. During this delay period, the code should check if the user has hovered over the submenu again. If they have, the submenu should stay open instead of closing.

### 😯 Current Behavior

The submenu closes immediately which doesnt allow the user to click on the submenu item.

### 🔦 Context

Video included

**Comment by reidbarber** [comment]
Maybe the timeout isn't being properly reset in [useSafelyMouseToSubmenu](https://github.com/adobe/react-spectrum/blob/68e305768cb829bab7b9836dded593bd731259f3/packages/%40react-aria/menu/src/useSafelyMouseToSubmenu.ts)?

**Comment by zommerberg** [comment]
I have the same issue in the official tailwindcss example, it seems like once it detects that i hover on another menu item it immediately closes the submenu (as shown in the video)

https://github.com/user-attachments/assets/8b1e15f9-415a-422d-9bed-c13fae5e6e44

**Comment by snowystinger** [comment]
This is a good guide for the expected behavior https://react-spectrum.adobe.com/blog/creating-a-pointer-friendly-submenu-experience.html

**Comment by zommerberg** [comment]
Then it seems to be a bug

**Comment by reidbarber** [comment]
I think this may just be an issue with the Tailwind starter. I noticed in the Submenu story we render a RAC Popover, but our custom Menu component also renders a RAC Popover. I noticed pointer events weren't being prevented on the popover like they should, and it's working as expected in the docs in React Aria and React Spectrum.

**Comment by zommerberg** [comment]
My implementations follows the official example with popover around the menu and i still have the issue which is weird.

**Comment by reidbarber** [comment]
Just tested https://github.com/adobe/react-spectrum/pull/7251 and I'm not seeing the issue in that story anymore. I'm not seeing it any the docs site examples anywhere, but if you're still seeing it somewhere, let me know.

**Comment by zommerberg** [comment]
@reidbarber  You are right! I didnt see there was a hidden popup within the Menu.

The fix resolved it, thank you!
