### ISSUE TITLE
Headless toast for React Aria

### ISSUE THREAD

**Issue by musjj** [adobe/react-spectrum#7252]
### Provide a general summary of the feature here

There's a toast component for React Spectrum: https://react-spectrum.adobe.com/react-spectrum/Toast.html. But there's no headless/unstyled equivalent in React Aria.

### 🤔 Expected Behavior?

A headless/unstyled toast component for React Aria.

### 😯 Current Behavior

Toast component is only available for React Spectrum users.

**Comment by reidbarber** [comment]
See [useToast](https://react-spectrum.adobe.com/react-aria/useToast.html). We'll also be adding Toast to React Aria Components in the future.

**Comment by yihuiliao** [comment]
I'm going to close this since we already have a ticket in our project board for this. You can track [RAC Toast here](https://github.com/orgs/adobe/projects/19/views/4?filterQuery=toast&pane=issue&itemId=60631165)
