### ISSUE TITLE
Unnecessary dom element when using tag

### ISSUE THREAD

**Issue by pan-alexey** [adobe/react-spectrum#7259]
### Provide a general summary of the issue here

When using TagGroup with the onRemove callback, focusing on any element, not necessarily a tag, adds a div to the body with the description "press delete to remove tag."

![telegram-cloud-photo-size-2-5249162919135012243-y](https://github.com/user-attachments/assets/81e68eca-81ac-44ae-b87f-0039bbb0a82b)

### 🤔 Expected Behavior?

The text suggesting to delete the tag appears only when focusing on a tag element that can be removed.

### 😯 Current Behavior

When using TagGroup with the onRemove callback, focusing on any element, not necessarily a tag, adds a div to the body with the description "press delete to remove tag."

### 🖥️ Steps to Reproduce

Open https://react-spectrum.adobe.com/react-aria/TagGroup.html, focus to any element.

### Version

3.35.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac OS

**Comment by snowystinger** [comment]
Thanks for the issue. Is the div causing a problem?

**Comment by pan-alexey** [comment]
It is not critically important, but in the example, the problem is that when focusing on any element, it is not just a hidden element; it's an element that changes the accessibility description of the element (not focused).



![Uploading Screenshot 2024-10-30 at 16.40.21.png…]()

**Comment by snowystinger** [comment]
I don't see an issue with that. It won't be announced and it's not visible. It's only a needed description when using the keyboard, so we turn it on whenever we detect the user is interacting through the keyboard.

Here's the original issue from our accessibility team https://github.com/adobe/react-spectrum/issues/4278

I'm going to close this as it's not causing an issue and it's been extensively tested with accessibility. Changing it would require re-testing all of it for no clear benefit.

Thanks for understanding
