### ISSUE TITLE
Clicking triggers focus ring

### ISSUE THREAD

**Issue by musjj** [adobe/react-spectrum#7276]
### Provide a general summary of the issue here

[Kooha-2024-10-29-04-48-27.webm](https://github.com/user-attachments/assets/283ea428-8bd7-4236-8f20-cab2db2a1447)

Clicking on elements like `<Link>` or `<Button>` causes a focus ring to appear around the element. Clicking and dragging outside of the element will make the focus ring stay even when you let go of the button. You can of course style it so that the focus ring will not be visible, but now it will never be visible even when tab-focusing which of course hurts accessibility.

The behavior occurs both in Chrome and Firefox. Strangely, I can't reproduce it in the preview in the [documentation page](https://react-spectrum.adobe.com/react-aria/Button.html). 

### 🤔 Expected Behavior?

Behave like a normal native element. Clicking on element should not trigger the focus ring.

### 😯 Current Behavior

See the video above.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/amazing-torvalds-mqjdy6

### Version

1.4.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Linux

**Comment by reidbarber** [comment]
You should add `outline: none` as a default style for these elements (you'll notice we do for all our docs examples). Similar closed issue: https://github.com/adobe/react-spectrum/issues/6683

**Comment by musjj** [comment]
Updated the sandbox to include `outline: none` (https://codesandbox.io/p/sandbox/amazing-torvalds-mqjdy6), but the issue still occurs. Is there something else you need to do?

**Comment by musjj** [comment]
Thank you, it works pretty well!
