### ISSUE TITLE
NVDA screen reader, when using arrow keys in RAC <Table /> focus gets stuck on checkboxes

### ISSUE THREAD

**Issue by ihsib** [adobe/react-spectrum#7300]
### Provide a general summary of the issue here

While using the NVDA screen reader with the React Aria Components Table, focus gets stuck in a table row once you come to a checkbox. [This behavior can also be observer in the docs for React Aria Components Table which uses checkbox](https://react-spectrum.adobe.com/react-aria/Table.html)

### 🤔 Expected Behavior?

Expect table to allow user to navigate between checkboxes and text cells while using the left, right arrow keys.

### 😯 Current Behavior

Once focus is on a checkbox you can not navigate to any other cell in the table with the arrow keys.

### 🖥️ Steps to Reproduce

1. Go to https://react-spectrum.adobe.com/react-aria/Table.html
2. Activate the [NVDA screen reader](https://www.nvaccess.org/download/)
3. Click just above the table
4. Tab into the table and start navigating to a checkbox
5. Verify that focus is not stuck and the screen reader voice is out of sync

### Version

latest

### What browsers are you seeing the problem on?

Microsoft Edge

### If other, please specify.

Firefox

### What operating system are you using?

Windows

### 🧢 Your Company/Team

Adobe React aria components

**Comment by devongovett** [comment]
What happens is that NVDA shifts from focus mode into browse mode. This is known issue in NVDA: https://github.com/nvaccess/nvda/issues/11413. The user can always manually switch to focus mode, and then NVDA will stay in focus mode. I don't think there's much we can do here other than wait for a fix in NVDA.
