### ISSUE TITLE
ColorArea: Transparent border apply to wrong edges

### ISSUE THREAD

**Issue by thorbde** [adobe/react-spectrum#7302]
### Provide a general summary of the issue here

We ran into a strange issue where we are using transparent borders on the ColorArea. But it seems like they apply to the incorrect borders, the bottom border is applied to the top, left is applied to the right and vice versa. 

<img width="618" alt="Screenshot 2024-10-31 at 22 26 14" src="https://github.com/user-attachments/assets/0197bf09-38a5-48bf-8b17-f7d88d98aae0">

### 🤔 Expected Behavior?

Expect the borders to apply to the correct edges.

### 😯 Current Behavior

See description.

### 🖥️ Steps to Reproduce

Apply a semi transparent border to the ColorArea

### Version

1.4.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macos sequoia

**Comment by reidbarber** [comment]
Can you try using `background-origin: border-box;`?

**Comment by thorbde** [comment]
@reidbarber Does not change anything, same result

**Comment by reidbarber** [comment]
How about `background-repeat: no-repeat` ?

**Comment by thorbde** [comment]
Same result

**Comment by reidbarber** [comment]
Can you provide a codesandbox/stackblitz reproducing this? I'm throwing these styles onto the docs examples and seeing good results.

**Comment by thorbde** [comment]
@reidbarber  https://codesandbox.io/p/sandbox/pensive-https-wvxsf4
