### ISSUE TITLE
Full view of all Illustrations

### ISSUE THREAD

**Issue by Lexachoc** [adobe/react-spectrum#7314]
### 🙋 Documentation Request

Hi, 
I came across the [IllustratedMessage](https://react-spectrum.adobe.com/react-spectrum/IllustratedMessage.html#example-illustrations) part and I like the illustrations. But I couldn't find a complete list or overview of all available illustrations.
The only one I found is for [Icons](https://spectrum.adobe.com/page/icons/), and there are no illustrations there.

Is it available so we can see/know how to import the illustrations we want?

**Comment by Lexachoc** [comment]
@nwidynski Thanks for the hint of the NPM registry. Now I have a rough idea of how many illustrations are available.

It would be good to have a search page for illustrations like https://spectrum.adobe.com/page/icons/ though.

**Comment by reidbarber** [comment]
Unfortunately, there isn't a large set like there is for icons. All the available ones are listed on that page: https://react-spectrum.adobe.com/react-spectrum/IllustratedMessage.html#example-illustrations

Additionally, there is a File and Folder one, mostly used for cases like ListView: https://react-spectrum.adobe.com/react-spectrum/ListView.html#complex-items

**Comment by Lexachoc** [comment]
Thank you both! This can be closed then.
