### ISSUE TITLE
[RAC] Disabled DatePicker stops Tab focus moving forward when used inside Modal & Dialog

### ISSUE THREAD

**Issue by joonass-visma** [adobe/react-spectrum#7321]
### Provide a general summary of the issue here

When having disabled DatePicker inside Modal Dialog with some focusable elements before and after it (e.g. TextFields) and you start Tabbing through the fields with keyboard, the focus won't move past the DatePicker.

### 🤔 Expected Behavior?

Keyboard focus should jump over the disabled DatePicker and continue normally to next focusable element.

### 😯 Current Behavior

Keyboard focus gets stuck to last focusable element before disabled DatePicker.

### 🖥️ Steps to Reproduce

Try adding to DatePicker with isDisabled=true after the "Last name" TextField in this example: https://react-spectrum.adobe.com/react-aria/Modal.html#example

### Version

react-aria-components v1.4.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Windows 11

**Comment by nwidynski** [comment]
@joonass-visma Can confirm this issue. As an intermediary solution, set the `onKeyDown` property of the last focusable element before the disabled date picker (e.g. the textfield) to an empty function.

@snowystinger We need to set `tabIndex` to -1 when disabled here.
https://github.com/adobe/react-spectrum/blob/c7033239f65fd4014aaa5ff077d11541112e56e6/packages/%40react-aria/spinbutton/src/useSpinButton.ts#L177-L189
