### ISSUE TITLE
NumberParser: Incorrect Parsing of Comma-Separated Number Strings

### ISSUE THREAD

**Issue by tihcamos** [adobe/react-spectrum#7420]
### Provide a general summary of the issue here

When using the `NumberParser` from `@internationalized/number`, I encountered an issue where the string `'1,1,1.2'` is being parsed incorrectly as `111.2`. 

### 🤔 Expected Behavior?

The input string `'1,1,1.2'` should throw a parsing error (since it is not a valid number format in any locale),

### 😯 Current Behavior

The input string `'1,1,1.2'` is parsed as `111.2`, which appears to ignore the commas inappropriately and concatenate the numbers.

### 🖥️ Steps to Reproduce

1. Import and initialize `NumberParser`:
    ```javascript
    import { NumberParser } from '@internationalized/number';

    const parser = new NumberParser('en-US'); // Example locale
    const result = parser.parse('1,1,1.2');
    console.log(result); // Outputs: 111.2
    ```
2. Observe that the output is `111.2` instead of an error or a correctly parsed value.

### Version

3.5.4

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 11

**Comment by LFDanLu** [comment]
@snowystinger do you happen to remember if this was feasible or if there were any edge cases that you encountered when working on NumberField that prevented this? If feels like we could perhaps have a case for this in `parse` or `isValidPartialNumber`?
