### ISSUE TITLE
Bad coding practice in the example

### ISSUE THREAD

**Issue by SmileHub** [adobe/react-spectrum#7432]
### 🙋 Documentation Request

In https://react-spectrum.adobe.com/react-aria/Calendar.html#calendargridheader
the hook is called conditionally:
 `let formatted = date ? useDateFormatter().format(date) : 'None';`

which is a bad practice in react. I'd suggest something like this, or alike:
```
const {format}= useDateFormatter();
let formatted = date ? format(date) : 'None';
```

**Comment by snowystinger** [comment]
Looks like a fine alteration. The general guiding principles of our docs is to keep the examples short, this won't expand it by much.
