### ISSUE TITLE
Tab ref is null when using local ref in conjunction with forwarded ref

### ISSUE THREAD

**Issue by axelthat** [adobe/react-spectrum#7496]
### Provide a general summary of the issue here

I have a next js 14 app where I have created a wrapper around `Tab` component. It leverages both local ref and forward ref. When I use this component in pages and I ref it, ref is null.

```
// components/CustomTab.tsx
import { forwardRef, useImperativeHandle, useRef } from "react";
import { Tab, TabProps } from "react-aria-components";

export const CustomTab = forwardRef<HTMLDivElement, TabProps>(
    ({ ...props }, forwardedRef) => {
        const ref = useRef<HTMLDivElement | null>(null);

        useImperativeHandle(forwardedRef, () => ref.current as HTMLDivElement);

        return <Tab {...props} ref={ref} />;
    }
);

CustomTab.displayName = "CustomTab";
```

```
// pages/flow.tsx
import { CustomTab } from "@/components/CustomTab";
import { useEffect, useRef } from "react";
import { TabList, TabPanel, Tabs } from "react-aria-components";

export default function FlowPage() {
    const ref = useRef<HTMLDivElement | null>(null);

    useEffect(() => {
        setTimeout(() => {
            console.log(ref.current); // is null
        }, 1000);
    }, []);

    return (
        <>
            <Tabs>
                <TabList>
                    <CustomTab id="apple" ref={ref}>
                        Apple
                    </CustomTab>
                    <CustomTab id="mango">Mango</CustomTab>
                </TabList>

                <TabPanel id="apple">Apple tab</TabPanel>
                <TabPanel id="mango">Mango tab</TabPanel>
            </Tabs>
        </>
    );
}
```

### 🤔 Expected Behavior?

`ref.current` should be tab's html element.

### 😯 Current Behavior

`ref.current` is null.

### 🖥️ Steps to Reproduce

https://stackblitz.com/~/github.com/axelthat/nextjs-rac-bug-1

### Version

^1.5.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

macOS 15.1.1

**Comment by snowystinger** [comment]
Looks like something is wrong with how you're merging the refs via imperative handler, if you just pass the forwardedRef directly through to the Tab, it appears to work.

You could use our utility to merge refs, https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/mergeRefs.ts or use a similar idea

**Comment by axelthat** [comment]
Beautiful, that works. Thank you @snowystinger.
