### ISSUE TITLE
Support for rapid fire press events on button & usePress

### ISSUE THREAD

**Issue by elieven** [adobe/react-spectrum#7504]
### Provide a general summary of the feature here

The ability to have buttons and related hooks behave like native html buttons when focused and enter button held where they rapid fire press / click events.

### 🤔 Expected Behavior?

When a button is held down it should be able to rapid fire press events (optionally).

### 😯 Current Behavior

The press event only gets fired once when enter key held when button is in focus.

### 🔦 Context

I was trying to make a button with react aria / use the react aria's own button component and the behavior of firing the click / press event rapidly when the button is in focus and the enter key is held down was not there.

**Comment by snowystinger** [comment]
Can you provide some context around the use case for this?
A real world example of when it's used would be very helpful.

**Comment by elieven** [comment]
Well I have some control panel kind of situation in an app that has some counters you can increment and people quite like the ability to hold down enter to quickly increment the number. An alternative could be a direct number input which would likely be OK. 

It is quite a common behavior on the web though and it would be nice to be able to do it as one would expect buttons to behave that way no? Like pressing any key on the keyboard it first "does the input" once e.g. outputs a letter and then when you keep holding it down it keeps firing the event rapidly.

Is there a reason it was decided to not have such a behavior for buttons?

**Comment by snowystinger** [comment]
If you are incrementing something, spin button is the way you want to go. This is built into NumberField. There's also a useSpinButton hook we could consider making more public.

The reason button doesn't do that right now is to assist people who might have mobile impairments which could cause them to press a button for longer than intended.

An additional benefit of Spin button is that they are typically paired with a field so that it communicates what the step size is for holding it down. Otherwise the field could progress much more quickly (or slowly) than the user expects.
Announcements are also tricky when it comes to situations like this, spin button can help with that.

**Comment by elieven** [comment]
Hmm. At least a few of these are a bit more complex inputs that just a number. They are more of an "add object to array" buttons with the number showing how many objects with this id are in the array. The reason why a direct number input does not work for it is that the object "template" could have been modified and adding a new one to the list or removing previously added ones would not work with direct number input manipulation. But for when one wants to add multiple entries with the current template quickly the current pattern is to hold down enter and use the rapid fire click event. Same for removing.

**Comment by snowystinger** [comment]
We had a chat in the team today. This should be doable already. You'd `setInterval` in `onPressStart`, and cancel it in `onPressEnd`.

If you have it available to keyboard users, you probably want it available for mouse users as well. This approach will handle both.

I'm going to close this as build-able.

**Comment by elieven** [comment]
Yep, thanks. Did it myself. I don't know why I didn't think of that. Probably just assumed there are more fancy things, edge cases and potential cross browser issues that I might not be considering but yeah it works just fine!
