### ISSUE TITLE
ColorField does not accept pasting lower case hex code

### ISSUE THREAD

**Issue by BenSwennen** [adobe/react-spectrum#7547]
### Provide a general summary of the issue here

When pasting a lower case hex code (e.g. `#e84e0f`) into the ColorField, it stays empty. Pasting a upper cased one (e.g. `#E84E0F`) works.

### 🤔 Expected Behavior?

ColorField accepts pasting a lower cased hex code.

### 😯 Current Behavior

ColorField stays empty after pasting a lower cased hex code.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/reverent-sun-c9cd2t

1. Copy lower cased hex code (`#e84e0f`)
2. Paste lower cased hex code in ColorField
3. Unexpected: ColorField stays empty (paste not working)

### Version

react-aria-components 1.5.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by snowystinger** [comment]
I've just tried this on Chrome on my Mac both in the sandbox and in our docs, it appears to work.

Could you provide a video showing it reproducing? Maybe I missed a step.
