### ISSUE TITLE
Pressing Tab in desktop Safari does not tab between focusable items in documentation pages

### ISSUE THREAD

**Issue by mohsen1** [adobe/react-spectrum#758]
# 🐛 Bug Report 
See screen recording. I kept pressing tab while recording 
![bug](https://user-images.githubusercontent.com/543633/87570469-b73f6280-c696-11ea-8474-662f409a7a67.gif)

## 🤔 Expected Behavior
In Chrome it does cycle through focusable items 

## 😯 Current Behavior
After a few tab key presses it focuses the address bar 

## 🌍 Your Environment

macOS Safari 13

**Comment by devongovett** [comment]
Unfortunately, this is a Safari issue. There's a setting you must enable to make Safari handle tabbing as expected.

<img width="886" alt="Screen Shot 2020-07-15 at 10 01 32 AM" src="https://user-images.githubusercontent.com/19409/87573797-4c842c00-c682-11ea-9dd3-6117b4f49dc7.png">

**Comment by mohsen1** [comment]
I didn't know about that option. However, with that option off I'm still able to tab through butting in GitHub, Twitter and even Paul Graham's website:

![9](https://user-images.githubusercontent.com/543633/87576283-1e611500-c69f-11ea-9bfb-34ebc7a96921.gif)

**Comment by devongovett** [comment]
I think the difference is, with the option on it highlights links, buttons, etc. but without it only highlights form elements. You can see this on Github: with the option on, you can tab through all the links on the homepage, but without, you only go to buttons and form elements.

**Comment by mohsen1** [comment]
Thank you for explaining! That makes sense! Congrats on the launch! This looks very good!
