### ISSUE TITLE
Get started link is broken (404)

### ISSUE THREAD

**Issue by itohiro73** [adobe/react-spectrum#764]
# 🙋 Documentation Request

It seems the "Get Started" link in the document top page is broken.
https://react-spectrum.adobe.com/react-spectrum

Current Link (not existing):
https://react-spectrum.adobe.com/getting-started.html

Correct Link:
https://react-spectrum.adobe.com/react-spectrum/getting-started.html

## 🧢 Your Company/Team

N/A

**Comment by devongovett** [comment]
Oh hmm, it's a relative link... Seems to work if you have a trailing slash: https://react-spectrum.adobe.com/react-spectrum/

**Comment by heyjiawei** [comment]
Hey can I help fix this?

**Comment by ross-pfahler** [comment]
https://react-spectrum.adobe.com/react-spectrum should now redirect to https://react-spectrum.adobe.com/react-spectrum/.

Thank you for the issue @itohiro73!
