### ISSUE TITLE
Types of useFocusRing incompatible with useButton

### ISSUE THREAD

**Issue by rovansteen** [adobe/react-spectrum#766]
# 🐛 Bug Report 

Using `useFocusRing` in combination with `useButton` like so

```tsx
const ref = useRef<HTMLElement>();
const { isFocusVisible, focusProps } = useFocusRing();
const { buttonProps, isPressed } = useButton(focusProps, ref);
```
results in the following type error
```
Argument of type 'HTMLAttributes<HTMLElement>' is not assignable to parameter of type 'AriaButtonProps'.
  Types of property 'onFocus' are incompatible.
    Type '((event: FocusEvent<HTMLElement>) => void) | undefined' is not assignable to type '((e: FocusEvent<Element>) => void) | undefined'.
      Type '(event: FocusEvent<HTMLElement>) => void' is not assignable to type '(e: FocusEvent<Element>) => void'.
        Types of parameters 'event' and 'e' are incompatible.
          Type 'FocusEvent<Element>' is not assignable to type 'FocusEvent<HTMLElement>'.
            Type 'Element' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 106 more.ts(2345)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0.2

**Comment by devongovett** [comment]
This is because `useFocusRing` returns DOM props, but `useButton` accepts props for a button component. I think what you need to do is pass the props for the button (e.g. children, `onPress`, etc.) to `useButton`, and combine the props from `useFocusRing` onto your DOM node.

```jsx
function Button(props) {
  const { isFocusVisible, focusProps } = useFocusRing();
  const { buttonProps, isPressed } = useButton(focusProps, ref);

  return (
    <button {...focusProps} {...buttonProps}>{props.children}</button>
  );
}
```

Even better, check the [mergeProps](https://react-spectrum.adobe.com/react-aria/mergeProps.html) utility to help merge those props and ensure one doesn't overwrite the other.

```jsx
<button {...mergeProps(focusProps, buttonProps)}>{props.children}</button>
```

**Comment by devongovett** [comment]
Going to close this. Feel free to reopen if the solution doesn't work for you. 😄

**Comment by rovansteen** [comment]
@devongovett thanks! In your example you are still passing `focusProps` to `useButton` but I assume that's a typo. Without that it works. 

Just wondering why `useButton` is using `Element` and not `HTMLElement` for it's types?

**Comment by devongovett** [comment]
Ah, I think the `FocusEvent` type comes from @types/react. That seems to default to `Element` instead of `HTMLElement`...

**Comment by jtmclucas13** [comment]
I'm seeing this same issue with `useFocusRing()` and `useTextField`. Let's say I have an interface defined as follows, intending to allow any valid argument to `useTextField` be a prop: 

```
type CustomTextAreaProps = {
	customProp: any;
} & Parameters<typeof useTextField>[0];
```

and the component usage is as follows:

```
function CustomTextArea(props: CustomTextAreaProps) {
	const inputRef = useRef(null);
	const { inputProps } = useTextField(
		{ ...props, inputElementType: 'textarea' },
		inputRef
	);

	return <textarea {...inputProps} />;
}
```

In a parent component, I get the same `onFocus` type error as described in the original issue (`Type 'FocusEvent<Element>' is not assignable to type 'FocusEvent<HTMLElement>').` when I try to pass in merged props

```
const ProblemComponent = props => {
	const { focusProps } = useFocusRing({
		autoFocus: true,
		isTextInput: true,
	});
	const { hoverProps } = useHover({});

	return <CustomTextArea {...mergeProps(hoverProps, focusProps)} />;
};
```

This is a very slimmed down version of my use case, but it should show the problem sufficiently.
