### ISSUE TITLE
There are some css warnings

### ISSUE THREAD

**Issue by shotaCoffee** [adobe/react-spectrum#768]
# 🐛 Bug Report 

![image](https://user-images.githubusercontent.com/14342186/87673518-a8000800-c7af-11ea-9442-1cbcce57c9dc.png)

## 🤔 Expected Behavior

After installing, the button was displayed according to the document

https://react-spectrum.adobe.com/react-spectrum/getting-started.html

## 😯 Current Behavior

Here is the code
```
import React from 'react';
import './App.css';
import {
  Provider,
  defaultTheme,
  Button
} from '@adobe/react-spectrum';

function App() {
  return (
    <div className="App">
      <Provider theme={defaultTheme}>
        <Button
          variant="cta"
          onPress={() => alert('Hey there!')}>
          Hello React Spectrum!
        </Button>
      </Provider>
    </div>
  );
}

export default App;
```

![image](https://user-images.githubusercontent.com/14342186/87673518-a8000800-c7af-11ea-9442-1cbcce57c9dc.png)

## 💁 Possible Solution

I think it's enough to change the code as below
`fill-available` -> `stretch`
`start` -> `flex-start`

I think the corresponding file is here
`react-spectrum/packages/@adobe/spectrum-css-temp/components/modal/index.css`

`react-spectrum/packages/@adobe/spectrum-css-temp/components/tray/index.css`

## 🔦 Context

I want to get rid of warnings and be aware of warnings and errors that I really want to see

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0.2
| Browser          | Chrome（latest）
| Operating System | MacOS Catalina（10.15.5）

I submitted my first assignment.
Please let me know if the submission method is incorrect.
Thank you for confirmation.

**Comment by snowystinger** [comment]
Hi! thanks for filing an issue. Some work has been done around this, however, we cannot get rid of all of them at this point in time.
https://github.com/adobe/react-spectrum/pull/686

the corresponding issue upstream is https://github.com/adobe/spectrum-css/issues/737

We might be able to fix the `start` one, but at the time I worked on that branch I didn't have the time to look into why the moz prefix wasn't being added. https://github.com/adobe/react-spectrum/pull/686#discussion_r446379464 I'm hoping it's not related to the version of autoprefixer like 'fill-available' is

**Comment by shotaCoffee** [comment]
Thank you for confirmation!

We've found that it's supported, so wait for the next release.

I'll try to find something that I can fix.

This issue will be closed.

Thank you

**Comment by devongovett** [comment]
Reopening. We'll need to fix these warnings ourselves in the meantime.

**Comment by deadcoder0904** [comment]
[this pr seems merged](https://github.com/adobe/react-spectrum/pull/2695) but its still gives me a warning. i'm using `"@adobe/react-spectrum": "^3.15.1"`
