### ISSUE TITLE
Add support for responsive style props

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#770]
# 🙋 Feature Request

Our [style props](https://react-spectrum.adobe.com/react-spectrum/styling.html) are already a nice way to use Spectrum defined variables for things like layout and spacing props, but it would be useful to support responsive behavior as well. For example, you might wish to switch layouts on smaller screens. This would be especially useful for our [layout components](https://react-spectrum.adobe.com/react-spectrum/layout.html).

## 💁 Possible Solution

I think the API could look something like this:

```jsx
<TextField width={{S: 'size-1000', M; 'size-2000', L: 'size-3000'}} />
```

This would set a different width at 3 breakpoints: small (mobile), medium (tablet), and large (desktop). We could have default values for these breakpoints, but also allow applications to define their own values using the `Provider` component.

```jsx
<Provider breakpoints={{S: 380, M: 768, L: 1024}}>
  <TextField width={{S: 'size-1000', M; 'size-2000', L: 'size-3000'}} />
</Provider>
```

This would define each of the breakpoints for the entire app, and all components within the provider could respond to those breakpoints.

## 🧢 Your Company/Team

RSP

**Comment by RafalFilipek** [comment]
https://styled-system.com/ has similar solution, with two small additions:

`_` key to define default value. This is very useful when you have more breakpoints.

```
{ _: 100, L: 300 } // {S: 100, M: 100, L: 300}
{ _: 100, M: 300 } // {S: 100, M: 300, L: 300}
```

and array notation

```
[100, 100, 300]
```

But this one, in my opinion is not very useful.

Here you can find more information: https://styled-system.com/responsive-styles

Do we want similar behavior?

**Comment by devongovett** [comment]
Ah yes that makes sense. I didn't quite understand the syntax at first though. Maybe the underscore could be a name like `default`?

```
{ default: 100, L: 300 }
```

The array syntax is also too cryptic IMO. I feel like the object syntax with named breakpoints is much easier to read.

**Comment by CraigCav** [comment]
Probably best to avoid `default` as [it's a keyword](https://mathiasbynens.be/notes/javascript-identifiers). The design system I created for ezcater uses `base` for the default value (which also has the benefit of being only 4 chars), but something like `initial` could also work. 🤷‍♂️

**Comment by undavide** [comment]
Hi, coming here from [there](https://github.com/adobe/react-spectrum/issues/1373), and upvoted right away. I understand this is still in a feat. request stage, correct? Thanks!

**Comment by snowystinger** [comment]
It's in a stage where anyone can pick it up. There's been a little discussion around what it might look like in this thread, and I expect there will be more once there is a PR up. It's unlikely the core team is going to pick it up in the near future.
