### ISSUE TITLE
Replace :hover CSS pseudo class with useHover hook

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#771]
# 🙋 Feature Request

We need to replace usage of the `:hover` pseudo class with a JS based solution for styling hover effects (the `useHover` hook). `:hover` does not play nice with touch devices. Usually, they show the hover styles on touch, and then remove them when you touch again. We currently have a postcss plugin that wraps these in the `@hover` media query, which is supposed to detect disable the hover styling if it's unsupported. Unfortunately, it's inconsistent at best, especially on hybrid devices that support both mouse and touch (e.g. Surface or iPad with pointer). This is because the media query only detects whether hover is supported, not whether its currently in use. The only way around this it seems is to use JS pointer events to detect the pointer type and apply the hover effect as a css class.

## 🤔 Expected Behavior

Hover effects shouldn't show when interacting with touch.

## 😯 Current Behavior

Hover effects are shown sometimes when interacting with touch, especially on hybrid devices.

## 💁 Possible Solution

1. Create a postcss plugin that replaces `:hover` with a `.hover` class.
2. Add `useHover` to all components that support hover effects, and apply this class when the component is hovered. We could also make a helper component to do this by wrapping around an element, similar to `<FocusRing>`.

## 🧢 Your Company/Team

RSP

**Comment by so99ynoodles** [comment]
Hi, I've just started to work on this issue, I need you to check if I'm doing right. 
I hope you to check my WIP PR #775, and let me know whether I can proceed or not.

> 1. Create a postcss plugin that replaces `:hover` with a .hover class.

I wrote postcss plugin that replaces `:hover` with `is-hovered`, but I'm not familiar with these. It will be very nice if you can give me some advice.

> 2. Add useHover to all components that support hover effects, and apply this class when the component is hovered. We could also make a helper component to do this by wrapping around an element, similar to <FocusRing>.

I fixed useHover a little and added it to Buttons. 
If this looks fine to you, I will add this to all hoverable components.
Thank you.
