### ISSUE TITLE
Use ResizeObserver where available for Breadcrumbs and ButtonGroup

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#773]
# 🙋 Feature Request

In any component that supports collapsing items based on size, we should use `ResizeObserver` instead of window `resize` events if possible. This will make it handle cases where part of the UI changes size without the window changing size (e.g. opening/closing a sidebar). We'll need to document that if you want to support older browsers, you'll need to include a polyfill. By default, we could fall back to window resize events, as the polyfill would only be needed for specific use cases.

## 💁 Possible Solution

Use `ResizeObserver` to handle resize events in Breadcrumbs and ButtonGroup, and whatever other components we add going forward that need this behavior. Perhaps we could create a reusable hook to handle this.

## 🧢 Your Company/Team

RSP

**Comment by Anenth** [comment]
Would love to work on this

**Comment by devongovett** [comment]
Awesome @Anenth! Let us know if you have any questions. 😀
