### ISSUE TITLE
Trays need extra padding on iPhone X

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#782]
# 🐛 Bug Report 

Trays on iPhone X or other iPhones with no home button are partially obscured by the home indicator at the bottom of the screen.

## 🤔 Expected Behavior

There should be some extra padding at the bottom of the tray to account for the home indicator.

## 😯 Current Behavior

The home indicator sometimes overlaps or is too close to the contents of the tray, making it hard to access.

<img width="300" src="https://user-images.githubusercontent.com/19409/87844591-63d63b80-c873-11ea-99c2-03726a364730.png">

## 💁 Possible Solution

We could possibly add some padding using the safe area insets defined in CSS. Not tried this yet though. https://webkit.org/blog/7929/designing-websites-for-iphone-x/

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0.2
| Browser          | Safari
| Operating System | iOS

## 🧢 Your Company/Team

RSP

**Comment by sanskar-p** [comment]
Hi @devongovett
Is it fine if I try my hands on this issue? I'll start by trying `safe-area-inset` as mentioned in the link you suggested.(https://webkit.org/blog/7929/designing-websites-for-iphone-x/)

**Comment by devongovett** [comment]
@sanskar-p that would be awesome! Let us know if you have any questions. 😀

**Comment by sanskar-p** [comment]
@devongovett  extremely sorry to bother you with such a simple issue. But I can't seem to successfully run `yarn install`. I'm using Windows 10.
Here is the error I'm getting.

![image](https://user-images.githubusercontent.com/54014518/87883938-7f367780-ca28-11ea-8ea4-53a8e335580c.png)

**Comment by devongovett** [comment]
@sanskar-p Looks like you need to install the windows dev tools (Visual Studio). See https://github.com/nodejs/node-gyp#on-windows. Let me know if it doesn't work.

**Comment by sanskar-p** [comment]
Hi! Your suggestion fixed the previous error. I had to install MinGW to be able to run `makefile`. But now I'm facing this issue. `pwd` is a Linux command and hence I'm unable to work around this problem.

![image](https://user-images.githubusercontent.com/54014518/87886132-31c20680-ca38-11ea-8de3-18dba114a9f5.png)

**Comment by mischnic** [comment]
You can remove the `&& pwd` part in the `build-icons` here for now:
packages/@spectrum-icons/color/package.json
packages/@spectrum-icons/ui/package.json
packages/@spectrum-icons/workflow/package.json

It's not really needed anyway and just a kind of progress indicator in the terminal

**Comment by snowystinger** [comment]
Yeah, that's an old artifact that we can get rid of

**Comment by sanskar-p** [comment]
I'm still not able to run `yarn install` successfully. Here is the error

![image](https://user-images.githubusercontent.com/54014518/87927640-248d3200-caa1-11ea-8bdd-ec8789a11321.png)

**Comment by mischnic** [comment]
Looks like nobody so far was working on Windows 😄 

Add the package `cross-env` as a dev dependency and prepend it (`cross-env BUILD_ENV=production babel ....`).

**Comment by sanskar-p** [comment]
I was finally able to run the storybook after jumping through many loops. However, now the storybook does not display properly 😢 
![image](https://user-images.githubusercontent.com/54014518/87963295-1d344b80-cad6-11ea-9db1-d1d6bee3ef0a.png)
![image](https://user-images.githubusercontent.com/54014518/87963298-1e657880-cad6-11ea-92ba-92dbfb580539.png)

**Comment by devongovett** [comment]
Did you by chance run `make build` prior to running the storybook? If so, it might be resolving to the built packages instead of the source code. Try running `rm -rf packages/*/*/dist` (or whatever the equivalent windows command is).

**Comment by sanskar-p** [comment]
I don't think I ran `make build`. Anyhow, running `rm -rf packages/*/*/dist` did not make a difference.

**Comment by snowystinger** [comment]
any warnings or errors of note in your terminal?

**Comment by sanskar-p** [comment]
There are some warnings when I run `yarn install` to install the dependencies but none when I run `yarn start`

**Comment by mischnic** [comment]
@sanskar-p I've opened a PR to fix the whole Windows situation (including a change to the webpack config to fix storybook): #805.

**Comment by ronderksen** [comment]
Does this issue still occur? I've looked at the tray on my iPhone, but it seems that the grid layout adds enough space now?
