### ISSUE TITLE
Get everything running on Windows

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#796]
# 🙋 Feature Request

Get all of our commands working on windows. This is probably easiest for someone with a windows machine to do.

## 😯 Current Behavior

Current behavior has some problems, a few are seen in this issue. There are probably some more, check all the other commands.
https://github.com/adobe/react-spectrum/issues/782

**Comment by devongovett** [comment]
This might mean replacing `make`? I don't believe it works out of the box on windows. Maybe with WSL but not sure if we can require that.

**Comment by snowystinger** [comment]
A few of our package scripts don't use `make` anyways, and a few of our `make` targets must be directly invoked, I'm all for being more consistent on that front

**Comment by devongovett** [comment]
A bunch of the npm scripts just call make under the hood though

**Comment by snowystinger** [comment]
yeah, my comment is more about
`yarn install`
`yarn start`
but
`make clean_all`
