### ISSUE TITLE
[@react-stately/collections] Uses 'react' as a "dependency" rather than a "peerDependency"

### ISSUE THREAD

**Issue by Westbrook** [adobe/react-spectrum#799]
# 🐛 Bug Report  
`@react-stately/collections` includes `react` as a "dependency" making it extra difficult to alias React out of a build when attempting to leverage the stately hooks in other contexts.

## 🤔 Expected Behavior
All dependencies on React would be the same so that the `alias` technique could be the same across the board.

## 😯 Current Behavior
The use of "dependency" vs "peerDependency" prevents from above `alias`ing from replace React in the application.

## 🔦 Context
The Spectrum Web Components project is investigating whether it's possible to leverage the stately and aria hooks in their project. https://github.com/adobe/spectrum-web-components/pull/717

## 🧢 Your Company/Team
Adobe Spectrum

**Comment by devongovett** [comment]
Ah, that's an oversight. We should add this to `scripts/lint-packages.js`.
