### ISSUE TITLE
Chromatic stories for the rest

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#812]
# 🙋 Feature Request

- Alert
- Breadcrumbs
- Calendar?
- Datepicker?
- Form
- Icon
- Image
- Label
- Link
- Meter
- Progress
- Table
- Text
- View
- Well

## 💁 Possible Solution

Tabs/Breadcrumbs both rely on measurements that involve font, make sure that the font is already loaded
Tabs might need a delay until screenshot even with the font already loaded

**Comment by LFDanLu** [comment]
covered by https://github.com/adobe/react-spectrum/issues/1957
