### ISSUE TITLE
listbox does not open on Firefox for Android

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#816]
# 🐛 Bug Report 

On Firefox for Android, tapping a Select/Picker won't open the listbox.

## 🤔 Expected Behavior

Tapping the Picker should open the listbox.

## 😯 Current Behavior

The listbox flickers open but immediately closes again. Note that a long-press will actually open the listbox.

## 💻 Code Sample

https://react-spectrum.adobe.com/react-spectrum/Picker.html#example
https://react-spectrum.adobe.com/react-aria/useSelect.html#example

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0.2
| Browser          | Firefox for Android 68.10.1
| Operating System | Android 10

Note that this is *not* an issue on geckoview based browsers (Firefox Focus works, also Firefox Beta for Android)

**Comment by mischnic** [comment]
> Note that this is not an issue on geckoview based browsers (Firefox Focus works, also Firefox Beta for Android)

I've just tested this on stable, beta, nightly & Focus and they all behave the same for me (closes immediately again). Android 7

**Comment by stefanprobst** [comment]
i checked again, and it looks like this is indeed half-broken for Beta/Focus:

|   | Picker (https://react-spectrum.adobe.com/react-spectrum/Picker.html#example) |
|---|---|
| stable | broken |
| beta   | broken |
| focus  | broken |

|   | useSelect example (https://react-spectrum.adobe.com/react-aria/useSelect.html#example) |
|---|---|
| stable | broken |
| beta   | ok |
| focus  | ok |

**Comment by mischnic** [comment]
My findings for the Picker:

Firefox Android short press:
```
isOpen false Picker.tsx:132
console.trace() setOpen true useOverlayTriggerState.ts:35
    setOpen useOverlayTriggerState.ts:35
    toggle useOverlayTriggerState.ts:48
    toggle useMenuTriggerState.ts:39
    toggle useSelectState.ts:57
    onPress useMenuTrigger.ts:78
    triggerPressEnd usePress.ts:170
    onPointerUp usePress.ts:364
    (Async: EventListener.handleEvent)
    addGlobalListener usePress.ts:113
    onPointerDown usePress.ts:313
isOpen true 2 Picker.tsx:132
console.trace() setOpen false useOverlayTriggerState.ts:35
    setOpen useOverlayTriggerState.ts:35
    close useOverlayTriggerState.ts:45
    onBlurWithin useOverlay.ts:83
    onBlur useFocusWithin.ts:68
isOpen false Picker.tsx:132
```

Firefox Android long press/Chrome Android:
```
isOpen false Picker.tsx:132
console.trace() setOpen true useOverlayTriggerState.ts:35
    setOpen useOverlayTriggerState.ts:35
    toggle useOverlayTriggerState.ts:48
    toggle useMenuTriggerState.ts:39
    toggle useSelectState.ts:57
    onPress useMenuTrigger.ts:78
    triggerPressEnd usePress.ts:170
    onPointerUp usePress.ts:364
    (Async: EventListener.handleEvent)
    addGlobalListener usePress.ts:113
    onPointerDown usePress.ts:313
isOpen true 2 Picker.tsx:132
```

So apparently Firefox fires `onBlur` in this specific situation and that causes the overlay to immediately close again.

**Comment by stefanprobst** [comment]
just tested the `Picker` example again with Firefox for Android 82 (now that Beta has become the official FF) and this is unfortunately still an issue.

**Comment by PacoSoftwerft** [comment]
Bug still exits, see #2098
Closed the issue as it was a duplicate

**Comment by LFDanLu** [comment]
Should be fixed by https://github.com/adobe/react-spectrum/pull/2175
