### ISSUE TITLE
Dialog example takes 5s or longer to appear on Chrome Android

### ISSUE THREAD

**Issue by robcaldecottvelo** [adobe/react-spectrum#817]
# 🐛 Bug Report 

The Dialog example takes 5s or more to appear on Chrome Android.

## 🤔 Expected Behavior

The dialog should appear immediately.

## 💻 Code Sample

Navigate to https://react-spectrum.adobe.com/react-spectrum/Dialog.html using Chrome on Android and click the **Check connectivity** button.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0.2 |
| Browser          | Chrome 84.0.4147.89 |
| Operating System | Android 10 |

**Comment by mischnic** [comment]
It's instantaneous for me with the same Chrome version and Android 7

**Comment by robcaldecottvelo** [comment]
It is truly bizarre. I have a Google Pixel 3a XL running the latest Android 10 security patch. Booting in safe mode shows the same issue. While waiting for the dialog to open the page hangs: perhaps the transition effect is causing this. I installed Firefox and this works correctly. Odd. I'll knock a codesandbox together and see if I can shed any more light.

**Comment by robcaldecottvelo** [comment]
I knocked up a stand-alone example in codesandbox and it works as expected.
