### ISSUE TITLE
Clicking on the label should focus select/picker

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#839]
# 🙋 Feature Request

When clicking on the label for the Picker component, or the useSelect hook, focus should be placed on the dropdown trigger similar to a native `<label>` + `<select>`. We cannot use a real `<label>` for this because the trigger is a `<button>` element, so clicking the label would cause an `onClick` event to be fired on the button and open the menu. This would not match native behavior of simply focusing the select rather than opening it.

## 🤔 Expected Behavior

Clicking on the label should focus the select trigger.

## 😯 Current Behavior

Clicking the label does nothing.

## 💁 Possible Solution

Add `usePress` listeners to the label element and return event handlers as part of `labelProps` in `useSelect`, and call `focus()` on the ref to move focus to the trigger button.

## 🧢 Your Company/Team

RSP

**Comment by gavinhenderson** [comment]
Happy to pick this up 😃
