### ISSUE TITLE
Add Accordion component

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#848]
# 🙋 Feature Request

React Spectrum and React Aria should support an [accordion](https://w3c.github.io/aria-practices/#accordion) component. Accordions can be used to group content into collapsible sections.

## 💁 Possible Solution

The API should follow the [collection components](https://react-spectrum.adobe.com/react-stately/collections.html) API, using `<Item>` to specify each item. In addition, it follows the same API for exandable items used by other components like Tree.

```tsx
import {CollectionBase, Expandable} from '@react-types/shared';
import {AriaButtonProps} from '@react-types/button';

interface AccordionProps<T> extends CollectionBase<T>, Expandable {}

interface AccordionAria {
  /** Props for the accordion container element. */
  accordionProps: HTMLAttributes<HTMLElement>
}

declare function useAccordion<T>(props: AccordionProps<T>, state: TreeState<T>): AccordionAria

interface AccordionItemAriaProps<T> {
  item: Node<T>
}

interface AccordionItemAria {
  /** Props for the accordion item button. */
  buttonProps: AriaButtonProps,
  /** Props for the accordion item content element. */
  regionProps: HTMLAttributes<HTMLElement>
}

declare function useAccordionItem(props: AccordionItemAriaProps<T>, state: TreeState<T>): AccordionItemAria;
```

There are also some Spectrum-specific props that we'll be adding. Need to discuss with design first.

Here's an example of the API in action:

```tsx
import {Item} from '@react-stately/collections';

<Accordion expandedKeys={["files"]}>
  <Item key="files" title="Your files">
    <Files />
  </Item>
  <Item key="shared" title="Shared with you">
    <Shared />
  </Item>
</Accordion>
```

This should follow the ARIA [accordion pattern](https://w3c.github.io/aria-practices/#accordion). See the [example](https://w3c.github.io/aria-practices/examples/accordion/accordion.html), which describes the expected DOM structure and ARIA properties. Much of the keyboard behavior should already be handled by our selection/focus management hooks.

In terms of implementation, there are a few pieces:

* For state, we can use the [useTreeState](https://react-spectrum.adobe.com/react-stately/useTreeState.html) hook. This will handle converting children from `<Item>` elements to a [Collection](https://react-spectrum.adobe.com/react-stately/Collection.html) object, along with setting up state to handle focus and expanding/collapsing items. Since accordions don't allow selection, the `selectionMode` option should always be set to `"none"`. I don't think any other state will be needed for accordion, but if so we could set up a `useAccordionState` hook that wraps `useTreeState`.
* The `useAccordion` hook should be created to manage the list of accordion items. It should use the `useSelectableList` hook to manage focus and keyboard interactions (e.g. arrow keys). We may need to add an option to tell it to not handle the Tab key, since all items should be tabbable unlike other collections. It should return these props as `accordionProps` which will be placed on the top-level wrapper element for the accordion.
* The `useAccordionItem` hook should be created to manage an individual accordion item. The hook should receive a [Node](https://react-spectrum.adobe.com/react-stately/Collection.html#node-interface) object from the collection, and use the title and rendered properties for the accordion header and contents respectively. It should return props for the button element that will be used to toggle the accordion item, including an `onPress` handler that calls `state.toggleKey()`. It should also call the `useSelectableItem` hook, and add those props to the button as well. However, since accordions allow all items to be tabbable, the `tabIndex` prop should be overridden to `0`. Finally, props for the region element containing the contents should be returned, linking it with the button via an id.

The selection hooks *may* be overkill for this actually, but we can try it out and see how much we need to override.

## 🧢 Your Company/Team

RSP

**Comment by razvanip** [comment]
is this free to grab ? i can take it

**Comment by so99ynoodles** [comment]
Since nobody is working on it (I think), I'll take it.
