### ISSUE TITLE
The utils uses the classnames node module which is not an ES module

### ISSUE THREAD

**Issue by cedeber** [adobe/react-spectrum#849]
# 🐛 Bug Report 

Hello,
I am current using vitejs which only work with ES modules (because 2020) and react-spectrum/utils does use `classnames` which is not available as ESM. In this case, default export simply doesn't work and crash the app.

## 🤔 Expected Behavior

I am waiting that React spectrum is 100% compatible with ESM.

## 😯 Current Behavior

default import of classnames not found.

## 💁 Possible Solution

Honestly, classnames can be rewritten in few lines of code: https://github.com/cedeber/frontafino/blob/master/utilities/src/classnames.ts

A pull request also already exist for `classnames` but nothing happened for a year.
https://github.com/JedWatson/classnames/pull/194

Could you please replace `classnames` by a modern and easy solution?

Thanks a lot.

**Comment by devongovett** [comment]
We could look at https://github.com/lukeed/clsx maybe?

**Comment by cedeber** [comment]
Thanks for the proposition. Looks good to me. Do I do a PR?

**Comment by snowystinger** [comment]
that'd be fantastic if you don't mind :)

**Comment by cedeber** [comment]
Lots of work, but let's give it a try 👍

**Comment by devongovett** [comment]
Luckily I think there are very few places where we import the classnames module directly. Mostly we use our wrapper in `@react-spectrum/utils`. Thanks for looking into it!

**Comment by cedeber** [comment]
I found some places like `packages/dev/docs`, `.storybook` and `.chromatic` where classnames is also used. Is it ok to do the changes here too? (I already did, but not commited yet)

Any reasons why `aria/focus`, `aria/visually-hidden`, `spectrum/layout` and `spectrum/provider` don't use the `utils`?

**Comment by devongovett** [comment]
> I found some places like packages/dev/docs, .storybook and .chromatic where classnames is also used. Is it ok to do the changes here too?

Yep!

> Any reasons why aria/focus, aria/visually-hidden, spectrum/layout and spectrum/provider don't use the utils?

The util is mostly there to handle mapping the classes to CSS modules names. So when the classes are provided directly and not through a CSS module, we usually use the underlying classnames library directly.

**Comment by cedeber** [comment]
Pull request submitted 😁 https://github.com/adobe/react-spectrum/pull/859
