### ISSUE TITLE
ListBox typeahead shouldn't select the focused item when pressing space

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#851]
# 🐛 Bug Report 

Listbox supports typing to search for items in the list. A problem arises however when a user searches for an item with a space in its name (e.g. "Item 10") since hitting the space key will select the currently focused item. 

## 🤔 Expected Behavior

When the user is typing to search through items in the listbox, hitting space shouldn't select the focused item. Instead, typeahead should continue to work as expected and focus should be moved to the first item that matches what the user has typed.

## 😯 Current Behavior

As mentioned above, hitting space selects the currently focused item, which is a problem if the user attempts to type to search for a item with a space in its name.

If you build storybook locally, this story is a good place to reproduce: http://localhost:9003/?path=/story/listbox--listbox-w-many-sections-and-selection.

## 💁 Possible Solution

Possibly add a timeout that prevents space from selecting the focused item while the user types in the ListBox. Stopping propagating in useTypeSelect + changing it to be a capturing listener might be sufficient.

code for typeahead: https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/selection/src/useTypeSelect.ts

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  3.1.0
| Browser          |    All
| Operating System |  All

## 🧢 Your Company/Team

RSP

**Comment by solimant** [comment]
Working on it.
