### ISSUE TITLE
Click events don't work on MacOS in Adobe CEP extension unless debugger is attached

### ISSUE THREAD

**Issue by BrianHanechak** [adobe/react-spectrum#854]
# 🐛 Bug Report 

We are using the react-specturm in an Adobe CEP extension. On Windows, it works as expected. On MacOS, none of the controls are responsive. If we attach a chrome debugger to MacOS, the controls become responsive.

## 🤔 Expected Behavior

We would expect the controls to be responsive on both Windows and MacOS regardless of whether or not the debugger is attached.

## 😯 Current Behavior

The controls are not responsive. Button controls never have "onPress" event processed. For Picker controls, the popup for selecting an item never appears.

## 🔦 Context

This will make it impossible for us to let MacOS users use our application.

## 💻 Code Sample

```
      <Picker
        aria-label="Select Product"
        items={productList}
        onSelectionChange={(product) => setProduct(product as string)}
        selectedKey={product}
        marginBottom="size-50"
      >
        {(productLabel) => <Item key={productLabel.value}>{productLabel.label}</Item>}
      </Picker>
      <Button id="create-blank" variant="secondary" onPress={createBlankUi}>
        Create Blank
      </Button>
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.1.0
| Browser          | Embedded browser in Adobe Creative Suite 2020 (Illustrator and InDesign)
| Operating System | MacOS Catana (10.15.6)

**Comment by LFDanLu** [comment]
Hey, thanks for filing this issue. Do you have any debug logs, a sample environment that I could play in, or maybe a repo link? Do other clickable components also fail in a similar way?

**Comment by BrianHanechak** [comment]
I don't have anything to share right now. What we've seen is that buttons don't click and dropdowns don't open. I will try to make a small example CEP extension to reproduce this, and share it here.

**Comment by BrianHanechak** [comment]
[sample-app.zip](https://github.com/adobe/react-spectrum/files/5004564/sample-app.zip)

Here's a sample app I made to reproduce this. It has a regular react button, and a button from spectrum-react. On Windows, both buttons work. On MacOS, the spectrum button doesn't work, unless you attach a chrome debugger, then it does work.

**Comment by LFDanLu** [comment]
@BrianHanechak Hrmm, I'm having trouble getting the that sample extension to show up in Illustrator after following the instructions in the README (got the dist setup and added to the extensions folder, maybe running into an unsigned extension issue?). Maybe you could give me some pointers here or direct me to some other steps? 
![image](https://user-images.githubusercontent.com/9661127/89078888-16110700-d33a-11ea-8aa3-f40e78baec79.png)

**Comment by BrianHanechak** [comment]
It's called "Sample Panel", so it seems to be showing up in your menu item there.

**Comment by BrianHanechak** [comment]
If that's not the correct one, there are instructions for setting up running unsigned exceptions in the CEP Cookbook, located here: https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_9.x/Documentation/CEP%209.0%20HTML%20Extension%20Cookbook.md

Search for "unsigned". Note that there are some special notes specific to MacOS 10.9 or higher.

**Comment by LFDanLu** [comment]
Ah my mistake, I was looking for `Cimpress Template Maker` mentioned in the readme heh. I presume it isn't supposed to look like this right?
![image](https://user-images.githubusercontent.com/9661127/89079888-54a7c100-d33c-11ea-8017-1fe7c9c16253.png)

The spectrum button in the app is missing :/, I'll see about debugging

**Comment by LFDanLu** [comment]
thanks for the cep link, lemme dig through that

**Comment by BrianHanechak** [comment]
Ah, you do have it up.  In terms of making it appear, try setting your theme to light instead of dark... I didn't put anything in to set the theme appropriately, and I think the button might just be dark on dark.

Here's what it looks like on Windows for me:
![image](https://user-images.githubusercontent.com/10569566/89080148-0ef7f200-d356-11ea-9ef3-2df37bfe73c5.png)

**Comment by BrianHanechak** [comment]
Again, the strangest thing about this is... clicks work in Windows all the time. In MacOS, they work once you've attached the debugger, but they don't work if not.

**Comment by LFDanLu** [comment]
@BrianHanechak Yep, I was able to reproduce the click not working on mac, will need to dig into this.

**Comment by tyang-cimpress** [comment]
@LFDanLu It seems that the reason why attaching the chrome debugger helps is because of screencast. If I toggle screencast off then even with the debugger attached the spectrum button is not responsive.

**Comment by tyang-cimpress** [comment]
@LFDanLu any ideas on when this issue might be addressed?

**Comment by LFDanLu** [comment]
@tyang-cimpress Hey, thanks for the additional info and apologies for the slow response, I've been pretty busy with the upcoming release and ComboBox work. I hope to be able to dive back into issue soon.

**Comment by vonstring** [comment]
It appears pointer events don't fire in CEP extensions on Mac for some reason. I was able to dirtily work around this in my extension by just deleting window.PointerEvent on Mac so that they are assumed to be unsupported.

**Comment by LFDanLu** [comment]
Yep, can confirm your findings  @vonstring, thanks for digging. Since `typeof PointerEvent` is not undefined in the embedded browser, `usePress` chooses to use pointer events handlers rather than `onMouseDown`/`onMouseUp`/etc (see https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/interactions/src/usePress.ts#L293). 

@tyang-cimpress @BrianHanechak This feels like a Adobe CEP issue, would be good to raise this with them. In the meantime, does the workaround @vonstring noted work for you?

**Comment by tyang-cimpress** [comment]
Yes. We have confirmed that deleting window.PointerEvent does work around the issue

**Comment by vonstring** [comment]
Yes, apart from it feeling a bit icky, I haven't noticed any side effects from the workaround yet. 🤞

**Comment by LFDanLu** [comment]
I've filed a ticket against CEP internally. Since this has a workaround, I'll be closing this issue for now, feel free to reopen if need be. Thanks once again for reporting!

**Comment by lsh246** [comment]
Thanks everyone for figuring this out - wish I'd found this bug report hours ago! @LFDanLu could you post a comment here when the CEP bug is fixed and released, so we know when to remove the workaround?

**Comment by LFDanLu** [comment]
@lsh246 Sure, I'll set a reminder for myself!

**Comment by justadaniel** [comment]
Hello, any updates on this?

**Comment by LFDanLu** [comment]
Unfortunately, no. The internal ticket filed against the CEP team hasn't had any traction, will keep bumping it

**Comment by marbilher** [comment]
I think I hit this issue when using the  https://github.com/pmndrs/use-gesture  library to develop my adobe extension. Drag and drop functionality works everywhere except in the adobe cep html engine while on a mac. The owner of the use-gesture library suggested the issue might be with the adobe cep html engine not supporting pointer events.

**Comment by realningzheng** [comment]
For those who are unfamiliar with html, here is how to delete window.PointerEvent: Simply add the snippet before closing the html.

`<script>
  if (window.PointerEvent) {
    delete window.PointerEvent;
  }
</script>`

**Comment by Ligerx** [comment]
I’m using bolt-cep to start a CEP project in after effects. However, the above workaround does not work for me. I’ve been trying to debug for a while but can’t figure anything else out.

bolt-cep 1.3.0
react-spectrum 3.42.0

**Comment by Boelensman1** [comment]
I'm having the same issue as @Ligerx. The work around doesn't seem to change anything.

**Comment by lucaas** [comment]
The workaround with deleting `window.PointerEvent` does no longer work, because the react-aria interaction hooks (usePress, useHover, etc…) no longer support the mouse event fallback for missing pointer events. The code is still there, but it is only active in test (NODE_ENV === 'test').

To work around the issue, I delete window.PointerEvent and patch the react-aria hooks to remove the `process.env.NODE_ENV === 'test'` checks, which resolves the issue but is brittle as it depends on the continued existence of those test-only paths in react-aria.
