### ISSUE TITLE
[VisuallyHidden] Element imports CSS into JS, can this be handled in anothe way.

### ISSUE THREAD

**Issue by Westbrook** [adobe/react-spectrum#861]
# ❔ Question 
When working with `<VisuallyHidden/>` the currently vended copy relies on importing CSS into JS:
```
import "./main.css";
```
My project doesn't use CSS Modules and I'd like not to add additional complexity to my build tools. Is there an alternative to this techniques that could be used and support a broader number of project contexts?

The CSS is pretty small, might even fit into a Tweet `._u-react-spectrum-screenReaderOnly_3e916{border:0;clip:rect(0 0 0 0);-webkit-clip-path:inset(50%);clip-path:inset(50%);height:1px;margin:0 -1px -1px 0;overflow:hidden;padding:0;position:absolute;width:1px;white-space:nowrap}._u-react-spectrum-screenReaderOnly_3e916._is-focusable_3e916:active,._u-react-spectrum-screenReaderOnly_3e916._is-focusable_3e916:focus{clip:auto;-webkit-clip-path:none;clip-path:none;height:auto;margin:inherit;overflow:visible;position:static;width:auto;white-space:inherit}`, hopefully there are alternative approaches to including it.

## 🔦 Context
Attempting to use aria hooks in a low/no build environment. 

## 🧢 Your Company/Team
Adobe Spectrum

**Comment by devongovett** [comment]
I guess we could probably use inline styles... not sure if there's any perf impact to that vs classes. Or maybe inject a style tag, but that seems less ideal as well.

**Comment by Westbrook** [comment]
If this is something that was low occurrence (I've been only looking at a small subset of the API surface), I could see patch-packaging it out of the files so that I could choose how I wanted to include that CSS in my project. Not sure whether it creates trouble to manage two exports, one with CSS imported and one with documentation as to where to find the CSS files?

**Comment by devongovett** [comment]
Eh yeah, but we should solve this. Others might want to use React Aria in environments that don't support CSS imports too.

**Comment by devongovett** [comment]
Made an attempt here. Less optimal than I'd hoped due to the focus styles, which can't be reproduced with an inline style. So we need some JS to handle it. Looked at injecting a style tag at runtime, but this won't work for server side rendering. If anyone has other ideas, please let me know. https://github.com/adobe/react-spectrum/pull/911

**Comment by horacioh** [comment]
maybe this is related to this error. I made a codesandbox where is not possible to use `visually-hidden` or any package that uses it (like `overlays`) because of it: https://codesandbox.io/s/nextjs-react-aria-css-error-r33kz

any help I can do on testing or feedback let me know!
