### ISSUE TITLE
Checkbox doesn't remove `user-select: none;` style from body

### ISSUE THREAD

**Issue by mischnic** [adobe/react-spectrum#862]
# 🐛 Bug Report 

When quickly and repeatedly toggling a checkbox and then moving the cursor away from the component before letting go, sometimes `user-select: none;` on the HTML element isn't removed.

## 🤔 Expected Behavior

That style is always removed.

## 😯 Current Behavior

![Kapture 2020-07-29 at 18 03 46](https://user-images.githubusercontent.com/4586894/88824163-46379900-d1c6-11ea-8b69-bd14692f16f0.gif)

## 💁 Possible Solution

A race condition?

## 💻 Code Sample

https://react-spectrum.adobe.com/react-spectrum/Checkbox.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.1.0
| Browser          |   Chrome 84
| Operating System | macOS 10.15

**Comment by snowystinger** [comment]
I do not see that user-select at all? Can you explain more?

**Comment by snowystinger** [comment]
Ah, yep, i can do it. Just gotta look at the <html element :)

**Comment by zidian257** [comment]
I'd like to give this a try

**Comment by snowystinger** [comment]
thanks! i think this may be related https://github.com/adobe/react-spectrum/pull/893

**Comment by zidian257** [comment]
Thanks! I already made a pr for this using the lates main branch
