### ISSUE TITLE
Extract useResizeObserver hook into reusable util

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#863]
# 🙋 Feature Request

As of #793 we have a nice `useResizeObserver` hook that is used in breadcrumbs to handle setting up a `ResizeObserver` where available with a basic fallback to window resize events. It would be great to move this hook into `@react-spectrum/utils` so we can reuse it in other components, e.g. ButtonGroup and eventually ActionGroup and Tabs.

## 🧢 Your Company/Team

RSP

**Comment by McZenith** [comment]
Hi! Is this issue still available? I'm interested... Thanks

**Comment by devongovett** [comment]
Yep! Go for it. :smile:

**Comment by McZenith** [comment]
Thanks... I'm excited...
