### ISSUE TITLE
`value` attribute not supported/ignored in AriaButtonProps/useButton for elementType=input

### ISSUE THREAD

**Issue by shrugs** [adobe/react-spectrum#881]
# 🐛 Bug Report 

Much like #833, the `AriaButtonProps` types and `useButton` hooks don't support or pass-through the (usually) necessary `value` attribute when using a button component as an input (for form submissions).  [`useButton` is intended to also work as a submit button](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/button/src/useButton.ts#L55), which, when rendered as an `input`, is not allowed to have children and instead labels itself with the `value` attribute. Attempting to pass a child results in:

```
input is a void element tag and must not have `children` or use `props.dangerouslySetInnerHTML`. Check the render method of Component
```

## 🤔 Expected Behavior

The types and hook implementation for button components should support a `value` prop when `elementType="input"`.

```tsx
<Button elementType="input" value="Save & Continue" {...otherProps} />
```

## 😯 Current Behavior

- `AriaButtonProps` does not support the attribute `value?: string`
- `useButton` does not forward this property when `elementType="input"` as it does for `type` and `disabled`

## Workaround

Simply add `value?: string` to your button component's types, and add `{ value: props.elementType === 'input' ? props.value : undefined }` to your rendered element

**Comment by devongovett** [comment]
Hmm, why would you use an `input` element over a standard `button`? Not quite sure why the existing code you linked to is there tbh. That codepath was mainly meant for links or other elements like divs. What's your reason for using an input rather than a button or other element type?

**Comment by shrugs** [comment]
ah, TIL that `<button type="submit" />` and `<input type="submit" />` are functionally interchangeable. I had thought there was an a11y or default-browser-behavior reason for doing one over the other, but it looks like `<button type="submit" />` is just an upgrade across the board in terms of how we can render the element.

I also didn't read the useButton code correctly, my bad 😅 

ref: https://stackoverflow.com/a/7117660
