### ISSUE TITLE
Fullscreen Dialogs/AlertDialogs show isDismissable & variant icons in bottom right corner

### ISSUE THREAD

**Issue by dkario** [adobe/react-spectrum#882]
# 🐛 Bug Report 

Inside a `<DialogTrigger type="fullscreen">`, a `Dialog` with `isDismissable` or an `AlertDialog` with any variant that adds an icon to the header is rendered with the close "X" button or the icon in the bottom right corner. 

## 🤔 Expected Behavior

The close button and these icons should be hidden with CSS or not rendered. Maybe a JS warning can let users know these patterns aren't supported.

## 😯 Current Behavior

The button/icon renders in the bottom right corner of the dialog.
<img width="1473" alt="Screen Shot 2020-08-03 at 12 57 27 PM" src="https://user-images.githubusercontent.com/2606744/89224253-fe7d8c80-d58c-11ea-86db-67e98ca50682.png">

## 💁 Possible Solution

See "expected behavior".

## 🔦 Context

I have a dialog that has large, complex content which is also has dismissible. `AlertDialog` seemed like the right component to use but I found that it doesn't support different sizes to support this large content.

## 💻 Code Sample

```
<DialogTrigger type="fullscreen">
    <ActionButton>Press me</ActionButton>
    <AlertDialog variant="warning" title="Warning" primaryActionLabel="Confirm">
        Test
    </AlertDialog>
</DialogTrigger>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | v3
| Browser          | Chrome v84
| Operating System | Mac OSX 10.14.6

## 🧢 Your Company/Team

Adobe Experience Platform

**Comment by devongovett** [comment]
I think you need to use a `Dialog` here, not an `AlertDialog`. AlertDialog does not have a fullscreen variant. Also fullscreen dialogs don't support `isDismissible`. You need to put a button group in the dialog with a button to close it.

**Comment by dkario** [comment]
Thanks @devongovett, I'm now using a `Dialog` instead. I raised this issue just to let you know that some weird CSS appears that we could prevent.

**Comment by dannify** [comment]
I guess we might be able to target the icons to hide them. We should probably add to the docs that these cases are not supported too.

**Comment by dkario** [comment]
Putting that in the docs would have been most helpful for me, I was looking for exactly that.
