### ISSUE TITLE
Where is the `Side Navigation` component?

### ISSUE THREAD

**Issue by djyde** [adobe/react-spectrum#883]
I saw most adobe document using Side Navigation https://spectrum.adobe.com/page/side-navigation/ . But react-spectrum didn't provide a Side Navigation component. 🤔

**Comment by LFDanLu** [comment]
Hi @djyde, our team is continuously working on releasing new components to achieve 1 to 1 parity with the components listed in https://spectrum.adobe.com/ (like Side Navigation). If you are interested, you can help us out by picking up one of the [good first issues](https://github.com/adobe/react-spectrum/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)!

**Comment by gar1t** [comment]
This was closed nearly five years ago - has it been implemented? It's in the web component library. It's trivial to implement. And the React implementation active discourages devs by renaming `className` as `UNSAFE`. If you're going to insist on controlling this framework, why not complete it?
