### ISSUE TITLE
ListBox behaves badly if maxSize is a relative value or exceeds the available size provided by the outer container

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#888]
# 🐛 Bug Report 

If one wants a ListBox to span the complete height inside a size-constrainted flex-container this makes the ListBox freakout completely: 
- jumping back to top (if no size is provided)
- jump up a certain amount (if maxSize is larger than the outer container provides)
- show only some items (if maxSize is 100%). 

I prepared a reproducer at https://github.com/BestSolution-at/react-spectrum-playground/blob/listbox-relative-size-bug/src/App.tsx.

A temporary work around hack is to use a ResizeObserver and adjust the maxSize to match exactly the size from the outside container.

## 🤔 Expected Behavior

The ListBox works no matter what is specified as the max-size

## 😯 Current Behavior

ListBox is not not useable

## 🔦 Context

I tried to implement a master-detail layout with a list on the left and the detail on the right

## 💻 Code Sample

https://github.com/BestSolution-at/react-spectrum-playground/tree/listbox-relative-size-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.1.0
| Browser          | Chrome 84.0.4147.105
| Operating System | OS-X

**Comment by snowystinger** [comment]
Thanks for submitting this and making a demo! Unfortunately, I cannot run your demo though, `error An unexpected error occurred: "http://nexus.ci.bestsolution.at:8081/repository/npm-all/@adobe/react-spectrum/-/react-spectrum-3.1.0.tgz: getaddrinfo ENOTFOUND nexus.ci.bestsolution.at"`
I was able to run it by copying it into our storybook though, where I tried adding a key to all the items, `<Item key={idx}>`, this seems to have resolved the issues.
We do recommend a slightly different way of writing this though, see https://react-spectrum.adobe.com/react-stately/collections.html#why-not-array-map
Here's a gist of it written that way https://gist.github.com/snowystinger/4715984b7598ed0c48e7e2873121d389

Please let me know if this fixes your issue

**Comment by tomsontom** [comment]
on the error: oh sorry that because I use a local proxy - i guess removing yarn.lock and do a "yarn install" would fix it

on the gist: for me nothing changed if i use your code - things are still broken - could it be a something that is already fixed in current main-branch (I guess you ran it there?) - I have the your repo forked so if you could provide a gist to the storybook-code I could give it a go myself

on the collections-link: thanks I knew I came across that already but good you pointed me once more towards it

**Comment by tomsontom** [comment]
alternatively: Are the main-line (nightly) builds available?

**Comment by snowystinger** [comment]
We don't have nightly builds yet unfortunately, we're working on that and hope to have it soon.

As for the gist, are you unable to see the one I posted? I just stuck that in listbox/stories/ListBox.stories.tsx

**Comment by tomsontom** [comment]
so i changed that storybook to - https://gist.github.com/tomsontom/8e850a1f7197494a33770e255e4aa9d3 but I can still simply reproduce the wrong behavior. I recorded a video - https://youtu.be/XMMwlRZUPTw to make sure you see what I see!

**Comment by snowystinger** [comment]
Ok I can see these issues as well, I'm chatting with our team about it, both to see if they have ideas and to see our priority for it. Feel free to also take a go though if you need it resolved quickly. I've updated the gist to remove distractions and do a bit of cleanup.

**Comment by tomsontom** [comment]
Wow that was very fast! Is there a way for me to create a local build (it's not documented in the https://react-spectrum.adobe.com/contribute.html) how one would do a build to try out.

**Comment by dannify** [comment]
Yep we run storybook locally to develop and test. There is a developing section in the contributing guide.
https://react-spectrum.adobe.com/contribute.html#developing 
You can use a fork or just pull from main and run locally.

**Comment by tomsontom** [comment]
well I run the story book stuff but I was interested in using the fix in my real world application to see if it is fixed there too or just the narrow reproducer I came up with

**Comment by devongovett** [comment]
We're planning a release early next week. Also working on nightly releases so this will be faster soon. In the meantime, the best way is to run `make build` in the local repo and publish to a local npm e.g. [verdaccio](https://github.com/verdaccio/verdaccio). You can run `yarn lerna publish --registry http://localhost:4875` (or whatever your local verdaccio port is). Then use that registry to install in your application.
