### ISSUE TITLE
usePreventScroll should be controllable

### ISSUE THREAD

**Issue by jescowuester** [adobe/react-spectrum#889]
# 🙋 Feature Request

When a Modal or similar element has an entry/exit animation the body should be scrollable even while the modal is transitioning out. 

## 🤔 Expected Behavior

It should be possible to lock/unlock the body conditionally.

## 😯 Current Behavior

currently, there is no way to control usePreventScroll outside of rendering.

## 💁 Possible Solution

I propose to add an optional argument to usePreventScroll so that the behavior can be controlled outside of rendering:

```ts
usePreventScroll(isLocked?: boolean)
```

here is a possible, backwards-compatible implementation:

```ts
function usePreventScroll(isLocked?: boolean) {
  useEffect(() => {
    let { paddingRight, overflow } = document.body.style;

    if (isLocked !== false) {
      document.body.style.paddingRight = `${window.innerWidth - document.documentElement.clientWidth}px`;
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = overflow;
      document.body.style.paddingRight = paddingRight;
    }

    return () => {
      document.body.style.overflow = overflow;
      document.body.style.paddingRight = paddingRight;
    };
  }, [isLocked]);
}
```

## 🔦 Context

I have a modal with a 0.2-second exit transition. While the modal is exiting a large part of the content is visible but not scrollable. 

## 💻 Examples

In an application this could be used like this:

```
const [isOpen, setIsOpen] = useState(false)

// immediately lock/unlock body when isOpen is changed
usePreventScroll(isOpen)

return ...
``` 

## 🧢 Your Company/Team

-

**Comment by devongovett** [comment]
Makes sense to me. I think the API should accept an options object rather than a single boolean in case we need to add additional options in the future. The object could be optional: if not passed, it would behave as it does today (as if `isOpen` is always `true`), but if passed, then `isOpen` would need to be set to either true or false.

```jsx
interface PreventScrollOptions {
  isOpen?: boolean
}

function usePreventScroll(options?: PreventScrollOptions = {isOpen: true}) {
  // ...
}
```

**Comment by McZenith** [comment]
Can I work on this?

**Comment by devongovett** [comment]
Go for it @McZenith!

**Comment by McZenith** [comment]
Great... Thanks once again🎈
