### ISSUE TITLE
Customize what triggers `onClose()` in `useOverlay` 

### ISSUE THREAD

**Issue by chungwu** [adobe/react-spectrum#892]
# 🙋 Feature Request

Would like to better control when an overlay is dismissed via `useOverlay` by getting access to the event that caused the dismissal.

Right now, `useOverlay` calls `onClose()` whenever `onInteractOutside()` is called by `useInteractOutside`.  `useInteractOutside` calls `onInteractOutside()` whenever there's a click-like event on an element that's not contained by the argument ref (presumably, the ref of the overlay root).

I would like some way of better controlling this behavior to exclude interactions with known DOM elements from triggering the dismissal.  

## 🤔 Expected Behavior

With access to the event, I can make more nuanced decision on whether I really should dismiss an overlay. 

## 😯 Current Behavior

`onClose()` always called after click-like event on any element outside of the overlay root.

## 💁 Possible Solution

A few ideas:

* Let `onClose()` take in a `SyntheticEvent` argument; `onInteractOutside()` already takes one in as an argument, and it just has to pass it onto `onClose`.  Then, in my `onClose` handler, I can decide whether to really close or not by interpreting the event target.

* Allow passing in a custom `isValidEvent()` as a prop to `useInteractOutside` and `useOverlay`.

## 🔦 Context

In an overlay, I may have menus or popovers that are appended to, say, document.body instead of the root of the popover. I do not want clicking on those popovers to dismiss the overlay.

## 🧢 Your Company/Team

Plasmic

**Comment by devongovett** [comment]
Makes sense. I presume you are trying to prevent clicking on the trigger from closing and re-opening the popup? I believe @snowystinger was also having this issue recently I think we were thinking about possibly adding an option to pass a ref to a trigger element and have that ignore closing the overlay. Would that be sufficient for your use cases?

**Comment by chungwu** [comment]
Actually, my use case is that I have other overlays (menus, popovers) on top of my `useOverlay` dialog box, and I don't want interacting with my menus / popovers to dismiss my dialog box...  So I'd want to be able to ignore more than just the trigger element...

**Comment by devongovett** [comment]
Ah, hmm. That should be handled here. Only the top-most overlay should close, but I guess that's not happening? https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/overlays/src/useOverlay.ts#L64

**Comment by chungwu** [comment]
Ah sorry for the confusion; these other overlays are not managed by react-aria . So, say, I have a dialog box managed by react-aria, and in that dialog box, I have dropdowns that are _not_ managed by react-aria. I want to exclude interaction with those non-react-aria drop downs from dismissing the aria-managed dialog box, by basically checking the `event.target` in `onClose`. Right now I'm instead dropping down to `useInteractionOutside`, because its callback passes me the triggering event, whereas `onClose` in `useOverlay` does not.

**Comment by devongovett** [comment]
Got it, that makes sense. I think adding a `shouldCloseOnInteractOutside(element: HTMLElement): boolean` method to the `useOverlay` options could work, assuming you only need the event target and not any other event properties. I'd rather not expose the entire event object because `useInteractOutside` uses many types of events and the implementation could change. Wouldn't be great if people were relying on a specific event type and that changed from under them. TBH exposing the event from `onInteractOutside` was probably a mistake.

**Comment by chungwu** [comment]
Makes sense! https://github.com/adobe/react-spectrum/pull/913 :stuck_out_tongue:
