### ISSUE TITLE
useOverlay will dismiss a modal if the user left-clicks on the modal content's scrollbar and drags

### ISSUE THREAD

**Issue by stevecastaneda** [adobe/react-spectrum#896]
# 🐛 Bug Report 

Create a scrollable modal.  The modal will close unexpectedly when the user clicks + holds to drag on the scroll bar after releasing the click.  The user can scroll with the mouse wheel as expected.

## 🤔 Expected Behavior

The modal should not close when releasing the left mouse button after clicking a scroll bar and dragging.

## 😯 Current Behavior

The modal will close when the user clicks to drag on the scroll bar and releases the click.

## 🔦 Context

My users may often use the mouse to scroll a scrollable modal.  Doing so will close it unexpectedly.

## 💻 Code Sample

https://codesandbox.io/s/suspicious-sun-89uvk

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.1.0
| Browser          | Chrome, IE, Firefox
| Operating System | OSX, Windows

**Comment by dannify** [comment]
A code example would be great. We can also try to reproduce this .

**Comment by stevecastaneda** [comment]
I was able to get an interim fix in by turning `isDismissable` in `useOverlay` to `false` and then setting an onClick handler to the dimmer used behind the modal, but agree - I'll try to get that example up soon.

**Comment by stevecastaneda** [comment]
Working example added.  I wasn't able to reproduce it until I added in the Transitions, so I think this actually has to do with that vs. React Spectrum.  Can you confirm?

**Comment by snowystinger** [comment]
Hmmm we use Transitions as well, though not css Transitions https://github.com/adobe/react-spectrum/blob/c700898916bbd076bcc63e49d77c16d80623a8e7/packages/%40react-spectrum/overlays/src/Overlay.tsx#L47
I wonder if you can reproduce it with our Dialog component. I don't see any problems in our documentation https://react-spectrum.adobe.com/react-spectrum/DialogTrigger.html

**Comment by devongovett** [comment]
I think the issue is that the div outside the dialog is what's scrolling rather than the dialog itself – the `Transition` element has the `overflow-y-scroll` class on it. The `useOverlay` hook detects clicks outside the element its attached to, and in this case, clicking on the scrollbar fires an event on the div that's outside the dialog. If you made the dialog itself scrollable instead of the container, that should fix the issue since the event would fire on the dialog itself.

**Comment by stevecastaneda** [comment]
Thanks guys!  @devongovett I'll try re-arranging that tonight and see if that fixes the issue.  _Really_ appreciate the guidance.

**Comment by stevecastaneda** [comment]
I believe I have it.  Would you guys mind giving it a look over?

https://codesandbox.io/s/suspicious-sun-89uvk

**Comment by stevecastaneda** [comment]
Will close this in the meantime, confident this does not have to do with React Spectrum.

**Comment by devongovett** [comment]
Nice! Looks good to me. 😄
