### ISSUE TITLE
How to prevent Menu trigger auto close when scroll?

### ISSUE THREAD

**Issue by ladifire** [adobe/react-spectrum#900]
By default, the menu will close when we scroll page. But how to prevent it close when scroll?

**Comment by dannify** [comment]
Currently that's not really possible but that topic has been discussed within the team. There are a lot of questions around how we would handle keeping the correct position and general behavior. What use case do you have to keep a menu open when scrolling?

**Comment by ladifire** [comment]
Sometime I must have a dropdown with items that have action related to displayed UI, users must see other parts of UI to select corresponding menu items, but those parts a not on screen, so they must scroll UI to see them.

**Comment by dannify** [comment]
Sorry for the delay. That type of functionality can be quite complicated and as such is not something we are able to implement at the moment. It would be a future feature.

**Comment by maksimsemenov** [comment]
I have an issue with that behavior as well, and I think my use case is very common.

If I have a dropdown with a long list of items and I need to scroll through it, when I accidentally over-scroll (I scroll to the end of the list and continue scrolling), the dropdown closes itself, and now I have to open it again and scroll to the end but be very careful to not over-scroll. From a UX standpoint, it is very annoying.

To be honest, it is how props overlay works on react aria website, and it is very hard to scroll through it  to see what props are available:
![Screen Recording 2020-12-16 at 9 53 04 AM-2](https://user-images.githubusercontent.com/3608139/102367291-96ea3b80-3f87-11eb-84d4-41db7f4bd387.gif)

**Comment by devongovett** [comment]
This was fixed by #2926.
