### ISSUE TITLE
ActionButton should support is-selected

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#905]
# 🙋 Feature Request

According to https://opensource.adobe.com/spectrum-css/actionbutton.html there is an "is-selected" property which is not available through SpectrumActionButtonProps.

## 🤔 Expected Behavior

SpectrumActionButtonProps has a property "isSelected"

## 😯 Current Behavior

No property is available. Current work around is to use `UNSAFE_className="is-selected"` but that feels wrong

## 💁 Possible Solution

Add the property

## 🔦 Context

I'd like to have a toolbar-button who has a "toggle"-button behavior

**Comment by tomsontom** [comment]
To make it clear - I know that there's https://react-spectrum.adobe.com/react-spectrum/ActionGroup.html#selection but I have a single button who I'd like to show toggled on/off but using a Switch does not fit my UI need

**Comment by snowystinger** [comment]
Ah this is actually going to be a ToggleButton in the future most likely. In the meantime, you should be able to work around it using the ActionGroup as you pointed out.

**Comment by tomsontom** [comment]
folded into #915
