### ISSUE TITLE
ActionButton should support emphasized variant

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#907]
# 🙋 Feature Request

According to https://opensource.adobe.com/spectrum-css/actionbutton.html there are 2 variants of an action-button:
* normal (https://opensource.adobe.com/spectrum-css/actionbutton.html#standard)
* emphasized (https://opensource.adobe.com/spectrum-css/actionbutton.html#emphasized)

There's currently no way to define a single emphasized button beside using UNSAFE_className

## 🤔 Expected Behavior

Allow the user to define an optional variant-Property

## 😯 Current Behavior

No property is available and one has to use UNSAFE_className

## 💁 Possible Solution

Add a property `variant? : 'normal' | 'emphasized'`

**Comment by snowystinger** [comment]
You may be able to work around this using an ActionGroup.
We don't use variants for emphasized, we use the prop isEmphasized.
I'll check and see if there's some reason we only have it in the ActionGroup and not on individual ActionButtons

**Comment by tomsontom** [comment]
Let me know i‘m happy to contribute if there‘s no reason to not have it

**Comment by devongovett** [comment]
isEmphasized should be part of ToggleButton as well since it only applies when isSelected is also true.

**Comment by tomsontom** [comment]
I'm folding that one into #915
