### ISSUE TITLE
NumberField followup

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#908]
# 🙋 Feature Request

These are things left to do on NumberField

- [x] Story to demo changing currency

- [ ] Support VO

- [ ] Input mode should go to numberpad in mobile, how can we do this best? other numeral systems? (maybe use decimal?)
has correct keyboard layout in Android FF and Chrome
incorrect in iOS Safari, missing minus sign

Given everything that is wrong with mobile experience, maybe we consider something like this? https://spectrum-contributions.corp.adobe.com/page/mobile-numeric-keypad-beta/

- [x] Handle rounding, e.g. if user types in 3.4567 but only two decimals are shown, should we round the actual value emitted from onChange as well?

- [x] Focus styling fixes

Deferred:
- [ ] ON HOLD This will likely need an undo structure if we are formatting
- [ ] If group and decimal are both not “.”, and a period is typed, return NaN. (haven't figured out when this might be the case, deferring for now)

Question:
- [ ] Replace `UseNumberFieldStateProps` with types from react-types
Pretty sure there's nothing to do here, but maybe the wrong thing was recorded. I've compared it to other stately packages, I think it conforms.

**Comment by deebov** [comment]
> Input mode should go to numberpad in mobile, how can we do this best? other numeral systems?

I tried setting numberpad to both `numeric` and `decimal` on IOS. It however, shows the keyboard that you would for phone numbers or credit card numbers without the minus sign. Not having the minus sign could be a big downside I think

**Comment by snowystinger** [comment]
Agreed, that is not ideal if the user cannot make a negative number.
We may need to consider solutions similar to what we do with combobox (work in progress) making it modal for mobile and add a button to allow minus sign.

**Comment by snowystinger** [comment]
PR merged
