### ISSUE TITLE
Add a ToggleButton

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#915]
# 🙋 Feature Request

Feature requests #905 and #907 requested 2 new button properties and it was decided in #906 that the better way is to provide a completely new component named "ToggleButton"

**Comment by mischnic** [comment]
> Ok, here's what the API should look like:
> 
> ```tsx
> interface ToggleButtonProps extends ButtonProps {
>   /**  Whether the element should be selected (controlled). */
>   isSelected?: boolean,
>   /** Whether the element should be selected (uncontrolled). */
>   defaultSelected?: boolean,
>   /** Handler that is called when the element's selection state changes. */
>   onChange: (isSelected: boolean) => void
> }
> 
> interface SpectrumToggleButtonProps extends ToggleButtonProps, SpectrumActionButtonProps {
>    /** Whether the button should be displayed with an [emphasized style](https://spectrum.adobe.com/page/action-button/#Emphasis). */
>   isEmphasized?: boolean
> }
> ```
> 
> We'd also need a new hook in React Aria to implement the selection behavior. This hook should call `useButton` internally, and also add the `aria-pressed` prop to the `buttonProps` to indicate whether the toggle button is selected or not. In addition, it should handle `onPress` and toggle the selection state.
> 
> ```tsx
> interface AriaToggleButtonProps extends ToggleButtonProps, AriaBaseButtonProps {}
> 
> declare function useToggleButton(props: ToggleButtonProps): ButtonAria;
> ```
> 
> The state should be managed by the existing `useToggleState` hook, which is already used for checkboxes and switches, and will handle controlled/uncontrolled state and firing `onChange` appropriately.
> 

_Originally posted by @devongovett in https://github.com/adobe/react-spectrum/pull/906#issuecomment-670620796_

**Comment by tomsontom** [comment]
Something like that?

```typescript
export function useToggleButton(props: AriaToggleButtonProps, ref: RefObject<HTMLElement>): ButtonAria {
  const propsClone = {...props}
  if( propsClone.onPress ) {
    const originalPress = propsClone.onPress
    propsClone.onPress = e => {
      console.log("Hooked on press and forward")
      originalPress(e)
    }
  } else {
    console.log("Hooked on press")
  }
  return useButton(propsClone,ref);
}
```
Do i need a defensive copy or do I even have to simply modify the provided props instance?

**Comment by devongovett** [comment]
The `chain` function could take care of the chaining for you. You can do something like this:

```jsx
import {chain} from '@react-aria/utils';

useButton({
  ...props,
  onPress: chain(props.onPress, () => state.setSelected(!state.isSelected))
}, ref);
```

**Comment by tomsontom** [comment]
hm nice but then the event order is:
* onPress
* onChange

**Comment by tomsontom** [comment]
ah i can simply flip the arguments:

```typescript
export function useToggleButton(props: AriaToggleButtonProps, state: ToggleState, ref: RefObject<HTMLElement>): ButtonAria {
  return useButton({
    ...props,
    onPress: chain(() => state.setSelected(!state.isSelected), props.onPress)
  },ref);
}
```
