### ISSUE TITLE
Preventing focus on press

### ISSUE THREAD

**Issue by niklaskorz** [adobe/react-spectrum#918]
# ❔ Question

Is there any way to prevent a control using `useButton` or `usePress` to gain focus on interaction?

## 🔦 Context

In video players, a user usually doesn't expect controls to gain focus on interaction.
Instead, they should only gain focus when tabbing to the respective control.
This can be seen on YouTube, Vimeo, and Netflix, to name a few.

Edit to clarify: This is not simply about a control showing visual focus (I know react-aria already handles that), but also about a control taking over the space key, which is frequently used for toggling play/pause on videos.

## 💻 Code Sample

If this is not possible yet, I could imagine either a parameter `preventFocusOnPress` for the hooks themselves or a method `preventFocus()` for the press event would be useful.

**Comment by niklaskorz** [comment]
I have solved this for now by storing the previously focused element in the `onFocus` handler and giving it focus again in `onPressEnd`.

**Comment by snowystinger** [comment]
For components like the combobox, we move focus around to where it should be, https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/combobox/src/useComboBox.ts#L106
for a video player, do you need to keep the previously focused element? it sounds like it should always go to the player immediately if any of the controls are pressed in a non-keyboard way? and for keyboard interactions, focus should not be marshaled back at all, but should follow normal tabbing order? We have some methods for determining input modality https://github.com/adobe/react-spectrum/blob/93334701f3a5871b64efcc72174f394dad0eea1a/packages/%40react-aria/interactions/src/useFocusVisible.ts#L20

**Comment by niklaskorz** [comment]
Ah I have totally missed the modality! Your description fits perfectly, thanks, I will go this way. :)

**Comment by devongovett** [comment]
This also came up internally recently. I think a `preventFocusOnPress` option to `usePress` is probably a good thing to support. 👍
