### ISSUE TITLE
[React-Aria] Add `aria-checked` to `useRadio`

### ISSUE THREAD

**Issue by navin-moorthy** [adobe/react-spectrum#922]
# 🙋 Feature Request

Add `arai-checked=true` for the selected value and `aria-checked=false` to the rest of the `input`

As per "WAI-ARIA" standard - https://www.w3.org/TR/wai-aria-practices-1.1/examples/radio/radio-1/radio-1.html

![image](https://user-images.githubusercontent.com/39694575/89790247-48431580-db3f-11ea-8e81-84a8e8ef8b81.png)

**Comment by devongovett** [comment]
I don't believe this is necessary since we're using a native `<input type="radio">` and not a `<div role="radio">`. The native input element should already handle exposing the checked state to assistive technology, so adding the aria prop is unnecessary.

**Comment by navin-moorthy** [comment]
@devongovett for sharing this info.

I did checked Chakra & Reakit before raising this issue, Chakra did not have `aria-checked` but Reakit has it.

![image](https://user-images.githubusercontent.com/39694575/89866293-e9c47880-dbcc-11ea-86ed-6b9b6ed1174f.png)

So I thought better to raise an issue understand my concern.
Thanks 😄
