### ISSUE TITLE
Can't install Combobox

### ISSUE THREAD

**Issue by danublue** [adobe/react-spectrum#924]
# 📝 Feedback

Is there a way to install the combobox package? I know it is currently in alpha, but how can I install it?

## 🔦 Context

I am trying to use comboboxes in my project. But in the NPM package repository I cannot find it.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| [Package name]   |
| Browser          |
| Operating System |

**Comment by dannify** [comment]
Combobox is currently in progress and has not been released to npm as an alpha just yet. We are aiming to publish an alpha in the next month. Keep an eye on our releases page for updates - https://react-spectrum.adobe.com/releases/index.html

**Comment by danublue** [comment]
All right, thanks for this info!
