### ISSUE TITLE
Tooltip stories should have a delay by default

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#940]
# 🐛 Bug Report 

The stories for Tooltip mostly have their delay set to 0, we should be explicit about the stories we have with a delay of 0 vs default delay and prefer the default delay

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by solimant** [comment]
Working on it.
