### ISSUE TITLE
Tooltip should be placed slightly further from its target

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#941]
# 🐛 Bug Report 

There should be more space between target and tooltip as seen here https://spectrum.adobe.com/page/tooltip/

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by solimant** [comment]
Working on it.

**Comment by solimant** [comment]
Had an "offline" chat with @snowystinger - it doesn't seem to be always the case, like on the help icon:
![tooltip](https://spectrum.adobe.com/static/images1x/tooltip_behavior_delay@2x_32YINzQ3TFyry2Rurd6FMg_1570190087797.gif)

An alternative suggested approach is to:
> find a good default and a way to modify it.
