### ISSUE TITLE
[TypeScript] What's AriaButtonProps?

### ISSUE THREAD

**Issue by matamatanot** [adobe/react-spectrum#954]
# ❔ Question

Using `React.FC` type , `useButton` accept any object as a first argument.

## 🔦 Context

I was extending the props and I didn't get an error in IDE.

## 💻 Code Sample

**Not shown Error** 🤨
```
import { useRef } from "react";
import { useButton } from "@react-aria/button";
import type { AriaButtonProps } from "@react-types/button";

type Props = AriaButtonProps & {
  foo: string;
  bar: number;
};

export const Button: React.FC<Props> = (props) => {
  const ref = useRef(null);
  const { buttonProps } = useButton(props, ref);

  return (
    <button {...buttonProps} ref={ref}>
      {props.children}
    </button>
  );
};

```

**Show Error** 😌

```
export const Button: React.FC<Props> = (props) => {
  const ref = useRef(null);
  const { buttonProps } = useButton({ foo: "foo", bar: 0000 }, ref);

  return (
    <button {...buttonProps} ref={ref}>
      {props.children}
    </button>
  );
};

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.1.0 |
| Browser          | Chrome |
| Operating System | MacOS |

**Comment by snowystinger** [comment]
It would seem FC generic is not a recommended way to type if I'm understanding this correctly https://github.com/facebook/create-react-app/pull/8177
