### ISSUE TITLE
Custom color names

### ISSUE THREAD

**Issue by allforabit** [adobe/react-spectrum#957]
## 🙋 Feature Request

Really loving this project! From what I can see a good deal of the styling is quite generic and useable in any project. Obviously things like buttons and the likes would need to be implemented to fine tune the look and feel. Other components like "View", "Grid" and "Flex" would be very generally useful however.  The one area that would be nice to be able to customize a bit is the color palette.  I know you can change the actual colors in the theme but it's not easy to change the names of the colors.

## 🤔 Expected Behavior

It should be possible to change the names of the colors used in the palette.

## 😯 Current Behavior

It is currently quite hard coded in the typescript types, etc.

## 💁 Possible Solution

Allow color names to be passed as an option to the provider and make the typescript types generic

## 🔦 Context

I'm looking at using spectrum as the basis of general work and to customize the look and feel. I understand that this might be outside the scope of the project.

**Comment by devongovett** [comment]
This might be hard to support without basically changing all the TS definitions to open ended values like `string` instead of a list of color names, but if you have ideas, I'd love to hear them!

**Comment by allforabit** [comment]
Thanks for getting back to me. For now I'm just copying and pasting examples and components from react spectrum and am going to play around with it for a bit and see if I can come up with anything.

**Comment by dannify** [comment]
Closing as stale. Hopefully [React Aria Components](https://react-spectrum.adobe.com/react-aria/) can help here.
