### ISSUE TITLE
Support DialogTriggers from menus

### ISSUE THREAD

**Issue by jluyau** [adobe/react-spectrum#966]
# 🙋 Feature Request

Allow for the triggering of dialogs from a menu item. 

## 🤔 Expected Behavior

When using a menu, clicking a menu item should trigger a dialog.

## 😯 Current Behavior

Currently, clicking a menu item with a dialog trigger will flash the dialog (dialog trigger unmounts when menu closes on click)

## 💁 Possible Solution

Create a dialog container which will house the dialog (so the dialog doesnt unmount when the trigger unmounts).

## 🔦 Context

Need to trigger a dialog from a menu item.

## 🧢 Your Company/Team

Adobe/quarry

**Comment by stk26kakarla** [comment]
Is there a solution; can I have only Dialog and open it up with Menu Item?

**Comment by dannify** [comment]
A pull request has been submitted with a fix for this issue.
