### ISSUE TITLE
[Typescript][useModal] - incorrect useModal() return void ? 

### ISSUE THREAD

**Issue by matamatanot** [adobe/react-spectrum#970]
# 🐛 Bug Report 

`useModal()` return void. Is it incorrect?

## 🤔 Expected Behavior

return `ModalAria` interface?
https://github.com/adobe/react-spectrum/blob/586e5484d5fa854164c50651b2d6c8853113e9da/packages/%40react-aria/overlays/src/useModal.tsx#L137

## 😯 Current Behavior

return `void` type.

## 💻 Code Sample

`yarn add @react-aria/overlays`

`import { useModal } from "@react-aria/overlays";`

`let { modalProps } = useModal();`

![screenShot1](https://user-images.githubusercontent.com/39780486/90318753-95731d00-df6d-11ea-8c2b-09a01c5780b1.png)

![screenShot2](https://user-images.githubusercontent.com/39780486/90318758-9d32c180-df6d-11ea-9e64-bd7db0f25d87.png)

https://github.com/adobe/react-spectrum/blob/586e5484d5fa854164c50651b2d6c8853113e9da/packages/%40react-spectrum/overlays/src/Modal.tsx#L66

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.1.0 |
| Browser          | Chrome |
| Operating System | MacOS |

**Comment by devongovett** [comment]
This was a change recently to return a value, and it hasn't been released to npm yet.
