### ISSUE TITLE
[Typescript][useSwitch] - Is ref an optional argument?

### ISSUE THREAD

**Issue by matamatanot** [adobe/react-spectrum#971]
# 🐛 Bug Report 
It may be a Documentation problem.

## 🤔 Expected Behavior

Fix ref is optional or Fix useSwitch documentation.

## 😯 Current Behavior

ref is required. But, the documentation does not do so.

## 🔦 Context

Inside code, ref is required
https://github.com/adobe/react-spectrum/blob/586e5484d5fa854164c50651b2d6c8853113e9da/packages/%40react-aria/switch/src/useSwitch.ts#L30

Inside Docs, ref is optional.
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/switch/docs/useSwitch.mdx
`let {inputProps} = useSwitch(props, state);`

## 💻 Code Sample

![screenShot](https://user-images.githubusercontent.com/39780486/90320277-c4dc5680-df7a-11ea-8ff7-daeb3e0a6c23.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |3.1.0|
| Browser          |Chrome |
| Operating System | MacOS |

**Comment by devongovett** [comment]
It is required. That appears to be a bug in the docs.

**Comment by andrew-t-james** [comment]
@devongovett I can take this if it's still open.

**Comment by devongovett** [comment]
@andrew-t-james thanks, go for it!
