### ISSUE TITLE
Implement Color object in react-stately

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#973]
# 🙋 Feature Request

In preparation for building out various color picker components, we need a base representation of a `Color` value that will be used by all of these components. Colors can be represented in many different ways, e.g. hex (`#abcdef`), RGB strings `rgb(25, 50, 75)`, HSL, HSB/HSV, CMYK, Lab, etc. These are all representations of the same value, and it's possible to convert between them for display purposes. Therefore, representing colors as strings doesn't really make sense, and it would be useful to have a standard `Color` value that is agnostic to the format it is eventually converted to.

## 💁 Possible Solution

There are various libraries out there which include color parsing, manipulation, and formatting capabilities. For example [tinycolor](https://github.com/bgrins/TinyColor), [color](https://github.com/Qix-/color), [color-convert](https://github.com/Qix-/color-convert), and [color-js](https://github.com/brehaut/color-js). Unfortunately, these tend to be quite large and have many more features than we need. In addition, we'd like for React Spectrum's color representation to be agnostic to libraries even if we do use one so that we hide that implementation detail and can change it out later.

The API for the `Color` object should look like the following.

```tsx
/** A list of supported color formats. */
type ColorFormat = 'hex' | 'hexa' | 'rgb' | 'rgba' | 'hsl' | 'hsla' | 'hsb' | 'hsba';

/** A list of color channels. */
type ColorChannel = 'hue' | 'saturation' | 'brightness' | 'lightness' | 'red' | 'green' | 'blue' | 'alpha';

interface Color {
  /** Constructs a color from a string value */
  constructor(value: string),

  /** The color format of the input value. */
  readonly format: ColorFormat;

  /** Converts the color to a string in the given format */
  toString(format: ColorFormat): string,

  /** Converts the color to the given color format, and returns a new Color object */
  toFormat(format: ColorFormat): Color,
  
  /** Gets the minimum numeric value for a given channel, e.g. for a slider. */
  getChannelMin(channel: ColorChannel): number,

  /** Gets the maximum numeric value for a given channel, e.g. for a slider. */
  getChannelMax(channel: ColorChannel): number,

  /** Gets the step value for a given channel, e.g. for a slider. */
  getChannelStep(channel: ColorChannel): number,

  /** 
   * Gets the numeric value for a given channel.
   * Throws an error if the channel is unsupported in the current color format.
   */
  getChannelValue(channel: ColorChannel): number,

  /** 
   * Sets the numeric value for a given channel, and returns a new Color object.
   * Throws an error if the channel is unsupported in the current color format.
   */
  setChannelValue(channel: ColorChannel, value: number): Color,

  /** Returns a localized string name for the current color. */
  getName(locale: string): string
}
```

Color objects accept a string value which is parsed into an internal object structure. This can then be converted to other color formats. Color objects have a property which stores the input color format. This is so that when channel values are requested, an error can be thrown if the channel is not in the current format, and so that we can disambiguate between channels with the same name across multiple formats. For example, the saturation value is different between HSL and HSB, so we'll need to know which format we're in to do the proper conversions.

Users can convert between formats by calling `toFormat`, which returns a new `Color` object in the requested format, or by calling `toString`, which does the conversion and also converts the value to a color string. Color objects are immutable, so any time a method is called that changes something about the color, a new `Color` object is returned rather than mutating the existing one.

Internally, we could implement a few color models, e.g. RGB, HSL, and HSB, with conversion functions to map between them. There are fewer color models than formats. For example, `hex` and `rgb` are both represented as RGB, and `rgb` and `rgba` could be represented by the same model. A `Color` object could have an internal color value object that provides the implementation for these models, including conversions to other models. For example, the `RGBColor` implementation could have `toHSL` and `toHSB` methods to convert to `HSLColor` and `HSBColor` instances. We can copy the conversion functions from the libraries linked above to implement this.

This should be implemented in the `@react-stately/color` package.

We don't need to implement all of this right away, for example we could start with only supporting hex and RGB, and with only the methods we need. This API is mainly to get a sense for what we'll need eventually.

## 🧢 Your Company/Team

RSP

**Comment by DennisSmolek** [comment]
I like the idea of wrapping an existing library for at least the initial version.
I have to caution the logic of creating "Yet Another Color Library" as we did the same thing at my (recently closed) company.
As use cases and application demands grow you will be left refactoring or attempting to overcome limitations that previous libraries had already resolved..

As I'm now refactoring/porting to React I was planning on starting with tinycolor and implementing a very similar interface to the one you described. 

I would also bring in [isLight()](https://github.com/bgrins/TinyColor#islight) and [isDark()](https://github.com/bgrins/TinyColor#isdark) which for editor UI's is incredibly useful for things like X/Y position, labels, etc. 

And as a major goal of the spectrum project is accessibility I would also consider [getLuminance()](https://github.com/bgrins/TinyColor#getluminance) 

Another project I'd take a look at is [Pickr](https://github.com/Simonwep/pickr)
The whole library is for it's own picker but the color modifying is significantly smaller/simpler than some of the other implementations. He generally converts all colors to HSVA and then outputs/modifies from that object.

Another thing to consider would be modularizing the models/uses for example "CMYK" which would be very useful for any type of print or design from print application, but not very useful for most others. Color names (string conversion), gradients, extended logic, etc. could either be imported in a `Color-extended` type way or as module imports. This would help keep the initial codebase small while allowing later features and extensions.

**Question**
As you've already written a draft outline is this something you are going to tackle immediately or is this something you are open/interested in someone contributing? 

As I mentioned, I was already planning on doing something like this, and decided today to leverage Spectrum as the UI component base of my new application. I'm actively looking for Open Source projects to contribute to so this seems like it would be a good fit.

[Here's a quick little video](https://www.youtube.com/watch?v=vfiNLddj0g8) of our material color-picker working back in 2016

**Comment by devongovett** [comment]
Thanks @DennisSmolek! I've put together a very basic setup for what I think it could look like here: https://github.com/adobe/react-spectrum/pull/979.

> I have to caution the logic of creating "Yet Another Color Library" as we did the same thing at my (recently closed) company.

Totally valid concern. The main issue I see is that many of these libraries have a lot of features we don't need. We mainly need basic color conversions. If such a library exists that is tree-shakeable so we only pull in the functions we need, that would be great. Otherwise, it doesn't seem like too much work to copy/paste the ones we need for our color picker components.

> I would also bring in isLight() and isDark() which for editor UI's is incredibly useful for things like X/Y position, labels, etc. And as a major goal of the spectrum project is accessibility I would also consider getLuminance()

Yeah but I don't think I want to get into supporting too much functionality out of the box that the color picker components themselves don't need. Perhaps these types of functions could be implemented as separate functions outside the core `Color` object such that they can be tree-shaken when unused by an application?

> Another thing to consider would be modularizing the models/uses for example "CMYK" which would be very useful for any type of print or design from print application, but not very useful for most others.

In the basic setup I did, the models are implemented in separate classes, so it should be fairly easy to add new ones if needed. I suppose we could make it extensible via a registration mechanism for new models, but I don't want to get too complicated too quickly. Let's see how it goes first.

> As you've already written a draft outline is this something you are going to tackle immediately or is this something you are open/interested in someone contributing?

We are starting to work on it, but will be tackling the basics first. If you'd like to help us implement some of the missing functionality for color conversions, we'd love it! We're starting with a hex color field (see #974), but will be speccing the other color picker components (e.g. color sliders, areas, wheels, etc.) very soon, and would love some help from contributors on those as well. Let me know what you have time to work on! 😄

**Comment by allforabit** [comment]
Could I suggest https://github.com/thi-ng/umbrella/tree/develop/packages/color Very minimal and tree shakeable.

**Comment by NateBaldwinDesign** [comment]
I'm curious about this aspect of the API:
```
/** A list of color channels. */
type ColorChannel = 'hue' | 'saturation' | 'brightness' | 'lightness' | 'red' | 'green' | 'blue' | 'alpha';
```
Would this enumeration simply be added to as additional color models and formats are supported? For example, `HSV` is synonymous with `HSB` but if you support both outputs there would be channel names `value` and `brightness` that are the equivalent (same value would be returned). However, the term `lightness` spans a number of models with very different values being returned (for example, HSL vs LCH lightnesses are very different). 

Another interesting example would be when/if you support Lab colorspace. The `a` and `b` channels reference "Redness / greenness" and "Blueness / yellowness". In this case, specifying the color channel by it's individual character representation may be more reasonable. 
For example, let's say I have a color `lab(49,9,-67)`
If I want to know the `b` value, it would be strange to write `color. getChannelValue('blueYellow')`. It would be preferable in my opinion to specify the channel as a single character, ie `color.getChannelValue('b')`

The use of strings for these channel names also could be potentially confusing as the strings are closer to terms people use to _describe_ color, rather than the actual channel -- such that a user could easily mis-match terminology when they want the *saturation level of a color* that is defined in `lch` color space (which the correct term would then be "chroma"). Tying directly to the specific abbreviated character used in the colorspace name could make it more intuitive -- "I want the `c` value of color `lch(100, 97, 45)`

**Comment by devongovett** [comment]
Yeah that's right, we'd add more channels as we implement more models/formats. However, only the channels that are part of the current color format would be supported. For example, if you have a color in RGB format, then asking for the hue channel would throw an error. You'd need to convert this to an HSB/HSV/HSL color first before asking for that channel.

You're right that a channel name can map to different values depending on the color model. For example, HSL and HSB/HSV both have a "saturation" channel, but they will be different values. Same with LCH as you mentioned. This would also be true if we switched to single letter names for channel names too (the l or the s would be different values depending on the model). 

That's interesting feedback though - I was thinking it would be clearer to use full names in case the single letters mapped to different names (e.g. "brightness" vs "blue"). I could see either way though... 🤔

**Comment by snowystinger** [comment]
This has been merged https://github.com/adobe/react-spectrum/pull/979 and updated so now it is this: https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/color/src/Color.ts
