### ISSUE TITLE
Implement HexColorField component

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#974]
# 🙋 Feature Request

Implement a `HexColorField` component, which is a textfield that is specifically designed for editing a hex color value. This is an important component of any color picker. A hex color field works similarly to a number field, in that it restricts its input to only valid hex characters, and can be incremented and decremented using the keyboard. In addition, it always formats its value with a leading `#` character, and parses the input to a `Color` value (see #973).

## 💁 Possible Solution

`HexColorField` should use the `Color` object as defined in #973 for its value. It should accept string input, but always emit a `Color` to its `onChange` event handler. The API should look like this:

```tsx
interface HexColorFieldProps extends InputBase, Validation, FocusableProps, TextInputBase, LabelableProps {
  /** Current color value (controlled). */
  value?: string | Color,
  /** Default color value (uncontrolled). */
  defaultValue?: string | Color,
  /** Handler that is called when the color changes. */
  onChange?: (color: Color) => void,
  /** Amount to increment color by in hex space when arrow keys are pressed (default 1). */
  step?: number
}

interface AriaHexColorFieldProps extends HexColorFieldProps, AriaLabelingProps, FocusableDOMProps, TextInputDOMProps, AriaValidationProps {}

interface SpectrumHexColorFieldProps extends AriaHexColorFieldProps, SpectrumLabelableProps, StyleProps {
  isQuiet?: boolean
}
```

Since they are quite similar, we can reuse parts of the implementation of `NumberField` for `HexColorField`, in particular the react-aria part. This will provide the increment/decrement behavior and some of the accessibility. The state management is different, however, because we're dealing with `Color` values and not numbers here, and also because the formatting and parsing of hex colors is not localized like number parsing/formatting are. For this reason, I'd suggest implementing `useHexColorFieldState` from scratch rather than using `useNumberFieldState`, but returning a compatible interface. This way we can reuse `useNumberField` in react-aria internally to `useHexColorField`.

```tsx
interface HexColorFieldState extends NumberFieldState {
  colorValue: Color,
  setColorValue(color: Color) => void
}

declare function useHexColorFieldState(props: HexColorFieldProps): HexColorFieldState;

interface HexColorFieldAria {
  labelProps: LabelHTMLAttributes<HTMLLabelElement>,
  inputFieldProps: HTMLAttributes<HTMLInputElement>
}

declare function useHexColorField(props: AriaHexColorFieldProps, state: HexColorFieldState): HexColorFieldAria;
```

Note that the hex color field does not have stepper buttons like a number field, so the `numberFieldProps`, `incrementButtonProps`, and `decrementButtonProps` from `useNumberField` are discarded in `useHexColorField`.

### Expected behavior

* Color is formatted as a hex value, e.g. `#ABCDEF`. Leading `#` and upper case.
* User can focus and type valid hex characters, with or without the leading `#` and in upper/lower case.
* `onChange` is fired with a parsed `Color` value as the user types, when the value becomes valid. Both short and long hex values should be supported, for example `#abc` is the same as `#aabbcc`. For example, `onChange` would not be fired for `ab` but would be fired for `abc`.
* On blur, the text in the textfield should be re-formatted so that the leading `#` is there and the characters are upper case.

## 🧢 Your Company/Team

RSP

**Comment by emircado** [comment]
Hi @devongovett! A question for `HexColorFieldState`

```ts
interface HexColorFieldState extends NumberFieldState {
  colorValue: Color,
  setColorValue(color: Color) => void
}
```

`NumberFieldState` already has `value` and `setValue` and `HexColorFieldState` is adding `colorValue` and `setColorValue` on top of it. Can you confirm if we're only meant to use one of these pairs? 

I imagine we don't want `setValue` and `value` available in this component 'coz they're meant for numbers, unless we change them to accept colors instead and not define `colorValue` and `setColorValue`
```ts
interface HexColorFieldState extends NumberFieldState {
  value: Color,
  setValue(color: Color) => void
}
```

**Comment by emircado** [comment]
Under expected behavior
> On blur, the text in the textfield should be re-formatted so that the leading # is there and the characters are upper case.
If the user inputs a 3-character hex, should it change to six characters once reformatted?
