### ISSUE TITLE
Is there a release schedule?

### ISSUE THREAD

**Issue by shrugs** [adobe/react-spectrum#978]
# 📝 Feedback

Is there a defined release schedule for react-spectrum / react-aria / react-stately?
The last release was nearly a month ago, but there have been a bunch of useful additions and bugfixes.

**Comment by dannify** [comment]
Hey @shrugs,
Good question. We haven't quite worked out a consistent release schedule yet as we are still ironing out the process. However, we are in the middle of prepping the latest release. It should be out this week.

**Comment by dannify** [comment]
Release is out! https://react-spectrum.adobe.com/releases/2020-08-18.html

**Comment by shrugs** [comment]
awesome! 🎉  updating my apps now

feel free to close this issue or use it as a way to track the addition of a more defined release schedule, whatever the maintainers would like
