### ISSUE TITLE
Missing overflow Y, X props on View components

### ISSUE THREAD

**Issue by ivanjeremic** [adobe/react-spectrum#981]
Sometimes we want only `overflow-x` but hide `oveflow-y` the props provided in the View component do not give us props like `overflowY` or `overflowX` we would need them to be able to do this kind of custom design.

**Comment by LFDanLu** [comment]
@ivanjeremic The View component supports the `overflow` property to which you can provide up to two keywords. If two are provided the first keyword would apply to `overflow-x` and the second would apply to `overflow-y`. Lemme know if that is sufficient for your use case.

e.g. `<View overflow="visible hidden">` would yield a View with `overflow-x: visible` and `overflow-y: hidden`

**Comment by dannify** [comment]
Going to close this for now. Please reopen if this does not answer your question.
