### ISSUE TITLE
Allow developer to override default choice for popup/tray in Picker

### ISSUE THREAD

**Issue by michayou** [adobe/react-spectrum#989]
# 🙋 Feature Request

There should be a prop for Picker to allow the developer to decide if it should display its items in a tray or popup.

## 😯 Current Behavior

Currently, as can be seen in Picker.tsx, the choice is hardcoded based on the window width, but the developer might want to make that choice based on a different set of criteria.

## 💁 Possible Solution

Have a new boolean prop that -- if it exists -- overwrites the default decision in Picker.  If the prop does not exist, then use the defailt. 

## 🔦 Context

I am writing an excel plugin that is on windows, but its window width makes Spectrum think it is on a phone.  I want a popup list of items for my Picker, but it is appearing as a tray.

## 🧢 Your Company/Team

Adobe/Digital Experience for Report builder 2.0

What I'm seeing (on my computer NOT phone): 
![what I have](https://user-images.githubusercontent.com/69984832/90809300-428fc180-e2ef-11ea-8a2a-c2045d779eba.png)

What I want:
![what I want](https://user-images.githubusercontent.com/69984832/90809302-43285800-e2ef-11ea-90ca-09e7497cd7ec.png)

**Comment by dannify** [comment]
For now we have changed this behavior to use screen size instead of window size. Thanks @michayou
