### ISSUE TITLE
Picker opens items in a tray on a computer NOT phone

### ISSUE THREAD

**Issue by michayou** [adobe/react-spectrum#990]
# 🐛 Bug Report 

When clicking on a picker on my computer, it opens the items in a tray instead of as a popup.  This is due to how Picker decides if you are on a phone or computer.

## 🤔 Expected Behavior

It should open as a tray on phone, and as a popup on a computer.

## 😯 Current Behavior

I am using Picker in a microsoft excel plugin which is sideloaded into a strip on the right of the window.  It has a limited maximum width similar to a cell phone, but it is on a computer (in my case a Mac).  Because of how Picker tests for phone, it is coming up with the wrong solution.

## 💁 Possible Solution

Instead of testing the window max-width, test the screen width instead.  `window.screen.width` has been suggested 

## 🌍 Your Environment

Excel plugin on a Mac.  But I'd expect it to happen for other excel plugins too.

## 🧢 Your Company/Team

Adobe/Digital Experience for Report builder 2.0

What I'm seeing:
![what I have](https://user-images.githubusercontent.com/69984832/90809930-36f0ca80-e2f0-11ea-9b0c-c27cdccc7256.png)

What I want:
![what I want](https://user-images.githubusercontent.com/69984832/90809932-36f0ca80-e2f0-11ea-8eb9-f35095af5352.png)

**Comment by mischnic** [comment]
Looks like this is fixed by https://github.com/adobe/react-spectrum/pull/1001?
