### ISSUE TITLE
Allow specifying selector for OverlayContainer

### ISSUE THREAD

**Issue by TLadd** [adobe/react-spectrum#991]
# 🙋 Feature Request

I want to be able to control where OverlayContainer renders the modals. Currently, [ReactDOM.createPortal is called with document.body](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/overlays/src/useModal.tsx#L118) without the option to override it.

## 🤔 Expected Behavior

Allow passing in the createPortal container argument as a prop.

## 😯 Current Behavior

There is no way to override the container argument.

## 💁 Possible Solution

I think something like this should work?

```typescript
interface OverlayContainerProps extends ModalProviderProps {
  containerSelector?: () => HTMLElement
}

export function OverlayContainer(props: OverlayContainerProps): React.ReactPortal {
  let {containerSelector = () => document.body, ...rest} = props;
  let contents = <OverlayProvider {...rest} />;
  return ReactDOM.createPortal(contents, containerSelector());
}
```

I'm not sure if any of the other hooks are making any assumptions about where the modals are rendered and would also need modification. For my particular use case, just this change seems to work.

Happy to contribute if this is okay!

## 🔦 Context

I'm adding a modal to an application within a shadow DOM. As such, I need to be able to also render the modal within that same shadow DOM for it to render correctly. In order to have the modal render where I want it, I need to pass something like `document.querySelector("#shoadw-app-root").shadowRoot.querySelector("#react-aria-overlay-root")` to createPortal

**Comment by devongovett** [comment]
>  Is it equivalent to saying that an OverlayProvider cannot be nested within another ModalProvider or is that overly restrictive? If it is correct, then it would be easy to check if useModalProvider returns null or not in OverlayProvider.

Yes, that's correct, but checking if it's inside a context won't work because context flows through portals. We need to check whether it's inside the parent provider DOM wise, not context wise.

**Comment by nouman91** [comment]
Whats the latest on this? We have one area where we want to control the rendering of dialogs.
