### ISSUE TITLE
When spectrum for angular will be open-sourced?

### ISSUE THREAD

**Issue by lordsfantasy** [adobe/react-spectrum#995]
Any plans of making spectrum for angular?

**Comment by devongovett** [comment]
We don't currently have any specific plans for this, but we are interested in potentially looking into supporting React Aria in other frameworks generally. This could potentially work by shimming the Hooks API, e.g. I've started experimenting with this in [svelte](https://github.com/devongovett/svelte-hooks). If that's something you're interested in trying out, let us know! Gonna close this for now.
