### ISSUE TITLE
How to use useListBox with virtualizer (react-window/react-virtualized)

### ISSUE THREAD

**Issue by deebov** [adobe/react-spectrum#998]
# ❔ Question

I wanted use useListbox with some kind of virtualizer. I saw the implementation of react-aria's own virtualizer with listbox. However, there're some issues:

1) It does not use semantic HTML tags (ul, li)
2) Not as performant as other virtualizers (react-window/react-virtualized) out there
3) Hard to understand what's going on without a guide

Is it possible to use listbox with react-window/react-virualizer or whether the current API allows us to do so? If yes, can you give some directions on how to achieve that?

## 🔦 Context

I want to create a long list (100 items min.) with sections.

**Comment by deebov** [comment]
@devongovett thanks for clarifying 

2. I did not do any benchmarking but the result was significantly visible. e.g. if you scroll fast you can see a blank list for 100ms-600ms whereas with other virtualizers it's almost unnoticeable

**Comment by ktabors** [comment]
We are continuing to work on performance. Please let us know how your use of a different virtualizer goes. And please take a look at the documentation when this comment is released.
